### ISSUE TITLE
Branch 3.0 still uses OpenAPIParser instead of OpenAPIV3Parser

### ISSUE THREAD

**Issue by lemvik** [swagger-api/swagger-codegen#10018]
##### Description

https://github.com/swagger-api/swagger-codegen/blob/29f4107fe812c155ebacdb7d32dfef866e11a568/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/config/CodegenConfigurator.java#L13
The codegen configuration still tries to parse given OpenAPI schema using v2 parser and fails, producing an error complaining "missing openAPI input!"

##### Swagger-codegen version

3.0.16

##### Command line used for generation

```bash
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:latest generate -i /local/apis/product-search-service-api.json -o /local/src/app/services/generated -l typescript-angular 
```

##### Steps to reproduce

Run the generator on a openAPI 3.0 schema file.

##### Suggest a fix/enhancement

Add `io.swagger.parser.v3` dependency and use `OpenAPIV3Parser` from there.

**Comment by frantuma** [comment]
the mentioned [OpenAPIParser](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/OpenAPIParser.java) is not the v2 parser, it is part of v3, and delegates parsing to the `OpenAPIV3Parser` and its extensions (by default a converter v2->v3).

I would think the problem could be related to an error in the input file, or a typo maybe, can you check that and close ticket if this is the case?

running e.g.
```
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:latest generate -i https://petstore3.swagger.io/api/v3/openapi.json -o /local/src/app/services/generated -l typescript-angular
```
seems not to raise any error

**Comment by lemvik** [comment]
Okay, my bad about the guess.
The line you've provided indeed does work, but the spec I'm working with fails with 
```
08:35:17.298 [Thread-1] DEBUG io.swagger.codegen.v3.config.CodegenConfigurator - getClientOptInput - parsed inputSpecURL /local/apis/<redacted>.json
Exception in thread "Thread-1" java.lang.RuntimeException: missing OpenAPI input!
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:772)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:360)
	at java.lang.Thread.run(Thread.java:748)
```
even tough schema is reported to be valid by [openapi-spec-validator](https://github.com/p1c2u/openapi-spec-validator).
As far as I can tell this is because the `OpenAPIParser` returns null on parse/validation failure (?) but I have little clue as to why (running with verbose output doesn't help unfortunately).

I'll try to check schema with other tools but this issue report is just wrong, so I'll close it.
