### ISSUE TITLE
[Java] javax.xml.bind.DatatypeConverter doesn't exist for android

### ISSUE THREAD

**Issue by reginald-louis** [swagger-api/swagger-codegen#1002]
This class doesn't exist on android. I don't know if there's an alternative. I will check, but just to let you know.

**Comment by reginald-louis** [comment]
The import is used in the file `HttpBasicAuth.java` and for this function

```
  @Override
  public void applyToParams(Map<String, String> queryParams, Map<String, String> headerParams) {
    String str = (username == null ? "" : username) + ":" + (password == null ? "" : password);
    try {
      headerParams.put("Authorization", "Basic " + DatatypeConverter.printBase64Binary(str.getBytes("UTF-8")));
    } catch (UnsupportedEncodingException e) {
      throw new RuntimeException(e);
    }
  }
```

It's for converting byte to base64. The equivalent in android is in `android.util.Base64.encodeToString`. I can always fork and patch for my own need, but maybe we should think of a compatible way!

Thx!

**Comment by xhh** [comment]
The code generated by Java client generator (the java template) is meant to be used in JVM environment, not other environments like Android.
There is a android-java template for Android, which has not implemented HTTP basic auth yet.

**Comment by reginald-louis** [comment]
Ok thx! The android generation work!

On Wed, Jul 22, 2015 at 11:07 PM, Xu Hui Hui <notifications@github.com>
wrote:

> The code generated by Java client generator (the java template) is meant
> to be used in JVM environment, not other environments like Android.
> There is a android-java template for Android, which has not implemented
> HTTP basic auth yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-codegen/issues/1002#issuecomment-123946964>
> .
>



-- 
/RL
