### ISSUE TITLE
Wiki link to PetStore sample on GH is broken

### ISSUE THREAD

**Issue by admackin** [swagger-api/swagger-codegen#1003]
The wiki page at https://github.com/swagger-api/swagger-spec/wiki points to the PetStore sample for swagger-codegen annotations. However, the provided URL is https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/PetApi.java which gives a 404. Somewhat concerted digging has not shown me the correct link either

**Comment by admackin** [comment]
Sorry wrong project I suck

**Comment by wing328** [comment]
@admackin np :)

you can find the samples under `https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples` (note that this is the develop_2.0 branch, which contains the latest bug fixes and enhancements)

**Comment by admackin** [comment]
Ah, interesting - I ended up updating the wiki page in question, but I pointed it to https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs/src/main/java/io/swagger/sample/resource/PetStoreResource.java

**Comment by wing328** [comment]
@admackin that will do as well. Thanks for updating the wiki page.
