### ISSUE TITLE
[FLUTTER] Creating swagger-codegen for Flutter with the Flutter dio HTTP package

### ISSUE THREAD

**Issue by fzyzcjy** [swagger-api/swagger-codegen#10032]
(not an issue) Hi, thanks for the library! Currently the swagger-codegen, a popular tool to generate API clients from specs, only generates dart code without the dio library (also without things like json_serialize). Thus, I am going to implement it. Is it OK? (Or is there already one hidden in the corner...?)

**Comment by HugoMario** [comment]
hi @fzyzcjy , sorry for delay. and yes. it's ok, ping me if you need help wtih PR

**Comment by fzyzcjy** [comment]
Sorry I have solved my problem by doing some hacks... So maybe I do not have time to do that
