### ISSUE TITLE
[TYPESCRIPT-ANGULAR] package.json with invalid @angular/http for Angular 9

### ISSUE THREAD

**Issue by prochemo** [swagger-api/swagger-codegen#10040]
##### Description

when implementing a code generation of typescript-angular for angular 9( 8+), the package.json generated defines in peerDependencies and devDependencies @angular/http^9.0.1 
this declaration in invalid in angular 9 since it should used @angular/common/http. 

the swagger codegen is called from the maven plugin. 

the issue came from [package.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/package.mustache) 

```bash
...
https://github.com/request/request/issues/3142
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/http@^9.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

##### Swagger-codegen version

used on swagger-codegen version 2.4.12 

##### Swagger declaration file content or url

N/A

##### Command line used for generation

```xml
<pluginExecutor>
									<plugin>
										<groupId>io.swagger</groupId>
										<artifactId>swagger-codegen-maven-plugin</artifactId>
										<version>2.4.12</version>
									</plugin>
									<goal>generate</goal>
									<configuration>
										<inputSpec>${project.basedir}/../${project.parent.artifactId}-interface/apis/@item@/api.yaml</inputSpec>
										<output>${project.build.directory}/generated-sources/client-ts/</output>
										<language>typescript-angular</language>
										<additionalProperties>
											<additionalProperty>usePromise=true</additionalProperty>
											<additionalProperty>useES6=true</additionalProperty>
											<additionalProperty>npmName=@sct-services/client-api</additionalProperty>
											<additionalProperty>ngVersion=9.0.1</additionalProperty>

										</additionalProperties>
									</configuration>
								</pluginExecutor>
```

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

the issue came from [package.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/package.mustache) 

package.json file extract
```json 
{
  "name": "@sct-services/client-api",
  "version": "1.0.0",
  "description": "swagger client for @sct-services/client-api",
  "author": "Swagger Codegen Contributors",
  "keywords": [
    "swagger-client"
  ],
  "license": "Unlicense",
  "scripts": {
    "build": "ng-packagr -p ng-package.json"
  },
  "peerDependencies": {
    "@angular/core": "^9.0.1",
    "@angular/http": "^9.0.1",
    "@angular/common": "^9.0.1",
    "@angular/compiler": "^9.0.1",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "~6.3.3",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^9.0.1",
    "@angular/core": "^9.0.1",
    "@angular/http": "^9.0.1",
    "@angular/common": "^9.0.1",
    "@angular/compiler": "^9.0.1",
    "@angular/platform-browser": "^9.0.1",
    "ng-packagr": "5.3.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "~6.3.3",
    "zone.js": "^0.7.6",
    "typescript": ">=2.1.5 <2.8"
  }
}
```
I think it should be possible to provide the fixed mustache folder with 
<templateDirectory>../_mustache</templateDirectory>
as described by https://github.com/swagger-api/swagger-codegen/issues/8179

Is there other way or a better configuration to define ?
Thanks 

Best Regards. 

```

**Comment by Nirostar** [comment]
Same problem. You can use angular 7.0.0 as a kind of Workaround.

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen/pull/11100
