### ISSUE TITLE
Missing dependency in pom.xml on Java 11

### ISSUE THREAD

**Issue by kibertoad** [swagger-api/swagger-codegen#10042]
##### Description

Default pom.xml generated for Java project fails on Java 11 because `javax.annotation` is no longer bundled with the language.

##### Swagger-codegen version

2.4.12

##### Suggest a fix/enhancement

It shouldn't cause any issues if `javax.annotation` is included as a dependency by default in pom.xml generated for Java, especially since Java 8 was deprecated for commercial use, so supporting Java 11 out-of-the-box sounds like a good idea.

If we want to be super-explicit and conservative,  dependency block can be included in pom.xml.

If either of options are approved, I can prepare a PR for that.

**Comment by gshel** [comment]
I've run into this as an issue and would greatly appreciate a fix :)

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen/pull/11132

**Comment by HugoMario** [comment]
to use java 11 we need to use the option:
```
--additional-properties java11=true
```
