### ISSUE TITLE
editor.swagger.io generates duplicate C# enums structures when they should be references

### ISSUE THREAD

**Issue by Camios** [swagger-api/swagger-codegen#10059]
##### Description

When generating from this https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.json
Swagger correctly creates Enums eg. (BankingProductCategory), but incorrectly creates nested Enums instead of references (e.g. BankingProductsV2.BankingProductCategory and others).

##### Swagger-codegen version

editor.swagger.io on 21/Feb/2020

##### Swagger declaration file content or url

https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.json

##### Command line used for generation

Generate Server aspnetcore

##### Steps to reproduce

editor.swagger.io
Provide url
Generate Server aspnetcore

##### Suggest a fix/enhancement

Don't generate duplicate nested enums

**Comment by HugoMario** [comment]
thanks @Camios , will take a look on this

**Comment by Smootium** [comment]
FYI: This also occurs / is still occurring with OAS 3 generator (ver 3.0.18) (https://generator3.swagger.io/index.html)

**Comment by HugoMario** [comment]
issue is fixed by https://github.com/swagger-api/swagger-codegen/pull/10197
version 3.0.x fixed by https://github.com/swagger-api/swagger-codegen-generators/pull/657

thanks guy for reporting this
