### ISSUE TITLE
Requesting a release of swagger-codegen

### ISSUE THREAD

**Issue by michaeldavis-wf** [swagger-api/swagger-codegen#10054]
##### Description

Would it be possible to request a release of swagger-codegen and swagger-codegen-generators? I would love to be able to consume some of the recent code.

Thanks!

**Comment by michaeldavis-wf** [comment]
@frantuma

**Comment by webron** [comment]
Thanks for filing the issue. You can always use the SNAPSHOT version if you want to try out bleeding edge. Regardless, a new release of the codegen is coming in the next few days.
