### ISSUE TITLE
swagger-codegen generates some invalid code

### ISSUE THREAD

**Issue by martijintro** [swagger-api/swagger-codegen#10053]
##### Description

swagger-codegen generates some invalid code

##### Swagger-codegen version

Version: swagger-codegen-cli-3.0.16

##### Command line used for generation

`java -jar swagger-codegen-cli-3.0.16.jar generate -i swagger.json -l spring`

##### Steps to reproduce

Download the REST API definitiv from payment provider "SumUp", save it and use the command above!

https://developer.sumup.com/e3c10586-a75e-47f4-bb48-3861706a3d83

##### Suggest a fix/enhancement

The Eclipse Project has Java 1.8 compatibility. Wrong Java Code examples:

Example 1, two times "DEBIT_DIRECT" field:

`public enum EntryModeEnum {
    CUSTOMER_ENTRY("CUSTOMER_ENTRY"),
    
    BOLETO("BOLETO"),
    
    CHIP("CHIP"),
    
    CONTACTLESS("CONTACTLESS"),
    
    CONTACTLESS_MAGSTRIPE("CONTACTLESS_MAGSTRIPE"),
    
    DIRECT_DEBIT("DIRECT_DEBIT"),
    
    MAGSTRIPE("MAGSTRIPE"),
    
    MAGSTRIPE_FALLBACK("MAGSTRIPE_FALLBACK"),
    
    MANUAL_ENTRY("MANUAL_ENTRY"),
    
    MOTO("MOTO"),
    
    DIRECT_DEBIT("DIRECT DEBIT"),`

Example 2, `TransactionMixinHistory ` is not an interface in my case - it's a class:

`public class TransactionHistory extends TransactionMixinBase implements TransactionMixinHistory {`

Example 3, same problem as above:

`public class TransactionFull extends TransactionMixinBase implements TransactionMixinCheckout, TransactionMixinHistory {`

...and so on. @Developers: I think you should create the Java Spring Code from the SumUp REST service definition file by yourself - then you will see all the error messages / wrong code.

Thank you,
Jan

**Comment by martijintro** [comment]
No answer...??

**Comment by martijintro** [comment]
Problem solved with ignoring your crappy codegen!!

**Comment by HugoMario** [comment]
Hello @martijintro , thanks for reporting this issue. Please, try to not get angry for small things, it's not healthy :)
