### ISSUE TITLE
Fix typo in swagger-codegen README. Should be 'receive' instead of 'receieve'.

### ISSUE THREAD

**Issue by PippaClarkGDS** [swagger-api/swagger-codegen#10058]
##### Description 

There is a typo in the swagger-codegen README on line 767. It should be 'receive' instead of 'receieve'.

##### Swagger-codegen version

Using the master version of swagger-codegen - 2.4.13.

##### Swagger declaration file content or url

n/a

##### Command line used for generation

n/a

##### Steps to reproduce

n/a

##### Related issues/PRs

n/a 

##### Suggest a fix/enhancement

Change 'receieve' to 'receive' on line 767.

**Comment by HugoMario** [comment]
nice catch, thanks @PippaClarkGDS

**Comment by HugoMario** [comment]
fixed!
