### ISSUE TITLE
[R] R client for the version 3 branch

### ISSUE THREAD

**Issue by mtesch-um** [swagger-api/swagger-codegen#10084]
##### Description

This is just a ticket to request and track adding R client support for the 3.0 branch.  Could help out with this, just want to coordinate with anyone else interested.

##### Swagger-codegen version

3.0.16

##### Command line used for generation

`swagger-codegen generate -i api.json -l r -o xxx`

##### Related issues/PRs

#2231 #6697 #6616 #6520

##### Suggest a fix/enhancement

Suggest adding or porting the 2.x R client generator to the 3.x branch.  What needs to be done?  Are there any gotchas to consider for whoever tackles this?  Thanks!

**Comment by HugoMario** [comment]
hello @mtesch-um , i'm going to help you with migration from 2.0 to 3.0.x.

**Comment by HugoMario** [comment]
added generator on https://github.com/swagger-api/swagger-codegen-generators/pull/625

so closing now, if you  make changes in a future and need help to merge, please dont hesitate to ping me

**Comment by mtesch-um** [comment]
Fantastic! Thank you!
