### ISSUE TITLE
swagger-codegen cannot create README.md

### ISSUE THREAD

**Issue by dougbeauchene** [swagger-api/swagger-codegen#1008]
I am invoking codegen from a gradle task to generate .json from .yaml source.

When it runs, I see this message displayed in the output:
can't open swagger\README.md for input

A README.md file of length 0 bytes is created.

From within the swagger-editor, if I select Generate Client-->Swagger JSON....a zip file is created that contains a valid README.md and my .json output.

Why do I get the message when gradle generates the .json for me.  I don't need this README.md ?

Here is code from my gradle task:

apply plugin: 'java'

dependencies {
    compile 'com.wordnik:swagger-codegen-cli:2.1.0-M2'
}

task swaggerBuildPublicJson(type:JavaExec) {
    main 'com.wordnik.swagger.codegen.Codegen'
    classpath = sourceSets.main.runtimeClasspath
    args 'generate', '-i', 'public/public.yaml', '-l', 'swagger', '-o', './public'
}

**Comment by wing328** [comment]
@dougbeauchene please test with `develop_2.0` branch which contains the latest bug fixes and enhancements to see if you still experience the same issue.

**Comment by wing328** [comment]
@dougbeauchene closing the issue as we've not heard any update from you.
