### ISSUE TITLE
Angular Client is throwing an error when no configuration is provided

### ISSUE THREAD

**Issue by Neospiro** [swagger-api/swagger-codegen#10090]
Hi,

I generate angular clients and since last release, there is a problem.

Before, this was the generated code for a request : 
![image](https://user-images.githubusercontent.com/4870502/76294360-ff96e000-62b2-11ea-8e6f-81831273e9f0.png)

Now, it generate this : 
![image](https://user-images.githubusercontent.com/4870502/76294432-20f7cc00-62b3-11ea-89ac-c3edc7e7b750.png)

The problem is with this line : 
`if (this.configuration.apiKeys["Authorization"]) {`
throwing an error because `this.configuration.apiKeys` is never initialized as an array (no default value).

If I manually fix the generated code with 
`if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {`

It works

**Comment by HugoMario** [comment]
fixed by [swagger-codegen-generators#622](https://github.com/swagger-api/swagger-codegen-generators/pull/622)
