### ISSUE TITLE
javascript client generator missing BigDecimal model for number property

### ISSUE THREAD

**Issue by AmazingTurtle** [swagger-api/swagger-codegen#10105]
##### Description

`javascript` client generator emits import in `api/DefaultApi.js` to `../model/BigDecimal` but the model is not generated.

![Screenshot_20200315_140741](https://user-images.githubusercontent.com/2357438/76701971-57c04e80-66c6-11ea-991a-b13ee7958f9a.png)

```js
...
import ApiClient from "../ApiClient";
import BigDecimal from '../model/BigDecimal';
import CreateFormDto from '../model/CreateFormDto';
...
```

##### Swagger-codegen version

[v3.0.18](https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.18/)

##### Swagger declaration file content or url

schema property field `type` set to `number`, example:
```json
"UpdateFormDto": {
  "properties": {
    "id": {
      "type": "number"
    },
    "form": {}
  },
  "type": "object",
  "required": [
    "id",
    "form"
  ]
}
```

##### Command line used for generation

```
java -jar swagger-codegen-cli-3.0.18.jar generate -i swagger.json -l javascript -o api-client
```

##### Steps to reproduce

Get [this swagger.json](https://gist.github.com/AmazingTurtle/9d5d33c9aa80fe76549576a543733974) file and run the command line above.

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen-generators/issues/336
perhaps also referencing [this line of code](https://github.com/swagger-api/swagger-codegen-generators/blob/6a331b0095409a51b1d1de200b008c4a994634a5/src/main/java/io/swagger/codegen/v3/generators/javascript/JavaScriptClientCodegen.java#L144)

##### Suggest a fix/enhancement

For me it seems like the changes [the code](https://github.com/swagger-api/swagger-codegen-generators/blob/6a331b0095409a51b1d1de200b008c4a994634a5/src/main/java/io/swagger/codegen/v3/generators/javascript/JavaScriptClientCodegen.java#L144) mentioned above did not make it to 3.0.18, am I right?

**Comment by keefertaylor** [comment]
+1 I am also hit by this issue

**Comment by HugoMario** [comment]
thanks for reporting this, i just assigned to myself to work on it as soon i got a chance
