### ISSUE TITLE
[Java/SpringBoot] Compilation error in generated interfaces for server stub

### ISSUE THREAD

**Issue by luizrod** [swagger-api/swagger-codegen#10185]
##### Description
I'm following instructions here https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO on how to build a stub server for java/SpringBoot.
After generating using the command line provided in the HOWTO file, I navigate to the generated sources folder /samples/server/petstore/springboot. I try to compile the generated server using mvn package. I get several compilation errors starting with:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-spring: Compilation failure: Compilation failure:
[ERROR] /C:/Work/swagger-codegen/samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java:[38,5] default methods are not supported in -source 1.7
To fix these, I have to open the generated pom.xml and change the line 
	<java.version>1.7</java.version>
to 
	<java.version>1.8</java.version>
Question 1: If the generated code requires java 1.8 to compile then why does the pom specify java 1.7?

Question 2: After changing the Java versionto 1.8 in the pom file and rebuilding with mvn clean package, I get multiple compilation errors starting with:
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Work/swagger-codegen/samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java:[39,12] cannot find symbol
  symbol:   method getObjectMapper()
  location: interface io.swagger.api.StoreApi
[ERROR] /C:/Work/swagger-codegen/samples/server/petstore/springboot/src/main/java/io/swagger/api/StoreApi.java:[39,45] cannot find symbol
  symbol:   method getAcceptHeader()
  location: interface io.swagger.api.StoreApi

##### Swagger-codegen version
Swagger version: 2.4.14

##### Swagger declaration file content or url
json used to generate: http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l spring -o samples/server/petstore/springboot
Note: Executed on Windows 10 64 bits

##### Steps to reproduce
1. Obtain version 2.4.14 (I did it cloning from https://github.com/swagger-api/swagger-codegen.git)
2. Build module swagger-codegen
3. Generate using the above command location
4. Compile the generated code unsing the pom.xml in samples/server/petstore/springboot

##### Related issues/PRs
Could not find a similar issue but one may exist.

##### Suggest a fix/enhancement
I could compile after manually replacing code such as 
    default ResponseEntity<Void> deleteOrder(@Min(1L)@ApiParam(value = "ID of the order that needs to be deleted",required=true) @PathVariable("orderId") Long orderId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default StoreApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
in StoreApi.java by
	ResponseEntity<Void> deleteOrder(@Min(1L)@ApiParam(value = "ID of the order that needs to be deleted",required=true) @PathVariable("orderId") Long orderId);
The same in other interfaces in fils *Api.java

**Comment by charygao** [comment]
I find most samples are error in file:
java\io\swagger\api\StoreApi.java
java\io\swagger\api\UserApi.java
java\io\swagger\api\PetApi.java

there lost code:
``` java
    Logger log = LoggerFactory.getLogger(PetApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }
    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }
```

**Comment by luizrod** [comment]
Ok but I tried adding the code and still had to change to java 1.8 in the pom file and it still didin't compile, required a bunch om import statements that were missing.
Is this issue already being tracked?

Thank you,
Luiz
