### ISSUE TITLE
[SPRING]Missing JsonTypeInfo Annotations with Swagger Generator 3.0.19

### ISSUE THREAD

**Issue by rajeswarikolluri** [swagger-api/swagger-codegen#10198]
##### Description

Issue noticed in generated models for inherited classes while using Swagger Code Generator version 3.0.19.

##### Swagger-codegen version

3.0.19
##### Swagger declaration file content or url
openapi: "3.0.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://petstore.swagger.io/v2"
servers: 
  - url: http://petstore.swagger.io/v2 
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: pet_type
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Dog`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:     # "Cat" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Cat`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            hunts:
              type: boolean
            age:
              type: integer

##### Suggest a fix/enhancement
Same works with Swagger Generator 3.0.16

**Comment by rajeswarikolluri** [comment]
[model_3.0.19.zip](https://github.com/swagger-api/swagger-codegen/files/4520550/model_3.0.19.zip)
[model_3.0.16.zip](https://github.com/swagger-api/swagger-codegen/files/4520551/model_3.0.16.zip)

`openapi: "3.0.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://petstore.swagger.io/v2"
servers: 
  - url: http://petstore.swagger.io/v2 
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: pet_type
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Dog`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:     # "Cat" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Cat`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            hunts:
              type: boolean
            age:
              type: integer`

**Comment by rajeswarikolluri** [comment]
**Model of PET with Swagger Generator 3.0.16**

`@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-04-23T11:28:27.017+05:30[Asia/Calcutta]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "pet_type", visible = true )
@JsonSubTypes({
  @JsonSubTypes.Type(value = Cat.class, name = "Cat"),
  @JsonSubTypes.Type(value = Dog.class, name = "Dog"),
})
public class Pet   {`

**Model of PET with Swagger Generator 3.0.19**
`@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-04-23T11:32:12.263+05:30[Asia/Calcutta]")
public class Pet   {`

**Comment by lucianogalvaodesousa** [comment]
The same issue happens with me. Until version 3.0.18 the @JsonTypeInfo was put into the class, after this version, not is putting.

Version: 3.0.18
=====================================================================
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-07-02T15:12:56.488-03:00[America/Sao_Paulo]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "tipoPessoa", visible = true )
@JsonSubTypes({
        @JsonSubTypes.Type(value = PessoaJuridica.class, name = "PessoaJuridica"),
        @JsonSubTypes.Type(value = PessoaFisica.class, name = "PessoaFisica"),
})
public class Pessoa   {
...
===============================================================================

Version: 3.0.19
===============================================================================
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-07-02T15:00:31.725-03:00[America/Sao_Paulo]")
public class Pessoa   {
  /**
   * Gets or Sets tipoPessoa
   */
================================================================================


openapi: 3.0.0
servers:
  - description: Polimorfism Test
    url: https://virtserver.swaggerhub.com/lucianogalvaodesousa/samples/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Polimorfism API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /inserir:
    post:
      tags:
        - cadastrarEvento
      summary: Adicao de Eventos
      operationId: addInventory
      description: Adiciona evento
      responses:
        '201':
          description: evento created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evento'
        description: Evento item to add    
  /consultar:
    post:
      tags:
        - listarEventos
      summary: Lista de Eventos
      operationId: getEventos
      description: Lista os eventos
      responses:
        '200':
          description: lista dos eventos
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsultaEvento'
        description: Consulta Evento
components:
  schemas:
    Pessoa:
      discriminator: 
        propertyName: tipoPessoa
      required:
      - tipoPessoa
      properties:
        tipoPessoa:
          type: string
          enum:
            - PF
            - PJ
    PessoaFisica:
      allOf: 
        - $ref: '#/components/schemas/Pessoa'
        - type: object
          required:
            - cpf
            - nome
            - dataNascimento
          properties:
            cpf: 
              type: string
            nome: 
              type: string
            dataNascimento: 
              type: string
    PessoaJuridica:
      allOf: 
        - $ref: '#/components/schemas/Pessoa'
        - type: object
          required:
            - cnpj
            - razaoSocial
          properties:
            cnpj:
              type: string
            razaoSocial:
              type: string
    Evento:
      type: object
      required:
      - identificador
      - nome
      - participantes
      properties:
        identificador:
          type: integer
          format: int64
        nome:
          type: string
        participantes:
          type: array
          items:
            $ref: '#/components/schemas/Pessoa'
    ConsultaEvento:
      type: object
      required:
      - identificador
      properties:
        identificador:
          type: string

**Comment by pablo-ml** [comment]
The same happened to me. It works in version 3.0.18, but fails in versions 3.0.19 and 3.0.20.

**Comment by rajeswarikolluri** [comment]
Similar issue raised - https://github.com/swagger-api/swagger-codegen-generators/issues/686

**Comment by mike03081972** [comment]
Hi all,

For me no codegen cli v3 version are generating the jackson @JsonTypeInfo

I have tested version : 17 -> 21

Using this command line :

   java -Dmodels -jar swagger-codegen-cli-3.0.18.jar generate -l java -i rest-api-v3-light.yaml -o generated

     or

   java -Dmodels -jar swagger-codegen-cli-3.0.18.jar generate -l spring -i rest-api-v3-light.yaml -o generated

Any idea ?
