### ISSUE TITLE
Support HTTP Basic Auth for client generation

### ISSUE THREAD

**Issue by akkie** [swagger-api/swagger-codegen#102]
It isn't possible to create a client if the API is protected with HTTP Basic Auth.

It should be possible to pass the credentials in the URL. Maybe like:

 http://user:password@host/api-docs special-key

**Comment by StephanBeutel** [comment]
This doen't work for me. I only get this exception:

java.io.IOException: Server returned HTTP response code: 401 for URL:

**Comment by fehguy** [comment]
will make sure this is tested for 2.1.0-m1

**Comment by keithchong** [comment]
Hello, I am still getting a Server returned HTTP response code: 401 for URL when I try to generate the java client code.  Do you need to provide -auth?

**Comment by fehguy** [comment]
@keithchong please open a new issue. I'm sure this is supported so perhaps a usage issue.

**Comment by keithchong** [comment]
Hi Tony, will do.  I'm using v2.1.5.
