### ISSUE TITLE
JAX-RS generated server readme template mentions it's using scalatra

### ISSUE THREAD

**Issue by jplegoff** [swagger-api/swagger-codegen#1020]
In readme template, it mentions it's using scalatra framework : 
`This example uses the [scalatra](http://scalatra.org/) framework.`
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/README.mustache

**Comment by wing328** [comment]
@jplegoff thanks for reporting the issue. I agree that the README needs to be updated (my guess is that it was copied over from the Scalatra folder).

Please feel free to submit a PR against the `develop_2.0` branch

**Comment by wing328** [comment]
@jplegoff  Updated to remove reference to scalatra
