### ISSUE TITLE
[ASP Net Core] Support for dotnet core version 3.1

### ISSUE THREAD

**Issue by amalkurup89** [swagger-api/swagger-codegen#10209]
##### Description

I tried creating aspnetcore application using swagger codegen and the latest supported dotnet core version is 3.0. Are there any development in progress from your end, to support dotnet core version 3.1, as it has a long term support

##### Swagger-codegen version

Latest, which is available on swagger editor

##### Command line used for generation

Generated on swagger editor online

**Comment by HugoMario** [comment]
issue has been solved by https://github.com/swagger-api/swagger-codegen-generators/pull/746
