### ISSUE TITLE
Different code generated with the same specification

### ISSUE THREAD

**Issue by haidaraM** [swagger-api/swagger-codegen#1021]
Hi everyone,
I don't know if this is really an issue.
I used  swagger editor and swagger codegen to generate client code in java with the same specification but I didn't get the same client. There are some differences between both like `Pair.java` which is only presents  when using the online generator.
Is there a reason why I don't have the same code? If yes, which one I should use?

**Comment by wing328** [comment]
@haidaraM for swagger-codegen are you using `develop_2.0` branch, which contains the latest bug fixes and enhancements?

**Comment by haidaraM** [comment]
No. I'm on the `master` branch.

**Comment by haidaraM** [comment]
I just switched to `develop_2.0` branch and I have the same code (I think). So I had to use this branch ??

**Comment by wing328** [comment]
I would recommend you to use `develop_2.0`, which has the latest bug fixes and enhancements. Otherwise you may encounter issue that's fixed in `develop_2.0` branch.

**Comment by haidaraM** [comment]
Ok. Thanks for your reply.
