### ISSUE TITLE
compilation error in generated code.

### ISSUE THREAD

**Issue by manojpandey89** [swagger-api/swagger-codegen#10240]
Compilation error in generated file for attached swagger json. Kindly look into the issue and provide the fix. 
[apiDefinition.txt](https://github.com/swagger-api/swagger-codegen/files/4615250/apiDefinition.txt)

**Comment by HugoMario** [comment]
hi @manojpandey89 what language are you generating code for?

**Comment by manojpandey89** [comment]
Clent code generation in java language..
