### ISSUE TITLE
Unable to override specific templates using Swagger Codegen v3

### ISSUE THREAD

**Issue by radarsh** [swagger-api/swagger-codegen#10272]
##### Description

I would like to override specific handlebars for certain languages (Spring and Micronaut) but the v3 codegen seems to want me to include every single template found for that particular language under the swagger-codegen-generators repository. If I don't do that, I keep getting `FileNotFoundException`s for every template the language depends on until I eventually have added them all.

I believe this was fixed in #10107 but the fix should really be applied in the codegen framework rather than an individual language as it seems to affect every language.

##### Swagger-codegen version

```gradle
classpath 'io.swagger.codegen.v3:swagger-codegen:3.0.20'
classpath 'io.swagger.codegen.v3:swagger-codegen-generators:1.0.20'
```

##### Command line used for generation

```gradle
task swagger {
    inputs.file('api.yml')
    outputs.dir(file("${buildDir}/generated/sources"))
    doLast {
        new DefaultGenerator().opts(
            new CodegenConfigurator(
                inputSpec: file('api.yml').text,
                outputDir: "${buildDir}/generated/sources",
                lang: 'micronaut',
                additionalProperties: [
                    dateLibrary: 'java8',
                    invokerPackage: 'com.example.todo',
                    configPackage: 'com.example.todo.config',
                    apiPackage: 'com.example.todo.api',
                    modelPackage: 'com.example.todo.api.model',
                    skipSupportingFiles: 'true'
                ]
            ).setTemplateDir('templates/JavaMicronaut')
                .addDynamicProperty('sourceFolder', 'src/swagger/java')
                .toClientOptInput()
        ).generate()
    }
}
```

##### Steps to reproduce

Just copy a single file into your local template directory instead of the whole lot and run codegen again.

##### Related issues/PRs

#10107

**Comment by HugoMario** [comment]
hey @radarsh PR #10348 has changes fixing this, however keep in mind if you are using a template that include other templates inside, you would need them in the same custom path. Going to close this, if you see something wrong, please let me know and i work on it asap.
