### ISSUE TITLE
Your HTTPS certificate just expired!

### ISSUE THREAD

**Issue by pulimento** [swagger-api/swagger-codegen#10273]
Hi all,

Sorry for not using the template, but I think in this case it's not necessary.

Your certificates just expired (all related with *.swagger.io), and the browser shows a nasty red warning when you navigate to the page (example: [https://generator3.swagger.io/ui/](https://generator3.swagger.io/ui/))

![Screenshot 2020-05-26 at 17 26 21](https://user-images.githubusercontent.com/503313/82919236-0cec6e00-9f76-11ea-8c37-a725173acbd7.png)

Cheers,
Javi P

**Comment by aarontc** [comment]
The link you provided is using an Amazon cert that expires `5/15/2021, 5:00:00 AM (Pacific Daylight Time)`. Maybe there was a caching issue or something on your end. https://www.ssllabs.com/ssltest/analyze.html?d=generator3.swagger.io&latest

**Comment by JonathanParrilla** [comment]
Hey. Our cert expired yesterday and a new one has replaced it. This can be closed out.
