### ISSUE TITLE
Fatal error compiling: invalid target release: 1.8 

### ISSUE THREAD

**Issue by victorpaulo** [swagger-api/swagger-codegen#10283]
##### Description
Error during the code generation using run-in-docker.sh;
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project swagger-codegen: Fatal error compiling: invalid target release: 1.8 -> [Help 1]**
 

##### Swagger-codegen version

2.4.15-SNAPSHOT
##### Command line used for generation
swagger-codegen/run-in-docker.sh generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l java \
  -o /tmp/petstore

##### Suggest a fix/enhancement
from run-in-docker.sh:

docker run --rm -it \
        -w /gen \
        -e GEN_DIR=/gen \
        -e MAVEN_CONFIG=/var/maven/.m2 \
        -u "$(id -u):$(id -g)" \
        -v "${PWD}:/gen" \
        -v "${maven_cache_repo}:/var/maven/.m2/repository" \
        --entrypoint /gen/docker-entrypoint.sh \
        maven:3-jdk-7 "$@"

From run-in-docker.sh, I changed from  maven:3-jdk-7 to  maven:3-jdk-8 solved the problem;

**Comment by seiyab** [comment]
I got same error.
Seems to reproduce since  #10262
