### ISSUE TITLE
[JAVA] Bug Generating with Swagger Gen V3 Not Resolving Internal $ref And Instead has Insane broken Import

### ISSUE THREAD

**Issue by PRAquilone** [swagger-api/swagger-codegen#10294]
Sorry had to delete per company policy.

**Comment by PRAquilone** [comment]
Ok so looking deeper I think the real issue is when the bundle is generated it is referencing the wrong object.  One that does not become a class.

**Comment by HugoMario** [comment]
hey @PRAquilone can you add a similar sample to reproduce this?
