### ISSUE TITLE
Any plan to add a brew installer?

### ISSUE THREAD

**Issue by soasme** [swagger-api/swagger-codegen#1030]
Something like 

```bash
$ brew install swagger-codegen
$ swagger-codegen generate -i ./schema.json -l objc 
```

**Comment by who** [comment]
Neat idea - throw a PR together if you like :)

**Comment by wing328** [comment]
@soasme I don't think anyone is working on a brew installer for swagger-codegen. Feel free to submit a PR as suggested @who and the community would appreciate your contribution.

**Comment by arnested** [comment]
I submitted a pull request for inclusion of swagger-codegen in Homebrew: https://github.com/Homebrew/homebrew/pull/45360.

**Comment by wing328** [comment]
Thank you @arnested :beer:

**Comment by arnested** [comment]
Swagger Codegen has now been added to Homebrew: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/swagger-codegen.rb
