### ISSUE TITLE
[JAVA] RxJava3 Support

### ISSUE THREAD

**Issue by tgerth** [swagger-api/swagger-codegen#10312]
#### Description

We would like to add a useRxJava3 setting with retrofit2 which would result in:
```
ext {
    retrofit_version = "2.0.2"
    rx_java_version = "3.0.4"
}
dependencies {
    compile "com.squareup.retrofit2:retrofit:$retrofitVersion"
    compile "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    compile "com.github.akarnokd:rxjava3-retrofit-adapter:3.0.0"
    compile "io.reactivex.rxjava3:rxjava:$rx_java_version"
}
```
#### Related issues
Similar to this issue:
https://github.com/swagger-api/swagger-codegen/issues/4698

**Comment by Vlad-M-1** [comment]
RxJava 2 end of life is in February which is two months from now:

https://github.com/ReactiveX/RxJava
