### ISSUE TITLE
Incorrect swagger-codegen-cli code generation for nested array

### ISSUE THREAD

**Issue by vijayrcse** [swagger-api/swagger-codegen#1033]
I am using swagger-codegen-clie version 2.1.2. For a given json schema that contains nested array the model property is generated as follows

```java
private List<List<Descriptor>> chains = new ArrayList<List>() ;
```
Above doesn't compile. The swagger spec is 2.0 and a sample snippet is as follows which represent the nested array

how should we get past this issue ?

generated json snippet from service end point using swagger spec 2.0

```json
"chains": {
                "type": "array",
                "description": "Ordered descriptor chains",
                "items": {
                    "type": "array",

                    "items": {
                        "$ref": "#/definitions/Descriptor"
                    }
                }
            }
```

**Comment by vijayrcse** [comment]
issue is same as https://github.com/swagger-api/swagger-codegen/issues/989

**Comment by wing328** [comment]
Closing this as it's the same as #989 (closed)
