### ISSUE TITLE
Java Codegen not producing joda DateTime for "date-time" format objects in swagger.json

### ISSUE THREAD

**Issue by mdotson** [swagger-api/swagger-codegen#1035]
In our codegen project, we have date-time fields that we would like to be generated to joda DateTime objects. Currently, they are parsed into Date objects.

Model in jersey service:
@ApiModelProperty(required = true, position = 9")
public DateTime getCreationTimestamp() { return ModelUtils.millisToJoda(creationTimestamp); }

swagger.json:
```js
creationTimestamp: {
type: "string",
format: "date-time"
}
```
Generated model from codegen:
```java
@ApiModelProperty(required = true, value = "")
  @JsonProperty("creationTimestamp")
  public Date getCreationTimestamp() {
    return creationTimestamp;
  }
  public void setCreationTimestamp(Date creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }
```
Is there DateTime support currently in any form? Swagger-core seems to have support for DateTime objects according to the swagger.json, so it seems that if there is no support, it is very much needed.

**Comment by akkie** [comment]
We use:
```
"lastLoginTime":{"type":"DateTime"}
```

**Comment by mdotson** [comment]
We tried adding the dataType="DateTime" to our swagger annotation (we're using jersey again), but it's still coming out with a "type": "string", "format":"date-time". Our swagger-core version is 1.5.2-M2.

**Comment by mdotson** [comment]
Also, according to the swagger 2.0 spec, "type":"string", "format":"date-time" should be interpreted as DateTime:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types

**Comment by wing328** [comment]
@mdotson you're correct in saying that `"type":"string", "format":"date-time"` corresponds to `dateTime` in swagger 2.0 spec.

May I know which code generator you're using ?

**Comment by mdotson** [comment]
We are just using the "java" generator. "-l java". This generates a Date object and not a joda DateTime object.

**Comment by xhh** [comment]
It's the expected behavior that `{"type": "string", "format": "date-time"}` is mapped to `java.util.Date`, see the mapping [here in DefaultCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules%2Fswagger-codegen%2Fsrc%2Fmain%2Fjava%2Fio%2Fswagger%2Fcodegen%2FDefaultCodegen.java#L304).

There are joda-related code there (and also `pom.xml` of Java client), but apparently they are not used. Maybe `date-time` will be mapped to `DateTime` from joda in the future, or those joda-related code will be removed.

**Comment by mdotson** [comment]
I mean I see that the generator has Date and not DateTime, but is that really intended? If this is intended, is there a way to substitute my own Codegen class to override this behavior?

**Comment by fehguy** [comment]
Yes, well `java.util.date` is really a date-time.  The older java date stuff is truly a mess.

The best solution if you're not on java 8 is to use joda.  Note that the types are configured like such:

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L449-L452

```java
    public String getSwaggerType(Property p) {
        String datatype = null;
        ///
        } else if (p instanceof DateProperty) {
            datatype = "date";
        } else if (p instanceof DateTimeProperty) {
            datatype = "DateTime";
```

That means you can use the `typeMapping` to map to whatever classes you like.  So you should do this:

```java
// you can add this or simply remove the `DateType` mapping
typeMapping.put("date", "LocalDate");

typeMapping.put("DateTime", "DateTime");
```

It's probably worth a PR to support this correctly if you can do it.
