### ISSUE TITLE
Question: How to customize generator for NOT a new language

### ISSUE THREAD

**Issue by UnHumbleBen** [swagger-api/swagger-codegen#10367]
There is documentation for how to make a generator for a completely new language, but that is too much for my use case. I just want to modify the [current generator](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/DefaultCodegenConfig.java)'s behavior so that I can add a IS_KEY_IN_COOKIE_EXT_NAME mustache variable and use it for my mustache templates.

I see tons and tons of documentation about making generator for a [completely new language](https://github.com/swagger-api/swagger-codegen/wiki/How-to-add-a-generator-for-a-new-language-or-framework) but cannot find any documentation about customizing a generator that has already been made. Are we not allowed to customize generators? Are we expected to start from scratch for doing something as simple as modifying one line of code in the generator?

##### Swagger-codegen version

Using version 3.

**Comment by UnHumbleBen** [comment]
I guess the best way is to clone and edit it manually :(

**Comment by HugoMario** [comment]
@UnHumbleBen 
extending from generator class does not work for you?

**Comment by UnHumbleBen** [comment]
@HugoMario I was unable to extend the generator class because how I could not run it with the configuration file using the `-c` option flag I was using for Java. If I extend it to a generator such as `MyClientCodegenGenerator` and try to pass this into the `-l` flag, the command line tool will complain that there are no configurations for language: `MyClientCodegen`, and then lists all the other languages.
```
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name MyClientCodegen
 Available: aspnetcore
csharp
csharp-dotnet2
go
go-server
dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
micronaut
spring
nodejs-server
openapi
openapi-yaml
kotlin-client
kotlin-server
php
python
python-flask
r
scala
scala-akka-http-server
swift3
swift4
swift5
typescript-angular
typescript-fetch
javascript

        at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
        at io.swagger.codegen.v3.cli.SwaggerCodegen.main(SwaggerCodegen.java:96)
Caused by: java.lang.ClassNotFoundException: javafsjkflsdjf
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
        ... 1 more
```

In addition, I need to add a constant to `CodegenConstants.java` and add a method to `CodegenSecurity.java`, so I couldn't just extend the generator class even if I was allowed to add configurations. (I'm surprised you are not allow to use configurations if you use a custom generator though):
```diff
diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java
index efb847320..c71a58503 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenConstants.java
@@ -301,6 +301,7 @@ public class CodegenConstants {
     public static final String IS_BEARER_EXT_NAME = PREFIX_IS + "bearer";
     public static final String IS_OAUTH_EXT_NAME = PREFIX_IS + "oauth";
     public static final String IS_API_KEY_EXT_NAME = PREFIX_IS + "api-key";
+    public static final String IS_KEY_IN_COOKIE_EXT_NAME = PREFIX_IS + "key-in-cookie";
     public static final String IS_KEY_IN_QUERY_EXT_NAME = PREFIX_IS + "key-in-query";
     public static final String IS_KEY_IN_HEADER_EXT_NAME = PREFIX_IS + "key-in-header";
     public static final String IS_CODE_EXT_NAME = PREFIX_IS + "code";
diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSecurity.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSecurity.java
index abfc2e857..ef6de9fd7 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSecurity.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/CodegenSecurity.java
@@ -102,6 +102,8 @@ public class CodegenSecurity extends CodegenObject {
         return getBooleanValue(CodegenConstants.IS_API_KEY_EXT_NAME);
     }
 
+    public Boolean getIsKeyInCookie() { return getBooleanValue(CodegenConstants.IS_KEY_IN_COOKIE_EXT_NAME); }
+
     public Boolean getIsKeyInQuery() {
         return getBooleanValue(CodegenConstants.IS_KEY_IN_QUERY_EXT_NAME);
     }
```

**Comment by HugoMario** [comment]
@UnHumbleBen 
for your custom generator, you must add a `io.swagger.codegen.CodegenConfig` file at:
`src/main/resources/META-INF/services` folder. and add the full name of your generator class
