### ISSUE TITLE
Python: Apostrophe in comments is converted to "&#39;s"

### ISSUE THREAD

**Issue by sadu99** [swagger-api/swagger-codegen#1038]
When python files are generated using swagger-codegen, all code comments containing an apostrophe are converted to "&#39;s".

Example:  "Information about the capsule&#39;s end marker"

Using swagger-codegen 2.1.3-SNAPSHOT

**Comment by fehguy** [comment]
Hi, can you please give an example so we can fix it?   We're probably missing the triple mustache...

**Comment by sadu99** [comment]
Looks like my example updated itself after submitting the issue. Here's an image:

![screen shot 2015-07-30 at 4 42 10 pm](https://cloud.githubusercontent.com/assets/7516660/8997761/290dbeb8-36da-11e5-973d-4b0d5cd47a22.png)

**Comment by geekerzp** [comment]
@sadu99 Fixed in https://github.com/swagger-api/swagger-codegen/pull/1039

**Comment by wing328** [comment]
@sadu99 PR merged into `develop_2.0`. Please let us know if you still experience the issue.

**Comment by wing328** [comment]
@sadu99 closing this issue as we'e not heard from you.
