### ISSUE TITLE
 php 7.4 PR #8534 was merged to master but never merged into any of the 3.0 releases.

### ISSUE THREAD

**Issue by softwareok1** [swagger-api/swagger-codegen#10392]
##### Description

If you generate a php-client with codegen 3.0.x composer install fails because "friendsofphp/php-cs-fixer": "~1.12" 

##### Swagger-codegen version

3.0.19

##### Steps to reproduce
generate any openapi3 client with swagger-codegen-cli-3.0.19 and then try composer install
##### Related issues/PRs
#8533 8533

##### Suggest a fix/enhancement

merge PR #8534 in releases 3.0.x

**Comment by mmihalev** [comment]
Any updates on this?

**Comment by mylemans** [comment]
Ran into a similar issue with PHP8

**Comment by pblan** [comment]
Any fixes yet?

**Comment by HugoMario** [comment]
This has been fixed by https://github.com/swagger-api/swagger-codegen-generators/pull/1119
