### ISSUE TITLE
Create a GDD generator

### ISSUE THREAD

**Issue by 2rs2ts** [swagger-api/swagger-codegen#1040]
The idea is simple: create a generator which converts your swagger spec document to a [Google Discovery Document](https://developers.google.com/discovery/v1/reference/apis) or a set thereof.

I have already been working on an implementation of this, but it basically requires me to modify this repo itself (it's not something I can do by generating a new codegen module with `Meta`.) I'm willing to see this through, but I wonder if the main contributors to this project would be okay with me adding fields to the codegen model objects, such as a `format` for `CodegenProperty`.

**Comment by wing328** [comment]
@2rs2ts thanks for contributing a converter for Google Discovery Document format.

Would it be better to put the converter logic into [Swagger Core](https://github.com/swagger-api/swagger-parser) ?

Currently, it can read a swagger spec using Swagger Parser as follows:
```
import io.swagger.parser.SwaggerParser;
import io.swagger.models.Swagger;

// ... your code

  // read a swagger description from the petstore
  Swagger swagger = new SwaggerParser().read("http://petstore.swagger.io/v2/swagger.json");
```

One option is to implement a `toGoogleDiscoveryDocument()` function for `Swagger`. In the future, other contributors can implement converters for other formats.

**Comment by fehguy** [comment]
I actually think the logic should go int swagger-parser.  We can simply add an extension via SPI so it'll be picked up at runtime if added as a dependency.  Look at the swagger-compat-spec-parser, which handles older versions

**Comment by 2rs2ts** [comment]
@wing328 If I implemented a `toGoogleDiscoveryDocument()` method, then that would probably output a string, right?

@fehguy I'm confused by your comment. Isn't the goal of swagger-parser to read files and represent them as a `Swagger` object?

**Comment by wing328** [comment]
@2rs2ts I've fixed the link. Sorry what do you mean by without a JSON library?

**Comment by 2rs2ts** [comment]
@wing328 I didn't see Jackson as a dependency in swagger-core. I figured it would be hard to output a serialized JSON document in that project. I guess we could add model objects for GDD but at that point it might be better to just create a library modeling GDD and providing Swagger/GDD inter-conversion. Not sure I want to go that far, but it seems like the most reasonable solution.

An update on my progress with implementing this with swagger-codegen: I got pretty far until tags got in the way. We use tags at PayPal to describe certain characteristics of operations, such as service capacity and whether an operation is considered experimental (i.e. ready for consumption but not for live traffic.) swagger-codegen uses tags to populate its operations list... which is making my GDD generator spit out a method per tag. Plus the tag sanitization is making things difficult as well. I will try to clean up what I've got so far and push it to a branch of my fork of swagger-codegen, and will ask for input.

**Comment by wing328** [comment]
@2rs2ts if you've a valid reason (which I think you do), I think it's ok to add another library as a dependency of the project.

@fehguy I also confused on how `swagger-parser` can be used in this case and would appreciate if you can elaborate a bit more.

**Comment by 2rs2ts** [comment]
@wing328 Well, what if we made a separate project that just pulled in swagger-core, so that way anyone using swagger-core wouldn't have to pull in the extra dependency (or exclude it?) The more I work on this generator the more I think that would be the best route forward.

Anyway, I do have some progress which you can view [here](https://github.com/swagger-api/swagger-codegen/compare/swagger-api:master...2rs2ts:gdd-generator?expand=1).

**Comment by fehguy** [comment]
Hi @wing328 @2rs2ts sorry for the lag responding.

I would love to support importing as many formats as possible into swagger specs.  I would like to have first-class support as optional modules in swagger-parser, which is pluggable by design so you can parse whatever structure you want as long as you output a swagger object.  Via `SPI`, you simply include your module and voila.

As for going the other way, we don't have a pluggable module to do so.  You can certainly depend on swagger-core to build swagger specs as POJOs, and conversion should be simple.  You can even do this with javascript alone using JSON patch or other libraries.  Because that's not a primary goal of this project (it's certainly not discouraged!), there's no place to put it.

Regarding the JSON dependency, the `swagger-core` project has many modules in it.  I think you only need the `swagger-models` dependency, although you might want to use the `swagger-core` library to get the JSON deserializer, which is based on jackson 2.4.6 as of swagger-core-1.5.2.

Let me know if that covers everything.

**Comment by 2rs2ts** [comment]
@fehguy I am more interested in Swagger -> GDD than the other way around presently. I'm working on building it as its own module, and I'll share that with you when it's done, and you can find a good home for it.

**Comment by fehguy** [comment]
Sounds good.  Take a look at how swagger-parser is structured, you might be able to use that as a template for this as well.

**Comment by 2rs2ts** [comment]
@fehguy @wing328 I've implemented most of the necessary logic. Check [this branch](https://github.com/2rs2ts/swagger-gdd/tree/feature/prototype) out.

**Comment by 2rs2ts** [comment]
An update: while my project is lacking tests it's pretty close to done. There are only two things I want to address:

1. GDD doesn't support header, form, or cookie parameters, but Swagger does and I'm not sure what to do about them
2. Vendor extensions aren't really supported in GDD, but it might be nice to be able to port them over. I'm thinking of enabling the API to pass transformative operations to the conversion method to allow the processing of vendor extensions.

**Comment by wing328** [comment]
For 1, I asked the same question in their [forum](https://groups.google.com/forum/embed/?place=forum/google-apis-discovery&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fdevelopers.google.com%2Fdiscovery%2Fforum#!topic/google-apis-discovery/_r8obd_f_w0) but got no reply. The last post before mine was Nov 2014.

I wonder if the spec (GDD) is still active.

**Comment by 2rs2ts** [comment]
@wing328 Thanks for looking into it! I think I'm going to take the spec as it is to be literal but I'll make it so that it's quite possible to allow converting header, form, and cookie parameters. It'd be by a similar mechanism as the way I'll support vendor extensions.

**Comment by wing328** [comment]
@2rs2ts FYI. Google also joins the OpenAPI initiative (https://openapis.org/). I can't speak on behalf of them but I'm not surprised if they already have a plan in place to replace GDD with OpenAPI spec.
