### ISSUE TITLE
[JAVA] import mappings in model generation are ignored by default

### ISSUE THREAD

**Issue by oliverschmidthypoport** [swagger-api/swagger-codegen#10419]
##### Description

Since https://github.com/swagger-api/swagger-codegen/pull/9981 I have to specify an additional Property `ignoreImportMappings=false` to use `importMappings`. The JavaCodegen ist the only Codegen where the default is to ignore defined `importMappings`. Imho the default should be inverted - it was really hard to find the cause for the not working `importMappings` after updating the plugin.

##### Swagger-codegen version

2.4.12 and above

##### Swagger declaration file content or url

```xml
          <plugin>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-codegen-maven-plugin</artifactId>
            <version>2.4.15</version>
            <executions>
              <execution>
                <goals>
                  <goal>generate</goal>
                </goals>
                <configuration>
...
                  <language>java</language>
                  <additionalProperties>
                    <additionalProperty>ignoreImportMappings=false</additionalProperty>
                  </additionalProperties>
                  <importMappings>
...
                  </importMappings>
                </configuration>
              </execution>
            </executions>
          </plugin>

```

##### Suggest a fix/enhancement

Remove the default in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java, so the default from https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java is used.

**Comment by tibors13** [comment]
The same problem is in V3 codegen (latest). On the beginning it is false, but at some point before handling importSettings has true value (when not set, as above or in code), so the list is ignored :(

**Comment by ajperez81** [comment]
I was experiencing a similar problem with v2.4.19:

The `<importMappings>` option was being used correctly for the imports inside the generated classes. However, the mapped classes were still being generated, without any need for them.

Adding `<additionalProperty>ignoreImportMappings=false</additionalProperty>` stopped them being generated.

**Comment by ydbondt** [comment]
Same problem on the latest 3.0.37 version. Took me quite some time to figure out what (I assumed) I was doing wrong.
It is an unusual assumption that a user should disable a flag in order to use a certain feature.

Fixed it for now using the following gradle config (thnx to the comments above):
```groovy
swaggerSources {
    myModel {
        inputFile = file('src/main/resources/spec.yaml')
        code {
            // ...
            additionalProperties = [
                    "ignoreImportMappings": "false"
            ]
        }
    }
```
