### ISSUE TITLE
C# - How do I create *just* a project? (not a full solution)

### ISSUE THREAD

**Issue by aschuhardt** [swagger-api/swagger-codegen#10410]
##### Description

I want to be able to generate a .NET Core project that will fit into an existing solution.  I don't see any way of doing that right now; the `csharp` and `aspnetcore` modules will generate a new solution.

##### Swagger-codegen version

3.0.20

##### Suggest a fix/enhancement

Add an option to generate solely a project file (.csproj) and its related source files, instead of an entire solution.

**Comment by BryceBarbara** [comment]
If you use the argument `-dsupportingFiles=MyPackage.csproj` that should work.

So it would be something like `java -dsupportingFiles=MyPackage.csproj -jar swagger-codegen-cli.jar generate ...`

**Comment by aschuhardt** [comment]
Thank you!
