### ISSUE TITLE
[JAVA/Swing] swagger-codegen insists on including NULL fields in requests

### ISSUE THREAD

**Issue by spierepf** [swagger-api/swagger-codegen#10426]
##### Description

Attempting to use swagger to interact with a Solace PubSub server using their provided `semp-v2-swagger-config.yaml` configuration. However, their API does not accept NULL when an optional parameter is not included in a request.

https://github.com/SolaceSamples/solace-samples-java/issues/64

I've tried including `spring.jackson.default-property-inclusion=non_null`  in my `application.properties` file, and even overriding the default jackson `ObjectMapper`. But the result is always the same.

##### Swagger-codegen version

2.4.15

##### Swagger declaration file content or url

I downloaded the `semp-v2-swagger-config.yaml` from here:
https://solace.com/downloads/#1pubsub-standard-management

And here is a github project that exhibits the problem
https://github.com/spierepf/solace-junit5-test

##### Command line used for generation

`$ mvn clean test`

##### Steps to reproduce

`$ git clone https://github.com/spierepf/solace-junit5-test`
`$ mvn clean test`

##### Related issues/PRs

My issue is like this one except that his solution of  including `spring.jackson.default-property-inclusion=non_null`  in my `application.properties` file is not having the desired effect

https://github.com/swagger-api/swagger-codegen/issues/6488

##### Suggest a fix/enhancement

I think there should be a configuration property in my `pom.xml` file that adds the appropriate annotations to the generated model source files.

**Comment by gracekarina** [comment]
Hi, @spierepf I tried testing locally by adding the option `<notNullJacksonAnnotation>true</notNullJacksonAnnotation>`
at the maven plugin configuration, got some docker related errors, please give it a try and let me know if this is still an issue.
```
<configOptions>
	<notNullJacksonAnnotation>true</notNullJacksonAnnotation>>
</configOptions>
