### ISSUE TITLE
Inconsistensies/(bug?) in Swagger Data Types specification for pattern keyword

### ISSUE THREAD

**Issue by PaddySe** [swagger-api/swagger-codegen#10455]
Hi,

The Swagger Data Types documentation for the pattern keyword (https://swagger.io/docs/specification/data-models/data-types/#pattern) specifies that the format used should follow the ECMA 262 format. This format is /pattern/flags. However, in the example a few lines below, you use a different format (pattern: '^\d{3}-\d{2}-\d{4}$').

This opens up for a lot of problems, people writing the yaml files according to your example, but the code generators **require** the ECMA 262 format (I have only checked with the csharp och python code generators, however the java generator seems to accept it), and if the format is wrong, the generators simply throws an exception about the wrong format being used.

There are a lot of (open) issues here about this problem.

The "fun" part is that while the csharp generator throws an exception if the wrong format is used, it doesn't generate any code that actually use the pattern...

Fixing the format to use /pattern/ in the yaml file stops the csharp generator from throwing an exception.

**Comment by hkosova** [comment]
As explained in https://github.com/OAI/OpenAPI-Specification/issues/1985, `pattern` is supposed to contain a regular expression _body_ such as `^[A-Za-z0-9]+$` or `^\d{3}-\d{2}-\d{4}$`, rather than a regex _literal_ such as `/pattern/flags`.

**Comment by PaddySe** [comment]
@hkosova, ahh, thanks for that! There were too many hits when I searched so couldn't really read through them all.

The problem I (and many others) have is that several of the code generators **require** the `/pattern/flags` format, since they throw exceptions if that format **isn't** used.
