### ISSUE TITLE
csharp generator does not use invokerPackage

### ISSUE THREAD

**Issue by nabheet** [swagger-api/swagger-codegen#1047]
The compile.mustache template has the following line:

%CSCPATH%\csc /reference:bin/Newtonsoft.Json.dll;bin/RestSharp.dll /target:library /out:bin/{{invokerPackage}}.dll /recurse:src\*.cs /doc:bin/{{invokerPackage}}.xml

But the invokerPackage specified in the configuration file does not end up in the compile.bat file.

**Comment by wing328** [comment]
@nabheet sorry I misunderstood the issue earlier.

Here is the PR to fix the issue: #1131

Please let me know if you've any questions.

**Comment by wing328** [comment]
@nabheet the PR has been merged into master. Closing this issue for now. Please reopen this issue if needed.

**Comment by nabheet** [comment]
:+1:
