### ISSUE TITLE
C# model to typescript, with property type "object", generates "modelObject" but "modelObject.ts" is missing

### ISSUE THREAD

**Issue by JDelladecimas** [swagger-api/swagger-codegen#10499]
##### Description

When generating C# models to typescript-angular, when the C# property is of type Object the generator creates a different type called Model Object. _"Object (model name matches existing language type) cannot be used as a model name. Renamed to ModelObject"_
Since Object in C# means it can be anything, I would expect the generated type to be any (or Object as there is one in typescript).

Also the generator does not create the file modelObject.ts and if you run ng build it fails.

##### Swagger-codegen version

swagger-codegen-cli-3.0.22.jar

##### Swagger declaration file content or url

java -Dmodels -DsupportingFiles  -jar swagger-codegen-cli-3.0.22.jar 
generate -i https://localhost:44387/swagger/v1/swagger.json -l typescript-angular -o "src/models"
-Dio.swagger.parser.util.RemoteUrl.trustAll=true 
-Dio.swagger.v3.parser.util.RemoteUrl.trustAll=true
##### Command line used for generation

Api written in C# .Net Core 3. Generator is in a .bat file.
##### Steps to reproduce
One of the models that swagger needs to generate needs have a property of type object. eg 
`public class FieldOption {
   public string DisplayText { get; set; }
   public object Value { get; set; }
}`

the output is

`
import { ModelObject } from './modelObject';

export interface FieldOption { 
    displayText?: string;
    value?: ModelObject;
}
`
Expected: to have a file `modelObject.ts' but that does not exist.
To have one of typescripts built in objects.
eg
`
export interface FieldOption { 
    displayText?: string;
    value?: any;
}
`

##### Related issues/PRs

#10496

**Comment by frantuma** [comment]
fixed in swagger-api/swagger-codegen-generators/pull/1051
