### ISSUE TITLE
ModelObject in generated typescipt code

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-codegen#10496]
Using swagger-codegen 3.0.22 all my models containing an object property are now generated as a "ModelObject" referenced by 

`import { ModelObject } from './modelObject';`

that doesn't even exist. I've seen some old issues regrading this, but it should have been fixed already?

    IEnumValue:
      type: object
      properties:
        id:
          nullable: true
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        isDefault:
          type: boolean
      additionalProperties: false

```
import { ModelObject } from './modelObject';

export interface IEnumValue { 
    id?: ModelObject;
    name?: string;
    description?: string;
    isDefault?: boolean;
}
```

**Comment by Alpin-io-inc** [comment]
Hi Swagger Team,

I have same issue on my project. Yesterday, I migrated from 5.5.1 version to 5.6.1 and the issue appears.
So, I upgraded to last version (5.6.3) but the issue still persists.

Here is what I found by comparing the generated Swagger.json file:

For 5.5.1 -> Property "parameters", **in C# with 'object' type**

`          "parameters": {
            "type": "object",
            "additionalProperties": false,
            "nullable": true
          },`

Same property 'parameters' with Swagger.json but on 5.6.3 version

`          "parameters": {
            "nullable": true
          },`

_properties 'type' and 'additionalProperties' are not generated._

Hope this comparaison help you.
Tks for help!

**Comment by Alpin-io-inc** [comment]
Hi Swagger Team,

Any news about issue ?

Tks for your help!

**Comment by tsproesser** [comment]
Guess one of us needs to check code and implement it - rock paper scissors?

**Comment by angelaki** [comment]
Any news on this?

**Comment by sccheruku** [comment]
For what it is worth, I noticed that it occurs when the class contains a static method. I previously had the static methods `ScheduleDateHelper.fromTimeStamp`, `ScheduleDateHelper.fromObject` and `ScheduleDateHelper.fromTimeString` inside the `ScheduleDate` class. As a result the generated typescript was adding the line 
`import { ModelObject } from './modelObject';`

With the static methods separated into a helper class, I'm able to avoid seeing the line with `ModelObject`

```
// the typescript decorators are from nestjs-swagger
export class ScheduleDate {
    @ApiProperty({ type: "integer" })
    year: number;
    @ApiProperty({ type: "integer", minimum: 0, maximum: 11 })
    month: number;
    @ApiProperty({ type: "integer", minimum: 1, maximum: 31 })
    date: number;
    @ApiProperty({ type: "integer", minimum: 0, maximum: 23 })
    hour: number;
    @ApiProperty({ type: "integer", minimum: 0, maximum: 59 })
    minute: number;
    @ApiProperty({ type: "integer", minimum: 0, maximum: 59 })
    second: number;
}

/** This class has to be separate from ScheduleDate for OpenAPI Generation to work correctly */
export class ScheduleDateHelper {
    static fromTimeStamp(timestamp: number): ScheduleDate {
        const date = moment(timestamp);
        return ScheduleDateHelper.fromObject({
            year: date.year(),
            month: date.month(),
            date: date.date(),
            hour: date.hour(),
            minute: date.minute(),
            second: date.second(),
        });
    }

    static fromObject(value: any): ScheduleDate {
        let date = new ScheduleDate();
        ["year", "month", "date", "hour", "minute", "second"].forEach(key => date[key] = value[key]);
        return date;
    }

    static fromTimeString(timestring: string): ScheduleDate {
        const date = moment(timestring);
        if (!date.isValid()) { throw new Error("Invalid Date") }
        return ScheduleDateHelper.fromObject({
            year: date.year(),
            month: date.month(),
            date: date.date(),
            hour: date.hour(),
            minute: date.minute(),
            second: date.second(),
        });
    }
}
```

**Comment by angelaki** [comment]
Is anyone aware of this? The solutions seams so pretty easy: assume no type as **any**. Why isn't this going to be fixed?

**Comment by den19980107** [comment]
dose swagger teams still maintain this project 🥲

**Comment by JonasSL** [comment]
I'm also experiencing this problem - any news?

**Comment by WaldemarEnns** [comment]
Same issue on using `swagger-codegen -l typescript-fetch`. Using `version 3.0.32` it generates the type `ModelObject` for many - I guess currently _all_ - of my models. Running tests/build fails, since the type `ModelObject` does not exist.

## Dirty fix

Manually add:

```typescript
type ModelObject = any
```

to your generated `api.ts`.

That will not help in the long term if your goal is to auto-generate the client in pipelines or in general, in an automated way.

Any progress on this? I mean the last _fix_ comment was at version `3.0.27`? Thats already some versions and months that passed ...

**Comment by WaldemarEnns** [comment]
Is this even being maintained? Do the maintainers notice activity and requests on this open issue? :) Would be nice if we get some kind of feedback.

**Comment by StanleySathler** [comment]
I really appreciate all maintainers that help building this - most times for free. But c'mon guys... would be nice to have at least a confirmation from maintainers like "Yeah, this is indeed an issue and we have no plans to fix it right now".

Makes us think swagger-codegen is not even maintained.

**Comment by StanleySathler** [comment]
@WaldemarEnns going with your workaround.

We do have auto-generated types in our CI pipeline, so gonna create a script that literally adds this to the generated types. Seems there won't be a fix anytime soon.

**Comment by auzick** [comment]
We are experiencing this same issue. Is this being addressed, or should we abandon SwaggerHub on our project?

**Comment by frantuma** [comment]
fixed in swagger-api/swagger-codegen-generators/pull/1051

**Comment by WaldemarEnns** [comment]
@frantuma nice! That was surprising - will check it out immediately!
