### ISSUE TITLE
Missing fields in Java and Python classes

### ISSUE THREAD

**Issue by rickylevan** [swagger-api/swagger-codegen#1053]
When generating code in Java and Python (I haven't tried other languages, but I assume the problem is there as well) from a Swagger JSON document, some—but not all—of the "property" keys in the JSON end up becoming fields in the corresponding Java and Python classes. So some fields are just missing. Has anyone else had this problem?

**Comment by fehguy** [comment]
Hi, that typically is an issue when there are errors in your spec, like missing formats, etc.  Can you share your spec?  Any error messages?

**Comment by rickylevan** [comment]
I can't share the spec, but I'll look more tomorrow to see if there are places where it doesn't conform to Swagger. Thanks!

**Comment by wing328** [comment]
@rickylevan you can try https://editor.swagger.io to see if it throws any error for your spec.

**Comment by fehguy** [comment]
See if you can share the output from the codegen, strip away anything that seems proprietary.

**Comment by rickylevan** [comment]
Hey thank you for the advice. There were a few spots in the JSON that were not conforming to spec. Using https://editor.swagger.io, I now simply get three warnings about definitions that are defined but not used, which shouldn't make a difference. 

Running the codegen now gives errors from io.swagger.properties.PropertyBuilder, saying "no property for null, null" and "no property for string, string", which ultimately ends in a NullPointerException. 

But before reaching this exception, the model files were written again and the missing field problem persists, which I suspect would happen even with the above problem resolved. 

If this isn't enough information to be useful, I can try to make a stripped-down version of the JSON that removes anything proprietary.

**Comment by wing328** [comment]
@rickylevan are you using `develop_2.0` branch for your test? develop_2.0 contains the latest bug fixes and enhancements.

**Comment by rickylevan** [comment]
@wing328 I switched to develop_2.0 and re-ran "mvn package" followed by 
"java -jar modules/swagger-codegen-cli/target/original-swagger-codegen-cli.jar generate \
  -i https://localhost/api/1.0/api-docs \
  -l python \
  -o samples/client/pythonapi/python"

but received the following error:
"Exception in thread "main" java.lang.NoClassDefFoundError: io/airlift/airline/Cli
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:24)"

**Comment by wing328** [comment]
Here is line 24 in SwaggerCodegen.java
```
 20 public class SwaggerCodegen {
 21 
 22 
 23     public static void main(String[] args) {
 24         Cli.CliBuilder<Runnable> builder = Cli.<Runnable>builder("swagger")
 25                 .withDescription("Swagger code generator CLI. More info on swagger.io")
 26                 .withDefaultCommand(Langs.class)
 27                 .withCommands(
 28                         Generate.class,
 29                         Meta.class,
 30                         Langs.class,
 31                         Help.class,
 32                         ConfigHelp.class
 33                 );
 34 
 35         builder.build().parse(args).run();
```
I don't see anything that would obviously go wrong in that line.

If your spec cannot be shared publicly, do you mind sharing with me privately via my email address listed in Github profile page ? Otherwise, please provide a stripped down version of the spec for further troubleshooting.

**Comment by rickylevan** [comment]
@wing328 @fehguy You guys might find this interesting. If you run the commands from the instructions on github:
1. Clone repository
2. Run mvn package
3. Run generate command:
(java -jar modules/swagger-codegen-cli/target/original-swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l python \
  -o samples/client/pythonsdk/python),

it works perfectly if I start from branch master, but the exact same thing fails from branch develop_2.0. Note that this is using the petstore json file as a starting poing, not something proprietary. 

Best,
Ricky

**Comment by wing328** [comment]
@rickylevan please try the following command instead (swagger-codegen-cli.jar instead of original-swagger-codegen-cli.jar)
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
-i https://localhost/api/1.0/api-docs \
-l python \
-o samples/client/pythonapi/python
```

May I know where in the documentation you find the `original-swagger-codegen-cli.jar` so that I can update accordingly ?

**Comment by rickylevan** [comment]
Thank you for all the help. I found the origin of the problem. In the Data Types section (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types), if one includes a redundant format as well as type in the string case (i.e. including format "string" for type "string"), the codegen silently refuses to include the corresponding description fields in the model files. 

This may or may not be a bug. If it is important that the data types in the spec not be permissive, an error message about fields in model objects that fail to generate would be a nice feature. 

Best,
Ricky
