### ISSUE TITLE
[Java] HTTP Basic auth is broken in generated clients

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#1054]
It looks like HTTP Basic auth in the generated java clients is broken.  I used to be able to create an instance of ApiClient, set username and password into it, and then pass that instance of the ApiClient into the API class.  However, I am always receiving an HTTP 401, as the authentication is not sent. As a workaround, I am setting an Authorization header on the request.

Here's how I expect it to work:

```      
ApiClient apiclient = new ApiClient(); 
apiclient.setUsername("myUsername");
apiclient.setPassword("myPassword");
MyApiClass myApiClass = new MyApiClass(apiclient);      
myApiClass.callSomethingThatRequiresBasicAuth("foo");
```

**Comment by xhh** [comment]
Hi @who, I tried and it worked for me.

Do your swagger-spec has more than one HTTP basic authentication (securityDefinitions) defined? If so, you might need to explicitly retrieve and set data for a HTTP basic authentication, as the methods `setUsername` and `setPassword` are just helper methods to set data for the **first** HTTP basic authentication.
The following is sample code which works for me:

```java
HttpBasicAuth basic2 = (HttpBasicAuth) apiclient.getAuthentication("basic2");
basic2.setUsername("myUsername");
basic2.setPassword("myPassword");
```

**Comment by wing328** [comment]
@who we would appreciate if you can share with us your feedback on the current authentication approach of the Java API client. From a developer perspective, is that "natural" (easy-to-use, straightforward) to you? 

Ideally a developer who has never used the Java API client generated by codegen should not take more than 5 minutes to figure out how to authenticate using the API client (assuming sufficient documentation is provided)

**Comment by who** [comment]
@wing328 

Yes, I'd say that the auth approach in the generated Java client is natural and easy-to-use.  

However, for API classes that require authentication, perhaps their constructor method could be generated differently to accept a required Authentication object.

**Comment by who** [comment]
This turned out to be an error on the server side.  The authentication code in ApiClient turned out to be a red herring. Closing now.

**Comment by xiwenc** [comment]
Perhaps related to: https://github.com/swagger-api/swagger-parser/pull/117

**Comment by ecki** [comment]
In my case the swagger file has no security definition, so the genrated API looks like:

    // Setup authentications (key: authentication name, value: authentication).
    authentications = new HashMap<String, Authentication>();
    // TODO: manually: authentications.put("basic", new HttpBasicAuth());
    // Prevent the authentications from being modified.
    authentications = Collections.unmodifiableMap(authentications);

it does not add any authenticators so I cannot use setUsername().

If I manually add a authentication (TODO above) it seems not be enough as it is not applied to the http client it seems.

**Comment by berdachuk** [comment]
Hi @ecki,
Look like problem still exists, 
>>  it does not specify "authnames" in the various methodCall invocations.
I see, than If I use in REST controller Api like: 
    @ApiOperation(value = "sign in",
            notes = "Sign in to account",
            response = AuthorizationDetails.class,
            **authorizations = {@Authorization(value = "basicAuth")},**
            tags = {"authorisation"},
            nickname = "signIn")

then authNames populated:
...
String[] localVarAuthNames = new String[] { "basicAuth" };

but in generated ApiClient it is still missing initialisation:
**authentications.put("basicAuth", new HttpBasicAuth());**

**Comment by tschlegel** [comment]
It is generated, when specified in the OpenAPI 3.0 Spec. See https://swagger.io/docs/specification/authentication/basic-authentication/
