### ISSUE TITLE
[Java] Project does not compile. Missing dependency swagger-parser-version 1.0.9-SNAPSHOT

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#1055]
It looks like swagger-parser-version 1.0.9-SNAPSHOT is not available in the central repos, yet swagger-codegen requires it. Because of this, compilation of a fresh clone fails. Changing the version to 1.0.9 seemingly fixes the issue.

**Comment by wing328** [comment]
Tony redeployed swagger parser 1.0.9-SNAPSHOT. Issue resolved.
