### ISSUE TITLE
[Java] generated client truncates lone, quoted string response body

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#1056]
If you have an API that returns a single, quoted string in the response body, the swagger-codegen generated client will truncate the the last character of that string.

For instance, if your API returns a response body of `"hello world"`, the swagger-codegen ApiClient->deserialize() will return `hello worl`. The quotes, and the last character inside the quotes, are removed.

**Comment by who** [comment]
It seems like this is the culprit line: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache#L302

This should should probably be changed to  `return json.substring(1, json.length() - 1);`

I'll put a PR together and run some tests.

**Comment by fehguy** [comment]
right you are.  should be -1 because of the offset

**Comment by who** [comment]
Fixed in this PR: https://github.com/swagger-api/swagger-codegen/issues/1056

Ran tests (including integration) and things look good.

**Comment by fehguy** [comment]
thanks!

**Comment by xhh** [comment]
The same issue exists in Android and Scala clients, I'm submitting a PR for it.

**Comment by xhh** [comment]
The same issue exists in Android and Scala clients, I'm submitting a PR for it.
