### ISSUE TITLE
Deprecate InlineModelResolver and use flatten option provided by parser

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-codegen#10586]
https://github.com/swagger-api/swagger-parser/pull/1494 introduces flatten option (and related `InlineModelResolver` migrated from `swagger-codegen`) in swagger-parser v1; swagger-codegen 2.x and 3.x must be updated to:

1. Deprecate `InlineModelResolver` and clearly state that further development and maintenance will be targeting swagger-parser

2. Replace all occurrences of `InlineModelResolver` usage with an updated parser invocation with `flatten = true`, in both v2 and v3

**Comment by gracekarina** [comment]
closed by https://github.com/swagger-api/swagger-codegen/pull/10841
