### ISSUE TITLE
EXTREMELY HIGH PRIORITY - Smoke check failing - [JAVA] Bug with method being declared twice

### ISSUE THREAD

**Issue by pligor** [swagger-api/swagger-codegen#10580]
### Description

Receiving this error:
```
/home/student/Dropbox/swagger_projects/petstore_java/src/main/java/io/swagger/client/api/PetApi.java:245: error: method addPetCall(Pet,Long,String,Category,List<String>,List<Tag>,String,ProgressListener,ProgressRequestListener) is already defined in class PetApi
    public com.squareup.okhttp.Call addPetCall(Pet body, Long id, String name, Category category, List<String> photoUrls, List<Tag> tags, String status, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
```

Apparently the exact same function is being generated  

##### Swagger-codegen version

Latest stable release 3.023

##### Swagger declaration file content or url

As simple as the PetStore sample swagger json: https://petstore3.swagger.io/api/v3/openapi.json

##### Command line used for generation

swagger-codegen generate -i openapi.json -l java -o ~/Dropbox/swagger_projects/petstore_java/

##### Steps to reproduce

Simply compiling the project in Jetbrains Intellij by Build -> Rebuilt project will bring the error
This is basic Java language error, to have two function with the exactly same name and signature

##### Related issues/PRs
No

##### Suggest a fix/enhancement

Find what is causing to generate the function twice

**Comment by panargirakis** [comment]
Faced the same issue while building an OpenAPI 3.0 project with `swagger-codegen`. Using `openapi-generator-cli/5.4.0` my client built successfully.

**Comment by frantuma** [comment]
@panargirakis I am not able to reproduce it, can you possibly provide some more details, as the spec you are using and language/options?

**Comment by frantuma** [comment]
closing as inactive

**Comment by alexmelyon** [comment]
Have the same issue

**Comment by panargirakis** [comment]
@frantuma I no longer use swagger-codegen but in case it helps you can find my schema [here](https://gist.github.com/panargirakis/0d465f954f2c913ef3fc379f1b63da91).

I did not use any special options when generating.
