### ISSUE TITLE
[python3] SyntaxError in generated client code

### ISSUE THREAD

**Issue by avdv** [swagger-api/swagger-codegen#1060]
For the following (partial) swagger 2.0 spec (which is generated):

```json
"/api/v1/swagger.json": {
            "get": {
                "description": "You can add more detailed information here.",
                "parameters": [],
                "responses": {},
                "summary": "Get main swagger json documentation",
                "tags": [
                    "Api"
                ]
            }
        },
```

The python3 client generator creates the following invalid method name in `client/api_api.py`:

```py
    def api_v1_swagger/json_get(self, **kwargs):
               """Get main swagger json documentation
        You can add more detailed information here.

        Args:
            

        Returns: 
        """
```

So, it seems it replaces the '.' with a forward slash. Python complains:

```
  File "/test/data/client/api_api.py", line 1036
    def api_v1_swagger/json_get(self, **kwargs):
                      ^
SyntaxError: invalid syntax
```

**Comment by wing328** [comment]
@avdv `operationId` determines the method name. Please add it to the spec and you will have complete control of the method naming (with respect to the style guide in the respective language)

Here is an example:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L216

**Comment by geekerzp** [comment]
BTW. @avdv You can try `python-codegen` to generate the sdk for python3. The `python3-codegen` is outdated.

**Comment by wing328** [comment]
@avdv as @geekerzp has pointed out, please use the `python` codegen (instead of `python3` codegen) as API client generated by `python` codegen is compatible with both python2 and python3
