### ISSUE TITLE
Java 'path' query string parameter causes compile error

### ISSUE THREAD

**Issue by RMarinaro** [swagger-api/swagger-codegen#1061]
Using `path` as a query string parameter causes the java client to generate something like this
```
public void somemethodGet (String path) throws ApiException {
    Object postBody = null;
    
    // verify the required parameter 'path' is set
    if (path == null) {
       throw new ApiException(400, "Missing the required parameter 'path' when calling fileopsDeletePost");
    }
    
    // create path and map variables
    String path = "/fileops/delete".replaceAll("\\{format\\}","json");
```

```
Variable 'path' is already defined in the scope
```

Unfortunately, I am unable to change the query string parameter of the API I'm using (dropbox). A possible fix would be adding local parameters to the [reserved list](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L34) but that would make _path an invalid query string parameter.  Another solution would be to qualify local parameters in the mustache file with some 'codegen' prefix.  If there are any other workarounds I'd be happy to go that route instead. 

Thanks!

**Comment by wing328** [comment]
@RMarinaro thanks for reporting the issue. I think other clients (e.g. PHP, Python) may encounter similar issue. My suggested solution is to name the local variable differently (e.g. with _Swagger prefix). Naming collision may still occur but less likely.

**Comment by RMarinaro** [comment]
Thanks for the quick reply @wing328, is there any way to add this to the language configuration? e.g. "variablePrefix": "_swagger"? Otherwise the best practice would be to fork, and tweak the mustache file?

**Comment by wing328** [comment]
I agree that ideally the local variable prefix should be configurable. If it's a bit too much work, I'll implement that as a day 2 requirement. Would that be ok ?

**Comment by RMarinaro** [comment]
I'm happy to take a look at it (if you guys are accepting pulls) for at least the java stuff, but I'm not sure where these config files are parsed. Can you point me in the right direction and let me know the general strategy for adding a new json configuration parameter?

**Comment by webron** [comment]
We thrive on PRs.

**Comment by RMarinaro** [comment]
Is there any way to run the integration tests locally, or do contributors just open up PRs? I apologize if this is answered somewhere else. Thanks!

**Comment by wing328** [comment]
@RMarinaro sorry for missing your question. To run the test locally, please run `mvn verify -Psamples`
