### ISSUE TITLE
Flash code generator Java class missing

### ISSUE THREAD

**Issue by nViso** [swagger-api/swagger-codegen#1072]
Hi,

In the resources there is a folder for Flash however there is no Java class for this language in the code generator. Is actionscript / Flash intended to be supported? Does anyone have a working generator as we are interested to use it and support it.

Thanks,
Tim

**Comment by wing328** [comment]
@nViso thanks for offering help to support it.

It was not migrated from 1.2 to 2.0 during the Swagger spec upgrade. If it's not urgent, I can spend some time this weekend to come up with a working generator for Flash but would need your help to verify/test it.

**Comment by nViso** [comment]
That would be fantastic. Actually we have resources that we can allocate to testing / verifying it starting from next Monday, so if you can put something together as a starting point over the weekend it would be perfect.

**Comment by wing328** [comment]
@nViso I've filed #1079 to add back the flash generator. I think it should be good enough for review after fixing issue with templates, default value, etc. (I do not have Flex builder installed so can't tell if the code has any syntax error)

Please kindly help review the output here: https://github.com/wing328/swagger-codegen/tree/add_flash_generator/samples/client/petstore/flash/src/main/flex

**Comment by wing328** [comment]
@nViso the PR has been merged and you can find the flash generator in the develop_2.0 branch. To generate the sample, please run `mvn clean && ./bin/flash-petstore.sh`

**Comment by fehguy** [comment]
looks like it's merged and this can be closed

**Comment by wing328** [comment]
@nViso may I know if you've a chance to test the flash generator, which is now available in `master`? let me know if you found any issue and we can work together to address those (if you need my help with the fix).
