### ISSUE TITLE
Code generation for Slim PHP framework

### ISSUE THREAD

**Issue by Zyles** [swagger-api/swagger-codegen#1075]
Please consider adding code generation for server in Slim PHP framework.

**Comment by wing328** [comment]
@Zyles currently, we have code generator for Silex in `develop_2.0` branch. Here is the code samples for Petstore: https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples/server/petstore/silex/SwaggerServer 

We do not have anything for Slim PHP framework at the moment. Is that something you would like to contribute? We (community) can help you on that and the code generator for Slim PHP framework would be a good starting point.

**Comment by wing328** [comment]
@Zyles if you can provide the implementation of Slim PHP framework for the following endpoints in Petstore:
[addPet](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L29)
[getPetById](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L216)
[updatePetWithForm](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L263)
[deletePet](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L314)

We should be able to reverse-engineer the code back into the mustache template. Thanks in advance.

**Comment by Zyles** [comment]
Not sure how to do this. Also it might be best to wait for Slim 3 to be released as 2 will soon be deprecated anyway.

**Comment by jfastnacht** [comment]
[Slim Framework 3.0.0 RC2](https://github.com/slimphp/Slim/tree/3.0.0-RC2) is released. Is someone already working on this issue or do you wait for a full release?

**Comment by wing328** [comment]
@jfastnacht personally I don't think we need a full release and I'm not aware of anyone working on it at the moment. Do you have cycle to help implement it? If yes, I can work with you on it.

**Comment by jfastnacht** [comment]
@wing328 I'd like to give it a try if no one else wants to rush it. It might take some time.

**Comment by jfastnacht** [comment]
I've made a fork and work on the Slim support in a seperate branch at https://github.com/EduGraph/swagger-codegen/tree/issue-1075 . I've already added basic Slim support based on silex-PHP. It's still WIP! Just wanted to mention that I'm on it.

**Comment by wing328** [comment]
@jfastnacht :+1:  Let us know if you need any help :)

**Comment by jfastnacht** [comment]
I'd like to have some feedback on my changes in https://github.com/EduGraph/swagger-codegen/tree/issue-1075 
Thank you!

**Comment by wing328** [comment]
@jfastnacht overall it looks good :)

Do you mind submitting a PR so that I can leave some comments to start the discussion?
