### ISSUE TITLE
Could not resolve dependencies on mvn package

### ISSUE THREAD

**Issue by kfedorov91** [swagger-api/swagger-codegen#1078]
After running `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar meta -o custom -n CustomCodegen -p com.custom` and then `mvn package` from the generated project I get the error `[ERROR] Failed to execute goal on project custom-swagger-codegen: Could not resolve dependencies for project io.swagger:custom-swagger-codegen:jar:1.0.0: Failure to find io.swagger:swagger-codegen:jar:2.1.2-M1`. I'm on the master branch. I get the same error on the develop_2.0 branch except the main project itself can't resolve dependencies on that branch.

**Comment by wing328** [comment]
@kfedorov91 I've submitted #1080 (merged) to fix the issue.

Please try again with the `develop_2.0` branch to see if you still experience the same issue.

**Comment by wing328** [comment]
@kfedorov91 closing the issue as we've not heard from you.
