### ISSUE TITLE
C# - Swagger Codegen WithHttpInfo methods do not return 4xx-5xx responses but throw generic error

### ISSUE THREAD

**Issue by Christian-Oleson** [swagger-api/swagger-codegen#10825]
##### Description
Previously, the C# swagger codegen items, when generated, would not throw an Exception when a 4xx or 5xx response was received with the WithHttpInfo versions only. This allowed the user to then handle these responses gracefully (e.g. what if a particular resource is not found). Now, when regenerating an Api, these methods throw an Exception (not even an ApiException). 

##### Swagger-codegen version
2.4.17 (also exists in latest 2.4.18)

##### Swagger declaration file content or url
(this.json)
{
	"packageName": "Ed.Api",
	"targetFramework": "v5.0",
	"netCoreProjectFile" : true
}
----
["/req/User/GetUserAccessById": {
"get": {
"tags": [
"User"
],
"summary": "Get's the user's access via their Id",
"operationId": "User_GetUserSAccessById",
"consumes": [ ],
"produces": [
"application/json",
"text/json"
],
"parameters": [
{
"name": "id",
"in": "query",
"description": "",
"required": true,
"type": "string",
"format": "uuid"
}
],
"responses": {
"200": {
"description": "The user was found and their access has been retrieved",
"schema": {
"type": "array",
"items": {
"$ref": "#/definitions/Business.DTO.UserAccessDTO"
}
}
},
"404": {
"description": "The user or access was not found"
}
}
}
},](url)

##### Command line used for generation
java -jar swagger-codegen-cli-2.4.17.jar generate -l csharp -c this.json -i https://localhost/API/swagger/docs/v1 -o ../Api/Generated

##### Steps to reproduce
1. Regenerate the code
2. Call the WithHttpInfo (or WithHttpInfoAsync method from the generated ApiClient)
3. Make sure the response will be a 4xx
4. Verify that an exception is thrown, you cannot handle the ApiResponse

##### Related issues/PRs
None?

##### Suggest a fix/enhancement
Don't throw an Exception, or at the very least don't throw anything aside from an ApiException. Ideally, a 4xx error in the WithHttpInfo response will allow you to handle a 404 or alike without an exception. This is so you can make sure to avoid the costly Try/Catch for logic, as this kills performance

**Comment by Christian-Oleson** [comment]
@HugoMario , per your request

**Comment by HugoMario** [comment]
thanks @Christian-Oleson

**Comment by HugoMario** [comment]
Hello @Christian-Oleson, sorry for this long delay.

I was looking into this, and noted that the exception implementation is present for almost 5 years from [this commit](https://github.com/swagger-api/swagger-codegen/commit/fafcd33e276faf28966813a6e81f19d1a2b7c242). Besides the lot of changes that have been made on api template file, the exception stuff is still present, so i'm not sure to change something that could affect many users.

I propose you to use custom templates for the changes you want. Let me know if you need help with that, and i can provide you a template without the exception handling.

Going to close the issue, since i dont see this as a problem.

**Comment by Christian-Oleson** [comment]
> Hello @Christian-Oleson, sorry for this long delay.
> 
> I was looking into this, and noted that the exception implementation is present for almost 5 years from [this commit](https://github.com/swagger-api/swagger-codegen/commit/fafcd33e276faf28966813a6e81f19d1a2b7c242). Besides the lot of changes that have been made on api template file, the exception stuff is still present, so i'm not sure to change something that could affect many users.
> 
> I propose you to use custom templates for the changes you want. Let me know if you need help with that, and i can provide you a template without the exception handling.
> 
> Going to close the issue, since i dont see this as a problem.

Thanks, Hugo,
While I disagree with the implementation, I understand why this has been closed. I've done exactly what you mentioned (as of the day I reported this). I prevented the exception from being thrown by returning when results are not a 2xx or 3xx via mustache templates. Likewise, I needed custom templating for implementing a retry policy anyways, so I'm fine with this being closed.

**Comment by Hollerweger** [comment]
Current implementation makes little sense. 
Why having a ResponseEntity when still an Exception is thrown?
At least for a new major version a fix should be considered.
