### ISSUE TITLE
codegen.v3:swagger-codegen-maven-plugin 3.0.22 / 3.0.23 : can't parse OpenAPI YAML when servers url section present.

### ISSUE THREAD

**Issue by dtoch** [swagger-api/swagger-codegen#10823]
##### Description

When using swagger-codegen-maven-plugin 3.0.22 / 3.0.23 to generate the code for an OpenAPI YAML file that contains the servers url section, following error occurs:

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (String)"openapi: 3.0.0

This problem is only present with the maven plugin and not when invoking swagger-codegen-cli e.g. using :  

java -jar swagger-codegen-cli-3.0.23.jar generate -l spring -o output -i testbug.yaml

##### Swagger-codegen-maven-plugin version

Regression. The problem is present in swagger-codegen-maven-plugin 3.0.22 / 3.0.23 but not in 3.0.21 or lower.

Also the bug is only present when invoking the Maven plugin (not when invoking swagger-codegen-cli).

##### Swagger declaration file content or url

testbug.yaml:

```yaml
openapi: 3.0.0
info:
  title: "testbug"
  version: "0.1"
servers: 
  - url: '/test'
paths:
  /testbug/:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                myPart:
                  type: object
              required:
                - myPart
      responses:
        "200":
          description: OK
```

pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>test</artifactId>
    <groupId>test</groupId>
    <version>1</version>
    <build>
        <plugins>
            <plugin>
                <groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.23</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/testbug.yaml</inputSpec>
                            <language>java</language>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

##### Command line used for generation

mvn generate-sources

##### Steps to reproduce

mvn generate-sources

##### Related issues/PRs

None.

##### Suggest a fix/enhancement

None.

**Comment by SlavchoArsovski** [comment]
Hi @dtoch,

this issue is same as https://github.com/swagger-api/swagger-codegen/issues/10844.

It only happens on windows based machine.

Best,
Slavcho

**Comment by SlavchoArsovski** [comment]
PR pending:
https://github.com/swagger-api/swagger-codegen/pull/10886

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen/pull/10886
