### ISSUE TITLE
No Documentation in CodegenConfig.java

### ISSUE THREAD

**Issue by kfedorov91** [swagger-api/swagger-codegen#1084]
CodegenConfig.java needs to be implemented by every custom codegen class and yet it has NO doc comments and ALL of the method names are vague and confusing. "fromModel" ? From model to what? Why would I want to override that? When is it used? "generateExamplePath" ? What is an example path? Why would I want to generate one in the first place? Where is it used?

**Comment by wing328** [comment]
@kfedorov91 agree with you that the documentation in the code can be further improved.

If you've cycle, please help document it (assuming you fundamentally understand how the codegen works)

**Comment by crissdev** [comment]
Some documentation around workflow would be great. It takes a lot of time to figure out if I need to overwrite a method or append to some field. Honestly I know very few about Java, so having some sort of diagram of function calls would be great. I hope someone who sees the whole picture and has time will share that.

**Comment by wing328** [comment]
@kfedorov91 @crissdev I submitted https://github.com/swagger-api/swagger-codegen/pull/1438 (merged into master) to improve the documentation a bit. Will try to document more when time permits.

**Comment by crissdev** [comment]
@wing328 Thanks.
