### ISSUE TITLE
After generated java client, this part of code(jsonReader.nextObject()) can not be compiled by maven.

### ISSUE THREAD

**Issue by yanfemao** [swagger-api/swagger-codegen#10866]
In these files:
/src/main/java/io/swagger/client/model/SystemStatus.java;
/src/main/java/io/swagger/client/model/QuoteReq.java;
/src/main/java/io/swagger/client/model/Field.java;
/src/main/java/io/swagger/client/model/APIField.java;
/src/main/java/io/swagger/client/model/GetFieldsReq.java.

Contained code can not be compiled by maven:
     `@Override
      public XXXEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextObject();
        return StatusEnum.fromValue(String.valueOf(value));
      }`

Maven install cmd log(Maven3.6.1/Java1.8.0_211):
[ERROR] COMPILATION ERROR:
[INFO] ----------------------------------------------- --------------
[ERROR] /java-client-generatedOld/src/main/java/io/swagger/client/model/SystemStatus.java: [74,34] Symbol not found
  Symbol: Method nextObject ()
  Location: Variables of type com.google.gson.stream.JsonReader jsonReader
[ERROR] /java-client-generatedOld/src/main/java/io/swagger/client/model/QuoteReq.java: [79,34] Cannot find symbol
  Symbol: Method nextObject ()
  Location: Variables of type com.google.gson.stream.JsonReader jsonReader
[ERROR] /java-client-generatedOld/src/main/java/io/swagger/client/model/Field.java: [94,34] Cannot find symbol
  Symbol: Method nextObject ()
  Location: Variables of type com.google.gson.stream.JsonReader jsonReader
[ERROR] /java-client-generatedOld/src/main/java/io/swagger/client/model/APIField.java: [91,34] Symbol not found
  Symbol: Method nextObject ()
  Location: Variables of type com.google.gson.stream.JsonReader jsonReader
[ERROR] /java-client-generatedOld/src/main/java/io/swagger/client/model/GetFieldsReq.java: [73,34] Cannot find symbol
  Symbol: Method nextObject ()
  Location: Variables of type com.google.gson.stream.JsonReader jsonReader
[INFO] 5 errors

**Comment by izabelacg** [comment]
+1 I'm also seeing a similar issue in generated code. I'm running swagger-codegen version `3.0.24`

**Comment by rhvonlehe** [comment]
I have a similar issue with swagger-codegen version 2.4.18 generating for java.  The generated code has dependency:
`import com.google.gson.stream.JsonReader;`

but JsonReader has no method `nextObject()`.

**Comment by yanfemao** [comment]
I generated a usable java client using swaggerHub.But it still is a bug that existed in swagger-codegen, needs to be fixed.

**Comment by killvetrov** [comment]
I'm also having this issue, seems to be a regression, as before v3.0.24 it generated correct line `String value = jsonReader.nextString()`

**Comment by izabelacg** [comment]
Seems to be related with this other issue #10871

**Comment by yanfemao** [comment]
Already fixed, thanks for this guy's effort.
https://github.com/swagger-api/swagger-codegen-generators/pull/851/files
