### ISSUE TITLE
python client: add configuration for SSL certificate validation

### ISSUE THREAD

**Issue by yzats** [swagger-api/swagger-codegen#1086]
Similar to other clients generated by codegen, add run-time python client options to 

a) specify ssl certificate bundle path
b) disable ssl certificate validation (so that clients could be used against servers with self-signed certificates)

**Comment by wing328** [comment]
@yzats yes, the same feature will be rolled out to python client soon.

**Comment by geekerzp** [comment]
@yzats fixed in https://github.com/swagger-api/swagger-codegen/pull/1132

**Comment by wing328** [comment]
@yzats PR merge into master. Issue closed.
