### ISSUE TITLE
Python Client: All are generated as "SwaggerPetstore"

### ISSUE THREAD

**Issue by mach-kernel** [swagger-api/swagger-codegen#1087]
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java#L16

Please fix this.

**Comment by who** [comment]
@mach-kernel I believe that has been fixed in the yet-to-be-released develop_2.0 branch.

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java

**Comment by wing328** [comment]
@mach-kernel it's already addressed in `develop_2.0` as mentioned by @who.

Please reopen this issue if you still encounter error.
