### ISSUE TITLE
[JAVA] useOas2 config option is getting overwritten

### ISSUE THREAD

**Issue by sleicht** [swagger-api/swagger-codegen#10879]
##### Description
Setting `<useOas2>true</useOas2>` in maven plugin configuration is getting overwritten by the option USE_OAS2_OPTION which gets set in `setLanguageArguments(...)`.

##### Swagger-codegen version
`3.0.24`

##### Suggest a fix/enhancement
On following Line I either would expect a `&&` or the USE_OAS2_OPTION should also be on configuration level instead of configOptions. So `codegenArguments` would also have this option defined from start.
https://github.com/swagger-api/swagger-codegen/blob/8e4cc54eda7b3d12877617b31da2e0535b0b256d/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/DefaultGenerator.java#L205

**Comment by sleicht** [comment]
Please accept proposed pull request. Usage of v3 apis with old swagger v2 dependencies is not possible as it is.

**Comment by frantuma** [comment]
fixed in #10880

**Comment by sleicht** [comment]
Thank you, @frantuma
