### ISSUE TITLE
[Question] how to download swagger-codegen-cli.jar file

### ISSUE THREAD

**Issue by saostad** [swagger-api/swagger-codegen#10946]
Hey, 
I have tried to find the swagger-codegen-cli.jar file in the release section or other parts of this repo, also tried to compile from source code but my system doesn't have all the required java dependencies to compile and keep getting me error messages. 
is there any place that I can get compiled version of the new v2 release?

**Comment by albertoZurini** [comment]
Home of the repo: CTRL+F "wget". Good luck with codegen!
```
# Download current stable 2.x.x branch (Swagger and OpenAPI version 2)
wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.19/swagger-codegen-cli-2.4.19.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar help

# Download current stable 3.x.x branch (OpenAPI version 3)
wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.25/swagger-codegen-cli-3.0.25.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar --help
```
