### ISSUE TITLE
[CSharp] ProblemDetails generation goes wrong

### ISSUE THREAD

**Issue by fabianschurz** [swagger-api/swagger-codegen#10976]
##### Description

When generating code for my api swagger codegen generates a model for "ProblemDetails" which is broken. Because of that i cannot build the solution. ProblemDetails is the model being sent on 401 (Unauthorized) & 400 (BadRequest). I added the ProducesResponseType Flags to my controller which shows (400 - ProblemDetails) as possible return value.

The schema in swagger looks like this:
![image](https://user-images.githubusercontent.com/17854304/114677724-dee95700-9d0a-11eb-8ea0-5b4b53414b9f.png)

The broken stuff:
![image](https://user-images.githubusercontent.com/17854304/114680136-22dd5b80-9d0d-11eb-9fc2-163f4058c8a9.png)
![image](https://user-images.githubusercontent.com/17854304/114678726-d1809c80-9d0b-11eb-8cb9-555ca322dfbb.png)

##### Swagger-codegen version

I'm using the cli docker image version 3.0.25

##### Swagger declaration file content or url

I don't want to send the complete json because it contains sensitive informations.

```json
"responses": {
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
```

##### Command line used for generation

docker run --rm -v //c/Users/myuser/tmp:/local swaggerapi/swagger-codegen-cli-v3:3.0.25 generate -i https://myswaggerurl -l csharp -o /local/out -D packageName=Somecompany.Path.Project targetFramework=v5.0 netCoreProjectFile=true

##### Steps to reproduce
Make a C# ASP.NET Core API Project. Add [ProducesResponseType(StatusCodes.Status400BadRequest)] to any controller method or to the whole controller. Run swagger-codegen against your api-

##### Related issues/PRs

I did not find any

##### Suggest a fix/enhancement

Generation of the class ProblemDetails should be succesfull.

**Comment by sw-ngoc** [comment]
I'm having the same issue, and even when I specify the type being returned with the response like this, it's still `ProblemDetails` in Swagger.

`[ProducesResponseType(typeof(void), Microsoft.AspNetCore.Http.StatusCodes.Status401Unauthorized)]`

**Comment by fabianschurz** [comment]
@sw-ngoc Switched to openapi generator which was a fork of this and is more active.
