### ISSUE TITLE
Need to avoid language keywords in enums

### ISSUE THREAD

**Issue by c-knowles** [swagger-api/swagger-codegen#1102]
I've been trying out some Java API client code gen on a few APIs and encountered some issues with the enum generation due to the way the values are placed directly inside a Java enum. I hit both keyword issues and enum value starting with a numeric, both of which are not allowed in Java which means the code generated fails to compile.

One example I was trying to generate a client API for is the Runscope API:
- "interval" on https://www.runscope.com/docs/api/schedules starts with a numeric
- "emails.notify_on" on https://www.runscope.com/docs/api/environments uses "switch" which is a Java keyword

I could not find anything in the Swagger Spec to define this, but perhaps I missed something. Otherwise perhaps this should be dealt with at the code generation level somehow. For example, something like this while just returning the JSON property as a String (using getValue below):

```
public enum IntervalEnum {
  onem("1m"),  fivem("5m"),  fifteenm("15m");

  private String value;

  public IntervalEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }
};
```

I'm pretty new to this project so wanted some feedback before working on a pull request.

**Comment by xhh** [comment]
@c-knowles please have a look at #1126 and let me know if it works for you

**Comment by c-knowles** [comment]
@xhh Looks great to me and will solve the issues with Java keywords in the enums, thanks not only the quick response but the update!
