### ISSUE TITLE
typescript-axios client generates untyped models

### ISSUE THREAD

**Issue by chuej** [swagger-api/swagger-codegen#11043]
##### Description

When generating a client for `typescript-axios`, the models come back untyped.  This is evident in the samples. See [this typescript-axios client model](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/samples/client/petstore/typescript-axios/petstore-mixed/models/pet.ts) vs [this typescript-angular client model](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/samples/client/petstore/typescript-angular-v4/npm/model/pet.ts#L19-L27). 

##### Swagger-codegen version

3.0.26

##### Swagger declaration file content or url

https://github.com/swagger-api/swagger-codegen/blob/3.0.0/samples/yaml/pet.yml

##### Command line used for generation

n/a

##### Steps to reproduce

See links in description.

##### Related issues/PRs
[Feature request for typescript-axios client generation](https://github.com/swagger-api/swagger-codegen/issues/9415)
[Comment on another ticket pointing out the same issue](https://github.com/swagger-api/swagger-codegen/issues/10595#issuecomment-756725694)

##### Suggest a fix/enhancement

What's strange is that the [type annotation above the field declaration](https://github.com/swagger-api/swagger-codegen/blob/3.0.0/samples/client/petstore/typescript-axios/petstore-mixed/models/pet.ts#L22) has the proper type; I was looking [here](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/handlebars/typescript-axios/modelGeneric.mustache#L14-L20) at the mustache templates for `typescript-axios` and it looks like it's using the same `datatype` variable to interpolate in both places, so not sure where things are going wrong.

**Comment by pablos91** [comment]
I'm facing the same issue here. Even though the proper model sits in the comment, property has "any" type. Whatsoever the model is being generated and exported so I can cast the any object to CustomerSearchResponse. The only thing - it is not being used in the parent object.

```TS
export interface CustomerSearchResponseServiceResponse {
    /**
     *
     * @type {number}
     * @memberof CustomerSearchResponseServiceResponse
     */
    status?: any;
    /**
     *
     * @type {number}
     * @memberof CustomerSearchResponseServiceResponse
     */
    substatus?: any | null;
    /**
     *
     * @type {CustomerSearchResponse}
     * @memberof CustomerSearchResponseServiceResponse
     */
    data?: any;
}
```

**Comment by chuej** [comment]
My workaround is to generate the `typescript-angular` client and copy the models into the `typescript-axios` client since the models follow the same signatures. The only difference is that `typescript-angular` puts models at `model/models.ts` and `typescript-axios` puts them at `models/index.ts` so there some `mv`ing around, but works for my use case.

**Comment by HugoMario** [comment]
hey @balzdur 
Sorry for delay, i will

**Comment by Miyagee** [comment]
Any progress on the PR?
