### ISSUE TITLE
PHP client sourcecode generated broken for guzzlehttp/psr7 v 2.0.0

### ISSUE THREAD

**Issue by riccafi** [swagger-api/swagger-codegen#11087]
##### Description
Library guzzlehttp/psr7 has released new 2.0.0 version. [changelog](https://github.com/guzzle/psr7/blob/master/CHANGELOG.md) .
With version 1.* guzzlehttp/psr7 started to introduce `Query::build` class method in place of future deprecated function `build_query `.
Since version 2.0.0, old deprecated function `build_query ` has been dropped going to require `Query::build` instead.
Swagger codegen generates sourcecode using the old function that is no more existent, giving run time exception.

##### Swagger-codegen version
3.0.27

##### Command line used for generation
./bin/php-petstore.sh 

##### Steps to reproduce
Download the source code.
Build the code.
Launch the previous command (`./bin/php-petstore.sh` ).

##### Related issues/PRs

[PR guzzle http psr7 2.0 compliant](https://github.com/swagger-api/swagger-codegen/pull/11086)

**Comment by frantuma** [comment]
fixed by #11104 (including and replacing #11086)
