### ISSUE TITLE
GenerateTest.java is under directory io.swagger.codegen instead of io/swagger/codegen

### ISSUE THREAD

**Issue by pablograna** [swagger-api/swagger-codegen#1112]
Just:

mv ./modules/swagger-codegen-cli/src/test/java/io.swagger.codegen/GenerateTest.java ./modules/swagger-codegen-cli/src/test/java/io/swagger/codegen

Otherwise, eclipse will complain on the GenerateTest package declaration.

**Comment by fehguy** [comment]
see #1113

**Comment by pablograna** [comment]
UOUH, that was fast, thanks!!!

**Comment by fehguy** [comment]
Working on a release right now so I'd like to close the easy stuff fast :)
