### ISSUE TITLE
There is no docker image for third version 

### ISSUE THREAD

**Issue by Legion112** [swagger-api/swagger-codegen#11161]
##### Description
There is no docker image for third version https://hub.docker.com/r/swaggerapi/swagger-generator/

##### Swagger-codegen version
-

##### Swagger declaration file content or url
-
##### Command line used for generation

```shell
docker run --rm swaggerapi/swagger-codegen-cli generate -l openapi-yaml -i ./specification/v2.yaml -o ./docs -DoutputFile=openapi.yaml
```
##### Steps to reproduce
Run the line above

##### Suggest a fix/enhancement
Set up the auto-build for 3 versions of the tool.

**Comment by 4n70w4** [comment]
The same issue!

**Comment by 4n70w4** [comment]
https://hub.docker.com/r/swaggerapi/swagger-generator-v3
