### ISSUE TITLE
PHP codegen results in broken syntax

### ISSUE THREAD

**Issue by jamiehannaford** [swagger-api/swagger-codegen#1118]
When I generate a PHP client based on [this Swagger schema](https://gist.github.com/jamiehannaford/0b92a57e6cbf9ee809e6), I get broken syntax:

![](http://i.imgur.com/eWUECy1.png)

**Comment by jamiehannaford** [comment]
It happens in Python too. I think the codegen _assumes_ a parameter's name will be all one word, but this is not mandated in the 2.0 spec. I'll close this, but I think it would be useful to add in some logic that converts strings to the respective case of the language (camelCase for PHP, snake_case for python etc.)

**Comment by wing328** [comment]
Thanks for the reporting the issue. I agree with you that the parameter name should be sanitized (e.g. replacing space with _)

For python, we should have done it to make the parameter name to follow snake_case: [PythonClientCodegen.java#L180](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java#L180)

For php, it's also using snake_case at the moment: [PhpClientCodegen.java#L294](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java#L294)

**Comment by jamiehannaford** [comment]
@wing328 Okay. According to [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md), PHP should be using camelCase.

**Comment by wing328** [comment]
Yes, we'll provide an option so that parameter name will be in camelCase.

**Comment by wing328** [comment]
@jamiehannaford submitted #1125 with a CLI option use camelCase for variable (parameter, property) naming. Would that meet your requirement ?

**Comment by jamiehannaford** [comment]
@wing328 Yes, that looks good - thanks for adding. IMO, all syntax styling should abide by PSR-2 by default since it's effectively the industry standard now. I think we should be assuming people want the standard, but also allow them to override with granular options (such as the one you've just added).

**Comment by wing328** [comment]
@jamiehannaford I agree with you. Previously we'd other PRs to make the PHP client more conform to the PSR-2 standard. This one is left over and thanks again for bringing it up.

If you find other syntax styling not conforming to PSR-2, please kindly point it out to us (by opening a new issue for tracking)

**Comment by wing328** [comment]
@jamiehannaford FYI. PR merged into master

**Comment by wing328** [comment]
@jamiehannaford. FYI. #1139 submitted to handle space (converted to _) in parameter name
