### ISSUE TITLE
Scala - CodeGen v 2.1.3 - Response.getStatusInfo().getStatusCode()

### ISSUE THREAD

**Issue by sundriver** [swagger-api/swagger-codegen#1128]
Hi,
 It looks like in the ApiInvoker template for plain scala code gen, 

response.getStatusInfo().getStatusCode()

needs to be replaced with

response.getStatus

**Comment by fehguy** [comment]
Are you sure?  Travis-ci is running unit tests on the build, the scala project is part of it as well.

**Comment by sundriver** [comment]
The generated scala code compiles but when I use it, I get Response.getStatusInfo().getStatusCode() doesn’t exist.

**Comment by fehguy** [comment]
What are your dependencies?

**Comment by sundriver** [comment]
Here is the SBT dependencies for the project using swagger generated code (com.sensorfront …)

libraryDependencies ++= Seq(
  "com.sensorfront" % "scala-client" % "1.0.0-snapshot",
  "com.sun.jersey" % "jersey-core" % "1.19",
  "com.sun.jersey.contribs" % "jersey-multipart" % "1.19"
)

**Comment by xhh** [comment]
`ClientResponse` in jersey-client 1.19 does have a [`getStatusInfo `](https://jersey.java.net/apidocs/1.19/jersey/com/sun/jersey/api/client/ClientResponse.html#getStatusInfo()) method, returning `Response.StatusType` that has a [`getStatusCode`](https://jersey.java.net/apidocs/1.19/jersey/javax/ws/rs/core/Response.StatusType.html#getStatusCode()) method.

I tried petstore scala client and can not reproduce this issue. @sundriver could you post the full stack trace of the exception, and try the petstore scala client as well (located at *samples/client/petstore/scala* in the repo)?

**Comment by wing328** [comment]
@sundriver closing this issue for now as we've not heard further update from you. Please reopen this issue if needed.
