### ISSUE TITLE
unknown `format` value causes a NullPointerException

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#1133]
**Summary**
When trying to run swager-codegen on a swagger definition with a unknown format name (like in the example below `iso-4217-alpha` for the currency code or `decimal` for the number), it breaks with a NullPointerException.

(I tried this with current master, commit 392e5172b.)

**Reproducible by**

File (bug-trigger.yaml):

    swagger: '2.0'
    info:
      title: Swagger Codegen bug trigger
      description: |
         This demonstrates a bug in swagger-codegen.
      version: 0.0.1
    basePath: /api
    definitions:
      money:
        type: object
        properties:
    #      currency:
    #        type: string
    #        format: iso-4217-alpha
          amount:
            type: number
            format: decimal

Command line:

    java -jar /home/paulo/.m2/repository/io/swagger/swagger-codegen-cli/2.1.4-SNAPSHOT/swagger-codegen-cli-2.1.4-SNAPSHOT.jar generate -i src/main/resources/api/bug-trigger.yaml -l java -o target/generated-sources/swagger-codegen

Standard output:

    reading from src/main/resources/api/bug-trigger.yaml
    (was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["amount"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["money"])
    reading from src/main/resources/api/bug-trigger.yaml
    (was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["amount"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["money"])

Standard error:

```
367 [main] WARN io.swagger.util.PropertyDeserializer - no property from number, decimal, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=decimal, READ_ONLY=null, VENDOR_EXTENSIONS={}}
371 [main] WARN io.swagger.util.PropertyDeserializer - no property from number, decimal, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=number, FORMAT=decimal, READ_ONLY=null, VENDOR_EXTENSIONS={}}
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: src/main/resources/api/bug-trigger.yaml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:60)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:134)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

It looks like the exception whose stack trace is shown here comes only from trying to fall back to a swagger 1 parser, after the original parsing causes an error (no PropertyBuilder.Processor is found for the `(type: number, format: decimal)` combination).

When removing the comment signs, I get a similar error for `(type: string, format: iso-4217-alpha)`.

**Expected behavior**

[The specification says](http://swagger.io/specification/#dataTypeFormat):

> Primitives have an optional modifier property `format`. Swagger uses several known formats to more finely define the data type being used. However, the `format` property is an open `string`-valued property, and can have any value to support documentation needs. Formats such as `"email"`, `"uuid"`, etc., can be used even though they are not defined by this specification.

I would interpret this that any format names should be allowed, including my invented `decimal` and `iso-4217-alpha`, and they should be handled by swagger-codegen just like if there was no format mentioned, assuming there is no special code to handle it. If I did interpret this wrong, maybe the spec needs clarification.

**Comment by ePaul** [comment]
The issue seems to be in swagger-core/swagger-models, not in swagger-codegen. I'll try to fix it there.

**Comment by wing328** [comment]
Closing this as I could no longer repeat the issue.
```
swagger-codegen|master⚡ ⇒   java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i /var/tmp/bug-trigger.yaml \
  -l java \
  -o /var/tmp/java/test
reading from /var/tmp/bug-trigger.yaml
writing file /var/tmp/java/test/src/main/java/io/swagger/client/model/Money.java
```
and currency is a string in the generated code.
```
public class Money   {

  private String currency = null;
  private BigDecimal amount = null;
```
