### ISSUE TITLE
Android client doesn't use ApiInvoker.parseDateTime()

### ISSUE THREAD

**Issue by kenhunt** [swagger-api/swagger-codegen#1134]
Symptom: I generated an Android client using a Swagger spec that uses 'date-time' on a model:

```
    "definitions": {
        "User": {
            "properties": {
                       <... >
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
            <...>
```
The server returns a string for "createdAt" field that should be accepted based on ApiInvoker's parseDateTime().
   (ex: "2015-08-21T20:36:44.000Z" ) 

The ApiInvoker.parseDateTime() is never called. Instead, gson's DefaultDateTypeAdapter's deserialize method is called, and an exception is thrown. (It doesn't expect milliseconds).

**Comment by xhh** [comment]
JSON model deserialization is done via Gson, which is using this date format for date/date-time properties (see [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/android-java/jsonUtil.mustache#L16)):
```java
gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
```

This format does expect milliseconds (tested and confirmed on my local), but the trailing `Z` in your example does fail to be deserialized: `2015-08-21T20:36:44.000Z`, changing it to `2015-08-21T20:36:44.000+0000` works.

The date format trailing `Z` is valid in ISO 8601, so it would be better to be supported here. I can prepare a PR for it if needed.

**Comment by samuelg** [comment]
This is also a problem for me.

The Android client should be able to deal with dates properly formatted with the format defined in the  Swagger spec. Having to reformat dates that are already spec compliant adds complexity that should not be necessary.

**Comment by fehguy** [comment]
Please open a PR for the templates, or suggest how the GSON decoder should handle the dates in a more lenient fashion.

**Comment by baogechen** [comment]
The correct format for iso 8601 is "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", with which the 'Z' will be parsed 。
