### ISSUE TITLE
Python codegen generates invalid function names

### ISSUE THREAD

**Issue by iwsmith** [swagger-api/swagger-codegen#1136]
Hi, 
Given a swagger yaml with an operationId containing a dot (as below) swagger-codgen outputs a / instead. This is an invalid syntax for a function name in python. I've tracked down the problem to the [underscore function](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L1261), which replaces a dot with a slash.

The fix likely has something to do with making underscore non-static so it can be overridden, but that is a non-trivial change so I didn't make it :-)

## Repro
This swagger.yaml
```
  /bulk/find:
    post:
      description: Returns publisher and paper_id for a set of titles
      operationId: app.bulk_find
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Bulk find request
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Returns an array of dictionaries containing metadata. If metadata cannot be found for a paper null wil be returned in that location.
```

produce this output `` def app/bulk_find(self, body, **kwargs):``

**Comment by wing328** [comment]
@iwsmith submitted #1139 to handle method name with special character (. is converted to _).

May I know how your swagger spec is generated? Is it using some 3rd-party plug-ins?

**Comment by wing328** [comment]
#1139 merged into master. Please reopen this issue if needed.
