### ISSUE TITLE
Maven plugin finishes silently (successfully) even when there is an exception during generation

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#1140]
Possibly introduced by #1052, `DefaultCodegen.generate()` just sets a status if there was any exception, but this status is not used by CodeGenMojo (line 164 in current master):

        new DefaultGenerator().opts(input).generate();

Thus if there is any exception during generation (caused either by a bug in the generator or a malformed swagger file), the generation stops at some point (in my example after the first Model was generated, because the second model hit a bug and threw a NullPointerException), but the maven build still finishes with the usual "BUILD SUCCESS" message.

The exception itself is also not shown anymore, which makes debugging it quite difficult.

**Comment by ePaul** [comment]
The same is true for the CLI version. See #1141 for an example where an exception is swallowed without any error message.

**Comment by ePaul** [comment]
For easier reproduction: If there is no `paths` entry in the swagger file, a NullPointerException is thrown in DefaultGenerator.processPaths, line 397 (because `paths` is null there), called from line 170 in generate().
```
swagger: '2.0'
info:
  title: Swagger Codegen bug trigger
  description: |
     This demonstrates a bug in swagger-codegen.
  version: 0.0.1
basePath: /api
#paths: {}
```
I guess that should also give a better error message.

**Comment by wing328** [comment]
@ePaul I just performed a test but could no longer repeat the issue with the spec (no path) you provided above. Let me know if you still experience the same NPE

**Comment by fehguy** [comment]
Please reopen if you're still having an issue.
