### ISSUE TITLE
Generated PHP classes sometimes contain invalid chars 

### ISSUE THREAD

**Issue by jamiehannaford** [swagger-api/swagger-codegen#1145]
If I reference the following in my Swagger schema:

```json
"parameters": [
   {
      "name": "cat",
      "in": "body",
      "description": "The JSON payload for the new cat",
      "required": true,
      "schema": {
         "$ref": "cat-new.json"
      }
   }
]
```

Then it will generate a model file called `Cat-new.php`, with a `Cat-new` class inside, which is [prohibited](http://php.net/manual/en/language.oop5.basic.php). Ideally we should be generating `CatNew` rather than `Cat_New`.

**Comment by wing328** [comment]
@jamiehannaford is `cat-new` a model? if yes, it should be defined as `#/definitions/CatNew`

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L238

Seems like the parameter is related to creating new "cat". I simply name it as just "cat"

**Comment by wing328** [comment]
@jamiehannaford also do you mind sharing with us how your swagger spec is generated? Is that using some third-party swagger plug-ins?

**Comment by jamiehannaford** [comment]
@wing328 But there are different permutations of the model, depending on the operation. For example, when creating a cat the user would not send an `id` property, which would be returned when all cats are listed.

All that's happening above is that I'm referencing an externally defined model schema. I'm not using a third-party plugin.

**Comment by wing328** [comment]
@jamiehannaford  Thanks for sharing with me how the swagger spec was created and it's definitely valid to use [relative schema file](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#relative-schema-file-example) in swagger spec.

But I couldn't repeat the issue with the following:
```
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": false,
            "schema": {
              "$ref": "new-Pet.json"
            }
          }
        ],
```
manually created a file named "new-Pet.json" and ran `./bin/php-petstore.sh` but didn't get any "New_Pet" model.

Do you mind sharing with me what the content of `catNew.json` looks like?

**Comment by jamiehannaford** [comment]
Sure, it's [here](https://gist.githubusercontent.com/jamiehannaford/98a693559ea8807315ad/raw/19e342acdfd44cd1422f823563ab6bdbfd60d1de/catNew.json). Please note I renamed it from `cat-new.json` to `catNew.json` after your first message

**Comment by wing328** [comment]
Thanks. But still no luck in reproducing the issue. I'll given it another try this weekend.

**Comment by xhh** [comment]
Hey @jamiehannaford, I can reproduce it with this model (in `definitions`):

```json
"cat-new": {
    "$ref": "cat-new.json"
}
```

which would generate the model file: *lib/Model/Cat-new.php*
Is your case like this? That is, it should have nothing to do with `parameters`.

If so, changing the key (model name) to `CatNew` will work:

```json
"CatNew": {
    "$ref": "cat-new.json"
}
```

**Comment by jamiehannaford** [comment]
@xhh Yep, that's it. 

I didn't see any documentation which indicated that camel case was the only acceptable format. IMO, the code generator needs to always convert class names so they end up being idiomatic in the outputted language, regardless of input.

**Comment by jamiehannaford** [comment]
Thanks @xhh! :smile:
