### ISSUE TITLE
jaxrs/spring-mvc: API methods have annotations with line breaks in their strings

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#1146]
**Summary**
When a `description` of a response has a line break in the swagger yaml (or json) and we generate for `jaxrs`, an annotation with a broken string literal is generated, which is not compilable in Java.

**Reproducible by**
bug-trigger.yaml:
```
swagger: '2.0'
info:
  title: Example API
  description: bla bla
basePath: /api
definitions:
  example:
    type: object
    properties: {}
paths:
  /example-path:
    put:
      summary: create or update the example.
      responses:
        201:
          description: |
            Example was created.

            No content.
```
Generation using the maven plugin:

			<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>2.1.4-SNAPSHOT</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<inputSpec>src/main/resources/api/bug-trigger.yaml</inputSpec>
					<language>jaxrs</language>
					<output>target/generated-sources/swagger-codegen</output>
					<addCompileSourceRoot>false</addCompileSourceRoot>
					<apiPackage>de.zalando.einkaufshelden.example.api</apiPackage>
					<modelPackage>de.zalando.einkaufshelden.example.model</modelPackage>
				</configuration>
			</plugin>

Generated file ExamplePathApi.java (there are other files generated, but this one shows the problem):
```
package de.zalando.einkaufshelden.example.api;

import de.zalando.einkaufshelden.example.model.*;
import de.zalando.einkaufshelden.example.api.ExamplePathApiService;
import de.zalando.einkaufshelden.example.api.factories.ExamplePathApiServiceFactory;

import io.swagger.annotations.ApiParam;

import com.sun.jersey.multipart.FormDataParam;


import java.util.List;
import de.zalando.einkaufshelden.example.api.NotFoundException;

import java.io.InputStream;

import com.sun.jersey.core.header.FormDataContentDisposition;
import com.sun.jersey.multipart.FormDataParam;

import javax.ws.rs.core.Response;
import javax.ws.rs.*;

@Path("/example-path")


@io.swagger.annotations.Api(value = "/example-path", description = "the example-path API")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JaxRSServerCodegen", date = "2015-08-28T15:38:47.345+02:00")
public class ExamplePathApi  {

   private final ExamplePathApiService delegate = ExamplePathApiServiceFactory.getExamplePathApi();

    @PUT
    
    
    
    @io.swagger.annotations.ApiOperation(value = "create or update the example.", notes = "", response = Void.class)
    @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 201, message = "Example was created.

No content.
", response = Void.class) })

    public Response examplePathPut()
    throws NotFoundException {
    return delegate.examplePathPut();
    }
}
```
The `message` attribute of the `@ApiResponse` annotation has a broken string literal, and thus the file cannot be compiled.

Using the `spring-mvc` language instead, the problem is in `Example-pathApi.java`, which has a broken class name (see #1142), and also has the same broken annotation:

```
package de.zalando.einkaufshelden.example.api;

import de.zalando.einkaufshelden.example.model.*;


import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

import static org.springframework.http.MediaType.*;

@Controller
@RequestMapping(value = "/example-path", produces = {APPLICATION_JSON_VALUE})
@Api(value = "/example-path", description = "the example-path API")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.SpringMVCServerCodegen", date = "2015-08-28T15:48:42.066+02:00")
public class Example-pathApi {
  

  @ApiOperation(value = "create or update the example.", notes = "", response = Void.class)
  @ApiResponses(value = { 
    @ApiResponse(code = 201, message = "Example was created.

No content.
") })
  @RequestMapping(value = "", 
    
    
    method = RequestMethod.PUT)
  public ResponseEntity<Void> examplePathPut()
      throws NotFoundException {
      // do some magic!
      return new ResponseEntity<Void>(HttpStatus.OK);
  }

  
}
```

**Expected behavior**
Those strings need to be sanitized before using them in the generated text.

In this concrete example, either replacing the line breaks by spaces or by a `\n` escape would be okay (though the trailing newline should be stripped).

(At some other places, e.g. for model descriptions, I've seen output with lots of `\n` in it, both in those annotations as well as in generated comments (which looks stupid). Only in string literals the line breaks should be escaped, not in comments.)

**Comment by ePaul** [comment]
The same happens for the operation's `summary` attribute.
I'm working on a pull-request to fix this (and also to remove the stupid `\n` in the models' descriptions).

**Comment by wing328** [comment]
PR merged

**Comment by XANDERM** [comment]
Hello, I have the same problem with the version 3.0.45 of maven swagger codegen plugin
 
 Example:
 description = "Status code update:
  0 - Processing,
  1 - Pending Signature,
  2 - Partly Signed,
  3 - Processed,
  7 - Cancelled,
  8 - Rejected,
  9 - Error" and my project don't compile...
  
  openApi code:
     description: |
        Status code update:
          0, Processing
          1, Pending Signature
          2, Partly Signed
          3, Processed
          7, Cancelled
          8, Rejected
          9, Error
