### ISSUE TITLE
The enum model is not fully generated

### ISSUE THREAD

**Issue by Richou** [swagger-api/swagger-codegen#1147]
Hello,

I'm using the swagger codegen version 2.1.0-M2 with the swagger spec 2.0, and I have noticed that enums generated in model are not completely generated.

For example : 

I have the following enum 

```java
public enum MyPrettyEnum {
     ENUM_1("Enum1", "The enum number one"),
     ENUM_2("Enum2", "The enum number two"),
     ENUM_3("Enum3", "The enum number three");

    private String key;
    private String label;

    MyPrettyEnum(String key, String label) {
         this.key = key;
         this.label = label;
    }

    public String getKey() {
        return this.key;
    }

    public String getLabel() {
        return this.display;
    }
}
```

But the swagger codegen generates 

```java

    ...
    public enum MyPrettyEnum {
         ENUM_1, ENUM_2, ENUM_3;
    }
    ...
```

Is that normal ? 
Is it fixed in version 2.1.2 ?

Best Regards.

**Comment by wing328** [comment]
@Richou the version you used was released a few months ago. Please use the latest version and let us know if you still encounter the issue.

**Comment by Richou** [comment]
@wing328 I've tried with the latest version (I presume it is the v2.1.3) but I have the same issue.

**Comment by wing328** [comment]
Closing this issue as we've not heard any update from you
