### ISSUE TITLE
Grouping of auto-generated classes in folders

### ISSUE THREAD

**Issue by sohail-aspose** [swagger-api/swagger-codegen#1155]
Hi,
I want to group auto-generated classes as follows:  
SwaggerClient
&nbsp;&nbsp;&nbsp;&nbsp;cells
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;api
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;model
&nbsp;&nbsp;&nbsp;&nbsp;words
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;api
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;model  
All API classes belongs to **cells module** should go into **api** sub-folder and model classes (definitions) into **model** sub-folder inside **cells** folder. Same should happen with **words** module.

What change should I make in Swagger Specification or Mustache Templates to make this happen.

Thanking you in anticipation.

**Comment by wing328** [comment]
@sohail-aspose I think you need to modify the codegen (Java class) in order to achieve the requirement above.

A possible workaround could be breaking the spec into 2 different spec for `cells` and `words` and move the auto-generated files under the same parent directory.

**Comment by wing328** [comment]
Closing this question as there's no further update.
