### ISSUE TITLE
HEAD path item is missing

### ISSUE THREAD

**Issue by arnested** [swagger-api/swagger-codegen#1156]
If I put HEAD methods in my API definition they don't appear in generated HTML.

An example. If I use the minimal example and just change the method from GET to HEAD:

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    head:
      responses:
        200:
          description: OK
```

Then I generate static HTML:

```sh
java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i minimal.yaml -o ~/docs
```

The method is not part of the generated documentation.

According to the specification HEAD should be a valid path item: http://swagger.io/specification/#pathItemHead

Bug? Or am I doing something wrong?

**Comment by wing328** [comment]
HEAD should be supported so it's bug.
