### ISSUE TITLE
basic authentication not listed in generated static HTML

### ISSUE THREAD

**Issue by arnested** [swagger-api/swagger-codegen#1158]
If I generate static HTML from the "basic-auth.yaml" example with:

``` sh
java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i basic-auth.yaml -o ~/docs
```

The generated HTML will have a "Access" heading but no security definitions will be listed under it and no security requirement will be listed under the path item either.

basic-auth.yaml:

``` yaml

---
swagger: '2.0'
info:
  version: "1.0.0"
  title: Basic Auth Example
  description: |
    An example for how to use Basic Auth with Swagger.
    Server code is available [here](https://github.com/mohsen1/basic-auth-server). It's running on Heroku.

    **User Name and Password**
    * User Name: `user`
    * Password: `pass`
host: basic-auth-server.herokuapp.com
schemes:
  - http
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /:
    get:
      security:
       - basicAuth: []
      responses:
        200:
          description:  Will send `Authenticated` if authentication is succesful, otherwise it will send `Unauthorized`
```

**Comment by arnested** [comment]
Trying the "security.yaml" I noticed that no security definitions or security requirements are listed in the generated static HTML either.

**Comment by wing328** [comment]
@arnested thanks for reporting the issue and would be great if you can submit a PR to improve the HTML documentation.

**Comment by NabiKAZ** [comment]
As said. The `securityDefinitions` block, does not appears in HTML generated!
This is important.

**Comment by wing328** [comment]
@NabiKAZ The PR #2929 should have added more info about security setting. Are you using the latest master to generate the documentation?

Also there's another doc generator: `html2`, which is definitely worthwhile to try.

**Comment by wing328** [comment]
Also worth sharing with you is that most API clients come with auto-generated documentation on how to use the API client, and the README contains info on the security settings: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/README.mustache#L111-L127

**Comment by NabiKAZ** [comment]
@wing328 
I use `swagger-codegen-cli-2.2.2`.
And I have `security` and `securityDefinitions` tags.
My command:
`java -jar swagger-codegen-cli-2.2.2.jar generate -l html2 -i api.yaml -o docs`
But does not appears any security block in html output.
But I try [another library ](https://github.com/Rebilly/ReDoc)and does not any problem.

**Comment by wing328** [comment]
@arnested you will need to build the JAR based on the latest master in order to use the enhancements in https://github.com/swagger-api/swagger-codegen/pull/2929

**Comment by wing328** [comment]
Added support for basic authentication:
```
  {{#hasAuthMethods}}
    <ol>
    {{#authMethods}}
      <li>{{#isBasic}}HTTP Basic Authentication{{/isBasic}}{{#isOAuth}}OAuth AuthorizationUrl:{{authorizationUrl}}TokenUrl:{{tokenUrl}}{{/isOAuth}}{{#isApiKey}}APIKey KeyParamName:{{keyParamName}} KeyInQuery:{{isKeyInQuery}} KeyInHeader:{{isKeyInHeader}}{{/isApiKey}}</li>
    {{/authMethods}}
    </ol>
  {{/hasAuthMethods}}
```
