### ISSUE TITLE
Generate sdk from swagger file with OpenAPI version: 3.1.0

### ISSUE THREAD

**Issue by ngouy** [swagger-api/swagger-codegen#11627]
I can't find anywhere where it's stated that OpenAPI 3.1.0 isn't supported (I see 3.X in the docs, so supposedly, 3.1.0 is supported)
But I can't find a way to make it work when we bump our OpenAPI version

Is it supported or not? I'm lost

**Comment by frantuma** [comment]
OpenAPI 3.1 is not yet supported, it's on the roadmap though, but no ETA at the moment

**Comment by ngouy** [comment]
Thanks for the reply

is there a place from where we can follow the progression?

**Comment by frantuma** [comment]
Codegen work has not started yet, it's based on finalization of support of OAS 3.1 in swagger-core and swagger-parser, please see [this comment](https://github.com/swagger-api/swagger-parser/issues/1535#issuecomment-936707841) for details

**Comment by ngouy** [comment]
Thanks, hasn't seen this ticket. Appologies for the duplicated

**Comment by daniel-klingensmith-jamf** [comment]
Looks like swagger-core and swagger-parser were updated to support 3.1 as of April, any updates on swagger-codegen?

btw, big fan of what you guys do.

**Comment by ilfa** [comment]
Hey!
Do you have any updates about OpenAPI 3.1? I saw [this article](https://swagger.io/blog/swagger-support-for-openapi-3-0-and-openapi-3-1/) about "Swagger support for OpenAPI 3.0 and OpenAPI 3.1" and there is no word about `swagger-codegen`, but there were updates about `swagger-core` and `swagger-parser`.

**Comment by ilfa** [comment]
Hey!
Will any updates about OpenAPI 3.1 follow?

**Comment by slifty** [comment]
It looks like there is a more recent issue for this: https://github.com/swagger-api/swagger-codegen/issues/12210
