### ISSUE TITLE
java: generated model class references non-existing "Object" class when using inline schema for property

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#1165]
**Summary**
When a model definition includes a property with an inline type definition, the generated Java model class refers to `Object` (in the same model package), which does not exist.

**Reproducible by**
Swagger YAML:
```
swagger: '2.0'
info:
  title: Swagger Codegen bug trigger
  description: |
     This demonstrates a bug in swagger-codegen.
  version: 0.0.1
basePath: /api
definitions:
  example:
    type: object
    properties:
      foo:
        type: object
        properties:
          bar:
            type: string
paths: {}
```
Generate with any Java language: (`java`, `jaxrs`, `spring-mvc`).

This will generate (in the model package) just one file Example.java:

```
package de.zalando.einkaufshelden.example.model;

import de.zalando.einkaufshelden.example.model.Object;

import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.JsonProperty;


@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.SpringMVCServerCodegen", date = "2015-08-31T15:41:08.374+02:00")
public class Example  {
  
  private Object foo = null;

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("foo")
  public Object getFoo() {
    return foo;
  }
  public void setFoo(Object foo) {
    this.foo = foo;
  }

  

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Example {\n");
    
    sb.append("  foo: ").append(foo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
```
This compilation unit imports a class `Object` (which itself is not generated), and tries to use it for the `foo` field and its getter + setter. This does not compile.

**Expected behaviour**
Some class is generated for the property type (with a different name than `Object`, preferably), and this is used for the field and getter/setter types.

**Workaround**
Do not use inline types for object properties.

**Comment by wing328** [comment]
@ePaul inline schema is not supported by codegen at the moment.

Ref: https://github.com/swagger-api/swagger-codegen/issues/354

**Comment by ePaul** [comment]
This is not quite the same situation as mentioned in #354, though: there the inline schema is in a POST argument, here it is in another schema. There the result is a NullPointerException, here it is a reference to a not generated class.

(But I accept that about the same implementation would be needed for both.)

**Comment by wing328** [comment]
@ePaul I've submitted https://github.com/swagger-api/swagger-codegen/pull/1309 (merged into master) to fix the issue.

If I understand correctly, that should fix the issue for SpringMVC you reported above. Would you please pull the latest master and see if you still encounter the same issue with SpringMVC?

If the fix works, I'll apply similar fix to Java and Jax-RS.

**Comment by fehguy** [comment]
Will be resolved when https://github.com/swagger-api/swagger-codegen/commit/9508579eed1346f728b395e047b06e9a323bea81 is merged to master

**Comment by fehguy** [comment]
Inline schemas are now supported, please reopen if you're still having issues.
