### ISSUE TITLE
vendor extension support

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1173]
We have vendor extensions but they're not exposed in codegen.

**Comment by fehguy** [comment]
now supported in codegen.

**Comment by ovidiom** [comment]
@fehguy: Do you have an example of how to use the vendor extensions in a Mustache template? I'm adding some vendor extensions to models and model properties and I saw that they are exposed in the codegen but only within the "modelJson" and "jsonSchema" attributes which are both a string representation of a JSON which I can probably not use directly in a Mustache template.

**Comment by fehguy** [comment]
You should be able to access them from 'vendorExtensions.x-your-extension' inside the template logic. Make sure you're on the latest (2.1.4) of codegen to do so

**Comment by ovidiom** [comment]
Thanks for the rapid feedback.

I was already on the latest version but after looking at your commit, it seems like you implemented support for the vendor extensions for parameters but not for models and properties (CodegenModel and CodegenProperty). Would it be possible to extend the support to models and properties?

**Comment by wing328** [comment]
FYI. #1768 will fix it.
