### ISSUE TITLE
Support for Spring RestTemplate

### ISSUE THREAD

**Issue by mparaz** [swagger-api/swagger-codegen#1176]
I would like support for Spring RestTemplate. It will allow easy testing of the client with the `MockRestServiceServer` providing mock API interaction.

**Comment by kumartheashwani** [comment]
@fehguy Can I work on this feature.

**Comment by fehguy** [comment]
Sure!  That would be helpful.

**Comment by wing328** [comment]
@kumartheashwani https://github.com/swagger-api/swagger-codegen/pull/1545 would be a good starting point to add support for another HTTP library in the Java API client. Let us know if you need any assistance. Thanks in advance.

**Comment by dan-lind** [comment]
Any progress on this issue?

**Comment by wing328** [comment]
If anyone wants to work on this, please reply to let us know.

**Comment by cbornet** [comment]
For people arriving here, you might want to have a look at the spring-cloud FeignClient generator as the FeignClients have much more awesomeness than RestTemplate. Note that you can use it with a regular monolithic spring-boot app, you don't need to have the full microservice architecture.

**Comment by mariomatar** [comment]
+1

**Comment by RaphC** [comment]
Hi @kumartheashwani 

Did you work on this ?

**Comment by wing328** [comment]
@RaphC I don't think anyone has working on it so feel free to contribute if you've time.

If you need help from us (the community), please reply to let us know.

**Comment by RaphC** [comment]
Right,

I developed a client generator for spring cloud feign template. not spring rest template. It's not exactly the same thing. Should I create a new issue ?

**Comment by cbornet** [comment]
There is already a spring cloud feign generator. But you can help to improve it !

**Comment by RaphC** [comment]
@cbornet I've just updated my comment to mention what you said in the prevois post :). Can you give me the name of the existing module?

Thanks

**Comment by cbornet** [comment]
It's spring with library spring-cloud

**Comment by RaphC** [comment]
ok. I'll try it ASAP. About the current issue, adding "rest-template" library in spring module is possible?

**Comment by kyeljmd** [comment]
Anyone working on this? if None I can talk work/look on this one. Please let me know.

**Comment by RaphC** [comment]
@kyeljmd I think you can.

**Comment by robertnac** [comment]
Hi, is there any progress? We would also like to use RestTemplate.

**Comment by gerardbosch** [comment]
@cbornet (This is out-of-topic, sorry), but, I cannot find any example of POM that allows me to use language `spring`, library `spring-cloud` to generate my `@FeignClient` annotated interface. I am using `swagger-codegen-maven-plugin` version 3.0.2.

When I configure it to use `spring-cloud` library I get the following error on `mvn compile`:

    io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.2:gen‌​erate failed: Unknown library: spring-cloud
    [ERROR] Available libraries:
    [ERROR]   spring-boot
    [ERROR]   spring-mvc

I tried to look for documentation, StackOverflow and Google with no luck. Some example, link or help will be appreciated.

**Comment by cbornet** [comment]
@gerardbosch see #194
