### ISSUE TITLE
[Objective-C] output is nil, response received

### ISSUE THREAD

**Issue by DanielChristoph** [swagger-api/swagger-codegen#1177]
I have an issue with the generated objective-c code.
The equivalent android code works pretty nice!

I'm using the API like this:
```objective-c
    SWGUserApi *userApi = [[SWGUserApi alloc] init];
    [[SWGConfiguration sharedConfig] setDebug:YES];
    [userApi addUserWithCompletionBlock:^(SWGOAuthUser* output, NSError* error){
        NSLog(@"%@", output);
    }];
```

The output and error are always nil. 
I used the sharedConfig debug mode to see more information and I receive a response.

**Comment by wing328** [comment]
The debug log should show the response header and response body. Do you mind sharing the complete debug log so that we can look into the issue further? (we assume you're using the latest version `master` of swagger-codegen)

**Comment by DanielChristoph** [comment]
I found the issue by myself and I think it's a problem with the objective-c code generator.
The swagger specification, https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md, writes in Schema, Swagger Object that the consumes and produces can be declared global.
I did this and it works in android, but not in objective-c. 
I have written the produces and consumes in each api call and it works perfectly. So maybe the code generator vor Objc does not look at the global declaration of the produces and consumes?

**Comment by DanielChristoph** [comment]
and yeah, I'm using the master.

**Comment by DanielChristoph** [comment]
This is the json file which works:
http://tunnel.se-labor.de/app_dev.php/swagger.json
(Server can may be offline sometimes, it's a test server)

Without my changes, the "produces" and "consumes" with "application/json" were only defined global.

**Comment by wing328** [comment]
@DanielChristoph thanks for sharing the spec with us to repeat the issue. We'll use it to repeat the issue with ObjC and other API clients.

**Comment by wing328** [comment]
The issue was reported before and tracked here: #827

**Comment by wing328** [comment]
@DanielChristoph I've implemented the support for top level consumes and produces in my repo (wing328: branch global_consume). If you've time, please help perform a test.

**Comment by wing328** [comment]
@DanielChristoph PR merged. Please pull the latest master and let us know if you still see issue with top-level consumes or produces.

**Comment by wing328** [comment]
The change has been reverted as we're pending an enhancement PR for swagger-parser: https://github.com/swagger-api/swagger-parser/pull/115. I'll let you know once the PR has been merged into master again

**Comment by wing328** [comment]
PR merged
