### ISSUE TITLE
C# generator does not handle dots in output directory correctly

### ISSUE THREAD

**Issue by corruptmem** [swagger-api/swagger-codegen#1178]
If you call swagger-codegen-cli generate as follows:

    java -jar lib\swagger-codegen-cli.jar generate -i my.yaml -l csharp -o output/a.b.c

You will get some supporting files in output/a.b.c and the generated files in output/a/b/c/

This is because the apiFileFolder() and modelFileFolder() methods in CSharpClientCodegen replace all dots with slashes in the outputFolder, whereas the supporting files code presumably leaves them untouched.

**Comment by wing328** [comment]
@corruptmem agree that output folder name with dot should be supported. For the time being, please work around the issue by using a folder name without dot.

And of course we would welcome a PR from you to fix the issue for the C# generator.
