### ISSUE TITLE
[JAVA] Swagger codegen maven plugin does not work with Jakarta 9 and Jersey3

### ISSUE THREAD

**Issue by agatarychter** [swagger-api/swagger-codegen#11797]
##### Description

Swagger-codegen does not support the Jakarta 9 dependency - it is not possible to use it without JEE 8 (Javax) dependencies.

##### Swagger-codegen version

3.0.33 

                <groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.33</version>

##### Swagger declaration file content or url
- not relevant
##### Command line used for generation

- not relevant

##### Steps to reproduce

Try to use Jersey3 library for Swagger codegen plugin config.

##### Related issues/PRs

-

##### Suggest a fix/enhancement

Please add support for Jersey3 (Jakarta 9)

**Comment by honza-zidek** [comment]
Is there any progress please? It is getting crucial now, it is a showstopper for using Spring Boot 3.
See https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0#:~:text=Check%20if%20Third%2Dparty%20Projects%20Have%20Jakarta%20EE%209%20Compatible%20Releases

**Comment by s-jepsen** [comment]
I'm thinking of taking a stab at this for spring-boot-3.

Since spring-boot 3 is basically a switch to Jakarta and a minimum of java17 - i'm thinking of doing a new dedicated spring-boot-3 library target. 

Is this the way to go?

**Comment by ComputerDaddyGuy** [comment]
Hello,

I have set a workaround in my project.
Assuming you are generating your objects inside `/src/gen/java/your/package`, you can add the following plugin to your `pom.xml`

```
<plugin>
	<groupId>com.google.code.maven-replacer-plugin</groupId>
	<artifactId>replacer</artifactId>
	<version>1.5.3</version>
	<executions>
		<execution>
			<phase>generate-sources</phase>
			<goals>
				<goal>replace</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<includes>
			<include>${project.basedir}/src/gen/java/**/*.java</include>
		</includes>
		<regex>false</regex>
		<token>javax.annotation</token>
		<value>jakarta.annotation</value>
	</configuration>
</plugin>
```

You will then see some new logs in your console, after the `swagger-codegen-maven-plugin` logs:
```
[INFO] --- replacer:1.5.3:replace (default) @ my-super-api ---
[INFO] Replacement run on 39 files.
```
