### ISSUE TITLE
[TypeScript-Angular] Override keyword needed in encoder.ts file

### ISSUE THREAD

**Issue by thisisthemurph** [swagger-api/swagger-codegen#11852]
##### Description

When generating the Angular TypeScript api from my `swagger.yaml` file I have to manually fix the below error, which is presented when running `ng serve` to serve the application.

`error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'HttpUrlEncodingCodec'.`

This fix is to navigate to the generated `encoder.ts` file and manually prepend the two methods with the `override` keyword.

##### Swagger-codegen version

2.4.27 (current stable)

##### Command line used for generation

```
java -jar ../swagger-codegen-cli.jar generate -i ./swagger.yaml -l typescript-angular -o ../web-ui/src/app/shared/data-access/api-client -c ./swagger-config.json
```

##### Steps to reproduce

1. Generate typescript-angular api from swagger file
2. Serve the Angular application
3. Review error

**Comment by NanezX** [comment]
Same issue here. Our project use it and we have to add the `override` keyword everytime we generate the files. 

We are using Swagger-codegen version `3.0.31`, but also using the ``3.0.35` have this error.

**Comment by Traivok** [comment]
Same issue here. I'm using swagger-codegen version `3.0.35`.

**Comment by thekhegay** [comment]
Same issue.

@HugoMario

**Comment by paibrahim** [comment]
If you do not explicitly need to have the override keyword then set the _compilerOptions.noImplicitOverride_ to **false** in the tsconfig.json file.

**Comment by mohansvrm** [comment]
What is the resolution for this?

**Comment by HugoMario** [comment]
the override keyword can be set using:
```
--additional-properties useOverride=true
```
This will be available for next release
