### ISSUE TITLE
Java generated code fails findbugs test

### ISSUE THREAD

**Issue by mparaz** [swagger-api/swagger-codegen#1186]
The problems:
* `Date` parameters use simple get and set, which can be maliciously modified. Either use `clone()` when getting or setting, or Joda as in #1035, or Java 8 if project allows.
* ApiClient loops using `keySet()` to iterate through the keys and then `get()` to obtain the values - should use `entrySet()` instead, like in `getXWWWFormUrlencodedParams()`
* Unused variables and null variables that are accessed.

**Comment by wing328** [comment]
@mparaz thanks for using findbugs to check the generated code.

Do you mind sharing with us the full report so that we can find out more about the unused variables.

**Comment by fehguy** [comment]
closing as not active.
