### ISSUE TITLE
All API responses are empty in generated html2 client

### ISSUE THREAD

**Issue by ramseyfeng** [swagger-api/swagger-codegen#11911]
- OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.127 (Official Build) (64-bit)
 - Method of installation: yarn
 - Swagger-Editor version: 4.4.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
# sample yaml provided in the official repository 
src/plugins/default-definitions.js
```

Swagger-Editor configuration options:

no configuration, as we tried it on the official website [https://editor.swagger.io/](https://editor.swagger.io/)

### Describe the bug you're encountering

All API response schemas are empty in generated html2 client.

### To reproduce...

1. Go to [https://editor.swagger.io/](https://editor.swagger.io/)
2. Click on **Generate Client > html2**
3. Open the downloaded index.html and scroll to any API's response section. (e.g. **getPetById**)
4. See error: **response is empty**

### Expected behavior

Response schemas should be displayed correctly

### Screenshots

![image](https://user-images.githubusercontent.com/2835062/192988426-cf9e7a97-9568-404d-9440-cf669ff051d8.png)

### Additional context or thoughts

Since **generate html1** clients has response schemas, maybe the issue should be caused by the API:
``` js
https://generator3.swagger.io/api/generate
```

**Comment by HugoMario** [comment]
Hey @ramseyfeng 
Thanks for reporting this issue. I'm currently working in a fix for it.

**Comment by satyamthakurdev** [comment]
@HugoMario Still getting the issue on site when trying to generate html2 form https://editor.swagger.io/

Attached petstore yaml you can reproducethe issue easily using same.

Can you please assist with same.
[pet.txt](https://github.com/swagger-api/swagger-codegen/files/9820335/pet.txt)

**Comment by ramseyfeng** [comment]
@satyamthakurdev I guess they just fixed it and havn't release it.

**Comment by swwapnily4io** [comment]
I still see the same issues even with the new swagger editor. Is it yet to be released ?
