### ISSUE TITLE
Errors during the compilation

### ISSUE THREAD

**Issue by lakeba** [swagger-api/swagger-codegen#1197]
The following errors are not blocking the compilation that end to SUCCESS but are bad to see:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
model is io.swagger.models.Swagger@a14c0b35
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
model is io.swagger.models.Swagger@d0491c8
519 [main] INFO io.swagger.codegen.cmd.Generate -
VERBOSE MODE: ON. Additional debug options are injected

**Comment by wing328** [comment]
Submitted #1205 to remove the warnings. 

Please help test and let us know if you find any issue.
