### ISSUE TITLE
No Perl Support

### ISSUE THREAD

**Issue by tehmoth** [swagger-api/swagger-codegen#120]

**Comment by icydee** [comment]
I have just come across this project and I have a few decades experience with Perl and would be happy to provide a Perl support if someone could give me some guidelines...

**Comment by deardooley** [comment]
@icydee If you would still like to contribute, we are in need of this feature as well. All the work is basically in creating mustache templates to generate the perl code. One of our community contributors on the Agave project whipped up a [Perl SDK](https://github.com/cghiban/Agave-Client) to support a legacy application. It might serve as a good starting point for generating the templates. If you'd like to take a crack at it, please let me know. I'll lend a hand to get a prototype done.

**Comment by webron** [comment]
Please be aware that it is even easier now - https://github.com/swagger-api/swagger-codegen/tree/develop_2.0#making-your-own-codegen-modules.

**Comment by webron** [comment]
@icydee, @deardooley - did either of you get a chance to have a look at it? It's perfectly fine if not, just trying to get a status. If not, I may give a shout out to the community to see if anyone could contribute.

**Comment by deardooley** [comment]
We have a decent template in Perl and R, but have not rolled it back into moustache and codegen yet. Mostly due to lack of feedback.

--
Rion

----- Reply message -----

**Comment by webron** [comment]
@deardooley - I think it would be great if you could donate it. R sounds interesting too :)

**Comment by fehguy** [comment]
as @webron said, we can help you convert them if you'd like to contribute.

**Comment by deardooley** [comment]
I'd like that. What is the easiest way? I can forward the git repos or send over whatever else you need. Also, we forked the python generator to create a SDK that works like the JavaScript one. It's a rather different approach, however. Is that of interest?

--
Rion

----- Reply message -----

**Comment by webron** [comment]
Sure, the git repos would be a good starting point.

@fehguy would comment regarding the python gen :)

**Comment by deardooley** [comment]
https://github.com/cghiban/Agave-Client
https://github.com/cran/rPlant

--
Rion

----- Reply message -----

**Comment by wing328** [comment]
I've created the templates for Perl (with reference to PHP and Python) #737 

Here is the Perl SDK for Petstore: https://github.com/wing328/petstore-perl

All feedback is welcome.

**Comment by wing328** [comment]
@icydee the PR has been merged into develop_2.0. Please checkout develop_2.0 and run the following to generate the Perl SDK for Petstore:
```
mvn clean && ./bin/perl-petstore.sh 
```
Let me know if you've any feedback.

**Comment by wing328** [comment]
I think this can be closed given that the perl templates have been merged into master

**Comment by biancalana** [comment]
https://github.com/jhthorsen/swagger2
