### ISSUE TITLE
Support for 2D arrays in C# codegen

### ISSUE THREAD

**Issue by amitbansal012** [swagger-api/swagger-codegen#1202]
Hi team,

I am using codegen for generating C# code. I found an issue with 2D arrays. The generated C# should say "int[,]", instead it says "List\<List\>", which is a compilation issue.
My java method looks like :
      Interface:
          	int[][] getPrimitiveDouble3();
      Impl:
              @Override	
              @ApiOperation(value = "This is test service - getPrimitiveDouble3")
	      @RequestMapping(value = "/getPrimitiveDouble3", method = GET)
      	      @ResponseBody
	      public int[][] getPrimitiveDouble3() {
		return null;
	     }
C#:
           List\<List\> GetPrimitiveDouble3UsingGET ();

Is there a bug in the support of 2D arrays? 

Thanks,
Amit Bansal

**Comment by wing328** [comment]
@amitbansal012 can you share the spec as I was not able to repeat the issue? Here is a test I did and the code works fine:

```
        List<List<Pet>> PlaceOrder (Order body);
```

**Comment by amitbansal012** [comment]
Hi,
The spec is as follows:
>>
{"swagger":"2.0","info":{"description":"This is a Sample service just to see how springfox works","version":"2.0","title":"MySampleService :) ","termsOfService":"http://springfox.io","contact":{"name":"springfox"},"license":{"name":"Apache License Version 2.0","url":"https://github.com/springfox/springfox/blob/master/LICENSE"}},"host":"hostname:port","basePath":"/","tags":[{"name":"test","description":"Operations in test service"}],"paths":{"/service/testService/getPrimitiveDouble3":{"get":{"tags":["test"],"summary":"This is test service - getPrimitiveDouble3","operationId":"getPrimitiveDouble3UsingGET","consumes":["application/json"],"produces":["*/*"],"responses":{"200":{"description":"OK","schema":{"type":"array","items":{"$ref":"#/definitions/Array"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}}}

Also, the code which you pasted:
>>List\<List\<Pet\>\> PlaceOrder (Order body);

Is this Csharp? If so, should it not be something like: [for a 2D array]
>> Pet[,] PlaceOrder (Order body);

Correct me if i am wrong.
Please paste your server code as well. 

Thanks,
Amit

**Comment by wing328** [comment]
For array of array in C#, we only support List of List at the moment.

{"type":"array","items":{"$ref":"#/definitions/Array"}} is an array of Model (with the name "Array"). Here is an array of array of model "Pet":
```
          "schema": {
              "type": "array",
              "items": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/Pet"
                }
              }
```
(for my example, there's no server code)

**Comment by amitbansal012** [comment]
Hi,

Thanks for responding. 
I understand that the spec which i provided was incorrect. I generated the spec using Springfox-Swagger. Please let me know if there is an alternative of generating the spec or handling similar error scenarios, I faced the same issue with nested Maps as well [https://groups.google.com/forum/embed/?place=forum%2Fswagger-swaggersocket&theme=default&fragments=true&showsearch=false&showtabs=true&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Fswagger.io%2Fforum%2F&afterlogin#!topic/swagger-swaggersocket/AoNJh01yk_I]

Thanks,
Amit

**Comment by wing328** [comment]
Are you using the latest version of springfox-swagger? I would suggest you to open an issue in https://github.com/springfox/springfox for the problems you've encountered with array and map.

**Comment by amitbansal012** [comment]
Hi,
I am using the latest jar [io.springfox:springfox-swagger2:2.1.1]. I have opened an issue in springfox for this [https://github.com/springfox/springfox/issues/956]

Thanks,
Amit

**Comment by wing328** [comment]
Thanks. Closing this as it's not a codegen issue.
