### ISSUE TITLE
Issue with compile.bat generated for C# codegen

### ISSUE THREAD

**Issue by amitbansal012** [swagger-api/swagger-codegen#1204]
Hi team,
In the compile.bat generated as part of codegen for C#, there is a segment saying "/doc:bin/IO.Swagger.xml". When i try to execute this using cmd [start compile.bat], it gives the following issue:

>>    src\main\csharp\IO\Swagger\Api\TestApi.cs(10,22): warning CS1591: Missing XML
            comment for publicly visible type or member 'IO.Swagger.Api.ITestApi'
    src\main\csharp\IO\Swagger\Api\TestApi.cs(82,35): warning CS1570: XML comment on
            'IO.Swagger.Api.ITestApi.GetDatesUsingGET()' has badly formed XML -- 'A
            name contained an invalid character.'
    src\main\csharp\IO\Swagger\Api\TestApi.cs(88,35): warning CS1570: XML comment on
            'IO.Swagger.Api.ITestApi.GetDatesUsingGETAsync()' has badly formed XML
            -- 'A name contained an invalid character.'

Can you please tell me what is the use of "/doc:bin/IO.Swagger.xm" ? 
[FYI: the error doesn't come if i remove this part manually]

Linked Request : https://groups.google.com/forum/embed/?place=forum%2Fswagger-swaggersocket&theme=default&fragments=true&showsearch=false&showtabs=true&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Fswagger.io%2Fforum%2F&afterlogin=#!topic/swagger-swaggersocket/AoNJh01yk_I

Thanks,
Amit Bansal

**Comment by wing328** [comment]
@amitbansal012 I ran compile.bat in the Petstore example and didn't encounter the issue you mentioned above. Looking at the error message, it complained about invalid characters in the code. Did you find the invalid characters in those lines?

**Comment by wing328** [comment]
Closing this as there's no further update.
