### ISSUE TITLE
Add swagger Codegen in swagger editor

### ISSUE THREAD

**Issue by GuptaAmit311** [swagger-api/swagger-codegen#1207]
I am trying to add swagger codegen in my swagger editor Jboss project ( for generate server and generate client dependencies).  Is there any document or readme file to do that. 

Thanks for your support.

**Comment by wing328** [comment]
To generate SDKs using codegen, you can submit a HTTP request to generator.swagger.io, e.g.
```
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' http://generator.swagger.io/api/gen/clients/php
```
Is that what you're looking for?

**Comment by GuptaAmit311** [comment]
Hi,
I am trying to host swagger codegen on my server locally, so no internet or http connection required to work the codegen. 
Thanks.

**Comment by wing328** [comment]
Please try the following:
```
cd modules/swagger-generator && mvn jetty:run
```
and you should then find the generator service running at localhost:8001

**Comment by GuptaAmit311** [comment]
Thanks. But I am trying to add Swagger codegen in my project of swagger editor which is running on my company server behind the proxy. I can not use http://generator.swagger.io/api/gen/servers/ to access the generator (codegen) server.

**Comment by wing328** [comment]
As suggested above, you can host your own generator server.

In the server running the swagger editor, you can update host table to add an entry for `generator.swagger.io` to point to the IP address of your internal generator server, or you can update the local copy of swagger editor by replacing http://generator.swagger.io/ with the URL to your local generator server.

**Comment by GuptaAmit311** [comment]
Yes exactly I want to do that,  Is there any way to generate the local generator client. And it needs to be done on JBoss server. My web application works on Jboss. As to add Swagger editor, I used the dist static files to create on local server. But in swagger codegen, I could not see any static files to generate generator client.

**Comment by wing328** [comment]
@GuptaAmit311 can't help as I'm not familiar with JBoss

**Comment by fehguy** [comment]
Remember also that swagger-cli is built as part of the codegen package, and you can easily invoke it from your app as an in-process or out-of-process function.

**Comment by GuptaAmit311** [comment]
@fehguy  thanks. So using only codegen-cli module I can generate the client code of different languages.

Do you have any idea about what arguements required by the main class of codegen-cli?

**Comment by fehguy** [comment]
Yes if you pass help it'll give cli options
