### ISSUE TITLE
Code generation is currently broken for node.js

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#1208]
_From @grucode on September 10, 2015 3:51_

Currently we are unable to generate server code for node.js
The server is responding with a 500 Internal Server error message on all requests for code generation.

_Copied from original issue: swagger-api/swagger-editor#637_

**Comment by mohsen1** [comment]
@webron @fehguy It seems codegen server has an issue.

**Comment by wing328** [comment]
Confirmed as I'm able to repeat the issue:
```
/tmp|⇒ curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' http://generator.swagger.io/api/gen/clients/php
{"code":500,"type":"unknown","message":"something bad happened"}%   
```

**Comment by fehguy** [comment]
We had a server error.  All better now.
