### ISSUE TITLE
Issue with Swagger Codegen for C# for Map<String, String>

### ISSUE THREAD

**Issue by amitbansal012** [swagger-api/swagger-codegen#1216]
Hi Team,
I am facing the following issue:
Code:
>> @Override
    @ApiOperation(value = "This is test service")
    @RequestMapping(value = "/getMap", method = GET)
    @ResponseBody
    public Map\<String, String\> getMap(Map\<String, String\> m);

Generated Spec
>>  "/service/testService/getMap":{"get":{"tags":["test"],"summary":"This is test service","operationId":"getMapUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"in":"body","name":"m","description":"m","required":false,"schema":{"type":"object","additionalProperties":{"type":"string"}}}],"responses":{"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"string"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}

If you see, the generated spec is in accordance with https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#model-with-mapdictionary-properties. However, the C# generated code looks like:
>> public Dictionary\<String, string\> GetMapUsingGET (Object m)

<b>The issue is that the input parameter should be "Dictionary\<string, string\> m", instead it is getting converted to "Object m". Please let me know if this a bug.</b>

On the same context, can you please also explain that, in the return type, which is generated as "Dictionary\<<b>String, string</b>\>", why is there an inconsistency in this("<b>String</b>" and "<b>string</b>")? Is this expected ?

Thanks,
Amit Bansal

**Comment by wing328** [comment]
@amitbansal012 thanks for reporting the inconsistency. We'll update `Dictionary<String, string>` to `Dictionary<string, string>`

(`string` is just an alias to `System.String`)

**Comment by amitbansal012** [comment]
Hi,
Can you please comment on the issue of input parameter conversion as well (From Map to Object) ?

Thanks,
Amit Bansal

**Comment by wing328** [comment]
@amitbansal012 before answer your question above, would you please given an example of what the HTTP request body looks like?

**Comment by wing328** [comment]
@amitbansal012 you're using inline schema, which is not supported by codegen at the moment:
```
"parameters":[{"in":"body","name":"m","description":"m","required":false,"schema":{"type":"object","additionalProperties":{"type":"string"}}}]
```

To workaround the issue, please define the following in the model section:
```
"SimpleMap": {
  "type":"object",
  "additionalProperties":
    {
      "type":"string"
    }
}
```
and reference it as follows:
```
"parameters":[{"in":"body","name":"m","description":"m","required":false,"schema":{"$ref":"#/definitions/SimpleMap"}}]
```

**Comment by amitbansal012** [comment]
Hey William,
Here is a screenshot of the requestBody:

![codegenmapissue](https://cloud.githubusercontent.com/assets/10416236/9844251/464cf466-5adf-11e5-96e0-8693453097c7.png)

Let me know if you need anything else.
Thanks,
Amit

**Comment by wing328** [comment]
@amitbansal012 I replied with a workaround 2 days ago. Did you have a chance to test that?

**Comment by amitbansal012** [comment]
Hi,
I have tested "Dictionary<String, string> to Dictionary<string, string>" fix. It works fine. Thanks for fixing this.
-Amit

**Comment by wing328** [comment]
I mean https://github.com/swagger-api/swagger-codegen/issues/1216#issuecomment-139775297 to avoid using inline schema.

**Comment by wing328** [comment]
@amitbansal012 closing this one as we've not heard any update from you.

**Comment by deepakbhise28** [comment]
issue with Dictionary on previous version i never seen this.

public partial class Address : **Dictionary<String, >,**  IEquatable<Address>, IValidatableObject

Address:
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier.
      street:
        type: string
        description: Street address detail.
      complex:
        type: string
        description: Complex name.
      suburb:
        type: string
        description: Suburb name.
      town:
        type: string
        description: Town name.
      city:
        type: string
        description: City name.
      province:
        type: string
        description: Province name.
      country:
        type: string
        description: Country name.
      postalCode:
        type: string
      districtCouncil:
        type: string
      municipality:
        type: string
      suburbId:
        type: string
      addressString:
        type: string
      streetType:
        type: string
      matchLevel:
        type: string
    additionalProperties: false
    description: Address details.
