### ISSUE TITLE
Swagger Codegen for C# [URL Formation Issue]

### ISSUE THREAD

**Issue by amitbansal012** [swagger-api/swagger-codegen#1217]
Hi Team,
I am having some problems while using codegen for APIs with List parameteres.
Code:
>> @Override
    @ApiOperation(value = "This is test service")
    @RequestMapping(value = "/getList", method = GET)
    @ResponseBody
    public List<Integer> getList(@RequestParam List<Integer> li) {
        System.out.println(li);
        return Arrays.asList(10, 20);
    }

Generated Spec:
>> "/service/testService/getList":{"get":{"tags":["test"],"summary":"This is test service","operationId":"getListUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"li","in":"query","description":"li","required":true,"type":"array","items":{"type":"integer","format":"int32"},"collectionFormat":"csv"}],"responses":{"200":{"description":"OK","schema":{"type":"array","items":{"type":"integer","format":"int32"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}

Code Generated:
>>         public List<int?> GetListUsingGET (List<int?> li)
        {            
            // verify the required parameter 'li' is set
            if (li == null) throw new ApiException(400, "Missing required parameter 'li' when calling GetListUsingGET");
            
    
>>            var path = "/service/testService/getList";
    
>>            var pathParams = new Dictionary<String, String>();
            var queryParams = new Dictionary<String, String>();
            var headerParams = new Dictionary<String, String>();
            var formParams = new Dictionary<String, String>();
            var fileParams = new Dictionary<String, FileParameter>();
            String postBody = null;

>>            pathParams.Add("format", "json");
            
>>            if (li != null) queryParams.Add("li", ApiClient.ParameterToString(li)); // query parameter
            
            
            
            
    
>>            // authentication setting, if any
            String[] authSettings = new String[] {  };
    
>>            // make the HTTP request
            IRestResponse response = (IRestResponse) ApiClient.CallApi(path, Method.GET, queryParams, postBody, headerParams, formParams, fileParams, pathParams, authSettings);
    
>>            if (((int)response.StatusCode) >= 400)
                throw new ApiException ((int)response.StatusCode, "Error calling GetListUsingGET: " + response.Content, response.Content);
            else if (((int)response.StatusCode) == 0)
                throw new ApiException ((int)response.StatusCode, "Error calling GetListUsingGET: " + response.ErrorMessage, response.ErrorMessage);
    
>>            return (List<int?>) ApiClient.Deserialize(response.Content, typeof(List<int?>), response.Headers);
        }
    

The problem is when i invoke this using:
>>         ApiClient c = new ApiClient("http://host:port/");
            TestApi t = new TestApi(c);

>>        List<int?> li = new List<int?>();
            li.Add(5);

>>       Console.Write(t.GetListUsingGET(li));

The url generated looks like:
>> http://host:port/service/testService/getList?li=System.Collections.Generic.List`1[System.Nullable`1[System.Int32]]&format=json

My doubt is, in this case, how is my server supposed to understand this "<b>li=System.Collections.Generic.List`1[System.Nullable`1[System.Int32]]</b>"

Please provide some guidance on this.

Thanks,
Amit Bansal

**Comment by wing328** [comment]
@amitbansal012 it's a bug and we'll address that.

**Comment by wing328** [comment]
@amitbansal012 fixed in #1218 

Do you mind performing a test to confirm?

**Comment by wing328** [comment]
PR merged

**Comment by amitbansal012** [comment]
Hi, 
I can perform a test, but can you please tell me how can i download the latest jar which has the fix?

-Amit

**Comment by wing328** [comment]
You can pull the latest master and do a `mvn clean package`

**Comment by amitbansal012** [comment]
Hi,
I have tested the url fix. It works fine. New url generated: "host:port/service/testService/getPrimitiveDouble2?d2=5%2C10". Thanks for fixing this.
-Amit
