### ISSUE TITLE
underscores ommited from properties generated by typescript axios client on next editor

### ISSUE THREAD

**Issue by chihabhajji** [swagger-api/swagger-codegen#12203]
- OS: Windows 11
 - Browser: Brave
 - Version: 22
 - Method of installation: https://editor-next.swagger.io/
 - Swagger-Editor version: next
 - Swagger/OpenAPI version: OpenAPI 3.0

### Describe the bug you're encountering
Typescript axios client is ommiting underscores from properties, eg: _id becomes id

### To reproduce...

1. Go to https://editor-next.swagger.io/
2. Click on 'import from file' and insert yaml file URL
3. Generate typescript-axios client

### Expected behavior
properties should be generated like defined in the yaml file and editor (on editor i see ids as _id)

### Screenshots
![definition](https://github.com/swagger-api/swagger-editor/assets/35853327/6af577da-91c0-4a77-a767-9f1117a74f27)
![generated](https://github.com/swagger-api/swagger-editor/assets/35853327/c2c4c031-b6ba-4910-a5d6-dad9295e1991)

**Comment by char0n** [comment]
Transferred from swagger-editor repo, as the issue is specific to swagger-codegen.

**Comment by chihabhajji** [comment]
thank you 😊, ill go explore the repo to see if i can pin point the issue, but i dont see the issue there
