### ISSUE TITLE
Spring-MVC: CORS headers with POST method

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-codegen#1220]
Hi,

I have a problem using Spring-MVC stub server.. It's generated automatically using a JSON spec file. I also use Swagger-ui to make the calls of the stub server.. 

The problem is that if we use a POST method, it transforms it into an OPTIONS method.. If I check the console, I get an error like this: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8002/api/company/create. (Reason: CORS header 'Access-Control-Allow-Origin' missing).` I, of course, added this CORS header and others too: 
```     
HttpHeaders headers = new HttpHeaders();   
headers.add("Access-Control-Allow-Credentials", "true");
headers.add("Access-Control-Allow-Origin", "http://localhost:8080");
headers.add("Access-Control-Allow-Methods", "GET, OPTIONS, POST, HEAD");
headers.add("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
headers.add("Access-Control-Max-Age", "3600");
```

Do you have any idea how I can get rid of this problem?? 

Thanks in advance

**Comment by wing328** [comment]
@glederrey using the petstore swaggers spec (which contains POST endpoints), I used the springmvc generator but couldn't find any reference to OPTIONS
```
swagger-codegen|master⚡ ⇒ grep -R -i OPTIONS samples/server/petstore/spring-mvc/src/*
swagger-codegen|master⚡ ⇒ 
```

Are you using the latest version of swagger-codegen?

**Comment by glederrey** [comment]
@wing328 I'm using the last version of swagger-codegen.. 

You may have misunderstood my problem.. The thing is when I call a POST request, then I receive a 200 OPTIONS response.. (In the log, it says that I'm missing the 'Access-Control-Allow-Origin') From what I've understood, when you do a POST (or PUT, or DELETE), the request always send a first OPTIONS request to be sure that everything is working and then it sends the real POST request.. 

I thought that my problem could come from the fact I'm adding some headers.. But if I don't add them, the GET request doesn't even work.. (I think this should be fixed in the `api.mustache` file)

**Comment by glederrey** [comment]
It looks like the issue is related to Preflighted CORS requests when the POST body is not text/plain. The SpringMVC implementation is not responding correctly to the OPTIONS preflight response. It seems the version of SpringMVC (4.0.9) does not supports CORS out of the box. We would suggest upgrading to 4.2 that does support CORS (https://docs.spring.io/spring/docs/current/spring-framework-reference/html/cors.html) including preflight ones. This would most probably solve the issue. Do you know what would be required to upgrade to SpringMVC 4.2?

http://www.eriwen.com/javascript/how-to-cors/

Simple vs. Preflighted requests

Now suppose we want to add a new product, but we want to use an Ajax request to keep the user on our the same page (instead of using a form). We want to make a request like this:

POST '{"name": "Awesome Widget", "price": "13.37"}' http://api.foo.com/products

If we want to send the data with a Content-Type of application/json, this would turn our request into a “Preflighted” request. In this case, CORS adds an extra step to the request. This is required by the spec in any of the following circumstances:

    Uses an HTTP verb other than GET or POST
    Custom headers need to be sent (e.g. X-API-Key: foobar)
    The request body has a MIME type other than text/plain

These requests have to be “preflighted”, meaning that the browser sends OPTIONS http://api.foo.com request to the URL, and the server must respond with a response that basically approves the actual request you want. Here’s what the sequence of HTTP requests and responses might look like (some irrelevant headers omitted):

**Comment by glederrey** [comment]
Solution found on #1244.. Closing it..
