### ISSUE TITLE
swagger-codegen not working with Java 8

### ISSUE THREAD

**Issue by MKaimltech** [swagger-api/swagger-codegen#12211]
##### Description
Not able to build the swagger-codegen, shared the steps below.

##### Swagger-codegen version

I am using latest master branch.

##### Swagger declaration file content or url
https://github.com/swagger-api/swagger-codegen

![image](https://github.com/swagger-api/swagger-codegen/assets/142029059/37146ea7-121a-40ce-988f-9f29ae6c82b2)

##### Command line used for generation
I have below version of Maven and Java:
Apache Maven 3.6.2
Java version: 1.8.0_321

##### Steps to reproduce

To build follow below steps:

git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
mvn clean package

Could some one help here?

Thanks in advance!!

**Comment by Lunatricky** [comment]
According to the Git page (https://github.com/swagger-api/swagger-codegen) if you want to build you need at least java 11. To use with Java 8 you need to get one of the releases from https://github.com/swagger-api/swagger-codegen/releases/.
At least that's what I read from this:
![image](https://github.com/swagger-api/swagger-codegen/assets/24878825/4cce5c66-92c8-4f9e-ab4c-deaf6ef858c8)

**Comment by micryc** [comment]
To build project from source, as it's specified in documentation, you need to meet two requirements:

- Java 11 +
- At least Apache Maven 3.6.2

Closing the ticket.
