### ISSUE TITLE
JavaJAXRS web.mustache template not updating swagger.api.basepath

### ISSUE THREAD

**Issue by MichaelMcClure** [swagger-api/swagger-codegen#1224]
In a given swagger.yaml, you may provide
host: <hostname>:<port>
basePath: /<path>
to identify the host, port, and path to be used by the "Try It Now" buttons.

This information does not, however, translate into the generated web.xml swagger.api.basepath as it should. Instead, the current web.mustache file is hardcoded to http://localhost:8080 

When I pulled swagger-codegen and updated the web.mustache file with no other changes, then generated the JavaJaxRS server, the web.xml was generated with the correct information.

This looks like a one-file one-line change to swagger-codegen/modules/swagger-codegen/src/main/resources/JavaJaxRS/web.mustache. In that file, at approximately line 36, instead of this:
```
     <param-name>swagger.api.basepath</param-name>
     <param-value>http://localhost:8080</param-value>
```
It should be this:
```   
    <param-name>swagger.api.basepath</param-name>
    <param-value>{{basePath}}</param-value>      
```

I swear I have read an issue about this in the past, but I cannot locate it. I apologize if there is another active issue on this.

**Comment by wing328** [comment]
@MichaelMcClure thanks for reporting the issue. Agree that it should be fixed according to the way you described above. Would you like to submit a PR to fix the issue or you would like me to fix it instead? (if my memory serves me well, I've fixed a similar issue before for nodejs but not jaxrs)

**Comment by MichaelMcClure** [comment]
I'll make a PR. I'm a noob on the swagger repos & don't know the releases. Should I fork off Master or develop_2.0 ?

**Comment by MichaelMcClure** [comment]
So my fix above (using basePath) has an unintended side effect - it sets the default basePath to "localhost" instead of "localhost:8080". I think this will mess people up.

I think this is two issues:  
1. the hostname and port (swagger file "host" attribute) being ignored 
2. the path (context path & swagger file "basePath" attribute) being ignored.

Regarding number 2:
Changing the web.mustache file to read like this
```
 <param-name>swagger.api.basepath</param-name>
 <param-value>http://localhost:8080{{contextPath}}</param-value>
```
gets the context path passing through correctly while not impacting the default port. I think this is a clear and needed fix.

Regarding number 1:
In looking at this further, I can see why no one has fixed this (yet). Hostname/port is set in DefaultGenerator, so any change there would be global.  It sort of broaches the issue of default hostname / port in a global sense (across all generators). Either way, I see it as a separate issue as in create a different issue for it . Wing328 - do you agree on making a separate issue for number 1??? 

Detail below:
Currently, the default of localhost:8080 is set in the web.mustache file. If that is removed, there seems to be no good place to set the default port to 8080 only for the scope of Java / JaxRS, because the default of "localhost" is set in DefaultGenerator.generate() around line 104 if no "host" is set in the input swagger file. Any changes there would be global to all codegens. 

We could have DefaultGenerator invoke a method on the CodgeGenConfig object -> config.getDefaultHostAndPort() and update the CodegenConfig interface and all implementing classes.
OR test for some additionalProperty like "serverPort" on codegenConfig and use it if it were present AND modify JaxRSServerCodeGen to have that property & set it into the additionalProperties. 

I looked at the nodejs generator too, and what I see is that the port is hardcoded in the generator - if you did specify host:port in the swagger definition, you would get host:port:hardcodedport.

**Comment by wing328** [comment]
@MichaelMcClure I totally agree with you that ideally the fix should be backward compatible.

For 1, what about checking if `host` is set in the mustache template, e.g.
```
{{#host}}{{host}}{{/host}}{{^host}}localhost:8080{{/host}}
```
This will use localhost:8080 as default if `host` is not provided.

For 2, we can use similar fix to the above to check if `basePath` is set

Correction: I was wrong about fixing similar issue for the nodejs generator. The change I made before is for TypeScript (client)

**Comment by MichaelMcClure** [comment]
Agree - good idea. I will test & submit PR.

**Comment by fehguy** [comment]
Assuming the PR was submitted and merged.  Please reopen if not.
