### ISSUE TITLE
JavaSpringMVC/formParams.mustache: change the name of one parameter

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-codegen#1227]
Hi, 
I just want to ask if it's possible to change the definitions of formParams.mustache.. For the moment, it's like this:

```@ApiParam(value = "{{{description}}}"{{#required}}, required=true{{/required}} {{#allowableValues}}, allowableValues="{{{allowableValues}}}"{{/allowableValues}}{{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}) @RequestPart(value="{{paramName}}"{{#required}}, required=true{{/required}}{{^required}}, required=false{{/required}}) {{{dataType}}} {{paramName}}{{/notFile}}{{#isFile}}@ApiParam(value = "file detail") @RequestPart("file") MultipartFile fileDetail{{/isFile}}{{/isFormParam}}```

I would like to change the name `fileDetail` by the name of the parameter.. You cna either use `{{paramName}}` or `{{baseName}}`.. 

It would be more useful if we're using this in the file api.mustache.. 

Thanks

**Comment by wing328** [comment]
@glederrey would you please take a look at #1219 to see if it's the same issue?

**Comment by glederrey** [comment]
@wing328 It's not exactly the same.. But it's related to this issue.. The problem I had here is that the name of the `MultiPartFile` parameter is always `fileDetail`.. And it should be the name of the parameter.. That's why I'm suggesting to change this `fileDetail` to `{{paramName}}` or `{{baseName}}`.. Do you see what I mean??

**Comment by wing328** [comment]
Now I see what you mean and would suggest you to use {{baseName}} in the@AprParam annotation.

Let me know if you need any help submitting a PR to address it (or you would like the community to file a PR instead)

**Comment by glederrey** [comment]
Yes, it would be perfect.

I'm still new to Github.. So, I don't really know how to submit a PR.. Sorry
