### ISSUE TITLE
[Typescript] Multiple duplicate identifiers in generated client.

### ISSUE THREAD

**Issue by kbegiedza** [swagger-api/swagger-codegen#12300]
##### Description

Generated client contains multiple duplicate identifiers.

ex:
```
TS2300: Duplicate identifier 'IUserInfo'.
    14 |
  > 15 | import { IUserInfo } from './iuser-info';
       |          ^^^^^^^^^
    16 | import { UserMetadata } from './user-metadata';
    17 | import {
    18 |     IUserInfo,UserMetadata,
```

and:

> An interface can only extend an identifier/qualified-name with optional type arguments.

```
export interface ValidationProblemDetails extends null<String, any> {
}
```

##### Swagger-codegen version

3.0.51

##### Swagger declaration file content or url

https://gist.github.com/kbegiedza/35d6af4118239867a93e11440eb1a67c

##### Command line used for generation

```
java -jar swagger-codegen-cli.jar generate \
    -i http://localhost:5000/swagger/v1/swagger.json \
    -l typescript-axios \
    -o output
```

##### Steps to reproduce

Run using above

##### Related issues/PRs

N/D

##### Suggest a fix/enhancement

N/A

**Comment by supidupicoder2** [comment]
Same for me

**Comment by aatrostle** [comment]
Just in case anyone is blocked by this, ran into a similar duplicate import issue in typescript generation. Rolling back to swagger-codegen `3.0.50` resolved the issue.
