### ISSUE TITLE
[ASPNETCORE] bad character in generated file

### ISSUE THREAD

**Issue by Bobdugrand8** [swagger-api/swagger-codegen#12308]
##### Description

When using the generator for ASPNETCORE, it add a bad character that blocks the project to open.
##### Swagger-codegen version

3.0.51 on https://editor.swagger.io/

##### Swagger declaration file content or url

The default PETStore is also bugged

##### Steps to reproduce

Generate the aspnetcore server.
Try to open the project in visual studio (or rider)
The project fail to open.

##### Suggest a fix/enhancement

The error is in IO.swagger.csproj:
```
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>`
```

**Comment by HugoMario** [comment]
https://github.com/swagger-api/swagger-codegen-generators/pull/1233
