### ISSUE TITLE
[JAVA] okhttp4-gson template is not compatible with jakarta=true

### ISSUE THREAD

**Issue by valley-fordham** [swagger-api/swagger-codegen#12319]
##### Description

When generating code with a .config file settings set to the following..
```
  "useBeanValidation": "true",
  "jakarta": "true",
  "hideGenerationTimestamp": "true",
  "library": "okhttp4-gson"
```
..javax imports are still used, which causes the code to not be compileable.

##### Swagger-codegen version

swagger-codegen-cli 3.0.51

##### Suggest a fix/enhancement

The template looks like it isn't respecting the 'jakarta' setting at all. If we get to a point where we need to move to okhttp4 then I may end up creating a pull request.

**Comment by phs-glenfordham** [comment]
this can be closed, logged in the wrong project

**Comment by valley-fordham** [comment]
This can be closed, logged in the wrong project
