### ISSUE TITLE
getTypeDeclaration is getting RefProperty's

### ISSUE THREAD

**Issue by sverhagen** [swagger-api/swagger-codegen#1231]
Let's say this is a question (and I hope it's okay I post that here), I've little confidence that it's actually a bug. I may just be doing something stupid.

This is my Swagger JSON:

    "models": {
        "SomeItem": {
            "id": "SomeItem",
            "properties": {
            ...
                "fields": {
                    "$ref": "Map[string,Object]",
                },

This is the annotation on the server:

    @ApiModelProperty(position = 99, value = "Blah blah", required = true)
    public Map<String, Object> getFields() {
        return fields;
    }

I am trying to use Java code generation, but instead of this:

    private Map<String, Object> fields = null;

I'm getting this:

    private MapStringObject fields = null;

I see that `JavaClientCodeGen.getTypeDeclaration` is getting a `RefProperty` while it only knows how to handle an `ArrayProperty` or a `MapProperty`.

**Comment by wing328** [comment]
@sverhagen To generate a map of object, please use `additionalProperties` instead

Ref: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#model-with-mapdictionary-properties

**Comment by sverhagen** [comment]
Thank you for the quick response. I'll take it that asking questions this way may be kinda okay then :wink: Closing the issue now.
