### ISSUE TITLE
Docker v3 release scripts use the wrong dockerfiles for minimal and codegen

### ISSUE THREAD

**Issue by tariqajyusuf** [swagger-api/swagger-codegen#12343]
##### Description

The build and release scripts on `3.0.0` are not using the correct build files for the minimal and CLI images.

##### Swagger-codegen version

3.0.53 (regression from 2.x.x for cli)

##### Swagger declaration file content or url

N/A

##### Command line used for generation

v2 runs
```sh
$ docker run -it swaggerapi/swagger-codegen-cli
usage: swagger-codegen-cli <command> [<args>]
...
```

v3 runs
```sh
$ docker run -it swaggerapi/swagger-generator-v3-minimal
no main manifest attribute, in /generator/jetty-runner.jar
$ docker run -it swaggerapi/swagger-codegen-cli-v3
no main manifest attribute, in /generator/jetty-runner.jar
```

##### Steps to reproduce

See above

##### Related issues/PRs

The [last workflow run](https://github.com/swagger-api/swagger-codegen/actions/runs/7901750959) was 3 days ago and ran the script on `3.0.0`. The issue seems to be here

https://github.com/swagger-api/swagger-codegen/blob/08c77e91ce0b97a10f56094fea8331369f4f0d47/.github/workflows/docker-release-3.0.yml#L83C7-L100C118

##### Suggest a fix/enhancement

I'm working on a PR to use the Dockerfile in `modules/swagger-codegen-cli/`. I'm still not certain what's happening with `minimal`. It seems that there is an issue with the generated file `modules/swagger-codegen/Dockerfile_minimal`, my best guess is that it's related to the missing additional jetty jars but I'm hesitant to suggest a fix since I'm unclear as to the intent.

**Comment by frantuma** [comment]
Thanks for reporting, investigating and providing the fix. Main issue has been fixed in #12331 and is available in 3.0.54 release. Swagger Generator "minimal" image is still failing and will be addressed in different ticket scope
