### ISSUE TITLE
Package com.squareup.okhttp does not exist when using swagger-codegen-v3 with com.squareup.okhttp3

### ISSUE THREAD

**Issue by RHinderiks** [swagger-api/swagger-codegen#12340]
##### Description

Trying to set up a project using codegen v3 via maven. However i seem to require com.squareup.okhttp which in turn requires a backport library for java 8 dates. Adding com.squareup.okhttp3 as a dependency results in the following error **package com.squareup.okhttp does not exist**

##### Swagger-codegen version

io.swagger.codegen.v3 using version 3.0.52

##### Swagger declaration file content or url

Pet store example file is used

##### Command line used for generation

mvn clean compile

**Comment by smeh-git** [comment]
Can I ask how you fixed this? I have same problem
