### ISSUE TITLE
Missing releases on mvnrepository.com

### ISSUE THREAD

**Issue by r-simlinger** [swagger-api/swagger-codegen#12350]
##### Description

On https://mvnrepository.com/artifact/io.swagger.codegen.v3/swagger-codegen you can only find the versions up to 3.0.52

##### Swagger-codegen version

So the releases 3.0.53 and 3.0.54 are missing on mvnrepository.com

**Comment by r-simlinger** [comment]
As workaround you could use the links from https://central.sonatype.com/ :

- https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.54/swagger-codegen-cli-3.0.54.jar
- https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.53/swagger-codegen-cli-3.0.53.jar
- https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/

**Comment by frantuma** [comment]
Closing ticket as it depends on indexing of mvnepository.com


some background for ref:

mvnrepository.com is a site providing a registry/search for maven artifacts. It is not the same as the official "Maven central" maintained by sonatype. Explain who owns/maintains mvnrepository.com, how artifacts are deployed there, what's the difference with "Maven Central".

Artifacts are not directly deployed to mvnrepository.com. Instead, this site indexes artifacts that are hosted in actual Maven repositories, like Maven Central or JCenter. Developers do not upload artifacts to mvnrepository.com; they deploy them to Maven Central or other repositories, and mvnrepository.com provides a searchable interface to these artifacts.

mvnrepository.com periodically indexes information from Maven Central and possibly other repositories, meaning there can be a delay between an artifact's availability in Maven Central and its appearance on mvnrepository.com.
