### ISSUE TITLE
No generated code from swagger-codegen

### ISSUE THREAD

**Issue by kmrgithub** [swagger-api/swagger-codegen#1237]
Hi. I just updated my swagger-codegen repo and after the update no Java code is generated. 
I first built v2.1.3 and also unsuccessfully tried with v2.1.2.

Here is my command-line:
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar gene
rate -l java -i swagger.json -o C:\Temp

Here is the output: 
reading config from swagger-codegen.cfg
reading from C:\Users\...\swagger.json

Any ideas?

**Comment by kmrgithub** [comment]
Hi. I think I may have found the issue.

Line 335 in JavaClientCodegen.java in package io.swagger.codegen.languages throws an exception due to hasEnums is null.
if (allDefinitions != null && codegenModel != null && codegenModel.parent != null && codegenModel.hasEnums) {

The class CodegenModel in file CodegenModel.java in package io.swagger.codegen does not initialize any of its members.

**Comment by wing328** [comment]
@kmrgithub would you please pull the latest master and see if you still experience the same issue ?

**Comment by kmrgithub** [comment]
Will do before Friday.

**Comment by kmrgithub** [comment]
I receive an empty class named EnumTest from this entry in Swagger Editor.
  EnumTest:
    type: string
    enum: ["hello", "goodbye"]

**Comment by wing328** [comment]
@kmrgithub do you mind sharing the full spec so that we can reproduce the issue?

Also I would recommend pulling the latest master as we've addressed quite a few issues recently.

**Comment by kmrgithub** [comment]
@wing328 -
Here is my input json:
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "BuyerFirstRS",
        "description": "BuyerFirst REST API"
    },
    "host": "a",
    "definitions": {
        "EnumTest": {
            "type": "string",
            "enum": [
                "hello",
                "goodbye"
            ]
        }
    }

Here is my swagger-codegen command line:
java -jar C:/src/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.json -l java

Here is the java output:
package io.swagger.client.model;
import io.swagger.client.StringUtil;
import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.JsonProperty;

@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2015-10-20T11:33:46.397-04:00")
public class EnumTest   {
  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnumTest {\n");
    sb.append("}");
    return sb.toString();
  }
}

**Comment by fehguy** [comment]
Hi, two things.  First, you're missing paths, which is technically not a valid swagger.  Next, your model definition is missing the `properties` path.  If you update it like such:

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "BuyerFirstRS",
    "description": "BuyerFirst REST API"
  },
  "host": "a",
  "paths": {},
  "definitions": {
    "EnumTest": {
      "properties": {
        "foo": {
          "type": "string",
          "enum": [
            "hello",
            "goodbye"
          ]
        }
      }
    }
  }
}
```

It generates the model as you would expect.
