### ISSUE TITLE
Unable to generate auth_settings properties with swagger 1.2

### ISSUE THREAD

**Issue by DariusMR** [swagger-api/swagger-codegen#1240]
Hello
I've swagger 1.2, and the latest swagger-codegen and i'm unable to generate properly my api_key settings.
For example in python only this is generated for this specific method in configuration.py file :
```python
    def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
        }
```
but with petstore example which uses swagger 2.0 this is generated :
```python
    def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'api_key':
                {
                    'type': 'api_key',
                    'in': 'header',
                    'key': 'api_key',
                    'value': self.get_api_key_with_prefix('api_key')
                },
        }
```
Same thing with methods generated in apis folder. Only this is generated for all methods : 
```python
auth_settings = []
```
but with petstore example in apis folder : 
```python
auth_settings = ['api_key', 'petstore_auth']
```
or
```python
auth_settings = ['api_key']
```
is generated.
I've used the same command line in each example to generate the code
And this is not only with python language. It's the same think with java generated code or other langages
Did I miss something ?

**Comment by wing328** [comment]
@DariusMR can you share the spec with us so that we can use it to repeat the issue ?

**Comment by wing328** [comment]
@DariusMR if you're still encountering the issue, would you please share the spec with us? also I would suggest using another generator (e.g. Ruby, PHP) to see if the same issue occurs.

**Comment by inska** [comment]
I've met this issue, too. Ruby client seems working well with auth_settings but swift and python client not working.

**Comment by wing328** [comment]
@DariusMR @inska please give it another try as the latest version of Swagger-Codegen (master) should have fixed it.

**Comment by fehguy** [comment]
Please reopen if you're still seeing this issue.
