### ISSUE TITLE
codgen does not emit parameter type for body parameters of type string 

### ISSUE THREAD

**Issue by bedag-moo** [swagger-api/swagger-codegen#1241]
For the operation spec:

    "operations" : [ {
      "method" : "POST",
      "nickname" : "createIssue",
      "type" : "void",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "body",
        "name" : "subject",
        "required" : true
      } ],
      "authorizations" : {
        "OpenID Connect" : [ ]
      }
    } ]

codegen for Java generates the following method signature in the API class:

    public void createIssue( subject) throws ApiException {
    
As you can see, the parameter type is missing, causing a compilation error.

**Comment by bedag-moo** [comment]
Debugging revealed that the type is not written

* because {{dataType}} is null
* because CodegenParameter.dataType is not assigned in DefaultCodeGen.fromParameter() 
* because param.model is null
* because SwaggerCompatConverter.modelFromExtendedTypedObject returns null

That method does the following:

    public Model modelFromExtendedTypedObject(ExtendedTypedObject obj) {
        String type = obj.getType() == null ? null : obj.getType().toString();
        String format = obj.getFormat() == null ? null : obj.getFormat().toString();

        Model output = null;
        if (obj.getRef() != null) {
            output = new RefModel().asDefault(obj.getRef());
        } else {
            if ("array".equals(type)) {
                ArrayModel am = new ArrayModel();
                Items items = obj.getItems();
                type = items.getType() == null ? null : items.getType().toString();
                format = items.getFormat() == null ? null : items.getFormat().toString();

                Property innerType = PropertyBuilder.build(type, format, null);
                if (innerType != null) {
                    am.setItems(innerType);
                } else if (items.getRef() != null) {
                    am.setItems(new RefProperty(items.getRef()));
                } else {
                    am.setItems(new RefProperty(type));
                }
                output = am;
            } else {
                Property input = PropertyBuilder.build(type, format, null);     // yields a StringProperty
                if (input == null && !"void".equals(type)) {                             // is false
                    //use ref model
                    output = new RefModel().asDefault(type);
                }                                                                                            // and output is never assigned
            }
        }
        return output;
    }

I am not really sure why this code creates a Property object (which correctly contains a StringProperty), but only assigns output if the Property object is null.

**Comment by fehguy** [comment]
Please try updating to swagger spec 2.0, which has much better support for this.  You would use the syntax like such:

```json
{
  "post": {
    "operationId": "createIssue",
    "parameters": [
      {
        "in": "body",
        "type": "string",
        "name": "subject",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    ]
  }
}
```

as swagger-spec 1.2 is over a year old, we are focusing on the 2.0 support.  Please reopen with any questions.

**Comment by bedag-moo** [comment]
We can not easily switch to Swagger 2.0, because our spec is generated by [swagger-jaxrs-doclet](https://github.com/teamcarma/swagger-jaxrs-doclet), which [does not yet support Swagger 2.0](https://github.com/teamcarma/swagger-jaxrs-doclet/issues/29).
