### ISSUE TITLE
Link to swagger-codegen-maven-plugin broken

### ISSUE THREAD

**Issue by Christian1984** [swagger-api/swagger-codegen#12478]
##### Description

The link to the swagger-codegen-maven-plugin documentation (https://github.com/swagger-api/swagger-codegen/blob/3.0.0/docs/modules/swagger-codegen-maven-plugin/README.md) on https://github.com/swagger-api/swagger-codegen/blob/3.0.0/docs/workflow-integration.md is broken.

##### Swagger-codegen version

N/A

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

Link should point to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-maven-plugin/README.md

**Comment by ponelat** [comment]
Should be addressed in https://github.com/swagger-api/swagger-codegen/pull/12485 
Thanks @Christian1984 (and @micryc )!
