### ISSUE TITLE
Move generated Java code to target/generated-sources instead of src

### ISSUE THREAD

**Issue by c-knowles** [swagger-api/swagger-codegen#1249]
Although not heavily documented as a standard, most projects generating source for Java projects using Maven place it under target/generated-sources/plugin-name. My suggestion is to do the same for Java Swagger codegen in order to allow additional source to be committed to the same project while allowing the project to be easily to use and maintain.

If all the source is under src but we also want to add additional source, it is very difficult to clear out the code generated by swagger-codegen prior to a rebuild. One option is to ignore each individual generated file in your source control mechanism, that's not ideal though.

**Comment by fehguy** [comment]
The maven plugin does this by default, and you can override it as you see fit.

**Comment by c-knowles** [comment]
Ah, has that changed then in a recent release? The latest version at the date of the report, which was 2.1.3, generated the pom.xml for the client code project and put the generated source under src not target.

**Comment by fehguy** [comment]
Hmm I think it was the case in 2.1.3.  But as of yesterday, we now have 2.1.4, which may have introduced that as the default location.  See [here](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.1.4) for more details on the release.
