### ISSUE TITLE
HTML output inconsistent with Swagger Editor preview

### ISSUE THREAD

**Issue by alexhawdon** [swagger-api/swagger-codegen#1251]
As per title. For my [swagger.yml](https://gist.github.com/alexhawdon/5acb0ea555bb608aa303) definition here is the Swagger UI preview for a given method:
![upload_17_9_2015_at_16_54_35](https://cloud.githubusercontent.com/assets/1389105/9938801/003ac296-5d5f-11e5-821b-c2c787e5e11f.png)
and here is the same method in the HTML output:
![upload_17_9_2015_at_16_56_59](https://cloud.githubusercontent.com/assets/1389105/9938808/093c6f48-5d5f-11e5-918b-18ede8142688.png)

Note the missing parameters.

Thanks for any assistance.

**Comment by wing328** [comment]
@alexhawdon thanks for reporting the issue. Similar issue has been opened before: #1212

May I know if you've cycle to submit a PR to improve the HTML documentation?

**Comment by lavadiablo** [comment]
I have same issue and I am working on a PR.
