### ISSUE TITLE
[Objective-C][Swift] Lists of enum make the objc and swift generator crash

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#1257]
The following spec makes the objc and swift generators crash silently
```json
{
    "definitions": {
        "Foo": {
            "properties": {
                "foo": {
                    "type": "string",
                    "items": {
                        "type":"string",
                        "enum": ["foo", "bar"]
                     }
                 }
             }
        }
    },
    "info": {
        "title": "Foo",
        "version": "1.0.0"
    },
    "paths": {},
    "swagger": "2.0"
}
```

**Comment by webron** [comment]
While it shouldn't crash, that's basically saying that` foo` is of type `string`, not an array of strings.

**Comment by cbornet** [comment]
Oops, wrong copy/pasting ! The crash is with array, of course. Thanks for pointing that out.
The problematic definition is:
```json
{
    "definitions": {
        "Foo": {
            "properties": {
                "foo": {
                    "type": "array",
                    "items": {
                        "type":"string",
                        "enum": ["foo", "bar"]
                     }
                 }
             }
        }
    },
    "info": {
        "title": "Foo",
        "version": "1.0.0"
    },
    "paths": {},
    "swagger": "2.0"
}
```

**Comment by webron** [comment]
From what you write I take it if you remove the `enum` it works fine?

Side note: You should always set `"type": "object"` when using a model definition (that is, when using `properties`).

**Comment by cbornet** [comment]
@webron Yes if I remove ```enum``` it is generated with a list of string.

**Comment by wing328** [comment]
@cbornet the issue should be fixed in the latest master (by @fehguy). Please given it a try and let us know if you still encounter the issue.

**Comment by cbornet** [comment]
Looks OK to me. Thanks.

**Comment by Ravi-Impiger** [comment]
But still I could not able to generate enums for either objective c or swift code.
