### ISSUE TITLE
[spring-mvc]swagger codegen for spring-mvc imports "io.swagger.model.Object" for some definitions

### ISSUE THREAD

**Issue by tckb** [swagger-api/swagger-codegen#1258]
Hi, this is a weird bug from swagger-codegen. Apparently for some definitions, the spring-mvc codegen imports [modelpackage].Object in the corresponding class file. this of course raises a compile time error. 
Not sure why this occurs only for some definitions, here are some of the definitions:

```
WebserviceResponse:
    type: object
    description: A generic webservice response  for every webservice request
    properties:
      meta_data:
        $ref: "#/definitions/WebResponseMetaData"
      response_object:
        type: object
        description: 'on `http_status`=200, response object encapsulated in it'
WebResponseMetaData:
    type: object
    properties:
      status:
        type: string
        description: 'status of the response, either "Sucess/failure"'
      http_status:
        type: integer
        description: 'HTTP response code, `200` for successful operation| `500`  for server side error'
      success_message:
        type: string
        description: additioanl sucess message
      error_message:
        type: string
        description: description of error message

**Comment by wing328** [comment]
@tckb the property `response_object` is defined as `object`
```
      response_object:
        type: object
        description: 'on `http_status`=200, response object encapsulated in it'
```
Currently, there's a bug that the code treats "object" as a model and that's why you found the `imports [modelpackage].Object` in the code.

To workaround the issue for the time being, you can set `response_object` to a well-defined model using $ref.

**Comment by tckb** [comment]
I see that, the idea was to use this model as a sort of generic response. the response object would depend on the request (I have no idea how one could achieve that. I ended up creating individual responses :-/) . Hence, I can't use any specific reference to the definition.

**Comment by gboysko** [comment]
I'm experiencing the same problem. Just started to use Swagger and got tripped up by this...

**Comment by wing328** [comment]
@tckb I've submitted #1309 to address the issue. Would you please perform a test to confirm?

@gboysko I assume the issue you encountered is also with SpringMVC but not other languages/frameworks and would be nice if you can also test the fix to confirm.

**Comment by tckb** [comment]
@wing328 is this already pushed to the master code base? I'll test it on my end.

**Comment by wing328** [comment]
@tckb not yet merged into master. To test, please do the following:
```
git clone https://github.com/wing328/swagger-codegen.git
cd swagger-codegen
git checkout fix_springmvc_object
mvn clean package
```

I did perform a test to confirm but of course it would be better if you can confirm as well before we merge the fix into master.

**Comment by tckb** [comment]
@wing328  performing tests now, will get back to you.

**Comment by tckb** [comment]
@wing328  Issue resolved. Generated code compiles and runs perfectly. Issue appears to be closed. 

Nevertheless, the "JavaSpringMVC" template needs some fixes and additions which I'd like to push.

**Comment by wing328** [comment]
@tckb Thanks for the confirmation. PR merged into master.

We look forward to your PR to address other issues with JavaSpringMVC. If you need any help with the PR, just let me know (personal email address available at github profile page)
