### ISSUE TITLE
[python] The steam handler add many times when project includes many swagger clients

### ISSUE THREAD

**Issue by SparrowJang** [swagger-api/swagger-codegen#1262]
Show twice messages if include two swagger clients.

Because handler will be added logger by swagger client.

```python
logger.debug("hello")
```

output:
```
2015-09-20 15:41:39,682 DEBUG hello

2015-09-20 15:41:39,682 DEBUG hello
```

**Comment by wing328** [comment]
@SparrowJang the fix has been merged into master. Closing this and please reply to let us know if you still experience the issue.
