### ISSUE TITLE
Improve exception handling, particularly in the maven codegen plugin

### ISSUE THREAD

**Issue by bedag-moo** [swagger-api/swagger-codegen#1266]
Currently, `DefaultCodegen.generate()` catches all exceptions, and communicates success or failure to its caller through the public field `DefaultCodegen.status`. This field is ignored by the maven codegen plugin, i.e. a build continues even if code generation failed.

Ideally, `DefaultCodegen.generate()` would let exceptions propagate to its caller. The CodeGenMojo could then wrap the exception into a `MojoExecutionExecutionException` to tell maven about the failed build.

**Comment by bedag-moo** [comment]
... and whatever you do, please do not discard exceptions without logging them (as the catch block in `DefaultCodegen.generate()` currently does). It sucks to have to debug the maven codegen plugin to find out where the swagger documentation was incomplete, as in #1267.

**Comment by wing328** [comment]
@bedag-moo I agree with you that the exception handling can be further improved. I'm working on the improvement and hopefully will have a PR by the end of this week.

**Comment by bedag-moo** [comment]
I have also started work on this, and have fixed the exception handling in the areas that concern me. Let me test it some more, and I'll send a pull request.

**Comment by wing328** [comment]
Ok. Thanks @bedag-moo

**Comment by ches** [comment]
Seems like this can be closed with #1276 merged.

**Comment by ches** [comment]
Does it also satisfactorily fix #1267?

**Comment by bedag-moo** [comment]
I did not systematically check the code for other instances where exceptions are discarded, but the ones I stumbled across have been fixed, so closing it ok with me.
