### ISSUE TITLE
[Python] TLS support

### ISSUE THREAD

**Issue by madhuri-rai07** [swagger-api/swagger-codegen#1299]
I want to use TLS connection in python generated client code. But not sure how to pass client certificate and key file.
I see urllib3 is used which supports TLS.

**Comment by wing328** [comment]
@madhuri-rai07 you can find the setting in the configuration class: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/swagger_client/configuration.py#L94

**Comment by madhuri-rai07** [comment]
@wing328 @geekerzp This is just to pass own CA certificate file but what about client certificate file and client keyfile?

**Comment by geekerzp** [comment]
@madhuri-rai07 Add support in pr https://github.com/swagger-api/swagger-codegen/pull/1300

**Comment by madhuri-rai07** [comment]
Thank you @wing328 @geekerzp

**Comment by wing328** [comment]
@madhuri-rai07 PR merged into master. Please test and let us know if it still does not fully meet your requirement.
