### ISSUE TITLE
additionalProperties with Boolean value causes NPEs

### ISSUE THREAD

**Issue by ches** [swagger-api/swagger-codegen#1318]
I'll come back and provide a more minimal reproduction case, just wanted to file this while it's fresh (it seems fairly trivial to reproduce, and a quick grep shows a lot of code that seems to assume `additionalProperties` will be a map).

`additionalProperties` in JSON Schema [can be an object or a Boolean][1]. When I use a Boolean value, codegen blows up with an NPE (using rev 253c46a0d5a96dd4da8 at time of this trace):

```
$ make gen
Running Swagger code generation
java -jar /Volumes/onner/onner-sdk-ios/vendor/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
                --input-spec /Volumes/onner/onner-sdk-ios/../API/docs/swagger.json \
                --lang objc \
                --config /Volumes/onner/onner-sdk-ios/config.json \
                --output /Volumes/onner/onner-sdk-ios
reading from /Volumes/onner/onner-sdk-ios/../API/docs/swagger.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["additionalProperties"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["JsonApi"])
reading from /Volumes/onner/onner-sdk-ios/../API/docs/swagger.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["additionalProperties"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["JsonApi"])
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:63)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
make: *** [gen] Error 1
```

The offending spec definition in this case is this one:

```yaml
  # http://jsonapi.org/format/#document-jsonapi-object
  JsonApi:
    description: An object describing the server's implementation
    type: object
    properties:
      version:
        type: string
      meta:
        $ref: '#/definitions/Meta'
    additionalProperties: false
```

This API conforms to JSON API and derives definitions from [the JSON Schema definition][2] of JSON API, which declares `additionalProperties: false` here. The `$ref` here is inconsequential—commenting out the `additionalProperties` line (and others like it in the rest of the spec) avoids the codegen failure and succeeds.

[1]: http://json-schema.org/latest/json-schema-validation.html#anchor64
[2]: http://jsonapi.org/faq/#is-there-a-json-schema-describing-json-api

**Comment by dolmen** [comment]
Here is a small test case:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "test of Swagger of boolean additionalProperties"
  },
  "paths": {
    "/": {
      "get": {
        "produces": [ "application/json" ],
        "description": "xxx",
        "responses": {
          "200": {
            "schema": { "$ref": "#/definitions/Root" }
          }
        }
      }
    }
  },
  "definitions": {
    "Root": {
      "type": "object",
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}
```
```
java -jar ~/bin/swagger-codegen-cli.jar generate -i x.json -l html -o html
reading from x.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["additionalProperties"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Root"])
reading from x.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["additionalProperties"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Root"])
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:63)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by dolmen** [comment]
Related: swagger-api/swagger-core#1437

**Comment by dolmen** [comment]
@ches The definition `additionalProperties` that matters is not the one in `JSON Schema` that you linked to but [the one in the Swagger spec](/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L988).

**Comment by ches** [comment]
@dolmen I'm aware that Swagger adds a slight semantic override, but in regard to `additionalProperties` [the spec as written says][1]:

> The following properties are taken from the JSON Schema definition but their definitions were adjusted to the Swagger Specification. **Their definition is the same as the one from JSON Schema**, only where the original definition references the JSON Schema definition, the Schema Object definition is used instead.

> • items
> • allOf
> • properties
> • additionalProperties

My added emphasis is to stress that I'm pretty sure there is a conscious decision not to break backward compatibility implied there.

[1]: http://swagger.io/specification/#schemaObject

**Comment by dolmen** [comment]
@ches There is no "backward compatibility" involved here. This is just about maintaining the similar meaning, for consistency (not compatibility) with JSON Schema.

**Comment by ches** [comment]
@dolmen Is that an "official" stance on JSON Schema compatibility?

Either way, I hope we can agree that the written spec and the implementation are currently inconsistent.

**Comment by fehguy** [comment]
@ches there is an official stance on json-schema.  Swagger supports a subset of JSON schema draft-4 which should be clearly documented in the [swagger-spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md).

The spec is the source of truth and projects may not implement all aspects of the spec 100%.  If we have unimplemented features, we like to get community confirmation and feedback on the importance of the feature

**Comment by ches** [comment]
Thanks @fehguy. I take

> the Schema Object which is a subset of JSON Schema Draft 4

and my other above quotation to mean that *for the subset* that the Schema Object encompasses, the types should (eventually) be completely conformant to JSON Schema.

But I misread @dolmen's link above when I said that there is an inconsistency—the Swagger schema does include `boolean` in the `anyOf` for `additionalProperties`. So it's just the implementation in swagger-codegen and possibly elsewhere that isn't supporting it yet, and thus this issue. My apologies for the oversight and the ensuing diversion :smile:

**Comment by webron** [comment]
Sorry for taking a while to reply.

So we definitely need to make this clearer in the spec (and please feel free to open a ticket on it once we clarify it). The spec itself is a bit incomplete with regard to how `additionalProperties` is intended to work.

Unlike what's stated, `additionalProperties` can only take an object value. An empty object value is equivalent to setting the value to `true`. Now, the reason why `false` is not needed is because... that's the default value. Yes, this is different than how JSON Schema works, but that's our assumption all along (and again, will be clarified in the spec). We can go into the 'why' but that's what it is, and I do apologize for the confusion. 

Given that, you should not require having to set `additionalProperties: false` at all and would not encounter the issue raised in this ticket.

**Comment by dolmen** [comment]
@webran Thanks for the clarification. The JSON schema for Swagger must be updated to match your definition to disallow `"additionalProperties": true`. I'll make a PR that add an enum.

About the codegen issue, not that codegen does not accept either an empty object.

Here is a test case that fails html generation:
```json
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "test of Swagger of boolean additionalProperties"
  },
  "paths": {
    "/": {
      "get": {
        "produces": [ "application/json" ],
        "description": "xxx",
        "responses": {
          "200": {
            "schema": { "$ref": "#/definitions/Root" }
          }
        }
      }
    }
  },
  "definitions": {
    "Root": {
      "type": "object",
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    }
  }
}
```

**Comment by dolmen** [comment]
I wrote:
> The JSON schema for Swagger must be updated to match your definition to disallow "additionalProperties": true. I'll make a PR that add an enum.

I just submitted swagger-api/swagger-spec#477
