### ISSUE TITLE
Reference for template variables?

### ISSUE THREAD

**Issue by ches** [swagger-api/swagger-codegen#1320]
Forgive me if this isn't a good place to ask this, but I was looking at the [Building your own Templates wiki page][1] and saw that @wing328 just edited it minutes before, so I thought it might be a good time to ask and update that page further…

Where can I find info or source code for where the template context/variables come from? It would be useful to compile a reference of what's already available, since a lot of customization can probably be done simply by editing templates, without needing to modify transformer code. I'm digging through to grok the transformers and `DefaultCodegen` but it's not jumping out at me yet…

Thanks!

[1]: https://github.com/swagger-api/swagger-codegen/wiki/Building-your-own-Templates

**Comment by wing328** [comment]
@ches I totally agree with you that a list of template variables would be helpful to swagger-codegen contributors. If it's not too urgent, I'll compile a list later after I submit PRs to enhance the exception handling for SwaggerCodegen.

Do you mind sharing more with us your requirement? Are you working on adding a template for another language or framework?

**Comment by ches** [comment]
Thank you, no it's not terribly urgent :smile: 

So far, I'm just considering some tweaks to the ObjC templates, for one to add doc comments from `description` fields when available in some places where this isn't already done, and then perhaps functional changes to suit organization preferences. Some upstream-able and some not, I think :wink: 

It's certainly possible I'd work on other langs/frameworks in the future too, after getting more familiar and as needs arise.

**Comment by ches** [comment]
Okay, this is becoming a little more urgent for me :smile: 

@wing328 could you just give me a pointer to where code lives that sets up the template context/vars? I think I can mostly grok what I need to know from that point, and hopefully come back to share some suggested wiki doc additions myself once I've dug into it.

Thanks!

**Comment by wing328** [comment]
@ches one way to obtain the template variables is to use the "debugOperations" or "debugModels" switch, e.g.
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l csharp \
  -o /var/tmp/csharp/test/ \
  -D debugModels=true
```
which will print out the template variables for models. For operations (resources), please use "debugOperations" instead.

Would these help?

**Comment by ches** [comment]
Woohoo! Yes, that's a huge help, thanks!

**Comment by wing328** [comment]
Good. I'll document these in the wiki page for future reference.

**Comment by wing328** [comment]
Documented at https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables
