### ISSUE TITLE
POST resources with EMPTY json response schema {} fails to generate the API classes

### ISSUE THREAD

**Issue by amitkshirsagar13** [swagger-api/swagger-codegen#1321]
Please find the attached jsons samples, I have included documentation with empty {} json as response and other as some response in json. Also, I have given same resource with using PUT with no schema to return.

Getting error as below,

writing file C:\ATG\developer.back\workspaces\ws_swagger_codegen\java\mission/src/main/java/io\swagger\client\model\CompanyTargetsParameters.java
java.lang.NullPointerException
        at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.modelImplToXml(XmlExampleGenerator.java:59)
        at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:38)
        at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:119)
        at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:27)
        at com.wordnik.swagger.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:46)
        at com.wordnik.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:759)
        at com.wordnik.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:322)
        at com.wordnik.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:296)
        at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:153)
        at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:77)
        at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)

Case 1: Not working with POST when response has a schema defined which does not have any response in it.

![notworkingwhenpostwithemptyjsonschemaasresponse](https://cloud.githubusercontent.com/assets/7577083/10223675/dc4b9164-681f-11e5-8e0d-09c21cad6ab7.png)

Case 2: Working with POST when response has a schema defined which does have some response in it.

![workingwhensomeresponsepresentinschamewithpost](https://cloud.githubusercontent.com/assets/7577083/10223674/dc49575a-681f-11e5-9857-db601dfd73fe.png)

Case 3: Working with PUT when response has a no schema defined for response.

![workingwithput](https://cloud.githubusercontent.com/assets/7577083/10223676/dc4b8d40-681f-11e5-94f8-25ecb9e38663.png)

**Comment by amitkshirsagar13** [comment]
I think, the root cause of the issue is for below,

Not working:
"produces": ["application/json",
				"text/json",
				"application/xml",
				"text/xml"],

Working:
"produces": ["application/json",
				"text/json"],


So, looks like when response schema contains {} Empty JSON, its not able to produce the client api with xml and which is causing it to fail.

if we some how make it correct the code for xml response also then it will work

Thanks,
Amit

**Comment by wing328** [comment]
@amitkshirsagar13 `produces` is mapped to `Accept` in the API client. For your server, does it have a preference to return data in XML format if "application/xml" is present (the last item) in the HTTP accept header?

**Comment by amitkshirsagar13** [comment]
I think, the issue was they had specified {} JSON as response with application/json.

This combination is failing, so, either we need to fix the code-gen to handle the scenario and allow {} to be as return response in application/JSON.

empty response in case of application/XML some how is working.

Thanks,
Amit

**Comment by wing328** [comment]
@amitkshirsagar13 Using [petstore.json](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L218), I created an Object without any properties (using {}) and updated getPetById to return the Object (response). Running `./bin/java-petstore.sh` and `./bin/php-petstore.sh' did not result in any exception.

**Comment by amitkshirsagar13** [comment]
Can you use something like below,

"parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": false,
            "schema": {
              "$ref": "#/definitions/Object"
            }
          }
        ]




Schema as below.


	  "Object" : {
		"type" : "object",
		"properties": {
		
		}
	  }

**Comment by amitkshirsagar13** [comment]
If you try to use something like above it will fail while generating the Api classes.

**Comment by amitkshirsagar13** [comment]
If you can send me email on amit.kshirsagar.13@gmail.com, I can send you sample json, which you can try to work with.

**Comment by wing328** [comment]
I did try with the above but maybe I made a mistake in my tests. I'll do another test tomorrow.

In the meantime, do you mind pulling the latest master (git pull && mvn clean package) and give it a try again?

**Comment by amitkshirsagar13** [comment]
Sure, I will.

**Comment by wing328** [comment]
I used https://gist.githubusercontent.com/wing328/2270a0bf6b089ebb0f89/raw/340c950e60eb6cb2dac6d137b641468f2e26c762/swagger_empty_object.json but couldn't repeat the issue.

**Comment by amitkshirsagar13** [comment]
Yes, it looks like its working.

Some how it was not working before.

Not sure, where I was missing.

Sorry for false alarm and wasting time.

:'(

Thanks,
Amit

**Comment by amitkshirsagar13** [comment]
Can you also try to see if we can work on other issue I raised,

https://github.com/swagger-api/swagger-codegen/issues/1324

**Comment by wing328** [comment]
OK. Closing this one.

**Comment by amitkshirsagar13** [comment]
Thanks.
