### ISSUE TITLE
Need provision to add import packages on API Classes

### ISSUE THREAD

**Issue by amitkshirsagar13** [swagger-api/swagger-codegen#1324]
I think, there should be provision in config file to import specific classes/packages on Generated API classes.

Currently, I am having issue while importing APIs which complain about asking for forcefully use import java.lang.Object in API classes.

It will be great if there is provision to add certain package/class for import in API class while generated.

Something like --api-import "{imports:['java.lang.Object', 'xxx.temp.dummy.SampleClass']}"

Please see if we can work on this to provide additional flexibility.

**Comment by wing328** [comment]
@amitkshirsagar13 is your issue similar to this one (springmvc): https://github.com/swagger-api/swagger-codegen/issues/1258 ?

**Comment by amitkshirsagar13** [comment]
No, Actually, Its bit more than that, I know it might seem unnecessary, but it will be good if, we can have provision to import specific Classes/Packages in API to make sure, in future, no other class names created in Models will conflict.

There is one workaround currently, where we can patch or add those imports manually, but I think, it wont be difficult to provide a configuration and add those package/classes to import list in API classes.

Please give me a call if you want to discuss it more and I will be happy to explain the solution I have in my mind.

My Number is 901 319 2434 I am in Memphis TN.

**Comment by wing328** [comment]
@amitkshirsagar13 is your goal to reserve model name for future use?

**Comment by amitkshirsagar13** [comment]
No, Actually, I just want to import some special Classes in the API, like java.lang.Object, because if we have Object class created in Model, and if we are trying to refer it in our API class, by default it will be referred but In API class, Object is expected from java.lang.Object. So, it gets confused and asks to import specific Class java.lang.Object.

For this, I have written a patch which will add the import java.lang.Object; line in the API class generated, I thought if there are such conflicts with other classes also, we can have those imported using this option.

So, we dont need to manually update the client API generated classes, or need any patch to write just to add import lines.

I hope I am able to explain what issue I was facing.

**Comment by wing328** [comment]
I think one way to meet your requirement is to clone this repo and add the class you want to import manually in the mustache template here: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/Java

**Comment by fehguy** [comment]
I do believe there is a default section for each language, which lets you configure which classes are automatically added by the language/framework.  Please take a look there and reopen with any questions.
