### ISSUE TITLE
Can't generate clients from the Instagram example. 

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#1325]
_From @chrislatimer on October 1, 2015 16:50_

None of the clients seem to generate when the instagram example is used. A 500 error is returned without any details. Happens both when running locally and from editor.swagger.io. 

_Copied from original issue: swagger-api/swagger-editor#675_

**Comment by webron** [comment]
@chrislatimer - I can't seem to reproduce it. Is it the instragram example as-is or did you modify it? Can you please try reloading the example and giving it another try?

**Comment by chrislatimer** [comment]
Hi @webron when I do File -> Open Example -> Instagram with no changes I can't generate any clients.

![image](https://cloud.githubusercontent.com/assets/831081/10233561/28d2f198-685d-11e5-990d-85f45c571c7b.png)

**Comment by webron** [comment]
@mohsen1?

**Comment by mohsen1** [comment]
I'm getting the same 500 error with this body:

```
{"code":500,"type":"unknown","message":"something bad happened"}
```
Editor is not showing the error modal which is a bug I opened here https://github.com/swagger-api/swagger-editor/issues/678

**Comment by webron** [comment]
Sorry, I had some network issues. Will retest in a bit.

**Comment by fehguy** [comment]
Builds fine against current master, which will be deployed to the online generator tonight.
