### ISSUE TITLE
documentation/readme relying on docker

### ISSUE THREAD

**Issue by ducin** [swagger-api/swagger-codegen#1326]
Hello,

I've been trying to play around with swagger, trying to generate an HTML docs file file based on a swagger definition file. I don't have docker installed and I'm strongly convinced, that I should not need docker to run swagger. The problem is that [readme](https://github.com/swagger-api/swagger-codegen#build-and-run-using-docker) (or [this readme link](https://github.com/swagger-api/swagger-codegen/blob/master/README.md#build-and-run-using-docker)) shows only how to both build and run server stub using docker.

I come here as a swagger newbie, motivated by the community to try swagger, and I'm completely lost. I do have problems with generating HTML swagger docs, but I don't know if it's related to docker or not. AFAIK the only hard-dependency on swagger is just Java and Maven. If so, the basic instructions for swagger-codegen should rely on Java and Maven only. I wish the docs included instructions without docker. Maybe the best solution is to include both (with docker + without docker) to make everyone happy.

PS the whole swagger idea seems to be a great thing. But trying to set it up on a CI is really hard for a beginner IMHO.

**Comment by webron** [comment]
Hi @ducin - thanks for the feedback. You're indeed correct and docker is definitely not required to run the codegen. The order of the readme is misleading and we'll fix that.

In the meantime, assuming you clone the repository, please follow the instructions from the following step - https://github.com/swagger-api/swagger-codegen#os-x-users (if you're not on os x, skip to the next one).

If you want to integrate it with your CI, you don't even need to clone the repository and build the project on your own, but for now, I'd suggest we get you to a point where you can run it from your own machine and continue from there.

**Comment by ducin** [comment]
Hi @webron, thanks for a fast reply!

I've managed to make `swagger-codegen` work under `mvn`. I just find current documentation unclear due to docker presence *and* incomplete commands, such as [this one](https://github.com/swagger-api/swagger-codegen#generating-static-html-api-documentation). As a result, it takes more time to go through it than it could ;)

----

If you're open to more feedback, I'd suggest improving the readme first. Guess, if I'm lost, then other people might be lost as well...

In the [`json-schema-faker`](https://github.com/json-schema-faker) project we face a similar problem - trying to keep a complex tool simple for the community (I'm a co-author of it). The thing I'd suggest for a good start is to add a table of contents, just like [this one](https://github.com/json-schema-faker/json-schema-faker#table-of-contents). It'd be easier for all (both experienced guys and newcommers) find relevant info in a big readme.

**Comment by webron** [comment]
Sure, feedback is always welcome. The problem is normally lack of time not lack of willingness :)

When you say incomplete command, do you mean you'd want to see the full command rather than just the flag to be used?

**Comment by ducin** [comment]
I might PR a table of contents, if you like this idea. I'm happy to contribute as long as my commits don't lie in github PRs for months ;)

regarding incomplete commands - IMHO the best solution is to leave the flag to be used as it is, but to add a complete example. If the flag is obvious, then you may skip the example. But if it's not, the example is useful.

**Comment by webron** [comment]
We do our best to merge PRs in a timely manner, especially in this project which highly depends on user contributions. Feel free to submit a ToC PR.
