### ISSUE TITLE
generating static HTML docs - assets are broken/missing

### ISSUE THREAD

**Issue by ducin** [swagger-api/swagger-codegen#1327]
I'm trying to generate a static documentation for a given swagger definition file (something that would look just like the [petstore example](http://petstore.swagger.io/)). For that purpose I'm just using the [petstore definition file](http://petstore.swagger.io/v2/swagger.json).

Having java and maven installed, I'm running (Windows under powershell, nevermind the (back)slashes):

```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l html
reading from http://petstore.swagger.io/v2/swagger.json
writing file c:\Users\tomasz.ducin\Development\Learning\swagger-codegen\.\index.html
```

The result is just the `index.html` file produced in the main project directory. I know I can move it using the `-o` option. Anyway, I can see that this file tries to load `site.css`, which doesn't exist. But the index.html file includes some CSS, which look different than the petstore example (in fact, it's significantly uglier and less user-friendly than the online petstore demo).

I've managed to find some assets in `...\swagger-codegen\modules\swagger-codegen\target\classes\swagger-static\assets`, but these are not copied during the `html` build. Moreover, when I copy the `...\swagger-codegen\modules\swagger-codegen\target\classes\swagger-static\assets\css\site.css` file next to auto-generated index.html, it is not used (and the generated docs remains ugly).

Seems like the `html` build is either corrupted or messy.

I know I can copy & paste the swagger definition to the awesome editor of yours, then copy & paste the generated HTML, but I want to automate the process for the night build on a CI environment, so browser-based copy & paste is not an option.

Maybe there is some better way to do that, but I didn't manage to find it.

**Comment by webron** [comment]
I'll leave it to @wing328 to comment about the missing assets, but I wanted to make sure you understand that the ui you see in the online pet store is not the same as the html generated by this project, and that they serve different purposes. I'm not sure what your end goal is in this case, but if you provide us with more details, we may be able to suggest some other routes.

**Comment by ducin** [comment]
My purpose is quite simple - suppose I've got a swagger definition file and I want to generate an HTML/css/js-based documentation for it. I want to do it automatically every day (under a CI), since the definition file is under a VCS.

After reading about ~codegen, ~UI and ~editor, to be honest, I didn't figure out that html codegen and ui serve different purposes. At least I couldn't find which one suits my needs. The thing I can see at the [petstore demo](http://petstore.swagger.io/) is perfect - user-friendly, clear and enables to execute operations from the browser.

Just to compare - for the whole `API blueprint` tool stack, it's clear that you should use [`aglio`](https://github.com/danielgtaylor/aglio) to generate docs. Here it's not clear.

**Comment by webron** [comment]
So let's try and make things clearer.

swagger-editor is used for editing new definitions. Its preview is not standalone and cannot be used independently with your projects.

swagger-ui is a set of static flies that load a swagger definition dynamically. You can include it as part of your application or host it separately, and simply point it to your swagger definition. The online pet store is a java application that includes the swagger-ui as part of it and simply loads its output at run time. This UI is more interactive and gives you a way to execute your API.

swagger-codegen will generate a different set of html file(s) that is more static. It does not include your swagger definition but simply builds a static html pre-built with all the information and does not provide you a way to interact with your API.

To me, it sounds like you're looking to use swagger-ui rather than swagger-codegen.

**Comment by ducin** [comment]
@webron thank you for this explanation! My quick summary:
1. swagger-codegen->html is just static docs
2. swagger-ui is docs + play around (execute)
3. I was missing an overview just as you did above. It might be anything (a blog post or a small section on swagger.io website) as long as it's easily accessible (i.e. linked from the website). Maybe something like "common usecases" or "beginners guide"?

And getting to the original issue - `swagger-codegen`/`html` has some inconsistencies regarding assets...

**Comment by webron** [comment]
I'm writing a series of blog posts about [getting started with Swagger](http://swagger.io/getting-started-with-swagger-i-what-is-swagger/) - there's a pending post and another one waiting to be written. I'll take your comments into account in a future post in the series in hopes of clarifying it.

**Comment by wing328** [comment]
@ducin according to #666, site.css is no longer needed but I can still find site.css in index.html. 

Submitted #1335 to remove site.css from index.html.

**Comment by ducin** [comment]
thanks

**Comment by wing328** [comment]
PR merged into master
