### ISSUE TITLE
Spring MVC client codegen support missing?

### ISSUE THREAD

**Issue by raja6955** [swagger-api/swagger-codegen#1339]
Hi,

I see support for SpringMVC server side stub codegen but not for spring MVC client side (RestTemplate based). The java client generates JaxRS/Jersey client and my requirement is to use spring RestTemplate. Would that be added anytime soon?

**Comment by wing328** [comment]
@raja6955 currently, the Java client supports the following libraries:
```
	library
	    library template (sub-template) to use:
	    <default> - HTTP client: Jersey client 1.18. JSON processing: Jackson 2.4.2
	    jersey2 - HTTP client: Jersey client 2.6
	    okhttp-gson - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1
	    retrofit - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1 (Retrofit 1.9.0)
```
RestTemplate is not yet supported. Is it a must to use RestTemplate?

Java clients using other HTTP libraries should work with the Spring backend without issue.

**Comment by wing328** [comment]
@raja6955 we're closing this issue since we've not received any update from you.
