### ISSUE TITLE
Can't built codegen from behind a proxy

### ISSUE THREAD

**Issue by ryber** [swagger-api/swagger-codegen#1343]
mvn can't build the codegen project from behind a proxy. There are issues with the google download plugin steps. I'm not sure if this step is absolutely needed for generating code or not. I actually would love the option to just download the jars but the Maven central repository only has the POMs and not the jars?
http://mvnrepository.com/artifact/io.swagger/swagger-generator/2.1.2
https://repo.maven.apache.org/maven2/io/swagger/swagger-generator/2.1.2/swagger-generator-2.1.2.pom (200)
https://repo.maven.apache.org/maven2/io/swagger/swagger-generator/2.1.2/swagger-generator-2.1.2.jar (404)

```
[INFO] --- download-maven-plugin:1.2.1:wget (swagger-ui) @ swagger-generator ---
Downloading: https://github.com/swagger-api/swagger-ui/archive/master.tar.gz
java.net.UnknownHostException: github.com: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
```

**Comment by wing328** [comment]
@ryber you can also use the online generator. Here is an example:
```
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' http://generator.swagger.io/api/gen/clients/php
```

**Comment by fehguy** [comment]
You can also grab the codegen executable jar from here:

https://oss.sonatype.org/content/repositories/releases/io/swagger/swagger-codegen-cli/

**Comment by elouanKeryell-Even** [comment]
I think passing proxy options this way works:

```
mvn clean install -Dhttp.proxyHost=12.23.34.45 -Dhttp.proxyPort=1234 -Dhttps.proxyHost=12.23.34.45 -Dhttps.proxyPort=1234
```

**Comment by diyfr** [comment]
You can add a proxy in the Maven settings file
```
   <proxies>
		<proxy>
			<active>true</active>
			<protocol>http</protocol>
			<host>my.proxy</host>
			<port>8080</port>
			<nonProxyHosts>*.domain.tld|*.domain2.tld</nonProxyHosts>
		</proxy>
	</proxies>
```
If you already have a proxy defined in https you can replace http to https in [pom.xml](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-generator/pom.xml#L114)
