### ISSUE TITLE
Swagger-editor: Using items without type: array still validated ok

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#1344]
_From @hpoints on October 6, 2015 19:42_

My yaml validated ok, but then I could not generate any client/server artifacts. Had to manually find the error. My error was using items in some places where schema should have been used.

_Copied from original issue: swagger-api/swagger-editor#681_

**Comment by mohsen1** [comment]
A JSON Schema like this: `{"type": "array"}` is describing an array with *any* element. It is valid JSON Schema. This is a problem in swagger-codegen where it doesn't like arrays without `items` schema.

**Comment by wing328** [comment]
@mohsen1 according to the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-7), if type is `array`, then `items` must be provided.
```
items	Items Object	Required if type is "array". Describes the type of items in the array.
```

**Comment by mohsen1** [comment]
Then the swagger json schema should catch it. @webron

**Comment by webron** [comment]
Well, there's https://github.com/swagger-api/swagger-spec/issues/404 and https://github.com/swagger-api/swagger-spec/pull/413.

**Comment by fehguy** [comment]
I believe we fall back to string in the codegen if the inner type is not specified.
