### ISSUE TITLE
Error in node.js index.mustache template

### ISSUE THREAD

**Issue by oYo-fr** [swagger-api/swagger-codegen#1349]
In nodejs file index.js when generating a node.js server, the variable serverPort is never used.
In file /modules/swagger-codegen/src/main/resources/nodejs/index.mustache, which seems to be the template for this file, I think we should have this (lines 34 to 37):

  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
    console.log('Swagger-ui is available on http://localhost:%d/docs', serverPort);
  });

Instead of this:

  http.createServer(app).listen({{serverPort}}, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', {{serverPort}}, {{serverPort}});
    console.log('Swagger-ui is available on http://localhost:%d/docs', {{serverPort}});
  });

... notice the removal of {{ }} surrounding the "serverPort" variable.

**Comment by wing328** [comment]
@oYo-fr  I agree that the variable `serverPort` should be used instead of `{{serverPort}}`. Do you have cycle to submit a PR for the change?

**Comment by oYo-fr** [comment]
Hi wing328,

I would love to make a pull request but I simply don't know how to do it :(

I suck at git :-/
