### ISSUE TITLE
generator.swagger.io - Error invoking /gen/clients/* - Disk space?

### ISSUE THREAD

**Issue by goncaloborrega** [swagger-api/swagger-codegen#1350]
All requests to http://generator.swagger.io/api/gen/clients/{language} are yielding an error:
*Unable to build target: Could not process operation*

Example using curl and petstore
```
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' http://generator.swagger.io/api/gen/clients/objc 
```

result

```
{
"code":1,
"type":"error",
"message":"Unable to build target: Could not process operation:\n  Tag: pet\n  Operation: findPetsByStatus\n  Resource: get /pet/findByStatus\n  Definitions: {Order=io.swagger.models.ModelImpl@42fe8e87, User=io.swagger.models.ModelImpl@47191636, Category=io.swagger.models.ModelImpl@b616536a, Tag=io.swagger.models.ModelImpl@99c7ebc6, Pet=io.swagger.models.ModelImpl@67e0aabb, ApiResponse=io.swagger.models.ModelImpl@b94d6109}"
}
```

Feedback on irc channel pointed to full disk

**Comment by fehguy** [comment]
looks like it was a commit that caused this.  https://github.com/swagger-api/swagger-codegen/commit/733e19c113b3cf77be28489ae9bc07b425cdd053 should address it, and I've pushed the fix to the online version.  Thanks for reporting and reopen if you see any other issues.
