### ISSUE TITLE
[Java][Android] Make android a sub template of the Java generator

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#1353]
This way android would benefit from the enhancements of the Java generator.
Also I wonder if the android specific files could not be added to all the Java templates so that you can choose which libraries you want to use for your android app ?

**Comment by wing328** [comment]
@cbornet currently the `okhttp-gson` is compatible with Java, Android and Scala. What  other HTTP libraries you would like to add for Android client in the Java template? 

Personally I welcome the support of more libraries in the Java template.

**Comment by cbornet** [comment]
@wing328 yes, my point is that all java libraries could be made compatible with android and that they could have a android-build.gradle to generate an android apk.
And the android generator could be made as a java sub-template renamed "apache-httpclient-gson" for instance (or even completely removed because who still uses apache-httpclient ? ;-))

**Comment by cbornet** [comment]
@wing328 Now that all java libs support android, what should be the next step : remove android codegen and document that java codegen supports android or move it to java apache-httpclient-gson ?

**Comment by wing328** [comment]
@cbornet thanks for the effort on that. Much appreciated. 

Last time when I sunset the Python3 generator, I updated the README to inform the users that this generator won't be updated/patched any more and moving forward they should use the Python generator, which works with both Python 2.x and 3.x. Not sure how many users actually read the updated README but I suggest we also do the same this time.

Even better, we can post in the Google Group to inform the community about sunsetting Android generator in the future and they should use the Java generator as a replacement instead. (To me, one month of notification is enough)

Also if we remove the Android generator, users will no longer see "Android" under the "Generate Client" dropdown menu. Maybe we should rename the Java generator to something else (e.g. Java & Android).

**Comment by cbornet** [comment]
OK. I just discovered that there are some things missing in the java libs to be fully compatible with android (like a Manifest file). I will fix this ASAP

**Comment by cbornet** [comment]
There is also an issue with javax annotations Generated which is not part of Android by default

**Comment by cbornet** [comment]
@wing328 There is no README file in android templates and I don't see the point of adding one now just to say that it is deprecated. I have submitted a PR to deprecate it in the editor (although it is rejected by CI and I don't really know why...). 
So where else should we notice the user that android-java is deprecated ? I looked at getHelp() method of Codegen but it seems it is not used anymore...

**Comment by karussell** [comment]
@cbornet Is android-java deprecated? If so, I would point this out while calling the command with this option

My problem is now that user reports problems with the 'pure' java client and Gradle&Android: https://github.com/karussell/directions-api-vrp-java-client/issues/8

Now I thought I would use the android client instead but reading this thread here indicates I should keep using the java client but a more recent version. Is this corrent? Could an update fix the issue?

**Comment by cbornet** [comment]
@karussell you shouldn't use the default android-java as it is based on the deprecated apache httpclient. Instead I would either use android-java with the brand new "volley" library option or use java with the "retrofit" or "retrofit2" option. The latest java generators should be compatible with Android (with a config field to set). If it is not the case for you, please open a detailed issue and I will have a look.

**Comment by karussell** [comment]
Thanks! So your aim is to just have one java client in the future with different options for the used (http) libraries where some of them are (or should be) Android compatible?

What I would need is a client working on the Desktop and for Android. So 'volley' is not an option for me I guess?

And I guess retrofit is the current stable retrofit where retrofit2 is the not yet "stable released" retrofit2?

**Comment by cbornet** [comment]
If you want one client lib for all, then maybe the [Feign](https://github.com/Netflix/feign) generator would be the best bet. On android, you can easily plug okhttp with it.

**Comment by cbornet** [comment]
And on server you can plug Ribbon, Jackson and Hystrix

**Comment by xhh** [comment]
@karussell FYI. the `okhttp-gson` template of Java client is verified to work in both JVM (desktop or server) and Android.
See the Petstore sample on how to specify the option for it:
https://github.com/swagger-api/swagger-codegen/blob/master/bin/java-petstore-okhttp-gson.sh#L29
https://github.com/swagger-api/swagger-codegen/blob/master/bin/java-petstore-okhttp-gson.json#L2

**Comment by karussell** [comment]
@xhh & @cbornet thanks for these infos!

**Comment by karussell** [comment]
Different options for a Java environment are provided to give the developers freedom of choice and potentially reduce dependencies (e.g. if jackson is already used) or what is the intention behind this?

**Comment by cbornet** [comment]
Closing this as now the android codegen now uses "volley" and it doesn't make sense to mix it with java codegens.
We can have a discussion on extracting the common attributes for java-based generators in an abstract codegen in another issue.

**Comment by karussell** [comment]
Can you roughly outline for me why not just using gson+okhttp for Android? I do not like the idea much of having two clients and currently using gson+okhttp to solve this.

**Comment by wing328** [comment]
@karussell the short answer is that some users prefer `volley` instead of `okhttp` (they didn't mention why they prefer `volley` though)

**Comment by cbornet** [comment]
volley is very popular for android users and the android team is now maintaining it directly (https://android.googlesource.com/platform/frameworks/volley).
okhttp-gson is also a good choice but you should really have a look at [retrofit](http://square.github.io/retrofit/) which uses okhttp internally and gives a cleaner way to write the api methods with annotations.

**Comment by cbornet** [comment]
And the retrofit client has oauth2 support with automatic management of the token if that is of interest for you.

**Comment by karussell** [comment]
Thanks for the clarification and will have a look at your links! But if I do not use oauth2 and the classes are created for me like for swagger then I could prefer the smaller lib :) ?

**Comment by cbornet** [comment]
Your choice but that won't make a very big difference.
I recall you wanted to have the same client in server back-end and android. Then I suggest also having a look at Feign which is IMO the best library for servers (obviously, it's developped by Netflix :smile: ). For your android client, you can very easily plug on it okhttp for the network calls. The only possible drawback is that even though it's possible to make Feign use gson, the current generator generates for jackson.
