### ISSUE TITLE
Usage of $httpHeader in exception handler

### ISSUE THREAD

**Issue by arnested** [swagger-api/swagger-codegen#1354]
In the PHP client `$httpHeader` is used in the exeception handler: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L176

But the variable is only set as a return value from the very same callApi that throws the exception: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L168

Because of this I get a lot of PHP notices:
```
Notice: Undefined variable: httpHeader
```

I think this was introduced in 7f31da734d94fd34d9d39070509d4ed536533190 and fcd0b31d7d3b2d7a7a185481676a58942404a691 (@wing328).

Isn't this a bug?

**Comment by arnested** [comment]
I could make a pull request fixing this - but I'm not quite sure I understand the use case this is supposed to support and how to achieve this in a better way.

**Comment by wing328** [comment]
@arnested so far the only use case for $httpHeader is when the response is `file` and the filename can be obtained from $httpHeader.

**Comment by arnested** [comment]
Thank you for the quick reply.

So after looking in to the `ApiException`callss I guess the line (https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L176) should be changed from
```php
$data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '{{dataType}}', $httpHeader);
```
to
```php
$data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '{{dataType}}', $e->getResponseHeaders());
```

Unless you say I got this wrong I'll create a pull request.

**Comment by wing328** [comment]
I think there's something wrong with file download at the moment. I'll do a test and reply back.

($httpHeader should be passed to the `deserialize` method at https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L188 instead)

**Comment by arnested** [comment]
But that won't change the fact that `$httpHeader` is an undefined variable in the `catch`blocks.

(There might be something wrong with the file download also but I haven't used that (yet)).

**Comment by wing328** [comment]
You're absolutely right: it ($httpHeader) should not be used in the catch block

I just did a test. File download still works but the file name is randomly generated: 
```
[INFO] Written 156 byte to /private/var/tmp/php/7hT2LE. Please move the file to a proper folder or delete the temp file after processing.
SplFileObject Object
(
    [pathName:SplFileInfo:private] => /private/var/tmp/php/7hT2LE
    [fileName:SplFileInfo:private] => 7hT2LE
    [openMode:SplFileObject:private] => w
    [delimiter:SplFileObject:private] => ,
    [enclosure:SplFileObject:private] => "
)
```
To fix that, we need to pass $httpHeader in the `deserialize` method at line 188 and move the `{{returnType}}` tag inside the try block.

**Comment by arnested** [comment]
I create pull request #1355 for not using `$httpHeader` in `catch` blocks.

Regarding the file download issue I really have no experience but I tried to implement the solution you sketched (not tested - and I'm definitely on thin ice regarding my understanding of the code base): https://github.com/arnested/swagger-codegen/commit/3bd4502bbf1cf3a4feb9e378ae0d4b4f421e4a28.

**Comment by wing328** [comment]
Thanks for incorporating the fix into your PR. It looks good to me.

**Comment by arnested** [comment]
Well, they are actually two PR's now. I can combined them to one if you prefer.

**Comment by wing328** [comment]
It's fine. Will review and approve accordingly.

Thanks for your help in fixing the issue.

**Comment by arnested** [comment]
Thank you for the quick follow up. It is real pleasure not having to wait for ages before getting feedback!

**Comment by wing328** [comment]
PRs merged into master. Issue closed.
