### ISSUE TITLE
Example Usage / Sample Code

### ISSUE THREAD

**Issue by jhitchcock** [swagger-api/swagger-codegen#1363]
Hello, I'm In the process of writing a 'Slate Docs' generator. 

Does anyone have a bit of sample code for using the Obj-C Generated Library? 

Or is there a resource somewhere with code samples for all libs? 

Whilst I'm happy to make my own for some languages, I can't do that for all the ones I want to cover 

.

**Comment by wing328** [comment]
@jhitchcock would the test code for Petstore ObjC client help? https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/objc/SwaggerClientTests/Tests/PetApiTest.m

**Comment by jhitchcock** [comment]
Thanks for that @wing328 It's a good starter! Never even thought of looking at the tests ;)
