### ISSUE TITLE
objc not generating models

### ISSUE THREAD

**Issue by rkaltreider** [swagger-api/swagger-codegen#1367]
When i try to generate objc code i only get two files called FPSeedItem.h and .m.. any ideas?

**Comment by wing328** [comment]
@rkaltreider can you share the spec so that we can reproduce the issue?

**Comment by wing328** [comment]
Closing this as we've not received any update from you.

**Comment by rkaltreider** [comment]
I am sorry for not getting back sooner. I am not able to share the entire spec at this time.  Is there a particular portion that would suffice? or a known incompatibility?  I am able to successfully produce Java, .NET, PHP, Python, and Ruby.  It just seems like the objc and swift do not work because they only produce 2 files.

**Comment by wing328** [comment]
@rkaltreider are you using the latest master of swagger-codegen?

**Comment by rkaltreider** [comment]
i am using the 2.1.3 release.

**Comment by wing328** [comment]
Please pull the latest as 2.1.3 was released almost 2 months ago.

**Comment by rkaltreider** [comment]
Here is the batch script i use to generate objc

~~~
@echo off
::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::: GLOBAL VARIABLES ::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::
set SWAGGER_CODEGEN_CLI="D:\swagger-codegen-213\swagger-codegen-cli.jar"
set APIDOCS_PATH="<PRIVATE>"
set SEVENZIP_PATH="C:\Program Files\7-Zip\7z.exe"

IF "%PROJECT_VERSION%"=="" set PROJECT_VERSION=1.0.0-SNAPSHOT

@echo { > config.json
@echo 	"classPrefix" : "SC", >> config.json
@echo 	"podName" : "SomeClient", >> config.json
@echo 	"podVersion" : "%PROJECT_VERSION%" >> config.json
@echo } >> config.json

java -jar %SWAGGER_CODEGEN_CLI% generate -i %APIDOCS_PATH% -l objc -o %WORKSPACE% -c %WORKSPACE%\config.json
del %WORKSPACE%\config.json

cd %WORKSPACE%
%SEVENZIP_PATH% a -tzip flavorprint-objc-client-%CLARITY_PROJECT_VERSION%-src.zip *
~~~

**Comment by wing328** [comment]
Please pull the latest and do a `mvn clean install` for swagger-codegen

**Comment by rkaltreider** [comment]
i can certainly do that.  is it possible to schedule a release for what is currently in master, or is a release pretty far off yet?  I am cool with cutting edge, but bleeding edge might be too much for my company to handle :)

**Comment by wing328** [comment]
Understood your concern, currently we don't have a release date for v2.1.4 but I'll get back to you on that later.

**Comment by rkaltreider** [comment]
Thanks @wing328 and again, apologies for not getting back sooner. I look forward to the next release!

**Comment by wing328** [comment]
@rkaltreider v2.1.4 has been released. Please refer to https://github.com/swagger-api/swagger-codegen/releases/tag/v2.1.4 for more information.
