### ISSUE TITLE
Authentication setting for operations are all empty (missing)

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#1371]
There seems to be an issue with the latest swagger-parser (1.0.11-SNAPSHOT) that authentication settings (`security`) for all operations are all empty (missing).

This can be confirmed by the debugOperations switch.

To workaround the issue, update pom.xml to use swagger-parser 1.0.10 for the time being

**Comment by fehguy** [comment]
I have deployed the fix to 1.0.11-SNAPSHOT, please close if you see it's fixed.

**Comment by cbornet** [comment]
Hello @fehguy I just tested a code generation and securityDefinitions are not parsed with 1.0.11-SNAPSHOT. It is OK with 1.0.10.

**Comment by fehguy** [comment]
Are you sure you got the latest snapshot?

**Comment by wing328** [comment]
@fehguy I just tested with `mvn clean install -U` to force maven download the latest snapshot of swagger-parser but still found the same issue (`security` in all operation missing).

**Comment by wing328** [comment]
Pulled the latest version and confirmed the issue has been resolved.
