### ISSUE TITLE
NullPointerException while processing body parameter

### ISSUE THREAD

**Issue by buremba** [swagger-api/swagger-codegen#1381]
This is the specification:
```json
{
  "swagger": "2.0",
  "paths": {
    "/event/collect": {
      "post": {
        "tags": [
          "collection",
          "event"
        ],
        "summary": "Collect event",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "test",
            "required": false,
            "schema": {
              "required": [
                "collection",
                "project",
                "properties"
              ],
              "properties": {
                "project": {
                  "type": "string",
                  "default": ""
                }
              }
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Project does not exist."
          }
        }
      }
    }
  }
}
```

Since body parameter doesn't have type and format, it fails with the following exception:
```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: default
  Operation: null
  Resource: post /event/collectJsonResponse=io.swagger.models.ModelImpl@70e463a8}
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:520)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:421)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:184)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1229)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1016)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:473)
	... 4 more
```

**Comment by wing328** [comment]
@buremba inline schema is not supported at the moment. Ref: https://github.com/swagger-api/swagger-codegen/issues/354

To workaround the issue, please properly define the model for the time being. Here is an example: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L45

**Comment by buremba** [comment]
@wing328 I searched for this issue but couldn't found it. Sorry for the duplication.

**Comment by wing328** [comment]
@buremba that's perfectly fine :)

Do you mind sharing with me how your swagger spec is generated?

There are plug-ins (e.g. [SpringFox](https://github.com/springfox), [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle)) that can easily generate Swagger spec right from the code. Let me know if you need more info.

**Comment by buremba** [comment]
@wing328 I'm using swagger-core with custom Swagger library that is forked from swagger-jaxrs. I developed it for my RESTful library that allows creating RESTful services easily. (https://github.com/buremba/netty-rest) I appreciate the hard work you put on Swagger, swagger-editor combined with swagger-codegen are really killer features. :)

**Comment by wing328** [comment]
@buremba thanks for sharing. Ping us if you need further assistance or have any feedback for us.

**Comment by buremba** [comment]
:+1:
