### ISSUE TITLE
Generating documentation for client libraries

### ISSUE THREAD

**Issue by buremba** [swagger-api/swagger-codegen#1387]
Even though their functions are same, each client api has different usages since each programming language has its own syntax and conventions.

Statically-typed languages such as Java has automatic api generators (javadoc) but in dynamically-typed languages users will have to look at the source code in order to use client libraries since there won't be any example of how the client library can be used.

It would be nice to generate documentations for client libraries that are also generated by swagger-codegen. The generated documentation will actually be similar to API documentation, except it will demonstrate constructing objects, passing parameters and executing queries.

**Comment by wing328** [comment]
@buremba thanks for the feedback. Here is a similar suggestion opened before: https://github.com/swagger-api/swagger-codegen/issues/1363

**Comment by jhitchcock** [comment]
I'm working on generating Slate documentation. Will PR once I am done. Not sure how long it will be though!

**Comment by buremba** [comment]
@jhitchcock I started a separate project that generates Slate markdown from Swagger specification. It's still far from being mature but may be helpful for you. https://github.com/buremba/swagger-slate

Currently, it uses custom template files and have `swagger-codegen` dependency in order to generate example usage section of Slate for different languages.

**Comment by wing328** [comment]
UPDATE: `html2` generates documentation with code samples.
