### ISSUE TITLE
[PHP][CURL] The usage of the @filename API for file uploading is deprecated

### ISSUE THREAD

**Issue by akkie** [swagger-api/swagger-codegen#1390]
Please see:
https://wiki.php.net/rfc/curl-file-upload
http://stackoverflow.com/questions/20972513/php-curl-the-usage-of-the-filename-api-for-file-uploading-is-deprecated
http://stackoverflow.com/questions/17032990/can-anyone-give-me-an-example-for-phps-curlfile-class

**Comment by wing328** [comment]
@akkie thanks for the link about the use of @filename for file upload being deprecated. I'm aware of that and my intention is to support PHP v5.3. Given that PHP v5.3 (and v5.4) are no longer supported, we plan to migrate to [Guzzle](http://docs.guzzlephp.org/en/latest/overview.html), which requires v5.5 or above, as suggested by other PHP users before.

Is that something you have cycle to contribute?

**Comment by wing328** [comment]
Ref: PHP Support Version - http://php.net/supported-versions.php

**Comment by akkie** [comment]
> Is that something you have cycle to contribute?

Sorry that I cannot help here. I'm really busy with my own OS projects and I avoid it whenever possible to code in PHP.

**Comment by wing328** [comment]
@akkie that's ok :)

Back to the original subject, is file upload broken for you or you just want to let us know we're using deprecated method for file upload?

**Comment by akkie** [comment]
I could fix it temporary by editing the `api.mustache` file manually and use `CurlFile` instead of the deprecated @filename method. So it's not really a problem for me.

**Comment by arnested** [comment]
This was fixes in #1451.

**Comment by wing328** [comment]
Thanks @arnested :beer: 

I'll open another task for updating the HTTP library to use [Guzzle](http://docs.guzzlephp.org/en/latest/)
