### ISSUE TITLE
Support library under config options for maven plugin

### ISSUE THREAD

**Issue by kkrauth** [swagger-api/swagger-codegen#1398]
Codegen process for java can be further parametrized with a library sub-template (i.e okhttp-gson). Maven plugin doesn't support this option so when "java" is specified as the target language, only the default template can be used (jersey).

**Comment by wing328** [comment]
#1400 submitted by @testn should fix the issue and has been merged into master. Please pull the latest and see if it works for you.

**Comment by testn** [comment]
when do you plan to release the version?

**Comment by wing328** [comment]
We have not finalized a date to release v2.1.4 so please kindly pull the latest master of swagger-codegen for the time being.

**Comment by kkrauth** [comment]
Thank you!
