### ISSUE TITLE
Ruby client url generation has adjacent slashes

### ISSUE THREAD

**Issue by jonocodes** [swagger-api/swagger-codegen#1399]
```
SwaggerClient.configure { |c| [ c.debugging = true, c.host='http://localhost:8080' ] }
apiclient = SwaggerClient::ApiClient.new
serviceapi = SwaggerClient::ServiceApi.new(apiclient)
serviceapi.config
```

Logs
```
GET //service/config HTTP/1.1
Host: localhost:8080
Accept: */*
User-Agent: ruby-swagger-1.0.0
Content-Type: application/json

HTTP/1.1 404 Not Found
```

And this is true, http://localhost:8080//service/config will 404 but
http://localhost:8080//service/config will not.

Anyway to get rid of this extra slash? I tried various values in the base_path.

**Comment by wing328** [comment]
@jonocodes are you using the latest version of swagger-codegen (master)?

I don't see double slashes in the Petstore example. Here is part of the tcpdump result:
```
GET /v2/pet/10002 HTTP/1.1
Host: petstore.swagger.io
User-Agent: ruby-swagger-1.0.0
Content-Type: application/json
Accept: application/json
```

**Comment by wing328** [comment]
@jonocodes I'm able to repeat the issue with different values of `base_path`. will submit a PR to address it. (Thanks for reporting the issue)

**Comment by wing328** [comment]
@jonocodes fix merged into master. Please pull the latest and reopen this if you're still seeing issues.
