### ISSUE TITLE
Ruby client: Cant get HTTP basic auth to work

### ISSUE THREAD

**Issue by jonocodes** [swagger-api/swagger-codegen#1407]
In the python client I am able to do something like the following
```
swagger_client.configuration.username = 'dev'
swagger_client.configuration.password = 'dev'
apiclient = swagger_client.ApiClient('http://localhost:8080', header_name="Authorization", header_value=swagger_client.configuration.get_basic_auth_token())
serviceapi = swagger_client.ServiceApi(apiclient)
```

In the Ruby client, I have not been able to figure out how to do this. I have tried several things, but perhaps this feature is not implemented. I dont see a way to pass in headers or get the ApiClient to regard the Basic auth params I have provided.

It looks like each api can accept opts buy they dont get used. 

I have tried Configuration.update_params_for_auth, but I dont see how it would ever work since Configuration.auth_settings is always an empty set.

**Comment by wing328** [comment]
@jonocodes in your swagger spec, the endpoints (which required basic HTTP auth) need to have proper authentication setting (`security`) defined. Do you mind sharing your swagger spec?

You do not need to call Configuration.update_params_for_auth manually. The method for the endpoint should do it automatically. Similar to python API client, you only need to use the Configuration object to set the proper username and password. 

(Also I'm assuming you're using the latest master from swagger-codegen)

**Comment by jonocodes** [comment]
Hello.

Yes, I am using the latest master.

My Ruby code looks something like this
```
SwaggerClient.configure { |c| [ c.host='http://localhost:8080',
   c.username = 'dev', c.password = 'dev'] }
apiclient = SwaggerClient::ApiClient.new
```

I have been using HTTP basic auth and have it working in swagger-ui.

My swagger spec output does not show anything about security. I am using Jersey (swagger-jersey2-jaxrs_2.10) and didnt know I needed to tell swagger about the security for this. I'm not sure how to expose that to swagger, but I will look some more.

**Comment by wing328** [comment]
Your swagger spec should contain something similar to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L245

and these should correspond to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L811

In the generated code, you can see the security setting at https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/ruby/lib/petstore/api/pet_api.rb#L240 to indicate that the endpoint requires certain authentication setting.

**Comment by wing328** [comment]
There was a recently resolved issue related to HTTP basic auth setting: https://github.com/swagger-api/swagger-parser/pull/117

Please pull the latest (mvn clean install -U) and give it a try again.

**Comment by jonocodes** [comment]
Thanks. I have almost got the 'security' key to work. I have it showing for my '@ApiOperation' annotation, but have not figured out how to get it to work for '@Api'. Also, I have not found any samples that explain how I can specify http basic auth.

But I do have a side question. If I want to include something in every request header from the Ruby client, how do I do it? I dont seem to see a way of doing it to all requests, or even on a single request.

**Comment by wing328** [comment]
What about setting `default_headers` in api_client.rb: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/ruby/lib/petstore/api_client.rb#L16 ? would that meet your requirement?

**Comment by jonocodes** [comment]
Thanks, that worked. For those who are looking, here is how I did it:
```ruby
SwaggerClient.configure { |c| [
   c.debugging = false, c.host='http://localhost:8080',
   c.username = 'dev', c.password = 'dev'] }

apiclient = SwaggerClient::ApiClient.new

apiclient.default_headers = {'Authorization'=> SwaggerClient.configure.basic_auth_token}
```

I will work on getting the annotations to appear.

**Comment by wing328** [comment]
@jonocodes FYI. You should not need to manually add the "Authorization" header if the authentication setting (HTTP basic) for endpoints are probably defined.

**Comment by jonocodes** [comment]
Yes. I am doing this as a workaround until I can get jersey swagger to generate the right security annotations for my service.
