### ISSUE TITLE
java client should ignore null fields by default

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1413]
From https://groups.google.com/forum/#!topic/swagger-swaggersocket/EnEURydhPZA, we may want to disable serializing null values in the JSON.java.

**Comment by fehguy** [comment]
@wing328 i'm inclined to do this, any concerns?

**Comment by wing328** [comment]
@fehguy no concern from me. Ruby, PHP, Python, etc are already behaving this way (skip null value). We missed the implementation for Java templates and will submit a PR to change the behaviour to skip null value. Sorry.

**Comment by fehguy** [comment]
No problem at all!  Thanks for the pr
