### ISSUE TITLE
Improve naming of generated enums in Swift

### ISSUE THREAD

**Issue by tomekc** [swagger-api/swagger-codegen#1420]
I think it would be great, if enum values in generated Swift models would follow convention, i.e.

CapitalizedWordsInSentence

instead of whatever strings are defined in the API.
I would happily try to implement this, if only anyone point me to relevant class :)

**Comment by xhh** [comment]
Hi @tomekc, here in [model.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/model.mustache#L16) you can see that `{{enum}}` is used to generate enum variable names:

```
public enum {{datatypeWithEnum}}: String { {{#allowableValues}}{{#values}}
    case {{enum}} = "{{raw}}"{{/values}}{{/allowableValues}}
}
```

And in [SwiftCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java#L239) here is how `enum` is set:

```java
for (String value : values) {
  Map<String, String> map = new HashMap<String, String>();
  map.put("enum", StringUtils.capitalize(value));
  map.put("raw", value);
  swiftEnums.add(map);
}
```

That is, enum names are capitalized currently. You could submit a PR to change it there. As a reference, you could take a look at PR [1264](https://github.com/swagger-api/swagger-codegen/pull/1264/files) on how enum name is normalized in Java client codegen (search for `toEnumVarName`).

**Comment by tomekc** [comment]
I just submitted PR #1436.

By the way, SwiftCodegen has two-space indents unlike everything else. Maybe reformat it some time?

**Comment by wing328** [comment]
@tomekc thanks for the PR and I agree with you that we should reformat it later.

**Comment by wing328** [comment]
PR merged
