### ISSUE TITLE
Client: Java

### ISSUE THREAD

**Issue by F191919** [swagger-api/swagger-codegen#1421]
If response is UserBean.class which contains for example an AddressBean.class ? How to show in Model Schema?

**Comment by wing328** [comment]
@F191919 it seem to me your question is more on how to describe your Restful service in Swagger (2.0). I would suggest you to post your question [here](https://groups.google.com/forum/#!forum/swagger-swaggersocket)

If your question is related to Swagger Codegen (code generator for API client/server), please elaborate more.

**Comment by fehguy** [comment]
Please reopen with any questions
