### ISSUE TITLE
make parameters unique in generated code

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1422]
There are scenarios where we may have duplicate parameter names in the generated code.  This should be easy to address while keeping the spec and operations as-is.

**Comment by paralin** [comment]
I'm running into this issue with the kubernetes API: https://github.com/kubernetes/kubernetes/issues/16387

Causes this:

```
ConnectOptionsNamespacedPodProxy_6 (string _namespace, string name, string path, string path);
```

Is there any fix?

**Comment by wing328** [comment]
@paralin in the example you provided. do you expect codegen to intelligently rename the second `path` variable to `path2` or something else?

One obvious fix is of course the API owner renames `path` to something else to make the parameter name unique in that operation.

**Comment by paralin** [comment]
@wing328 Unless it's not allowed in Swagger, I'd expect it to work, yes.

I've asked the Kubernetes devs to rename that variable.

**Comment by wing328** [comment]
[DefaultCodegen.java#L1223 ](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L1223) is a good starting point to make parameter unique.

If anyone in the community has cycle to implement the feature/fix, please reply to avoid duplicated efforts.

**Comment by xhh** [comment]
FYI, I'm going to work on this.

**Comment by fehguy** [comment]
That's great, thank you.  I do believe some uniqueness code exists in the swagger-parser for naming models, and yes, the point that @wing328 mentions is probably the right place to do it.

**Comment by wing328** [comment]
@paralin the fix has been merged into master. Please pull the latest master and give it another try.

**Comment by paralin** [comment]
Looks great, thanks
