### ISSUE TITLE
[Swift] Unit testing for Petstore sample (community contribution)

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#1424]
Similar to [ObjC Unit Testing for Petstore](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/objc/SwaggerClientTests), we also need unit testing for Swift to test the Petstore so as to ensure code changes do not break the existing functionality of the Swift API client.

Currently, we're looking for community contribution. If you need help to get started, please let me (@wing328) know. Thanks in advance.

**Comment by c314** [comment]
How to call "loginUser"?

Is it like this?

PetstoreClientAPI. UserAPI.loginUser(username username: txtUsername.text!, password: txtPassword.text!)


public class func loginUser(username username: String?, password: String?) -> RequestBuilder<String>

But the return is " RequestBuilder<String>", it is  not the response from the server.

How can I get the response?

Thank you very much.

**Comment by jaz-ah** [comment]
@wing328 I believe I have a good start in my latest PR for this one.

**Comment by wing328** [comment]
@jaz-ah  :+1: 

I'll close this after PR merges into master.
