### ISSUE TITLE
java client

### ISSUE THREAD

**Issue by F191919** [swagger-api/swagger-codegen#1443]
I'm trying to use Swagger to describe web-api I'm building. The problem is that I can't understand how to describe complex json object?

For example, how to describe this objects:

{
  name: "Jhon",
  address: [
    {
      type: "home",
      line1: "1st street"
    },
    {
       type: "office",
       line1: "2nd street"
    }
  ]
}

**Comment by wing328** [comment]
Are you using https://github.com/domaindrivendev/Swashbuckle ?

**Comment by wing328** [comment]
You can refer to the Pet object in Petstore as an example: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L876
