### ISSUE TITLE
Typescript-angular model parameter names are incorrectly created

### ISSUE THREAD

**Issue by Sweterings** [swagger-api/swagger-codegen#1445]
I have a swagger.json file that is generated from my API, which returns JSON objects with the parameter names in snake_case. In the swagger.json file, these names are correctly displayed as parameter_name, but when I run the generator, the parameters in the models are suddenly in camelCase, being parameterName. This causes my project to stop working, as the objects that are returned from the API calls are always empty, because the values are not correctly filled in.
Is there a setting I have missed to change this, or is this an issue in the project itself? 

The object in question in my swagger.json file: 

    "WeekReponseDTO" : {
        "type" : "object",
        "properties" : {
            "week" : {
                "type" : "integer",
                "format" : "int32"
            },
            "week_days" : {
                "type" : "array",
                "items" : {
                    "$ref" : "#/definitions/DayResponseDTO"
                }
            }
        }
    }

the WeekResponseDTO.ts file that is generated: 

    module API.Client {
        'use strict';
    
        export class WeekReponseDTO {

            week: number;

            weekDays: Array<DayResponseDTO>;
        }

    }

**Comment by wing328** [comment]
@Sweterings it's known issue: https://github.com/swagger-api/swagger-codegen/issues/1341

It would be great if you can help contribute a fix using attribute mapping.

**Comment by wing328** [comment]
@Sweterings if you're familiar with other languages (e.g. python, ruby, php) we can point to the source code on how these languages address the issue using attribute mapping.

**Comment by Sweterings** [comment]
Well, I have a quick and dirty fix right now. I created a new class, made it extend the AbstractTypeScriptClientCodegen class, and overrode the toVarName method. 

    public class TypescriptSnakeCaseConfig extends AbstractTypeScriptClientCodegen {
	
	@Override
	public String getName() {
		return "typescript-angular";
	}

	public String getHelp() {
		return "Generates a TypeScript AngurlarJS client library.";
	}

	public TypescriptSnakeCaseConfig() {
	    super();
	    outputFolder = "generated-code/typescript-angular";
	    modelTemplateFiles.put("model.mustache", ".ts");
	    apiTemplateFiles.put("api.mustache", ".ts");
	    templateDir = "TypeScript-Angular";
	    apiPackage = "API.Client";
	    modelPackage = "API.Client";
	    supportingFiles.add(new SupportingFile("api.d.mustache", apiPackage().replace('.', File.separatorChar), "api.d.ts"));
	}
	
	@Override
	public String toVarName(String name) {
		// replace - with _ e.g. created-at => created_at
		name = name.replaceAll("-", "_");

		// if it's all uppper case, do nothing
		if (name.matches("^[A-Z_]*$"))
			return name;

		// for reserved word or word starting with number, append _
		if (reservedWords.contains(name) || name.matches("^\\d.*"))
			name = escapeReservedWord(name);

		return name;
	}

This works for me right now, but I can understand that this is not a valid longterm solution, for me nor for you. I will try to find a more appropriate solution later. This issue can be closed as far as I'm concerned, although the issue isn't really fixed in the CodeGen project, just on my own project :)

**Comment by wing328** [comment]
@Sweterings yes, that's one way to fix it :)
If later you're working on the fix and you need any help from the community, please let us know.

We'll close this issue and use another for tracking.

**Comment by pixelshaded** [comment]
does  --additional-properties modelPropertyNaming=original have any effect on this?
