### ISSUE TITLE
JAX-RS default definition value 

### ISSUE THREAD

**Issue by SalehAly** [swagger-api/swagger-codegen#1448]
I am trying  to set the default value for  the definitions properties, but its not working when generating JAX-RS, works for integer when i specify the format but tried it for strings and boolean it does not work.. any ideas?
Example JSON:
`

  "definitions": {

     "Permission": {
         "properties": {
             "read": {
                 "type": "boolean",
                 "default": false
           }
        }
     }
  }`
`

Example Generated Models

 ```private Boolean read = null; ```

**Comment by wing328** [comment]
@SalehAly thanks for reporting the issue. Can you help confirm you're using the latest version (2.1.4), which was released 2 days ago?

**Comment by SalehAly** [comment]
@wing328 yes first tried with 2.1.3 didnt work then it i tried 2.1.4 didnt work neither.

**Comment by wing328** [comment]
@SalehAly Ok. I'll take a look.

**Comment by wing328** [comment]
PR (submitted by @xhh) merged, please try again.

**Comment by SalehAly** [comment]
works now :+1:
