### ISSUE TITLE
create JaxRS java files using config options

### ISSUE THREAD

**Issue by iambnz** [swagger-api/swagger-codegen#1449]
Right, now, JaxRS codegen ignores the config options, ie:
* apiPackage
* modelPackage

Reason is stated here: 
https://groups.google.com/forum/#!searchin/swagger-swaggersocket/codegen$20config/swagger-swaggersocket/QevO5BPyflY/syyDzFRHDQAJ

Relevant piece of code, copied from Google group: 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java#L38

> apiPackage = System.getProperty("swagger.codegen.jaxrs.apipackage", "io.swagger.api");
> modelPackage = System.getProperty("swagger.codegen.jaxrs.modelpackage", "io.swagger.model");

**Comment by wing328** [comment]
@iambnz thanks for reporting the issue. We would welcome PR to address the issue.

**Comment by lugaru1234** [comment]
Hi @iambnz I tried to reproduce the bug, but it works fine for me. apiPackage and modelPackage indeed are set to default values in constractor but then config.processOpts() are called in generator and these fields are set to desired values. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L108
I also checked it for v2.1.4 and v2.1.3 tags and it works fine too.
Could you please point the version you were using?

**Comment by wing328** [comment]
@iambnz closing this as there's no update from you.
