### ISSUE TITLE
Security, Consumes, and Produces do not respect global declarations

### ISSUE THREAD

**Issue by brhou** [swagger-api/swagger-codegen#1453]
Generated endpoints ignore the globally declared definitions of Security, Consumes, and Produces even when none are declared on the Operation Object.

The swagger spec appears to say that individual endpoint Operation Objects can override the global definition by declaring empty objects. My spec doesn't include the key for Security, Consumes, or Produces and codegen doesn't look to the global objects for the definition.

Example:

```
consumes:
  - application/json
produces:
  - application/json
security:
  - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
paths:
  /pets:
    get:
      parameters:
         ...
      responses:
         ...
```

The GET pets endpoint should generate the Accept and Content-Type headers with consumes and produces and put `api_key` in `auth_names` because the GET Operation object doesn't override any of those fields but codegen right now treats the fields as if they don't exist or were overridden.

**Comment by wing328** [comment]
@brhou are you using the latest version 2.1.4 ?

**Comment by brhou** [comment]
Yup, it doesn't work on both master and v2.1.4.

**Comment by wing328** [comment]
@brhou I couldn't repeat the issue. I tested with `modules/swagger-codegen/src/test/resources/2_0/petstore.json` by adding `application/pdf` and `application/msword` to top level consumes and produces respectively. Then I removed `produces` in getPetById (since all operations have produces defined) and generated the PHP SDK. I could find `application/pdf` and `application/msword` in the PHP SDK source code.

Do you have full spec you can share with me to reproduce the issue?

**Comment by brhou** [comment]
Ah forgot to mention that this was tested with the Ruby code generation path! Could you see if you could reproduce the behavior I'm seeing with Ruby?

**Comment by wing328** [comment]
Works for me. Here is the (partial) result after adding `application/pdf` in the top level `consumes`:
```
swagger-codegen|master⚡ ⇒ grep -R pdf samples/client/petstore/ruby/*
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb:      _header_content_type = ['applicaiton/pdf']
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb:      _header_content_type = ['applicaiton/pdf']
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb:      _header_content_type = ['applicaiton/pdf']
samples/client/petstore/ruby/lib/petstore/api/pet_api.rb:      _header_content_type = ['applicaiton/pdf']
```

**Comment by brhou** [comment]
I must have been using an old build. Verified that it works for me in master and v2.1.4. Closing this out.
