### ISSUE TITLE
map string-formatted numbers to `number`

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1454]
For client generation, it's often preferable to use strings to avoid precision loss with numbers across programming languages.  To support this, the following string format is introduced:

```json
{
  "type": "string",
  "format": "number"
}
```

The different languages can choose to treat this appropriately, but for Java, we should expect this to be represented as `BigDecimal`.

**Comment by srinirengasamy** [comment]
"amount": {
                    "type": "string",
                    "format": "number",
                    "description": "my amount"
                },
  Results in generating 
  private BigDecimal amount = null;
 @ApiModelProperty(value = "my amount")
  @JsonProperty("amount")
  public BigDecimal getAmount() {
    return amount;
  }
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

However I was expecting String generation like this
    @JsonSerialize(using = ToStringSerializer.class)
      private BigDecimal amount = null;

**Comment by srinirengasamy** [comment]
Pl make sure this is also generated
@JsonSerialize(using = ToStringSerializer.class)
private BigDecimal amount = null;

**Comment by srinirengasamy** [comment]
Once string annotation is added to the generated code pl close the issue. 
Pl merge the pull request

**Comment by cbornet** [comment]
Closed by #1787 ?

**Comment by wing328** [comment]
@cbornet has the annotation been added? I've checked to confirm.

**Comment by wing328** [comment]
@srinirengasamy please try with the latest master and let us know if you still encounter the issue.
