### ISSUE TITLE
TypeScript and Authentication

### ISSUE THREAD

**Issue by aersamkull** [swagger-api/swagger-codegen#1460]
Hi
We use the TypeScript Angular Code Gen and oAuth2 for Authentication. We should therefore be able to set the Authorization header globally. I think this is not currently possible and should be very straightforward to implement.

Any thoughts?

**Comment by aersamkull** [comment]
Similar to https://github.com/swagger-api/swagger-codegen/issues/1345

**Comment by wing328** [comment]
@aersamkull do you have cycle to add that feature (add default header) to TypeScript client? Let me know if you need pointer on where to start.

**Comment by aersamkull** [comment]
I think I should be able to do so, maybe it will take a week, but should be doable.

**Comment by wing328** [comment]
@aersamkull thanks in advance. Please let us know if you need any assistance. Here are the typescript (angular) generator and template:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java

https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/TypeScript-Angular
