### ISSUE TITLE
JAX-RS Definition Acces Modifiers and Keywords

### ISSUE THREAD

**Issue by SalehAly** [swagger-api/swagger-codegen#1467]
Is there any way to change definitions access modifiers and add Keywords such as static and final. If there is no, is there any way to edit the swagger-codegen to achieve this result

Thanks

**Comment by wing328** [comment]
Can you show the current output and the desired output so that we have a better idea what you would like to change?

**Comment by SalehAly** [comment]
"Test": {
"properties"{
 "property": {
          "accessModifier": "public",
           "isStatic": true,
            "isFinal": true,
             "type": "string"
            }  
       }
}
public static final  String property

**Comment by wing328** [comment]
You can customize the generator and template here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java

https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/JavaJaxRS

**Comment by SalehAly** [comment]
But then I have to customize also swagger-models from swagger-core to add the properties correct?

**Comment by wing328** [comment]
We recently added the support of vendor extension swagger-codegen: https://github.com/swagger-api/swagger-codegen/issues/1173

For more information on vendor extension, please refer to https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#vendorExtensions for more information
