### ISSUE TITLE
TypeScript Angular Parameter order

### ISSUE THREAD

**Issue by aersamkull** [swagger-api/swagger-codegen#1488]
In the TypeScript Angular Mustache file, there is the following code:
```TypeScript
static $inject: string[] = ['$http', '$httpParamSerializer'];

        constructor(private $http: ng.IHttpService, basePath?: string, private $httpParamSerializer?: (d: any) => any) {
...
}
```

Shouldn't we switch the last 2 Parameters? In my case, basePath gets set to the httpParamSerializer because of Angular.

**Comment by crissdev** [comment]
@aersamkull :+1: [This example](http://www.typescriptlang.org/Playground#src=class%20TypescriptAngularApi%20%7B%0D%0A%0D%0A%20%20%20%20private%20basePath%20%3D%20'%7B%7BbasePath%7D%7D'%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Constructor%0D%0A%20%20%20%20constructor(private%20%24http%3A%20ng.IHttpService%2C%20basePath%3F%3A%20string%2C%20private%20%24httpParamSerializer%3F%3A%20(d%3A%20any)%20%3D%3E%20any)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(basePath)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.basePath%20%3D%20basePath%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20%0D%0A%20%20%20%20%0D%0A%20%20%20%20%2F%2F%20DI%20Annotation%0D%0A%20%20%20%20static%20%24inject%20%3D%20%5B'%24http'%2C%20'%24httpParamSerializer'%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0Adeclare%20module%20ng%20%7B%0D%0A%20%20%20%20interface%20IHttpService%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A) clearly shows the code generated in that case.
