### ISSUE TITLE
Generating JAVA client. Looks like groupId and packageId is being ignored

### ISSUE THREAD

**Issue by ajainy** [swagger-api/swagger-codegen#1495]
My config-spec looks like this 
```
{
  "modelPackage": "io.snapcx.avs.client.model",
  "apiPackage": "io.snapcx.avs.client.api",
  "groupId": "io.snapcx.avs",
  "artifactId": "client",
  "artifactVersion": "1.0.0"
}
```

For model and api Package, it worked fine. But other client files were generated into io.swagger.client.. instead of io.snapcx.avs.client  

Please advise.

**Comment by fehguy** [comment]
Please add `invokerPackage` for common files which are used by the api classes.

**Comment by ajainy** [comment]
Thanks. Somehow I missed this property from docs.
