### ISSUE TITLE
C# generation missing 'using' statement for Stream

### ISSUE THREAD

**Issue by smwurster** [swagger-api/swagger-codegen#1510]
If my swagger spec contains a property with type `file`, the code generator for C# will declare this as type `Stream`.  Unfortunately, no `using` statement gets added for `System.IO`, which leads to an error when compiling the resulting C# code.

**Comment by wing328** [comment]
Are you using the latest version (2.1.4) or master?

I could find `using System.IO` in the test code.

**Comment by smwurster** [comment]
I believe I'm on master: 2.1.5-SNAPSHOT.

**Comment by smwurster** [comment]
Note: This is for a Model class, not an API.

**Comment by wing328** [comment]
Ah ok. I'll look into this more and file a PR accordingly if it's confirmed to be a bug.

**Comment by smwurster** [comment]
Thanks.

**Comment by wing328** [comment]
I've filed https://github.com/swagger-api/swagger-codegen/pull/1512 to fix the issue.

**Comment by wing328** [comment]
@smwurster PR merged. Please pull the latest and let us know if you still see any issue.

**Comment by smwurster** [comment]
The issue has been fixed.  Thanks!

**Comment by wing328** [comment]
@smwurster np. If you've other feedback on the C# API client, please let us know.

**Comment by smwurster** [comment]
The only other one I'm interested in right now is #955, which I'm watching.

**Comment by wing328** [comment]
@smwurster oh for that one. Please leave a message (e.g. +1) so that we can prioritize accordingly.
