### ISSUE TITLE
Online Generator

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#1513]
In the Generator app, the files are stored in a temporary location on disk and never erased. This can fill disks quickly. Need to delete the files when the operation is complete.

**Comment by fehguy** [comment]
https://github.com/swagger-api/swagger-codegen/commit/cdd20ac4089ebccfb847f5d83d8f46ca9890284f cleans up the messes left behind.  If a library isn't ever fetched, it won't be cleaned up, though.

We can always add a timeout for fetching the files.
