### ISSUE TITLE
Support for Retrofit 2

### ISSUE THREAD

**Issue by emilianobonassi** [swagger-api/swagger-codegen#1522]
Hi!
I'm using this beautiful tool and I'm very satisfied! :+1: 

Have you planned to support Retrofit v2 also if it's still in beta?

IMHO one of the nicest features of this new release of Retrofit is the unification of sync/async at interface level. Every interface method returns a `Call<T>` , you do the sync request invoking `Response<T> execute()` and the async one using `enqueue(Callback<T>)` (see [Call.java](https://github.com/square/retrofit/blob/72c794f5217399f280e006cd1bbaaae1eedcda39/retrofit/src/main/java/retrofit/Call.java)).
It helps a lot in shortening your app's code.

Further info on the [official website](http://square.github.io/retrofit/)

Waiting for your answer!

**Comment by wing328** [comment]
@emilianobonassi thanks for the suggestion. Currently, the Java client generator supports several HTTP library, e.g. Jersey 1.x, Jersey 2.x, Retrofit 1.x, etc.

If you've cycle to add another library (Retrofit 2.x, which is still in beta if I understand correctly) to the Java client generator, I can work with you and show you where to start.

**Comment by emilianobonassi** [comment]
@wing328 , thanks for the offer. I say, why not? Consider me engaged. :+1: 

I thought to start from the retrofit template modifying it and if I need help I will contact you.
Anyway, a condensed bootstrap from you is appreciated.

Let me know if you prefer to continue our talks here or by other means (e-mail/skype/gitter etc).

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/1256/files is a good starting point. I can be reached at email/skype via the email address in my github profile page.

**Comment by emilianobonassi** [comment]
@wing328 , thanks a lot.

**Comment by emilianobonassi** [comment]
@wing328 , let me know your comments. Thanks in advance.
