### ISSUE TITLE
Java Map not generated correctly

### ISSUE THREAD

**Issue by jbadeau** [swagger-api/swagger-codegen#1531]
given a field like:
```json
"test": {
    "type": "object",
    "additionalProperties" : {
        "type" : "string"
        }
    }
```

the resulting java code is:

```java
private String test = new HashMap<String, String>();
```
Any ideas?

**Comment by jbadeau** [comment]
Seems it is fixed with:

			<dependency>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen</artifactId>
				<version>2.1.4</version>
			</dependency>

any chance of a release using the latest swagger-codegen?

**Comment by dantran** [comment]
@jbadeau  just want to confirm you are expecting the generated code should be

private String test = new HashMap<String, String>();
