### ISSUE TITLE
Swagger JavaSpringMVC Server does not use correct annotations for bodyParams

### ISSUE THREAD

**Issue by rostskadat** [swagger-api/swagger-codegen#1532]
Hello,

The file /swagger-codegen/src/main/resources/JavaSpringMVC/bodyParams.mustache is missing the @RequestBody annotation

It should contains:

{{#isBodyParam}}@ApiParam(value = "{{{description}}}" {{#required}},required=true{{/required}} {{#allowableValues}}, allowableValues="{{{allowableValues}}}"{{/allowableValues}}{{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}) @RequestBody {{{dataType}}} {{paramName}}{{/isBodyParam}}

/Julien

**Comment by wing328** [comment]
@rostskadat thanks for the suggestion. Please kindly submit a PR for the change.

Guidelines for contributing: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

`@RequestBody` Annotation Ref: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-requestbody

**Comment by rostskadat** [comment]
Sorry, I'm new to github.

Are you suggesting for me to submit a pull request?

/Julien

**Comment by wing328** [comment]
Yes, that's what I suggested. Here are the high-level steps

1) folk https://github.com/swagger-api/swagger-codegen (there's a folk button in the upper right of the page)
2) git clone https://github.com/rostskadat/swagger-codegen.git
3) cd swagger-codegen
4) git checkout -b springmvc_request_body (this will create a new branch)
4) make changes to the file
5) git commit -a
6) git push origin springmvc_request_body
7) in https://github.com/rostskadat/swagger-codegen, click on the  (green?) button to create a pull request
