### ISSUE TITLE
Angular typescript question: $httpParamSerializer

### ISSUE THREAD

**Issue by markvdkerkhof** [swagger-api/swagger-codegen#1536]
the constructor of the generated api looks like:
constructor(private $http: ng.IHttpService, basePath?: string, private $httpParamSerializer?: (any) => any) {
But I get runtime errors because of the code expects the second parameter is $httpParamSerializer. So now I have to adapt manualy the generated file.

**Comment by crissdev** [comment]
I believe this is a dup of #1488 which was fixed with commit 5580eb7ac3d5448a0b8fd840f36e2e21ecfcbd22

**Comment by wing328** [comment]
@markvdkerkhof closing this as there's no update from you.
