### ISSUE TITLE
Angular typescript: basePath always https

### ISSUE THREAD

**Issue by markvdkerkhof** [swagger-api/swagger-codegen#1538]
the basePath is always set to https: "basePath = 'https://localhost:62300/api';"
is it possible to force that is http,

**Comment by wing328** [comment]
In the petstore example, basePath starts with `http` (not https):
Angular: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-angular/API/Client/PetApi.ts#L9
Node; https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-node/api.ts#L121

Do you have the spec that you can share with us ?

**Comment by wing328** [comment]
@markvdkerkhof closing this as there's no update from you.
