### ISSUE TITLE
Support for Jackson v1.X

### ISSUE THREAD

**Issue by TheIcemanCometh** [swagger-api/swagger-codegen#1539]
We have a legacy app that currently uses v1.X of Jackson that would benefit greatly from being able to select the version of Jackson that is generated from the **swagger-codegen** API.  We'd like to request a command-line parameter with proper support to generate the appropriate code with those classes.

**Comment by wing328** [comment]
Java code generator supports the following HTTP libraries:
```
	library
	    library template (sub-template) to use (Default: <default>)
	        <default> - HTTP client: Jersey client 1.18. JSON processing: Jackson 2.4.2
	        jersey2 - HTTP client: Jersey client 2.6
	        okhttp-gson - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1
	        retrofit - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1 (Retrofit 1.9.0)
```
(`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java` to show the usage)

The default HTTP library for Java supports Jersey client 1.18. Would that meet your requirement?

**Comment by TheIcemanCometh** [comment]
Unfortunately, no, those options won't meet our requirements.  Our legacy app is using 1.9.2/1.9.9 of the Jackson Core and Mapper and the code generated from Swagger CodeGen (SCG) causes issues mixing fasterxml and codehaus.

I did spend some time this morning with one of the APIs we want to generate code from, and manually changed the appropriate imports and statements to use fasterxml after the initial code was generated.  The updated code does work (it was one of our simpler APIs, so I don't know if more would be needed for more complicated situations), but it would be nice if SCG did it for us.

**Comment by TheIcemanCometh** [comment]
I have talked to the powers-that-be and the Gson could possibly be an option for us.

**Comment by fehguy** [comment]
mixing jackson 1.x and 2.0 is supported, per their documentation. http://www.cowtowncoder.com/blog/archives/2012/04/entry_469.html

**Comment by wing328** [comment]
@TheIcemanCometh closing this as there's no further update from you.
