### ISSUE TITLE
Codegen Not Correctly Generating Response Object

### ISSUE THREAD

**Issue by jjkirby** [swagger-api/swagger-codegen#1544]
I am trying to separate (different files) my API definitions from the Response Object so I can get Response Object reuse.  My Response Object schema is a $ref to an http based uri on a different server.
The editor handles the external reference nicely with no errors and displays the correct API documentation.  When I run the codegen (java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -c ./config.json -i catalog.json -l jaxrs -v) I get a warning:

reading from catalog.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}

No other errors/warnings

It looks like the codegen can't reference the schema $ref correctly so it creates this InlineResponse200.java instead of a Container.java for model

My input file (catalog.json) looks like this:

{
    "swagger": "2.0",
    "info": {
        "title": "Catalog API",
        "description": "APIs for Catalogs",
        "version": "1.0.0"
    },
    "basePath": "/cloud",
    "schemes": [
        "https"
    ],
    "paths": {
        "/catalog": {
            "get": {
                "summary": "Catalog Types",
                "description": "Gets All `Catalog` objects.\nRequires both authorization and vCloud tokens\n",
                "produces": [
                    "application/json",
                    "application/xml"
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "description": "Authorization token",
                        "required": true,
                        "in": "header",
                        "type": "string"
                    },
                    {
                        "name": "X-Vcloud-Org",
                        "in": "header",
                        "description": "vCloud token",
                        "required": true,
                        "type": "string"
                    }
                ],
                "tags": [
                    "Catalogs"
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "properties": {
                                "$ref": "http://81371-jk01.viawest.corp/container.json"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    }
}

The contents of   "$ref": "http://81371-jk01.viawest.corp/container.json" is this:

{
  "Container": {
    "type": "object",
    "properties": {
      "description": {
        "type": "string"
      },
      "any": {
        "type": "array"
      },
      "totalRecords": {
        "type": "integer"
      },
      "recordsPerPage": {
        "type": "integer"
      },
      "pageNumber": {
        "type": "integer"
      }
    }
  }
}

What am I doing wrong?

**Comment by wing328** [comment]
@jjkirby I don't think $ref to a URL is supported at the moment. As a workaround. Please define the model in the same file or in a separate file that can be read locally.

**Comment by wing328** [comment]
@jjkirby had another look at your swagger spec. Should the following 
```
"200": {
"description": "Successful response",
"schema": {
"properties": {
"$ref": "http://81371-jk01.viawest.corp/container.json"
}
}
},
```
replaced by the following instead?
```
"200": {
"description": "Successful response",
"schema": {
"$ref": "http://81371-jk01.viawest.corp/container.json"
}
},
```
Note that there's no property.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L238

**Comment by jjkirby** [comment]
Without the properties I get this is the swagger editor:

wagger Error
Data does not match any schemas from 'oneOf'
Jump to line 33
 <>Details
 Object <>
code: "ONE_OF_MISSING" <>
message: "Data does not match any schemas from 'oneOf'" <>
 path: Array [5] <>
0: "paths" <>
1: "/catalog" <>
2: "get" <>
3: "responses" <>
4: "200" <>
 inner: Array [2] <>
 0: Object <>
 1: Object <>
code: "OBJECT_MISSING_REQUIRED_PROPERTY" <>
message: "Missing required property: $ref" <>
 path: Array [5] <>
0: "paths" <>
1: "/catalog" <>
2: "get" <>
3: "responses" <>
4: "200" <>
level: 900 <>
type: "Swagger Error" <>
description: "Data does not match any schemas from 'oneOf'" <>
lineNumber: 33 <>

**Comment by jjkirby** [comment]
I have resolved both ther editor issue AND code gen with external response schema http based files:
I forgot to add the object reference (#/Container)


DOESN'T WORK

"200": {
"description": "Successful response",
"schema": {
"$ref": "http://81371-jk01.viawest.corp/container.json"
}
},


DOES WORK!!
"200": {
"description": "Successful response",
"schema": {
"$ref": "http://81371-jk01.viawest.corp/container.json#/Container"
}
},

**Comment by wing328** [comment]
Glad to hear that you've resolved the issue.
