### ISSUE TITLE
Unable to load RELATIVE ref

### ISSUE THREAD

**Issue by nickcmaynard** [swagger-api/swagger-codegen#1551]
With swagger-codegen 2.1.4, we receive this error when attempting to generate JAX-RS server from a swagger.json:
```
reading from http://localhost:9080/swagger.json
Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ./parameters.json
	at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:85)
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:91)
	at io.swagger.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:38)
	at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:28)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:58)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:38)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:62)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:317)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:186)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:75)
	... 9 more
```

I've seen other issues (#214) where @fehguy states this should be fixed, but we're not seeing this... does anyone have any ideas, please?

**Comment by wing328** [comment]
Here is the error:
`Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ./parameters.json`

Seems like you're using relative path for the definition of `parameters`.

Can you replace ./parameters.json with full URL instead as the parser is expecting the full URL (https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java#L71) ?

**Comment by wing328** [comment]
You can find an example for reference at https://github.com/swagger-api/swagger-codegen/issues/1544#issuecomment-156181857

**Comment by nickcmaynard** [comment]
That's the issue. Sadly, we need to use relative references - this gets deployed on a number of servers with different URLs.

**Comment by nickcmaynard** [comment]
To be clear, we expect this relative style to work, in line with @fehguy's assertion.

**Comment by wing328** [comment]
@nickcmaynard I read #214 twice but didn't see how it's related to this issue (relative URL) that  you reported.

Are you referring to another issue instead?

**Comment by nickcmaynard** [comment]
Definitely a typo. Will try to track down the real issue number. However, this issue should be sufficient. Essentially, @fehguy states "swagger-parser supports relative, so swagger-codegen should too". Clearly, not the case. Hence, raising the issue.

**Comment by nickcmaynard** [comment]
#742 is the issue I'm referring to.

**Comment by wing328** [comment]
I've read #742 and the issue #1193 associated with it. My understanding is that the thread/issue refers to relative "file" path (not URI).

Looking at the [swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#reference-object), [`canonical dereferencing`](http://json-schema.org/latest/json-schema-core.html#anchor27) is supported so in your case swagger parser should look for http://localhost:9080/parameter.json

**Comment by nickcmaynard** [comment]
swagger-codegen is being passed a URI. The URI contains a relative $ref. It throws the error linked in the original report. We expect it to work.

**Comment by nicksloan** [comment]
Until this is fixed, I have worked around it by using swagger-parser (the JavaScript library). Here is a quick node.js script I wrote to help: https://gist.github.com/nicksloan/b4aeb117734c5c1cec81

I simply run that with `$ node consolidate.js > full.json` to serialize my schema to a single JSON file, which I can then build using swagger-codegen. The extra step is a bummer, but not really that much of a problem in the grand scheme of things.

This is tested and working for local file schemas, but not for hosted schema URIs. It's probably worth a try though.

**Comment by nicksloan** [comment]
I'm not sure but I believe that this will be fixed when swagger-codegen depends on the next release of swagger-parser. More information is here: swagger-api/swagger-parser#213.

**Comment by wing328** [comment]
@nickcmaynard @nicksloan do you mind pull the latest master of Swagger Codegen to see if you're still facing the issue? Thanks.

**Comment by nicksloan** [comment]
I'll try to take a look this weekend.

**Comment by wing328** [comment]
@nicksloan may I know if you've a chance to take another look?

**Comment by fehguy** [comment]
This should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4094/commits/92af2cf8211a61291547eee137fdddaf862495e1
