### ISSUE TITLE
swagger-codegen for server using jersey2 with jersey2 annotations

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-codegen#1554]
I am trying to generate my server side code from my swagger file. I have tried the jaxrs language in swagger-codegen, but that uses jersey version 1.  In addition, I tried the java language with the jersey2 library, but that is only for client side.

I am working on adding templates for this, but there might need to be more needed than just template changes. 

Please add jaxrs jersey2 language templates for swagger-codegen.

**Comment by wing328** [comment]
@jeff9finger yes, ideally jaxrs generator should allow one to customize what HTTP library (e.g. Jersey2) to use.

May I know if you've cycle to help implement it for JaxRS generator?

Ref: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by jeff9finger** [comment]
Yes. I can help with this effort.

**Comment by wing328** [comment]
Thanks @jeff9finger 

Here are related-code in Java code generator for supporting multiple libraries:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L100
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L223

Here is the JaxRS generator:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java

JaxRS mustache template: 
https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/JavaJaxRS

These are the starting points I can think of for adding another library (Jersey2) for JaxRS generator. Please let me know if you've any questions.

**Comment by jeff9finger** [comment]
Thanks William.

I will get to this, just kinda swamped right now...


-jeff

**Comment by wizardbyron** [comment]
How about the latest progress?  I believe that generates code with test cases would be better. I'm trying to apply swagger to my project code but it doesn't generates any test code.

**Comment by jeff9finger** [comment]
Due to shift priorities at my company, I have not had a chance to look into this yet.

**Comment by David-Marin-Calleja** [comment]
@wing328 I will try. I've started and I pull as soon as.

**Comment by wing328** [comment]
@David-Marin-Calleja thank you!. Let me know if you need any help from us.

**Comment by David-Marin-Calleja** [comment]
@wing328 I've just made a pull request on github. Pleas could you help me with  test-case file. Any instance where to start.

**Comment by wing328** [comment]
@David-Marin-Calleja thanks for the PR. I've left a comment in the PR.

**Comment by nickjennings** [comment]
@wing328 - I'm new to this thread and swagger in general, but I was wondering what the status of this request is. Does the "feature " label you added mean that solution is now done, or does it mean it is schedule to be done.

**Comment by wing328** [comment]
@nickjennings https://github.com/swagger-api/swagger-codegen/pull/2263 has been submitted by @David-Marin-Calleja for this feature.

If you've time, can you perform some tests with his branch?

**Comment by nickjennings** [comment]
@wing328 - wow! yes I will check out the branch and perform tests, we have an active project that is ideal. Thanks.

**Comment by wing328** [comment]
@nickjennings may I know if @David-Marin-Calleja 's work meet your project requirement?

**Comment by fehguy** [comment]
Fixed in #2488
