### ISSUE TITLE
swagger-codegen for server using inflector with jersey2 annotations

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-codegen#1555]
I would like to use the inflector language of swagger-codegen, but have the code generated using the jaxrs/jersey2 annotations, instead of depending upon the inflector code for the dynamic routing.

There are at least 2 reasons that I want this.
- My company wants to be able to have the annotations in the code so that we are not tied to swagger-inflector.
- My company does not want to depend upon the swagger dynamic routing in production.

Does it fit within the purpose of swagger-inflector to have it create and operate with code that uses the jaxrs/jersey2 annotations (and the swagger annotations)? If so, please consider this a feature request.

The swagger-inflector is very useful for development and design, but my company is hesitant about using it for production.

**Comment by mamghari** [comment]
Hi @jeff9finger,

Could you please tell me more what is "inflector language" ?

Thank you.

**Comment by wing328** [comment]
cc @fehguy as the question is related to Java inflector.

**Comment by fehguy** [comment]
@mamghari The inflector is designed to be used with the library doing the routing.  You can't just take that away.  If you don't want that, the most non-invasive java integration is to use one of the jersey projects.
