### ISSUE TITLE
Cannot generate a definition with name  "File"

### ISSUE THREAD

**Issue by SalehAly** [swagger-api/swagger-codegen#1561]
When I try to generate the model of a custom made File definition, the file model does not get generated. I tried with Java and angular typescript client, it does not work also, not sure if this is intended ?

```
 "File": {
      "properties": {
        "id": {
          "type": "string"
        },
        "created": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
```

**Comment by wing328** [comment]
@SalehAly thanks for reporting the issue. I've filed #1606 to fix the issue in the Java API client.

**Comment by andrewryan1906** [comment]
Hello,

I'm observing this issue with the Typescript client. Is there anything I should be doing?
