### ISSUE TITLE
Error creating custom server generator

### ISSUE THREAD

**Issue by mm-gmbd** [swagger-api/swagger-codegen#1566]
So, I've successfully compiled a new jar, but when I run the following command (as stated in the readme):

    java -cp /path/to/swagger-codegen-distribution:/path/to/your/jar io.swagger.codegen.Codegen

I receive the following error:

    Error: Could not find or load main class io.swagger.codegen.Codegen

Here is the directory structure:

    + swagger-codegen
      + bin
      + modules
        + swagger-codegen
        + swagger-codegen-cli <- Is this the "/path/to/swagger-codegen-distribution"
        + swagger-codegen-maven-plugin
        + swagger-generator
      + output
        +myLibrary <- Current directory
          + src
          + target <- This is where the .jar is located

The readme, as it pertains to this step, could be made a little more clear. First, some of the questions I have:

- Is `/path/to/your/jar` the path **including** the .jar file itself, or just the path to the containing directory?
- What is `/path/to/swagger-codegen-distribution/`? Right now, I believe this is the directory `swagger-codegen/modules/swagger-codegen-cli`, but something more clear would be helpful. Also, is it asking for a path to a directory or to an actual .jar?

Here is the command that I am using (based on my "Current directory" as shown above):

    java -cp ../../modules/swagger-codegen-cli:target/myServerCodegen-swagger-codegen-1.0.0 io.swagger.codegen.Codegen
    Error: Could not find or load man class io.swagger.codegen.Codegen

Thanks in advance.

**Comment by fehguy** [comment]
There are two components.  1) the `swagger-codegen-cli.jar` is the executable jar that provides the codegen foundation, and 2) the custom module.

To run the codegen, you need to execute the executable jar.  To load your custom `myLibrary`, you need the output in your classpath.  Thus:

```
java -cp myLibrary/target/myLibrary.jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar {args}
```

will execute it

**Comment by mm-gmbd** [comment]
Ah, updating the documentation to reflect this would be great! But, I'm not quite all the way there yet.

I switched my current directory to the base of `swagger-codegen`, and ran the following command:

    cp output/myLibrary/target/myLibrary.jar modules/swagger/codegen-cli/target/swagger-codegen-cli.jar -i http://localhost:8080/api.json -l myCustomName -o ./output/myTestFolder
    Error: Could not find or load main class modules.swagger-codegen-cli.target.swagger-codegen-cli.jar

Is there supposed to be a colon between the two .jars after `java -cp`?

**Comment by fehguy** [comment]
i missed something!  sorry about that:

```
java -cp myLibrary/target/myLibrary.jar -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar {args}
```
(needed `-jar`)

**Comment by mm-gmbd** [comment]
Awesome! However, now that it runs, I receive an exception:

    Found unexpected parameters: [-i, http://localhost:8080/api.json, -l myCustomName, -o ./output/myTest]

Ideas? I thought those were the *expected* parameters.

**Comment by fehguy** [comment]
your args are off--take a look here:

https://github.com/swagger-api/swagger-codegen#to-generate-a-sample-client-library

My guess is you're missing `generate` before your options

**Comment by mm-gmbd** [comment]
Yes, that is what I was missing -- thanks! Not sure if this is the right place to continue discussion, but my newest error is:

    java.lang.RuntimeException: Can't load config class with name myLibrary

Although, in the myLibraryCodeGenerator.java file, I have the following defined:

    /**
     * Configures a friendly name for the generator.  This will be used by the generator
     * to select the library with the -l flag.
     *
     * @return the friendly name for the generator
     */
    public String getName() {
      return "myLibrary";
    }

**Comment by fehguy** [comment]
ok first, if you can help update the documentation with a PR (after you're working) that'd be great.

Next, you should see the following file in your `myLibrary/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig`:

```
com.yourPackage.myLibrary
```

If that doesn't match the package in `myLibraryCodeGenerator`, then you'll get that error.  Maybe faster if you jump on http://webchat.freenode.net/?channels=swagger

**Comment by mm-gmbd** [comment]
Yup, those are definitely different, I'll name them the same and get back soon.

And as far as a PR -- of course!

**Comment by fehguy** [comment]
ok great.  the meta generator is supposed to make them consistent so if it didn't, that's a bug.

**Comment by mm-gmbd** [comment]
I may have to leave the actual fix of that one up to you :)

**Comment by fehguy** [comment]
that's fair

**Comment by mm-gmbd** [comment]
Damn... I ran `mvn package` from the root of swagger-codegen - I presume stopping that in progress would be a bad thing?

**Comment by fehguy** [comment]
nah, it won't take long.

**Comment by mm-gmbd** [comment]
Also, as a side note, when running `mvn package` from the root, all of the packages install correctly except for swagger-generator. I don't believe I need it for what I'm doing, but I could file a separate issue for that if that would help.

**Comment by mm-gmbd** [comment]
So the metadata says the package name is the following:

    com.my.company.codegen.MyLibraryCodegenGenerator

So I made the following change in the java:

    /**
     * Configures a friendly name for the generator.  This will be used by the generator
     * to select the library with the -l flag.
     *
     * @return the friendly name for the generator
     */
    public String getName() {
      return "MyLibraryCodegenGenerator";
    }

After running the command to build again, I get the error:

    java.lang.RuntimeException: Can't load config class with name MyLibraryCodegenGenerator

**Comment by mm-gmbd** [comment]
@fehguy, I wrote you a note back on Friday. Did you receive that? Just following up...

**Comment by xhh** [comment]
@mm-gmbd I could make it work with these steps:

In swagger-codegen's top folder:

```shell
mvn clean package

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar meta \
  -o output/myLibrary -n myLibraryCodegen -p com.my.company.codegen

cd output/myLibrary
mvn package

java -cp ../../modules/swagger-codegen-cli/target/swagger-codegen-cli.jar:target/myLibraryCodegen-swagger-codegen-1.0.0.jar \
  io.swagger.codegen.Codegen \
  -i ../../modules/swagger-codegen/src/test/resources/2_0/petstore.json \
  -l myLibraryCodegen \
  -o ./test
```

The output is:

```shell
reading from ../../modules/swagger-codegen/src/test/resources/2_0/petstore.json                                      [3/1924]
writing file ./test/src/io/swagger/client/model/User.sample
writing file ./test/src/io/swagger/client/model/Category.sample
writing file ./test/src/io/swagger/client/model/Pet.sample
writing file ./test/src/io/swagger/client/model/Tag.sample
writing file ./test/src/io/swagger/client/model/Order.sample
[main] WARN io.swagger.codegen.DefaultGenerator - More than 1 security requirements are found, using only the first one
writing file ./test/src/io/swagger/client/api/UserApi.sample
writing file ./test/src/io/swagger/client/api/StoreApi.sample
writing file ./test/src/io/swagger/client/api/PetApi.sample
java.io.FileNotFoundException: myLibraryCodegen/myFile.mustache (No such file or directory)
```

The above exception would be gone after commenting out this section in *src/main/java/com/my/company/codegen/MyLibraryCodegenGenerator.java*:

```java
    supportingFiles.add(new SupportingFile("myFile.mustache",   // the input template or file
      "",                                                       // the destination folder, relative `outputFolder`
      "myFile.sample")                                          // the output file
    );
```

Note that I used the command from *output/myLibrary/README.md* which runs the `main` method of `io.swagger.codegen.Codegen`.

I tried this method as well;

```shell
java -cp output/myLibrary/target/myLibraryCodegen-swagger-codegen-1.0.0.jar \
  -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar \
  generate \
  -i modules/swagger-codegen/src/test/resources/2_0/petstore.json \
  -l myLibraryCodegen \
  -o ./my-library
```

but got an exception:

```shell
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name myLibraryCodegen Available: android
async-scala
csharp
dart
flash
java
...
```

It seems that somehow the *io.swagger.codegen.CodegenConfig* file from *output/myLibrary* is not loaded.

**Comment by wing328** [comment]
@mm-gmbd closing this as there's no update from you. Please reopen if needed.

**Comment by mm-gmbd** [comment]
@wing328, apologies for not getting to this sooner. I have moved on with a different tool, so I haven't had much time to look back just yet. I have *not* gotten the issue resolved, and the suggestion @xhh provided unfortunately does not work either.

**Comment by Nepoxx** [comment]
I'm having the exact same issue, but I don't know how to resolve it. The command works perfectly on linux, but on my coworker's windows box, I have the same error as @mm-gmbd 

`java -cp target\myCodeGenFile.jar:swagger-codegen-cli-2.1.5.jar io.swagger.codegen.SwaggerCodegen generate -l sarbakanCodeGen -i http://127.0.0.1:2100/api-docs -o generated` results in `Error: Could not find or load main class io.swagger.codegen.Codegen`

`java -cp target\myCodeGenFile.jar -jar swagger-codegen-cli-2.1.5.jar io.swagger.codegen.SwaggerCodegen generate -l sarbakanCodeGen -i http://127.0.0.1:2100/api-docs -o generated` results in `Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [io.swagger.codegen.SwaggerCodegen, generate, -l,`
