### ISSUE TITLE
Generated android client api multiple requests at the same time?

### ISSUE THREAD

**Issue by m4574** [swagger-api/swagger-codegen#1567]
Does generated android client api supports sending multiple http requests at the same time?
I got:
W/SingleClientConnManager﹕ Invalid use of SingleClientConnManager: connection still allocated. Make sure to release the connection before allocating another one.

From above log message. I realized that it sends only 1 request at the time. 
Since ApiInvoker class is singleton and it has only 1 instance of DefaultHttpClient object, which is actually deprecated. 

Can I somehow adapt client api library to the concurrent environment?

Let me know if you need more information about it.

Please advise!
Regards,
Yuriy

**Comment by wing328** [comment]
For Android client, I believe you're referring to the `android` template. Our plan is to sunset the Android template as it can be replaced by the Java client.

In the Java client, here are the options for selecting an HTTP library:
```
	library
	    library template (sub-template) to use (Default: <default>)
	        <default> - HTTP client: Jersey client 1.18. JSON processing: Jackson 2.4.2
	        jersey2 - HTTP client: Jersey client 2.6
	        okhttp-gson - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1
	        retrofit - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1 (Retrofit 1.9.0)
	        retrofit2 - HTTP client: OkHttp 2.5.0. JSON processing: Gson 2.4 (Retrofit 2.0.0-beta2)

```
(Usage: `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java`)

You can choose the HTTP library that would meet your requirement.

**Comment by wing328** [comment]
@m4574 closing this issue as there's no update. Please open a new one if the above didn't help.

**Comment by farmazon3000** [comment]
Using ```retrofit2``` is not working at the moment:  #1850.

**Comment by wing328** [comment]
To all, just an update regarding the `android` client. We'll keep `android` as there're HTTP libraries that can run on Android only (e.g. android-volley, which has been added to `android`).

If you've any questions, please reply to let us know.

**Comment by JimVanG** [comment]
Is it possible Retrofit with Jackson, instead of GSON?

**Comment by wing328** [comment]
@JimVanG  Don't think we offer that at the moment. We welcome contribution to add that: `retrofit-jackson`

If you've cycle to implement that, please let us know and we'll show you a couple good starting points.
