### ISSUE TITLE
Access parent vars

### ISSUE THREAD

**Issue by yonaskolb** [swagger-api/swagger-codegen#1568]
It would be useful to have access to a parent's vars.
This is for when `supportsInheritance` is set to true in DefaultCodegen

This would allow subclasses to references a super classes properties for doing stuff like the following

``` swift
class Parent{
    var parentVar:String
    var parentVar2:Bool

    init(parentVar:String, parentVar2:Bool){
        self.parentVar = parentVar
        self.parentVar2 = parentVar2
    }
}

class Child:Parent {
    var childVar:String

    //is accessing the parents properties
    init(childVar:String, parentVar:String, parentVar:Bool) {
        self.childVar = childVar
        super.init(parentVar: parentVar, parentVar: parentVar2)
    }
}
```

A parents variables could perhaps be references like this {{#parent}}{{#vars}} ... {{/vars}}{{/parent}}

Without this it's not possible to build the example above which is what I'm trying to achieve in a Swift target

**Comment by wing328** [comment]
@yonaskolb thanks for offering help to contribute to the Swift API client. For model inheritance, you may want to join the discussion at https://github.com/swagger-api/swagger-spec/issues/403.

For your request to access the parent's properties using `{{#parent}}{{#vars}} ... {{/vars}}{{/parent}}` that you proposed, I think I understand what you meant as I've run into similar issue before when trying to add better support of model inheritance. Last time I checked, it's not easy. I'll take another look later to see if it can now be done without too much effort/time.

**Comment by cbornet** [comment]
I think it's already possible with ```{{#parentModel}}{{#allVars}}```
