### ISSUE TITLE
Jersey 2.6 creating MIMEXXX.tmp files for every client call

### ISSUE THREAD

**Issue by CrossfireCurt** [swagger-api/swagger-codegen#1576]
We are using a Swagger client built with Jersey2 to make thousands of calls a day in our production environment and Jersey is creating 0 byte temp files in the /tmp directory every time a call happens. This eventually blows out the inode limit on the machine.

Documented here: https://java.net/jira/browse/JERSEY-2515
Looks like this was addressed in Jersey 2.12. As a work around I'm going to try excluding the org.glassfish.jersey.media:jersey-media-multipart:2.6 package when i include my client and replacing it with 2.12.

**Comment by CrossfireCurt** [comment]
I have confirmed that excluding the dependency and forcing media-multipart 2.12 works just fine as a temporary work around for us until Swagger upgrades to a newer jersey version:
```
compile("com.company:service-client:1.0"){
    exclude module: "jersey-media-multipart"
}
compile("org.glassfish.jersey.media:jersey-media-multipart:2.12")
```

**Comment by wing328** [comment]
@CrossfireCurt thanks for reporting the issue. Do you mind filing a PR to update the Jersey version at https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache#L165 ?

Ref: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by CrossfireCurt** [comment]
@wing328 sure thing!
