### ISSUE TITLE
swift codegen: Alamofire validate() not called

### ISSUE THREAD

**Issue by tigaris** [swagger-api/swagger-codegen#1592]
In **AlamofireImplementations.swift**, in the AlamofireRequestBuilder`<T>` class, in the processRequest method: because the function **validate()** is not called on the Alamofire Request object before **responseJSON**, any server side errors (like HTTP 500) drop through and are treated as successful.

This behavior results in a crash/exception as any JSON object returned by an HTTP 500 will not **decode** to the expected swagger object.

**Comment by wing328** [comment]
@tigaris sorry for late reply on this. May I know if you've cycle to submit a fix? A good starting point is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/AlamofireImplementations.mustache

Contributing guidelines: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by jaredegan** [comment]
This is fixed in the current implementation.

**Comment by jaredegan** [comment]
@tigaris would you like to confirm & close this issue?

**Comment by wing328** [comment]
Closing this. Please open a new issue for tracking if you still encounter the issue.
