### ISSUE TITLE
Autogenerate operation IDs if none 

### ISSUE THREAD

**Issue by diogeneshamilton** [swagger-api/swagger-codegen#1593]
on the python-flask server generator, it outputs null method names, which can be confusing.

**Comment by diogeneshamilton** [comment]
@fehguy let me know if you need more details.

**Comment by wing328** [comment]
@diogeneshamilton can you share the swagger spec for reproducing the issue (null method names)?

**Comment by diogeneshamilton** [comment]
https://swaggerhub.com/api/diogeneshamilton/Venmo/1.0

**Comment by wing328** [comment]
@diogeneshamilton the Swagger spec does not contain `operationId`, which explains why null method names are generated.

Ref: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-5

Can you set a proper `operationId` and try again?

**Comment by diogeneshamilton** [comment]
@wing328 I was told by @fehguy to submit an issue, because in the client codegen it will generate an operation ID if there is none. 

I understand that setting an operation ID will fix the issue, I am hoping that someone can build an improvement (myself included) which will help future people avoid my confusing experience.

**Comment by fehguy** [comment]
yes @diogeneshamilton is right--we should be auto-generating the operation IDs and putting them back in the swagger.

**Comment by xhh** [comment]
Auto-generate `operationId` has been implemented before, but the python-flask server generator overrides the behavior.
I just submitted #1614 for a fix.
