### ISSUE TITLE
Handling empty types in the definitions (for the java generator)

### ISSUE THREAD

**Issue by mattsheppard** [swagger-api/swagger-codegen#1594]
I have a swagger schema being produced by http://springfox.github.io/springfox/ which contains 'empty' types in the definition list like the following...

```
{
   "swagger":"2.0",
   "host":"example.com",
   "basePath":"/api",
   "paths":{
      "/example":{
         "get":{
            "responses":{
               "200":{
                  "description":"OK",
                  "schema":{
                     "$ref":"#/definitions/TriggerActions"
                  }
               }
            }
         }
      }
   },
   "definitions":{
      "TriggerActions":{
         "properties":{
            "actions":{
               "type":"array",
               "items":{
                  "$ref":"#/definitions/Action"
               }
            },
            "trigger":{
               "$ref":"#/definitions/Trigger"
            }
         }
      },
      "Action":{
      },
      "Trigger":{
      }
   }
}
```

When faced with this, the java code generator produces a TriggerActions class with references to Trigger and Action, but no Trigger or Action classes. That results in something along the lines of...

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swagger-java-client: Compilation failure: Compilation failure:
[ERROR] /opt/swagger-codegen/modules/swagger-codegen-cli/min_output/src/main/java/io/swagger/client/model/TriggerActions.java:[4,30] error: cannot find symbol
[ERROR] package io.swagger.client.model
[ERROR] /opt/swagger-codegen/modules/swagger-codegen-cli/min_output/src/main/java/io/swagger/client/model/TriggerActions.java:[5,30] error: cannot find symbol
[ERROR] package io.swagger.client.model
[ERROR] /opt/swagger-codegen/modules/swagger-codegen-cli/min_output/src/main/java/io/swagger/client/model/TriggerActions.java:[25,15] error: cannot find symbol
[ERROR] class TriggerActions
[ERROR] /opt/swagger-codegen/modules/swagger-codegen-cli/min_output/src/main/java/io/swagger/client/model/TriggerActions.java:[27,10] error: cannot find symbol
[ERROR] class TriggerActions
[ERROR] /opt/swagger-codegen/modules/swagger-codegen-cli/min_output/src/main/java/io/swagger/client/model/TriggerActions.java:[34,14] error: cannot find symbol
[ERROR] class TriggerActions
[ERROR] /opt/swagger-codegen/modules/swagger-codegen-cli/min_output/src/main/java/io/swagger/client/model/TriggerActions.java:[46,9] error: cannot find symbol
[ERROR] -> [Help 1]
```
...when trying to build the generated code.

To give some insight into the generating side - Trigger and Action are interfaces, with no get/set methods (since implementations will have different requirements there), so I can see why SpringFox generates this output (especially since it has no way to know what implementations exist).

I guess the ideal solution from my perspective would be for the codegen to create Trigger/Action interfaces (or empty classes I guess), such that someone using the client library could subsequently build subclasses to match the implementations available on the server side.

**Comment by webron** [comment]
Even those are interfaces, that's probably not the output you should be getting from SpringFox. The minimum it should provide for those is `"type": "object"`. Not saying that the codegen shouldn't be able to deal with empty models, but the meaning of it is not easy to define in many languages (it's not necessarily an object).

**Comment by mattsheppard** [comment]
(Yeah, I'm about to post an issue for them over there as well)
