### ISSUE TITLE
SimpleDateFormat problem for Java with Android

### ISSUE THREAD

**Issue by huiyiqun** [swagger-api/swagger-codegen#1595]
It's imported here:

https://github.com/swagger-api/swagger-codegen/commit/c59be88a3ef129acece69999086690166ba5f9ab#diff-3714cb3e3c7bbb1ce24de92a3fb9f01bR60

This has broken my android app with following runtime exception:
```
Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
...
```

According to [here](http://developer.android.com/reference/java/text/SimpleDateFormat.html), X is not valid pattern character 'X' for android java runtime.

Please fix this if possible. @xhh

**Comment by wing328** [comment]
There's a pending PR (https://github.com/swagger-api/swagger-codegen/pull/1579) to fix the issue.

Can you help test it to see if it resolves the issue for you on your Android app?

**Comment by xhh** [comment]
@huiyiqun please have a look at [my comment here](https://github.com/swagger-api/swagger-codegen/issues/1573#issuecomment-157325236). Is your Android app using the `okhttp-gson` template of Java codegen?
