### ISSUE TITLE
How to use Swagger APIs in swift?

### ISSUE THREAD

**Issue by c314** [swagger-api/swagger-codegen#1598]
Any one can provide any examples or any links of its tutorials?
Thanks in advance.

**Comment by jaz-ah** [comment]
@c314 I've just added a test program in this PR: https://github.com/swagger-api/swagger-codegen/pull/1991  -- take a look, that should help show how to use swift+promisekit to use the api's.

**Comment by wing328** [comment]
FYI. Here are the unit tests for Swift Petstore: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/swift/SwaggerClientTests
