### ISSUE TITLE
Java codegen upload image MediaType error

### ISSUE THREAD

**Issue by wangzilong** [swagger-api/swagger-codegen#1599]
My upload photo Resource code:
```java
  @POST
  @Path("/{id}/photo")
  @Consumes(MediaType.MULTIPART_FORM_DATA)
  @ApiOperation(value = "Update user info ", notes = "More notes about this method")
  public Result setPhoto(@PathParam("id") final String id,
                         @FormDataParam("photo") InputStream inputStream,
                         @FormDataParam("photo") @ApiParam(access = "internal") FormDataBodyPart formDataBodyPart,
                         @FormDataParam("photo") FormDataContentDisposition fileDetail) {
    ...
  }
```
Swagger spec 
```json
"post": {
        "tags": [
            "user"
        ],
        "summary": "Update user info ",
        "description": "More notes about this method",
        "operationId": "setPhoto",
        "consumes": [
            "multipart/form-data"
        ],
        "produces": [
            "application/json"
        ],
        "parameters": [
            {
                "name": "id",
                "in": "path",
                "description": "me or userId",
                "required": true,
                "type": "string",
                "default": "me"
            },
            {
                "name": "photo",
                "in": "formData",
                "required": false,
                "type": "file"
            }
        ],
        "responses": {
            ...
        }
    },
```

java codegen generate API:
UserApi.java
```java
public Result setPhoto (String id, File photo) throws ApiException {
    ...
    String path = "/user/{id}/photo".replaceAll("\\{format\\}","json") .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(id.toString()));
   ...
    if (photo != null)
      formParams.put("photo", photo);
    final String[] accepts = {
      "application/json"
    };
    final String accept = apiClient.selectHeaderAccept(accepts);
    final String[] contentTypes = {
      "multipart/form-data"
    };
    final String contentType = apiClient.selectHeaderContentType(contentTypes);
    String[] authNames = new String[] {  };
    TypeRef returnType = new TypeRef<Result>() {};
    return apiClient.invokeAPI(path, "POST", queryParams, postBody, postBinaryBody, headerParams, formParams, accept, contentType, authNames, returnType);
  }
```

Upload file code
```java
new UserApi.setPhoto("me", new File("src/test/resources/image/boy.jpg"));
```

When I debug in backend
formDataBodyPart.getMediaType() will return **multipart/form-data** instead of **image/jpg**.

does anyone have any ideas, please?

**Comment by wing328** [comment]
@wangzilong the `consumes` in the spec is defined as `multipart/form-data` so I'm not surprised if you get the result you mentioned above. Given that it's `multipart`, did you check each part to see if it contains data with type `image/jpg`? 

Please also consider using `tcpdump` or similar tools to capture the packet at the low level for troubleshooting.

**Comment by wangzilong** [comment]
I use wireshark to capture the packet, which is not like I think.
![image](https://cloud.githubusercontent.com/assets/4329939/11335212/636bb09e-91d2-11e5-9b25-a28498b225aa.png)

**Comment by wangzilong** [comment]
If I use the swagger-ui to upload the same image, this is the snapshot:
![image](https://cloud.githubusercontent.com/assets/4329939/11335315/2e9fe014-91d3-11e5-8bae-54ed3a3d3263.png)

**Comment by xhh** [comment]
@wangzilong The `okhttp-gson` template of Java client codegen has the implementation of guessing MIME type (Content-Type) for file part (boundary), see here:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java#L929

comparing with the default Java client codegen:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java#L929

Could you give the `okhttp-gson` template a try (via `{"library": "okhttp-gson"}` in config file) and see if it works for you? If so, we can implement it in the default Java client codegen then.

**Comment by wangzilong** [comment]
Thank you for your response!
Upload file works very well.

**Comment by wangzilong** [comment]
But we get float data in json instead of Long.

My Object is:
```
public class User   {
  @SerializedName("id")
  private String id = null;
  @SerializedName("dateCreated")
  private Date dateCreated = null;
  @SerializedName("lastUpdated")
  private Date lastUpdated = null;
...
``` 


When I call API in swagger-ui  , return json is :
```
{
    "id": "agdkZXZ-YXBwchELEgRVc2VyGICAgICAgMAKDA",
    "dateCreated": 1448274392494,
    "lastUpdated": 1448274392494,
...

```

But now 
return json is :
```
{
id=agdkZXZ-YXBwchELEgRVc2VyGICAgICAgMAKDA, 
dateCreated=1.448274392494E12, 
lastUpdated=1.448274392494E12
```

Why dateCreated & lastUpdated return Float ?

**Comment by wangzilong** [comment]
When debug into your code, I find that after run this code, Long data => Float.
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java#L60

This is my debug screenshot
![image](https://cloud.githubusercontent.com/assets/4329939/11343420/e1a18a5c-9203-11e5-9ae4-6fae30d04657.png)

**Comment by xhh** [comment]
@wangzilong It seems to be expected with Gson: http://stackoverflow.com/q/11586299/243797

The real issue here is that, since `dateCreated` and `lastUpdated` are of type `Date`, it is expected in JSON that they are string like `"2015-11-24T10:18:03.429+08:00"`.
If you want to support `long` value in JSON for `Date` type, could you create a new issue for it and then we can discuss it there?

**Comment by wangzilong** [comment]
OK
Thanks for you response!
