### ISSUE TITLE
Why all APIs return requestBuilder in SWIFT?

### ISSUE THREAD

**Issue by c314** [swagger-api/swagger-codegen#1607]
In all APIs, return requestBuilder 

```
return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)

return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)

```
How to use the requestBuilder after calling these APIs?

I guess it should be with Alamofirelmplementations.swift.

Thank you very much for any comment.

**Comment by mojjy** [comment]
you could do something like this
   reqBuilder.execute { (response, error) -> Void in
            if (error == nil) {
                //todo show some message
                controller.loadData()
            } 
        }
