### ISSUE TITLE
How to disable the appending of Using<Method> to method names?

### ISSUE THREAD

**Issue by rkaltreider** [swagger-api/swagger-codegen#1608]
I would like to disable the appending of Using<GET, POST...> to each of the methods in the generated API classes.  I have taken the time to add nicknames to my methods and would like them to appear that way without the additional appended text.

**Comment by wing328** [comment]
Are you using version 2.1.4 (stable release) or the latest master?

Please provide a swagger spec to illustrate the issue.

**Comment by rkaltreider** [comment]
2.1.4 currently

Sent from my iPhone

On Nov 24, 2015, at 2:57 AM, wing328 <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using version 2.1.4 (stable release) or the latest master?

Please provide a swagger spec to illustrate the issue.

-

**Comment by wing328** [comment]
Which `language` did you use?

**Comment by rkaltreider** [comment]
I looked at java, but have a feeling it is android too.


________________________________

**Comment by wing328** [comment]
I couldn't find "Using" (case-insensitive) in java/android Petstore samples.

**Comment by rkaltreider** [comment]
ok, i will look into springfox to see if its adding that to the nicknames


________________________________

**Comment by rkaltreider** [comment]
sorry about the mixup....it looks like springfox is adding these.  i scanned through the produced swagger doc....it will open a ticket with them...sorry again [☹]


________________________________

**Comment by wing328** [comment]
No worry. We'll close the issue for now. Please open a new one if you need help from us (community)
