### ISSUE TITLE
Java - generate simple smoke tests

### ISSUE THREAD

**Issue by giovannibotta** [swagger-api/swagger-codegen#161]
I was wondering if it was possible to add an additional mustache file to be used per API to create a very simple test class. It's easy to create the mustache file, not so easy add a custom code generation step it seems. Suggestions?

**Comment by jimschubert** [comment]
Support for api and model tests was added in fb1cc254e420999218929e972a824fda35e37108. Should be a matter of creating the mustache files now.

**Comment by wing328** [comment]
@giovannibotta please refer to this PR: https://github.com/swagger-api/swagger-codegen/pull/1980/files on how to add unit test files for a particular language.

I think so far we've done it for C#, PHP and Ruby.

Given that you're working on the Java unit test, I would suggest you to take a look at the C# unit test mustache template as C# and Java are quite similar.

If you've any questions, please let us know.

**Comment by wing328** [comment]
and thanks @jimschubert for bringing this up as I've completely forgotten about this feature request.

**Comment by wing328** [comment]
@giovannibotta may I know if you've cycle to contribute the auto-generated test files for Java? If yes, let us know if you need any help.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by giovannibotta** [comment]
I am not currently working with Swagger or java, so I won't be contributing to this. Sorry about that!

**Comment by wing328** [comment]
That's ok. We'll leverage the community to add the smoke test for Java API client.

**Comment by wing328** [comment]
UPDATE: The Java API client comes with auto-generated test cases.
