### ISSUE TITLE
Java generater --config {"library": "okhttp-gson"}, the Long data convert to Float.

### ISSUE THREAD

**Issue by wangzilong** [swagger-api/swagger-codegen#1615]
create a config.json file 
```json
{"library": "okhttp-gson"}
```
I use this command to generate java code:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -c config.json -i http://i-digi-sign.appspot.com/rest/swagger.json  -l java -o samples/client/iDigiSign-codegen/java
```

When I use the new code to test, I get another exception .

My Object is:
```java
public class User   {
  @SerializedName("id")
  private String id = null;
  @SerializedName("dateCreated")
  private Date dateCreated = null;
  @SerializedName("lastUpdated")
  private Date lastUpdated = null;
...
``` 

When I call API in swagger-ui  , return json is :
```json
{
    "id": "agdkZXZ-YXBwchELEgRVc2VyGICAgICAgMAKDA",
    "dateCreated": 1448274392494,
    "lastUpdated": 1448274392494,
...

```

But when I use the new code that generated with the advice @xhh   
return json is :
```
{
id=agdkZXZ-YXBwchELEgRVc2VyGICAgICAgMAKDA, 
dateCreated=1.448274392494E12, 
lastUpdated=1.448274392494E12
```

Why dateCreated & lastUpdated return Float ?

And when I convert json to User.class throw exception
```java
com.google.gson.JsonSyntaxException: 1.448274392494E12
	at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:81)
	at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:66)
	at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:41)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
	at com.google.gson.Gson.fromJson(Gson.java:805)
	at com.google.gson.Gson.fromJson(Gson.java:770)
	at com.google.gson.Gson.fromJson(Gson.java:719)
	at com.google.gson.Gson.fromJson(Gson.java:691)
```

**Comment by wangzilong** [comment]
@xhh please help me.

**Comment by wangzilong** [comment]
When debug into your code, I find that after run this code, Long data => Float.
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/JSON.java#L60

This is my debug screenshot
![image](https://cloud.githubusercontent.com/assets/4329939/11343420/e1a18a5c-9203-11e5-9ae4-6fae30d04657.png)

**Comment by cbornet** [comment]
The bug is not in the codegen.
The swagger spec from http://i-digi-sign.appspot.com/rest/swagger.json is incorrect : dateCreated is indicated as ```{"type":"string","format":"date-time"}``` whereas it sends you an integer.

**Comment by wangzilong** [comment]
how does it happen?  
How do I deal with this issue?

**Comment by wangzilong** [comment]
My project use Jersey 1.19
When system return a User Object, user.dateCreated will be convert to Long type
I think that it is good format, but I do not know why it become to Float type

**Comment by cbornet** [comment]
The problem is in the server. If you are writting the server code then you have several possibilities :
* configure your Json library (Jackson ?) to serialize dates as string. In Jackson this is setting the property WRITE_DATES_AS_TIMESTAMPS to false.
* annotate the dateCreated with ApiModelProperty(dataType="integer") so that the swagger.json says it is an integer (then an Integer will be generated client-side).
* modify the type of dateCreated in the server to Integer or Long.

**Comment by wangzilong** [comment]
Thanks for your advice.
I will to try it asap and then feedback to you.

**Comment by wangzilong** [comment]
I have add config in Jackson 
```java
 objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
```

and add swagger annotation
```
...
@ApiModelProperty(dataType="long")
  protected Date dateCreated;
  @ApiModelProperty(dataType="long")
  protected Date lastUpdated;
...
```

Swagger-spec
```
 "User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "dateCreated": {
                    "type": "integer",
                    "format": "int64"
                },
                "lastUpdated": {
                    "type": "integer",
                    "format": "int64"
                }
...
```

It does not work, API still return Float
```
dateCreated=1.448633488945E12, lastUpdated=1.448633488945E12
```

**Comment by cbornet** [comment]
No it was an "or" between the possibilities I enumerated. 
Either you want your API to send dates as timestamps (which are long values. Eg. 1448274392494) or as ISO formatted strings (eg. "2015-11-27T17:38:00Z").
With the annotations you are now saying : "my fields are long" but with  objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS), you send strings.

**Comment by wangzilong** [comment]
Anyway, I am using this code to test my APIs.
If generate client code without --config {"library": "okhttp-gson"}, there is no this problem.
If you do not think it is an issue, you can close this issue
