### ISSUE TITLE
[java] Honor Enum's value 

### ISSUE THREAD

**Issue by dantran** [swagger-api/swagger-codegen#1620]
Spec

        "status" : {
          "type" : "string",
          "enum" : [ "OK", "Canceled", "Failed", "OK_with_errors" ]
        },

swagger-codegen produces this

    public enum StatusEnum {
        OK("OK"),
        CANCELED("Canceled"),
        FAILED("Failed"),
        OK_WITH_ERRORS("OK_with_errors");

       private String value;

       StatusEnum(String value) {
           this.value = value;
       }

      @Override
       public String toString() {
           return value;
      }
    }

However, the generated code does not have @JsonValue at toString() method and therefor Jaskson use enum name ( instead to enum value ) during marshalling

Please fix this with 

    @Override
    @JsonValue //added
    public String toString() {
        return value;
    }

**Comment by dantran** [comment]
Since this is a quick fix, please have it at 2.1.5 milestone :-)

**Comment by xhh** [comment]
Hi @dantran, I tried it and there's no issue with the current code.
You can see that [these options are enabled for enum properties](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java#L20):

```java
mapper.enable(SerializationFeature.WRITE_ENUMS_USING_TO_STRING);
mapper.enable(DeserializationFeature.READ_ENUMS_USING_TO_STRING);
```

As for your PR #1621, I tested `@JsonValue` and it seemed to work too without the need of setting the above options.

**Comment by dantran** [comment]
@xhh  thanks for reviewing my PR.  Currently we only consume the generated POJO part ( not the client) and have our own client with Jackson as our marshaller

Without the proposed change, Jackson at client side marshall my enum as enum name ( not value), and the server rejected as bad request since it expect the value instead

I guest I can configure jackson mapper as suggested before, but it is must better if we can take advantage of annotation. And we dont have to document our external client to do that as well
