### ISSUE TITLE
' instead of " in build.gradle for java retrofit 2 generation

### ISSUE THREAD

**Issue by bmarty** [swagger-api/swagger-codegen#1626]
Hello,
When building a library for java with retrofit2, the generated file *build.gradle* contains the following lines:

```
dependencies {
    compile "com.squareup.okhttp:okhttp:$okhttp_version"
    compile "com.squareup.retrofit:retrofit:$retrofit_version"
    compile 'com.google.code.gson:gson:$gson_version'
    compile 'com.squareup.retrofit:converter-gson:$retrofit_version'
    compile "io.swagger:swagger-annotations:$swagger_annotations_version"
    compile "org.apache.oltu.oauth2:org.apache.oltu.oauth2.client:$oltu_version"
    testCompile "junit:junit:$junit_version"
}
```

Problem: for *gson* and *retrofit*, the **'** char is used instead of **"**, so gradle cannot interpret the **$** variables, and the library is not able to be compiled.

BR

**Comment by wing328** [comment]
I've submitted #1629 to update the gradle file. Please take a look.
