### ISSUE TITLE
unable to delete file in io.swagger.generator.online.OnlineGeneratorOptionsTest

### ISSUE THREAD

**Issue by tmalbonph** [swagger-api/swagger-codegen#1632]
generateOptionsTest(io.swagger.generator.online.OnlineGeneratorOptionsTest)  Time elapsed: 0.031 sec  <<< FAILURE!
java.io.IOException: Unable to delete file: C:\Users\ghello\AppData\Local\Temp\codegen-7269898903786282662-tmp\typescrip
t-node-client\api.ts
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2192)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1585)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1467)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2183)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1585)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1467)
        at io.swagger.generator.online.OnlineGeneratorOptionsTest.generateOptionsTest(OnlineGeneratorOptionsTest.java:11
2)

Results :

Failed tests:
io.swagger.generator.online.OnlineGeneratorOptionsTest.generateOptionsTest(io.swagger.generator.online.OnlineGeneratorOp
tionsTest)
  Run 1: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 2: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 3: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 4: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 5: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 6: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 7: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 8: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 9: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 10: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 11: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 12: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 13: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 14: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 15: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 16: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 17: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 18: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 19: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 20: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 21: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 22: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 23: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 24: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 25: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 26: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 27: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 28: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 29: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 30: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...
  Run 31: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...

Tests run: 34, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ........................... SUCCESS [1.232s]
[INFO] swagger-codegen (core library) .................... SUCCESS [44.491s]
[INFO] swagger-codegen (executable) ...................... SUCCESS [9.859s]
[INFO] swagger-codegen (maven-plugin) .................... SUCCESS [7.473s]
[INFO] swagger-generator ................................. FAILURE [49.702s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

This happen on  Windows PowerShell(Administrator) on Win7 after mvn package

mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 23:22:22+0800)

Java version: 1.7.0_71, vendor: Oracle Corporation
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

**Comment by wing328** [comment]
@tmalbonph I've filed #1633 to add better exception handling but still the temporary directory cannot be deleted for some unknown reasons.

**Comment by tmalbonph** [comment]
@wing328 thanks. It only happen on Win7. It run better on Ubuntu 14.04 (3.13.0-32-generic) running
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 23:22:22+0800)
Java version: 1.7.0_51, vendor: Oracle Corporation

**Comment by wing328** [comment]
@tmalbonph if you pull the latest, the build should succeed. Please give it another try.

**Comment by tmalbonph** [comment]
Error is still the same
  Run 31: OnlineGeneratorOptionsTest.generateOptionsTest:112 ╗ IO Unable to delete file:...


Tests run: 34, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ........................... SUCCESS [1.232s]
[INFO] swagger-codegen (core library) .................... SUCCESS [20.155s]
[INFO] swagger-codegen (executable) ...................... SUCCESS [9.906s]
[INFO] swagger-codegen (maven-plugin) .................... SUCCESS [7.410s]
[INFO] swagger-generator ................................. FAILURE [49.733s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:29.123s
[INFO] Finished at: Mon Nov 30 13:06:45 CST 2015
[INFO] Final Memory: 33M/94M

git log -3
commit 1913b0594f2ddcf56feecac41fbb3e470db11e37
Merge: 6685bad dfc0813
Author: wing328 <wing328hk@gmail.com>
Date:   Mon Nov 30 00:09:25 2015 +0800

    Merge pull request #1628 from wing328/csharp_optional_parameter

    [C#] add optional parameter to c# API client

commit 6685bad8de4f2f6de56720e2b2e1ad1a39e95d57
Merge: 2d34f56 a41ca72
Author: wing328 <wing328hk@gmail.com>
Date:   Sun Nov 29 23:32:37 2015 +0800

    Merge pull request #1629 from wing328/fix_gradle_var

    [Java][Retrofit2] update retrofit2 gradle to use double quote

commit a41ca7278a2504749f8e51664c60fd838458e0e4
Author: wing328 <wing328hk@gmail.com>
Date:   Sat Nov 28 16:01:59 2015 +0800

    update retrofit2 gradle to use double quote

**Comment by wing328** [comment]
My apologies. I just merged the fix into master. Please give it another try.

**Comment by tmalbonph** [comment]
# before the pull
git log -1
commit 2d34f567ffb12610026e03831ef03733fb46b68b
Merge: a9fdb8f 41936ab
Author: wing328 <wing328hk@gmail.com>
Date:   Sun Nov 29 00:54:03 2015 +0800

    Merge pull request #1619 from EduGraph/issue-1075
    
    [PHP] Slim Framework v3 - Server Generator #1075

# get your updates
git pull
remote: Counting objects: 131, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 131 (delta 53), reused 34 (delta 34), pack-reused 27
Receiving objects: 100% (131/131), 21.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (53/53), completed with 34 local objects.
From https://github.com/swagger-api/swagger-codegen
   2d34f56..d7460da  master     -> origin/master
Updating 2d34f56..d7460da
Fast-forward
 modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConstants.java  |   2 ++
 .../src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java         |  12 ++++++++
 .../src/main/resources/Java/libraries/retrofit2/build.gradle.mustache           |   4 +--
 modules/swagger-codegen/src/main/resources/csharp/api.mustache                  |  18 ++++++------
 .../src/test/java/io/swagger/codegen/csharp/CSharpClientOptionsTest.java        |   2 ++
 .../src/test/java/io/swagger/codegen/options/CSharpClientOptionsProvider.java   |   1 +
 .../src/test/java/io/swagger/generator/online/OnlineGeneratorOptionsTest.java   |   7 ++++-
 .../Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs                  |  56 ++++++++++++++++++-------------------
 .../Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/StoreApi.cs                |   8 +++---
 .../Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/UserApi.cs                 |  40 +++++++++++++-------------
 samples/client/petstore/csharp/SwaggerClientTest/SwaggerClientTest.userprefs    |   2 +-
 samples/client/petstore/csharp/SwaggerClientTest/TestPet.cs                     |   8 +++++-
 .../client/petstore/csharp/SwaggerClientTest/bin/Debug/SwaggerClientTest.dll    | Bin 67584 -> 68096 bytes
 .../petstore/csharp/SwaggerClientTest/bin/Debug/SwaggerClientTest.dll.mdb       | Bin 21137 -> 21165 bytes
 .../client/petstore/csharp/SwaggerClientTest/obj/Debug/SwaggerClientTest.dll    | Bin 67584 -> 68096 bytes
 .../petstore/csharp/SwaggerClientTest/obj/Debug/SwaggerClientTest.dll.mdb       | Bin 21137 -> 21165 bytes
 samples/client/petstore/java/retrofit2/build.gradle                             |   4 +--
 .../petstore/java/retrofit2/src/main/java/io/swagger/client/StringUtil.java     |   2 +-
 18 files changed, 97 insertions(+), 69 deletions(-)

# updated swagger-codegen
git log -3
commit d7460dac3270e6deba31d1645b6891c66a52b25c
Merge: 1913b05 90c9352
Author: wing328 <wing328hk@gmail.com>
Date:   Mon Nov 30 13:24:13 2015 +0800

    Merge pull request #1633 from wing328/fix_window_test_case
    
    Add exception handling in the test case (for Windows)

commit 90c93522b3454b653d356ea564015d6d3c1290b5
Author: wing328 <wing328hk@gmail.com>
Date:   Mon Nov 30 10:59:51 2015 +0800

    undo ios sample change

commit 96003a1e90afb43e6c730427ac19b34688783a7c
Author: wing328 <wing328hk@gmail.com>
Date:   Mon Nov 30 10:53:31 2015 +0800

    fix typo

# rebuild now successful
mvn clean
mvn package
...
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ........................... SUCCESS [1.264s]
[INFO] swagger-codegen (core library) .................... SUCCESS [20.108s]
[INFO] swagger-codegen (executable) ...................... SUCCESS [9.891s]
[INFO] swagger-codegen (maven-plugin) .................... SUCCESS [5.428s]
[INFO] swagger-generator ................................. SUCCESS [10.031s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.299s
[INFO] Finished at: Mon Nov 30 14:15:26 CST 2015
[INFO] Final Memory: 34M/84M

@wing328 Thank your for the fast fix

**Comment by wing328** [comment]
@tmalbonph thanks for the confirmation.

**Comment by tmalbonph** [comment]
@wing328 You did fix the compilation error.
For windows user, maybe the documentation for swagger-generator should mention about directories created at (drive):/Users/[username]/AppData/Local/Temp/codegen-xxxx-temp directories will eventually accumulate because org.apache.commons.io.FileUtils.deleteDirectory(dir) failed to delete the temporary directories created by swagger-generator/src/test/java/io/swagger/generator/online/OnlineGeneratorOptionsTest.java. This does not happen on Ubuntu 14.04

**Comment by wing328** [comment]
Yes, we'll document that as a known issue at the moment. I'd spent some time look into it but couldn't figure out why the directory deletion failed.
