### ISSUE TITLE
[Swift] Code error in RequestBuilder Extension

### ISSUE THREAD

**Issue by Greensource** [swagger-api/swagger-codegen#1636]
Hi,
when I try to compile Swift generated source I've got some errors.
In file Extensions.swift, line 69 :
let deferred = Promise<Response<T>>.defer()
-> Consecutive statements on a line must be separated by ';'

**Comment by wing328** [comment]
I got the same error

<img width="898" alt="screen shot 2015-12-25 at 4 52 01 pm" src="https://cloud.githubusercontent.com/assets/934260/12001710/31da14e2-ab29-11e5-8696-ee0b0338e3fd.png">

and I'm using Swift 2.1.1
```
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
```

@Edubits when you've time, I wonder if you can take a look.

**Comment by wing328** [comment]
For the error with `defer()`, I was able to fix it by renaming it to `pendingPromise()`. Ref: https://github.com/mxcl/PromiseKit#promisekit-3

There's only one error remaining:

<img width="891" alt="screen shot 2015-12-25 at 6 05 19 pm" src="https://cloud.githubusercontent.com/assets/934260/12002117/1a4b8f64-ab32-11e5-839f-7e293ea7e65a.png">

**Comment by wing328** [comment]
UPDATE. I'm able to resolve the error by renaming "NSError" in that line to "ErrorType" and the build is now OK.

I'll submit a PR later to update the Swift template.

**Comment by Edubits** [comment]
Sorry for not responding earlier, glad you were able to fix it @wing328!
