### ISSUE TITLE
codegen does not support parameters from swagger 2.0

### ISSUE THREAD

**Issue by gaalandr** [swagger-api/swagger-codegen#1637]
Swagger-codegen does not support the following properties from swagger spec 2.0:
``` 
maximum, exclusiveMaximum, minimum, exclusiveMinimum, maxLength,
minLength, pattern, maxItems, miIems, uniqueItems, multipleOf
```  
There is a fix in this pull request:
https://github.com/swagger-api/swagger-codegen/pull/1458

Please verify and merge.
Thanks,
Andras

**Comment by wing328** [comment]
@gaalandr thanks for the PR. I'll review and let you know if I've any questions.

**Comment by wing328** [comment]
PR merged.
