### ISSUE TITLE
[Swift] AlamoFire and Promise Kit not up to date

### ISSUE THREAD

**Issue by Greensource** [swagger-api/swagger-codegen#1638]
Hi,
When I try to build my app after a pod install, I had some issue with PromiseKit (2.2.1). So I force version to 3.0.0.

**Comment by wing328** [comment]
I ran into the issue with PromiseKit 2.2.1 as well and upgrading to 3.0.0 resolves those errors. Here is the error for tracking purpose:

<img width="266" alt="screen shot 2015-12-25 at 5 16 17 pm" src="https://cloud.githubusercontent.com/assets/934260/12001791/6647cca4-ab2b-11e5-8aba-bd09c32b944b.png">

I will submit a PR later to update PromiseKit to the latest version (3.0.0), which was released in Oct 2015.
