### ISSUE TITLE
Generated Jersey2 client doesn't work when uploading two files in one call 

### ISSUE THREAD

**Issue by chenjianjx** [swagger-api/swagger-codegen#1650]
Swagger-codegen version:  2.1.5-SNAPSHOT 
Generated Jersey client version:    using parameter "library":"jersey2" when generating.

### Problem
1. My web service has a method allowing the client to pass 2 files at a time.  
  *. The method also takes some other string-typed parameters. 
  *. My service is also written in Jsersey2 
  *. All the parameters in the service are annotated with @FormDataParam("paramName")

2. When I use the generated Jersey client to upload 2 files, on the server side,
  *. The 2 file parameters(InputStream) and their detail parameters (FormDataContentDisposition) are good
  *. Other string-typed parameters' values are all null  

3. I modified the generated client according to Jersey2's sample code. And it worked. 

### The code generated by swagger codegen
````
  MultiPart multipart = new MultiPart();
  for (Entry<String, Object> param: formParams.entrySet()) {
    if (param.getValue() instanceof File) {
      File file = (File) param.getValue();

      FormDataMultiPart mp = new FormDataMultiPart();
      mp.bodyPart(new FormDataBodyPart(param.getKey(), file.getName()));
      multipart.bodyPart(mp, MediaType.MULTIPART_FORM_DATA_TYPE);

      multipart.bodyPart(new FileDataBodyPart(param.getKey(), file, MediaType.APPLICATION_OCTET_STREAM_TYPE));
    } else {
      FormDataMultiPart mp = new FormDataMultiPart();
      mp.bodyPart(new FormDataBodyPart(param.getKey(), parameterToString(param.getValue())));
      multipart.bodyPart(mp, MediaType.MULTIPART_FORM_DATA_TYPE);
    }
  }
  formEntity = Entity.entity(multipart, MediaType.MULTIPART_FORM_DATA_TYPE);
````

### My Code
````
		MultiPart multiPart = new MultiPart();

		for (Entry<String, Object> param : formParams.entrySet()) {
			if (param.getValue() instanceof File) {
				File file = (File) param.getValue();
				FormDataBodyPart onePart = new FormDataBodyPart(
						FormDataContentDisposition.name(param.getKey())
								.fileName(file.getName()).size(file.length())
								.build(), file,
						MediaType.APPLICATION_OCTET_STREAM_TYPE);
				multiPart.bodyPart(onePart);
			} else {

				FormDataBodyPart onePart = new FormDataBodyPart(
						FormDataContentDisposition.name(param.getKey())
								.fileName(param.getKey()).build(), param
								.getValue().toString());
				multiPart.bodyPart(onePart);
			}
		}
		Entity<MultiPart> formEntity = Entity.entity(multiPart,
				MediaType.MULTIPART_FORM_DATA_TYPE);
````

My code is similar with Jersey2's [official sample](https://github.com/jersey/jersey/blob/master/examples/multipart-webapp/src/test/java/org/glassfish/jersey/examples/multipart/webapp/MultiPartWebAppTest.java)

Would anybody please look into it?

**Comment by xhh** [comment]
I can reproduce the issue, working on a PR for it.

**Comment by wing328** [comment]
@chenjianjx PR merged. Please let us know if you still encounter the issue.

Thanks again for reporting the issue.

**Comment by chenjianjx** [comment]
Thank you

**Comment by chenjianjx** [comment]
I tested without your new code, and it worked.  Thank you!
