### ISSUE TITLE
[Obj-C] Form properties of type "boolean" fail with swagger-tools

### ISSUE THREAD

**Issue by samuelg** [swagger-api/swagger-codegen#1668]
We have a boolean form property defined as follows:

``` json
{
    "name": "prop",
    "in": "formData",
    "description": "",
    "required": true,
    "type": "boolean"
}
```

The Objective-C generated client sends this as 0/1. However, swagger-tools middleware validates boolean values as true/false only. How can we use swagger-codegen and swagger-tools together without running into this issue?

**Comment by samuelg** [comment]
See https://github.com/apigee-127/swagger-tools/blob/master/lib/validators.js#L498 for the validation in swagger-tools middleware.

**Comment by wing328** [comment]
Thanks for reporting the issue. Boolean is mapped to NSNumber at the moment. Changing it to BOOL may probably fix it.

Do you have cycle to contribute the fix?

Here is the starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java#L76

Contribution guidelines: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
@samuelg I proposed a fix via https://github.com/swagger-api/swagger-codegen/issues/4491. Please take a look.

Closing this one as using https://github.com/swagger-api/swagger-codegen/issues/4491 for tracking.
