### ISSUE TITLE
Push docker images to Docker Hub

### ISSUE THREAD

**Issue by yewton** [swagger-api/swagger-codegen#1681]
Hi,

It's very useful if the docker images are available on Docker Hub.

We would be able to just `docker pull` and run generation like `docker run --rm -v "$PWD"/spec:/spec -v "$PWD"/gen:/gen -v "$PWD"/templates:/templates swagger-api/swagger-codegen:v2.1.4 generate -l nodejs -i /spec/swagger.yml -o /gen -t /templates/nodejs`.
I just forked and tested above example and it worked well.

Please try to consider it.

Thanks.

**Comment by wing328** [comment]
@yewton I think that's a good suggestion :)

**Comment by ChrisPearce** [comment]
+1

**Comment by fehguy** [comment]
see here https://hub.docker.com/u/swaggerapi/

**Comment by yewton** [comment]
Thank you :smile:
