### ISSUE TITLE
Syntax issue when generating Javascript client operation without parameters 

### ISSUE THREAD

**Issue by thibaultclem** [swagger-api/swagger-codegen#1691]
When generating Client JS for an operation without parameters, an unnecessary comma is added before the callback parameter:
```
self.logoutUser = function(, callback) {
```
You can see the error directly on the generating UserApi.js:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/scripts/rest/api/UserApi.js#L233

I provided a PR: https://github.com/swagger-api/swagger-codegen/pull/1690

PS: @jfiala thanks for this useful JS generator ;)

**Comment by wing328** [comment]
@thibaultclem thanks for reporting the issue and the PR, which has been merged into master.
