### ISSUE TITLE
[Javascript] Add unit testing for Petstore Javascript API client

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#1692]
Similar to API clients in other programming languages, we want to have a way to unit test the Petstore client.

Currently, the Petstore Javascript API client does not have unit testing.

If anyone would like to contribute, please reply to let us know.

**Comment by wizardbyron** [comment]
I saw a merged PR. Is this closed or still open ?

**Comment by wing328** [comment]
That PR added some test cases. If you would like to add more, I'm sure the community would welcome that.

Do you have any test cases in mind you would like to add ?

**Comment by wing328** [comment]
Closing it for now as there're already some test cases added via #1735
