### ISSUE TITLE
If I generate models only, I will be missing a class called io.swagger.client.StringUtil

### ISSUE THREAD

**Issue by chenjianjx** [swagger-api/swagger-codegen#1701]
## How to reproduce:

```` shell
java -jar -Dmodels  modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate   -i http://localhost:8080/xxx/swagger.json -l java  -o /somedir  -c  /some.json
````
the some.json is 

````json
{"artifactId":"xxx","artifactVersion":"1.0-SNAPSHOT","groupId":"xxx","library":"jersey2","modelPackage":"xxx.model"}
````

## The problem:

The generated model files will be depending on "io.swagger.client.StringUtil" in their toString() methods, which is not generated .

## Suggestion
We don't need very beautiful output for toString() methods.  I think you can just remove the dependency for StringUtil.

**Comment by wing328** [comment]
Thanks for reporting the issue. I think we will resolve it by including StringUtil as some developers may prefer developer-friendly output (pretty print).

**Comment by chenjianjx** [comment]
You can "inline" StringUtil, which means generating pretty-printing toString() methods for every model.

**Comment by fehguy** [comment]
I do agree that it would be nice to avoid having this external class in the models
