### ISSUE TITLE
CSharp Clients Do Not Format query parameter date-time As Per Swagger Spec

### ISSUE THREAD

**Issue by mirthy** [swagger-api/swagger-codegen#1705]
The CSharp Client serializes the date-time parameters incorrectly.  The format chosen is not ISO 8601 / RFC3339 compatible.

The Universal Sortable ("u") Format Specifier was used instead of the Round-trip ("O", "o") Format Specifier for converting parameters. [Microsoft Documentation on the Round-trip format specifier ("o"). ](https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8)

Currently: 2008-04-10 13:30:00Z  (note the missing T separator)
Should be: 2008-04-10T13:30:00.0000000

See:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L159

This bug completely breaks any service which strictly enforces RFC3339 formatting. 

There is a bit of deserializing code that's parsing it correctly using that same Round Trip format but it's unrelated here: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L212

**Comment by wing328** [comment]
PR merged into master
