### ISSUE TITLE
[python] generator uses keywords

### ISSUE THREAD

**Issue by seanfarley** [swagger-api/swagger-codegen#1711]
In our api, we use the word 'self' as a property. It seems the swagger code generator doesn't check for keywords thereby producing unusable code.

**Comment by wing328** [comment]
@seanfarley thanks for reporting the issue. Do you mind contributing the fix?

It can be as easy as updating the reserved word list: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java#L61

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by seanfarley** [comment]
Sure, I can take a stab at it.

**Comment by wing328** [comment]
@seanfarley do you need help submitting a fix? or you would like us to fix the issue with a PR?

**Comment by seanfarley** [comment]
Oops, sorry. I have this fixed locally but got distracted with the holidays. I was trying to add some more pythonic stuff but that might be delayed.

**Comment by wing328** [comment]
@seanfarley np :)

Do you mind elaborating on the "pythonic stuff" a bit more?

**Comment by wing328** [comment]
#1808 merged into master.
