### ISSUE TITLE
[Javascript] generate the JS Api Client

### ISSUE THREAD

**Issue by thibaultclem** [swagger-api/swagger-codegen#1715]
When generating the JS client, the generated API call a not generated module apiClient:

```
apiClient.invokeAPI(path, "PUT", queryParams, postBody, postBinaryBody, headerParams, formParams, accept, contentType, authNames, null);
```

See PetApi for instance https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/scripts/rest/api/PetApi.js#L55

**Comment by xhh** [comment]
There are similar issues referring to `apiClient.escapeString` and `apiClient. parameterToString`, see [here](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/scripts/rest/api/PetApi.js#L274) and [here](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/scripts/rest/api/PetApi.js#L419).

**Comment by wing328** [comment]
PR merged. Closing this issue.
