### ISSUE TITLE
Enable codegen templates access tags descriptions

### ISSUE THREAD

**Issue by splintor** [swagger-api/swagger-codegen#1719]
Codegen templates can access the tags of each operation, but I need to be able to provide description about the tag (which is defined in the tag list at the yaml top-level), and it seems the list of declared tags and their descriptions are not available from the mustache template.

**Comment by wing328** [comment]
Is this the same as https://github.com/swagger-api/swagger-codegen/issues/1073 ?

**Comment by splintor** [comment]
Yes, indeed. I missed it.

**Comment by wing328** [comment]
@splintor it's ok. From your perspective, is that something your urgently need?

**Comment by splintor** [comment]
Indeed!
I'm building a JS CLI, and would like the list the tags and their descriptions. Currently, it seems I'll have to resort to hard-coding the description, but I really don't like it.

**Comment by wing328** [comment]
Please leave a reply e.g. +1 in #1073  so that we can prioritize accordingly.
