### ISSUE TITLE
[Javascript] Issues with constructFromObject in models

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-codegen#1721]
Taking the [Pet.js](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/scripts/rest/model/Pet.js#L78) as an example:

```js
  	self.constructFromObject = function(data) {
	  	
	  	self.id = data.id;
	  	
	  	self.category.constructFromObject(data.category);
	  	
	  	self.name = data.name;
	  	
	  	self.photoUrls = new Array();
	  	
	  	self.tags = new Array();
	  	
	  	self.status = data.status;
	  	
	}
```

1. array fields like `photoUrls` and `tags` are not assigned with values from `data`
2. there would be an error when `data` in `undefined`, for example, the `category` field might be missing in the above `data`, then `self.category.constructFromObject(data.category);` would throw error: "Cannot read property 'id' of undefined"

**Comment by petoknm** [comment]
I don't think that the first point was addressed!
"1. array fields like photoUrls and tags are not assigned with values from data"

**Comment by xhh** [comment]
@petoknm you're right, I'll try fixing it soon.
