### ISSUE TITLE
[python] doc string has empty lines

### ISSUE THREAD

**Issue by seanfarley** [swagger-api/swagger-codegen#1727]
When there is a empty string, it seems the mustache template will still generate an empty line here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api.mustache#L53

You can see this on the following swagger file: https://api.bitbucket.org/swagger.json

**Comment by fehguy** [comment]
This can be fixed by changing to this:

```
{{#notes}}{{{notes}}}{{/notes}}
```

Would you mind sending a PR?

**Comment by seanfarley** [comment]
I should have mentioned that I already tried that :-) Something else seems wrong with the variable. Perhaps empty and not null fools jmustache?

**Comment by fehguy** [comment]
Ahh different then :)  OK it is entirely possible that it's an empty string, which is different from null.  If you run codegen with `-DdebugOperations`, can you see if the field exists?  If so, then it's an empty string.

**Comment by seanfarley** [comment]
That option doesn't seem to change any of the output.

**Comment by fehguy** [comment]
Hi, it won't change the output, but it'll help us debug it.  You should get a giant JSON object printed on your screen.

**Comment by seanfarley** [comment]
Yes, that's what I mean.

```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/Downloads/swagger.json -l python -o ../swagger-bb-test -DdebugOperations &> debug.out
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/Downloads/swagger.json -l python -o ../swagger-bb-test &> non-debug.out
$ diff -u non-debug.out debug.out
$ echo $?
0
```

**Comment by wing328** [comment]
It should be `debugOperations=true`, e.g.
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l csharp \
  -D debugOperations=true
```
Ref: https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables

**Comment by wing328** [comment]
Closing this as there's no further update.
