### ISSUE TITLE
[Java] need to be able to set timeout

### ISSUE THREAD

**Issue by benmccann** [swagger-api/swagger-codegen#1730]
There's currently no way to set a connection or read timeout. I'm talking to a server that occasionally never connects or never sends a response and my program then just hangs. The default Java client builds a `com.sun.jersey.api.client.Client`, but doesn't let you get to it to change underlying properties like timeout and doesn't seem to expose timeout itself.

**Comment by wing328** [comment]
Agree that there should be a way to set time out. Currently, the PHP API client allows developers to change the time out: https://github.com/swagger-api/swagger-codegen/blob/cf947811df72b690c3b8bb46ddeb55c420045367/samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php#L371

We'll do the same for other languages.

**Comment by xhh** [comment]
@benmccann the `okhttp-gson` client supports accessing to the `OkHttpClient`, I also submitted a PR #1755 to add a helper method to set the connect timeout. Maybe you want to give it a try.

**Comment by wing328** [comment]
PR merged. Closing this issue.

**Comment by benmccann** [comment]
I was using the Jersey client, but it was the OkHttpClient that was fixed. Can you reopen this issue for the Jersey client? Thanks!

**Comment by wing328** [comment]
@benmccann  #1853 fixed the default (jersey) and jersey2 client. Please pull the latest master.

**Comment by mb1069** [comment]
Hi, is this fixed for the JS client export? If so how can I set a timeout on a call?

**Comment by wing328** [comment]
@mb1069 this has nothing to do with JS API client.

For JS API client, you can set timeout in ApiClient and here are some code related to setting timeout:
```
samples/client/petstore/javascript/src/ApiClient.js:     * The default HTTP timeout for all API calls.
samples/client/petstore/javascript/src/ApiClient.js:    this.timeout = 60000;
samples/client/petstore/javascript/src/ApiClient.js:    // set request timeout
samples/client/petstore/javascript/src/ApiClient.js:    request.timeout(this.timeout);
``` 
If you need further help, please open a new issue for tracking.

**Comment by normana400** [comment]
This looks like it only allows you to set the connectTimeout, but not the readTimeout (as the original poster requested). In addition to that you should also be able to set the writeTimeout as well.

all three of those values are set to 10 seconds by default and there are many scenarios that you'd want a larger setting for one of those values.

**Comment by normana400** [comment]
I created a ticket for the delta requirement:
https://github.com/swagger-api/swagger-codegen/issues/6852

**Comment by bnlcnd** [comment]
this seems resolved. But, is there any documentatio saying that what system property or config parameter we should use to specify the connect / read / write timeout in milli second?
