### ISSUE TITLE
Add Eclipse folder '.settings' to Git ignore list.

### ISSUE THREAD

**Issue by garydgregory** [swagger-api/swagger-codegen#1743]
Please add the Eclipse folder '.settings' to Git's ignore list in the root for the project. It would be great to do this for all Swagger projects.

**Comment by fehguy** [comment]
I do see it in this project:

https://github.com/swagger-api/swagger-codegen/blob/master/.gitignore#L61

Is this not working correctly?  A PR would ensure it's working correctly.

**Comment by garydgregory** [comment]
Attaching is a patch for the whole project...

[swagger-codegen.diff.txt](https://github.com/swagger-api/swagger-codegen/files/69129/swagger-codegen.diff.txt)
