### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by nikhilbansal01** [swagger-api/swagger-codegen#1760]
Failed to execute goal on project swagger-codegen: Could not resolve dependencies for project io.swagger:swagger-codegen:jar:2.1.5-SNAPSHOT: Failure to find io.swagger:swagger-core:jar:1.5.5-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]

I am running on branch master with most latest changes. (commit 3e5f23dc7a42b75fb5f8cd3446672e11d1bae405)

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: C:\Program Files\apache-maven-3.3.9\bin\..
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_80\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"

**Comment by wing328** [comment]
@nikhilbansal01 please pull the latest master as we've just updated the pom to use the latest version of swagger core and parser.
