### ISSUE TITLE
Unused imports in Java client

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-codegen#1764]
The generated Java for an existing Swagger file contains to much unused imports.

For example, generating a simple Enumeration:
My Swagger enum is:
```
"definitions": {
"MediumStatus": {
     "type": "string",
     "enum": [
          "CLOSED",
          "OPEN_AVAILABLE",
          "OPEN_NOT_AVAILABLE",
          "NOT_AVAILABLE"
      ]
    }
}
```

The generated client is :
```
package io.swagger.client.model;
import io.swagger.client.StringUtil;
import java.util.Objects;
import io.swagger.annotations.;
import com.fasterxml.jackson.annotation.;

public enum MediumStatus {
     CLOSED, OPEN_AVAILABLE, OPEN_NOT_AVAILABLE, NOT_AVAILABLE
}
```

And there we can see that there is imports. To define a classic enum like that, there is normally no import at all necessary !

**Comment by fehguy** [comment]
Yes thank you, we will do some house cleaning before the next release
