### ISSUE TITLE
swagger-core version wasn't updated?

### ISSUE THREAD

**Issue by Mumutu** [swagger-api/swagger-codegen#1773]
swagger-codegen- 2.1.5-SNAPSHOT's pom show the version of swagger-code is still 1.5.5  while it needs the `BinaryProperty` .. so the error occurs 

```
[ERROR] Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.1.5-SNAPSHOT:generate (default) on project xplat-swagger-codegen: 
Execution default of goal io.swagger:swagger-codegen-maven-plugin:2.1.5-SNAPSHOT:generate failed: 
A required class was missing while executing io.swagger:swagger-codegen-maven-plugin:2.1.5-SNAPSHOT:generate: io/swagger/models/properties/BinaryProperty
```

**Comment by wing328** [comment]
@Mumutu did you pull the latest master and do a `mvn clean install -U` ?

**Comment by Mumutu** [comment]
@wing328 Thanks I followed what you said and no error occurs any more. 
Maybe some jar updated unexpectedly since I didn't change anything in local.
