### ISSUE TITLE
akka-scala implemention NPE on spec with no securityDefinitions property

### ISSUE THREAD

**Issue by andylowry** [swagger-api/swagger-codegen#1781]
Seen in release 2.1.4, and in latest commit on master branch: 564f6e2bb5ff22bdf08672c103c5a14dffdef60a

In the `fromSecurity` method override in `AkkaScalaClientCodegen`, the iterator that looks for an OAuth security definition fails with NPE if the spec contains no `securityDefinitions` property.

The superclass method explicitly returns null in this case, and that null value is used by the akka-scala module, leading to the NPE.

To reproduce this, remove (not just empty out) the `securityDefinitions` property in petstore (and remove all `security` properties, where the removed definitions are referenced).

Possible fixes include:

1. Check for null in `AkkaScalaClientCodegen#fromSecurity`
2. Return an empty list in `DefaultCodegen#fromSecurity` instead of null

Latter seems preferable to me, since an empty list should have the same meaning as omitting the `securityDefinitions` property, and it would prevent others from falling into the same trap in the future.

**Comment by wing328** [comment]
@andylowry thanks for the detailed issue report. We'll look into this and get back to you.

**Comment by wing328** [comment]
FYI. @andylowry 's PR has been merged into master.

I also reviewed other codegen and confirmed no other codegen overrides `fromSecurity`, which means only Akka-Scala codegen had the issue.
