### ISSUE TITLE
PHP language module fails on windows

### ISSUE THREAD

**Issue by andylowry** [swagger-api/swagger-codegen#1782]
Seen in release 2.1.4 

In `PhpClientCodegen#toPackagePath`, the following expression fails on Windows, where `File.separator` is a single backslash:

    packageName.replaceAll("[\\.\\\\/]", File.separator)

The problem is that the replacement string in `String#replaceAll` is not treated as a bare string. Replacements from matching regex groups are processed, and backslashes are used to escape characters that would otherwise indicate replacements. They must themselves be escaped.

To reproduce: attempt to use the php codegen module on petstore.json on Windows.

**Comment by wing328** [comment]
@andylowry thanks for the reporting the issue. I tested the latest master with `.\bin\windows\php-petstore.bat` but didn't see any issue.

Please pull the latest master and try again.

**Comment by andylowry** [comment]
Sorry, I was mistaken in thinking I had reproduced it in latest master. I see the bug fix now to quote the replacement string.

**Comment by wing328** [comment]
@andylowry np :)
