### ISSUE TITLE
[C#] Inherited classes must come before implemented interfaces in the class definition

### ISSUE THREAD

**Issue by T-Boss** [swagger-api/swagger-codegen#1799]
In the model template, it currently specifies ````public class {{classname}} : IEquatable<{{classname}}>{{#parent}}, {{{parent}}}{{/parent}}````. This isn't an issue if the class doesn't inherit from anything, so you end up with _public class classname : IEquatable<classname>_. But when you inherit from a class, you end up with _public class classname : IEquatable<classname>, ParentClass_, which throws a .NET compiler error when compiling the DLL because the parent class must come before the interface. The order should be reversed so that the interface comes after the parent.

**Comment by wing328** [comment]
PR merged.
