### ISSUE TITLE
Enum support in swagger-codegen

### ISSUE THREAD

**Issue by ayakushev99** [swagger-api/swagger-codegen#180]
Currently the only thing that is available in swagger-codegen is a the {{allowableValues}} variable, which contains the string representation of a list. Would be nice to break that out into an actual list, so that we could have enum support.

**Comment by fehguy** [comment]
This is addressed, please see the java samples:

https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples/client/petstore/java
