### ISSUE TITLE
[python] use of Configuration() as default parameter evaluates at definition-time, not runtime

### ISSUE THREAD

**Issue by rbpasker** [swagger-api/swagger-codegen#1802]
using this idiom, Configuration().host is evaluated when the method is defined, which is when `from swagger_client import SomeClient` is executed by the interpreter, and **NOT** when the constructor is called.

````
    def __init__(self, host=Configuration().host,
                 header_name=None, header_value=None, cookie=None):

````

https://github.com/Tengah/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_client.mustache#L69

**Comment by wing328** [comment]
PR merged. Closing the issue.
