### ISSUE TITLE
[java] missing import java.util.Objects 

### ISSUE THREAD

**Issue by dantran** [swagger-api/swagger-codegen#1804]
From Latest 2.1.5-SNAPSHOT

I have a this json schema snippet

    "definitions" : {
      "PointInTimeGroup" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "format" : "uuid",
            "readOnly" : true
          },
          "pointInTime" : {
            "type" : "string",
            "readOnly" : true
          },
          "values" : {
            "type" : "array",
            "readOnly" : true,
            "items" : {
              "type" : "object"
            }
          }
        }
      },

which generate this class PointInTimeGroupValues

with this hash() method

    @Override
    public int hashCode() {
      return Objects.hash();
    }

However the class does not have the required 'import  java.util.*'

**Comment by wing328** [comment]
@dantran thanks for reporting the issue. I could repeat it using the latest master with the model definition you provided above.

We're working on a fix.

In this case, do you intend to generate a model without any property?

**Comment by hiveship** [comment]
It would be great to only import 
```
java.util.Objects
```
instead of 
```
java.util.*
```

**Comment by wing328** [comment]
Totally agree.

**Comment by wing328** [comment]
Submitted #1807 to fix it. For `java.util.*`, I'll work on it later as it requires updating the import logic to handle multiple import for a single type.

**Comment by wing328** [comment]
PR merged. 

Submit #1810 for tracking work related to `java.util.*`
