### ISSUE TITLE
angular2 client

### ISSUE THREAD

**Issue by damienpontifex** [swagger-api/swagger-codegen#1809]
Just wondering if there is an angular2 client in the works?

If not, I'll take a crack one.

**Comment by wing328** [comment]
There's one for Typescript and here is an example for Petstore: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-angular.

Would that meet your requirement?

**Comment by damienpontifex** [comment]
Yes, I found those ones, but they're all for angular1.

Looking at utilising Typescript and Angular2

**Comment by wing328** [comment]
What about updating that to support Angular2? 

For the Java client, we can use the `library` option to specify which HTTP library (e.g. Retrofit, Jersey, etc) to use. Maybe we can use similar approach to support both Angular1.x and 2.x in the same `typescript-angular` client.

cc @tandrup @mhardorf as they might have some work in progress for typescript angular2

**Comment by damienpontifex** [comment]
Started some work on a template here https://github.com/damienpontifex/TypescriptAngular2CodeGen and using the `typescript-angular` language with the swagger-codegen tool.

Still to sort out some issues with imports of the model classes, but a start that generates with the updated types and angular2 style

**Comment by zcsongor** [comment]
+1

**Comment by ilkkanisula** [comment]
+1

**Comment by VR-Architect** [comment]
++1

**Comment by dani-inside** [comment]
+1

**Comment by wing328** [comment]
Thanks @damienpontifex. May I know if you need any help with the import of model classes?

**Comment by damienpontifex** [comment]
Hi @wing328 yes, help with importing model classes would be good.

Currently I have all types exported via api.d.ts similar to how typings would have worked with angular1. Although having issues getting the appropriate import statement when there is an intra dependency. 

As an example, if you run `swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -o client/petstore -l typescript-angular -t .` from inside [my template repo](https://github.com/damienpontifex/TypescriptAngular2CodeGen), the generated `Pet` class requires an import of `Category` and `Tag` but I haven't come across anything thus far to put just the required import statements in the model.mustache file for generators. 

Hope this makes some sort of sense.

**Comment by wing328** [comment]
You can use the {{imports}} mustache tag. For example, ObjC model template (header) 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/objc/model-header.mustache#L10
outputs the following for Pestore
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/objc/SwaggerClient/SWGPet.h

For specifying the `library` option in the Java code generator, here are some good starting points: 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L105

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L179

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L246

**Comment by wing328** [comment]
@damienpontifex has submitted a PR to include the work he's done so far.

If anyone from the community wants to continue the work, please reply to let us know.

**Comment by roni-frantchi** [comment]
I've created a client project, using some of damienpontifex 's templates, altering them a bit to make the generated code compile and actually work, and included them in a java project created using the swagger cli. see here:

**Comment by Vrolijkx** [comment]
I created a pull request based on roni-fratchi's work. see #2645.

**Comment by wing328** [comment]
PR merged into master. Please pull the latest.
