### ISSUE TITLE
[Java] better import to avoid `java.util.*`

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#1810]
Currently, the Java model contains redundant import, e.g. 
```
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Category;
import io.swagger.client.model.Tag;
import java.util.*;
import java.util.Objects;
```
Ref: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java#L9

`import java.util.*;` should be replaced with the following:
```
java.util.ArrayList;
java.util.List;
```

We will need to revise the import logic to handle multiple import for a single type.

**Comment by Mumutu** [comment]
By the way. not all the java library ‘s pom file .i.e retrofit  has the 
```xml
<dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>${jackson-version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson-version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson-version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.jaxrs</groupId>
      <artifactId>jackson-jaxrs-json-provider</artifactId>
      <version>${jackson-version}</version>
    </dependency>    
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-joda</artifactId>
      <version>2.1.5</version>
    </dependency>
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>${jodatime-version}</version>
    </dependency>
```

**Comment by wing328** [comment]
@Mumutu do you mind submitting a PR for the above? We'll review accordingly. Thanks.

**Comment by Mumutu** [comment]
@wing328  Since the retrofit library uses `gson` as serializer/deserializer so the imports 
```
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
```
is dummy.  So I am not sure whether use a fixed `imports` in retrofit's `model.mustache` or just add the dependency in the `pom.mustache`. Currently I just remove the fastxml import with a replace " " ..

**Comment by CraigStuntz** [comment]
Was about to report this myself! I ended up declaring my own `ApiModel` and `ApiModelProperty` types, since it was slightly less irksome than either using a hacked up version of codegen locally or taking an unnecessary dependency. Would be fine if this was configurable via a template, but making it automatic would be even better.

**Comment by xhh** [comment]
@Mumutu @CraigStuntz the jackson imports issue was fixed (for e.g. retrofit) in commit f4581d3, which is included in v2.1.5 and the latest master.
See the petstore for example, there's no JsonProperty/JsonValue in the [model](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/retrofit/src/main/java/io/swagger/client/model/Pet.java).

**Comment by CraigStuntz** [comment]
@xhh I'm talking about `ApiModelProperty` and `ApiModel`, not `JsonProperty`/`JsonValue`. I am using v2.1.5 and Retrofit. The imports are still there, both in the models I'm generating and in the example you link. They will probably be unnecessarily added as long as [these lines](https://github.com/xhh/swagger-codegen/blob/34a941f3528c85961f6b63275bf4cca27ef82c51/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L525-L526) of code are still present, although I appreciate that there are times when the imports will in fact be necessarily, namely if you actually use those attributes in your mustache template (I don't).

**Comment by xhh** [comment]
For `ApiModelProperty` and `ApiModel`, please track on #2152
