### ISSUE TITLE
inheritence models may lookup by wrong key

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1817]
For inheritance of schemas, it is possible that the keys are being resolved by model name, not by original key name

**Comment by erikvanzijst** [comment]
> 13:36 < erikvz> https://bitbucket.org/snippets/evzijst/78nyR
> 13:36 < erikvz> when parsing the "repository" object
> 13:36 < erikvz> which extends base_object
> 13:36 < erikvz> at the time of the NullPointer it has already parsed base_obejct and it's in the 
>                 allDefinitions map
> 13:37 <@tonytam> looking
> 13:37 < erikvz> except it seems to look it up by the Java class name "BaseObject", while the 
>                 allDefinitions map keys with the original json names (base_object)
> 13:37 < erikvz> and so it pulls out null and then fails shortly after
> 13:38 < erikvz> io/swagger/codegen/languages/JavaClientCodegen.java:461
