### ISSUE TITLE
Custom NodeJS server port

### ISSUE THREAD

**Issue by frinux** [swagger-api/swagger-codegen#1825]
In the file: swagger-codegen/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java

Line 24: ```protected int serverPort = 8080;```

It seems this value cannot be overridden, am I right? Is it planned?

Thanks

**Comment by fehguy** [comment]
Seems like this should follow the java server port:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JaxRSServerCodegen.java#L174-L182

**Comment by frinux** [comment]
This is for Jax-RS, not fore NodeJS server?

**Comment by fehguy** [comment]
yes, i'm saying we can use this same technique here.  Please watch for a commit to address this.

**Comment by wing328** [comment]
@fehguy I can help work on this tomorrow if you're busy with other enhancements.

**Comment by fehguy** [comment]
I've got this one--thanks for offering!
