### ISSUE TITLE
readme.md doesn't agree with usage: -D either is or is not an allowed option

### ISSUE THREAD

**Issue by leemeador** [swagger-api/swagger-codegen#1828]
Github is showing README.md on its main page.  On that page in the SYNOPSIS section and OPTIONS below, it says I can use -D as an option. Further down the page it indicates properties (like the Java "models" option) can be set with -D.

I try it by using the following gradle task:
```Groovy
task genSwagger(type: JavaExec) {
    description "generate swagger doc or clients via codgen package and gradle"
    // has buildscript dependency  classpath "io:swagger-codegen:2.1.5"
    classpath = buildscript.configurations.classpath
    args  = ["generate",
             "-i", "http://localhost:25630/v1/mystuff/api-docs",
             "-o", "${buildDir}/docs/rest-api",
             "-l", "jaxrs",
            "-D", "models"
            ]
    main      = "io.swagger.codegen.Codegen"
}
```
and I get "usage" that does not show -D as an option. It does not say that -D is the offense causing usage to be shown but removing the -D actually generates .java files.
```
usage: Codegen
 -a,--auth <arg>           adds authorization headers when fetching the
                           swagger definitions remotely. Pass in a
                           URL-encoded string of name:header with a comma
                           separating multiple values
 -c,--config <arg>         location of the configuration file
 -d,--debug-info           prints additional info for debugging
 -h,--help                 shows this message
 -i,--input-spec <arg>     location of the swagger spec, as URL or file
 -l,--lang <arg>           client language to generate.
                           Available languages include:
                           [android, async-scala, csharp, dart, flash,
                           python-flask, java, javascript, jaxrs,
                           inflector, jmeter, nodejs, objc, perl, php,
                           python, qt5cpp, ruby, scala, scalatra,
                           silex-PHP, sinatra, slim, spring-mvc,
                           dynamic-html, html, swagger, swagger-yaml,
                           swift, tizen, typescript-angular,
                           typescript-node, akka-scala, CsharpDotNet2,
                           clojure]
 -o,--output <arg>         where to write the generated files
 -t,--template-dir <arg>   folder containing the template files
```
Version 2.1.5, 2.1.4

**Comment by fehguy** [comment]
Try `-Dmodels` not `-D models`

**Comment by leemeador** [comment]
Thank you fehguy for the suggestion. I will try that.

The issue I was trying to report is that the Github docs don't match what "usage" shows. A reasonable fix would have both show the same option list for "generate"

Perhaps there is another issue here in that Github looks like there is a space after the -D but you seem to be saying that is incorrect as well

**Comment by leemeador** [comment]
This does not work either (though I tried it with 2.1.5 instead of 2.1.2) so leaving the space out isn't a way for me to get the output I want.

    args  = ["generate",
             "-i", "http://localhost:25630/v1/mystuff/api-docs",
             "-o", "${projectDir}/",
             "-l", "java", "-Dmodels"
            ]

The result is the same "usage" message as in the original issue report.

**Comment by fehguy** [comment]
OK from this command:

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i http://petstore.swagger.io/v2/swagger.json \
   -o foo \
   -l java \
   -Dmodels
```

It does appear that the empty `-Dmodels` does _not_ generate "all models".  It _does_ work by specifying the models you want to generate specifically like `-Dmodels=Pet,Order`.  So there's a bug here.

**Comment by wing328** [comment]
When I'm trying to fix this bug and tested with `-Dmodels=Pet,Order`. Only the model Pet is generated. I tested with `-Dmodels="Pet,Order"` but got the same result. It seems like everything after `,` is omitted. Am I the only one having this issue?

**Comment by wing328** [comment]
@leemeador you need to add -Dmodels to the 1st command line argument like this:
```
java -Dmodels -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i modules/swagger-codegen/src/test/resources/2_0/petstore.json \
   -l csharp \
   -o /var/tmp/csharp/assembly/
```

**Comment by wing328** [comment]
@leemeador closing this as there's no update.
