### ISSUE TITLE
[Java Client] Authentication not correctly added

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-codegen#1836]
I am writing a specification for my API and I've found a problem in the Java client generated (I generate my with using the Swagger Editor option > Generate Java Client).

My Swagger files contains:
```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Application Server
  description: The API to communicate with the Application Server
  termsOfService: http://foo.com/terms
  contact:
    name: Foo Company
    email: contact@foo.com
    url: http://foo.com
  license:
    name: Licence
    url: http://
    
host: localhost:8080

basePath: /foo

schemes:
  - http
  
consumes:
  - application/json
  - application/xml
  
produces:
  - application/json
  - application/xml
  
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP`.
 security:
       - basicAuth: []
  
paths:
  /:
    get:
      description: |
        Get the general information about the nabuTalk Application Server
      summary: Ping the nabuTalk Application Server.
      operationId: ping
      tags:
        - Global
      responses:
        200:
          description: Server information
        default:
          description: Server error
          schema: 
            $ref: '#/definitions/Error'
```
So I think that this file is correct to specify a HTTP Basic Authentication for the whole API.

In the Swagger Editor and the Swagger UI everything is OK, I can test my methods and it's working.
But in the Java generated client, I always got an HTTP 401 return code. It seems that the authentication is not added as a header parameter.

My Java code is:
```java
ApiClient apiClient = Configuration.getDefaultApiClient();
apiClient.setUsername("username");
apiClient.setPassword("password");

GlobalApi defaultApi = new GlobalApi(apiClient);
defaultApi.ping();
```

but if I modify my Swagger file as below (remove the global "security" element and add it on each method on each path)
```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Application Server
  description: The API to communicate with the Application Server
  termsOfService: http://foo.com/terms
  contact:
    name: Foo Company
    email: contact@foo.com
    url: http://foo.com
  license:
    name: Licence
    url: http://
    
host: localhost:8080

basePath: /foo

schemes:
  - http
  
consumes:
  - application/json
  - application/xml
  
produces:
  - application/json
  - application/xml
  
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP`.
  
paths:
  /:
    get:
      security:
       - basicAuth: []
      description: |
        Get the general information about the nabuTalk Application Server
      summary: Ping the nabuTalk Application Server.
      operationId: ping
      tags:
        - Global
      responses:
        200:
          description: Server information
        default:
          description: Server error
          schema: 
            $ref: '#/definitions/Error'
```
Then everything is ok !

I think it's a bug ?

**Comment by fehguy** [comment]
not a bug!  You need to declare what methods need which security requirements.  In your example, adding `security` on the `/get` method is what you need to do.  To apply security to *all* operations, you would add it at the same level as `paths`.

**Comment by xhh** [comment]
I think the reason is that the swagger-codegen at http://editor.swagger.io/ is not the latest one.

I can reproduce the issue on http://editor.swagger.io/ with the above spec (with indentation corrected and a fake `Error` definition).
In the downloaded Java client, **GlobalApi.java** contains:
`String[] authNames = new String[] {  };`

But when I tried downloading the spec and generating the Java client with my local (latest) swagger-codegen, it is fine:
`String[] authNames = new String[] { "basicAuth" };`

**Comment by hiveship** [comment]
@fehguy It's exactly what I am trying to do, look at my first Swagger file:
```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Application Server
  description: The API to communicate with the Application Server
  termsOfService: http://foo.com/terms
  contact:
    name: Foo Company
    email: contact@foo.com
    url: http://foo.com
  license:
    name: Licence
    url: http://

host: localhost:8080

basePath: /foo

schemes:
  - http

consumes:
  - application/json
  - application/xml

produces:
  - application/json
  - application/xml

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP`.
security:
       - basicAuth: []

paths:
```
There is a "security" bloc at the same level as "paths" and it's now working !

@xhh is correct, with the first Swagger File, I have:
 ```java
    String[] authNames = new String[] {  };
```

but when I specify the security on each method It's correct:
```java
    String[] authNames = new String[] { "basicAuth" };
```

I have only tried with the swagger-codegen at http://editor.swagger.io/.

**Comment by jbonevich** [comment]
This continues to be an issue in v2.2.1

**Comment by jbonevich** [comment]
Nevermind.  A closer reading of the spec revealed my issue.  You specifically have to provide an empty value to the security setting if it is NOT oauth.  So, for example:

security:
  - api_key: []
