### ISSUE TITLE
compilation error when generating client library

### ISSUE THREAD

**Issue by pradeepgoudra** [swagger-api/swagger-codegen#1837]
Issue I am seeing is when swagger has type as string like below

"CityName": {
      "type": "string"
    },

Java class generated is as below and it doesn't have imports for javax annotation and so compilation error. 

package io.swagger.client.model;

import java.util.Objects;

@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-01-07T10:48:57.939-05:00")

How can we fix this?

**Comment by fehguy** [comment]
ok that's a bug.  For now, disable the generation option

**Comment by pradeepgoudra** [comment]
thanks for the response. Do  you know time frame when this will be fixed and released.

**Comment by fehguy** [comment]
well we just released yesterday so it'll probably be a few days minimum.

**Comment by pradeepgoudra** [comment]
Ok np. Please notify me when the issue is fixed and i can retest. Appreciate your help.

**Comment by fehguy** [comment]
I will close this bug when it's in snapshot.

**Comment by wing328** [comment]
@pradeepgoudra please try the latest master and let us know if it's still an issue.

SNAPSHOT of the latest master can be found in the project's README
