### ISSUE TITLE
Binary file encoding issues and Ruby

### ISSUE THREAD

**Issue by jqr** [swagger-api/swagger-codegen#1848]
I'm new to the swagger-codegen project, so apologies if this is the wrong venue or way to suggest changes.

I'm working on making a fix for downloading file data using a Ruby generated swagger client. My primary issue is when downloading a binary file, a file is made on the local filesystem with default encoding (UTF-8) and then binary data is attempted to be written into it, which triggers an attempted encoding transformation. At best, this transformation will fail and you'll get an immediate exception. At worst you'll get a silently corrupted file.

This is happening because the Rails framework [sets default encodings to `UTF-8`](https://github.com/rails/rails/blob/master/railties/lib/rails.rb#L19-L20) and that's used everywhere an encoding isn't specified, like in swagger client file write operations.

I believe the smallest change to fix this is to open the file in binary mode instead of the default. This is just adding a `b` to the flags passed to `File.open`. I provide a better fix below.

```ruby
File.open(path, 'wb') { |f| f.write(response.body) }
```

But the more I look at this code I wonder if we should be doing all this file manipulation in the first place. It's likely similar issue exists in some other language generators too. The Ruby client:

```ruby
# Save response body into a file in (the defined) temporary folder, using the filename
# from the "Content-Disposition" header if provided, otherwise a random filename.
#
# @see Configuration#temp_folder_path
# @return [File] the file downloaded
def download_file(response)
  tmp_file = Tempfile.new '', @config.temp_folder_path
  content_disposition = response.headers['Content-Disposition']
  if content_disposition
    filename = content_disposition[/filename=['"]?([^'"\s]+)['"]?/, 1]
    path = File.join File.dirname(tmp_file), filename
  else
    path = tmp_file.path
  end
  # close and delete temp file
  tmp_file.close!

  File.open(path, 'w') { |file| file.write(response.body) }
  @config.logger.info "File written to #{path}. Please move the file to a proper folder "\
                      "for further processing and delete the temp afterwards"
  File.new(path)
end
```

Summarized:

1. Make a `Tempfile` with a specific `temp_folder_path` solely to get it's path + filename.
2. If a filename was given use that with the path from above
3. Otherwise use `Tempfile` generated filename.
4. Close `Tempfile`
5. Open a new file with the name, write all data to it.
6. Close new file
7. Warn user about the things we're doing
8. Open file once more and leave open

What value does saving to a file in the generated client file provide? It saves the user this bit of Ruby in their application:

```ruby
File.open(filename, mode) { |f| f.write(response) }
```

In theory it could provide a streaming write of the data to disk, but it does not at present.

The downside of saving the user 1 line of code is 16 lines of generated code that introduces a fair number of complexities and increased responsibility for the swagger-codegen libraries.

**Security Issue**

> From [HTTP/1.1 RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html)
> 
> The receiving user agent SHOULD NOT respect any directory path information present in the filename-parm parameter, which is the only parameter believed to apply to HTTP implementations at this time. The filename SHOULD be treated as a terminal component only.

As shown by the code below, we are actually allowing relative path components to sneak in from this field. At minimum we should use `File.basename(filename)`.

```ruby
# simplified code from above
tmp_file = Tempfile.new '', "/usr/local/" # using a dir everyone has to ease in running this code locally
content_disposition = 'filename="../../hello"' # this is possible
filename = content_disposition[/filename=['"]?([^'"\s]+)['"]?/, 1]

path = File.join File.dirname(tmp_file), filename
# => ""/usr/local/../../hello" # unintended

path = File.join File.dirname(tmp_file), File.basename(filename)
# => ""/usr/local/hello" # intended
```

**Encoding**

Care must be taken to ensure matched encoding of input data to the filesystem. For Ruby this should probably just match the file encoding to the response body encoding. This problem only appears when `Encoding.default_external` is set, which is very commonly set to `UTF-8` in the Ruby world.

```ruby
File.open(path, 'w') do |file|
  file.set_encoding(response.body.encoding)
  file.write(response.body)
end
```

**Unecessary Open/Close**

On every file save we open 3 files, and write 1, and close 2. With some optimization of the current technique we could make that a little better.

|                         | opens | writes | closes
|-------------------------|-------|--------|-------
| current                 |     3 |      1 |      2
| optimized no filename   |     2 |      1 |      1
| optimized with filename |     1 |      1 |      0

**Read-only environments are blocked**

Requiring write access to the filesystem limits places where this code can run. What if you're just going to send this data to S3? Why write it to the filesystem at all?

**Common case causes warnings that are dangerous if ignored**

The current code requires warnings about remembering to delete files otherwise they will accumulate over time and probably fill the disk. This seems pretty dangerous for the common case.

**Should we be using files at all?**

The added security, encoding, configuration, performance and limitations weighed against a single line of file writing suggests to me that filesystem manipulation adds a lot of increased complexity with very little benefit.

What's the process for changing something like this? I'm happy to undertake this for the Ruby language, and possible others as I become more familiar with them.

**Comment by wing328** [comment]
@jqr thanks for the detailed analysis. I agree with you that the Ruby file download operation can be further improved. For the C# client, it will return a in-memory file. Are you suggesting something similar for Ruby? 

For the security issue, we'll check other client to see if there's a similar issue and fix accordingly.

To submit a PR, the [contributing guildeline](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md) is a good starting point.

**Comment by jqr** [comment]
Wow, all that typing and I wasn't really clear on my suggestion, ha. 

I think that returning a string in Ruby makes the most sense and we should remove the file handling entirely. It side-steps the issues I outlined above and would solve an immediate problem I'm running into with the Ruby generated client in Rails.

**Comment by wing328** [comment]
@jqr the main reason why I decided to return a file instead of string/byte array is usability. If a developer uses the SDK and call the method, all they get back is just a file (which can be easily and likely understood by a beginner programmer who just learns programming in Ruby for only 3 months) 

Of course, as you point out, the file is saved in temp directory (which is configurable) and needs to be cleaned up later (or the file should be moved to a proper location after the method returns the file), which is definitely a limitation of this approach. 

To return a string/byte array, may I suggest you to describe the return type as `type:string` & `format:binary` instead? The binary format is not yet supported in the Ruby client but I think it should be more suitable to describe a string/byte array representation of a file.

Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by jqr** [comment]
Yeah I think I had tried that without success before and assumed file was the best approach since it worked.

Can you point me towards a working version of the string/binary style in one of the other languages so I can bring that functionality into Ruby?

**Comment by wing328** [comment]
I just submitted https://github.com/swagger-api/swagger-codegen/pull/1864 for C# API client. Please take a look. I'm still looking for a better way to test binary body parameter.

**Comment by wing328** [comment]
FYI. Filed #1865 to fix the filename security issue. Thanks again for reporting the issue.

**Comment by jqr** [comment]
Looks like the initial issue is resolved with #1876.

P.S. You're doing amazing work bringing the changes to all the languages. Thank you! :clap::clap::clap:

**Comment by wing328** [comment]
@jqr are you working on adding support for `binary` in the Ruby API client? Just want to avoid duplicated efforts.

**Comment by jqr** [comment]
I haven't started yet. It's all yours sir :)

**Comment by wing328** [comment]
@jqr no problem. We should be able to implement it by the end of this week.
