### ISSUE TITLE
PHP file deserializing undefined variable

### ISSUE THREAD

**Issue by jqr** [swagger-api/swagger-codegen#1849]
In b282d4f a typo on [this line](https://github.com/swagger-api/swagger-codegen/commit/b282d4f#diff-630a0645a0b3fabb89412db600734cfbR201) references an unset variable causing the file download code to get the following error in PHP.

```
PHP Notice:  Undefined variable: httpHeaders in .../lib/ObjectSerializer.php on line 234
```

The defined variable is singular, but the reference is plural. For what it's worth, I think plural form is more appropriate :)

A test case would catch this issue. As soon as I familiarize myself with the PHP tests I'll try to write one along with the fix.

**Comment by wing328** [comment]
Fixed with https://github.com/swagger-api/swagger-codegen/pull/1832

I took your suggestion and used httpHeaders instead as httpHeaders is an array of string.
