### ISSUE TITLE
unknown library: retrofit2

### ISSUE THREAD

**Issue by farmazon3000** [swagger-api/swagger-codegen#1850]
When I create JSON config like:

```
{
  "library":"retrofit2"
}
```

and try do make:

```
java -jar swagger-codegen-cli-2.1.4.jar generate -i https://graphhopper.com/api/1/vrp/swagger.json -l java -o ../vrp-client -c retrofit2cfg.json 
```

I'm getting an exception:

```
Exception in thread "main" java.lang.RuntimeException: unknown library: retrofit2
	at io.swagger.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:1637)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:307)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:186)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by farmazon3000** [comment]
It works fine when I change to:

```
{
  "library":"retrofit"
}
```

**Comment by wing328** [comment]
@farmazon3000 are you using the latest version (2.1.5) or master ?

**Comment by wing328** [comment]
From the command line, you're using 2.1.4, which does not have retrofit2 support yet. Please use 2.1.5 or the latest master. (I just did a test with retrofit2 and it worked fine as expected)

**Comment by farmazon3000** [comment]
Indeed it works with v2.1.5.

**Comment by Sujimoshi** [comment]
I have 2.2.2 but still has: "unknown library: retrofit(retrofit2)" Mac OS installed via homebrew

**Comment by bdauer** [comment]
@Sujimoshi did you find a way to resolve? I'm seeing the same thing.

**Comment by wing328** [comment]
@Sujimoshi you may be specifying "android" instead of "java' as the language.
