### ISSUE TITLE
Wrong link: tag v2.1.5 in README.md leads to v2.1.4

### ISSUE THREAD

**Issue by farmazon3000** [swagger-api/swagger-codegen#1852]
In README.md in the part:

```
2.1.5 (current stable) 	2015-01-06 	1.0, 1.1, 1.2, 2.0 	tag v2.1.5
```

link leads to https://github.com/swagger-api/swagger-codegen/tree/v2.1.4 which is probably wrong, please check.

**Comment by wing328** [comment]
Fixed.
