### ISSUE TITLE
[WIP] Generate server code that use Apache CXF

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-codegen#1854]
I have read something about generating server code from a Swagger spec that use Apache CXF ? However, in the generator, I can"t find anything about it ? :(
Can someone tel me how to generate a server code using Apache CXF from my Swagger file ?

**Comment by fehguy** [comment]
The generator support JaxRS with Jersey, not CXF.

**Comment by hiveship** [comment]
I found a sample here https://github.com/swagger-api/swagger-samples/tree/master/java/java-jaxrs-cxf . How this sample has been generated ?

**Comment by wing328** [comment]
@hiveship we would welcome contribution for server stub using Apache CXF.

**Comment by hiveship** [comment]
I'm currently working on it :)
See: https://github.com/swagger-api/swagger-samples/issues/43

**Comment by wing328** [comment]
:beers: 

Reopened this task for tracking so that others know it's WIP and can offer help if needed

**Comment by hiveship** [comment]
I will not be able to finish this new codegen support until this issue is not resolved :( 
https://github.com/swagger-api/swagger-codegen/issues/1888

**Comment by hiveship** [comment]
Work finish and PR submitted https://github.com/swagger-api/swagger-codegen/pull/1933

**Comment by hiveship** [comment]
Now in https://github.com/swagger-api/swagger-codegen/pull/1967

**Comment by wing328** [comment]
PR merged.
