### ISSUE TITLE
Distinguish between java.lang.Object and a generated POJO named Object

### ISSUE THREAD

**Issue by erikvanzijst** [swagger-api/swagger-codegen#1856]
A swagger file that contains a definition named "object" compiles into a
class named `Object`. This is technically not a problem as it lives in a
different package than `java.lang.Object`, but this requires the templates to
refer to Java's `Object` using its fully qualified name.

**Comment by wing328** [comment]
@erikvanzijst  Please try the latest version 2.1.6, which should handle this by renaming the model from Object to ModelObject.

**Comment by wing328** [comment]
Closing this as there's no update.
