### ISSUE TITLE
Custom function in mustache files

### ISSUE THREAD

**Issue by giovannibotta** [swagger-api/swagger-codegen#186]
Is it possible to call a custom function from one of the mustache templates as described in [this doc](http://scalate.fusesource.org/documentation/mustache.html#Functions)? I looked through the code but couldn't find a way.

**Comment by ClayAtWork** [comment]
@wing328 @fehguy Is there a way to do this (custom template functions available in mustache) without having to modify the java code?

**Comment by fehguy** [comment]
No, it's not possible right now.  You can have your own templates with your own mustache conditionals.

**Comment by ClayAtWork** [comment]
Ok. And its' still valid that we would just modify the `processModelMap` to insert our own function? Do you think it's a common use case for people to override the java code to suite the generation to their codebase? It'd be nice if this were completely handled by templates, but I understand this is a limitation of mustache.

**Comment by fehguy** [comment]
Yes, you can do that.  We are collecting feedback on the next version of codegen, please chime in with your thoughts on this ticket:

https://github.com/swagger-api/swagger-codegen/issues/3950
