### ISSUE TITLE
sanitizeForSerialization in ObjectSerializer in PHP Client causing bad JSON to be created

### ISSUE THREAD

**Issue by jaredrsowers** [swagger-api/swagger-codegen#1860]
When an object is sent to the client, and all of the properties of the object are null, sanitizeForSerialization behaves incorrectly. The result produces "[]" instead of "{}". If you cast the $values to object `(object)$values` in the `is_object()` section it resolves the issue:

```php
    public function sanitizeForSerialization($data)
    {
        if (is_scalar($data) || null === $data) {
            $sanitized = $data;
        } else if ($data instanceof \DateTime) {
            $sanitized = $data->format(\DateTime::ISO8601);
        } else if (is_array($data)) {
            foreach ($data as $property => $value) {
                $data[$property] = $this->sanitizeForSerialization($value);
            }
            $sanitized = $data;
        } else if (is_object($data)) {
            $values = array();
            foreach (array_keys($data::$swaggerTypes) as $property) {
                $getter = $data::$getters[$property];
                if ($data->$getter() !== null) {
                    $values[$data::$attributeMap[$property]] = $this->sanitizeForSerialization($data->$getter());
                }
            }
            $sanitized = (object)$values;
        } else {
            $sanitized = (string)$data;
        }

        return $sanitized;
    }
```

**Comment by wing328** [comment]
@jaredrsowers thanks for reporting the issue. Do you have cycle to submit a PR for the fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

For test case, you can add it here: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/php/SwaggerClient-php/tests

**Comment by wing328** [comment]
@jaredrsowers fixed by https://github.com/swagger-api/swagger-codegen/pull/1916

**Comment by wing328** [comment]
PR merged. Please pull the latest master and let me know if you're still seeing the issue.
