### ISSUE TITLE
Authentication C# Client

### ISSUE THREAD

**Issue by illukarl23** [swagger-api/swagger-codegen#1868]
How can I set Password and Username of my Client for basic Authentication?
ist it possible to use a Client to call an API that is protected by Windows Authentication?

**Comment by wing328** [comment]
You can use `Configuration` class for authentication: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/Configuration.cs#L30

and then construct the API class with an instance of the configuration, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs#L380

**Comment by wing328** [comment]
I'm not familiar with Windows Authentication. Does it put something (token, username & password, etc) in the HTTP header? If yes, then it can be supported.

**Comment by illukarl23** [comment]
Got it, you can use the RestSharp RestClient.Authenticator and set the Authentication to Ntlm.

thanks.

**Comment by wing328** [comment]
You can obtain an instance of RestClient in ApiClient (e..g https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Client/ApiClient.cs#L76) and set the authentication accordingly.
