### ISSUE TITLE
[Scala Question] How to put path parameters and payload parameters together in a case class?

### ISSUE THREAD

**Issue by yuekang0629** [swagger-api/swagger-codegen#1872]
When I generate Scala clients for my APIs, I noticed that each API's request case class only includes the payload schema. Is there a way to generate Scala clients so that the path parameters and payload parameters is shown together in a case class? Or is there any other tools I can use to accomplish this? Thanks!

**Comment by wing328** [comment]
@yuekang0629 can you give an example to elaborate a bit? 

The Java client (okhttp-gson) also works with Scala and you may want to give it a try.

**Comment by yuekang0629** [comment]
Let's take this API for example:   
  '/sample/{Id}':
    post:
      summary: sample
      operationId: sample
      parameters:
        - name: Id
          in: path
          type: string
          required: true
        - name: payload
          in: body
          required: true
          schema:
            type: object
            properties:
              field1: 
                type: string
              field2:
                type: string
      responses:
        '200':
          description: Successful response

If I generate scala client for this API, I got a payload.scala in /model folder, the case class is like this: 
case class Payload (
  field1: String,
  field2: String)
  
However, in my team, when we define the APIs, we also put the path parameter {Id} in the case class, like this: 
case class sample_request (
  Id: String,
  field1: String,
  field2: String)

Is there a way to generate such case classes?

**Comment by wing328** [comment]
I don't think you can put a path parameter as a model property. What does the HTTP request body looks like for the example above ?

**Comment by yuekang0629** [comment]
@wing328  Thanks for the prompt response. The request body is like is : {"field1":"value1", "field2":"value2"}. Our target case class is actually like this: 
case class sample_request (
apiName: String
Id: String,
field1: String,
field2: String)

Are you going to deploy this in the future?

**Comment by wing328** [comment]
To meet your "requirement", you can change the URL from `/sample/{id}` to `/sample` instead (of course you need to update your backend to handle the POST operation for /sample)

**Comment by wing328** [comment]
For example, https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L65
