### ISSUE TITLE
Jaxrs file upload service class incorrect

### ISSUE THREAD

**Issue by scottrw93** [swagger-api/swagger-codegen#1880]
I am trying to generate Jaxrs server code from the following Swagger definition:

    cars/uploadImage" : {
      "post" : {
        "tags" : [ "The car store" ],
        "summary" : "uploads an image",
        "description" : "",
        "operationId" : "uploadFile",
        "consumes" : [ "multipart/form-data" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "file",
          "in" : "formData",
          "description" : "file in",
          "required" : true,
          "type" : "file"
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
    }

This produces `public Response uploadFile(FormDataContentDisposition fileDetail, SecurityContext securityContext)` in the service implementation class. As you can see it does not provide the `InputStream parameter`, so I have not way of accessing the content of the file except in the api class. 
`InputStream param` is in the api class with the jaxrs annotations and I can access the file there: `public Response uploadFile(  @FormDataParam("file") InputStream inputStream,
			@FormDataParam("file") FormDataContentDisposition fileDetail,@Context SecurityContext securityContext)`

**Comment by wing328** [comment]
@scottrw93 Petstore also has an endpoint for uploading file (image): https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/PetApi.java#L176
and it has an InputStream parameter.

Here is the swagger spec (JSON) for Petstore that you can try to repeat the issue with:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L218

**Comment by scottrw93** [comment]
Yes but it does not pass that param to the delegate class. If you look at https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java#L75 you'll see that it does not have  an InputStream parameter, so you can only access details of the file, not the contents.

**Comment by wing328** [comment]
OK. Understood. If no one has cycle to fix this, I'll give it a try next week.
