### ISSUE TITLE
@DefaultValue not added to JavaJaxRS code

### ISSUE THREAD

**Issue by fooo** [swagger-api/swagger-codegen#1885]
When generating the Java JaxRS code, the in swagger defined defaultvalue is not mapped to a @DefaultValue specification in the API.

I think it should be possible to change _swagger-codegen/modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/queryParams.mustache_ to include @DefaultValue like so:

```
{{#isQueryParam}}@ApiParam(value = "{{{description}}}"{{#required}},required=true{{/required}}{{#allowableValues}}, {{> allowableValues }}{{/allowableValues}}{{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}) @DefaultValue("{{defaultValue}}") @QueryParam("{{baseName}}") {{{dataType}}} {{paramName}}{{/isQueryParam}}
```

**Comment by wing328** [comment]
@fooo do you mind contributing a fix for the issue as I believe you've identified the right place to make the change?

Ref: guildelines for contributing https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by hiveship** [comment]
I submitted a PR https://github.com/swagger-api/swagger-codegen/pull/1902 to handle support the JAX-RS @DefaultValue annotation.

**Comment by wing328** [comment]
PR merged
