### ISSUE TITLE
[csharp] error CS1061: 'RestSharp.RestClient'

### ISSUE THREAD

**Issue by MarcinKwiatkowski1988** [swagger-api/swagger-codegen#1890]
Good morning all, 
when generating the csharp library I got this error:

error CS1061: 'RestSharp.RestClient' does not contain a definition for 'ExecuteTaskAsync' and no extension method 'ExecuteTaskAsync' accepting a first argument of type 'RestSharp.RestClient' could be found (are you missing a using directive or an assembly reference?)

I tried also to put in the bin folder the RestSharp.WindowsPhone.dll instead of RestSharp.dll (and changed the compile.bat file) but is still not working. Can you help me please

**Comment by wing328** [comment]
Which version of RestSharp are you using?

**Comment by MarcinKwiatkowski1988** [comment]
the ddl I put under the project's bin is version 104.1

**Comment by wing328** [comment]
Can you try the latest version of RestSharp using NuGet?

**Comment by wing328** [comment]
The one that comes with the C# API client is v105.1. Please give that a try.

**Comment by MarcinKwiatkowski1988** [comment]
Never used Nuget, but sure, I'll give it a try and let you know

**Comment by MarcinKwiatkowski1988** [comment]
With the latest version is working. Thank you. You should put this error and the solution in some wiki-docs, or otherwise many will just download the most common version of RestSharp, which is not the latest. Thank you again for the solution.

**Comment by wing328** [comment]
Based on your feedback, I've submitted #1925 to update the C# README on the version of the dependencies.
