### ISSUE TITLE
JsonModel deserialization errors

### ISSUE THREAD

**Issue by mateuszmackowiak** [swagger-api/swagger-codegen#1907]
Generated objc is missing JsonModel serialization errors. 
If there is an error in the services and we get an array when a dictionary is needed there is no answer and no error.

**Comment by wing328** [comment]
@mateuszmackowiak thanks for the PR (#1907) to address the issue. 

I left you comments about updating the integration tests for ObjC Petstore client. Let me know if you need any help fixing those.

**Comment by wing328** [comment]
PR (#1907) merged into master. Issue closed.
