### ISSUE TITLE
ObjC & file upload

### ISSUE THREAD

**Issue by ocasta** [swagger-api/swagger-codegen#191]
We've discovered a couple of issues with the code generated for ObjC when wanting a file upload.

- While the swagger 1.2 spec states that for type *file* the paramType MUST be *form*. To generate the appropriate multipart form in the ObjC code, paramType must be *body*

- The field name for a parameter of type *file* is ignored and name=image is always generated

**Comment by fehguy** [comment]
OK this has been fixed, and upgraded to AFNetworking 2.0
