### ISSUE TITLE
Add a vagrantfile to run docker 

### ISSUE THREAD

**Issue by wizardbyron** [swagger-api/swagger-codegen#1913]
As I saw many subjects on running docker with errors. I think run docker in a vagrant VM is a simple idea which sets an standard environment which cross platforms. 
I can add a Vagrantfile with a provision script.

**Comment by wing328** [comment]
@wizardbyron thanks for the suggestion. I don't any drawback providing an option to run docker in a vagrant VM. Do you mind sending a PR so that we can review the suggested change?

**Comment by wizardbyron** [comment]
I have added a Vagrantfile in the PR: https://github.com/swagger-api/swagger-codegen/pull/1943

**Comment by wing328** [comment]
PR merged
