### ISSUE TITLE
PHP client model: Nested objects not converted to JSON

### ISSUE THREAD

**Issue by moee** [swagger-api/swagger-codegen#1914]
I have a swagger file with nested objects. If I convert the object to a string, the nested objects are not serialized to json.

To illustrate the problem I created the following minimal working example of a Swagger definition file: https://gist.github.com/moee/c5fd1d0e10e4bbec654a

## Reproduction

1. Import the provided example into the Swagger editor: http://editor.swagger.io/#/?import=https:%2F%2Fgist.githubusercontent.com%2Fmoee%2Fc5fd1d0e10e4bbec654a%2Fraw%2F0585c6482e5d4cb3bc14c26361d74ee7f553b7f8%2Fpetstore.yaml
2. Click `Generate Client` > `PHP`

With the generated client consider the following code:

        <?php
        $petStore = new \Swagger\Client\Model\PetStore();
        $dog = new \Swagger\Client\Model\Pet();
        $dog->setName("dog");
        $petStore->setPets([$dog]);
        echo strval($petStore);

## Expected result

    { "pets": [ { "name": "dog" } ] }

## Actual result

    { "pets": [ {} ] }

Is this behavior intended or am I missing something?

**Comment by wing328** [comment]
@moee please use json_encode($your_object) as a workaround for the time being (currently, object serializer also uses json_encode to convert the object, array of object of map of object into string)

We'll update the model to use json_encode in the __toString method.

**Comment by wing328** [comment]
@moee I've filed https://github.com/swagger-api/swagger-codegen/pull/1916 to fix the issue.

**Comment by moee** [comment]
@wing328 Wow, that was quick :smiley: Thanks for the fix!

**Comment by wing328** [comment]
PR merged. Please pull the latest and let me know if you're still seeing the issue.

**Comment by kgrosvenor** [comment]
JSON encode gives empty object for me...

**Comment by wing328** [comment]
@kgrosvenor please open a new issue with details for tracking.

Please also try the latest master if you've not done so. SNAPSHOT version of the latest master (2.3.0) can be found in the project's README

**Comment by kgrosvenor** [comment]
I am however using a swagger spec that has a property with an empty object, the idea was for me to hydrate that object with custom data. - is this possible before i open up a issue?

**Comment by wing328** [comment]
You may find this discussion useful: https://stackoverflow.com/questions/25296967/how-to-express-arbitrary-json-in-swagger-spec
