### ISSUE TITLE
Swashbuckle/Swagger-codegen c#: Missing client member of type byte[]

### ISSUE THREAD

**Issue by BugRaptor** [swagger-api/swagger-codegen#1918]
Not sure it is an issue or a missuse on my side:
http://stackoverflow.com/questions/34852192/swagger-codegen-c-missing-client-member-of-type-byte
Any help welcome.
Thank you.

**Comment by wing328** [comment]
@BugRaptor are you using the latest version (master) to generate the C# ApiClient? Binary (byte[]) support was just added recently (not yet in the latest stable release 2.1.5)

**Comment by BugRaptor** [comment]
Actually I'm using the last available Nuget packages Swashbuckle and Swasbuckle.Core (5.2.2). As I understand they seem to include the Swagger-ui 2.1.3. 

Note: I just clone the Swashbuckle git repository (https://github.com/domaindrivendev/Swashbuckle.git) and found that the latest available stable release is 5.2.2 which includes Swagger-ui 2.13. The latest not released version in this repository includes swagger-ui 2.1.4. I found no trace of Swagger-ui 2.1.5 or 2.1.6 in this swashbuckle repository.

But my c# client is generated using maven (3.3.9) and java/jdk (1.7.0_15) from the swagger-codegen java source files found in the https://github.com/swagger-api/swagger-codegen.git github repository to get the swagger-codegen executable jar files (especially the swagger-codegen-cli.jar) and then using them to generate my c# client from the Swagger json documentation file of my Swagger Web Api 2 firmware publishing service.
 
Nevertheless, I found another better way to upload/download firmwares files using a streams instead of byte arrays. This seems to be better supported by the swagger-codegen c# client generator.(Solution found here: https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/SwaggerExtensions/AddFileUploadParams.cs)

**Comment by wing328** [comment]
OK. Please pull the latest as it contains some bug fixes for Windows .net (not mono on Mac/Linux).

**Comment by BugRaptor** [comment]
Done. I pulled the latest state from the github swagger-codegen repository and recompiled the swagger-codegen-cli.jar file and regenerated the c# client. The result is the same. (With the first Byte[] type mapping, the Byte[] LelFile property [DataMember] is always missing in the client side model class PackagePublishRequestInfoAndLel. And with the second type mapping (array of items of type byte) I get the same NullPointerException when generating the client... 
But like I said, I will switch to another solution for my web api, uploading the firmware file as a stream instead of a byte[].
Thank you for your help.

**Comment by wing328** [comment]
Ok. No problem.
