### ISSUE TITLE
generated enums 

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1919]
Currently a generated class gives enums like such:

```java
public enum FormatEnum {
  ENUM1("enum 1"),
  ENUM2("enum 2");

  private String value;

  FormatEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return value;
  }
}
```

When constructing a value from the string "enum 1", you will get an error as "enum 1" is compared against the ENUM1 and ENUM2 keys, resulting in an exception.

**Comment by fehguy** [comment]
There is an easy fix for this.  First, the enum generation in the templates should be updated as such:

```
    public enum MixedCase {
        MYHOME("my-home"),
        MYWORK("my work");

        private String text;

        MixedCase(String text) {
            this.text = text;
        }

        public String toString() {
            return this.text;
        }

        @JsonCreator
        public static MixedCase fromValue(String text) {
            if (text != null) {
                for (MixedCase b : MixedCase.values()) {
                    if (text.equals(b.text)) {
                        return b;
                    }
                }
            }
            return null;
        }
    }
```

Note the `@JsonCreator` which will triggers matching with the input string, and does an equals on the value.

Next, the Serialization mapper--if Jackson--should be configured as such:

```
Json.mapper().enable(SerializationFeature.WRITE_ENUMS_USING_TO_STRING);
```

With this change, the `toString()` method is called, allowing `MYHOME` to serialize as `my-home`.

@wing328 I can make this change but for the other libraries (gson, for example), we may need to have a different approach.

**Comment by wing328** [comment]
@fehguy this is noted. We'll test other Java HTTP libraries.

**Comment by ePaul** [comment]
@fehguy I would write this fromValue method slightly differently:

```java
        @JsonCreator
        public static MixedCase fromValue(String text) {
            for (MixedCase b : MixedCase.values()) {
                if (b.text.equals(text)) {
                    return b;
                }
            }
            return null;
        }
```

No need for the null check, other possibly for a performance optimization.

**Comment by wing328** [comment]
@ePaul I like your suggestion. Do you have cycle to contribute the enhancement?

**Comment by ePaul** [comment]
@wing328 I can't promise anything currently, sorry. (I'm on vacations until start of April, and then likely will be buried in project work again.)

**Comment by wing328** [comment]
@ePaul enjoy your vacation! We'll take care of it. No worry.

**Comment by wing328** [comment]
Added via https://github.com/swagger-api/swagger-codegen/pull/3531
