### ISSUE TITLE
Generated Java Client does not support PATCH

### ISSUE THREAD

**Issue by sutdisi** [swagger-api/swagger-codegen#1924]
ApiClient throws exception for PATCH: ApiException: unknown method type PATCH

Because getAPIResponse does not know about PATCH.

```java
    if ("GET".equals(method)) {
      response = (ClientResponse) builder.get(ClientResponse.class);
    } else if ("POST".equals(method)) {
      response = builder.type(contentType).post(ClientResponse.class, serialize(body, contentType, formParams));
    } else if ("PUT".equals(method)) {
      response = builder.type(contentType).put(ClientResponse.class, serialize(body, contentType, formParams));
    } else if ("DELETE".equals(method)) {
      response = builder.type(contentType).delete(ClientResponse.class, serialize(body, contentType, formParams));
    } else {
      throw new ApiException(500, "unknown method type " + method);
    }
```

**Comment by webron** [comment]
Looks like just one step before a PR!

**Comment by sutdisi** [comment]
Hey webron, does that mean you're working on this?

**Comment by webron** [comment]
No, it means that it looks like you found the code causing the issue, so it should be easy for *you* to create a PR for it.

**Comment by wing328** [comment]
@sutdisi I believe you're using the default Java client, which uses Jersey 1.x as the HTTP client. 

Jersey1.x only supports PATCH using PostReplaceFilter: http://stackoverflow.com/questions/22355235/patch-request-using-jersey-client

As an alternative, you can use Jersey2.x or Retrofit as the HTTP client for your library. Please refer to https://github.com/swagger-api/swagger-codegen#customizing-the-generator for more information on selecting a different HTTP library in the Java API client.

**Comment by sutdisi** [comment]
Using default client I added the override header and the query parameter in the client, but server still received it as a POST. Instead of PATCH which I was trying to send. I didn't see anything in the links, but is there a server setting I need?

**Comment by wing328** [comment]
@sutdisi if you've use tcpdump or other tools to verify that the HTTP request is good (e.g. PATCH is used instead of POST), then I think it's a server-side error.

**Comment by wing328** [comment]
PR merged into master.
