### ISSUE TITLE
Retrofit2 @ApiModel : missing import

### ISSUE THREAD

**Issue by alexist** [swagger-api/swagger-codegen#1929]
In model.mustach, there is not import of io.swagger.annotations.ApiModelProperty class. The import is added in JavaClientCodegen.postProcessModelProperty().

But when a model doesn't have any property, the import is not added and the classes doesn't compile.

**Comment by wing328** [comment]
@alexist sorry for late reply on this. Do you mind providing a spec to easily reproduce the issue?

**Comment by wing328** [comment]
Closing this as there's no update.
