### ISSUE TITLE
Is there a simple usage for generating a python client library by this project?

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-codegen#1931]
I don't want to download the whole project because I only need to using it to generate a python library from my swagger definition file (myswagger.json).

In fact , I can paste my json file to the tool Swagger-Editor and select to generate the Python Client.
But How can I write a offline tool to realize it?

Can I use a restful API of Swagger-Editor to do this?

**Comment by wing328** [comment]
You can use the online generator: https://github.com/swagger-api/swagger-codegen#online-generators

**Comment by LouisZou** [comment]
Thanks wing328. I will look at the online tool.

is there a project like the following:
I have a swagger definition file. The project can read this file and then generate a code to run all of the API to verify the Restful API server. the parameters of request can be got from a specified input file (xml or json).
just like user do the test in the web page of swagger-ui.

**Comment by wing328** [comment]
We don't have that yet. We just added support to generate files for unit testing in PHP API client.

**Comment by LouisZou** [comment]
Hi wing328, just now I try to use the online generate to generate my client code. but it failed with the error "The swagger specification supplied was not valid". where can I get more detailed message for this.
and I can use this swagger definition file to get a swagger-ui page. I think the format of this file is no problem.

**Comment by wing328** [comment]
If you put load the spec into https://editor.swagger.io, did you get any error/warning?

**Comment by LouisZou** [comment]
I paset the spec into the left frame,
there is the following error message in the top of right frame:
emptyDocsError: "Empty Document Error"
level: 900
type: "Empty Document Error"
description: "Empty Document Error"

And I click "jump to line", the line seem normal.

**Comment by LouisZou** [comment]
Thanks wing328, I found the error position.
I add a useless section for defining the Error.
I delete this section and now there is no error in  https://editor.swagger.io.
And Now I try to generate client by online generate tool, but it seems block.
I will wait for it.

**Comment by LouisZou** [comment]
Unfortunately it failed with the same error. I think the Swagger Editor can not get my json file from my Flask Server.
I paste the content of the json file to Swagger Editor, it is ok.
If I select to import URL, it failed with error " Error loading URL:" and the status is "-1".

But I can open the json from my web browser using the URL.

**Comment by fehguy** [comment]
It's probably a CORS issue with your server.  I think your questions are not really editor questions, perhaps they should be moved to the correct projects.

**Comment by LouisZou** [comment]
Thanks fehguy.
in the swagger-Editor, how can I do to resolve the CORS problem for the flask app?

**Comment by LouisZou** [comment]
Addition.
I import the following json file in the swagger-Editor, it also failed with the  above error message.
http://petstore.swagger.io/v2/swagger.json

**Comment by wing328** [comment]
I don't see any error importing http://petstore.swagger.io/v2/swagger.json into https://editor.swagger.io

**Comment by babukt** [comment]
Hi Louis,

Did you get the solution for your requirement? 
I'm also looking similar to this.

**Comment by bedge** [comment]
@babukt For a minimal fuss solution, (on mac):
```
brew install swagger-codegen
swagger-codegen generate -i <json/yaml swagger filename> -l python -o <target dir>
```
