### ISSUE TITLE
Javascript Client Subobject Naming Issue

### ISSUE THREAD

**Issue by petoknm** [swagger-api/swagger-codegen#1935]
I have come across this issue where I have defined an object

![screenshot from 2016-01-21 13-58-16](https://cloud.githubusercontent.com/assets/5087675/12481088/0efc7ee6-c047-11e5-9dd9-9f43c545b4f6.png)

and it automatically creates a subobject (error) for me (because the object contained another object). The issue is that the name for it was derived twice with different results. The name that was generated for the subobject is "ResultError". In the generated code it is imported fine but in the constructor for the Result object it uses a different name "Result_error" which cannot be found when run and therefore throws an error.

![screenshot from 2016-01-21 14-02-30](https://cloud.githubusercontent.com/assets/5087675/12481180/aefe0d74-c047-11e5-822b-f2029ed647f1.png)

I would like to ask where is the part of the code that generates the name for the subobject and why is it not using the same name as the first occurances of the name. Because everywhere else it is fine. 

This contains the YAML example definition which generates the invalid code

[swagger (27).yaml.zip](https://github.com/swagger-api/swagger-codegen/files/99142/swagger.27.yaml.zip)

**Comment by xhh** [comment]
Thanks for reporting the issue. I can repeat it and will submit a PR to fix it.
