### ISSUE TITLE
qt5cpp template does not support file

### ISSUE THREAD

**Issue by realhawker** [swagger-api/swagger-codegen#1936]
The template for the qt5cpp api-body does not contain code for parameters of type "file". I seems to me, that in this case the function input.add_file needs to be called.

**Comment by fehguy** [comment]
You are correct.  If you can provide a code sample or pull request, we can get it added.

**Comment by realhawker** [comment]
I have some code, but I have no experience with mustache and no easy way to test it, because I have neither a running test system nor checked out code. I was using the online generator and it didn't work for me, so I started investigating. From what I see in the rest of the template the code should be something like that:
```
{{#formParams}}
if({{paramName}} != NULL) {
{{^isFile}}
    input.add_var("{{paramName}}", *{{paramName}});
{{/isFile}}
{{isFile}}
    input.add_file("{{paramName}}", *{{paramName}}.local_filename, *{{paramName}}.request_filename, *{{paramName}}.mime_type);
{{/isFile}}
}
{{/formParams}}
```
But I could be completely wrong.

**Comment by wing328** [comment]
@realhawker I've filed #2006 with your suggested fix (with some minor modifications).

Here is what the output looks like: https://github.com/swagger-api/swagger-codegen/pull/2006/files#diff-95df983c928806ef2c2b79fdab4b1d44R498

Please review the change when you've time.

**Comment by realhawker** [comment]
@wing328 Thank you for reacting so fast. The output and the fix are looking OK for me. Do you know when I could expect this fix to be present in the online generator?

**Comment by wing328** [comment]
@realhawker thanks for reviewing the change. PR merged.

@fehguy do we have any plan to deploy the latest master of swagger-codegen to generator.swagger.io?
