### ISSUE TITLE
Wired Java Tests in javascript client test folder.

### ISSUE THREAD

**Issue by wizardbyron** [swagger-api/swagger-codegen#1944]
There are two wired tests in javascript client test folder:

`samples/client/petstore/javascript/test/api/StoreApiTest.java`
`samples/client/petstore/javascript/test/api/UserApiTest.java`

And compare with:

`samples/client/petstore/java/default/src/test/java/io/swagger/petstore/test/StoreApiTest.java`
`samples/client/petstore/java/default/src/test/java/io/swagger/petstore/test/UserApiTest.java`

They are similar.

Could I delete them and create a new PR ?

**Comment by wing328** [comment]
Yes. Please create a PR to remove those. 

I think those Java test under the JS sample folder were accidentally added.
