### ISSUE TITLE
[Go] Add unit testing for Go Petstore API client

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#1948]
Currently, we only have [test.go](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/test.go) to perform a simple HTTP request.

We want to add more tests with https://golang.org/pkg/testing/ to ensure the Go API client works without issues.

If you would like to contribute this task, please reply to let us know.

**Comment by wing328** [comment]
To begin with, we want to test the following methods as a starting point:
- AddPet
- GetPetById
- UpdatePetWithForm

**Comment by guohuang** [comment]
for these tests, do you want to dynamically generate it or you expect static test?

**Comment by wing328** [comment]
Static test is a good starting point. Later we can add auto-generate test cases similar to PHP, C#, Perl: https://github.com/swagger-api/swagger-codegen/issues/2276

**Comment by wing328** [comment]
Done via #2532 #2544 . Thanks @guohuang
