### ISSUE TITLE
[Go] add a Configuration struct to store setting

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#1949]
Similar to API clients in other languages, we want to have a Configuration struct to store settings such as
- `Username`, `Password` for HTTP basic auth
- `ApiKey`, `ApiKeyPrefix` for API key authentication
- `Debug` for switching on/off the debugging flag
- `DebugFile` for the location of the log file
- `OAuthToken` for oauth token 
- `Timeout` for HTTP connection timeout
and more.

Please reply to let us know if you want to work on this.

**Comment by treeder** [comment]
Please also add Host, scheme and base path to this list. They are currently unchangeable in the generated Go code.

**Comment by fehguy** [comment]
:+1:

**Comment by wing328** [comment]
@treeder thanks for the feedback. have you tried another constructor to initialize the API class with basePath? e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/swagger/PetApi.go#L20

**Comment by treeder** [comment]
@wing328 I see, we found this one: NewXApiWithBasePath

Seems like you could end up with a lot of constructors. Even just exporting the fields in the XApi struct seems like it would be sufficient and you wouldn't need extra constructors.

**Comment by wing328** [comment]
@treeder thanks for the feedback. We make the base path configurable via the `WithBasePath` method as `ApiClients` in other languages also offer similar constructor to setup base path (while other option/config setting can be changed via `setter`).

May I know if you've cycle to contribute to this task? Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/api.mustache#L15

**Comment by treeder** [comment]
I don't have the time at the moment, but as we depend on this more, we'll probably be forced to have time. ;)

**Comment by wing328** [comment]
Done via #2528. Thanks @guohuang
