### ISSUE TITLE
[JavaScript] Add a README file to JavaScript client

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-codegen#1954]
It would be good to have a README containing guides like how to use the code in Node.js (as a [NPM](http://npmjs.com/) module) and browser (with [Browserify](http://browserify.org/), [webpack](https://webpack.github.io/) or [RequireJS](http://requirejs.org/)).

**Comment by demonfiddler** [comment]
+1 for comprehensive documentation.

Functional PetStore browser and Node.js example clients would be useful, too.

**Comment by wing328** [comment]
@demonfiddler may I know if you've cycle to contribute a README for javascript cilent?

Here are some good starting points: 
- https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/Javascript
- https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java#L231
- https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/README.md

**Comment by demonfiddler** [comment]
@wing328 I have developed a simple Pet Store web client that uses the swagger-codegen generated JavaScript API, which I'd be happy to contribute. The work queue for my day job just acquired a bunch of new, complicated and time-consuming assignments, so it might prove hard to find the time to create the comprehensive documentation that I'd envisaged. I will endeavour to add some basic usage notes to the readme, however.

**Comment by jimschubert** [comment]
@wing328 I can do this documentation.

**Comment by jimschubert** [comment]
I have barely started on this. Going through job and housing transition at the moment, may be 2-3 weeks before I can get back to it.

**Comment by wing328** [comment]
@jimschubert we've created the documentation (including README) for JS API client. Here is an example: https://github.com/xhh/swagger-petstore-js

Please take a look and let us know if you've any feedback.

**Comment by jimschubert** [comment]
That's great news. I checked it out and the documentation looks really good.

**Comment by wing328** [comment]
@jimschubert thanks for the feedback. All the best to your new job!
