### ISSUE TITLE
README: Python Flask (Connexion): Can't load config class with name flaskConnexion

### ISSUE THREAD

**Issue by hjacobs** [swagger-api/swagger-codegen#1955]
The README (https://github.com/swagger-api/swagger-codegen#python-flask-connexion) says:

```bash
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l flaskConnexion \
  -o samples/server/petstore/flaskConnexion
```

but it should be:

```bash
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l python-flask \
  -o samples/server/petstore/flaskConnexion
```

The first (wrong) command throws an error 'Exception in thread "main" java.lang.RuntimeException: Can't load config class with name flaskConnexion Available:'.

**Comment by fehguy** [comment]
Can you please send a PR for update?

**Comment by hjacobs** [comment]
Will do, I'm also checking the code template for Connexion and will clean it up a bit :smile:

**Comment by fehguy** [comment]
that's great, thank you.

**Comment by hjacobs** [comment]
:+1: thanks, that was fast :smile:

**Comment by fehguy** [comment]
it either happens immediately... or never :D
