### ISSUE TITLE
don't overwrite pom.xml on regeneration

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#1956]
For java clients (and probably others), we should not overwrite the pom.xml when regenerating a client.

**Comment by fehguy** [comment]
Probably should do the same for `package.json`, etc.

**Comment by Velvorn** [comment]
I don't know if you had plans to do it already, but I would love to have this for spring-mvc too!
Also, in general, would it be possible to have something like the `-D` option, but to exclude some files? Something that would allow generating every files except a few ones (like `pom.xml`) directly from CLI...

**Comment by wing328** [comment]
What about adding a `.swagger-codegen-ignore` file (similar to .gitignore) in the output directory, which contains a list of files to be ignored (not overwritten) by swagger-codgen when generating the files? The logic can be applied to all languages.

**Comment by Velvorn** [comment]
@wing328 Great idea !

**Comment by fehguy** [comment]
I'll implement the ignore file in a separate issue.
