### ISSUE TITLE
Java codegen doesn't support multiple security schemes

### ISSUE THREAD

**Issue by jasonmartens** [swagger-api/swagger-codegen#1959]
There is a comment in the DefaultGenerator.java:
```
// NOTE: Use only the first security requirement for now.
// See the "security" field of "Swagger Object":
//  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object
//  "there is a logical OR between the security requirements"
if (securities.size() > 1) {
     LOGGER.warn("More than 1 security requirements are found, using only the first one");
}
```
Which is incorrect as of the current version of the spec, which says there is a logical AND, not OR.

**Comment by xhh** [comment]
Looking at the `security` field of [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) the global [Swagger Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object), I still see logic OR for the provided security requirements. For example for the Operation Object:

> A declaration of which security schemes are applied for this operation. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). This definition overrides any declared top-level security. To remove a top-level security declaration, an empty array can be used.

**Comment by jasonmartens** [comment]
It appears that there is a contradiction then, since this section:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-requirement-object
clearly says that it is an AND. 

It makes sense for the *global* security object to be OR. However, an individual path would need to be AND to support an api_key in addition to oauth for instance.

**Comment by webron** [comment]
There's no contradiction, only a slight confusion.

`security` whether global or at the operation allow you to define a *list* of Security Requirements. Between the items in the list there's a logical OR allowing you to specify different variations.

However, the Security Requirement is an *object* of Security Definitions. Between these there's a logical AND.

**Comment by wing328** [comment]
I suggest we update the spec with examples to show
- API key in header `OR` query
- API key `AND` Client ID in the header

**Comment by cbornet** [comment]
IMO the generator should not set the security on operations but only give a hint on what securities can be used. Then it is the responsibility of the caller to chose which security he wants to use (since there is an OR). This is how it is done in retrofit and feign subgens.

**Comment by wing328** [comment]
@cbornet I left a [comment](https://github.com/swagger-api/swagger-codegen/pull/1961#issuecomment-184597223) in the PR.

For refrofit and feign API clients, does it support `AND` for auth settings (e.g. both `api_client_id` and `api_client_secrete` required in the header) ?

**Comment by cbornet** [comment]
In Feign and retrofit, only the auth global definitions are used. The user then must configure manually which securities are part of its ApiClient with an AND between the securities that he puts. Of course ideally, the operation security definitions would be used but I don't see how the generated code would choose the right security when there is an OR. Maybe something could be done when there is only one operation security but I'm not sure it wouldn't get confusing for the user....

**Comment by wing328** [comment]
Here is the current authentication-related code in PHP for a method that requires either API key in header or query:
```
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('test_api_key_header');
        if (strlen($apiKey) !== 0) {
            $headerParams['test_api_key_header'] = $apiKey;
        }
        
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('test_api_key_query');
        if (strlen($apiKey) !== 0) {
            $queryParams['test_api_key_query'] = $apiKey;
        }

```
In other words, the developer choose which authentication they want by providing the API key in either `test_api_key_query` or `test_api_key_header`

The "problem" is that the developer can set both `test_api_key_header` and `test_api_key_query`, which will result in API key appearing in both query and header in the HTTP request (which may still work if the server does not reject requests with API key in both query and header.

For AND, here is the PHP code for a method that requires both client ID and secret in the header:
```
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-test_api_client_id');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-test_api_client_id'] = $apiKey;
        }
        
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-test_api_client_secret');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-test_api_client_secret'] = $apiKey;
        }
```
(which should work fine)

**Comment by wing328** [comment]
Closing this as @jasonmartens has confirmed it's now working for him after pulling the latest master.
