### ISSUE TITLE
consumes uses swagger default for formData

### ISSUE THREAD

**Issue by jasonmartens** [swagger-api/swagger-codegen#1971]
If an operation has a formData parameter, and there is no consumes specified for the operation, then the default swagger consumes content type will be used. This is a problem because it causes multipart/form-data posts to be sent with application/json as the content type if that is the default defined in the spec.

One solution I came up with is to set the contentType to multipart/form-data if an operation has no other type specified, and contains a parameter with type formData. 
https://github.com/jasonmartens/swagger-codegen/commit/bb2b2ef9a77494c3ca882304bab244193f6c7392

**Comment by wing328** [comment]
Instead of using a default value for `consumes` if `consume` is set to empty array, should the openapi/swagger spec be updated to provide a proper `consumes` instead ?

**Comment by jasonmartens** [comment]
I'm personally not sure. The default seemed logical to me, since in my experience if you are submitting formData, the content type should always be multipart/form-data or application/x-www-form-urlencoded. Maybe that is a problem however, since there is no way to determine which of those to pick? At least for file uploads (my use case) it seems like it should be multipart/form-data.

**Comment by wing328** [comment]
@jasonmartens I mean the owner of the spec should know the correct `consumes` and put it in the spec.

For the issue, may I know which API client did you use? Java? ObjC?

**Comment by jasonmartens** [comment]
I was using the Java client.

**Comment by wing328** [comment]
I believe you're using the default HTTP library for Java (which supports also `retrofit`, `okhttp-gson` and more)

For other API clients like PHP and Ruby, the HTTP library will pick the correct "content-type" (consumes) if it's not provided.

We'll do a test with `refrofit`, `okhttp-gson` Java API client to see if there are similar issue.

**Comment by jasonmartens** [comment]
I'm using okhttp-gson.

**Comment by wing328** [comment]
@jasonmartens are you happy to fix the issue in the spec (by defining a proper consume)?

**Comment by jasonmartens** [comment]
Sure, that would fix the problem too.

**Comment by wing328** [comment]
OK. Issue closed.
