### ISSUE TITLE
Incorrect package.json produced by Javascript codegen

### ISSUE THREAD

**Issue by sladha-db** [swagger-api/swagger-codegen#1973]
I tried this with commit 03b463bc4325764f5d4a9edeef549c166ddc15fc

swagger-codegen Javascript generates  package.json:
   "version": "1.0"

However, node expects semver:
  "version": "1.0.0"

**Comment by xhh** [comment]
By default it uses the `info.version` field of the provided spec, and you could override it with custom config, for example:

```shell
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i your_swagger_spec \
  -l javascript \
  -o your_output_folder \
  -c your_config.json
```

and in *your_config.json*:

```json
{
  "projectVersion": "1.0.0"
}
```

You can get a list of all supported options with this command:

```shell
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l javascript
```

**Comment by wing328** [comment]
Closing this as there's no update.
