### ISSUE TITLE
Javascript - Blob type

### ISSUE THREAD

**Issue by sladha-db** [swagger-api/swagger-codegen#1974]
Tried commit 03b463bc4325764f5d4a9edeef549c166ddc15fc

The Javascript codegen produces a file called ApiClient.js. ApiClient.js refers to Blob type. Node does not have a native Blob type.

**Comment by xhh** [comment]
Thanks for reporting the issue. I've fixed is [PR #1947](https://github.com/swagger-api/swagger-codegen/pull/1947/files#diff-ed539442b1237b0ffd547136ae38868dR90), please try again in that branch or when the PR is merged.

**Comment by wing328** [comment]
@sladha-db PR merged. Please pull the latest and try again.
