### ISSUE TITLE
No commas in arrays for generated javascript client

### ISSUE THREAD

**Issue by petoknm** [swagger-api/swagger-codegen#1987]
Hi
I am generating Javascript client code and I always have to add commas to the arrays at the top of the models. It would be nice to actually fix it because your generated code throws an error when it reaches those lines.
![screenshot from 2016-01-27 08-53-07](https://cloud.githubusercontent.com/assets/5087675/12607244/bc81c98c-c4d3-11e5-96e3-c69becf40fb1.png)
Thanks

**Comment by wing328** [comment]
@petoknm may I know how you generated the JS client? 

I tried to grep "export module" in the template directory but couldn't find anything.

**Comment by xhh** [comment]
@petoknm The issue should've been fixed in the master branch with PR #1922.
Please give it a try and let us know if it works for you.

**Comment by wing328** [comment]
Closing this as there's no update. Please let us know if you're still facing the issue.
