### ISSUE TITLE
[General] We should add more data to the generated headers

### ISSUE THREAD

**Issue by jaz-ah** [swagger-api/swagger-codegen#1996]
Currently a generated header in Swift for example is:
//
// Foo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

It would be useful to also include:
-The date of code generation
-The version of swagger used to generate the code
-Any other useful information that we can add there?

**Comment by wing328** [comment]
I agree. I think there should be standard header for all generated codes. I'll submit a PR this weekend or early next week if no one else has cycle to work on it.

**Comment by jaz-ah** [comment]
cool thx.

**Comment by jqr** [comment]
I wanted to provide some perspective as a swagger-codegen user. We find these date based annotations add a lot of noise to our review process when we regenerate clients.

We solved this problem by writing [post-processing scripts](https://github.com/DocRaptor/docraptor-java/blob/master/script/post_generate_language) but I thought it worth mentioning even if our use-case was a minority.

**Comment by wing328** [comment]
@jqr thanks for sharing the requirement with us.

so ideally the generator should skip the file if the newly-generated file and the one in the output directory are the same, right?

**Comment by wing328** [comment]
What about putting the date in one file only (e..g pom.xml for Java, Gemfile for Ruby, etc)?

**Comment by wing328** [comment]
Submitted https://github.com/swagger-api/swagger-codegen/pull/2008 for Ruby mustache templates. Let me know if you've any feedback.

Will gradually update mustache templates for other languages with similar change.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/issues/2963
