### ISSUE TITLE
onerous to edit embedded mustache files

### ISSUE THREAD

**Issue by RobBlairInq** [swagger-api/swagger-codegen#200]
While making custom templates for my own custom library generation, I found it slow and plodding, having to rebuild the swagger-codegen.jar every time I wanted to modify the templates.

I suggest there should be sample scala example that is setup to load the templates from file system, rather than the resources in the codegen jar file.

**Comment by aparnarus** [comment]
hello, is there a way to override just one single template(Mustache file)? if i specify "templateDirectory" it seems to be taking it for all templates.

**Comment by wing328** [comment]
@aparnarus which version of swagger codegen are you using? I believe the latest stable version supports customizing a single template instead of all.

**Comment by aparnarus** [comment]
Thanks for your response 
Do you have an example ? Or doc 
We are 2.1.6

Thanks again

**Comment by wing328** [comment]
OK. Please given the latest stable version a try: https://github.com/swagger-api/swagger-codegen/releases

**Comment by aparnarus** [comment]
ok will do.
 but to override a Single template file, is setting "templateDirectory" the way to go?

**Comment by wing328** [comment]
Yes, if the generator cannot find the template file in the custom template directory, it will use the default one.

The command line option is `-t` (which is equivalent to "templateDirectory" in the maven plugin option if I'm not mistaken)

Ref: https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen-maven-plugin/README.md#L70

**Comment by aaronjwhiteside** [comment]
@wing328 this solution doesn't work because most languages don't set the embeddedTemplateDir value if a custom templateDirectory is supplied.. so they can't fallback to resolving from the classpath..
