### ISSUE TITLE
Any plans on generating a C# Web API server stub?

### ISSUE THREAD

**Issue by andrewkrowczyk** [swagger-api/swagger-codegen#2004]
I was curious if anyone had already discussed generating a C# Web API server stub/scaffolded project based on a Swagger definition?

**Comment by wing328** [comment]
Yes, there's a separate request [here](https://github.com/swagger-api/swagger-codegen/issues/1469).

We're looking for community contribution. Ideally a working WebApi sample to start with.

Closing this one and using #1469 for tracking.
