### ISSUE TITLE
swagger codegen maven dependency cannot download

### ISSUE THREAD

**Issue by laki88** [swagger-api/swagger-codegen#2005]
I went to the below link. it goes to an error page. 
http://mvnrepository.com/artifact/io.swagger/swagger-codegen

**Comment by wing328** [comment]
Please try https://oss.sonatype.org/index.html#nexus-search;quick~swagger-codegen instead.

**Comment by wing328** [comment]
There's also an online generator: https://github.com/swagger-api/swagger-codegen#online-generators

**Comment by laki88** [comment]
Thanks a lot for the quick response wing328. When I generate via online generator I have to carefully copy generated sources to my project manually. Anyway If I generate via maven plugin, source will be generated in the specified location in the project. The only thing I have to do is issuing maven clean install command. I tried adding  2.1.6-SNAPSHOT as plugin version. but it says that dependency version could not be resolved.

**Comment by laki88** [comment]
I could be able to build the project by removing version property in plugin definition
