### ISSUE TITLE
Swift path format

### ISSUE THREAD

**Issue by onemanstartup** [swagger-api/swagger-codegen#2010]
Codegen makes this kinda code. I think format should be json or xml, but I can't find option for this. I think this is mistake.
```swift
        public class func pOSTApiValuesJson(name name: String) -> RequestBuilder<Void> {
            let path = "/api/values.{format}"
```

**Comment by wing328** [comment]
@onemanstartup Can you share the openapi/swagger spec? Is `format` a path variable?

**Comment by onemanstartup** [comment]
@wing328 I can hide format entirely and then path is "/api/values"
I'm using https://github.com/ruby-grape/grape-swagger
``` ruby
  add_swagger_documentation format: :json, hide_format: false
```

```json
{"apiVersion":"0.1","swaggerVersion":"1.2","produces":["application/xml","application/json","application/octet-stream","text/plain"],
"apis":[{"path":"/session.{format}","description":"Operations about sessions"},
{"path":"/users.{format}","description":"Operations about users"}
,{"path":"/swagger_doc.{format}","description":"Operations about swagger_docs"}],"info":{}}
```
Is there format settings in swagger-codegen? It seems there is not.

**Comment by wing328** [comment]
There's no default `format` in swagger spec. In your case, you've to either define the path variable `format`, remove it (together with `.`) from the path, or replace `{format}` with `json`

**Comment by onemanstartup** [comment]
Yeah sorry. Stupid me, it's not codegen issue, it's my library generate that path.

**Comment by wing328** [comment]
np, ping us if you need further assistance. closing the issue for now.
