### ISSUE TITLE
Spring MVC - Header parameters and Redirect

### ISSUE THREAD

**Issue by glederrey** [swagger-api/swagger-codegen#2012]
Hi,

I encountered a problem with the Spring MVC server.. When I use some parameters as headers and inside a function of the Spring MVC server, I use a header "Location", then the redirect doesn't work.. 

Does anyone have an idea why?? Do I have to put something specific in the headers other than just the Location?? 

BTW, it works correctly when I'm using the same parameters as query.. 

Thanks in advance

**Comment by wing328** [comment]
Do you mean you've a header parameter named `Location`?

**Comment by glederrey** [comment]
@wing328 
Hi,
Yes, exactly.. 

In the mean time, I've done some more careful tests.. The problem doesn't come from the Spring-MVC server but it comes from Swagger UI.. I'll open an issue there and close this one.. 
Sorry for the disturbance..

**Comment by glederrey** [comment]
Issue moved here: https://github.com/swagger-api/swagger-ui/issues/1935

**Comment by wing328** [comment]
`Location` has special meaning (redirection) in HTTP header: https://en.wikipedia.org/wiki/HTTP_location

and I would suggest you avoid using it in your endpoints.

**Comment by glederrey** [comment]
But that's exactly what I want to do.. It's the creation of a new resource.. Maybe there's a better way to do it using Spring MVC??

**Comment by wing328** [comment]
How does creation of a new resource have anything to do with "Location" in the header?

**Comment by glederrey** [comment]
Wikipedia says that when you create new resource, you can redirect using `Location` and 201 or 202 to the newly created resource. 

If I do this, that's because I was never able to make the type `file` in the spec work with Spring MVC.. Returning `byte[]` is easier.. (I always have a 406 error when I use the type `file`)
