### ISSUE TITLE
Csharp client: Avoid generating model classes with "I" prefix and do a rename ex. IEmployeeId -> EmployeeId

### ISSUE THREAD

**Issue by bluemmc** [swagger-api/swagger-codegen#2016]
@wing328 I have a csharp api using swagger where some of the return types on the server side are interfaces like f.x. IEmployeeId. This works fine server side, but gives trouble client side using the current version of the csharp client 2.1.5

When using swagger-codegen with csharp, the generated model class for implementing classes retains the "I" prefix. So I get a generated class called IEmployeeId instead of EmployeeId.

This is very much against C# naming standards with reserves the "I"-prefix to interfaces, so I suggest that generated csharp clients remove any "I" prefix from generated class names.

**Comment by bluemmc** [comment]
I should add that I think swagger-codegen+csharp client to be cool regardless BUT I have great difficulty in persuade c# developers internally to adopt swagger-codegen as long as generated classes have names that violate this universal c# naming standard.

**Comment by wing328** [comment]
@bluemmc thanks for the feedback. Is it correct to say that your spec uses `IEmployeeId` as the class name and it cannot be changed to `EmployeeId`?

Naming the class starting with `I` (e.g. IEmployeeId`) seems to me your spec is biased toward C# and you will face the same issue later when generating API clients in other languages (e.g. PHP, Ruby)

**Comment by bluemmc** [comment]
My server implementation uses IXXXId as the (interface) type of key fields and Swashbuckle/Ahoy (swagger for .NET) expose this type directly in the swagger.json file. 

You do have a point that this might give strange names for PHP/Ruby/etc as well allthough it will not directly violate naming conversions to the same degree as for c#. 

I think in any case that the "I" should be stripped by swagger-codegen, but I will investigate if I can also customize Swashbuckle/Ahoy to strip the "I" so I have a better solution for all languages.

Thanks for the detailed response!

**Comment by bluemmc** [comment]
@wing328 Per you suggestion, I have worked around this on the server side so this issue is no longer a high priority for me.

**Comment by wing328** [comment]
@bluemmc glad you found a workaround. Closing this for now and will reopen if someone cannot find a way to name the models for any reason.
