### ISSUE TITLE
Syntax error in generated JS client

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#2022]
I am using swagger-codegen from master, just cloned.
I am getting the following at the top of my ApiClient.js

```javascript
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['superagent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('superagent'));
  } else {
    // Browser globals (root is window)
    if (!root.) {
      root. = {};
    }
    root..ApiClient = factory(root.superagent);
  }
```

Notice the `root.` and `root..`. This causes node to choke.
My swagger.yaml file is automatically generated from my Java server, so it should be fine.

**Comment by xhh** [comment]
It seems your spec contains an empty title: `{"info": {"title": ""}}`, which will be used to generate the project/module name (if not provided via config options).
I'll work on a fix to use a default module name when info.title is empty string. (Currently it works if info.title is missing, i.e. `null` in JSON)

**Comment by delenius** [comment]
@xhh, thanks for letting me know. Any idea how to get the title generated from Java server code through annotations?

**Comment by xhh** [comment]
@delenius I'm not familiar with it but hope this helps: https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#info

**Comment by delenius** [comment]
... and there I ran into this issue: https://github.com/swagger-api/swagger-core/issues/1594
In short, I cannot set the title, so it would be good to have some other default :)

**Comment by delenius** [comment]
I was able to get a title in, which solved the problem above. However, I found another similar problem. In the `api/FooApi/js` file, there is again the `root.` problem. What attribute is it looking for here?

**Comment by fehguy** [comment]
@delenius my guess is that you need an `operationId` or a `tag` on the operation itself.

**Comment by delenius** [comment]
I do have something like this at the top of my yaml file:

```
info:

tags:
- name: "Foo"
```

The code generation seems sensitive to the exact contents of that string, but I haven't found the pattern yet. With "Foo", as above, and with info.title set to, say "Bar", it correctly generates FooApi.js, with things like `root.Bar.FooApi` in it.

**Comment by delenius** [comment]
I had such a tag already. There seems to be some really weird problem having to do with the exact content of that attribute. By editing it slightly, I got it to work, but I haven't figured out the pattern yet.

In any case, this is another case to add a default and warn the user.
