### ISSUE TITLE
JS client: Support for default parameter values

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#2027]
This is a feature request to support default parameter values in the generated JS client. These seem to be ignored currently.

**Comment by wing328** [comment]
For other API clients, we don't implement default value for parameters because the default value should be handled/added in the server side. 

For your case, if the default value is not provided, will the server handle it properly?

**Comment by delenius** [comment]
I see, but then the problem is that the client will get confused about the arguments. For example, if I have one operation `foo` that takes one parameter `bar` (say as a query param), which has a default value, then the generated client API function will be

```javascript
self.foo = function(bar, callback) {
...
}
```

Now, if the user just calls `foo(myCallback)`, things will not work. You would have to at least call it with `foo(null, myCallback)` (which is kind of ugly).

However, I realize now that there will be problems when you have a mix of default and non-default parameters. E.g. this would not work:

```javascript
self.foo = function(p1, p2 = true, p3, p4 = false){
 ...
}
```

I guess this is why [the other JS client](https://github.com/swagger-api/swagger-js) uses named parameters, like

```javascript
foo({ p1: 17, p4: true })
```

**Comment by wing328** [comment]
Definitely valid point and we'll evaluate your suggestion using named parameter (which is already supported by C#, Ruby, etc)

**Comment by xhh** [comment]
We can implement optional parameters like in [Ruby client](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/ruby/lib/petstore/api/pet_api.rb#L334). I'll submit a PR for it.

**Comment by wing328** [comment]
@delenius what's your view on using Ruby's style optional parameter in JS functions?

**Comment by delenius** [comment]
I like it, and I have seen that style used in JS libraries before.
