### ISSUE TITLE
JS client on the web: Undefined from require('fs') in isFileParam

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#2028]
Using the JS generator, I get `undefined` from `require('fs')` in the function `isFileParam` in `ApiClient.js`:

```javascript
    if (typeof module === 'object' && module.exports &&
        (param instanceof Buffer || param instanceof require('fs').ReadStream)) {
      return true;
    }
```

I am using browserify, and I tried installing `browserify-fs`, and setting this in my package.json:

```json
  "browser": {
    "fs": "browserify-fs"
  }
```

But I am not sure that this is the correct approach.

**Comment by xhh** [comment]
Thanks for reporting the issue, I'll fix it.

P.S. the `fs` or `browserify-fs` module is not needed here.
