### ISSUE TITLE
Generated code for C# does not include default headers for some methods

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#2029]
_From @ayuda-yves on February 3, 2016 16:21_

Some generated methods have the line:

`var headerParams = new Dictionary<String, String>();`

instead of

`var headerParams = new Dictionary<String, String>(Configuration.DefaultHeader);`

Because of this, the default headers are missing when calling those methods.

Not sure why some methods have the correct code and why others don't, but it seems to be based on the method's signature as all methods with the same signature will either all include headers or none do.

_Copied from original issue: swagger-api/swagger-editor#808_

**Comment by wing328** [comment]
Submitted #2035 to fix the issue. Sorry for the oversight.

**Comment by wing328** [comment]
PR merged into master. @ayuda-yves please pull the latest master and give it another try.

**Comment by wing328** [comment]
@ayuda-yves closing this as there's no further update from you.

**Comment by ayuda-yves** [comment]
Oops, sorry. It works. :)

**Comment by wing328** [comment]
@ayuda-yves np. thanks for the confirmation. let us know if you've further feedback on the C# API client.
