### ISSUE TITLE
[csharp] Generics yields illegal class names in output

### ISSUE THREAD

**Issue by bluemmc** [swagger-api/swagger-codegen#2033]
My endpoints use generic C# types like Resource[Employee], that unfortunately yields illegal class names (and strange filenames) in the generated C#.  

The generated class/file names for the above example should be "Resource_Employee" rather then "Resource[Employee]" since it is a concrete instance that is being generated and not a generic type.

I.e. For any generic C# type GT<A> the name of the generated file/class by swagger-codegen should be GT_A

**Comment by bluemmc** [comment]
Actually, I just checked what the java code generator does for this and the name of the generated output is "ResourceEmployee" for the example about. The csharp output should properly be aligned with this (no underscore).

**Comment by wing328** [comment]
Thanks for reporting the issue. I'm working on other changes for CSharp and will try to include a fix for this.

We'll check other languages as well.

**Comment by bluemmc** [comment]
Wonderful !! Great news.

BTW: Interestingly, I tried to run my copy of the csharp *.mustache files using the java generator and then the generated files/names seem to be correct (but there might be other bugs introduced). This leads me to conclude the error is not in the csharp *.mustache templates but in the c# generator code. Maybe some code can be copied from the java to the csharp generator to easily fix it ?

**Comment by wing328** [comment]
Submitted #2035 to fix the issue. My test result looks good.

**Comment by bluemmc** [comment]
That was fast. Do you have an ETA for next release ?

**Comment by wing328** [comment]
PR merged into master. Please pull the latest master and give it a try.

**Comment by bluemmc** [comment]
Ok. I installed latest jdk, maven and build using todays master. The class/file names are now correct (and models are partial). Unfortunately, the generated output will not be compile but this is unrelated to this fix (see #2064). 

Thank you very much for the fix.
