### ISSUE TITLE
Python client will not take list of files

### ISSUE THREAD

**Issue by scottrw93** [swagger-api/swagger-codegen#2036]
I am trying to upload a list of files with the python client but the files are never processed as files but are treated as a list of strings

    "/uploadImages" : {
      "post" : {
        "tags" : [ "specific_alarm" ],
        "summary" : "uploads images of cars",
        "description" : "",
        "operationId" : "uploadMultipleFiles",
        "consumes" : [ "multipart/form-data" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "files",
          "in" : "formData",
          "description" : "file detail",
          "required" : true,
          "type" : "array",
          "items" : {
            "type" : "file"
          },
          "collectionFormat" : "multi"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation"
          }
        }
      }
    }

This gives the following error 

    'list' does not have the buffer interface

**Comment by wing328** [comment]
@scottrw93 I saw the commit f5b18f0 so I believe you're already working on a fix?

I think other API clients have similar issue and we'll check on those.

**Comment by scottrw93** [comment]
Yes, I'm not sure when I'll get a chance to finish but hopefully at the weekend.
