### ISSUE TITLE
additionalProperties issue in python code generation

### ISSUE THREAD

**Issue by mtngld** [swagger-api/swagger-codegen#2037]
Assume the following definition in a swagger.yaml file:

```yaml
definitions:
  definition1:
    type: object
    properties:
      prop1:
        type: string
      prop2:
        type: integer
      prop3:
        type: object
        additionalProperties:
          $ref: '#/definitions/definition2'
   
  defintion2:
    type: object
    properties:
       foo:
          type: string
       bar:
          type: string
```

I had issues with the `to_dict` method of `defenition1`,

solved by adding another test in the `to_dict` as follows:
```python
def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}
        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
           # *fix start*
            if isinstance(value, dict):
                result[attr] = dict(map(
                    lambda (k,v): (k, v.to_dict()), value.iteritems()))
           # *fix end*
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value
```

Not sure how to modify the code generator to create this, or if there is any other way to solve that

**Comment by wing328** [comment]
@mtngld thanks for reporting the issue and proposing the fix.

You probably need to update the Python model mustache template: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/model.mustache#L85

Then run `mvn clean && ./bin/python-petstore.sh` to update the Petstore sample.

Guidelines for contribution: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md
