### ISSUE TITLE
support java8

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#205]
the current assembly task fails with java 8, see #204

**Comment by billumina** [comment]
@fehguy when is v2.1.0-M1 expected to be released? java 8 support would be great. thanks!

**Comment by fehguy** [comment]
Probably in the next week or so.  We just got 1.5.0-M1 of swagger core out the door (announcement coming soon) which was a prerequisite to codegen getting a milestone release.

**Comment by fehguy** [comment]
codegen is fully java 8 compatible now

**Comment by FossiFoo** [comment]
Do you plan on supporting the native "java.time" LocalDate & LocalTime in generated clients? At the moment i'm overwriting the importMappings in a custom CodeGen, but that doesn't feel so nice.

**Comment by x2b** [comment]
@fehguy I would much appreciate that as well...
