### ISSUE TITLE
[java] Generating AndroidManifest.xml for java client

### ISSUE THREAD

**Issue by sbelan** [swagger-api/swagger-codegen#2050]
Hi,
I have moved my project from swagger codegen version 2.1.4 to 2.1.5. After generating java client swagger generating AndroidManifest.xml under src/main folder which is not require for java. Also in previous version it was not getting generates for java client

**Comment by wing328** [comment]
Yes, you will also find `build.gradle` as well for building the library using Gradle. Since Java API client can also be used in the Android environment so we generate build files (pom, gradle, etc) and developers can pick the right one for their development environment.

**Comment by sbelan** [comment]
@wing328 .. Fine... Thanks

**Comment by tudor-stanciu** [comment]
any config arguments that we could use in order not to generate the additional files (quite annoying to generate something than remove most of it)
