### ISSUE TITLE
Template Repo

### ISSUE THREAD

**Issue by jhitchcock** [swagger-api/swagger-codegen#2051]
I have quite a lot of handy documentation style templates. 

Where is a good place to put them (Pull request) since they all use the static HTML generator. 

Is there a template repo anywhere?

**Comment by wing328** [comment]
@jhitchcock thanks for contributing the templates.

What about putting them in a new folder (e.g. templates) under https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/htmlDocs?

**Comment by jhitchcock** [comment]
Will do. I'll tidy them up over the weekend and get them in sometime next week, thanks

**Comment by wing328** [comment]
@jhitchcock if you need help from the community in organizing the templates, please let us know.

**Comment by jhitchcock** [comment]
Hey! Sorry had a break in Contract, back now. Working on these again, I'll get them sorted soon and do a PR

**Comment by wing328** [comment]
@jhitchcock np. Let us know if you need any help.

**Comment by jhitchcock** [comment]
Sneak Preview, just trying to make sure the code samples generate correctly. I'll be creating a seperate generator for this one. 

![docs](https://cloud.githubusercontent.com/assets/965054/17057023/c2f62f68-5017-11e6-93e0-a81f8ea39837.png)

**Comment by jhitchcock** [comment]
I'll open a new thread or a PR for the actual documentation, as I could do with a bit of help / feedback / discussion :)

**Comment by jhitchcock** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3447
