### ISSUE TITLE
Add templated supporting files by config

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#2068]
It would be great to be able to add custom supporting files by config when using an alternate template dir
Eg.

``` json
{
  "additionalSupportingFiles": {
    "myCustomClass.mustache": "src/main/java/com/company/myapp/myCustomClass.java"
 }
}
```

**Comment by sbelan** [comment]
@cbornet ... I have raised issue #2047. Are  you suggesting the same? 
We are using config and for alternate template path we required to extend DefaultCodeGenerator.

**Comment by wing328** [comment]
@cbornet do you mind sharing with me a bit more about your use case of adding additional files to be used by Codegen? Currently do you have any workaround for this limitation?

**Comment by cbornet** [comment]
Of course. For instance I use a template to adapt the feign generator to Spring-Boot, generating automatically some beans for the apiclient and the apis that the user can then inject wherever he wants with Spring DI.
With the current implementation, I cannot create new files so I have to put everything in ApiClient with nested classes. It would be easier and make the code more readable if I could create more classes.

**Comment by cbornet** [comment]
[Here](https://github.com/cbornet/generator-jhipster-swagger-cli/blob/master/generators/app/templates/swagger-codegen/libraries/feign/ApiClient.mustache) is my templated ApiClient for reference.

**Comment by Keyrat06** [comment]
Has this feature been added? This would be very useful!

**Comment by wing328** [comment]
PR: https://github.com/swagger-api/swagger-codegen/pull/6487/files
