### ISSUE TITLE
[Swift] names containing - ( mathematical symbols )

### ISSUE THREAD

**Issue by Glagnar** [swagger-api/swagger-codegen#2084]
The SWIFT code generator generates variable names with a minus in it. This is not allowed in SWIFT

**Comment by Glagnar** [comment]
The C# generator does better:
        `[DataMember(Name="Association-Link", EmitDefaultValue=false)]`
        `public string AssociationLink { get; set; }`

versus
`    public var Association-Link: String?`

**Comment by fehguy** [comment]
There are two things here-- first, variables need to have a "friendly name" which is escaped for the language being used.  There should be no hyphens in a variable name.

Next, a model property or parameter in JSON _can_ have special characters in it.

The templates have `{{paramName}}` for safe names and `{{baseName}}` for _actual_ names.  There are overrides in the java class which is used to correctly make the `paramName` safe.

You can verify this in the `SwiftCodegen.java` class and override the `String toParamName(String name)` method to make it safe.

**Comment by wing328** [comment]
@Glagnar thanks for reporting the issue.

Do you know what naming convention does Swift variable name follow? 
- camelCase
- PascalCase
- snake_case

Here is how C# handles the parameter naming: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java#L319

**Comment by Glagnar** [comment]
@wing328 the swift documentation uses camelCase:
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html

**Comment by wing328** [comment]
@Glagnar thanks. Do you have you cycle to contribute a fix for that?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by Glagnar** [comment]
I will have a look. There is also an issue with parameter naming:
`public class func featureOfInterestsGet($orderby $orderby: String?, $top: Int?, $skip: Int?, $filter: Int?) ->`
The $ is not supported.

**Comment by wing328** [comment]
You can leverage `sanitize` to clean up the parameter name before converting to camelCase. e.g.

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java#L325

**Comment by wing328** [comment]
@Glagnar there are several PRs related to Swift merged into master. Please pull the latest and rebase.

**Comment by Glagnar** [comment]
@wing328 thank you. The issues were not solved by these changes, but I have a solution ready that I am testing.

**Comment by wing328** [comment]
@Glagnar yes, those PRs do not address the issue you reported. The reason I would like you to rebase on the latest master is that one of the PRs added unit testing to the Swift Petstore API so you can leverage it to ensure your change passes all the unit tests.

**Comment by wing328** [comment]
@Glagnar let us know if you need help with the fix.

**Comment by wing328** [comment]
@Glagnar if you're too busy, the community can help submit a fix for this. Let us know.

**Comment by Glagnar** [comment]
@wing328 Thanks. Last week was holidays in Denmark, and this week I am attending meetings abroad. I dont have time to implement it before next week.

**Comment by wing328** [comment]
@Glagnar  Hope you'd a wonderful holidays in Denmark. Please take your time as I don't think anyone else is facing the same issue.

**Comment by Glagnar** [comment]
@wing328 I might be doing this wrong, but I dont seem to be able to push a fix for this issue:
`thomas@gLap:~/code/swagger-codegen$ git push origin issue-2084
remote: Permission to swagger-api/swagger-codegen.git denied to Glagnar.
fatal: unable to access 'https://github.com/swagger-api/swagger-codegen.git/': The requested URL returned error: 403
`

**Comment by wing328** [comment]
@Glagnar you need to do it in your folked `swagger-codegen` repo by first clicking on the "folk" button in https://github.com/swagger-api/swagger-codegen

**Comment by Glagnar** [comment]
@wing328 Thanks. This is the first time I contribute anything to github. :]

**Comment by wing328** [comment]
@Glagnar no problem. I hope you enjoy the process and thanks for your contribution.

**Comment by wing328** [comment]
Fixed with https://github.com/swagger-api/swagger-codegen/pull/2262
