### ISSUE TITLE
javascript client bug in ApiClient.js

### ISSUE THREAD

**Issue by deefactorial** [swagger-api/swagger-codegen#2091]
The code generated by the javascript client has errors. 

In my [yaml file](https://github.com/deefactorial/openmoney-api/blob/master/api/swagger/swagger.json#L2517) I have a reference to a `modification` 

the error I get is:
```
/home/deefactorial/development/js/giftcard/node_modules/pipeworks/pipeworks.js:204
      throw err; // rethrow
      ^

TypeError: Cannot read property 'map' of undefined
    at Function.convertToType (/home/deefactorial/development/js/openmoney-api-client/javascript-client/src/ApiClient.js:256:22)
    at StewardsGet.self.constructFromObject (/home/deefactorial/development/js/openmoney-api-client/javascript-client/src/model/StewardsGet.js:89:41)
```

it's trying to access the map function from the data, but data is undefined. the solution I coded manually was to check if data is undefined first.

**Comment by wing328** [comment]
There are many enhancements (by @delenius) to the Javascript API client. Please pull the latest master and let us know if you're still seeing the same error.

**Comment by wing328** [comment]
@deefactorial closing this as there's no update from you. Please reopen if you still encounter issue with the JS API client generated by the latest master of Swagger Codegen.
