### ISSUE TITLE
mark 'findMethodResponse' method in DefaultCodegen.java as 'protected' to make it possible to override for handling custom response codes

### ISSUE THREAD

**Issue by neoasket** [swagger-api/swagger-codegen#2094]
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L1181

**Comment by wing328** [comment]
@neoasket the suggestion definitely sounds reasonable to me but can also elaborate a bit how you would like to handle custom response codes?

**Comment by neoasket** [comment]
@wing328,
our API endpoints produces error codes which start with "2" as an HTTP response
yeah, I know, looks strange but this is what we live with (:
and in this case codegen produces incorrect return type

**Comment by wing328** [comment]
@neoasket do you mind submitting a PR for the change? We'll then review.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md
