### ISSUE TITLE
[Swift] missed char escaping for operationId, resulted in syntax error against generated method name

### ISSUE THREAD

**Issue by hideya** [swagger-api/swagger-codegen#2095]
In our usage, `operationId` can contain characters like `.`, `{`, `}`.  My understanding is that there is no restrictions against kind of characters used in `operationId`, and when to use `operationId` to generate some part of the code, special characters should be escaped/removed by the codegen to avoid syntax errors.

In Swift codegen, `operationId` seems used to generate the method name and special characters there are not removed, which results in compilation error.  e.g. in one of our use cases, we see a generated method name like `public class func user.existsGetUsers{id}Exists(id id: String) -> ... ` for API with `perationId: 'User.exists__get_Users_{id}_exists'`

BTW, Obj-C codegen generates `-(NSNumber*) userExistsGetUsersidExistsWithCompletionBlock :...` for the same API. The method name is not ideal but the special characters are removed and the generated code doesn't break the build. I'd expect Swift codegen does the same treatment.  Would it be reasonable assumption?

This issue is found with a pull as of 3ba4cd1
(@bajtos wanted to keep informed about this too)

**Comment by wing328** [comment]
@hideya yes, agree that the `operationId` should be sanitized to remove special/illegal characters. 

Do you have cycle to contribute a fix?

Here is how Objc cleans up the `operationId`: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java#L425

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by hideya** [comment]
@wing328 thanks for getting back to me quickly again.  Sure, I'll work on it :-)

**Comment by hideya** [comment]
@wing328 could I ask you a beginner's question for fixing code in this project?  I updated `SwiftCodegen.java` and did `mvn package`, which compiled the source and updated the jar file.  But when I performed `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ... -l swift -o ...` after that, the updated code doesn't seem to get executed (the original one without my mod seems executed).  Would you kindly point me what I'm possibly doing wrong...?

**Comment by wing328** [comment]
Have you tried `mvn clean package` instead ?

**Comment by hideya** [comment]
Thanks, it worked!  I was too careless...  I've confirmed that I fixed the issue.  I'll submit a PR soon.
