### ISSUE TITLE
String type parameters with "uuid" as format generate incorrect code

### ISSUE THREAD

**Issue by ayuda-yves** [swagger-api/swagger-codegen#2099]
If the parameter or return type of a method is of type "string" and format "uuid", the generated code uses a fictitious "UUID" type instead of "Guid".

Example:
```
return new ApiResponse<UUID>(statusCode,
    response.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
    (UUID) Configuration.ApiClient.Deserialize(response, typeof(UUID)));
```

(Copy paste from Java code generation maybe?)

**Comment by wing328** [comment]
I filed #2123 to add the mapping between `uuid` and `Guid` in C# codegen.

**Comment by wing328** [comment]
PR merged into master. Please pull the latest and give it a try.

**Comment by ayuda-yves** [comment]
I use the online editor and it still generates code using "UUID". I'm assuming the editor hasn't been updated yet. Will test again later.

**Comment by ayuda-yves** [comment]
The online editor has been updated. I can finally confirm that this now works correctly. :)

**Comment by wing328** [comment]
@ayuda-yves thanks for the confirmation

**Comment by skondratov** [comment]
This problem still actual for CsharpDotNet2 generator.

**Comment by wing328** [comment]
@skondratov what about `csharp` generator? 

If C# client does not have similar issue, we can port the fix to `CsharpDotNet2` generator

**Comment by skondratov** [comment]
@wing328 `csharp` generator does not introduce properties with type UUID for my swagger config, `CsharpDotNet2`  generator does.

> we can port the fix to CsharpDotNet2
I did not review fix, but result certainly should be same: Guid instead of UUID 

https://msdn.microsoft.com/en-us/library/system.guid.aspx
> .NET Framework 
> Available since **1.1**

**Comment by wing328** [comment]
C# generator already has the correct type mapping for `uuid`: https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java#L136

Are you using the latest master when testing the C# generator?

**Comment by wing328** [comment]
(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Comment by wing328** [comment]
@skondratov can you also share the spec so that we can review to ensure it's defining the property in `uuid` correctly?

**Comment by skondratov** [comment]
I use [swagger-codegen-cli-2.2.1.jar](https://oss.sonatype.org/content/repositories/releases/io/swagger/swagger-codegen-cli/2.2.1/swagger-codegen-cli-2.2.1.jar), took it here: http://swagger.io/docs/#swagger-codegen-documentation-9

btw: Just checked 2.3.0 -- same result.

> can you also share the spec

I prepared example for you:
https://gist.github.com/skondratov/c324b3cfde8ee98e27a03d2c5a3f804f/revisions

I took standard example from http://editor.swagger.io -- default.yaml and changed the only string. You can see it in diff. Then i generated `csharp` and `CsharpDotNet2` projects using editor.swagger.io. And then compared: `src\main\CsharpDotNet2\IO\Swagger\Model\Activity.cs` and `src\IO.Swagger\Model\Activity.cs`

Result:
 `public UUID Uuid { get; set; }` vs `public Guid? Uuid { get; set; }`

**Comment by skondratov** [comment]
> please consider adding your company name to this list

Prepared PR: https://github.com/swagger-api/swagger-codegen/pull/4343

**Comment by skondratov** [comment]
@wing328 btw: CsharpDotNet2 does not extend AbstractCSharpCodegen

**Comment by wing328** [comment]
> @wing328 btw: CsharpDotNet2 does not extend AbstractCSharpCodegen

Yes, I'm aware of that. I'll try to port the fix later today. Will keep you posted.

**Comment by wing328** [comment]
Filed #4347 to fix it.

The test result using the gist you provided looks good:
```
        List<Product> EstimatesTimeGet (double? startLatitude, double? startLongitude, Guid? customerUuid, string productId);
```

**Comment by wing328** [comment]
@skondratov PR merged into master. Please pull the latest master to give it a try.

Currently, C# 2.0 API client does not come with auto-generated documentation and code sample. If we add those, would you have time to review?

**Comment by skondratov** [comment]
@wing328, sure.

**Comment by wing328** [comment]
@skondratov I've filed https://github.com/swagger-api/swagger-codegen/pull/4354 to add auto-generated documentation for C# 2.0 client. Here is the README for Petstore: https://github.com/swagger-api/swagger-codegen/blob/6f65209b3559d52694c605225bd6b2b387ed789a/samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient/README.md

Please help review the readme (installation, getting started, etc) and code samples in the API documentation. Thanks!

**Comment by wing328** [comment]
@skondratov I'll merged the enhancement into master as beta release so that we can collect feedback from other C# 2.0 users as well.
