### ISSUE TITLE
[JavaScript] Strange enum generation

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#2101]
It seems that the generation of enums in the JS client generator is a bit odd. Currently, I get something like (omitting comments):

```javascript
var AccountTypeEnum = function AccountTypeEnum() {
  var self = this;
  self.PAIDACCOUNT = "paidAccount",
  self.FREEACCOUNT = "freeAccount"
}
```

This is a class, where each instance has its own copy of the fields `PAIDACCOUNT` and `FREEACCOUNT`. To use this, you would currently have to do:

```javascript
var myAccountType = new AccountTypeEnum();
doSomething(myAccountType.PAIDACCOUNT);
```

This is a strange way to encode enums.
 
I propose that we change it to just an object,

```javascript
var AccountTypeEnum = {
  PAIDACCOUNT: "paidAccount",
  FREEACCOUNT: "freeAccount"
}
```

The usage would then be

```javascript
doSomething(AccountTypeEnum.PAIDACCOUNT);
```

If the powers that be agree, I can file a PR.

**Comment by wing328** [comment]
@delenius agree that your approach is better as there's no need to crete a new object in order to use the enum values.

**Comment by delenius** [comment]
Ok. And just to double-check, these enums aren't actually used anywhere currently, right?

**Comment by wing328** [comment]
PR  merged. I don't think it's used. There's no test case I'm aware of for any models in Petstore sample.

We would appreciate if you can add a few test cases for Pet model
- to test enum ["status"](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L1009)
- to test `constructFromObject`
