### ISSUE TITLE
[JavaScript] Bug in handling of optional fields in models

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#2103]
(I already filed PR https://github.com/swagger-api/swagger-codegen/pull/2087 for this issue)

In the `constructFromObject` methods, we are always setting all the
parameters, including optional ones that are missing in the data
object. Because of the `convertToType` calls, this has the effect
of producing the *strings* `"undefined"` or `"null"` as property
values on the constructed object! This obviously leads to difficult
bugs.

This commit makes sure that we first check that the data field
exists in the `data` object. Note that both `null` and `undefined`
values will be skipped.

There are some additional related problems, but I will wait for this to be resolved first.

**Comment by fehguy** [comment]
:+1: Thanks for all the work on this @delenius

**Comment by dbousamra** [comment]
This still seems broken (or a variation at least). When a value is defined as not required in a swagger spec, the convertToType method still tries to parse null and undefined, resulting in nulls parsed as types (i.e. string being 'null' and numbers being NaN.

Can anyone confirm?

**Comment by wangzw** [comment]
@dbousamra I got the same issue as you and file a PR to fix the issue. #4932

**Comment by wing328** [comment]
@dbousamra we've merged the fix by @wangzw into master. Please pull the latest to give it a try.

**Comment by dbousamra** [comment]
Thanks all

**Comment by wing328** [comment]
No problem (If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
