### ISSUE TITLE
add an ignore file for codegen

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#2105]
From #1956, adding a .codegen-ignore file would be helpful for keeping languages from overwriting files unexpectedly.

**Comment by jimschubert** [comment]
I've begun development on this. https://github.com/jimschubert/swagger-codegen/tree/feature/codegen-ignore

**Comment by wing328** [comment]
Thanks for the contribution from @jimschubert to add the support of `.swagger-codegen-ignore` file to skip file overwrite
