### ISSUE TITLE
Java/pojo.mustache generates incorrect equals when class has an internal field that is the same as the classVarName of the class

### ISSUE THREAD

**Issue by vivin** [swagger-api/swagger-codegen#2117]
This is kind of an edge case. A simple example:

Assume we have the following class that has been exposed through the swagger model:
```java
public class Name {

    private String name;

    ...
}
```

The autogenerated code `Name#equals(Object)` ends up having this:

```java
return true && Objects.equals(name, name.name);
```

The fix is quite simple; we just need to prefix the properties with `this`. So the template should be:

```hbs
return true {{#hasVars}}&& {{#vars}}Objects.equals(this.{{name}}, {{classVarName}}.{{name}}){{#hasMore}} &&
        {{/hasMore}}{{/vars}}{{/hasVars}}
```

I can submit a PR for this fix, if that's alright.

**Comment by wing328** [comment]
@vivin the proposed fix looks good to me. Let me know if you need help submitting a PR.

https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
FYI. C# is already using the fix you proposed: 

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/model.mustache#L88

**Comment by vivin** [comment]
Awesome! I will try submitting a PR today or possibly during the weekend.

**Comment by wing328** [comment]
@vivin thanks! Let us know if you need any help.
