### ISSUE TITLE
JMeter API ignores basePath in service URL

### ISSUE THREAD

**Issue by foragerr** [swagger-api/swagger-codegen#2118]
Spec: https://gist.github.com/foragerr/1daf27b05abab842d197
codegen version: 2.1.5
Language: JMeter

As the title says, basePath should be added to the URL, but is completely dropped by JMeter codegen.

**Comment by wing328** [comment]
@foragerr thanks for reporting the issue.

May I know if you've cycle to to contribute a fix?

Here are some good starting points:

JMeter template: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/JMeter

Java template: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/Java

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md
