### ISSUE TITLE
[Swift] simplifications for the API method usage?

### ISSUE THREAD

**Issue by hideya** [swagger-api/swagger-codegen#2120]
All the generated APIs return `RequestBuilder<T>` for further process.  I'm wondering what is the motivation for this, which requires extra typing?

I'm wondering why the usage couldn't just be simple like the following (something equivalent to Obj-C version)?
```swift
        CoffeeShopClientAPI.CoffeeShopAPI.coffeeShopCreate(data: coffeeShop) {
            output, error in
            // `output` holds the returned model as an instance of CoffeeShop
            ...
        }
```
instead of:
```swift
        CoffeeShopClientAPI.CoffeeShopAPI.coffeeShopCreate(data: coffeeShop).execute {
            response, error in
            let coffeeShop = response!.body
            ...
        }
```
Could someone share thoughts on this?  (@bajtos wanted to keep informed about this too)

**Comment by wing328** [comment]
@hideya I don't think I've an answer on this.

My guess is that the current approach allows the developers to obtain the response's status code and headers (in addition to the body)

**Comment by hideya** [comment]
@wing328  thanks for getting back to me.  Are those flexibilities (obtaining the response's status code and headers) supported for other languages?  If such flexibilities are required, I thought the ObjC code generation should also support it too.  Otherwise, Swift side could be simplified as mentioned above.  What would you think?

**Comment by wing328** [comment]
I would love to add the feature to ObjC code. Time and resource are always the constraints for me.

If you look at C# API client, you will find that we've introduced another method `{{operationId}}WithHttpInfo`, which returns an Object (ApiResponse) containing the status code, HTTP header, deserialized body of the HTTP response.

`{{operationId}}` simply calls `{{operationId}}WithHttpInfo` and returns the deserialized body. e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient/src/main/csharp/IO/Swagger/Api/PetApi.cs#L1178

If you've time, please implement something similar for Swift (and ideally ObjC as well) to make the API clients more consistent across different langauges.

**Comment by hideya** [comment]
@wing328 thanks for the reply and the info.  That approach makes sense.  This feature seems to require a bit of time to implement.  Please let me see if I can spare time and get back to you when I figured I can.

**Comment by Edubits** [comment]
One of the reasons for this is indeed having access to HTTP status and headers. In my use case this is for example needed to handle errors properly (some info is provided in headers). Having separate calls for with- and without this would make sense, the simpler it's to use, the better.

**Comment by hideya** [comment]
@Edubits thanks for the comment back.  Sounds good!  
@wing328 I'm working on a PR for this change.  I'll finalize it in a few hours.

**Comment by wing328** [comment]
@hideya thank you for your contribution. I'm sure the Swift developers would appreciate your effort.
