### ISSUE TITLE
[ObjC] generated method name's `WithCompletionBlock` postfix doesn't follow convention?

### ISSUE THREAD

**Issue by hideya** [swagger-api/swagger-codegen#2121]
API methods for Obj-C always seems to have `WithCompletionBlock` postfix, which doesn't follow the coding convention.  For example, I think the following generated method:
```objc
-(NSNumber*) userConfirmWithCompletionBlock :(NSString*) uid 
     token:(NSString*) token 
     redirect:(NSString*) redirect 
    completionHandler: (void (^)(NSError* error))completionBlock;
```
should have been like the following:
```objc
-(NSNumber*) userConfirmWithUid :(NSString*) uid 
     token:(NSString*) token 
     redirect:(NSString*) redirect 
    completionHandler: (void (^)(NSError* error))completionBlock;
```
FYI, the yaml for this method is:
```yaml
  /Users/confirm:
    get:
      tags:
        - User
      summary: Confirm a user registration with email verification token.
      description: !<tag:yaml.org,2002:js/undefined> ''
      operationId: User.confirm
      parameters:
        - name: uid
          in: query
          description: !<tag:yaml.org,2002:js/undefined> ''
          required: true
          type: string
        - name: token
          in: query
          description: !<tag:yaml.org,2002:js/undefined> ''
          required: true
          type: string
        - name: redirect
          in: query
          description: !<tag:yaml.org,2002:js/undefined> ''
          required: false
          type: string
      responses:
        '204':
          description: Request was successful
          schema: !<tag:yaml.org,2002:js/undefined> ''
      deprecated: false
```
This is as of b54947d (the current latest) (@bajtos wanted to keep informed about this too)

**Comment by wing328** [comment]
@hideya do you mean the postfix (WithCompletionBlock) is causing compiling error?

**Comment by hideya** [comment]
@wing328 no, this is an improvement request, as e.g. `userConfirmWithCompletionBlock` doesn't follow Obj-C method naming convention.

**Comment by wing328** [comment]
I see. For the naming convention, do you have the URL to the style guide for our reference?

**Comment by hideya** [comment]
Sure.  [Apple's Guide to Naming Methods](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF) says that:

> Make the word before the argument describe the argument.
- (id)viewWithTag:(NSInteger)aTag; -- Right.
- (id)taggedView:(int)aTag; -- Wrong.

**Comment by wing328** [comment]
Thanks for the URL. Using the example `User.confirm` you provide, you suggest naming it as `userConfirmWithUid` where `uid` is the first argument (in Pascal case).

The easiest fix I can think of is to rename `operationId` to `userConfirmWithUid` but of course the side effect that other API client would use the same method name (assuming API client in other langauges is used)

To fix it just for ObjC, one needs to customize the ObjC generator to provide another mustache tag (e.g. `firstParameter`), which stores the name of the 1st method argument in Pascal case. This can be done in `Map<String, Object> postProcessOperations(Map<String, Object> objs)`

**Comment by hideya** [comment]
Thanks for the explanation.  Yeah, I'd like to have it fixed just for ObjC.
Would you willing to take the change if I worked on a PR for it? (although it is a compatibility breaking change in terms of ObjC client SDKs people already have generated...)

**Comment by wing328** [comment]
I don't mind. To me it's ok to make this breaking change (non-backward compatible) as your suggestion is better in terms of conforming to Apple's guidelines in naming method.

Later we can include this in the release note or migration guide to make sure developers are informed of this breaking change when they upgrade to the next stable release.

**Comment by hideya** [comment]
Thanks!  I'll work on it then!
