### ISSUE TITLE
Generated XxxServiceApi add and update methods pass null data to callback

### ISSUE THREAD

**Issue by demonfiddler** [swagger-api/swagger-codegen#2124]
The generated JavaScript addYyy(yyy, cb), updateYyy(yyy, cb), updateYyyWithForm(..., cb) methods all set returnType = null when invoking ApiClient.callApi(...), even in cases where the newly created or updated object is returned in the response body.. The consequence is that the callback receives data = null. This is undesirable, since the service may have applied various business rules during the creation or update process. This could result in the client's copy of the object (as sent with the add or update request) being out of date with respect to the response body. The client may need to refresh its UI and the obvious way to do that is from the returned data. Or am I missing something?

The lack of a data parameter to add and update callbcks is readily demonstrable in the Pet Store example: SwaggerPetstore.PetApi.addPet() and SwaggerPetstore.PetApi.updatePet() at lines 88 and 51 respectively of the generated src/api/PetApi.js.

I've tried to attach a zipped sample Maven/Eclipse project illustrating the issue, but DNDing the ZIP to this window results in the message "Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."... huh?

**Comment by wing328** [comment]
Which generator are you referring to? Java? Python?

Can you also share the swagger spec so that we can use it to repeat the issue?

**Comment by demonfiddler** [comment]
@wing328 my apologies. I'd intended to attach the 'Client: JavaScript' label, discovered I couldn't, then got distracted. Anyhow, I've updated the description above to make it clear. I can e-mail you the ZIP that I was unable to attach, if that would help.

**Comment by wing328** [comment]
No worry. Are you using the latest master? Recently, there's been a lot of enhancements to the Javascript API client so I would suggest you to try the latest if you've not done so.

**Comment by demonfiddler** [comment]
Yep, I'm using 2.1.6-SNAPSHOT locally built from GitHub MASTER HEAD.

**Comment by wing328** [comment]
@demonfiddler I believe this issue can be closed. Please reply to let me know if that's not the case.

**Comment by demonfiddler** [comment]
@wing328 my apologies for not having responded sooner - I missed the original the notification amidst a blizzard of personal e-mails. I've just looked over the code and it seems to be doing the right thing.
