### ISSUE TITLE
Support `@property` property names in JSON Schema

### ISSUE THREAD

**Issue by highsource** [swagger-api/swagger-codegen#2130]
One of the widespread conventions is using `@` to denote "attribute" properties. This often appears in cases where XML is converted to JSON.

Right now, Swagger Codegen would generate `property` for `@property`.

It would be better to consider this use case and generate something like `attributeProperty` in this case.

**Comment by fehguy** [comment]
For which language?  Can you share more details?

**Comment by highsource** [comment]
Sure. This also relates to #2131.

Here's the specification I'm compiling:

https://github.com/highsource/lhapi-specification/blob/master/lhapi-specification.yaml#L291-L300

This is a spec for the Lufthansa API (countries, airports, departures/arrivals etc.):

https://developer.lufthansa.com/docs/read/api_details/reference_data/Countries

The problematic part is the `Name` type:

```
  Name:
    type: object
    required:
      - '@LanguageCode'
      - '$'
    properties:
      '@LanguageCode':
          type: string
      '$':
          type: string
```

Which is most probably migrated from the XML Schema. Here's the XML representation:

```
<Name LanguageCode="de">Deutschland</Name>
```

I'm compiling this spec into a Java client, here's my project:

https://github.com/highsource/lhapi-client

What I get with Swagger Codegen 2.1.5 is this:

```
  private String languageCode = null;
  private String  = null;

  
  /**
   **/
  
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("@LanguageCode")
  public String getLanguageCode() {
    return languageCode;
  }
  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }

  
  /**
   **/
  
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("$")
  public String get() {
    return ;
  }
  public void set(String ) {
    this. = ;
  }
```

This happens because of the [sanitizeName](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2211):

```
       // remove everything else other than word, number and _
        // $php_variable => php_variable
        return name.replaceAll("[^a-zA-Z0-9_]", "");
```

I've added this as a temporal fix:

```
        name = name.replaceAll("^[$]$", "value");
        name = name.replaceAll("^@", "attribute");
```

Hope this helps.

**Comment by wing328** [comment]
I think it's essential to understand what your backend (server) expects. Does it expect to receive the following from the API clients?
```
{
  "@LanguageCode": "something",
  "$": "blahblahblah"
}
```

**Comment by highsource** [comment]
Hi @wing328,

it's the other way round, I'm generating the client for the existing API, so the question is not what the server expects to receive but what it sends.

And indeed it sends JSON as you quoted:

```
{"@LanguageCode":"de","$":"Gordon Downs"}
```

My problem is that Swagger Codegen simply strips `@` and `$` when generating Java client. So  `@LanguageCode` becomes `LanguageCode` (which isn't that bad), but `$` becomes empty, which is bad.

At the moment I've added this to the `DefaultCodegen`:

```
        name = name.replaceAll("^[$]$", "value");
        name = name.replaceAll("^@", "attribute");
```

This generates `attributeLanguageCode` and `value` which is fine now.

**Comment by wing328** [comment]
I found `@JsonProperty("@LanguageCode")` in the code you provided above. Does it not map the JSON key name properly to "@LanguageCode"?

**Comment by highsource** [comment]
@wing328 Yes, it does.

The problem is not the `@JsonProperty`, the problem is the generated Java property:

```
  private String languageCode = null;
  private String  = null;


  /**
   **/

  @ApiModelProperty(required = true, value = "")
  @JsonProperty("@LanguageCode")
  public String getLanguageCode() {
    return languageCode;
  }
  public void setLanguageCode(String languageCode) {
    this.languageCode = languageCode;
  }


  /**
   **/

  @ApiModelProperty(required = true, value = "")
  @JsonProperty("$")
  public String get() {
    return ;
  }
  public void set(String ) {
    this. = ;
  }
```

I get the Java bean property `languageCode`, the `@` gets lost. It'd be better to get `attributeLanguageCode` or something like that to keep the `@` semantics.

But `@` is a minor issue here, purely cosmetic. I'd be ok with `wontfix`.

The big problem is `$` (see #2131).

**Comment by wing328** [comment]
Agree that $ can be mapped to something else to resolve the compile error.

in your case, what exactly is "$"? Is that a "name"?

**Comment by wing328** [comment]
I don't get your point about replacing `@languageCode` with `attributeLangaugeCode` or keeping it as it's with the `@` sign.

**Comment by highsource** [comment]
`$` is a `value`.

Basically

`"Name":{"@LanguageCode":"de","$":"Gordon Downs"}`

is a replacement for XML:

```
<Name LanguageCode="de">Gordon Downs</Name>
```

So `value` would be a good replacement for `$`.

> I don't get your point about replacing @languageCode with attributeLangaugeCode or keeping it as it's with the @ sign.

I'd just prefer `getAttributeLanguageCode` instead of `getLanguageCode` because `@` comes from "legacy" XML attribute. You can't keep it with `@` in Java since you'll get `get@LanguageCode` then which is invalid. Once again - it's about the name of the Java bean property, not the JSON property (which should of course stay as it is).

**Comment by wing328** [comment]
$ is now replaced with `value` but for @, we won't map it to `Attribute`

**Comment by highsource** [comment]
It's ok, this is not a problem for me.

**Comment by wing328** [comment]
Thank you for your understanding. Issue closed.
