### ISSUE TITLE
[Swift] generating Int32/Int64 when those are required in format

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2133]
Currently whatever is in format, int32 or int64, the code generated Int and not Int32 or Int64 while Swift has an exact mapping.

**Comment by wing328** [comment]
According to http://stackoverflow.com/a/27440158/677735 (which references the Swift doc), there's no need to be specified as int32/int64 is used based on platform.

**Comment by cjolif** [comment]
"there's no need to be specified as int32/int64 is used based on platform."

Yes, sure you don't have to in general. But then if you run on a 32  bits platform and you use Int for everything you will get 32 bits even when the Swagger requires 64 bits? So you might get into trouble?

**Comment by wing328** [comment]
You definitely have your point. To update the mapping, you can do it [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java#L104)

I also read [that](http://stackoverflow.com/questions/24048334/swift-errors-when-using-different-integer-sizes) casting is needed when dealing with Int32 and Int64.

What mapping would you propose for `integer` and `long`?

**Comment by cjolif** [comment]
in Swagger `integer` is 32 bits and `long` 64 bits right? So this would give `Int32` and `Int64` respectively I suppose?

**Comment by cjolif** [comment]
Or `Int` for `integer` as it is at least 32 bits. This would avoid casting in this case.

**Comment by kenjitayama** [comment]
I think fixing only the mapping for `long` is enough and best.
That's what the Swift doc mentioned before recommends.

The fix : https://github.com/kenjitayama/swagger-codegen/commit/adf63de76ceadf6a796da9ad6b07e763cc74fb78

**Comment by kenjitayama** [comment]
I made a PR from it : https://github.com/swagger-api/swagger-codegen/pull/2406 :)

**Comment by cjolif** [comment]
> I think fixing only the mapping for long is enough and best.

Meanwhile I had more thoughts about that on my side, and I must admit I lead the other direction. By not fixing it for int32 you possibly let someone enter 64 bits while you actually only accept 32 bits in your server storage. 
I know Swift docs recommends using Int but really what they have in mind is not that data (un)marshalling use case. They probably thing about local variables (like loop index). In that case yes they say don't bother with bit-exact version. But when we are doing storage with (un)marshalling I think there is not much choice than sticking to exactly what we can deal with.

**Comment by wing328** [comment]
We can add a CLI option to set the mapping so as to meet different use cases/requirements.

**Comment by kenjitayama** [comment]
@cjolif I'm not sure I got your point, but now I have a feeling `Int32` should be used as well.

If `Int` is not fixed to `Int32`, and if a server sends back a 64bit integer by mistake (32bit in api spec), 64 bit client platforms would work fine, but 32 bit client platforms are in trouble.

For example, if a team building an iPhone app doesn't test using 32bit platform, this mistake could go by unnoticed. They could notice if `Int32` was used instead of `Int`.

**Comment by kenjitayama** [comment]
@wing328 
> We can add a CLI option to set the mapping so as to meet different use cases/requirements.

Yes, I am using `--type-mappings long=Int64` for now.

**Comment by cjolif** [comment]
> @cjolif I'm not sure I got your point, but now I have a feeling Int32 should be used as well.

Basically the same as  yours ;) So looks like we are inline that Int32 should be used.
