### ISSUE TITLE
[Java] Provide access to ApiClient.mapper to enable additional Serialization/Deserialization features

### ISSUE THREAD

**Issue by highsource** [swagger-api/swagger-codegen#2134]
I'm sung Swagger Codegen to generate a Java client for an existing API which I have no influence to.

In some cases, the API returns single items instead of arrays. For instance:

```
airportCode: [ "UFA", "FRA"]
```

Or:

```
airportCode: "UFA"
```

Jackson ObjectMapper can handle this situation if the `DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY` feature is enabled:

```
mapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
```

The `mapper` is initialized in the `ApiClient`:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache#L62-L68

I want to enable the said feature but I can't legally access the `mapper` of the `ApiClient`.

Please allow to access or provide the `ObjectMapper` from/to the `ApiClient`, for instance:

* Make the `mapper` field protected.
* Add public `getMapper` setter.
* Allow passing the mapper in a constructor.

**Comment by wing328** [comment]
@highsource thanks for the feedback. The suggestion sounds reasonable and we'll work on that.

**Comment by wing328** [comment]
@highsource PR merged into master. Please pull the latest and give it a try.

**Comment by highsource** [comment]
Will do. This one and #2131 were blocking me.

**Comment by wing328** [comment]
Just fixed that too. Please pull the latest.

**Comment by highsource** [comment]
Just checked both this one as well as #2131 #2184 - works as expected. Thank you very much.
