### ISSUE TITLE
[Java][Question]Object type enums

### ISSUE THREAD

**Issue by derekmok9201** [swagger-api/swagger-codegen#2139]
In Java, we are able to define enums like:

```java
public enum EnumWithDescription {
    ENUM_1("describing Enum1"),
    ENUM_2("describing Enum2")
    .... // + relevant constructor etc.
}
```

Is there any way to specify this in the swagger specification, and for the codegen to generate the enum definition accordingly? http://json-schema.org/latest/json-schema-validation.html#anchor76 says we can use anything in an enum array, however when using key-value pairs in the enum array, the codegen does not interpret it properly.

**Comment by wing328** [comment]
Sorry for late reply. Here is an example on how to define enum as an outer class:

https://github.com/swagger-api/swagger-codegen/pull/2508/files#diff-7e06e94c5a62e40662e5f3280a9bbc4bR1380

**Comment by derekmok9201** [comment]
Thankss!
