### ISSUE TITLE
Question: Is there a way to access request-example value from generated operations?

### ISSUE THREAD

**Issue by foragerr** [swagger-api/swagger-codegen#2145]
For instance, in the swagger pet shop example, how can I access the example for /pet POST?
See the example with yellow background here: http://i.imgur.com/2VUFE3l.png

I noticed that the **response** examples are available in `operations/operation/examples` but not request examples

**Comment by wing328** [comment]
For `example`, do you mean example for parameter (e.g. path, query, etc) in the request? or just the HTTP request body?

**Comment by foragerr** [comment]
request body. Basically the content contained in the Example Value box in the image I posted.

**Comment by wing328** [comment]
You can provide the example body using vendor extension, e.g. x-request-body, and then access it via {{vendorExtensions.x-request-body}} in the mustache template.

Is that what you're looking for?

**Comment by foragerr** [comment]
Are you suggesting I construct the content myself in the codegen class, and save it to the vendorExtension map?

Could you possibly point me to where I can grab the content from? Since it is displayed on swaggerUI, I'm assuming it is available someplace already. The petshop spec doesn't seem to contain it though.

**Comment by wing328** [comment]
I believe the example with yellow background in your image is constructed by swagger-ui.

**Comment by foragerr** [comment]
Guess this is a question for a different forum then. Thanks @wing328
