### ISSUE TITLE
how to generate yaml for java code.

### ISSUE THREAD

**Issue by imleihuang** [swagger-api/swagger-codegen#2147]
I have now a yaml file, I use this project to generate java code with Java 7. can anyone tell me, how can I use this project to generate?

I am new in this field, because I need more details..

Thanks.

**Comment by imleihuang** [comment]
I imported this project in eclipse, and built it with maven. as following: 

![unbenannt](https://cloud.githubusercontent.com/assets/14833088/13077246/d61fac8a-d4b7-11e5-808b-c5581ed8213d.PNG)

What is the next step to generate java code???

**Comment by wing328** [comment]
Here is a good starting point: https://github.com/swagger-api/swagger-codegen#to-generate-a-sample-client-library

**Comment by wing328** [comment]
Closing this as no update from you.
