### ISSUE TITLE
[csharp] Parameter names are not sanitized

### ISSUE THREAD

**Issue by ivanmartinvalle** [swagger-api/swagger-codegen#2151]
Language: C#
Version: Head of master as of February 16, 2016

Problem: The $skip parameter [(an OData parameter)](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/) is not escaped in C#, causing compiler errors. It is escaped in Java to be simply "skip". 

Minimal yaml to reproduce issue
```yaml
swagger: '2.0'
info:
  title: Example
  version: "1.0"
host: api.example.com
paths:
  /test:
    get:
      parameters:
        - name: $skip
          in: query
          required: false
          type: number
          format: int32
      responses:
        200:
          description: test response
```

**Comment by wing328** [comment]
@ivanmartinvalle thanks for reporting the issue, which has been fixed by #2154.

Please kindly pull the latest master and let us know if you're still seeing the issue.
