### ISSUE TITLE
NSDateFormatter FatalError on iOS Swift

### ISSUE THREAD

**Issue by CMasterson** [swagger-api/swagger-codegen#2159]
Setting the device to use 12-hour time format then trying to parse a 24-hour time from JSON causes the formatter to fail and the Models.swift initialize method to throw a FatalError.

Example time string: 2016-02-17T20:00:00.000+00:00

Setting the formatters locale fixes this issue:

`let formatter = NSDateFormatter() //Models.swift Line 106

formatter.locale = NSLocale(localeIdentifier:"en_US_POSIX") //Set the formatter locale

formatter.dateFormat = format

return formatter`

**Comment by wing328** [comment]
@CMasterson thanks for reporting the issue and suggesting a fix. Would you please file a PR so that we can review the change?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by CMasterson** [comment]
@wing328 The fix I suggested is in the generated code, I honestly have no idea where in the Swagger source code this would need to be implemented.

**Comment by wing328** [comment]
A good starting point is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/Models.mustache#L16

After making the change, please run the following to ensure all test cases passed:
```
mvn clean && ./bin/swift-petstore.sh
cd samples/client/petstore/swift/SwaggerClientTests
mvn integration-test
```
