### ISSUE TITLE
[Javascript] ApiClient.convertToType handles comparison to Object incorrectly

### ISSUE THREAD

**Issue by tkukola-db** [swagger-api/swagger-codegen#2165]
File ApiClient.js, method ApiClient.convertToType.

In the if/else ladder, type of Object ends up in the default case. The problem is that typeof Object is 'function', hence the Object takes the 'function' path inside the default, which leads to an exception.

I changed my local version of the ApiClient.converType's default to this:
        if (type === Object) {
          // for plain object type like: {'String': 'Integer'}
          var keyType, valueType;
          for (var k in type) {
            if (type.hasOwnProperty(k)) {
              keyType = k;
              valueType = type[k];
              break;
            }
          }
          var result = {};
          for (var k in data) {
            if (data.hasOwnProperty(k)) {
              var key = ApiClient.convertToType(k, keyType);
              var value = ApiClient.convertToType(data[k], valueType);
              result[key] = value;
            }
          }
          return result;
        } else if (typeof type === 'function') {
          // for model type like: User
          var model = type.constructFromObject(data);
          return model;
        } else if (Array.isArray(type)) {
          // for array type like: ['String']
          var itemType = type[0];
          return data.map(function(item) {
            return ApiClient.convertToType(item, itemType);
          });

**Comment by wing328** [comment]
@tkukola-db can I confirm with you that you're using the latest master to generate the JS API client? recently there's been a lot of enhancements to the JS API client.

**Comment by tkukola-db** [comment]
The version I'm using is from this morning (17th of Feb, 2016). Master branch, c4d799a4a7e47863437b22ee9b75c7d1828990e5

**Comment by xhh** [comment]
I tried but can't reproduce this issue. @tkukola-db could you provide a sample spec?

**Comment by tkukola-db** [comment]
Attached is the minimal API that seems to be able to generate the problem. The problem happens when my client gets a response from server and Swagger tries to construct the Dummy object based on the server response. The screenshot is from Chrome debugger when the exception fires. In the 'if' above the breakpointed line, you will see that the Object is of type function.

[api.txt](https://github.com/swagger-api/swagger-codegen/files/137093/api.txt)
![swagger_api_exception_chrome](https://cloud.githubusercontent.com/assets/15619214/13160788/7c95e42a-d64e-11e5-8d78-7068436d7fd0.png)

**Comment by xhh** [comment]
@tkukola-db Thanks, I can reproduce the issue with the spec you provided.
The reason I found is that the 3 nested models (foo, bar and baz) have no properties. As a result, no models are generated for them.

```json
    "Dummy": {
      "title": "Dummy",
      "type": "object",
      "description": "Dummy",
      "required": [
        "foo",
        "bar",
        "baz"
      ],
      "properties": {
        "foo": {
          "type": "object",
          "description": "Foo"
        },
        "bar": {
          "type": "object",
          "description": "Bar"
        },
        "baz": {
          "type": "object",
          "description": "Baz"
        }
      }
    }
```

If one of them, say "foo", has at least one property, then a `DummyFoo.js` model file will be generated and the `type` in the above screenshot will be `DummyFoo` instead of `Object`.

@tkukola-db what does your model look like? Can you provide an example of the JSON payload?

**Comment by tkukola-db** [comment]
In this case foo/bar/baz are expected to be objects of any form. The currently generated code produces Dummy, which seems to work just fine (foo/bar/baz get assigned and can be accessed) after changing the code that currently trips on Object being a function type.

If I declared Dummy as an object without any properties, then the resulting code would be a Dummy class with no functionality (which is not what I would expect).

**Comment by xhh** [comment]
Now that "objects of any form" (`object` type with no properties) are supported (see #2297), I will fix this.

**Comment by wing328** [comment]
@tkukola-db fix merged into master. Please pull the latest and let us know if you're still seeing the issue.
