### ISSUE TITLE
Missing vendorExtensions on RefProperty 

### ISSUE THREAD

**Issue by carlodonpromillo** [swagger-api/swagger-codegen#2172]
When parsing a RefProperty object which has vendorExtenstions defined in preprocessSwagger step, this vendor extensions are not accessible (via property.getVendorExtensions()). 
Example:
definitions:
  search_result:
    properties:
      query:
        $ref: '#/definitions/query'
        x-someString: value

**Comment by fehguy** [comment]
Vendor extensions are not allowed on any ref

**Comment by carlodonpromillo** [comment]
I didn't meant the ref itself. I meant the complete property:
"query":{
"$ref":"#/definitions/query",
"description":"some desc",
"x-someString":"value"
}
Why isn't that allowed?

**Comment by webron** [comment]
@carlodonpromillo because JSON References don't allow *any* additional properties within them. Both `description` and `x-someString` would be ignored by JSON References parsers (following the JSON Parser spec).

**Comment by webron** [comment]
Ugh, following the JSON Reference spec.
