### ISSUE TITLE
[Retrofit2] Use multiple converters and remove the custom gson converter

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#2177]
Retrofit 2 can use multiple converters so the custom gson converter is not needed anymore.
The adapter could be built with
```java
adapterBuilder = new Retrofit
               .Builder()
               .baseUrl(baseUrl)
               .client(okClient)
               .addConverterFactory(ScalarsConverterFactory.create())
               .addConverterFactory(GsonConverterFactory.create(gson));
```
This has the advantage of working for both request and response, and also to deal with all primitive types (not only String).

**Comment by cbornet** [comment]
Actually this should wait retrofit-2.0.0-beta4(#2149) since it has ScalarResponseBodyConverters integrated.

**Comment by wing328** [comment]
@cbornet  FYI #2149 has been merged into master.
