### ISSUE TITLE
Indicate somewhere the swagger-codegen version that was used

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#2183]
It would be handy to have the swagger-codegen version that generated the code somewhere. For instance in the READMEs or in a dedicated file.

**Comment by wing328** [comment]
@cbornet yes, agree with you that the swagger-codegen version is useful (e.g. for troubleshooting the SDK)

**Comment by jimschubert** [comment]
I'd also like to see a dump of the options that were used.

**Comment by jimschubert** [comment]
Would anyone be opposed to creating output `.swagger/VERSION` and `.swagger/OPTIONS` text files for all generators?

**Comment by wing328** [comment]
There's an ongoing work to add a mustache tag containing the Swagger Codegen version (e.g. 2.3.0) but there are minor issues that we need to roll back the enhancement: https://github.com/swagger-api/swagger-codegen/pull/5489

Related discussion: https://github.com/swagger-api/swagger-codegen/issues/5376

**Comment by jimschubert** [comment]
@wing328 cool. It looks like that PR and issue are interested in outputting the version to templates. I opened a PR that outputs the version to `.swagger/VERSION`.  See #5556 and let me know what you think.

**Comment by cbornet** [comment]
Shouldn't it be `.swagger-codegen/VERSION` ?

**Comment by jimschubert** [comment]
@cbornet generally, hidden folders are org-specific and not product-specific... at least in my experience. Do you think `.swagger/CODEGEN_VERSION` would be better? I don't mind either way.

I could change it to `.swagger-codegen/VERSION` if you think that's more appropriate.

**Comment by wing328** [comment]
@jimschubert I would prefer `.swagger-codegen/VERSION` so as to do a little bit of growth hacking for Swagger Codegen - developers who consume the API clients or use the server stubs may do a Google search on swagger-codegen after discovering the hidden folder.

**Comment by wing328** [comment]
Thanks @jimschubert for the PR, which has been merged into master.

I've renamed .swagger to .swagger-codegen via fd3cae6

**Comment by jimschubert** [comment]
Thanks. I hadn't seen your comment from yesterday about moving forward with `.swagger-codegen`.
