### ISSUE TITLE
[Swift] client library contains an unresolved identifier "ByteArray", while generating the code from Swagger editor

### ISSUE THREAD

**Issue by SurajSundar** [swagger-api/swagger-codegen#2185]
We have defined an object for a user in the swagger.json file, which is as follows
  User:
    type: object
    properties:
      name:
        type: string
        description: Name of the user
      email:
        type: string
        description: "User's email id"
      favorite_team:
        type: string
        description: Name of favorite team
      **image:
        type: string
        format: byte
        description: "User's image"**
      is_anonymous:
        type: boolean
        description: "Flag to hide User's image from non-friend users."
      dob:
        type: string
        format: date
        description: "User's date of birth."
      timezone:
        type: string
        description: "User's timezone."
      country_code:
        type: string
        description: "User's country code."
      provider:
        type: string
        description: "User's oauth provider."
      access_token:
        type: string
        description: "User's oauth access token(provided by FB)"
      unique_id:
        type: string
        description: "User's oauth id(provided by FB)"

While generating the client code for Swift, the "image" attribute gets mapped as a type "ByteArray". This data type is not supported in Swift and the compilation fails. 

 instance.image = Decoders.decodeOptional(clazz: **ByteArray**.self, source: sourceDictionary["image"])

Could someone please suggest a workaround of a fix for this?

Thanks,
Suraj

**Comment by wing328** [comment]
@SurajSundar are you using the latest master to generate the Swift API client?

**Comment by SurajSundar** [comment]
Hi @wing328 ,

I'm using the link http://editor.swagger.io/ to generate the client code

Thanks,
Suraj

**Comment by wing328** [comment]
That's using stable release 2.1.5. Please use the latest master instead as there're quite many enhancements to the Swift API client recently.

**Comment by SurajSundar** [comment]
Ok. Would try that. Any ETA on when the updates would be available on the link?

Thanks,
Suraj

**Comment by wing328** [comment]
Sorry we don't have ETA at the moment but if you look at our previous release cycle, it usually take 2 to 3 months for another stable release.

**Comment by SurajSundar** [comment]
Ok. 

Thanks, 
Suraj

**Comment by wing328** [comment]
I can confirm in the latest master that `binary` is mapped to `String` so closing this issue for now. 

Please reopen if you still encounter the issue using Swift API client generated by the latest codegen.

**Comment by SurajSundar** [comment]
@wing328 can you give me an example of how to run the swagger-codegen command for swift code generation, in terminal?

Thanks,
Suraj

**Comment by wing328** [comment]
A good example is `./bin/swift-petstore.sh`, which contains the command to generate Swift API client for Petstore API.
