### ISSUE TITLE
Serialize collection multi PHP problem

### ISSUE THREAD

**Issue by chosroes** [swagger-api/swagger-codegen#2212]
Hi,

I have a big problem with my function parameters.
My Api is waiting for filters like this:

> ?filters[id][]=1&filters[id][]=2&filters[name]=Me

Or even

> ?filters[name][]=Me&filters[name][]=You&filters[date][before]=2012-01-01

However, in the generated code:

``` php
if (is_array($filters)) {
    $filters = $this->apiClient->getSerializer()->serializeCollection($filters, 'multi', true);
}

if ($filters !== null) {
    $queryParams['filters'] = $this->apiClient->getSerializer()->toQueryValue($filters);
}// query params
```

So i get a stupid ?filters=id=1&id=2&name=Me

The behavior should have be:

``` php
if (is_array($filters)) {
    $filters = $this->apiClient->getSerializer()->serializeCollection(['filters' => $filters], 'multi', true);
}
```

And in the serializeCollection method:

``` php
if ($allowCollectionFormatMulti && ('multi' === $collectionFormat)) {
    return http_build_query($collection, '', '&');
}
```

Because for the moment it's blowing everything up:

`preg_replace('/%5B[0-9]+%5D=/', '=', http_build_query($collection, '', '&'));`

I can't use the codegen like that, and it's not me that have to adapt my API behavior...

**Comment by fehguy** [comment]
I don't believe the codegen supports that format for query parameters in arrays.  Unfortunately arrays in query parameters are not standardized and that format isn't one that we support.

**Comment by wing328** [comment]
You can customize [`toQueryString`](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php#L122) and provide your customized template via `-t` option (e.g. `-t modules/swagger-codegen/src/main/resources/php`)

**Comment by christiaanderidder** [comment]
This issue still exists but can easily be resolved for collectionType multi because `\GuzzleHttp\Psr7\build_query` already handles arrays correctly according to the spec (https://swagger.io/docs/specification/2-0/describing-parameters/#array):
`?param=a&param=b`

For example:
```php
// query params
        if (is_array($filterStatuses)) {
            $filterStatuses = ObjectSerializer::serializeCollection($filterStatuses, 'multi', true);
            var_dump($filterStatuses);
        }
        if ($filterStatuses !== null) {
            $queryParams['filter.statuses'] = ObjectSerializer::toQueryValue($filterStatuses);
        }
```
Can be changed to
```php
if ($filterStatuses !== null) {
            $queryParams['filter.statuses'] = $filterStatuses;
        }
```
for 'multi' collections

I won't mind creating a pull request, unless there are any implications when making this change.

**Comment by wing328** [comment]
@chosroes please create a pull request so that we can review the fix more easily. Thank you 🙇
