### ISSUE TITLE
[Python] Swagger spec 2.0 with valid securityDefinitions are ignored (oauth 2.0 Bearer)

### ISSUE THREAD

**Issue by cbdelavenne** [swagger-api/swagger-codegen#2213]
Hello!

Here's my spec file below (with some abstractions):
```
{
  "info": {
    "version": "api-v1",
    "title": "API V1"
  },
  "securityDefinitions": {
    "Bearer": {
      "in": "header",
      "type": "accessToken",
      "name": "Authorization"
    }
  },
  "paths": {
    "/token": {
      "post": {
        "parameters": [
          {
            "in": "formData",
            "type": "string",
            "description": "app name",
            "required": true,
            "name": "app"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "app related client_id",
            "required": true,
            "name": "client_id"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "grant type",
            "required": true,
            "name": "grant_type"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "username",
            "required": true,
            "name": "username"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "password",
            "required": true,
            "name": "password"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "utm field",
            "required": true,
            "name": "utm_campaign"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "utm field",
            "required": true,
            "name": "utm_content"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "utm field",
            "required": true,
            "name": "utm_medium"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "utm field",
            "required": true,
            "name": "utm_source"
          },
          {
            "in": "formData",
            "type": "string",
            "description": "utm field",
            "required": true,
            "name": "utm_term"
          }
        ],
        "operationId": "Authentication_GetToken",
        "summary": "Gets authentication token.",
        "tags": [
          "Authentication"
        ],
        "deprecated": false,
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/TokenResultDto"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ]
      }
    }
  },
  "schemes": [
    "http",
    "https"
  ],
  "definitions": {
    "TokenResultDto": {
      "properties": {
        "token_type": {
          "type": "string"
        },
        "referralCode": {
          "type": "string"
        },
        ".expires": {
          "type": "string"
        },
        "refresh_token": {
          "type": "string"
        },
        "token_version": {
          "type": "string"
        },
        "expires_in": {
          "type": "string"
        },
        "firstname": {
          "type": "string"
        },
        "sendMarketingEmail": {
          "type": "string"
        },
        "preferredCulture": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "access_token": {
          "type": "string"
        },
        ".issued": {
          "type": "string"
        }
      },
      "title": "TokenResult",
      "type": "object",
      "required": [
        "token"
      ]
    }
  },
  "swagger": "2.0",
  "host": "localhost"
}
```

Python code generated via this spec creates the following `configuration.py` `auth_settings` function:
```
    def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {

        }
```

As you can see, it just returns an empty dictionary. I have a few endpoints that need to have the following header:
```"Authorization": "Bearer {access_token}"```

I tried just passing that in the 'default headers' to the client, but it's not used during the actual request.

Is Bearer not recognized by swagger codegen Python client?

Thanks!

**Comment by wing328** [comment]
@cbdelavenne I don't think the following is the correct way to define OAuth authentication:
```
  "securityDefinitions": {
    "Bearer": {
      "in": "header",
      "type": "accessToken",
      "name": "Authorization"
    }
  },
```
Please refer to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L924 for an example on how to define oauth security definition.

I did confirm in the code that `Authorization": "Bearer {access_token}` is supported for Python and other API clients.

**Comment by cbdelavenne** [comment]
Yea, after review, you are right, that definition was incorrect. However, the example you linked doesn't seem to apply to my case - or there's multiple ways of defining it.

Here's the working version for a security definition header `Authorization: Bearer {access_token}`:
```
  "securityDefinitions": {
    "Bearer": {
      "in": "header",
      "type": "apiKey",
      "name": "Authorization"
    }
  },
```
Note my mistake was to set the `type` to an invalid `Bearer` type.

This generates the following swagger codegen function in `swagger_client/configuration.py`:
```
    def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'Bearer':
                {
                    'type': 'api_key',
                    'in': 'header',
                    'key': 'Authorization',
                    'value': self.get_api_key_with_prefix('Authorization')
                },

        }
```

Verified it via [editor.swagger.io](url)

Spec MVCE:
```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Based on \"Basic Auth Example\"",
        "description": "An example for how to use Auth with Swagger.\n"
    },
    "host": "basic-auth-server.herokuapp.com",
    "schemes": [
        "http",
        "https"
    ],
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "paths": {
        "/": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Will send `Authenticated`"
                    },
                    "403": {
                        "description": "You do not have necessary permissions for the resource"
                    }
                }
            }
        }
    }
}
```

**Is this way of defining `securityDefinitions` deprecated?
If not, it might be a good example to add to the `petstore.json`**

**Comment by wing328** [comment]
Instead of using `apiKey`, please use `oauth2` instead. Here is an example: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#implicit-oauth2-sample

**Comment by wing328** [comment]
Here are the source code related to OAuth in Python:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/configuration.mustache#L76

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/configuration.mustache#L244

**Comment by cbdelavenne** [comment]
Would the `authorizationUrl` point to my `/token` endpoint?

How do scopes work internally?
I understand that for all paths that require an authentication bearer token, I should be declaring something like:
```
"security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
```

Also, some of my endpoints use custom grant-types. I was told this isn't actually supported by swagger (it only supports [OAuth2's common flows (implicit, password, application and access code)](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-scheme-object)).

Do you know anything about that?

<hr> 
Just to explain a bit what I'm working with here. I'm using swagger-codegen to generate a Python client of my company's REST API. They have a swagger spec, but that spec file doesn't include OAuth2 because they use custom grant types, and what not.

So what I'm doing to make it work is downloading the spec, injecting the `securityDefinitions` and the non-mapped `/token` path to the spec (in a loaded json object) and saving that to a temporary file to generate my Python client. It isn't an ideal situation, but it's easier than writing every request manually.

**Comment by wing328** [comment]
OK. You can use `apiKey` definition as a workaround. This is what you provided before:
```
  "securityDefinitions": {
    "Bearer": {
      "in": "header",
      "type": "apiKey",
      "name": "Authorization"
    }
  },
```
`Bearer` is just the name of the security definition. The developer will need to set the API key prefix to `Bearer` in configuration.py (e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/swagger_client/configuration.py#L69)

**Comment by cbdelavenne** [comment]
Is there a way to define the API key prefix in the swagger spec?

**Comment by wing328** [comment]
Not officially. As a workaround you can use vendor extension (e.g. x-apikey-prefix) (but it's not supported in the mustache template yet)

Would that be a show stopper to use the Python SDK?

**Comment by cbdelavenne** [comment]
I've been using a different workaround:
```
        # Add header 'Authorization: Bearer {token}' to client default headers
        client.set_default_header(header_name='Authorization', header_value=access_token)

        # Initialize API to client
        app_api = swagger_client.ApplicationApi(client)
```
It's dirty, but it works.

**Comment by wing328** [comment]
Yes, that's another way.

**Comment by cbdelavenne** [comment]
Just a note, on modifying the configuration.py manually. Every time the client is re-generated by swagger_codegen, the changes to configuration.py have to be done manually or via another supporting script.

**Comment by wing328** [comment]
For the manual change in configuration.py, do you mean setting the API key prefix?

**Comment by cbdelavenne** [comment]
Yes, that's what I'm referring to.

**Comment by wing328** [comment]
That's not how I expect the Python API client to be used. 

I would imagine a sample code is provide to the developers using the Python SDK on how to set the API key prefix and API key in their script/app.

Would that solve the problem of manually updating configuration.py with hard-coded API key prefix?

**Comment by cbdelavenne** [comment]
I'd rather continue to use my current workaround (setting authentication header in default headers of the client before initializing an API).

**Comment by wing328** [comment]
@cbdelavenne it's entirely up to you. Closing this issue.

Please open a new one if you need further assistance from us.

**Comment by cbdelavenne** [comment]
@wing328 Thanks for your help again :+1:

**Comment by ianseyer** [comment]
I am experiencing a similar issue:

My spec:
```
securityDefinitions:
  developer_id:
    type: apiKey
    name: "Developer-id: Bearer:"
    in: header
  knurld_auth:
    type: oauth2
    authorizationUrl: https://api.knurld.io/oauth/client_credential/accesstoken?grant_type=client_credentials
    tokenUrl: https://api.knurld.io/oauth/client_credential/accesstoken?grant_type=client_credentials
    flow: application
```

The produced `configuration.py`:
```
def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'developer_id':
                {
                    'type': 'api_key',
                    'in': 'header',
                    'key': 'Developer-id: Bearer:',
                    'value': self.get_api_key_with_prefix('Developer-id: Bearer:')
                },

        }
```

Any ideas?
