### ISSUE TITLE
Typescript Angular Client validates boolean parameter with !operator

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#2221]
_From @AndreasM009 on February 23, 2016 7:23_

When creating a Typescript Angular Client which includes methods that has a boolean Parameter, the boolean Parameter is verified using the !Operator. It is not possible to set the boolean Parameter to a false value. Setting the boolean Parameter to false will cause an exception.

Example:
// verify required parameter 'aProductMakerId' is set
            if (!aBooleanParameter) {
                throw new Error('Missing required parameter aBooleanParameter when calling xyz');
            }

_Copied from original issue: swagger-api/swagger-editor#825_

**Comment by wing328** [comment]
@AndreasM009 thanks for the reporting the issue.

In TypeScript, how should one validate the boolean parameter to ensure it's provider by the function caller?

(Disclaimer: not an expert in TypeScript)

**Comment by wing328** [comment]
@AndreasM009 what about using the following instead?
```
if (aBooleanParameter == null) {
```

**Comment by AndreasM009** [comment]
I think you should compare it to 'undefined'.
undefined === aBoolean
________________________________
Von: wing328<mailto:notifications@github.com>
Gesendet: ‎29.‎02.‎2016 06:42
An: swagger-api/swagger-codegen<mailto:swagger-codegen@noreply.github.com>
Cc: AndreasM009<mailto:andreas.mock@live.com>
Betreff: Re: [swagger-codegen] Typescript Angular Client validates boolean parameter with !operator (#2221)

@AndreasM009 what about using the following instead?
```
if (aBooleanParameter == null) {
```

---

**Comment by wing328** [comment]
Here is the discussion to the solution I proposed: http://stackoverflow.com/a/28984306/677735

**Comment by pixelshaded** [comment]
My two cents:

It depends on if we want to support null or not. Right now, the spec itself does not:
https://github.com/OAI/OpenAPI-Specification/issues/229
And this would sway me towards throwing on null params.

But looking in to the future, I think there is a good chance the spec will support nulls. Many APIs give meaning to receiving null data (not my preference personally). 

The spirit of the code is to validate that data was passed. If we get null, data has still been technically passed, but we also want to generate clients that protect the consumer as much as possible. Take the example of an endpoint that expects an array. An empty array might be valid, but a null array might not be.

For the sake of the consumer, I think we should throw on nulls, hence the loose equality check on null.

**Comment by wing328** [comment]
Close via #2574
