### ISSUE TITLE
[Java] pom.xml is not being generated

### ISSUE THREAD

**Issue by kumarpr** [swagger-api/swagger-codegen#2224]
Hi, 
I am trying to build Java client. But I am not able to get pom.xml generated. It just creates build.gradle, gradle.properties and settings.gradle.

Here is the script, I am using
set executable=.\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar
If Not Exist %executable% (
  mvn clean package
)
set JAVA_OPTS=%JAVA_OPTS% -XX:MaxPermSize=256M -Xmx1024M -DloggerPath=conf/log4j.properties
set ags=generate -i METADATA_PATH -l java -o OUTPUT -c CONFIG_JSON
java %JAVA_OPTS% -jar %executable% %ags%

Here is how config json looks
CONFIG_JSON
{
  "groupId":"com.swagger.rating",
  "invokerPackage": "com.swagger.rating.client",
  "modelPackage": "com.swagger.rating.model",
  "apiPackage": "com.swagger.rating.api",
  "artifactId": "RestClient",
  "library": "jersey2",
  "sourceFolder":"src"  
}

Thanks
Prakash

**Comment by wing328** [comment]
@kumarpr are you using in the latest master, which should have the issue addressed?

**Comment by wing328** [comment]
FYI. Fixed by https://github.com/swagger-api/swagger-codegen/pull/2195

**Comment by kumarpr** [comment]
I am using the latest master only.

**Comment by fehguy** [comment]
If the pom.xml already exists, it will not overwrite it.  Can you please verify it is not already there?

**Comment by kumarpr** [comment]
No it is not there and it was never created for me.

**Comment by kumarpr** [comment]
I do not see pom.xml file created in swagger-codegen\samples\client\petstore\java either when used bin\windows\java-petstore.bat

**Comment by kumarpr** [comment]
Ok, so it depends upon where I am running it from, but it should not behave like this. I was running it from swagger-codegen folder which has pom.xml and README.md and that is why these 2 files are not being generated for me.

The DefaultCodegen:writeOptional() method, which checks if the file exists or not and adds to supportingFiles, looks in the folder I am running from while it should check in outputfolder instead.

JavaClientCodegen.java
Line 236: writeOptional(new SupportingFile("pom.mustache", "", "pom.xml"));

Should we change this to 
writeOptional(new SupportingFile("pom.mustache", outputFolder, "pom.xml"));

**Comment by fehguy** [comment]
Ok that should have been fixed in a recent PR. Will look to see why it's not working, can you be sure you have the latest source from master?

**Comment by kumarpr** [comment]
Ok, seems I had few days older code and missed wing328 comment about 2195. 
Thanks wing328 and fehguy for all your responses.

**Comment by fehguy** [comment]
Great, thanks for following up.

**Comment by wing328** [comment]
I'll add a log (info) to show that the file is not written and the reason behind.

**Comment by wing328** [comment]
Added a log message via https://github.com/swagger-api/swagger-codegen/pull/2239
```
reading from modules/swagger-codegen/src/test/resources/2_0/petstore.json
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting pom.xml as the file already exists in /var/tmp/java/github//pom.xml
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting README.md as the file already exists in /var/tmp/java/github//README.md
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting build.gradle as the file already exists in /var/tmp/java/github//build.gradle
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting settings.gradle as the file already exists in /var/tmp/java/github//settings.gradle
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting gradle.properties as the file already exists in /var/tmp/java/github//gradle.properties
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting AndroidManifest.xml as the file already exists in /var/tmp/java/github/src/main/AndroidManifest.xml
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting ApiClient.java as the file already exists in /var/tmp/java/github/src/main/java/io/swagger/client/ApiClient.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/model/User.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/model/Category.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/model/Pet.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/model/Tag.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/model/Order.java
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: get /pet/{petId}?testing_byte_array=true. Renamed to auto-generated operationId: petPetIdtesting_byte_arraytrueGet
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/api/UserApi.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/api/PetApi.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/api/StoreApi.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/StringUtil.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/auth/OAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/auth/OAuthFlow.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/ApiException.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/Configuration.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/Pair.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/java/github/src/main/java/io/swagger/client/auth/Authentication.java
```

**Comment by kumarpr** [comment]
Thanks :+1:
