### ISSUE TITLE
生成安卓客户端的/volley/build.mustache模版文件有问题

### ISSUE THREAD

**Issue by yuanpan365** [swagger-api/swagger-codegen#2228]
swagger-codegen/modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache

第77行   testCompile "net.jodah:concurrentunit:${concurrentunitVersion}"  

concurrentunitVersion 应该是 concurrent_unit_version

**Comment by wing328** [comment]
@yuanpan365 do you mind submitting a PR for the fix so that we can review?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
@yuanpan365 fixed with https://github.com/swagger-api/swagger-codegen/pull/2277, please pull the latest master and let us know if you still see the issue.
