### ISSUE TITLE
Generating file for each operation

### ISSUE THREAD

**Issue by onemanstartup** [swagger-api/swagger-codegen#2235]
Is there a way to generate file for each operation besides overriding generate method?

**Comment by fehguy** [comment]
Not now. What would you call the generated classes if it did?

**Comment by onemanstartup** [comment]
@fehguy I making ruby api server. At least i research how to do it with swagger codegen. And I want use validation library https://github.com/dryrb/dry-validation to define schemas. 
I want every call to conform to that schema. For now i can do this with supporting file where every schema will live, but its ugly.

**Comment by wing328** [comment]
@onemanstartup is it correct to say that for each "api" file generated, there's a corresponding "dry-validation" file for it?

**Comment by wing328** [comment]
@onemanstartup if you don't mind, can you share a bit more about the Ruby API server you're working on? Is that based on [rails-api](https://github.com/rails-api/rails-api)?

**Comment by onemanstartup** [comment]
@wing328 rails-api has been merged, but yeah.
"for each "api" file generated" not for each api, but for each operation.
Right now it seems easier way will be generating https://github.com/ruby-grape/grape grape api.

**Comment by wing328** [comment]
Recently, I've added auto-generated unit test files for Perl API client: https://github.com/swagger-api/swagger-codegen/pull/2109

Is that similar to what you're looking for?

**Comment by onemanstartup** [comment]
@wing328 test files are great, thanks. Is it more similar for generating api files.
Every Api file for now is just wraps multiple endpoints. I want generating files for each endpoint.  
```
controllers/api/books_api/create.rb
schemas/api/books_api/create.rb
```

**Comment by wing328** [comment]
OK. Understood what you're trying to do. Can't help at the moment :(

Would the following still meet the (minimal) requirement to build a functional rails API app?
```
controllers/api/books_api.rb
schemas/api/books_api.rb
```

**Comment by onemanstartup** [comment]
@wing328 right now i can do this in one supporting file, so yeah. It was a feature wish.

**Comment by wing328** [comment]
@onemanstartup  Do you mind if I open a task "Create Rails API generator" and mention the fact that you've started working on it so that the community is aware and provide help if needed?

**Comment by onemanstartup** [comment]
@wing328 I'm starting another project right now and wont be available in the next 2 months. And I'm not java programmer, so my generator won't be great anyway :)

**Comment by wing328** [comment]
@onemanstartup no worry. We'll create a task to see if anyone in the community has cycle to contribute the generator for Rails API.

**Comment by wing328** [comment]
Opened https://github.com/swagger-api/swagger-codegen/issues/2253.

Closing this one.

**Comment by Leghrib** [comment]
i have the same issue , i want to generate (jmeter) jmx file for each api operation
