### ISSUE TITLE
[java] invalid java code gen for Map<String, Object>

### ISSUE THREAD

**Issue by dantran** [swagger-api/swagger-codegen#2237]
swagger spec is like this

    "attributes" : {
          "type" : "object",
          "additionalProperties" : {
            "type" : "object"
          }
      },

codegen: maps it to   Map\<String, SomeName\>

      package xxx.SomeName;

      import java.util.Objects;

    @javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",   date = "2016-02-24T18:46:14.064-08:00")
    public class SomeName{
  
    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }
      SomeName someName= (SomeName) o;
      return true;
    }

    @Override
    public int hashCode() {
      return Objects.hash();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder();
      sb.append("class SomeName{\n");
    
      sb.append("}");
      return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
      if (o == null) {
        return "null";
      }
      return o.toString().replace("\n", "\n    ");
    }
    }

Which does not do much

My current pay load is just a map of String to primitive ( string/int)

Run with 2.1.5 and 2.1.6 SNAPSHOT

swagger-codegen 2.1.4 map it to Map\<String,Object\> but this version is not usable for me

**Comment by dantran** [comment]
I am able to remove the mention generated code and use Map<String, Object>. This solves my issue

**Comment by dantran** [comment]
I have not heard from wagger-codegen dev yet, this means my report is not clear? feedback is very much appreciated.

**Comment by wing328** [comment]
@dantran currently "type: object" without any property or $ref does not map to Object (in Java or other lang)

In your case, can the `object` in additionalProperties be defined properly ?

**Comment by dantran** [comment]
@wing328 not possible to defined the 'object' properly.  here is the story:

  * we started out of  java pojo   ( ie Map<String, Object> attributes) and use swagger-maven-plugin to generate the swagger spec where the 'attributes' has the json which we have no control

    "attributes" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "object"
      }
    }

  * The Object means it can be anything

  * Use swagger-codegen-maven-plugin to convert back at client side which should map back to Map<String,Object> ( used to work under 2.1.4)

**Comment by wing328** [comment]
@dantran to confirm, when you said it worked under 2.1.4, you mean swagger codegen 2.1.4 mapped "type: object" without property or $ref to "Object" in Java, right?

**Comment by dantran** [comment]
@wing328, Yes.   swagger-codegen 2.1.4 maps the json snippet back to Map<String,Object>

**Comment by wing328** [comment]
OK. I'll take a deeper look.

I think it's related to adding the support of inline schema object (which automatically creates an object when "type: object" has neither property nor $ref.

**Comment by wing328** [comment]
@dantran we've fixed the issue in the latest master. Would you please pull the latest and give it a try?

**Comment by dantran** [comment]
@wing328. It works.   Thank you!!!

**Comment by wing328** [comment]
@dantran thanks for the confirmation and sorry for the inconvenience caused by this.

We've added test cases to cover the issue moving forward.

**Comment by wing328** [comment]
Fixed by https://github.com/swagger-api/swagger-codegen/pull/2297

**Comment by dantran** [comment]
@wing328 Thank you for this incredible quick fix. Could you deploy latest 2.1.6-SNAPSHOT to sonatype?

**Comment by wing328** [comment]
I think Tony just deployed an updated JAR a few hours ago. Have you check the latest with `'mvn clean install -U` ?

I believe you can also workaround by doing a `mvn clean install` to install the 2.1.6-SNAPSHOT locally in your machine?

**Comment by dantran** [comment]
@wing328 I should have checked latest snapshot at sonatype before requesting for new one.  Thanks again
