### ISSUE TITLE
Support for Windows UWP

### ISSUE THREAD

**Issue by jerry1621** [swagger-api/swagger-codegen#2241]
Question:

I'd like to use Swagger-Api for a Windows UWP project, but the RestSharp-Library #, which is used for C#-generation (#673), unfortunately has no support for Windows UWP-Apps...

Any way to solve this issue?

**Comment by wing328** [comment]
@jerry1621 Thanks for reporting the issue. Have you opened a ticket with RestSharp to see if they've any plan to support Windows UMP apps?

**Comment by jerry1621** [comment]
@wing328 There is already an issue since August '15, but unfortunately no updates recently ([https://github.com/restsharp/RestSharp/issues/745](url))

**Comment by wing328** [comment]
Seems like the PR for supporting UWP has merged: https://github.com/restsharp/RestSharp/pull/780

**Comment by wing328** [comment]
@jerry1621 may I know if it works for you?

**Comment by jerry1621** [comment]
@wing328 Not quite:
While RestSharpUWP supports Windows UWP-devices with x86 and x64 architecture, I'm not able to get it to run on an ARM-powered device and unfortunately all Windows 10 Mobile-devices available are ARM-powered, so I'm able to run it on a Win 10 Desktop but not on Win 10 Mobile, which is the platform I need it for...

**Comment by wing328** [comment]
@jerry1621 I would suggest you report your finding to RestSharp team so that they can look into that.

**Comment by weird-dreams** [comment]
Does ARM work now?

**Comment by jerry1621** [comment]
@wing328 Unfortunately I got no reaction from RestSharp, but I was able to compile the RestSharp library for ARM-archtiecture and am now doing some further work and testing, because the generated swagger-code still needs some adaptions (mostly because of RestSharp)

**Comment by wing328** [comment]
@jerry1621 thanks for doing further work and testing. Can you elaborate on the "adaptions"? Maybe the community can help out on that.

**Comment by jerry1621** [comment]
@wing328 Sure, a few examples:

- In the generated configuation `Environment.OSVersion` and `Assembly.GetExecutingAssembly()...`  are used, but not available in Windows UWP (which is not critical, because they are used for debug-reports)
- In the genrated ApiClient `RestClient.Execute` (for the sync http-request, theres an async one too) is used, which is not available on Windows UWP
- In ApiClient again: in method `PrepareRequest()` there is this call in a for-loop: `request.AddFile(param.Value.Name, param.Value.Writer, [...];` and the `param.Value.Writer` is a `System.Action<System.IO.Stream>` as type but `byte[]` is needed

Those are some things I need to adjust or else I'll get compile-errors...

**Comment by jerry1621** [comment]
Another Update:
After adjusting those things stated above like this

- new class to replace `Environment.OSVersion` which provides me with needed information on UWP
- Replaced `var response = RestClient.Execute(request);` with `var response = new object();` in `CallApi(...)` (which obviously is not working anymore, but preventing compile-errors (using `CallApiAsync(...)` instead))
- Wrote a method to convert `param.Value.Writer` in `PrepareRequest(...)` from `System.Action<System.IO.Stream>` to `byte[]`

All in all those are minor adaptions and now everything works like expected :)

**Comment by wing328** [comment]
@jerry1621 thanks for sharing the above with us. Do you mind generating the C# SDK for UMP using https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json and then upload it to github to send it directly to me so that we can use reverse engineering to plot back the change to the C# mustache template?

**Comment by jerry1621** [comment]
@wing328 Am I getting you right, that you ask me to generate the C# code for that petstore.json and then do those necessary adaptions to send that changed code it to you?

**Comment by wing328** [comment]
@jerry1621 yes, or you can provide the one you've already customized to me via my email address (wing328 at yahoo.com) so that I can make the comparison to figure out what changes are needed.

**Comment by wing328** [comment]
Submitted https://github.com/swagger-api/swagger-codegen/pull/2427 to support UWP

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/2427 merged into master.
