### ISSUE TITLE
Update TypeScript(Node.js) Bluebird usage

### ISSUE THREAD

**Issue by shadeglare** [swagger-api/swagger-codegen#2251]
I noticed that the bluebird defer is obsolete and will be removed in a feature version.
Got this:
`Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.`

**Comment by wing328** [comment]
@shadeglare thanks for letting us know. May I know if you've cycle to contribute a PR?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache#L215

**Comment by bherila** [comment]
+1, also adding that it would be great to keep the syntax close to ES6 promises as possible. That way when compiling under ES6 the reference to bluebird is simply not needed.
