### ISSUE TITLE
C# Client generator exceptions

### ISSUE THREAD

**Issue by ChenJasonGit** [swagger-api/swagger-codegen#2252]
I used C#  Client generator.This design use exception for status_code.
The design is not good.
Or we can modify the code for   `if (statusCode >= 400)    throw new ApiException .`
404 is so common status_code,I think it shoud not  be an exception.
And,
I think we can use the fish‘s networklib instead of the rest sharp.(https://www.nuget.org/packages/network.fishlee.net/).

**Comment by wing328** [comment]
The design is based on our review of other C# SDKs (Stripe, Twilio, Dropbox, Twiiter, etc). Other languages also follow the same approach.

You can customize the template to catch the 404 exception and re-throw the exception if needed.

For Fish's networklib, does it support the following?
- Multiple file upload
- Async and sync HTTP requests
- various Windows platform (e.g. Windows UWP)

We welcome contribution to support different HTTP/REST libraries in C# as we've already have something similar in the Java API client, which supports Jersey1.x, Jersey2.x, Retrofit 1.x, Retrofit 2.x, etc

**Comment by wing328** [comment]
Closing this as we've not heard from you.
