### ISSUE TITLE
[Ruby] Create a generator for Rails API server 

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2253]
If anyone from the community wants to work on this, please reply to let us know.

Ref: [How to add a generator for a new language or framework] (https://github.com/swagger-api/swagger-codegen/wiki/How-to-add-a-generator-for-a-new-language-or-framework)

**Comment by zlx** [comment]
我来试试看，生成一个基于  Rails 5 的 Server

**Comment by wing328** [comment]
Thanks @zlx for contributing the Rails5 server generator.
