### ISSUE TITLE
model properties eliminated by additionalProperties element

### ISSUE THREAD

**Issue by egimaben** [swagger-api/swagger-codegen#2268]
I have run into this issue now with implementing arbitrary field behaviour with `additionalProperties`. Below is my model with additional properties.
```javascript
"CObject": {
 "type": "object",
 "properties": {
  "_id": {
   "type": "string"
  },
  "createdAt": {
   "type": "string",
   "format": "date-time"
  },
  "updatedAt": {
   "type": "string",
   "format": "date-time"
  }
 },
 "additionalProperties": {
  "type": "string"
 }
}
```
Indeed the only change I see in the generated java client is that my `CObject.java` now sub-classes HashMap class. I expected that a call to `put([key],[value])` on `CObject ` would just add a new property in the request body. On running a test, I realized that all properties within `CObject `are absent in the final request body. So, the client only sends a request body with properties defined arbitrarily and eliminates all other properties defined in the specification. Am using the latest swagger-codegen(2.1.6 snapshot). how can I get past this issue???

**Comment by wing328** [comment]
@egimaben if I understand correctly, CObject is a special object with several properties (_id, createAt, updateAt) but it's also a HashMap in Java that developers can add key-value (string) pair to it.

Is it correct to say that the key-value pair is more like a dynamic property list in Java that you can add or remove "property" (key) with ease?

cc @fehguy @webron to see if they've any comment on this type of setup.

**Comment by egimaben** [comment]
@wing328, yes. To illustrate further, If I add any extra property , "name", the property  set should now change from (_id, createAt, updateAt) to (_id, createAt, updateAt,name).

**Comment by wing328** [comment]
@egimaben given that the properties are dynamic, I think the best way to model it is simply using `type: object`.

**Comment by egimaben** [comment]
@wing328. Does this suggestion affect additionalProperties? I mean like this:
```javascript
 "additionalProperties": {
  "type": "object"
 }
```
or do you mean something else. An example to illustrate this would help

**Comment by wing328** [comment]
Please refer to http://stackoverflow.com/questions/35782175/how-to-receive-a-dynamic-response-in-a-swagger-spec/35791870#35791870

**Comment by egimaben** [comment]
@wing328 thanks, this works for  response.  I was trying to model the same for request but with pre-existing properties. I realized that I cannot :
```
"CObject": {
 "type": "object",
 "properties": {
  "_id": {
   "type": "string"
  },
  "createdAt": {
   "type": "string",
   "format": "date-time"
  },
  "updatedAt": {
   "type": "string",
   "format": "date-time"
  }
 },
 "additionalProperties": {
  "type": "string"
 }
}
```
Because in the generated java client, properties "_id","createdAt" and "updatedAt" won't appear in the request. Instead only properties set in code with `object.put([key],[value])` will. This explains the problem `model properties eliminated by additionalProperties element`.

Thus I think in client code, the object above is equivalent to this;
```
"CObject": {
 "type": "object",
 "additionalProperties": {
  "type": "string"
 }
}
```
then one has to call  `object.put([key],[value])` for each of default properties  `_id`,`createdAt` and `updatedAt` ontop of any other custom properties not known before hand.

This is the only work around that has gotten me past this.
