### ISSUE TITLE
[Swift] Update reserved keyword list

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2269]
Currently, Swift API client is using the default reserved keyword list. We will need to update it with the latest Swift reserved keyword list: http://www.dotnetperls.com/keyword-swift

**Comment by wing328** [comment]
If anyone from the community would like to work on this task, please let us know. A good starting point is the reserved keyword list in ObjC code generator: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ObjcClientCodegen.java#L96

**Comment by Edubits** [comment]
The official docs for this can be found here: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html#//apple_ref/doc/uid/TP40014097-CH30-ID413
There are some small differences with the list on Dot Net Perls.

Note that from the upcoming minor update Swift 2.2 on most reserved keywords are allowed as argument labels. See https://github.com/apple/swift-evolution/blob/master/proposals/0001-keywords-as-argument-labels.md

**Comment by wing328** [comment]
@Edubits Thanks for the official list and the minor update for Swift 2.2.

Can reserved keywords be used as model property/member?

**Comment by Edubits** [comment]
@wing328 If I interpreted it correctly you still can't use the reserved keywords for properties/members, only for function arguments. In all other cases it should be possible to use `backticks` for escaping.

**Comment by wing328** [comment]
@Edubits OK. Will keep the current login for the time being.

**Comment by lightbow** [comment]
Being new to swagger/mustache files, etc, I'm not sure if this is related to the same issue, but thought I'd mention it in this thread in case it was relevant. I have a lot of models with properties named "on" that are boolean. While this worked fine with the Swift2.x codegen (for example:`public var on: Bool?` and `nillableDictionary["on"] = self.on`) I'm seeing the Swift 3 generator map "on" to "true" which obviously causes problems. (so the generated code from the same model objects is instead `public var _true: Bool?` and `nillableDictionary["true"] = self._true`). Is "on" somehow in the reserved keyword list and causing this mis-mapping?

**Comment by fehguy** [comment]
Yea, that's YAML unfortunately.  `on`, `yes`, `true` if _unquoted_ in a YAML file will resolve to `true` (the boolean.

This needs to be handled in your definition.
