### ISSUE TITLE
[TypeScript] Bug with multi API key settings

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2274]
Currently, there's an issue with multi API key settings: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-node/api.ts#L151-L169
```
    set apiKey(key: string) {
        this.authentications.test_api_key_header.apiKey = key;
    }

    set apiKey(key: string) {
        this.authentications.api_key.apiKey = key;
    }

    set apiKey(key: string) {
        this.authentications.test_api_client_secret.apiKey = key;
    }

    set apiKey(key: string) {
        this.authentications.test_api_client_id.apiKey = key;
    }

    set apiKey(key: string) {
        this.authentications.test_api_key_query.apiKey = key;
    }
```
As the same function name `apiKey` is used repeatedly. To fix the issue, one way is to rename the function as `set apiKey(key: string, apiKeyIdentifier: string)` and set the key based on `apiKeyIdentifier`

If anyone from the community wants to work on this, please reply to let us know. Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/TypeScript-node/api.mustache#L156

**Comment by pixelshaded** [comment]
@wing328 Setters can't have more than one parameter, but it was a good suggestion otherwise.

**Comment by wing328** [comment]
@pixelshaded thanks for the fix :)
