### ISSUE TITLE
[JavaScript] Possibility to set timeout while using JS generated client

### ISSUE THREAD

**Issue by rkostrab** [swagger-api/swagger-codegen#2275]
In default JavaScript generated client it is not possible to set timeout without changing the generated code. Please add this feature.

[Here is stackoverflow thread I have created about it.](http://stackoverflow.com/questions/35558088/how-to-set-timeout-in-javascript-swagger-generated-client)

**Comment by wing328** [comment]
@rkostrab thanks for the suggestion. Would you have cycle to help implement the feature? A good starting point is to implement the `timeout` similar to `defaultHeader`: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache#L33

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by rkostrab** [comment]
I would do it but I don't have more spare time to help (deadlines, deadlines...). I'm sorry @wing328 :/ So I'm not gonna use swagger generated client right now because of missing this issue.

**Comment by vzeman** [comment]
@wing328 Do I need git permission to push the suggested change request into new branch?
I have created localy new branch "issue-2275" and I'm trying to push it into your repository, but I'm getting error ERROR: Permission to swagger-api/swagger-codegen.git denied to vzeman.

**Comment by wing328** [comment]
You will need to create the branch in your folked `swagger-codegen` repository. Please click on the `Folk` button in https://github.com/swagger-api/swagger-codegen and let me know if you need further assistance.

**Comment by vzeman** [comment]
created pullrequest https://github.com/swagger-api/swagger-codegen/pull/2287

**Comment by wing328** [comment]
Thanks. Left you a comment about updating Petstore sample.

**Comment by wing328** [comment]
PR merged
