### ISSUE TITLE
Ruby generator generates invalid class names

### ISSUE THREAD

**Issue by vincentjames501** [swagger-api/swagger-codegen#228]
If my api resource path has a hyphen in it, such as distribution-lists, the generated class is like the following:

```ruby
class Distribution-lists_api
end
```

It would be nice to convert hyphens into proper class and file names

**Comment by wing328** [comment]
@vincentjames501 #545 should have addressed the issue you reported.
Would you please give it another try with the develop_2.0 branch to see if the issue still persists ?

**Comment by webron** [comment]
Since it's merged, I'll close the issue for now. Please reopen if there's still a problem.
