### ISSUE TITLE
ASPNet5 Vendor specific Patterned Objects not exposed to mustache templates

### ISSUE THREAD

**Issue by escofieldnaxos** [swagger-api/swagger-codegen#2283]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject

I believe the Patterned Fields x- extension fields should be exposed to the mustache templates for vendor specific customization.  This would facilitate using an IOC and service locator pattern generated from the DL.  I could then regenerate from the DL without overwriting custom controller logic since it would be encapsulated in a service class.  This is for AspNet5 generation.

for example.

    "/pet/{petId}?testing_byte_array=true": {
      "get": {
        "tags": [
          "pet"
        ],
        "summary": "Fake endpoint to test byte array return by 'Find pet by ID'",
        "description": "Returns a pet when ID < 10.  ID > 10 or nonintegers will simulate API error conditions",
        "operationId": "",
        "x-serviceHandler": "IService",
        "produces": [
          "application/json",
          "application/xml"
        ],
Thanks!

**Comment by fehguy** [comment]
I believe they are available:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java#L33

You should be able to access them like such:

```
{{{vendorExtensions.x-serviceHandler}}}
```

**Comment by escofieldnaxos** [comment]
Thanks, that indeed worked!
