### ISSUE TITLE
[Go] Generated client code has several Case / visibility issues

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2285]
I'm a Go n00b, but I suspect I've caught several issues with the generated Go code. These are all related to Camelization and the fact that package-visibility in Go is determined by the name being UpperCamelized.

- **Escaping:** For escaping reserved keywords, using `_Name` won't work, because underscore is not considered uppercase by Go (I think), therefore the escaped name will not be visible beyond the package. For example:

````
type Artifact struct { 
        Id  int   ...
        Name  string ...
        CreatedDate  string  ...
        _Type  string... // This is bad
        Links  links  ... // This is also bad (the type name is "Links")
        }
````
* **Lowercase typename:** In the last line above, `links` should be `Links`.
* **Clashing `UpperCamel` param and type names in functions:** There are cases where a function can have a param with the same (UpperCamel) name as its type in the function defintion, e.g. `func (a DefaultApi) UpdateBuild (BuildId int32, Build Build) (error) {` ... this is obviously confusing, but also can cause an error if the generated code tries to refer to the type, e.g. `response := new(Build)`... the compiler will try to pass the object to the `new` function, instead of passing the type. This can be solved by always making functions params `lowerCamel`, e.g. `func (a DefaultApi) UpdateBuild (BuildId int32, build Build) (error) {`

**Comment by wing328** [comment]
@neilotoole thanks for the feedback.  I can help make some changes to improve the reserved keyword handling in Go. Would you have cycle to test the change when it's ready?

**Comment by neilotoole** [comment]
@wing328 I have a PR ready to go in the morning :-)

**Comment by wing328** [comment]
@neilotoole thanks for the contribution :beer:

**Comment by wing328** [comment]
PR merged.
