### ISSUE TITLE
[Go] Generated client code doesn't honor error (non-2xx) responses 

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2292]
If you have some swagger like this:

````
      responses:
        200:
          description: Found your pet
          schema:
            $ref: '#/definitions/pet'
        404:
          description: The pet is not found
          schema:
            $ref: '#/definitions/petIsMissingError'
````
It seems that for non-`2xx` codes, the generator API code doesn't ever return the custom error objects. However, what makes things even worse is that no error at all is returned. This is because of this piece of code:

````
    response := new(Pet)
    _, err := _sling.ReceiveSuccess(response)
    return *response, err
````

Due to the use of `ReceiveSuccess`, an error is only returned if a network layer error occurs, not if a non-`2xx` code is returned from the server. So, a `404` won't result in an error. One would instead need to use `_sling.Receive(successV, failureV)` and a bit of condition checking.

**Comment by wing328** [comment]
Yes, you're right. When I worked on the first version of the Go generator, I only tested with 2xx response. Ideally 4xx and 5xx response should also have been tested to uncover the issue (we already've similar tests for other langauges).

A good starting point to address the issue is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/api.mustache#L72-L80

**Comment by neilotoole** [comment]
Would you believe I have a PR almost ready to go? ;-)

**Comment by wing328** [comment]
:+1:

**Comment by neilotoole** [comment]
So... that PR does not fully address this issue in that we still do not return non-success objects, however it makes a vast improvement in that at least we now return an error (of some kind) for non-2xx conditions.  Perhaps we should have a separate issue for the returning-error-objects aspect?

**Comment by wing328** [comment]
Yes, please kindly open another issue for tracking so that the community can help work on that.
