### ISSUE TITLE
swagger.py is incompatible with python 2.x

### ISSUE THREAD

**Issue by peterquirk** [swagger-api/swagger-codegen#230]
I'm using the files in samples/client/petstore. swagger.py generates the following error in python 2.6.6.

Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import swagger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "swagger.py", line 115
    for (key, val) in objDict.iteritems()
      ^
SyntaxError: invalid syntax

**Comment by fehguy** [comment]
please see https://github.com/swagger-api/swagger-codegen/commit/db5259b9130450e01cf365a1899ab9f8adbccbd7
