### ISSUE TITLE
Please update 2.1.6-SNAPSHOT to oss.sonatype.org

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#2308]
It looks like swagger-codegen 2.1.6-SNAPSHOT hasn't been pushed to [sonatype](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.1.6-SNAPSHOT/) since Feb 12th. Would it be feasible to have this updated with the artifacts from latest master?

**Comment by wing328** [comment]
@fehguy @webron can you please take a look?

**Comment by fehguy** [comment]
all done
