### ISSUE TITLE
Swift code in swagger

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2315]
_From @AnkitaScienceInc on March 4, 2016 15:46_

I can no more generate client code for swift

_Copied from original issue: swagger-api/swagger-editor#839_

**Comment by wing328** [comment]
@AnkitaScienceInc can you please share the spec so that we can reproduce the issue?

**Comment by wing328** [comment]
@AnkitaScienceInc Please also try the latest master as there's been a lot of enhancements to Swift API client.

**Comment by AnkitaScienceInc** [comment]
i used http://editor.swagger.io/#/ where  I pasted JSON to generate a client code. Some days back to was allowing to generate a swift code, now it does not allow.

**Comment by wing328** [comment]
@AnkitaScienceInc can you send me the spec so that I can take a look? if the spec cannot be shared publicly, please you send it to my email account in the Github profile page.

**Comment by AnkitaScienceInc** [comment]
@wing328  i cloned a master branch code and was working great. now i'm facing this issue wherein for a variable with "_" (underscore)  character it generates camel case model variable.

This was not an issue some days back. Now this issue is appearing in a master branch code.

And also when i newly clone the master branch and go to generate an code. It give below issue:
Error: Unable to access jarfile modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
[SwaggerCodeIssue.pdf](https://github.com/swagger-api/swagger-codegen/files/177938/SwaggerCodeIssue.pdf)

**Comment by wing328** [comment]
@AnkitaScienceInc after you cloned the master, did you do a `mvn package` to create the jar?

**Comment by AnkitaScienceInc** [comment]
@wing328 yes i already did. Earlier it was working with the master branch. Last code which i generated was on 3rd March and it had worked.

**Comment by wing328** [comment]
@AnkitaScienceInc just so we're on the same page. The issue you're referring to is the model's **property name** (not the model name).

Again, can you send me the spec so that I can repeat the issue ?

**Comment by AnkitaScienceInc** [comment]
please check Models.swift

// Decoder for [User]
            Decoders.addDecoder(clazz: [User].self) { (source: AnyObject) -> [User] in
                return Decoders.decode(clazz: [User].self, source: source)
            }
			// Decoder for User
            Decoders.addDecoder(clazz: User.self) { (source: AnyObject) -> User in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = User()
                instance.id = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["id"])
                instance.fbId = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["fbId"])
                instance.name = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"])
                instance.authToken = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["authToken"])
                instance.displayName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["displayName"])
                instance.favoriteTeam = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["favoriteTeam"])
                instance.consecutivePlays = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["consecutivePlays"])
                instance.isAnonymous = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["isAnonymous"])
                instance.image = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["image"])
                instance.timezone = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["timezone"])
                instance.countryCode = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["countryCode"])
                instance.devices = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["devices"])
                return instance
            }

**Comment by AnkitaScienceInc** [comment]
this code i just generated. In the place of 'authToken' it should have been "auth_token"

**Comment by wing328** [comment]
so it should be like this?
```
instance.authToken = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["auth_token"])
```

**Comment by AnkitaScienceInc** [comment]
yes..

**Comment by AnkitaScienceInc** [comment]
Even in the model class we require a correction to be made.

Please check how its generating now. 

//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class User: JSONEncodable {

    public var id: Int?
    public var fbId: String?
    public var name: String?
    public var authToken: String?
    public var displayName: String?
    public var favoriteTeam: String?
    public var consecutivePlays: Int?
    public var isAnonymous: Bool?
    public var image: String?
    public var timezone: String?
    public var countryCode: String?
    public var devices: [Device]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["fbId"] = self.fbId
        nillableDictionary["name"] = self.name
        nillableDictionary["authToken"] = self.authToken
        nillableDictionary["displayName"] = self.displayName
        nillableDictionary["favoriteTeam"] = self.favoriteTeam
        nillableDictionary["consecutivePlays"] = self.consecutivePlays
        nillableDictionary["isAnonymous"] = self.isAnonymous
        nillableDictionary["image"] = self.image
        nillableDictionary["timezone"] = self.timezone
        nillableDictionary["countryCode"] = self.countryCode
        nillableDictionary["devices"] = self.devices?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

**Comment by wing328** [comment]
There's no recent change to https://github.com/swagger-api/swagger-codegen/blame/master/modules/swagger-codegen/src/main/resources/swift/Models.mustache#L136

**Comment by wing328** [comment]
You said it works in an earlier commit. Can you provide the commit hash so that I can perform a test with that?

**Comment by AnkitaScienceInc** [comment]
I dont know which hash it was.

**Comment by wing328** [comment]
Do you recall when you first cloned it and there was no "underscore" removal issue?

**Comment by wing328** [comment]
cc @Edubits who last changed that line to see if he recalls anything about keeping the original name (e.g. auth_token) of the property.

**Comment by AnkitaScienceInc** [comment]
it was on 2nd March 2016

**Comment by wing328** [comment]
I checkout a57bc98f591e8058b3ae236da8b0dd92af04691b on Mar 2nd but I got the same result. After renaming `shipDate` (property in Order of Petstore) to `ship_date`, I got the following:
```
instance.shipDate = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["shipDate"])
```
(which is not what you guys expected...)

**Comment by AnkitaScienceInc** [comment]
I got that date when we 1st used the code generated from master branch; as per our commit for our project. We did not change anything manually as i can see in the commits.

**Comment by jaz-ah** [comment]
@wing328 I definitely see something similar - basically for a json object that is this:
                "NumberOfHours": {
                    "type": "number"
                },

it now gets decoded like:

                instance.numberOfHours = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["numberOfHours"])

instead of 2.1.5 which generated this:

                instance.NumberOfHours = Decoders.decodeOptional(clazz: Double.self, source: sourceDictionary["NumberOfHours"])

I don't care about the parameter name (instance.NumberOfHours) but my server is returning the string as "NumberOfHours" and that has to stay constant.

I can take a look at this tonight if you're not already ...

**Comment by wing328** [comment]
I've submitted #2405. Please test (the instruction can be found in the PR)

Please test both serialization and deserialization.

**Comment by wing328** [comment]
A better solution is to use [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper). If anyone has cycle to implement it, please reply to the task below.

Ref: https://github.com/swagger-api/swagger-codegen/issues/2194

**Comment by jaz-ah** [comment]
tested serialization/deserialization and all appears correct - thanks!

**Comment by wing328** [comment]
Thanks for the tests. PR merged into master.
