### ISSUE TITLE
Would you mind not outputing timestamp in auto-generated file header?

### ISSUE THREAD

**Issue by QianJin2013** [swagger-api/swagger-codegen#2318]
The auto-generated file header contains timestamp which cause file difference, it's very inconvenient to check many auto-generated file's diff,
Would you mind not outputing the timestamp? so the auto-generated files can be saved in git better. 

```
+@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", 
date = "2015-11-19T13:52:16.052+01:00")
```

**Comment by QianJin2013** [comment]
I am working on a project which use swagger to generate client and server code, put them to git.
Sometimes, someone customized the swagger-autogen, then he new swagger-cli to generate new source code and commit again.

I need to know where auto-generated code changes, so i have to diff each file, but actually, most files have not changed except the timestamp file header.

**Comment by QianJin2013** [comment]
Sorry, i forgot to say the most common use case:

Someone add interface definition into yml, 
then use swagger-autogen-cli to generate client and server again,
at this time, too many files are treated as changed just because different timestamp in file header.

Don't you think this is inconvenient? i have to diff files one by one to see where changed.

**Comment by ePaul** [comment]
These are good arguments to not have a timestamp. (I previously did patch a company-internal plugin to remove the timestamp in generated files meant to be committed, so I can certainly feel with you.)

I can also understand that others prefer to see when a file was generated (just to see how old it is).
So the right thing to have should be an option to turn this on or off. I'm not sure which of them should be the default.

**Comment by fehguy** [comment]
I suggest we make the timestamp off by default, and use a configuration option to enable it.  I agree it makes git commits a mess.

**Comment by QianJin2013** [comment]
I am glad to here same feeling

**Comment by jqr** [comment]
@QianJin2013 I have the same issue. [Here is my fix](https://github.com/DocRaptor/docraptor-java/blob/7ecc1c2d0fbe95b99b297815cd3887c154fb6249/script/post_generate_language#L5-L7) in the mean time. I run this automatically after regenerating the clients.

**Comment by QianJin2013** [comment]
@jqr thank you. I works! 
Finally, without recompile, i chose modifying template file and specify `--template-dir <the dir of resources>` to auto gen cli command line.

src/main/resources/generatedAnnotation.mustache:
```
@javax.annotation.Generated(value = "{{generatorClass}}", date = "{{generatedDate}}")
```
I modified it to ->
```
@javax.annotation.Generated(value = "{{generatorClass}})
```
