### ISSUE TITLE
org.scala-lang#scala-library;2.10.2: not found

### ISSUE THREAD

**Issue by GerardSoleCa** [swagger-api/swagger-codegen#232]
Hello,

I'm trying to use swagger codegen against my API. I've installed Scala 2.10.1 and Maven 3.0.4.

When I run `./sbt assembly` I get a `org.scala-lang#scala-library;2.10.2: not found` I've tried changing the sbt version or adding new repositories, but nothing solved that issue.

Do someone have any recomendations?

Thankyou all!

**Comment by unoexperto** [comment]
In case someone ends up here from Google search. I had same issue until I realized that I'd edited `~/.sbt/1.0/global.sbt` with `offline := true` in the past to work on the plane. It prevented SBT from getting libraries for new scala.
