### ISSUE TITLE
Parameter names with "_" in the swagger.json file gets replaced with camelCase parameter names in generated Swift code

### ISSUE THREAD

**Issue by SurajSundar** [swagger-api/swagger-codegen#2337]
Hi,

We have some of the parameter names for POST requests, defined with "_" (underscore) in the swagger.json file. But the problem is that, when we generate the Swift code using this, the parameter keys for the same that are used to set the HTTP body, gets replaced with camelCase names. Because of this, all the POST requests are failing. Currently we are manually changing the parameter names to the correct ones in the generated code.
Could you please help us rectify this issue?
We are using the code generator installed on mac using brew.

Thanks,
Suraj

**Comment by ePaul** [comment]
@SurajSundar did the problem solve itself (you closed this issue 4 minutes after opening it)? If so, could you add a comment on how this was solved? If not, could you reopen it and add an example spec which demonstrate the problem?

**Comment by wing328** [comment]
That should be resolved by Swift API client generated by latest master of Swagger Codegen (homebrew uses stable release 2.1.5)
