### ISSUE TITLE
Parameter names with "_" in the swagger.json file gets replaced with camelCase parameter names in generated Swift code

### ISSUE THREAD

**Issue by SurajSundar** [swagger-api/swagger-codegen#2338]
Hi @wing328 

We have some of the parameter names for POST requests, defined with "_" (underscore) in the swagger.json file. But the problem is that, when we generate the Swift code using this, the parameter keys for the same that are used to set the HTTP body, gets replaced with camelCase names. Because of this, all the POST requests are failing. Currently we are manually changing the parameter names to the correct ones in the generated code.
Could you please help us rectify this issue?
We are using the code generator installed on mac using brew.

Thanks,
Suraj

**Comment by wing328** [comment]
@SurajSundar are you using the latest master (which should have the issue resolved) to generate the Swift API client?

**Comment by SurajSundar** [comment]
@wing328, i have installed the swagger codegen with homebrew. The version number was 2.1.5

**Comment by wing328** [comment]
@SurajSundar please use the latest master.

**Comment by SurajSundar** [comment]
@wing328, could you please tell me how to do this by not using Homebrew?

Thanks,
Suraj

**Comment by wing328** [comment]
It's in the README: https://github.com/swagger-api/swagger-codegen#building

**Comment by SurajSundar** [comment]
@wing328,

Thanks for your help. Could generate the proper code from master branch. 

Thanks,
Suraj

**Comment by wing328** [comment]
No problem. Glad to hear that the issue has been resolved.

**Comment by SurajSundar** [comment]
@wing328,

We are finding the same issue with the decoders now. The decoders seem to be removing the underscores

**Comment by SurajSundar** [comment]
@wing328,

The code was generated with the latest master branch. Also we noted that this was working in an older version of the master branch. Seems to have broken in the latest version. Please refer to attached file for details

[SwaggerCodeIssue.pdf](https://github.com/swagger-api/swagger-codegen/files/177863/SwaggerCodeIssue.pdf)

**Comment by wing328** [comment]
Is this the same as issue https://github.com/swagger-api/swagger-codegen/issues/2315 ?

**Comment by SurajSundar** [comment]
@wing328,

Yup. Its the same.

**Comment by wing328** [comment]
Please join the discussion there.

**Comment by SharathPS** [comment]
Hello @wing328,

I still see the same issue when I generate a java api client the parameters with _ get replaced.

**Comment by SharathPS** [comment]
any update on this @wing328

**Comment by wing328** [comment]
Thanks for tagging me but I'm no longer involved in this project. I hope others will be able to help you out. Good luck.
