### ISSUE TITLE
Kubernetes v1.json generates java client that won't compile. Any type mapping may be missing.

### ISSUE THREAD

**Issue by ieb** [swagger-api/swagger-codegen#2347]
using the latest code from master and doing the following

```
java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i testproject/src/main/resources/kubernetes/v1.json -l java -o kubernetes-client
cd kubernetes-client
mvn clean package
```

results in a few 100 compile errors of the form 

```
[ERROR] /Users/ieb/Adobe/src/granite/kubernetes-client/src/main/java/io/swagger/client/model/V1ObjectMeta.java:[7,30] error: cannot find symbol
```
V1ObjectMeta.java:[7,30] is 

```
import io.swagger.client.model.Any;

```

io.swagger.client.model.Any.java was not generated.

Is the type "any" missing from the Java client generator, or is there something else I need to do when generating the client ?

I could not find a duplicate open or closed bug and looking at the current code there does not appear to be a type mapping for "any".

**Comment by fehguy** [comment]
Can you please point to the kubernetes json document that you're loading?  Looks like it's local to your machine

**Comment by wing328** [comment]
@ieb I believe you're using https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json

That's a known issue with Kubernetes: https://github.com/kubernetes/kubernetes/issues/4700.

To workaround the issue, please replace "any" with "object".

Ref: https://github.com/swagger-api/swagger-codegen/issues/997

**Comment by ieb** [comment]
@wing328 thank you.
Schema reference was correct. I was using v1.1.8 of Kubernetes.
Workaround (replace "any" with "object") works perfectly with swagger-codegen master and Kubernetes v1.1.8 on both the main api.json and the extensions_v1beta1..json

Thanks for finding the Kubernetes issue, I failed, searching for "Any" generates lots of results.

**Comment by wing328** [comment]
@ieb no problem. I also suggested in https://github.com/kubernetes/kubernetes/issues/4700 to replace "any" with "object" so that others won't encounter the compilation error moving forward.
