### ISSUE TITLE
csharp support for KeyValuePair<TKey, TValue>

### ISSUE THREAD

**Issue by langdonx** [swagger-api/swagger-codegen#2355]
In trying to generate csharp from my spec, it created a file called "KeyValuePair[String,String].cs" and made references to it as well, like:

    public List<KeyValuePair[String,String]> RuleExpressions { get; set; }

Is there something I can configure to get around this for now?

**Comment by wing328** [comment]
@langdonx are you using the latest master of swagger-codegen to generate the C# API client?

The latest master should have the issue resolved.

Also can you share the spec on what's exactly `KeyValuePair[String,String]`?

**Comment by langdonx** [comment]
I was using 2.1.5.

The latest master branch does something different, but I wouldn't say it resolves it.  It created a KeyValuePairStringString class:

    public partial class KeyValuePairStringString :  IEquatable<KeyValuePairStringString>

I created a simple spec that reproduces the issue.  It's attached.

[v1.json.txt](https://github.com/swagger-api/swagger-codegen/files/169516/v1.json.txt)

**Comment by wing328** [comment]
If you want to model a `map/dictionary`, please use `additionalProperties`: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties, according to the spec.

**Comment by langdonx** [comment]
Ahh, thanks.  It looks like I need to go dig around to see what Swashbuckle's capabilities are with defining `additionalProperties` (with attributes I assume) since that's what generated my spec.

It seems like `swagger-codegen` did exactly as it was told?

**Comment by wing328** [comment]
Swagger-Codegen generates the API client based on the OpenAPI/Swagger spec.

Closing this issue for the time being. If you need further assistance, please open a new issue.
