### ISSUE TITLE
Code generation issue on return type void - Java 

### ISSUE THREAD

**Issue by emirozer** [swagger-api/swagger-codegen#2361]
Hi,

Hope this is the right repo to report this problem.
In the swagger definition file if i set the return type to be `"void"`
PS: yes its actually not a type, but not specifying a type at all doesn't end up as being `void`
Swagger generates the following example function:

```java
public Void Something()
```

`Void` is not a keyword in Java, `void` is :) so this fails.

So maybe having no return type defaulting to `void` might be a solution.

Thanks !

**Comment by ePaul** [comment]
Actually, there is the class `java.lang.Void`, which is used here as a type. That class has no instances, so that method can only return `null`. (Though I agree that it should be `void` instead.)

**Comment by wing328** [comment]
@emirozer can you share the spec? If the endpoint does not return anything in the response body, there's no need to set the response (2xx)

**Comment by emirozer** [comment]
@ePaul i learn a new thing everyday :) you have point, thanks for the feedback..

@wing328, yes below is an example, PUT operation schema type, i want that method to be `void`, i set to void expecting the generated one would be `void`. (this was the observation i made), but instead it is `java.lang.Void` as Paŭlo pointed out
```
/endpoint/{endpoint}/app/{url}/buildstatus:
      put:
        operationId: "buildStatus"
        x-swagger-router-controller: "App"
        parameters:
          -
            $ref: "#/parameters/Endpoint"
          -
            $ref: "#/parameters/App"
          -
            name: "buildStatus"
            in: "body"
            schema:
              type: "void"
        responses:
          200:
            description: "Put App buildstatus"
            schema:
              type: "string"
          default:
            description: "Unexpected error"
            schema:
              $ref: "#/definitions/Error"
```

**Comment by wing328** [comment]
The method returns a "string" (as defined in response 200). Removing that will set the function return type to void.

**Comment by wing328** [comment]
@emirozer closing this for now. Let us know if you need further assistance.

**Comment by dharapatel06** [comment]
`responses:
        '200':
          description: Changed successfully
        '400':
          description: Invalid status value`

Even though there is no "string" type in response. I am facing the same issue. 
Return value is still "Void" instead of "void".
