### ISSUE TITLE
Java Client Codegen (2.1.2) - Response content-type xml.

### ISSUE THREAD

**Issue by vinimk25** [swagger-api/swagger-codegen#2364]
Hi,
 I have generated Jaxrs server side code and Java by Swagger 2.0 codegen (2.1.2) and the example pet_store.json template. I am trying to test Java client code and found that the deserialisation of an object returned by the server works only when it is returns in Json format, If i specify the content-type as xml then it is not working. seems like there is no xml serialization code available. Please let me know does the newer versions of codegen supports this or if there is anything being developed on this front.

Regards,
Vinay.

**Comment by wing328** [comment]
@vinimk25 the latest stable version is 2.1.5 and next release 2.1.6 is on the way. (2.1.2 was released quite a while ago)

I would suggest you to try the latest master to see if the issue still occurs.

**Comment by wing328** [comment]
@vinimk25 closing this as there's no update.
