### ISSUE TITLE
[C#] Requests should set User-Agent

### ISSUE THREAD

**Issue by jqr** [swagger-api/swagger-codegen#2367]
Revision: 62fbcb9e8bec4a40569e51c7f316af85806628ee

Most of the generated clients set a User-Agent to something like `ruby-swagger-1.2.3`. But the Csharp client does not.

The User-Agent string is really handy for server side debugging of client issues as well as alerting customers to new versions or issues with their deployed version.

You can see how we're currently fixing this in the generated clients in https://github.com/DocRaptor/docraptor-csharp/commit/245cdbc4f068b08405047c670ef93f972727cbdd

At the risk of overloading this issue, I'd love to see a standard way for specifying this version string in the `language-config.son` so that we could have consistent use across languages. Has that been discussed?

**Comment by wing328** [comment]
@jqr agree with you that it's better to make the user agent configurable. I'll spend some time tomorrow (Sunday) to implement it for C# to begin with if it's not very urgent.

**Comment by jqr** [comment]
Not urgent at all. Thanks for your attention!

**Comment by wing328** [comment]
Fixed by https://github.com/swagger-api/swagger-codegen/pull/2376.

Please pull the latest and let us know if you still find issue setting user agent for C# API client.
