### ISSUE TITLE
Getting generated java client to use LocalDate instead of Date

### ISSUE THREAD

**Issue by jonocodes** [swagger-api/swagger-codegen#2377]
My server is Jersey/Java8. I am generating a spec. Then I am generating a Java client from the spec. I would like to use java.time.LocalDate in the client and server, but the generated client it is showing java.util.Date objects. I am running codegen with Java 8. Maybe there is something else I need to enable to get this to work?

More specifically...

I have several different date types in my application. One type we need to handle is a date without a time (ie - 2016-03-14). I am trying to use java.time.LocalDate for this on my server.

The swagger.json it generates shows a model with

"startdate" : {
  "type" : "string",
  "format" : "date"
},

According to the swagger spec documentation 'date' is defined by full-date in the json spec. Can the generated java client use java.util.LocalDate instead of java.util.Date ?

**Comment by fehguy** [comment]
Yes, there is an option to enable java8 dates.  Please use `-DdateLibrary=java8`

**Comment by jonocodes** [comment]
Fantastic. I was using 2.1.5 so I see this was not implemented yet, so now I have compiled codegen master (sidenote - compilation appears to be using JDK 7, but I presume that does not matter).

The generated client still does not appear to be using DateLocal. Maybe I am using it incorrectly?

java -jar -DdateLibrary=java8 $HOME/applications/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://localhost:8080/v1/swagger.json -l java -o ./java -c ned_java.json

**Comment by fehguy** [comment]
Ah, if you're using a configuration file with the `-c ned_java.json`, you should add it in there:

```
{
  "dateLibrary": "java8"
  ...
}
```

**Comment by jonocodes** [comment]
Thanks. That did the trick.

**Comment by jonocodes** [comment]
This is working for turning my 'date' objects into 'LocalDate', but now that I am using the Java 8 flag it has changed my 'date-time' objects to use LocalDateTime.

According to the JSON spec, it would seem that date-time should use java.util.Date class since it includes a timezone. Or perhaps it should use java.time.ZonedDateTime?

http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14

**Comment by wing328** [comment]
@jonocodes please pull the latest master to give it a try as there're several PRs (listed in https://github.com/swagger-api/swagger-codegen/issues/2874) to improve datetime handling in Java API clients.

**Comment by prateek2007** [comment]
in case of "dateLibrary": "java8", DateFormatter is =DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)
which accepts date of format 12/6/19

**Comment by omrihq** [comment]
Trying to run: 
`swagger-codegen generate -i test-swag.yaml -DdateLibrary=java8 -l scala` but not seeing LocalDates, do I need to do something different for scala?
