### ISSUE TITLE
Question: Clojure: How to override the generated default base-url?

### ISSUE THREAD

**Issue by urzds** [swagger-api/swagger-codegen#2382]
`swagger-codegen` appears to take the API specification of my service:
```json
{
  "swaggerVersion": "1.2",
  "apiVersion": "v1",
  "basePath": "https://...",
  "resourcePath": "/api/v1",
  ...
```

And then generates following code from this:
```clojure
; src/kubernetes/core.clj
(def default-api-context
  "Default API context."
  {:base-url        "https://.../"
```

Is there any way to override the generated `:base-url`?

The swagger spec was generated by a private instance of a Kubernetes cluster, but I would still like to publish the generated code -- without disclosing the IP address of our private cluster, of course.

**Comment by xhh** [comment]
@urzds The default base URL is generated from the provided swagger spec (see [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L155)), which could be overridden in runtime via the `with-api-context` macro (see [here](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/clojure/test/swagger_petstore/core_test.clj#L24) for an example).
To change the default base URL, is it possible for you to update the path in your swagger spec before generating the Clojure client?

**Comment by urzds** [comment]
> To change the default base URL, is it possible for you to update the path in your swagger spec before generating the Clojure client?

No, the Swagger spec is generated directly from a running Kubernetes Apiserver. I have no influence on the spec generation.

**Comment by wing328** [comment]
@urzds As mentioned by @xhh, you can use `with-api-context` to override the default base path. Please given it a try.

**Comment by urzds** [comment]
The Kubernetes API is available in Swagger format at: https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.2/api/swagger-spec/v1.json
Thus I stepped away from generating it myself from our own, private instance of Kubernetes and the `with-api-context` method you describe is now sufficient.
