### ISSUE TITLE
Use build.sbt for generated Scala files, instead of pom.xml

### ISSUE THREAD

**Issue by ngocdaothanh** [swagger-api/swagger-codegen#241]
Currently, the generated Scala files are used with a pom.xml file. It should be build.sbt by default.

**Comment by wing328** [comment]
@ngocdaothanh agree that build.sbt is preferable to pom.xml for scala.

Do you mind coming up with a sample build.sbt for https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/scala ? Then we'll use it to come up with a build.mustache template.

Thanks in advance.

**Comment by wing328** [comment]
Closed via #3149
