### ISSUE TITLE
Python client delete method body ignored

### ISSUE THREAD

**Issue by scottrw93** [swagger-api/swagger-codegen#2410]
The body for a DELETE method is completely ignored by the Python client as can be seen from the following snippet of code from rest.py, particularity the last three lines:

            if method in ['POST', 'PUT', 'PATCH', 'OPTIONS']:
                if query_params:
                    url += '?' + urlencode(query_params)
                if headers['Content-Type'] == 'application/json':
                    r = self.pool_manager.request(method, url,
                                                  body=json.dumps(body),
                                                  headers=headers)
                if headers['Content-Type'] == 'application/x-www-form-urlencoded':
                    r = self.pool_manager.request(method, url,
                                                  fields=post_params,
                                                  encode_multipart=False,
                                                  headers=headers)
                if headers['Content-Type'] == 'multipart/form-data':
                    # must del headers['Content-Type'], or the correct Content-Type
                    # which generated by urllib3 will be overwritten.
                    del headers['Content-Type']
                    r = self.pool_manager.request(method, url,
                                                  fields=post_params,
                                                  encode_multipart=True,
                                                  headers=headers)
            # For `GET`, `HEAD`, `DELETE`
            else:
                r = self.pool_manager.request(method, url,
                                              fields=query_params,
                                              headers=headers)

Is this by design, as by my understanding the body should be passed for all methods, not just PUT and POST?

**Comment by wing328** [comment]
@scottrw93 it's *not* by design. DELETE operations can have HTTP body.

**Comment by scottrw93** [comment]
Ok thanks, I wasn't sure whether this was desired behaviour as some people consider it bad practice to use HTTP body with delete. So this should also be the case for GET operation?

**Comment by wing328** [comment]
Technically a GET operation can include HTTP body. 

Can you share your use case on why the HTTP body is needed in the GET request?

Ref: http://stackoverflow.com/a/983458/677735

**Comment by scottrw93** [comment]
I don't actually have one, I was actually reading the same stackoverflow answer and saw that it was supported but should not be used.

**Comment by wing328** [comment]
so is it correct to say Python API client works with your spec without issue and your question is more for design-related discussion?

**Comment by scottrw93** [comment]
For GET it works with my spec, I am not passing a http body, for DELETE it does not work as I need to pass a body
