### ISSUE TITLE
Provide support for JSR-303 annotations

### ISSUE THREAD

**Issue by kkrauth** [swagger-api/swagger-codegen#2412]
Enable ability to turn on JSR-303 bean validation annotations for the generated model.

**Comment by wing328** [comment]
@kkrauth thanks for the feedback. Would you have cycle to contribute the enhancement?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
Discussion moved to #2549
