### ISSUE TITLE
Default iOS reachability status

### ISSUE THREAD

**Issue by Stuart-campbell** [swagger-api/swagger-codegen#2422]
Hi,

Currently the default reachability status is 'AFNetworkReachabilityStatusNotReachable' this is causing me issues when attempting to check the status as my application starts up.

I suggest that the default status should be 'AFNetworkReachabilityStatusUnknown' as this is true at this point in the application lifecycle.

If this seems like reasonable suggestion happy to create a PR.

Effected line. https://github.com/swagger-api/swagger-codegen/blob/23696c5eb36d77be670e199d91a6818683ec1191/modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache#L9

Side note: Thanks for the great work on the library!!

Thanks
Stuart

**Comment by wing328** [comment]
@Stuart-campbell thanks for suggestion and offering help to contribute a PR.

I'm not sure if changing default status from "AFNetworkReachabilityStatusNotReachable" to "AFNetworkReachabilityStatusUnknown" would break any existing applications that use the ObjC SDK. What about adding a CLI option to make the status configurable (and default to AFNetworkReachabilityStatusNotReachable)?

(btw, I used the ObjC SDK a month ago but didn't encountered the issue you mentioned)

**Comment by Stuart-campbell** [comment]
@wing328 

My issue is actually a result of the cache force fallback.

https://github.com/swagger-api/swagger-codegen/blob/23696c5eb36d77be670e199d91a6818683ec1191/modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache#L598

I need to always force network as knowing the date the data was returned from the server is important. The library forces cache if offlineState=true but there is no getting for offline state so I check the reachability which sets the offlineState.

On first load offlineState is default to false and reachabilityStatus defaults to AFNetworkReachabilityStatusNotReachable so at this point the two are out of sync meaning your requests will not be forced to use cache but reachabilityStatus is NotReachable.

My suggestion for ReachableUnknown is based on that seeming most logical but I fully understand not wanting to change something it could cause issues for other people. Either a setter reachability status or a getting for offlineState would solve my issue.

I would like to tell it not to use cache if offline but I don't have as good justification for that.

Thanks

**Comment by wing328** [comment]
> Either a setter for reachability status or a getter for offlineState would solve my issue.

Your suggestion sounds good to me. Let us know if you need help implementing the getter/setter.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by Stuart-campbell** [comment]
Create a PR with the updates.

https://github.com/swagger-api/swagger-codegen/pull/2426

Thanks

**Comment by wing328** [comment]
PR merged. Please pull the latest master. Thanks for the contribution.
