### ISSUE TITLE
Documentation about writing templates

### ISSUE THREAD

**Issue by Nepoxx** [swagger-api/swagger-codegen#2428]
The README focuses on usage but not much else. I want to write a template for another language, but there's no information on which variables to use in the template. Where would I find this information?

(For instance, what is {{returnType}}? Is that the 200 response type? etc. (I know this particular one btw, just providing an example))

**Comment by wing328** [comment]
@Nepoxx would this help? https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables

**Comment by Nepoxx** [comment]
@wing328 Absolutely! Sorry I didn't find that page on my own. Thank you!

**Comment by wing328** [comment]
@Nepoxx np. If you don't mind, can you tell us a bit more about your work/customization on Swagger Codegen? Are you adding a new language code generator?

**Comment by Nepoxx** [comment]
@wing328 I don't mind :). I'm modifying https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/CsharpDotNet2 to work with Unity3d natively.

The way it is right now, it is using RestSharp's sync functionality, but we're modifying it so it uses RestSharp for unity3d and uses unity's json serialization.

My understanding is that I should copy https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java as-is (maybe change the package name/class name, but otherwise as-is) with my mustache templates instead. 

Does that make sense?

**Comment by wing328** [comment]
If my memory serves me well, CsharpDotNet2 should work with Unity3d.

cc @who (the author of CsharpDotNet2)

**Comment by Nepoxx** [comment]
I think it does, however as far as I know it does so synchronously. I'd definitely like @who 's input on this!
