### ISSUE TITLE
[swift]swagger client export issue

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2430]
_From @riceman2 on March 18, 2016 2:14_

When outputting a model that was created in Swagger Editor , key chain case is turned to the Lower camel case , you can not get the correct value .

for example

[key-color]
to
instance.keyColor = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["keyColor"])

_Copied from original issue: swagger-api/swagger-editor#846_

**Comment by wing328** [comment]
@riceman2 the issue has been fixed in the latest master of Swagger Codegen
