### ISSUE TITLE
Java Codegen's SimpleDateFormat is incompatible with Android

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-codegen#2431]
The generated ApiClient.java produces this 

```
    // Use RFC3339 format for date and datetime.
    // See http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14
    this.dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");

```

Android doesn't support this DateFormat and throws this error:

`System.err: Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'`

Does it make sense to switch back to a DateFormat that is compatible with both Oracle Java and Android?

**Comment by wing328** [comment]
@maneeshsahu are you using the latest Java API client with the `default` (jersey1.x) in swagger-codegen `master`?

**Comment by maneeshsahu** [comment]
@wing328 Yes, I am using the default. Do you recommend I generate one for java/jersey and another for java/android ?

**Comment by wing328** [comment]
@maneeshsahu nope, that's not something I would recommend.

Can you use the `okhttp-gson` library for Java instead?

**Comment by maneeshsahu** [comment]
Regenerated with okhttp-gson as the library and the DateFormat issue is resolved. Q - Is okhttp a worthwhile library upgrade for both Java and Android?

**Comment by cbornet** [comment]
@maneeshsahu Yes okhttp is a very good lib for Android. You can also use the retrofit lib which uses okhttp internally and has less generated code.
As for the dateLibrary, I strongly recommend using joda on Android which is now the default on current master.

**Comment by wing328** [comment]
@maneeshsahu please pull the latest master and give it a try as suggested by @cbornet 

Issue closed.
