### ISSUE TITLE
About the "content type" in rest.py of python client

### ISSUE THREAD

**Issue by WillaLuo** [swagger-api/swagger-codegen#2432]
Hi, the rest.py of the python client generated by swagger-codegen like this :

try:
           # For `POST`, `PUT`, `PATCH`, `OPTIONS`
           if method in ['POST', 'PUT', 'PATCH', 'OPTIONS']:
               if query_params:
                   url += '?' + urlencode(query_params)
               if headers['Content-Type'] == 'application/json':
                   r = self.pool_manager.request(method, url,
                                                 body=json.dumps(body),
                                                 headers=headers)
               if headers['Content-Type'] == 'application/x-www-form-urlencoded':
                   r = self.pool_manager.request(method, url,
                                                 fields=post_params,
                                                 encode_multipart=False,
                                                 headers=headers)
               if headers['Content-Type'] == 'multipart/form-data':
                   # must del headers['Content-Type'], or the correct Content-Type
                   # which generated by urllib3 will be overwritten.
                   del headers['Content-Type']
                   r = self.pool_manager.request(method, url,
                                                 fields=post_params,
                                                 encode_multipart=True,
                                                 headers=headers)
           # For `GET`, `HEAD`, `DELETE`
           else:
               r = self.pool_manager.request(method, url,
                                             fields=query_params,
                                             headers=headers)
       except urllib3.exceptions.SSLError as e:
           msg = "{0}\n{1}".format(type(e).__name__, str(e))
           raise ApiException(status=0, reason=msg)
       r = RESTResponse(r)

How can I add a case when our project use a specified name "'application/xx-xx-v3+json'" replace the "application/json" in headers.? That means I need add a case manually in the rest.py if I want get a success response:

if headers['Content-Type'] == 'application/xx-xx-v3+json':   
                    r = self.pool_manager.request(method, url,
                                                  body=json.dumps(body),
                                                  headers=headers)

Does this have a auto method? should I modify some file like a template before generated the client with swagger-codegen ?

Thanks a lot !

**Comment by wing328** [comment]
You need to modify your spec to set a proper "consumes": https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L73

**Comment by WillaLuo** [comment]
The spec of our project set the consumes to "application/xx-xx-v3+json", because our api server design the api with "application/xx-xx-v3+json" as content-type and accept. This is a special design of our product for different from other company's product. 

There are also some other special use, like ant type of body data is supported by our api.
I wonder if there is possible for us to modify the rest.py by ourselves? 
Or if java client support this?

**Comment by wing328** [comment]
If your spec sets the consumes to `application/xx-xx-v3+json`, then the auto-generated Python API client should work correctly for that endpoint. Can you share the spec so as to better illustrate the issue?

**Comment by wing328** [comment]
I think i know what you mean. The solution should be updating the following line:
```
if headers['Content-Type'] == 'application/json':
```
with regular expression to look for 'application/(.*)json' instead.

This is the line in the mustache template that needs to be updated: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/rest.mustache#L140

Would you have cycle to contribute a PR (pull request)?

**Comment by WillaLuo** [comment]
Hi, 
 Sure, but this is only used by our company, maybe there is no need to update it in the rest.mustache file. So I want to know how to specify our the rest.mustache to generate python client source. Can you tell me how to do it?  or  give me some information. 
appropriate for you help !
Thanks.

**Comment by wing328** [comment]
OK. You can provide customised template by specifying the directory using the `-t` command line argument:
```
                [(-t <template directory> | --template-dir <template directory>)]
```

Please refer to the README for more information.

**Comment by WillaLuo** [comment]
Thanks, I misunderstand "template directory" to "template file". I know what's wrong.

Thanks a lot!
