### ISSUE TITLE
[JavaScript] Need option for withCredentials

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#2442]
In order to be able to send cookies to the server, we need to call `request.withCredentials()` in `ApiClient.js`. See [the superagent documentation](https://visionmedia.github.io/superagent/#cors). This should be an option, as it may not always be desirable.

In my case, I am calling a server on a different URL, which means I have to use CORS, and I am using cookies for session management (set by Java through the use of `@SessionScoped` beans).

I will submit a PR to add such an option if there are no objections.

**Comment by fehguy** [comment]
cookies aren't supported by the specification, which is why they're not supported in the client.  So I suggest not doing this, it encourages unsupported behavior.

**Comment by delenius** [comment]
The only alternative, for my use case, is to write a lot of server-side (and some client-side) code to maintain sessions manually. This way, all that stuff is handled automatically by Java annotations.

Until the swagger spec supports this, I need some way of doing it. It's just an option, which is disabled by default.

**Comment by wing328** [comment]
@fehguy is it something you would consider given that it's an option disabled by default?

Understood that it's not supported by the spec and I think clearer description of the CLI option (disabled by default) can help reinforce the message that cookies aren't supported by the spec.

**Comment by cbornet** [comment]
@fehguy withCredentials is used to authorize the browser to add the authentication cookie when doing a cross-site request. So this is not really related to the spec but more to javascript client configuration.

**Comment by delenius** [comment]
@cbornet , that's an argument in favor of allowing this option, right? I don't see any other way to do this...

**Comment by delenius** [comment]
I changed the PR to do this in a better way. Now, it is no longer an option for the generator. Instead, the client simply needs to set the `ApiClient.withCredentials` flag to `true` to achieve the same result.
