### ISSUE TITLE
[Swift] Array body parameter get lost because of cast into dictionary.

### ISSUE THREAD

**Issue by orkenstein** [swagger-api/swagger-codegen#2448]
Generated example:
```
public class func method(someId: Int, arrayParam: [Value], startDate: NSDate?, endDate: NSDate?) -> RequestBuilder<Response> {
     var path = "/listings/{someId}/method"
     path = path.stringByReplacingOccurrencesOfString("{someId}", withString: "\(someId)", options: .LiteralSearch, range: nil)
     let URLString = SwaggerClientAPI.basePath + path
            
     let parameters = arrayParam.encodeToJSON() as? [String:AnyObject]

     let requestBuilder: RequestBuilder<Response>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

     return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: false)
}
```

As you can see `arrayParam` is getting converted into `dictionary` and will produce `nil` all the time.
Other parameters get lost too, 'cause they not even included in request parameters.

**Comment by wing328** [comment]
@orkenstein sorry for late reply on this. Do you mind pull the latest master and see if the issue persists?

We've just released stable version v2.1.6 and want to know if this is still an issue.

**Comment by wing328** [comment]
@orkenstein closing this as there's no update.

**Comment by saltwat5r** [comment]
I have the same issue...

**Comment by wing328** [comment]
Please try the `swift` or `swift3` generator in 2.3.0 branch, which has a lot of enhancements (breaking changes) and bug fixes.

If it's still an issue, please open a new one with the details.
