### ISSUE TITLE
 maven version number incorrect in readme

### ISSUE THREAD

**Issue by arilynN** [swagger-api/swagger-codegen#2454]
The Maven number is incorrect in the maven readme file. I tried to build the samples with maven 3.0.5 and the readme says 3.0.3 is minimal required and i got a exception. Now im running maven 3.3.9 and its working fine.

**Comment by wing328** [comment]
@arilynN thanks for reporting the issue. Version updated.

https://github.com/swagger-api/swagger-codegen/blob/master/README.md#prerequisites
