### ISSUE TITLE
Swagger-codegen prints everything on terminal instead of logging!

### ISSUE THREAD

**Issue by rnavagamuwa** [swagger-api/swagger-codegen#2455]
I'm using swagger codegen as a maven dependency for one of my projects and I really need to have a proper log. But instead of logging in prints everything on terminal. Why can't that be removed and add a log instead?

**Comment by wing328** [comment]
@rnavagamuwa are you using the latest master?

**Comment by rnavagamuwa** [comment]
@wing328 I'm using this one [http://mvnrepository.com/artifact/io.swagger/swagger-codegen/2.1.5](url)

**Comment by wing328** [comment]
please use the latest master or wait for 2.1.6 release, which will be due soon.

**Comment by rnavagamuwa** [comment]
Sure thanks :+1:
