### ISSUE TITLE
[Typescript] Generated code exports classes with reserved names e.g. Object {}

### ISSUE THREAD

**Issue by bherila** [swagger-api/swagger-codegen#2456]
The generated .ts file contained this code: 

```
export class Object {
}
```

which leads to a compile error when trying to build the file: 

```
error TS2339 Property 'keys' does not exist on type 'typeof Object'.
```

**Comment by wing328** [comment]
@bherila can you share your spec? My guess is that it contains an empty definition of the object `Object`.

**Comment by bherila** [comment]
Yup, you are right. So this might be an issue for Swashbuckle. https://github.com/domaindrivendev/Swashbuckle

```
definitions: {
    Object: {
        type: "object",
        properties: {}
    },
}
```

However, is there a more appropriate type for APIs that don't have a well-defined return type? 

```
responses: {
200: {
description: "OK",
schema: {
$ref: "#/definitions/Object"
}
}
},
```

**Comment by bherila** [comment]
I'll bring this issue up with Swashbuckle, but maybe swagger-codegen for Typescript/Javascript should also handle the issue that Object is not a valid name to be used in a generated type? Similar to https://github.com/swagger-api/swagger-codegen/issues/2457

**Comment by webron** [comment]
@bherila - That's pretty much how you'd define such a return type.

**Comment by wing328** [comment]
@bherila can you try replacing 
```
schema: {
$ref: "#/definitions/Object"
}
```
with the following instead?
```
"schema": {
 "type": "object"
}
```

Currently codegen is not smart enough to figure out the reference model has not properties.

**Comment by bherila** [comment]
I can try to see if I can make it work as a one-off. 

Unfortunately, the schema definition for this API is auto-generated by Swashbuckle from C# code annotations, and then that output is passed on to swagger-codegen, I can try to patch Swashbuckle but unfortunately it will take a couple of days before I'll have the cycles to do that.

**Comment by wing328** [comment]
I'll open a ticket with Swashbuckle to see if they can simply output `type: object` instead of creating a model "Object".

**Comment by wing328** [comment]
Ref: https://github.com/domaindrivendev/Swashbuckle/issues/698

**Comment by wing328** [comment]
Got a reply from the author of Swashbuckle saying that the fix will be available in 5.4.0 release.

**Comment by pixelshaded** [comment]
I just came across this issue myself. The original issue is a compiler issue. It seems that keys is missing from the node definitions. I added this to my definitions so that I could compile.

```typescript
interface Object {
  keys: (Object) => string[];
}
```

However, the issue of reserved names being generated is not a swashbuckle specific problem. Any swagger spec could create language specific reserved names in definitions. Array might be the next offender. Because this is a language focused concern (in this case, a javascript issue), I think it's the responsibility of the template author to be aware of this potential problem and code against it. In this case, all classes that you could create should be in a namespace to prevent a naming collision with the globals. Right now they are generated at the top of the output file with var ReservedName = IIFE.

**Comment by rgarcia** [comment]
I am running into this with a swagger definition file that had a type named `Error`. The generated typescript code contains an `Error` class, but also internally has calls to the builtin `Error` type, e.g. `throw new Error("...")`. This causes the typescript compiler to complain.

**Comment by wing328** [comment]
@rgarcia thanks for reporting the issue. We can properly escape `Error` by adding it to the reserved word list.

**Comment by kenisteward** [comment]
Should this be closed?  It looks like there has been a PR merged to fix it. #4203

**Comment by wing328** [comment]
@kenisteward yes, just closed it. Thanks for reviewing the issue.

**Comment by bherila** [comment]
Woohoo thanks @wing328 ; I had forgotten about this and can finally deprecate my little script to hack the generated output file 👍
