### ISSUE TITLE
[Typescript] Generated code can contain invalid enum values

### ISSUE THREAD

**Issue by bherila** [swagger-api/swagger-codegen#2457]
When the enum values are also valid numbers, they should be prefixed with a string, e.g.: 

```typescript
export namespace MySampleEnumModel {
    export enum TypeEnum { 
        VALUE_0 = <any> '0',
        VALUE_1 = <any> '1',
    }
}
```

currently the bad code looks like this:
```typescript
export namespace MySampleEnumModel {
    export enum TypeEnum { 
        0 = <any> '0',
        1 = <any> '1',
    }
}
```

this generates a typescript compilation error.

**Comment by wing328** [comment]
@bherila to make my life easier reproducing the issue and come up with a fix, can you please share the spec? If it's private, please send it to my personal email address in my github profile if you don't mind.
