### ISSUE TITLE
Typescript Template Variables: Defining Value for Online Generator

### ISSUE THREAD

**Issue by pixelshaded** [swagger-api/swagger-codegen#2458]
Looking at the template https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache, there should be a way to define classname.

I've been using the online generator and my class name is always being generated as DefaultApi. I've defined classname and className in the options object of the GeneratorInput that is passed to the POST method, but they don't seem to be used. Looking at source code, it seems the server adds everything in options object to additional properties of codegen config, but I'm not sure if that is the right place. Should classname be in system properties? How would I set that via the API?

**Comment by wing328** [comment]
My guess is that your spec does not use "tags" (e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L67)

Can you please share the spec so that we can reproduce the issue?

**Comment by pixelshaded** [comment]
```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Settings UI API
  description: Api for the UI of settings.ignitionone.com
basePath: /api
definitions:
  Entity:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      typeId:
        type: integer
      ancestry:
        type: array
        items:
          $ref: '#/definitions/Entity'
  AddUser:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      empOfEntityId:
        type: number
      empOfEntityTypeId:
        type: number
      email:
        type: string
      isInternal:
        type: boolean
      cultureId:
        type: number
      landingPageId:
        type: number
paths:
  /users:
    x-swagger-router-controller: UserSwaggerController
    post:
      operationId: addUser
      description: |
        Add user.
      parameters:
        -
          name: user
          in: body
          description: User object to add to system.
          required: true
          schema:
            $ref: '#/definitions/AddUser'
      responses:
        200:
          description: Successful response
          schema:
            type: number
            description: id of created user
  /users/{userId}:
    x-swagger-router-controller: UserSwaggerController
    put:
      operationId: updateUser
      description: |
        Add user.
      parameters:
        -
          name: userId
          in: path
          description: User id
          required: true
          type: number
        -
          name: user
          in: body
          description: User object to add to system.
          required: true
          schema:
            $ref: '#/definitions/AddUser'
      responses:
        200:
          description: Successful response
          schema:
            type: number
            description: id of created user

  /users/entities:
    x-swagger-router-controller: UserSwaggerController
    get:
      operationId: entities
      description: |
        Get entities based on type and permission.
        Ancestry is in order from parent to child.
      parameters:
        -
          name: permissionIds
          in: query
          description: Permission ids to filter by
          required: true
          type: array
          items:
            type: integer
        -
          name: entityTypeIds
          in: query
          description: Entity ids to filter by
          required: true
          type: array
          items:
            type: integer
        -
          name: includeAncestry
          in: query
          description: Output will include ancestry (parents in order from top level to lowest level) if true
          type: boolean
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Entity'
```

**Comment by wing328** [comment]
I would suggest you to "try". A endpoint without any tag default to "DefaultApi" and you can use tag to group endpoints into a Api class file. Hope this helps.

**Comment by pixelshaded** [comment]
It does help. I'm going to guess, based on your suggestion, that there is no documentation explaining how tags influence generated code?

**Comment by wing328** [comment]
Unfortunately we don't have that documented at the moment. For Typescript, we can use the following endpoint as an example to illustrate:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L660 (tag: store)

The generate code is in https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-angular/API/Client/StoreApi.ts#L176 (StoreApi)

**Comment by wing328** [comment]
FYI. I've started building an FAQ here: https://github.com/swagger-api/swagger-codegen/wiki/FAQ

Hopefully others would find it useful as we accumulate more and more questions and answers

**Comment by pixelshaded** [comment]
NIce. Thanks for the follow up.

Things to Consider Adding to FAQ
In the POST body (modeled after GeneratorInput), what is options supposed to represent? From service source code it seems like it is simply the same as additional properties if you were using the command line.

Note that apiPackage and modelPackage in options affects namespace of output.

**Comment by wing328** [comment]
Please feel free to "edit" that FAQ page with the suggested details.

**Comment by pixelshaded** [comment]
Updated with a code example for hitting API and unzip files to a folder.

> In the POST body (modeled after GeneratorInput), what is options supposed to represent?

This one however I don't have a direct answer for so nothing to put in the FAQ
