### ISSUE TITLE
How to generate definition of enum witrh java ?

### ISSUE THREAD

**Issue by mariomatar** [swagger-api/swagger-codegen#2474]
Hi 

I use Spring boot, swagger-maven-plugin and springfox-swagger2 with last versions

I just want to have enums in my definitions  

   public class OrderDto {
            private String id;
            private OrderTypeEnum type;

Currently : 

    "OrderDto" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string",
          "enum" : [ "A", "B" ]
        },

But I want someting like this : 

    "OrderDto" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "type" : {
          "type" : "string",
          "items" : {
            "$ref" : "#/definitions/OrderTypeEnum"
          }
        },

Have you an idea ?

**Comment by fehguy** [comment]
Yea, that's not really valid.  Try using http://editor.swagger.io which will give you some interactive feedback on the validity of your spec.  What you listed first is correct.

**Comment by mariomatar** [comment]
I use swagger.json to generate javascript API Client and Models classes

If I have to classes use OrderTypeEnum, it will generate 
ClassAOrderTypeEnum
ClassBOrderTypeEnum

It's not good

**Comment by fehguy** [comment]
Please read the README.  If you don't like the generation, you can choose how to handle it.  You can even disable enums and use strings, it's in the options.

**Comment by mariomatar** [comment]
ok
thanks for your replay
