### ISSUE TITLE
2.1.6-SNAPSHOT broken on Sonatype repo

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2480]
It seems the currently deployed SNAPSHOT (https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen/) itself depends on swagger-parser 1.0.18-SNAPSHOT which is not available anymore (1.0.18 is released and SNAPSHOT is 1.0.19). Maybe the SNAPSHOT should be redeployed? (I'm not sure this SNAPSHOT is officially supported, but it is useful to me at least ;)).

**Comment by wing328** [comment]
@cjolif thanks for reporting.

cc @fehguy

**Comment by wing328** [comment]
@cjolif we should be able to release v2.1.6 today (Tue) or tomorrow (Wed)

**Comment by cjolif** [comment]
cool thanks!

**Comment by fehguy** [comment]
Thanks, I've updated it to the release version, and 2.1.6 should be out soon.

**Comment by cjolif** [comment]
believe it or not but this is broken again ;) (because parser released 1.01.9 so SNAPSHOT is now 1.0.20). As 2.1.6 should be out soon I guess this can wait. But this makes me think that your snapshot might better depend on a release version of parser to avoid this issue as they seem to release quite often?

**Comment by cjolif** [comment]
@wing328 @fehguy will you publish a 2.2.0-SNAPSHOT as you were doing for 2.1.6? The reason I'm asking is that my workflow relies on that ;) The more frequent you could to that the better for me. Otherwise I will look into a different workflow if that is not something you would like to pursue.

**Comment by ePaul** [comment]
@cjolif I think you should not rely on SNAPSHOTs from projects which are not under your control. Or maybe compile it yourself (or have some job which compiles it for you) and upload to your own Maven repository?

**Comment by ePaul** [comment]
On the other hand, for this project:
* We should try not to depend on SNAPSHOT dependencies which are not in the same repository (i.e. which are updated together).
* We should try to actually release more often than once every few months, so people can use the released versions to get their new features/bug fixes instead of having to rely on SNAPSHOT versions.

**Comment by fehguy** [comment]
I'll try to get travis to start uploading snapshots.

**Comment by cjolif** [comment]
@ePaul I agree my production workflow should not include these snapshots. But I'm in experimental mode right now and doing contributions , and getting the snapshot working would be helping.

**Comment by webron** [comment]
The projects that the codegen depends on are still under swagger-api. Given the nature of the projects development and the dependencies between them, it is inevitable to have SNAPSHOTs depend on other SNAPSHOTs. We don't have the capacity to do an intense release cycle and if we wait for a stable release for each dependency (swagger-parser, swagger-core) to solve issues in the codegen, we'll get nowhere.

When we release stable releases, we do those without SNAPSHOTs, obviously. It's our job, of course, to make sure that when we do make such releases, to update the depending projects accordingly, either by making them depend on the stable release (for as long as it can) or by updating it to depend on the next SNAPSHOT.

I believe we should try to make more frequent releases for the projects as a whole though, and trying to come up with a plan for it now.
