### ISSUE TITLE
[Swift] Operations with both query-based parameters & body-based parameters are not working

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2483]
If in your operations you have something as follows:

``` js
             {
                        "name": "param1",
                        "in": "query",
                        "required": false,
                        "type": "string",
                        "enum": [
                            "true",
                            "false"
                        ]
                    },
                    {
                        "name": "param2",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/MyType"
                        }
```

The generated swift will contain something of the following form:

``` swift
 public class func myOperationWithRequestBuilder(param2: MyType, param1: String?) -> RequestBuilder<> {
        var path = ...
        let URLString = SwaggerClientAPI.basePath + path

        let parameters = param2.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: false)
```

ignoring the query parameter (param1) and passing isBody false to the init.

The root limitation is that Alamofire either send parameters as query parameters or body but can't do both.

**Comment by wing328** [comment]
@cjolif may I know if you or someone has already opened a ticket with https://github.com/Alamofire/Alamofire/ team? (I did a search in that repo but couldn't find one)

**Comment by cjolif** [comment]
no, but actually in the interim someone told me that using lower-level Alamofire APIs (i.e. not the high level API used in swagger-codegen) it should be feasible. I don't have the details however.

**Comment by HSchultjan** [comment]
Im willing to work on this issue. 
I already have a mustache template that will properly encode query parameters for POST requests, but since Alamofire doesn't really support this its a quite hacky solution which i would like to avoid.
Im trying to find a clean solution. So if you have any ideas where to start, please comment.

**Comment by fehguy** [comment]
Typically we've been building the URL manually in other languages.  I believe this was the same approach in the Objective-C library here, which also uses AFNetworking.  So I don't see a way around doing that.

**Comment by HSchultjan** [comment]
Okay. Do you have any coding conventions/guidelines?

**Comment by wing328** [comment]
@HSchultjan please have a look at https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
@cjolif @HSchultjan the fix by @tomekc has been merged into master. Please pull the latest to give it a try.
