### ISSUE TITLE
Enumerations with non-alphanumeric characters

### ISSUE THREAD

**Issue by degroves** [swagger-api/swagger-codegen#2487]
[JSON spec and generated Java code](https://gist.github.com/degroves/4e1af1a72779c59b60ef42c731c61cbd)

I generated java code using 2.1.5:

java -jar swagger-codegen-cli.jar generate -i enum_example.json -l java -o target

Unless I've misinterpreted the JSON schema specification (json-schema.org/latest/json-schema-validation.html), an enumeration of type string can have any Unicode character in the enumeration name.  While using mathematical symbols is unusual, they are Unicode characters and so the swagger code generator should generate Java code which can compile for this enumeration.

**Comment by wing328** [comment]
Welcome to GitHub and thanks for reporting the issue. For your case, what's the expected `MyEnum.java` look like from your perspective?

**Comment by sbelan** [comment]
@wing328 .. similarly, if ENUMS are case sensitive... Swagger always creating enum with UPPERCASE
e.g:
In my case server is expecting value as Success and Fail, so I mentioned the same in swagger specification but during client creation swagger always created it in uppercase like SUCCESS and FAIL.
I did quick fix for this but let me know your advice on this.

**Comment by wing328** [comment]
@sbelan please open a separate issue for tracking and provide more information such as spec to reproduce the issue and which language(s) you're referring

**Comment by degroves** [comment]
@wing328: Something along these lines:



    public enum MyEnum
    {
        LESS_THAN("<"), NOT_EQUALS("!="),  EQUALS("=");

        private final String description;

        MyEnum(final String description)
        {
            this.description = description;
        }

        public static void MyEnum getByDescription(final String description)
        {
            // Some efficient mapper here
        }
    
    }


This might also solve the problem @sbelan described.  You could have SUCCESS map to "Success" and FAIL map to "Fail".

The problem is how to come up with a generalized mapping.  I don't have a solution for that.  There's a lot of characters in the Unicode character set.  You might need some user input to come up with a good mapping.

**Comment by sbelan** [comment]
@degroves .. we resolved this issue by overriding postProcessModels() from JavaClientCodegen and changed logic for enum during inserting into enum map.

**Comment by degroves** [comment]
@sbelan, thanks for the pointer, I might do the same.

**Comment by wing328** [comment]
@degroves #3519 (for Java-related generators) merged into master to provide the mapping between symbol and symbol name. 

Please pull the latest to give it a try.

**Comment by wing328** [comment]
@sbelan the issue you mentioned should be fixed by https://github.com/swagger-api/swagger-codegen/pull/3531. Please pull the latest master to give it a try.

**Comment by degroves** [comment]
@wing328 : I tried out the fix.  It looks good.  Thanks!
