### ISSUE TITLE
petstore.json contains typos

### ISSUE THREAD

**Issue by vipera** [swagger-api/swagger-codegen#2489]
Hiya,

I'm new to this project, but there seem to be a couple of errors/typos in modules/swagger-codegen/src/test/resources/2_0/petstore.json that prevent the example Sinatra server from being generated with `$ ./bin/sinatra-petstore-server.sh`.

One example:
```json
"Return": {
  "descripton": "Model for testing reserved words",
```

Instead of:

```json
"Returns": {
  "description": "Model for testing reserved words",
```

The consequent error:
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Return'
```

I can make a pull request with the fix if this really is an error with the file in question (and I suspect it is).

**Comment by wing328** [comment]
@vipera thanks for reporting the issue. I'm fixing it now.

**Comment by wing328** [comment]
@vipera I've submitted #2490 to fix it.

The typo (which is fixed by this PR) does not cause the exception though.

It's due to model name using reserved words (e.g. return) and Sinatra code generator has not been updated to handle that yet.

**Comment by wing328** [comment]
As part of this PR, `./bin/sinatra-petstore-server.sh` uses the original petstore spec (without the additional models I added for testing) and you should not get any error when running the command again.

**Comment by vipera** [comment]
@wing328 Ah, I see. Thanks for the explanation and fix!

**Comment by wing328** [comment]
@vipera np. Let me know if you need any help with Sinatra or other API client/server code generator.
