### ISSUE TITLE
[Android] Generated sample for Android Volley does not compile

### ISSUE THREAD

**Issue by fabdslv** [swagger-api/swagger-codegen#2492]
Here is the error : 

```
C:\development\projects\android-swagger-petstore-sdk-volley\src\main\java\io\swagger\client\ApiInvoker.java:196: error: cannot find symbol
     INSTANCE.authentications.put("petstore_auth", new OAuth());
                                                       ^
  symbol:   class OAuth
  location: class ApiInvoker
```

It seems that there's a missing dependency to OAuth.

**Comment by wing328** [comment]
@fabdslv I think that's fixed in the latest master. Please pull the latest to give it a try.

**Comment by fabdslv** [comment]
@wing328 Yes, it compiles with the latest master version. Sorry for opening this defect, I'll close it.
Thanks.

**Comment by wing328** [comment]
@fabdslv it's also worth sharing with you that the Java API client (using e.g retrofit, retrofit2, okhttp-gson, etc) is also compatible with Android.

**Comment by fabdslv** [comment]
@wing328 are you saying it may be more suitable to use Retrofit 2 that Volley in this case? I mean, is the generator for Retrofit better maintained than it is for Volley?

**Comment by wing328** [comment]
@fabdslv I'm saying that you've other options and would suggest you to evaluate those (if you've time) to see whether those better fit your requirement (e.g. to use the API client not only in Android but also Java later on)

**Comment by fabdslv** [comment]
@wing328 Yes, I'm already comparing those solutions. Thanks for your advice.
