### ISSUE TITLE
jaxrs-cxf: borked enum definitions

### ISSUE THREAD

**Issue by 414n** [swagger-api/swagger-codegen#2507]
Hello,
I'm trying to generate JAXRS server code from a Swagger API spec but I'm encountering various issues.

I first tried the jaxrs generator but I had issues with the generated factories and then I tried the jaxrs-cxf generator, as I could see from the online editor that the code generated by the latter is more simple, cleaner and, therefore, more useful to my specific use case.
However, what I did not see at first is that the jaxrs-cxf generator generates totally borked inner enum 
types, while the "pure" jaxrs one generates correct enum specifications like a boss.

Here's an example enum property from my API spec:
```yaml
MyObject:
    type: object
    properties:
      name:
        type: string
      method:
        type: string
        enum:
          - SET_ON
          - SET_OFF
          - TOGGLE
          - SET_BOOLEAN
          - SET_LEVEL
          - SET_STRING
          - SET_COLOR
```
and the generated Java code from the jaxrs-cxf generator:

```java
package io.swagger.model;

import io.swagger.model.DeviceFunctionParam;
import java.util.ArrayList;
import java.util.List;



import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder =
	{ "name", "method", "params"
})

@XmlRootElement(name="MyObject")
public class MyObject  {
  

  private String name = null;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name="MyObject")
@XmlEnum
public enum MyObject {
    {values=[SET_ON, SET_OFF, TOGGLE, SET_BOOLEAN, SET_LEVEL, SET_STRING, SET_COLOR], enumVars=[{name=SET_ON, value=SET_ON}, {name=SET_OFF, value=SET_OFF}, {name=TOGGLE, value=TOGGLE}, {name=SET_BOOLEAN, value=SET_BOOLEAN}, {name=SET_LEVEL, value=SET_LEVEL}, {name=SET_STRING, value=SET_STRING}, {name=SET_COLOR, value=SET_COLOR}]}, 
    
    public String value() {
        return name();
    }

    public static MyObject fromValue(String v) {
        return valueOf(v);
    }
}

  private MethodEnum method = null;

  
  /**
   **/
  
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  /**
   **/
  
  public MethodEnum getMethod() {
    return method;
  }
  public void setMethod(MethodEnum method) {
    this.method = method;
  }
  
  /**
   **/
  

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceFunction {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
```

As you can see, the main issues are:
 - declaration of the class interleaved with that of the enum (side note: are those Xml* annotations really necessary?)
 - wrong enum name, as it takes the name of the class instead of the property (but getters and setters are correctly generated instead)
 -  weird "values" and "enumVars" declaration

As the jaxrs-cxf generator is not in a stable release yet (if I'm not mistaken, it's only in version 2.1.6-SNAPSHOT), I think this issue should be fixed with its mainlining.

**Comment by 414n** [comment]
Just adding that the enums generated by the `jaxrs` generator inside the model classes are indeed good.

**Comment by sbarinov** [comment]
Could you please explain me how to generate classes with XML annotations (like @XmlRootElement and so on)?
I use swagger-codegen-maven-plugin maven plugin and "Generate server" on http://editor.swagger.io/#/ using the jaxrs language and I don't see any xml-related annotations in the result model classes.

here is my plugin settings:

      <plugin>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>2.1.6</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${basedir}/src/main/resources/rest.yaml</inputSpec>
              <language>jaxrs</language>
              <modelPackage>com.test.rest.model</modelPackage>
              <apiPackage>com.test.rest.api</apiPackage>
              <invokerPackage>com.test.rest.invoker</invokerPackage>
              <output>${project.basedir}/</output>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by 414n** [comment]
@sbarinov: sorry, can't help you with that. The XML annotations you might have seen in my snippet before where erroneously generated.

**Comment by wing328** [comment]
@414n #3506 should have fixed it. Please pull the latest master to give it a try.

**Comment by 414n** [comment]
@wing328 I performed a first quick test about this issue and it seems that the generated code is now ok. Will confirm if everything is indeed ok ASAP.
Thank you!
