### ISSUE TITLE
[Java Client - Retrofit 2] Petstore sample does not build when 'target = android' 

### ISSUE THREAD

**Issue by fabdslv** [swagger-api/swagger-codegen#2509]
Here is the error : 

```
C:\development\projects\android-swagger-petstore-sdk-retrofit2\src\main\java\io\swagger\client\StringUtil.java:3: error: package javax.annotation does not exist
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-03-14T22:17:54.660+08:00")
                 ^
Note: C:\development\projects\android-swagger-petstore-sdk-retrofit2\src\main\java\io\swagger\client\ApiClient.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileDebugJava FAILED
```

I think there is a missing dependency (which, by the way, is present in Retrofit 1 sample) : 

```
dependencies {
            provided 'javax.annotation:jsr250-api:1.0'
}
```

**Comment by wing328** [comment]
@fabdslv is that generated using https://editor.swagger.io or the latest master of swagger-codegen?

**Comment by fabdslv** [comment]
@wing328 I used the latest master of swagger-codegen, uncommenting the 'target=android' line in gradle.properties file in order to create an AAR library.

**Comment by wing328** [comment]
@fabdslv to help us troubleshoot, did you get similar error when running `gradle build` in `samples/client/petstore/java/retrofit2`?

(It works fine for me in Mac)

**Comment by fabdslv** [comment]
Yes, I got the error running `gradle build` (but again, only when uncommenting the line `target = android` in gradle.properties file).

**Comment by wing328** [comment]
I wonder if it's related to platform (Windows) and you mention the same `gradle build` command works for Retrofit (v1) without issue, right?

**Comment by fabdslv** [comment]
Right, and yes I'm using Windows. It works on Retrofit v1, but in v1 `gradle.build` file, there is a dependency for `javax.annotation`, while there isn't in Retrofit v2.

**Comment by wing328** [comment]
Understood. May I know if you have cycle to submit a PR with the fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
I'll take care of it later this week if no one has a chance to submit a PR.

@fabdslv once again thanks for reporting the issue. We should have a better way to catch the issue moving forward using the CI.

**Comment by fabdslv** [comment]
@wing328 Sure, I can do it today, it should be quick. Just FYI, I found the PR that fixed Retrofit 1 : https://github.com/swagger-api/swagger-codegen/pull/1491.

**Comment by sam26109025** [comment]
Do you have any plans in pipeline to provide codegen for android client using retrofit2 library.

**Comment by wing328** [comment]
Would the following helps?

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

(for `library`, please set to `retrofit2`)

**Comment by sam26109025** [comment]
Thanks @wing328 that was really helpful.
