### ISSUE TITLE
How to use Volley for android?

### ISSUE THREAD

**Issue by Jonovono** [swagger-api/swagger-codegen#2510]
Hi. I can't seem to generate android and have it use volley. From what I can this has been added.

This is my attempt

    swagger-codegen generate -i http://localhost:8080/swagger.json -l android-volley -o ./out/android-volley

But I tried just `volley` as well.

**Comment by jaz-ah** [comment]
just use "-l android" and it will generate android code that can run your api's on volley.

**Comment by fehguy** [comment]
If you're using swagger-codegen from brew, you may not be picking it up correctly.  @wing328 can correct me if this is wrong, but you should just use the `java` target with the `volley` library.

You can grab the source for this project and build with `mvn package`.  Then you can run this:

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l android
```

to see your options.  Alternately you can use the [online generator](http://generator.swagger.io/).

**Comment by Jonovono** [comment]
Sweet, thanks @jaz-ah  and @fehguy that helped me figure it out!

**Comment by wing328** [comment]
@Jonovono FYI. I've documented it in https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk
