### ISSUE TITLE
[Android] Crash w/ volley timeout

### ISSUE THREAD

**Issue by jaz-ah** [swagger-api/swagger-codegen#2512]
If you get a volley network timeout the generated android code will crash because it is trying to dereference a null pointer here:

throw new ApiException(((VolleyError) ex.getCause()).networkResponse.statusCode, ((VolleyError) ex.getCause()).getMessage());

where networkResponse can be null.

(easy fix - i'll submit in a PR)

**Comment by wing328** [comment]
Thanks @jaz-ah. Appreciate your contribution.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/2513
