### ISSUE TITLE
Missing files when generating a Python Flask Server for use with Python 2.7

### ISSUE THREAD

**Issue by twhetzel** [swagger-api/swagger-codegen#2517]
When generating a server for Python Flask from the Swagger Editor and then running the app using Python 2.7, additional files are needed to run the app, an empty __init__.py file is needed in both the python-flask-server/ base directory as well as inside the controllers/ subdirectory. Otherwise, the following error is returned: ValueError: need more than 1 value to unpack.

**Comment by wing328** [comment]
@twhetzel thanks for reporting the issue. Following the readme, I could use python3 to start up the server without issue.

I got the following error using Python2 to start the app:
```
flaskConnexion|master⚡ ⇒ python app.py 
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import connexion
ImportError: No module named connexion
flaskConnexion|master⚡ ⇒ 
```
Did you get the same error?

**Comment by twhetzel** [comment]
Yes, that is the first error message I received. I then used `pip install -U connexion` to install the module. After this is when I received the error I mentioned above in the initial post.

**Comment by wing328** [comment]
Ideally the generate Python Flask code should work for both python 2.x and 3.x. I'll try to submit a PR with a fix this weekend.

**Comment by twhetzel** [comment]
Thanks, another issue is that the file default_controller.py includes type hints so I also needed to remove  ` -> str` from the functions. After that the app ran, but no content was displayed.

**Comment by wing328** [comment]
@twhetzel I've filed #2560 to support Python2.

You need to pass `-DsupportPython2=true` to the command line argument. Here is an example:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l python-flask -DsupportPython2=true \
  -o /var/tmp/python-flask/
```
About no content being display, did you get the "do some magic!" string when accessing the endpoint?

**Comment by twhetzel** [comment]
Thanks again for the quick response! 
Still sorting out the blank page display. My swagger.yaml file is [here](https://github.com/twhetzel/mygene-swagger/blob/master/swagger.yaml) - do you have suggestions on how to resolve this issue? Also, I can open a new post if preferred.

**Comment by wing328** [comment]
@twhetzel it works for me:
```
python-flask|⇒ curl http://localhost:8080/v2/store/inventory 
"do some magic!"
```
