### ISSUE TITLE
Lack of clarity of template inputs and how to customize interface

### ISSUE THREAD

**Issue by cdaringe** [swagger-api/swagger-codegen#2522]
hello:

thanks for the great utility!

i've read up [how to modify the templates](https://github.com/swagger-api/swagger-codegen#modifying-the-client-library-format), however, what is missing from that picture is what inputs are available to me.  further, for example, in the JS output it uses the `{{ importPath }}` which turns my route of `GET /scans/{id}` into `myApi.ScansidAPI.get(...)`.  i'd like to change that entirely to `myApi.scan.get(...)`, but i am not clear on how to do so.  any help would be great!

thanks

**Comment by fehguy** [comment]
I wish there was more documentation on the input structure to the templates.  But the best thing to do is run the utility with the `-DdebugOperations`, `-DdebugModels`, `-DdebugSwagger`, `-DdebugSupportingFiles` flags.

**Comment by wing328** [comment]
@cdaringe would this help?

https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables

**Comment by cdaringe** [comment]
Ya, thanks guys.
