### ISSUE TITLE
[Objective C] Generated code fails to build due to missing import

### ISSUE THREAD

**Issue by timburks** [swagger-api/swagger-codegen#2523]
After using homebrew to install swagger-codegen, I found that the generated code failed to compile with the following errors in SWGApiClient.m:

SWGApiClient.m:401:36: No known instance method for selector 'initWithDictionary:error:'
SWGApiClient.m:754:37: Unknown receiver 'SWGObject'; did you mean 'NSObject'?
SWGApiClient.m:755:24: No known instance method for selector 'toDictionary'

These errors disappeared when I added the following as the second line of the file:
#import "SWGObject.h"

With this, the generated library also successfully called my test API.

I believe that the appropriate change to fix this is in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache

and should be to add
#import "{{classPrefix}}Object.h"

as the second line of that file.

**Comment by fehguy** [comment]
I believe Homebrew is providing swagger-codegen 2.1.4, whereas we are now at 2.1.6.

**Comment by timburks** [comment]
I just tried the 2.1.6 jar and found the same build error in the generated code. But I did notice that some minor problems in the generated names were fixed.

**Comment by wing328** [comment]
@timburks do you mind sharing the spec for reproducing the issue?

**Comment by timburks** [comment]
@wing328 Here's a swagger file that you can use: [swagger.json.txt](https://github.com/swagger-api/swagger-codegen/files/209669/swagger.json.txt)

**Comment by wing328** [comment]
Thanks. I'll look into the issue and get back to you.

**Comment by wing328** [comment]
@timburks  I was able to workaround the issue by adding a dummy model to the spec (which does not contain any model).

I'm working on a fix to make the objc client works without models.

**Comment by wing328** [comment]
@timburks I've filed https://github.com/swagger-api/swagger-codegen/pull/2540 to fix the issue.

**Comment by wing328** [comment]
@timburks PR merged into master. Please pull the latest and give it another try.

**Comment by timburks** [comment]
Works. 👍

**Comment by wing328** [comment]
@timburks glad to hear that. Let us know if you've any feedback on the ObjC API client. I hope you find it easy to use with the documentation (markdown)
