### ISSUE TITLE
Superagent v2

### ISSUE THREAD

**Issue by mattfysh** [swagger-api/swagger-codegen#2527]
The upcoming v2 release of superagent fixes a couple of issues, namely promises implementation: https://github.com/visionmedia/superagent/pull/925
https://github.com/visionmedia/superagent/issues/763

Is anyone actively looking at the upgrade path for the generated JS clients?

**Comment by wing328** [comment]
@mattfysh  I'm not aware anyone working on it.

I just checked again and the latest release is `2.0.0-alpha.1`

Do you have cycle to contribute a PR?

**Comment by frol** [comment]
Hmm, there is already Superagent 3.5.0. I haven't tested it extensively, but it seems like a simple version update in the `package.json` is enough.

**Comment by wing328** [comment]
FYI. The latest uses 3.5.2.
