### ISSUE TITLE
[Swift] enum parameters do not generate enums

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2531]
```js         
               "name": "paramName"
               "required": false,
               "type": "string",
               "enum": [
                   "one",
                   "two"
               ]
```
generates:

```swift
    public class func action(paramName: String?)
```

while ideally it should generates:

```swift
   enum ParamName: String {
      case One = "one"
      case Two = "two"
   }
   public class func action(paramName: ParamName?)
```

**Comment by jaz-ah** [comment]
what version of Swagger are you using?  This is working for me on master...

**Comment by cjolif** [comment]
@jaz-ah I'm using something as follows: https://gist.githubusercontent.com/cjolif/76d29bec15b7fb735f6a2a76de70b67e/raw/12d26bf3e18180e5e2b8b08dfb9943bcb3a365b9/api.json 
on master, is that working for you?

**Comment by jaz-ah** [comment]
@cjolif ah sorry - I had a slightly different enum case within an object that was working - your case is definitely broken.
