### ISSUE TITLE
ApiClient : getClient() is private => cannot be overriden

### ISSUE THREAD

**Issue by mrooz** [swagger-api/swagger-codegen#2539]
getClient should be a protected method so that it may be overridden e.g. when needing to add functionality such as support for configuring an SSL trust manager.

**Comment by wing328** [comment]
I believe you're using the [default Android API client](https://github.com/swagger-api/swagger-codegen/blob/4d19da41dd8a3462f88c2be57174aace45101064/samples/client/petstore/android/default/src/main/java/io/swagger/client/ApiInvoker.java#L394)

I would recommend you to use the Android API client with the volley library or using the Java API client instead. Please refer to https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk for more information.

We'll still incorporate your feedback to enhance the default API client but it's not something with the highest priority.

**Comment by mrooz** [comment]
Hi,
I actually started using the okhttp-gson version of ApiClient but noticed
there's a bit of a problem dealing with binary data.  In your opinion,
what's the best library to use if I need the option to configure my
trruststore / ssl certificates?
(BTW I'm not running on Android)

thanks,
Mike

**Comment by wing328** [comment]
Can you please elaborate on the binary data issue?

**Comment by jfiala** [comment]
For jersey1 + jersey2 getHttpClient() is public since February.

**Comment by wing328** [comment]
Issue closed.
