### ISSUE TITLE
[Swift] Model generation not working with objects using inheritance. 

### ISSUE THREAD

**Issue by harryblam** [swagger-api/swagger-codegen#2550]
Swagger.yaml defintion as follows:

`BaseAccount:
    type: object
    discriminator: accountType
    required:
    - accountType
    properties:
      accountType:
        type: "string"`
  `Account:
    allOf:
      - $ref: '#/definitions/BaseAccount'
      - type: object
        properties:
          nickname:
            type: "string"
            description: "Description the user has given to their account"
        required:
        - nickname`

generates: 

`public class BaseAccount: JSONEncodable {}`
`public class Account: JSONEncodable {}`

whereas the desired output would be:

`public class BaseAccount: JSONEncodable {}`
`public class Account: BaseAccount {}`

I have tried the generation with Objective C templates, and the inheritance works fine, which makes me believe this is a bug within the Swift templates.

**Comment by wing328** [comment]
@harryblam I don't think it's supported in Swift at the moment.

**Comment by RobertBiehl** [comment]
@harryblam Hey, try this #4052

**Comment by RobertBiehl** [comment]
@wing328 this issue can probably be closed

**Comment by harryblam** [comment]
hey, thanks @RobertBiehl . Nice work!
