### ISSUE TITLE
missing documentation 

### ISSUE THREAD

**Issue by arilynN** [swagger-api/swagger-codegen#2566]
There should be a hint in the documentation which explains how the mustache templates are built. There is nothing about -DdebugOperations -DdebugModels or -DdebugSupportingFiles which explain a mustache template and its attributes.

**Comment by wing328** [comment]
Would this help? https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables

**Comment by arilynN** [comment]
Yes alot. Is there even more documentation about the codegeneration or specific things about it? Maybe it would be good if u make a link in the a README of codegen. I looked for something like that and havn't found it.

**Comment by arilynN** [comment]
Maybe a little example of how to use it in a template -> {{basePath}} would be nice

**Comment by wing328** [comment]
Added https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables#usage.

Let us know if you've further feedback.

**Comment by wing328** [comment]
Added links to Wiki and FAQ in the front page (README.md)
