### ISSUE TITLE
[Go] Add docstring to Go API methods

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2572]
From what I know, there's no official way to document a method in Go. We'll use the [ObjC method comment](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/objc/api-header.mustache#L25) as a starting point to document the API methods in Go.

**Comment by guohuang** [comment]
@wing328 we already have this on the api method, what are we missing? https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/swagger/PetApi.go#L32-38

**Comment by wing328** [comment]
@guohuang you're right. I was reading some outdated code.

**Comment by wing328** [comment]
@guohuang I noticed that there's a commented method declaration at https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/swagger/PetApi.go#L38

If you've time, I wonder if you can file a PR later to remove it.
