### ISSUE TITLE
Generated classes should override equals and hashCode

### ISSUE THREAD

**Issue by mauhiz** [swagger-api/swagger-codegen#258]
... especially if they are to be used in a Set (uniqueItems-type container)

**Comment by dantran** [comment]
Any plan for this feature? it is marked fo 2.1.0-M2 but we are now at 2.1.4.

**Comment by wing328** [comment]
@dantran I think I can come up with something for C# this weekend.

**Comment by wing328** [comment]
PR for C# merged into master. Please report if you encounter any issue using the new methods

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/1605 submitted by @xhh for Java API client.

**Comment by wing328** [comment]
PR merged
