### ISSUE TITLE
C#: Required properties causing deserialization to fail

### ISSUE THREAD

**Issue by jforsell** [swagger-api/swagger-codegen#2584]
A generated C# client throws an exception when deserializing a model that has one or more required properties. For example, the attached yaml has a Product model with a product_id attribute that is required:

[yaml.txt](https://github.com/swagger-api/swagger-codegen/files/216941/yaml.txt)

When hitting the endpoint /product that returns one Product, the ApiClient will try to deserialize it by doing:

`
return JsonConvert.DeserializeObject(response.Content, type);
`

An exception is thrown at this point because no product_id is provided to the constructor of the Product:

`
if (ProductId == null)
{
    throw new InvalidDataException("ProductId is a required property for Product and cannot be null");
}
`

**Comment by wing328** [comment]
@jforsell are you using v2.1.6 or the latest master to generate the C# client?

**Comment by wing328** [comment]
Also given that product_id is a required property and it's missing in the response (response.Content). Do you expect a Product object is created without PrductId set to null (which violates the constraint of the required property)?

**Comment by jforsell** [comment]
@wing328 Using latest master (pulled two days ago). The /product endpoint would return a {"product_id": "abc123"} response but the deserializer above invokes the constructor with null parameters causing the constraint to be violated in the constructor of the Product class and throwing an exception. I think the json library invokes the constructor first when deserializing and sets properties after the object is constructed.

**Comment by jforsell** [comment]
Apologies, have been playing around with this some more and just realised the example YAML I attached above was overly simplified and did not properly demonstrate the issue. Please see this new example:

[yaml.txt](https://github.com/swagger-api/swagger-codegen/files/230010/yaml.txt)

The problem is when you have a model, Product, with an allOf reference to BaseProduct. This generates a C# class called Product that has BaseProduct as a super-class. When deserializing the JSON:

{"id": "123", "description": "A product."}

both parameters are correctly passed to the Product constructor. However, since BaseProduct is Product's parent class, its default constructor is invoked and since id is a required property of BaseProduct, it will throw an exception.

The generated constructor for Product is:

public Product(string Id = null, string Description = null)

I can fix this particular model just by adding a call to the super constructor, but don't know if this can be extended to a general fix:

public Product(string Id = null, string Description = null) : base(Id)

**Comment by jforsell** [comment]
Not sure if relevant, but I get the same result (exception thrown in parent BaseProduct class) when adding a discriminator productType:

[yaml.txt](https://github.com/swagger-api/swagger-codegen/files/230024/yaml.txt)

**Comment by wing328** [comment]
@jforsell thanks for the details and I agree that this should be extended to a more general fix.

Here are some examples for models using composition/inheritance: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#models-with-composition

**Comment by jimschubert** [comment]
@jforsell What is the target framework (4.0, 4.5?), OS and .NET runtime version you are experiencing this under?

I think there are two separate issues here: 

1. The defaulted parameters actually generate a parameterless constructor that can be used by the deserializer. I had initial concerns about this, but in testing there didn't seem to be issues. I'd have to look again to see if something has changed.

2. The base constructor should be considered in the generated model. I'm not entirely sure how this could be handled cleanly with logicless templating, but it's an issue for any api with a non-flat type hierarchy.

**Comment by boxjar** [comment]
@jimschubert I'm on Windows 7 targeting 4.5, but tried targeting 4 (generating for 3.5) just now and got the same problem. I am generating the example with:

`
java -jar swagger-codegen-cli.jar generate -i yaml.txt -l csharp -c config.txt
`

config.txt only contains the targetFramework setting.

Interesting that you mention the constructor with the default parameters. I can actually get the generated code working by explicitly adding a parameterless constructor, ie:

```
// Added this after code generation:
public Product()
{
}

// Already generated:
public Product(string Id = null, string ProductType = null, string Description = null)

```

```
// Added this after code generation:
public BaseProduct()
{
}

// Already generated:
public BaseProduct(string Id = null, string ProductType = null)

```

**Comment by jimschubert** [comment]
@boxjar 

I'd have to play around with a better approach for handling required properties. The reason I brought up the defaulted parameters in the constructor is because most serializers require a parameterless constructor to construct the object, then work some magic to set the properties. The original intention for the constructor with the defaulted parameters was to require those parameters to construct an instance of the object. 

It may be that a better approach would be to be less restrictive on construction by providing the parameterless constructor and a secondary constructor and provide some sort of serialization error handling.

If you're interested in more technical details of how parameters with only defaulted arguments work, for a class `Example.cs`:

```
using System;
public class Example {
   public String Id {get;set;}
   public String Name {get;set;}
   public Example(string id = null, string name = null) { }
}
```

Here's the constructor that gets generated in IL:

```
.method public hidebysig specialname rtspecialname
           instance default void '.ctor' ([opt] string id, [opt] string name)  cil managed
    {
	.param [1] = nullref
	.param [2] = nullref
        // Method begins at RVA 0x2050
	// Code size 7 (0x7)
	.maxstack 8
	IL_0000:  ldarg.0
	IL_0001:  call instance void object::'.ctor'()
	IL_0006:  ret
    } // end of method Example::.ctor
```

In mono, you can compile that class with `mcs /target:library Example.cs` and view the IL with `monodis Example.dll`. In .NET, you can run `ildasm` and load the dll to view the same output. The IL is usually different between Mono and .NET.

**Comment by jimschubert** [comment]
Leaving this link here since it may help with a resolution: https://manski.net/2014/10/net-serializers-comparison-chart/

The linked post explains general capabilities of different serialization frameworks, and requirements for common serialization attributes.

**Comment by jimschubert** [comment]
@jforsell @boxjar I was wondering if you could try a fix I just committed on my branch: https://github.com/jimschubert/swagger-codegen/tree/cs/req_properties_2584

I've added a protected parameterless constructor when a class contains any required properties, but I probably won't have time to test it myself for a few days.

**Comment by jforsell** [comment]
@jimschubert I've only done a quick test using your branch but didn't get a protected parameterless constructor when generating the code using the above example, not sure why. I tried adding the constructor manually after generating, but looks like Json.Net doesn't recognise it when it's protected; I had to change it to public to make it work.

**Comment by jimschubert** [comment]
@jforsell Thanks. I'll explore other options. I think I'll investigate JSON.Net serialization options next. I'm trying to avoid the public constructor, but I think that would be an acceptable final result considering the model types are partial and consumers could just as easily create their own constructors.

**Comment by jimschubert** [comment]
@jforsell Thanks for testing that. I'm not sure why you didn't get the protected constructor from my branch. There was a [small additional change](https://github.com/jimschubert/swagger-codegen/blob/cs/req_properties_2584/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L23) I had to make for this to work properly for deserialization. I force pushed new changes and opened a pull request with the steps I took to verify the change, which works for me in both Windows and OS X.

**Comment by jforsell** [comment]
@jimschubert Working for me too now! Suspect I must have had some build issue earlier, I've tried again including the small additional change you mentioned above and both my example and my real-world app are working properly.

**Comment by jimschubert** [comment]
Awesome. Thanks for verifying.

**Comment by jimschubert** [comment]
@wing328 @jforsell anything more required by this issue?

**Comment by wing328** [comment]
I don't think so. Closing it.
