### ISSUE TITLE
swagger generated names are different compared to name in class.

### ISSUE THREAD

**Issue by kalkkhi** [swagger-api/swagger-codegen#2586]
Hi Swagger team,

We are working with Apache CXF framework and we used Swagger provided examples to generate swagger API specification. We use Apache CXF to expose soap and restful services together. We are generating our classes from an XSD. Field name tBr is generating successfully by CXF and working fine in restful service, but when spec is created by Swagger it is changing from tBr to tbr in swagger.json, second letter in field name changed from upper case to lower case. We would like to know the reason for this. We checked this behaviour on another field by making second letter into upper and there also Swagger changed it into lower case.

Snippet of XSD used:
                <xsd:element name="acctsFltr" minOccurs="0">
                    xsd:complexType
                        xsd:choice
                            <xsd:element name="actNumber" type="tns:AccountNumberType" />
                            <xsd:element name="tBr" type="tns:BranchType" />
                            <xsd:element name="bch" type="tns:BranchType" />
                        /xsd:choice
                    /xsd:complexType
                /xsd:element

Snippet generated Java files

  @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-04-13T10:25:39-04:00", comments = "JAXB RI v2.2.11")
  protected GetDetailsRequest.ActGrp actGrp;

 public static class ActGrp {

```
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-04-13T10:25:39-04:00", comments = "JAXB RI v2.2.11")
    protected String actNumber;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-04-13T10:25:39-04:00", comments = "JAXB RI v2.2.11")
    protected String tBr;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2016-04-13T10:25:39-04:00", comments = "JAXB RI v2.2.11")
    protected String bch;
```

Thanks,
Anoop

**Comment by kalkkhi** [comment]
@wing328 Hi I can see that you were looking on other issues reported and this issue was skipped. Can you have a look on it?

**Comment by wing328** [comment]
@kalkkhi well I didn't skip it. I'm just no expert in Apache CXF framework and let's see if someone from the community can help on this.

**Comment by kalkkhi** [comment]
Thanks @wing328, I am not sure about forum practices, so is this added as a bug and kept to fix on release version v2.2.0?

**Comment by wing328** [comment]
@kalkkhi I've marked it as 2.2.0 for the time being but there's no guarantee.

I would suggest you to share the swagger spec so that the community can use it to reproduce the issue and help fix the issue if they've cycles.

**Comment by kalkkhi** [comment]
@wing328 how to share the swagger spec, json fie alone or the implementation classes and class files?

**Comment by wing328** [comment]
The json file. You can use gist.github.com

**Comment by jfiala** [comment]
@kalkkhi Can you try this with the lastest master? If the error still occurs, please share the spec for easy reproduction.

**Comment by wing328** [comment]
@kalkkhi closing this as there's no update from you.
