### ISSUE TITLE
JAX-RS ApiResponse 'response' and 'responseContainer' annotations get duplicated

### ISSUE THREAD

**Issue by vdillon** [swagger-api/swagger-codegen#2588]
I used the Swagger Editor to create:

```
swagger: '2.0'
info:
  version: "0.0.1"
  title: Response annotation test
paths:
 /person:
    get:
      summary: Get all person api
      responses:
        200:
          description: Get all person
          schema:
            type: array
            items:          
              $ref: '#/definitions/Person'
        500:
          description: Unexpected error(s)
          schema:
            $ref: '#/definitions/ApiError'
definitions:
  Person:
    type: object
    properties:
      name:
        type: string
  ApiError:
    type: object
    properties:
      errorMsg:
        type: string
```

Then I generated JAX-RS Server code from the editor.  Here is the APIResponses section in the PersonApi class:

```
   @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "Get all person", response = Person.class, responseContainer = "List"),
        @io.swagger.annotations.ApiResponse(code = 500, message = "Unexpected error(s)", response = Person.class, responseContainer = "List") })
```

The 'response' and 'responseContainer' annotations from the 200 response block got used in the 500 ApiResponse.

**Comment by wing328** [comment]
@vdillon thanks for reporting the issue. What should be correct APIResponses section looks like?

**Comment by vdillon** [comment]
Given the above Swagger, I would expect the correct APIResponses to be:

@io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "Get all person", response = Person.class, responseContainer = "List"),
        @io.swagger.annotations.ApiResponse(code = 500, message = "Unexpected error(s)", response = ApiError.class) })

**Comment by wing328** [comment]
@vdillon may I know if you've cycle to contribute the fix? A good starting point is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/api.mustache#L48

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by vdillon** [comment]
I cannot commit to contributing at this time.
 
Van
 
--------- Original Message --------- Subject: Re: [swagger-api/swagger-codegen] JAX-RS ApiResponse 'response' and 'responseContainer' annotations get duplicated (#2588)
