### ISSUE TITLE
[Swift] duplicate lines in models objects

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2599]
In Model objects you sometimes get twice the same line generated:

nillableDictionary["id"] = self.id?.encodeToJSON()
nillableDictionary["id"] = self.id?.encodeToJSON()

See: https://github.com/swagger-api/swagger-codegen/commit/44a4219e3e89a34a297bbb7fa7482dd2c57f0681#commitcomment-17070194

for more details.

**Comment by wing328** [comment]
Just want to add that from what I know this bug does not impact the functionality of the Swift API client or cause any issue but still we need to clean it up as there's no point handling the same property twice.

**Comment by seb-pereira** [comment]
The duplicated line in comment https://github.com/swagger-api/swagger-codegen/commit/44a4219e3e89a34a297bbb7fa7482dd2c57f0681#commitcomment-17070194 is in file `InlineResponse200.swift`. When I run  `./bin/swift-petstore.sh` it does not generate this file. How is the file `InlineResponse200.swift` generated?

**Comment by wing328** [comment]
@seb-pereira thanks for the finding. I've updated the Swift petstore sample via #2651 

We'll reopne this issue when there's another report of the same issue.

**Comment by wing328** [comment]
FYI. Test cases for Swift Petstore passed:
```
	 Executed 3 tests, with 0 failures (0 unexpected) in 1.335 (1.337) seconds
Test Suite 'UserAPITests' started at 2016-04-20 16:58:41.863
Test Case '-[SwaggerClientTests.UserAPITests test1CreateUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test1CreateUser]' passed (0.506 seconds).
Test Case '-[SwaggerClientTests.UserAPITests test2GetUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test2GetUser]' passed (0.614 seconds).
Test Case '-[SwaggerClientTests.UserAPITests test3DeleteUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test3DeleteUser]' passed (0.499 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' passed (0.520 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' passed (0.612 seconds).
Test Suite 'UserAPITests' passed at 2016-04-20 16:58:44.616.
	 Executed 5 tests, with 0 failures (0 unexpected) in 2.750 (2.754) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2016-04-20 16:58:44.617.
	 Executed 11 tests, with 0 failures (0 unexpected) in 5.687 (5.696) seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.666 s
[INFO] Finished at: 2016-04-20T16:58:44+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```
