### ISSUE TITLE
codegen cli doesn't warn or error for non existent template path

### ISSUE THREAD

**Issue by sreich** [swagger-api/swagger-codegen#2604]
if a template path provided to swagger-codegen-cli doesn't exist, it is simply silently ignored. this costed me a bit of debug time, as i finally realized my typo. 

it can be assumed that if that option is passed, it should be an error if the template path does not exist. or else why would you be specifying it? alternatively i'd just settle for a warning..anything is better than nothing.

**Comment by wing328** [comment]
Sorry to hear that it's causing you a bit of time to debug. Are you using the latest master? or 2.1.6 stable version?

If my memory serves me well, I did get warning/error before when the expected template file is not found.

**Comment by sreich** [comment]
Yep, did it with latest stable, 2.1.6. Simply add -t "/path/doesnt/exist"  and it won't error or warn.

**Comment by wing328** [comment]
OK. I'll look into this more on coming weekend or next.

**Comment by wing328** [comment]
@sreich I've submitted a PR with better exception handling and an example of the error message is shown below:
```
Exception in thread "main" java.lang.IllegalArgumentException: Template directory modules/swagger-codegen/src/main/resources/xxx does not exist.
	at io.swagger.codegen.config.CodegenConfigurator.setTemplateDir(CodegenConfigurator.java:156)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:159)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```

**Comment by wing328** [comment]
PR merged into master. Closing this issue.

@sreich please kindly pull the latest and give it another try to see if you're now more happy with the error message.
