### ISSUE TITLE
[Swift] reserved keywords management is a bit agressive

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2605]
`Type` is a reserved keyword in Swift. But `type` is not (at least as far as I know). Still if I use `type` it will be escaped to `_type`.

**Comment by wing328** [comment]
Yes, the current approach is to make a case insensitive comparison of the reserved word list.

Is it correct to say that Swift reserved keyword are **all** case sensitive just like "Type"?

**Comment by cjolif** [comment]
I can't find a good official reference on that, _but_ for example I can use 'Var' as variable name, so it seems so, that yes they should all be sensitive.

**Comment by yonaskolb** [comment]
Yes, this was a recent change to reserved types that I didn't agree with. I've made a pull request here https://github.com/swagger-api/swagger-codegen/pull/2633 that makes reserved types case sensitive again in Swift

**Comment by wing328** [comment]
Thanks @yonaskolb for the PR, which has been merged into the master.
