### ISSUE TITLE
Jaxrs-CXF missing mustache variables for javax.validation framework

### ISSUE THREAD

**Issue by FlorentBarreau** [swagger-api/swagger-codegen#2615]
Hello,

I'm using swagger codegen maven plugin to auto-generate endpoints and models for a REST API project. I personalize mustache template to generate javax.validation annotations such as 
@Valid, @Min, @Max, @Size, @Pattern, etc... on Query/PathParam and Models 

So far I'm facing to those 2 Issues : 
- {{minimum}} and {{maximum}} returns Double values because of CodegenProperty minimum and maximum types which are Double (and I understand it could be useful to have Double instead of Integer...)
  Issue is that I can't use @Min({{minimum}}) and @Max({{maximum}}) on my mustache templates : it will break at compilation because it requires Integer values instead of Double
  Now I'm looking for a fancy solution without modifying codegen source code if possible. Is CodegenProperty overridable by config ? Is there any secret param I can use to change that behavior ?
- For Endpoint QueryParams, I have this problem : @NotNull must be added only if required = true, but I can only test if tag 'required' is present or not, through {{#required}}, and so I cannot use same tricks than in java's templates
  So far I can work-around this issue by deleting all 'required = false' in swagger specification yaml and using {{#required}}@NotNull{{/required}} but this will generate functional issues if people modify yaml...
  So I was looking for some kind of isRequired tag or another solution without modifying codegen source if possible, but haven't found one yet.

At worst, if those issues are not solvable by config, is extending AbstractJavaJAXRSServerCodegen a good idea to generate new properties and use them for mustache templates ?

FYI I'm adding my overrides of jaxrs-cxf templates (dev on-going...), maybe it can help to understand/reproduce

[jaxrs-cxf_javax_validation_mustache_templates.zip](https://github.com/swagger-api/swagger-codegen/files/221320/jaxrs-cxf_javax_validation_mustache_templates.zip)

I'll be glad to post those templates and contribute to this project once all issues solved.

Thanks and regards,
Florent Barreau

**Comment by wing328** [comment]
@FlorentBarreau ideally {{minimum}} and {{maximum}}  should be determined by langauges (e..g 3.7F for float value in C#) and I would foresee some changes in the codegen class to accommodate that.

For {{#required}}, are you looking for {{^required}} (the opposite of "required" being set to true) ?

And most importantly thanks for offering help to contribute to this project.

**Comment by FlorentBarreau** [comment]
@wing328 thanks for your reply !

Actually, I finally forked the codegen and added a JavaCXFValidationServerCodegen which extends JavaCXFServerCodegen (generation langage option = "jaxrs-cxf-validation")

- for the {{minimum}} issue, i made the following work-around : 
As CodegenProperty min and max variables are not used and as they are String, I copy minimum/maximum intValue on them, and display min and max on templates: {{#max}}@Max({{max}}){{/max}}
But yes, It could be find to find a proper way to have a Type for minimum/Maximum which is langage-dependent

- for the {{required}} issue, I was looking for a way to test the value of the required variable. My goal is : "if required = true, then display @NotNull", "if required = false, nothing to display"
that's why I couldn't use {{#required}} and {{^required}}, which only test if required is present or not (and not looks for the value true/false)
Anyway, on my JavaCXFValidationServerCodegen, I surcharged required property by setting null if it's false. By this way, {{#required}} will display @NotNull only if required = true

And of course, I'll push this module when it's finished ;)

**Comment by wing328** [comment]
`{{#required}}@NotNull{{/required}}` should meet your requirement assuming 'required' is a boolean, not a string.

Ref: https://mustache.github.io/mustache.5.html => "False Values or Empty Lists"

**Comment by wing328** [comment]
And here is a helpful tip for debugging: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-to-debug-swagger-codegen

**Comment by FlorentBarreau** [comment]
@wing328 : Yes you're right about {{#required}}@NotNull{{/required}}, no need to set it to null: if it's false, it won't be display.
Thanks for debugging tips !

**Comment by wing328** [comment]
@FlorentBarreau no problem. Let me know if you need any further assistance.

**Comment by wing328** [comment]
@FlorentBarreau  If you need help filing a PR for the enhancement, please reply to let us know.

**Comment by jfiala** [comment]
BeanValidation annotation support + automatic BeanValidation has been added to jaxrs-cxf-server in PR #4003 , pls check if you are missing something.

**Comment by jfiala** [comment]
@wing328: This has been fixed as PR #4003, I think you can close this as there is no response from @FlorentBarreau  so far?

**Comment by wing328** [comment]
@jfiala ok. Closing this.
