### ISSUE TITLE
Generated class should have members but doesn't

### ISSUE THREAD

**Issue by degroves** [swagger-api/swagger-codegen#2618]
I used the JSON spec in [this gist](https://gist.github.com/degroves/4f9cae2dfb799842ed90f8f81d027669) with Swagger Codegen 2.1.6.  The spec includes the definition of a string type with a pattern.  The gist includes the generated code for that string type and the generated DefaultApi.java.  There are no members at all for the generated class.  The DefaultApi.java code uses the generated class.

The class should either a) have a String member and enforce the pattern or b) generated client API methods referencing this type should return a String and enforce the pattern. I prefer the first option.

**Comment by wing328** [comment]
@degroves the model properties should be inside "properties".

e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L940

**Comment by degroves** [comment]
I changed the definitions from the gist I posted to this:

    "definitions": {
      "emptyclass": {
        "properties": {
          "notemptyanymore": {
            "type": "string",
            "pattern": "samplepattern"
          }
        }
      }
    },

I saw the generated class included a string, but did not enforce the pattern.

**Comment by wing328** [comment]
@degroves The pattern is not supported at the moment.

**Comment by degroves** [comment]
OK, good to know.  Thanks!

**Comment by degroves** [comment]
Is there an issue to add support or should I leave this open to add support?

**Comment by wing328** [comment]
I'll open a separate issue to track it as we need to add the support for all languages we supported so far (which is a lot...)

How critical is the pattern to your use case?

**Comment by degroves** [comment]
Having pattern support will make our lives easier, but I think we can work around not having it.  

I'll close this issue.  Thanks for your help!

**Comment by wing328** [comment]
FYI. Opened https://github.com/swagger-api/swagger-codegen/issues/2663 for tracking.

**Comment by degroves** [comment]
Thank you!
