### ISSUE TITLE
Swagger codegen test files compilation issue - wrong package name

### ISSUE THREAD

**Issue by sbelan** [swagger-api/swagger-codegen#2622]
@wing328 ... just took latest master and found compilation issue for GO test files GoClientOptionsTest .java and GoModelTest .java . Test classes has package package io.swagger.codegen.Go; it should be package io.swagger.codegen.go;

[](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/java/io/swagger/codegen/go/GoClientOptionsTest.java)

**Comment by wing328** [comment]
@sbelan first of all, there's no need to pinpoint me for every "issue"

I just pull the latest in a new folder and couldn't repeat the issue.

**Comment by sbelan** [comment]
@wing328 ..really sorry for the inconvenience

**Comment by wing328** [comment]
np.
