### ISSUE TITLE
Magento2 Swagger generated php client - Syntax error in ErrorParametersItem

### ISSUE THREAD

**Issue by quickshiftin** [swagger-api/swagger-codegen#2625]
I've generated a PHP client library for Magento2, against [their public schema](http://devdocs.magento.com/swagger/schemas/latest-2.0.schema.json), using [swagger-codegen](https://github.com/swagger-api/swagger-codegen).

The generated client has a syntax error in the _lib/Model/ErrorParameters.php_ file:

`class ErrorParameters extends array<ErrorParametersItem> implements ArrayAccess`

should be

`class ErrorParameters extends ErrorParametersItem implements ArrayAccess`

**Comment by arnested** [comment]
That's definitely an error (it's not even valid PHP being generated)!

I don't think right code is `class ErrorParameters extends ErrorParametersItem implements ArrayAccess` though.

In the specification `ErrorParameters` are defined as an array of `ErrorParametersItem`s. That doesn't sound like `ErrorParameters` should extend `ErrorParametersItem`:
```json
    "error-parameters": {
      "type": "array",
      "description": "Error parameters list",
      "items": {
        "$ref": "#/definitions/error-parameters-item"
      }
    },
```
I have a small fix that will generate better code for this but I'll have to look a bit more into exactly what it does and why (see patch below if you need something to try out right away).

Besides that I don't think we handle arras properly. I'm looking into that as well (having a test case as step one).


This patch generates better code -- no guarantees for other side effects though 😄:
```patch
diff --git a/modules/swagger-codegen/src/main/resources/php/model.mustache b/modules/swagger-codegen/src/main/resources/php/model.mustache
index 6f292e8..f1726be 100644
--- a/modules/swagger-codegen/src/main/resources/php/model.mustache
+++ b/modules/swagger-codegen/src/main/resources/php/model.mustache
@@ -46,7 +46,7 @@ use \ArrayAccess;
  * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
  * @link        https://github.com/swagger-api/swagger-codegen
  */
-class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}implements ArrayAccess
+class {{classname}} {{#parentSchema}}extends {{{parentSchema}}} {{/parentSchema}}implements ArrayAccess
 {
     /**
       * The original name of the model.
@@ -64,7 +64,7 @@ class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}implements ArrayA
     );
   
     static function swaggerTypes() {
-        return self::$swaggerTypes{{#parent}} + parent::swaggerTypes(){{/parent}};
+        return self::$swaggerTypes{{#parentSchema}} + parent::swaggerTypes(){{/parentSchema}};
     }
 
     /** 
@@ -77,7 +77,7 @@ class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}implements ArrayA
     );
   
     static function attributeMap() {
-        return {{#parent}}parent::attributeMap() + {{/parent}}self::$attributeMap;
+        return {{#parentSchema}}parent::attributeMap() + {{/parentSchema}}self::$attributeMap;
     }
 
     /**
@@ -90,7 +90,7 @@ class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}implements ArrayA
     );
   
     static function setters() {
-        return {{#parent}}parent::setters() + {{/parent}}self::$setters;
+        return {{#parentSchema}}parent::setters() + {{/parentSchema}}self::$setters;
     }
 
     /**
@@ -103,7 +103,7 @@ class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}implements ArrayA
     );
   
     static function getters() {
-        return {{#parent}}parent::getters() + {{/parent}}self::$getters;
+        return {{#parentSchema}}parent::getters() + {{/parentSchema}}self::$getters;
     }
 
     {{#vars}}
@@ -120,7 +120,7 @@ class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}implements ArrayA
      */
     public function __construct(array $data = null)
     {
-        {{#parent}}parent::__construct($data);{{/parent}}
+        {{#parentSchema}}parent::__construct($data);{{/parentSchema}}
         {{#discriminator}}// Initialize discriminator property with the model name.
         $discrimintor = array_search('{{discriminator}}', self::$attributeMap);
         $this->{$discrimintor} = static::$swaggerModelName;
```

**Comment by quickshiftin** [comment]
Thanks for your quick attention to this. My 'solution' was to just make it `class ErrorParameters extends ErrorParametersItem implements ArrayAccess` in my build of the generated code. Since it's under version control I think I'll have to live with patches on the generated code until upstream changes resolve them. Interesting that may not even be a correct patch though!

Appreciate your quick attention to this, do you feel I should close this out or leave it open for now?

**Comment by arnested** [comment]
Just leave it open. There is a bug in Swagger Codegen. I'll work on a patch for this.

Patching either swagger codegen or the generated code can be an ok way to move forward on a project. I've done that myself as well.

**Comment by arnested** [comment]
@quickshiftin, this should be fixed in the master branch now and will appear in the next stable release.

**Comment by quickshiftin** [comment]
Thank you sir!
