### ISSUE TITLE
[Documentation] Add CLI switch to opt-out documentation (md) generation

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2631]
Add a CLI switch (e.g. generateDoc) for generating documentation.

Default is true.

Related discussion: https://github.com/swagger-api/swagger-codegen/pull/2595, https://github.com/swagger-api/swagger-codegen/issues/2079

If anyone wants to work on this, please reply to let us know.

**Comment by jimschubert** [comment]
I have a pull open for this feature using options apiDocs and modelDocs in #2866.

**Comment by wing328** [comment]
PR merged. Thanks for the contribution from @jimschubert
