### ISSUE TITLE
[Java] Need to reference Java objects that are not in the model

### ISSUE THREAD

**Issue by yaelah** [swagger-api/swagger-codegen#2641]
We have multiple components that use swagger. Some of the model classes are shared among those components.
We need to reference those classes from the swagger models that are not shared. If we simply generate those classes for each component, we will need to write conversion code for those classes. This is bad for performance and it is error prone. 
If the swagger models supported reference to external classes, that could solve our problem.

**Comment by ePaul** [comment]
Did you try [the import-mappings feature](https://github.com/swagger-api/swagger-codegen#bringing-your-own-models)?  (I didn't, but the description sounds like it is what you want.)

**Comment by yaelah** [comment]
Thank you so much for your suggestion. It works!

**Comment by wing328** [comment]
Documented in the FAQ: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-to-import-java-objects-that-are-not-defined-as-model-in-the-openapiswagger-spec
