### ISSUE TITLE
Does the generator support to generate API endpoints with match priority?

### ISSUE THREAD

**Issue by abcsun** [swagger-api/swagger-codegen#2643]
I am try to create a lumen generator, but apis generated from the mustache file may not work well because the match priority question.

this is my [route.mustache](https://github.com/abcsun/swagger-codegen/blob/lumen/output/LumenServer/src/main/resources/LumenServerCodegen/app/Http/routes.mustache) file. 

and these routes was produced from the [petstore](http://petstore.swagger.io/v2/swagger.json)
```
/**
 * GET getUserByName
 * Summary: Get user by user name
 * Notes: 
 * Output-Formats: [application/xml, application/json]
 */
$app->GET('/user/{username}', function($username, $null = null) use ($app) {
     
    
    

    return response('How about implementing getUserByName as a GET method ?');
    });


/**
 * GET loginUser
 * Summary: Logs user into the system
 * Notes: 
 * Output-Formats: [application/xml, application/json]
 */
$app->GET('/user/login', function($null = null) use ($app) {
     
    $username = Request::input('username');    
    $password = Request::input('password');    
    
    

    return response('How about implementing loginUser as a GET method ?');
    });
```

the question is /user/login was shadowed by previously defined /user/{username} api.
 
Any suggests? Thanks.

**Comment by wing328** [comment]
@abcsun for this case, a workaround is to ask the spec owner to rearrange the endpoints so that `/user/login` appears first.

We can document this workaround for the time being until the community comes up with a better solution.

Thanks for the contribution to create the server generator for PHP Lumen.

**Comment by wing328** [comment]
@abcsun another workaround I can think of (without modifying the template) is to sort the endpoints in ascending order so that endpoints with { will end up at the bottom.

**Comment by abcsun** [comment]
@wing328  this may be a good solution.

Referenced from the other generators such as [GoClientCodegen](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java#L355)

To override the postProcessOperations function so that i could sort the endpoints, but it doesn't work.

Any suggests as i am not familiar with the Swagger core source.   

Thanks

```
public class LumenServerCodegen extends DefaultCodegen implements CodegenConfig {

// override with any special post-processing
    @Override
    public Map<String, Object> postProcessOperations(Map<String, Object> objs) {
        @SuppressWarnings("unchecked")
        Map<String, Object> objectMap = (Map<String, Object>) objs.get("operations");
        @SuppressWarnings("unchecked")
        List<CodegenOperation> operations = (List<CodegenOperation>) objectMap.get("operation");
        for (CodegenOperation operation : operations) {
            // http method verb conversion (e.g. PUT => Put)
            operation.httpMethod = camelize(operation.httpMethod.toLowerCase());
        }

        return objs;
    }
```

**Comment by wing328** [comment]
@abcsun using postProcessOperations is a good start 👍 

I'll take another look later today or tomorrow to see if I can provide you a better hint.

**Comment by wing328** [comment]
@abcsun sorry I didn't have a chance to work on this yet.

I've marked the task as "Need Community Contribution" for the time being so that anyone from the community can also work on this enhancement.
