### ISSUE TITLE
Generator - numbers getting stripped from tag names

### ISSUE THREAD

**Issue by vipera** [swagger-api/swagger-codegen#2657]
I have a swagger path tagged with "v1-apiname", and would like to generate an api (with api.mustache) that is named v1_apiname.rb (according to my settings).

My first thought was to override `toApiFilename`, but it seems that a function higher in the call chain, `apiFilename` (DefaultCodegen.java line 2404), already gets "Vapiname" as the tag parameter using the above example, meaning that I am unable to keep the numbers and do my own conversion.

Since the functions deeper in the stack seem problematic to override, I wonder if it's possible to get the name by some other method or delegate the stripping of numerals and dashes to an overridable function.

Thanks :)

**Comment by wing328** [comment]
The conversion from tag to file name should be customizable. We'll need to look into this more.

If anyone from the community wants to work on this, please reply to let us know.

**Comment by vipera** [comment]
Down the line I found out that overriding `sanitizeTag` achieves the effect I wanted.

Having the call just before outputting api filenames might be a more logical design (then you could have access to the actual tag in the api filename set of methods, instead of having "tag" contain a pre-sanitized tag), but I'm not sure what the use case is - and since it's possible to customize the mapping by overriding `sanitizeTag`, feel free to resolve this issue since this isn't really a bug.

**Comment by wing328** [comment]
@vipera my guess it that previously we found non-alphanumeric characters (e.g. #, $) in the tag. I agree with you that number should not be removed.

I'll leave this open for the time being so that we will update sanitizeTag with better logic and a test case (a tag with numbers) to cover it moving forward.
