### ISSUE TITLE
[Android] Generated models 'hashCode' and 'equals' problems

### ISSUE THREAD

**Issue by andriydruk** [swagger-api/swagger-codegen#2660]
In version 2.16 in generated models 'equals' and 'hashCode' don't work or lead to crash on old devices.

1. Android (default and voley) generated models don't implement methods 'equals' and 'hashCode'. It makes impossible to use this classes in collections. E.g. class [Animal](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/android/default/src/main/java/io/swagger/client/model/Animal.java).
2. Java (default, feign, jersey2, okhhtp-gson, retrofit, retrofit2) generated models implement 'equals' and 'hasCode' but they use java.utils.Objects with min API 14. As a result, you will get NoClassDefFoundError because  java.utils.Objects available only from API 19. E.g. class [Animal](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Animal.java).

**Comment by wing328** [comment]
@andriydruk thanks for reporting the issue. Would you have cycle to contribute a PR to implement `equals` and `hashCode` for Android (default and volley)?

Here are some good starting points:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/android/model.mustache

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/android/libraries/volley/model.mustache

**Comment by andriydruk** [comment]
@wing328 yes. Should I rebuild samples after my fix? Could you explain how I should do it? 
When I execute android-petstore.sh, script rebuilds the only subset of models like 'User', 'Tag', 'Pet' but doesn't 'Animal', 'Dog', 'Cat', etc.

**Comment by wing328** [comment]
@andriydruk have you done a `mvn clean package` before running `./bin/android-petstore.sh`?

**Comment by wing328** [comment]
@andriydruk btw, please pull the latest before working on your fix.

**Comment by andriydruk** [comment]
@wing328 yes, I've done this. 
I've just looked at `./bin/android-petstore.sh`. It contains `-i modules/swagger-codegen/src/test/resources/2_0/petstore.json`. 
In this [petstore.json](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json) I can't find any of `Animal`, `Cat` or `Dog` models, but these classes are already in samples.

**Comment by wing328** [comment]
Sorry, those are left over after updating the spec.

You can choose to purge the model and api models before running ./bin/android-petstore.sh again.

**Comment by JonasPrap** [comment]
What about when using Java client and target Android?

**Comment by andriydruk** [comment]
Hi JonasPrap, 

@wing328 asked for help only for Android version. In Java version this problem still exists, and I don't know how to fix it without influence on all Java projects.

Frankly speaking, I think that it's a bad idea to use flag for Java version. Maybe would be better to create android specific versions for such libraries like 'retrofit', 'retrofit2', etc.
