### ISSUE TITLE
argument list vs single argument object

### ISSUE THREAD

**Issue by leonyu** [swagger-api/swagger-codegen#2665]
I am looking to create my own codegen template specifically for TypeScript with XHR. If it is generic enough, I might create a PR to merge it back. 

However, looking at the two existing TypeScript implementations, they both use argument list instead of argument object: 
```typescript
public reqPost (url: string, format?: string, title?: string, note?: string, _private?: boolean, domain?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<Result> { }
```
Since a lot of the API params are optional for my project, I would much prefer
```typescript
public reqPost (testParams: TestParams, extraHttpRequestParams?: any ) : PromiseLike<Result> { }
```
Is there existing facility for doing this? e.g. have those codegen targets generate an object based API? 
If not, what is the consensus around it? Is there an option for user to choose between the two within a single client target?

**Comment by wing328** [comment]
One option is to customize it: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/api.mustache and pass the customized template folder via command line argument `-t`
