### ISSUE TITLE
[Swift] Generated SDK build fails when using request parameters of type integer in query or body

### ISSUE THREAD

**Issue by fabdslv** [swagger-api/swagger-codegen#2669]
It is caused by the fact that `Int32` is not convertible into `AnyObject`. In the API method, the following code fails to build : 

```
public class func getPerson(name: String? = nil, age: Int32? = nil) -> RequestBuilder<[EntityBrief]> {
       
        let URLString = MyAPI.basePath + "/person"

        let nillableParameters: [String:AnyObject?] = [
            "name": name,
            "age": age
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[EntityBrief]>.Type = MyAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

```

**Comment by cjolif** [comment]
This seems to be a follow up of some of my work. So I'll look into this. thanks for reporting.

**Comment by fabdslv** [comment]
@cjolif Okay, thanks.

**Comment by fabdslv** [comment]
[Here](https://gist.github.com/fabdslv/12fbb7918d41e0cbc7e057ffeb061e3e) you can find Petstore swagger modified with only `getPetById` request, failing because I removed the `format` property.

**Comment by fabdslv** [comment]
After review, `format` property doesn't change anything, the issue is related to the parameter location : it is working for `path` but not for `query` or `body`. I updated the gist in consequence.

**Comment by cjolif** [comment]
PR: #2674

**Comment by wing328** [comment]
@fabdslv PR (by @cjolif ) merged into master. Please pull the latest master and let us know if you still experience the issue.

**Comment by fabdslv** [comment]
@wing328 It seems to be fixed, thanks

**Comment by wing328** [comment]
@fabdslv thanks for the confirmation. Credits go to @cjolif
