### ISSUE TITLE
how to use swagger codegen with symfony2

### ISSUE THREAD

**Issue by NadaBen** [swagger-api/swagger-codegen#2673]
Hello, i'm developping an api with symfony2, i'm using nelmio bundle for documentation task, i want to know how to use swagger-codegen to generate and support other languages

**Comment by wing328** [comment]
@NadaBen sorry I don't quite understand what you mean.

Is your API documented in Swagger Spec? If yes, you can use it to generate API clients, server stubs, documentation. Please refer to https://github.com/swagger-api/swagger-codegen#getting-started to get started.

**Comment by NadaBen** [comment]
I'm searching for a documentation to use swagger-codegen with symfony2

**Comment by wing328** [comment]
@NadaBen are you looking for this instead? https://github.com/activelamp/swagger-ui-bundle

**Comment by NadaBen** [comment]
this bundle can help in documentation case, i want to generate code for other languages

**Comment by wing328** [comment]
if you use that bundle, you should be able to obtain or generate the openapi/swagger spec.

Once you've the spec, you can refer to https://github.com/swagger-api/swagger-codegen#getting-started as a starting point on using swagger codegen to generate different API clients given the openapi/swagger spec.

**Comment by NadaBen** [comment]
I tried what u proposed to me, when i run the command 
`java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i http://localhost/test/web/app_dev.php/v1/photos/bymachinetags.json -l php -o c:\temp\php_api_client`

it shows me this error:
`[main] INFO io.swagger.parser.Swagger20Parser - reading from http://localhost/test/web/app_dev.php/v1/photos/bymachinetags.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://localhost/test/web/app_dev.php/v1/photos/bymachinetags.json
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:89)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)`

**Comment by wing328** [comment]
From the error, seems like it cannot find `http://localhost/test/web/app_dev.php/v1/photos/bymachinetags.json`

**Comment by NadaBen** [comment]
that can be linked to the swagger-ui-bundle configuration ?

**Comment by wing328** [comment]
For swagger-ui-bundle, you may want to use `dev-master` which supports Swagger 2.0: https://github.com/activelamp/swagger-ui-bundle#for-swagger-v1x-support-use-the-v021-of-this-repository-dev-master-is-now-using-swagger-v2

That may resolve the issue you encountered above.
