### ISSUE TITLE
Typescript angular2 should have a package.json

### ISSUE THREAD

**Issue by Vrolijkx** [swagger-api/swagger-codegen#2677]
For know the TypeScript angular2  generator only generate typescript files. It would be better if it could create a whole node/npm project. This way we could publish our client to npm and import it into other projects.

I created a pull request with a working example #2676

**Comment by Vrolijkx** [comment]
@wing328  This issue is resolved.

**Comment by wing328** [comment]
@Vrolijkx thanks for your contribution.
