### ISSUE TITLE
ubuntu "\lib\Models" instead of "/lib/Models"

### ISSUE THREAD

**Issue by woohooyayaya** [swagger-api/swagger-codegen#2682]
I followed this tutorial([https://azure.microsoft.com/en-us/documentation/articles/machine-learning-consume-web-services/](url)) and tried to generate php client code in regards to the deployed Azure service. 

This is the output on the terminal.

> ubuntu@ubuntu:~/Downloads/swagger/swagger-codegen-master$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/Downloads/swagger.json -l slim -o ~/server/fp/slim[main] INFO io.swagger.parser.Swagger20Parser - reading from /home/ubuntu/Downloads/swagger.json
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/AzureBlobDataReference.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/BatchExecutionRequest.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/BatchExecutionStatus.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/BatchInputs.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/BatchOutputs.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/ExecutionInputs.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/ExecutionOutputs.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/ExecutionRequest.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/ExecutionResults.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/GlobalParameters.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/Input1Item.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer\lib\Models/Output1Item.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer/README.md
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer/composer.json
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer/index.php
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /home/ubuntu/server/fp/slim/SwaggerServer/.htaccess

And this is what the folder looks like that files were supposed to be written to after the command finished running. The "\lib\Models/" folder is not showing up at all.

> ubuntu@ubuntu:~/server/fp/slim/SwaggerServer$ ls
composer.json  index.php  README.md

Then I realized "\lib\Models/" should be "/lib/Models/" instead.

Are there any quick fixes to this???

Thank you.

**Comment by wing328** [comment]
@woohooyayaya  I did a test but couldn't repeat the issue in Mac or Ubuntu. Here is the partial result:
```
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/apps/tmp/swagger-codegen/samples/client/petstore/php/SwaggerClient-php/autoload.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/apps/tmp/swagger-codegen/samples/client/petstore/php/SwaggerClient-php/README.md
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /var/apps/tmp/swagger-codegen/samples/client/petstore/php/SwaggerClient-php/.travis.yml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/apps/tmp/swagger-codegen/samples/client/petstore/php/SwaggerClient-php/git_push.sh
dev01@dev01 swagger-codegen %uname -a
Linux dev01 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

May I know which version of swagger codegen did you use?

**Comment by wing328** [comment]
@woohooyayaya you may also want to try the online generator as well: https://github.com/swagger-api/swagger-codegen#online-generators

**Comment by wing328** [comment]
@woohooyayaya closing this as there's no update from you.
