### ISSUE TITLE
[Swift?] arbitrary JSON

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2683]
Some swagger file do not define exactly the type of some return/input. The just say "type:" "object" and potentially return arbitrary JSON (i.e. not in a well defined format). Swift generator does not provide any means to deal with that. Is that something some of the other generators are doing? Is that something that would make sense to add?

**Comment by jaz-ah** [comment]
@cjolif so Swift is returning an "AnyObject" now to deal w/ this, Android returns an "Object" - and then these can be decoded appropriately - would you rather something more explicit somehow?

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/issues/2093 is another discussion thread related to arbitrary JSON.

**Comment by cjolif** [comment]
@wing328 #2093 indeed looks very much like my issue, so I guess we can close this one.
