### ISSUE TITLE
Pass environment variables from maven plugin to generators without using system properties

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#2698]
Currently the maven plugin (and CodegenConfigurator) sets system properties (from `<configuration><environmentVariables>`), which are then read by later code (DefaultGenerator (12×), DefaultCodegen (1×), and also some of the language Codegens (3×)).

As noted in #2232, this causes several problems, as the properties leak out, both to later executions of the same plugin (which might need different or no values for them) and to other maven plugins, which might be using the same names for other meanings. Also, maven offers better ways to set global system properties.

Instead of building a workaround in the plugin by saving and restoring the system properties, the right way of doing this would be to pass this information in a different way from the plugin (or other ways the CodegenConfigurator is called) to the users.

Currently the system properties are copied into `additionalProperties` if a language module declares a CliOption of the same name. I guess the same could be done for the properties used by DefaultGenerator: `debugOperations`, `debugSupportingFiles`, `debugModels`, `debugSwagger` and the options `models`, `apis`, `supportingFiles` defining what to generate – though the latter ones could become actual command line arguments instead.

We could still allow users to use system properties to pass in this information from the outside, but should not be setting system properties inside codegen. (So CodegenConfigurator would have a look at the system properties, allowing them to override the command line arguments, or fall back to them if the command line arguments are not given?)

**Comment by fehguy** [comment]
The maven plugin needs a refactoring so it uses the same configuration process as the CLI tool.

**Comment by ePaul** [comment]
Actually currently both are using `System.setProperty`, the maven plugin even twice for each property (once directly, once in CodegenConfigurator).

**Comment by ePaul** [comment]
I just found this issue which I opened one year ago ... I guess it can count as a duplicate of #4788.
