### ISSUE TITLE
Replace jMustache with more advanced template engine

### ISSUE THREAD

**Issue by Danielku15** [swagger-api/swagger-codegen#2704]
I am not sure if this topic was already discussed somewhen, I could not find any related topic via search. 

Mustache advertises itself as "Logic-less templates" (http://mustache.github.io/) which makes it somehow hard to implement advanced code generators. You need to prepare a lot in the Java backend for type mappings etc. and even then it's some times challenging to get the behavior you'd like to have. 

An example: You generate your model classes and have some dedicated JSON conversion functions for the different swagger types. There is no way to make something like: 
```
{{#if property.type == "string"}}
 property.value = convertToString(jsonValue)
{{/if}}
```

In C# (ASP.net) there is a really nice template engine called Razor which translates the template into a C# class. This means you can utilize all benefits of C# within your templates. In the Java world the equivalent to Razor is Rhythm: http://rythmengine.org/doc/feature Mustache might be simple to learn and write, but I think for code generation an advanced template engine is more suitable. 

I would really like to see a more advanced template engine for swagger codegen to utilize all JDK functions and access all model properties as I want them to use.   

I am currently working on a C++ codegenerator for our project but struggle a lot with the type conversions since complex types need different serialization than basic types or strings.

**Comment by wing328** [comment]
@Danielku15 thanks for the feedback. Can you share a bit more about the issue encountered when implementing the C++ code generator? (I'm sure you aware that swagger codegen already supports 2 C++ generator: qt5 and tizen)

We've already added a lot of boolean flags to mustache template and you can find out more here: https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables. Would this help?

For detecting complex type, what about using `{{^primitiveType}}` ?

**Comment by Danielku15** [comment]
I mainly have troubles with aligning the property types of model classes with matching JSON serialization/deserialization methods. Arrays are mapped to `std::vector` other model classes are kept as `std::shared_pointer<ModelType>`. In the code behind I setup the mappings similar like done here: https://github.com/MathiasWasAlreadyTaken/swagger-codegen/tree/development

The serialization on this repository is far from complete and already requires some "custom objects" being stored as part of the properties and operations. I tried to generate the code without touching the core part of the code generation but failed. A model class can become quite complex like: 

```cpp
class MyModel
 : public ModelBase
{
private: 
    std::vector<utiltiy::string_t> m_Strings;
    int m_IntValue;
    std::shared_pointer<MyModel> m_NestedModel;
    std::vector<std::shared_pointer<MyModel>> m_NestedModelVector;
}
```

Since the JSON serialization/deserialization is done manually in cpprestsdk I need to have proper mapping functions which can create and read such types. I managed to get many cases working by using templates, but you can imagine how hard it's to generate a code like the following:

```
void MyModel::fromJson(const web::json::value& value) const 
{
    //...
    m_NestedModelVector.clear();
    for(web::json::value& item : value[U("nestedModelVector")])
    {
        std::shared_pointer<MyModel> model(new MyModel());
        model->fromJson(item);
        m_NestedModelVector.push_back(item);
    }
    //...
}
```

The type of m_NestedModelVector is arleady the full `std::vector<std::shared_pointer<MyModel>>` it's impossible to unwrap this type again to std::shared_pointer<MyModel> or new MyModel() 

Strings seem to be treated as complex types just like normal model classes. all model classes have a fromJson/toJson but not std::string/utility::string_t . 

I could try to move more logic into the templates but I fear that won't solve my problems.

**Comment by wing328** [comment]
>  Arrays are mapped to std::vector other model classes are kept as std::shared_pointer<ModelType>

Would the boolean flag `isListContainer` help in your situation to determine if it's a list/array?

I would also recommend you to look at how other languages perform serialization/deserializaton of JSON

**Comment by purpleKarrot** [comment]
> I am currently working on a C++ codegenerator for our project but struggle a lot with the type conversions since complex types need different serialization than basic types or strings.

Why? Especially in C++ you should be able to treat different types the same way.

For each complex type you would generate a function like the following:
```
std::string convertToString(ComplexType const& v) { ... }
```

For builtin standard types you would provide implementations in a support library:
```
std::string convertToString(int v) { return std::to_string(v); }
std::string convertToString(std::string v) { return v; }
```

Then you just always call `convertToString`, no condition needed.

**Comment by Danielku15** [comment]
@wing328: Most of the other languages have a runtime type information (reflection) available all serialization is done automatically within the JSON framework. In C++ you do not easily get this information.I had a look at the QT serialization, there it seems that string comparisons during runtime are used to do the serialization. I find this approach with void pointers and string comparisons a bit dangerous, but is seems to work. 

@purpleKarrot: I want to store all complex types as std::shared_pointer objects, not as copies. This will result again in some c++ template methods which I struggled with to work correctly. During my tests the linker started to complain about not finding the correct methods.

**Comment by wing328** [comment]
@Danielku15 please take a look at PHP: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

It relies on swagger_type mapping (static): e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/Model/Pet.php#L59

**Comment by wing328** [comment]
> I would really like to see a more advanced template engine for swagger codegen to utilize all JDK functions and access all model properties as I want them to use.

Thanks for the feedback. I've not tried Razor nor Rhythm so I cannot comment on those. I'm not surprised if there's a template system/library out there better than mustache. One thing we also need to consider is the "switching cost" from mustache to another one as we cannot assume our contributors are familiar with the mustache replacement.

Given that mustache is also improving (recent upgrade allows cleaner template and easier alignment), my take is to stick with mustache for now.

**Comment by Danielku15** [comment]
Sticking for Mustache is also an option. To allow more advanced templating also new model properties and helpers could do the job. In the end, in my opinon, it should be possible to access exactly the original swagger schema and all of it's properties. By combining the full model with some more advanced helpers, also building conditions, string replacements, loops etc. should easily possible. 

But since it sounds like reinventing the wheel to me, I thought of proposing a template engine where you anyhow have access to the full language features and data models.

**Comment by wing328** [comment]
@Danielku15 thanks again for the suggestion. We mark this as a feature request pending community contribution for now.

**Comment by wing328** [comment]
@Danielku15 do you need any help adding the `cpprestsdk` support? I would suggest you to file a PR so that the community can help review the change make improvements to it.

**Comment by Danielku15** [comment]
I am still working on the generation. I tried also some other code generators to check which works best for our code generation. I lately found out that you are using really only the very basic "mustache" engine. When working with mustache templates I usually prefer "Handlebars" which is a bit more advanced since you can register custom helpers which do more advanced stuff. 

Take a look at this library for Java: 
https://github.com/jknack/handlebars.java

If for some particular reasons more advanced logic is required, the particular language generator can register some helpers which are then used in the template. 

Would such a solution sound more feasable for you? 

If I can manage to write a code generator that would be reusable for the public I will share it. I am currently focusing hard on getting our API specifics into the generator as we need it. One example is that we also need application/x-multipart-formdata serialization to support file uploads. We write our API with ASP.net Web API which could result in some particular extra logic which only applies for Web API.

**Comment by wing328** [comment]
Hi all,

I've checked with Daniel, who has created the C++ generator in https://github.com/Danielku15/swagger-codegen-cpprestsdk and here is the latest update:

> It has reached a state where API calls can be made and serialization works. There are still quite some parts missing like model validation, generating docs etc. 

If anyone has cycle to plot it back to Swagger Codegen, please reply to let us know.

**Comment by MathiasWasAlreadyTaken** [comment]
Thats nice! My work on the cpprest generated has stopped completely due to change of track to Apache Thrift at the company I work for. Nice that someone completed a cpprest generator.

**Comment by Danielku15** [comment]
We are already actively using the SDK generated by my code generator in our software and the client will be part of our next software release. If you only need to state calls including some generic error handling the generator works perfectly fine. If the API call fails (status code >= 300) you receive an ApiException where you can parse the body manually. For success calls the main response parsing is supported. 

A special feature (which is currenty invalid according to OpenAPI spec, see [#694](https://github.com/OAI/OpenAPI-Specification/issues/694)) is that you can even have HTTP files as part of your models. This means all models can be serialized as JSON and as multipart/form-data. 

As @wing328 quoted me already: There is no client side validation so far and also the output documentation is quite bad, also no tests can be generated. The very essentials: model and operation generation works fine and are working. Currently my templates rather focus on readablity of the code than readability of the templates themselves. Handling spacing and new lines in mustache is really hard. Without those _ugly_ templates I used to have like 5-10 empty lines in some of the generated code.

**Comment by wing328** [comment]
@Danielku15 FYI. jmustache has a new feature to trim empty lines: https://github.com/samskivert/jmustache#newline-trimming

**Comment by wing328** [comment]
To all, I've started plotting the c++ generator created by Daniel to Swagger Codegen.

**Comment by wing328** [comment]
@Danielku15 some mustache template files seem to be missing:
```
        supportingFiles.add(new SupportingFile("modelbase-header.mustache", "", "ModelBase.h"));
        supportingFiles.add(new SupportingFile("modelbase-source.mustache", "", "ModelBase.cpp"));
        supportingFiles.add(new SupportingFile("apibase-header.mustache", "", "ApiBase.h"));
        supportingFiles.add(new SupportingFile("apibase-source.mustache", "", "ApiBase.cpp"));
```
I couldn't find these mustache templates in https://github.com/Danielku15/swagger-codegen-cpprestsdk/tree/master/src/main/resources/cpprestsdk. Do you mind taking a look and adding them back if needed?

**Comment by Danielku15** [comment]
The files [modelbase-header.mustache](https://github.com/Danielku15/swagger-codegen-cpprestsdk/blob/master/src/main/resources/cpprestsdk/modelbase-header.mustache
) and [modelbase-source.mustache](https://github.com/Danielku15/swagger-codegen-cpprestsdk/blob/master/src/main/resources/cpprestsdk/modelbase-source.mustache) are in the repository. For the apibase files you are right they are missing, but only because they are not required anymore. 

I updated the repository accordingly.

**Comment by wing328** [comment]
PR merged into master. Issue closed.

Thanks @Danielku15 again for his contribution.
