### ISSUE TITLE
swagger codegen maven plugin issue with java 1.6

### ISSUE THREAD

**Issue by chirag272003** [swagger-api/swagger-codegen#2709]
I am using swagger codegen maven plugin 2.1.6 along with java 1.7. But my server side rest api is developed on java 1.6.

Everything works fine but ClientResponse.getStatusInfo() never matches with ClientResponse.Status.BAD_REQUEST due to java version mismatch. I can see that all the values of statusinfo enum(status code, family and reasonphrase) are same in both.

Please let me know if above use case of having server on java 1.6 and using swagger plugin with java 1.7 is valid.

Also I see that swagger codegen 2.1.4 uses maven-compiler-plugin of 1.6 it has code from java 1.7.
For example usage of import java.nio.file.Paths inside CodegenConfigurator.java class.

**Comment by wing328** [comment]
@chirag272003 the minimal requirement is Java1.7: https://github.com/swagger-api/swagger-codegen#prerequisites

Would you consider upgrading the server to use Java1.7 instead?
