### ISSUE TITLE
The classes should implement equals(), hashCode() and toString().

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2711]
As a matter of general Java hygiene, all of the modeling classes (e.g. `CodegenModel`) should implement `equals()` and `hashCode()`, especially given that they are stored/accessed via Collections.. subtle bugs can appear when dealing with collections and these methods are not implemented. A friendly `toString()` also makes debugging a lot easier.

**Comment by wing328** [comment]
PR merged. Thanks for the contribution.
