### ISSUE TITLE
Can I use a json string or json as input for code-gen?

### ISSUE THREAD

**Issue by alvindaiyan** [swagger-api/swagger-codegen#2713]
Hi,

As when I use the code-gen, my server side uses a cookie for session management. It looks like code-gen not supports cookie. So can I use a json file as input?

Also, if the return type has generic types, the static html page looks bad:

`
SomethingÂ«SomethingImplÂ»
`

**Comment by wing328** [comment]
For input, do you mean parameter (body or form)?

For the static html page issue, do you mind sharing the spec so that we can more easily reproduce the issue?

**Comment by alvindaiyan** [comment]
Thanks for response.

For the input, I mean, for example, I run the command line 
`
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate 
  -i my/local/path/swagger-api.json 
  -l java 
  -o samples/client/petstore/java
`
where the "my/local/path/swagger-api.json" is on my file system not from a server. Because I understand the "-i" takes an url as input, I want to use a file path as input in this case.

For the generic type problem, I will try to reproduce it because the original code is from my work project.

**Comment by wing328** [comment]
"-i" works with both local path and URL. Please give it a try. You can refer to more examples in README.md.

**Comment by alvindaiyan** [comment]
Yes, you are right. The "-i" option does working with local path. The reason I ignored this because when I run my json, it throws multiple null pointer exception:
`com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.swagger.models.properties.RefProperty["$ref"])`

But the file was there which I didn't check. 

Also, for the generic problem, this bug is from the swagger core because the swagger.json has the bad looking string for generic types.

Please close this issue. 
Thanks

**Comment by ePaul** [comment]
Where did you get the idea to use `«...»` for generic types?

It looks like either you are looking at the output file with a wrong encoding, or somewhere the way the encoding is handled wrong. (I think `«` and `»` are not valid in Java names, so they should be escaped somehow, I guess. I'm not sure what you are expecting, though)

**Comment by fehguy** [comment]
@ePaul I think that's a bug in SpringFox

**Comment by alvindaiyan** [comment]
the `«...»` is from swagger. Because the api has a generic type with the return. In this case, it's `Something<SomethingImpl>`. The springfox will generate a json string `Something«SomethingImpl»` and the codegen will generate "SomethingÂ«SomethingImplÂ»". In my opinion, both springfox and codegen should avoid this case.

**Comment by wing328** [comment]
@alvindaiyan to me it's more like a bug in SpringFox. Please kindly open an issue with SpringFox.
