### ISSUE TITLE
[Go] [Bug] api_response file does not use package variable

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2717]
See [line 1](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/api_response.mustache#L1) ... this should be using the `{{packageName}}` variable instead of fixed as `swagger`. This causes the compilation to fail if the user has specified the `packageName` variable in their config.

On a more general note, this testifies to our need for an automated testing framework for our Go code... we really shouldn't be merging into master changes that produce Go code that won't compile (obviously!). But it's easy to do this today, alas.

**Comment by wing328** [comment]
@neilotoole agree with you that we need better way to test the auto-generated Go package.

For other languages, there's a way to automatically generate [test files (skeleton)](https://github.com/swagger-api/swagger-codegen/issues/2276). Is that what you've in mind?

To prevent this particular issue from happening again, we need to update the Petstore Go API client to use a different package name (e.g. Petstore) instead of `swagger` (default).

**Comment by wing328** [comment]
According to https://blog.golang.org/package-names, the package name should be in lower case so we should use `petstore` instead.

**Comment by neilotoole** [comment]
@wing328 Yes, we should be generating test stubs, but the key thing is that we need to execute those stubs as part of the check process before a PR can be merged. As we discussed before, the easiest way to do this is by executing the Go tests in a container...

**Comment by neilotoole** [comment]
@wing328 I'm not quite sure what you're referring to re the package-names... the `{{packageName}}` var will get substituted at generation time by whatever variable the user has specified in their config (which should be a lowercase value, yes)...

**Comment by neilotoole** [comment]
Ah, I think I see what you're saying now... re not using the default `swagger` name. Must get coffee!

**Comment by wing328** [comment]
☕ ☕ ☕

**Comment by wing328** [comment]
PR merged. 

For the improvement, we'll open another task for tracking.
