### ISSUE TITLE
[Go] Use "petstore" instead of "swagger" for Go petstore package name

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2722]
For the related discussion, please refer to #2717

**Comment by guohuang** [comment]
isn't the additional property going to replace the default package name?
 https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java#l121

**Comment by wing328** [comment]
You need to specify it via command line or config file. If not provided, it will use the default `swagger`

**Comment by wing328** [comment]
PR merged. Closing this.
