### ISSUE TITLE
[Go] [Bug] import of 'encoding/json' not always required

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2725]
In `api.mustache`, we currently always [import](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/api.mustache#L7) `encoding/json`. However, if none of the operations in an API return an object (e.g. if there's only one operation and it's just a DELETE), then this import is unused, and thus we have a Go error.

**Comment by wing328** [comment]
PR merged into master
