### ISSUE TITLE
Export Client HTML Error

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2730]
_From @taufiksu on April 27, 2016 12:50_

I cannot download export client html and php

_Copied from original issue: swagger-api/swagger-editor#895_

**Comment by saharj** [comment]
This is probably a codegene issue. Please provide your swagger document. I'm moving it to swagger-codegen.

**Comment by wing328** [comment]
@taufiksu can you please share the spec so that we can use it to reproduce the issue?

**Comment by wing328** [comment]
@taufiksu closing this as there's no update fro you. Please provide the spec so that we can troubleshoot.

Closing this for now.
