### ISSUE TITLE
SWIFT Error parsing int to string

### ISSUE THREAD

**Issue by Glagnar** [swagger-api/swagger-codegen#2735]
I have a swagger definition where an attribute is defined as a type String.
In reality, sometimes data is returned as a String, other times as an int.

`{"@iot.id":100}`

The C# code casts the int to a String at runtime, but the SWIFT code crashes. I do not know what the correct solution is to the problem - the C# behaviour or the SWIFT behaviour. One could argue that you can always cast an int to String.

**Comment by Glagnar** [comment]
I found that declaring the attribute as type 'object' solves my problem, and allows the generated code to correctly parse the json. But I dont know if this is the correct solution.

**Comment by wing328** [comment]
If the data is arbitrary json, then it should be described as "type: object"
