### ISSUE TITLE
[develop 2.0] nickname generator fails with Path Parts

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#274]
When an `operationId` is not specified, the codegen logic makes invalid method names when path params are present

**Comment by earth2marsh** [comment]
Could this have regressed, possibly? Importing a description with path params but no operationid is causing complaints about unsupported characters.

**Comment by fehguy** [comment]
@earth2marsh can you please share a sample?

**Comment by earth2marsh** [comment]
Yessir! https://gist.githubusercontent.com/earth2marsh/db8ab2ffcb4895e78d14/raw/3a4ebdd242fa4b4c9e0b0fcff5dd44ae8842b78f/apm.json

**Comment by webron** [comment]
@earth2marsh - that's because you have a typo there. You use `operationid` instead of `operationId`. Change that and you should be good.

**Comment by earth2marsh** [comment]
Sorry, it looks like I linked to the wrong revision of that spec where I had later added the operationid to test it. :facepalm 

@webron try this: https://gist.githubusercontent.com/earth2marsh/db8ab2ffcb4895e78d14/raw/0241924f47061a5f6668874651926779a781df9f/apm.json

If you bring that into swagger-codegen, then you should see the error as it tries to use the brace char to create the operationId.

**Comment by webron** [comment]
@earth2marsh - do you get errors for a specific language? Just tried running it with the java client generator and didn't get any errors. However, I'm not sure that's the sample you wanted to share because in your original post you mentioned the path params seem to be causing the issue and the sample has no path parameters.

**Comment by earth2marsh** [comment]
@webron I'm not sure what happened here—I must have had some wires crossed somewhere. You're totally right that my sample doesn't actually cover the issue I described, and I can't seem to reproduce my original issue. My apologies for the wild goose chase! I'm going to go back to the start again and see if I can make this happen predictably.

**Comment by webron** [comment]
@earth2marsh - no worries, it's better to check on issues that can't be reproduced thanto not be aware of ones that can :)
