### ISSUE TITLE
Unable to generate signed apk while using swagger generated retrofit - HTTP client

### ISSUE THREAD

**Issue by rahulc-nrift** [swagger-api/swagger-codegen#2741]
I am not able to generate signed APK when I am using swagger generated retrofit 1 HTTP client 

Following warnings messages are thrown 

Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find superclass or interface org.apache.oltu.oauth2.client.HttpClient
Warning:com.dummy.trading.oms.model.AccountBalanceInfo: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.AccountBalanceInfo: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.AccountSummary: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.AccountSummary: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.CloseContractQueryResult: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.CloseContractQueryResult: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.CloseContractSummaryView: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.CloseContractSummaryView: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ContractCounts: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ContractCounts: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ContractQueryCriteria: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ContractQueryCriteria: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ContractQueryResult: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ContractQueryResult: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ContractSummaryView: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ContractSummaryView: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ErrorInfo: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ErrorInfo: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ExerciseRequest: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ExerciseRequest: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.InlineResponse200: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.InlineResponse2001: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.InstrumentQueryCriteria: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.InstrumentQueryCriteria: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.InstrumentQueryResult: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.InstrumentQueryResult: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.InstrumentSummary: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.InstrumentSummary: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.MapOfstringAndstring: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.MenuDTO: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.MenuDTO: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.MktDataInfo: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.MktDataInfo: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderAmendRequest: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderAmendRequest: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderCancelRequest: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderCancelRequest: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderDetails: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderDetails: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderEntryRequest: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderEntryRequest: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderExecution: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderExecution: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderHistory: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderHistory: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderQueryCriteria: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderQueryCriteria: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderQueryResult: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderQueryResult: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.OrderSummaryView: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.OrderSummaryView: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.PrefMap: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.SecurityInfo: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.SecurityInfo: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.UserCredentials: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.UserCredentials: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.UserDetailsDTO: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.UserDetailsDTO: can't find referenced class io.swagger.annotations.ApiModel
Warning:com.dummy.trading.oms.model.ValidationResponse: can't find referenced class io.swagger.annotations.ApiModelProperty
Warning:com.dummy.trading.oms.model.ValidationResponse: can't find referenced class io.swagger.annotations.ApiModel
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$AuthenticationRequestBuilder
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$AuthenticationRequestBuilder
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.ApiClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$AuthenticationRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.OAuthClient
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.message.types.GrantType
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.message.types.GrantType
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthBearerClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthSystemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.OAuthClient
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthProblemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$AuthenticationRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthSystemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthProblemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.message.types.GrantType
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.OAuthClient
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$AuthenticationRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthSystemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthSystemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthProblemException
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$TokenRequestBuilder
Warning:io.swagger.client.auth.OAuth: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest$AuthenticationRequestBuilder
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthSystemException
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.HttpClient
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.common.exception.OAuthProblemException
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthClientResponse
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.response.OAuthClientResponse
Warning:io.swagger.client.auth.OAuthOkHttpClient: can't find referenced class org.apache.oltu.oauth2.client.request.OAuthClientRequest

**Comment by wing328** [comment]
@rahulc-nrift please share the spec so that we can use it to repeat the issue.

**Comment by rahulc-nrift** [comment]
Hi wing,

I am working on android app where I used swagger codegen to generate
retrofit 1.9 client library . In android debugging mode it is working fine
. But when I try to generate signed apk It was showing mentioned warning .
I have prepared proguard rules and also included retrofit and related rules
. Please find below mentioned proguard rules


Please let me know if done any thing wrong or do I need to specify any
thing more in proguard related to generated client lib.

I faced same problem when I was using AWS API gateway . But after adding
some rules in proguard that issue was resolved . Those rules was mentioned
in there documentation .


-keep interface retrofit.** { *;}
-keep interface com.squareup.** { *; }
-dontwarn rx.**
-dontwarn retrofit.**

-dontwarn org.apache.lang.**


-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

-keepattributes EnclosingMethod

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }

-dontwarn okio.**

-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**
-dontwarn okio.**


Thanks in advance


*Rahul C*
Associate Software Engineer – Technology
-------------------------------------------------------------------------------------------------------------------
Nomura Research Institute Financial Technologies India Pvt. Ltd.
Office: +91-33-6604-1000  Ext: 1631
Mobile: +91-9874-233-500
Email: rahulc@nrifintech.com <abc@nrifintech.com>
NRI Corporate Site <http://www.nri.com/global/> | NRI Financial Solutions
<http://fis.nri.co.jp/en/index.html> | NRI Financial Technologies India
<http://www.nrifintech.com/>

On Sun, May 1, 2016 at 9:58 AM, wing328 <notifications@github.com> wrote:

> @rahulc-nrift <https://github.com/rahulc-nrift> please share the spec so
> that we can use it to repeat the issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-codegen/issues/2741#issuecomment-216015423>
>

-- 
***********************************************************************************
***************

PLEASE READ: The information contained in this e-mail is confidential  and 
intended 
for the named  recipient(s)  only. If  you are not  an intended recipient 
of this  e-mail 
please  notify the sender immediately and delete your copy  from your 
 system. Our 
company accepts no liability for any damage sustained as a result of 
viruses in this 
e-mail or any attachment(s) to it.

***********************************************************************************
***************

**Comment by wing328** [comment]
@rahulc-nrift I would suggest you pull the latest master, build the JAR and generate the Retrofit 1.x SDK in a new directory as the warning is related to missing dependency.

**Comment by wing328** [comment]
@rahulc-nrift let us know if you still experience the issue with the latest master.

Closing the issue for now.
