### ISSUE TITLE
[PHP] Unit tests are generated in wrong directory

### ISSUE THREAD

**Issue by mikolajprzybysz** [swagger-api/swagger-codegen#2743]
I have used most recent version from master branch and I noticed that the tests are generated in the default directory even though I have set up custom InvokerPackage.

Additionally I would like to propose decoupling code from tests by moving the test outside lib directory to have it on the same level as lib.

**Comment by wing328** [comment]
Are you using codegen on the windows platform?
2016年4月29日 下午9:31於 "Mikołaj Przybysz" <notifications@github.com>寫道：

**Comment by mikolajprzybysz** [comment]
My OS is Ubuntu 14.04, you can find changes in PR "Issue 2743"

**Comment by wing328** [comment]
@mikolajprzybysz thanks for the PR. I believe it addresses the issue as well as adding the proposed enhancement to the library (decoupling code from tests).

We'll review and let you know if we've any question.

**Comment by wing328** [comment]
PR: #2753

**Comment by wing328** [comment]
PR: https://github.com/swagger-api/swagger-codegen/pull/2753

**Comment by wing328** [comment]
PR merged. Issue closed.
