### ISSUE TITLE
Python-Flask Server generated code on editor.swagger.io produces wrong output.

### ISSUE THREAD

**Issue by xamox** [swagger-api/swagger-codegen#2744]
The default_controller.py file is generated as the following:
```

def estimates_price_get(startLatitude, startLongitude, endLatitude, endLongitude) -> str:
    return 'do some magic!'

def estimates_time_get(startLatitude, startLongitude, customerUuid, productId) -> str:
    return 'do some magic!'

def products_get(latitude, longitude) -> str:
    return 'do some magic!'

def history_get(offset, limit) -> str:
    return 'do some magic!'

def me_get() -> str:
    return 'do some magic!'

```

To fix it I just needed to remove the -> but I'm guessing something is not getting parsed correctly to format like below which works:

```

def estimates_price_get(startLatitude, startLongitude, endLatitude, endLongitude):
    return 'do some magic!'

def estimates_time_get(startLatitude, startLongitude, customerUuid, productId):
    return 'do some magic!'

def products_get(latitude, longitude):
    return 'do some magic!'

def history_get(offset, limit):
    return 'do some magic!'

def me_get():
    return 'do some magic!'
```

**Comment by wing328** [comment]
The default is for Python3. To generate the server stub in python2, please supply the following to the command line argument
```
-DsupportPython2=true
```

**Comment by wing328** [comment]
@xamox do you need any help passing the CLI option `-DsupportPython2=true` when generating the Python Flask server stub?

**Comment by xamox** [comment]
@wing328 Thanks for following up.  I didn't realize that -> operator was valid in python3.  I can use python3, I've just been stuck in python 2.7 land for too long.  I found my default python is 2.7 on my host OS, so I'm all good with keeping how it is.  In fact if I read the README that is generated it also states I should be using python3.

**Comment by wing328** [comment]
@xamox no problem. Let us know if you need further assistance. Closing this issue for now.
