### ISSUE TITLE
[Go] Generated code should conform to Go fmt

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2748]
The Go code should conform to the Go conventions. Currently there are spaces instead of tabs, etc. Essentially, running `go fmt` on the generated code should be a no-op.

**Comment by wing328** [comment]
Totally agree and I believe you're working on it :)

Ref: http://stackoverflow.com/a/19094788/677735

**Comment by neilotoole** [comment]
Well yes, as it turns out, I am working on it :-)

Incoming shortly.

**Comment by wing328** [comment]
@neilotoole  PR merged into master. Thank you for your contribution.

**Comment by guohuang** [comment]
that is strange, i used to love tabs when programming in .net, but then it creates a lot of issues, so i ended up switching to spaces, and love it, i don't know why Go chooses tabs as standard. (and it is width of 8, which is a lot)

**Comment by wing328** [comment]
@guohuang same experience here but given that Go explicitly sets the rule (tab with a width of 8), we don't have a choice.
