### ISSUE TITLE
Generated typescript when using additional properties is incorrect.

### ISSUE THREAD

**Issue by Vrolijkx** [swagger-api/swagger-codegen#2751]
The code generated by the Typescript client when having additional properties in the spec file will never compile. The next example is from the typescript-angular2 client. The other Typescript clients have te same problem.
```typescript
export interface User extends models.null<String, string> {
    id?: number;
    userStatus?: number;
}
```
with spec file:
https://gist.github.com/Vrolijkx/b220edc20c6f9379bfc8291ea6e28aec

In other languages they extend from a map to support the additional properties behaviour. But I don't think that's a good solution in Typescript. The support for [Map](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Map) is very browser dependent. Maps are also not converted correctly to json when using ```JSON.stringify()``` so a custom converter will be needed.

I think the best way to support additional properties in Typescript is to go in the next direction:
```typescript
export interface User {
    [key: string]: string

    id?: number;
    userStatus?: number;
}
```

**Comment by wing328** [comment]
@Vrolijkx please go with your suggestion. Let me know if you need updating the TS template.

**Comment by budgebi** [comment]
As was mentioned by @Vrolijkx, this same issue exists in all of the TS clients. I am able to verify that the issue is still occurring in typescript-node. Should I open a new issue for this?
