### ISSUE TITLE
PHP model mustache modification issue

### ISSUE THREAD

**Issue by archana27m** [swagger-api/swagger-codegen#2757]
I am trying to include reference of another generated model from swagger codegen but I am unable to make it using following reference code for mustache in PHP - 

{{#imports}} include_once {{imports}};
{{/imports}}

Please help me, I need to include another model in model file.

**Comment by wing328** [comment]
What about including the model in the PHP model mustache template: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/model.mustache#L38 ?

**Comment by archana27m** [comment]
Like java, I need to import some models and the syntax mentioned above is not working for php.

**Comment by arnested** [comment]
Do you have an example of specification(s) for this? Or an example of another language in Swagger Codegen that does this correct?

I'm not sure I understand when you expect another model to be exposed in `{{import}}`.

**Comment by wing328** [comment]
@archana27m you can use the `-t` (template) option to specify your own customized mustache files.

Closing this issue for now and please reply if you need further assistance.
