### ISSUE TITLE
explicit setting of Api and model package names not working in php -issue with method toPackagePath(String packageName, String basePath)

### ISSUE THREAD

**Issue by sbelan** [swagger-api/swagger-codegen#2759]
Hi,
I am setting package and model name from my code as below.
```
setModelPackage("myApi"+File.separator+"model");
setApiPackage("myApi"+File.separator+"model");

```
But swagger is not creating code as per the mentioned packages. Please let me know, significance of method toPackagePath(String packageName, String basePath) from PhpClientCodegen. As per the observation this method is creating the issue.
`packageName = packageName.replace(invokerPackage, " ");`

**Comment by arnested** [comment]
I believe this is fixed in the current master branch and should appear in the upcoming 2.2.0 release.

**Comment by wing328** [comment]
@sbelan can you please pull the latest master and give it a try?

**Comment by sbelan** [comment]
ok.. will check and let you know.

**Comment by wing328** [comment]
@sbelan closing this as there's no update. Please keep us posted once you've time to perform a check.
