### ISSUE TITLE
PHP Client: Fatal error: Class 'Number' not found in ...lib/ObjectSerializer.php on line XXX

### ISSUE THREAD

**Issue by frostshoxx** [swagger-api/swagger-codegen#2768]
Hi 

We have some issue where the our PHP client code generated by Swagger somehow treat the "Double" type attribute in C# to "Number" type in JSON

When the API method attempts to deserialize the JSON string, it received the error: PHP Client: Fatal error: Class 'Number' not found in ...lib/ObjectSerializer.php on line XXX. I looked around the project, all values that were double on our yaml code are converted to Number. 

Are we missing this Number class? or there is something wrong with the code generator?

Thank you,

**Comment by wing328** [comment]
@frostshoxx which version of Swagger Codegen are you using? v2.1.6 or the latest master?

**Comment by wing328** [comment]
@frostshoxx I can confirm that we've it covered in our test cases: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/Model/FormatTest.php#L170

Please pull the latest master and give it another try.

**Comment by arnested** [comment]
I think what you experience is what we fixed in 194e80ddab0e7adb33d69a787206a76a20f92888. If you try master this should be fixed.

**Comment by wing328** [comment]
@arnested thanks for the confirmation. 

@frostshoxx let me know if you still see the issue and we're happy to reopen this. Closing this for now.

**Comment by frostshoxx** [comment]
I just checked with my colleague, turned out we used the web based swagger https://generator.swagger.io/ to generate the client package.

Do you guys maintain that system as well?

Thank you,

**Comment by wing328** [comment]
@frostshoxx I don't. https://github.com/swagger-api/swagger-codegen#getting-started is a good starting point to build swagger codegen locally. Let us know if you need any help.

**Comment by frostshoxx** [comment]
Thank you, I'll give that a shot!

Best regards,
