### ISSUE TITLE
deserialize 'Array[Pet]' type doesn't support in petstore

### ISSUE THREAD

**Issue by geekerzp** [swagger-api/swagger-codegen#277]
I have played with the api `findPetsWithStatus` of python lib, but i got some errors about this line https://github.com/wordnik/swagger-codegen/blob/master/samples/client/petstore/python/PetApi.py#L356. 
The i reference the `deserialize` method in swagger.py found that in this line(https://github.com/wordnik/swagger-codegen/blob/master/samples/client/petstore/python/swagger.py#L148), it will execute `eval('Array[Pet].Array[Pet]')`, but this thow some errors.
It seems that `deserialize` couldn't handle array of models.
How can i resolve this problem? Thanks

**Comment by fehguy** [comment]
I've confirmed this is fixed in develop 2.0
