### ISSUE TITLE
[typescript-angular2] Update angular2 client for rc

### ISSUE THREAD

**Issue by taxpon** [swagger-api/swagger-codegen#2770]
Angular2 released [rc.0](https://github.com/angular/angular/releases/tag/2.0.0-rc.0) and [rc.1](https://github.com/angular/angular/releases/tag/2.0.0-rc.1).

They started to use npm scoped package, so template should be updated. (see [CAHNGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md))

**Comment by Vrolijkx** [comment]
@wing328 Think this on can be closed.

**Comment by wing328** [comment]
@Vrolijkx you're right. Closing it.
