### ISSUE TITLE
Unicode Local Text Support issue

### ISSUE THREAD

**Issue by catinred2** [swagger-api/swagger-codegen#2779]
checkout here:[escapeText](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L326)

escapeJava would encode the Chinese into unicode like \u8BA1 , so Chinese would not show properly in the generated static html or java code.

**Comment by wing328** [comment]
@catinred2 thanks for reporting the issue. I think this will impact other double byte characters as well.

May I know if you've cycle to contribute a fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by catinred2** [comment]
I'll give it a try tomorrow.

**Comment by wing328** [comment]
@catinred2 thanks. ping me if you need any help.
