### ISSUE TITLE
Incomplete HtmlDoc Generation

### ISSUE THREAD

**Issue by catinred2** [swagger-api/swagger-codegen#2781]
I've placed ApiResponse annotation in controller like this:
`@ApiResponse(code=200, message = "return value",response = GetInfoResult.class)`

and there is no information about GetInfoResult in the generated htmldoc.

> Responses
200
return value
401
Unauthorized
403
Forbidden
404
Not Found

**Comment by wing328** [comment]
PR merged. Issues closed.
