### ISSUE TITLE
java-client compilation error because of missing import

### ISSUE THREAD

**Issue by buremba** [swagger-api/swagger-codegen#2805]
I generated the java-client of [this swagger definition](https://gist.github.com/buremba/a9c87052f7a76284cf8f6fb1fede30de) using version 2.1.6 and tried to install it with maven using `mvn clean install` but it throws compilation error.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project rakam-client: Compilation failure: Compilation failure:
[ERROR] /Users/buremba/Code/rakam-client/java-client/src/main/java/org/rakam/client/api/UsermailboxApi.java:[89,19] error: cannot find symbol
[ERROR] class UsermailboxApi
[ERROR] /Users/buremba/Code/rakam-client/java-client/src/main/java/org/rakam/client/model/OLAPTable.java:[37,5] error: cannot find symbol
[ERROR] class AggregationsEnum
[ERROR] /Users/buremba/Code/rakam-client/java-client/src/main/java/org/rakam/client/api/UsermailboxApi.java:[127,26] error: cannot find symbol
[ERROR] class UsermailboxApi
[ERROR] /Users/buremba/Code/rakam-client/java-client/src/main/java/org/rakam/client/api/UsermailboxApi.java:[127,84] error: cannot find symbol
[ERROR] -> [Help 1]
```

It seems that swagger-codegen fails to import some generated classes so maven complains about missing class error.

**Comment by fehguy** [comment]
Please share your definition so we can help

**Comment by wing328** [comment]
@buremba the issue should be fixed by https://github.com/swagger-api/swagger-codegen/pull/2804

Please pull the latest master and give it another try.

**Comment by buremba** [comment]
@fehguy I already shared that in previous post. You can also find it here: https://gist.github.com/buremba/a9c87052f7a76284cf8f6fb1fede30de

**Comment by buremba** [comment]
@wing328 One of the errors was related with @JsonValue but there is also one other missing import in UsermailboxApi. It fails to import Message model which is not related with @JsonValue.

**Comment by fehguy** [comment]
@buremba please list the files generated by your specification?

**Comment by buremba** [comment]
@fehguy Here is the output: https://gist.github.com/buremba/7fdf83802549e7e9185d1e2b3e931a92

And the configuration that I used for creating java client:
https://github.com/buremba/rakam-client/blob/master/scripts/generated/java.json

**Comment by wing328** [comment]
@buremba I found the issue which is due to array of array of model. Working on a fix now...

**Comment by buremba** [comment]
@wing328 Thanks!

**Comment by wing328** [comment]
@buremba I've filed #2806 to fix it. My manual tests using your spec and config file work.

**Comment by wing328** [comment]
@buremba the fix has been merged into master. Please pull the latest and give it another try.

**Comment by natami** [comment]
Any chance of a bugfix release soon?

**Comment by wing328** [comment]
I think you're referring to stable release of 2.2.0. No timeline yet. Usually it takes 3 to 4 months for a stable release.

For the time being, can you pull the latest master which contains the bug fix?

**Comment by natami** [comment]
The gereration worked with @JsonValue on release 2.1.5.

Is it available on some snapshot repo?

**Comment by wing328** [comment]
You will need to clone this repo and build locally (`mvn install`)

**Comment by natami** [comment]
There is no chance of a 2.1.6.1 fix release - as the support of Enums in the generated models is a pretty important functionality?
