### ISSUE TITLE
how to create decimal in yaml for C# generate code

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2813]
_From @deepakbhise on May 9, 2016 15:24_

_Copied from original issue: swagger-api/swagger-editor#921_

**Comment by wing328** [comment]
@deepakbhise the current type mapping can be found in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java#L112

For your use case, is it correct to say that you must use decimal?

**Comment by wing328** [comment]
@deepakbhise closing the issue as there's no update from you.
