### ISSUE TITLE
[Ruby] convert should to expect in Petstore rspec files

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2816]
`should` needs to be replaced with `expect` (introduced a few years ago) 

Ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

Files that need to be updated: 
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/ruby/spec/pet_spec.rb
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/ruby/spec/store_spec.rb

If anyone from the community wants to work on this, please reply to let us know.

**Comment by zlx** [comment]
Done with a62fa1c80c4cecde0cd349236a0c1ad43253d840

**Comment by wing328** [comment]
@zlx thanks for the contribution

Linked to #2893
