### ISSUE TITLE
modules/swagger-codegen/pom.xml module has conflicting source/target lang versions.

### ISSUE THREAD

**Issue by aoboturov** [swagger-api/swagger-codegen#2817]
The `swagger-codegen/modules/swagger-codegen/pom.xml` contains `maven-compiler` twice with conflicting versions `1.6` and `1.7`.

As a side question: why couldn't the 1.8 be used?

**Comment by ePaul** [comment]
For the side question: If swagger-codegen is using 1.8, then it can't be used easily in 1.6/1.7 VMs (especially important for the maven plugin). The other way around it works better.

We have a project which still doesn't build on Java 8, but we still are using Swagger-Codegen in the build process.

**Comment by aoboturov** [comment]
@ePaul Codegen could be run on Java8, but produce code for Java6. There's no problem.

Could you fix the original problem from this ticket?

**Comment by wing328** [comment]
@aoboturov do you submitting a PR so that we can review your proposed fix/change?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by aoboturov** [comment]
Wow, one month + 10 days for a reply...
