### ISSUE TITLE
external security / securityDefinitions

### ISSUE THREAD

**Issue by haroldcarr** [swagger-api/swagger-codegen#2823]
Is there a way to externally declare `security` and `securityDefinitions`.

Often I get swaggers from other places that either have NO security declarations or have one that I want to override for testing.

It would be very useful to be able to do something like

    --security-declaration <declaration-file>

where <declaration-file> would be a swagger excerpt like:

     {
        "security"            : [ { "basic"    : [] },
                                       { "apiKey" : [] }
                                     ],
        "securityDefinitions" : { "basic"    : { "type"     : "basic"},
                                             "apiKey" : { "type"     : "apiKey",
                                                               "name"    : "Mobile-Backend-ID",
                                                               "in"          : "header"
                                           }
                            }
     }

Another possibility is to make `ApiClient.authentications` modifiable so one could add/delete `Authentication` objects.

**Comment by wing328** [comment]
@haroldcarr thanks for the suggestion. Even the security definition is overridden, the RESTful backend still has the security setup in place so the API client still needs to provide the required authentication parameter (token, http basic auth, etc). Can you elaborate a bit more on your use case? (currently, the API client does not validate any authentication parameter in the client side)

**Comment by haroldcarr** [comment]
I am given Swagger descriptions that do not contain security definitions.
Out-of-band I am given two types of security:
- test instance that uses basic auth
- production instance that uses OAuth

Currently, using swagger-codegen, I have to edit the swagger by hand for both
types of security and then generate twice, once for each security.

To illustrate why two generations are required I show pieces of code below for "no security" and "security" (using basic auth in the example):

----------
generated ApiClient:

no security:

    // Setup authentications (key: authentication name, value: authentication).
    authentications = new HashMap<String, Authentication>();
    // Prevent the authentications from being modified.
    authentications = Collections.unmodifiableMap(authentications);

security:
    authentications = new HashMap<String, Authentication>();
    authentications.put("basic", new HttpBasicAuth());
    // Prevent the authentications from being modified.
    authentications = Collections.unmodifiableMap(authentications);

Given the above, there is no way to add/remove `Authentication` objects dynamically.

----------
generate *Api classes:

no security:

    String[] localVarAuthNames = new String[] {  };

security:

    String[] localVarAuthNames = new String[] { "basic" };

Given the above, there is no way to dynamically call *Api method with different security dynamically.

It would be useful to be able to optionally

1. specify security info externally from a Swagger

2. change security types in code dynamically

**Comment by wing328** [comment]
@haroldcarr thanks for sharing the details

I think it's reasonable to be able to set the security setting dynamically in the code. 

I've marked this as "Need Community Contribution" for the time being to see if anyone from the community has cycle to implement this feature.

**Comment by cbornet** [comment]
@haroldcarr I guess you are using the jersey/default generator. If you use the feign or retrofit generators, they both support dynamic security setting.

**Comment by wing328** [comment]
@haroldcarr please try the feign or retrofit2 generator.

Issue closed for now.
