### ISSUE TITLE
[Swift] enum with colons are generating non compilable swift code

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-codegen#2824]
If you have:

```json
 "properties": {
                "prop": {
                    "type": "string",
                    "enum": [
                        "foo:1",
                        "foo:2"
                    ]
                }
}
```

This is valid swagger but generates 

```swift
    public enum Prop: String { 
        case Foo:1 = "foo:1"
        case Foo:2 = "foo:2"
    }
```

which is not legal swift.

**Comment by Edubits** [comment]
Hi @cjolif, 
That's indeed not valid Swift. I see that for example in the Java codegen the following code is generated:
```java
public enum EnumPropEnum {
    _1("foo:1"),
    _2("foo:2");
    ..
}
```
Is that expected? What would be your expected output in Swift?

**Comment by cjolif** [comment]
@Edubits looks like. I will test and double check.

**Comment by cjolif** [comment]
@Edubits the problem is still here after @wing328 commit. Indeed the fix is in `escapeText` which is not called by `toEnumVarName`
