### ISSUE TITLE
C/C++ generator

### ISSUE THREAD

**Issue by arschles** [swagger-api/swagger-codegen#283]
Does anyone know if there are plans to add support in this repo? Otherwise, is there a C/C++ generator elsewhere?

**Comment by J-cztery** [comment]
Hi, the link https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/src/main/resources/tizen does not seem to work (404).

**Comment by wing328** [comment]
Moved to
https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/tizen

**Comment by webron** [comment]
@fehguy - are we going to have a specific C++ implementation or stick with the Tizen one?

**Comment by fehguy** [comment]
@webron after spending time on this, I'm guessing we'll have many different c++ generators based on the frameworks, etc.

**Comment by webron** [comment]
If anyone on this thread wants to jump in and donate a template, that would be great. 

Should be relatively easy now, for those who know C/C++ - https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules.

**Comment by MathiasWasAlreadyTaken** [comment]
I have started to implement a C++ generator for Casablanca/cpprest. It is still in its early stages, meaning there are lots of implementation and verification left.
But for the not so faint of heart who wants to test things out, it does creates something that is usable...in labs...check the [readme for this fork](https://github.com/MathiasWasAlreadyTaken/swagger-codegen/blob/development/modules/swagger-codegen/src/main/resources/cpprest/README.md).
https://github.com/MathiasWasAlreadyTaken/swagger-codegen/tree/development

**Comment by wing328** [comment]
@MathiasWasAlreadyTaken thanks for the contribution. Would you have time to submit a PR for the Casablanca/cpprest C++ generator? Let me know if you need any help.

**Comment by MathiasWasAlreadyTaken** [comment]
Hi @wing328!
As soon as I have something that have been tested and I know works I will create a pull request. Right now I know that it lack lots of functionality that should not go into the main repo.

/Mathias

**Comment by wing328** [comment]
@MathiasWasAlreadyTaken OK. Please take your time and let us know if you need any assistance.

**Comment by KrishnaPG** [comment]
+1 for cpprest generator. C/C++ strongly needs wider REST base and swagger is the best way

**Comment by stunney** [comment]
Another +1 for the cpprest sdk generator.  PLEASE!!!!

**Comment by wing328** [comment]
@MathiasWasAlreadyTaken if you've something ready for beta (a partially working C++ client), I would suggest you to submit a PR so that the community can start looking into it and file PRs for improvement.

**Comment by MathiasWasAlreadyTaken** [comment]
I would love to be able to work more on this, and the future is looking brighter. I might be able to do some work with it soon, so as soon as I have something that is runnable I'll submit a PR.

**Comment by stunney** [comment]
Do you have any more work done on it at all?  You might get some assistance from others like myself :)

**Comment by wing328** [comment]
@MathiasWasAlreadyTaken thanks for the update. Please take your time.

(My suggestion is that even though you've partially-finished c++ generator that's not runnable yet, it's still good to submit a PR to let the community helps improve it to make it runnable)

**Comment by arschles** [comment]
@schmidt4brains you asked above (a long time ago) if I have any updates or have made any progress. Just FYI that I don't and am not currently planning on working on the C++ generator anymore

**Comment by schmidt4brains** [comment]
@arschles Thanks for the update. My team has taken an alternative approach to C++ code generation (they are basically hand-coding a wrapper layer for each REST endpoint they consume). It still feels like boilerplate work to me, but they are happy with it.

**Comment by fehguy** [comment]
I'd be happy to tackle the templates, providing a good example client + build instructions were provided.

**Comment by wing328** [comment]
Here is another update related to C++ generator:

https://github.com/swagger-api/swagger-codegen/issues/2704#issuecomment-225537925

**Comment by fehguy** [comment]
We have C++ for QT + CPPRest so time to close this.

**Comment by itschrono** [comment]
Am I wrong or there is no **server** version for this two ? (qt5cpp-server, cpprest-server ?)

**Comment by wing328** [comment]
@itschrono there are C++ server generators for Pistache and Restbed. Would that meet your requirement?

**Comment by itschrono** [comment]
I guess it will for my C++ (Qt5 standalone software). Now I may need a visual basic client (I known it's lame xD) see #6831

**Comment by chrisinmtown** [comment]
Forgive me for posting to a closed issue. The page https://github.com/swagger-api/swagger-codegen says "C++ is supported" as an API client. When I try to generate a C++ client by invoking the generator version 3.0.34 with argument `-l c++` it rejects my attempt, and the list of supported languages it shows does not include `cpprest` or anything that looks like C/C++. Please guide me here.
```
% java -jar swagger-codegen-cli.jar generate -i openapi.yml -l c++ -o client
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name c++ Available: dart
aspnetcore
csharp
csharp-dotnet2
go
go-server
dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
micronaut
spring
nodejs-server
openapi
openapi-yaml
kotlin-client
kotlin-server
php
python
python-flask
r
ruby
scala
scala-akka-http-server
swift3
swift4
swift5
typescript-angular
typescript-axios
typescript-fetch
javascript

	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
	at io.swagger.codegen.v3.cli.SwaggerCodegen.main(SwaggerCodegen.java:96)
Caused by: java.lang.ClassNotFoundException: c++
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
	... 1 more
```

**Comment by MiroYld** [comment]
Can anyone re-open the ticket? 
Because we have exactly the same problem as @chrisinmtown
