### ISSUE TITLE
Question: Why use SplFileObject for PHP file downloads instead of returning bytes? Why call error_log each time? 

### ISSUE THREAD

**Issue by nicholasareed** [swagger-api/swagger-codegen#2836]
In PHP, when having a returnType mapped to `file` the SplFileObject type is used, which causes an error message from the following line: https://github.com/swagger-api/swagger-codegen/blob/50bbd9818cfb2133758ddb5697bd4b36cef62d05/modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache#L271

Why is this necessary? I don't see a similar approach being taken in other languages, so why is PHP using a temporary file location instead of returning the bytes and allowing the user to create their own SplFileObject (or just file_put_contents($bytes))? If saving to an SplFileObject is the smartest way to implement the file download, then why is an error always displayed?

**Comment by wing328** [comment]
To return bye array, please use `binary` (format) instead.
Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

About displaying the "error", we want to show it as log (info) to remind users about moving the temp file to a permanent location. If you've any suggestion to make the message less confusing, please let us know.

**Comment by nicholasareed** [comment]
Thanks @wing328. Using `binary` is an option, but it doesn't answer why PHP is the only language where swagger-codegen decides to use a temporary file instead of streaming the file bytes back for `file` formats. In our SDK implementations (and most others I would assume), it would be odd to switch a response type in our spec.json from `file` to `binary` for only the PHP SDK build. 

For the error, it again seems an odd choice to force it upon the user when they have no recourse to actually suppress the message, even if they are moving the temporary file immediately. I can see a first-time user having trouble discerning what/where the SplFileObject points, but that seems better suited to a "better documentation and examples" solution than "permanent error message."

We can easily work around the defaults in swagger-codegen by just commenting out the error message, or changing the typeMapping (`typeMapping.put("file", "string")`) in PhpClientCodegen.java, but we had enough confusion around the defaults that I thought it would be good to ask.

**Comment by wing328** [comment]
@nicholasareed I believe other languages like Ruby, Python also write to a local file if the response is defined as `file`

For the "error" message `[INFO] Written $byte_written byte to $filename...`, if we show it only if the debug flag is on, would that cause less confusion to you?

I agree the default may not suit everyone's need so please share with us what makes senses or does not make sense to you so that we can incorporate your feedback to improve the auto-generated SDKs.

**Comment by nicholasareed** [comment]
Ah, I actually didn't see it in those languages. It definitely seemed out-of-place for a single language but I assumed it couldn't be alone! 

Only showing if the debug flag is on would be a great solution. I think that strikes the right balance between informative and bothersome for first-time vs. repeat users.

**Comment by wing328** [comment]
#2867 (debug switch to show the info) has been merged into master.
