### ISSUE TITLE
Custom namespace

### ISSUE THREAD

**Issue by Serjster** [swagger-api/swagger-codegen#2837]
Hello, thank you for creating this wonderful tool.  am using it to create C# classes. For my questions:

1) Most importantly, how I tell the swagger-codegen which namespace, or perhaps base namespace to use? 2) All of my generated models start with I... as in ICustomer... is there any way to strip that first **I**? 3) If 2 can be done, is there a way to have it append a : IWhatever... so if it's trying to gen ICustomer, I'd like to see a **public class Customer : ICustomer**, can this be done?

4) For my last question, I am using this commandline
**java -jar swagger-codegen-cli.jar generate -i http://localhost:57772/MyService/swagger/v1/swagger.json -l csharp -o C:/Code/AutoGenned/MyService**
The problem is that it adds this to the path:
src\main\csharp\IO\Swagger

Is there a way for me to not have this added to the path?

5) Finally, least importantly, it gens 4 folders: **Api, Client, Model, Properties** is there a way to only gen the Client and the Model folders?

**Comment by fehguy** [comment]
Hi, there are a number of options for the C# generator.  Have you looked at the configuration options?  Try this:

```
swagger-codegen config-help -l csharp
```

Or look at the options from the online generator:

https://generator.swagger.io/#!/clients/getClientOptions

which says:

```
curl -X GET --header 'Accept: application/json' 'https://generator.swagger.io/api/gen/clients/csharp'

{
  "packageName": {
    "opt": "packageName",
    "description": "C# package name (convention: Title.Case).",
    "type": "string",
    "default": "IO.Swagger"
  },
  "packageVersion": {
    "opt": "packageVersion",
    "description": "C# package version.",
    "type": "string",
    "default": "1.0.0"
  },
  "sourceFolder": {
    "opt": "sourceFolder",
    "description": "source folder for generated code",
    "type": "string",
    "default": "src/main/csharp"
  },
  "packageGuid": {
    "opt": "packageGuid",
    "description": "The GUID that will be associated with the C# project",
    "type": "string"
  },
  "targetFramework": {
    "opt": "targetFramework",
    "description": "The target .NET framework version.",
    "type": "string",
    "enum": {
      "v3.5": ".NET Framework 3.5 compatible",
      "v4.5": ".NET Framework 4.5+ compatible"
    },
    "default": "v4.5"
  },
  "sortParamsByRequiredFlag": {
    "opt": "sortParamsByRequiredFlag",
    "description": "Sort method arguments to place required parameters before optional parameters.",
    "type": "boolean",
    "default": "true"
  },
  "useDateTimeOffset": {
    "opt": "useDateTimeOffset",
    "description": "Use DateTimeOffset to model date-time properties",
    "type": "boolean",
    "default": "false"
  },
  "useCollection": {
    "opt": "useCollection",
    "description": "Deserialize array types to Collection<T> instead of List<T>.",
    "type": "boolean",
    "default": "false"
  },
  "returnICollection": {
    "opt": "returnICollection",
    "description": "Return ICollection<T> instead of the concrete type.",
    "type": "boolean",
    "default": "false"
  },
  "optionalMethodArgument": {
    "opt": "optionalMethodArgument",
    "description": "C# Optional method argument, e.g. void square(int x=10) (.net 4.0+ only).",
    "type": "boolean",
    "default": "true"
  },
  "optionalAssemblyInfo": {
    "opt": "optionalAssemblyInfo",
    "description": "Generate AssemblyInfo.cs.",
    "type": "boolean",
    "default": "true"
  },
  "optionalProjectFile": {
    "opt": "optionalProjectFile",
    "description": "Generate {PackageName}.csproj.",
    "type": "boolean",
    "default": "false"
  },
  "optionalEmitDefaultValues": {
    "opt": "optionalEmitDefaultValues",
    "description": "Set DataMember's EmitDefaultValue, default false.",
    "type": "boolean",
    "default": "false"
  }
}
```

Finally, note there are two C# generators, `csharp` and `CsharpDotNet2`.

**Comment by jimschubert** [comment]
To answer a few more of your questions...

There's no way to modify the model names. You can append or prepend to your model names, however. Just pass `--model-name-prefix` or `--model-name-suffix`. These values are concatenated to the model names provided from your swagger definition by an underscore. For example, `--model-name-prefix=Api` will result in `Api_ICustomer`.

Related to your question about the path `src\main\csharp\IO\Swagger`, I recently reworked the client output for the next release. You can view the new folder structure here: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/csharp/SwaggerClient. If you generate against master with:

```
java -jar swagger-codegen-cli.jar \
    generate -i http://localhost:57772/MyService/swagger/v1/swagger.json \
    -l csharp -o C:/Code/AutoGenned/MyService
```

You'll end up with the following structure:

```
    .
    ├── MyService.sln
    ├── README.md
    ├── bin
    ├── build.bat
    ├── build.sh
    ├── docs
    ├── packages
    └── src
        ├── MyService
        │   ├── Api
        │   ├── Client
        │   ├── Model
        │   ├── Properties
        │   └── packages.config
        └── MyService.Test
            └── packages.config
```

Lastly, you can selectively generate code: https://github.com/swagger-api/swagger-codegen#selective-generation

**Comment by Serjster** [comment]
Thank you for your answers. BTW, I attached a Swagger.json deal that breaks the online gen.
[cl.zip](https://github.com/swagger-api/swagger-codegen/files/261737/cl.zip)

**Comment by wing328** [comment]
Thanks for sharing the spec (deleted). I did a test with the latest master and didn't get any issue.

Issue closed.
