### ISSUE TITLE
Parameters is nil after converting body in API class

### ISSUE THREAD

**Issue by winster** [swagger-api/swagger-codegen#2838]
Inside request builder method of API class, parameters becomes nil

let parameters = myBody.encodeToJSON() as? [String : AnyObject]

If I change that to [[String : AnyObject]]  I get value for parameters, but requestBuilder.init requires parametes of [String : AnyObject]

**Comment by wing328** [comment]
@jaz-ah @Edubits would you please take a look when you've time? Thank you.

**Comment by jaz-ah** [comment]
@winster could you give a ptr to your swagger doc so we can reproduce?

**Comment by wing328** [comment]
@winster please provide the spec so that we can reproduce the issue.

Issue closed for now.
