### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!

### ISSUE THREAD

**Issue by NadaBen** [swagger-api/swagger-codegen#2839]
m trying to execute this command in the command prompt, to generate code for python,

`java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i http://localhost/test/swagger-docs/api-docs.json -l python -o c:\temp\python_testapi_client`

and it shows me this error:

`   Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:89)
    at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
    at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)`

and when i open this file in my browser, it contains:
`{"swaggerVersion":"1.2","apis":[{"path":"\/v1-machinetags","description":"Deletes machine tags by they titles."},{"path":"\/v1-photos","description":"Uploads photo with tags."},{"path":"\/v1-photos-bymachinetags","description":"List of photos with possibility filtering by Machine tags."},{"path":"\/v1-photos-bytags","description":"List of photos with possibility filtering by tags."},{"path":"\/v1-photos-user-bymachinetags","description":"List of photos of a specific user with possibility filtering by machine tags."},{"path":"\/v1-photos-user-bytags","description":"List of photos of a specific user with possibility filtering by tags."},{"path":"\/v1-photos","description":"Deletes photo."},{"path":"\/v1-photos-machinetags","description":"Associate photo with machine tags."},{"path":"\/v1-photos-tags","description":"Associate photo with tags."},{"path":"\/v1-resources","description":"Add a new RDF resource ."},{"path":"\/v1-tags","description":"Deletes tags by they titles."},{"path":"\/v1-triplets","description":"Get All triplets."},{"path":"\/v1-triplets-bylanguages","description":"Get Resources by a given language."},{"path":"\/v1-triplets-bytypes","description":"Get Resources by a given type."}],"apiVersion":"0.1","info":{"title":"Symfony2","description":"My awesome Symfony2 app!","TermsOfServiceUrl":null,"contact":null,"license":null,"licenseUrl":null},"authorizations":[]}`

i used nelmio api doc with swagger to generate this file 
`nelmio_api_swagger:
    resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix: /api-docs

    

    
al_swagger_ui_static_resources:
    resource: @ALSwaggerUIBundle/Resources/config/static_resources_routing.yml
    prefix: /swagger-docs`

**Comment by wing328** [comment]
@NadaBen looks like swagger parser fails to parse the swagger spec at http://localhost/test/swagger-docs/api-docs.json.

Can you try downloading the spec to a local folder, e.g. c:\temp\spec and run your command with `-i c:\temp\spec\api-docs.json` instead?

**Comment by NadaBen** [comment]
I tried that, but same error, i think it's a specification problem, i dont know how to solve it
