### ISSUE TITLE
java/jersey2 pom template enhancements

### ISSUE THREAD

**Issue by jerrylawson** [swagger-api/swagger-codegen#2847]
- pom template should not be hardcoded to execute gradle; there should be a way of disabling this via swagger-codegen options

- pom template should allow for configuration of a parent pom entry.

**Comment by fehguy** [comment]
Just think of the pom as a starting point.  It's expected that you're going to make changes, like adding dependencies, etc.  I don't think it makes sense to make every aspect of it configurable, that should be part of your workflow.
