### ISSUE TITLE
java/jersey2 should expose builder or setter for ApiClient.httpClient

### ISSUE THREAD

**Issue by jerrylawson** [swagger-api/swagger-codegen#2849]
The httpClient value in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L58 is private without a setter method. This does not allow for an application to provide its own Client instance to be used.

It would be good to have ApiClient either provide a protected or public setHttpClient(Client) method, or provide a protected getHttpClient() and use that within ApiClient, rather than accessing httpClient directly.

**Comment by wing328** [comment]
@jerrylawson thanks for the suggestion. May I know if you've cycle to contribute the enhancement?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by jerrylawson** [comment]
Yes, I can contribute this change

**Comment by wing328** [comment]
@jerrylawson  PR merged. Please pull the latest to give it a try.
