### ISSUE TITLE
[2.0 Spec] "Operation" object: implement parameter references

### ISSUE THREAD

**Issue by martoe** [swagger-api/swagger-codegen#285]
The 2.0 spec allows to define reusable [parameterDefinitions](https://github.com/wordnik/swagger-spec/blob/master/versions/2.0.md#parametersDefinitionsObject) that can be referenced in [operations](https://github.com/wordnik/swagger-spec/blob/master/versions/2.0.md#operationObject).
This feature is not implemented yet.

(cloned from https://github.com/wordnik/swagger-core/issues/698)

**Comment by wing328** [comment]
Both swagger-api/swagger-core#705 and swagger-api/swagger-core#698 are closed.
