### ISSUE TITLE
[python] Extra slash inserted between endpoint and basePath

### ISSUE THREAD

**Issue by Amadiro** [swagger-api/swagger-codegen#2850]
When specifying the basePath as "/", and some given path as e.g. "/my_api_call", the generated python code will make a request to "//my_api_call".

When specifying the path as "my_api_call" the request generated goes to "/my_api_call" as intended, but the Swagger document does not validate.

I did not verify whether this is an issue with other generators.

**Comment by wing328** [comment]
@scottrw93 would you please take a look when you've time?

**Comment by scottrw93** [comment]
The petstore example [spec](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/swagger_client/configuration.py#L59) file does not seem to produce this problem. Could you provide an example of one that does? Also could you confirm what version of Swagger Codegen you are using as there has been some changes made around this code that might have resolved it.

**Comment by Amadiro** [comment]
@scottrw93 the petstore example does not have a basePath of "/", which seems to be the thing triggering the issue. 

As for the version, I'm using swagger-codegen-cli-2.1.6.jar from http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar.

**Comment by scottrw93** [comment]
Sorry, I misunderstood. In this case you should just not specify the base path as it is not a required field and you can exclude it from your spec to get the intended results. I don't feel it is a bug, it is the equivalent of ending the base path if there is one with a slash which will also produce a double slash in the url.

**Comment by Amadiro** [comment]
Ah, thanks for the clarification. I tried previously to leave the basePath empty, but that was not permitted. I was not aware I could just omit it. Closing.

**Comment by wing328** [comment]
Here is the official definition of `basePath` from the spec:
```
The base path on which the API is served, which is relative to the host. If it is not included, the API is served directly under the host. The value MUST start with a leading slash (/). The basePath does not support path templating.
```
Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields
