### ISSUE TITLE
Can't find io.swagger.client.model.QueryResult

### ISSUE THREAD

**Issue by billharrelson** [swagger-api/swagger-codegen#2851]
I used Swagger-codegen to generate a java interface to a providers API, but the PrefetchMapper.java class references io.swagger.client.model.QueryResult which I can't find.  I managed to find all of the other jars that it referenced (jackson, etc.) on the Maven repository, but that class isn't in the Model classes (there's a Query, but no QueryResult), and I can't find references to it anywhere.  Can someone help me resolve this?  Thanks.(ps, Windows 7)

**Comment by fehguy** [comment]
Please share your definition

**Comment by billharrelson** [comment]
https://balihoo.looker.com:19999/api/3.0/swagger.json

**Comment by fehguy** [comment]
Hi, I see a number of issues in your definition. If you can send me a note directly, I'll work on this offline with you.

**Comment by wing328** [comment]
@billharrelson I assume this has been addressed. If not, please reply to let us know.

Closing the issue for now.
