### ISSUE TITLE
[python] swagger generator seems to be unable to resolve references from local files

### ISSUE THREAD

**Issue by Amadiro** [swagger-api/swagger-codegen#2853]
I have a spec that uses pathes from an external file like so:

`
"paths": {
       "$ref": "./paths/videos__query_exact.json"
   }
`

the file in paths/videos__query_exact.json looks like so:

`
{
  "/videos__query_exact": { ... }
}
`

However, when doing this, no VideoApi object is generated. When first running

`json-refs resolve`

on the file and using the output of that command, the VideoApi object is generated, and everything works as expected.

This looks like it might be an issue with the reference resolving code in the generator? When running e.g. BigstickCarpets swagger-validator over the file, it works either way (with external references or with the references inlined through json-refs).

I have not verified whether this issue also exists with other language generators.

**Comment by wing328** [comment]
@Amadiro can you please share the full spec so that we can repeat the issue?

**Comment by Amadiro** [comment]
Hello,
I've tried creating a minimal test-case, but it seems to not reproduce, and since I've messed around with our spec so much by now, I can't get it to reproduce locally anymore either. Maybe it was just a mistake on my part -- I'll make sure to re-open if I manage to reproduce after all. Closing for now.

**Comment by wing328** [comment]
Np. Just ping us if you need help.
