### ISSUE TITLE
[csharp] (Discussion) Refactor and document ApiClient/Configuration

### ISSUE THREAD

**Issue by jimschubert** [swagger-api/swagger-codegen#2858]
This is in response to conversation in #2723.

I'd like to discuss the following:
1. Differentiate between "global configuration" and "instance/per-request configuration".
2. Better documentation related to constructing the *Api classes with `Configuration` instances.
3. Clean up the constructors for ApiClient to call through to the other constructors.
4. Maybe deprecate `Configuration.Default` or mark it obsolete and introduce `Configuration.Global`?
5. Maybe remove the circular reference between `Configuration` and `ApiClient`? It makes sense that ApiClient _has a_ Configuration, but it isn't immediately clear why Configuration _has an_ ApiClient.
## References

> 3. Clean up the constructors for ApiClient to call through to the other constructors

```
public ApiClient()
{
    Configuration = Configuration.Default;
    RestClient = new RestClient("http://petstore.swagger.io/v2");
}

public ApiClient(Configuration config = null)
{
    if (config == null)
        Configuration = Configuration.Default;
    else
        Configuration = config;

    RestClient = new RestClient("http://petstore.swagger.io/v2");
}

public ApiClient(String basePath = "http://petstore.swagger.io/v2")
{
    if (String.IsNullOrEmpty(basePath))
        throw new ArgumentException("basePath cannot be empty");

    RestClient = new RestClient(basePath);
    Configuration = Configuration.Default;
}
```

> 4. Maybe deprecate `Configuration.Default` or rename to `Configuration.Global`?

```
public static Configuration Default = new Configuration();
```

> 5. Maybe remove the circular reference between Configuration and ApiClient? 

```
// In Configuration.cs
public ApiClient ApiClient;

public void setApiClientUsingDefault (ApiClient apiClient = null)
{
    if (apiClient == null)
    {
        if (Default != null && Default.ApiClient == null)
            Default.ApiClient = new ApiClient();

        ApiClient = Default != null ? Default.ApiClient : new ApiClient();
    }
    else
    {
        if (Default != null && Default.ApiClient == null)
            Default.ApiClient = apiClient;

        ApiClient = apiClient;
    }
}

// In ApiClient
public Object CallApi(
    String path, RestSharp.Method method, Dictionary<String, String> queryParams, Object postBody,
    Dictionary<String, String> headerParams, Dictionary<String, String> formParams,
    Dictionary<String, FileParameter> fileParams, Dictionary<String, String> pathParams,
    String contentType)
{
    var request = PrepareRequest(
        path, method, queryParams, postBody, headerParams, formParams, fileParams,
        pathParams, contentType);

    // set timeout
    RestClient.Timeout = Configuration.Timeout;
    // set user agent
    RestClient.UserAgent = Configuration.UserAgent;

    var response = RestClient.Execute(request);
    return (Object) response;
}

// In Api types:
public PetApi(String basePath)
{
    this.Configuration = new Configuration(new ApiClient(basePath));

    // ensure API client has configuration ready
    if (Configuration.ApiClient.Configuration == null)
    {
        this.Configuration.ApiClient.Configuration = this.Configuration;
    }
}
```

**Comment by fehguy** [comment]
We might want to separate the schemes in the templates, per the spec rather than jam them into a single `scheme`+`host`+`basePath`

**Comment by jimschubert** [comment]
@fehguy Can you provide an example of your comment?

A [System.Uri](https://msdn.microsoft.com/en-us/library/system.uri(v=vs.110).aspx) instance is already exposed from `Configuration.ApiClient.RestClient.BaseUrl` which refers to the `basePath` string in a strongly typed manner.

Are you suggesting `Configuration#BasePath` should be a `Uri` instead of a string? I could get down with that, but I didn't want to introduce too many breaking changes for this refactoring.

Here's an example of what that Uri offers:

```
csharp> Uri uri = new Uri("https://api.mysite.com/v1");
csharp> uri.AbsoluteUri
"https://api.mysite.com/v1"
csharp> uri.PathAndQuery
"/v1"
csharp> uri.Host
"api.mysite.com"
csharp> uri.Scheme
"https"
```

I think at some point, the RestClient exposed from ApiClient (`Configuration.ApiClient.RestClient.BaseUrl`) should be better hidden from users. I'd consider `RestClient` an implementation detail, and exposing it means we can't easily switch from using RestSharp to something else without breaking changes.

**Comment by fehguy** [comment]
@jimschubert looks like exposing the `uri` does it all.  Previous versions of this library (and current versions of other languages) exposes a `basePath` variable in the client, which is really the scheme + host + basePath.  It looks like if you allow setting the `uri` here, then you have it covered already.

**Comment by jimschubert** [comment]
Thanks! I just wanted to clarify I wasn't missing a functionality request.

**Comment by jimschubert** [comment]
#5740 should address the refactor part of this issue. It could still use some additional documentation about how to pass the configurations.
