### ISSUE TITLE
vertx code swagger auto generation 

### ISSUE THREAD

**Issue by yogiGueta** [swagger-api/swagger-codegen#2881]
Hi,
Does swagger  soppurt vertx (auto generation of code)?

**Comment by wing328** [comment]
@yogiGueta I believe you're referring to http://vertx.io/, which is not supported in Java, JavaScript, Groovy, Ruby at the moment.

We would welcome contribution to support it as an option.

**Comment by phiz71** [comment]
Hello,
I've created a swagger-codegen library for Vert.X : https://github.com/phiz71/swagger-vertx-codegen 
The generated project needs https://github.com/phiz71/vertx-web-swagger to compile.

Hope it will help you.

**Comment by fehguy** [comment]
Nice @phiz71 thanks for sharing.  Perhaps you'd like to submit a PR to add the templates to the main project?

**Comment by phiz71** [comment]
It would be nice, but the maven project that my swagger codegen library generates has a dependancy on a custom library I made. I think I should first publish this custom library on a maven repo before submit a PR.

**Comment by wing328** [comment]
@phiz71 thanks! Let us know if you need help submitting a PR for Vert.X

**Comment by thomsonimjd** [comment]
@phiz71 , could you please give more acurate **simple** example on **swagger with vertx  rest api.**

**Comment by Neal910** [comment]
Hi @thomsonimjd , Have you got any luck on your project of swagger with vert.x RestAPI?

**Comment by thomsonimjd** [comment]
@Neal910 ; I have not yet, if you know please revert me .

**Comment by Neal910** [comment]
@thomsonimjd , http://jooby.org/ seems to be an option. But I haven't looked into it.

**Comment by wing328** [comment]
@phiz71 May I know if you need help submitting a PR to add vert.x templates to Swagger Codegen?

cc @slinkydeveloper

**Comment by phiz71** [comment]
Oops.. I must admit I had forgotten I had to work on this PR :$
I will try  these dans :-)!

**Comment by wing328** [comment]
@phiz71 no problem. Let us (the community) know if there's anything we can help.

I would suggest you to pull the latest master before you start working on the PR as there are many enhancements to the project on a regular basis.

**Comment by phiz71** [comment]
PR done : https://github.com/swagger-api/swagger-codegen/pull/6014

**Comment by wing328** [comment]
@phiz71 thanks for the PR, which has been merged into master.

@yogiGueta @Neal910 @thomsonimjd please pull the latest master or use the 2.2.3-SNAPSHOT version to give it a try.

**Comment by lopesmcc** [comment]
Vert.x client generation would also be very useful. The solution is awesome (thanks @phiz71 🥇 ) but focuses on generating Server stubs.

@wing328 I'm working on a client generator, and should have something ready very soon. 
Should we create a new issue for it or re-open this one?

**Comment by wing328** [comment]
@lopesmcc please open a new ticket (issue) for tracking instead. If you need help with the PR, please let us know.
