### ISSUE TITLE
Overriding of sourceFolder in JavaCXFServerCodegen doesn't work 

### ISSUE THREAD

**Issue by AlexFaster** [swagger-api/swagger-codegen#2894]
When I try to override sourceFolder property in config file, then it doesn't work. It just leaves value assigned in line 65 in JavaCXFServerCodegen.java
My config file 
`
{
    "modelPackage": "com.luxoft.ob10.papi.services.user.domain",
    "apiPackage": "com.luxoft.ob10.papi.services.user",
    "sourceFolder": "src/main/java"
}
`
I tried invokerPackage option, but it didn't work too.

**Comment by wing328** [comment]
@AlexFaster I would suggest you to pull the latest master and give it another try.

**Comment by wing328** [comment]
@AlexFaster please try the latest master or wait for the 2.2.0 stable release, which will be out soon.
