### ISSUE TITLE
C#: Option to disable dynamic type in ApiException.ErrorContent

### ISSUE THREAD

**Issue by kbrooks** [swagger-api/swagger-codegen#2896]
The ApiException class encapsulates the ErrorContent of a REST API request as a dynamic type

        /// <summary>
        /// Gets or sets the error content (body json object)
        /// </summary>
        /// <value>The error content (Http response body).</value>
        public dynamic ErrorContent { get; private set; }

Unfortunately, one of the products I have to integrate with does not support dynamic types, and the engineers in charge of it are vehemently opposed to adding support.

It would be nice if the `dynamic` type here could optionally be replaced with a `string`.

**Comment by jimschubert** [comment]
If you pass `-DtargetFramework=v3.5` to generate .NET 3.5 client, you shouldn't get the dynamic type. Setting the option disables the `supportsAsync` variable passed to the templates. see https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L391

**Comment by wing328** [comment]
@kbrooks https://github.com/swagger-api/swagger-codegen#getting-started is a good starting point to explore different options (general or language-specified)

**Comment by jimschubert** [comment]
I was going through C# issues to see if there was any new information. Saw the link I provided earlier was to the wrong file. Actual file is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/ApiException.mustache#L21.

Relevant code:
```csharp
/// <summary>
/// Gets or sets the error content (body json object)
/// </summary>
/// <value>The error content (Http response body).</value>
public {{#supportsAsync}}dynamic{{/supportsAsync}}{{^supportsAsync}}object{{/supportsAsync}} ErrorContent { get; private set; }
```

Where `supportsAsync` is set depending on the target framework.

@kbrooks please verify, or provide any additional information about the problem you're seeing with `object` as a workaround.

**Comment by wing328** [comment]
Closing this as there's no update.
