### ISSUE TITLE
Java and Android codegen-ed API sources don't list the nested model classes in the imports

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-codegen#290]
The Java and Android API Codegen only imports the outermost model classes. Other model classes that are nested within these classes are not imported.

Quick fix - Do a * style import in . Depend on IDE to optimize the imports.

**Comment by xhh** [comment]
This has been fixed as there is a wildcard import (*) now (I checked the develop_2.0 branch).
For example in PetApi.java from the Petstore Java sample:
```java
package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiInvoker;

import io.swagger.client.model.*;

import java.util.*;

import io.swagger.client.model.Pet;
import java.io.File;
```

There is redundant import though, i.e. the "io.swagger.client.model.Pet" import is no longer needed.

**Comment by fehguy** [comment]
yes, we may have redundant imports.  I'll close this and we can reopen as needed.
