### ISSUE TITLE
JavaScript: Breaks multi byte encoding

### ISSUE THREAD

**Issue by arikon** [swagger-api/swagger-codegen#2900]
Here is an example of md file from json containing cyrillic symbols in utf-8:

-----

# SandboxJsonApi.Group

## Properties
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**url** | **String** | URL \u043F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u044F \u0434\u0435\u0442\u0430\u043B\u044C\u043D\u043E\u0439 \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u0438 \u043E \u0433\u0440\u0443\u043F\u043F\u0435 |
**name** | **String** | \u0418\u043C\u044F \u0433\u0440\u0443\u043F\u043F\u044B |
**rights** | **String** | \u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u043E \u0432\u043E\u0437\u043C\u043E\u0436\u043D\u044B\u0435 \u043F\u0440\u0430\u0432\u0430 \u043D\u0430 \u0434\u0430\u043D\u043D\u044B\u0439 \u0440\u0435\u0441\u0443\u0440\u0441 \u0443 \u0442\u0435\u043A\u0443\u0449\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F |
**members** | **[String]** | \u0421\u043F\u0438\u0441\u043E\u043A \u0438\u043C\u0435\u043D \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u0439 \u0433\u0440\u0443\u043F\u043F\u044B |
**email** | **String** | Email-\u0430\u0434\u0440\u0435\u0441 \u0433\u0440\u0443\u043F\u043F\u044B. |
**priorityLimits** | [**GroupPriorityLimits**](GroupPriorityLimits.md) | \u041C\u0430\u043A\u0441\u0438\u043C\u0430\u043B\u044C\u043D\u043E \u0434\u043E\u043F\u0443\u0441\u0442\u0438\u043C\u044B\u0435 \u043F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442\u044B \u0437\u0430\u0434\u0430\u0447\u0438, \u0441\u043E\u0437\u0434\u0430\u0432\u0430\u0435\u043C\u043E\u0439 \u0432 \u044D\u0442\u043E\u0439 \u0433\u0440\u0443\u043F\u043F\u0435 |
**sync** | [**GroupSyncSource**](GroupSyncSource.md) | \u0412\u043D\u0435\u0448\u043D\u0438\u0439 \u0438\u0441\u0442\u043E\u0447\u043D\u0438\u043A \u0434\u043B\u044F \u0441\u0438\u043D\u0445\u0440\u043E\u043D\u0438\u0437\u0430\u0446\u0438\u0438 \u0441\u043E\u0441\u0442\u0430\u0432\u0430 \u0433\u0440\u0443\u043F\u043F\u044B | [optional]

**Comment by arikon** [comment]
@xhh Have a look, please

**Comment by wing328** [comment]
@arikon can you please share the spec?

**Comment by arikon** [comment]
@wing328 https://gist.github.com/arikon/2f078fcf15aae07984c7e1d35def90bf

**Comment by wing328** [comment]
@arikon thanks for providing the spec. I did a test to confirm the issue has been addressed in the latest master:

https://github.com/wing328/js-multibyte-test/blob/master/docs/TaskApi.md#taskCustomFooter
https://github.com/wing328/js-multibyte-test/blob/master/docs/TaskAuditItem.md

Can you please pull the latest master and give it a try?

**Comment by jimschubert** [comment]
@arikon if you test against master and still have the same output, please share the command and parameters you're using to generate.

**Comment by arikon** [comment]
@wing328 @jimschubert I could not build from master with failing test:

```
Tests run: 477, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.347 sec <<< FAILURE! - in TestSuite
generatesCorrectDirectoryStructure(io.swagger.codegen.typescript.typescriptangular2.TypescriptAngular2AdditionalPropertiesIntegrationTest)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.AssertionError: Directory content of '/Users/arikon/projects/sandbox/yasandbox-generated/swagger-codegen/modules/swagger-codegen/target/test-classes/integrationtests/typescript/additional-properties-expected' and '/Users/arikon/projects/sandbox/yasandbox-generated/swagger-codegen/modules/swagger-codegen/target/test-classes/integrationtests/typescript/additional-properties-result' differ.: lists don't have the same size expected [8] but found [7]
	at io.swagger.codegen.testutils.AssertFile$1.preVisitDirectory(AssertFile.java:59)
	at io.swagger.codegen.testutils.AssertFile$1.preVisitDirectory(AssertFile.java:48)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:192)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2600)
	at java.nio.file.Files.walkFileTree(Files.java:2633)
	at io.swagger.codegen.testutils.AssertFile.assertPathEqualsRecursively(AssertFile.java:48)
	at io.swagger.codegen.AbstractIntegrationTest.generatesCorrectDirectoryStructure(AbstractIntegrationTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Failed tests:
  TypescriptAngular2AdditionalPropertiesIntegrationTest>AbstractIntegrationTest.generatesCorrectDirectoryStructure:43 Directory content of '/Users/arikon/projects/sandbox/yasandbox-generated/swagger-codegen/modules/swagger-codegen/target/test-classes/integrationtests/typescript/additional-properties-expected' and '/Users/arikon/projects/sandbox/yasandbox-generated/swagger-codegen/modules/swagger-codegen/target/test-classes/integrationtests/typescript/additional-properties-result' differ.: lists don't have the same size expected [8] but found [7]

Tests run: 477, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by wing328** [comment]
@arikon please pull again. I just fixed it. Sorry for the inconvenience.

**Comment by arikon** [comment]
@wing328 It worked, thanks!
