### ISSUE TITLE
[Objc] Invalid Objc code generation for collection parameter

### ISSUE THREAD

**Issue by iomark** [swagger-api/swagger-codegen#2907]
##### Description

Objc code generator produces invalid source code that can not be compiled. Problem generated code:
`if (teamIds != nil) {
queryParams[@"team_ids"] = [[SWGQueryParamCollection alloc] initWithValuesAndFormat: team_ids format: @"csv"]; }`

##### Suggest a Fix

Second **team_ids** (after initWithValuesAndFormat) should be **teamIds**

Fix will be provided by pull request

##### Swagger-codegen version

Swagger-codegen version 2.0

##### Swagger declaration file content or url

can be find on [https://dl.dropboxusercontent.com/u/41121857/telemetrio.json](url)

##### Command line used for generation

swagger-codegen generate -i telemetrio.json -l objc

##### Steps to reproduce

1. Generate Objc source code from _telemetrio.json_ using command line _swagger-codegen generate -i telemetrio.json -l objc_
2. Add result source code to your ios project using Xcode IDE
3. Try to compile project
4. Expected result: built application. Actual result: error message "error: use of undeclared identifier 'team_ids'; did you mean 'teamIds'?"

**Comment by wing328** [comment]
PR merged. Closing the issue.
