### ISSUE TITLE
[TypeScript] Issue with Enum naming 

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2909]
```
-        if (res.body.status != api.Pet.StatusEnum.pending) {
+        if (res.body.status != api.Pet.StatusEnum.StatusEnum_pending) {
```
we need to remove the enum name with underscore so that only value is used.

Ref: https://basarat.gitbooks.io/typescript/content/docs/enums.html

**Comment by christoph-lucas** [comment]
We tried to understand why underscores are not allowed in enum values in typescript. We couldn't find any reference for that. Also, in the provided link to the gitbook we couldn't find any mentioning of that. Could you please give some reference? Thanks in advance!

**Comment by wing328** [comment]
@christoph-lucas this is not to say enum "name" (not value) with underscore is not allowed. We simply want to conform to certain naming convention. If it's causing an issue to your use case, please open a new issue with an example and link to this issue for reference.

**Comment by christoph-lucas** [comment]
@wing328 Thank you very much for your quick response. We do not have an issue with the enum names but with the enum values. We (probably not entirely correctly) use the enum value and the string representation interchangeably and we rely on having the same enum values as on the server. Therefore, any change in the enum value breaks our code. Yet, this might be a very specific problem. We modified our fork of the codegen to leave enum values unchanged, which seems to work. We were just wondering whether there are any technical restrictions on the enum values.

**Comment by wing328** [comment]
@christoph-lucas which version of Swagger Codegen are you using?

**Comment by christoph-lucas** [comment]
@wing328 We forked v2.2.2, and we noticed the change upgrading from 2.2.0-SNAPSHOT.

**Comment by wing328** [comment]
@christoph-lucas please open a new issue with the details (e.g. spec to reproduce) if you've not done so.

**Comment by wing328** [comment]
Please try the latest master and open a new issue for tracking if there's an issue.

SNAPSHOT version of the latest master can be found in the README.
