### ISSUE TITLE
C#: Constructor is malformed if first property is readOnly: true

### ISSUE THREAD

**Issue by dmilov** [swagger-api/swagger-codegen#2911]
##### Description

C# class constructor is not generated properly when first property is readonly. 

Here is the produced code:

public Foo(, string Baz = null)
        {
            this.Baz = Baz;
        }

##### Swagger-codegen version

Swagger-codegen built with latest code from master.

##### Swagger declaration file content or url

https://gist.github.com/dmilov/770cd90452d310fe870156e5ee3ba087

##### Command line used for generation

 java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /tmp/foo.yaml -l csharp -o /var/tmp/foo_csharp

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/2795

**Comment by wing328** [comment]
@dmilov as a workaround, please move the readonly property to the end of the property list for the time being.

I should be able to come up with better solution this coming weekend.

**Comment by wing328** [comment]
@dmilov I've filed #2932 to fix the issue and have used the spec you provided to confirm the issue has been addressed.

**Comment by wing328** [comment]
@dmilov PR merged into master. Please pull the latest to give it a try.

**Comment by dmilov** [comment]
Just verified. It is fixed.

**Comment by wing328** [comment]
@dmilov thanks for the confirmation
