### ISSUE TITLE
[2.0 spec] implement SchemaObject.default

### ISSUE THREAD

**Issue by martoe** [swagger-api/swagger-codegen#292]
In the generated (Java) code, all model values are initialized with `null`(or an empty collection) - see `DefaultCodegen.toDefaultValue()`.
I think it would be a better choice to initialize these fields with the `default` value from the specification (https://github.com/wordnik/swagger-spec/blob/master/versions/2.0.md#schemaObject)

**Comment by clintfoster** [comment]
I notice this seems to be working now, at least for strings, e.g.:
```
      days:
        type: string
        default: "365"
```
Generates:
```
    private String days = "365";
```

However, integers are initialized with null:
```
      days:
        type: integer
        default: 365
```
Generates:
```
   private Integer days = null;
```
I'm using version 2.1.6 of the swagger-codegen-maven-plugin. I noticed the same behavior when generating client code directly from http://editor.swagger.io/

**Comment by wing328** [comment]
@clintfoster thanks for reporting the issue. I believe that's for Java and we'll look into that.

editor.swagger.io is using the latest stable version v.2.1.6

**Comment by wing328** [comment]
We've better default value support for Java API client. Please pull the latest master to give it a try.

Closing the issue for now.
