### ISSUE TITLE
[swagger-codegen-maven-plugin] custom module/generator/language not possible?

### ISSUE THREAD

**Issue by sreich** [swagger-api/swagger-codegen#2923]
trying to create a custom generator, the examples only show how to do it from the cli (generate the library, pass it to the swagger-cli). which is great, except i'm using the maven plugin.

i tried creating a jar and adding it as a dependency to that plugin, but it doesn't seem to recognize the language as valid. if what i am doing is actually possible, please also provide a simple example (like put it in the readme for maven plugin)

essentially:

            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>${swagger-codegen-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/yaml/testyamlfilename.yaml</inputSpec>
                            <language>custom-java</language>

                            <output>${project.build.directory}/generated-sources</output>
                            <apiPackage>${default.package}.handler</apiPackage>
                            <modelPackage>${default.package}.model</modelPackage>
                            <invokerPackage>${default.package}.handler</invokerPackage>
                        </configuration>
                    </execution>
                </executions>

                <dependencies>
                    <dependency>
                        <groupId>com.my.templates</groupId>
                        <artifactId>swagger-templates</artifactId>
                        <version>0.1-SNAPSHOT</version>
                    </dependency>
                </dependencies>

            </plugin>

##### Swagger-codegen version

swagger-codegen-maven-plugin 2.1.6

**Comment by sreich** [comment]
it seems this is possible by specifying <language>com.my.custom.MyGenerator</language>. really wish that would be in the readme, didn't know it was possible.

**Comment by wing328** [comment]
@sreich do you minding updating the README on that? I agree that the documentation can be further improved and your help will definitely make it better.
