### ISSUE TITLE
[Python]  Allow special characters in a url

### ISSUE THREAD

**Issue by pambeard** [swagger-api/swagger-codegen#2926]
##### Description

I need to use + in the resource path for example /thing/group+user, in api_client.py (line 120) there seems to be no way to specify quote(str(self.to_path_value(v)),safe='/,+') with the safe chars as it is here.  + is allowable in the url per RFC 3986  

##### Swagger-codegen version

Codegen version 2.1.2
Python Version: 3.5.1 
SDK Package Version: 1.0.0

##### Suggest a Fix

supply a setting to allow additional special chars over the default '/'
quote(str(self.to_path_value(v)),safe='/,+')

**Comment by wing328** [comment]
@pambeard please try the latest master to see if the issue still persists.

Here is a good starting point: https://github.com/swagger-api/swagger-codegen/#getting-started

**Comment by wing328** [comment]
@pambeard closing this as there's no update.

If you still encounter issue with the latest master, let us know.

**Comment by pambeard** [comment]
I still encounter this problem, in order to use the python code the I have to edit
api_client.py - line 120 as follows:

                replacement = quote(str(self.to_path_value(v)),safe='/,+')


Swagger Codegen Version    | Release Date | OpenAPI Spec compatibility | Notes
-------------------------- | ------------ | -------------------------- | -----
2.2.0-SNAPSHOT             |              | 1.0, 1.1, 1.2, 2.0   | [master](https://github.com/swagger-api/swagger-codegen)
2.1.6 (**current stable**) | 2016-04-06   | 1.0, 1.1, 1.2, 2.0   | [tag v2.1.6](https://github.com/swagger-api/swagger-codegen/tree/v2.1.6)
2.0.17                     | 2014-08-22   | 1.1, 1.2             | [tag v2.0.17](https://github.com/swagger-api/swagger-codegen/tree/v2.0.17)
1.0.4                      | 2012-04-12   | 1.0, 1.1             | [tag v1.0.4](https://github.com/swagger-api/swagger-codegen/tree/swagger-codegen_2.9.1-1.1)

**Comment by wing328** [comment]
@pambeard can you please share the spec here or via https://gist.github.com?

**Comment by pambeard** [comment]
I want to make sure I post what you are looking for.  Do you want me to post the modified api_client.py or the my swagger definition file.  If the swagger definition file, I don’t see anywhere in the documentation to specify that the url path will be using ‘+’ .  Please let me know if I am missing something.

**Comment by wing328** [comment]
@pambeard we need the swagger spec to reproduce the issue.

**Comment by pambeard** [comment]
Here it is
https://gist.github.com/pambeard/090a9bfa76d29b72a9ecf335980e718e
