### ISSUE TITLE
[2.0 spec] implement Response objects

### ISSUE THREAD

**Issue by martoe** [swagger-api/swagger-codegen#293]
There are a few things missing on the [Responses Object](https://github.com/wordnik/swagger-spec/blob/master/versions/2.0.md#responsesObject) implementation (CodegenResponse.java):
- `description` property
- `headers` property
- `examples` property
- the `CodegenOperation.responses` list should contain _all_ response objects (currently it excludes the 200/default response)

**Comment by wing328** [comment]
@martoe please pull the latest master to give it another try.
