### ISSUE TITLE
Swift: Add formatter "yyyy-MM-dd'T'HH:mm:ss.SSS"

### ISSUE THREAD

**Issue by mbarclay** [swagger-api/swagger-codegen#2935]
##### Description

When consuming responses from api.tfl.gov.uk, decoding fails for the date-time format "yyyy-MM-dd'T'HH:mm:ss.SSS"

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

https://github.com/mbarclay/tfl-unified-api-swagger/blob/master/tfl-unified-api.swagger.yaml

Specifically, TfL often use date-time formats to fractional seconds without the timezone. Definitions > AdditionalProperties > modified is one example. Example feed https://api.tfl.gov.uk/BikePoint?app_id=&app_key=

##### Command line used for generation

swagger-codegen generate -i https://github.com/mbarclay/tfl-unified-api-swagger/blob/master/tfl-unified-api.swagger.yaml -l swift

##### Steps to reproduce

Import the codegen to Xcode and call the /BikePoint API. It will fail when parsing the first 'modified' property on the AdditionalProperties object. 

##### Related issues

Not that I am aware of, but apologies in advance if this has been raised before. I am not entirely certain the format is RFC3339 compliant.

##### Suggest a Fix

Add the formatter "yyyy-MM-dd'T'HH:mm:ss.SSS" after line 110 of modules > swagger-codegen > src > main > resources > swift > Models.mustache. For example...

`static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'",
                "yyyy-MM-dd'T'HH:mm:ss.SSS"`

**Comment by wing328** [comment]
@mbarclay thanks for reporting the issue. Do you mind submit a PR with the fix (and ideally a test case in https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/swift-promisekit/SwaggerClientTests)?

**Comment by wing328** [comment]
@mbarclay also you may want to try the latest master which has all the dependencies of the Swift API client updated to the latest version (which might fortunately fix the issue you experienced)

**Comment by mbarclay** [comment]
Sure thing. Will check latest build and submit PR as soon as I can get to it.

**Comment by mbarclay** [comment]
Hi @wing328 I have a PR ready to go for fixing the date issue. Still navigating the code base – I have questions around creating tests. Namely once I have say altered a Moustache template in my branch, is there a recommended workflow for regenerating the petstore sample SwaggerClient and should those changes (assumabliy along with the tests) be merged back in?

Is Travis also running the Xcode tests?

Nevertheless, I can submit the PR. Passes in Travis.

**Comment by wing328** [comment]
@mbarclay please run `mvn && ./bin/swift-petstore-promisekit.sh` to update the sample and then run the following to trigger the integration test
```
cd samples/client/petstore/swift/promisekit/SwaggerClientTests
mvn integration-test
```

(Travis does not run the integration tests for Swift/Objc Petstore client)

**Comment by mbarclay** [comment]
Cheers. Will do.

**Comment by mbarclay** [comment]
I have also run `mvn && /bin/swift-petstore.sh` I notice that this scripts file permission is **not** set to executable, could just be my system – but wondered if there's a reason for this.

**Comment by wing328** [comment]
If you don't mind, please set it to executable and commit the change.

**Comment by mbarclay** [comment]
np

**Comment by wing328** [comment]
PR merged. 

Thanks for the contribution from @mbarclay
