### ISSUE TITLE
[typescript-angular2] APIKey setting unavailable

### ISSUE THREAD

**Issue by inska** [swagger-api/swagger-codegen#2938]
##### Description

Thank you @Vrolijkx, and generated code have no error, and build successfully. However, there are some missing Swagger spec on the client. We need to setup API Key for communicating with API Server. In other client such as Swift or Python, I am updating api_key in singleton configuration class to set API Key.. but that seems missing in typescript-angular2 client. 

Please consider above case and put them in.
##### Swagger-codegen version

swagger-api version is 2.1.6, and master branch with codegen
##### Swagger declaration file content or url

petstore

**Comment by tanaka-takayoshi** [comment]
I'm afraid the same issue is existing in typescript-node. Should I create a new issue for typescript-node or don't need to do so?

**Comment by wing328** [comment]
@tanaka-takayoshi I prefer creating a separate issue for tracking.

May I know if you've cycle to contribute the fix?

**Comment by timadamson** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3781

**Comment by timadamson** [comment]
I've create a pull request: https://github.com/swagger-api/swagger-codegen/pull/3781

**Comment by wing328** [comment]
Thanks for the PR from @timadamson 

@inska please pull the latest master to give it a try.
