### ISSUE TITLE
[PHP] Providing apikey via constructor instead of via method call

### ISSUE THREAD

**Issue by mikolajprzybysz** [swagger-api/swagger-codegen#2941]
##### Description

Apikey is required as a parameter of method you are calling which causes the caller to know the api key. However usually apiClient will be passed as dependency to the object using it. Currently I am solving this issue by creating my own apiClient which uses the default one, which adds unnecessary overhead. To be more specific my class `MyObjectStorage` is not responsible for knowing the storage apikey, it is the responsibility of the apiClient.

The following would be the usage I would expect:
```
class MyObjectStorage {
    function __construct($apiClient) {
        $this->apiClient = $apiClient;
    }
    function save($myObject) {
        $this->apiClient->savePost($myObject);
    }
}
```
##### Swagger-codegen version

master branch

##### Suggest a Fix

I would propose to move apiKey to defaultApi constructor and remove it from the method call.

Let me know what do you think about this, maybe we can come up together with even better solution.

**Comment by wing328** [comment]
In your Swagger spec, did you define proper security definition for the endpoint that requires the API key authentication? Can you share the spec via gist.github.com?

**Comment by mikolajprzybysz** [comment]
Hmm I guess I did not, I didn't even know I can this is my Swagger spec:
https://gist.github.com/mikolajprzybysz/a38d1be0a26a8df7d9f1c8d836bff412

**Comment by mikolajprzybysz** [comment]
@wing328 Sorry that was config this is spec:
https://gist.github.com/mikolajprzybysz/0686aec4ded7e66100befd1913e097e7

**Comment by wing328** [comment]
@mikolajprzybysz please follow https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L182 as an example and define the security setting. Then you can refer to the auto-generated doc (markdown) on how to set the API key when calling that method.

**Comment by mikolajprzybysz** [comment]
I will investigate this and get back to you

**Comment by mikolajprzybysz** [comment]
@wing328 you were right, I just put it as a regular param instead of as securityDefinition I should have added to the root:
```
securityDefinitions:
  x_api_key:
    type: apiKey
    name: x-api-key
    in: header
security:
  - x_api_key: []
```
and it works like a charm, not I have all endpoints secure and I can configure everything via Configuration class.
