### ISSUE TITLE
[csharp] If you have a definition named "Client", generated code wont' compile

### ISSUE THREAD

**Issue by langdonx** [swagger-api/swagger-codegen#2943]
##### Description
If you have a class definition named `Client`, the generated code won't compile because of a conflict with the namespace.  `Client` seems like it might be a very common model name (`Api` not so much, maybe `Model`, but probably not as common as `Client`).

##### Swagger-codegen version
master, cloned at the time of posting

##### Swagger declaration file content or url
N/A

##### Command line used for generation
java -jar swagger-codegen-cli.jar generate -i http://localhost:50002/swagger/docs/v1 -l csharp -c swagger-codegen-csharp-config.json --import-mappings Object=System.Object -o ./

##### Steps to reproduce
Just have a definition named Client in your spec.

##### Related issues
Couldn't find any related issues.

##### Suggest a Fix
Change the generated namespace from Client to ApiRestClient (worked well for my in my template).

**Comment by jimschubert** [comment]
Changing the namespace would be a breaking change for anyone consuming the client outside of the generated code. Do you think a namespace alias would suffice?

```
using SwaggerClient = IO.Swagger.Client;
//…

/// <summary>
/// Initializes a new instance of the <see cref="PetApi"/> class.
/// </summary>
/// <returns></returns>
public PetApi(String basePath)
{
    this.Configuration = new SwaggerClient.Configuration(new SwaggerClient.ApiClient(basePath));
    //…
}
```

This is also related in part to #2630

**Comment by wing328** [comment]
Or we can escape `Client` to `ModelClient` (similar to what we've done for `Object`, which is mapped to `ModelObject` in C#.

**Comment by jimschubert** [comment]
Would we do the same for Model? Or should we allow users to change the model/Api/client package names?

**Comment by wing328** [comment]
I think I will go with fully-qualified names as we've discussed in another thread.

**Comment by wing328** [comment]
@langdonx I filed #2962 to add test model "Client". If you've time, please pull that branch to test.

**Comment by langdonx** [comment]
Thanks guys, I really appreciate it.  The less template overrides I have to make the better!.  Won't be able to test until Tuesday, but definitely get to it.

**Comment by wing328** [comment]
@langdonx I found an issue and will need a bit more time to fix. Will keep you posted.

**Comment by wing328** [comment]
#3331 has been merged into master. Please pull the latest to give it a try.
