### ISSUE TITLE
[Java]  inconsistent version 2.1.6 in mavencentral with current code in github

### ISSUE THREAD

**Issue by martinmuellerrohde** [swagger-api/swagger-codegen#2949]
Note: we noticed CodegenModel.java with Map<String, Object> allowableValues is missing in a Swagger-codegen jar downloaded from Maven-central.

There seems to be an inconcistency:

If Maven retrieves version 2.1.6 from maven-central it gets the version with CodegenModel.java where `allowableValues `is represented as a `List<String>`.

If downloading the latest code from github it also creates a version 2.1.6 but this time with CodegenModel.java where `allowableValues `is represented as a `Map<String, Object>`.

In other words:
The releases tagged as 2.1.6 doesn't contain your great additions in CodegenModel.java for enum key/value-pairs. 
Even though thoses changes were prior to 2.1.6 they are not included in the release dated from April 6th 2016.

I really would like to use the new enum-features and don't know how to make my build-process stable if it downloads the wrong version.

Swagger-codegen version: 2.1.6

Proof:
Compare content of 
http://central.maven.org/maven2/io/swagger/swagger-codegen/2.1.6/swagger-codegen-2.1.6.jar
with your latest code.

Suggestion:
a) change the version in your pom.xml from 2.1.6 to 2.1.7-SNAPSHOT 
b) tag the latest code with Map<String, Object> allowableValues to make it available for download via mavencentral

**Comment by wing328** [comment]
@martinmuellerrohde I've merged https://github.com/swagger-api/swagger-codegen/pull/2950 into master to update the version to 2.2.0-SNAPSHOT (which is the next stable version)

**Comment by martinmuellerrohde** [comment]
Thank you @wing328  !
Currently your readme.MD still says "2.1.7-SNAPSHOT" even though it is 2.2.0-SNAPSHOT  now.

**Comment by wing328** [comment]
@martinmuellerrohde updated :)

**Comment by wing328** [comment]
For `allowableValues` it's a breaking change due to the need to have better enum support. Please refer to https://github.com/swagger-api/swagger-codegen/pull/2508#issuecomment-221574421 for more information.

**Comment by martinmuellerrohde** [comment]
Super !
Now I guess I still need it to be published at maven central, right?

**Comment by wing328** [comment]
@martinmuellerrohde I do not have right to do that. I think @fehguy and @webron are busy at the CloudFoundry Summit.

Can you do a `mvn install` to install the 2.2.0-SNAPSHOT version locally for the time being?

**Comment by fehguy** [comment]
Hi, we are definitely not ready to release 2.2.0, but we can do a patch release of 2.1.7 whenever @wing328 is ready.

**Comment by wing328** [comment]
@martinmuellerrohde it usually takes 3 to 4 months to release a stable version. I think your request is to upload 2.2.0-SNAPSHOT (not 2.2.0) to maven repo for the time being, right?

**Comment by fehguy** [comment]
I would suggest that we don't do that though, because 2.2.0 will have some major changes in packaging and it'll break @martinmuellerrohde 's deployment when that happens...

**Comment by martinmuellerrohde** [comment]
Right!
Am 25.05.2016 17:10 schrieb "wing328" <notifications@github.com>:

**Comment by martinmuellerrohde** [comment]
Oh, yes.
You are right.
A 2.1.7 would be a lot nicer.
Am 25.05.2016 17:14 schrieb "Tony Tam" <notifications@github.com>:

**Comment by heikom71** [comment]
Same problem like Martin in my project - a patch version 2.1.7 would be fanatastic...

**Comment by wing328** [comment]
We'll release 2.2.0 soon. 

Closing this issue.
