### ISSUE TITLE
swagger-codegen-maven-plugin parses the yaml file twice

### ISSUE THREAD

**Issue by pablograna** [swagger-api/swagger-codegen#2958]
##### Description

CodeGenMojo calls (and does not use the local variable swagger):

        Swagger swagger = SwaggerParser().read(inputSpec);

and later in the code, CodegenConfigurator calls:

        Swagger swagger = new SwaggerParser().read(inputSpec, authorizationValues, true);

This shows any error twice in the plugin output.

##### Swagger-codegen version

I ran this from master, v 2.1.6, HEAD was 917192e5585e33bda5d9684184fc956c890a08f1.

##### Swagger declaration file content or url

Any yaml that does not parse correctly

##### Suggest a Fix

I simply removed the first call to the parser from the CodeGenMojo. I can as for a pull request.

**Comment by wing328** [comment]
@pablograna thanks for reporting the issue. Would you please file a PR so that we can review the fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by pablograna** [comment]
This is the pull request: https://github.com/swagger-api/swagger-codegen/pull/2977

Unfortunately, I also pushed a different commit that went into this pull request. The second one fixes a 'compilation error' in eclipse. Let me know if it is better to send a new pull request with the first commit alone.

**Comment by pablograna** [comment]
I created a new, cleaner, PR, sorry for the overhead: https://github.com/swagger-api/swagger-codegen/pull/3005

**Comment by wing328** [comment]
PR merged.

Thanks @pablograna for the contribution.
