### ISSUE TITLE
[RUBY] README.md and docs not exporting with Ruby generation

### ISSUE THREAD

**Issue by chrismanderson** [swagger-api/swagger-codegen#2959]
##### Description

When I export a Ruby client with `swagger-codegen`, there are some files missing that are present when I use editor.swagger.io, namely the `README.MD`, `docs` folder, `spec` folder, and `git_push.sh`.

I'm assuming there is a flag I'm missing, but couldn't find anything revelatory in the swagger-codegen readme.

If I export the client library from editor.swagger.io, those missing files are included.

##### Swagger-codegen version

`2.1.5` installed via homebrew

##### Command line used for generation

    swagger-codegen generate \
      -i ~/def/swagger.json \
      -l ruby \
      -o ~/swagger/exports \
      -c ~/def/config.json

##### Steps to reproduce

1. Run the previously stated command line command, observe no docs are generated.

**Comment by wing328** [comment]
editor.swagger.io is using swagger-codegen v2.1.6 (latest stable version)

please pull the latest master (which uses apache 2.0 for Ruby API client) or use homebrew to update swagger codegen to 2.1.6

**Comment by chrismanderson** [comment]
Homebrew doesn't have 2.1.6, only seems to have up to 2.1.5. No worries, I pulled down and built manually.

Thanks!

**Comment by fehguy** [comment]
homebrew has 2.1.6, be sure to run `brew update` to pick it up.
