### ISSUE TITLE
Drop down menu for selecting country then states then district

### ISSUE THREAD

**Issue by DeepzSandra** [swagger-api/swagger-codegen#2964]
I am not able to design the function "print_district" to get the values from s_b. Kindly help me to defined this multidimensional array.

I suppose to get c11,c12,c13,... on selection from C1 from country country 1 and c21,c22,c23,... on selecting C2 from country 1 But I am getting d11,d12,d13,... and d12,d22,23 so on which is from country 2
 this is my code:
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
<script type= "text/javascript">
var country_arr = new Array("country 1", "country 2");
var s_a = new Array();
s_a[0]="";
s_a[1]="C1|C2";
s_a[2]="D1|D2";

var s_b = new Array();
s_b[1,1]="c11|c12|c13|c14|c15|c16|c17|c18|c19|c10";
s_b[1,2]="c21|c22|c23|c24|c25|c26|c27|c28|c29|c210";
s_b[2,1]="d11|d12|d13|d14|d15|d16|d17|d18|d19|d10";
s_b[2,2]="d21|d22|d23|d24|d25|d26|d27|d28|d29|d210";
function print_country(country_id){
    // given the id of the <select> tag as function argument, it inserts <option> tags
    var option_str = document.getElementById(country_id);
    option_str.length=0;
    option_str.options[0] = new Option('Select Country','');
    option_str.selectedIndex = 0;
    for (var i=0; i<country_arr.length; i++) {
        option_str.options[option_str.length] = new Option(country_arr[i],country_arr[i]);
    }
}

function print_state(state_id, state_index){
    var option_str = document.getElementById(state_id);
    option_str.length=0;
    option_str.options[0] = new Option('Select State','');
    option_str.selectedIndex = 0;
    var state_arr = s_a[state_index].split("|");
    for (var i=0; i<state_arr.length; i++) {
        option_str.options[option_str.length] = new Option(state_arr[i],state_arr[i]);
    }
}
//This function is incorrect, just to demonstrate, please help to correct this

function print_district(district_id, district_index){
    var option_str = document.getElementById(district_id);
    option_str.length=0;
    option_str.options[0] = new Option('Select district','');
    option_str.selectedIndex = 0;
    var district_arr = s_b[district_index].split("|");
    for (var i=0; i<district_arr.length; i++) {
        option_str.options[option_str.length] = new Option(district_arr[i],district_arr[i]);
    }
}

</script>
</head>

<body>
<form>
Select Country:   <select onchange="print_state('state',this.selectedIndex);" id="country" name ="country" ></select>
        <br />
        State: <select onchange="print_district('district',this.selectedIndex);" name ="state" id ="state"></select>
        <br />
        District <select name ="district" id ="district"></select>
        <input type="submit"></form>
        <script language="javascript">print_country("country");</script>
</body>
</html>

**Comment by wing328** [comment]
Sorry I don't understand your question. To help you model your "data', can you provide the data in JSON format?

**Comment by DeepzSandra** [comment]
This is my script: 
var country_arr = new Array("country 1", "country 2");
var s_a = new Array();
s_a[0]="";
s_a[1]="C1|C2";
s_a[2]="D1|D2";

var s_b = new Array();
s_b[1,1]="c11|c12|c13|c14|c15|c16|c17|c18|c19|c10";
s_b[1,2]="c21|c22|c23|c24|c25|c26|c27|c28|c29|c210";
s_b[2,1]="d11|d12|d13|d14|d15|d16|d17|d18|d19|d10";
s_b[2,2]="d21|d22|d23|d24|d25|d26|d27|d28|d29|d210";
function print_country(country_id){
    // given the id of the <select> tag as function argument, it inserts <option> tags
    var option_str = document.getElementById(country_id);
    option_str.length=0;
    option_str.options[0] = new Option('Select Country','');
    option_str.selectedIndex = 0;
    for (var i=0; i<country_arr.length; i++) {
        option_str.options[option_str.length] = new Option(country_arr[i],country_arr[i]);
    }
}

function print_state(state_id, state_index){
    var option_str = document.getElementById(state_id);
    option_str.length=0;
    option_str.options[0] = new Option('Select State','');
    option_str.selectedIndex = 0;
    var state_arr = s_a[state_index].split("|");
    for (var i=0; i<state_arr.length; i++) {
        option_str.options[option_str.length] = new Option(state_arr[i],state_arr[i]);
    }
}
//This function is incorrect, just to demonstrate, please help to correct this

function print_district(district_id, district_index){
    var option_str = document.getElementById(district_id);
    option_str.length=0;
    option_str.options[0] = new Option('Select district','');
    option_str.selectedIndex = 0;
    var district_arr = s_b[district_index].split("|");
    for (var i=0; i<district_arr.length; i++) {
        option_str.options[option_str.length] = new Option(district_arr[i],district_arr[i]);
    }
}

**Comment by DeepzSandra** [comment]
choose country1 display s-a[c1,c2] and choose c1 not proper districk  display s_b[2,1]="d11|d12|d13|d14|d15|d16|d17|d18|d19|d10";

**Comment by ePaul** [comment]
Sorry, could you elaborate what this has to do with Swagger-Codegen?

(Also please note that you can format code as such by either indenting it with four spaces, or by wrapping it in three backticks:

    ```
    code here
    ```

But this project's issue tracker is for issues with the Swagger-Codegen project, not a general coding help forum.)
