### ISSUE TITLE
[C#] Map `number` to `Decimal`

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2967]
Similar to Java which maps `number` to `BigDecimal`,  we should do the same for C# to make it consistent across different langauges by mapping `number` to `Decimal` in C#.

If anyone has any concern or suggestion, please kindly voice out.

**Comment by jimschubert** [comment]
Would this be the same as #2813 , or would that issue then require an option to generate as `Double` instead? I think we had discussed this previously.

**Comment by wing328** [comment]
My understanding is that we need the following mapping:

float	(type:number, format: float) => float	
double (type: number, format: double) => double
number (type: number, no format) => decimal

(currently number is mapped to double as well)

**Comment by wing328** [comment]
#2813 has been closed due to no response from the user.
