### ISSUE TITLE
online swagger codegen server support latest version option

### ISSUE THREAD

**Issue by whq731** [swagger-api/swagger-codegen#2974]
##### Description
I faced an bug in 2.1.6 which is stable version and fixed in 2.2 current master version.

https://github.com/swagger-api/swagger-codegen/pull/2785

But now the online api is only using the stable version 2.1.6.

https://generator.swagger.io/#/
[ base url: /api , api version: 2.1.6 ]

Could the api team add an option for using the latest version of swagger codegen?

**Comment by wing328** [comment]
If you want to use the latest version, the recommended approach is to do it locally: https://github.com/swagger-api/swagger-codegen#getting-started

(you can also run your own generator with latest master locally)

**Comment by whq731** [comment]
Yeah,i can run the latest locally.

It means i have to perform the generator.swagger.io's api services locally...
Thank you by the .I will look into it.

**Comment by wing328** [comment]
A workaround is to modify the host table (windows/mac/linux) to point generator.swagger.io to your localhost assuming your'e running the generator locally at port 80 (and of course remember to remove it later when you want to use the production generator.swagger.io)

**Comment by whq731** [comment]
👌！THX！
