### ISSUE TITLE
Codegen from libraries not supported for templates in JAR file

### ISSUE THREAD

**Issue by mythofcode** [swagger-api/swagger-codegen#2981]
##### Description

Specifying a library, e.g. "jersey2" does not work.

Instead, code-generation defaults to using the base template, e.g. jersey1_18 for jaxrs.

##### Swagger-codegen version

2.2.0, however I have seen this in several previous versions.

##### Swagger declaration file content or url

swagger-config.json should contain (and may have other properties for packages etc)
{
  "library":"jersey2"
}

##### Command line used for generation

<swagger-codegen> -i ANY-YAML -l jaxrs -c swagger-config.json

##### Steps to reproduce

1. Run swagger-codegen from a jar, e.g.
java -jar YOUR-PATH/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar $*

2. Examine the generated pom.xml and you will see:

...
   ` <jersey-version>1.18.1</jersey-version>`
...

You should see:
...
    `<jersey2-version>2.6</jersey2-version>`
...

##### Related issues

?

##### Suggest a Fix

A fix to AbstractGenerator.java should be sufficient. I'll follow-up with either a patch or a pull request.

**Comment by wing328** [comment]
@mythofcode thanks for reporting the issue and offering help for a fix.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by mythofcode** [comment]
Here's a diff patch.

```
diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java
index 40b5943..6ad19c8 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/AbstractGenerator.java
@@ -63,6 +63,18 @@ public abstract class AbstractGenerator {
         throw new RuntimeException("can't load template " + name);
     }
 
+    private boolean resourceExists(String path) {
+        if (getClass().getClassLoader().getResource(getCPResourcePath(path)) != null) {
+            LOGGER.debug("Using resource " + path + " from jar");
+            return true;
+        } else if (new File(path).exists()) {
+            LOGGER.debug("Using resource " + path + " from filesystem");
+            return true;
+        }
+        LOGGER.debug("Resource " + path + " does not exist");
+        return false;
+    }
+
     /**
      * Get the template file path with template dir prepended, and use the
      * library template if exists.
@@ -77,21 +89,20 @@ public abstract class AbstractGenerator {
             String libTemplateFile = config.templateDir() + File.separator +
                 "libraries" + File.separator + library + File.separator +
                 templateFile;
-
-            if (new File(libTemplateFile).exists()) {
+            if (resourceExists(libTemplateFile)) {
                 return libTemplateFile;
             }
 
             libTemplateFile = config.embeddedTemplateDir() + File.separator +
                 "libraries" + File.separator + library + File.separator +
                 templateFile;
-            if (embeddedTemplateExists(libTemplateFile)) {
+            if (resourceExists(libTemplateFile)) {
                 // Fall back to the template file embedded/packaged in the JAR file...
                 return libTemplateFile;
             }
         }
         String template = config.templateDir() + File.separator + templateFile;
-        if (new File(template).exists()) {
+        if (resourceExists(template)) {
             return template;
         } else {
             // Fall back to the template file embedded/packaged in the JAR file...

```

**Comment by wing328** [comment]
@mythofcode please submit a PR and we'll review.

(change in AbstractGenerator.java would take more time to review and from what I understand the issue is jaxrs-specified while `java` API client does not have similar, maybe the fix should be in the JaxRS generator java class)

**Comment by mythofcode** [comment]
@wing328 I appreciate you are swamped and want to take a conservative view of the fix, but when you take the time to review the code that calls this, you will see that it attempts to read resource files from two stores: the CLASSPATH, and the filesystem. The original code generates several path patterns, but each path is only tested against one store. The change simply makes it test against both stores, so the calling code works correctly. A PR won't help you to review this, because the problem originates mainly in the assumptions from the calling code :)

**Comment by wing328** [comment]
@mythofcode I'm able to fix it locally and should be able to file a PR by today.

(A PR would make our life easier as the change will go through the CI tests run by Travis to make sure it's not breaking anything covered by the tests and there's an easy way in the PR page that I can pull the change to test locally in my machine)

**Comment by wing328** [comment]
@pubudu91 FYI. Update above.

**Comment by pubudu91** [comment]
@wing328 Thanks a lot! It's working! One minor issue is that the Jetty version in the pom file is missing a dot. It should be "9.3.10.M0"

**Comment by wing328** [comment]
@pubudu91 @mythofcode The fix has been merged into master. Please pull the latest and give it a try.

**Comment by mythofcode** [comment]
@wing328 Merge is good, my fix is working correctly. I also tested the legacy support for jersey1, also looking good.

I've also updated the docs to reflect the new jersey2 default, see below for diffs, ready to git apply.

```
diff --git README.md README.md
index 2c42729..2baa040 100644
--- README.md
+++ README.md
@@ -47,7 +47,8 @@ Check out [Swagger-Spec](https://github.com/OAI/OpenAPI-Specification) for addit
       - [Python Flask (Connexion)](#python-flask-connexion)
       - [Ruby Sinatra](#ruby-sinatra)
       - [Scala Scalatra](#scala-scalatra)
-      - [Java JAX-RS (Java JAX-RS (Jersey v1.18)](#java-jax-rs-jersey-v118)
+      - [Java JAX-RS (Java JAX-RS (Jersey 2)](#java-jax-rs-jersey-2)
+      - [Java JAX-RS (Java JAX-RS (Jersey 1)](#java-jax-rs-jersey-1)
       - [Java JAX-RS (Apache CXF 2 / 3)](#java-jax-rs-apache-cxf-2--3)
       - [Java JAX-RS (Resteasy)](#java-jax-rs-resteasy)      
       - [Java Spring MVC](#java-spring-mvc)
@@ -548,8 +549,8 @@ CONFIG OPTIONS
 
 	library
 	    library template (sub-template) to use:
-	    <default> - HTTP client: Jersey client 1.18. JSON processing: Jackson 2.4.2
-	    jersey2 - HTTP client: Jersey client 2.6
+	    <default> - HTTP client: Jersey client 2 (2.22.2 or later). JSON processing: Jackson 2 (2.4.5 or later)
+	    jersey1 - HTTP client: Jersey client 1.19.1. JSON processing: Jackson 2 (2.4.5 or later)
 	    feign - HTTP client: Netflix Feign 8.1.1.  JSON processing: Jackson 2.6.3
 	    okhttp-gson - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1
 	    retrofit - HTTP client: OkHttp 2.4.0. JSON processing: Gson 2.3.1 (Retrofit 1.9.0)
@@ -696,13 +697,27 @@ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -o samples/server/petstore/scalatra
 ```
 
-### Java JAX-RS (Jersey v1.18)
+### Java JAX-RS (Jersey 2)
+
+Currently Jersey 2.22.2
+
+```
+java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
+  -i http://petstore.swagger.io/v2/swagger.json \
+  -l jaxrs \
+  -o samples/server/petstore/jaxrs-jersey2
+```
+
+### Java JAX-RS (Jersey 1)
+
+Currently Jersey v1.19.1
 
 ```
 java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i http://petstore.swagger.io/v2/swagger.json \
   -l jaxrs \
-  -o samples/server/petstore/jaxrs-jersey
+  --library jersey1 \
+  -o samples/server/petstore/jaxrs-jersey1
 ```
 
 ### Java JAX-RS (Apache CXF 2 / 3)
```
