### ISSUE TITLE
Java Feign client generator:  HTTP header name should be named Accept not Accepts

### ISSUE THREAD

**Issue by daknin** [swagger-api/swagger-codegen#2983]
##### Description

The Feign generator is producing Api classes with an incorrect header name.
e.g.
  @RequestLine("DELETE /pet/{petId}")
  @Headers({
    "Content-type: application/json",
    "Accepts: application/json",
    "apiKey: {apiKey}"
  })
  void deletePet(@Param("petId") Long petId, @Param("apiKey") String apiKey);

The header should be named Accept not Accepts. 

##### Swagger-codegen version
2.1.6

**Comment by daknin** [comment]
Pull request: https://github.com/swagger-api/swagger-codegen/pull/2984

**Comment by daknin** [comment]
PR has been merged so closing issue

**Comment by wing328** [comment]
@daknin thanks again for the contribution.
