### ISSUE TITLE
[slim] generator creates invalid paths for Models

### ISSUE THREAD

**Issue by jkt628** [swagger-api/swagger-codegen#2985]
##### Description

the slim generator creates two directories: 'SwaggerServer' and 'SwaggerServer\lib\Models'.  on un*x the latter should be SwaggerServer/lib/Models, e.g., using File.separator like other pathnames.

##### Swagger-codegen version

http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar

##### Swagger declaration file content or url

samples/yaml/echo.yaml

##### Command line used for generation

java -jar swagger-codegen-cli-2.1.6.jar generate -l slim -i samples/yaml/echo.yaml

##### Steps to reproduce

git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
curl -O http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar
java -jar swagger-codegen-cli-2.1.6.jar generate -l slim -i samples/yaml/echo.yaml
ls -ld S*

##### Related issues

unknown

##### Suggest a Fix

could borrow toPackagePath() from PhpClientCodegen.

**Comment by wing328** [comment]
@jkt628 thanks for reporting the issue. Would you have cycle to contribute a fix?

Also it's worth sharing with you that we've added "PHP Lumen" generator in the latest master that you may be interested in giving it a try.

**Comment by jkt628** [comment]
Java is foreign to me.  if it were C, C++ or Go, sure, i'd do it.

**Comment by wing328** [comment]
@jkt628 no problem we'll leverage the community to fix it instead.

**Comment by wing328** [comment]
@jkt628 what about using https://editor.swagger.io to generate PHP slim server stub as a workaround?

**Comment by jkt628** [comment]
first thing i see:

Server code generator is unreachable! Client code generator is unreachable!

**Comment by wing328** [comment]
I suspect it's due to network issue with your machine.

**Comment by wing328** [comment]
@jkt628 I should have fixed it for Slim. Can you please do a check to confirm?

**Comment by jkt628** [comment]
@wing328 thanks for the fix.
