### ISSUE TITLE
[JAVA] Incorrect display of date-time in UI

### ISSUE THREAD

**Issue by pavel-sbor** [swagger-api/swagger-codegen#2991]
##### Description

I have date-time field in my spec.
```
definitions:
  MDCTrace:
    title: MDC Trace definition
    type: object
    properties:
      expirationTime:
        type: string
        format: date-time
        readOnly: true
```
Although "expitationTime" has a date format in generated java code,  it displays as a number on UI page:

```
Response Body:
[
  {
    "expirationTime": 1474344922000
  }
]
```

##### Swagger-codegen version

I use docker image for generation
https://github.com/mydock/swagger-codegen-prebuilt

##### Swagger declaration file content or url

```
swagger: '2.0'

# This is your document metadata
info:
  version: "0.1.0"
  title: 'TITLE'
  description: |
    Description.
  contact:
    name: API Support
    url: http://uri.ru/
    email: mail@mail.ru
    
produces:
  - application/json
  
definitions:
  MDCTrace:
    title: MDC Trace definition
    properties:
      expirationTime:
        type: string
        readOnly: true
paths:
  /mdc/traces:
    get:
      description: |
        Get MDC Traces definitions.
      tags:
      - traces
      operationId: getMDCTraces
      responses:
        200:
          description: |
            MDC Traces definitions.
          schema:
            title: ArrayOfMDCTaces
            type: array
            items:
              $ref: '#/definitions/MDCTrace'
        default:
          description: |
            Generic Error.
```

##### Command line used for generation

docker run --rm -t -v $(pwd):/code mydock/swagger-codegen-prebuilt generate -i /code/swagger.yaml -l spring-mvc -o /code/app

##### Steps to reproduce

1) Generate code with spec
2) Create in "/mdc/traces" method's handler (getMDCTraces()) instance of MDCTrace class.
3) Return it as a list of MDCTraces
` return new ResponseEntity<List<MDCTrace>>(list, HttpStatus.OK);`
4) Make a query and look at _expirationTime_ field

##### Related issues

not found

##### Suggest a Fix

I suppose, the problem in displaying on the web page, because before the line
` return new ResponseEntity<List<MDCTrace>>(list, HttpStatus.OK);`
expirationTime displayed as normal date in Java code.

**Comment by ePaul** [comment]
**I did reproduce this**, using the following steps in addition to what was mentioned in the report:

* add the `format: date-time` line in the swagger.yaml (it was missing there)
* Add a main class:

```java
package io.swagger;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@EnableAutoConfiguration
@SpringBootApplication
public class SwaggerTestApplication {
    public static void main(final String[] args) {
        SpringApplication.run(SwaggerTestApplication.class, args);
    }
}
```
* Add a dependency to spring-boot-starter-web (and use spring-boot-starter-parent:1.3.5.RELEASE as the pom's parent)
* remove the dependency for slf4j-log4j12 (because that caused the application to not start up because of a cyclic dependency with log4j-over-slf4j ... I guess I could also have excluded the latter one).
* execute `mvn spring-boot:run` to start the server
* in another terminal, run `curl -i http://localhost:8080/mdc/traces`

I added these lines to the MdcApi.getMDCTraces method:

```java
      final MDCTrace trace = new MDCTrace();
      trace.setExpirationTime(new Date());
      final List<MDCTrace> list = Arrays.asList(trace);
      LoggerFactory.getLogger(MdcApi.class).info("sending back list of traces: {}", list);
      return new ResponseEntity<List<MDCTrace>>(list, HttpStatus.OK);
```
This logs as expected
```
list of traces: [class MDCTrace {
  expirationTime: Mon May 30 20:31:51 CEST 2016
}
]
```
but returns over HTTP this:

```http
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 30 May 2016 18:31:51 GMT

[{"expirationTime":1464633111614}]
```

Unfortunately I can't see which Swagger-Codegen version is actually used there. But generating with a fresh build from master (2.2.0-SNAPSHOT) has the same effect.

Here is the relevant part of the generated `MDCTrace` class:

```java

  private Date expirationTime = null;

  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("expirationTime")
  public Date getExpirationTime() {
    return expirationTime;
  }
  public void setExpirationTime(Date expirationTime) {
    this.expirationTime = expirationTime;
  }
```

**Comment by ePaul** [comment]
**Possible fix**

Adding e.g.
```java
  @JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd'T'HH:mm:ss'Z'")
```
to the get method makes the output look like this (which matches what I would expect after reading the spec):
```http
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 30 May 2016 18:58:06 GMT

[{"expirationTime":"2016-05-30T18:58:06Z"}]
```

I guess this needs to be somehow added in the templates (or the Java Codegen classes).

**Comment by cbornet** [comment]
It's better to configure Jackson with ```spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false``` in spring-boot or to configure the Jackson2ObjectMapperBuilder in spring-mvc.
See [here](https://spring.io/blog/2014/12/02/latest-jackson-integration-improvements-in-spring#customizing-the-jackson-objectmapper)

**Comment by wing328** [comment]
@pavel-sbor please try the fix suggested by @ePaul and @cbornet if you've not done so.

Issue closed due to lack of activity.
