### ISSUE TITLE
Jersey 2 generator not working

### ISSUE THREAD

**Issue by pubudu91** [swagger-api/swagger-codegen#2997]
##### Description

I tried to generate a Jersey 2 server stub using Codegen, by passing a JSON config file. In that config file, I set the library to be Jersey 2. However, when checking the generated code, I found that it has used Jersey version 1.18.1. The config file seems to be processed correctly,  since other properties I had set in it were configured correctly in the pom file (such as groupId, artifactId etc). 

##### Swagger-codegen version

I built Codegen from the master branch. 

##### Command line used for generation

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i <path-to-spec>/docker-registry.yaml -c <path-to-config-file>/swagger-codegen-config.json -o samples/server/jersey2-server -l jaxrs`

##### Related issues

Issue #2488

**Comment by wing328** [comment]
@pubudu91 thanks for reporting the issue.

Is it the same as https://github.com/swagger-api/swagger-codegen/issues/2981 ?

**Comment by pubudu91** [comment]
Ah yes. Sorry. Didn't see that one. Yes, this is the same issue.

**Comment by wing328** [comment]
No worry. Closing this one.
