### ISSUE TITLE
[Scala][Java] Add "sbt" build config to Java/Scala SDK

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3006]
Currently, Java supports maven and gradle to build the library. We want to add "sbt" as well: http://www.scala-sbt.org/

This will make it easier for Scala developers to build the Scala/Java SDK to use it in their Scala program.

If anyone wants to work on this, please reply to let us know.

**Comment by jimschubert** [comment]
I think this duplicates #241.

I can take a look at creating the build file.

**Comment by wing328** [comment]
#241 is for scala while for this one, I want to cover Java API client as well ( so that it can be more easily used in scala with build.sbt)

I think @clasnake may have done it already.

**Comment by wing328** [comment]
Just did a check. Scala Petstore client still misses the bulid.sbt file. If you've cycle, please help create the build file for Scala API client.

**Comment by clasnake** [comment]
@wing328 @jimschubert I've added sbt for feign, retrofit2, retrofit2rx and jersey2 for the java client. The scala client and default client for java haven't been done yet. Please help create that sbt if you've cycle.

**Comment by jimschubert** [comment]
@wing328 @clasnake I've added sbt to the scala client. I looked at some of the other implementations and they all use `build.sbt` which I've had issues with in the past. I didn't know if sbt vs scala build files should be an option, but I always use the .scala files. Also, others drop sbt/gradle/pom to the output directory and my PR does not do this. I didn't know if this was a standard or what.

**Comment by wing328** [comment]
@jimschubert for the issue you encountered in the past, is there a SO link (or other URls) with more details that I can look into?

**Comment by jimschubert** [comment]
I've just looked through my bookmarks and don't see anything relevant. It may be that I've used sbt for multiproject builds with lots of customizations and plugins in the past (3 yrs ago). I've only recently picked sbt back up in the past few months.

Do you think build.sbt would be better and only offer the other format of requested by users?

**Comment by wing328** [comment]
I think we can go with build.sbt first for day 1 requirement and if users complain, we can then look into the issue.

Given that the issue you encountered was a few years ago, I think the issue may have been addressed already.

Given that your PR has generated ProjectBuild.scala already, we can go with both (build.sbt and ProjectBuild.scala and include the instruction in the auto-generated README)

**Comment by jimschubert** [comment]
@wing328 If we provide both (build.sbt and ProjectBuild.scala), it would require an option because two of the same project definitions can't live side by side. You can, however, have ProjectBuild.scala and any other .sbt file and sbt will compile and merge the contents of all of these under the `/project` directory.

**Comment by wing328** [comment]
@jimschubert then I would prefer to go with build.sbt and if users report issues building the sdk using sbt, then we'll consider ProjectBuild.scala.

**Comment by jimschubert** [comment]
@wing328 Thanks. Sorry to hijack this issue with discussion more related to #241.

To provide some context for this issue, you'll want to add the following two things to java's build.sbt:

```
crossPaths := false
autoScalaLibrary := false
```

crossPaths removes scala suffixes (e.g. `_2.11`), and autoScalaLibrary tells sbt to not include the scala-lang or whatever as a dependency.

**Comment by ramzimaalej** [comment]
@wing328 I think we can closed this one after you merged the PR I raised to add build.sbt
