### ISSUE TITLE
HaskellServantCodegen depends on NotImplementedException from sun package

### ISSUE THREAD

**Issue by pablograna** [swagger-api/swagger-codegen#3011]
##### Description

In Eclipse the HaskellServantCodegen has the following error:
 The type NotImplementedException is not accessible due to restriction on required library /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar

For some reason, eclipse does not allow references for certain packages in your sources, even if the code compiles from the command line. I cannot find the reason now, but I recall that some packages are some sort of internal api that should not be used in user code (sun.misc is an example I remember).

##### Suggest a Fix

Replace the NotImplementedException with UnsupportedOperationException from java.lang.

**Comment by wing328** [comment]
@pablograna I read more about `NotImplementedException` and agree with your suggestion to use `UnsupportedOperationException` instead.

cc @algas to see if he's any comment on the proposed change.

**Comment by wing328** [comment]
I did a search to confirm only haskell server stub generator uses `NotImplementedException`:

https://github.com/swagger-api/swagger-codegen/search?l=java&q=NotImplementedException&utf8=%E2%9C%93

**Comment by pablograna** [comment]
I'll submit a PR, then. I will also add some changes related to inconsistent package names.
Thanks.

**Comment by wing328** [comment]
@pablograna  PR merged. Issue closed.

Thanks for the contribution.
