### ISSUE TITLE
[Swift] NSDate parameters are percent-encoded rather than passed through an NSDateFormatter

### ISSUE THREAD

**Issue by vineetshah** [swagger-api/swagger-codegen#3019]
##### Description

NSDate parameters seem to be percent-encoded using their description string, which contains whitespace. This causes an NSDate such as `2016-05-31 16:31:44 +0000` to be encoded as `2016-05-31%2016%3A31%3A44%20%2B0000` in the HTTP request.
##### Swagger-codegen version

2.1.6
##### Suggest a Fix

NSDate parameters should be passed through an NSDateFormatter before adding it to the HTTP request, so that it looks something like: `2016-05-31T16:31:44Z`

**Comment by wing328** [comment]
Here is a related PR: https://github.com/swagger-api/swagger-codegen/pull/3264/commits

**Comment by jgavris** [comment]
@vineetshah Has #3264 resolved this?

**Comment by wing328** [comment]
Closing this as there's no update.
