### ISSUE TITLE
[Python] Provide option to eliminate body for DELETE request

### ISSUE THREAD

**Issue by taxpon** [swagger-api/swagger-codegen#3020]
##### Description
- Provide option to eliminate body for DELETE request
- Some server application (ex. Google App Engine, [ref](https://code.google.com/p/googleappengine/issues/detail?id=601)) do not take DELETE request with body
    - Current code will create body even if I set `body = None` because `json.dumps(None)` creates `nil` in `rest.py`

##### Swagger-codegen version
2.2.0-SNAPSHOT

##### Steps to reproduce
Create python clients with swagger-codegen and send DELETE request to servers which do not permit DELETE request with body (like Google App Engine)

##### Related issues
#2410 

I think codegen should provide users an option to choose whether or not to attach body.

##### Suggest a Fix
Add `request_body` variable in `rest.py`. If this is OK, I'll create PR.

```python
            # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
            if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
                if query_params:
                    url += '?' + urlencode(query_params)
                if headers['Content-Type'] == 'application/json':
                    request_body = json.dumps(body) if body else None
                    r = self.pool_manager.request(method, url,
                                                  body=request_body,
                                                  headers=headers)
```

**Comment by wing328** [comment]
Your suggestion looks good to me. The only question I've is whether the following conforms to PEP8:
```
request_body = json.dumps(body) if body else None
```
I would suggest using the typical if else in multiple lines instead.

cc @scottrw93

**Comment by taxpon** [comment]
I guess conditional expression do not violate any [PEP8](https://www.python.org/dev/peps/pep-0008/#references) rules.

**Comment by wing328** [comment]
@taxpon thanks for sharing (I've not used `pep8` to check the 1-liner if else statement myself)

And thank you for the PR. I know you may also use the Typescript API client to talk to your GAE backend. May I know if you've encountered similar issue with the DELETE operation? If yes, we'll open another issue to track that.

**Comment by taxpon** [comment]
@wing328 Ok. There is no problem so far. If I find any problem, I will create issues.

**Comment by wing328** [comment]
PR merged. Issue closed.

**Comment by pambeard** [comment]
Prior to 6/2 is could use the pyhon client code to generate commands similar to curl -k -X DELETE --user dds+PlanetLabs:zbQt2tnDVCr8lcfpMd3NnrBwcGfreoaqHOayAqoJ --header 'Content-Type: application/json' --header 'Accept: application/json' 'https://xxx.xxx.xxx.xxx/reservations/myuser/fred' with no body.  Now, when I try this I get HTTP error: SyntaxError: Unexpected token n<br>  &nbsp .  I see changes made to the way DELETE is handled in rest.py

**Comment by wing328** [comment]
@pambeard can you elaborate more on how you use the python client code to generate commands similar to curl? When you use the python API client directly (not the generate curl command), did you get similar error?

**Comment by pambeard** [comment]
The Curl command is from the swagger editor.  The python API adds the open pointy bracket br close pointy bracket (a single line break) which eventually calls the function request in rest.py.  Here the DELETE handling has been changed between the version that worked and the version that did not work.

**Comment by wing328** [comment]
@pambeard  Given that you're using swagger editor for your test, can you please pull the latest master to generate the Python API client to confirm if the issue still occurs?

**Comment by pambeard** [comment]
I should be able to test this today

**Comment by pambeard** [comment]
This is working in the latest pull.
Thanks,
Pam

From: Beard, Pam
Sent: Monday, June 27, 2016 8:28 AM
To: 'swagger-api/swagger-codegen'
Subject: RE: [swagger-api/swagger-codegen] [Python] Provide option to eliminate body for DELETE request (#3020)

I should be able to test this today

**Comment by wing328** [comment]
@pambeard thanks for the confirmation.
