### ISSUE TITLE
Fix warnings in pom.xml.

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3024]
When running `mvn`, you may find the following warnings:

```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.swagger:swagger-petstore-jersey2:jar:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 68, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

To fix the warning, please refer to https://github.com/swagger-api/swagger-codegen/pull/3023

If anyone wants to work on this for other Java API client or server stub generator, please reply to let us know.

**Comment by devcsrj** [comment]
Hi! This seems pretty straightforward. Let me fix the others!

**Comment by devcsrj** [comment]
@wing328 I just noticed - this issue can be closed now!
