### ISSUE TITLE
[C#] namespace issues

### ISSUE THREAD

**Issue by Serjster** [swagger-api/swagger-codegen#3032]
I'm using http://editor.swagger.io/ though I think that is of little consequence. I have 2 swagger clients being consumed in my web app and since they both share the same namespace when I try to new up a new client it becomes ambiguous... it would be awesome if there was an attribute that I can set in my server/swagger apps that specified the namespace to create in the client... is there one that I missed? If it's simple enough, any clue how I could go about creating one? My concern is that I'd have to make modifications to the gen tool to make use of my new attribute and I don't want to do that. I know I can specify a namespace in the jar codegen... but we'd like to stay with the online tool if possible... the other option is to create a new project for each client.... but that seems like a band-aid, not to mention overkill. Your help is appreciated.

**Comment by jimschubert** [comment]
@Serjster You can view the specification at http://swagger.io/specification/.

I think you're probably generating your clients in an unmaintainable way (or unintended, maybe?). The parameters used to customize the generated client are only available via the codegen jar or the generator web application. You can access the generator online at https://generator.swagger.io/ to check it out.

You can also run the codegen jar as a docker container. I have a container available for the codegen jar (https://hub.docker.com/r/jimschubert/swagger-codegen-cli/) and there's already one available for the generator api (https://hub.docker.com/r/swaggerapi/swagger-generator/), and I have pull #2945 open to integrate my container and other changes related to docker builds.

The following is an example usage of hitting the generator docker container, it's written for bash, so pre-Windows 10 you'd probably want to adapt it to batch or powershell:

```
# Start container and save the container id
CID=$(docker run -d swaggerapi/swagger-generator)
# allow for startup
sleep 5
# Get the IP of the running container
GEN_IP=$(docker inspect --format '{{.NetworkSettings.IPAddress}}'  $CID)
# Execute an HTTP request and store the download link
RESULT=$(curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "swaggerUrl": "http://petstore.swagger.io/v2/swagger.json"
}' 'http://localhost:8188/api/gen/clients/javascript' | jq '.link' | tr -d '"')
# Download the generated zip and redirect to a file
curl $RESULT > result.zip
# Shutdown the swagger generator image
docker stop $CID && docker rm $CID
```

If you absolutely want to use a web-based service, you can send an HTTP post with the options you need to `https://generator.swagger.io/`. I'm not sure whether that service is intended to be used like that, but that's where the code from http://editor.swagger.io/ is being generated if you look at your devtools network tab. You could probably also write a [snippet](https://developers.google.com/web/tools/chrome-devtools/debug/snippets/) fairly easily which intercepts requests on that page and adds the namespace to the request.

Regarding your question about specifying a namespace in the API's swagger definition, I think it would probably be difficult to get community buy-in on such a change to the official API specification. Generating clients for your swagger-documented API is generally considered a devops concern, not a public API concern. From a different perspective, the specification isn't designed to assume homogenous languages between APIs and Clients. The public API documentation is intentionally pretty language agnostic. There is a concept of [vendor extensions](http://swagger.io/specification/#vendorExtensions) which I think could support your requirements, but it would still require modification to the codegen module. Not only that, a vendor extension would either be .NET specific or it would require modifications to all generators.

**Comment by jimschubert** [comment]
For reference:

There is a new wiki page for documenting vendor extensions: https://github.com/swagger-api/swagger-codegen/wiki/Vendor-Extensions

If we go the route of using a vendor extension, that wiki page should be updated.

**Comment by Serjster** [comment]
Thanks for the info.
