### ISSUE TITLE
Swift GET request without any parameters has a body

### ISSUE THREAD

**Issue by Landschaft** [swagger-api/swagger-codegen#3036]
##### Description

In my API there is a GET call with a single @PathParam (no other parameters). When a generated Swift client calls this, there will be a request-body that consist of an empty JSON object: "{}". It seems odd that a GET request has a body at all; but this empty JSON object makes absolutely no sense. Even worse, it will be rejected by the WAF.

##### Swagger-codegen version

This bug occurs with Swagger 2.2.0.

In earlier versions, this would work.

##### Swagger declaration file content or url

`	@Path("some/{id}/details")
	@GET
	@Timed
	@ApiOperation(value = "Get the details for some ID.")
	public DetailsDTO getDetails(@PathParam("id") String id) {
		...
	}
`
It seems that the introduction of function APIHelper.convertBoolToString that converts an input of nil to an empty dictionary causes this. The empty parameter dictionary will result in the GET request having a body.

Before the introduction of APIHelper.convertBoolToString, an empty parameter dictionary would be nilled by APIHelper.rejectNil and the GET request would not have a body.

- https://github.com/swagger-api/swagger-codegen/commit/4b39e0579f2b03cbf51702624bf16cd0eb3803f6
- https://github.com/swagger-api/swagger-codegen/commit/8f0bd7301f9fde00dd5234658f9d262da1e537ad

##### Suggest a Fix

Make APIHelper.convertBoolToString output nil for nil input.

**Comment by wing328** [comment]
@Landschaft thanks for reporting the issue.

cc @jaz-ah @Edubits

**Comment by wing328** [comment]
@Landschaft may I know if you've cycle to contribute a PR to fix the issue?

**Comment by Landschaft** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3038

**Comment by wing328** [comment]
Closing this as #3038 has been merged into master.
