### ISSUE TITLE
ASPNET5 Server Stub - problem connecting to SQL

### ISSUE THREAD

**Issue by kdc415** [swagger-api/swagger-codegen#3040]
##### Description

ASPNET5 Server Stub - problem connecting to SQL

##### Swagger-codegen version

From the swagger.io website - latest

I'm using the codegen server stub, which uses ASP NET 5 RC1.

The assembly used for DependencyInjection is: using Microsoft.Extensions.DependencyInjection;

The problem I have is trying to add a sql connection like this:

services.AddEntityFramework().AddSqlServer().AddDbContext<Models>(options => { options.UseSqlServer(connectionString); });

AddEntityFramework is not a part of that assembly. I can do it with using Microsoft.Framework.DependencyInjection; 

..but that conflicts with the other assembly and if I use the latter over the former then it breaks all the other service injections that make up the heart swagger.

Can someone point me to an example on how to connect the API to SQL or offer advice?

Thanks - Ken

**Comment by jimschubert** [comment]
@wing328 This is more a question about ASP.NET 5 (ASP.NET Core 1.0) than a bug with the generator. The server generator doesn't have any references to ADO.NET, EF, or any other SQL provider.

@kdc415 it sounds like you may be trying to use an incompatible version of Microsoft.Data.Entity. For a complete working example of accessing a database in ASP.NET 5 (which was renamed this year to ASP.NET Core 1.0), you can see this example of mine: https://github.com/jimschubert/aurelia-webapi-example/blob/example/src/AureliaWebApi/Startup.cs. If you actually run the code, I apologize for how silly the UI looks... I was evaluating workflow of the new ASP.NET stack with Aurelia for the frontend.

This example uses the following compatible dependencies (from project.json):

```
 "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.InMemory": "7.0.0-rc1-final",
    "EntityFramework.SQLite": "7.0.0-rc1-final",
    "EntityFramework.Sqlite.Design": "7.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final"
  },
```

The example also uses an in-memory database for dev as well as a SQLite database for "prod".

The test project also has examples of unit testing and functional end-to-end API testing of the new ASP.NET stuff.

**Comment by kdc415** [comment]
**@jimschubert** - I agree it's not a bug. I posted in the group and was directed here. I used the only SQL example I could find in the Core docs and it's not compatible with the injection swagger uses. 

Thanks for the example - I'll be checking it out. What's the best place to post future questions? Doesn't seem like c# is popular in the google group.

Thanks - Ken

**Comment by jimschubert** [comment]
It's no problem.

Best place for questions might be one of the chat rooms.  https://gitter.im/orgs/aspnet/rooms

**Comment by jimschubert** [comment]
@kdc415 just wanted to follow up, was the example I provided helpful?

**Comment by kdc415** [comment]
Very much so Jim - thank you. I wanted to do some quick prototyping and
that was helpful.

Looking forward to the Core RTM so we can all move forward.

-- 
Ken Corley
Master Technology Solutions, LLC
334-262-8668

**Comment by jimschubert** [comment]
@kdc415 no problem. I think this issue could be closed.
