### ISSUE TITLE
[Python] Follow PEP8 rules

### ISSUE THREAD

**Issue by taxpon** [swagger-api/swagger-codegen#3041]
##### Description
- According to [CONTRIBUTING.md](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md), generated python codes are desired to follow [PEP8] (https://www.python.org/dev/peps/pep-0008/) rules.
- Currently,  generated codes are violating some PEP8 rules.
- I think templates should be fixed so that generated codes can follow PEP8 as far as possible.

###### PEP8 result sample under `/samples/client/petstore/python`
(Actually, I ignored E501(line too long) rule, because the swagger spec (like variable name) is possible to cause E501 errors in some cases, so it is impossible to omit E501 error completely with template modification.)
```bash
$ pep8 --ignore=E501
./setup.py:6:161: W291 trailing whitespace
./setup.py:11:1: W293 blank line contains whitespace
./setup.py:15:1: W293 blank line contains whitespace
./setup.py:17:1: W293 blank line contains whitespace
....
./tests/test_api_exception.py:47:1: W293 blank line contains whitespace
./tests/test_api_exception.py:90:1: W391 blank line at end of file
./tests/test_deserialization.py:81:17: E126 continuation line over-indented for hanging indent
./tests/test_deserialization.py:97:13: E121 continuation line under-indented for hanging indent
./tests/test_deserialization.py:127:9: E122 continuation line missing indentation or outdented
```

##### Swagger-codegen version
2.2.0-SNAPSHOT

##### Suggest a Fix
I'll create PR.

**Comment by wing328** [comment]
@taxpon your suggestion sounds good to me and agree that E501 should be ignored as the method/variable name can be really long as there's no limitation in spec to restrict that.

**Comment by taxpon** [comment]
@wing328 
One question.

Just after I run `mvn clean && bin/python-petstore.sh`, `samples/client/petstore/python/swagger_client/models/inline_response_200.py` seems not to be updated. Is that file generated by current swagger codegen? or past remaining (currently not used)? If it's a past remaining, can I delete it?

I do not understand codegen's core deeply, so your advice would be great help for me ;)

**Comment by wing328** [comment]
We've removed some of the tests in the Pestore swagger spec. Please feel free to delete it.

**Comment by wing328** [comment]
PR merged.
