### ISSUE TITLE
How to specify "--skip-overwrite" parameter for swagger-codegen-maven-plugin

### ISSUE THREAD

**Issue by smileyogurt** [swagger-api/swagger-codegen#3042]
I tried to pass the property in configOptions, but it seems does not work:

`<configOptions>
     <skipOverwrite>false</skipOverwrite>
</configOptions>
`

How to pass "--skip-overwrite" property for plugin?

I checked plugin code, it does not have this property specified, only in swagger-codegen-cli not plugin though. However this property is very important and we need to this to customize the new REST APIs/Models. Thanks,

**Comment by wing328** [comment]
@smileyogurt instead of using `skipOverwrite`, please pull the latest master, which will generate .swagger-codegen-ignore file (similar to .gitignore), and in .swagger-codegen-ignore you can put down files that you want to skip the overwrite.

**Comment by smileyogurt** [comment]
It is a maven project and I am using swagger-codegen-maven-plugin to generate APIs.

@wing328 Could  you elaborate more on how to use "skip overwrite" setting in pom.xml?

**Comment by jimschubert** [comment]
@smileyogurt Can you share the relevant parts of the command line you're using to generate?

If you're doing `java -jar swagger-codegen.jar generate -i swagger.json -l java -o api_v3\generated_sources\`, then `.swagger-codegen-ignore` would need to be under generated_sources as you have.

You've included a pom.xml. Are you using the maven plugin and not targeting the master branch?

**Comment by smileyogurt** [comment]
@jimschubert 

I am using a pom.xml, and maven plugin. I didn't target master branch.

            `<plugin>`
                `<groupId>io.swagger</groupId>`
                `<artifactId>swagger-codegen-maven-plugin</artifactId>`
                `<version>${swagger-codegen-version}</version>`
                `<executions>`
                    `<execution>`
                        `<id>generate_service_stub</id>`
                        `<phase>package</phase>`
                        `<goals>`
                            `<goal>generate</goal>`
                        `</goals>`
                        `<configuration>`
                            `<inputSpec>data/${yaml-file}.yaml</inputSpec>`
                            `<language>spring-mvc</language>`
                            `<output>${api-folder}_${yaml-file}/generated-sources</output>`
                            `<configOptions>`
                                `<sourceFolder>src</sourceFolder>`
                                `<dateLibrary>java8</dateLibrary>`
                                `<serializableModel>true</serializableModel>`
                            `</configOptions>`
                        `</configuration>`
                    `</execution>`
                `</executions>`
            `</plugin>`

**Comment by smileyogurt** [comment]
I also think all features of swagger codegen should be enhanced in plugin for a big project, instead of using CLI as a tool.

**Comment by jimschubert** [comment]
@smileyogurt I'd previously refactored the maven plugin to better support codegen options. That should exist in version 2.1.6.

The .swagger-codegen-ignore feature is new (about two weeks old) and only available in master/ branch/SNAPSHOT releases. You won't need to add any configuration options, as the codegen module used by the maven plugin will load the file from the output directory and skip writing according to rules in the file.

**Comment by jimschubert** [comment]
The .swagger-codegen-ignore support should be in the 2.2.0 release.

**Comment by smileyogurt** [comment]
@jimschubert 

When can 2.2.0 release be available at mvnrepository?

http://mvnrepository.com/artifact/io.swagger/swagger-codegen-maven-plugin

And before that any solution for now by using 2.1.6, or is there a snapshot plugin?

**Comment by jimschubert** [comment]
@smileyogurt I don't know about the timelines or whatever. Maybe @wing328 knows?

I looked on maven central and jcentral and there doesn't seem to be a SNAPSHOT plugin publilshed anymore. I seem to recall seeing one for some 2.1.x in the past, but I could be wrong.

However, you can clone the repository and on the master branch run `mvn clean package install` to get 2.2.0-SNAPSHOT installed locally.

**Comment by wing328** [comment]
Usually it takes 3 to 4 months for a stable minor release.

Given that the next release is a major release (2.2.0), it may take a bit longer.

**Comment by smileyogurt** [comment]
@jimschubert @wing328 

Thanks for comments I will build local 2.2.0-SNAPSHOT for current usage then.

**Comment by jimschubert** [comment]
@smileyogurt I didn't look at the plugin's implementation because you had said the option wasn't included. I just verified and the `skipOverwrite` option exists. I apologize for not looking sooner.

Try moving the skip overwrite option outside of the `configOptions` node. I hadn't recognized it before, but that `configOptions` is a confusing name. It currently only supports instantiation-types, import-mappings, type-mappings, language-specific-primitives, and additional-properties. Probably adding to the confusion is that all of the private members with Parameter annotations on the plugin code are options to the plugin. The `configOptions` node holds a map of dynamic key/value pairs.

I like your suggestion of an option for ignoring only if the file already exists.

**Comment by jimschubert** [comment]
@smileyogurt You haven't commented on this PR, so I assume you resolved your issues. I just wanted to let you know that I just opened a PR which will allow you to specify the location of a `.swagger-codegen-ignore` location outside of the generated directory. I think this will better address the issues you were having and give you more control than `skipOverwrite`.
