### ISSUE TITLE
[Java] Separate Spring and Swagger annotations for controllers

### ISSUE THREAD

**Issue by thebignet** [swagger-api/swagger-codegen#3053]
##### Description

Swagger @Api annotations could be extracted into an interface for each Spring Controller.  It should then be possible to generate only these interfaces and let the API developer implement those interfaces.

This is true for Spring controllers but should also be possible for other servers.

##### Swagger-codegen version

2.1.6

**Comment by cbornet** [comment]
Would #3039 do what you need ?

**Comment by thebignet** [comment]
Yes, that seems to do exactly that. Indeed the purpose of this is to keep existing implementation while generating interfaces and models from Swagger definition.
