### ISSUE TITLE
[Javascript] Single argument instead of multiple arguments for api parameters

### ISSUE THREAD

**Issue by darylteo** [swagger-api/swagger-codegen#3054]
##### Description

Right now, when generating in Javascript, it gives me:

```javascript
this.entityGet(param1, param2, param3) { }
````

This becomes quite unwieldy when large numbers of possible parameters are available (e.g. for filtering purposes). Swagger currently does not support object based query parameters, so I cannot reduce these parameters to one.

Alternatively, the idiomatic JS way to support large variable parameters is to use a object parameter instead

```javascript
this.entityGet(options) {}
````

##### Swagger-codegen version

2.1.6

##### Suggest a Fix

The current code generation for DefaultApi could be changed from 

```javascript
    this.entityGet = function(param1, param2, param3) {
      var postBody = null;

      // verify the required parameter 'param1' is set
      if (param1 == undefined || param1 == null) {
        throw "Missing the required parameter 'param1' when calling entityGet";
      }
      // verify the required parameter 'param2' is set
      if (param2 == undefined || param2 == null) {
        throw "Missing the required parameter 'param2' when calling entityGet";
      }
      // verify the required parameter 'param3' is set
      if (param3 == undefined || param3 == null) {
        throw "Missing the required parameter 'param3' when calling entityGet";
      }
      ...
    }
````

to 

```javascript
    this.entityGet = function(options) {
      var postBody = null;
      var param1 = options.param1;
      var param2 = options.param2;
      var param3 = options.param3;

      // verify the required parameter 'param1' is set
      if (param1 == undefined || param1 == null) {
        throw "Missing the required parameter 'param1' when calling entityGet";
      }
      // verify the required parameter 'param2' is set
      if (param2 == undefined || param2 == null) {
        throw "Missing the required parameter 'param2' when calling entityGet";
      }
      // verify the required parameter 'param3' is set
      if (param3 == undefined || param3 == null) {
        throw "Missing the required parameter 'param3' when calling entityGet";
      }
      ...
    }
````

Additional cli parameter will have to be added to support user opt-in to this idiomatic style.

**Comment by wing328** [comment]
@darylteo I'd a look at Twilio and Strip NodeJS libs:
https://github.com/twilio/twilio-node/blob/master/lib/TaskRouterClient.js#L23
https://github.com/stripe/stripe-node/blob/master/lib/MultipartDataGenerator.js#L8

Both list out parameters in the method signature.

For your suggestion using just `options`, may I know if it's based on some best practices/style guides? 

(this is not to say your suggestion is not good but we need to understand if your suggestion is part of the best practice/style guides adhered by the majority of NodeJS developers)

**Comment by darylteo** [comment]
@wing328  thanks for taking the time to review!

First up I'm not a NodeJS developer. Most of my Javascript work is on the frontend.

I guess the frustration for me at present comes from dealing with this particular api call that supports many different filtering and pagination options (up to 10!). This api is written in Java - JAXRS, and we are using a bytecode analyzer to generate a swagger spec, which then gets converted to the Javascript API that we are distributing to potential customers.

This means we have to minimise any potential API breaks as possible. With the current format of parameterised function calls, we have a problem - because the bytecode analyzer reviews the the parameters in alphabetical order, this means parameters added to the end of the method definition CAN break API parameter order as well as they are added to the swagger spec in that order! This is a NO - I'm reviewing the analyzer at the moment to see if we can get the parameter definition order instead.

Furthermore, with a large degree of optional parameters, this leads to potentially lots of "null" parameters being specified. Without named parameters, it is difficult to identify which parameters are which.

I take inspiration from the [jQuery ajax()](http://api.jquery.com/jquery.ajax/) call. The "data" field simply holds a list of all the appropriate parameters to set in the query string.

>  Data to be sent to the server. It is converted to a query string, if not already a string. It's appended to the url for GET-requests.

Having an object style approach would simplify the api call, increase visibility into what parameters are which, and reduce clutter of nulls for optional parameters. 

To be honest, at this point I don't have a better solution for this. The generator does not support serializing of objects so I can't provide a single argument for filtering (for example). Perhaps we can draw the line and aggregate only optional parameters at the end of the function call as the final parameter.

For example (something simple):

```javascript
api.resourceGet(id, {
  locale: "AU"
});
````

**Comment by wing328** [comment]
Are the filtering and pagination parameters defined as optional? If yes, you should see all optional parameters are represented by "opts" in the method signature, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/api/PetApi.js#L327

**Comment by darylteo** [comment]
*sigh* you're right =) I am tackling a separate issue where all parameters are mandatory with no way to turn them off.

https://github.com/sdaschner/jaxrs-analyzer/issues/55

That's exactly what I was asking, but obviously I jumped the gun a little without testing. I apologise. Closing!
