### ISSUE TITLE
[Python] Bug: test files do not use packageName 

### ISSUE THREAD

**Issue by taxpon** [swagger-api/swagger-codegen#3055]
##### Description
- Python test files generated by codegen do not use `packageName` option.
    - Package name is fixed to `swagger_client`

##### Swagger-codegen version
2.2.0-SNAPSHOT

##### Suggest a Fix
- Fix following files to user `packageName`
    - [api_test.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_test.mustache)
    - [model_test.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/model_test.mustache)

**Comment by wing328** [comment]
Yes we definitely need to fix that and update the `bin/python-petstore.sh` to cover it moving forward.

Please let us know if you've cycle to work on that.

**Comment by taxpon** [comment]
Do you mean we need to update `bin/python-petstore.sh` so that we can confirm that `pacageName` defined in config appears in test files correctly?

**Comment by wing328** [comment]
@taxpon yes but no worry I'll take care of it when I add better CI coverage for Python API client.

**Comment by taxpon** [comment]
@wing328 Oh, I created PR #3061 with `bin/python-petstore.sh` update. Please review it.

**Comment by wing328** [comment]
@taxpon the way you named the package looks good to me 👍
