### ISSUE TITLE
DELETE with no body creates a bad URL

### ISSUE THREAD

**Issue by pambeard** [swagger-api/swagger-codegen#3060]
##### Description

rest.py delivered with 6/2 python client package breaks DELETE with no body.  It works with 5/23 download. 

##### Swagger-codegen version

Code gen from both dates report - SDK Package Version: 1.0.0

##### Swagger declaration file content or url

/reservations/{userId}/{taskId}:
    delete:
      tags:
          - reservation
      description: Delete a `Reservation`
      operationId: deleteReservationTaskId
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - basicAuth: []  
      parameters:
        - name: userId
          in: path
          description: ID of user to fetch
          required: true
          type: string    
        - name: taskId
          in: path
          description: taskID of reservation to delete
          required: true
          type: string
      responses:
        '200':
          description: Reservation deleted
        "400":
          description: Bad request or malformed message
          schema:
            type: string
       

##### Command line used for generation

I am using the swagger editor to generate the python client

##### Steps to reproduce

Generate client after 6/2, replace rest.py and api_client.py with versions from 5/23

##### Suggest a Fix

For DELETE with no body, use the 5/23 version of python client

**Comment by taxpon** [comment]
Is this related to #3020 ? But DELETE codes generated with 6/2 version are working well for my development..

**Comment by pambeard** [comment]
If I go back to the 5/23 version, I able use delete generated from the python client similar to this curl command "curl -k -X DELETE --user myUserId:password --header 'Content-Type: application/json' --header 'Accept: application/json' 'https://xxx.xxx.xxx.xxx/reservations/myuser/fred'"   When doing this in the 6/2 version I get HTTP  "SyntaxError: Unexpected token n<br> &nbsp;"

**Comment by pambeard** [comment]
Sorry, "SyntaxError: Unexpected token 'single line break' "  it is an  open pointy bracket  br close pointy bracket

**Comment by ePaul** [comment]
Just to make clear ... what is the "6/2" or "5/23" version? What the online generator delivered at those dates? (I guess we should somehow make the online generator show which version of swagger-codegen it is using.)

Also, please wrap your YAML into

    ```yaml

and

   ```

so it gets highlighted as YAML (and the indentation is not broken).

**Comment by pambeard** [comment]
Yes, what the online generator delivered at those dates

**Comment by wing328** [comment]
@pambeard editor.swagger.io submits HTTP requests to generator.swagger.io to generate the SDKs.

As confirmed with @fehguy generator.swagger.io is using stable version v2.1.6.

We're working out a plan to push the latest master on a daily/weekly basic or based on PR merged to Swagger Codegen.

**Comment by wing328** [comment]
@pambeard did you have a chance to pull the latest master and build locally to give it another try?

**Comment by wing328** [comment]
Closing this as there's no update.
