### ISSUE TITLE
[swift] how to catch 401 status with current implementation ?

### ISSUE THREAD

**Issue by romk1n** [swagger-api/swagger-codegen#3062]
##### Description

ErroType returned has code of -6003 and description. 

```
FAILURE: Error Domain=com.alamofire.error Code=-6003 "Response status code was unacceptable: 401" UserInfo={NSLocalizedFailureReason=Response status code was unacceptable: 401}
```
##### Swagger-codegen version

2.1.6
##### Swagger declaration file content or url

any request resulting in 401
##### Command line used for generation

n/a
##### Steps to reproduce

Make a request to service without user token. get an error with no response object. how to detect that it is 401 error ?
##### Related issues

n/a

**Comment by wing328** [comment]
cc @Edubits @jaz-ah

**Comment by jaz-ah** [comment]
@romk1n I manually modified AlamofireImplementations.swift to the processRequest function to do this:

....
        request.responseJSON(options: .AllowFragments) { response in
            managerStore.removeValueForKey(managerId)

            // AlamoFire doesn't automatically check status responses for error codes
            // so we do it manually here - also we could call validate() on the AlamoFire
            // request but it doesn't put the status code in the error message
            // which isn't too helpful in the client code
            if request.response?.statusCode >= 400 {
                let error = NSError(domain: (request.response?.URL?.URLString)!, code: (request.response?.statusCode)!, userInfo: nil)
                error.log()
                completion(response: nil, error: error)
                return
            }

This works well and I might integrate it soon into the main branch... but you could try this for now.

**Comment by jgavris** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3343

**Comment by romk1n** [comment]
@jgavris would be great not to explicitly unwrap optional in that code that may crash badly

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/3624
