### ISSUE TITLE
Case mismatch issue in python/configuration.mustache results in wrong auth_settings codegen with oauth

### ISSUE THREAD

**Issue by guangyang** [swagger-api/swagger-codegen#3064]
##### Description

In of lines 222 and 230 file https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/configuration.mustache where it checks oauth or not, there is a case miss match. It should be ``isOAuth`` but right now it's ``isOauth``, which results in wrong ``auth_settings()`` function codegen when the Swagger spec has Oauth security definition.

##### Swagger-codegen version

It's in the master branch right now. Not sure about the history.

##### Swagger declaration file content or url

Any Swagger spec with Oauth security definition will repro this.

##### Command line used for generation

Only happens for python. I did a quick search in all the mustache files and this is the only place.

##### Steps to reproduce

Just check the file. This is an obvious one.

##### Suggest a Fix

Change ``a`` to ``A``.

**Comment by taxpon** [comment]
@wing328 @guangyang I created PR #3066. Please review it.

**Comment by wing328** [comment]
@guangyang thanks for reporting the issue. @taxpon submitted a fix, which has been merged into master.

Please pull the latest master and give it another try.
