### ISSUE TITLE
[Javascript] Return rejected Promise if required parameters are not set

### ISSUE THREAD

**Issue by darylteo** [swagger-api/swagger-codegen#3068]
##### Description

When using the --promise version of javascript, when required parameters are not provided, it throws an exception. To maintain the consistency of the function, it could return a rejected Promise, so that we can simply write a failure handler at the end of the fluent chain.
##### Swagger-codegen version

2.1.6
##### Suggest a Fix

Instead of 

``` javascript
  // verify the required parameter 'count' is set
  if (count == undefined || count == null) {
    throw "Missing the required parameter 'count' when calling resourceGet";
  }
  ...
  try {
    api.resourceGet(...)
      .then(res => {
        ...
      }, err => {
        // error 1
      });
  } catch (e) {
    // error 2
  }
```

Let's do

``` javascript
  // verify the required parameter 'count' is set
  if (count == undefined || count == null) {
    Promise.reject(new Error("Missing the required parameter 'count' when calling resourceGet"));
  }
  ...
  api.resourceGet(...)
    .then(res => {
      ...
    }, err => {
      // error 1
    });
```

**Comment by wing328** [comment]
@darylteo thanks for the suggestion and the code snippets to illustrate the difference.

cc @delenius who added Promise support to the Javascript API client.

**Comment by frol** [comment]
I am looking at that code currently while working on #3654, and this request doesn't make a lot of sense to me. Let's compare the behavior to other languages:

* compiled languages (C++/Java/C#/...) raise compilation error, meaning that the execution doesn't even start
* sane interpreted languages (Python/Ruby/...) raise language-specific runtime errors, meaning that the return value doesn't take any responsibility of taking care of the error with input parameters

IMHO, this issue is invalid.

**Comment by darylteo** [comment]
Happy to go with that! 👍 been so long my entire code base is pretty stable
with that anyway.

Thanks Vlad.

@wing328 feel free to close if you agree.

On Fri, Mar 3, 2017 at 8:46 AM Vlad Frolov <notifications@github.com> wrote:

I am looking at that code currently while working on #3654
<https://github.com/swagger-api/swagger-codegen/issues/3654>, and this
request doesn't make a lot of sense to me. Let's compare the behavior to
other languages:

   - compiled languages (C++/Java/C#/...) raise compilation error, meaning
   that the execution doesn't even start
   - sane interpreted languages (Python/Ruby/...) raise language-specific
   runtime errors, meaning that the return value doesn't take any
   responsibility of taking care of the error with input parameters

IMHO, this issue is invalid.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/swagger-api/swagger-codegen/issues/3068#issuecomment-283792249>,
or mute the thread
