### ISSUE TITLE
Java client erroneous if using okhttp with Response class

### ISSUE THREAD

**Issue by karussell** [swagger-api/swagger-codegen#3071]
##### Description

Creating a java client fails as 
`import com.graphhopper.routeopt.client.model.Response;`

is wrong and clashes with okhttp its Response statement in the generated SolutionApi:
`import com.squareup.okhttp.Response;`

##### Swagger-codegen version

2.1.5 and 2.1.6

##### Swagger declaration file content or url

https://graphhopper.com/api/1/vrp/swagger.json

##### Command line used for generation

```bash
FILE=swagger-codegen-cli-2.1.5.jar
SPEC=https://graphhopper.com/api/1/vrp/swagger.json
LANG=java
DIR=.
PKG="com.graphhopper.routeopt.client"
CONFIG="--api-package $PKG --invoker-package $PKG --model-package $PKG.model"
java -jar $FILE generate -i $SPEC -l $LANG $CONFIG -o $DIR/$LANG
```

##### Suggest a Fix

Either use the explicit "Response" for okhttp or for the model "Response" in SolutionApi or both

**Comment by wing328** [comment]
@karussell thanks for reporting the issue.

I would go for fully-qualified name `com.squareup.okhttp.Response`. May I know if you've cycle to contribute a fix on this?

**Comment by karussell** [comment]
Yes, will try :)
