### ISSUE TITLE
Javadoc creation failed making central maven release hard

### ISSUE THREAD

**Issue by karussell** [swagger-api/swagger-codegen#3074]
When I try to release the autogenerated files of the java client (library 'okhttp-gson') to maven central it triggers `mvn javadoc:javadoc` and this fails with lots of errors 

```
[ERROR] dir/src/main/java/com/graphhopper/routeopt/client/ApiClient.java:965: warning: no @param for formParams
[ERROR] public RequestBody buildRequestBodyMultipart(Map<String, Object> formParams) {
[ERROR] ^
[ERROR] dir/src/main/java/com/graphhopper/routeopt/client/ApiClient.java:965: warning: no @return
[ERROR] public RequestBody buildRequestBodyMultipart(Map<String, Object> formParams) {
```

as in Java 8 this is a lot stricter than before. See this [SO question](http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete) for more details and a workaround but I would like to have this fixed in swagger codegen.

See #3071 for the (same) setup.

**Comment by wing328** [comment]
@karussell agree that it's an issue that we need to address in order for the Java SDK to be released to Maven Central.

**Comment by wing328** [comment]
@karussell I've merged #3077 into master. Please pull the latest and give it a try.

**Comment by karussell** [comment]
I cannot test the master branch as I get the following error (although it build the client jar successfully)

> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (gradle-test) on project directions-api-java-client-route-opt: Command execution failed. Cannot run program "gradle" (in directory "/somedir/client"): error=2, No such file or directory -> [Help 1]

Also I did not find an issue indicating that this is my fault somehow :) ?

**Comment by wing328** [comment]
Did you run `mvn clean package` or something else?

**Comment by karussell** [comment]
I get this error when I try a deployment via `mvn -DperformRelease=true -DskipTests=true -Dpgp.secretkey=keyring:id=54EA4B68 clean compile package deploy`

... but probably I just need to tweak the pom for my purposes? As currently I see `For testing build.gradle, build.sbt, mvn javadoc:javadoc`

Also why now our `Break` model class is named `ModelBreak`? (this breaks backward compatibility)

**Comment by wing328** [comment]
For pom issue, I've filed #3095 to fix it.

For break, it's a keyword in Java so we escape it with `ModelBreak`

**Comment by karussell** [comment]
> For break, it's a keyword in Java so we escape it with ModelBreak

But it is upper case and worked before or what was the issue?

**Comment by wing328** [comment]
Your point is definitely valid.

The logic for Java API client is here: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L63-L79.

To fix it for Java, we probably need another method `setReservedWords` to set the reserved key words as it's and override `isReservedWord` to make a case sensitive comparison in Java code generator.

Please let me know if you've cycle to contribute the enhancement.
