### ISSUE TITLE
Please set scalaVersion := "x" in build.sbt and run ./sbt assembly

### ISSUE THREAD

**Issue by Rogercf** [swagger-api/swagger-codegen#308]
I'm using Ubuntu 14.04 and trying the release 2.0.17 of the swagger codegen

I tried with multiple versions of Scala (2.11.2, 2.11.1, 2.9.1.final, 2.10.4) but I always get the same message when trying to run "./bin/scala-petstore.sh":

Please set scalaVersion := "x" in build.sbt and run ./sbt assembly

Where "x" is the current version of Scala I'm trying

What I did:
export SCALA_HOME={my_scala_home}
export PATH=$PATH:$SCALA_HOME/bin
(Then I edited build.sbt and set the "scalaVersion" to the current version of Scala I'm trying)
./sbt assembly
./bin/scala-petstore.sh

I think I did all right installing Scala because after testing each version I ran "scala -version" and the output was like (for each version I tried, the output returned the right version):

"Scala code runner version 2.10.4 -- Copyright 2002-2013, LAMP/EPFL"

Did I miss something or is it really a bug?

I'm not used to Scala, so I'm sorry if I did a dumb mistake or something...

**Comment by everett-toews** [comment]
Worked for me by updating `scalaVersion` to the entire Scala version in build.sbt

-scalaVersion := "2.10.4"
+scalaVersion := "2.11.5"

**Comment by allenh** [comment]
I know this is old but what everett-toews did worked for me. The following is where my build.sbt changed:

Scala Version:
```
crossScalaVersions := Seq("2.10.4", "2.11.0", "2.11.1", "2.11.7")

scalaVersion := "2.11.7"  \\ the full Scala version
```

Assembly Settings (bottom of the file):
```
assemblySettings

jarName in assembly := "swagger-codegen.jar"
```

I am also using Java 8 (jdk1.8) while running `./sbt assembly`
