### ISSUE TITLE
Missing header in typescript-angular2

### ISSUE THREAD

**Issue by sebastianhaas** [swagger-api/swagger-codegen#3081]
##### Description
`typescript-angular2` doesn't set `Content-Type` and `Accept` in the Header which might cause problems on some servers. In my case, I wasn't able to POST data to a LoopBack (Express) backend.

##### Swagger-codegen version

Latest master, baed578010332a020d3d722dce6cb5f62b862d98

##### Generated code
The generated API class currently sends an empty header:
```typescript
public defaultHeaders : Headers = new Headers();
```

##### Command line used for generation
`java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)`

##### Steps to reproduce
Just look it up in the generated sample
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-angular2/default/api/PetApi.ts

##### Suggest a Fix
I think we want to set `application/json` as default for all requests:
```typescript
    public defaultHeaders : Headers = new Headers({
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    });
```
Fixed the problem in my case. I opened a PR with that two additional lines of code.

**Comment by wing328** [comment]
Have you set a proper `consumes` and `produces` in the spec for the endpoints?

e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L37

**Comment by sebastianhaas** [comment]
My spec does specify proper `consumes` and `produces`:

```json
"host": "localhost:3000",
"basePath": "/api",
"schemes": ["http"],
"consumes": ["application/json", "application/x-www-form-urlencoded", "application/xml", "text/xml"],
"produces": ["application/json", "application/xml", "text/xml", "application/javascript", "text/javascript"],
```

I can't see any efforts made in the respective `.java` and `.mustache.` source to take these into account anyway.
I also do not think that any other content type than json would work for current solution. It is using `JSON.stringify()` to pass the body to Angular2's `Http` class.

https://angular.io/docs/ts/latest/api/http/Http-class.html

**Comment by wing328** [comment]
@sebastianhaas thanks for sharing more. For other API clients (e.g. C#), we've a function to select the property content-type and accepts: 

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/ApiClient.cs#L351
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/ApiClient.cs#L369

These functions are called by endpoint methods:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/PetApi.cs#L523
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Api/PetApi.cs#L530

I wonder if you can implement something similar.

(If my memory serves me well, setting a default may cause issue to some backend/sever framework that does not expect accepts based on the endpoint setting)

**Comment by wing328** [comment]
cc @Vrolijkx

**Comment by sebastianhaas** [comment]
@wing328 I see, that's certainly the way to go for the angular2 client as well. Would you be interested in a PR? I might find some time to get it done.

**Comment by wing328** [comment]
Thanks @sebastianhaas. A PR would be good.

**Comment by wing328** [comment]
@sebastianhaas do you need any help with the PR for better support of `produces` and `consumes` in typescript client?

**Comment by Vrolijkx** [comment]
In my opinion we should only support ```application/json``` otherwise we give the impression we also support other content types. But in the end we only support json.

**Comment by wing328** [comment]
For 'produces', we should support binary (e.g. jpeg file) as well.

For 'consumes', we also support `application/x-www-form-urlencoded` (https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L190)

**Comment by sebastianhaas** [comment]
I was just about to write the fix you suggested, but now I think I have to step back from this. I tend to agree with @Vrolijkx that supporting `application/json` is probably enough in this case. Both accepting `application/xml` or sending as `application/x-www-form-urlencoded` doesn't feel right (in the context of angular) to me.

It would take a lot of extra effort to handle anything different but json requests, and I don't see a point in doing so when json is already the native format in the codegen target language?

Supporting binary data is a different thing however, but I took a look at the related codegens like ng1, ng2, JS and Nodejs where none of them seems to support binary at the moment. I'm not saying this is something that isn't required after all but its probably out of scope for this specific issue?

A feasible solution might be to omit non-json endpoints for now, just like in [1], and always 
request for `application/json`. Then you could maybe accept the PR, we have a running solution for most cases now and I will come back to this in a month or so and try to provide a solution for binary endpoints. I'm gonna need that anyway later this summer, but it really requires some additional testing and thinking.


[1] https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java#L196

**Comment by sebastianhaas** [comment]
Obviously. I was just wondering if that is likely to be a common use-case. :)

**Comment by wing328** [comment]
@sebastianhaas I do not have any figure to tell if using form parameters is a common case or not.

I've definitely seen endpoints for authentication using form parameters to pass the username and password.

**Comment by wing328** [comment]
PR merged.
