### ISSUE TITLE
Swagger spec date format not supported by Java client

### ISSUE THREAD

**Issue by tadhgpearson** [swagger-api/swagger-codegen#3087]
##### Description

The generated Java client does not correctly parse the Swagger date format from API responses.

According to the[ swagger spec](http://swagger.io/specification/) a response field of type string, format date must return a full-date defined by [RFC 3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) which specifies the format as 

>    full-date       = date-fullyear "-" date-month "-" date-mday

This is not supported by the default Java client, which generates using a single date format, used for both date and date-time which is

>     DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");

This means simple date fields are not supported and cause the client to throw an InvalidFormatException during the parsing of a response model which contains Date fields..

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url
Source swagger file is https://github.com/amadeus-travel-innovation-sandbox/sandbox-content/blob/master/swagger.yml

##### Command line used for generation
java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i https://raw.githubusercontent.com/amadeus-travel-innovation-sandbox/sandbox-content/master/swagger.yml -l java -o /java-client

##### Steps to reproduce
1. Build java client using above command
2. Register on sandbox.amadeus.com and create a new app to get an API key
2. Create a new unit test using the java client to invoke our hotel API to demonstrate the bug, like so:
```

	private static final String APIKEY = "YOUR_API_KEY_HERE";
	private static final DefaultApi API = new DefaultApi();
	private static final DateTimeFormatter DATE = ISODateTimeFormat.date();

	@Test
	public void testHotelAirportSearch() throws ApiException {
		LocalDate checkIn = new LocalDate().plusWeeks(6);
		LocalDate checkOut = checkIn.plusDays(1);
		HotelSearchResponse hotelSearchRS = API.hotelAirportSearch(APIKEY, "BOS", DATE.print(checkIn), DATE.print(checkOut), 25, "EN", "USD", null, null, 3, false, false, null);
		assertEquals("US", hotelSearchRS.getResults().get(0).getAddress().getCountry()); 
		assertEquals(checkIn, hotelSearchRS.getResults().get(0).getRooms().get(0).getRates().get(0).getStartDate());
	}
```

##### Related issues
No noted related issues

##### Suggest a Fix
There are two good approaches to this.
Either define a date and a dateTime formatter, and use them appropriately, or define a looser date parser for all API responses that can handle any valid ISO Date/Time

**Comment by cbornet** [comment]
The best way is to use joda date lib (or JSR310 on java8).
It has been implemented on feign and retrofit clients.
When all java clients are done, we will be able to switch the default date lib to joda.

**Comment by cbornet** [comment]
Actually the default(jersey) and jersey2 libs also have joda support

**Comment by tadhgpearson** [comment]
Sure. I prefer Joda too, or even Java 8, and I'd be happy if you'd make it the default.
But this is the default option right now and it's broken. If you agree it's an issue, and you have a preferred approach to fixing it, I'd be happy to do a fix and provide a pull request.

**Comment by cbornet** [comment]
In the end it will be the default.
For now you can use -DdateLibrary=joda

**Comment by tadhgpearson** [comment]
Sure... but I also need it to work with the default option

**Comment by wing328** [comment]
@tadhgpearson yes, editor.swagger.io only uses the default option. Please pull the latest master to generate the SDK instead: https://github.com/swagger-api/swagger-codegen#getting-started (there are more than 120+ enhancements,bug fixes since v2.1.6 release)

**Comment by tadhgpearson** [comment]
Thanks for the clarification @wing328  
Yes, I am using the latest master, and the issue still exists in it. I didn't realize that this wasn't the same as v2.1.6, sorry about that.

**Comment by wing328** [comment]
When generating the Java client, did you use `-DdateLibrary=joda` as suggested by @cbornet ?

Which Java HTTP library did you use? default, jersey2, okhttp-gson, etc?

**Comment by tadhgpearson** [comment]
I'm using the default HTTP library.
Seeing the resolution, does this mean that support for [java.util.Date](http://classicprogrammerpaintings.com/post/142649999919/javautildate-salvador-dali-oil-on-canvas-1931) has been removed?

**Comment by cbornet** [comment]
You can still use it with -DdateLibrary=legacy but I encourage you to use joda if you can.

**Comment by tadhgpearson** [comment]
LOL - no encouragement needed!
