### ISSUE TITLE
mvn install fail with okhttp-gson

### ISSUE THREAD

**Issue by TranAn** [swagger-api/swagger-codegen#3092]
##### Description

After generating Android client lib with okhttp-gson. I build it with **mvn package** and it work fine, but when i try install it **mvn install** i get this error:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (g
radle-test) on project swagger-java-client: Command execution failed. Cannot run
 program "gradle" (in directory "C:\My_Data\Project\JavaTest_Project\JavaSpring_
WebService\swagger-codegen\samples\client\springboot\okhttp-gson"): CreateProces
s error=2, The system cannot find the file specified -> [Help 1]
```

so i have to remove exec-maven-plugin from pom file and then it work.

##### Swagger-codegen version

in commit ae3a31fb7930cbfaef9b100e1da0693b1317bdc8

**Comment by wing328** [comment]
Do you have gradle installed?

**Comment by TranAn** [comment]
@wing328 Sorry i haven't install gradle, but i don't see gradle is requirement in anywhere.

**Comment by wing328** [comment]
I'll review the pom.xml as well

Given that android studio treats gradle as first class citizen and many Android SDK that I used also rely on gradle for installation, I would strongly recommend you to install it.

**Comment by wing328** [comment]
Which folder did you run the `mvn install` command?

**Comment by TranAn** [comment]
This is destination folder where swagger-codegen generate the library:

`-o samples/client/springboot/okhttp-gson`

of course i run in it :dancer:

**Comment by wing328** [comment]
I found the problem and will file a PR to fix it shortly.

**Comment by wing328** [comment]
@TranAn I've filed #3095 to fix the issue. Thanks again for reporting the issue.

**Comment by wing328** [comment]
@TranAn PR merged into master. Please pull the latest to give it a try.

**Comment by TranAn** [comment]
@wing328 ok, thank you for your quick reply.
