### ISSUE TITLE
Angular 1: Required parameter check causes unexpected behaviour

### ISSUE THREAD

**Issue by moanrose** [swagger-api/swagger-codegen#3096]
The required parameter check in the api.mustache causes unexpected behaviour if the actual parameter value evaluates to false e.g "false", 0, -1, false

swagger-codegen/modules/swagger-codegen/src/main/resources/typescript-angular/api.mustache

The code

if (!{{paramName}}) {
	throw new Error('Missing required parameter {{paramName}} when calling {{nickname}}');
}

Needs to be changed to:

if ({{paramName}} === undefined || {{paramName}} === null) {
	throw new Error('Missing required parameter {{paramName}} when calling {{nickname}}');
}

I can make a pull request myself, but i do not have the necessary permissions to create a branch - should i make the change on a separate fork?

**Comment by wing328** [comment]
@moanrose thanks for the suggestion.

Yes, agree that we should reuse the same check in `typescript-node` to validate required parameter: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L200-L205

May I know if you've cycle to contribute a fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
`typescript-angular2` needs similar fix: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L44-L51

**Comment by wing328** [comment]
@moanrose thanks for the PR, which improves both typescript-angular1 and typescript-angular2
