### ISSUE TITLE
JSON response element are missing '_' 

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#3104]
_From @ksriharish on May 12, 2016 9:54_

The swagger codegen is removing the '_' in the json elements. I am generating the code using swagger-codegen 2.1.6 jar. Is this fixed or planned for future? If it is fixed which version is this working?

_Copied from original issue: swagger-api/swagger-ui#2153_

**Comment by wing328** [comment]
@ksriharish please share more, e.g. which language, swaggers spec, steps to reproduce,

**Comment by wing328** [comment]
Closing this as there's no update.
