### ISSUE TITLE
[typescript-angular2] Handle date type correctly

### ISSUE THREAD

**Issue by taxpon** [swagger-api/swagger-codegen#3105]
##### Description
- As mentioned in #2776, typescript clients do not handle date type correctly.
- I think api clients should convert ISO8601 string into Date object when receiving request, convert Date object into ISO8601 string when sending request.
##### Swagger-codegen version

2.2.0-SNAPSHOT
##### Related issues
#2776, #2030
##### Suggest a Fix

I am thinking updating of `api.mustache` of typescript-angular2. If it's ok, I'll create PR.

**Comment by wing328** [comment]
@taxpon yes, the typescript-angular2 client still needs some work and proper date/datetime handling is one of them. It would be great if you can contribute the enhancement with a PR.

**Comment by moanrose** [comment]
I would suggest that the desiralization of date are not handled by swagger codegen, I am sure that Angular 2 has a extensibility point for deserializing similar to Angular 1 see #2776

**Comment by wing328** [comment]
@moanrose thanks for the suggestion. For other langauges (e.g. C#, Java, Ruby, Python, etc), the auto-generated SDK handles the deserialization of string back into datetime object in the language automatically so doing the same in Angular 1or 2 API client will make the developer experience more consistent.

If it's more common for Angular 1 or 2 developers to handle the deserialization in their own program, then one workaround I can think of is to document the datetime string as `type: string` in the OpenAPI/Swagger spec instead.

**Comment by gregjacobs** [comment]
(Copy/pasted from #2776)

@moanrose I agree with @wing328 that the deserialization should happen as part of the generated code.

The article you linked to simply provides one option for a place to deserialize date objects in Angular code, but it doesn't necessarily mean that it's the "proper" place to deserialize date objects. In fact, from a software engineering perspective, I would argue that `$httpProvider.defaults.transformResponse` is not a good place to put this sort of transformation, as it is tying your code specifically to the Angular 1 framework. This makes upgrading your code to Angular 2, or switching frameworks in general more difficult.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/4264 in 2.3.0 branch

**Comment by kimamula** [comment]
I want to note that #4264 only fixed the behavior of typescript-node.
For typescript-angular, the issue still remains to be solved.

**Comment by mixer2** [comment]
@wing328 is it possible to reopen this issue, since, as @kimamula already mentioned, #4264 didn't cover it?
