### ISSUE TITLE
[Swift] auto ganerated enum var name issue.

### ISSUE THREAD

**Issue by KingShashi** [swagger-api/swagger-codegen#3118]
##### Description : 
The Swagger Codegen does not create enums properly. The case names contains the characters like [ , ]  i.e. braces. 

Also "**repeat**" is keyword in Swift, if I add repeat to reservedWords in SwfitCodegen.java then it does't affect the code. Is it correct way to add keywords?

##### Swagger declaration file content or url
Look at the following auto generated code
```yaml
 public enum SortOrder_getLanguages: String { 
        case [ascending = "[ascending"
        case Descending] = "descending]"
    }    
```

**Comment by wing328** [comment]
@KingShashi thanks for reporting the issue.

What should be the correct name looks like for `[ascending` and `Descending]`? Are you aware of any naming convention for Swift enum?

cc @Edubits @jaz-ah

**Comment by KingShashi** [comment]
In this case, It should not contain the [ & ].

**Comment by Edubits** [comment]
@KingShashi Could you attach the relevant part of the swagger.json?

> Also "repeat" is keyword in Swift, if I add repeat to reservedWords in SwfitCodegen.java then it does't affect the code. Is it correct way to add keywords?
That's sounds like the way to do it.

**Comment by KingShashi** [comment]
"tags": ["Languages"],
				"summary": "Get the list of supported languages.",
				"description": "",
				"operationId": "getLanguages",
				"produces": ["application/json"],
				"parameters": [{
					"name": "sortOrder",
					"in": "query",
					"description": "Ascending or descending sort order",
					"required": false,
					"type": "string",
					"default": "ASC",
					"enum": ["ascending", "descending"]
				}],

**Comment by Edubits** [comment]
@KingShashi Thanks, I tried your snippet and generated the Swift code, for me it results in:
`public enum SortOrder_getLanguages: String { 
        case Ascending = "ascending"
        case Descending = "descending"
    }`

With which version of swagger-codegen did you test? Could you try it with the latest master?

**Comment by wing328** [comment]
@KingShashi please pull the latest master and give it a try.

Closing the issue for now.

**Comment by shashi34** [comment]
Yes the issue has been resolved.

**Comment by Edubits** [comment]
@shashi34 good to hear, thanks for confirming!
