### ISSUE TITLE
[All] Hard Coding Api Key value in header when using a Swagger Generated Client

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#3121]
##### Description

In Swagger Client Generator's page I have found this model that permit to set up the clients options but I cannot find how (and if) the API key can be hard coded (or any other kind of authorization) in the client code.

```
GeneratorInput {
    spec (object, optional),
    options (object, optional),
    swaggerUrl (string, optional),
    authorizationValue (AuthorizationValue, optional),
    securityDefinition (SecuritySchemeDefinition, optional)
}
AuthorizationValue {
    value (string, optional),
    type (string, optional),
    keyName (string, optional)
}
SecuritySchemeDefinition {
    description (string, optional),
    type (string, optional)
}
```

##### Swagger-codegen version

2.1.6 (current stable)

##### Suggest a Fix

I suppose I must set AuthorizationValue object but there is no documentation about that (or I can not find it).

Anyone has an idea ?

**Comment by wing328** [comment]
Usually the API client comes with a method `addDefaultHeader` to add HTTP header in the request. Would that meet your requirement?

**Comment by lunat** [comment]
I was using that method in my generated client to add ApyKey in Header.

Than later, after putting this property in my main swagger.json:

`"securityDefinitions":{"myWakesAuth":{"type":"apiKey","description":"MyWakes Application Id","name":"X-MyWakes-Application-Id","in":"header"}}`

I can initialize the `Configuration `object by setting directly the ApiKey.

But, what I want is different.
I am making my API available for third party developers and I would like that any one wants to generate his own client in any supported languange, he could specify his own ApiKey and then that ApiKay will be Hard Coded in the just created client.

I hope I was clear...

Many Thanks

**Comment by wing328** [comment]
The spec does not support hard-coded API key but you can use vendor extension and customize the template accordingly: https://github.com/swagger-api/swagger-codegen/wiki/Vendor-Extensions (doing a search of those listed vendor extension will show you the usage in the template)

I wouldn't recommend you hard-coding the API key in the auto-generated SDK as I don't think that conforms to security best practice.

**Comment by lunat** [comment]
Many thanks ! 

I will sure take a look at that page.

By the way, the page https://generator.swagger.io/ that contains the 
`POST /gen/clients/{language} ` endpoint
contains that BODY definition:
```
{
  "spec": {},
  "options": {},
  "swaggerUrl": "http://petstore.swagger.io/v2/swagger.json",
  "authorizationValue": {
    "value": "string",
    "type": "string",
    "keyName": "string"
  },
  "securityDefinition": {
    "type": "string",
    "description": "string"
  }
}
```
do you know if there is any documentation about these fields ?

**Comment by cbornet** [comment]
The best place to put the documentation about these fields would be the https://generator.swagger.io/api/swagger.json itself :smile:

**Comment by wing328** [comment]
@lunat please see https://github.com/swagger-api/swagger-codegen#online-generators

**Comment by lunat** [comment]
@wing328 thank you but the missing documentation is at
https://generator.swagger.io
clients
POST
