### ISSUE TITLE
[Scala] Generator for Finch

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3132]
##### Description

If anyone wants to work on a Scala server generator for [Finch](https://github.com/finagle/finch), please reply to let us know.

**Comment by jimschubert** [comment]
@wing328 also, Finch's maintainer created https://github.com/finagle/finch-petstore, should be a matter of converting that to a generator.

**Comment by wing328** [comment]
@jimschubert that would be a very good starting point to starting the reverse engineering

**Comment by zcfrank1st** [comment]
👍

**Comment by wing328** [comment]
Here is a good starting point: https://github.com/swagger-api/swagger-codegen/wiki/How-to-add-a-generator-for-a-new-language-or-framework

**Comment by tomjadams** [comment]
There are a couple of other examples here too: https://github.com/tomjadams/finch/blob/master/docs/best-practices.md#pulling-it-all-together

**Comment by clasnake** [comment]
@wing328 I'll work on this one for the Finch generator.

**Comment by vkostyukov** [comment]
It's really awesome to see how much support this ticket got!

Thanks a lot @clasnake for taking a stub on this! https://github.com/finagle/finch/issues/73 is our oldest ticket that's still open.

**Comment by daviddenton** [comment]
There's a swagger code generator in fintrospect that you can convert the implementation of...  it's pretty simple TBH. One of the more interesting bits is if you want to support generation of JSON schema models for using in the Swagger UI.

https://github.com/daviddenton/fintrospect/blob/master/core/src/main/scala/io/fintrospect/renderers/swagger2dot0/Swagger2dot0Json.scala

**Comment by andreaTP** [comment]
It should be trivial to extend https://github.com/unicredit/sbt-swagger-codegen to supporto Finch. It looks like a task for @mfirry :-P

**Comment by wing328** [comment]
I believe @clasnake is busy with work so I'll give it a try this weekend and hopefully release a beta version.

**Comment by clasnake** [comment]
@wing328 Yup that'd be great. Thanks very much.

**Comment by devshorts** [comment]
Any progress on this? @wing328 If you are blocked I can probably try helping

**Comment by wing328** [comment]
@devshorts thanks for offering help. I'll push what I've done so far by tomorrow...

**Comment by wing328** [comment]
Dear all,

I've submitted https://github.com/swagger-api/swagger-codegen/pull/3905, which is still work in progress.

Please review and help fix the remaining issue/error.

Thanks.

**Comment by wing328** [comment]
Hi all,

Thanks for the contribution from @jimschubert. We now have the first release of the Finch generator.

Please pull the latest master to give it a try and let us know if you've any feedback.

Best regards,
William

**Comment by wing328** [comment]
Tweet: https://twitter.com/wing328/status/825564638393704448

Please help retweet to promote the new server generator to other developers.
