### ISSUE TITLE
aspnet5 generator ignores sourceFolder option

### ISSUE THREAD

**Issue by debben** [swagger-api/swagger-codegen#3137]
##### Description

When using the aspnet5 generator, the sourceFolder option is ignored an the source folder is always set to src/IO.Swagger.

##### Swagger-codegen version

Latest master (b782dc017803b8dbc82e9059447d1888bce89c40)

##### Steps to reproduce

Run the aspnet5 generator with the option "-DsourceFolder=..." or in the configuration json given to the command. The path given to the sourceFolder option is ignored and the resulting output will always have a directory structure with the default path of "src/IO.Swagger".

##### Suggested Fix
The culprit looks to be the redefinition of the protected string sourceFolder in AspNet5ServerCodegen.java. This hides the previous definition of sourceFolder AbstractCSharpCodegen.java. Moving the initialization of sourceFolder to the constructor of the AspNet5ServerCodegen class seems to resolve the issue for me.

**Comment by wing328** [comment]
@debben thanks for reporting the issue. May I know if you've cycle to contribute a fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by jimschubert** [comment]
@wing328 @debben ignoring the `sourceFolder` option was the intention. Please see my comment in the referenced PR (#3160)
