### ISSUE TITLE
[Jaxrs] Missing Import in Generated Model for Map<String, List<T>>

### ISSUE THREAD

**Issue by qtstc** [swagger-api/swagger-codegen#3140]
##### Description

I was trying to add this property
```
        "projections": {
          "type": "string",
          "additionalProperties": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
```
In the generated model class, the `import java.math.BigDecimal;` is missing.
##### Swagger-codegen version
Happens on 2.16 and current master build.
##### Command line used for generation
`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.json -l jaxrs`

**Comment by wing328** [comment]
PR merged. Issue closed.

Thanks again for the PR from @qtstc
