### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/Consts

### ISSUE THREAD

**Issue by tamirtf** [swagger-api/swagger-codegen#3141]
##### Description

I generated SDK of Android language which is packaged as AAR. 
The Android application is compiled with the AAR.

However, in run time, it gets the following exception:
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/Consts;
at io.swagger.client.ApiInvoker.<clinit>(ApiInvoker.java:55)

It could be solved by adding the following line to application's build.gradle:
compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'

I wonder why the user should add any line to build.gradle, except the line of generated artifact (SDK),  instead of used libraries (JARs) would be part in the AAR.

##### Swagger-codegen version

The version is 2.2.0-SNAPSHOT, it's not a regression.
##### Swagger declaration file content or url
It happens with any swagger declaration file, it's not related to a specific file.

##### Command line used for generation
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i example.yaml -l android -o androidApis

##### Steps to reproduce
1. 'mvn clean install' to the generated project.

2. Add to build.gradle:
compile group: 'io.swagger',
            name: 'swagger-android-client',
            version: '1.0.0',
            ext: 'jar'

3. Use in an Android application:
CarApi apiCar = new CarApi();

4. Run the application.

**Comment by wing328** [comment]
@tamirtf there should be no need to manually add another line in build.gradle in order to make the Android SDK works. I'm looking into it.

You can also want to try the Java (okhttp-gson) API client, which works with Java, Android, Scala, etc: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#android

**Comment by wing328** [comment]
@tamirtf Here are some update.

I'm able to repeat similar issue (error message: `Multiple dex files define Lorg/apache/http/Consts;`) with `compile 'io.swagger:swagger-android-client:1.0.0` but not the following:
```
compile group: 'io.swagger',
name: 'swagger-android-client',
version: '1.0.0',
ext: 'jar'
```
(which means the compile group option fixes the issue for me)

I got other errors such as duplicated files copied and I could resolve those using packagingOptions -> exclude

To be clear, I didn't add `compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'`

Here is a screen cap showing my build.grade and message confirming the APK build is successful.
 
<img width="880" alt="screen shot 2016-06-16 at 1 00 33 am" src="https://cloud.githubusercontent.com/assets/934260/16089462/ca897996-335d-11e6-9ebe-19c2d42b2449.png">

**Comment by wing328** [comment]
And btw, https://github.com/mcxiaoke/android-volley was deprecated a few months ago.

**Comment by cbornet** [comment]
I think only the mirror is deprecated and now we should use com.android.volley:volley:1.0.0

**Comment by wing328** [comment]
@cbornet you're right. The official one is still (kinda) active: https://android.googlesource.com/platform/frameworks/volley. Last update was 3 months ago.

I saw you already created a task to track the update to use the official one instead 👍

**Comment by tamirtf** [comment]
Hello,
I'm able to solve the issue only if I add to build.gradle the following:

apply plugin: 'maven-publish'

publishing {
    publications {
        bar(MavenPublication) {
            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')
                configurations.compile.allDependencies.each {
                    def dependencyNode = dependenciesNode.appendNode('dependency')
                    dependencyNode.appendNode('groupId', it.group)
                    dependencyNode.appendNode('artifactId', it.name)
                    dependencyNode.appendNode('version', it.version)
                }
            }
            
            groupId 'io.swagger'
            artifactId 'swagger-android-client'
            version '1.0.0'
        }
    }
    repositories {
        mavenLocal()
    }
}

It adds to swagger-android-client-1.0.0.pom all the dependencies.

Do you know whether another reasons might cause to the original issue?

**Comment by wing328** [comment]
@tamirtf what IDE are you using? Android studio 2.0?

Did you try the Java (okhttp-gson or retrofit2) API client to see if you get similar issue?

(i'm assuming you're using the latest master of swagger codegen)

**Comment by tamirtf** [comment]
I use Android Studio 2.0 and the latest master of swagger codegen.
I use the latest master of swagger codegen.
I tried with okhttp-gson and I did not have the issue.

**Comment by wing328** [comment]
@tamirtf I've filed https://github.com/swagger-api/swagger-codegen/pull/3219 to add dependency `httpclient-android`

**Comment by wing328** [comment]
@tamirtf  #3219 merged into master. Please pull the latest and give it a try.
