### ISSUE TITLE
[JavaScript] exception when setting type string on an enum

### ISSUE THREAD

**Issue by diegode** [swagger-api/swagger-codegen#3143]
##### Description

On the valid yaml file below, the code generation for javascript is failing (but not for java, for instance).
This was the minimal example I could make where the bug appears.

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

```yaml
  ---
  swagger: "2.0"
  info:
    version: "0.1.0"
    title: test
  host: example.com
  paths:
    type: object
  definitions:
    foo:
      type: object
      discriminator: baz
      properties:
        baz:
          type: string
          enum:
          - a
          - b
      required:
      - baz
    bar:
      type: object
      allOf:
      - $ref: '#/definitions/foo'
      - type: object
```

##### Command line used for generation

swagger-codegen generate -i {yaml file} -l javascript -o {output dir}

##### Steps to reproduce

1. Running the above command line, it will throw an exception.
2. If you remove the "type: string" line, it works fine.
3. It works too replacing -l javascript with -l java.

**Comment by wing328** [comment]
@diegode can you please also show the stack trace for the exception you got?

**Comment by diegode** [comment]
@wing328 sure, this is:
`[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yaml
Exception in thread "main" java.lang.RuntimeException: Could not process model 'bar'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:244)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:919)
	at io.swagger.codegen.languages.JavascriptClientCodegen.fromModel(JavascriptClientCodegen.java:674)
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:901)
	at io.swagger.codegen.languages.JavascriptClientCodegen.fromModel(JavascriptClientCodegen.java:678)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:799)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:237)
	... 2 more
`

**Comment by gtrevg** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (210/200 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:50946 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bE6vH-0007HP-Eo
	for github@trevorgattis.com; Sat, 18 Jun 2016 03:27:51 +0000
Date: Thu, 16 Jun 2016 08:10:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466089809;
	bh=YwgfrJdnxIhZIv3qL47Anxw2AnbJlJRhvPPTngzRrPg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=YuYvvRcrAF+iSTmK5tVSoFwlQ30vO+3BE9AoPNm1TM8CjSh7i3UZDl2FXNBXbYgtY
	 YcEKlAGevgdycqMiZZk8DGHz4W+q+1n5cwqUhbboIAKdq2/iJ2zGtp0jbjzoesUwbq
	 8Njnhnm6x0zJIpMlzRBM9PwcFBi1VncWbuOl8D8Y=

**Comment by wing328** [comment]
I couldn't repeat the issue with the latest master:
```
swagger-codegen|bug/issue3143⚡ ⇒  java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
>   -i  /var/tmp/npe.yaml \
>   -l javascript \
>   -o /var/tmp/javascript/npe/
[main] INFO io.swagger.parser.Swagger20Parser - reading from /var/tmp/npe.yaml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/src/model/Bar.js
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/test/model//Bar.spec.js
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/docs//Bar.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/src/model/Foo.js
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/test/model//Foo.spec.js
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/docs//Foo.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/package.json
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/src/index.js
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/src/ApiClient.js
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/git_push.sh
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/README.md
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /var/tmp/javascript/npe/mocha.opts
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /var/tmp/javascript/npe/.travis.yml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/.swagger-codegen-ignore
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/javascript/npe/LICENSE
```

Please pull the latest master to give it a try.

**Comment by diegode** [comment]
@wing328 great! git-bisecting I found that this commit fixed it: https://github.com/swagger-api/swagger-codegen/commit/7dfddd449ddc2ae8e7e35b6d5ab7fc10e52bc93d
Thanks!

**Comment by wing328** [comment]
@diegode thanks for the confirmation. Issue closed.
