### ISSUE TITLE
[Android][volley] Use com.android.volley:volley:1.0.0

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#3144]
The mirror we currently use is deprecated.
And the AOSP released com.android.volley:volley:1.0.0 on bintray so we can use the official now.

**Comment by wing328** [comment]
If anyone wants to work on this, please reply to let us know.

**Comment by wing328** [comment]
Thanks for the PR https://github.com/swagger-api/swagger-codegen/pull/3766 from @Richou to update the dependency.
