### ISSUE TITLE
[ASPNET5] code generation using multiple swagger specs

### ISSUE THREAD

**Issue by zalak1612** [swagger-api/swagger-codegen#3145]
Is it possible to generate one server side code using multiple swagger specification file?

Also, is it a good design practice to have multiple swagger specification file for a single project?

**Comment by fehguy** [comment]
Yes, you can use JSON Pointers to reference objects in different locations.  Please see the [OAI](https://github.com/OAI/OpenAPI-Specification) repository for more information

**Comment by zalak1612** [comment]
I could not find any documentation indicating code generation using multiple swagger specification file. 
For example, If I have three spec file for petStore (PetStore1.json, PetStore2.json, PetStore3.json)
Can I generate a single code base using 3 specification file?
If yes: Could you please point me to appropriate documentation?

Ex:
 ```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
_-i modules/swagger-codegen/src/test/resources/2_0/petstore1.json  
-i modules/swagger-codegen/src/test/resources/2_0/petstore2.json 
-i modules/swagger-codegen/src/test/resources/2_0/petstore3.json_
-l perl \**
 --git-user-id "wing328" \
 --git-repo-id "petstore-perl" \
 --release-note "Github integration demo" \
 -o /var/tmp/perl/petstore
```

**Comment by fehguy** [comment]
See the specification here:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

Any place that references `JSON Pointer` allows for a reference to an external swagger definition.  Note, they are only allowed in specific locations.  You would not pass multiple definition files directly to the codegen, rather pass a single one, which references potentially many files using the $ref syntax.

**Comment by zalak1612** [comment]
Thank you.

**Comment by TheAshwanik** [comment]
is this possible in 2020?  or still an enhancement?
Thank you.
