### ISSUE TITLE
enums are not generated in Java/Android Codegen

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-codegen#315]
This property was not codgen-ed:

       "order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ]
        }

as 
    private OrderEnum order = null;

But the Class - OrderEnum was not generated.

**Comment by SunriseJJJ** [comment]
faced same issue today. in definitions section i have:
```
"A": {
    "type": "string",
    "enum": [
        "VALUE_1",
        "VALUE_2"
    ]
}
```
result of generation is empty A class. if i wrap this in definition named B and set A as property - class B with one field (A as enum) generated correctly but IMO looks a little bit ugly.
maybe type "enum" may be introduced?..

**Comment by xhh** [comment]
The enum class is generated correctly right now.
Please have a look at [here](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/java/src/main/java/io/swagger/client/model/Pet.java#L19):

```java
public class Pet  {
  
  private Long id = null;
  private Category category = null;
  private String name = null;
  private List<String> photoUrls = new ArrayList<String>() ;
  private List<Tag> tags = new ArrayList<Tag>() ;
  public enum StatusEnum {
     available,  pending,  sold, 
  };
  private StatusEnum status = null;
```

That is, the enum class (`StatusEnum` above) is generated inline within the model class containing the property (`status`).
Below is some code verifying that it works:

```java
Pet pet = new Pet();
pet.setId(new Long(9527));
pet.setName("Kitty");
pet.setStatus(Pet.StatusEnum.pending);
api.addPet(pet);

Pet pet = api.getPetById(new Long(9527));
System.out.println(pet);
System.out.println(pet.getStatus());
System.out.println(pet.getStatus().getClass());

/* OUTPUT
class Pet {
  id: 9527
  category: null
  name: Kitty
  photoUrls: []
  tags: []
  status: pending
}

pending
class io.swagger.client.model.Pet$StatusEnum
*/

List<Pet> pets = api.findPetsByStatus(Arrays.asList("pending"));
System.out.println(pets);

/* OUTPUT
[class Pet {
  id: 9527
  category: null
  name: Kitty
  photoUrls: []
  tags: []
  status: pending
}
]
*/

@Sun
Regarding

**Comment by SunriseJJJ** [comment]
@xhh currently i have two different options:
* declare this enum wrapped in another entity, like this (but not looks really pretty for me)
```
"workflowStatus": {
    "description": "Wrapper for Workflow Status enum",
    "properties": {
        "status": {
            "type": "string",
            "enum": [
                "Status_1",
                "Status_2",
                "Status_3",
                "Resolved"
            ]
        }
    }
}
```
* declare this enum as inline enum (like you described) in different entities to 're-use' it
but it is not really nice because e.g. if i use this enum in ten entities and want to add new parameter for this enum - i need to find all ten usages and add additional parameter for all of them
instead of going to one (and only :) ) enum declaration and add parameter to it

that's the reason why i want to generate 'stand-alone' enum classes.

**Comment by xhh** [comment]
@SunriseJJJ I agreed with you that in the case you described it would be better to generate standalone enum class. However, the generator is not perfect/smart enough for now to detect the sharing of same enum classes, or to distinguish cases of whether to generate inline or standalone enum classes. And for now the inline approach would be the more "practical" one, before we making the generator perfect enough for enum (if possible/necessary).

Regarding your needing of changing enum values, I think that would need changing those enum values for all models (definitions) in the spec file, right? After that rerunning the codegen will just generate the new code.

**Comment by SunriseJJJ** [comment]
@xhh agree, yep, i understand that after change in contract new values will be generated, but it will be better if i need to change my enum just in one place instead of many (i think that it is valid case for large web-services)

by the way, current approach is acceptable! it's just about improvements. :)

**Comment by who** [comment]
@xhh Currently, because enums are not generated as stand-alone classes, the java output of swagger-codegen will not compile when using enums inside subTypes.  I have filed a bug here: https://github.com/swagger-api/swagger-codegen/issues/1050

**Comment by wing328** [comment]
Should be resolved. Please reopen if needed.
