### ISSUE TITLE
[JAVASCRIPT] Uncaught ReferenceError in constructFromObject

### ISSUE THREAD

**Issue by ferristseng** [swagger-api/swagger-codegen#3155]
##### Description

I'm running into an error in `constructFromObject`:

```
Uncaught ReferenceError: result is not defined
```

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

I can try to supply a simplified declaration if needed. I think the issue is just a typo, so I don't really want to spend the time testing this further.

##### Command line used for generation

```
java -jar bin/swagger-codegen-cli.jar generate -l javascript -i swagger.yaml -c conf/javascript.json
```

The conf that is pointed to has an empty json object.

##### Related issues

I couldn't find any...it seems like this is caused by a typo.

##### Suggest a Fix

The fix is to rename `result[k]` to `obj[k]`. The docs say that `obj` is the target. `result` is not declared anywhere in the function, so I'm assuming it was just a typo.

**Comment by gtrevg** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (209/200 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:50940 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bE6vH-0007HI-CZ
	for github@trevorgattis.com; Sat, 18 Jun 2016 03:27:51 +0000
Date: Thu, 16 Jun 2016 12:50:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466106612;
	bh=Y8dA9UfC7GDeswvoSRMRTnBvoIAvrZhG7GRnD3tM6C8=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=yhSk3hqa3g14kw/IDOB2u8pudK9aEtu2pTdItyqNKZCE1lfDXrM5lxpa2RdQMDDCO
	 D82lC/w0koWqMlEDnuKHPxTifg3pVV50AnaoT71OBwFLsS1Ji7jke+d+mWFlyHiV1M
	 Wf7l6eVDxpkrBReQjD1+VYOxKmu2tj8hwdADQjaw=
