### ISSUE TITLE
Jersey2 Jaxrs Import org.glassfish.jersey.media.multipart

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#3157]
_From @stfanbrg on June 2, 2016 14:14_

Hi,

I set the parameter   library to "Jersey core 2" for code generator but each  time I have to  replace (in my XyzApiService and XyzApi)

import com.sun.jersey.multipart.FormDataParam;
import com.sun.jersey.core.header.FormDataContentDisposition;

with 

import org.glassfish.jersey.media.multipart.FormDataContentDisposition;
import org.glassfish.jersey.media.multipart.FormDataParam;

for start my project on Tomcat 7.

Is it a issue or do I have to do something different ? 

_Copied from original issue: swagger-api/swagger-core#1817_

**Comment by cbornet** [comment]
@stfanbrg Can you test with latest master ? Also please paste the command line you use for generation.

**Comment by stfanbrg** [comment]
@cbornet I am not in my office for the week. I use the button in the web menu of swaggerhub  to generate my code .

**Comment by wing328** [comment]
@stfanbrg please test with the latest master or wait for the 2.2.0 stable release.

Closing this for now.
