### ISSUE TITLE
nodejs-server generates invalid root securityRequirement tag

### ISSUE THREAD

**Issue by dwasyluk** [swagger-api/swagger-codegen#3173]
Having an issue where generated code contains something that is reported as an invalid tag. When I use swagger-codegen to generate nodejs server code and then run 'node .' I get the following error related to the generated file in /api/swagger.yaml:

> API Errors:
> #: Additional properties not allowed: securityRequirement

If I change the generated root tag of 'securityRequirement:' to 'security:' the server runs but I do not see anything in swagger UI that suggests all paths other than /login are protected. Also for some reason the generated docs do not look the same as those on http://editor.swagger.io.

The generated docs on editor.swagger.io contain a dedicated Security (image) section which those generated via swagger-codegen do not.

![screen shot 2016-06-19 at 2 50 35 pm](https://cloud.githubusercontent.com/assets/987186/16179227/41bd0650-362d-11e6-8aa7-ec3e26c96146.png)

Here is the spec I'm using to generate the server, using swagger-codegen locally on latest commit as of this post b8c0569febedb17de099a52e98cc872db6f23643. I haven't tried generating the server via editor.swagger.io although that's something I'll give a go here shortly. Thanks for any assistance!

**Spec: http://pastebin.com/XvAWMmRx**

**Comment by dwasyluk** [comment]
The version of swagger-codegen being used on editor.swagger.io does not produce the erroneous securityRequirement tag, i don't see any references to the generated security information anywhere in the output outside /api/swagger.yaml.

**Comment by wing328** [comment]
@dwasyluk I tested with latest master and couldn't repeat the error:
```
tmperror|⇒ node .
Your server is listening on port 8080 (http://localhost:8080)
Swagger-ui is available on http://localhost:8080/docs
```

**Comment by wing328** [comment]
@dwasyluk closing this as there's no update. Please open a new issue if you need help from us (community)
