### ISSUE TITLE
In csharp client, model member names which match class name cause compile errors

### ISSUE THREAD

**Issue by dkelkhoff** [swagger-api/swagger-codegen#3184]
##### Description
We have a model class which has a member, whose name is the same as the class's name.  This causes the following compile error in the csharp client:
```src/Infoplus/Model/Carrier.cs(54,21): error CS0542: `Infoplus.Model.Carrier.Carrier': member names cannot be the same as their enclosing type```

##### Swagger-codegen version
Version 2.2.0-SNAPSHOT / HEAD.

##### Swagger declaration file content or url
Swagger JSON:  https://gist.github.com/dkelkhoff/189c0688c837fac3cabf25c993c8be28

##### Command line used for generation
```java -jar $CODEGEN_JAR generate -i $SWAGGERFILE -l csharp -o ~/tmp/infoplus-csharp-client -c <(echo "{\"packageName\": \"Infoplus\"}")```
* With ```CODEGEN_JAR``` pointed at a fresh build of the codegen cli (ie, ```~/git/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar```) 
* And ```SWAGGERFILE``` pointed at the swagger json file referenced in the gist above.  

##### Steps to reproduce
Here's a rough version of the steps I used to reproduce this on my Mac (using Docker to run a Mono container...):
* Build CSharp client using command line above
* Copy client into src/ path of a docker image, with the following Dockerfile:
```
FROM mono
COPY src /opt/mono/src
CMD ["bash"]
```
* ```docker run``` the image identified above.
* ```root@36a79d2e8f33:/opt/mono/src# bash build.sh```

##### Related issues
Not that I've found in my searches so far.

##### Suggest a Fix
Perhaps prefixing (or suffixing) member names with ```_```, for example, may fix the issue (whether all, or just ones found to match class names).

**Comment by jimschubert** [comment]
@dkelkhoff Thanks for reporting this. #2943 previously reported the issue, and #2962 is an open PR to resolve the issue. Can you review the issue and PR to verify this is the same issue you're seeing?

**Comment by wing328** [comment]
@dkelkhoff I've filed https://github.com/swagger-api/swagger-codegen/pull/3187 to fix it. There are 2 issues.

1) model & property having the same name is fixed by a case-insensitive comparison between model & property name
2) model with only read-only property fixed by introducing an additional mustache tag "hasOnlyReadOnly"

**Comment by dkelkhoff** [comment]
@wing328 

I merged ```model_propert_same_name``` locally, and after a rebuild of all the things, I think it does resolve my issue.  I can't 100% tell, because the only environment I have for compiling this thing is the mono docker image I referenced in the issue, and I get a few different errors when I run the ```compile-mono.sh``` script in that:

```
error CS0006: Metadata file `bin/Newtonsoft.Json.dll' could not be found
error CS0006: Metadata file `bin/RestSharp.dll' could not be found
```

But - I'm guessing those are unrelated to this member-name-class-name-matching issue - so, I feel confident with your change.

Thanks!

**Comment by wing328** [comment]
@dkelkhoff thanks for testing the fix, which has been merged into the master.

Please pull the latest to get the fix.

For the `compile-mono.sh` issue, I'll take a look as well

**Comment by dkelkhoff** [comment]
@wing328 

I would say, don't worry about the ```compile-mono.sh``` issue.  When I actually read the error message, all it's saying is that my container doesn't have the 2 dependencies installed which are clearly listed as required for the client.  So, this is 100% my problem, not yours.

Thanks again.

**Comment by wing328** [comment]
@dkelkhoff ok. No problem and thanks again for reporting the issue with the details.
