### ISSUE TITLE
support file download

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#319]
based on https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#responseSchema

**Comment by lakeba** [comment]
any news on this feature?

**Comment by wing328** [comment]
It's a limitation with the spec at the moment. Please refer to https://github.com/swagger-api/swagger-spec/issues/50 for the latest discussion.

**Comment by webron** [comment]
@wing328 - not quite. There *is* a solution in the spec for file downloads using the `file` type in responses. That applies to this issue regardless of the #50 issue in the swagger-spec.

**Comment by wing328** [comment]
Ah ok. Sorry I got confused before.

**Comment by lakeba** [comment]
I don't think that .NET have a file type as response.

**Comment by webron** [comment]
@lakeba - it's not about .NET, it's about how Swashbuckle translates the code to the Swagger definition. I don't know what's common there and how it is translated (there's normally more than one method).

**Comment by wing328** [comment]
For C#, I've submitted a PR #927 to support the feature.

@lakeba do you mind help doing a test to see if it would meet your requirement ?

**Comment by lakeba** [comment]
I will do

**Comment by fantapop** [comment]
This is an old one. @wing328 Any updates here?

**Comment by wing328** [comment]
@fantapop thanks for tagging me but I'm no longer involved in this project. I hope others will help you out. Good luck.

**Comment by Alec321** [comment]
@HugoMario any updates?

**Comment by HugoMario** [comment]
@Alec321 
unfortunately no, been busy in other issues :(

**Comment by ak89224** [comment]
@HugoMario Any workaround either for the issue ?

**Comment by HugoMario** [comment]
This has been implemented in multiple generators
