### ISSUE TITLE
[Spring] Add support for the contextPath in Spring-boot gen

### ISSUE THREAD

**Issue by dan-lind** [swagger-api/swagger-codegen#3193]
##### Description

I recently went from 2.1.6 to 2.2.0-SNAPSHOT. 
With 2.1.6, the SpringMVC server stub served the generated api at /basePath.
With 2.2.0-SNAPSHOT this is no longer the case, the api is simply served at / 
(bottom of http://localhost:8080/swagger-ui.html also says [ base url: / , api version: 1.0.0 ] )

##### Swagger-codegen version

2.2.0-SNAPSHOT, commit eda6d35b9f2b02099e4305bd3e6b2bd0ed7a934b

##### Swagger declaration file content or url

petstore_full.yaml from the online editor

##### Command line used for generation
Using swagger-codegen-maven-plugin, 2.2.0-SNAPSHOT

Relevant config

```
<execution>
    <id>stub</id>
    <goals>
        <goal>generate</goal>
    </goals>
    <configuration>
        <inputSpec>${project.basedir}/src/main/resources/test.yaml</inputSpec>
        <language>spring</language>
        <output>${project.build.directory}/generated-sources/stub</output>
    </configuration>
</execution>
```

##### Steps to reproduce
mvn clean package
mvn -f target/generated-sources/stub/pom.xml package in 
java -jar target/generated-sources/stub/target/swagger-spring-server-1.0.0.jar

**Comment by wing328** [comment]
@dan-lind please note that in the latest master `spring`generates spring boot instead of spring mvc server stub.

To generate server stub for spring mvc, please set library to `spring-mvc`.

Ref: https://github.com/swagger-api/swagger-codegen/pull/3133

cc @cbornet

**Comment by dan-lind** [comment]
Yes, I saw that, sorry for being unclear. 
So this issue is relates to spring boot.

**Comment by cbornet** [comment]
@dan-lind I don't reproduce your issue. To me, the API was already served on / on 2.1.6.

**Comment by cbornet** [comment]
Ah, you mean jetty's context path ! I'll have a look.

**Comment by cbornet** [comment]
Jetty's context path seems to still uses the basePath on master. See https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/spring-mvc/pom.xml
```xml
<webAppConfig>
                        <contextPath>/v2</contextPath>
</webAppConfig>
```
for petstore.yaml
```yaml
host: petstore.swagger.io
basePath: /v2
```

**Comment by cbornet** [comment]
I also generated petstore_full.yaml with
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://editor.swagger.io/spec-files/petstore_full.yaml -l spring --library spring-mvc
```
then in the project dir
```
mvn clean jetty:run
```
then
```
$ curl -v -X GET --header 'Accept: application/json' 'http://localhost:8080/v2/pet/1'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/pet/1 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: application/json
> 
< HTTP/1.1 200 OK
< Date: Thu, 23 Jun 2016 07:49:15 GMT
< Content-Length: 0
* Server Jetty(9.2.15.v20160210) is not blacklisted
< Server: Jetty(9.2.15.v20160210)
< 
* Connection #0 to host localhost left intact
```
so the /v2 basePath is used !

**Comment by dan-lind** [comment]
I see that you tested here with spring-mvc. I know I was a bit unclear in the initial issue, but if you look at my maven execution config in the first post, I used spring boot. Is it possible that this is an issue for spring boot but not spring-mvc ?

**Comment by cbornet** [comment]
Indeed, the springboot gen doesn't use the basePath.
It's easy to add with ```server.contextPath={{#contextPath}}``` in application.properties

**Comment by cbornet** [comment]
@dan-lind Could you change the title of your issue to request support for the contextPath in Spring-boot gen ?

**Comment by dan-lind** [comment]
Done!

**Comment by wing328** [comment]
PR merged. Please pull the latest to give it a try.

Thanks for the contribution from @vovan-

**Comment by diyfr** [comment]
Warning,  Don't customize the file application.properties. 
The example given server port here should not be there

**Comment by wing328** [comment]
@diyfr that line (server.port) is commented out as it's started with "#"

In http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html, it gives an example on `server.port` as well.

If that's not the correct location to specify the server port, where else should we put it?
