### ISSUE TITLE
Model imports don't support nested Arrays and Maps.

### ISSUE THREAD

**Issue by faresd** [swagger-api/swagger-codegen#3194]
Model imports don't support nested Arrays and Maps.
##### Description

The problem can be reproduced using Swagger property the contains a nested Arrays such as:

``` yaml
"values" : {
          "type" : "array",
          "items" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/definitions/ApiNameValue"
            }
          }
        }
```

In the model generated (in my case JS) don't include the object "ApiNameValue" in the imports.
##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

https://swagger-ui-1243.appspot.com/apis/search/v1

**Comment by wing328** [comment]
It should be fixed in the latest stable version v2.2.3. Please give it a try.
