### ISSUE TITLE
[PHP] Client documentation

### ISSUE THREAD

**Issue by joskfg** [swagger-api/swagger-codegen#3197]
##### Description

The documentation generated has invalid namespaces.

##### Swagger-codegen version

2.1.6

##### Swagger call

I call https://generator.swagger.io/api/gen/clients/php using this parameters

```json
{
    "swaggerUrl": "URL",
    "options": {
        "modelPackage": "Vendor\\MyApiSdk\\Client\\Model",
        "apiPackage": "Vendor\\MyApiSdk\\Client\\Api",
        "invokerPackage": "Vendor\\MyApiSdk",
        "packagePath": "VendorApiSdk",
        "srcBasePath": "src",
        "composerVendorName": "vendor",
        "composerProjectName": "my_api_sdk",
        "artifactVersion": "1.0.0"
    }
}
```

##### Steps to reproduce

Just use a different modelPackage and apiPackage than:
invokerPackage + /Api/

For example:
```
"modelPackage": "Vendor\\MyApiSdk\\Client\\Model",
"apiPackage": "Vendor\\MyApiSdk\\Client\\Api",
"invokerPackage": "Vendor\\MyApiSdk",
```

##### Suggest a Fix

Instead of use in the documentation a contatenation of 
```
invokerPackage + /Api/
```

use the corresponding namespace
```
modelPackage
```
or
```
apiPackage
```

**Comment by arnested** [comment]
This is already fixed in the current master branch and should appear in the upcoming 2.2.0 release.

Thank you for reporting this anyway.

**Comment by wing328** [comment]
@joskfg can you please pull the latest master to help confirm?

**Comment by wing328** [comment]
Closing this as there's no update.
