### ISSUE TITLE
escapeString method of ApiInvoker is empty [Android]

### ISSUE THREAD

**Issue by bensteUEM** [swagger-api/swagger-codegen#3202]
##### Description

while adding parameters in io.swagger.client.request.APIinvoker the escapeString method is used to wrap input and convert e.g. from space to %20 for the correct url encoding, however the escapeString method used does not do the required action and returns the unchanged result

##### Swagger-codegen version

 i think 2.0.0 (3 days ago export)

##### Swagger declaration file content or url

results in code 400 on request due to space in URL and parameters

##### Command line used for generation

n/a

##### Steps to reproduce

make a get request with any autogenerated API package for andriod which has at least one parameter which is not the last one with a space

##### Related issues

no idea

##### Suggest a Fix

make sure that the following code is used for escapeString method in respective class (line 222 in my case)
      try {
          return URLEncoder.encode(str, "UTF-8");
      } catch (UnsupportedEncodingException e) {
          e.printStackTrace();
          return null;
      }

**Comment by bensteUEM** [comment]
suspecting https://github.com/swagger-api/swagger-codegen/blob/6697c865c28bd7b6844124a3ca9b1d6aee6f3bec/samples/client/petstore/android/httpclient/src/main/java/io/swagger/client/ApiInvoker.java#L209

**Comment by bensteUEM** [comment]
https://github.com/swagger-api/swagger-codegen/blob/4d19da41dd8a3462f88c2be57174aace45101064/modules/swagger-codegen/src/main/resources/android/apiInvoker.mustache#L209

https://github.com/swagger-api/swagger-codegen/blob/c39bf41d1068e9d9ec1d0d8986e5305a1c5e377b/modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache#L231

**Comment by wing328** [comment]
@bensteUEM thanks for reporting the issue. For Volley, I believe there's no need to escape the query parameter as the encoding is handled by the Volley library. Did you actually encounter issue sending query parameters using the Android API client with Volley library?

**Comment by wing328** [comment]
PR merged into master. Please pull the latest to give it a try.
