### ISSUE TITLE
[JAVA] swagger-codegen-ignore ignores files while building java client

### ISSUE THREAD

**Issue by Nightapes** [swagger-api/swagger-codegen#3209]
##### Description

Files like .gitignore, git_push.sh, gradle-wrapper.properties are ignored by swagger-codegen-ignore. 

##### Swagger-codegen version

2.1.6

##### Steps to reproduce

1. Add .gitignore to .swagger-codegen-ignore
1. change .gitignore 
1. run generator
1. .gitignore is overwritten 

##### Suggest a Fix
 
Move generation of files from supportingFiles to writeOptional

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L89-96

**Comment by wing328** [comment]
@Nightapes that should be fixed in the latest master. Please pul the latest and give it a try.

**Comment by Nightapes** [comment]
@wing328 yes, in the latest master it is working.
