### ISSUE TITLE
[Ruby] Unable to set optional boolean form params to false

### ISSUE THREAD

**Issue by JustSilverman** [swagger-api/swagger-codegen#3215]
##### Description

When setting optional query parameters, the Ruby client uses a truthy check (rather than checking for nil) to check for the presence of the query parameter in the options hash.  This check will return false if the query parameter is present in the options hash with a value of false and will result in the query parameter incorrectly not being passed to the request body. The field should be in the body with a value of false.

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url
See [gist](https://gist.github.com/JustSilverman/d9704f9fe8c5c78394b801e71a6f8a66#file-default_api_snippet-rb-L24) for an example of schema and generated code. Line 24 of default_api_snippet.rb illustrates the issue.

##### Command line used for generation

NA

##### Steps to reproduce

* Define an optional boolean field in formData.
* Generate ruby client code
* Pass `false` as value for the field
* Field will not end up query parameters of request

##### Related issues

NA

##### Suggest a Fix
When checking for the presence of a key in the options hash, the code should check if the value for the key is not nil.

Based on the sample code in gist, line 24:

```ruby
form_params["isDog"] = opts[:'is_dog'] if opts[:'is_dog']

# should be:
form_params["isDog"] = opts[:'is_dog'] if !opts[:'is_dog'].nil?
```

**Comment by wing328** [comment]
@JustSilverman thanks for reporting the issue. I've filed #3218 to fix it.

**Comment by wing328** [comment]
@JustSilverman PR merged into master. Please pull the latest master to give it a try.

**Comment by JustSilverman** [comment]
@wing328 LGTM. Thanks for moving so quickly on this.
