### ISSUE TITLE
[csharp] Property validation for Model's Constructor and Setter Parameters

### ISSUE THREAD

**Issue by RowanJKWalker** [swagger-api/swagger-codegen#3222]
##### Description

Generated C# models do not have property validation for pattern, minLength, maxLength etc.
##### Swagger-codegen version

[v2.1.6](https://github.com/swagger-api/swagger-codegen/tree/v2.1.6)
##### Related issues

[#2663](https://github.com/swagger-api/swagger-codegen/issues/2663)
##### Suggest a Fix

Update:
- [Generated Models](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache)
- [Generated Docs](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/model_doc.mustache)

Maybe update:
- [Generated tests](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/model_test.mustache)
- Pet store example

**Comment by wing328** [comment]
Yes, we've started adding validation to languages one by one and so far we only cover PHP, Python and Ruby.

May I know if you've cycle to contribute the enhancement?

Ref: https://github.com/swagger-api/swagger-codegen/issues/2663 (with links to other PRs implementing validation in Ruby, PHP, Python, which are good starting points)

cc @jimschubert

**Comment by jimschubert** [comment]
For C#, I wonder if it would be better to use DataAnnotations?

One problem with Constructor and setter validations is they're done once and provide only one validation error.

DataAnnotations are incorporated into tools like Entity Framework and allow for aggregations of all validation errors. I've found it to be a much better experience.

Plus, it's possible using reflection to bypass setter validation. If a model's validation rings just before serialization, we can be sure the object sent to the server is actually valid.

**Comment by wing328** [comment]
I also prefer DataAnnotations.

**Comment by RowanJKWalker** [comment]
Cool, I'll look into it on the weekend.

**Comment by jimschubert** [comment]
@RowanJKWalker did you do any work on this? I can take a look if you haven't.

**Comment by jimschubert** [comment]
I created a PR with an `IValidatableObject` implementation. Let me know if you've done other work and we can coordinate.

**Comment by RowanJKWalker** [comment]
Hey sorry, I didn't get round to doing this.

**Comment by wing328** [comment]
Should be closed via #3552
