### ISSUE TITLE
[PHP] refactor PHP-related client into a common abstract base class

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3227]
##### Description

Similar to Java, C# and Typescript, we want to refactor all PHP-related generators (API client, Lumne, Silex, Slim) into a common base class so that the same enhancements or bug fixes can be applied to all PHP generators without duplicated efforts.

If anyone from the community can help work on this, please reply to let us know. Much appreciated.

**Comment by abcsun** [comment]
I will try it.

**Comment by Potherca** [comment]
Depending on circumstances I might also be able to contribute.

**Comment by wing328** [comment]
@Potherca this has been done via #3310. Please pull the latest master and you should see an abstract base class for PHP-related generator.
