### ISSUE TITLE
[OBJC] Petstore Sample code Typo in README.md and linking error in XCode 7 iOS 9

### ISSUE THREAD

**Issue by jshin49** [swagger-api/swagger-codegen#3234]
##### Description
1. Typo in swagger-codegen/samples/client/petstore/objc/default/README.md

The example code in README contains typos (lines 73~83).

2. The example code causes linking error in XCode 7 and iOS 9 as the following:

   ```
 Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_SWGPetApi", referenced from:
      objc-class-ref in ViewController.o
      "_OBJC_CLASS_$_SWGPet", referenced from:
      objc-class-ref in ViewController.o
      "_OBJC_CLASS_$_SWGConfiguration", referenced from:
      objc-class-ref in ViewController.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

##### Swagger-codegen version

I'm just trying out the Petstore example

##### Steps to reproduce

For 2.

I just followed the Swagger documentation (README) with a sample app.

##### Suggest a Fix

1.  This is the fixed version for the typos in the README

```
         SWGConfiguration *apiConfig = [SWGConfiguration sharedConfig];

         // Configure OAuth2 access token for authorization: (authentication scheme: petstore_auth)
         [apiConfig setAccessToken:@"YOUR_ACCESS_TOKEN"];


         SWGPet* body = [[SWGPet alloc] init]; // Pet object that needs to be added to the store (optional)

         SWGPetApi *apiInstance = [[SWGPetApi alloc] init];

         // Add a new pet to the store
         [apiInstance addPetWithBody:body
                   completionHandler: ^(NSError* error) {
                       if (error) {
                           NSLog(@"Error: %@", error);
                       }
                   }];

```
2. No idea to fix the linking issue. Any insights? I'm a newbie with both Swagger and iOS.

**Comment by wing328** [comment]
Please run the integration test for Petstore ObjC API client to see if you get any error:

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-do-i-run-integration-test-with-petstore-objc-api-client

cc @mateuszmackowiak

**Comment by wing328** [comment]
@jshin49 I've fixed the typo. Please pull the latest to give it a try.

For the linking issue, we cannot reproduce it. Please run the integration-test as suggested above.
