### ISSUE TITLE
Generating Java client with customised templates works on current master (swagger-codegen-cli-2.2.0-SNAPSHOT.jar) but not on codegen 2.1.6

### ISSUE THREAD

**Issue by talolierwork** [swagger-api/swagger-codegen#3242]
Generating Java client with customised templates works on current master (swagger-codegen-cli-2.2.0-SNAPSHOT.jar) but not on codegen 2.1.6
##### Description

I am using codegen 2.1.6 in order to generate Java client code via the following command:
java -jar swagger-codegen-cli-2.2.0-SNAPSHOT.jar generate -l java --artifact-version 1.0.0 --group-id com.olier.csp.sdk --artifact-id csp-sdk -i csp-host.json -o csp-sdk-generated-code---retrofit2 --invoker-package com.olier.csp.sdk.invoke --model-package com.olier.csp.sdk.model --api-package com.olier.csp.sdk.api --library retrofit2 --template-dir templates

I have one file in temoplates directory: ApiClient.mustache

It works great (and the ApiClient.mustache in the templates directory overides the one codegen/retroft arrives with) when using swagger-codegen-cli-2.2.0-SNAPSHOT.jar, but when building my product with swagger-codegen-cli-2.1.6.jar it does not work - seems like codegen ignores the ApiClient.mustache template.

Is that a bug in 2.1.6 that was fixed? or do I need to do additional stuff in 2.1.6 that I do not need to in 2.2.0?

TIA,

-Tal.
##### Swagger-codegen version

2.1.6, 2.2.0
##### Swagger declaration file content or url

n/a
##### Command line used for generation

java -jar swagger-codegen-cli-2.1.6.jar generate -l java --artifact-version 1.0.0 --group-id com.olier.csp.sdk --artifact-id csp-sdk -i csp-host.json -o csp-sdk-generated-code---retrofit2 --invoker-package com.olier.csp.sdk.invoke --model-package com.olier.csp.sdk.model --api-package com.olier.csp.sdk.api --library retrofit2 --template-dir templates
##### Steps to reproduce

Just use the above command.
##### Related issues

n/a
##### Suggest a Fix

n/a

**Comment by jbogarin** [comment]
Did you solve this? I'm having the same issue.

**Comment by wing328** [comment]
@jbogarin have you tried the latest master to see if the issue still occurs?

**Comment by jbogarin** [comment]
@wing328 yeah, I just did this:
git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
mvn clean package
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i <file> -t <template> -o <output dir> -l go

and it completely ignores the template directory

**Comment by talolierwork** [comment]
@jbogarin, last master worked for me. I am using retrifit2 lib (if that matters).

**Comment by hoeggi** [comment]
i just had the same problem, for me it was my template folder structue
-templates(folder)
--xxx.mustache
--yyy.mustache
--libraries(folder)
---retrofit2(folder)
----zzz.mustache
----aaa.mustache

took me a few hours to find this commit https://github.com/swagger-api/swagger-codegen/commit/83e8a2e90ca942e4ad7f9a636c8c9df4e1e7fa78

maybe this should be documented as breaking change somewhere.

happy to make a PR if someone can tell me where to document this.

**Comment by hoeggi** [comment]
also was there a reason for removing subdirectories? i could note find any issue/pr related to this change.

**Comment by hoeggi** [comment]
nevermind found this https://github.com/swagger-api/swagger-codegen/pull/3043 still think this should be documented as breaking change.

**Comment by wing328** [comment]
@hoeggi I've marked #3043 as breaking change (without fallback) based on your feedback.

**Comment by hoeggi** [comment]
@wing328 thx, but don't you think it's a breaking change *with* fallback? since moving all library templates to the root folder solves the issue.

**Comment by wing328** [comment]
Usually "breaking change (with fallback)" refers to breaking changes that can be remediated using CLI option. You do have your point that this issue can also easily be remediated by changing the path (input) a little bit.

Let me think about this more (likely I'll take your suggestion)
