### ISSUE TITLE
Static html file doesn't contain tag information

### ISSUE THREAD

**Issue by rejithkumarb** [swagger-api/swagger-codegen#3243]
##### Description

Static html file doesn't contain tag information
##### Swagger-codegen version

swagger 2.0

**Comment by wing328** [comment]
@rejithkumarb May I know if you've cycle to contribute the enhancement?

**Comment by wing328** [comment]
@rejithkumarb a new documentation generator has been released: `html2`.

Please pull the latest master to give it a try.
