### ISSUE TITLE
[WINDOWS] Backslash in filename in ec2abe78e3b4aff59578d068612261846f5a487c breaks checkout

### ISSUE THREAD

**Issue by milo-minderbinder** [swagger-api/swagger-codegen#3247]
##### Description

Commit ec2abe78e3b4aff59578d068612261846f5a487c added the file [samples/server/petstore-security-test/slim/SwaggerServer\lib\Models/Return.php](https://github.com/swagger-api/swagger-codegen/blob/ec2abe78e3b4aff59578d068612261846f5a487c/samples/server/petstore-security-test/slim/SwaggerServer%5Clib%5CModels/Return.php) which breaks checkouts on Windows due to the directory "SwaggerServer\lib\Models" which contains backslashes in the directory name.

##### Swagger-codegen version

2.2.0-SNAPSHOT - commit ec2abe78e3b4aff59578d068612261846f5a487c

##### Steps to reproduce

From a Windows machine, attempt to clone swagger-codegen at or after ec2abe78e3b4aff59578d068612261846f5a487c:
```bash
git clone https://github.com/swagger-api/swagger-codegen.git
git reset --hard ec2abe78e3b4aff59578d068612261846f5a487c
```

![git-error](https://cloud.githubusercontent.com/assets/10577399/16456060/90392926-3de4-11e6-8e1a-905d01eaa1f5.png)

##### Suggest a Fix

see [http://stackoverflow.com/questions/18920351/bugged-file-path-in-git](http://stackoverflow.com/questions/18920351/bugged-file-path-in-git)

**Comment by wing328** [comment]
@milo-minderbinder thanks for reporting the issue. I'll file a PR to remove that shortly.

**Comment by wing328** [comment]
@milo-minderbinder the bug should be fixed by #3251. Please pull the latest master to give it a try.

**Comment by wing328** [comment]
@milo-minderbinder it's also worth mentioning that the latest master has PHP Lumen generator that you may find useful. If you encounter any issue and have feedback for us, please reply to let us know.

**Comment by milo-minderbinder** [comment]
@wing328 thanks! appreciate the prompt fix!

**Comment by wing328** [comment]
@milo-minderbinder FYI. We've added CI tests in the Windows environment to ensure the JAR can be built successfully in Windows environments moving forward.

A huge thanks to [AppVeyor](https://appveyor.com) for providing free CI tests in the Windows environment.
