### ISSUE TITLE
CodegenModel should have format field

### ISSUE THREAD

**Issue by gokl** [swagger-api/swagger-codegen#3257]
##### Description

For the static html generator I would like to see the format of a parameter. The format however is missing from the CodegenModel, so it should be added and filled with the format from Model.
After that I could add the format to the template.

##### Suggest a Fix

If you want, I could provide a PR for it.

**Comment by wing328** [comment]
For format, I believe you're referring to `int32`, `float`, etc. Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

Your suggestion is definitely reasonable.

Please contribute a PR if you've time. Thanks!

**Comment by gokl** [comment]
Hi, i created a PR. Tell me if it's OK or you want some changes / additions.
Thanks!

**Comment by wing328** [comment]
@gokl Thanks for the PR. The change looks good to me and I've merged it into master.

Next time, please also run `./bin/html-petstore.sh` to keep the Petstore sample (HTML doc) up-to-date.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by gokl** [comment]
@wing328: Will do run it next time :-)
