### ISSUE TITLE
sbt assembly failure

### ISSUE THREAD

**Issue by somethingShiny** [swagger-api/swagger-codegen#326]
I have cloned the repository and am trying to build the petstore sample to familiarize myself with swagger-codegen. When I try to run sbt assembly, I  get 
    ./sbt: line 118: conditional binary operator expected
    ./sbt: line 118: syntax error near `=~'
    ./sbt: line 118: `  if [[ ! -r "$default_file" && $overriding_var =~ ^@(.*)$ ]]; then' 
What do I need to do to resolve this issue?

**Comment by webron** [comment]
Closing as this is no longer relevant to the new codegen. Please try the latest version.
