### ISSUE TITLE
[Java] How to add gzip filter to com.sun.jersey.api.client.Client

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#3279]
##### Description

I want to add the GZIPContentEncodingFilter to Jersey-Client in the generated ApiClient class.
However, there currently seems no way to access the com.sun.jersey.api.client.Client: 
The method to access the Jersey-Client is private:
private Client getClient() 

Pls advise on how to add gzip encoding to the generated ApiClient?
##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/2539
##### Suggest a Fix

It would be great if the getClient method is protected, so it is possible to access the Client to add filters etc.

Currently there seems no workaround but to copy the whole ApiClient.java class and rewrite the getClient method ourselves ...

Thank you & Best regards,
Johannes

**Comment by jfiala** [comment]
One additional thought:
Jersey1 com.sun.jersey.api.client.filter.GZIPContentEncodingFilter 
and Jersey2 org.glassfish.jersey.message.GZipEncoder
don't implement any configurable threshold (like e.g. org.apache.cxf.transport.common.gzip.GZIPOutInterceptor does), so it will always use gzip regardless of the size of the request.
https://jersey.java.net/apidocs/2.6/jersey/org/glassfish/jersey/message/GZipEncoder.html

So it would make sense to be able to add filters not for the whole ApiClient, but per method invocation (e.g. for multipart-invocations to use gzip, and the others not).

**Comment by wing328** [comment]
@jfiala I checked jersey1 and jersey2 client. Both have the following in ApiClient.java:
```
  public Client getHttpClient() {
    return httpClient;
  }

  public ApiClient setHttpClient(Client httpClient) {
    this.httpClient = httpClient;
    return this;
  }
```
Are you using the latest master?

**Comment by jfiala** [comment]
@wing328: You're absolutely correct, this has already been added for both jersey1 + jersey2, I also commented in #2539!

Regarding the Gzip: maybe it would be nice to add a switch for this in the Java-Jersey-Clients test templates?
BTW: Wouldn't it make sense to rename java to java_jersey to make it more obvious it is using the jersey-implementation?

**Comment by wing328** [comment]
About renaming `java` to `java_jersey1`, we just change the default Java library to `okhttp-gson` via https://github.com/swagger-api/swagger-codegen/pull/3312

If the request is gzipped, I think it should be documented using vendor extension and the template can do something accordingly.

**Comment by jfiala** [comment]
added gzip support to the jaxrs-cxf client in PR #4003  + documented the supported gzip feature using interface GzipFeatures
