### ISSUE TITLE
Caught in a loop "Please set scalaVersion := "2.11" in build.sbt and run ./sbt assembly"

### ISSUE THREAD

**Issue by neilyoung** [swagger-api/swagger-codegen#329]
I'm somehow caught in a loop. I think I have installed all pre-requisites. Running on OSX 10.10. 
Whatever script I'm launching (e.g. ./bin/static-docs.sh ) I'm gettin

"Please set scalaVersion := "2.11" in build.sbt and run ./sbt assembly"

Running ./sbt assembly doesn't change the situation. What am I doing wrong?

**Comment by webron** [comment]
Closing as the the new version doesn't use scala anymore. Please try the latest version.
