### ISSUE TITLE
[csharp] Documentation suggestion for links

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#3296]
##### Description

Link Within a Page (anchors) in documentation resulting from MD files do not work.

##### Swagger-codegen version

2.2.0

##### Suggest a Fix
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/api_doc.mustache

------------------------------------------------------------------
change line 13
        # **{{{operationId}}}**

to
        <a name="{{{operationIdLowerCase}}}"></a>
        # **{{{operationId}}}**
------------------------------------------------------------------

==================================================================
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/README.mustache

------------------------------------------------------------------
change line 27-28
        - [RestSharp] (https://www.nuget.org/packages/RestSharp) - 105.1.0 or later
        - [Json.NET] (https://www.nuget.org/packages/Newtonsoft.Json/) - 7.0.0 or later

to
        - [RestSharp](https://www.nuget.org/packages/RestSharp) - 105.1.0 or later
        - [Json.NET](https://www.nuget.org/packages/Newtonsoft.Json/) - 7.0.0 or later
------------------------------------------------------------------
change line 108
        ## Documentation for API Endpoints

to
        <a name="documentation-for-api-endpoints"></a>
        ## Documentation for API Endpoints
------------------------------------------------------------------
change line 117
        ## Documentation for Models

to
        <a name="documentation-for-models"></a>
		## Documentation for Models
------------------------------------------------------------------
change line 131
        {{#authMethods}}### {{name}}

to
        <a name="{{#authMethods}}{{name}}"></a>
		{{#authMethods}}### {{name}}

**Comment by wing328** [comment]
@lunat  Please file a PR with the C# Petstore sample updated (by running `./bin/csharp-petstore.sh) and we'll review the change. Thanks!

**Comment by wing328** [comment]
Thanks for the PR (#3313), which has been merged into master.
