### ISSUE TITLE
[JAX-RS] Codegen Creates form-data variables with duplicate names

### ISSUE THREAD

**Issue by jencodingatwork** [swagger-api/swagger-codegen#3300]
##### Description

The JAX-RS Code generator creates variables with duplicate names when more than one file is included in the API call which results in a compilation error.

##### Swagger-codegen version
2.1.6

##### Swagger declaration file content or url

```
paths:
  /Plugin:
    post:
      tags:
        - Plugin
      summary: Upload Plugin
      description: This can only be done by the logged in user.
      operationId: createPlugin
      consumes:
      - "multipart/form-data"
      produces:
        - application/json
        - application/xml
      parameters:
        - in: formData
          name: json
          description: Uploaded Plugin
          required: true
          type: string
        - in: formData
          name: jarFile
          description: Jar File to upload
          required: true
          type: file
        - in: formData
          name: configFile
          description: config File to upload
          required: true
          type: file
      responses:
        200:
          description: successful operation
```

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i C:/PluginAPI/plugin.yaml -l jaxrs -o C:/Temp/JAX_RStest java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i C:/PluginAPI/plugin.yaml -l jaxrs -o C:/Temp/JAX_RStest

##### Steps to reproduce

1. Execute command
2. Look at Plugin API code, where you should see the following method. Notice that there are two variables named inputStream, two variables named fileDetail, and all params are set to “file”.

```
@POST 
    @Produces({ "application/json", "application/xml"})
    @Consumes({"multipart/form-data"})
    @io.swagger.annotations.ApiOperation(value = "Upload Plugin", notes = "This can only be done by the logged in user.", response = void.class, tags={ "Plugin", })
    @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "successful operation", response = void.class) })
    public Response createAnalytic(@ApiParam(value = "Uploaded Plugin", required=true)@FormParam("json")  String json,
            @FormDataParam("file") InputStream inputStream,
            @FormDataParam("file") FormDataContentDisposition fileDetail,
            @FormDataParam("file") InputStream inputStream,
            @FormDataParam("file") FormDataContentDisposition fileDetail,@Context SecurityContext securityContext)
    throws NotFoundException {
        return delegate.createAnalytic(json, inputStream, fileDetail, inputStream, fileDetail, securityContext);
    }
```

##### Related issues

I could not find any related issues.

##### Suggest a Fix

My fix to this was to modify three mustache files so that the hardcoded variable name also includes the paramName resulting in the following code:

```
@POST 
    @Produces({ "application/json", "application/xml"})
    @Consumes({"multipart/form-data"})
    @io.swagger.annotations.ApiOperation(value = "Upload Plugin", notes = "This can only be done by the logged in user.", response = void.class, tags={ "Plugin", })
    @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "successful operation", response = void.class) })
    public Response createAnalytic(@ApiParam(value = "Uploaded Plugin", required=true)@FormParam("json")  String json,
            @FormDataParam("jarFile") InputStream jarFileinputStream,
            @FormDataParam("jarFile") FormDataContentDisposition jarFileDetail,
            @FormDataParam("configFile") InputStream configFileinputStream,
            @FormDataParam("configFile") FormDataContentDisposition configFileDetail,@Context SecurityContext securityContext)
    throws NotFoundException {
        return delegate.createAnalytic(json,jarFileinputStream, jarFileDetail,configFileinputStream, configFileDetail,securityContext);
    }
```
Line 79 of the api.mustache file should be modified to become:

```return delegate.{{nickname}}({{#allParams}}{{#isFile}}{{paramName}}inputStream, {{paramName}}Detail{{/isFile}}{{^isFile}}{{paramName}}{{/isFile}},{{/allParams}}securityContext);```

The formParams.mustache file should be updated to become:

```
{{#isFormParam}}{{#notFile}}@ApiParam(value = "{{{description}}}"{{#required}}, required=true{{/required}}{{#allowableValues}}, {{> allowableValues }}{{/allowableValues}}{{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}){{#vendorExtensions.x-multipart}}@FormDataParam("{{paramName}}")  {{{dataType}}} {{paramName}}{{/vendorExtensions.x-multipart}}{{^vendorExtensions.x-multipart}}@FormParam("{{paramName}}")  {{{dataType}}} {{paramName}}{{/vendorExtensions.x-multipart}}{{/notFile}}{{#isFile}}
            @FormDataParam("{{paramName}}") InputStream {{paramName}}inputStream,
            @FormDataParam("{{paramName}}") FormDataContentDisposition {{paramName}}Detail{{/isFile}}{{/isFormParam}}
```
The serviceFormParams.mustache file should be updated to become:

`{{#isFormParam}}{{#notFile}}{{{dataType}}} {{paramName}}{{/notFile}}{{#isFile}}InputStream {{paramName}}inputStream, FormDataContentDisposition {{paramName}}fileDetail{{/isFile}}{{/isFormParam}}`

**Comment by wing328** [comment]
@jencodingatwork thanks for reporting the issue and suggesting a fix to address the issue.

Your suggested solution looks good to me. May I know if you've a cycle to submit a PR for your suggested fix?

**Comment by jencodingatwork** [comment]
Sure, I should be able to submit one by the end of this week.

**Comment by wing328** [comment]
@jencodingatwork thanks. Let us know if you need help submitting the PR.

**Comment by jencodingatwork** [comment]
@wing328 I have created a PR with the fix (#3304)

**Comment by wing328** [comment]
PR merged. Thanks for the contribution.

**Comment by YathendraPrasad** [comment]
@wing328 , Has the fix been merged to 2.2.2 swagger-codegen-maven-plugin . I could still see the issue . Here is my JSON and the API spec
JSON : 
{
                        "name": "classname_positive_examples",
                        "in": "formData",
                        "description": "A compressed (.zip) file of images that depict the visual subject for a class within the classifier. Must contain a minimum of 10 images.",
                        "required": true,
                        "type": "file"
                    },
                    
                    {
                        "name": "negative_examples",
                        "in": "formData",
                        "description": "A compressed (.zip) file of images that do not depict the visual subject of any of the classes of the new classifier. Must contain a minimum of 10 images.",
                        "required": false,
                        "type": "file"
                    }


API Generated : 

 @POST
    @Path("/classifiers/{classifier_id}")
    @Consumes({ "multipart/form-data" })
    @Produces({ "application/json" })
    @io.swagger.annotations.ApiOperation(
    	value = "Update a classifier", 
		notes = "", 
		response = GetClassifiersPerClassifierVerbose.class, tags={ "VisualRecognition",  })
    @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "success", response = GetClassifiersPerClassifierVerbose.class),
        
        @io.swagger.annotations.ApiResponse(code = 400, message = "Invalid request", response = GetClassifiersPerClassifierVerbose.class) })
    @OAuthSecurity(enabled=false)   
    public Response v3ClassifiersClassifierIdPost(
@ApiParam(value = "The ID of the classifier.",required=true) @PathParam("classifier_id") String classifierId,
  @FormDataParam("file") InputStream inputStream,
@FormDataParam("file") FormDataContentDisposition fileDetail,@ApiParam(value = "API Key used to authenticate.") @QueryParam("api_key") String apiKey
,
  @FormDataParam("file") InputStream inputStream,
@FormDataParam("file") FormDataContentDisposition fileDetail,@ApiParam(value = "The release date of the version of the API you want to use. Specify dates in YYYY-MM-DD format.", defaultValue="2016-05-20") @DefaultValue("2016-05-20") @QueryParam("version") String version
)
    throws NotFoundException, ServiceFactoryFinderException  {
...

}

**Comment by YathendraPrasad** [comment]
@wing328 : same name "inputStream" created

**Comment by YathendraPrasad** [comment]
Hi ,

Any update on this will be helpful 

Thanks

**Comment by jencodingatwork** [comment]
@YathendraPrasad It looks like the code change is in the JavaJaxRS resources code, but I don't know if it is in the maven plugin. In the worse case scenario, you can do what I did and write a modified version of the JavaJaxRS code generator so that it does what you need.

**Comment by YathendraPrasad** [comment]
Hey thanks @jencodingatwork for the update and sorry for late reply . After making the changes that you have pointed to i have encountered the below issues

# Build Issue

[128,32] method v3DetectFacesPost in class com.ibm.mfp.adapters.sample.api.VisualRecognitionApi cannot be applied to given types;
  required: java.lang.String,java.io.File,java.lang.String,java.lang.String
  found: java.lang.String,java.io.InputStream,com.sun.jersey.core.header.FormDataContentDisposition,java.lang.String,java.lang.String,javax.ws.rs.core.SecurityContext
  reason: actual and formal argument lists differ in length


# Server Side code : 

`@POST
    @Path("/detect_faces")
    @Consumes({ "multipart/form-data" })
    @Produces({ "application/json" })
    @io.swagger.annotations.ApiOperation(
    	value = "Detect faces in an image", 
		notes = "", 
		response = Faces.class, tags={ "VisualRecognition" })
    @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "success", response = Faces.class),
        
        @io.swagger.annotations.ApiResponse(code = 400, message = "Invalid request", response = Faces.class) })
    @OAuthSecurity(enabled=false)   
    public Response v3DetectFacesPost(@ApiParam(value = "API Key used to authenticate.") @QueryParam("api_key") String apiKey
 ,

            @FormDataParam("imageFile") InputStream imageFileInputStream,
            @FormDataParam("imageFile") FormDataContentDisposition imageFileDetail ,
@ApiParam(value = "A JSON file containing an array of image URLs to analyze.   For example: {\"urls\": [\"...\", \"...\"]}")@FormDataParam("parameters")  String parameters ,@ApiParam(value = "The release date of the version of the API you want to use. Specify dates in YYYY-MM-DD format.", defaultValue="2016-05-20") @DefaultValue("2016-05-20") @QueryParam("version") String version
 ,@Context SecurityContext securityContext)
    throws NotFoundException, ServiceFactoryFinderException {

        //return getV3ApiService().v3DetectFacesPost(apiKey,inputStream, fileDetail,parameters,version,securityContext);

        com.ibm.mfp.adapters.sample.ApiClient apiAuthInstance = new com.ibm.mfp.adapters.sample.ApiClient();

        com.ibm.mfp.adapters.sample.api.VisualRecognitionApi apiInstance = new com.ibm.mfp.adapters.sample.api.VisualRecognitionApi(apiAuthInstance);
        
         String retval = "NA";
         com.ibm.mfp.adapters.sample.model.Faces result = null;
         apiAuthInstance.setUsername(configurationApi.getPropertyValue("username"));
         apiAuthInstance.setPassword(configurationApi.getPropertyValue("password"));
        try {
            System.out.println("Calling Node server.");
           // result = apiInstance.v3DetectFacesPost(apiKey,imageFile,parameters,version);
           **result = apiInstance.v3DetectFacesPost(apiKey,imageFileInputStream, imageFileDetail,parameters,version,securityContext);**
            System.out.println(result);
        } catch (Exception e) {
            System.err.println("Exception when calling V3Api#v3DetectFacesPost");
            e.printStackTrace();
        }
        System.out.println("Return from Node server: "+ result);
        if (result != null)
        {
            retval = result.toString(); 
        } 
        return Response.ok().entity(result).build();
    }`


# Client side generated Code : 

`public Faces v3DetectFacesPost(String apiKey, File imageFile, String parameters, String version) throws ApiException {
        ApiResponse<Faces> resp = v3DetectFacesPostWithHttpInfo(apiKey, imageFile, parameters, version);
        return resp.getData();
    }`


It would be help full if i get some quick solution . I could not figure out where exactly is the problem

**Comment by YathendraPrasad** [comment]
Purpose is to upload an image / zip file

**Comment by jencodingatwork** [comment]
@YathendraPrasad This sounds like an issue with your api code. As you can see from the error message:

```
class com.ibm.mfp.adapters.sample.api.VisualRecognitionApi cannot be applied to given types;
 required: java.lang.String,java.io.File,java.lang.String,java.lang.String
 found: java.lang.String,java.io.InputStream,com.sun.jersey.core.header.FormDataContentDisposition,java.lang.String,java.lang.String,javax.ws.rs.core.SecurityContext
 reason: actual and formal argument lists differ in length
```

you are not passing in the correct number arguments. I don't think there is a quick solution for this. I would recommend walking your code in a debugger to try and determine what the problem is.

**Comment by YathendraPrasad** [comment]
@jencodingatwork , I understand but both the server api code and the client side code are the genreted one .

If we see server side code (generated from *.mustache file) , it takes two parameters for file upload

`@FormDataParam("imageFile") InputStream imageFileInputStream,
        @FormDataParam("imageFile") FormDataContentDisposition imageFileDetail `

and then call is made to generated method

`return getV3ApiService().v3DetectFacesPost(apiKey,inputStream, fileDetail,parameters,version,securityContext);`


Now the client code generated using swagger codegen using my JSON is

`public Faces v3DetectFacesPost(String apiKey, File imageFile, String parameters, String version) throws ApiException {.. }`

and yes it clearly say parameter mismatch .  

What i want to understand is that the generated client code from JSON is correct ???

If that the way object is client code is formed for file upload ?

if so , then do i need to  convert from FileInputStream to File object and pass the File object to match the function on the client side .

@webron , It would be helpful if you give your suggestions on this


Thanks

**Comment by YathendraPrasad** [comment]
Also , can you guide me where can i get the sample JSON code to upload an **image file**

**Comment by jencodingatwork** [comment]
@YathendraPrasad I always use a YAML file to generate the code not JSON so I'm afraid I can't be of any more help.

**Comment by YathendraPrasad** [comment]
Ok Thanks for that . Just final thing is the client code correct for the file upload ??? or else you wanted to try with YAML file and see

**Comment by jencodingatwork** [comment]
@YathendraPrasad I think you are going to wait for someone with more understanding of the code base to look into this; I just found a bug while using it and fixed it. I would suggest opening a new issue. If you do, please make sure to format your code. Some of your previous posts are difficult to read with some sections formatted as code and some not. Good Luck!

**Comment by YathendraPrasad** [comment]
@jencodingatwork : My Sincere apologies for that . I did not see the preview of it and did it in hurry.

Thanks
