### ISSUE TITLE
Swift client cannot use authentication credentials in lockscreen background fetch

### ISSUE THREAD

**Issue by dylan-colaco** [swagger-api/swagger-codegen#3301]
##### Description

The Swift swagger client uses NSURLCredential for authenticating with a Swagger API(using Alamofire). This works fine when the app is active or in the background when the phone is unlocked. However it doesn't work when a background fetch happens while the phone is locked. This is because NSURLCredential cannot access the keychain from the lockscreen, and there seems to be no way to change this behavior.
##### Swagger-codegen version

Latest, from website generator at https://locus.sh/docs/index.html
##### Steps to reproduce

Generate swagger client.
Make a request to an API that requires HTTP Basic Authentication in background fetch method(in AppDelegate).
Lock the screen.
Simulate a background fetch in Xcode. You get a 401 error.
##### Suggest a Fix

Use keychain directly to store credentials instead of NSURLCredential, and set accessibility to accessibleAfterFirstUnlock. For http basic auth, credentials can be added to the header.

**Comment by dylan-colaco** [comment]
I've solved this by manually generating a basic auth header from the user credentials and passing it to the request builder as an additional header, for the methods that need to do background fetch with authentication (for anyone who runs runs into this in the future)

**Comment by wing328** [comment]
@dylan-colaco thanks for sharing the fix. Please try the swift4 generator in the latest master to see if it meets your requirement.
