### ISSUE TITLE
SWIFT: Swagger client method with completion closure passing an array has completion closure called multiple times

### ISSUE THREAD

**Issue by dylan-colaco** [swagger-api/swagger-codegen#3311]
##### Description

I am using the swift swagger client that has a completion closure which passes data which contains an array of objects. Ideally, this closure should be called only once, since all objects are contained within the array. However it seems to be called once for every object in the array, but passing the same array over and over again. You can see this in the attached screenshot.(The data in UserAPI.getUnackedMessages is of type message response which contains a messages(array) property [message] where message is a custom object)
<img width="1240" alt="screen shot 2016-07-06 at 2 41 32 pm" src="https://cloud.githubusercontent.com/assets/19706806/16613341/44263196-4389-11e6-8928-50320e781ab5.png">
##### Swagger-codegen version

latest, generated on website https://locus.sh/docs/index.html#!
##### Steps to reproduce

Generate Swift Swagger Client
Call an API Method which passes an array of data in a completion closure.
##### Suggest a Fix

Call the closure only once, since the array contains all the required items.

**Comment by wing328** [comment]
@dylan-colaco thanks for reporting. I don' think that's using the latest master to generate the Swift API client.

Please pull the latest master to generate the Swift API client to see if the issue still occurs.

cc @jaz-ah @Edubits

**Comment by wing328** [comment]
Closing this as there's no update.
