### ISSUE TITLE
[RUBY] JSON boolean attributes are always evaluated to false

### ISSUE THREAD

**Issue by daniellb** [swagger-api/swagger-codegen#3318]
##### Description
When an attribute in a definition has the type boolean, the autogenerated code evaluates this value always to false when the JSON response is deserialized.

This happens because the attribute is treated as string and not a boolean value.

##### Swagger-codegen version

2.1.5

##### Swagger declaration file content or url

https://raw.githubusercontent.com/heragu/swagger-codegen-ruby-bug/master/json-boolean-attribute-ruby-bug.yaml

##### Command line used for generation

swagger-codegen generate -i https://raw.githubusercontent.com/heragu/swagger-codegen-ruby-bug/master/json-boolean-attribute-ruby-bug.yaml -l ruby -o client/

##### Steps to reproduce

All information in repository https://github.com/heragu/swagger-codegen-ruby-bug

**Comment by wing328** [comment]
I believe the issue has been addressed in the latest master. Please pull the latest master to give it a try.

**Comment by wing328** [comment]
@daniellb please use the latest master to generate the Ruby API client and let us know if you still experience the issue. 

Closing this for now.
