### ISSUE TITLE
Issues with multiple ApiClient instances in default package

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#3342]
##### Description

Previously, the ApiClient generated in java clients was copied directly from the templates without any modification.  Later updates have added checks for authorization values directly in the ApiClient class, which means it has become specific to each integration.

If a user keeps the default package for the ApiClient class _AND_ has more than one generated client, the behavior is indeterminate, because only one ApiClient instance will be loaded by the classloader, and the authorization check is always, by murphy's law, the wrong one.  Same goes for the `basePath` value.  Two clients in one VM are going to have an issue.

##### Swagger-codegen version

2.2.0-SNAPSHOT (master as of 7/11/2016)

##### Suggest a Fix

We should choose only one of the following:

1. We can revert back to having "logic-less" ApiClient classes, where it is simply a wrapper to the underlying HTTP library.  The ApiClient class will simply create URLs, parse query params, encode values, etc.  The authorization can be moved up into the generated Api client classes, which are possibly the more logical place for this code

2.  We can default the ApiClient to the `api` package, to avoid conflicts with having multiple libraries in a single VM

Note! This may apply to other languages as well, I was just recently bit by it in Java.

**Comment by cbornet** [comment]
I think multiple clients shoud be generated in different packages so there's one ApiClient per client. It also prevents model/api collision.

**Comment by cbornet** [comment]
Other bad thing that can happen trying to mutualize generated files is if they are generated by different versions of the codegen.

**Comment by wing328** [comment]
Closed via #3382
