### ISSUE TITLE
Error with serializableModel?

### ISSUE THREAD

**Issue by jtorres-viavansi** [swagger-api/swagger-codegen#3345]
Hi, I'm trying to generate an API with serializableModel=true. The API is generated correctly, however when I try to compile with maven I get a lot of errors of this type:

`error: method does not override or implement a method from a supertype`

I've revised generated model and all errors occurs with methods marked as @Override that it's supossed to implement Serializable methods, but should not be marked as @Overrride, maybe?

`@Override
  public boolean equals(java.lang.Object o)`

I use swagger-codegen-2.1.6. Thanks

**Comment by jtorres-viavansi** [comment]
More info: it seems that swagger-codegen generates a class Serializable as this:
`public class Serializable  implements java.io.Serializable`

Due to this class, maven gives the following error:
`cyclic inheritance involving Serializable`

And the mvn package fails.

**Comment by wing328** [comment]
Please try the latest master and provide the spec for repeating the issue.

**Comment by jtorres-viavansi** [comment]
Hi, a little more information. Some Java classes in the original project has the following signature:

```
public class RestResponseDTO<T extends Serializable> implements Serializable {
    ...
    public RestResponseDTO(T content) {
        this.content = content;
        this.httpStatusCode = HttpStatus.SC_OK;
    }
```
It's translated into this by codegen:

```
public class RestResponseDTO implements Serializable  {
 ...
  public RestResponseDTO content(Serializable content) {
    this.content = content;
    return this;
  }
```

The object "content" received by constructor is from generated class Serializable. Here goes the swagger.json specification: [http://descargas.viavansi.com/swagger.json](url)

Thanks for your help.

**Comment by wing328** [comment]
Seems like the spec is incorrect in describing the RESTful API.
```
"definitions":{"ConfigCadesDTO":{"type":"object"},"Serializable":{"type":"object"},"PrivateKey":
```
That's part of the spec and it declares an object named `Serializable`. I don't think that's correct.

Can you share more on how you generated/created the spec?

**Comment by jtorres-viavansi** [comment]
Sure. The API has been generated with annotations and swagger servlet, io.swagger.jersey.config.JerseyJaxrsConfig. The original model don't define any Serializable class, it seems that it's automatically generated by swagger at this point:

```
        "RestResponseDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content (class that extends from Serializable)",
                    "$ref": "#/definitions/Serializable"
                },
```

RestResponseDTO objects uses any object that implements serializable and it's considered by swagger as a class, not Serializable interface, maybe?

Here goes original RestResponseDTO object: [RestResponseDTO.zip](http://descargas.viavansi.com/swagger/RestResponseDTO.zip)

PD.: sorry I didn't provide formatted json, here goes a more readable version: [Formatted swagger.json](http://descargas.viavansi.com/swagger/swagger.json)

**Comment by letspeak** [comment]
I'm using swagger-codegen-2.1.6 and successfully generated serialized model classes through swagger-codegen-maven-plugin using serializableModel configOptions. However, I don't see the serialVersionUID added to the classes, neither I can find any documentation to include it. Any help would be appreciated. Thanks in advance.

**Comment by wing328** [comment]
@letspeak are you looking for the following line in the auto-generated models?
```
private static final long serialVersionUID = 1L;
```

Btw, 2.1.6 is pretty old. Please use the latest stable version 2.2.1 instead: https://github.com/swagger-api/swagger-codegen/releases

**Comment by letspeak** [comment]
Thanks @wing328 , even I have tried with 2.2.1 , however that did not added the below line:

private static final long serialVersionUID = 1L;

This is what I have in my pom, what else I'm missing

`
<configuration>
<inputSpec>${project.basedir}/src/main/resources/abc.yml</inputSpec>
<language>java</language>
<configOptions>
	<sourceFolder>gen</sourceFolder>
	<groupId>com.abc.xyz</groupId>
	<artifactId>abc-client-gen</artifactId>
	<artifactVersion>${project.version}</artifactVersion>
	<serializableModel>true</serializableModel>
</configOptions>
</configuration>

`

**Comment by wing328** [comment]
@letspeak I've filed https://github.com/swagger-api/swagger-codegen/pull/4311 to add the following line in the Java model when the `serializableModel` option is switched on:
```
  private static final long serialVersionUID = 1L;
```

**Comment by wing328** [comment]
@letspeak PR merged into master. Please pull the latest to give it a try.

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Comment by letspeak** [comment]
@wing328  that did work, thanks.
