### ISSUE TITLE
[csharp] [documentation] Missing double quotation mark in csharp sample code

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#3346]
##### Description

In swagger-codegen/modules/swagger-codegen/src/main/resources/csharp/api_doc.mustache the rows that create string in cSharp sample code is not correct because in c# string uses double quotation mark.

##### Swagger-codegen version

2.2.0

##### Suggest a Fix

            {{#hasAuthMethods}}{{#authMethods}}{{#isBasic}}
            // Configure HTTP basic authorization: {{{name}}}
            Configuration.Default.Username = 'YOUR_USERNAME';
            Configuration.Default.Password = 'YOUR_PASSWORD';{{/isBasic}}{{#isApiKey}}
            // Configure API key authorization: {{{name}}}
            Configuration.Default.ApiKey.Add('{{{keyParamName}}}', 'YOUR_API_KEY');
            // Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
            // Configuration.Default.ApiKeyPrefix.Add('{{{keyParamName}}}', 'Bearer');{{/isApiKey}}{{#isOAuth}}
            // Configure OAuth2 access token for authorization: {{{name}}}
            Configuration.Default.AccessToken = 'YOUR_ACCESS_TOKEN';{{/isOAuth}}{{/authMethods}}
            {{/hasAuthMethods}}

has to become

            {{#hasAuthMethods}}{{#authMethods}}{{#isBasic}}
            // Configure HTTP basic authorization: {{{name}}}
            Configuration.Default.Username = "YOUR_USERNAME";
            Configuration.Default.Password = "YOUR_PASSWORD";{{/isBasic}}{{#isApiKey}}
            // Configure API key authorization: {{{name}}}
            Configuration.Default.ApiKey.Add("{{{keyParamName}}}", "YOUR_API_KEY");
            // Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
            // Configuration.Default.ApiKeyPrefix.Add("{{{keyParamName}}}", "Bearer");{{/isApiKey}}{{#isOAuth}}
            // Configure OAuth2 access token for authorization: {{{name}}}
            Configuration.Default.AccessToken = "YOUR_ACCESS_TOKEN";{{/isOAuth}}{{/authMethods}}
            {{/hasAuthMethods}}

**Comment by wing328** [comment]
@lunat thanks for reporting the issue. That was my mistake and I'll submit a PR with the fix.

**Comment by wing328** [comment]
@lunat #3358 has been merged into master to address the issue. Please pull the latest master to give it a try.
