### ISSUE TITLE
Relative links not handled correct

### ISSUE THREAD

**Issue by mosling** [swagger-api/swagger-codegen#3347]
##### Description

Trouble using relative links.

Using a reference: `"$ref": "user.json" `
Starting swagger-codgen-cli with  `-i http://localhost:8282/schema/rest/v1/swagger.json`

`user.json` is available under `http://localhost:8282/schema/rest/v1/user.json` but not found by codegen.

I can't change this notation for relative links because:

- it's conform to JSON schema
- I use JsonSchemaValidator to validate json documents and this tool doesn't work with "./user.json"

##### Swagger-codegen version

2.2.0-SNAPSHOT

##### Suggest a Fix

It looks that `io.swagger.models.refs.GenericRef` is wrong. The default case is INTERNAL link.

**Comment by wing328** [comment]
Is the issue similar to this one: https://github.com/swagger-api/swagger-codegen/issues/1551 ?

**Comment by crankydillo** [comment]
Pretty sure this is the same as [this swagger-core issue #1730](https://github.com/swagger-api/swagger-core/issues/1730).  Even though, I discuss '#' my fundamental problem is the exact same (i.e. [json-schema-validator](https://github.com/daveclayton/json-schema-validator) not liking './').

As an aside, my thinking is that validator library should support './user.json'; however, the treatment of $ref is moderately confusing, so I'm hesitant to claim certainty:)

**Comment by fehguy** [comment]
@crankydillo This was just addressed in the swagger-parser project.  The `./a.json` !== `a.json` is actually a URI design, and needs to be specially-cased for "reasonable, expected" behavior.  [See here.](https://github.com/swagger-api/swagger-parser/blob/9a848c416cf17a4ccd9718f44d2288000d3da1f9/modules/swagger-parser/src/main/java/io/swagger/parser/processors/ExternalRefProcessor.java#L117-L145)

**Comment by fehguy** [comment]
This should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4094/commits/92af2cf8211a61291547eee137fdddaf862495e1
