### ISSUE TITLE
[C#] Enum casing is lost in the generated client

### ISSUE THREAD

**Issue by jdebbink** [swagger-api/swagger-codegen#3348]
##### Description

Enum value casing is not preserved in the generated library

For example if there is an enum with the following definition:
```
public enum MyEnum
{
  InProgress
}
```

The genereated enum will look like:
```
public enum MyEnum
{
   [EnumMember(Value = "InProgress")]
   Inprogress  // case is lost
}
```

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

The casing is preserved in the swagger definition file
```
{"swagger":"2.0","info":{"version":"v1","title":"WebApplication1"},"host":"localhost:63332","schemes":["http"],"paths":{"/api/Values":{"post":{"tags":["Values"],"operationId":"Values_Post","consumes":["application/json","text/json","application/xml","text/xml","application/x-www-form-urlencoded"],"produces":[],"parameters":[{"name":"value","in":"body","required":true,"schema":{"$ref":"#/definitions/MyRequest"}}],"responses":{"204":{"description":"No Content"}},"deprecated":false}}},"definitions":{"MyRequest":{"type":"object","properties":{"Status":{"enum":["InProgress"],"type":"string"}}}}}
```

##### Command line used for generation

```
java -jar swagger-codegen-cli.jar generate -i http://localhost:63332/swagger/docs/v1 -l csharp -o CSharpClient/generated/ -D packageName=Test.Service
```

##### Steps to reproduce

- In Visual Studio, create a new Web API project
- Add Swashbuckle via nuget
- In ```SwaggerConfig.cs``` add:
```
c.DescribeAllEnumsAsStrings();
```
- In the default API controller add something like the following:
```
public class MyRequest
	{
		public MyEnum? Status { get; set; }
	}

	public enum MyEnum
	{
		[Display(Name = "InProgress")]
		InProgress
	}

	public class ValuesController : ApiController
	{
		[HttpPost]
		public void Post(MyRequest value)
		{
			Console.WriteLine(value.Status);
		}
	}
```
- Launch the project locally and run the code generation:
```
java -jar swagger-codegen-cli.jar generate -i http://localhost:63332/swagger/docs/v1 -l csharp -o CSharpClient/generated/ -D packageName=Test.Service
```

**Comment by wing328** [comment]
@jdebbink we did make some improvement to C# enum in the latest master.

Please pull the latest to give it a try.

**Comment by jdebbink** [comment]
@wing328 Just built master and this issue still exists.

**Comment by wing328** [comment]
The fix (#3360) has been merged into master. Please pull the latest to give it a try.

Thanks for reporting the issue.

**Comment by jdebbink** [comment]
@wing328 I just pulled and built the latest and the issue still exists.

**Comment by wing328** [comment]
I did a test and works for me
```
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {

            /// <summary>
            /// Enum InProgress for "InProgress"
            /// </summary>
            [EnumMember(Value = "InProgress")]
            InProgress
        }
```
Have you done a `mvn clean package`?

**Comment by jdebbink** [comment]
That did the trick - thanks!

**Comment by jdebbink** [comment]
I submitted a PR to update the readme to use ```mvn clean package``` as the default way to build. 
https://github.com/swagger-api/swagger-codegen/pull/3361
