### ISSUE TITLE
[C#] automatically generate nuspec file

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3350]
##### Description

We want to automatically generate nuspec file ([example](https://github.com/twilio/twilio-csharp/blob/master/Twilio.nuspec)) for C# API client so that the C# API client can be easily packaged into NuGet library using the following command:

```
nuget pack <project_file> -OutputDirectory <temp_path>
```

Ref: https://docs.nuget.org/create/nuspec-reference
##### Swagger-codegen version

Latest master
##### Suggest a Fix/Solution

If anyone wants to work on this, please reply to let us know. Thanks!

**Comment by jimschubert** [comment]
I can pick this up.

**Comment by wing328** [comment]
Closed via #4576. Thanks for the contribution from @jimschubert
