### ISSUE TITLE
[C#] add an option to implement INotifyPropertyChanged in generated model

### ISSUE THREAD

**Issue by tdjastrzebski** [swagger-api/swagger-codegen#3356]
##### Description

Please add an option to implement INotifyPropertyChanged in generated model.
##### Swagger-codegen version

1.0

**Comment by wing328** [comment]
@tdjastrzebski thanks for the suggestion. May I know if you've cycle to contribute the feature?

**Comment by jimschubert** [comment]
@tdjastrzebski @wing328 This can easily be done using https://github.com/Fody/PropertyChanged. We could then make the `INotifyPropertyChanged` functionality optional as many devs are passionate about not using `INotifyPropertyChanged` when it's not being used.

**Comment by wing328** [comment]
@jimschubert thanks for sharing https://github.com/Fody/PropertyChanged. The solution looks very neat.

I've marked the task as "Need community contribution" to see if anyone's cycle to make the contribution.

I believe we'll start with C# API client to begin with, and then C# server stub (ASP.NET core and NancyFx)

**Comment by jimschubert** [comment]
@wing328 I'll look at doing this using Fody. It should be relatively simple.

**Comment by jimschubert** [comment]
I've implemented this for .NET 4 and higher in PR #3547. It's a lot easier to maintain and test if we limit the feature to the newer framework version.

@wing328 .NET Core support would have to apply the changes manually to the models, unless we wait for .NET Core projects to go back to MSBuild-based. Then we could just use Fody there, too.

**Comment by wing328** [comment]
@tdjastrzebski PR merged into master. Please pull the latest to give it a try.

**Comment by jimschubert** [comment]
@tdjastrzebski I'd be interested to know if you've tried this and if it is working for you.

**Comment by wing328** [comment]
Closing this as there's no update.
