### ISSUE TITLE
[PHP] problem with transforming array properties in ObjectSerializer 

### ISSUE THREAD

**Issue by corleonis** [swagger-api/swagger-codegen#3362]
There is a change on the `ObjectSerializer` for PHP which can be seen here: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache#L180

This is serious change from previous behaviour, so before we used to get the default option which was CSV and now this will return following:

for given array of values:
["val1", "val2", "val3"]

result would be:
0=val1&1=val2&2=val3

where the above string gets passed to the actual query parameters and the resulting URL will have this format:
http://service.com/api/getValue?values=0=val1&1=val2&2=val3

That's actually an invalid query parameter. Is that behaviour expected and/or wanted, or am I missing something?

**Comment by arnested** [comment]
You should only run into that line of code if your parameter is defined with `collectionFormat: multi`. CSV is still the default collection format.

Can you post the part of your specification defining the parameter?

**Comment by wing328** [comment]
Closing this as there's no further update.

**Comment by FireLizard** [comment]
What was the solution to this issue, @wing328 @corleonis  ?
