### ISSUE TITLE
[JavaScript] Reference to non-existent "ApiClient.default" variable in sample code

### ISSUE THREAD

**Issue by michaelkourlas** [swagger-api/swagger-codegen#3363]
##### Description

The JavaScript sample code in README.md generated for a Swagger specification using HTTP basic authentication references an `ApiClient.default` field that does not exist:

```javascript
var Test = require('test');

var defaultClient = Test.ApiClient.default;

// Configure HTTP basic authorization: basicAuth
var basicAuth = defaultClient.authentications['basicAuth'];
basicAuth.username = 'YOUR USERNAME'
basicAuth.password = 'YOUR PASSWORD'

var api = new Test.DefaultApi()

var callback = function(error, data, response) {
  if (error) {
    console.error(error);
  } else {
    console.log('API called successfully.');
  }
};
api.testPost(callback);
```

##### Swagger-codegen version

Current master ([0986acd](https://github.com/swagger-api/swagger-codegen/tree/0986acd2a6e542ca74188c4d3fb13f8241cf42eb))

##### Swagger declaration file content or url

````json
{
  "info": {
    "title": "test",
    "version": "0.1.0"
  },
  "paths": {
    "/test": {
      "post": {
        "description": "Test description.",
        "responses": {
          "200": {
            "description": "Test description."
          }
        },
        "security": [
          {
            "basicAuth": []
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  },
  "swagger": "2.0" 
}
````

##### Command line used for generation

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i <JSON file> -l javascript -o <Output directory>`

##### Steps to reproduce

Use the Swagger specification defined above to generate a JavaScript API with the default options (i.e. the command line specified above) and then try to use the sample code in README.md.

##### Suggest a Fix

`ApiClient` exports an `instance` variable -- is this what should be used instead of `default`?

````javascript
  /**
   * The default API client implementation.
   * @type {module:ApiClient}
   */
  exports.instance = new exports();
````

**Comment by wing328** [comment]
@michaelkourlas thanks for reporting the issue and suggesting a fix.

Do you mind submitting a PR with the suggested fix and we'll review?

Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/README.mustache#L61

**Comment by michaelkourlas** [comment]
[Done.](https://github.com/swagger-api/swagger-codegen/pull/3364)
