### ISSUE TITLE
[Python] Online editor generates incorrect auth_settings with oauth

### ISSUE THREAD

**Issue by OmarShehata** [swagger-api/swagger-codegen#3366]
##### Description

When using the online [editor](http://editor.swagger.io/) the generated Python code ignores the oauth2 security definition. _This bug is not there when cloning and running locally._

##### Steps to reproduce

Go to the [editor](http://editor.swagger.io/), select File>Open Example and choose **security.yaml**.

Then Generate Client>Python. Download, extract and look at swagger_client/configuration.py. Line 220 is where the auth_settings function is, and it will have:

````python
    def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'internalApiKey':
                {
                    'type': 'api_key',
                    'in': 'header',
                    'key': 'api_key',
                    'value': self.get_api_key_with_prefix('api_key')
                },

        }
````

Which is missing entries for **petstoreImplicit** and **githubAccessCode**. To be sure, you can try to change internalApiKey's type from api_key to oauth2 in the yaml, and if you regenerate, it will disappear leaving you with an empty object in the function. 

So this shows that security definition objects of oauth2 are being ignored.

##### Suggest a Fix

Since this bug only exists in the online editor (I tried generating the same yaml file locally and it does indeed generate the right security definition object), I think it might be related to this issue which was recently fixed:

https://github.com/swagger-api/swagger-codegen/issues/3064

Perhaps the online server just hasn't been updated yet? I thought I should report it nonetheless.

**Comment by wing328** [comment]
@OmarShehata editor.swagger.io uses https://generator.swagger.io to generate SDKs and the generator is not using the latest master of Swagger Codegen.

Please pull the latest and build the JAR locally to generate API clients, server stubs or documentation.

**Comment by ianseyer** [comment]
This does not resolve the issue for me using the `petstore-full` example (compiled locally).

```
    def auth_settings(self):
        """
        Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'api_key':
                {
                    'type': 'api_key',
                    'in': 'header',
                    'key': 'api_key',
                    'value': self.get_api_key_with_prefix('api_key')
                },

        }
```

Despite there being a `petstore_auth` object that is referenced in `api_client.py`.

**Comment by wing328** [comment]
@ianseyer I saw you replied to 2 different threads about python authentication issue. Please open a new issue with the details (e.g spec to reproduce the issue) and you can link the new issue to those you've left comments.

**Comment by ianseyer** [comment]
Yes - one is for my personal spec (a WIP).

This is for the petstore-full example, so I felt it was appropriate here.

**Comment by wing328** [comment]
I'm not saying it's not appropriate. I'm just making a suggestion so that your issue would have a higher chance to draw attention from the community and the core team.

**Comment by ianseyer** [comment]
I see; I have opened an issue relating to my own code at #3435.
However I still consider this issue open, as using entirely example material and an up-to-date version of `swagger-codegen` is producing invalid code.

**Comment by fehguy** [comment]
@wing328 the online generator is running 2.2.0 now, fyi
