### ISSUE TITLE
Problem Generating C# library for bitbucket.com API / Groovy works

### ISSUE THREAD

**Issue by jerrywiltse** [swagger-api/swagger-codegen#3376]
##### Description
Error when loading swagger file, and then separate error when generating C# library.  Meanwhile, Groovy library seems to generate successfully.  I did not test others. 

First error: 
> ✖ Swagger Error
> Path parameter is defined but is not declared: key
> Jump to line 7860
> Details
>  Object
> code:  "MISSING_PATH_PARAMETER_DECLARATION"
> message:  "Path parameter is defined but is not declared: key"
>  path: Array [5]
> level: 900
> type:  "Swagger Error"
> description:  "Path parameter is defined but is not declared: key"
> lineNumber: 7860

Second Error
> "Unable to build target: Could not process model 'branchrestriction'"

##### Swagger-codegen version

N/A - Current URL

##### Swagger declaration file content or url

http://api.bitbucket.com/swagger.json

##### Command line used for generation

Using this URL:
http://editor.swagger.io/#/

##### Steps to reproduce

navigate to URL http://editor.swagger.io/#/

**Comment by wing328** [comment]
I imported http://api.bitbucket.com/swagger.json into editor.swagger.io and got some errors and warnings, e.g.
```
Path parameter is defined but is not declared: key
```
You will need to check with the bitbucket team to fix the issue with the spec.
