### ISSUE TITLE
URLSearchParams.toString()  After the conversion is complete. Is null

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#3381]
_From @ToBePlus on July 14, 2016 9:6_

**Swagger File**

``` yaml
 # paste your swagger document here
```
- Version: 
- Browser/OS: 

**Issue**

public userRegisterSmsPost (mobile: string, rnd: string, sign: string, extraHttpRequestParams?: any ) : Observable<models.CommonResponse> {
        const path = this.basePath + '/user/register/sms';

```
    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    let formParams = new URLSearchParams();

    // verify required parameter 'mobile' is set
    if (!mobile) {
        throw new Error('Missing required parameter mobile when calling userRegisterSmsPost');
    }
    // verify required parameter 'rnd' is set
    if (!rnd) {
        throw new Error('Missing required parameter rnd when calling userRegisterSmsPost');
    }
    // verify required parameter 'sign' is set
    if (!sign) {
        throw new Error('Missing required parameter sign when calling userRegisterSmsPost');
    }
    headerParams.set('Content-Type', 'application/x-www-form-urlencoded');

    formParams['mobile'] = mobile;

    formParams['rnd'] = rnd;

    formParams['sign'] = sign;

    let requestOptions: RequestOptionsArgs = {
        method: 'POST',
        headers: headerParams,
        search: queryParameters
    };
    requestOptions.body = formParams.toString();   //toString() = "";
   //**After the conversion is complete. Is null**

    return this.http.request(path, requestOptions)
        .map((response: Response) => response.json());
}
```

**formParams.toString(); After the conversion is complete. Is null**

_Copied from original issue: swagger-api/swagger-editor#1004_

**Comment by wing328** [comment]
@tobeplus please pull the latest master to give it a try. If the issue still occurs, please provide the spec and which language you're referring to.

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by ku6ryo** [comment]
This happens in my environment. Could you re-open and take a look?

GoogleChrome: 56.0.2924.87 (Official Build) (64-bit)
SwaggerCodegen: 2.2.1
Lang: Angular2
TypeScript: 2.0.3

240     public uploadThumbnail (id: string, file: any, extraHttpRequestParams?: any ) : Observable<models.Thumbnail> {
241         const path = this.basePath + '/project/project/{id}/thumbnail'
242             .replace('{' + 'id' + '}', String(id));
243 
244         let queryParameters = new URLSearchParams();
245         let headerParams = this.defaultHeaders;
246         let formParams = new URLSearchParams();
247 
248         // verify required parameter 'id' is not null or undefined
249         if (id === null || id === undefined) {
250             throw new Error('Required parameter id was null or undefined when calling uploadThumbnail.');
251         }
252         // verify required parameter 'file' is not null or undefined
253         if (file === null || file === undefined) {
254             throw new Error('Required parameter file was null or undefined when calling uploadThumbnail.');
255         }
256         headerParams.set('Content-Type', 'application/x-www-form-urlencoded');
257 
258         formParams['file'] = file;
259         
260         let requestOptions: RequestOptionsArgs = {
261             method: 'POST', 
262             headers: headerParams,
263             search: queryParameters
264         };  
265         requestOptions.body = formParams.toString();
266                              
267         return this.http.request(path, requestOptions)
268             .map((response: Response) => {
269                 if (response.status === 204) {
270                     return undefined;    
271                 } else {                 
272                     return response.json();
273                 }                        
274             });                          
275     }

**Comment by ku6ryo** [comment]
at line 265, toString() returns nothing
