### ISSUE TITLE
Generated JAVA API does not support file upload

### ISSUE THREAD

**Issue by u1982** [swagger-api/swagger-codegen#3389]
##### Description

I generated a Java API which should allow me to upload files, but it does not. Looks like there is something wrong with choosing the right content type

##### Swagger declaration file content or url

#...
basePath: /
produces:
  - application/json
paths:
  /1/upload:
    post:
      summary: Upload document
      operationId: upload
      parameters:
     #...
        - name: file1
          in: formData
          description: File 1 
          required: true
          type: file
      responses:
        default:
          description: UploadResponse
          schema:
            $ref: '#/definitions/UploadResponse'         
#...
definitions:
  UploadResponse:
    type: object
    properties:
      taskId:
        type: string
#...

##### Steps to reproduce

1. Generate JAVA API
2. use upload

**Comment by wing328** [comment]
@u1982 have you tried to set a proper `consumes`?

e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L253

**Comment by u1982** [comment]
I did not. Thank you, that partially solves the problem. Now I can upload files. Unfortunately, now the Content Type multipart/form-data is also set for the Parameters, which should not be the case. Is there an option to change that in the swagger.yaml? Here is what I changed in the Class ApiClient to make it work:
`public Object serialize(Object obj, String contentType, Map<String, Object> formParams) throws ApiException {
    if (contentType.startsWith("multipart/form-data")) {
      FormDataMultiPart mp = new FormDataMultiPart();
      for (Entry<String, Object> param: formParams.entrySet()) {
        if (param.getValue() instanceof File) {
          File file = (File) param.getValue();
          mp.bodyPart(new FileDataBodyPart(param.getKey(), file, MediaType.APPLICATION_OCTET_STREAM_TYPE)); //originally, it is also //MediaType.MULTIPART_FORM_DATA_TYPE here
        } else {
          mp.field(param.getKey(), parameterToString(param.getValue()), MediaType.MULTIPART_FORM_DATA_TYPE);
        }
      }
      return mp;
    } else if (contentType.startsWith("application/x-www-form-urlencoded")) {
      return this.getXWWWFormUrlencodedParams(formParams);
    } else {
      // We let Jersey attempt to serialize the body
      return obj;
    }
  }
`

**Comment by wing328** [comment]
What do you mean by content type `multipart/form-data` set for parameter?j

Please share your spec via http://gist.github.com.

**Comment by u1982** [comment]
[Here](https://gist.github.com/u1982/3ba1a258b33ba0790d039a9c75d3b258) are HTTP Post like the autogenerated C# and Java clients produce. The C# Version works fine, the Java Version not. In the Java client's POST, everything what is declared in "parameters" in the swagger.yaml has the extra "Content-Type: multipart/form-data" which causes the error. In the C# client's POST the uploaded files Content-Type is application/octet-stream. 
Changing the ApiClient.java like I did [here](https://gist.github.com/u1982/14802327ce236fb7f35a127aee1c792a) forces the Java Client to produce a working HTTP POST.

**Comment by wing328** [comment]
For Java API client, can you try the `retrofit2` API client instead to see if it has the same issue?

Here is an FAQ on how to specify library: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk
