### ISSUE TITLE
Add the ability to use a refreshToken for the oauth2 authentication flow

### ISSUE THREAD

**Issue by gregra81** [swagger-api/swagger-codegen#3405]
##### Description

Swagger doesn't support refreshToken settings OOTB. We need that the security will include that parameter given that the securityDefenitions property will have an 'x-refreshTokenUrl' field in the swagger file
##### Swagger-codegen version

Version 2.2.0

**Comment by cbornet** [comment]
You mean that you have a refresh token URL different than the access token URL ? That's kinda weird...

**Comment by gregra81** [comment]
I know that generally API providers (such as Google) supply the same endpoint for access token and refresh token but there are API providers that supply different endpoints for that

**Comment by gregra81** [comment]
Opened a PR: https://github.com/swagger-api/swagger-codegen/pull/3409

**Comment by cbornet** [comment]
I have never seen a provider do that. Do you have examples ?
It doesn't seem to be possible in the rfc6749, is not supported by the swagger-spec and by the oauth frameworks I know of (spring-security, oltu, ...)

Also I don't think it is a good idea to modify the core classes for a vendor-extension. This should be handled at the codegen class / template level.

**Comment by gregra81** [comment]
Sure: Autodesk does that - https://developer.autodesk.com/en/docs/oauth/v2/reference/http/refreshtoken-POST/.

Regarding what you suggest - changing it in the class / template level - that means I'll have to change it in each class / template I want to use oauth (for each language). That doesn't sound right to me...

**Comment by cbornet** [comment]
Well, I don't know why Autodesk does that... Looks like a bad implementation of rfc6749 but that wouldn't be the first time...

**Comment by gregra81** [comment]
Looking at the specification (https://tools.ietf.org/html/rfc6749#page-10) it is unclear that access token and refresh token URLs should have the same endpoint... On what are you basing your statement that it is a bad implementation?

**Comment by cbornet** [comment]
https://tools.ietf.org/html/rfc6749#section-3 : only 2 endpoints on authorization server : authorize endpoint and token endpoint.

**Comment by gregra81** [comment]
ok, thank you for that.

**Comment by col-panic** [comment]
I guess this ticket could be marked closed, no?

**Comment by dflorey** [comment]
All API's that are created with https://apiary.io also provide a different URL for refreshing the access token.
See this generated API as an example:
https://fpme.docs.apiary.io/#reference/oauth/oauthtoken

Right now we are adding "x-refreshUrl" into the vendor extenstions to configure the auth, but this is really ugly.
