### ISSUE TITLE
swagger generated code is not encoding the url

### ISSUE THREAD

**Issue by pradeepkumarreddyk** [swagger-api/swagger-codegen#3406]
i have generated code for android and volley library. 

 using the generated code i have tried a get request. There were spaces in the arguments for get request, so i was getting the following exception : 
"java.util.concurrent.ExecutionException: com.android.volley.ServerError"

Why swagger is not encoding the url before doing a get request ?

**Comment by pradeepkumarreddyk** [comment]
The following is the url with space in query args. 
http://192.168.1.5:8080/krayon/api/v1/framework/lxlContentTitleCardLarge?args={"author":"Mr. Arvind"}

This url was encoded when i tried to do a get request and i got the following exception
"java.util.concurrent.ExecutionException: com.android.volley.ServerError"

**Comment by wing328** [comment]
Related issue https://github.com/swagger-api/swagger-codegen/issues/3202

**Comment by wing328** [comment]
PR: https://github.com/swagger-api/swagger-codegen/pull/3204

**Comment by wing328** [comment]
PR merged into master. Please pull the latest to give it a try.
