### ISSUE TITLE
NPE parsing referenced path parameters

### ISSUE THREAD

**Issue by diegode** [swagger-api/swagger-codegen#3412]
I described it here: https://github.com/swagger-api/swagger-parser/issues/268
I cross-post it since it is a serious bug introduced on 2.2.0 in the last minute (the latest 2.2.0-SNAPSHOT doesn't have it), so maybe it deserves to bump the version to 2.2.1 after fixing it.

**Comment by msrao10** [comment]
we are facing the same issue described here.  swagger codegen 2.1.6 works fine with referenced parameters in Path, but 2.2.0 fails with NPE.

Can we please reopen this issue.

**Comment by diegode** [comment]
@msrao10 @wing328 this is already fixed in swagger-parser's master branch.

**Comment by wing328** [comment]
@diegode I believe a patch version of swagger parser and codegen will be released soon.

I'll close this task after the release.

**Comment by fehguy** [comment]
The parser release candidate is in sonatype snapshots as 1.0.22-SNAPSHOT

**Comment by wing328** [comment]
@diegode @msrao10 I believe the issue should have been addressed with the latest version of swagger-parser. Please let me know if that's not the case.
