### ISSUE TITLE
[JAVA] dateLibrary=legacy not working in retrofit2

### ISSUE THREAD

**Issue by hoeggi** [swagger-api/swagger-codegen#3413]
##### Description

when using dateLibray=legacy in a config file or with -DdateLibrary generator still uses joda-time
##### Swagger-codegen version

2.2.0
##### Steps to reproduce

update java-petstore-retrofit2.json to:

```
{
    "library": "retrofit2",
    "artifactId": "swagger-petstore-retrofit2",
    "dateLibrary": "legacy"
}
```

and run java-petstore-retrofit2.sh
### 

Expected output: java.util.Date is used
Actual output: joda-time is used
##### Suggest a Fix

I think the problem is that the templates use syntax like this:

```
{{^java8}}
import org.joda.time.DateTime;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormatter;
import org.joda.time.format.ISODateTimeFormat;
{{/java8}}
{{#java8}}
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
{{/java8}}
```

If i change templates to:

```
{{#joda}}
import org.joda.time.DateTime;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormatter;
import org.joda.time.format.ISODateTimeFormat;
{{/joda}}
{{#java8}}
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
{{/java8}}
```

everything works as expected since joda is used as default and when adding =legacy nothing of that gets used. 

I can make a PR and go over all the templates if this changes are ok/if this is really a bug and not intended. 

Also if this happens with other java libraries i can also take a look at those template files.

**Comment by wing328** [comment]
@hoeggi thanks for reporting the issue and proposing the fix. Do you mind submitting a PR so that we can review the fix?

cc @cbornet

**Comment by hoeggi** [comment]
yes, i can do this tomorrow.

**Comment by cbornet** [comment]
Indeed, the joda imports and dependency are still pulled but java.util.Date should be used in the model and api for date and dateTime properties.

**Comment by cbornet** [comment]
Warning : the tag "joda" doesn't exist !

**Comment by hoeggi** [comment]
what do you been by the tag does not exist? can you point me in some direction for this please because i was assuming the tags in the templates where arbitrary as long as the generator knows about them.

**Comment by cbornet** [comment]
I mean that setting dateLibrary=joda currently doesn't set a "joda" flag in additionalProperties.
Can you check if your model was generated with java.util.Date date/date-time ?

Also, I don't think it is a big issue to include joda mappers if "legacy" dates are used.

Are you trying to generate for a legacy app ? If you can, you should try to migrate to joda since it's way better than java.util.Date.

**Comment by hoeggi** [comment]
as far as i can see joda gets set in additional properties here: 
[https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java#L230](url)

that results in 2 entries:

`10 = {HashMap$Node@1663} "dateLibrary" -> "joda"
15 = {HashMap$Node@1698} "joda" -> "true"`

I'm using the retrofit2 code for an android project and since I'm not really having any date/time related usecases in the app i didn't want to have joda as an additional dependency.

So far I have updated all templates for feign, jersy2, okhttp-gson and retrofit2 + their samples. so far the output looks good and i can send a PR for you to take a look at.

**Comment by hoeggi** [comment]
also there is https://github.com/dlew/joda-time-android for android because of performance issues and since all build.gralde.mustache files already contain switches for android, maybe it's a good idea to add a switch for this depencency too? but i guess this should go into it's own issue.

**Comment by cbornet** [comment]
So in the end dateLibrary=legacy works fine ! It's just that it's not optimal on android because of the joda lib footprint. So it can be improved and your PR is welcome !

Note: I don't see any  ```additionalProperties.put("joda", "true");``` in the code you linked but it's easy to add...

**Comment by hoeggi** [comment]
what do you think about a new PR to update build.gradle files to use joda-android instead of the default joda-time lib if running an android?

**Comment by cbornet** [comment]
Sorry, I hadn't seen ```additionalProperties.put(dateLibrary, "true");```...

**Comment by hoeggi** [comment]
well you where right, it was not getting added if nothing was specified, i changed those lines to add joda if dateLibrary is missing so it is always set as default

**Comment by cbornet** [comment]
@hoeggi yes joda-time-android would be a nice addition for android users.

Also if you really want to use java.util.Date on android, note that currently only the okhttp-gson library has a full support of rfc3339 format for "date" and "date-time" types.

**Comment by wing328** [comment]
I believe this issue can be closed.
