### ISSUE TITLE
Java language inflector does not handle inheritance in the same way as jaxrs-spec

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-codegen#3414]
##### Description

It appears that the fixes for inheritance for the Java servers, jaxrs and family did not make it into the inflector language.

##### Swagger-codegen version

2.2.0

swagger-codegen-plugin
version 2.2.0

##### Related issues
https://github.com/swagger-api/swagger-codegen/pull/3393

**Comment by cbornet** [comment]
Did you test on 2.2.0 or master ?

**Comment by jeff9finger** [comment]
2.2.0. It seems to work in 2.2.1-SNAPSHOT. Was hoping to have this in 2.2.0.

closing.
