### ISSUE TITLE
[JavaScript] String Enum types produce invalid code

### ISSUE THREAD

**Issue by xyin96** [swagger-api/swagger-codegen#3416]
##### Description

Enum types produce invalid JavaScript when dealing with `String` constants

##### Swagger-codegen version

Latest (2.2.0)

##### Swagger declaration file content or url

Given a swagger definition for an `Enum` type:

```json
"deviceType": {
          "enum": [
            "ANDROID",
            "UNKNOWN",
            "IOS"
          ],
          "type": "string"
        },
```

The generated JS client looks like this

```javascript
exports.DeviceTypeEnum = {
    /**
     * value: ANDROID
     * @const
     */
    "ANDROID": ANDROID,


    /**
     * value: UNKNOWN
     * @const
     */
    "UNKNOWN": UNKNOWN,


    /**
     * value: IOS
     * @const
     */
    "IOS": IOS

  };
```

Which is invalid javascript, since the constants `IOS`, `UNKNOWN`, etc. are `undefined`. 

##### Proposed fix

We've worked around this by adding in double quotes to the templates:

```
exports.{{datatypeWithEnum}} = {
  {{#allowableValues}}
  {{#enumVars}}
{{#emitJSDoc}}
    /**
     * value: {{{value}}}
     * @const
     */
{{/emitJSDoc}}
    "{{name}}": "{{{value}}}"{{^-last}},
    {{/-last}}
  {{/enumVars}}
  {{/allowableValues}}
  };
```

##### Command line used for generation

```
swagger-codegen generate -i $SWAGGER_URL \
    -l javascript \
    -o clients/javascript/ \
    --additional-properties usePromises=true,projectName=test-project 
```

**Comment by wing328** [comment]
@xyin96 our test does not have the issue you described: https://github.com/swagger-api/swagger-codegen/blob/90857e898884238d61dbfbd3ede5c7cc57de483f/samples/client/petstore/javascript/src/model/EnumTest.js#L107

Have you done a `mvn clean package` to build the jar before generating the JS API client?

**Comment by xyin96** [comment]
I realized I was using swagger-codegen (installed from Homebrew) which seems to have an outdated version.

This issue doesn't come up when we run the codegen through the JAR
