### ISSUE TITLE
[java, jaxrs*, inflector] sub class does not contain defined properties

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-codegen#3420]
##### Description

A model defined using an allOf does not contain any defined properties in the class. The properties from the base class are now not included, but the defined properties are not included.

##### Swagger-codegen version

2.2.0, 2.2.1-SNAPSHOT

##### yaml file

```yaml
swagger: '2.0'

info:
  version: "1.0.0"
  title: Foo Bar
host: 'localhost:8080'
basePath: /base
schemes:
  - http
paths:
  /test:
    get:
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FooObject'
      operationId: getFooObject
definitions:
  FooObject:
    properties:
      myObj:
        $ref: '#/definitions/SubModel'
  ModelType:
    type: string
    enum:
    - TypeA
    - TypeB
    - TypeC
  BaseModel:
    discriminator: model_type
    required:
      - model_type
    properties:
      id:
        type: integer
        format: int64
      model_type:
        $ref: '#/definitions/ModelType'
  SubModel:
    allOf:
      - $ref: '#/definitions/BaseModel'
    properties:
      prop_a:
        type: string
      prop_b:
        type: string
```
##### Command line used for generation

generate source using any of the java languages: java, jaxrs-spec, inflector, etc

**Comment by jeff9finger** [comment]
Looks like the properties have to be indented.
```yaml
  SubModel:
    allOf:
      - $ref: '#/definitions/BaseModel'
      - properties:
          prop_a:
            type: string
          prop_b:
            type: string
```

Is that the correct solution?

**Comment by markaevans7** [comment]
I have the same problem.  If the yaml definition has the "allOf:" statement, then the generated Java class will extend the $ref class BUT NOT include the other properties listed in the class.  (If the yaml does not have the "allOf:", then the Java class does include the properties.

If this is my YAML:
 MyObjDef:
    allOf:
      - $ref: "#/definitions/MyBody"
    properties:
      requestType:
        type: string

Then java class MyObjDef extends MyBody but does NOT include the requestType field.

If this is my YAML:
  MyObjDef:
    properties:
      requestType:
        type: string

Then java class MyObjDef (does not extend MyBody -- ok) and does include the requestType field (ok).  But does not accomplish my goals.

If I try to use the format proposed above (hyphen before "properties:" and indent it), then the SwaggerEditor fails to parse (Bad indentation of a mapping entry at line XXX, column Y: - properties:").

**Comment by fehguy** [comment]
@markaevans7 that definition isn't valid.  Try this instead:

```yaml
MyObjDef:
    allOf:
      - $ref: "#/definitions/MyBody"
      - type: object
        properties:
          requestType:
            type: string
```

items in `allOf` MUST be in an array

**Comment by markaevans7** [comment]
Thank you fehguy!  That did it.

Note that the "properties" MUST be aligned 2 spaces to the right of the "-type object".  Without that indentation (which the SwaggerEditor does NOT complain about), the properties are NOT defined.

With "properties:" indented (as above in fehguy's post), the Java code DOES extend MyBody and DOES include the properties (requestType in this example).

**Comment by fehguy** [comment]
great, but do note that the leading `-` is required.  I'll close this, thanks for reporting back!
