### ISSUE TITLE
[JAVA] Generated enum code contains html character codes &gt; &lt; leading to compilation errors

### ISSUE THREAD

**Issue by cbrainerd** [swagger-api/swagger-codegen#3421]
##### Description

Generated Java code contains html character codes `&gt;`, `&lt;` within code for List of enums where `>` or `<` would be expected. Example:

`public enum List&lt;Prop1Enum&gt; {`

This causes the generated code to fail to compile.

##### Swagger-codegen version

v2.2.0
Also tried latest master which exhibited the same issue.

##### Swagger declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "title": "test",
    "version": "0.1"
  },
  "consumes": [
    "application/json"
  ],
  "paths": {
    "/test/1/test": {
      "get": {
        "responses": {
          "200": {
            "description": "testing",
            "schema": {
              "$ref": "#/definitions/ExtendedDef"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BaseDef": {
      "properties": {
        "prop1": {
          "items": {
            "enum": [
              "one",
              "two"
            ],
            "type": "string"
          },
          "type": "array"
        }
      }
    },
    "ExtendedDef": {
      "allOf": [
        {
          "$ref": "#/definitions/BaseDef"
        },
        {
          "properties": {
            "prop2": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}

```

This results in code:
```java
package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;


/**
 * BaseDef
 */
public class BaseDef   {
  

  /**
   * Gets or Sets prop1
   */
  public enum List&lt;Prop1Enum&gt; {
    

    private List&lt;String&gt; value;

    List&lt;Prop1Enum&gt;(List&lt;String&gt; value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }


  /**
   * Gets or Sets prop1
   */
  public enum Prop1Enum {
    @SerializedName("one")
    ONE("one"),

  // <SNIP> Everything beyond here seems to be fine.
```

##### Command line used for generation
` java -jar ../swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i spec.json -l java -o sdk_bug_java`

##### Steps to reproduce

* Save the above swagger spec as spec.json
* Use above command line to generate Java code
* See `&gt;` and `&lt;` in `sdk_bug_java/src/main/java/io/swagger/client/model/BaseDef.java`

##### Related issues
Some similarity to #3355 but not an exact match. (Locations of encoded character differs).

I tried the workaround anyway `library=okhttp-gson` but the issue was unchanged.

**Comment by wing328** [comment]
Is there by any chance you're still using v2.1.6?

I tested with latest master and 2.2.0 JAR but couldn't repeat the issue.

**Comment by cbrainerd** [comment]
I'm using 2.2.0:
`git checkout v2.2.0`
`mvn package`

However, it seems I can only reproduce this on my Mac (El Capitan 10.11.5). I tried to reproduce on Ubuntu and the code generated and compiled correctly.

**Comment by wing328** [comment]
I'm using Mac.

Can you try 'mvn clean package' instead?

**Comment by cbrainerd** [comment]
I ran `mvn clean package` and re-ran codegen. I am no longer seeing the encoded characters and it compiles fine now. Sorry for the bother!

**Comment by wing328** [comment]
@cbrainerd np. Glad to hear that you've the issue resolved.

**Comment by mspmax** [comment]
@wing328 I'm getting similar kind of an issue for android. I'm using swagger-codegen version 2.2.0

**Error segment**

`public enum List&lt;ScopesEnum&gt; {
     Catalog,  Commerce,  Settings, 
  };`

**Related Definition from the server**
`AccountTokenRequest: {
type: "object",
required: [],
additionalProperties: false,
properties: {
email: {
description: "The email associated with the account.",
type: "string"
},
password: {
description: "The password associated with the account.",
type: "string"
},
scopes: {
description: "The scope(s) of the tokens required. For each scope listed an Account and Profile token of that scope will be returned ",
type: "array",
items: {
type: "string",
enum: [
"Catalog",
"Commerce",
"Settings"
]
}
}
},
example: {}
},`

I'm using android with volley. Glad if you can help out with this issue.

**Comment by wing328** [comment]
@mspmax can you build the JAR based on the latest master and do a test to see if the issue still occurs?

**Comment by mspmax** [comment]
@wing328 Thanks for the quick reply. I did use latest master and did a 'mvn clean package' but the issue is still there. I tested it against okhhtp-gson codegen and it worked perfectly. I can give you the full URL of the spec if it's necessary.
