### ISSUE TITLE
Swagger Codegen 2.2.0 release notes error

### ISSUE THREAD

**Issue by andylowry** [swagger-api/swagger-codegen#3437]
##### Description

The "list" links for "breaking changes (without fallbacks)" and "breaking changes (with fallbacks)" are mixed up. The "with fallbacks" links leads to the "without fallbacks" list, and vice-versa.

This is at https://github.com/swagger-api/swagger-codegen/releases/tag/v2.2.0
 
##### Swagger-codegen version

2.2.0

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

Browse the release notes and click on either of the indicated links.

##### Related issues

None

**Comment by wing328** [comment]
@andylowry thanks for reporting the issue. I've just fixed it.
