### ISSUE TITLE
[csharp] RootNamespace and AssemblyName are incorrect for Project.mustache

### ISSUE THREAD

**Issue by jimschubert** [swagger-api/swagger-codegen#3441]
##### Description

Client generated assembly uses assembly name and default namespace of `Swagger Library` rather than `IO.Swagger` (as the project is defined). This breaks from common C# convention and causes problems when adding new files (tested in Xamarin, VS2015, Rider EAP).

##### Swagger-codegen version

2.2.0/master

##### Command line used for generation

n/a, sample code can be used for evaluation

##### Steps to reproduce

1. Open `samples/petstore/csharp/SwaggerClient/IO.Swagger.sln`
2. Build the solution
3. Inspect output artifacts
    - Notice: `bin/Debug/Swagger Library.dll`
    - Expected: `bin/Debug/IO.Swagger.dll`
4. Add a new file to the `IO.Swagger` project in your IDE of choice. 
    - Notice: `namespace Swagger Library {`
    - Expected: `namespace IO.Swagger {`

##### Related issues

n/a

##### Suggest a Fix

Change `packageTitle` in `Project.mustache` to `packageName`. The `packageTitle` property is intended for assembly metadata, not root namespace and assembly filename.

**Comment by jimschubert** [comment]
This is a simple fix to a problem I just encountered. Since I've already fixed it locally, I'll build and open a PR.

**Comment by wing328** [comment]
PR merged. Issue closed.
