### ISSUE TITLE
Regenerate Test files

### ISSUE THREAD

**Issue by zivSher** [swagger-api/swagger-codegen#3445]
##### Description

The Test folder seems to be generated only the first time you generate the SDK. Changes in the configuration files or the swagger file - don't trigger regeneration of the SDK.

Would be nice to Regenerate by default - OR using option that enables to choose whether to regenerate the 'Test' folder or not.
##### Swagger-codegen version

2.2.0
##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate   -i http://spark-dev-portal-dev-1.s3.amazonaws.com/greg/print_new_specs.json   -l javascript   -o samples/client/print/js

**Comment by cbornet** [comment]
```.swagger-codegen-ignore``` could be used to give the choice to the end user.

**Comment by zivSher** [comment]
Thanks @cbornet,
seems like this option meant to choose what NOT to regenerate/overwritten, but the question was about first allowing regeneration.

**Comment by cbornet** [comment]
Yes there is work to do in the generator to:
* allow overwriting the test files
* add the test directory to the generated .swagger-codegen-ignore

**Comment by wing328** [comment]
@zivSher the reason why we don't want to overwrite the test files is that the test file only contains the structure for developers to easily add test cases and we don't want the tests cases added by developers overwritten when regenerating the API client or server stub.

The direction is to leverage .swagger-codegen-ignore to replace `writeOptional` in the generator.

As a workaround, if you want regenerate a particular test file, just move it to another directory (for backup just in case you need it later) and the next run will create it.

**Comment by zivSher** [comment]
Thanks @wing328.

**Comment by gumble42** [comment]
@wing328 has this issue actually been resolved in the v2.3.0 milestone? I could not see any difference compared to v2.2.0 though...

**Comment by wing328** [comment]
@gumble42 for the issue, are you referring to the test files not being overwritten when regenerating the code?

**Comment by gumble42** [comment]
@wing328 yes, exactly. As the issue was closed recently I assumed that it was included in the v2.3.0 release.

**Comment by wing328** [comment]
@gumble42 that's by design as the test files may have already been updated by the developers. To regenerate the test files, please remove them before regenerating the client again.
