### ISSUE TITLE
[Spring] boot server with Jax-RS

### ISSUE THREAD

**Issue by jkerak** [swagger-api/swagger-codegen#3452]
##### Description

I would like to generate server code from a swagger YAML file that I created. I have found that I can generate a JAX-RS server, or a Spring Boot Server that uses springMVC controllers. I would like to use Jersey2 or something other than springMVC, but I also would like to do all my configuration in Java with spring boot rather than a web.xml. This does not seem to currently be a supported.

**Comment by cbornet** [comment]
There is no web.xml in the spring-boot codegen.
Also why do you want to use something else than spring-mvc in spring ? I don't see what you gain in changing for jersey...

**Comment by jkerak** [comment]
The only reason is that my client uses Jersey throughout their codebase, and they requested I use Jersey. I agree that it is apple and oranges - just wanted to make sure I understood correctly.

**Comment by cbornet** [comment]
I think there is little interest to do that in the generator. 
Now if you really need to generate jersey controllers, you could copy them from a generated jaxrs server to your generated spring boot app.

**Comment by jkerak** [comment]
thanks - that's exactly what I'm doing.
