### ISSUE TITLE
[Go] api.mustache not generating GetApiKeyWithPrefix Code

### ISSUE THREAD

**Issue by bitt-john** [swagger-api/swagger-codegen#3453]
modules/swagger-codegen/src/main/resources/go/api.mustache  not generating GetApiKeyWithPrefix Code on line 67

I have this problem with current stable and 2.2

line 66 has the template variable on the same line as the comment

// set key with prefix in querystring{{#hasKeyParamName}}
	queryParams["{{keyParamName}}"] =  a.Configuration.GetAPIKeyWithPrefix("{{keyParamName}}")

**Comment by wing328** [comment]
@bitt-john thanks for reporting the issue. I've filed #3458 to fix it.

cc @neilotoole @guohuang

**Comment by wing328** [comment]
@bitt-john PR merged into master. Please pull the latest to give it a try.
