### ISSUE TITLE
[Go] [Feature] API client should allow configurable http.Transport

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#3461]
##### Description

The generated code should allow the caller to:

- provide a custom `http.Client` (which is not possible given use of `resty`), or
- provide a custom `http.Transport` (and therefore also custom `tls.Config`: note that the TLS config is a field of the transport, so just providing access to the transport is sufficient).

##### Reasoning

There are circumstances under which a caller needs additional control over the `http.Client`. For example, if calling a HTTPS endpoint with a self-signed/expired cert (which is often the case during development), then the caller needs to be able to set `tls.Config.InsecureSkipVerify`.

The `resty` library we use does indeed provide a means to set both the transport and the TLS config (it doesn't allow the caller to provide a custom `http.Client`, but access to the transport address 90% of the use cases).

##### Solution

We add a `Transport *http.Transport` field to the generated `Configuration` object. Then rather than using `resty.R()`  (which uses resty's package-level `DefaultClient`, which we don't want to do), each of our generated APIs creates its own resty `Client` instance (using `restyClient := resty.New()`), and if there's a custom transport provided, we call `restyClient.SetTransport(config.Transport)` before making a request to the REST service.

##### Swagger-codegen version

`master`

**Comment by wing328** [comment]
> it doesn't allow the caller to provide a custom http.Client

I would recommend you to open a ticket to the resty github repo for the above. The author is pretty responsive to feature request and bug report.

**Comment by wing328** [comment]
cc @guohuang

**Comment by neilotoole** [comment]
Another really good example why we need the transport is so that the caller can specify a network timeout for the API.

**Comment by wing328** [comment]
@neilotoole right. Other API clients (e.g. Ruby, PHP, Java, etc) already supports configurable timeout for requests so it would be nice if we can provide the same in the Go API client.
