### ISSUE TITLE
Enums defined in json defination file could not able to create enums in Objective-c language.

### ISSUE THREAD

**Issue by Ravi-Impiger** [swagger-api/swagger-codegen#3478]
##### Description: 
Enums defined in json defination file could not able to generate enums in Objective-c language.
If you defined enum as a class then it will be generated with out enums.
all enum in models  classes are created as NSString prperty.

and ther eis no support for constants and macros.

##### Swagger-codegen version : 
: 2.2.0 (current stable version)

##### Swagger declaration file content or url
     http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation
 swagger-codegen generate -i $SWAGGER_URL -l objc

##### Steps to reproduce
Generate enums in objective -C thats it

**Comment by wing328** [comment]
@Ravi-Impiger ObjC API client does not support enum at the moment. There was a PR (not merged) before: https://github.com/swagger-api/swagger-codegen/pull/1185.

Would you have cycle to contribute the eum support for ObjC API client? If yes, I can show you some good starting points.

**Comment by wing328** [comment]
Duplicated: https://github.com/swagger-api/swagger-codegen/issues/1167
