### ISSUE TITLE
[Server:Spring] Operation groups configuration

### ISSUE THREAD

**Issue by ebelanger** [swagger-api/swagger-codegen#3497]
##### Description

Currently, the operations are grouped by the base path of an operation.  While it works for most scenarios, we have a little exception to this.  Our API has two context in the same API.  We have what we call user operations which are accessible to everyone and extended operations which are always prefixed with the /specialized path.  Some resources are shared by the contexts when the user may only have read access and the specialist has create, read or delete accesses.

On the server side, we would like to group the operations together in a controller since we are working with the same resources.  On the client side, we use tags to split the contexts.  We are using interface generation.

The problem we have is that the interface has a @RequestMapping class annotation so we cannot implement both interfaces on a controller, making us implement what is mostly the same class but with operations splitted between them.

Is there any way this could be made simpler?
##### Swagger-codegen version

2.2.0
##### Swagger declaration file content or url

``` yaml
'/invoice-items/{id}':
  get: ...
'/reseller/invoice-items/{id}':
  post: ...
  put: ...
  delete: ...
```
##### Suggest a Fix

 A simple fix would probably to not add a base path to the controller interface and put the full path in the method annotations.  There could also be different strategies for grouping operations?

**Comment by wing328** [comment]
To customize the logic in grouping operation, you will need to update this function: https://github.com/swagger-api/swagger-codegen/blob/d621021fb17f86cdde3389bb4530f06db3f0e486/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java#L177

You can also use customized mustache templates via the "-t" option.

**Comment by wing328** [comment]
@ebelanger here is another way to group the operations by `tags`: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaCXFServerCodegen.java#L46

**Comment by cbornet** [comment]
The problem with tags server side is that you risk to have 2 tags for the same path and that will generate 2 resources with the same path.

**Comment by fehguy** [comment]
If we reuse the code from the JAXRS implementations, we would only use the first tag when generating the resources.  Maybe that has changed or is different

**Comment by cbornet** [comment]
Spring behaviour was copied from JAXRS which is to (group by base path)[https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java#L131] instead of tag

**Comment by wing328** [comment]
@ebelanger please pull the latest master and try the following option for Spring:
```
	useTags
	    use tags for creating interface and controller classnames (Default: false)
```
