### ISSUE TITLE
[HTML] Bug generating static HTML, generator omits parameter's object type when using array of objects as parameter

### ISSUE THREAD

**Issue by dmelo** [swagger-api/swagger-codegen#3498]
##### Description

If you have a yaml API spec with and an endpoint have a parameter that is an array of objects, the static HTML generated from that don't have the details about the parameter, that it is an array of a certain object.

##### Swagger-codegen version

I'm using the latest commit on master branch: 1886abb9f9e654b54d28bcd0f09408d7476ac403

##### Swagger declaration file content or url

If you have the following yaml describing the parameters of an endpoint:

```yaml
      parameters:
          - name: list
            in: body
            required: true
            description: List of passages
            schema:
              title: List of passages
              type: array
              items:
                $ref: '#/definitions/Passage'
```

The generated HTML is:

```html
    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">list (required)</div>

      <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash; List of passages </div>
    </div>  <!-- field-items -->
```

It omits 1) the type array of the parameter and 2) the type of the array item

##### Command line used for generation

```bash
java -jar ~/proj2/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.yaml -l html -o html
```

##### Steps to reproduce

Use the swagger-codegen-cli to generate an the static HTML documentation from an swagger.yaml that contains an endpoint with an array of objects as parameter.

##### Related issues

None that I know.

##### Suggest a Fix

It is probably omitting it just for the lack of implementation of what to do with that information.

**Comment by wing328** [comment]
@dmelo thanks for reporting the issue. You can may want to pull the latest to master to generate `html2` documentation added via https://github.com/swagger-api/swagger-codegen/pull/3447.

Moving forward, we want to focus on `html2` as `html` is not actively maintained by anyone.

**Comment by dmelo** [comment]
That is awesome. Didn't know about `html2`. It is generating everything I need.
