### ISSUE TITLE
[JAVA] Feign client generator: HTTP Header params are getting converted to camel case

### ISSUE THREAD

**Issue by himanshu-mishra** [swagger-api/swagger-codegen#3502]
##### Description
For Java API Client using Feign as library, header param names are getting converted to came case  breaking the API. 
For example: header parameter **user-id** gets converted to **userId**.

##### Swagger-codegen version
2.2.0

##### Suggest a Fix
Issue is with Line 30 of api.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache#L30

Changing the template on left hand side from paramName to baseName fixes the issue.
From:
`"{{paramName}}: {{=<% %>=}}{<%paramName%>}<%={{ }}=%>"{{#hasMore}},`
To:
`"{{baseName}}: {{=<% %>=}}{<%paramName%>}<%={{ }}=%>"{{#hasMore}},`

**Comment by wing328** [comment]
@himanshu-mishra thanks for reporting the issue. Your suggested fix looks good to me. May I know if you've time to submit a PR for the fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md
