### ISSUE TITLE
Possible swagger hub codegen issue with Spring Data Mongo

### ISSUE THREAD

**Issue by mherb63** [swagger-api/swagger-codegen#3509]
##### Description
Mongo not able to map swagger code generated fields with domain model code generated from swaggerhub.

The following JSON is used on swaggerhub:
        "frameTransmissionPeriod": {
          "description": "SLM period for frame transmission",
          "type": "string",
          "enum": [
            "_10ms",
            "_100ms",
            "_1sec",
            "_10sec"
          ],
          "default": "_100ms"
        },

And here is the generated code (Server->Spring), note the uppercase "MS" and "SEC"
  public enum FrameTransmissionPeriodEnum {
    _100MS("_100ms"),
    _1SEC("_1sec"),
    _10SEC("_10sec");

    private String value;

    FrameTransmissionPeriodEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return value;
    }
  }

When reading from Spring Data mongo we have what's in Mongo:
		"ethOamDmmCfg" : {
			"testId" : "5555",
			"pmCosId" : 1,
			"vlanId" : 100,
			"frameTransmissionPeriod" : "_100ms",
			"frameSize" : "1028"
		},

And the following Mongo error:
2016-08-02 15:46:21.804 ERROR 79727 --- [nio-8680-exec-8] c.c.l.p.exception.ApiExceptionHandler    : No enum constant com.ciena.lion.mef.pm.domain.EthOamDmmCfg.FrameTransmissionPeriodEnum._100ms
java.lang.IllegalArgumentException: No enum constant com.ciena.lion.mef.pm.domain.EthOamDmmCfg.FrameTransmissionPeriodEnum._100ms
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:819)

##### Swagger-codegen version
swaggerhub.com

##### Suggest a Fix
at some point in time, the generated Spring code has upper-cased the enums and I believe this has caused the issue.  If I change "MS" and "SEC" to "ms" and "sec" in the generated domain model code, Mongo is happy.

**Comment by wing328** [comment]
@mherb63 are you saying the following enum name and value mapping is incorrect?
```
_100MS("_100ms"),
_1SEC("_1sec"),
_10SEC("_10sec");
```
If yes, what would the correct mapping looks like?

**Comment by mherb63** [comment]
it seems like Mongo is looking for "_100ms" (with lower case).

c.c.l.p.exception.ApiExceptionHandler : No enum constant com.ciena.lion.mef.pm.domain.EthOamDmmCfg.FrameTransmissionPeriodEnum._100ms
java.lang.IllegalArgumentException: No enum constant com.ciena.lion.mef.pm.domain.EthOamDmmCfg.FrameTransmissionPeriodEnum._100ms
at java.lang.Enum.valueOf(Enum.java:238)
at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:819)

**Comment by wing328** [comment]
@mherb63 this should be fixed by https://github.com/swagger-api/swagger-codegen/pull/3531. Please pull the latest master to give it a try (I assume you're using Jersey1.x or 2.x Java API client and you will need to use the --library option to specify that as Java API client now defaults to use `okhttp-gson`)

**Comment by wing328** [comment]
Please try the stable version 2.2.1 and let us know if you still experience the same issue.

**Comment by mherb63** [comment]
I'm generating Spring code from swaggerhub.  Just tried and its still uppercasing the enums.

**Comment by wing328** [comment]
@mherb63 thanks for checking again. I'll take another look at the issue for Spring (the fix I mentinoed was for Java client)

**Comment by mherb63** [comment]
Great.  Thanks!

**Comment by mherb63** [comment]
any updates on this issue?  When will fixes be pushed to swaggerhub for Spring server code generation?

Thanks!

**Comment by wing328** [comment]
@mherb63 To be clear, the fix will still convert the enum name to upper case. The fix we did with Java added the `fromValue` method so that the deserialization works: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/EnumArrays.java#L95

I've been very busy these days and I'll try to file a PR for this issue tomorrow (Fri).

**Comment by wing328** [comment]
UPDATE: Filed #3615 to add the `fromValue` method

**Comment by wing328** [comment]
#3615 merged into master. Please pull the latest master and build the JAR locally to use the fix before stable version 2.2.2 is released.

**Comment by mherb63** [comment]
I'm curious why you are converting the enum name to upper case.  This is recent new behavior which has broken our existing code.  Can you not use the enum value as the name (without uppercasing)?  That's how it was working up until about a month ago or so.

Thanks!

**Comment by wing328** [comment]
@mherb63 we do it to conform the enum naming convention in Java: http://docs.oracle.com/javase/tutorial/java/javaOO/enum.html, http://stackoverflow.com/a/3069863/677735

**Comment by mherb63** [comment]
I just discovered another side effect of the uppercasing.  The Model Schema on the Swagger UI page shows the lowercase version.  Notice the "interval" below:

![image](https://cloud.githubusercontent.com/assets/1205814/18093705/c9d07cc6-6e9e-11e6-982b-e509f8bdf709.png)

and the generated Spring server code:

![image](https://cloud.githubusercontent.com/assets/1205814/18093873/6a1c4fde-6e9f-11e6-8380-fbbd2637b299.png)

**Comment by wing328** [comment]
I believe the "Model Schema" shows the JSON presentation of the model.

**Comment by mherb63** [comment]
yea but the Enums should be all caps there, otherwise it fails.  For example:

![image](https://cloud.githubusercontent.com/assets/1205814/18096587/b40ef70a-6ea8-11e6-9866-6ddc6e20834d.png)

**Comment by wing328** [comment]
Did you get the error using the latest master, which should have addressed the deserialization for `spring` model with enum property if I'm not mistaken?

**Comment by mherb63** [comment]
I generated the code from Swagger hub on Aug 24th (6 days ago).  What new code did you add that I can check if its there?

**Comment by wing328** [comment]
We added the `fromValue` static method. e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/EnumTest.java#L38

**Comment by mherb63** [comment]
I just generated our code from swaggerhub and I'm not seeing any fromValue method.

```
  public enum FrameTransmissionPeriodEnum {
    _10MS("_10ms"),
    
    _100MS("_100ms"),
    
    _1SEC("_1sec"),
    
    _10SEC("_10sec");

    private String value;

    FrameTransmissionPeriodEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }
```

Michaels-iMac:spring-server-generated mherb$ pwd
/Users/mherb/Downloads/spring-server-generated
Michaels-iMac:spring-server-generated mherb$ find . -name *.java | xargs grep -i fromValue
Michaels-iMac:spring-server-generated mherb$

**Comment by wing328** [comment]
I don't think SwaggerHub is using the latest master of Swagger Codegen.

**Comment by mherb63** [comment]
are you sure this bug is fixed for Spring Server code generation?  I just did the below and I'm still not seeing any fromValue methods in the generated model code.

brew install swagger-codegen
swagger-codegen generate -i Y1731PMActivation-1.1.12-swagger.yaml -l spring-mvc

Mike

**Comment by wing328** [comment]
brew is not installing the latest master either. It's using the latest stable version 2.2.1 instead.
