### ISSUE TITLE
 Codegen not support annotations SpringMVC ?¿

### ISSUE THREAD

**Issue by IsmaTeddy** [swagger-api/swagger-codegen#3526]
I am using it to document my service "springfox-swagger-ui" , when I try to generate my sdk not know translate ResponseEntity <byte[ ]>  because it is a SpringMVC notation. If I look I see codegen library for spring only jersey2 , okhttp - GSON , etc ... any solution ?

**Comment by wing328** [comment]
@IsmaTeddy please follow the issue template to provide more information (e.g. spec, codegen version, etc) so that we (the community) can help you.

**Comment by IsmaTeddy** [comment]
Sorry @wing328 , 
I try to give more information.

I used:
swagger codegen v2.2.0
springfox-swagger-ui v2.5.0
springfox-swagger2 v2.5.0

And not resolved correctly:
public ResponseEntity<byte[]> file(@PathVariable String documentId) throws IOException {

generated client:

@Test
    public void fileUsingGETTest() throws ApiException {
        String documentId = null;
         List<byte[]> response = api.fileUsingGET(documentId);
    }

**Comment by wing328** [comment]
Can you provide the spec? which target (language) do you want to generate the code for?

**Comment by IsmaTeddy** [comment]
The service is created with SpringMVC and springboot ( eureka ) . Try to generate the java client jersey2 .

**Comment by wing328** [comment]
@IsmaTeddy without the spec, it's hard for us to reproduce the issue.
