### ISSUE TITLE
Generated code is having ByteArray Class instaed of byte[] for c# Client

### ISSUE THREAD

**Issue by guptakumartanuj** [swagger-api/swagger-codegen#3528]
##### Description

I have generated the C# client code from the given below of Swagger Codegen version. So in the generated code, There is a class called ByteArray for which I need to download the 3rd party dll which I don't want. So I want the code which can generate byte[] instead of ByteArray Class.

Note* - can't take the latest version because of our internal restriction.  

##### Swagger-codegen version

2.1.3-M1

##### Swagger declaration file content or url

System.Threading.Tasks.Task<ByteArray> GetAuditTrailAsync (string accessToken, string agreementId, string xApiUser);

**Comment by wing328** [comment]
@guptakumartanuj sorry to hear about the internal restriction in your company but there's nothing we can do in our side to workaround that.

Please upgrade to the latest version and open a new issue if there's still an issue.

**Comment by guptakumartanuj** [comment]
Hi Team,

Thanks for the kind reply. But I think would have added the support of
ByteArray. Before that it would have been byte[]. So can you please give me
that CL number so that I can get that code to incorporate the changes.

Thanks for the kind support and coordination.

Thanks & Regards,
Tanuj Gupta

   - Mobile - +91-8861007240
