### ISSUE TITLE
[ALL] Server generation is broken

### ISSUE THREAD

**Issue by kevinchabreck** [swagger-api/swagger-codegen#3539]
##### Description
It seems that server generation for most (if not all) languages/libraries is currently broken. Attempting to generate a server from a few of the sample YAML files supplied in the swagger editor fails with different errors depending on the language. 

##### Swagger declaration files tested:
* [default.yaml](https://github.com/swagger-api/swagger-editor/blob/master/spec-files/default.yaml)
* [petstore_simple.yaml](https://github.com/swagger-api/swagger-editor/blob/master/spec-files/petstore_simple.yaml)

##### Steps to reproduce
1. navigate to http://editor.swagger.io/
2. "File" -> "Open Example" -> "petstore_simple.yaml"
3. "Generate Server" -> pick anything

Expected result: download of zip file with server stub generated

Observed result: server generation fails

##### Related issues
I first noticed the problem when trying to generate a java-based server, and received the following error: 
`Unable to build target: Could not generate model [xxxxx]`
This is similar to the error [described in this thread](https://github.com/swagger-api/swagger.io/issues/101). However, after further investigation I believe this is an overarching issue not limited to java-based servers.

**Comment by wing328** [comment]
Using "petstore_full.yaml", I could repeat the issue with Ruby, Python and PHP with the following error messages:
```
Unable to build target: Could not generate model 'Category'

Details:

 Object
code: 1
type:  "error"
message: "Unable to build target: Could not generate model 'Category'"
```

I do not have access to the server (generator.swagger.io, which is used by swagger editor to generate code)

As a workaround, please pull the latest master and build the JAR locally: https://github.com/swagger-api/swagger-codegen#getting-started

**Comment by wing328** [comment]
cc @fehguy @webron

**Comment by wing328** [comment]
According to @fehguy the issue with generator.swagger.io has been fixed. Please give it another try.
