### ISSUE TITLE
Generated code is having ByteArray Class instaed of byte[] for c# Client

### ISSUE THREAD

**Issue by guptakumartanuj** [swagger-api/swagger-codegen#3554]
##### Description

I have generated the C# client code from the given below of Swagger Codegen version. So in the generated code, There is a class called ByteArray which breaks compilation. To avoid this, I need to download the 3rd party dll which I don't want. 

Can you please tell me in which version you had added the support of ByteArray so that I can take the code of the previous version related to byte[] or Please suggest me any workaround for the same ?

In addition to it, IF I make some changes given below in the getSwaggerType(Property p) api of DefaultCodegen.java, Some of the test cases fail.

Original --

if (p instanceof ByteArrayProperty) {
            datatype = "ByteArray";

Modified --

if (p instanceof ByteArrayProperty) {
            datatype = "byte[]";

Please help me for the same. Thanks for the kind support and coordination.

##### Swagger-codegen version

2.1.3-M1

##### Swagger declaration file content or url

public async System.Threading.Tasks.Task<ByteArray> GetAPI (string accessToken)

**Comment by wing328** [comment]
Please use the latest version instead. 2.1.3-M1 is pretty old.
