### ISSUE TITLE
How to overwrite the ApiClient.basePath in ApiClient.js

### ISSUE THREAD

**Issue by bys-wallance-zhang** [swagger-api/swagger-codegen#3556]
##### Description
[JavaScript] I success generate the js lib from a json source, I want to overwrite the basePath in my production environment, so how to implement it in node js.

**Comment by wing328** [comment]
I believe you can customize the basePath here: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/ApiClient.js#L60

and then pass the instance of ApiClient when constructing the API class (e.g. PetApi.js), e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/api/PetApi.js#L55

**Comment by wing328** [comment]
Closing this as there's no update.
