### ISSUE TITLE
[html2] curl example always show apiKey.

### ISSUE THREAD

**Issue by adonishi** [swagger-api/swagger-codegen#3560]
##### Description
in html2 ( htmlDoc2 ), there is 'curl' example. and it always shows 'apiKey' & 'apiSecret' header parameter.
```
curl -X GET -H "apiKey: [[apiKey]]" -H "apiSecret: [[apiSecret]]"  ...
```

##### Command line used for generation
```
swagger-codegen generate -l html2 -c config.json -i api.yaml -o html-docs/
```

##### Steps to reproduce
just generate html2. it always there.

##### Related issues

#3447

##### Suggest a Fix
wrap by {{#apiKey}}. see PR.

**Comment by wing328** [comment]
@adonishi thanks for opening an issue for tracking and the PR for the improvement.

**Comment by wing328** [comment]
PR merged.
