### ISSUE TITLE
 securityDefinitions not found in swagger.json 

### ISSUE THREAD

**Issue by ElXDi** [swagger-api/swagger-codegen#3563]
##### Description

The securityDefinitions is not found in produced swagger.json file. However in yaml file the securityDefinitions exists. Thus the 'Authorize' button is hidden on the Swagger UI (version 2.1.5) and I can't use the api key authorization flow.
##### Swagger-codegen version

2.2.1 (also tested with 2.1.6)
##### Command line used for generation

java -jar swagger-codegen-cli-2.2.1.jar generate -i http://petstore.swagger.io/v2/swagger.json -l jaxrs --library=jersey1 -o ~/petstore
##### Related issues

The original question location: https://github.com/OAI/OpenAPI-Specification/issues/750

**Comment by wing328** [comment]
@ElXDi thanks for reporting the issue. May I know if you've cycle to contribute a fix? If yes, I can show you some good starting points.

**Comment by ElXDi** [comment]
@wing328 Yes I'm interesting in contribution of fixing this issue. Please show a starting point. 
Unfortunately I do not have much time, but I'll try my best. 😉

**Comment by wing328** [comment]
@ElXDi I did some tests. I believe you're using `-l jaxrs-spec` instead of `-l jaxrs` (which does not generate swagger.json).

The swagger.json generated by `jaxrs-spec` does contain securityDefinition.

**Comment by ElXDi** [comment]
@wing328 I'm using following generation code: `java -jar swagger-codegen-cli-2.2.1.jar generate -i http://petstore.swagger.io/v2/swagger.json -l jaxrs --library=jersey1 -o ~/petstore` 
And then `cd ~/operators && mvn package jetty:run`
Once server is running you can open http://localhost:8080/API/v1/swagger.json (if I remember correctly the URL of swagger.json)
Please check securityDefinition in the swagger.json. 
I mean that I'm using generated on the fly swagger.json sile

**Comment by wing328** [comment]
@ElXDi I'm able to repeat the issue but have no clue why the issue occurs (I seldom work on the Java server generator).

@fehguy do you have any idea on how the swagger.json was generated when accessing http://localhost:8080/v2/swagger.json ?

(I did a find for `swagger.json` but no luck so it seems to me swagger.json was generated during jetty start or accessing the URL)

**Comment by yanniks** [comment]
Is there any possiblity this problem gets fixed in the near future?

**Comment by fehguy** [comment]
Aye, not sure how I missed this.

@wing328 the `swagger.json` is generated automatically from [here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java#L15).

@yanniks you need to create a bootstrap to add your security definitions.  They are not generated with the codegen.
