### ISSUE TITLE
[GO] Self-referencing definitions result in generating 'recursive' and thus invalid structs

### ISSUE THREAD

**Issue by ivucica** [swagger-api/swagger-codegen#3565]
##### Description

Because structs and not pointers to structs are used in the generated code, a `definition` cannot refer to itself.
##### Swagger-codegen version

7a245e31894c30a050e59cffefb97739005c0013
##### Swagger declaration file content or url

Full file available at https://bitbucket.org/api/swagger.json (it may change, but that's out of my control)

Also https://bitbucket.org/ivucica/calendarify/src/f1297e3411fcb52e830bd02dd0108e85eed39488/vendor/bitbucket.org/api/swagger.json
##### Command line used for generation

See https://bitbucket.org/ivucica/calendarify/src/f1297e3411fcb52e830bd02dd0108e85eed39488/vendor/bitbucket.org/api/BUILD

``` python
genrule(
    name = "rest_client_go_gen",
    srcs = [":swagger.json"],
    outs = SWAGGER_GENERATED,
    tools = [
        "//vendor:swagger-codegen-cli",
        "//vendor:swagger-codegen-cli_deploy.jar",
    ],
    cmd = "\n".join([
        "mkdir -p \"$$(dirname $(location :configuration.go))\"",
        "$(location //vendor:swagger-codegen-cli) --singlejar generate " +
        " -i $(location :swagger.json)" +
        " -l go" +
        " -o \"$$(dirname $(location :configuration.go))\"",
    ]),
)
```

Versions of dependencies: https://bitbucket.org/ivucica/calendarify/src/f1297e3411fcb52e830bd02dd0108e85eed39488/WORKSPACE

Versions of swagger projects: https://bitbucket.org/ivucica/calendarify/src/f1297e3411fcb52e830bd02dd0108e85eed39488/vendor/github.com/swagger-api/
- swagger-codegen [7a245e31894c]
- swagger-core [c7c9a4c641dc]
- swagger-parser [0e2fac8d6e46]
- swagger-ui [44149467753f]
##### Steps to reproduce

Bitbucket's API contains the following definition (transformed from JSON into YAML by the Swagger editor):

``` yaml
  repository:
   allOf:
      - $ref: '#/definitions/object'
      - additionalProperties: true
        type: object
        description: A Bitbucket repository.
        properties:
          ...
          created_on:
            type: string
            format: date-time
          parent:
            $ref: '#/definitions/repository'
          full_name:
            type: string
            description: >-
              The concatenation of the repository owner's username and the
              slugified name, e.g. "evzijst/interruptingcow". This is the same
              string used in Bitbucket URLs.
          ...
```

Generated code looks like:

``` go
type Repository struct {
...
          Parent Repository `json:"parent,omitempty"`
...
}
```

This results in a build error in Go such as:      

```
badc0de.net/pkg/calendarify/bazel-out/local-fastbuild/genfiles/vendor/bitbucket.org/api/repository.go:69: invalid recursive type Reposit
ory
```
##### Related issues

I am unaware of any.
##### Suggest a Fix

Consider updating the generated code to have properties of definitions generated as pointer types of struct fields.

``` go
type Repository struct {
...
          Parent *Repository `json:"parent,omitempty"`
...
}
```

To maintain compatibility with preexisting code that assumes fields are not pointers, this could be done only in case a definition refers to itself.

**Comment by wing328** [comment]
@ivucica thanks for the suggestion. I believe a similar discussion is https://github.com/swagger-api/swagger-codegen/issues/2330

**Comment by ivucica** [comment]
It is indeed related. This is indeed an additional reason to use pointers.

>

**Comment by wing328** [comment]
cc @neilotoole @guohuang

**Comment by wing328** [comment]
@ivucica when you've time I wonder if you can check out 2.3.0 branch to generate Go API client, which has been rewritten by @antihax with a lot of enhancements, and let us know if you've any feedback. Thanks!

**Comment by wing328** [comment]
@ivucica please pull the latest master to give it a try.
