### ISSUE TITLE
C# Generated code is having sync and async API also. Can you please justify the reason for the same ?

### ISSUE THREAD

**Issue by guptakumartanuj** [swagger-api/swagger-codegen#3571]
##### Description

While working on the generation of C# client API using swagger codegen, It has generated both sync and async API also. Can you please justify the reason for the same  as I can both the apis are having the same block of code. 

So actually the question is, It seems like both the apis will do the same work because there is no async operation defined in that particular block. So this is just for shake to call it as asyn API  or any logic behind the same ?

Please justify the same. Thanks for the kind support.
 

##### Swagger-codegen version

 2.1.3 M

##### Command line used for generation

 
Generated sync API - 
public GroupDetailsInfo GetGroupDetails (List<KeyValuePair<String, String>> headers,string groupId)

Generated async API - 
public async System.Threading.Tasks.Task<GroupDetailsInfo> GetGroupDetailsAsync (List<KeyValuePair<String, String>> headers,string groupId) 

code inside both the APIs is same.

**Comment by wing328** [comment]
We provide sync and aysnc methods so that developers can choose the right one to use based on their use cases.
