### ISSUE TITLE
JavaJAXRSSpecServerCodegen declares some parameters more than once

### ISSUE THREAD

**Issue by andylowry** [swagger-api/swagger-codegen#3572]
##### Description

The `JavaJAXRSSpecServerCodegen` class contains the following code in its constructor:

```
        cliOptions.add(new CliOption(CodegenConstants.IMPL_FOLDER, CodegenConstants.IMPL_FOLDER_DESC)); 
        cliOptions.add(new CliOption("title", "a title describing the application"));
```

Unfortunately, so does its super classs, `AbstractJavaJAXRSServerCodegen`. As a result, each of the two parameters ends up appearing twice in the `cliOptions` list declared in `DefaultCodegen`. This may seem harmless, but in some cases it could represent a bug in the module. And besides, this possibility makes things awkward for software that exposes swagger-codegen functionality in a more user-friendly way than the command-line interface that ships with swagger-codegen.

Ideally, DefaultCodegen should fail when the same parameter appears more than once in `cliOptions`, so module developers will notice this and correct their code.
##### Swagger-codegen version

2.2.0
##### Swagger declaration file content or url

Bug is independent of actual swagger model.
##### Command line used for generation

Any command line specifying `-l jaxrs-spec`
##### Steps to reproduce

Bug is not evident in normal command-line execution.
##### Related issues

Not that I could see
##### Suggest a Fix

Quick fix: Remove the duplicate parameter declarations from `JavaJAXRSSpecServerCodegen`.

Longer term: Also arrange for `DefaultCodegen` to check for duplicate parameters and fail if they are encountered. There is no legitimate need for such duplication, and it indicates a potentially serious bug in the offending module.

**Comment by wing328** [comment]
@andylowry thanks for reporting the issue. May I know if you've cycle to contribute a PR with the suggested fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by andylowry** [comment]
@wing328 Sure, will do.

**Comment by andylowry** [comment]
@wing328 Q: Are you comfortable with my suggested "Longer term" fix? I.e. arranging for `DefaultCodegen` to fail if it detects duplicate params?

**Comment by wing328** [comment]
@andylowry sounds like a good idea to me and after you commit the fix, the CI (shippable) should be able to report similar issues for other generators.

**Comment by andylowry** [comment]
@wing328 
See https://github.com/swagger-api/swagger-codegen/pull/3576 for my "quick fix". For reasons detailed in comments on that PR I've declined to attempt the longer-term fix I recommended.
