### ISSUE TITLE
Add composition support to templates

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#358]

**Comment by davesag** [comment]
+1 to this

**Comment by ialmetwally** [comment]
+1

**Comment by mxl** [comment]
Is this feature implemented for static html documentation generator?
I'm using build of `develop_2.0` branch and generated html has empty `Return type` sections for responses with `allOf`.

**Comment by wing328** [comment]
@mxl the latest develop_2.0 branch should have supported of `allOf`, which means the response should contains all properties defined in `allOf`. Do you mind sharing the swagger spec that I can help repeat the issue (assuming the spec can be shared publicly) ?

**Comment by mxl** [comment]
@wing328 I created simplified [spec](https://gist.github.com/mxl/df3ad1b1a1b57502ec61)
Also `$ref` to response object is not rendering in html.
Running swagger-codegen gives this output:
```
reading from test.json
321 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
322 [main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null}
380 [main] WARN io.swagger.codegen.DefaultCodegen - generated operationId test1Get
384 [main] WARN io.swagger.codegen.DefaultCodegen - generated operationId test2Get
```

**Comment by wing328** [comment]
@mxl Thanks. I'll take a look tomorrow (Sunday)

**Comment by meskall** [comment]
Is this not yet supported?

**Comment by wing328** [comment]
@meskall depending on language. Which language are you referring to so that I can take a look?

**Comment by meskall** [comment]
Java

**Comment by meskall** [comment]
I'm attempting to fix some swagger documentation and use swagger codegen to build my client.  

I believe this is the proper way to define it:
    ViewModelResponse: 
      properties: 
        view_models: 
          type: "array"
          items: 
            $ref: "#/definitions/ViewModel"
 ViewModel: 
      properties: 
        type: 
          description: "Type Differentiator"
          type: "string"
      discriminator: "type"

    ViewModelOne: 
      allOf: 
        - 
          $ref: "#/definitions/ViewModel"
        - 
          properties: 
            data: 
              $ref: "#/definitions/SpecificViewModelData"


I was hoping that not only would the class extend the base class properly but it would deserialize into the proper ViewModelOne so that I can in java go through the list on ViewModelResponse and check the class of each item...

This is possible with Jackson annotation but I cannot seem to codegen them.

**Comment by DavidBiesack** [comment]
We see the same problem when using allOf to compose model schema. See https://github.com/swagger-api/swagger-ui/files/1160284/duplicate-models.yaml.txt (and related [Swagger UI bug](https://github.com/swagger-api/swagger-ui/issues/3417) ). In the `-l html` output, 
There is a base schema named createModel then two derived schema updateModel and model which define an inheritance hierarchy createModel -> updateModel -> model via allOf / $ref,
but each with their own title and description. the HTML output only shows the properties from the most base type, createModel. The HTML output for updateModel and model do not show the additional members that they define.

I'd be happy to work on a PR but I would greatly appreciate some guidance on where to look in the code for how swagger-codegen builds the models from the `definitions` and `$ref` and `allOf`
