### ISSUE TITLE
Adding securityField is breaking API GET call with parameters

### ISSUE THREAD

**Issue by amitkhese** [swagger-api/swagger-codegen#3584]
var securityField = new Dictionary<string, IEnumerable<string>>();
  securityField.Add("Authorization", new List<string>());
  operation.security.Add(securityField);

Adding securityField is breaking API GET call with parameters. Given 401 error.
But Post and Get without parameter are working getting proper result.
Please suggest

**Comment by wing328** [comment]
Please open a new one by providing details by filling the issue template/form.
