### ISSUE TITLE
[typescript-angular2] API Call Returns Model with "undefined" Member Value

### ISSUE THREAD

**Issue by darius-iko** [swagger-api/swagger-codegen#3586]
##### Description

When calling API by using TypeScript-Angular2 codegen, it returns data with "undefined" member value. When I inspect the returned data, the issue relies on different letter case (the return data has Pascal-case property name, but the model declaration has Camel-case property name).

![image](https://cloud.githubusercontent.com/assets/8023913/17643966/a2cd035a-61ac-11e6-9a17-f1509fa98c91.png)

##### Swagger-codegen version

2.2.1

##### Steps to reproduce

1. Create an API service with return model which has Pascal-case property name (e.g. AuthenticationToken).
2. Generate code with typescript-angular2 language.
3. Write a dummy TypeScript code to call the API and compare the return data with the model declaration. Both has different capitalization style.

##### Suggest a Fix

Please add mapping for the returned data from any-case to camel-case, or change the property name to follow the letter case of the returned data.

**Comment by wing328** [comment]
@darius-iko I think the issue you reported is similar to this one: https://github.com/swagger-api/swagger-codegen/issues/2766

Have you tried the `modelPropertyNaming` option to see if that addresses the issue for you?
```
swagger-codegen|master⚡ ⇒ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l typescript-angular2

CONFIG OPTIONS
	sortParamsByRequiredFlag
	    Sort method arguments to place required parameters before optional parameters. (Default: true)

	ensureUniqueParams
	    Whether to ensure parameter names are unique in an operation (rename parameters that are not). (Default: true)

	modelPropertyNaming
	    Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name (Default: camelCase)

	supportsES6
	    Generate code that conforms to ES6. (Default: false)

	npmName
	    The name under which you want to publish generated npm package

	npmVersion
	    The version of your npm package

	npmRepository
	    Use this property to set an url your private npmRepo in the package.json

	snapshot
	    When setting this property to true the version will be suffixed with -SNAPSHOT.yyyyMMddHHmm (Default: false)
```

**Comment by wing328** [comment]
cc @Vrolijkx

**Comment by darius-iko** [comment]
Thank you. It works.

**Comment by darius-iko** [comment]
Hi, how to inject parameter in HTTP Headers? Can I set by using the Api.defaultHeaders before calling the API?
e.g: 
this.api.defaultHeaders.set('id', 'xxxxxx');

**Comment by sebastianhaas** [comment]
@darius-iko could you please try and see if #3603 fixes your issues?

**Comment by wing328** [comment]
@darius-iko #3603 has been merged into master. Please pull the latest to give it a try.

If the issue still occurs, we'll reopen this issue.

**Comment by darius-iko** [comment]
Thank you.
