### ISSUE TITLE
[JAVA] No option for skipping models, apis, runtime and authn

### ISSUE THREAD

**Issue by rajeshkamal** [swagger-api/swagger-codegen#3587]
Issue:
We have around 4 to 5 different services which are independent. Swagger codegen is run for every service's swagger spec. Each of the generated classes is compiled to a jar. Since we do not have an option to skip the runtime and the authn classes. Every service contains these duplicated classes.

Ex:
service-1.jar - contains models, apis, runtime and authn
service-2.jar - contains models, apis, runtime and authn
service-3.jar - contains models, apis, runtime and authn

Instead if we have an option to skip the runtime and authn generation which is common. We can generate something like this,
service-1.jar - contains models, apis
service-2.jar - contains models, apis
service-3.jar - contains models, apis
common-runtime.jar - contains runtime and authn.

**Comment by rajeshkamal** [comment]
This can potentially apply for all languages.

**Comment by fehguy** [comment]
You can skip those classes.  See https://github.com/swagger-api/swagger-codegen#selective-generation

**Comment by rajeshkamal** [comment]
Thanks for the pointer @fehguy ... When trying to use it I got into this issue #2232 & #2698
