### ISSUE TITLE
[Ruby] DateTime values are incorrectly parsed in Ruby client

### ISSUE THREAD

**Issue by jackychow** [swagger-api/swagger-codegen#3588]
##### Description

when a property is of type: string, format: date-time
The ruby client would wrongfully parse the value as a Time.at(0)

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

Foo:
  type: object
  description: some object
  properties:
     request_at:
      type: string
      format: date-time
      description: the first time user sign on to the event

#############################################

I believe this piece of code is the culprit in the basemodel that was generated:

        begin
          return case type.to_sym
                   when :DateTime
                     if value.is_a?(DateTime)
                       value
                     elsif value.is_a?(Integer) || value.respond_to?(:to_i)
                       Time.at(value.to_i).to_datetime
                     else
                       DateTime.parse(value)
                     end
................

When the format is date-time, the json response for the datetime object is presented sent as a string.
The value.respond_to?(:to_i) would then pickup the string (although it's something like "2016-08-10T11:45:29.000+00:00", a string also has a to_i method which would returns 0 if it's not a legitimate integer ... so all of my dates are returned as Time.at(0) which are basically the epoch beginning of time.

**Comment by wing328** [comment]
@jackychow  I couldn't find `value.respond_to?(:to_i)` in 2.1.6 nor the latest master.

Are you using a customized version of Swagger Codegen somehow?

**Comment by jackychow** [comment]
@wing328 , you are right. It indeed is the customized ruby codegen implementation that I'm using that's causing the problem. This is unrelated to the codegen's core implementations. Thanks and sorry for the confusion. I'm closing this issue.

**Comment by wing328** [comment]
@jackychow no problem. We would recommend contributing back the enhancements so that you do not need to maintain your own version of Swagger Codegen and other users can enjoy the enhancements or bug fixes.

Let me know if you need help submitting a PR.
