### ISSUE TITLE
[develop 2.0] BUILD FAILURE if no model classes are generated

### ISSUE THREAD

**Issue by sovannaN** [swagger-api/swagger-codegen#359]
I tried to generate android-client code from a json file without models in it with the develop 2.0 branch.
Code is generated as wanted and wihtout any errors but when you try to run "mvn package" command on it, there's a build error.
The class generated for my API contains an import of the package "com.test.client.model.*" that doesn't exist. If I remove the import manually from the generated file, the "mvn package" commands works fine since I don't have any models.

Codegen should import the package "com.test.client.model.*" only if the source file contains models in it.

**Comment by fehguy** [comment]
This should be addressed in develop_2.0
