### ISSUE TITLE
[JAVA] Bug generating date-time as body parameter in POST or PUT

### ISSUE THREAD

**Issue by adamcode** [swagger-api/swagger-codegen#3601]
When generating Java for a PUT or POST with body parameter of format "date-time" the import statements for Java or Joda data\time are not added. I tried this in 2.1.6, 2.2.0 and 2.2.1. 

I've pasted in a snippet below and attached a modified petstore json to reproduce this. 

    ```json
    "post" : {
				"tags" : ["pet"],
				"summary" : "Add a new pet to the store",
				"description" : "",
				"operationId" : "addPet",
				"consumes" : ["application/json", "application/xml"],
				"produces" : ["application/xml", "application/json"],
				"parameters" : [{
						"in" : "body",
						"name" : "body",
						"description" : "Pet object that needs to be added to the store",
						"required" : true,
						"schema" : {
							"format" : "date-time",
							"type" : "string"
						}
					}
				],
    ```

##### Command line used for generation

java -jar .\swagger-codegen\swagger-codegen-cli-2.2.1.jar generate -i .\petstoreswagger.json -l java -o ./petstore --api-package com.petstore.sample --artifact-id com.petstore.sample --group-id com.petstore --model-package com.petstore.models --artifact-version 1.0.4

[petstoreswagger_datetime.zip](https://github.com/swagger-api/swagger-codegen/files/421919/petstoreswagger_datetime.zip)

##### Steps to reproduce

Generate as above then compile or package with Maven. PetApi.java will contain references to the type "DateTime" but no imports to resolve this type.

**Comment by wing328** [comment]
Usually the body parameter refers to "model". Can you give an example of what the HTTP body (content) looks like?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L49

**Comment by adamcode** [comment]
That's a good question on the content. When we looked it wasn't getting serialized as JSON. To tidy this up we added a model to wrap the value and the generation issue disappeared. This feels like an edge case to me so I'm happy to close this if you agree.

**Comment by wing328** [comment]
@adamcode glad to hear that the issue has been resolved for you using "model"
