### ISSUE TITLE
[Typescript-Angular2] No file generated for schema with array of types

### ISSUE THREAD

**Issue by Emmpa** [swagger-api/swagger-codegen#3607]
When a schema defines a type as an array, no model is generated

Related Swagger ticket: https://github.com/OAI/OpenAPI-Specification/issues/458

##### Swagger declaration file content or url
(NOTE: this swagger spec file validates okay in http://editor.swagger.io/#/)
```yaml
swagger: "2.0"
info:
  version: "0.0.1"
  title: TEST
  description: TEST

host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    post:
      tags:
        - TEST
      operationId: tester
      description: tester
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Test"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Success"

definitions:
  Success:
    properties:
      success:
        type: boolean

  Test:
    required:
      - val
    properties:
      val:
        type: ["integer", "boolean"]
```

##### Command line used for generation
`java -jar swagger-codegen-cli-2.2.1.jar generate -i ./swagger.yaml -l typescript-angular`

**Comment by wing328** [comment]
I don't think the following is valid:
```
        type: ["integer", "boolean"]
```
What does the `Test` model looks like? Can you provide an example (JSON)?

**Comment by webron** [comment]
It isn't. There's no support for multiple types.

**Comment by Emmpa** [comment]
I had to migrate an old API to swagger, so I still have to support legacy bad-practices. I'm using multiple types for a few specific cases:
1) boolean/integer, where the value can be either true/false or 0/1. In that case, I would usually define the parameter as:
```
BoolInt:
  type: ["boolean", "integer"]
  description: DB storage of boolean
  minimum: 0
  maximum: 1
```

2) I'm using swagger-tools in node.js and in order to validate server responses I have had to use type/null definitions for database columns that are nullable. For example:
```
Url:
  type: ["string", "null"]
```

Other existing tools, like swagger editor and swagger-tools support multiple types. The discussion on Open-Api specifications (https://github.com/OAI/OpenAPI-Specification/issues/458) mentions the relevant JSON schema definition (5.5.2.1).

**Comment by wing328** [comment]
For 1) you can document it as an enum string with allowable values: "0", "1", "true", "false" as a workaround.

For 2) you can use vendor extension `x-nullable` to document the property as nullable. Please refer to https://github.com/swagger-api/swagger-codegen/issues/2885 for more info. 

Closing this as multi type is not supported by the spec.
