### ISSUE TITLE
[PYTHON] OAuth2 access token not included in http request headers

### ISSUE THREAD

**Issue by rebeccabauer** [swagger-api/swagger-codegen#3609]
Hi! I am using swagger-codegen to generate clients for an app that uses oauth2 bearer tokens. 
The problem is that the generated python client does not include the token in the request headers.  

So if the header parameters should be:
{'Content-Type': 'application/json', **'Authorization': 'Bearer myoauthtoken'**, 'Accept': 'application/json', 'User-Agent': 'Swagger-Codegen/1.0.0/python'}

My request is instead sent with the following header parameters:
{'Content-Type': 'application/json', **'Authorization': 'Bearer '**, 'Accept': 'application/json', 'User-Agent': 'Swagger-Codegen/1.0.0/python'}

For reference, the security definition in the swagger specs is: 
    
```json
    "securityDefinitions": {
        "application_auth": {
            "scopes": {
                "email": "default scope"
            }, 
            "type": "oauth2", 
            "flow": "implicit", 
            "authorizationUrl": "https://example.com/oauth2/"
        }
    }
```

The cause of this issue is that the ‘Configuration’ object's access_token attribute is set to an empty string and is never updated to a real token value.  

My current solution is to create a subclass of the ApiClient object that allows the token to be set, and updates the token in the config object just before the header is created in update_params_for_auth.  Then I pass in this subclass when I create instances of specific apis.  

```python
class ApiWithOAuth(search_client.ApiClient):
    def __init__(self, **kwargs):
        super(ApiWithAuth, self).__init__(**kwargs)
        self.token_generator = TokenGenerator()     # TokenGenerator is a class for generating oauth2 tokens

    # Override the method that updates auth parameters
    def update_params_for_auth(self, headers, querys, auth_settings):
        """
        Updates header and query params based on authentication setting.

        :param headers: Header parameters dict to be updated.
        :param querys: Query parameters dict to be updated.
        :param auth_settings: Authentication setting identifiers list.
        """
        config = search_client.Configuration()
        config.access_token = self.token_generator.get_token()	# this line is the only one that is different from the parent class

        if not auth_settings:
            return

        for auth in auth_settings:
            auth_setting = config.auth_settings().get(auth)
            if auth_setting:
                if not auth_setting['value']:
                    continue
                elif auth_setting['in'] == 'header':
                    headers[auth_setting['key']] = auth_setting['value']
                elif auth_setting['in'] == 'query':
                    querys[auth_setting['key']] = auth_setting['value']
                else:
                    raise ValueError(
                        'Authentication token must be in `query` or `header`'
                    )
```

This works, but I would definitely prefer to use built-in functionality to deal with the tokens.  Please let me know if you have any advice or a solution that I missed!  

If others have encountered this problem, I could alter the api_client.mustache file to support setting the access token, or the header fields in general (currently we can only set the header field defaults, which in this case are overwritten with incorrect oauth2 details from Configuration when the header is created).

**Comment by wing328** [comment]
@rebeccabauer thanks for the details in reporting the issue and showing the fix that you're using.

Currently I believe you can already set the access token in configuration.py without subclassing ApiClient: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/configuration.py

You're correct in saying that the current Python API client lacks methods to automatically retrieve the access token. May I know if you've cycle to contribute the enhancements? Is there any Python OAuth 2.0 lib you find useful in retrieving the token?

**Comment by rebeccabauer** [comment]
@wing328, thanks for responding!  The problem with setting the access token in the configuration object is that ApiClient doesn't just use a single instance of Configuration - it creates a new instance every time a setting is needed, in init, update_params_for_auth, and __deserialize_file.  So currently, if we want to set the oauth token and have the change be reflected in the header, we have to set the token in the specific Configuration instance used by update_params_for_auth.  An easy fix for this would be to give ApiClient a config instance variable instead of recreating the configuration each time.  Then, the user could set the access token via api_client_instance.config.access_token.  I guess another option is to manually edit configuration.py, but I would prefer not to do that because it will be frequently regenerated.

**Comment by wing328** [comment]
@rebeccabauer the configuration class is singleton: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/configuration.py#L41 so the same instance of configuration class should be used in init, update_params_for_auth, and __deserialize_file.

Which version of Swagger Codegen are you using to generate the Python API client?

**Comment by rebeccabauer** [comment]
Thanks for pointing that out - I completely missed the singleton decorator.  OAuth2 headers are working for me now!

**Comment by Gladskih** [comment]
Same problem as OP but in C#.
```
Configuration.Default.AccessToken = <token>;
new MyApi().GetData();
```
In debug MyApi instance uses config with JWT initialized, but do not add it to header and in Fiddler I see the request:

> GET https://<host>/<path> HTTP/1.1
> Accept: application/json
> User-Agent: Swagger-Codegen/1.0.0/csharp
> Host: <host>
> Accept-Encoding: gzip, deflate
> Connection: Keep-Alive

**Comment by wing328** [comment]
@Gladskih please open a new issue to track the issue in the C# API client.

I assume you're using the latest stable version 2.3.1

**Comment by Sarek-Wyona** [comment]
I am running into a similar issue where I get " ValueError: Invalid value for `access_token`, must not be `None`"
I am editing the configuration like so 

        url = <my url>
        configuration = swagger_client.Configuration()
        configuration.host = url
        configuration.access_token =<my token>
        configuration.verify_ssl = False
        configuration.ssl_ca_cert = None
        configuration.assert_hostname = False
        configuration.cert_file = None

        api_client = swagger_client.ApiClient(configuration=configuration, header_name='Authorization',
                                              header_value=<my access token>)
        oauth = swagger_client.Oauth(api_client=api_client) 

I am absolutely at a loss as to why the access token is not being set.
