### ISSUE TITLE
Possible swagger hub codegen issue with nested elements: the @JsonProperty annotation is missing from get methods

### ISSUE THREAD

**Issue by ralgor14** [swagger-api/swagger-codegen#3612]
The @JsonProperty annotation is missing when codegen creates Java code (Server->jaxrs) for nested elements.
 
The following block:
 
 
    "PM_Session": {
      "description": "description",
      "type": "object",
      "properties": {
        "id": {
          "description": "description",
          "type": "string"
        },
                                ....
                                "ethOamPerfMonCfg": {
          "$ref": "#/definitions/EthOamPerfMonCfg"
        }
    },
                                
                "EthOamPerfMonCfg": {
      "description": "description.",
      "type": "object",
      "properties": {
        "startTime": {
          "description": "description",
          "type": "string"
        },
                                ...
        "EthOamDmCfg": {
          "$ref": "#/definitions/EthOamDmCfg"
        },
        "EthOamDmmCfg": {
          "$ref": "#/definitions/EthOamDmmCfg"
        },
      },
      "required": [
                    ...
      ]
    },
    ...
caused creation of the following Java code:
 
@ApiModel(description = "Performance Management Session also known as MA - Maintenance Association - Reference MEF 35.1 Section 10.1.1 General Overview of Parameters")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-08-16T13:50:07.517Z")
public class PMSession   {
  private String id = null;
  ...
  private EthOamPerfMonCfg ethOamPerfMonCfg = null;
  
  ...
}
 @ApiModel(description = "Ethernet OAM Performance Monitoring Configuration.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-08-16T13:50:07.517Z")
public class EthOamPerfMonCfg   {
  private String startTime = null;
  ...
  private EthOamDmCfg ethOamDmCfg = null;
 
  private EthOamDmmCfg ethOamDmmCfg = null;
 
  @ApiModelProperty(value = "")
  public EthOamDmCfg getEthOamDmCfg() {
    return ethOamDmCfg;
  }
 
  ...
  @ApiModelProperty(value = "")
  public EthOamDmmCfg getEthOamDmmCfg() {
    return ethOamDmmCfg;
  }
  ...
}
 
while get methods with @ApiModelProperty annotation should also have @JsonProperty("baseName").
In our case:
 
  @ApiModelProperty(value = "")
  @JsonProperty("EthOamDmCfg")
  public EthOamDmCfg getEthOamDmCfg() {
    return ethOamDmCfg;
  }
 
  ...
  @ApiModelProperty(value = "")
  @JsonProperty("EthOamDmmCfg")
  public EthOamDmmCfg getEthOamDmmCfg() {
    return ethOamDmmCfg;
  }
 
  Missing annotation causes the JSON file to be considered illegal.
  It was OK in previous versions of swagger hub.
Annotations are used by jackson's fasterXml package.

**Comment by wing328** [comment]
@ralgor14 can you share the full spec (e.g. via https://gist.github.com) for us to repeat the issue?

**Comment by shades66** [comment]
To reproduce use the editor to create the default example and look in the definitions at the product object. You will see product_id & currency_code and a number of other fields defined in snake case.  The live rendering view of the model all looks correct but when you generate the springboot application it now producing everything with camel case fieldnames like productId & currencyCode due to the missing @JsonProperty attribute.

**Comment by ralgor14** [comment]
{
  "swagger": "2.2.1",
  "info": {
    "description": "demo",
    "version": "1.1.11",
    "title": "demo",
    "contact": {
      "name": "Ruth Algor",
      "email": "ruth_a@rad.com"
    }
  },
  "host": "A.B.C:8080",
  "basePath": "/y1731pm/v1",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/pm/pmsession": {
      "post": {
        "tags": [
          "PM_Session"
        ],
        "operationId": "createPmSession",
        "summary": "Create PM Session",
        "description": "Create PM Session",
        "deprecated": false,
        "parameters": [
          {
            "name": "PM_Session",
            "required": true,
            "in": "body",
            "description": "PM Session",
            "schema": {
              "$ref": "#/definitions/PM_Session"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK - Request was successful",
            "schema": {
              "$ref": "#/definitions/PM_Session"
            }
          },
          "202": {
            "description": "Accepted - The request has been accepted for processing, but the processing has not been completed for asynchronous operations.",
            "schema": {
              "$ref": "#/definitions/PM_Session"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error_Response"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/Error_Response"
            }
          },
          "422": {
            "description": "Resource Issue",
            "schema": {
              "$ref": "#/definitions/Error_Response"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PM_Session": {
      "description": "PM_Session",
      "type": "object",
      "properties": {
        "id": {
          "description": "Identifier for this PM Session",
          "type": "string"
        },
        "state": {
          "description": "State of PM Session",
          "type": "string",
          "enum": [
            "active",
            "inactive"
          ]
        },
        "ethOamPerfMonCfg": {
          "$ref": "#/definitions/EthOamPerfMonCfg"
        }
     }
    },
    "EthOamPerfMonCfg": {
      "description": "EthOamPerfMonCfg",
      "type": "object",
      "properties": {
        "startTime": {
          "description": "description",
          "type": "string"
        },
        "enabled": {
          "description": "State",
          "type": "boolean"
        },
        "EthOam1SlCfg": {
          "$ref": "#/definitions/EthOam1SlCfg"
        },
        "EthOamDmCfg": {
          "$ref": "#/definitions/EthOamDmCfg"
        }
      },
      "required": [
        "startTime"
      ]
    },
    "EthOam1SlCfg": {
      "description": "description",
      "type": "object",
      "properties": {
        "testId": {
          "type": "string"
        },
        "unicastDestMacAddr": {
          "type": "string"
        },
        "unicastSrcMacAddr": {
          "type": "string"
        },
        "frameTransmissionPeriod": {
          "description": "DMM period for frame transmission",
          "type": "string",
          "enum": [
            "_10ms",
            "_100ms",
            "_1sec",
            "_10sec"
          ],
          "default": "_1sec"
        },
        "frameSize": {
          "type": "string"
        }
      }
    },
    "EthOamDmCfg": {
      "description": "description",
      "type": "object",
      "properties": {
        "testId": {
          "type": "string"
        },
        "multicastDestMacAddr": {
          "type": "string"
        },
        "vlanId": {
          "type": "string"
        },
        "frameTransmissionPeriod": {
          "description": "description",
          "type": "string",
         "enum": [
            "_100ms",
            "_1sec",
            "_10sec"
          ],
          "default": "_1sec"
        },
        "frameSize": {
          "type": "string"
        }
      }
    },
    "Error_Response": {
      "description": "Error addition information",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      }
    }
  }
}

**Comment by ralgor14** [comment]
Above is the full spec. What is missing is the annotation @JsonProperty for get methods with  annotation @ApiModelProperty

**Comment by denis-yuen** [comment]
Ran into the same issue, noticed also that this problem was introduced between 2.1.6  and 2.2.1 with the following example https://gist.github.com/denis-yuen/47a5bd391ffffc887ed08672b3d1d11b and running `java -jar swagger-codegen-cli-2.1.6.jar generate -i swagger.json  -l jaxrs -o jaxrs_old` vs the current stable jar.

**Comment by wing328** [comment]
@denis-yuen @ralgor14 ok. I'll take another look later today.

**Comment by cbornet** [comment]
@ralgor14 I tested on current master and the @JsonProperty annotations are correctly generated on the attributes:
```java
public class EthOamDmCfg   {
  @JsonProperty("testId")
  private String testId = null;

  @JsonProperty("multicastDestMacAddr")
  private String multicastDestMacAddr = null;

  @JsonProperty("vlanId")
  private String vlanId = null;
```

**Comment by cbornet** [comment]
Note : it's perfectly fine to put the @JsonProperty annotation on the attribute and not the getter/setter.

**Comment by denis-yuen** [comment]
Nice catch, I can verify that in 2.2.1, the @JsonProperty is generated on the getter. In 2.1.6, they disappear altogether. In the current master (2.2.2-SNAPSHOT), they reappear on the attributes.

**Comment by wing328** [comment]
@ralgor14 @denis-yuen so is this still an issue?

**Comment by denis-yuen** [comment]
No changes here. I think we just have to wait for a 2.2.2 release and then, ideally, for that to propagate to  http://editor.swagger.io/#/

**Comment by wing328** [comment]
@denis-yuen Is building the JAR based on the latest master an option for you?

**Comment by denis-yuen** [comment]
@wing328  Yup, we also have a workaround by inserting a Jackson property naming strategy.

**Comment by ralgor14** [comment]
Yes. If nothing was changed it’s still an issue.


[RAD.jpg]

Ruth Algor
RADview Software Engineer
M: +972-54-524-5488 | ruth_a@rad.com<mailto:ruth_a@rad.com>
T:  +972-3-645-9406   | F: +972-3-6440898

www.rad.com<http://www.rad.com>  |  Follow RAD on LinkedIn<http://www.linkedin.com/company/7369/>  |  Facebook<http://www.facebook.com/pages/RAD-Data-Communications/72479223117>  |  Twitter<http://twitter.com/raddatacomms>  |  YouTube<http://www.youtube.com/user/radwebmaster#g/u>
