### ISSUE TITLE
[Swift] is there a reason for not moving decodeJson to the actual model?

### ISSUE THREAD

**Issue by romk1n** [swagger-api/swagger-codegen#3619]
##### Description

models.swift is enormous file. and having encodeJson in model is a good thing but not having a decodeJson is not. It would make a model much more versatile if the model would have both encoding and decoding in the same file.

**Comment by wing328** [comment]
@romk1n what about using ObjectMapper instead? Ref: https://github.com/swagger-api/swagger-codegen/issues/2194

**Comment by romk1n** [comment]
@wing328 it may work as well. Closing in favour of that. Thanks.
