### ISSUE TITLE
[Typescript-Angular2] defaultHeaders getting bad request on json content type

### ISSUE THREAD

**Issue by 002** [swagger-api/swagger-codegen#3621]
##### Description
I got this issue when i do a post and put

##### Suggest a Fix
I fixed this adding the follow line
this.defaultHeaders.append('Content-Type', 'application/json');
before
let headerParams = this.defaultHeaders;

Archive: DefaultApi.ts

**Comment by wing328** [comment]
@002 thanks for reporting the issue, which will be addressed by https://github.com/swagger-api/swagger-codegen/pull/3603

**Comment by wing328** [comment]
#3603 has been merged into master. Please pull the latest master to give it a try.
