### ISSUE TITLE
volley  timeout error in swagger generated code for android

### ISSUE THREAD

**Issue by pradeepkumarreddyk** [swagger-api/swagger-codegen#3627]
I'm getting the following exception by using swagger generated code for android:
------------------------------------------------------------------------------------------
java.util.concurrent.ExecutionException: com.android.volley.TimeoutError

The following is the swagger generated code : 
---------------------------------------------------
try {
        String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
        if(localVarResponse != null){
           return (Lxlresponse) ApiInvoker.deserialize(localVarResponse, "", Lxlresponse.class);
        } else {
           return null;
        }
      } catch (ApiException ex) {
         throw ex;
      } catch (InterruptedException ex) {
         throw ex;
      } catch (ExecutionException ex) {
          if(ex.getCause() instanceof VolleyError) {
                  throw new ApiException(((VolleyError) ex.getCause()).networkResponse.statusCode,((VolleyError) ex.getCause()).getMessage());
         }
         throw ex;
      } catch (TimeoutException ex) {
         throw ex;
      }

In the above code, i'm getting exception at the following line:
-----------------------------------------------------------------------
throw new ApiException(((VolleyError) ex.getCause()).networkResponse.statusCode,((VolleyError) ex.getCause()).getMessage());

**Comment by pradeepkumarreddyk** [comment]
I had increased the volley timeout value from 30 ms to 30 sec in the swagger generated code. Now it is working fine.

**Comment by pradeepkumarreddyk** [comment]
Again i'm getting volley timeout error. I'm getting following exception : "java.util.concurrent.ExecutionException: com.android.volley.TimeoutError"
I think the problem is not with the timeout value, but because of some other reason.

**Comment by wing328** [comment]
@pradeepkumarreddyk can you try the Java API client to see if you still face the timeout issue? https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

**Comment by wing328** [comment]
You may also want to check the server log (if possible) to see if there's any clue.

**Comment by sidhantgoyal** [comment]
I think the problem is socket connection timeout. Possibly related to https://github.com/swagger-api/swagger-codegen/issues/3635

**Comment by pradeepkumarreddyk** [comment]
at the server side i'm not even receiving the request. so server log is not generated at all.

**Comment by pradeepkumarreddyk** [comment]
I have generated the code for java using the following command :
java -jar swagger-codegen-cli.jar generate -i input.yml -l java --library=okhttp-gson -o out_directory -c config.json

can you provide some sample code to use this generated code and see if i still get the timeout issue

**Comment by wing328** [comment]
> at the server side i'm not even receiving the request. so server log is not generated at all.

It seems to me it's more likely a network issue.

**Comment by wing328** [comment]
> can you provide some sample code to use this generated code and see if i still get the timeout issue

The SDK comes with the doc. You can upload it to github (using git_push.sh) and follow the README.md

**Comment by pradeepkumarreddyk** [comment]
it was a network issue. my device was not connected to the same wifi to which server was connected.

**Comment by mitchellbusby** [comment]
Hi @wing328 I seem to be getting these timeouts on my Android code even though my webserver is responding in a timely manner and logs are being registered - any idea why this could be?
I've tried building from the brew version, as well as the latest cloned swagger-codegen from github and compiled.

**Comment by wing328** [comment]
@mitchellbusby the latest master allows you to change the timeout value: https://github.com/swagger-api/swagger-codegen/pull/3646

If you increase the timeout value, does it work for you?

**Comment by mitchellbusby** [comment]
@wing328 I'll try this but isn't the default timeout 30secs anyway?

**Comment by mitchellbusby** [comment]
Tried setting the timeout value to 50 seconds, still have the same issue. Very weird.
Below is the exact error I'm facing:
![screen shot 2016-09-19 at 2 43 32 pm](https://cloud.githubusercontent.com/assets/1575729/18622794/b542f782-7e77-11e6-9b52-b8ba8aaf4801.png)

**Comment by sidhantgoyal** [comment]
@mitchellbusby I think the issue is that RequestFuture.get is on the same thread as UI thread. Try using  AsyncTask or the other heatmapPointGet call which uses response listeners (callbacks).

**Comment by mitchellbusby** [comment]
@sidhantgoyal I have now tried using the callback method, doesn't seem to have fixed the issue. I'll try using an asynctask and report back.

**Comment by mitchellbusby** [comment]
Apologies, I've resolved my issue - turns out that if your model class doesn't map correctly to the received response *precisely*, it'll never trigger the onResponse method in the RequestFuture!

**Comment by tahitiangabriel** [comment]
@mitchellbusby I'm facing the same issue. How did you resolved it? What do you mean by :
>  if your model class doesn't map correctly to the received response precisely
My entities are the same on both the server and in android.

The onResponse method in the RequestFurture is trigger after the timeout with the correct data in the response.

**Comment by mitchellbusby** [comment]
@tahitiangabriel your problem may not even be the same as mine. My issue came about because I was being lazy and just wrote a test entity  that *sort of* matched what my server was sending, but didn't go all the way down. For example, an array on the server that I would represent as a string on the client because I didn't want to have to learn how to define an array.

**Comment by tahitiangabriel** [comment]
OK my bad, I've found that the call to the web service must be made in a AsyncTask.
