### ISSUE TITLE
Java (spring) server code generation of  allOf field in yml seems broken

### ISSUE THREAD

**Issue by realjax** [swagger-api/swagger-codegen#3629]
Using 'allOf' no longer produces classes that extend the allof reference. 
Tested in the current master branch (2.2.2), trying to generate spring-mvc server code.
When using the live swagger editor (2.3.0) things work fine however.

**Comment by realjax** [comment]
It turns out this was caused because the discriminator field was left out.  Apparently this 'a_dds support for polymorphism_' and _'The property name used MUST be defined at this schema '_  in master (2.2.2) but is not needed in the live swagger editor (2.3.0)

**Comment by cbornet** [comment]
I'm working on this. Stay tuned !

**Comment by cbornet** [comment]
Just a note though : the discriminator is needed to have polymorphism. If the parent model doesn't have it, then the child model will not extend it and will make a copy of its properties instead.

**Comment by realjax** [comment]
Well actually it didn't make copies either.  

I came from version 2.1.6 where the discriminator was not needed in order to use polymorphism, only using 'allOf' would suffice.  And after bringing our fork up to 2.2.2 it suddenly broke :)

But what threw me off was that the live swagger editor ( http://editor.swagger.io/ ) doesn't require the use of the discriminator field either.

**Comment by wing328** [comment]
@realjax PR merged into master. Please pull the latest master to give it a try.
