### ISSUE TITLE
Integer type in JavaScript Client

### ISSUE THREAD

**Issue by iCEAGE** [swagger-api/swagger-codegen#3631]
##### Description

Regarding to the commit 1dd8c2b, still integer type should should be kept IMO, as [JSON schema](http://json-schema.org/latest/json-schema-core.html#rfc.section.3.5) has a definition of integer type. Although, JavaScript only has [Number type](https://developer.mozilla.org/en-US/docs/Glossary/Number).

And of course, parseInt("1.3434") and parseFloat("1.3434") return different values!

##### Swagger-codegen version
2.2.2-SNAPSHOT

Thanks,
Hamed

**Comment by wing328** [comment]
@iCEAGE can you share a use case with a spec in which mapping `integer` to `Number` in JS is causing issue?

**Comment by wing328** [comment]
@iCEAGE closing this as there's no update.
