### ISSUE TITLE
Circular reference causes bug in c# client generation

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#3632]
_From @ngzero on August 23, 2016 16:42_

The main problem occurs in the concrete Api in the Api-folder, not to be confused with the ClientApi.
In my example concrete Api is called ParticipantApi.

Try to create a new instance of the ParticipantApi to call a method of the api.

Even before the concrete ParticipantApi is called, the static value "Default" of type "Configuration" in the class "Configuration" itself is created. So the "Configuration" class holds a static variable of its own.
While the creation of the static variable calls the constructor of "Configuration" class with parameter ApiClient = null, the constructor calls setApiClientUsingDefault(null) which creates a new instance of ApiClient and assigns it to the ApiClient field in the static default variable of "Configuration".

IO.Swagger.Client.Configuration.Default, Line 102
static Configuration default = new Configuration() > Configuration.ctor(null) > setApiClientUsingDefault(null) > ApiClient = new ApiClient(); <--- random

Then the constructor of the concrete ParticipantApi is called with a basePath. The constructor then creates a new instance of "Configuration" with the creation of a new instance of ApiClient as parameter inline. IO.Swagger.Api.ParticipantApi.ctor(String), Line 107

So from inner to outer, a new instance of ApiClient(basePath) is created first. The constructor of ApiClient assigns to its field "Configuration" of type "Configuration" the value of "Configuration.Default" the static instance with a random ApiClient.

ApiClient (concrete) > Configuration (default) > ApiClient (random)

After the instance of ApiClient is created it goes directly as parameter to the constructor of Configuration. Where the constructor calls setApiClientUsingDefault with the concrete ApiClient.
Then in the else statement of setApiClientUsingDefault it is checked if Default is not null (indeed, it is a static variable) and if Default.ApiClient is null. No, is is not null because the same method created a new instance of a random ApiClient for the Default Configuration.

Back in the constructor of ParticipantApi there comes one last check
// ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }

Configuration will never be null cause it keeps the default Configuration which keeps a random/default ApiClient.

Circular references aren't good and this is the reason why, please fix.
And also why are there so many properties in the Configuration class, that are never used and there is no documentation. So, if I have a look at it and see oh... Configuration contains AccessToken and so on, then I try to use it but it will fail cause it is not implemented.
If one tries to implement it on its own then this will be impossible cause the ApiClient got the wrong Configuration. And if one tries to fix this, it is easier to write the whole thing new.

[csharp-client.zip](https://github.com/swagger-api/swagger-editor/files/433038/csharp-client.zip)
[swagger.zip](https://github.com/swagger-api/swagger-editor/files/433040/swagger.zip)

_Copied from original issue: swagger-api/swagger-editor#1056_

**Comment by wing328** [comment]
@ngzero please give https://github.com/swagger-api/swagger-codegen/pull/3530 a try and leave a comment in that PR if you've any feedback.

**Comment by jimschubert** [comment]
@ngzero if you check out my refactor in #3530, be warned Configuration.Timeout isn't hooked up to anything at the moment. I personally think it's confusing here if Configuration isn't an actual abstraction over RestClient, but I'm looking for feedback if this is indeed used/needed.

**Comment by jimschubert** [comment]
Also, refactor done based on issues reported in #1893

**Comment by wing328** [comment]
@ngzero please try the latest master and let us know if you still need help on this.
