### ISSUE TITLE
[Android] Volley configurable socket connection timeout 

### ISSUE THREAD

**Issue by sidhantgoyal** [swagger-api/swagger-codegen#3635]
##### Description 
The volley version of Android code does not have configurable socket connection timeout and it is fixed to 2.5s https://android.googlesource.com/platform/frameworks/volley/+/master/src/main/java/com/android/volley/DefaultRetryPolicy.java#36 
It is resulting in timeouts.

##### Suggest a Fix 
One suggestion to make socket connection timeout configurable is to override the setRetryPolicy method of Request.java.

**Comment by wing328** [comment]
PR merged.
