### ISSUE TITLE
Go generation is somewhat broken.

### ISSUE THREAD

**Issue by AmandaCameron** [swagger-api/swagger-codegen#3644]
##### Description

- [ ] Swagger types that are free-form, such as the generator API's `GeneratorInput.Spec` field are being encoded as an undefined type `Object` -- I'd recommend these get defined as `interface{}`
- [ ] Non-JSON returning functions, such as `ClientsApi.DownloadFile` are always returning an error due to trying to unmarshal a non-json type.

##### Swagger-codegen version

Docker image latest for generator API. swagger.json self-reports as `"2.2.2-SNAPSHOT"`

##### Swagger declaration file content or url

Swagger generator's swagger.json causes these errors.

##### Command line used for generation

API Endpoint

**Comment by wing328** [comment]
Please provide a spec for reproducing the issue.

**Comment by AmandaCameron** [comment]
http://generator.swagger.io/api/swagger.json causes both of the issues I've
mentioned in this issue.

**Comment by wing328** [comment]
Thanks. @guohuang when you've time, would you please take a look?
