### ISSUE TITLE
Empty model objects are not deserialized correctly in generated python client

### ISSUE THREAD

**Issue by zbiro** [swagger-api/swagger-codegen#3647]
##### Description

Empty model objects are not deserialized correctly in generated python client.
When a referenced model entity does not contain any property (it is just an alias to a field) deserialization in generated python client does not work properly.
With the example bellow instead of the string value the resonse will contain an empty Message object (with a 'swagger_types' and 'attribute_map' field).

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url
```json
"paths": {
  "/messages/{id}": {
    "get": {
    "description": "Returns a message.",
    "responses": {
      "200": {
        "description": "Successful response, the desired message is here.",
        "schema": {
          "$ref": "#/definitions/Message"
        }
      }
    }
  }
},

"definitions": {
  "Message": {
    "description": "A message.",
    "type": "string"
  }
}
```

**Comment by wing328** [comment]
Setting $ref to property/field definition (not model) is not supported by the swagger parser at the moment.

Please define the response type as `string` inline.

**Comment by zbiro** [comment]
I found a workaround (fix?) for this issue. If the commented block is inserted to api_client.py then the mentioned blocks are filled properly.

```
def __deserialize_model(self, data, klass):
    """
    Deserializes list or dict to model.

    :param data: dict, list.
    :param klass: class literal.
    :return: model object.
    """
    instance = klass()

    #if(not instance.swagger_types):
    #return data
    #
    for attr, attr_type in iteritems(instance.swagger_types):
        if data is not None \
           and instance.attribute_map[attr] in data\
           and isinstance(data, (list, dict)):
            value = data[instance.attribute_map[attr]]
            setattr(instance, attr, self.__deserialize(value, attr_type))

    return instance
```

**Comment by wing328** [comment]
@zbiro thanks for suggestion a fix. I think your fix essentially performs a check/validation to see if `data` is a model.

May I know if you've time to submit a PR so that CIs can verify the change?

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/3668
