### ISSUE TITLE
[JavaScript] Promise client doesn't return response headers

### ISSUE THREAD

**Issue by amannn** [swagger-api/swagger-codegen#3654]
##### Description

I'm using Swagger with an API that allows for a request like HEAD /books which returns the number of books available as a response header.

The generated JavaScript Promise client doesn't return that information. It would help if it would at least provide a way to get access to the raw response object, so I could read the headers myself.

The swagger documentation suggests to call the method like so:

```
apiInstance.sendBooksMetadata(opts).then(function() {
  console.log('API called successfully.');
}, function(error) {
  console.error(error);
});
```
##### Swagger-codegen version

2.0
##### Swagger declaration file content or url

``` yaml
/books:
  head:
    summary: Get books info
    operationId: sendBooksMetadata
    parameters:
      - name: status
        in: query
        description: The book status. For example, "ACTIVE", "INACTIVE", "PENDING".
        type: string
        required: false
    tags:
      - Books
    responses:
      200:
        description: The number of books in the header
        headers:
          X-Books-Count:
            description: The number of books
            type: integer
```
##### Command line used for generation

```
java -jar ../../third-parties/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i schema/schema.yaml -l javascript -o javascript --additional-properties usePromises=true
```
##### Suggest a Fix

It looks like the exports.prototype.deserialize function of the generated ApiClient only returns the body of the response and the headers are lost in that function.

**Comment by wing328** [comment]
@amannn thanks for the feedback. For other clients (e.g. PHP, Ruby, Python, etc), there's an additional "WithHttpInfo" method to get not only the list of HTTP response headers but also the HTTP status code. Here is an example for PHP:

[getPetById](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php#L463)

[getPetByIdWithHttpInfo](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/Api/PetApi.php#L478)

For JS, we also want to something similar. Would this approach meet your requirement?

**Comment by amannn** [comment]
Thanks for the quick response! I had a look at that PHP function. That looks pretty good to me, would be great to have a similar function signature for the JS client.

**Comment by wing328** [comment]
@amannn may I know if you've time to contribute the enhancement?

**Comment by amannn** [comment]
Currently I'm sadly not able to. But if I'm the only one interested in this feature, maybe you can just leave the issue open so I might help in the future.

**Comment by kpradeepkumarreddy** [comment]
I'm trying to get headers for android client. how can i get the headers ?
my yaml file is as follows:-
------------------------------
paths:
  /login:
     post:
      summary: send mobileNum and otp to login
      description: send mobileNum and otp to login
      parameters:
        - name: args
          in: query
          description: send mobileNum and otp in args 
          required: true
          type: string
          format: string
      tags:
        - login
      responses:
        '200':
          headers:
            Authorization:  
              description: access token will be set in the authorization header
              type: string
          description: login successful, received accessToken in header and refreshToken in body
          schema:
            $ref: '#/definitions/ResponseTO'
=> in the response i'm not getting the headers.

**Comment by fehguy** [comment]
I believe the codegen returns a POJO for the model and not the headers

**Comment by wing328** [comment]
@kpradeepkumarreddy please call the `WithHttpInfo` method (for every endpoint) to get the response headers as well as status code.

**Comment by kpradeepkumarreddy** [comment]
what should i do to get the headers in response. I'm using android client and volley library.

**Comment by wing328** [comment]
Please use the Java (okhttp-gson) API client instead.
