### ISSUE TITLE
[JAVA] How to parse OAuth2Definition into code

### ISSUE THREAD

**Issue by infastra** [swagger-api/swagger-codegen#3659]
I'm trying to generate code Java-code from a RESTful API by using swagger-codegen-plugin (in maven). The converting of messages and api-clients works. Only the creation of OAuth2-Objects doesn't run as aspected. Either authorizationUrl nor tokenUrl I will found in the generated code. Do I have to make some settings in the configuration? The basefile of the swagger-application describes the definitions as follows:

``` json
"securityDefinitions": {
  "app-oauth": {
    "description": "Normal app access token-based authorization.",
    "type": "oauth2",
    "authorizationUrl": "https://beta.my-app.com/api/v3/oauth2/authorize",
    "tokenUrl": "https://beta.my-app.com/v3/authorization/token",
    "flow": "accessCode",
    "scopes": {
      "app:full": "Full user-level access to a app-account."
    }
  }
}
```

Do you have any ideas how I could create a runnable OAuth2Definition in my java-code?

Swagger-codegen version: 2.2.1

**Comment by wing328** [comment]
@infastra can you try to generate the Java (retrofit2) client to see if that meets your requirement?

This may help: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

**Comment by wing328** [comment]
Closing this as there's no update.
