### ISSUE TITLE
Unable to configure for PropertyNamingStrategy for sdk generated in scala from swagger-codegen.

### ISSUE THREAD

**Issue by SangeetaGulia** [swagger-api/swagger-codegen#3663]
Originally, in ScalaUtilJson Object(in generated SDK) we are getting : 

object ScalaJsonUtil {
  def getJsonMapper = {
    val mapper = new ObjectMapper()
    mapper.registerModule(new DefaultScalaModule())
    mapper.registerModule(new JodaModule());
    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    mapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT)
    mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
    mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)
    mapper
  }
}

we need one more configuration to be included here:
mapper.setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES);

Is there any way to configure it or to set this property using swagger-codegen-cli, such that we do not have to make changes in the generated sdk.

**Comment by wing328** [comment]
The option to name the model property with a different convention is done via https://github.com/swagger-api/swagger-codegen/pull/3685
