### ISSUE TITLE
Enhancement | Tizen | Make prefix an optional parameter

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-codegen#3670]
##### Description

The Prefix in the TizenClientCodegen is hard-coded to Sami. Need to make this a optional parameter, and default the value to SWG like in the ObjC codegen

##### Swagger-codegen version

2.2.2-SNAPSHOT

**Comment by maneeshsahu** [comment]
@wing328 Can I push my commits directly, or do I need to create a PR?

**Comment by akhilkedia** [comment]
The variable String PREFIX is indeed assigned the value "Sami", however the prefix is actually never used anywhere. 
The Prefix was abandoned to give the files a "cleaner" file name.

**Comment by wing328** [comment]
@maneeshsahu please create a PR for any change/fix. Please also pull the latest 2.3.0 branch as https://github.com/swagger-api/swagger-codegen/pull/3666 has been merged into 2.3.0 instead of master.
