### ISSUE TITLE
Duplicate object created in core + model folders

### ISSUE THREAD

**Issue by equinox2k** [swagger-api/swagger-codegen#3673]
##### Description

Duplicate object created in core + model folders
##### Swagger-codegen version

v2.3.0
##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://cosus-mobile-api.pnimedia.com/swagger/docs/v3 -l objc -o /Users/ptribe/Documents/Api
##### Steps to reproduce

Running the above command line creates two classes of same name in Core + Model called SWGObject.h

And thus the model version has .m code that looks like...
# import <Foundation/Foundation.h>
# import "SWGObject.h"

@protocol SWGObject
@end

@interface SWGObject : SWGObject //compiler complains recursive
@end

in order to fix i had to rename the core object to SWGObjectCore

**Comment by wing328** [comment]
@equinox2k thanks for reporting the issue. 

@mateuszmackowiak would you please take a look when you've time?

**Comment by wing328** [comment]
@equinox2k I think it's due to the following:
```
        '201':
          description: Project added to cart successfully
          schema:
            $ref: '#/definitions/Object'
```
but '#/definitions/Object' is not defined. That's why an empty SWGObject is created.
