### ISSUE TITLE
Java Codegen in Android sending incorrect content-length on POST

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-codegen#3674]
##### Description

I am using the gson/okhttp Java codegen. When I exercise a POST Java call in Android Studio, I get this error

`client.ApiException: java.net.ProtocolException: unexpected end of stream
08-29 16:42:43.451 24498-26385/cloud.artik.example.hellocloud W/System.err:     at cloud.artik.client.ApiClient$1.onFailure(ApiClient.java:1014)
08-29 16:42:43.451 24498-26385/cloud.artik.example.hellocloud W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
08-29 16:42:43.451 24498-26385/cloud.artik.example.hellocloud W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
08-29 16:42:43.451 24498-26385/cloud.artik.example.hellocloud W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-29 16:42:43.451 24498-26385/example.hellocloud W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-29 16:42:43.451 24498-26385/example.hello W/System.err:     at java.lang.Thread.run(Thread.java:818)`

It seems like the Content-Length being sent is 1 less than the actual value. In my case, the header says 137, but it should be 138.
##### Swagger-codegen version

2.2.2-SNAPSHOT/main
##### Steps to reproduce

This works in Java 8 (outside Android Studio) though.
okhttp-version: 2.7.5

**Comment by wing328** [comment]
@maneeshsahu thanks for reporting the issue. As a workaround, can you please try the `retrofit2` Java library (instead of `okhttp-gson`) and `android` generator?

**Comment by wing328** [comment]
Closing this as there's no update.
