### ISSUE TITLE
Add 'modelPropertyNaming' option for Scala

### ISSUE THREAD

**Issue by arpitkulria** [swagger-api/swagger-codegen#3675]
##### Description
This option is already in type script but don't have for scala, this is used while generating case classes and maintain its casing.
Currently it is set to camel case.

##### Suggest a Fix
Will be creating a PR for this (only option).

**Comment by arpitkulria** [comment]
PR for the same #3676

**Comment by wing328** [comment]
Instead of changing the model property naming convention, what about using a scala lib that can handle the mapping between model property name and JSON key name? e.g. https://github.com/spray/spray-json

**Comment by arpitkulria** [comment]
@wing328 Yeah, that's a valid point, but we are changing nothing, just giving users another option to work with.
What I am trying to have the ability to make model property naming convention configurable instead of only camel case.

**Comment by wing328** [comment]
But naming the property in other naming convention (e.g. snake_case) will not conform to the Scala style guide: http://docs.scala-lang.org/style/naming-conventions.html

Also for Json key name with special characters such as dash (e.g. created-at), that won't work without a proper lib to handle the mapping.

**Comment by arpitkulria** [comment]
Yeah, completely with you on this point, but flexibility is always an add-on :)

**Comment by wing328** [comment]
@arpitkulria the PR has been merged into master. May I know if you've time to add the support of `spray-json` for Scala API client?

**Comment by arpitkulria** [comment]
@wing328 Thanks and sure, I'll try. :)
