### ISSUE TITLE
[swagger-codegen-maven-plugin:2.2.1] Use both java8 date-time and model name suffix will result wrong date-time class name

### ISSUE THREAD

**Issue by fayndee** [swagger-api/swagger-codegen#3678]
##### Description

When using `swagger-codegen-maven-plugin:2.2.1`, if both `dateLibrary=java8` and `modelNameSuffix=Resource` options are specified, it will accidentally generate fields with type for example: `OffsetDateTimeResource`.
##### Swagger-codegen version

2.2.1
##### Command line used for generation

Maven config:

``` xml
<plugin>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>2.2.1</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>http://petstore.swagger.io/v2/swagger.json</inputSpec>
                <language>java</language>
                <library>retrofit2</library>
                <configOptions>
                    <dateLibrary>java8</dateLibrary>
                </configOptions>
                <modelNameSuffix>Resource</modelNameSuffix>
            </configuration>
        </execution>
    </executions>
</plugin>
```
##### Steps to reproduce

Run `mvn package`.

**Comment by wing328** [comment]
@fayndee thanks for reporting the issue.

cc @cbornet

**Comment by liqidator** [comment]
+1

**Comment by wing328** [comment]
@fayndee @liqidator it should be fixed in the latest master. Please give it a try.

If not, we'll reopen this issue and look into it again.

**Comment by liqidator** [comment]
When I use format: uuid (https://github.com/swagger-api/swagger-codegen/pull/4739) and modelNameSuffix=Gen, the outcome type is UuidGen, which is not compilable.
Probably best to re-open.

**Comment by wing328** [comment]
@liqidator which version are you using? 2.2.2 (released a few days ago)?

**Comment by liqidator** [comment]
Yes, I used 2.2.2

**Comment by wing328** [comment]
Reopened the issue. If you remove 'format: uuid" (which means it's just a string), would that work?

**Comment by liqidator** [comment]
Thanks. When I removed format uuid, it worked fine. But I had to use just type string for uuid

**Comment by wing328** [comment]
Ok, so I think that's an edge case my fix/work didn't handle properly. 

Would you have time to contribute the fix? I can show you some good starting points.

**Comment by ePaul** [comment]
I start to regret having contributed this feature (modelNamePrefix/Suffix) :-(
... or at least this way of implementing it.

**Comment by liqidator** [comment]
No, it's really useful feature. I guess the implementation is tricky as you have to either cover all edge cases or come up with generic implementation. 
I am sorry I am stuck with business stuff, I wish I had time to contribute.

**Comment by wing328** [comment]
@ePaul I'm sure many Swagger Codegen users appreciate your work on this feature.

This issue will be a minor fix: Java generator thought that a property/parameter with `uuid` type is a model, we'll need to add `uuid` to the list of language-specified primitive type to fix the issue.

**Comment by ePaul** [comment]
I think I added this at a wrong place ... or possibly the current architecture only allows this hacky way.

There should be one place where names of model types are mangled (adapted to language style), and a different place where names of predefined types are retrieved (like String, UUID, Integer/Double, BigDecimal, all the date types, Maps/Lists, etc.). The prefixing/suffixing should only happen in the first case.

**Comment by otrosien** [comment]
@ePaul would you mind adding a follow-up ticket to rework that part of the code?

**Comment by ePaul** [comment]
@otrosien Done, #5027. Thanks for the hint.

**Comment by wing328** [comment]
@liqidator the issue should be fixed via #5026. My test result is good. Please pull the latest master to give it a try.

**Comment by otrosien** [comment]
@wing328 AFAICS #5026 is only for fixing the UUID issue. #5027 is supposed to tackle the logic where type-mapping is applied in general, in order to simplify / fix such problems in the future.

**Comment by Ashishen** [comment]
Hi, I am using maven plugin 2.3.1, is there any way we can generate date-time in java.utils.date format?
