### ISSUE TITLE
Add "modelPropertyNaming" config option for java

### ISSUE THREAD

**Issue by geetikagupta16** [swagger-api/swagger-codegen#3681]
##### Description

This issue is concerned with adding a new config option for java language. This option is already available for other languages. This option is used while naming the class variables for java, default value for this is set to camelCase.

##### Suggest a Fix

Can have a function to check for the "modelPropertyNaming" option and set the parameter name accordingly.

**Comment by wing328** [comment]
Not all generators need the `modelNamingProperty` option, which was introduced for the Typescript generators as Typescript API client does not support mapping between model's properties and JSON key name.

The current property naming convention for Java should conform to the Java style guide.

**Comment by geetikagupta16** [comment]
There can be scenarios when our json response is in snake_case while our model's class variables have camelCasing, so to overcome that problem we can use this option for json mapping.

**Comment by wing328** [comment]
We already took care of that scenario, which means the mapping should already work in the existing Java client (no matter what HTTP library you used: jersey, jersey2, okhttp-gson, retrofit, retrofit2)

If you did find an issue with the mapping, please provide details (e.g. spec to reproduce the issue, etc)

**Comment by geetikagupta16** [comment]
What I am trying to do is to map the response Json into the model's classes.
My response case classes are represented in camelCase and json response are in snake_case.
For example: 
case class Person(firstName: String) 
Response format : 
{
first_name : "abcd"
}
and the generated SDK for java is unable to map the response back into the model's classes.

The model classes that I get from the SDK using jersey2 library is as follows:
public class Person {
@JsonProperty("firstName")
public String firstName;
}

I will create a demo project so you can have a look and let me know if I am doing anything wrong.

Thanks.

**Comment by wing328** [comment]
Can you share the spec for the model you mentioned?

**Comment by geetikagupta16** [comment]
Here is the link for the project:
https://github.com/geetikagupta16/testSwagger

and the command that I used to generate SDK is as follows:

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://localhost:9000/docs/swagger.json -l java -o demoSwagger

Below is the screenshot of the swagger.json file
![image](https://cloud.githubusercontent.com/assets/17196397/18194134/1422ea16-7101-11e6-9497-519ef2865f6f.png)

**Comment by cbornet** [comment]
If you want it to be "first_name" in the exchanged JSON, set it as "first_name" in the swagger spec. The codegen will take care of camel casing the java property.

**Comment by geetikagupta16** [comment]
The definitions part in swagger.json is autogenerated based on our response case classes. As we are using scala, so we can't use snake_case for case classes as it violates scala standards.

**Comment by wing328** [comment]
Your swagger spec is not correctly describing your REST API, no matter whether it's auto-generated or manually created. What plug-in are you using to generate swagger.json from annotation in your scala code base?

**Comment by geetikagupta16** [comment]
We are using iheartradio play-swagger and here is the github link for the same : 
https://github.com/iheartradio/play-swagger

We have validated the generated spec by swagger-editor and we are successfully able to generate swagger-UI.

**Comment by wing328** [comment]
If the JSON key name is `first_name` and you document it as `firstName`, it's simply incorrect and tools built on top of Swagger won't be able to determine the correct JSON key name, which is `first_name` (even though the spec is valid)

**Comment by geetikagupta16** [comment]
But as per scala standards we can't use snake_case in our case classes. Is there any other way to configure the mapping option so that it can map snake_case Json to camelCase ?

**Comment by cbornet** [comment]
This is an issue with play-swagger. You should open an issue there.

**Comment by geetikagupta16** [comment]
My colleague has created an issue over there.
Thanks for the help.
