### ISSUE TITLE
Add support for threetenbp datetime library for clients [Java]

### ISSUE THREAD

**Issue by mikeholler** [swagger-api/swagger-codegen#3688]
Swagger currently provides code generation options for `java.util.Date`, `java.time`, and `joda`. Joda has shown to be lacking in some ways (notably only allowing for millisecond precision).

Android developers like myself (and developers on other systems constrained by Java version pre-1.8) needing microsecond or nanosecond precision, and developers hoping to migrate to Java 8 someday, have taken to using [ThreeTenBP](https://github.com/ThreeTen/threetenbp) to bridge this gap.

In addition to being a backport of the Java 8 `java.time` APIs, ThreeTenBP is written and maintained by Steven Colbourne, author of Joda Time and JSR-310 (the standard that became `java.time`) and used by many Java developers stuck on pre-Java 8 systems.

I would like to start generating our Java clients using our Swagger specifications, but the biggest limiting factor in my doing so is the lack of support for ThreeTenBP as a date library option for Java. Could a "threetenbp" library option be added to the Java client generator?

**Comment by cbornet** [comment]
Interesting. That would  replace joda I guess...

**Comment by mikeholler** [comment]
I don't know that it has to replace `joda-time`, since tons of people still use it. More of an addition than a replacement is what I'd think would be best.

**Comment by cbornet** [comment]
It would be at least our default dateLibrary : http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html

**Comment by mikeholler** [comment]
Yeah, I think switching it to the default makes sense.
