### ISSUE TITLE
TypeScript Angular2 wrong Map usage

### ISSUE THREAD

**Issue by ataraxus** [swagger-api/swagger-codegen#3695]
##### Description

Hello, I'm using the editor.swagger.io for code generation. I stumbled upon this: If you define formData parameter the api client generates following code: 
`formParams['key'] = value;`
which leds to an empty request, since later on the request parameters are derived by;
`requestOptions.body = formParams.toString();` 
The 'correct' usage of the TS Map interface would be:
`formParams.set('key', value);`

I would imagine that this could be a fairly simple fix, I even looked at the **TypeScriptAngular2ClientCodegen.java** but wasn't sure if this could be the [problem](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java#L123) 

##### Swagger-codegen version

editor.swagger.io

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Broken TS Map generation
host: broken.map
basePath: /

paths:
  /brokenMap:
    post:
      parameters:
        - name: limit
          in: formData
          description: number of User to return
          type: integer
         
      responses:
        200:
          description:  List all User
          schema:
            title: Pets
            type: array
            items:
              $ref: '#/definitions/User'

definitions:
  User:
    type: object
    properties:
       roles:
        type: array
        items:
          type: string

```

**Comment by wing328** [comment]
@ataraxus thanks for reporting the issue and suggesting a fix. I believe updating this line should fix it: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L90

May I know if you've time to contribute a fix?

**Comment by ataraxus** [comment]
@wing328 Hey, thanks for pointing this out! yes this looks like the correct place to fix it, actually i can see that there are already some other bugs fixed which i have on my list..

I'll try to setup the project on my machine and test the change and also see if the other issues i experienced still exist!

**Comment by ataraxus** [comment]
@wing328 fixed it. good that i had also an edge case in my api, so I had to add explicit casting before calling .set. right now it works like a charm ;) 

By the way, it fixed all other issues i had with the previous release! kudos!

When will this version be released?

**Comment by wing328** [comment]
@ataraxus usually it takes 3 to 4 months for a minor release.
