### ISSUE TITLE
Client Generator

### ISSUE THREAD

**Issue by joskfg** [swagger-api/swagger-codegen#3701]
##### Description

When I try to generate a PHP client, I get this error:
` Could not process model 'File'.Please make sure that your schema is correct!`

I guess this happens with other generator because the error is in "DefaultGenerator".

##### Swagger-codegen version

master

##### Swagger declaration file content or url

https://download.sftapi.com/schema

##### Command line used for generation

```
echo '{
        "modelPackage": "Softonic\\DownloadApiSdk\\Model",
        "apiPackage": "Softonic\\DownloadApiSdk\\Api",
        "invokerPackage": "Softonic\\DownloadApiSdk",
        "packagePath": "DownloadApiSdk",
        "srcBasePath": "src",
        "composerVendorName": "softonic",
        "composerProjectName": "download_api_sdk",
        "artifactVersion": "v2.0.95"
}' > config
docker run -u 996 -i -w /gen -v /var/lib/jenkins/workspace/sdk-generator:/gen -v /var/lib/jenkins/.m2/repository:/root/.m2/repository maven:3-jdk-7 java -jar /gen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l php -i swagger.json -o generated -c config
```

##### Steps to reproduce

Just try to create the client. It fails in generation part.

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/3396
https://github.com/swagger-api/swagger-codegen/issues/3693

##### Suggest a Fix

The error is too deep inside the swagger-codegen and I didn't find the way to fix it. I'll get another try.

**Comment by joskfg** [comment]
It seems a fail in my swagger. It validates but it indicates 

```
type: array
items { type: array}
```

So the generator don't know how to generate it. I modified the schema to do a reference and it should work.

```
type: array
items { $ref: #/definitions/test }
```

**Comment by wing328** [comment]
@joskfg If you want to generate a 2D array of model, you will need to specify the `items` for the inner array.
