### ISSUE TITLE
[JAVA] InlineModelResolver drop all vender extensions for any Schema Object

### ISSUE THREAD

**Issue by zhengcan** [swagger-api/swagger-codegen#3706]
##### Description

The spec told me "Allows extensions to the Swagger Schema."
ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-objects-9

When I define some schema objects in `definitions` section, and use $ref to reference it in response, I've noticed that all vender extensions works well.
But when I use the vender extensions in 'schema' section in `response` directly, all vender extensions gone.

I've debugged my generator code, and confirmed that the `InlineModelResolver` used by `DefaultGenerator` drops all vender extensions when it try to `flatten` all response schema objects to inline schema.

For example:
```java
    public Model modelFromProperty(ObjectProperty object, String path) {
        String description = object.getDescription();
        String example = null;

        Object obj = object.getExample();
        if(obj != null) {
            example = obj.toString();
        }
        String name = object.getName();
        Xml xml = object.getXml();
        Map<String, Property> properties = object.getProperties();

        ModelImpl model = new ModelImpl();
        model.setDescription(description);
        model.setExample(example);
        model.setName(name);
        model.setXml(xml);

        if (properties != null) {
            flattenProperties(properties, path);
            model.setProperties(properties);
        }

        return model;
    }
```

I'm not sure why it work like this, but it seams like a kind of bug.

As workaround, I have to `cache` all vender extensions for response schema in `preprocessSwagger(Swagger)`, and set them back in `fromOperation(String, String, Operation, Map<String, Model>, Swagger)`.

##### Swagger-codegen version

master

##### Swagger declaration file content or url

```yaml
response:
  200:
    schema:
        type: object
        properties:
            ....
        x-my-ext: the-value
```

In mustache file:
```mustache
{{#operations}}{{#operation}}
  {{#responses}}
    {{schema.venderExtensions}}
  {{/responses}}
{{/operations}}{{/operation}}
```

##### Command line used for generation

Just run generator.

##### Steps to reproduce

Run generator, and check the output file.

##### Related issues

na

##### Suggest a Fix

Modify `InlineModelResolver` to handle vender extensions.

**Comment by wing328** [comment]
@zhengcan thanks for reporting the issue. May I know if you've time to contribute a fix to `InlineModelResolver`?

As a workaround, you can fully define the model instead of doing it inline.
