### ISSUE TITLE
Enhancement: Json Schema id attribute in models

### ISSUE THREAD

**Issue by beaupral** [swagger-api/swagger-codegen#3715]
##### Description

This is a suggestion to include Json Schema "id" attribute into models objects.
This would allow us to organize and regroup our Java model objects under different packages (similar to xml namespace usage in JAX-WS).

I have not seen anything else that would allow me to generate "dynamic" model package name.

Thanks!

**Comment by wing328** [comment]
@beaupral in the spec, did you manually add the "id" attribute into each model?

**Comment by beaupral** [comment]
@wing328 Thanks for the quick reply!  However I'm not sure I understand your question.

We have just started writing our APIs spec with YAML.  This work is divided into multiple YAML files and multiple JSON Schema files (in which the "id" attribute is defined).  We would like to regroup generated java model objects by their JSON schema file "id" (the package name would have the same name as the "id" attribute).
  
Does this make sense ?

We also feel this would ease reusing already generated java objects between APIs.

**Comment by wing328** [comment]
@beaupral sorry I don't think I understand. Please elaborate by providing an example.

**Comment by beaupral** [comment]
@wing328 Basically, our problem is the following:  
In our yaml, we have many "models" defined in the "definitions" section.
We would like to regroup generated java objects in subpackage to ease maintenance.  

For example, we would like objets relating to "orders" to be automatically generated inside package
com.model.orders

And objets relating to "clients" to be generated inside package
com.model.clients

Note that "orders" objects may contain references to "clients" objects.

I don't think this can be done with the current version of swagger-codegen.  Furthermore, I don't think there would be a standard way in swagger to hint in which package the model would belong.  My suggestion was to use the json schema "id" attribute as the package name, but anything else that would allow "subpackage" would make us happy.

**Comment by wing328** [comment]
@beaupral we do not support this particular use case at the moment.

Assuming you're referring to the Java API client generator, you can customize the following to meet your requirement:

- generator: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
- templates: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/Java
