### ISSUE TITLE
Spring Server codegen - swagger-2.0 basePath not generated

### ISSUE THREAD

**Issue by tdhancii** [swagger-api/swagger-codegen#3720]
##### Description

@RequestMapping annotation is not generated in spring server code generation.
basePath is properly defined in swagger.yaml file.

##### Swagger-codegen version

Swagger codegen version :
swagger-codegen-maven-plugin: 2.2.1 and also tired with 2.2.2-SNAPSHOT

##### Swagger declaration file content or url

https://gist.github.com/tdhancii/1d0dde04413b6d98a76598a549a68985

##### Command line used for generation

Used Maven plugin to generate code
` <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/swagger.yaml</inputSpec>
                            <apiPackage>co.test.swagger.api</apiPackage>
                            <modelPackage>co.test.swagger.model</modelPackage>
                            <language>spring</language>
                            <environmentVariables>
                                <models></models>
                                <apis></apis>                                <supportingFiles>HomeController.java,SwaggerDocumentationConfig.java</supportingFiles>
                            </environmentVariables>
                        </configuration>
                   </execution>
                </executions>
            </plugin>
`
##### Steps to reproduce

just generate the code using maven plugin and check the DomainApi.java class. You will see that there is not path mapping annotation for basePath: v1 defined in the swagger spec

**Comment by wing328** [comment]
The context Path (e.g. v1, v2) should be set in application.properties, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/springboot/src/main/resources/application.properties

**Comment by tdhancii** [comment]
I think basePath:v1 given in my example is a bad choice.
Consider the following scenario, 

Spring Boot application server root context : /my-app

Under this root context I will be in need of
/my-app/account/...
/my-app/bills/...
/my-app/payments/...

So in this case, I will define

server.contextPath=/my-app

and in swagger doc I will define
basePath: /account
basePath: /bills
baseapth: /payments 

Each of these basePath results in a separate Spring Rest Controller class with their root context as "account", "bills" and "payments" respectively.  Here the understanding is that basePath in swagger is the root context path for Controller class rather than for spring boot server. Because I can have many controllers each with a different basePath but same server root context.

With this understanding, I was under the impression that following would be a fix

File: modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache b/modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache

 {{>generatedAnnotation}}
 @Api(value = "{{{baseName}}}", description = "the {{{baseName}}} API")
@RequestMapping(value = "{{contextPath}}")   - Proposed Fix 
 {{#operations}}
 public interface {{classname}} {
....
....
}

**Comment by ShortyFR** [comment]
How can the context v1 or v2 (which can both be contained in the same Spring instance) be set in application.properties (which is common to all endpoints in the Spring instance) ?
And what if the same Spring instance handles other URLs than just the Swagger-managed API ?
