### ISSUE TITLE
[Apex] New API client generator

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3722]
##### Description

We want to add a new API client generator for [Apex](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_intro.htm), a programming language invented by SalesForce.
##### Swagger-codegen version

Latest master

If anyone wants to work on this task, please reply to let us know.

Given that it's similar to Java, cloning the Java API client generator is a good starting point

Ref: https://en.wikipedia.org/wiki/Salesforce.com#Apex

**Comment by khalidx** [comment]
Hey there @wing328 , I think I can take this on. Have worked on two custom generators, so I think I have the flow good.

**Comment by wing328** [comment]
Thanks @khalidx

**Comment by khalidx** [comment]
Cool, if you could go ahead and assign it to me I'll get started.

Also, I landed here after noticing the following question on the SalesForce Success Community Forum:
[SalesForce Idea: "Swagger2Apex" REST callout code generator](https://success.salesforce.com/ideaView?id=0873A000000CPZjQAO)

**Comment by pcon** [comment]
@khalidx i don't have time to help write it but I can help you test it. Let me know when you get to that stage if you need it.

**Comment by khalidx** [comment]
@pcon Sounds great! Thank you for the help.

**Comment by asnelling** [comment]
I've actually been working on one. It's complete, but could probably use some tweaks from someone who's already built a few generators. @khalidx if you're not already underway, this could give you a head start.
I had to work around quite a few of the intricacies (often inconvenient, undocumented) of Apex so it's not quite a clone of the Java codegen.

**Comment by khalidx** [comment]
"Often inconvenient, undocumented" -- sounds like Apex ;)

That's awesome, can you share your repo/branch? I only have basic scenarios working so far, with paths/model generation.

**Comment by asnelling** [comment]
Here it is: https://github.com/asnelling/swagger-codegen/tree/apex-codegen

I'm using this generator for a fairly large API, so I had to make some design decisions that avoid eating up too much of my [Apex limits](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm#size_gov_limits_section)
... just another one of those Salesforce things

**Comment by wing328** [comment]
@asnelling do you mind submitting a PR so that we can review it?

**Comment by muenzpraeger** [comment]
@asnelling Let me know if you're going to proceed with your generator. I started my own and may (want) stop if yours gets added. ;-)

**Comment by wing328** [comment]
@asnelling may I know if you need help submitting a PR? or you want us to submit a PR based on https://github.com/asnelling/swagger-codegen/tree/apex-codegen on your behalf?

**Comment by wing328** [comment]
@khalidx @muenzpraeger I've added Apex API client generator based on https://github.com/asnelling/swagger-codegen/tree/apex-codegen by @asnelling 

Please pull the latest master to give it a try.

For discussion on enhancing the Apex client generator, please go to https://github.com/swagger-api/swagger-codegen/issues/5670

**Comment by wing328** [comment]
UPDATE: another PR to add Apex generator has been filed by @nikhltripathi696 

Please check it out and see if we can merge some of the features/enhancements into the Apex generator in the current master.

**Comment by muenzpraeger** [comment]
@wing328 I'm not sure what @nikhltripathi696 wants to add. That PR only contains old code/commits from the initial creation of the generator.

https://github.com/swagger-api/swagger-codegen/pull/6849/commits

**Comment by wing328** [comment]
@muenzpraeger thanks for reviewing

@nikhltripathi696 did you mean to submit a PR with enhancements to the current Apex client generator?

**Comment by arangari** [comment]
Hello @wing328 , while  working on CUFX 4.1 API integration, I came across the swagger generated client SDK code for APEX. I found multiple issues in the generated code. While I understand the generated code may not ensure that everything works without any trouble, I wanted to know if we were able to test some basic behaviors of generated code on Apex.  I would be interested in knowing more.



FYI : This is my first time on using SwaggerHub and the generated code.

**Comment by muenzpraeger** [comment]
@arangari We moved over here => https://github.com/OpenAPITools/openapi-generator

**Comment by arangari** [comment]
@muenzpraeger  - thanks for the help. Does this mean, I can get the client SDK of published APIs on openAPI?

**Comment by muenzpraeger** [comment]
@arangari The core maintainers of this repo moved to OpenAPITools. I'd look there.
