### ISSUE TITLE
Python client only accepting Json in body parameters of POST requests

### ISSUE THREAD

**Issue by bkryza** [swagger-api/swagger-codegen#3723]
##### Description

Python client seems to only accept JSON Content in the body of POST requests, other formats must be sent in formData.

##### Swagger-codegen version

master

##### Swagger declaration file content or url

See the following Gist: [echo-xml.yaml](https://gist.github.com/bkryza/4a786fade448137483266785aa01e9ed)

##### Command line used for generation

```bash
cd swagger-codegen

mvn package

vim echo-xml.yaml # Paste the above example

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l swagger -i ./echo-xml.yaml -o ./output/echo-xml

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l swagger -i ./samples/yaml/echo-xml.yaml -o ./output/echo-xml
```

##### Steps to reproduce
Generate the Python client using the above steps.

Then create an [echo-xml-test.py](https://gist.github.com/bkryza/2503f95f614fbd73d763b68d31718296) in the swagger-codegen folder and run the script. Server is not necessary, as the client fails before making any HTTP requests:

```bash
> swagger-codegen git:(master):  python echo-xml-test.py
Traceback (most recent call last):
  File "echo-xml-test.py", line 43, in <module>
    echo_api.echo(message=echo_message, callback=None)
  File "./output/python/swagger_client/apis/default_api.py", line 78, in echo
    (data) = self.echo_with_http_info(message, **kwargs)
  File "./output/python/swagger_client/apis/default_api.py", line 160, in echo_with_http_info
    collection_formats=collection_formats)
  File "./output/python/swagger_client/api_client.py", line 313, in call_api
    _return_http_data_only, collection_formats)
  File "./output/python/swagger_client/api_client.py", line 147, in __call_api
    post_params=post_params, body=body)
  File "./output/python/swagger_client/api_client.py", line 350, in request
    body=body)
  File "./output/python/swagger_client/rest.py", line 210, in POST
    body=body)
  File "./output/python/swagger_client/rest.py", line 167, in request
    r = RESTResponse(r)
UnboundLocalError: local variable 'r' referenced before assignment
```

##### Suggest a Fix
The problem is in the `rest.mustache` file, which for body parameters only checks for `json` mimeType. For body parameters it should also allow other "text" formats such as xml, yaml, plain, etc...

**Comment by wing328** [comment]
@bkryza the API client (Python, Ruby, PHP, etc) does not support other formats (xml, yaml, etc) at the moment.

If you modify the `to_str` method ([example](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/models/user.py#L286)) to return an XML representation of the object, it should work.

**Comment by bkryza** [comment]
@wing328 Thanks for the information.

Unfortunately, the problem is not that the generated client fails to serialize the `body` argument which I provide. In fact in this example I provide already serialized XML as a string. The problem is that the client checks only the declared content-type and does not check the type of the body argument. 

I've just tested the Ruby client and it works just fine ([echo-xml-test.rb](https://gist.github.com/bkryza/dbaf7016f670b109528de4d86aede5ad)). 

I guess the Python client is missing the following condition which exists in the Ruby version: 

[data = body.is_a?(String) ? body : body.to_json](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/ruby/api_client.mustache#L272)

I will submit a PR to show you where the problem is...

**Comment by wing328** [comment]
@bkryza thanks for the fix, which has been merged into master.
