### ISSUE TITLE
[Java] Use RFC3339 formats for java.util.Date

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#3727]
- Jackson has an ISO8601Utils class that can be used to easily make a RFC3339DateFormat (or simply use the existing ISO8601Dateformat but it loses the timezone and milliseconds when serializing).
- ~~Gson has an equivalent UtcDateTypeAdapter~~ For Gson, it's easy to write a TypeAdapter using gson's ISO8601Utils.

These are more performant than SimpleDateFormat and SimpleDateFormat cannot be used on android (since "XXX" pattern is not supported).

**Comment by wing328** [comment]
Looks like we can close this.
