### ISSUE TITLE
[develop 2.0] add csharp generator

### ISSUE THREAD

**Issue by jamesecahill** [swagger-api/swagger-codegen#373]
Not sure if this is already in the works or not... I can start on porting the one from `master` if you'd like. 

@fehguy Please let me know what you think. Thanks.

**Comment by fehguy** [comment]
that'd be great.  Please take a look at the test structure as well, I'm looking to get the templates tested for all languages.

**Comment by josephmisiti** [comment]
is anyone working on this now ? i am going to need to do this for a project and wont want to waste time if it is done / almost done if possible.

- thanks

**Comment by fehguy** [comment]
We won't release 2.1.0-M1 without this, so it's something I hope to have done in the next 2 weeks.  I'd love contributions and/or review of the proposed template structure.

**Comment by jamesecahill** [comment]
@josephmisiti I was planning on it, but priorities shifted on my project and I won't be starting anytime soon.

**Comment by josephmisiti** [comment]
OK - I am new to this project - since it exists on master, is it as easy as a refactor of existing code, or has a lot changed and you basically are starting from scratch again ?

**Comment by fehguy** [comment]
The templates should be compatible with master.  The underlying code, however, is completely rewritten.

**Comment by wing328** [comment]
I think this one can be closed as C# generator was added to developer_2.0, which was merged into master via #598
