### ISSUE TITLE
[JAVA] array equals() fails findbugs

### ISSUE THREAD

**Issue by brentryan** [swagger-api/swagger-codegen#3731]
##### Description

Using swagger codegen to generate objects with arrays fails findbugs: http://findbugs.sourceforge.net/bugDescriptions.html#EC_BAD_ARRAY_COMPARE
##### Swagger-codegen version

2.2.2-SNAPSHOT
##### Swagger declaration file content or url

Create a property in a swagger definition like this:

```
byte:
     type: string
     format: byte
```

   Generates this code in equals()
`Objects.equals(this._byte, awesomeSnapshot._byte)`

**Comment by wing328** [comment]
@brentryan thanks for reporting the issue. May I know if you've cycle to make the enhancement?

I think we may need to handle it as a special case using `{{#isByte}} ... {{/isByte}}` mustache tag

**Comment by brentryan** [comment]
I might look into it, but it's currently not that important of a use case for us since we don't typically use byte[] types or binary types.  Both of those formats have the same issue here.  If I can get to this then I'll let you know but it might be a couple weeks before I get to it.

**Comment by wing328** [comment]
@brentryan thanks. If you need help submitting a PR, please let us (the community) know.

**Comment by bmordue** [comment]
I think this was fixed by #7341 ?

**Comment by wing328** [comment]
@bmordue yup, closing it.
