### ISSUE TITLE
[JAXRS-CXF] Enum values are generating &quot; stuff in the string

### ISSUE THREAD

**Issue by coding2012** [swagger-api/swagger-codegen#3735]
The code generator is creating "&amp;quot;" still in the jaxrs-cxf implementation:

Example:

    public enum TelecomTypeEnum {
          TELEPHONE(String.valueOf("&quot;TELEPHONE&quot;")), FAX(String.valueOf("&quot;FAX&quot;")), EMAIL(String.valueOf("&quot;EMAIL&quot;")), PAGER(String.valueOf("&quot;PAGER&quot;"));
        public static TelecomTypeEnum fromValue(String v) {
            return valueOf(v);
        }
    }

The Javadoc of the valueOf method is:
```Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)```

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url

Example JSON Swagger

```json
    "Telecom": {
            "type": "object",
            "properties": {
                "telecomType": {
                    "type": "string",
                    "enum": [
                        "TELEPHONE",
                        "FAX",
                        "EMAIL",
                        "PAGER"
                    ]
                },

```

##### Command line used for generation

mvn clean install using the following plugin:

```xml
<build>
        <plugins>
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${basedir}/src/main/resources/${project.artifactId}-swagger.json</inputSpec>
                            <language>jaxrs-cxf</language>
                            <configOptions>
                                <sourceFolder>/</sourceFolder>
                                <dateLibrary>joda</dateLibrary>
                            </configOptions>
```

##### Steps to reproduce

Clone this repo:
https://github.com/coding2012/swagger-codegen-issue-3735

Install latest maven 3, run
mvn clean install

Check folder:
target/generated-sources/swagger/com/test/model/Test.java

This file shows the &amp;quot;

##### Related issues

This might be somewhat related, but not sure. The fix in this issue missed the jaxrs-cxf codegen code I think:
https://github.com/swagger-api/swagger-codegen/issues/3450

**Comment by wing328** [comment]
@coding2012 I believe this is addressed in the latest master. Would you please pull the latest master and build the JAR locally to give it another try?

**Comment by coding2012** [comment]
Thanks for looking at this! Seems to be affected still:
`
    TELEPHONE(String.valueOf("&quot;TELEPHONE&quot;")), FAX(String.valueOf("&quot;FAX&quot;")), EMAIL(String.valueOf("&quot;EMAIL&quot;")), PAGER(String.valueOf("&quot;PAGER&quot;"));`

**Comment by wing328** [comment]
@coding2012 OK. Thanks for performing another test. I'll take a look and keep you posted.

**Comment by coding2012** [comment]
I may be able to mess around in the code, I see that it's nunjucks or some other templating system, I'll see if I can mess with the code a bit and rangle something up today.

**Comment by wing328** [comment]
@coding2012 As a workaround, you may consider `jaxrs` instead of `jaxrs-cxf` for server stub generation as `jaxrs` model templates should have the issue addressed.

**Comment by wing328** [comment]
@coding2012 fixed via #3750. Please pull the latest master and build the local JAR to give it a try.

**Comment by coding2012** [comment]
Wow, that worked perfectly!
No more &quot; issues! How do I send you a beer?

**Comment by wing328** [comment]
🍻 🍻 🍻
