### ISSUE TITLE
result field that used to generate HashCode is conflicting with model field with same name

### ISSUE THREAD

**Issue by teckken** [swagger-api/swagger-codegen#3736]
##### Description
result field that used to generate HashCode is conflicting with model field with same name "result", with that, what is the recommended workaround for this ?

I should not change the API model fields because the HashCode method is using the "result" variable name.

##### Swagger-codegen version
online generator : 2.2.1
output : android client

**Comment by wing328** [comment]
@teckken thanks for reporting the issue, which has been addressed by #3740 

Please pull the latest master and build the JAR locally to give it a try.
