### ISSUE TITLE
just need the class generate, not the whole project

### ISSUE THREAD

**Issue by sbuisson** [swagger-api/swagger-codegen#3737]
Hy, when I generate , I 've a whole project wo apear in generated-sources. I just need the src/main/java of this, 

Is there a way to have just this?

my config:
     ```
 <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>

```
                </execution>
            </executions>
            <configuration>
                
                <inputSpec>${basedir}/src/main/resources/api.yaml</inputSpec>

                
                <language>java</language>

                
                <configOptions>
                    <dateLibrary>java8</dateLibrary>
                </configOptions>
                <library>jersey2</library>
            </configuration>
        </plugin>
```

```
```

**Comment by wing328** [comment]
What about updating .swagger-codegen-ignore to ignore folders that you don't need?

**Comment by fehguy** [comment]
Either that or you can use the `<configuration>` options to disable any or all generators.
