### ISSUE TITLE
TypeScript Angular2 broken copy constructor usage

### ISSUE THREAD

**Issue by ataraxus** [swagger-api/swagger-codegen#3743]
Hey Guys, 

I stumbled upon the issue, that my default headers wouldn't be set as expected... currently this is used
` let headers = new Headers(this.defaultHeaders.values());`

where `Headers.values()` is returning: `string[][];`

the copy constructor of Headers is expecting this: 
` constructor(headers?: Headers | { [key: string]: any;  });`

I figured that this is working:
` let headers = new Headers(this.defaultHeaders.toJSON());`
since `Headers.toJSON()` returns: `  [key: string]: any;`

##### Swagger-codegen version

master

##### Swagger declaration file content or url
`swagger-codegen\modules\swagger-codegen\src\main\resources\typescript-angular2\api.mustache`

##### Command line used for generation
`./bin/typescript-angular2-petstore-all.sh`

**Comment by ataraxus** [comment]
created a pull request with the proposed fix.  #3744

**Comment by wing328** [comment]
PR merged.
