### ISSUE TITLE
[Python] codegen cannot produce a specific controller with the "tags" in .YAML file

### ISSUE THREAD

**Issue by bs-sdev** [swagger-api/swagger-codegen#3745]
##### Description

Hello everyone, 

I try to create multiple controllers in my API (on controller for each sub route). After reading the doc, I thought the key "tags" was used to specify on which controller the operation will be located on.

Nevertheless, it does not work with the Python server generation in which it only creates a "default_controller.py".

So unless I don't understand how it works on the python generation, could someone help me?

Thanks.
##### Swagger-codegen version

Latest (Done on http://editor.swagger.io/#/)
##### Swagger declaration file content or url

To illustrate my say, here is a part of my .yaml file: 

``` yaml
  /v0/application/new/{templateId}:
    post:
      tags:
        - test_controller
      description: |
        Get the templates list
      operationId: newApplication
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: templateId
          type: string
          required: true
        - in: body
          name: config
          required: true
          description: encoders needed to be implemented
          schema:
            $ref: "#/definitions/template"
```

And here is the part of the .yaml file generated into the archive I downloaded from the generator: 

``` yaml
paths:
  /v0/application/new/{templateId}:
    post:
      tags:
      - "test_controller"
      description: "Get the templates list\n"
      operationId: "controllers.default_controller.new_application"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "templateId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "config"
        description: "encoders needed to be implemented"
        required: true
        schema:
          $ref: "#/definitions/template"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            title: "object of the app infos"
            properties: {}
      x-tags:
      - tag: "test_controller"
```

**Comment by wing328** [comment]
@bs-sdev thanks for reporting the issue. I've spent some time to read [FlaskConnexionCodegen.java](modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java) and seems like it's not possible to create controllers by `tags` at the moment as all operations go to the same file (default_controller.py, which is configurable via CLI option).

Other server stub generator supports grouping methods by `tags` so we need to apply the same technique in the Python Flask generator.

May I know if you've time to contribute the enhancement? I can show you some good starting points to begin with.

**Comment by bs-sdev** [comment]
@wing328 Hello, I can spend some time on it, so yes, I can contribute, but could you tell me how? Maybe I should go to "How to contribute" ...

If you got ideas, it could be really great, while I wait for your reply, I watch the related file (JAVA programming is far for me, but I don't think it's difficult to be back on it!).

Kind regards.

**Comment by wing328** [comment]
@bs-sdev I've made the change to put the endpoints in different controllers based on `tags` via https://github.com/swagger-api/swagger-codegen/pull/3767 but now `python3 app.py` results in  errors. I wonder if you can take a look.

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3767 merged into master.
