### ISSUE TITLE
[JS] Setting license

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-codegen#3746]
##### Description

The JavaScript code generator always puts 

``` javascript
"license": "Apache-2.0",
```

in the generated package.json file. 
It should be possible to set this using the `projectLicenseName` property.
Also, according to the help screen, the default should be `info.license.name`. I don't know what that means, but it's not being used by the JS generator (or any others, it seems).
##### Swagger-codegen version

Latest from master, commit 47e75cb
##### Suggest a Fix

In `..../Javascript/package.mustache`, change the line above to

``` javascript
  "license": "{{{projectLicenseName}}}",
```

However, this will produce an empty string unless the user sets this optional property manually. If we want to default to Apache-2.0 as is currently done, we should change it to

``` javascript
  "license": "{{#projectLicenseName}}{{{projectLicenseName}}}{{/projectLicenseName}}{{^projectLicenseName}}Apache-2.0{{/projectLicenseName}}",
```

I will submit a PR to that effect.

**Comment by wing328** [comment]
@delenius please refer to https://github.com/swagger-api/swagger-codegen/issues/2963 for the latest discussion on the license of the auto-generated code.

**Comment by wing328** [comment]
@delenius closing this as we've removed license from the auto-generated code.

Please pull the latest master to give it a try.
