### ISSUE TITLE
[csharp] Missing tag in README.mustache

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#3748]
##### Description

Hello,
I need to push a branch with a minor correction that permits c-sharp documentation to correctly use relative anchor:

##### Swagger-codegen version
2.3.0

##### Suggest a Fix

In file swagger-api\swagger-codegen\modules\swagger-codegen\src\main\resources\csharp\README.mustache

I added at row 142 this line:
`<a name="{{name}}"></a>`

**Comment by lunat** [comment]
In order to clarify, hare are also  the lines before and after:

```
{{/authMethods}}
{{#authMethods}}
<a name="{{name}}"></a> 
### {{name}}
{{#isApiKey}}- **Type**: API key
```

**Comment by wing328** [comment]
@lunat would you please submit a PR so that we can review the change?

**Comment by jimschubert** [comment]
@wing328 @lunat I wonder if we should add anchor tags for all headings in the README?

Here are ones that are still missing anchors after @lunat's changes:

```
## Frameworks supported
## Dependencies
## Installation
## Getting Started
## Documentation for Authorization
```

There are a few others _with_ anchors, so I feel like it should be consistent? Thoughts?

**Comment by wing328** [comment]
@jimschubert sounds good to me.

**Comment by jimschubert** [comment]
@lunat @wing328 I added the extra tags I mentioned above.

**Comment by wing328** [comment]
PR merged.
