### ISSUE TITLE
Encode URLs

### ISSUE THREAD

**Issue by KevinColemanInc** [swagger-api/swagger-codegen#375]
My API documentation looks like this:
    
    "apis": [
    {
    "path": "/stores/{id}/tickets"
    }
    ],

I am having a problem where when I try to hit a url that looks like:

    /v1.0/api-docs/stores/{id}/tickets

the server returns a 500

But if I hit it in my browser, chrome url encodes it before hitting their server: 

    /v1.0/api-docs/stores/%7Bid%7D/tickets

the server returns a 200

I think the urls needs to be url encoded before they try to fetch the documentation from the server

**Comment by KevinColemanInc** [comment]
As a quick hack, I did this:

		if(auth.passAs == "header") {
			val connection = new URL(url.replace("{", "%7B").replace("}", "%7D")).openConnection()
			connection.setRequestProperty(auth.keyName, auth.value)
			connection
		}
		else if(auth.passAs == "query") {
			new URL(url.replace("{", "%7B").replace("}", "%7D") + "?%s=%s".format(URLEncoder.encode(auth.keyName, "UTF-8"), URLEncoder.encode(auth.value, "UTF-8"))).openConnection()
		}
		else {
			new URL(url.replace("{", "%7B").replace("}", "%7D")).openConnection()
		}

It no longer errors when fetching the urls, but it doesn't generate any code for those paths either (ruby)

**Comment by webron** [comment]
Based on the structure you shared, it looks like you're using Swagger 1.2.

As a general rule, we recommend *not* using templated URLs for the `path` values. Please note that the `path` there is not the URL of the API but rather the URL of the documentation as it is exposed by swagger.

It would be better if you just changed the path to `"/stores/id/tickets"`, how to do that depends on the framework that produces your documentation.

With the current structure, you may also encounter issues with swagger-ui.

**Comment by KevinColemanInc** [comment]
Unfortunately, I don't have control of the documentation.  So I am stuck with working with what is there.  They don't seem very pro-active about properly formed documentation, so I think I am going to be stuck rolling my own gem.

**Comment by KevinColemanInc** [comment]
so if I am reading this right, you recognize this is a bug in the generator and its in queue to get fixed?

**Comment by fehguy** [comment]
I'm investigating it and treating it as a bug, and expect the fix will be in M1.

**Comment by KevinColemanInc** [comment]
When is the expected release of M1?

**Comment by fehguy** [comment]
Probably first week of Feb.  We need to get M1 of swagger-core out the door first, which is slated for end of the month.

**Comment by fehguy** [comment]
This has been resolved, please reopen if you see issues.
