### ISSUE TITLE
Java: Latest JMustache breaks bigDecimalAsString

### ISSUE THREAD

**Issue by wienczny** [swagger-api/swagger-codegen#3754]
The commit samskivert/jmustache@9eda17f85bfd8849850bdafa92d2f6ffe12bb71f changes the default escape characters used by JMustache. This breaks the code-generation of bigDecimalAsString in the Java language because the annotation 
```@JsonSerialize(using = ToStringSerializer.class)``` 
is written as
```@JsonSerialize(using &#x3D; ToStringSerializer.class)```

You could avoid this by disabling the escaper in JMustache

**Comment by wing328** [comment]
What about using {{{ tag_name }}} (or {{& tag_name }}) for the unescape value instead ?

**Comment by wienczny** [comment]
I didn't know the triple mustache. This should work, too.
