### ISSUE TITLE
'pattern' field is removed from configuration when generating 'Python Flask' server

### ISSUE THREAD

**Issue by phoracek** [swagger-api/swagger-codegen#3765]
##### Description

`pattern` field is removed from `swagger.yaml` when generating 'Python Flask' server.
##### Swagger-codegen version

The one used by http://editor.swagger.io/
##### Swagger declaration file content or url

``` yaml

---
swagger: '2.0'
info:
  version: 1.0.0
  title: Test API
paths:
  /:
    post:
      parameters:
        - in: body
          name: data
          schema:
            $ref: '#/definitions/Test'
      responses:
        200:
          description: OK
definitions:
  Test:
    type: string
    pattern: '^[01]{1,9}$'
```
##### Command line used for generation

http://editor.swagger.io/ was used.
##### Steps to reproduce

Paste mention config to http://editor.swagger.io/ and let it generate 'Python Flask' server code. In the generated code, `pattern` field is missing in `swagger.yaml`.
##### Related issues

Maybe it is related to https://github.com/swagger-api/swagger-codegen/pull/2794. Anyways, I see no reason why to strip fields when generating.
##### Suggest a Fix

Keep `pattern` field.

**Comment by varunmittal91** [comment]
It is also ignoring validation parameters for integer
definition:
  somefield:
    type: integer
    minimum: 1
    maximum: 100

Produces:
  somefield:
    type: "integer"

**Comment by wing328** [comment]
v2.2.3 has been released. Please also try the current master (2.3.0)

If it's still an issue, I can show some good starting points to fix it (e.g. using the model templates from Python client)

**Comment by wing328** [comment]
v2.2.3 has been released. Please also try the current master (2.3.0)

If it's still an issue, I can show some good starting points to fix it (e.g. using the model templates from Python client)

**Comment by wing328** [comment]
Closing this as there's no update.
