### ISSUE TITLE
[Async-Scala] Could not get value of optional header parameters

### ISSUE THREAD

**Issue by geetikagupta16** [swagger-api/swagger-codegen#3774]
##### Description
Unable to fetch correct value from optional header parameters

Here is my swagger spec:
![image](https://cloud.githubusercontent.com/assets/17196397/18426469/769534b6-78df-11e6-8cab-8930b8ba088c.png)

When I generated the sdk it maps the optional header parameters to Option[String] and to get value from the parameters we should be using a map, but in the generated sdk we are directly using the option value.

Example: 
Suppose the method is :
def getInfoGet(param: Option[String] = None)(implicit reader: ClientResponseReader[Person]): Future[Person]

So to access the param value we should be using a map, but in the present scenario it is doing something like:

headerParams += "param" -> param.toString

**Comment by wing328** [comment]
@geetikagupta16 thanks for reporting the issue. Would you please also try the `scala` client? If it works, we can apply similar fix to the `async-scala` client.

**Comment by geetikagupta16** [comment]
scala client works fine. I have made changes for the async- scala client and will be sending a PR for the same.
But the test cases for the petstore example are showing compilation errors on the master branch. What should I do ?

**Comment by wing328** [comment]
If you've time, please help fix the test cases for `async-scala` Petstore client.

**Comment by wing328** [comment]
(if it's a runtime error, it may be due to invalid data in petstore.swagger.io. You can submit the PR so that the CI can test the change using a local version of the Petstore server)

**Comment by geetikagupta16** [comment]
Its showing compilation errors.
I'll try to fix the test cases.
