### ISSUE TITLE
[PHP] Bug in setter validation of non-required properties with null value

### ISSUE THREAD

**Issue by xaviapa** [swagger-api/swagger-codegen#3783]
##### Description

When generating an SDK in PHP, there is a problem in the Model generation of an entity/api resource. If a property is **not required** and has the value **null** you get the exception of the minlength condition. In my opinion the null value should be valid for a non-required property.

##### Swagger-codegen version

master

##### Swagger declaration file content or url

```
"Program": {
   "required": [
      "id_program",
      "id_origin",
      "id_platform",
      "id_category"
   ],
   "properties": {
      "id_program": {
          "type": "string",
          "description": "Program UUID or numeric ID",
          "minLength": 1,
          "maxLength": 36
      },
      "id_developer": {
          "type": "string",
          "description": "Developers identifier",
          "minLength": 1,
          "maxLength": 100
      },
      "id_origin": {
          "type": "string",
          "description": "Origins identifier",
          "minLength": 1,
          "maxLength": 40
      },
      "id_platform": {
          "type": "string",
          "description": "Platforms identifier",
          "minLength": 1,
          "maxLength": 20
      },
      "id_category": {
          "type": "string",
          "description": "Categories identifier",
          "minLength": 1,
          "maxLength": 40
      }
   }
},
```

##### Steps to reproduce

Check the SDK https://github.com/softonic/sdk_catalog-api, file https://github.com/softonic/sdk_catalog-api/blob/master/src/Model/Program.php, method setIdDeveloper()
```
public function setIdDeveloper($id_developer)
    {
        if (strlen($id_developer) > 100) {
            throw new \InvalidArgumentException('invalid length for $id_developer when calling Program., must be smaller than or equal to 100.');
        }
        if (strlen($id_developer) < 1) {
            throw new \InvalidArgumentException('invalid length for $id_developer when calling Program., must be bigger than or equal to 1.');
        }
        $this->container['id_developer'] = $id_developer;
        return $this;
    }
```
This is throwing the exception _'invalid length for $id_developer when calling Program., must be bigger than or equal to 1.'_ because _strlen(null) = 0_.

As $id_developer is a non-required property (see swagger content pasted above), the function should be:
```
public function setIdDeveloper($id_developer)
    {
        if (is_null($id_developer)) {
            $this->container['id_developer'] = $id_developer;
            return $this;
        }
        if (strlen($id_developer) > 100) {
            throw new \InvalidArgumentException('invalid length for $id_developer when calling Program., must be smaller than or equal to 100.');
        }
        if (strlen($id_developer) < 1) {
            throw new \InvalidArgumentException('invalid length for $id_developer when calling Program., must be bigger than or equal to 1.');
        }
        $this->container['id_developer'] = $id_developer;
        return $this;
    }
```

##### Suggest a Fix

https://github.com/swagger-api/swagger-codegen/pull/3785 (declined after finding a better solution) -> https://github.com/swagger-api/swagger-codegen/pull/3797

**Comment by ePaul** [comment]
Not sure this is related, but how is this property then sent over the wire? In OpenAPI 2.0 `null` values are not possible (you would omit the property instead).

**Comment by xaviapa** [comment]
@ePaul our API returns the properties with null values. This satisfy the response definition.
Here you have an example of a response from our API:
```
[
  {
    "id_program": "36507ab6-79c8-11e6-b32b-552b1a9ff074",
    "id_version": "0.9.8",
    "name": "0.9.8",
    "id_minimum_requirements_group": null,
    "id_recommended_requirements_group": null,
    "preversion": null,
    "postversion": null,
    "supported_formats": null,
    "id_license": "Fw",
    "age": null
  }
]
```

**Comment by xaviapa** [comment]
I close it because the changes from https://github.com/swagger-api/swagger-codegen/pull/3797 were merged to master.

**Comment by ePaul** [comment]
@xaviapa I think this is simply wrong according to the OpenAPI 2.0 spec. It should instead be this:

```json
[
  {
    "id_program": "36507ab6-79c8-11e6-b32b-552b1a9ff074",
    "id_version": "0.9.8",
    "name": "0.9.8",
    "id_license": "Fw"
  }
]
```

Of course, the problem here is that the server doesn't conform to the spec (and actually what your server returns can't be described in OpenAPI 2.0 – 3.0 will allow it, using the `nullable` property).
