### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by mn288** [swagger-api/swagger-codegen#3788]
Is swift 3.0 Supported yet? if not when is the release date?

**Comment by jaz-ah** [comment]
not yet - although now that Alamofire + Promisekit have released official Swift3.0 versions, I can imagine we'll be able to get to this in the next month.

**Comment by wing328** [comment]
WIP: https://github.com/swagger-api/swagger-codegen/pull/3823

**Comment by wing328** [comment]
#4002 has been merged into master.

Please pull the latest master to give it a try.

**Comment by SyedTayyab99** [comment]
I have pulled the latest master but when I try to generate Swift3 SDK it gives me the error: "Can't load config class with name Swift3" The list of available configs still only show "swift" and there is no entry for swift3.
