### ISSUE TITLE
[typescript-angular2] npm publish missing files

### ISSUE THREAD

**Issue by savcha** [swagger-api/swagger-codegen#3789]
##### Description
When attempting to publish to npm the generated files are not uploaded.
The generated package.json contains the following:
"files": [
    "lib"
  ],
There is no lib folder so only the default files(package.json, README, etc) get packaged when running "npm publish". 

##### Swagger-codegen version

2.2.1

https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/samples/client/petstore/typescript-angular2/npm/package.json

##### Suggest a Fix
Removing the files property from package.json includes all the generated files.

**Comment by wing328** [comment]
@savcha thanks for reporting the issue. May I know if you've time to file a fix?

**Comment by savcha** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3791

**Comment by wing328** [comment]
PR merged
