### ISSUE TITLE
specifying the response format in URLS

### ISSUE THREAD

**Issue by KevinColemanInc** [swagger-api/swagger-codegen#379]
the swagger-codegen seems to be having trouble with urls that end in .{format}.   So a path that looks like

    {
    "path": "/swagger_doc/authorize.{format}"
    },

the codegen is trying to 

    GET /swagger_doc/authorize.{format}

when it should be trying to get

    /swagger_doc/authorize.json

or 

    /swagger_doc/authorize.xml

I think my client is using the grape swagger gem to create his documentation.

https://github.com/tim-vandecasteele/grape-swagger/blob/e977feac26d2ba125d92067e3f6a433738415131/spec/simple_mounted_api_spec.rb#L77

**Comment by webron** [comment]
Is this in the api-docs level?

**Comment by KevinColemanInc** [comment]
Not super familiar with swagger, so I am not completely sure what you mean.  but is in the root level

**Comment by webron** [comment]
Fair enough, let me explain.

Normally, the root of the swagger documentation (1.2 and prior) is hosted under /api-docs - this is referred to the resource listing. It's basically a list of the available resources exposed by the documentation.

While some libraries may produce it wrong, the idea is that each path under the api-docs (or whichever root is used to host the swagger spec) is the path of the *documentation* of that resource (which does not have to be the same path as the resource itself).

This means that if the path is written as `/swagger_doc/authorize.{format}`, it will be exposed as `/api-docs/swagger_doc/authorize.{format}`. The replacement of {format} with either xml or json is irrelevant for the hosting of the *documentation*.

Does this make sense?

**Comment by KevinColemanInc** [comment]
I think so. So you're saying their documentation generator is wrong to create the path that way?

**Comment by webron** [comment]
Most likely, yes. Theoretically it could be fine, but using curly braces in actual URLs is... not recommended. I'd suggest opening an issue there, and pointing them to this issue. I'd be more than happy to provide more information if they need.

**Comment by fehguy** [comment]
this is supported as of https://github.com/swagger-api/swagger-parser/commit/1995bc4131074cafc49a7a3edfa0632ee1420981.  Please run `mvn clean install` and you should pick up the fix.
