### ISSUE TITLE
[Spring] compilation issue - query params enumerations

### ISSUE THREAD

**Issue by rajeshkamal** [swagger-api/swagger-codegen#3792]
When you an enumeration of supported/valid strings specified for the query parameter in the spec 
```
"parameters":[
   {
      "name":"acmeStatus",
      "in":"query",
      "description":"Status of Acme's you want to retrieve.",
      "required":true,
      "type":"string",
      "enum":[
         "SUCCESS",
         "FAILED",
         "INPROGRESS"
      ]
   }
]
```

The generated spring code - Controller Interface code does not compile. The @ApiParam's allowableValues(String) property gets generated and it has some issues

```
allowableValues = "{values=[SUCCESS, FAILED, INPROGRESS], enumVars=[{name=SUCCESS, value="SUCCESS"}, {name=FAILED, value="FAILED"}, {name=INPROGRESS, value="INPROGRESS"}]}"
```
Complete Controller Method
```
    @ApiOperation(value = "Query Acme's by status", notes = "Get the list of Acme's for the provided Acme status", response = Acme.class, responseContainer = "List", tags={ "AcmeService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Acme.class) })
    @RequestMapping(value = "/acmes",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Acme>> getAcmesByStatus(@ApiParam(value = "Status of Acme's you want to retrieve.", required = true, allowableValues = "{values=[SUCCESS, FAILED, INPROGRESS], enumVars=[{name=SUCCESS, value="SUCCESS"}, {name=FAILED, value="FAILED"}, {name=INPROGRESS, value="INPROGRESS"}]}") @RequestParam(value = "acmeStatus", required = true) String acmeStatus



);
```

**Comment by stevecookform3** [comment]
For the example enum:

```
        type: string
        enum:
         - CSV
         - XML
         - TXT
```


In jaxrs you get

`allowableValues="CSV, XML, TXT"`

in spring you get

`allowableValues = "{values=[CSV, XML, TXT], enumVars=[{name=CSV, value=\"CSV\"}, {name=XML, value=\"XML\"}, {name=TXT, value=\"TXT\"}]}") `

My assumption is that the jaxrs version is the correct one.

**Comment by wing328** [comment]
@stevecookform3 thanks for the additional info. I'll take a look later today or tomorrow.

**Comment by wing328** [comment]
@rajeshkamal @stevecookform3 It seems to me the issue should have been fixed in the latest master and we've a test case to cover it. Here is the auto-generated code for the test case:
https://github.com/swagger-api/swagger-codegen/blob/4e20bd9bab43ce21f21954a45402ca49df5a2a64/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/FakeApiController.java#L120

Have you pull the latest master to generate spring boot/mvc server stub?

**Comment by stevecookform3** [comment]
Yes - looks good in latest master. thanks.

**Comment by wing328** [comment]
@stevecookform3 thanks for the confirmation. Issue closed.
