### ISSUE TITLE
Fix docs around Windows use

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-codegen#380]
Comments such as https://github.com/swagger-api/swagger-codegen/issues/195#issuecomment-68026117 seem to indicate that the `README.md` is broken as regards Windows use. Can you add a pointer around [this point](https://github.com/swagger-api/swagger-codegen/#to-generate-a-sample-client-library) to the right path to take? Otherwise Windows use isn't mentioned after that point. But "Easy" is mentioned a couple of times! Perhaps something like:
     - *Note: this won't work on Windows, see [here](https://github.com/swagger-api/swagger-codegen/issues/195#issuecomment-68026117)*
Also if the commands/docs are broken, shouldn't the issue stay open?

**Comment by fehguy** [comment]
With the move from scala in codegen, this issue is now resolved.  You can run with maven or with the executable jar under swagger-codegen-distribution.

**Comment by srl295** [comment]
@fehguy thanks!
