### ISSUE TITLE
JMeter Bug Template testCases and Params not generated properly

### ISSUE THREAD

**Issue by richardfriedman** [swagger-api/swagger-codegen#3800]
* The testCases input variable is mis configured to 'host' but should be 'testCases'
* The Parameters for a Request is defaulting to 0 instead of using ${paramName}

##### Swagger-codegen version

Master

##### Swagger declaration file content or url

    ```yaml
    ---
    swagger: '2.0'
    info:
      version: 1.0.0
      title: Echo
      description: |
        #### Echos back every URL, method, parameter and header
        Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
        render back everything.
    schemes:
      - http
    host: mazimi-prod.apigee.net
    basePath: /echo
    paths:
      /{id}:
        get:
          parameters:
            - name: id
              in: path
              description: ID
              type: string
              required: true
            - name: user
              in: query
              description: name
              type: string
              required: true
            - name: location
              in: query
              description: location
              type: string
              required: true
          responses:
            200:
              description: Echo GET
    ```

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l jmeter -i echo.yaml -o ~/Downloads/JMETER

##### Steps to reproduce

Just create the generated file and open in JMeter to see the outputs.

##### Suggest a Fix

I am fixing this bug by updating the template for JMeter.

**Comment by wing328** [comment]
Fixed via https://github.com/swagger-api/swagger-codegen/pull/3801
