### ISSUE TITLE
[JAVA] Bug - Avoid adding the Content-Type header when it is null

### ISSUE THREAD

**Issue by alrocar** [swagger-api/swagger-codegen#3804]
When generating a Java Client with the okhttp-gson generator. It includes the Content-Type header even when the variable is null. This makes some clients to not understand the request.

I have already fixed this in my fork.

alrocar/swagger-codegen@2c154c0d1ba62814cd35dc43c7ac19468fb0b7b2

Should I do a PR?

**Comment by wing328** [comment]
@alrocar yes, please submit a PR so that we can review the fix.

**Comment by alrocar** [comment]
Hi,

finally found out a workaround in the API I was consuming.

Not a bug in the swagger-codegen. I close the issue :)
