### ISSUE TITLE
Swagger Swift codegen generates an empty implementation for a map

### ISSUE THREAD

**Issue by tharpa** [swagger-api/swagger-codegen#3805]
##### Description

The [Swagger specification](http://swagger.io/specification/) specifies a way to define a string to string
map, e.g. in JSON:

```
{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
```

or in YAML:

```
type: object
additionalProperties:
  type: string
```

Unfortunately, the [Swagger Swift code generator](https://github.com/swagger-api/swagger-codegen) seems to have a
problem with it, generating only an _empty_ class implementation,
e.g. `Payload.swift` below:

```
//
// Payload.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Payload: JSONEncodable {

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
```

Is there an easy way to fix it without having to maintain our own entity
class, e.g. `Payload.swift`?
##### Swagger declaration

in YAML

``````
```yaml
type: object
additionalProperties:
  type: string
```
``````

   or in JSON

``````
```json
  {
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
```
``````
##### Command line used for generation

`swagger-codegen generate -l swift -i ../core-api/src/main/resources/core-api.yaml`
##### Related issues

http://stackoverflow.com/questions/39506665/swagger-swift-code-generated-for-a-map-is-not-correct

http://stackoverflow.com/questions/28644595/how-to-define-a-map-in-swagger

**Comment by omerjanjua** [comment]
I've got a similar issue. 

I have a String `userId`. An extension on the `String` `encodeToJSON` which returns `AnyObject`. And then tries to cast it into a dictionary. 

It always returns nil. 

`let parameters = userId.encodeToJSON() as? [String:AnyObject]`

**Comment by wing328** [comment]
@tharpa @omerjanjua please give an example of what the actual JSON payload looks like. 

The following definition does not look correct as it's missing the `properties` attribute:
```
{
  "type": "object",
  "additionalProperties": {
    "type": "string"
  }
}
```
For example https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L926

**Comment by omerjanjua** [comment]
@wing328 the back end developer made this change and now the auto generated Swift code returns a value instead of nil 

This has fixed my issue 

Before: 
```
        "parameters" : [ {
          "in" : "body",
          "name" : "user-id",
          "description" : "unique identifier for user from identity provider",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }

```

After: 
```
        "parameters" : [ {
          "in" : "body",
          "name" : "user-id",
          "description" : "unique identifier for user from identity provider",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/UserIdDTO"
          }
        }
```

Defenition: 
```
        "UserIdDTO": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
```

**Comment by wing328** [comment]
If this is still an issue, please reply to let us know and we'll reopen this issue.

**Comment by tharpa** [comment]
Well, for me this is still an open issue because I don't know how to successfully define in Swagger a parameter of type object with keys and values being strings and get a Swift 3 generated code which successfully encodes it to JSON.

**Comment by wing328** [comment]
>  I don't know how to successfully define in Swagger a parameter of type object with keys and values being strings

Can you share an example of the object (JSON)? Are you using body parameters for JSON objects in requests?

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by wenjdu** [comment]
Can we re-open it, I have this.
my yaml.
   ```
properties:
        type: object
        additionalProperties:
          type: string
        description: 'The dictionary of key, value pairs.'
```

Then I generate code in swift 3. 
```
/** The dictionary of key, value pairs. */
    public var properties: [String:String]?
```
This is exactly what I want but here is the tricky part.
When I call the class.encodeToJSON(), I get this : 
`["range": 100.0, "deviceId": "1234567890", "topic": "alps-test", "duration": 0.0, "properties": [AnyHashable("role"): "developer"]]`

Is there anyway to get rid of this AnyHashable??
