### ISSUE TITLE
NullPointerException when using "allOf" without any additional properties

### ISSUE THREAD

**Issue by j4velin** [swagger-api/swagger-codegen#3808]
##### Description

java.lang.NullPointerException
	at io.swagger.codegen.InlineModelResolver.flatten(InlineModelResolver.java:245)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:215)
	at io.swagger.codegen.Codegen.main(Codegen.java:117)

##### Swagger-codegen version

latest from master

##### Swagger declaration file content or url

https://gist.github.com/j4velin/8e3081ff84f1a4871318014c695f1894

##### Command line used for generation

java -cp modules/swagger-codegen-cli/target/swagger-codegen-cli.jar:modules/swagger-codegen/target/swagger-codegen-2.2.2-SNAPSHOT.jar io.swagger.codegen.Codegen -l java -o ./minimal -i ../minimal.json 

##### Steps to reproduce

use the "causing_npe.json" in the linked gist

##### Suggest a Fix

Check for m.getChild() != null in io.swagger.codegen.InlineModelResolver

**Comment by wing328** [comment]
PR merged. Issue closed.
