### ISSUE TITLE
Let's encrypt certificate error

### ISSUE THREAD

**Issue by jmls** [swagger-api/swagger-codegen#3810]
I am trying to get a swagger spec from a https url that is secured with a let's encrypt certificate

I get this error

`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

(I haven't included the stack trace because it is rather large)

I'm using the command  

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://mysite/api/swagger -l typescript-node`

What do I need to do in order to get round this problem?

**Comment by wing328** [comment]
One workaround is to download the spec to a local drive and use something like `-i /var/tmp/swagger.yaml' instead when generating the typescript-node client.

(or you can use https://editor.swagger.io)

**Comment by jmls** [comment]
ah! good thinking. I will give that a try - thanks!

**Comment by wing328** [comment]
No problem
