### ISSUE TITLE
[Spring] No swagger ui when starting a project from scratch

### ISSUE THREAD

**Issue by pbashyal-nmdp** [swagger-api/swagger-codegen#3811]
##### Description
The sample Pet Application genereted for Spring Boot application doesn't show the Swagger UI nor the API calls work.

##### Swagger-codegen version

2.2.1 installed with home-brew

##### Swagger declaration file content or url

http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

```swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l spring -o /tmp/spring```

##### Steps to reproduce

1:  Use the pet store example to generate the spring application into /tmp/spring
```
swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l spring -o /tmp/spring
```
2:  Build the application
```
cd /tmp/spring
mvn clean package
```
3: Run the application
```
java -jar target/swagger-spring-1.0.0.jar
```

4: Browse to http://localhost:8080/ . 
   - You should have been redirected to swagger-ui.html. This doesn't happen.
   - Curl commands return 404 
```
curl -v http://localhost:8080/
curl -v http://localhost:8080/user/login
curl -v http://localhost:8080/swagger-resources/configuration/ui
```
##### Related issues

I didn't find anything related.

**Comment by cbornet** [comment]
Some information is missing

**Comment by pbashyal-nmdp** [comment]
Sorry, hit enter in the wrong textbox.

**Comment by cbornet** [comment]
I think the app contextPath has been set to /v2 in application.properties.
Can you try reaching http://localhost:8080/v2 ?

**Comment by pbashyal-nmdp** [comment]
Ok, that was it. Sorry I didn't go digging in and was trying to get  a sample working first.

Can I suggest that you comment the `server.contextPath=/v2` for the default case? 

Thanks Christophe for your prompt help.

**Comment by pbashyal-nmdp** [comment]
Nevermind. The reason it was set to /v2 was because the swagger.json specifies 
`basePath` as v2.
Thanks for your help.
