### ISSUE TITLE
Java: Missing "extends BaseClass" in generated model

### ISSUE THREAD

**Issue by wienczny** [swagger-api/swagger-codegen#3821]
##### Description

Generated code is missing a base class declaration. 
##### Swagger-codegen version

2.2.2
master
##### Swagger declaration file content or url

```

---
swagger: '2.0'
info:
  title: Test
  description: Client
  version: "1.0.0"
# the domain of the service
host: 127.0.0.1
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: access_token
security:
  - UserSecurity: []
paths:
  /child/{child_id}:
    get:
      summary: Load child
      description: |
        Load order
      parameters:
        - name: child_id
          in: path
          description: Child Id.
          required: true
          type: string
      tags:
        - Childs
      responses:
        200:
          description: Order
          schema:
            $ref: '#/definitions/Child'
definitions:
  Parent:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: name
  Child:
    allOf:
    - $ref: '#/definitions/Parent'
    - type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/definitions/Child'
```
##### Command line used for generation

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -o /tmp/test -l java -i test.yml
```
##### Steps to reproduce

Run the command  and check Child.java the base class. See that "extends Parent" is missing.

The code reads:

```
public class Child   {
```

instead of:

```
public class Child extends Parent {
```

**Comment by brentryan** [comment]
You're missing a field called "discriminator" in your swagger spec.  I believe this is required.

**Comment by wienczny** [comment]
This definition works when beeing generated using the current editor.swagger.io. Which swagger Version is used there?
If there is no descriminator field should'nt this be an error during generation? Currently neither are the base class declared nor the properties copied to the child.
I thought the descriminator was used to decide which class to used during parsing of message when the base class is used as parameter. My base class is used to share common properties for two or more sub classes which are referenced as result types. In that case you should not neead descriminator.

**Comment by damnhandy** [comment]
@wienczny same here! I'm seeing the same differences between the CLI and generator.swagger.io. Not sure what is actually different.

**Comment by damnhandy** [comment]
Adding discriminator works with the CLI. Thanks for the tip @brentryan !

**Comment by wing328** [comment]
generator.swagger.io is using the latest stable verison (2.2.1) and for CLI, I'm assuming you're building the local JAR on the latest master.

**Comment by baynezy** [comment]
@damnhandy - can you post an example because I am struggling to make `discriminator` do anything.

**Comment by wing328** [comment]
@baynezy would the following help?

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#models-with-polymorphism-support
