### ISSUE TITLE
discriminator generated in both base and child

### ISSUE THREAD

**Issue by AlexNolasco** [swagger-api/swagger-codegen#3829]
##### Description

Should the discriminator property be also a property of the child class even if it is already in the base class?
##### Swagger-codegen version

2.2
##### Swagger declaration file content or url

[ticket.yaml.txt](https://github.com/swagger-api/swagger-codegen/files/481027/ticket.yaml.txt)

##### Command line used for generation

Objective-C   and C# client generators generate the petType in the base and child class. Thus generating compilation warnings. OTOH, the Java generator does not duplicate the property.
##### Steps to reproduce

Simply generate C# or Objective-C client code for the YAML aforementioned
##### Suggest a Fix

Child classes should not duplicate properties found in the base class. The work around is to only define the discriminator in the base class and then copy/paste the property on each child class.

**Comment by wing328** [comment]
@alexandern am I understanding correctly that that the Java client does not have the issue and only ObjC, Swift and C# client has the issue?

**Comment by alexandern** [comment]
@wing328 

> am I understanding correctly that that the Java client does not have the issue and only ObjC, Swift and C# client has the issue?

Correct,

I've attached the Java client generated code for the yaml in question which does what you will expect. Base properties are _not_ copied to the child class.
 
[Dog.java.txt](https://github.com/swagger-api/swagger-codegen/files/485164/Dog.java.txt)
[Pet.java.txt](https://github.com/swagger-api/swagger-codegen/files/485165/Pet.java.txt)

On the other hand, the Objective-C does duplicate the properties
[SWGPet.h.txt](https://github.com/swagger-api/swagger-codegen/files/485182/SWGPet.h.txt)
[SWGCat.h.txt](https://github.com/swagger-api/swagger-codegen/files/485183/SWGCat.h.txt)

Possible workaround would be to mark the child properties as dynamic to avoid the compilation warnings produced by the current output. Not having the parent properties would probably be best.

The C# client generation also copies the properties found in the parent class
[Pet.cs.txt](https://github.com/swagger-api/swagger-codegen/files/485200/Pet.cs.txt)
[Dog.cs.txt](https://github.com/swagger-api/swagger-codegen/files/485201/Dog.cs.txt)

**Comment by alexandern** [comment]
@wing328 

I've tested Swift Client and it does not use inherit the Pet class,  it  uses composition instead. So, it should not be part of this issue.

**Comment by cbornet** [comment]
languages that support inheritance should have useInheritance=true. I guess it should be set for Obj-C and C# codegens.

**Comment by alexandern** [comment]
@cbornet 

I see some references to useInheritance 
https://github.com/swagger-api/swagger-codegen/search?utf8=%E2%9C%93&q=useInheritance

I'll try to figure out where to insert this code.

**Comment by cbornet** [comment]
Oh, my mistake ! It's **supportsInheritance** I was talking about !

**Comment by alexandern** [comment]
@cbornet 

In that case, I wonder if the fix is as simple to add the code below to the clients in question.

```
 if (additionalProperties.containsKey(USE_INHERITANCE)) {
              setUseInheritance(Boolean.parseBoolean((String)additionalProperties.get(USE_INHERITANCE)));
        } else {
            supportsInheritance = true;
}
```

**Comment by cbornet** [comment]
I would say just ```supportsInheritance = true;```.  The useInheritance property is only in javascript to have the choice between inheritance and composition.

**Comment by alexandern** [comment]
@cbornet 
Makes perfect sense, I've submitted a commit to my fork.  I still need to figure out if it may break any unit tests.

https://github.com/alexandern/swagger-codegen/commit/585f23185688aad7d46a6faa402abc0cbbddc20a

**Comment by cbornet** [comment]
You should regenerate the samples. There are scripts for this in the ./bin directory.

**Comment by alexandern** [comment]
Ok, I ran the ./bin/objc-petstore.sh against **petstore-with-fake-endpoints-models-for-testing.yaml** instead of **petstore.json** and I seem to generate what one would expect.

```
@interface SWGAnimal : SWGObject
@property(nonatomic) NSString* className;
@property(nonatomic) NSString* color;
@end

```
Child class no longer copies the className property
```

#import "SWGAnimal.h"
@protocol SWGCat
@end
@interface SWGCat : SWGAnimal
@property(nonatomic) NSNumber* declawed;
@end
```

All in all, changing ObjcClientCodegen.java appears to do the work which makes me wonder why it it was false.  It's my understanding that using allOf along with a discriminator is an indication of inheritance for code-gen.

```
    public ObjcClientCodegen() {
        super();
        supportsInheritance = true;
        ... 
    }
```

**Comment by alexandern** [comment]
@cbornet 
Submitted a pull request
https://github.com/swagger-api/swagger-codegen/pull/3903
