### ISSUE TITLE
JSON content type always chosen if declared in "consumes" (Java)

### ISSUE THREAD

**Issue by sstreety** [swagger-api/swagger-codegen#3830]
##### Description

I'm not sure if this should be an issue or a question.    I've declared 2 consumes entries in one endpoint (a POST):
~~~~
consumes:
        - application/json
        - application/yaml
~~~~

So, the above 2 entries end up in the following array:

~~~~
String[] contentTypes
~~~~

The generated code that chooses the contentType looks like this:

~~~~
public String selectHeaderContentType(String[] contentTypes) {
            if (contentTypes.length == 0) {
                return "application/json";
            }
     for (String contentType : contentTypes) {
            if (isJsonMime(contentType)) {
            return contentType;
            }
        }
            return contentTypes[0];
        }

~~~~

So, in my particular case, the JSON contentType will always be chosen and a yaml contentType will never be chosen. 
What was the intention of allowing multiple "consumes" entries, but always defaulting to JSON if it is one of the entries? Is it preferred to have 2 separate endpoints, one for json and one for yaml?

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

See above

##### Command line used for generation

mvn clean install

**Comment by wing328** [comment]
@sstreety very good question. The spec allows users to specify multiple `consumes` in case the endpoint supports so. However the API client generated by Swagger Codegen only supports JSON payload (HTTP body) at the moment and that's why we always to default it to `application/json` if it's defined in `consumes`.
