### ISSUE TITLE
Codegen for typescript-angular2 - all properties are optional

### ISSUE THREAD

**Issue by MaciejGit** [swagger-api/swagger-codegen#3831]
##### Description
Hi,

while generating typescript-angular2 models, all properties are marked as optional, even when they are properly attributed by "required" parameter.

This is even visible in the Petstore sample clients provided in this repo: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-angular2/default/model - see Pet object for example and compare with http://petstore.swagger.io/v2/swagger.json

Note that everything works fine for typescript-angular.

To generate my model, I use: java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l typescript-angular2 -o c:\temp\ng2_api_client

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url
http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation
java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l typescript-angular2 -o c:\temp\ng2_api_client

##### Steps to reproduce
Run model generation on Petstore swagger.json
Or use your own schema with required parameters

**Comment by wing328** [comment]
@MaciejGit thanks for reporting the issue. I've file #3843 to address it.

**Comment by wing328** [comment]
PR merged. Please pull the latest master to give it a try.
