### ISSUE TITLE
[typescript-fetch] basePath + subPath = "a invalid path", it lead to a "fetch api can not load" issue

### ISSUE THREAD

**Issue by fish2016** [swagger-api/swagger-codegen#3832]
##### Description

basePath(https://api.weixin.qq.com/) + subPath(/card/code/checkcode) 
= a invalid path(**https://api.weixin.qq.com//card/code/checkcode**)

**this invalid path can lead to a "fetch api can not load" issue.**

you can see that there are two slashes before "card" in the result path. one slash is correct, and two slashes are wrong.

the javascript-generated code is ok, but the typescript-fetch generated code is not ok.

*********************
I compared javascript code with typescript-fetch code,

javascript-generated code is:
this.basePath = 'https://api.weixin.qq.com/'.replace(/\/+$/, '');

typescript code is:
const BASE_PATH = "https://api.weixin.qq.com/";

**There is a redundant slash in the end of BASE_PATH**, I think this is root cause, please check it.

##### Swagger-codegen version

I don't konw which version am I using, 
I use "http://editor.swagger.io/#/" to generate code, I know that Swagger Editor version is 2.10.3

**Comment by wing328** [comment]
@fish2016 what about applying the same `.replace(/\/+$/, '');` for typescript code?

**Comment by fish2016** [comment]
After adding .replace(/\/+$/, '') for typescript code, this issue disappear.

just like the following code:
`const BASE_PATH = "https://api.weixin.qq.com/".replace(/\/+$/, '');` ,

**Comment by wing328** [comment]
@fish2016 thanks for the confirmation. May I know if you've time to submit a fix?

**Comment by fish2016** [comment]
but I don't know how to modify swagger-codegen code

**Comment by wing328** [comment]
No worry. I've filed https://github.com/swagger-api/swagger-codegen/pull/3855 to fix the issue. Will merge it into master once all the test cases pass

**Comment by wing328** [comment]
@fish2016 PR merged. Please pull the latest and give it a try.
