### ISSUE TITLE
Building docker image of swagger-generator

### ISSUE THREAD

**Issue by jmls** [swagger-api/swagger-codegen#3833]
##### Description

I need to be able to add the *let's encrypt* certificate to the swagger-generator docker image (https://hub.docker.com/r/swaggerapi/swagger-generator)

I am not a java guy at all, so all the java / maven tools are new and unfamiliar to me.

However - 
- I checked out swagger-codegen, and did a *maven package* in the root folder. 
- I made my changes to the Dockerfile in *modules/swagger-generator* 
```
RUN wget https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.der
RUN keytool -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt -importcert -alias lets-encrypt-x3-cross-signed -file lets-encrypt-x3-cross-signed.der
```
 - I then did a docker build from within the  *modules/swagger-generator* folder

All this happens without errors. I can then start the new swagger-generator docker image, and access the UI from the browser.

This is where it all goes wrong ;)

All I get is a blank screen, with console errors about missing js libraries

![image](https://cloud.githubusercontent.com/assets/929523/18665289/69e13f90-7f1e-11e6-8919-017f13b13aa6.png)

So the guestion is : what did I do wrong / what did I miss ?

thanks

**Comment by jimschubert** [comment]
I don't think using the generator docker image with HTTPS is going to be as easy as this.

swagger-generator is a Scalatra application which is started via Jetty over port 8080 [see Dockerfile](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-generator/Dockerfile#L10). The Scalatra [docs](http://www.scalatra.org/2.3/guides/deployment/configuration.html) say you can publish on 443 with an entry in `/etc/hosts`, but I don't know how you'd go about doing that without modifying code.

Probably the easiest way to do what you're trying to accomplish is to proxy the application with nginx. [Certbot](https://certbot.eff.org/docs/using.html#nginx) and [DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04) have great docs on the subject. I've recently used those documents personally to run a site using Let's Encrypt certs. [Here's another post](http://www.automationlogic.com/using-lets-encrypt-and-docker-for-automatic-ssl/) which seems to combine the two. As a result, you would run nginx on a server and startup the swagger-generator container (running at localhost:8080), and nginx would proxy localhost:8080 to your configured domain:443.

I've had Scalatra apps running in production with an nginx proxy for SSL termination, and it works great. The apps weren't running in docker, but I don't think that would be an issue-- it'll just add additional memory/CPU overhead.

**Comment by fehguy** [comment]
@jimschubert it's actually a [java app](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-generator), not scalatra

But regardless I don't have a suggestion how to do this.  @jmls it is simply exposing a port, so you should be able to install a SSL termination proxy (as Jim mentioned) and forward the requests to the generator.  Be sure to set the environment variable with `-e` to the _https_ endpoint though.
