### ISSUE TITLE
Generate bean validation regex pattern 

### ISSUE THREAD

**Issue by shailendrajain24** [swagger-api/swagger-codegen#3839]
Below method create a problem when we generate pattern regex in our code.
Problem is generate contain extra '\' when we apply bean validation @pattern like that  :-   /[a-zA-Z]/

public String addRegularExpressionDelimiter(String pattern) {
        if (pattern != null && !pattern.matches("^/.*")) {
            return "/" + pattern + "/";
        }

```
    return pattern;
}
```

Location of source file line number 3285 : https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L3285

My question is that any specific reason to add this method because this method is newly introduce.

**Comment by wing328** [comment]
@shailendrajain24 it's based on the discussion here: https://github.com/swagger-api/swagger-codegen/pull/2794

Is it causing any issue to your use case?

**Comment by shailendrajain24** [comment]
Jersey bean validation does not work with  this **/[a-zA-Z]/** pattern.

**Comment by mgriego** [comment]
We've run into a similar issue.  We're validating a path string on a model, so the regular expression is `[/a-zA-Z0-9_-]+`.  Since the code above doesn't do `Pattern.quote()` on the provided pattern, the `/` in the pattern ends up with an invalid regex: `/[/a-zA-Z0-9_-]+/`.

**Comment by wing328** [comment]
@mgriego @shailendrajain24 What about overriding `addRegularExpressionDelimiter` to not add any "/" in [AbstractJavaCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java) ? Would that resolve the issue for you guys?

cc @jfiala @cbornet

**Comment by wing328** [comment]
Closing this as there's no update.

Please pull the latest to give it another try as I've add some additional logic to better handle pattern.
