### ISSUE TITLE
[Java] dateLibrary=legacy doesn't work against JSON class

### ISSUE THREAD

**Issue by mt-snakamura** [swagger-api/swagger-codegen#3842]
##### Description

`dateLibrary=legacy` doesn't work against `JSON` class.
##### Swagger-codegen version

`2.2.1`; I installed via `brew` on Mac OS X.
##### Swagger declaration file content or url

Configuration:

``` json
{
  "library":"okhttp-gson",
  "dateLibrary":"legacy"
}
```
##### Suggest a Fix

Generated model classes are as expected. It has `java.util.Date` as Date. 
However `JSON` class has both `java.util.Date` and `org.joda.time`. I believe it's a bug. Thanks.

![2016-09-21 19 56 03](https://cloud.githubusercontent.com/assets/18651017/18708381/7de22a14-8035-11e6-8a5e-541ef529d299.png)

**Comment by wing328** [comment]
@mt-snakamura thanks for reporting the issue. Please kindly pull the latest master to give it a try.

**Comment by cbornet** [comment]
Same as #3413

**Comment by wing328** [comment]
I believe this issue can be closed.
