### ISSUE TITLE
go-server code gen has no means to set model templates

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [swagger-api/swagger-codegen#3851]
##### Description

When trying to use the go-server generator, the default behavior is that there are no model templates defined, so none are generated. There does not appear to be a means to get any defined such that they would be generated and there does not appear to be a default model.mustache in the source resources.
##### Swagger-codegen version

2.2.2-SNAPSHOT
##### Swagger declaration file content or url

Happens for any Swagger YAML
##### Command line used for generation

Using the maven plugin to wrap the command line:

> ```
>         <plugin>
>             <groupId>io.swagger</groupId>
>             <artifactId>swagger-codegen-maven-plugin</artifactId>
>             <version>2.2.2-SNAPSHOT</version>
>             <executions>
>                 <execution>
>                     <id>generate-management</id>
>                     <phase>generate-resources</phase>
>                     <goals>
>                         <goal>generate</goal>
>                     </goals>
>                     <configuration>
>                         <inputSpec>target/generated-resources/swagger/management.yaml</inputSpec>
>                         <output>${project.build.directory}/generated-sources/swagger/src/mgmt</output>
>                         <language>go-server</language>
>                         <templateDirectory>src/main/resources/codegen/go-server/templates</templateDirectory>
>                         <configOptions>
>                             <sourceFolder>src/gen/go/main</sourceFolder>
>                             <packageName>mgmt</packageName>
>                             <additional-properties>apiVersion=${apiVersion}</additional-properties>
>                             
>                             
>                             
>                             
>                         </configOptions>
>                         <configHelp>true</configHelp>
>                         <verbose>${buildVerbose}</verbose>
>                     </configuration>
>                 </execution>
>             </executions>
>         </plugin>
> ```
##### Steps to reproduce

Run the code generator for any Swagger YAML where there are models defined and there will be no models generated.
##### Related issues

Not that I could find.
##### Suggest a Fix

Add a default models.mustache that at least stubs an implementation so someone could replace it with their own. Right now, I already replace the templates but since there are no default ones used, it won't even look for any I have defined.

**Comment by wing328** [comment]
@AlskiOnTheWeb we can probably reuse the model template in the Go API client: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/model.mustache

cc @guohuang

**Comment by bvwells** [comment]
I took a look at this one and have submitted a PR. Let me know if you have any feedback.
