### ISSUE TITLE
[JAXRS-CXF] Standalone enum classes are missing class name, data type, and imports

### ISSUE THREAD

**Issue by waltwood** [swagger-api/swagger-codegen#3859]
##### Description

I'm trying to use an enum as a stand-alone class to be used in multiple places in my data model. However the enum classes are not generated correctly and are therefore unusable.

The classes appear to be missing:
- class name
- import statements for the JAXB annotations
- data type for field, constructor, and enum declarations

Example:

``` java
package io.swagger.model;

@XmlType(name="")
@XmlEnum
public enum  {

    CAT(.valueOf("cat")), DOG(.valueOf("dog")), FISH(.valueOf("fish"));

    private  value;

     ( v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static  fromValue(String v) {
        return valueOf(v);
    }
}
```
##### Swagger-codegen version

2.2.1

I also pulled the latest code on master (at the time of this report) to see if the problem described here was fixed, but I'm still seeing the behavior.
##### Swagger declaration file content or url

https://gist.github.com/waltwood/e016cb33c95b78c5a3cf77f264e5c76d#file-petstore-enum-json
##### Command line used for generation

``` cmd
/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l jaxrs-cxf -i petstore-enum.json -o temp
```
##### Steps to reproduce

Using the example petstore-enum.json definition (linked above), run the codegen via the cli with language of jaxrs-cxf and observe the generated PetType.java enum class file.
##### Related issues

The following seems somewhat related:
https://github.com/swagger-api/swagger-codegen/issues/3735
##### Suggest a Fix

I believe the issue to be in the mustache templates, but I'm not familiar with the syntax.

**Comment by jfiala** [comment]
This is fixed as of PR #4164 
Identical newer issue: #4160

**Comment by jfiala** [comment]
@waltwood  I fixed this with PR #4164 as I was already working at cxf, the enumOuterClass.mustache + reference to it in model.mustache was missing. I re-generated using the modified petstore with the external enum as you described.

You can re-generate with all CLI-flags on and get a running Spring-Boot app with swagger-ui shipped in it ready for usage.

**Comment by jfiala** [comment]
@waltwood can you pls take a look at my forked repo https://github.com/jfiala/swagger-codegen/tree/cxf_refine, branch cxf_refine if you have time and confirm if it is working for you (of course you can pick the relevant changes to enumOuterClass + model.mustache)?

If you want the JaxbAnnotations, you have to use the CLI flag for language jaxrs-cxf.

**Comment by wing328** [comment]
PR has been merged into master. Please pull the latest master to give it a try.

**Comment by waltwood** [comment]
Hi @jfiala, I pulled your latest from cxf_refine and I was able to confirm the fix. I also tested with the maven plugin and after a bit of an adjustment was able to build and release an existing project using swager, cxf, and maven. Thanks!

**Comment by jfiala** [comment]
@waltwood @wing328 hast already pulled it into the swagger-codegen/master - so you can verify there, pls closed if it verified successfully.

**Comment by waltwood** [comment]
@jfiala done, and done. Thanks again!
