### ISSUE TITLE
[develop 2.0] server samples are not migrated to the new codegen

### ISSUE THREAD

**Issue by jelly** [swagger-api/swagger-codegen#386]
The current develop_2.0 branch has no script to generate the server code for the examples in samples/server-generator/

**Comment by fehguy** [comment]
Yes, currently all the script info is in the README.  Will put scripts in the ./bin folder for M1.

**Comment by fehguy** [comment]
all the server samples have been migrated to 2.0, and available in the help for the executable jar from swagger-codegen-distribution.
