### ISSUE TITLE
[JAVA/jaxrs] Which is the actual default library template? jersey1 or jersey2

### ISSUE THREAD

**Issue by y-higuchi** [swagger-api/swagger-codegen#3861]
##### Description

When I print jaxrs config options by `swagger-codegen config-help -l jaxrs`, it outputs 
```
	library
	    library template (sub-template) to use (Default: jersey1)
	        jersey1 - Jersey core 1.x
	        jersey2 - Jersey core 2.x (default)
``` 
Which one is the actual default?

##### Swagger-codegen version

2.2.0 installed via Homebrew

##### Command line used for generation

`swagger-codegen config-help -l jaxrs`

##### Steps to reproduce

`swagger-codegen config-help -l jaxrs`

##### Suggest a Fix

Replace this line to jersery2
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java#L35

possibly also removing 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java#L74-L77

if the default is jersey2?

**Comment by wing328** [comment]
@y-higuchi I just did a test and the output (jaxrs) is using `jersey2`
```
  <properties>
    <java.version>1.7</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <swagger-core-version>1.5.9</swagger-core-version>
    <jetty-version>9.2.9.v20150224</jetty-version>
    <jersey2-version>2.22.2</jersey2-version>
    <junit-version>4.12</junit-version>
    <logback-version>1.1.7</logback-version>
    <servlet-api-version>2.5</servlet-api-version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
```

May I know if you've time to contribute a fix to the wording?
