### ISSUE TITLE
Swagger Codegen template for Go has a missing import

### ISSUE THREAD

**Issue by tysont** [swagger-api/swagger-codegen#3869]
##### Description

Brand new to the project, so forgive me if I'm missing something here. I just brew installed swagger-codegen and tried to use it to generate a Go server from a hello world YAML file:

> swagger-codegen generate -i hello.yml -l go

 I get an error when I build the project after generation:

> ./default_api.go:100 : undefined: json in json.Unmarshal

Looks like it's missing the import for "encoding/json" and adding that import fixes the issue. I grabbed the source and verified that it still appears to be an issue with latest, so I threw together a quick fix and will submit a one line PR for the issue.
##### Swagger-codegen version

Latest.
##### Swagger declaration file content or url

swagger: "2.0"
info:
  version: "1.0"
  title: "Hello World API"
paths:
  /hello/{user}:
    get:
      description: Returns a greeting to the user!
      parameters:
        - name: user
          in: path
          type: string
          required: true
          description: The name of the user to greet.
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.
##### Command line used for generation

swagger-codegen generate -i hello.yml -l go
##### Steps to reproduce

Run the swagger-codegen command above and then run go build.
##### Related issues

Searched briefly, didn't see anything.
##### Suggest a Fix

I haven't used mustache templates before so I'm not 100% certain, but I think this is just a 1-line fix to the resources/go/api.mustache file (unless this should be populated from something in {{import}}).

**Comment by tysont** [comment]
Scratch that. I just tried that fix and ran the shell script to regenerate petstore, and it causes a double import of "encoding/json" in pet_api.go. Maybe this is just my issue - what could I be screwing up here? Thanks in advance for the help...

**Comment by wing328** [comment]
@tysont I don't see double import of "encoding/json" in the Petstore sample: https://github.com/swagger-api/swagger-codegen/blob/b2344e10cbc6508065ea888f332fe75f553dbad2/samples/client/petstore/go/go-petstore/pet_api.go

The issue you encountered may have already been addressed in the master.

Please pull the latest master to give it a try. (brew only installs the latest stable version, not latest master)

**Comment by tysont** [comment]
To clarify, the issue is that "encoding/json" doesn't show up in the default_api.go file for the YAML that I included above, which causes a build failure. I repro'd the issue on the latest code here, so it isn't specific to the version that brew installed.

I forked the repo and took a stab at fixing the issue by adding the additional import to the api.mustache file here:

https://github.com/tysont/swagger-codegen

That fixed the issue for my project, but when I ran the shell script to generate the petstore project, I noticed that it caused the import to be included twice. Given that, the only logical conclusion seems to be that something is goofy about my configuration or project.

I noticed these lines in the api.go template file:

> {{#imports}}	"{{import}}"
> {{/imports}}

Seems like this likely has to do with how those imports are getting created and passed in?

**Comment by wing328** [comment]
@tysont thanks for testing the latest master.

To fix it we need to update the logic [here](https://github.com/swagger-api/swagger-codegen/blob/f47208a75b2ac00878e736131fb7dc192a595e85/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java#L409-L415) as it imports "encoding/json" for primitive response/return type.

**Comment by wing328** [comment]
cc @guohuang

**Comment by tysont** [comment]
If you help me understand the change that needs to be made for that conditional check, I'm happy to try to debug later and take a stab at making/testing the change and sending a PR over.

**Comment by guohuang** [comment]
@tysont can you tell me which api file has issue? i don't see the default_api.go in your repo, I need to know your return type of the function. thanks

**Comment by tysont** [comment]
I didn't include my generated sample project in the repo; it's just a fork of this (swagger-codegen) repo. IF you follow the repro steps above with the YAML that I provided, you should end up with a default_api.go that is missing the import. The problematic generated function looks as follows:

/**
 * 
 * Returns a greeting to the user!
 *
 * @param user The name of the user to greet.
 * @return *string
 */
func (a DefaultApi) HelloUserGet(user string) (*string, *APIResponse, error) {

	var httpMethod = "Get"
	// create path and map variables
	path := a.Configuration.BasePath + "/hello/{user}"
	path = strings.Replace(path, "{"+"user"+"}", fmt.Sprintf("%v", user), -1)


	headerParams := make(map[string]string)
	queryParams := url.Values{}
	formParams := make(map[string]string)
	var postBody interface{}
	var fileName string
	var fileBytes []byte
	// add default headers if any
	for key := range a.Configuration.DefaultHeader {
		headerParams[key] = a.Configuration.DefaultHeader[key]
	}


	// to determine the Content-Type header
	localVarHttpContentTypes := []string{  }

	// set Content-Type header
	localVarHttpContentType := a.Configuration.APIClient.SelectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		headerParams["Content-Type"] = localVarHttpContentType
	}
	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{
			}

	// set Accept header
	localVarHttpHeaderAccept := a.Configuration.APIClient.SelectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		headerParams["Accept"] = localVarHttpHeaderAccept
	}
	var successPayload = new(string)
	httpResponse, err := a.Configuration.APIClient.CallAPI(path, httpMethod, postBody, headerParams, queryParams, formParams, fileName, fileBytes)
	if err != nil {
		return successPayload, NewAPIResponse(httpResponse.RawResponse), err
	}
	**err = json.Unmarshal(httpResponse.Body(), &successPayload)**
	return successPayload, NewAPIResponse(httpResponse.RawResponse), err
}

**Comment by guohuang** [comment]
@wing328 after some investigation, I found this issue is the side effect of this fix, https://github.com/swagger-api/swagger-codegen/issues/2725, we conditionally remove `imports "encoding/json"`, however, if the return type is primitive then we don't have code to handle this situation, I thought I had some code to handle this situation, but I couldn't find it, we have to somehow handle any return type. cc: @neilotoole 

@tysont the temporary work around for this issue is, change your string return type in the template to a non-primitive object. we will notify you when we fix this issue.

**Comment by wing328** [comment]
@tysont we've refactored the Go API client in 2.3.0 branch. Do you mind giving it a try to see if the issue still persists?

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by tysont** [comment]
Sorry for the lack of an update before. I tested the fix a while ago and if I recall, the issue was resolved. Thanks for jumping on this, appreciate it!

**Comment by wing328** [comment]
No problem. We just released stable version 2.3.0: https://twitter.com/wing328/status/944259218386718720

Please check it out and let us know if you've any feedback.
