### ISSUE TITLE
Proper way of extending client generator?

### ISSUE THREAD

**Issue by chrismanderson** [swagger-api/swagger-codegen#3877]
##### Description

I'm trying to subclass the Ruby client generator by following the steps in https://github.com/swagger-api/swagger-codegen/blob/master/README.md#customizing-the-generator. I've made a subclass of the generator, followed the instructions in that readme section to make my subclass

```
    package com.mycompany.swagger.codegen;

    import io.swagger.codegen.languages.*;

    public class MyRubyCodeGen extends RubyClientCodegen {
        @Override
        public String toApiName(String name) {
            if (name.length() == 0) {
                return "Api";
            }
            // e.g. phone_number_api => PhoneNumberApi
            return camelize(name) + "Api";
        }
    }
```

Then named the file `MyRubyCodeGen.java` and placed it in the /codegen/languages folder. When I try to follow the instructions and use this new file as the library when running the generator, I get an error. (If I pass `-l ruby`) instead of my custom generator, it works properly (though obviously without my customizations.
##### Swagger-codegen version

2.2.1
##### Swagger declaration file content or url

https://gist.github.com/chrismanderson/942baf6c46ff585c52f48e6b2ed18cd4

```
java -jar ~/code/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -t ~/code/swagger-codegen/modules/swagger-codegen/src/main/resources/ruby -i ~/Downloads/swagger.json -l com.mycompany.swagger.codegen.MyRubyCodeGen -o ~/Downloads/wheniwork-ruby -c ~/Downloads/config.json
```

**Comment by jimschubert** [comment]
@chrismanderson Generators must also be registered (one line fully type name) in io.swagger.codegen.CodegenConfig (exact path is [modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig)). Generators are loaded reflectively using [ServiceLoader](https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenConfigLoader.java#L15). You didn't mention this step, so I'm assuming that's the missing piece.

For an example of how generators can be extended, check out `AbstractCSharpCodegen`, which is a base type I used for refactoring `CSharpClientCodegen` and creating `AspNet5ServerCodegen`. Another contributor derived from that generator and created `NancyFXServerCodegen`. I know that's 1 client and 2 server implementations, but I hope it can help provide more detail.

**Comment by fehguy** [comment]
thanks @jimschubert for the solution.
