### ISSUE TITLE
[JavaScript] Client sets Content-Type for multipart/form-data which causes a missing boundary in the header

### ISSUE THREAD

**Issue by Danielku15** [swagger-api/swagger-codegen#3878]
##### Description

When uploading files via Ajax and FormData, you must not set the Content-Type header which is done [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache#L366).  This will cause the browser to really send a header `Content-Type: multipart/form-data` which is wrong. If you do not set this header explicitely it will set the header to something like `Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryhwk47FtsDeemWl3V`. So basically the boundary is missing which makes it impossible for the server side to parse the body. 

##### Swagger-codegen version

Latest

##### Swagger declaration file content or url

PetStore sample is also affected. 
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/ApiClient.js#L379

##### Command line used for generation

Default parameters, see PetStore. We also use browserify to really use it in the browser, not in node.js. 

##### Steps to reproduce

Define a file parameter on your API, make a call using the generated API. When checking the Content-Type header on the server-side you will see the missing boundary. 

##### Related issues

https://github.com/swagger-api/swagger-editor/issues/666
https://github.com/swagger-api/swagger-editor/issues/995
https://github.com/swagger-api/swagger-ui/issues/662

##### Suggest a Fix

In [this if-block](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache#L374) the first statement should be:
```js
    } else if (contentType == 'multipart/form-data') {
      request.unset('Content-Type'); // unset content type for auto generation by browser
      var _formParams = this.normalizeParams(formParams);
      for (var key in _formParams) {
```

**Comment by wing328** [comment]
@Danielku15 thanks for reporting the issue and proposing a fix. What if the auto-generated JS API client is used in other environments (e.g. Node) other than browser?

**Comment by triptec** [comment]
@wing328 I've had the same problem and made this PR #3932 but this here is basically the same solution, not setting the content-type if it is multipart. I can confirm that it works in node (5.10.1)

**Comment by wing328** [comment]
@triptec thanks for filing a fix and performing tests in Node environment to confirm. I'll review your PR shortly.

**Comment by triptec** [comment]
This should be solved #3932

**Comment by c094728** [comment]
I am using the lastest version of swagger-node-express 2.1.3 and have this problem and file upload would not work.  I was able to get it to work by completely removing the consumes directive which I had set to multipart/form-data.  removing  this allowed it to work.  
consumes:
      - multipart/form-data

**Comment by c094728** [comment]
It can't seem to handle a file upload combined with a json body though.  body-parser gets Unexpected token # in JSON at position 0

- path: /api/v1/uploadZip/file
  operations:

  - httpMethod: POST
    summary: Upload File
    notes: "Upload file to artifactory"
    nickname: fileUpload
  
    responses:
      200:
        description: upload file
    parameters:

    - name: body
      paramType: body
      dataType: Publication
      required: true
      description: publication

    - name: zipFile
      description: zip file
      paramType: form
      required: true
      dataType: file
