### ISSUE TITLE
Build Issue while first installation

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#3884]
_From @gsujathap on September 27, 2016 7:31_

C
![screen shot 2016-09-27 at 12 50 13 pm](https://cloud.githubusercontent.com/assets/16931145/18864136/8c207f64-84b2-11e6-99b7-2de6863ff727.png)
urrently I am using Swift V 3.0. while build it is raising some errors. How to resolve them.

_Copied from original issue: swagger-api/swagger-editor#1075_

**Comment by wing328** [comment]
Duplicated: https://github.com/swagger-api/swagger-codegen/issues/3788
