### ISSUE TITLE
not supporting Swift 3.0 

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#3885]
_From @gsujathap on September 28, 2016 5:25_

while migrating to swift 3.0 swagger files generating errors. Please resolve this issue.
I have attached list of errors
![screen shot 2016-09-28 at 10 51 19 am](https://cloud.githubusercontent.com/assets/16931145/18901550/97294032-8569-11e6-8abc-a60249b2419d.png)

_Copied from original issue: swagger-api/swagger-editor#1076_

**Comment by Edubits** [comment]
@saharj could you please test with the updated generator in #3823 ? Thanks!

**Comment by webron** [comment]
Not @saharj but @gsujathap ;)

**Comment by Edubits** [comment]
Missed that line, thanks @webron

**Comment by gsujathap** [comment]
how to check it

**Comment by gsujathap** [comment]
actually we are downloading zip file from swagger editor using swift language and the JSON URL

**Comment by Edubits** [comment]
@gsujathap on https://github.com/swagger-api/swagger-codegen you can find instructions on how to build swagger-codegen and use it. In this case you should check out the swift-3 branch at https://github.com/hexelon/swagger-codegen/tree/swift-3

**Comment by gsujathap** [comment]
![screen shot 2016-09-28 at 4 39 14 pm](https://cloud.githubusercontent.com/assets/16931145/18911337/24213e88-859a-11e6-9b92-1990e3cfb695.png)
I have downloaded a swift file for API and models auto generating using JSON URL. In build it is generated 999+ errors. Please help me out

**Comment by Edubits** [comment]
@gsujathap The online generator runs on the latest stable release which does not support Swift 3 yet. That's why you should build your own Swagger codegen binary based on the swift-3 branch as described in the link.

**Comment by gsujathap** [comment]
which version it will support Swift 2.2 or swift 2.3

**Comment by gsujathap** [comment]
when I am trying 'mvn clean package' command 
command not found error occurs. plz check once

**Comment by gsujathap** [comment]
while I am doing run docker in vagarant 
git clone http://github.com/swagger-api/swagger-codegen.git
cd swagger-codegen
vagrant up
vagrant ssh
cd /vagrant
./run-in-docker.sh mvn package
**# I am getting this error but, I have installed docker latest version plz check once**
-bash: ./run-in-docker.sh: No such file or directory

**Comment by Edubits** [comment]
@gsujathap for `mvn clean package` to work you need to have Maven installed.
Swift 3 support is currently scheduled for the 2.3.0 release of Swagger Codegen.

**Comment by gsujathap** [comment]
i HAVE INSTALLED maven and vagarant everything is fine except this command( **./run-in-docker.sh mvn package**)

**Comment by gsujathap** [comment]
i HAVE INSTALLED maven and vagarant everything is fine except this command( **./run-in-docker.sh mvn package**)

**Comment by gsujathap** [comment]
after successful generation of APIs and Models still I am facing same errors. I have used this command for generting files. please respond to my comment ASAP. 
**# swagger-codegen generate -i http://viveky.com:3000/explorer/swagger.json -l swift -o /tmp/test/**

**Comment by wing328** [comment]
@gsujathap the "Getting Started" section is a good starting point: https://github.com/swagger-api/swagger-codegen#getting-started.

**Comment by gsujathap** [comment]
I have tried everything but still I am getting same errors 

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i http://viveky.com:3000/explorer/swagger.json \
   -l swift \
   -o /var/tmp/swift_api_client

**Comment by gsujathap** [comment]
which alamofire version using? I got lot of errors while using alamofire 4.0. please respond ASAP

**Comment by gsujathap** [comment]
I am getting this error **

> cannot invoke 'Method' with an argument list of type '(rawvalue: String)'

**  in **alamofireimplementations** class in **execute** fuction
Alamofire.Method(rawValue: method)
please respond ASAP

**Comment by grEvenX** [comment]
@gsujathap You need to specify `-l swift3`, not `-l swift` to generate Swift 3 compatible code.

**Comment by gsujathap** [comment]
currently I am not using ur library. Its not useful for my application.

**Comment by nmaoTV** [comment]
@grEvenX  tried swift3 and got this:
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name swift3 

not supported anymore?

**Comment by wing328** [comment]
@nmaoTV are you using the latest master and build the JAR locally?

**Comment by nmaoTV** [comment]
@wing328 java -jar swagger-codegen-cli-2.2.1.jar generate -i xxx.json -l swift3 -o testSwift3/
something like this

**Comment by wing328** [comment]
@nmaoTV that's not the latest master. You will need to pull the latest master and run `mvn clean package` to build the JAR locally.

(2.2.1 is the latest stable version)

**Comment by nmaoTV** [comment]
@wing328  oh yeah! works on master! thank you~

**Comment by wing328** [comment]
No problem :)

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
