### ISSUE TITLE
Brew: latest version not available

### ISSUE THREAD

**Issue by szuperaz** [swagger-api/swagger-codegen#3890]
##### Description

I have just installed swagger-codegen using brew, and it installed version 2.1.5, however the readme says the latest stable version is 2.2.1. I couldn't find this version on brew. Is it possible that it's not available there?

##### Steps to reproduce

`brew install swagger-codegen`

**Comment by wing328** [comment]
@szuperaz did you update the formula repo? (I did file a PR against the brew formula repo to add the latest stable version - 2.2.1)

**Comment by arnested** [comment]
Homebrew has version 2.2.1. See https://github.com/Homebrew/homebrew-core/blob/master/Formula/swagger-codegen.rb

Did you run `brew update` to update brews list of packages and versions recently?

If you still get the old version after running `brew update` I would guess there is something wrong with your Homebrew installation.

**Comment by ravi-ios** [comment]
How to install swagger codegen V2.1.6.

**Comment by wing328** [comment]
Please install the latest version 2.2.3 instead.
