### ISSUE TITLE
Form post support in generated clients

### ISSUE THREAD

**Issue by deardooley** [swagger-api/swagger-codegen#39]
Thank you for the great work on this project. I was implementing this on our api earlier today and I noticed a discrepancy in the swagger-ui and swagger-codegen projects. Support for defining and posting HTML forms was recently added to swagger-core and swagger-ui. I'm wondering if it was just a matter of time before post form support makes its way into swagger-codegen or if it is not on the roadmap. If there are not plans to add it anytime soon, I'm happy to send a pull request with the changes I made to support form submission in php and java. I'm afraid someone with other language expertise would need to check out the mustache templates in other languages. There's also the chance that I'm completely missing something conceptually. If so, please let me know. Thanks again for the great work.

**Comment by xhh** [comment]
Form post support is added to Java codegen with #681.

**Comment by wing328** [comment]
Based on my knowledge, this is done for Java, Android, Scala, Ruby, ObjC, Perl, Python, PHP.

**Comment by webron** [comment]
And what would it be missing for? :)

**Comment by wing328** [comment]
Well I can't confirm for C++ (Tizen and Qt5)
