### ISSUE TITLE
NodeServerFromSpec.scala does not exist

### ISSUE THREAD

**Issue by abramz** [swagger-api/swagger-codegen#3906]
##### Description

I am unable to follow the README for the NodeJS server generator as the scala file, `NodeServerFromSpec.scala` does not exist. It is not in the source repository and `mvn package` does not generate it.

##### Swagger-codegen version

Source from master 9/29/2016

##### Steps to reproduce

[Follow the README.md exactly](https://github.com/swagger-api/swagger-codegen/blob/4d19da41dd8a3462f88c2be57174aace45101064/samples/server-generator/node/README.md)

- Install nodejs
- Install scala
- put scala in PATH
- run `mvn package`

**Comment by wing328** [comment]
That README is outdated as we migrated the project from Scala to Java a while ago.

For NodeJS server, please refer to https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/nodejs

**Comment by abramz** [comment]
Thanks
