### ISSUE TITLE
[JAVA] CodegenParameter instance copy is not safe

### ISSUE THREAD

**Issue by RaphC** [swagger-api/swagger-codegen#3908]
Hi,
##### Description

I'm using swagger codegen maven plugin to generate from swagger file our Java class with my own generator. I extended JavaJAXRSSpecServerCodegen to add some feature like ignoring some of parameters in the methods which are described in the swagger file. To do that, I set a vendor extensions and then when the plugin invokes fromOperation It ignores the parameters with these extension. In my code I have to make a copy of the CodegenParameter.

List<CodegenParameter> printableParams = Lists.newLinkedList();
        for (CodegenParameter p : op.allParams) {
            ....
                printableParams.add(p.copy());
    }

Unfortunately when copying CodegenParameter instance, the attribute vendorExtensions is copied by reference.

output.vendorExtensions = this.vendorExtensions;

So If the current instance p modify its  vendorExtensions Map (add a new element for instance), my new cloned instance is affected by whereas it shouldn't be.
##### Swagger-codegen version

2.2.1
##### Suggest a Fix

Just make a copy of attribute vendorExtensions in the method copy() of CodegenParameter instead of  copying reference

**Comment by wing328** [comment]
@RaphC thanks for the suggestion. May I know if you've time to contribute the enhancement?

**Comment by RaphC** [comment]
Hi,

No problem, I can provide an enhancement.

Regards,

**Comment by RaphC** [comment]
Hi @wing328 
I've just created the following PR : https://github.com/swagger-api/swagger-codegen/pull/4093
