### ISSUE TITLE
Every endpoint fails validation with `Invalid data type UUID. Best guess: UUID`

### ISSUE THREAD

**Issue by jfeldstein** [swagger-api/swagger-codegen#391]
`Invalid data type UUID. Best guess: UUID`

Full console output here: http://cl.ly/text/0c3W0d32382I

What's up?

**Comment by jfeldstein** [comment]
Here's the swaggerset http://cl.ly/242V1y3X441Q

**Comment by webron** [comment]
Looks like you're trying to use `UUID` as the type for parameters, but `UUID

**Comment by webron** [comment]
Looks like you're trying to use `UUID` as a parameter type, but `UUID` is not a valid type in the Swagger spec. You can use `string` to specify a UUID field.

If you migrate to Swagger 2.0, you could use `"type": "string"` and `"format": "uuid"` together to specify it better, but it is not supported in Swagger 1.2.

**Comment by jfeldstein** [comment]
How do I migrate to 2.0? I cloned master branch from the repo home. 

@jglassenberg -- Does this make sense to you? Can you implement the fix to our Swaggerset?

**Comment by webron** [comment]
You can use the codegen (the develop_2.0 branch) to migrate a 1.2 spec to 2.0. However, for it to work, your 1.2 spec needs to be valid, which it isn't right now.

**Comment by jfeldstein** [comment]
What's wrong with it?

CC @jglassberg

I've never written one before

**Comment by fehguy** [comment]
I suggest you use the develop_2.0 branch.  You can simply take your JSON files and save them to the filesystem, and fix any issues that exist, like Ron mentioned.  Please reopen if you want help with that.
