### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: unknown library: volley

### ISSUE THREAD

**Issue by pradeepkumarreddyk** [swagger-api/swagger-codegen#3916]
##### Description
I have used the following dependency in android studio to download the swagger-codegen-cli jar file:-
compile "io.swagger:swagger-codegen-cli:2.1.4"

Then, I'm using the following command
##### Command line used for generation
java -jar swagger-codegen-cli-2.1.4.jar generate -i generate_upload.yml -l android --library=volley -o generated_code_for_upload_resource/ -c generate_config.json

and i'm getting the following exception:-
--------------------------------------------
Exception in thread "main" java.lang.RuntimeException: unknown library: volley
        at io.swagger.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:1637)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:307)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:186)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

##### Swagger-codegen version

i'm using 2.1.4 version of swagger codegen

##### Steps to reproduce
1) include the following dependency in android studio
compile "io.swagger:swagger-codegen-cli:2.1.4"

this downloads the jar file.

2) using this jar file, try to generate the code using the following command line

java -jar swagger-codegen-cli-2.1.4.jar generate -i generate_upload.yml -l android --library=volley -o generated_code_for_upload_resource/ -c generate_config.json

3) I'm getting exception as unknown volley library

**Comment by wing328** [comment]
The Android `volley` support was added in 2.1.5: https://github.com/swagger-api/swagger-codegen/pull/1775

I would suggest you to upgrade to the latest stable version: 2.2.1.

**Comment by ungular** [comment]
I want to generate java code from my yaml file, but got same error: "unknown library: xxx"
- I created the java-proj.json :
```
{
    "library": "proj",
    "artifactId": "swagger-patienten-app"
}
```
- and proj-test.sh :
```
...
ags="$@ generate -i swagger-file.yaml -l java -c java-proj.json -o proj -DhideGenerationTimestamp=true"
```
For what is '-c' option? and java-proj.json file? what is 'proj' from "library": "proj"?

**Comment by wing328** [comment]
`proj` is not a valid "library". For a list of supported `library`, please run `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java`

**Comment by ungular** [comment]
@wing328  I tried this in json:
```{
    "artifactId": "swagger-proj",
    "library": "jersey2",
    "useBeanValidation": true
}```
No errors, but it does not generate the test data and validation like in jersey2 sample, how to achieve this? What else should I change/add ?
