### ISSUE TITLE
[RAILS5] Server code issues

### ISSUE THREAD

**Issue by apanzerj** [swagger-api/swagger-codegen#3917]
##### Description

The autogenerated rails5 server code has some bugs. 
1. Controllers have the wrong names. (need to be plural)
2. Tables are singular (need to be plural)
3. validate_presence_of => validates_presence_of
##### Swagger-codegen version

master
##### Command line used for generation

./bin/rails5-petstore-server.sh
##### Steps to reproduce
1. `./bin/rails5-petstore-server.sh`
2. `cd samples/server/petstore/rails5`
3. `bundle exec rails server`
##### Suggest a Fix

PR: https://github.com/swagger-api/swagger-codegen/pull/3909

**Comment by apanzerj** [comment]
cc @zlx since it looks like you worked on this last...

**Comment by wing328** [comment]
@apanzerj thanks for the PR. We'll review and let you know if we've any question.

**Comment by apanzerj** [comment]
Hey thanks!

I'm going to keep digging on this and see if there are any other changes that need to be made, this was just the first pass but I wanted to keep the PR small.

**Comment by wing328** [comment]
I also prefer small PR as it's easier to review and merge.

**Comment by zlx** [comment]
@apanzerj It's helpful
