### ISSUE TITLE
[Java-Retrofit2] Vendor Mime-types in consumes definition.

### ISSUE THREAD

**Issue by Rajmohan** [swagger-api/swagger-codegen#3918]
##### Description

When vendor mime-types are specified in **_consumes_** section,  these (vendor mime-types) are not being propagated in the request.
##### Swagger-codegen version

master
##### Swagger declaration file content or url

https://gist.github.com/Rajmohan/45bd552ff87a06cf07cb40c3b0e09ed5

Especially, note the consumes field for POST request having a vendor mime-type,

``` json
   "consumes": [
          "application/vnd.example+json"
    ]
```

Generated code is,

``` java
public interface PetApi {                                                                 
  /**                                                                                     
   * Add a new pet to the store                                                           
   *                                                                                      
   * @param body Pet object that needs to be added to the store (optional)                
   * @return Call&lt;Void&gt;                                                             
   */                                                                                     

  @POST("pet")                                                                            
  Call<Void> addPet(                                                                      
    @Body Pet body                                                                        
  );                                                                                      

}  
```

Invoking above operation does not propagate vendor mime-type in the Content-type request.

Should not a Header annotation be generated to handle vendor-specific mime type ? For example,   

``` java

public interface PetApi {                                                                 

  @POST("pet")                                                                            
  @Headers({"Content-Type : application/vnd.example+json"})
  Call<Void> addPet(                                                                      
    @Body Pet body                                                                        
  );                                                                                      

}  

```

Adding the above header, results in correct propagation of the vendor mime-type.
##### Command line used for generation

java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar  generate -i petstore-post-vendor-ext.json -l java --library retrofit2
##### Steps to reproduce

As described above.
##### Suggest a Fix

Generate Operation Header annotation having content-type as vendor-specific mime-type.
This results in correct propagation of the vendor mime-type.

**Comment by wing328** [comment]
@Rajmohan your suggestion looks good to me. May I know if you've cycle to contribute the enhancement?

**Comment by Rajmohan** [comment]
@wing328 sure, I will take a shot at the fix. Thanks!

**Comment by wing328** [comment]
@Rajmohan thanks. Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/api.mustache#L32

To obtain the `consumes`, please refer to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/api.mustache#L87 as an example.
