### ISSUE TITLE
Codegen does not read all attributes of schema property

### ISSUE THREAD

**Issue by abhijith-prabhakar** [swagger-api/swagger-codegen#3925]
Swagger specification for schema object specifies a list of attributes which are valid for a given schema object.  But codegen(CodegenProperty.java) does not read in all of this attributes.  If declared on the schema, these attributes are ignored.  

Codegen should read these properties and use it for model generation with bean validation enabled.  Is linked to https://github.com/swagger-api/swagger-codegen/issues/2549

**Comment by JasonNorth** [comment]
This fixes maxItems and minItems for me although it needs a release of swagger-core first:

https://github.com/swagger-api/swagger-codegen/pull/4293/commits/4d55d25f9f5180f6cbb685d4d5c4b85405f7a719
