### ISSUE TITLE
Support for mix of composition & inheritance

### ISSUE THREAD

**Issue by yannickadam** [swagger-api/swagger-codegen#3926]
##### Description

I guess this is language independent => I am inspecting the output with -DdebugModels, with supportInheritance = true.
When trying to mix field composition and inheritance, I lose inheritance. In the sample below, I expect to have "Cat" extends "Pet", with "Pet" inside the parentModel property of "Cat". However, I only have interfaceModels inside "Cat". 

If I add a discriminator to "item", I have the proper chain of parentModel(s) (full inheritance)

I believe this issue started in the past few days, maybe after PR #3637? Is there some parameter I need to add to my custom generator?

##### Swagger-codegen version

Latest master

##### Swagger declaration file content or url

```yaml
definitions:
  item:
    type: object
    description: No discriminator here, I want field composition
    properties:
      id:
        type: string
  pet:
    type: object
    discriminator: type
    required:
      - name
      - type
    allOf:
      - $ref: '#/definitions/item'
      - type: object
        properties:
          name:
            type: string
          type: 
            type: string
  cat:
    type: object
    description: Cat has lost its parentModel
    allOf:
      - $ref: '#/definitions/pet'
      - type: object
        properties:
          sleepy: 
            type: boolean
```

**Comment by cbornet** [comment]
Indeed `cat`should have `pet` as parent. I'll have a look.

**Comment by yannickadam** [comment]
In DefaultCodegen.java, lines 1219-1221

```
        if (model instanceof ModelImpl) {
            m.discriminator = ((ModelImpl) model).getDiscriminator();
        }
```

In our case, `pet` is instanceof `ComposedModel` and there is missing code to fetch the discriminator.

**Comment by cbornet** [comment]
Well, `ComposedModel` doesn't have a discriminator property...
So this would need a modification in the core.
cc @wing328 @fehguy

**Comment by yannickadam** [comment]
After spending some time to check how swagger parses ComposedModels, I realized my `pet` definition isn't right. It should be like this:
```YAML
  pet:
    allOf:
      - $ref: '#/definitions/item'
      - type: object
        properties:
          discriminator: type
          required:
            - name
            - type          
          name:
            type: string
          type: 
            type: string
```
At least, the parser will properly load the discriminator that way. Afterward, I did a quick modifications to lines 1219+ : 
```JAVA
        if (model instanceof ModelImpl) {
            m.discriminator = ((ModelImpl) model).getDiscriminator();
        } else if (model instanceof ComposedModel) {
            for( Model innerModel: ((ComposedModel)model).getAllOf() ) {
                if( innerModel instanceof ModelImpl ) {
                    m.discriminator = ((ModelImpl) innerModel).getDiscriminator();
                }
            }
        }
```
I haven't done any extensive tests, but it works for this simple use case. I can work on a pull request if this looks fine (especially the assumption about the discriminator that needs to be inside the inline model).

**Comment by yannickadam** [comment]
Discriminator should be placed like this:
```YAML
  Pet:
    type: object
    allOf:
      - $ref: '#/definitions/_Item'
      - type: object
        discriminator: petType
        required:
          - name
          - petType          
        properties:
          name:
            type: string
          petType: 
            type: string
            enum: 
              - cat
              - dog
```

**Comment by jeff9finger** [comment]
+1

**Comment by jeff9finger** [comment]
Why was this closed? I had to add the code above to get codegen to create models with inheritance correctly.

My models are defined correctly.

Is this addressed in another issue?

**Comment by wing328** [comment]
@jeff9finger I believe @yannickadam fixed it by defining the `discriminator` correctly (not as a property)

**Comment by jeff9finger** [comment]
I still have this issue. My spec is correct, but still not getting inheritance defined correctly. When I try to use the 2.2.2-SNAPSHOT, it still does not work. Applying the suggested code above does the trick.

**Comment by jeff9finger** [comment]
I tried this again with that latest 2.2.2-SNAPSHOT and it seems to work. Thanks
