### ISSUE TITLE
[Swift] Incorrect generation emun type for swift language

### ISSUE THREAD

**Issue by razalur** [swagger-api/swagger-codegen#3934]
##### Description

Hello! I generate client for swift language. There is incorrect swift language syntax generated for enum type.

For example for this json code:
```json
{
  "basePath": "/myPath",
  "definitions": {
    "SomeValue": {
      "properties": {
        "level": {
          "description": "word (1 = Simple1 , 2 = Simple2 , 3 = Simple3 , 4 = Simple4 )",
          "enum": [
            1,
            2,
            3,
            4
          ],
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    }
  },
  "paths": {},
  "swagger": "2.0"
}
```

I've got this swift code for enum type "Level":
```swift
public enum Level: String { 
        case 1 = "1" 
        case 2 = "2"
        case 3 = "3"
        case 4 = "4"
    }
```

As you can see there are numbers after "case" keywords. But this is not correct syntax for swift (compiler error: "Expected identifier in enum 'case' declaration"). Unfortunately I can't change my json to avoid this. May be it is possible to change somehow the logic for swift code generation to get right solution?

Best regards,
Aleksey Razzhivaykin

**Comment by wing328** [comment]
@razalur thanks for reporting the issue. I'll take a look later today.

**Comment by wing328** [comment]
@razalur I've filed https://github.com/swagger-api/swagger-codegen/pull/3941 so that enum with numeric value looks like this:
```
public enum Level: String { 
        case Number1 = "1" 
        case Number2 = "2"
        case Number3 = "3"
        case Number4 = "4"
    }
```

**Comment by wing328** [comment]
@razalur PR merged into master. Please pull the latest master to give it a try.

**Comment by razalur** [comment]
It seems that nothing changes...  Please, check it again....

**Comment by wing328** [comment]
@razalur did you use editor.swagger.io to generate the Swift API client? 

editor.swagger.io is using the latest stable version (not the latest master) so plesae build the JAR locally based on the latest master.

**Comment by razalur** [comment]
I use:
```bash
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /Users/User/Desktop/test.json -l swift -o /tmp/
```

and in git log I can see you commit. But nothing changed in the result.

**Comment by wing328** [comment]
Did you do a `mvn clean package`?

**Comment by razalur** [comment]
No. Thank you! Now it's ok!

**Comment by c100k** [comment]
Hello. Actually, the PR does not solve completely the problem. For example, for this type of definition :

```yml
resolution:
  type: string
    enum:
      - 640x360
      - 950x540
      - 1280x720
      - 1920x1080
      - 2592x1458
```

Executing with the latest version :

`swagger-codegen generate -i http://example.com/swagger.json -l swift3 -o /tmp/swift/`

Outputs :

```swift
public enum Resolution: String { 
    case 640x360 = "640x360"
    case 950x540 = "950x540"
    case 1280x720 = "1280x720"
    case 1920x1080 = "1920x1080"
    case 2592x1458 = "2592x1458"
}
```

which is not valid Swift3 code.
