### ISSUE TITLE
[DART] type number without format generates wrong data type

### ISSUE THREAD

**Issue by ircecho** [swagger-api/swagger-codegen#3936]
##### Description

When having a model property with type "number" and no format property like the following: 

```json
"perOrderPercentage": {
    "type": "number"
}
```

The generated dart property would look as follows:

```dart
@Property(name: 'perOrderPercentage')
Number perOrderPercentage = null;
```

The problem is, that the data type "Number" does not exist. The correct type would probably be "num".

##### Swagger-codegen version

Tested on master@cd6b5fec20eb112dc099c91688c90855911672c9

**Comment by wing328** [comment]
@ircecho thanks for reporting the issue and tested with the latest master.

I've filed #3942 to address the issue.

**Comment by wing328** [comment]
@ircecho PR merged into master. Please pull the latest master to give it a try.

**Comment by ircecho** [comment]
I tested the code and it is working properly now.

**Comment by wing328** [comment]
@ircecho thanks for doing a test to confirm
