### ISSUE TITLE
branch develop_2.0 - 'mvn add_test_sources' doesn't work

### ISSUE THREAD

**Issue by alonsnir** [swagger-api/swagger-codegen#394]
tested with java generated client
mvn generate-test-sources
...
....
[INFO] --- build-helper-maven-plugin:1.9.1:add-test-source (add_test_sources) @ swagger-client ---
[INFO] Test Source directory: /home/user/swagger-codegen/samples/client/petstore/java/src/test/java added.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
..................................................................
but no test sources been generated

**Comment by fehguy** [comment]
Yes, there are no tests created in the client generated.  I will see about having some basic tests created from the generator.

**Comment by wing328** [comment]
@alonsnir we've added auto-generated test cases in most popular API clients. Please pull the latest master to give it a try.
