### ISSUE TITLE
[JAVA] Bug generating with retrofit2: package conflict with user classes

### ISSUE THREAD

**Issue by punksta** [swagger-api/swagger-codegen#3946]
##### Description

We have Entity named "Body". Swagger generates class for it `o.swagger.client.model.Body` and import it to retrofit api interface file:
```
import io.swagger.client.model.Body;
```
Name Body conflicts with retrofit body: `retrofit2.http.Body.` which is used without package specification.

```
 @POST("store/products")
  Observable<Product> createBody(
    @Body Body body
  );
``` 
##### Swagger-codegen version

2.2.1

##### Command line used for generation

java with config
```
{
  "library":"retrofit2",
  "useRxJava": true
}
```

##### Steps to reproduce

Create entity with name equals one of retrofit annotation(Body, POST, GET, Multipart, Part)

##### Suggest a Fix

It can be fixed by using full package of classes of retrofit annotations:
 ```
 @POST("store/products")
  Observable<Product> createBody(
    @retrofit2.http.Body Body body
  );
```

**Comment by wing328** [comment]
@punksta thanks for reporting the issue. May I know if you've time to contribute a fix?

**Comment by punksta** [comment]
I am going to fix it today
