### ISSUE TITLE
[All] Codegen does not support api-level security specification

### ISSUE THREAD

**Issue by ifreecarve** [swagger-api/swagger-codegen#3947]
##### Description

From the [swagger specification](http://swagger.io/specification/): 

> `security` [Security Requirement Object](http://swagger.io/specification/#securityRequirementObject) 
> A declaration of which security schemes are applied for the API as a whole. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). Individual operations can override this definition.

Codegen breaks the spec; it doesn't follow api-level security.
##### Swagger-codegen version

Using Swagger Editor Version 2.10.3.  (Their bug reporting tool referred me here for codegen issues.)
##### Swagger declaration file content or url

``` yaml
swagger: '2.0'
info:
  title: Test case for "global" security object
  version: 0.0.0
securityDefinitions:
  MyGlobalSecurity:
    type: basic
  MyLocalSecurity:
    type: basic
security:
  - MyGlobalSecurity: []
paths:
  /without_local_override:
    get:
      summary: Should show global security
      responses:
        default:
          description: Unexpected error
  /with_local_override:
    get:
      security:
        - MyLocalSecurity: []
      summary: Maybe show both types of security?
      responses:
        default:
          description: Unexpected error
```
##### Steps to reproduce
1. Open the [online swagger editor](http://editor.swagger.io/)
2. Paste the above snippet of code
3. Notice that the generated doc for `/without_local_override` does not include any section for "security".  Notice that the "security" section of `/with_local_override` has `MyLocalSecurity` but not `MyGlobalSecurity`.
4. Download and unzip the ruby client
5. Notice that in the generated ruby API, `auth_names = []` appears 
##### Related issues
- Possibly [this one for swagger-UI](https://github.com/swagger-api/swagger-ui/issues/1517)
##### Suggest a Fix

The current set of test cases do not include an API-level security test.

The sample codegen file should be updated:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/petstore.json#L20-L21

Add the `MyGlobalSecurity` entry shown in my code example.  

(e.g.):

``` yaml
securityDefinitions:
  MyGlobalSecurity:
    type: basic
```

Refer to it as an API-level `security` section at the top level:

(e.g.):

``` yaml
security:
  - MyGlobalSecurity: []
```

Then check whether the generated code refers to it.

**Comment by wing328** [comment]
@ifreecarve thanks for reporting the issue. We've addressed something similar before: https://github.com/swagger-api/swagger-codegen/issues/1365

I did a test with the latest master, which seems to work. Here are the code snippets:
```
      # http body (model)
      post_body = nil
      auth_names = ['MyLocalSecurity']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
```

```
      # http body (model)
      post_body = nil
      auth_names = ['MyGlobalSecurity']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
```

Can you please do a test with the latest master to see if that works for you?
(swagger editor is using the latest stable version , not the latest master of Swagger Codegen)

**Comment by ifreecarve** [comment]
I will try to run a test on the latest master.  Really though, I think the correct thing to do is add an automated test for this, starting with an API-level security specification in the `petstore.json` example.  I can try to put together a PR with that; where are the existing automated tests of the generator?

**Comment by wing328** [comment]
@ifreecarve totally agreed with covering the issue with automated tests. We created the tests in swagger-parser instead when the issue was first reported: https://github.com/swagger-api/swagger-codegen/pull/1380

If you want to add additional tests in Swagger Codegen, I'll reply later with more info (busy at the moment...)

Thanks for offering help to add more tests.

**Comment by wing328** [comment]
@ifreecarve the following file is a good starting point to add more tests:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java

**Comment by hsgreen** [comment]
This same problem is happening with both the documentation generated by the online editor and the Node.js server generated code.

**Comment by wing328** [comment]
If it's still an issue with the latest master, please reply to let us know and we'll reopen the issue.

**Comment by PatrickGeyer** [comment]
I'm still having this issue.
