### ISSUE TITLE
[cli] utility doesn't respect supportPython2 option

### ISSUE THREAD

**Issue by dkucsc** [swagger-api/swagger-codegen#3951]
##### Description

I supply a filename to the `swagger-cogegen-cli.jar generate --config` option, and its contents is just `{"supportPython2":"True"}`.  The filename ends with .json

I also specify the same command without specifying the `--config` option.

The problem is that the output stub servers from both commands produce seemingly the same output; the `app.py` file in both servers say Python 3 on the first line.

I even go to `modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java` and change the default value on line 119 from `"false"` to `"true"`, run `"mvn clean package"`, call the produced jar file at `./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar` in the same ways as before, and there still doesn't seem to be a difference.

This is the exact command I'm running:

`java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -c temp.json -i schemas/target/swagger/ga4gh/all_services.swagger.json -l python-flask -o server`

**Comment by dkucsc** [comment]
I specify just `true` (no single or double quotes) and it runs without complaining, but still produces a server with Python 3 at the top of `app.py`.

I specify `True` and it complains.

I specify `'True'` and it complains.

I specify `"True"` and it doesn't complain, but still doesn't work correctly.

**Comment by wing328** [comment]
@dkucsc thanks for reporting the issue. I think it's bug and I'll file a PR to fix it.

**Comment by wing328** [comment]
@dkucsc thanks for reporting the issue and I've filed #3952 to fix it.

There are 2 other references to `python3`, which are also addressed in #3952

**Comment by wing328** [comment]
PR merged into master. Please pull the latest master to give it a try.

**Comment by wing328** [comment]
@dkucsc did you have a chance to pull the latest master to confirm if the fix works for you?

**Comment by dkucsc** [comment]
Yes indeed, it worked.  I pulled the latest changes to my master and redid everything, and the output server `app.py` had just `python` at the top, without the `3`.  Thank you.

**Comment by wing328** [comment]
@dkucsc thanks for the confirmation
