### ISSUE TITLE
Swagger Swift codegen generates an empty implementation for a map #3805

### ISSUE THREAD

**Issue by grEvenX** [swagger-api/swagger-codegen#3960]
##### Description

If you include a reference to a definition that is not an object (primitive type) the Swift generated client creates an empty class instead of the correct type.

I have included an example definition in this issue.
The swagger-codegen for Swift generates an "empty" Gender class instead of an enum that can be used for the Person class. This leads to swagger code that can't be used for that model, workaround is to not use references to primitive types.

Previously swagger could only reference object types, but the definition now says:

> Definitions Object
> An object to hold data types that can be consumed and produced by operations. These data types can be primitives, arrays or models

The reason that this is of value in this particular case is when you have a lot of models using the same enum definition (e.g. "Gender") and you have to keep manually converting between the different enum types that are actually the same (we only want _one_ definition of Gender enum).
##### Swagger-codegen version

master-branch at #522e27b752bc39059af7f13d5ec25c21a5959aca
##### Swagger declaration file content or url

``` yaml
definitions:
  Person:
    type: object
    properties:
      name:
        type: string
      gender:
        $ref: '#/definitions/Gender'

  Gender:
    type: string
    enum:
      - male
      - female
```
##### Command line used for generation

swagger-codegen-cli generate -i /swagger-api/yaml/v1.yaml -l swift -c swift-config.json -o generated_swift_client

```
{
  "podHomepage": "http://myworkout.no",
  "sortParamsByRequiredFlag": true,
  "ensureUniqueParams": true,
  "projectName": "MyworkoutClient",
  "podSource": "{:git => \"git@bitbucket.org:myworkout/ios-api-client.git\", :tag => "1.0.0",
  "podVersion": "1.0.0",
  "podSummary": "MyworkoutClient for Myworkout API generated by Swagger"
}
```

**Comment by wing328** [comment]
@grEvenX `Gender` is not an model (type: object) and I believe Swagger Parser only supports `$ref` pointing to model (type: object) at the moment.

As a workaround, please define gender as an enum string directly without using $ref and give it another try.

**Comment by wing328** [comment]
@grEvenX please pull the latest master a try as the latest version of swagger parser has better support for reference to primitive types.
