### ISSUE TITLE
[csharp] Perhaps Modules documentation error in README.mustache

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#3961]
##### Description

Looking at README.mustache in csharp client (swagger-codegen/modules/swagger-codegen/src/main/resources/csharp/README.mustache) I have noticed a little singularity: while Api and Client inclusion are correct, Model path does not include the namespace.

This happens at rows 47-51 and 59-63.
##### Swagger-codegen version

2.2.0
##### Suggest a Fix

Instead of

```
using System;
using System.Diagnostics;
using {{packageName}}.Api;
using {{packageName}}.Client;
{{#modelPackage}}
using {{{.}}};
{{/modelPackage}}
```

I suppose is more correct

```
using System;
using System.Diagnostics;
using {{packageName}}.Api;
using {{packageName}}.Client;
using {{packageName}}.Model;
```

What do you think ?

Thanks,

Luca

**Comment by wing328** [comment]
@lunat  Yes, please file a PR with the suggested fix and I'll merge it into master.

**Comment by jimschubert** [comment]
@wing328 @lunat I'll add this to my PR #4010 in which I fix modelPackage elsewhere. The suggested fix in this PR would actually cause a bug after 4010 is accepted.

**Comment by jimschubert** [comment]
I've pushed the change to the open PR which is compatible with that PR's change (allows the C# generator to support custom API and Model namespaces via `apiPackage` and `modelPackage`).
