### ISSUE TITLE
Creating different Models from Objects with same structure if Objects have different Titles

### ISSUE THREAD

**Issue by akalitenya** [swagger-api/swagger-codegen#3967]
Is it possible?

It seems that now if codegen finds two objects with same schema (no matter of titles), it will create one model for them. Can we force it to alter this behavior?

For example, if objects have different titles - create separate models for them.

**Comment by wing328** [comment]
@akalitenya if you want complete control of the model name, the best way is to define the model properly instead if using inline schema (with title attribute) to define the models.
