### ISSUE TITLE
Generation of attributes for fields

### ISSUE THREAD

**Issue by egodolja** [swagger-api/swagger-codegen#3973]
##### Description

Question:

Does swagger support the generation of an attribute for specific fields or class? For example:
Person:
   properties:
      id:
         type: string
         attribute: true
      firstName:
         type: string
      lastName:
         type: string
This model would generate the following code (C#)

class Person {
    public string firstName {get; set;}
    [id("123")]
    public string lastName {get; set;}
}
--or--
[id("456")]
class Person{
    public string firstName{get;set;}
    public string lastName{get;set;}
}
**Does swagger-codegen currently support this or something similar to this?**

I attempted the following
xml:
  attribute: true
however, that's not the kind of attribute I am looking to generate. 

Currently using editor.swagger.io

**Comment by wing328** [comment]
Here is an example of what a model documented in Swagger/OpenAPI spec looks like: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L654

(there's no `attribute` field that I'm aware of)

Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by wing328** [comment]
Closing this as there's no update. If you need further assistance, please open a new issue.
