### ISSUE TITLE
[html2] curl examples not showing correct security headers

### ISSUE THREAD

**Issue by bshamblen** [swagger-api/swagger-codegen#3974]
I'm using the following security definition:

```yaml
securityDefinitions:
  basicAuth:
    type: basic
  apiKey:
    type: apiKey
    name: api-key
    in: header
```

When using editor.swagger.io to generate the `html2` version of the client, the curl example that's displayed for all of the endpoints looks like this:

```cli
curl -X GET -H "apiKey: [[apiKey]]" -H "apiSecret: [[apiSecret]]" "https://www.example.com/test"
```

### Issues when generating with a local build
- The `apiKey` header is currently broken. It's not displayed, even if you include it in your `securityDefinitions`.
- The curl example is not using the `name` value from the `apiKey` definition. 
- There's no `apiSecret` option in the OpenAPI specification, and there's no other security type that uses the `apiSecret` header. So, I'm not sure why the `apiSecret` header's included in the example. It doesn't hurt anything, but it's confusing to include it in the example.
- There's no example for the `basic` authentication type.

I'm using the latest version from the master branch.

URL of my yaml file (work in progress): https://api.riffyn.com/v1/docs

##### Command line example

```cli
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i https://api.riffyn.com/v1/docs \
   -l html2 \
   -o output/riffyn/clients/html2
```

### Suggested Fix

`/modules/swagger-codegen/src/resources/htmlDocs2/index.mustache` line 269

**Current**
```html
curl -X <span style="text-transform: uppercase;">{{httpMethod}}</span> -H "apiKey: [[apiKey]]" -H "apiSecret: [[apiSecret]]" "{{basePath}}{{path}}{{#hasQueryParams}}?{{#queryParams}}{{^-first}}&{{/-first}}{{paramName}}={{vendorExtensions.x-eg}}{{/queryParams}}{{/hasQueryParams}}"
```

**Suggested**
```html
curl -X <span style="text-transform: uppercase;">{{httpMethod}}</span>{{#authMethods}}{{#isApiKey}}{{#isKeyInHeader}} -H "{{keyParamName}}: [[apiKey]]" {{/isKeyInHeader}}{{/isApiKey}}{{#isBasic}} -H "Authorization: Basic [[basicHash]]" {{/isBasic}}{{/authMethods}} "{{basePath}}{{path}}{{#hasQueryParams}}?{{#queryParams}}{{^-first}}&{{/-first}}{{paramName}}={{vendorExtensions.x-eg}}{{/queryParams}}{{/hasQueryParams}}"
```

I've applied this fix to a local copy of the code pushed the generated html to https://api.riffyn.com

**Comment by wing328** [comment]
@bshamblen thanks for reporting the issue. Do you mind filing a PR for the fix so that the credit goes back to you?

**Comment by wing328** [comment]
PR merged into master. Thanks for the contribution.
