### ISSUE TITLE
[JAVA] Error for Apache NiFi swagger.json

### ISSUE THREAD

**Issue by simplesteph** [swagger-api/swagger-codegen#3976]
##### Description

I generated the swagger.json from the Apache NiFi project https://github.com/apache/nifi (just build it), and fed it to swagger-codegen. It mostly work but some parsing error happened. 
##### Swagger-codegen version

latest / master
##### Swagger declaration file content or url

https://gist.github.com/simplesteph/d0bc5d65f7383e69f03c730b32b2206a
##### Command line used for generation

Doesn't work for either java or python so it may be a "higher" bug

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/projects/github/nifi/swagger.json -l java -o ~/projects/github/nifi-sdk/java
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/projects/github/nifi/swagger.json -l python -o ~/projects/github/nifi-sdk/python
```
##### Steps to reproduce

Download the swagger.json and run the code above (just modify the file locations)
##### Suggest a Fix

Log attached here:
https://gist.github.com/simplesteph/389be520a55cc82a8e64edc5aa508944

**Comment by wing328** [comment]
It seems like the Swagger/OpenAPI [spec](https://gist.githubusercontent.com/simplesteph/d0bc5d65f7383e69f03c730b32b2206a/raw/a14b5f7805091463c5e95ffe1675cb4c1412448f/swagger.json) for Apache NiFi has issues. Please open it with https://editor.swagger.io to review errors

**Comment by simplesteph** [comment]
"type" : "ref" creates a lot of issues. It is related to https://github.com/kongchen/swagger-maven-plugin/issues/141 so I updated the plugin version and that fixed these issues.

Updated gist: https://gist.github.com/simplesteph/97ba4bc15761b578781fffd0b45180ee
Now, not sure if important, the swagger-codegen plugin works fine without errors, but the editor still shows errors such as:

```
Swagger Error
Security definition could not be resolved: Read Source - /{component-type}/{uuid}
Jump to line 280
Details
 Object
code:  "UNRESOLVABLE_REFERENCE"
message: "Security definition could not be resolved: Read Source - /{component-type}/{uuid}"
 path: Array [6]
0:  "paths"
1:  "/connections/{id}"
2:  "get"
3:  "security"
4:  "0"
5:  "Read Source - /{component-type}/{uuid}"
level: 900
type:  "Swagger Error"
description: "Security definition could not be resolved: Read Source - /{component-type}/{uuid}"
lineNumber: 280
✖ Swagger Error
Security definition could not be resolved: Read Destination - /{component-type}/{uuid}
Jump to line 281
Details
 Object
code:  "UNRESOLVABLE_REFERENCE"
message: "Security definition could not be resolved: Read Destination - /{component-type}/{uuid}"
 path: Array [6]
0:  "paths"
1:  "/connections/{id}"
2:  "get"
3:  "security"
4:  "1"
5:  "Read Destination - /{component-type}/{uuid}"
level: 900
type:  "Swagger Error"
description: "Security definition could not be resolved: Read Destination - /{component-type}/{uuid}"
lineNumber: 281
```
