### ISSUE TITLE
[C#] Pass properties using a `.properties` file instead paramaters

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#3993]
##### Description

I've took a look on [here](http://docs.virtocommerce.com/display/vc2devguide/How+to+generate+module+API+C%23+client) in order to feed myself acoording how to specifiy options on my `"codegen -l csharp"` generator.

I'd like to use a `.properties` file instead of `-Doption`. Is it possible?

##### Swagger-codegen version

2.3.0

##### Command line used for generation

    java -jar swagger-codegen-cli.jar generate -i http://localhost:8082/commty/cmng/swagger.json -l csharp -v

**Comment by wing328** [comment]
Instead of using -Doption, you can use -c to specify a JSON file which contains the option. Do a search for "-c" in the README should show you an example.

**Comment by jeusdi** [comment]
Thanks @wing328 , I've tested it and it works fine.

Nevertheless, let me ask you for how to get the specific options of each language. I've tested with `ava -jar swagger-codegen-cli.jar config-help -l csharp` and it dumps me nothing. Am I doing something wrong?

**Comment by jeusdi** [comment]
Thanks @wing328 . I've just tested a bit with it. In order to be able to get a list of specific options of `csharp` language, I've performed: `java -jar swagger-codegen-cli.jar config-help -l csharp`. It dumps me:

```
CONFIG OPTIONS
        packageName
            C# package name (convention: Title.Case). (Default: IO.Swagger)

        packageVersion
            C# package version. (Default: 1.0.0)

        sourceFolder
            source folder for generated code (Default: src)

        packageGuid
            The GUID that will be associated with the C# project

        targetFramework
            The target .NET framework version. (Default: v4.5)
                v3.5 - .NET Framework 3.5 compatible
                v4.5 - .NET Framework 4.5+ compatible
                uwp - Universal Windows Platform - beta support

        hideGenerationTimestamp
            Hides the generation timestamp. (Default: true)

        sortParamsByRequiredFlag
            Sort method arguments to place required parameters before optional parameters. (Default: true)

        useDateTimeOffset
            Use DateTimeOffset to model date-time properties (Default: false)

        useCollection
            Deserialize array types to Collection<T> instead of List<T>. (Default: false)

        returnICollection
            Return ICollection<T> instead of the concrete type. (Default: false)

        optionalMethodArgument
            C# Optional method argument, e.g. void square(int x=10) (.net 4.0+ only). (Default: true)

        optionalAssemblyInfo
            Generate AssemblyInfo.cs. (Default: true)

        optionalProjectFile
            Generate {PackageName}.csproj. (Default: true)

        optionalEmitDefaultValues
            Set DataMember's EmitDefaultValue. (Default: false)

        generatePropertyChanged
            Specifies a AssemblyDescription for the .NET Framework global assembly attributes stored in the AssemblyInfo file. (Default: false)
```

I would like to set:

 1.  SolutionName.
 2. ProjectName.
 3. Avoid Test project generation.

I've tested with this options:

```
{
	"packageName": "FEST",
        "excludeTests": true,
	"targetFramework": "v4.5.2",
	"optionalSolutionFile": false,
	"optionalSupportingFiles": false,
	"sourceFolder": ".",
	"invokerPackage": "CEST",
	"modelPackage": "Model",
	"apiPackage": "Api",
	"groupId": "com.living",
        "artifactId": "living-service-specs",
        "artifactVersion": "1.0.0"
}
```

According to last page reference I've written down on first post, it has to exist properties like `excludeTests`, or `optionalSolutionFile` which aren't on `config-help options list`.

How could I set a solution name for solution file, or exclude codegen generates me Tests project?

**Comment by jimschubert** [comment]
I looked at this. Looks like CSharpClientCodegen now only explicitly sets the following in `processOpts`:

```
apiPackage = "Api";
modelPackage = "Model";
clientPackage = "Client";
```

This should be set in the constructor because they're pulled from the `additionalProperties` in the abstract base class.

Model and api tests files were added at some point outside the `excludeTests` check, so all you were getting for `excludeTests` was exclusion of the nuget package config and the csproj.

@jeusdi you have a few issues with your test config file. Specifically, the following should be in an object called `additionalProperties`:

```
"targetFramework": "v4.5.2",
"excludeTests": true,
"optionalSolutionFile": false,
"optionalSupportingFiles": false,
```

Also, `v4.5.2` is not currently a target framework supported by the C# generator. See the options in the output you posted:

        targetFramework
            The target .NET framework version. (Default: v4.5)
                v3.5 - .NET Framework 3.5 compatible
                v4.5 - .NET Framework 4.5+ compatible
                uwp - Universal Windows Platform - beta support

You'll want 4.5. If you explicitly need 4.5.2, that would be a simple code addition if you want to open a PR (I intentionally made adding those options simple here).

Also, I don't know if this is relevant, but your `1.0.0` in your config is not the version that will be used in your C# client's AssemblyInfo. For that, you'll want `packageVersion` instead.

Here's an example of what the config _should_ look like:

```
{
    "packageName": "FEST",
    "invokerPackage": "CEST",
    "additionalProperties": {
        "modelPackage": "MyModels",
        "apiPackage": "MyApi",
        "excludeTests": true,
        "targetFramework": "v4.5",
        "optionalSolutionFile": false,
        "optionalSupportingFiles": false
    },
    "groupId": "com.living",
    "artifactId": "living-service-specs",
    "packageVersion": "9.9.9"
}
```

That said, there are a few other issues I've found while investigating your bug report. I will have a PR available in a bit for you to test out.

**Comment by jimschubert** [comment]
@jeusdi @wing328 I've submitted PR #4010 to address this issue.

**Comment by wing328** [comment]
PR merged into master. Please pull the latest master to give it a try.
