### ISSUE TITLE
What repository should I use to get the latest SNAPSHOT version (2.2.2-SNAPSHOT) ?

### ISSUE THREAD

**Issue by prakashmrec** [swagger-api/swagger-codegen#3997]
According to pom file, https://oss.sonatype.org/content/repositories/snapshots/ should have the snapshot version but that contains very old SNAPSHOT (https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen/2.2.2-SNAPSHOT/).

Is the SNAPSHOT version deployed somewhere when a new commit is pushed to 'master' branch ?

**Comment by wing328** [comment]
SNAPSHOT version is not published. You can build and install locally: `mvn clean install`

**Comment by prakashmrec** [comment]
Ok, thanks. I will build it locally.
