### ISSUE TITLE
[typescript-angular2] response headers not accessible

### ISSUE THREAD

**Issue by damienpontifex** [swagger-api/swagger-codegen#3999]
##### Description

When using the generated api classes with the typescript-angular2 generator, there isn't a way to access the response headers. Here [angular2/api.mustache#L44-L53](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L44-L53) is where the response serialises and returns the json body, and it would also be here that we would access the `response.headers` property. 

I think returning the data object is right here as it's the most common use case. Maybe there's an RxJS way to return multiple objects that I'm not aware of or another method that may be suggested for the json body and headers to be returned if the developer is interested.
##### Swagger-codegen version

2.2.1
##### Suggest a Fix

Haven't come up with a solution yet, but putting it out to the community and seeing if someone can. I'm happy to make the change/contribution, but unaware how it might be achieved just yet.

**Comment by wing328** [comment]
@damienpontifex for other API clients (e.g. ruby, python, php, etc), there's an additional method "_with_http_info" to return data (deserialized), http status code and http headers: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/ruby/lib/petstore/api/pet_api.rb#L39-L88

For Typescript API client, we can do something similar.

**Comment by damienpontifex** [comment]
@wing328 I was just looking at doing this, but it seems with latest master I think this is now done with #3760 is that correct?

**Comment by wing328** [comment]
@damienpontifex yes, that's correct. Please pull the latest master to give it a try.
