### ISSUE TITLE
Swift 3 Code Generation is outputting an old version

### ISSUE THREAD

**Issue by enagy27** [swagger-api/swagger-codegen#4012]
I had been following along with the Swift3 code generation before it was released and had everything working ok (before the swift3 flag was introduced). However, now it seems that when I run code generation using the Swift3 flag it outputs none of the expected changes. Verbose output shows that it is attempting to use the Swift3 code generation (with promise kit), but the output is still full of types such as NSUUID.

Command used:
`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ../OperatorSoftware/test.json -l swift3 -o ../swift-client --additional-properties usePromiseKit=true`

**Comment by wing328** [comment]
We just fixed it via https://github.com/swagger-api/swagger-codegen/pull/4013.

Can you please pull the latest master to give it a try?

**Comment by enagy27** [comment]
Yes, that did the trick, thank you!
