### ISSUE TITLE
Avoid to generate unnecessary artifacts

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#4016]
##### Description

When I perform `swagger codegen`, it generates me several files I'd like to avoid to. For example, it generates an `git_push.sh`, an `build.bat`, an `build.sh`, and `travis.yml` and so on.

How could I set it generates me only what I need?

I'm generating a CSharp client.

##### Swagger-codegen version

2.2.2

**Comment by wing328** [comment]
You can leverage `.swagger-codegen-ignore` file to skip files that you don't want to generate.

**Comment by jeusdi** [comment]
Is there some documentation or some stuff code about how to get it?

**Comment by wing328** [comment]
.swagger-codegen-ignore is also generated if it's not already present in the output directory and it contains some comments explaining its usage. It works like [.gitignore](https://git-scm.com/docs/gitignore))

To skip git_push.sh, just put git_push.sh in that file.

**Comment by wing328** [comment]
FAQ: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-to-skip-certain-files-during-code-generation
