### ISSUE TITLE
[PYTHON] refs to arrays in editor/codegen potential differences

### ISSUE THREAD

**Issue by FodT** [swagger-api/swagger-codegen#4018]
##### Description

Modeling a response using [this](https://www.irccloud.com/pastebin/OWxbqAoc/) yaml to model a response which looks like [this](http://pastebin.com/xSchfqD4) results in `data` coming back as an empty object/dict, rather than the expected array of entities.  
Changing `multiResponse` to define `data` as type array of `organizations` as below results in the response being correctly mapped. 
```multiResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/arrayOfEntities'
      meta:
        $ref: '#/definitions/meta'
```

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

https://www.irccloud.com/pastebin/OWxbqAoc/ original yaml - models http://pastebin.com/xSchfqD4

##### Suggest a Fix

I'm not even sure it's actually a bug - the editor renders the two yaml files a little differently, albiet a little unintuitively
first yaml:
![first](http://i.imgur.com/1daPuZB.png)
fixed:
![fixed](http://i.imgur.com/LFet5du.png)

**Comment by wing328** [comment]
```
      responses:
        '200':
          description: A list of Organizations
          schema:
            $ref: '#/definitions/multiResponse'
```
You need to revise the `responses` to return an array of `multiResponse` instead of just `multiResponse` (as shown above). Please refer to the following as an example:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L111-L117

**Comment by fehguy** [comment]
I think this can be closed, per @wing328 's advice
