### ISSUE TITLE
Create tests for python client generator

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#402]
per https://github.com/swagger-api/swagger-codegen/pull/397

**Comment by geekerzp** [comment]
hi @fehguy @webron python unit tests has been added in this pr https://github.com/swagger-api/swagger-codegen/pull/680.
Please have a look.

**Comment by webron** [comment]
Thanks for the note, @geekerzp. If @fehguy finds it provides enough coverage, I'm sure he'll close the issue.

**Comment by wing328** [comment]
Closing this as the unit tests have been added.
