### ISSUE TITLE
packageName and invokerPackage properties roles in csharp language

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#4020]
##### Description

Which is the output according these property values (or any others) using csharp language?
I don't quite get it.

```
"packageName": "Client",
"invokerPackage": "CEST",
```

Currently, it's generating me a `Client.csproj` file. I thought `invokerPackage` was the `"namespace"` used in each file. Nevertheless, each `api-like.cs` and the other generated classes has a `namespace Client.Client` or `Client.Api`.

As far I've been able to figure out it, it should be `namespace CEST.Client`, isn't it?

Is it possible that `"invokerPackage"` is ignored?
##### Swagger-codegen version

2.2.2

**Comment by wing328** [comment]
```
swagger-codegen|master⚡ ⇒ grep -R invokerPackage modules/swagger-codegen/src/main/resources/csharp/* 
swagger-codegen|master⚡ ⇒ 
```
You're correct in saying that `invokerPackage` is not used in C# mustache template.

**Comment by jimschubert** [comment]
It's interesting. I looked at the differences between `invokerPackage` and `packageName`. It looks like there was some confusion about what `invokerPackage` was when the C# generator was originally written.  Maybe there was a conscious effort to _not_ use `invokerPackage`? I don't know.

Would a simple fix be to prefer `packageName` in `AbstractCSharpCodegen`, and set packageName to the value provided in `invokerPackage` if it's set?

Something like this:

        // {{packageName}}
        if (additionalProperties.containsKey(CodegenConstants.PACKAGE_NAME)) {
            setPackageName((String) additionalProperties.get(CodegenConstants.PACKAGE_NAME));
        } else {
            additionalProperties.put(CodegenConstants.PACKAGE_NAME, packageName);
        }

        // NEW CODE:
        if (additionalProperties.containsKey(CodegenConstants.INVOKER_PACKAGE)) {
            setPackageName((String) additionalProperties.get(CodegenConstants.INVOKER_PACKAGE));
            additionalProperties.put(CodegenConstants.PACKAGE_NAME, packageName);
            
            LOGGER.warn("invokerPackage now overrides packageName");
        }
