### ISSUE TITLE
Vendor Extensions are not available CodegenResponse

### ISSUE THREAD

**Issue by RaphC** [swagger-api/swagger-codegen#4022]
##### Description

Hi,

OpenAPis specifies it is possible to define vendorExtension on Response object (CodegenResponse) but the class CodegenResponse doesn't support it. Is there any enhancement planned for this feature?

Here is the link on OpenAPI documentation

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject
##### Swagger-codegen version

2.2.1
##### Suggest a Fix

copy vendorExtensions from Response to CodegenResponse.

**Comment by wing328** [comment]
@RaphC thanks for reporting the issue. May I know if you've time to contribute the enhancement?

**Comment by wing328** [comment]
@RaphC I can show you some good starting points if you want to work on this.

**Comment by RaphC** [comment]
@wing328 : let me know how I have to do.

Thanks.

**Comment by wing328** [comment]
@RaphC I might have some time to work on this tomorrow. Will keep you posted.

**Comment by arr28** [comment]
It isn't just the OpenAPI spec. that allows vendor extensions here.  The Swagger spec. does too.

@wing328: If you can give me some pointers, I expect to have time to look at this early next week.

**Comment by sreeshas** [comment]
Hey @arr28 Do you mind if i take this bug? I think i have the solution. Ill publish it in a day or two.

**Comment by arr28** [comment]
@sreeshas: Sure - I'll need it early next week, but it sounds like you're expecting to have it done by then, in which case, I'm very happy for you to take it.  If you find that you aren't able to sort it out in that timescale, any pointers would be gratefully received.

**Comment by sreeshas** [comment]
@arr28 @wing328  PR #4517 has the fix.

**Comment by arr28** [comment]
Thanks @sreeshas.  This gets me part-way towards what I need.  Unfortunately, when vendor extensions in responses refer to other YAML fragments (with `$ref:`), the references aren't being followed so I have no access to the referenced objects in the mustache templates.  Since I doubt this is specific to vendor references **in responses**, I've raised #4527 as a new issue.

**Comment by wing328** [comment]
@arr28 agreed with you that it's a different issue. Thanks for opening a new one for tracking.

Thanks for the PR from @sreeshas. Closing this issue.

**Comment by RaphC** [comment]
Thanks @sreeshas
