### ISSUE TITLE
[TYPESCRIPT] typescript-fetch cannot pass fetch specific request options

### ISSUE THREAD

**Issue by alechill** [swagger-api/swagger-codegen#4025]
##### Description

Through the current fetch api template the fetch options is created internally by declaring simply the request method, and appended to in special cases such as headers/body/file etc. These cases not however exhaustive, and a bunch of request options in the spec (https://fetch.spec.whatwg.org/#concept-request) that may need be supplied are not accounted for. 

For example, cookies are not automatically sent via fetch api, and must instead have the `{ credentials: 'include' }` option set to inform it to do so.
##### Swagger-codegen version

2.2.1 (not a regression)
##### Suggest a Fix

Allow passing in custom request options which are `assign`ed to the fetch options at their point of creation, so that any of the already accounted for special cases are not overridden. This is flexible enough to encompass all use cases in a single implementation, and can be done so without breaking backwards compatibility

**Comment by taxpon** [comment]
@alechill @wing328 I think this issue can be closed

**Comment by wing328** [comment]
@taxpon thanks for reviewing (and sorry I missed your message)
