### ISSUE TITLE
Allow specifying API suffix in config

### ISSUE THREAD

**Issue by dcbroad3** [swagger-api/swagger-codegen#4028]
Working on generating a typescript/angular2 library using swagger-codegen. I note that it is hard-coded that Api files have "Api" appended to the name. In angular/angular2, these are definitely called Services, so "ThingApi" should be "ThingService." I note that for models it's possible to specify a prefix and suffix, but for api's the suffix is hard-coded. Could you expose an apiNameSuffix option in the config so that this could be changed? I've been able to make this change locally without too much trouble by basically copy/pasting the code for modelNameSuffix, and using it in place of the hard-coded value.

**Comment by wing328** [comment]
Agreed with you that some people may want to name the Api files differently (e.g. with Service suffix).

As a workaround, you can modify [TypeScriptAngular2ClientCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java) to overrride the following methods so as to customize the Api file name and class name:
```
    String toApiFilename(String name);
    String toApiName(String name);
```

If you've cycle to contribute the enhancement for Api suffix/prefix, let me know and I'll show you a PR as a starting point.

**Comment by dcbroad3** [comment]
https://github.com/dcbroad3/swagger-codegen/ is ready for a PR.

**Comment by wing328** [comment]
@dcbroad3 thanks! Please submit a PR and we'll review the change.
