### ISSUE TITLE
How to generate input json for generate client

### ISSUE THREAD

**Issue by balamanian** [swagger-api/swagger-codegen#403]
Hi All,
          I am newbie to swagger-cliengen tool. Please guide me to generate the client.

   first, i have done api generate json by swagger-doclet document generate tool. now i want to generate the client by using swagger-clientgen tool.By analyzing, i found,  it has different JSON format for document generation and client generation too. So please guide me to generate the JSON which will use for client generation like with below way 

java -cp .\target\*;.\target\lib\* com.wordnik.swagger.codegen.Codegen -i http://localhost:18080/swagger-sample/apidocs/sampleresource.json  -l java -o samples/client/sampleresource/java

By using swagger-doculet it will generate the below, for sample, i have only one rest resource class.
service.json (main api json)
```json
{
  "swaggerVersion" : "1.2",
  "apiVersion" : "1.0",
  "basePath" : "http://localhost:18080/swagger-sample/apidocs",
  "apis" : [ {
    "path" : "/sampleresource.{format}"
  } ]
}

{
  "apiVersion" : "1.0",
  "swaggerVersion" : "1.2",
  "basePath" : "http://localhost:18080/swagger-sample/rest",
  "resourcePath" : "/sampleresource",
  "apis" : [ {
    "path" : "/sampleresource",
    "description" : "this is test",
    "operations" : [ {
      "method" : "POST",
      "nickname" : "createResource",
      "type" : "Response",
      "parameters" : [ {
        "type" : "Resource",
        "paramType" : "body",
        "name" : "resource",
        "required" : true
      } ],
      "consumes" : [ "application/xml", "application/json" ],
      "produces" : [ "application/xml", "application/json" ]
    }, {
      "method" : "GET",
      "nickname" : "search",
      "type" : "Resource",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "query",
        "name" : "url"
      } ],
      "produces" : [ "application/xml", "application/json" ]
    } ]
  }, {
    "path" : "/sampleresource/all",
    "description" : "this is test",
    "operations" : [ {
      "method" : "GET",
      "nickname" : "getResources",
      "type" : "array",
      "produces" : [ "application/xml", "application/json" ]
    } ]
  }, {
    "path" : "/sampleresource/{name}",
    "description" : "this is test",
    "operations" : [ {
      "method" : "GET",
      "nickname" : "getResourceByName",
      "type" : "Response",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "path",
        "name" : "name",
        "required" : true
      } ],
      "produces" : [ "application/xml", "application/json" ]
    }, {
      "method" : "POST",
      "nickname" : "updateResource",
      "type" : "void",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "path",
        "name" : "name",
        "required" : true
      }, {
        "type" : "Resource",
        "paramType" : "body",
        "name" : "resource",
        "required" : true
      } ],
      "consumes" : [ "application/xml", "application/json" ],
      "produces" : [ "application/xml", "application/json" ]
    } ]
  } ],
  "models" : {
    "Resource" : {
      "id" : "Resource",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "url" : {
          "type" : "string"
        }
      }
    }
  }
}
```
But For client document generation it has different format, there a tool to generate the JSON which will use by swagger-clientgen tool.

Please guide me. thanks

**Comment by fehguy** [comment]
Hi, this should be fine.  the codegen tool will convert from your format (1.2) into the most recent (2.0) automatically.  Give it a shot and post back how it works.

**Comment by balamanian** [comment]
Hi, 
     If i tried to create a client using swagger-clientgen with following sampleresource.json. below is the output from console. Please validate it.

C:\Users\Downloads\swagger\code_gen\swagger-codegen-develop_2.0\swagger-codegen-develop_2.0>java -cp .\target\*;.\target\lib\* com.wordnik.swagger.codegen.Codegen -i http://localhost:18080/swagger-sample/apidocs/sampleresource.json  -l java -o samples/client/sampleresource/java
reading from http://localhost:18080/swagger-sample/apidocs/sampleresource.json
writing file samples/client/sampleresource/java\pom.xml
writing file samples/client/sampleresource/java\src/main/java\com\wordnik\client\ApiInvoker.java
writing file samples/client/sampleresource/java\src/main/java\com\wordnik\client\JsonUtil.java
writing file samples/client/sampleresource/java\src/main/java\com\wordnik\client\ApiException.java

C:\Users\Downloads\swagger\code_gen\swagger-codegen-develop_2.0\swagger-codegen-develop_2.0>

Below is the JSON Input for the above code.
{
  "apiVersion" : "1.0",
  "swaggerVersion" : "1.2",
  "basePath" : "http://localhost:18080/swagger-sample/rest",
  "resourcePath" : "/sampleresource",
  "apis" : [ {
    "path" : "/sampleresource",
    "description" : "this is test",
    "operations" : [ {
      "method" : "POST",
      "nickname" : "createResource",
      "type" : "Response",
      "parameters" : [ {
        "type" : "Resource",
        "paramType" : "body",
        "name" : "resource",
        "required" : true
      } ],
      "consumes" : [ "application/xml", "application/json" ],
      "produces" : [ "application/xml", "application/json" ]
    }, {
      "method" : "GET",
      "nickname" : "search",
      "type" : "Resource",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "query",
        "name" : "url"
      } ],
      "produces" : [ "application/xml", "application/json" ]
    } ]
  }, {
    "path" : "/sampleresource/all",
    "description" : "this is test",
    "operations" : [ {
      "method" : "GET",
      "nickname" : "getResources",
      "type" : "array",
      "produces" : [ "application/xml", "application/json" ]
    } ]
  }, {
    "path" : "/sampleresource/{name}",
    "description" : "this is test",
    "operations" : [ {
      "method" : "GET",
      "nickname" : "getResourceByName",
      "type" : "Response",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "path",
        "name" : "name",
        "required" : true
      } ],
      "produces" : [ "application/xml", "application/json" ]
    }, {
      "method" : "POST",
      "nickname" : "updateResource",
      "type" : "void",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "path",
        "name" : "name",
        "required" : true
      }, {
        "type" : "Resource",
        "paramType" : "body",
        "name" : "resource",
        "required" : true
      } ],
      "consumes" : [ "application/xml", "application/json" ],
      "produces" : [ "application/xml", "application/json" ]
    } ]
  } ],
  "models" : {
    "Resource" : {
      "id" : "Resource",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "url" : {
          "type" : "string"
        }
      }
    }
  }
}

With Sample come-up with swagger codegen, for the given uri http://petstore.swagger.wordnik.com/v2/swagger.json. it has different format JSON for client generation. Please guide me, how to generate the JSON format for swagger clientgen tool

**Comment by balamanian** [comment]
Any update on handling swagger codegen 1.2 version with swager codegen 2.0. Please guide me, if you did in wrong way... thanks

**Comment by fehguy** [comment]
You have a couple errors in your sample JSON, namely missing some `required=false` markers on your parameters, and the inner type of your array response.  See here for updated JSON, it builds the java client just fine with develop_2.0:

```json
{
  "apiVersion" : "1.0",
  "swaggerVersion" : "1.2",
  "basePath" : "http://localhost:18080/swagger-sample/rest",
  "resourcePath" : "/sampleresource",
  "apis" : [ {
    "path" : "/sampleresource",
    "description" : "this is test",
    "operations" : [ {
      "method" : "POST",
      "nickname" : "createResource",
      "type" : "Resource",
      "parameters" : [ {
        "type" : "Resource",
        "paramType" : "body",
        "name" : "resource",
        "required" : true
      } ],
      "consumes" : [ "application/xml", "application/json" ],
      "produces" : [ "application/xml", "application/json" ]
    }, {
      "method" : "GET",
      "nickname" : "search",
      "type" : "Resource",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "query",
        "name" : "url",
        "required": false
      } ],
      "produces" : [ "application/xml", "application/json" ]
    } ]
  }, {
    "path" : "/sampleresource/all",
    "description" : "this is test",
    "operations" : [ {
      "method" : "GET",
      "nickname" : "getResources",
      "type" : "array",
      "items": {
        "$ref": "Resource"
      },
      "produces" : [ "application/xml", "application/json" ],
      "parameters": []
    } ]
  }, {
    "path" : "/sampleresource/{name}",
    "description" : "this is test",
    "operations" : [ {
      "method" : "GET",
      "nickname" : "getResourceByName",
      "type" : "Resource",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "path",
        "name" : "name",
        "required" : true
      } ],
      "produces" : [ "application/xml", "application/json" ]
    }, {
      "method" : "POST",
      "nickname" : "updateResource",
      "parameters" : [ {
        "type" : "string",
        "paramType" : "path",
        "name" : "name",
        "required" : true
      }, {
        "type" : "Resource",
        "paramType" : "body",
        "name" : "resource",
        "required" : true
      } ],
      "consumes" : [ "application/xml", "application/json" ],
      "produces" : [ "application/xml", "application/json" ]
    } ]
  } ],
  "models" : {
    "Resource" : {
      "id" : "Resource",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "url" : {
          "type" : "string"
        }
      }
    }
  }
}

```

**Comment by fehguy** [comment]
Hi, please reopen if you're still having issues with this.
