### ISSUE TITLE
[ALL] lack of recieving file response support

### ISSUE THREAD

**Issue by www2k** [swagger-api/swagger-codegen#4034]
##### Description

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject

`Response Object`'s schema can be a single file type.
But swagger-codegen does not support it.

https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java
https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenResponse.java
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java

`CodegenOperation` has `isResponseBinary` but does not `isResponseFile`.
`CodegenResponse` has `isBinary` but does not `isFile`.
`CodegenProperty` has `isBinary` but does not `isFile`.

https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L1892-L1894

Therefore swagger-codegen supports binary response but does not file response.
##### Swagger-codegen version

swagger-codegen 2.2.1 or above
##### Swagger declaration file content or url

``` yaml
swagger: '2.0'
info:
  title: File Response Api
  version: "1.0.0"
paths:
  /file:
    get:
      summary: File
      description: Produces File
      parameters:
        - name: id
          in: query
          description: file id
          required: true
          type: number
          format: int32
      produces:
        - application/octet-stream
      responses:
        200:
          description: An array of products
          schema:
            type: file
```
##### Suggest a Fix

We should add relevant properties and some code flagments.

Thanks.

**Comment by wing328** [comment]
@www2k thanks for the suggestion. I think it's reasonable to add those additional mustache tags for `file`.

May I know if you've time to contribute the enhancements?

**Comment by www2k** [comment]
I will do it soon :)
