### ISSUE TITLE
Swagger Code Gen Failing On Swagger 1.2 Format

### ISSUE THREAD

**Issue by josephmisiti** [swagger-api/swagger-codegen#404]
```
base path is http://developers.vestorly.com/api-docs/
********* Failed to read swagger json!
ValidationError(articles:api/articles:get,responseClass is required,ERROR)
ValidationError(articles:api/articles/{id}:get,responseClass is required,ERROR)
ValidationError(articles:api/articles/{id}:put,responseClass is required,ERROR)
ValidationError(posts:api/posts:get,responseClass is required,ERROR)
ValidationError(posts:api/posts:post,responseClass is required,ERROR)
ValidationError(posts:api/posts/{id}:get,responseClass is required,ERROR)
ValidationError(posts:api/posts/{id}:put,responseClass is required,ERROR)
ValidationError(posts:api/posts/{id}:delete,responseClass is required,ERROR)
ValidationError(sources:api/sources:get,responseClass is required,ERROR)
ValidationError(sources:api/sources:post,responseClass is required,ERROR)
ValidationError(sources:api/sources/{id}:get,responseClass is required,ERROR)
ValidationError(sources:api/sources/{id}:put,responseClass is required,ERROR)
ValidationError(groups:api/groups:get,responseClass is required,ERROR)
```

I do not believe this `responseClass` is documented, but I tried to insert it in multiple places in the JSON and the validation is still failing. Any ideas ?

**Comment by webron** [comment]
The error is misleading.

Do you use the master version or the develop_2.0?

**Comment by okolehao** [comment]
@josephmisiti is using master

**Comment by webron** [comment]
Okay. Can you share the JSON of at least one of the operations that produces that error? That would help in isolating it.

Also, what library is used to produce the spec?

**Comment by josephmisiti** [comment]
swagger-docs was used to create the json. i need to get permission to send the json over but ill email it to your address in github

**Comment by webron** [comment]
Sure thing, that email would work great.

**Comment by josephmisiti** [comment]
@webron sent you the email to ron@swagger.io - thanks

**Comment by webron** [comment]
Is what you shared me the output of swagger-docs or did you manually change the output?

**Comment by josephmisiti** [comment]
i changed the directory structure to mimick examples that work. i did add `responseClass` to to articles.json but still got that output

**Comment by webron** [comment]
Yeah, the responseClass shouldn't be there. Can you revert the changes so I can see the original please?

**Comment by josephmisiti** [comment]
i just regenerated everything and copied it over

**Comment by webron** [comment]
Okay, so it looks like the output is definitely malformed. The codegen can deal with some malformations (such as the httpMethod being lowercase and not uppercase), but it can't deal with others. 

In this case, your operations miss the `type` property which is the return type of the operation (even if there's no return value, the value of the property needs to be `"void"`). In older versions of swagger, that was called the `responseClass` and the error message hasn't updated.

Adding the `type` property to all the operations should resolve the issues above.

**Comment by josephmisiti** [comment]
the error was created using

```
./bin/runscala.sh com.wordnik.swagger.codegen.BasicScalaGenerator http://developers.XXXXX.com/api-docs/
```

**Comment by webron** [comment]
That doesn't really change the answer... :)

**Comment by josephmisiti** [comment]
ok thanks for the info - do you know if `swagger-docs` can be configured to do that ?

**Comment by webron** [comment]
Unfortunately, I don't know. It's a community library but you can check its issues.

You can also check the alternatives to see if one would work better for you - https://github.com/swagger-api/swagger-spec#ruby

**Comment by josephmisiti** [comment]
thanks @webron !

**Comment by fehguy** [comment]
well @josephmisiti you do have two other options.  (1) You can pull the develop_2.0 branch of codegen, it's much more robust.  (2) you can save the JSON from the server to files, and "fix" anything in it.  The codegen can read from the filesystem all the same.

I'd personally start with 1, and move to 2

**Comment by webron** [comment]
@fehguy - will develop_2 detect no return type as void?

**Comment by josephmisiti** [comment]
@fehguy - i tracked down the first part of the issue a second ago:

https://github.com/swagger-api/swagger-codegen/issues/404

**Comment by fehguy** [comment]
i actually think it might.

**Comment by josephmisiti** [comment]
ill try now.

**Comment by josephmisiti** [comment]
@webron @fehguy - unless there was something else wrong with my json, it appears `develop_2` does not do this still

**Comment by webron** [comment]
What about the `type` field of the operations to declare the return type of the operation?

**Comment by josephmisiti** [comment]
@webron was that directed to me ?

**Comment by fehguy** [comment]
I can look at the json if you send it to me

**Comment by webron** [comment]
@josephmisiti, yup, after all we're trying to help you here ;-)

**Comment by webron** [comment]
Also congrats on opening #404 though I hope the answer **will** be found.

**Comment by josephmisiti** [comment]
@fehguy just sent it to your gmail account
