### ISSUE TITLE
[JAXRS-CXF] Lowercase enums sent as uppercase

### ISSUE THREAD

**Issue by markus-wa** [swagger-api/swagger-codegen#4045]
##### Description

When sending enums with lowercase 'value' attributes the uppercase enum name seems to be sent instead.
##### Swagger-codegen version

2.2.2-SNAPSHOT
##### Swagger declaration file content or url

http://petstore.swagger.io/v2/swagger.json
##### Command line used for generation

java -jar swagger2java/swagger-codegen-cli-2.2.2-SNAPSHOT.jar generate -i swagger.json -c config.json -l jaxrs-cxf -o out
##### Steps to reproduce

Example (petstore Pet.status) - note the lowercase values for the enum:

``` json
"status":{"type":"string","description":"pet status in the store","enum":["available","pending","sold"]}}
```

Generates this enum in the model (https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Pet.java#L44):

``` java
@XmlType(name="StatusEnum")
@XmlEnum
public enum StatusEnum {

    AVAILABLE(String.valueOf("available")), PENDING(String.valueOf("pending")), SOLD(String.valueOf("sold"));


    private String value;

    StatusEnum (String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusEnum fromValue(String v) {
        return valueOf(v);
    }
}
```

Implementation of getPetById():

``` java
    @Override
    public Response getPetById(Long arg0) {
        Pet result = new Pet();
        result.setId(arg0);
        result.setStatus(StatusEnum.AVAILABLE);
        result.setName("Test");
        return Response.ok().entity(result).type(MediaType.APPLICATION_JSON_TYPE).build();
    }
```

Results in uppercase status:

``` json
{
  "id": 5,
  "name": "Test",
  "status": "AVAILABLE"
}
```

The java client then expects a lowercase value (as specified) which results in a null value for status.
##### Suggest a Fix

I assume this happens because the enum's toString() method should be overridden to return the result of value() which isn't done, so it returns the name of the enum, which is uppercase.

**Comment by triptec** [comment]
I think this is a problem in jaxrs-jersey aswell

**Comment by markus-wa** [comment]
While I haven't tested it, neither jersey1 nor jersey2 would be affected if it is indeed just the missing toString() method.

See:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs/jersey1/src/gen/java/io/swagger/model/Pet.java#L52

And
https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/model/Pet.java#L52

**Comment by wing328** [comment]
`spring` (mvc) also has the toString() method: https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Pet.java#L52

so adding back the `toString()` method should fix the issue for `jaxrs-cx` ?

**Comment by triptec** [comment]
Ah sorry, my problem is that if I define enum as lowercase in the spec, the model generated gets uppercased enums like "image" in spec gives IMAGE("image") and if I send enum as lowercase in my call that wont be accepted so I have to change it to image("image") in the model. sorry for the confusion

**Comment by wing328** [comment]
@triptec based on what I know, defining the enum in any convention (lowercase, uppercase, snake_case) should not matter as the model serialization/deserialization should keep the original enum value. Are you suggesting that's not the current behaviour?

**Comment by triptec** [comment]
I think it's the deserialization that has a problem.

How do I show it?

**Comment by wing328** [comment]
I believe you mention you're using `jaxrs-jersey`. To confirm the issue, can you try `spring` as well  to see if the same issue occurs?

**Comment by triptec** [comment]
Yes, but what we are talking about now is another issue yes?

**Comment by wing328** [comment]
I think it's the same deserialization issue.

**Comment by markus-wa** [comment]
@triptec That sounds like a client issue to me. Are you generating the client as well? Or are you using the same model as server-side?

It looks like the CXF model would not be able to read lower case enums as well:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Pet.java#L59
This will attempt to find a enum whith the name 'available' while the name is 'AVAILABLE' instead of one with that value.


Jersey should be able to handle this from what i see:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/jaxrs/jersey2/src/gen/java/io/swagger/model/Pet.java#L57

**Comment by wing328** [comment]
I think the `fromValue` needs to be updated to something like https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/spring-mvc/src/main/java/io/swagger/model/Pet.java#L56-L65

**Comment by markus-wa** [comment]
Yes, that's already the case in Jersey (1 & 2), see at the bottom link. Which is why this seems odd.

But for CXF it's missing.

**Comment by wing328** [comment]
@markus-wa may I know if you've time to contribute the fix to `jaxrs-cxf`?

**Comment by triptec** [comment]
Hmm, I just removed my gen dir, regenerated and it works.. so disregard my earlier comments

**Comment by markus-wa** [comment]
@wing328 I can attempt a fix on monday

**Comment by markus-wa** [comment]
Has someone had time to take a look at my fix yet?

**Comment by wing328** [comment]
@markus-wa I've merged into master. Thanks for the contribution.
