### ISSUE TITLE
branch develop_2.0 - when might it be released?

### ISSUE THREAD

**Issue by billumina** [swagger-api/swagger-codegen#405]
I am pushing to use branch develop_2.0 in an upcoming project.

The biggest concern raised is that the code hasn't been released. Does anyone know when this might be released?

Also once branch develop_2.0 is released will it be able to be added to a maven script to automate the building on some POJOs?

Thanks for any help!

**Comment by webron** [comment]
We're about to make an announcement for the release of M1 support for Swagger 2.0 tomorrow, so a codegen release is relatively soon, though I can't say when.

You can already use the maven script to automate the work.

**Comment by billumina** [comment]
@webron would you mind elaborating on how I could use the maven script to automated the work? maybe point me in the right direction. I'm a .NET guy that's been put on a java project so trying to get up to speed on the inner workings on setting up a java project. Thanks again for a quick response.

**Comment by webron** [comment]
Hmpf, unfortunately the docs currently only cover the master version. @fehguy may get around to documenting that at some point. I'll try looking into it myself, but it may take a few days.

**Comment by billumina** [comment]
@webron thank you
