### ISSUE TITLE
Adding support for string response (text/plain) to CPPREST generator

### ISSUE THREAD

**Issue by plankswert** [swagger-api/swagger-codegen#4058]
##### Description

The generated code for CPPREST when the response is "string" has no support for handling 'text/plain' returns from an API.
##### Swagger-codegen version

Found in 2.2.2-SNAPSHOT
##### Swagger declaration file content or url

``````
```json
"/manifest": {
  "get": {
    "tags": [
      "Common"
    ],
    "summary": "Returns the manifest for the API service",
    "produces": [
      "text/plain"
    ],
    "description": "This resource provides the manifest for the API services found at the base URL.",
    "parameters": [],
    "responses": {
      "200": {
        "description": "Status 200",
        "schema": {
          "type": "string"
        }
      },

```
``````
##### Command line used for generation

java -jar swagger-codegen\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate --lang cpprest --input-spec webapp-swagger\src\main\resources\swagger.json --api-package=com.anyconnect.client.api --model-package=com.anyconnect.client.model
##### Steps to reproduce

Generate code and inspect code. application/json and multipart/form-data are handled. Accept defaults to application/json even when return type is string.
##### Related issues

None found.
##### Suggest a Fix

Fix to follow.

**Comment by wing328** [comment]
PR merged. Thanks for the contribution from @plankswert

**Comment by plankswert** [comment]
Thanks! Hopefully, more to come.
