### ISSUE TITLE
[Java] Support Java 1.6 in generated server stubs

### ISSUE THREAD

**Issue by imgx64** [swagger-api/swagger-codegen#4067]
##### Description

This is similar to issue #3568, but about server stubs. As a result of #3568, `supportJava6` option was added to Java **clients**. This option made the models not use `java.util.Objects`. It's a pretty simple change, and I'm sure it can be applied to server stubs as well.
##### Swagger-codegen version

2.2.2-SNAPSHOT built from git.
##### Swagger declaration file content or url

Doesn't matter, tried with `http://petstore.swagger.io/v2/swagger.json`
##### Command line used for generation

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l spring -o ../petstore-server -DsupportJava6=true
```
##### Steps to reproduce

Run the command above, then look at `src/main/java/io/swagger/model/Category.java`. You'll notice it's using `import java.util.Objects;`.
##### Related issues
#3568, but it only added it to Java **clients**. This issue is for **server stubs**

**Comment by imgx64** [comment]
I tried my hand at fixing this. It seems to be a rather invasive change, modifying many templates in JavaJaxRS, JavaSpring, etc. Would such a PR be accepted? I'll understand if this feature is not wanted. I admit that Java 6 on the server is rather niche these days.

**Comment by wing328** [comment]
@imgx64 Please take a look at https://github.com/swagger-api/swagger-codegen/pull/4064 as someone has already started the work. Please review the PR and share any feedback you've.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/4074
