### ISSUE TITLE
[Android] Generated libraries need to URL Encode String parameters

### ISSUE THREAD

**Issue by sanket0007** [swagger-api/swagger-codegen#4078]
##### Description

If we generate any endpoint for an android client accepting a string parameter, that parameter is never url encoded before sending.

This causes broken urls with spaces if the string contained spaces.
##### Command line used for generation

generated from swagger-editor
##### Steps to reproduce

make any simple endpoint with a simple string parameter. Generate the android client and execute the endpoint. Now observe the invalid URL thats fired.
##### Suggest a Fix

url encode all string parameters of type path or query before actually executing the request.

**Comment by wing328** [comment]
@sanket0007 the issue should have been fixed in the latest master. Please pull the latest master to give it a try.

(editor.swagger.io is using the latest stable version, not the latest master)

**Comment by wing328** [comment]
@sanket0007 closing this as there's no update from you.
