### ISSUE TITLE
html2 generated static client has no response schema if using enum property

### ISSUE THREAD

**Issue by David-Vander-Elst** [swagger-api/swagger-codegen#4081]
##### Description

After a long investigation about why the schema still empty when generating my static html2 documentation, I found that it was only when we have an enum property for some fields...
##### Swagger-codegen version

Current one.
##### Swagger declaration file content or url

**Here is an example of working JSON:**

```
{
  "swagger": "2.0",
  "info": {
    "title": "MyWebsite",
    "description": "MyWebsite API",
    "version": "1.0.0"
  },
  "host": "mywebsite.com",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "basePath": "/",
  "paths": {
    "/apicheck": {
      "get": {
        "summary": "Check the API",
        "description": "test",
        "tags": ["apicheck"],
        "responses": {
          "200": {
            "description": "The API connection succeed",
            "schema": {
              "$ref": "#/definitions/apicheck"
            }
          }
        }
      },
    }
  },

  "definitions": {
    "apicheck": {
      "type": "object",
      "properties": {
        "requestId": {
          "type": "integer",
          "description": "Test"
        },
        "typeResponse": {
          "type": "string",
          "description": "Test"
        }
      }
    }
  }
}
```

**Here is an example of JSON generating the bug (empty response schema in html2 client):**

```
{
  "swagger": "2.0",
  "info": {
    "title": "MyWebsite",
    "description": "MyWebsite API",
    "version": "1.0.0"
  },
  "host": "mywebsite.com",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "basePath": "/",
  "paths": {
    "/apicheck": {
      "get": {
        "summary": "Check the API",
        "description": "test",
        "tags": ["apicheck"],
        "responses": {
          "200": {
            "description": "The API connection succeed",
            "schema": {
              "$ref": "#/definitions/apicheck"
            }
          }
        }
      },
    }
  },

  "definitions": {
    "apicheck": {
      "type": "object",
      "properties": {
        "requestId": {
          "type": "integer",
          "description": "Test"
        },
        "typeResponse": {
          "type": "string",
          "enum": ["sync", "async"],
          "description": "Test"
        }
      }
    }
  }
}
```
##### Steps to reproduce
- Go to http://editor.swagger.io
- Copy paste the JSON
- Generate html2 client
- Check the schema part is empty with the second JSON and filled with the first one.

Thank you by advance.

D.

**Comment by bshamblen** [comment]
I tested this on my local copy and the output appears to be correct now. editor.swagger.io must be out of date.
![screen shot 2016-12-12 at 3 59 42 pm](https://cloud.githubusercontent.com/assets/4249514/21121927/081c8d44-c084-11e6-806d-57fdf7e9e980.png)

**Comment by wing328** [comment]
@bshamblen thanks for performing a test to confirm. editor.swagger.io relies on generator.swagger.io to generate codes and generator.swagger.io is not using the latest master (there's no daily job to update it with the latest master) 

@David-Vander-Elst please pull the latest master to give it a try.

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
