### ISSUE TITLE
Truncated PHP example code in the html2 generated client

### ISSUE THREAD

**Issue by David-Vander-Elst** [swagger-api/swagger-codegen#4082]
##### Description

When I generate the HTML2 client, we have a lot of code example for several languages. All langages examples looks great except for PHP. A part of the PHP code is truncated above
##### Swagger-codegen version

Current one.
##### Steps to reproduce

Simply generate an html2 client and check the PHP code example.

Thanks.

**Comment by wing328** [comment]
@David-Vander-Elst thanks for reporting the issue. May I know if you've time to contribute the enhancements?

**Comment by David-Vander-Elst** [comment]
it looks like this is simply an opened tag at line 3 witch is commented and not the closed one.
I'm not able to test it right now as I'm a PHP developer only, but I can try later to set an environment, but not my priority right now.

**Comment by jhitchcock** [comment]
This should resolve it; 
https://github.com/swagger-api/swagger-codegen/pull/4212

The opening PHP tag seems to be screwing up the HTML, and tbh its not really needed anyway in this context so I removed it. I may look into it in more detail in the future as it could cause issues with new languages

**Comment by wing328** [comment]
PR merged into master. Please pull the latest master to give it a try.
