### ISSUE TITLE
[JaxRsCXFServer] Minor improvements BeanValidation/Unittests/Jboss/JAXB

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4088]
###### Language CXF server 
- [x] add CLI-flag for @Consumes/@Produces annotations for JSON (default: true)
- [x] add CLI-flag for switching between Spring XML or annotation-config 
- [x] add CLI-flag for switching JAXB annotations in the model classes on/off
- [x] add  CLI-flag and JbossFeature to only generate jboss-specific files if requested
  (jboss-web.xml)
- [x] add CLI-flag useSwaggerUI to activate Swagger UI automatically
- [x] add basePath /services/services to ApplicationContext.xml to allow immediate usage of the generated contract
- [x] update to CXF 3.1.8 and add new flag supportSwaggerUi to ApplicationContext.xml
- [x] changed default path for Spring Boot to / for access using http://localhost:8080/
- [x] cleanup Jaxrs annotations from apiServiceImpl.mustache/parameter mustache templates
- [x] fix handling of Multiparts to org.apache.cxf.jaxrs.ext.multipart.Attachment
- [x] generate .swagger-codegen-ignore file to protect generated impl-code

###### Language CXF client
- [x] add CLI-flag for switching JAXB annotations in the model classes on/off

###### Language jaxrs-resteasy: 
- [x] add CLI flag for Jboss to language jaxrs-resteasy (with default true to be non-breaking)
- [x] added new test for CLI options JavaResteasyServerOptionsTest

##### Further features
- [x] improve CXF QueryParam BeanValidation formatting 
  currently reused from beanValidation.mustache, but will add a newline after each beanvalidation annotation. 
  @wing328: Does it make sense to setup a separate mustache files just to get nicer formatting?
- [x] add separate CLI-flags for controlling junit test features
  (e.g. gzip/logging/... support)
  The gzip/logging code lines are currently generated automatically for server + junit-tests if switched on, but I think it would be better to have separate flags for the unittests.

##### Further features Part 2
- [x] check for void in apiServiceImpl to suppress the return statement (instead of returnType, which is void for no returnType...)

> added all above features to branch cxf_refine.  
  
  > This requires a variable for the void type in the Generator!
##### Related issues

-  add CLI-flag to generate jboss-deployment-structure for JEE 6 servers and CXF 3 support
> IMHO currently not necessary

PR #4164
Former PR #4003, #4147 (closed as changes haven't been picked up)

**Comment by jfiala** [comment]
@wing328 can you pls have a quick look at the topics above?

**Comment by wing328** [comment]
> @wing328: Does it make sense to setup a separate mustache files just to get nicer formatting?

Yes, I think it's worthwhile to do so.

> The gzip/logging code lines are currently generated automatically for server + junit-tests if switched on, but I think it would be better to have separate flags for the unittests.

That's better but I would suggest doing it if you've free cycle or there's a demand from the community. In other words, I don't think this enhancement has the highest priority at the moment. I'll leave it up to you and the community on when this feature will be added.

 > check for void in apiServiceImpl to suppress the return statement (instead of returnType, which is void for no returnType...)

I should be able to work on it this week. Will keep you posted.

**Comment by jfiala** [comment]
@wing328 Rebased + added all features above to branch cxf_refine
Added the check for void methods to the api_test.mustache. Now we can uncomment the service call + check for the response using assertNotNull.
Pls advise if you like it that way, if yes pls merge into master.

**Comment by jfiala** [comment]
@wing328 currently in the tests the api invocations are commented out and thus cannot be compiled.
Wouldn't it be good to activate them and run the CI maven build with -DskipTests?

**Comment by jfiala** [comment]
This issue has already been fully implemented, moved open questions to #4513.
