### ISSUE TITLE
[Java*] BeanValidation for all Java languages

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4091]
##### Description

BeanValidation support has been added in #4003 for Java and jaxrs-cxf/jaxrs-cxf-client.
This needs to be added to all other Java languages

- [x] jaxrs-spec
- [x] jaxrs (Jersey2 + library jersey1)
- [x] jaxrs-resteasy
- [x] jaxrs-cxf-cdi
- [x] spring (default library spring-boot + library spring-mvc, spring-cloud)

##### Related issues

PR Beanvalidation annotation for Java and CXF  #4003
Issues with language jaxrs-spec #4509 

##### Issues with language jaxrs-spec (see #4509)

* the api is generated as class, but IMHO this should be an interface!?
* Jaxrs Response is used instead of the real response data type
* @ApiResponse uses wrong response type (the return type, not the response type of the contract)
* src/gen/java is not added to the build path
* "Attachment" is used for attachments, but no import is added for this (I think org.apache.cxf.jaxrs.ext.multipart.Attachment is referenced, but this is CXF-specific)

Update: moved all the issues with jaxrs-spec to #4509

##### Support for @DecimalMin/@DecimalMax
Also add support for @DecimalMin/@DecimalMax 

- [x] jaxrs-spec
- [x] jaxrs (Jersey2 + library jersey1)
- [x] jaxrs-resteasy
- [x] jaxrs-cxf-cdi

##### Final Cleanup (PR #4635)
- [x] move beanvalidation code to AbstractJavaJAXRSServerCodegen.java
(so it will stay redundant in AbstractJavaJAXRSServerCodegen.java and SpringCodegen.java) or to AbstractJavaCodegen?
- [x] Backport support for @DecimalMin/@DecimalMax
backport to languages which already have beanvalidation annotation support:
   - [x] java
   - [x] jaxrs-cxf / jaxrs-cxf-client

Final Cleanup implemented in PR #4635

**Comment by jfiala** [comment]
@wing328 If you like I can cycle through the language templates and add (optional) beanvalidation support there. Or do you prefer the language maintainers to do the job?

**Comment by wing328** [comment]
@jfiala if you've time, please add the bean validation support. I'm sure the community and the template owner would appreciate your effort.

**Comment by cbornet** [comment]
Small remark: if bean validation is an option, it should be activated by default (since you expect the generated code to follow the contract established by the swagger spec)

**Comment by deveshpujari** [comment]
@jfiala 

We would like to get support for server side code generation for jaxrs ( jersey2) with JSR303 annotations. We are doing topdown approach of writing apis in swagger editor and generating the code. I would really appreciate if you prioritize the JSR303 addition to server code for jaxrs ( jersey2). Thanks.

**Comment by jfiala** [comment]
@deveshpujari  @wing328 added beanvalidation support to jaxrs-spec, I also had to fix an issue with outer Enums. 

Additional issues with jaxrs-spec:
* the api is generated as class, but IMHO this should be an interface!?
* Jaxrs Response is used instead of the real response data type
* @ApiResponse uses wrong response type (the return type, not the response type of the contract)
* src/gen/java is not added to the build path
* "Attachment" is used for attachments, but no import is added for this

I suggest fixing those in a separate issue for jaxrs-spec.

**Comment by jfiala** [comment]
Issues with jaxrs (=Jersey) with library jersey1
* maximum and minimum are double, but @Min/@Max allows only Integer values, I commented @Min/@Max out in the template beanValidation.mustache for now.
```
 - name: number
          type: number
          maximum: 543.2
          minimum: 32.1
```

**Comment by cbornet** [comment]
For type number, the annotations should probably be @DecimalMin/@DecimalMax

**Comment by jfiala** [comment]
@DecimalMin/@DecimalMax are for BigDecimal only, so IMHO we need to distinguish between integer and decimal datatypes to generate the correct annotations. Is there already a flag for to do this already available in the mustache templates?

**Comment by cbornet** [comment]
Type number is mapped to BigDecimal.
If you talk about Float/Double formats, I don't know if @Min/Max or @DecimalXXX can be used. It probably depends on the validation framework used. So you should probably not use `format: float` with min and max in your swagger spec...

**Comment by cbornet** [comment]
And I think @DecimalXXX works with Integer, Long, etc ...

**Comment by jfiala** [comment]
@DecimalMin/DecimalMax is reserved for decimal values:
https://docs.oracle.com/cd/E19798-01/821-1841/gircz/index.html
The value of the field or property must be a decimal value lower than or equal to the number in the value element. 

@Min/@Max are for integer values:
The value of the field or property must be an integer value lower than or equal to the number in the value element. 

http://swagger.io/specification/
number => @DecimalMin/DecimalMax
integer => @Min/@Max

I added checks for isInteger/^isInteger and now we support @Min/@Max/@DecimalMin/@DecimalMax, thx for the hint.

**Comment by cbornet** [comment]
That's not what I read here : http://docs.oracle.com/javaee/6/api/javax/validation/constraints/DecimalMin.html
A quick test should answer that 😄

**Comment by jfiala** [comment]
Hm - Using @Min/@Max for integers appears cleaner to me, as @DecimalMin/@DecimalMax use a string for the limit.

**Comment by cbornet** [comment]
@jfiala agreed

**Comment by cbornet** [comment]
You probably also want @Min/@Max for isLong

**Comment by jfiala** [comment]
common name integer/long = type integer => isInteger should include both format32 (integer) and format64 (long) (see http://swagger.io/specification/).

**Comment by jfiala** [comment]
changed in jaxrs/jaxrs-spec and jaxrs-resteasy

**Comment by cbornet** [comment]
>common name integer/long = type integer => isInteger should include both format32 (integer) and format64 (long) (see http://swagger.io/specification/).

Looking at the code, it doesn't seem to be the case...

**Comment by jfiala** [comment]
you're right, should I add support for isLong or we add isTypeInteger (which could then correctly include integer + long)?

**Comment by jfiala** [comment]
So far added beanvalidation annotation support to all Java languages listed at the top.
Pls advise regarding isInteger/isLong vs isTypeInteger then I can backport this to cxf/java as well.

**Comment by jfiala** [comment]
Java beanvalidation has been fully implemented, further enhancements for @Valid are dealt with separate issues.
