### ISSUE TITLE
New to Swagger

### ISSUE THREAD

**Issue by github4swagger** [swagger-api/swagger-codegen#4096]
##### Description

The Swagger definition does not contain my services/paths

##### Swagger-codegen version

2.0

##### Swagger declaration file content or url

```json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "MyInitech",
    "version" : "1.0.2"
  },
  "host" : "localhost:8002",
  "basePath" : "/api",
  "schemes" : [ "http" ]
}
```

##### Command line used for generation

I am trying to generate swagger code using the above JSON with below command

java -jar "modules\swagger-codegen-cli\target\swagger-codegen-cli.jar" generate -i http://localhost:8080/rest/swagger.json -l jaxrs -o "C:\Shiva\Amway\Swagger\localstore"

##### Steps to reproduce

I get belwo issue when i run above command

```
Exception in thread "main" java.lang.NullPointerException
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.jav         a:698)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:37         7)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

##### Related issues

None

##### Suggest a Fix

I want to know how can i generate swagger with my services generated in the definition/ JSON.

We are using Application subclass and below is the swagger code i included in my application  

```java
public class RestApplicationConfig extends Application{
public RestApplicationConfig() {
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.2");
        beanConfig.setDescription("MyInitech");
        beanConfig.setSchemes(new String[]{"http"});
        beanConfig.setHost("localhost:8002");
        beanConfig.setBasePath("/api");
        beanConfig.setResourcePackage("io.swagger.resources,com.xxxx.services.restservice.benefit");
        beanConfig.setScan(true);
        beanConfig.setPrettyPrint(true);
    }

	@Override
	public Set<Class<?>> getClasses() {
        //.. our other resources
       classes.add(io.swagger.jaxrs.listing.ApiListingResource.class);
		 classes.add(io.swagger.jaxrs.listing.SwaggerSerializers.class);
		return classes;
	}
}
```

I included dependency in pom.xml

```xml
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jersey2-jaxrs</artifactId>
  <version>1.5.0</version>
</dependency>
```

These are the only two changes i have done to include Swagger into my application.
Though I have included my package com.xxxx.services.restservice.benefit in setResourcePackage,

 beanConfig.setResourcePackage("io.swagger.resources,com.xxxx.services.restservice.benefit");

I don't see the JSON generated has paths defined in the classes in the package.

It generates only below JSON 👍 

```json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "MyInitech",
    "version" : "1.0.2"
  },
  "host" : "localhost:8002",
  "basePath" : "/api",
  "schemes" : [ "http" ]
}
```

Help what else needs to be done to have my paths get generated in the JSON..

**Comment by fehguy** [comment]
Hi, your api has no paths, so you have an issue with how you've integrated swagger-core with your app.  Please open a ticket there and share some more information
