### ISSUE TITLE
formData parameters are not included in the HTML2 generated client

### ISSUE THREAD

**Issue by David-Vander-Elst** [swagger-api/swagger-codegen#4097]
##### Description

Again a bug in html2 client generator. All parameters type formData are not taken in account, and not shown in the HTML2 generated client.
##### Swagger-codegen version

Current.
##### Steps to reproduce
- Go to editor.swagger.io and past this:

```
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: <enter your title>

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /persons:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: formData
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
```
- Generate the HTML2 client and check. Parameter is missing.

**Comment by wing328** [comment]
@David-Vander-Elst A good starting point to add the `formData` parameters is https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/htmlDocs2.

Let me know if you've time to contribute the fix.

**Comment by David-Vander-Elst** [comment]
it looks like this is simply an opened tag at line 3 witch is commented and not the closed one.
I'm not able to test it  right now as I'm a PHP developer only, but I can try later.

**Comment by manoelledeviron** [comment]
Hello, I tried the same thing (I tried with my own doc, and with @david-vde 's example too), and I still don't see the formData parameters in the html2 generated client (the Parameters field is empty for both examples).
Is there a solution to this?

**Comment by wing328** [comment]
A good starting point to add the formData parameters is https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/htmlDocs2.

Would you have time to contribute the fix?

Form parameters can be retrieved from the tags {{#formParams}}:

https://github.com/swagger-api/swagger-codegen/search?utf8=%E2%9C%93&q=formparams&type=

**Comment by wing328** [comment]
Actually it seems to be added already:
```
swagger-codegen|fix_spring_cloud_client ⇒ grep -R 'formParams' modules/swagger-codegen/src/main/resources/htmlDocs2/*
modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache:                              {{#formParams}}
modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache:                              {{/formParams}}
``` 
Please pull the latest master to give it a try.

**Comment by manoelledeviron** [comment]
Indeed, I had the 2.2.1 version of swagger codegen, it works well with version 2.2.2. Thanks!
