### ISSUE TITLE
Inconsistent license terms

### ISSUE THREAD

**Issue by jodoglevy** [swagger-api/swagger-codegen#4104]
I want to use Swagger to generate libraries in Ruby, Python, and Java, but I am unsure on the guidance around the license terms present in some of the language-specific mustache files in this repo.

First question - if a mustache template has a copyright notice / license terms present, like [this Python template](https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/python/api_client.mustache), must I keep this notice present, intact, in my modified version of this template, so that it shows up as is in all of my generated libraries?

Second question - why do only some of the mustache templates have this notice? For example, the equivalent [Java template](https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache) and [Ruby template](https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/ruby/api_client.mustache) do not have a copyright notice / license terms like the [Python template](https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/python/api_client.mustache). If the template does not have any copyright notice / license text in it, does that mean I don't have to add any such SmartBear license text / copyright notice to my modified templates based off of these ones?

**Comment by wing328** [comment]
For questions/discussion related to licensing in the auto-generated code, please refer to https://github.com/swagger-api/swagger-codegen/issues/2963.

**Comment by jimschubert** [comment]
@jodoglevy I think this issue is negated by #4139 (Remove license headers from generated code). The way forward is with templates and swagger-codegen code being licensed, but generated code license is up to you.

**Comment by jodoglevy** [comment]
@jimschubert yes based on the latest comments in #2963 that seems right. Thanks @fehguy for the clarification and quick action on this. Closing.
