### ISSUE TITLE
[python][flask] operationId should be relative if x-swagger-router-controller is present

### ISSUE THREAD

**Issue by danyx23** [swagger-api/swagger-codegen#4106]
##### Description

[The docs](https://github.com/zalando/connexion#endpoint-routing-to-your-python-views) say that adding x-swagger-router-controller should make the operationId field relative - however, the operationId field in the swagger subdirectory of the generated python flask scaffold always contains the full default controller prefix.

##### Swagger-codegen version

Current stable (2.2.1)

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /test:
    get:
      summary: "demonstrate x-swagger-router-controller bug in python flask"
      x-swagger-router-controller: bla
      operationId: test_get
      responses:
        200:
          description: OK
```

##### Command line used for generation

```bash
java -jar swagger-codegen-cli.jar generate -l python-flask -i .\Swagger.yaml
```

##### Steps to reproduce

1. Generate the python flask scaffold with the above command or the swagger online editor
2. check swagger/swagger.yaml in the generated scaffold. operationId should be just 
`operationId: "test_get"` but is `operationId: "controllers.default_controller.test_get"`

##### Related issues

Couldn't find one

##### Suggest a Fix

The code preprocessing the operationId field should take the field x-swagger-router-controller into account: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java#L234

**Comment by wing328** [comment]
@danyx23 there are some changes/enhancements to Python Flask generator. Please pull the latest to give it a try: https://github.com/swagger-api/swagger-codegen/pulls?q=is%3Apr+label%3A%22Server%3A+Python%22+is%3Aclosed

**Comment by danyx23** [comment]
Hi @wing328, thanks for your reply! Sorry it took me a while to get around installing the JDK on my machine and compiling the latest version. I just checked and the behavior is still as I described - operationId contains the full controller path even if x-swagger-router-controller is set to an identical prefix.

I noticed that the new default seems to be to put every endpoint into it's own file instead of putting everything into default_controller.py. I changed layout of my files to match the new structure and adapted the x-swagger-router-controller to agree with the default generated paths but still no luck.

**Comment by cbornet** [comment]
I have the same issue. Also if you regen the pet sample from the generated swagger.yaml (the one used by flask-connexion) then you get a different swagger.yaml which painful.
I think the operationId shouldn't be modified during generation and x-swagger-router-controller must be generated instead.
PR incoming !

**Comment by wing328** [comment]
@danyx23 PR by @cbornet has been merged into master. Please pull the latest master to give it a try.
