### ISSUE TITLE
$ref of ./definitions/link.json is being referenced in generated class as DefinitionsLinkJson - Java

### ISSUE THREAD

**Issue by rickdbenetech** [swagger-api/swagger-codegen#4109]
##### Description

I'm working on a project that has the following two json definitions (below) and when I do a 'mvn clean install' it ends up generating the Category.Java file with references to 'DefinitionsLinkJson' type instead of 'Link' type, as it should, with errors like this:

[ERROR] symbol:   class DefinitionslinkJson
[ERROR] location: package io.swagger.client.model
[ERROR] /target/generated-sources/swagger/src/main/java/io/swagger/client/model/Category.java:[49,15] error: cannot find symbol

##### Swagger-codegen version

I'm using version 2.2.1

##### Swagger declaration file content or url

category.json
    ```
{
    "type": "object",
    "title": "Category",
    "properties": {
        "name": {
            "type": "string",
            "description": "Descriptive name of the subject category"
        },
        "categoryId": {
            "type": "string",
            "description": "Unique identifier"
        },
        "links": {
            "type": "array",
            "items": {
                "$ref": "./definitions/link.json"
            }
        }
    }
}
    ```

link.json
    ```
{
    "type": "object",
	"title": "Link",
    "properties": {
        "rel": {
            "type": "string",
			"description": "A relationship name"
        },
        "href": {
            "type": "string",
			"description": "An absolute or relative URI for a resource request"
        }
    }
}
    ```

##### Command line used for generation

mvn clean install

**Comment by wing328** [comment]
@rickdbenetech please pull the latest master to give it another try as we've just updated the project to use the latest stable version of Swagger Parser (released a few days ago), which has better support for JSON reference.

**Comment by jbrugge** [comment]
I tried this same situation with the old and new code, and the Swagger Parser update does seem to fix this problem.

Any sense for when a new release might get cut?

**Comment by wing328** [comment]
We've not set a date yet: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-long-does-it-take-to-release-a-stable-version-eg-215--216

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
