### ISSUE TITLE
Using struct for models in Swift template

### ISSUE THREAD

**Issue by dagio** [swagger-api/swagger-codegen#4126]
##### Description

Has anyone been working of using structs instead of classes in the Swift3 default template ?

##### Swagger-codegen version

from master

##### Swagger declaration file content or url

nil

##### Command line used for generation

nil

##### Steps to reproduce

nil

##### Related issues

nil

##### Suggest a Fix

nil

**Comment by wing328** [comment]
@dagio not that I'm aware of. Please note we've recently added `swift3` generator for Swift 3.0.

cc @jaz-ah @Edubits

**Comment by dagio** [comment]
I can make a PR introducing a new variable to allow to use structs instead of classes (while classes remain the default choice).

**Comment by wing328** [comment]
@dagio thanks. Please submit a PR and we'll review the change. I would suggest you add the option to the `swift3` generator as `swift` (2.x) will eventually be decommissioned.

**Comment by normand1** [comment]
This is a good idea, I think using structs would ultimately help with swift3 compile times.

**Comment by cbornet** [comment]
Talking about swift models, I think using https://github.com/tristanhimmelman/AlamofireObjectMapper would be best.

**Comment by wing328** [comment]
Yes, I suggested something very similar before via https://github.com/swagger-api/swagger-codegen/issues/2194

@dagio @normand1 would the ObjectMapper meet your need?

One thing to consider is to handle JSON key with special characters (e.g. "date-time").

**Comment by dagio** [comment]
@wing328 ObjectMapper is not necessary to support struct. It can be done without introducing a new dependency. I will make a PR this week to share what I did.

**Comment by wing328** [comment]
@dagio I'm aware that `struct` has no dependency on `ObjectMapper`.

Just want to make you aware of the option.

**Comment by dilutedsauce** [comment]
Is there a compelling reason not to have have both as options and let the user choose? It might also be nice to have a protocol option.

**Comment by wing328** [comment]
@normand1 @dagio please join the discussion in https://github.com/swagger-api/swagger-codegen/issues/6941
