### ISSUE TITLE
Remove License file from generated code

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#4137]
Per https://github.com/swagger-api/swagger-codegen/issues/2963#issuecomment-258559506, we should remove the LICENSE file from code generation.  It gives the impression that the parent projects' license is attached to the generated code, which is not the intent of this project.

**Comment by wing328** [comment]
Closed via the following PRs:

https://github.com/swagger-api/swagger-codegen/pull/4200
https://github.com/swagger-api/swagger-codegen/pull/4199
https://github.com/swagger-api/swagger-codegen/pull/4197
