### ISSUE TITLE
Remove license headers from generated code

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#4139]
Per this discussion:

https://github.com/swagger-api/swagger-codegen/issues/2963#issuecomment-258559506

We should remove the license header from all generated files.  The license of the generated files is entirely up to the creator of them, and is not subject to the parent project's licensing choice.

**Comment by wing328** [comment]
@fehguy I'll work on it this weekend.

**Comment by fehguy** [comment]
Thanks, I can help as well

**Comment by wing328** [comment]
Closed via the following PRs:

https://github.com/swagger-api/swagger-codegen/pull/4200
https://github.com/swagger-api/swagger-codegen/pull/4199
https://github.com/swagger-api/swagger-codegen/pull/4197
