### ISSUE TITLE
DefaultGenerator scope change for easier extensibility

### ISSUE THREAD

**Issue by billumina** [swagger-api/swagger-codegen#414]
When attempting to extend the JAX-RS generator to generate an additional file type from separate templates I was unable to access a few important variables.

I am suggesting the three variables below are made protected.

public class DefaultGenerator implements Generator {
  private CodegenConfig config;
  private ClientOptInput opts = null;
  private Swagger swagger = null;

**Comment by fehguy** [comment]
sure, that's easy, but it'd be helpful to know what you're looking to override so perhaps it can become part of the configuration.

**Comment by billumina** [comment]
@fehguy 

Thanks! I will definitely share more about what I'm trying to to do.

I was trying to create a separate output file for another type of class. This appears to require another Map<String, String> to hold the template files. Easy enough to add this to an inherited class, however because I was unable to access the parameters I mentioned in this item i was unable to follow conventions used in the default generator.

Please let me know if you want more information. I will gladly answer any questions. 

Thanks!

```
  //interface
  Response estimatesPriceGet(estimatesPriceGetRequest request);

  //request DTO; wanted this in a separate file
  public class estimatesPriceGetRequest
  {
    public estimatesPriceGetRequest() {}

    //getter/setters for each property
    ...
  }
```

**Comment by billumina** [comment]
@fehguy an option in the command line generator to create this type of code would probably be helpful to others. http://examples.javacodegeeks.com/enterprise-java/rest/jersey/json-example-with-jersey-jackson/ The idea is use a POJO for the request instead of a slew of parameters for readability.

**Comment by fehguy** [comment]
OK I'm going to open a new ticket with a bit more general title.
