### ISSUE TITLE
"No service of type Factory available in ProjectScopeServices" Error on importing auto generated Android-Client code.

### ISSUE THREAD

**Issue by acsr2016** [swagger-api/swagger-codegen#4150]
##### Description
Getting "No service of type Factory available in ProjectScopeServices" error on importing auto generated  'android-client' project as an android module. Client code was generated from swagger editor for 'minimal.yaml' sample file.
![image](https://cloud.githubusercontent.com/assets/23315627/20062779/fbb777a4-a52a-11e6-9389-3e3f8d4458fb.png)

##### Swagger Editor Version 2.10.3 
(obtained by using: docker run -p 80:8080 swaggerapi/swagger-editor)

Reference yaml that produces it.
- 'minimal.yaml' sample file was used.

Generate Client - Android

##### Steps to reproduce

1) Create a new Android Studio Project with Empty Activity and compile
2) Import Swagger Editor generated android client code for minimal.yaml sample file and try to compile to reproduce the error. 

##### Suggest a Fix
(Note: I just a beginner. Got hint from http://stackoverflow.com/questions/38825451/no-service-of-type-factory-available-in-projectscopeservices)
 
Updating dependencies to the following resolved the issue:
dependencies {
        // classpath 'com.android.tools.build:gradle:1.5.+'
        // classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
    }

**Comment by wing328** [comment]
@acsr2016 thanks for reporting the issue. Did you follow the README.md to install the library or you're using some other approaches to install it?

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by ejChathuranga** [comment]
I've faced the same issue. When I import a new project it appears. Is this fixed? 
this is the message ->
In my Gradle ->
`dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.0'
        classpath 'com.github.dcendents:android-maven-plugin:1.2'
    }`

this is the message ->
`Gradle 'easy-content-providers-master' project refresh failed`
