### ISSUE TITLE
produces "*/*" is converted into Accept: *_/_*

### ISSUE THREAD

**Issue by umbreak** [swagger-api/swagger-codegen#4151]
##### Swagger-codegen version: 2.2.1 (swagger-codegen-maven-plugin)

My yml file contains something like:

````
      consumes:
        - application/json
      produces:
        - '*/*'
````

Generating the client code from it works. However, I noticed that the server was crashing when returning the response to the client. After digging for quite some time I realized (with wireshark) that the client was sending the following **HTTP Header: "Accept: *_/_*"**

What is that?

As a workaround I did as follows:

````java
ApiClient apiClient = new ApiClient();
apiClient.addDefaultHeader("Accept", "*");
````

**Comment by wing328** [comment]
It's due to a security measure we put in to avoid code injection. I'll see what I can do to handle `*/*` as an exception.

**Comment by wing328** [comment]
@umbreak closed via https://github.com/swagger-api/swagger-codegen/pull/4155. Please pull the latest to give it a try.
