### ISSUE TITLE
[PYTHON] Request header Content-Type defaults to application/json

### ISSUE THREAD

**Issue by vproman** [swagger-api/swagger-codegen#4163]
##### Description

I have a GET swagger endpoint that depends entirely on URI query parameters, it sends nothing in the body.  If I do not set the "consumes" value for the endpoint, it defaults to application/json, which isn't correct since I'm sending nothing in the request body.

##### Swagger-codegen version

git cloned from master

##### Swagger declaration file content or url
 ```yaml
  /testa/testb:
    get:
      summary: test
      consumes:
      description: |
        test
      parameters:
        - name: testc 
          in: query
          description: testc
          required: true
          type: string
          default: testc
        - name: testd
          in: query
          description: testd
          required: true
          type: string
          default: testd
      responses:
        200:
          description: Successful response
          schema:
            title: response
            type: array
            items:
                  title: teste
                  type: string
```

##### Command line used for generation

java -jar ~/Projects/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.yaml -l python -o .

##### Steps to reproduce

Generate api from swagger endpoint without consumes/media type defined
call api endpoint method, verify that Content-Type is set to application/json

##### Suggest a Fix

Return empty string if content_types is None/empty:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_client.mustache#L460

OR

Only set Content-Type header if consumes, mediatype, or hasMore is defined:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api.mustache#L197

**Comment by wing328** [comment]
@vproman thanks for suggesting the fix. I think we need (1) (return empty/null string) and then similar to 'Accept' we will need to delete header_params['Content-Type'] if it's empty: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api.mustache#L195-L196

May I know if you've time to contribute the enhancement?

**Comment by wing328** [comment]
cc @scottrw93

**Comment by taxpon** [comment]
@wing328 @vproman Hi I am interested in working on this issue, but I am wondering how swagger-codegen works in other languages (Java, Ruby..) regarding this issue. In my opinion, swagger-codegen should provide some generation logic among multiple languages. @wing328 what do you say?

**Comment by wing328** [comment]
@taxpon thanks for offering help to fix this issue.

I totally agree with you that we should take a consistent approach and I've filed https://github.com/swagger-api/swagger-codegen/pull/4310 to fix the same issue for the Ruby API client using `hasConsumes`, `hasProduces`. 

Please review and let me know if you've any question.

**Comment by wing328** [comment]
Fixed via https://github.com/swagger-api/swagger-codegen/pull/4419
