### ISSUE TITLE
NodeJS server's README.md wrong?

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#4165]
_From @JeffML on November 9, 2016 23:22_

The README reads:

> 
> # Swagger generated server
> 
> ## Overview
> This server was generated by the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) project.  By using the [OpenAPI-Spec](https://github.com/OAI/OpenAPI-Specification) from a remote server, you can easily generate a server stub.  This is an example of building a node.js server.
> 
> This example uses the [expressjs](http://expressjs.com/) framework.  To see how to make this your own, look here:

But the only dependency I see is on connectjs, which isn't even part of expressjs anymore.  Perhaps I'm confused.

_Copied from original issue: swagger-api/swagger-editor#1105_

**Comment by wing328** [comment]
@jeffml I think you're right. I'll remove that line from the README

**Comment by wing328** [comment]
Closed via #4232 

Please pull the latest master to give it a try.
