### ISSUE TITLE
[Ruby] Client does not correctly call `super` method making error messages empty.

### ISSUE THREAD

**Issue by chakrit** [swagger-api/swagger-codegen#4167]
##### Description

The ruby client template for `api_error` class do not call `super` method on all code paths leading to empty message inside exceptions most of the time making things hard to debug.

##### Swagger-codegen version

master at commit 5899554

##### Swagger declaration file content or url

Irrelevant

##### Command line used for generation

Irrelevant

##### Steps to reproduce

1. Generate ruby client for *any* swagger project.
2. Install the client gem into a project. (e.g. `gem 'tester', git: 'testfolder')
3. Enter a ruby console (e.g. `bundle exec rails c`)
4. Requires the gem.
5. Creates a new `Tester::ApiError` class with similar code from other parts in the ruby template: `Tester::ApiError.new(code: 404, response_body: 'not_found')`
6. Check that the inspection logs doesn't contain any useful error information.
7. Try calling `.to_s` or `.message`, still no useful information.

##### Related issues

Havn't found any.

##### Suggest a Fix

(PR being opened)

**Comment by wing328** [comment]
Closed via #4168
