### ISSUE TITLE
[Java]Library support for resteasy when creating java client

### ISSUE THREAD

**Issue by gayathrigs** [swagger-api/swagger-codegen#4171]
##### Description
For generating a java client I understand that the supported libraries does not include resteasy. Is there a reason for that? In my project I used jersey2 to generate the client and all was well until I had to call the client api from a restful service deployed on wildfly 10. The client builder uses the resteasy libraries which I assume comes with wildfly.

##### Swagger-codegen version

I am using 
<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>2.2.1</version>
##### Swagger declaration file content or url

at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.withConfig(ResteasyClientBuilder.java:50)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:126)
	at io.swagger.client.ApiClient.buildHttpClient(ApiClient.java:676) 

##### Steps to reproduce

1. Generate a simple java swagger client (jersey2)
2. Try calling the API from a restful service deployed on wildfly 10 (or 9)

**Comment by wing328** [comment]
@gayathrigs No one has contributed the `resteasy` lib to Java API client so far. 

May I know if you've cycle to make the contribution? If yes, I can show you some good starting point.

**Comment by gayathrigs** [comment]
I will some time after next week. So yes, it will great to have some guidance to get me going.

**Comment by wing328** [comment]
@gayathrigs a good starting point is to look at how Retrofit2 was added: https://github.com/swagger-api/swagger-codegen/pull/1545

If you need any help, just let us (community) know.

**Comment by gayathrigs** [comment]
Thank you. I think I have a fair idea of what needs to be done. I will keep you posted with the updates.

**Comment by gayathrigs** [comment]
@wing328 I have the draft version working . I forked from master. Can I push my changes there? I am not familiar with the procedure. Please let me know.

**Comment by wing328** [comment]
@gayathrigs you will need to submit a PR (pull request) by going to https://github.com/gayathrigs/swagger-codegen and click on the "New pull request" button.

**Comment by agu780ph** [comment]
I am also interested in a `resteasy` Client. I checked out @gayathrigs branch, but it seems not to be finished yet. Is anyone still working on this branch?

**Comment by wing328** [comment]
I would suggest adding @gayathrigs work to the master as a starting point so that others can submit  PRs to enhance it.

@gayathrigs do you need help filing a PR? or you want us to do it for you?

**Comment by gayathrigs** [comment]
@wing328  and @agu780ph I have filed a PR with the changes that I have. Please review them. I have added java-petstore-resteasy.sh and java-petstore-resteasy.json to the bin folder. But when I ran it I got some errors. I will look into that later.

**Comment by wing328** [comment]
@gayathrigs thanks for the PR. I'll review shortly.

**Comment by wing328** [comment]
PR (https://github.com/swagger-api/swagger-codegen/pull/5379) merged into master. Thanks for your contribution.
