### ISSUE TITLE
Can I ask if we can add support for JSON object in HTTP header?  

### ISSUE THREAD

**Issue by beingcoder** [swagger-api/swagger-codegen#4181]
I understand its kind of silly,   but sometimes it is very useful to pass complex object  for GET operation,   e.g.  JSON Web Token(JWTs)

**Comment by cbornet** [comment]
You can't really know the mime-type of an object in header so I don't think it's really doable.
You can always pass it as a string and deserialize it yourself.

**Comment by beingcoder** [comment]
We can borrow the Consumer definition of Operation,  in swagger spec file,   if we let header parameter to refer to object type,   SwaggerUI can easily show what kind of request is acceptable.   Codegen can generate code accordingly.     Currently  header param only supports String,  but we can add type definition.    When come to HTTP Content-Type(MIME),  we don't really care about it much.   Swagger is used to demonstrate interface between client and service provider,  SwaggerUI and Editor/Codegen can fill that gap.   Actually body and header have no difference at all from user's perspective,  just place to hold data.    Why swagger can not show that if customized serialization is doable?  many thanks.

**Comment by cbornet** [comment]
From [swagger-spec](http://swagger.io/specification/#headersObject):
> Header Object
type 	string 	Required. The type of the object. The value MUST be one of "string", "number", "integer", "boolean", or "array".

So your spec wouldn't be valid.

**Comment by beingcoder** [comment]
true,   I just hope to change that.

**Comment by wing328** [comment]
@beingcoder you may want to provide your feedback via https://github.com/OAI/OpenAPI-Specification/issues as OpenAPI/Swagger spec 3.0 is being finalized.
