### ISSUE TITLE
Minor fix to python client example code

### ISSUE THREAD

**Issue by karussell** [swagger-api/swagger-codegen#4184]
##### Description

A minor change of the example code seems to be necessary accoding to [this PR](https://github.com/graphhopper/directions-api-clients-route-optimization/pull/9)

##### Swagger-codegen version

The master from ~[17. October](https://github.com/swagger-api/swagger-codegen/issues/3846#issuecomment-254484220)

##### Suggest a Fix

See again the proposed change in the PR

**Comment by wing328** [comment]
I believe that's already been fixed: https://github.com/swagger-api/swagger-codegen/blob/f63cae8aae4f780613deafd5a5bbe7633436e2ce/modules/swagger-codegen/src/main/resources/python/README.mustache#L73

Can you pull the latest master to give it a try?

**Comment by karussell** [comment]
Ah, ok. Didn't found it in the issues. Will update the master and try - thanks!
