### ISSUE TITLE
[develop_2.0] Java petstore client sample Pet deserialization exception

### ISSUE THREAD

**Issue by bennnjamin** [swagger-api/swagger-codegen#419]
Hi I'm testing the client samples. I've got a nodejs server running all seems to be working. When I go to http://54.213.53.9:8002/pet/findByTags from a browser I get 

{"message":"how about implementing findPetsByTags as a GET method?"}

Looks good. On the Java client (https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples/client/petstore/java) I've made a simple main method to test this same resource.

     
    public static void main(String[] args) {
        PetApi pApi = new PetApi();
        List<String> tags = new ArrayList<String>();
        try {
            ArrayList<Pet> pets = (ArrayList) pApi.findPetsByTags(tags);
        } catch (ApiException ex) {
            Logger.getLogger(PetStoreSW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

When I run this I get this error:

Exception in thread "main" java.lang.ClassCastException: io.swagger.client.model.Pet cannot be cast to java.util.List
	at io.swagger.client.api.PetApi.findPetsByTags(PetApi.java:226)

If you look into the PetApi.java source you'll see this:

      String response = apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType);
      if(response != null){
        return (List<Pet>) ApiInvoker.deserialize(response, "array", Pet.class);
       
      }

And if you look at ApiInvoker.deserialize() you'll see it's returning a Pet object and not an "array"

    try{
      if("List".equals(containerType)) {
        JavaType typeInfo = JsonUtil.getJsonMapper().getTypeFactory().constructCollectionType(List.class, cls);
        List response = (List<?>) JsonUtil.getJsonMapper().readValue(json, typeInfo);
        return response;
      }
      else if(String.class.equals(cls)) {
        if(json != null && json.startsWith("\"") && json.endsWith("\"") && json.length() > 1)
          return json.substring(1, json.length() - 2);
        else
          return json;
      }
      else {
        return JsonUtil.getJsonMapper().readValue(json, cls);
      }
    }
    catch (IOException e) {
      throw new ApiException(500, e.getMessage());
    }

**Comment by fehguy** [comment]
Yes, the generated server response isn't actually accurate.  The client tries to deserialize it based on what it *should* be.
