### ISSUE TITLE
Generate Java model with custom annotation and import

### ISSUE THREAD

**Issue by bgonline** [swagger-api/swagger-codegen#4198]
We are using swagger-codegen-cli to generate the Java client part of a swagger.json file, using "jersey2" as library.

We would like to add a specific annotation in the model objects generated and, therefore, the associated import.

Swagger-codegen version: 2.2.1.

Current solution: modify the "pojo.mustache" file of the swagger-codegen-cli path "Java".

Is it possible to do it in another way?

Thank you in advance for your help.

**Comment by jfiala** [comment]
@bgonline you use the -t (templates) CLI option to use your own templates (and simply overrule the templates supplied by the target language/library.

**Comment by bgonline** [comment]
Great idea, indeed, thank you for the advice!
Could you give me a URL where I could find more information about this option?
Thank you in advance ;-)

**Comment by jfiala** [comment]
In fact, it is the start page:
https://github.com/swagger-api/swagger-codegen

search for "[(-t <template directory> | --template-dir <template directory>)]" :).

**Comment by jfiala** [comment]
@bgonline pls close the issue if you are satisfied with the docs ...

**Comment by bgonline** [comment]
Thank you for your help ;-)

**Comment by maheshmahadevan** [comment]
Question - if you want to override only a single tempate i.e such as pojo.mustache , do we still need to replace the whole template directory, or does swagger can use other templates from default directory or only override the one provided in CLI option

**Comment by florimon** [comment]
> Question - if you want to override only a single tempate i.e such as pojo.mustache , do we still need to replace the whole template directory, or does swagger can use other templates from default directory or only override the one provided in CLI option

No, you don't need to replace the whole template directory, you can override just the file(s) you want/need.
