### ISSUE TITLE
[PHP] Non-leading numbers removed from generated classnames

### ISSUE THREAD

**Issue by careysizer** [swagger-api/swagger-codegen#4211]
##### Description

Trying to generate classes for the Magento 2 schema JSON (which has other issues that need addressing within the schema itself), the versioning that Magento has applied to their API gets removed. I wonder if this should be supported in `swagger-codegen`?

For example: `catalogAttributeSetRepositoryV1` gets converted to an API class of : `CatalogAttributeSetRepositoryVApi`. The classname `CatalogAttributeSetRepositoryV1Api` would be [legal in PHP](http://php.net/manual/en/language.oop5.basic.php) (just not if the first character of the class was a number).  

##### Swagger-codegen version

`2.2.2-SNAPSHOT`

##### Swagger declaration file content or url

http://devdocs.magento.com/swagger/schemas/latest-2.0.schema.json

```json
{
  "tags": [
    {
      "name": "storeStoreRepositoryV1",
      "description": "Store repository interface"
    },
  ]
}
```

##### Command line used for generation

Using [jimschubert/swagger-codegen-cli](https://hub.docker.com/r/jimschubert/swagger-codegen-cli/):

`docker-compose.yml`:

```yml
  swagger:
    image: jimschubert/swagger-codegen-cli
    volumes:
      - ./swagger/config:/root/config
      - ./swagger/schema:/root/schema
      - ./swagger/export:/root/export

```

`config.json`:
```json
{
  "variableNamingConvention" : "camelCase",
  "invokerPackage" : "SwaggerClient\\MagentoEnterprise212",
  "packagePath" : "MagentoEnterprise212",
  "composerProjectName" : "swaggerclient-magentoenterprise212",
  "gitUserId" : "test"
}
```

Command:

```sh
docker-compose run --rm swagger generate \
            -i /root/schema/magento2/schema.json \
            -l php \
            -o /root/export/result/ \
            -c /root/config/magento2/config.json
```

##### Steps to reproduce

1. Create docker-compose file with service shown above, with host sub-directories shown (`./swagger/config`,`./swagger/schema`,`./swagger/export`)
2. Download [Magento 2 schema](http://devdocs.magento.com/swagger/schemas/latest-2.0.schema.json) to  `./swagger/schema/schema.json`
3. Create `config.json` in `./swagger/config/config.json` with contents shown above
4. Run above command 

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/2392  - [PHP] Invalid classes generated if models start with a digit.

Magento 2 - [PR 7446](https://github.com/magento/magento2/pull/7446) - addressing issue with schema generation.

**Comment by wing328** [comment]
@careysizer agreed with you that non-leading numbers should not be removed.

I'll try to fix it over the weekend. Will keep you posted.

**Comment by wing328** [comment]
@careysizer I did a test with the latest master but couldn't repeat the issue. Here is partial result:
```
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/php/tag3/SwaggerClient-php/lib/Api/CatalogAttributeSetRepositoryV1Api.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/php/tag3/SwaggerClient-php/test/Api/CatalogAttributeSetRepositoryV1ApiTest.php
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/php/tag3/SwaggerClient-php/docs/Api/CatalogAttributeSetRepositoryV1Api.md
```
Did you try building the local JAR based on the latest master?

**Comment by careysizer** [comment]
Thanks @wing328 - I tested with latest master (I was at `cafcf51`) and looks like that's working for me too.

**Comment by wing328** [comment]
Glad to hear that it's working for you.
