### ISSUE TITLE
[java] Swagger codegen does not work when two json files has same name

### ISSUE THREAD

**Issue by abhijith-prabhakar** [swagger-api/swagger-codegen#4218]
Hi,

I have two versions of a schema file, both placed under respective folders.  ex: `v1/currency_code.json` and `v2/currency_code.json`.  v2 one has an incompatible change.  If I refer to both versions in my swagger.json, codegen generates only one CurrencyCode.java. 

Does codegen only work with unique filenames?  If yes, then I think this is a serious limitation.

**Comment by fehguy** [comment]
@abhijith-prabhakar can you please share more details on this? Are there duplicate operationId values? Duplicate models?

**Comment by abhijith-prabhakar** [comment]
It generates a single model class.  Which schema file generated model references depends on where it is defined in the api.  It is picking up first one it could find while parsing.  
I have updated the demo project here with a branch showing the issue.  Please check out the branch and run `mvn clean install`
https://github.com/abhijith-prabhakar/swagger-ref-error-demo/tree/diff_versions_issue4218

**Comment by fehguy** [comment]
You cannot have the same name defining different schemas.  Please choose a unique name.
