### ISSUE TITLE
[Java] :DefaultGenerator.java is too long and difficult to read.

### ISSUE THREAD

**Issue by sreeshas** [swagger-api/swagger-codegen#4225]
DefaultGenerator is too long and difficult to read. It needs refactoring. 

##### Description

DefaultGenerator is too long and difficult to read. It needs refactoring. 

##### Swagger-codegen version
master branch. top of the tree.

##### Swagger declaration file content or url
Not required.

##### Suggest a Fix

I have created a pull request #4224

**Comment by wing328** [comment]
Closed via #4224
