### ISSUE TITLE
Codegen class news up codegen class

### ISSUE THREAD

**Issue by billumina** [swagger-api/swagger-codegen#423]
This makes extensibility Codegen class somewhat challenging; sometimes making copy/paste inheritance needed. 

I think the generation portion should be separated from the command line parsing logic. Codegen should be the default case to preserve backwards compatibility, but should be able to be changed using a command line parameter. On line 91 it could load the appropriate class (Codegen or some other class specified via command line parameter)

On line 91 you will see:

```
new Codegen().opts(clientOptInput).generate();
```

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/Codegen.java#L91

Or maybe generate needs an optional way to accept clientOptInput so nothing has to be newed up here.

Thanks!

**Comment by fehguy** [comment]
Thanks, I'll get the interface documented.

**Comment by fehguy** [comment]
I believe the class should either accept args (for a CLI), or file with JSON in the arg structure.  If you'd like to send a PR for this, it'd be great.

**Comment by HugoMario** [comment]
Codegen class was deprecated a while ago, closing issue.
