### ISSUE TITLE
underscore("_") in property name of swagger.yaml is getting converted to camelCase in generated code of spring through swagger codegen maven plugin

### ISSUE THREAD

**Issue by bhuvnesharya** [swagger-api/swagger-codegen#4233]
##### Description

I am using swagger codegen maven plugin for spring language. I have given few property names with underscore("_") in swagger.yaml file that is a input to my swagger codegen maven plugin and my underscore("_") in property name of swagger.yaml is getting converted to camelCase in generated code of spring through swagger codegen maven plugin. I want to have a snake_case only in my generated source code.

##### Swagger-codegen version

 swagger-codegen maven plugin - 2.2.1

Please suggest resolution for the same.

**Comment by wing328** [comment]
snake_case does not conform to Java style guide. The serialization/deserialization should automatically convert the property name to snake_case

**Comment by shiqicao** [comment]
@wing328 seems it doesn't in spring.

**Comment by eblis** [comment]
I have created pull request #4508 which provides options to keep underscores and also allow unicode characters in identifier names.

**Comment by fehguy** [comment]
#4508 was merged.

**Comment by emreavsar** [comment]
nice! worked for me.

**Comment by VimalAnnamalai78** [comment]
Any idea for PYTHON? because it is avoiding the underscore in my property name..

example ;-  **`property_name`** in yaml file but after codegen process it is creating auto generated files with class name like **`Propertyname_Attributes`**..

Your help will be more appreciated..
