### ISSUE TITLE
Java DateTimeTypeAdapter class is not using the right formatter.

### ISSUE THREAD

**Issue by junewoo-suk** [swagger-api/swagger-codegen#4234]
##### Description

DateTimeTypeAdapter class has a variable `private final DateTimeFormatter formatter = ISODateTimeFormat.dateTime();` but it should be `private final DateTimeFormatter formatter = ISODateTimeFormat.dateTimeParser();`. For example, dates like `yyyy-MM-ddTHH:mm:ssZ` will not be parsable in the current version, but it will be possible with dateTimeParser function. The previous date format is a default date format from InnoDB passed to Django models

##### Swagger-codegen version
2.2.1

##### Suggest a Fix
DateTimeTypeAdapter.java
`private final DateTimeFormatter formatter = ISODateTimeFormat.dateTime();`
to
`private final DateTimeFormatter formatter = ISODateTimeFormat.dateTimeParser();`

**Comment by junewoo-suk** [comment]
right now work around is using `setDateFormat`

**Comment by cbornet** [comment]
Yes, but:
* It would rather be dateOptionalTimeParser()
* dateTime() should probably still be used for serializing (as the time is not optional in rfc3339)

**Comment by cbornet** [comment]
Fixed by #4473

**Comment by wing328** [comment]
@junewoo-suk please pull the latest master to give it a try.

Thanks @kevinoid for the fix.

(we've just added Swagger Codegen to ProductHunt: https://www.producthunt.com/posts/swagger-codegen, pleae upvote when you've time)
