### ISSUE TITLE
[develop_2.0] PHP Server Generator

### ISSUE THREAD

**Issue by bennnjamin** [swagger-api/swagger-codegen#424]
Templates need to be ported over to develop_2.0 for PHP Server generator.

**Comment by wing328** [comment]
@bennnjamin is the template available anywhere that I can try to port over ?

**Comment by bennnjamin** [comment]
I believe it has been completed here: https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples/server-generator/php

This was the original template I was referencing: https://github.com/swagger-api/swagger-codegen/tree/master/samples/server-generator/php

If you can confirm, this could be closed.

**Comment by wing328** [comment]
@bennnjamin thanks, I'll look into that.

**Comment by wing328** [comment]
@bennnjamin I put back the templates with PR #882 

Please kindly take a look as I'm no expert in PHP Silex framework.

Let me know if you've any question/feedback.

**Comment by wing328** [comment]
@bennnjamin the PR has been merged. Please checkout the latest develop_2.0.

We'll close this task if you do not have further questions about the template.

**Comment by bennnjamin** [comment]
Thank you.

**Comment by wing328** [comment]
@bennnjamin no problem. Please kindly perform some tests and we can work together to address issues, if any.
