### ISSUE TITLE
Type change for maximum property value in swagger.yml generated with python-flask-server

### ISSUE THREAD

**Issue by yucer** [swagger-api/swagger-codegen#4248]
##### Description

There is an attribute [maximum](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.2) in the [OpenAPI v2.0 specification ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) that restricts the higher value that a property field can have.

The type defined for this maximum value is "number". 

When specifying an int32 property the maximum value is an integer constant, but the `swagger/swagger.yml` file generated within the python-flask-server code presents the constant value as a float number. 

The server can not start, raising this error:

```bash
$ python3 app.py 
Traceback (most recent call last):
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: '9.99999999E8' is not of type 'number'

Failed validating 'type' in schema['properties']['definitions']['additionalProperties']['properties']['properties']['additionalProperties']['properties']['maximum']:
    {'type': 'number'}

On instance['definitions']['pet']['properties']['rv_account']['maximum']:
    '9.99999999E8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app.add_api('swagger.yaml', arguments={'title': 'A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification'})
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/connexion/app.py", line 149, in add_api
    debug=self.debug)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/connexion/api.py", line 109, in __init__
    validate_spec(spec)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/validator20.py", line 82, in validate_spec
    http_handlers=http_handlers)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/home/yucer/.virtualenvs/pet_server/lib/python3.5/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: '9.99999999E8' is not of type 'number'

Failed validating 'type' in schema['properties']['definitions']['additionalProperties']['properties']['properties']['additionalProperties']['properties']['maximum']:
    {'type': 'number'}

On instance['definitions']['pet']['properties']['rv_account']['maximum']:
    '9.99999999E8'
```

##### Swagger-codegen version

I am using the code from the master branch,  the last change sofar is:

```bash
commit 39ffc0ae6260cfc13b4dd6c3407ab4b3e7e2c6c2
Author: wing328 <wing328hk@gmail.com>
Date:   Wed Nov 16 16:38:15 2016 +0800
```

This seems to be a regression. I don't know which version of swagger-codegen is used by swagger-editor.io , but the online version generates it correctly. The following is the diff results between the code generated by the online version (`pet_server_online`) and the one generated from master (`pet_server`)

```bash
$ diff pet_server_online/swagger/swagger.yaml pet_server/swagger/swagger.yaml 
148c156
<         maximum: 999999999
---
>         maximum: 9.99999999E8
```

##### Swagger declaration file content or url

Take one of the pets examples and modify the `pet` object like this:

```yaml
definitions:
  pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      rv_account:
        type: integer
        format: int32
        description: rv_account
        maximum: 999999999
        maxLength: 9        
      tag:
        type: string 
```

the original file is the sample *Swagger Petstore (Simple)* from [Swagger Editor](http://editor.swagger.io/)

##### Command line used for generation

./run-in-docker.sh generate -i /gen/specs/pets.yml -l python-flask-server -o /gen/specs/pet_server -c /gen/specs/pets.cfg

Both the `.cfg` and `.yml` files were copied to a new folder inside the `swagger-codegen` they are attached here:
[pet.zip](https://github.com/swagger-api/swagger-codegen/files/609478/pet.zip)

##### Steps to reproduce

```bash
pip install connexion==1.0.129
cd pet_server
python3 app.py
```

**Comment by cbornet** [comment]
What is the value of maximum in the generated swagger/swagger.yaml file ? Is it still 999999999 ?

**Comment by yucer** [comment]
No, now it has changed to: 

```yaml
maximum: 9.99999999E8
```

It seems a regression, but I couldn't find where. Somehow the `number` type of `maximum` in the [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) is being used for the yml generation.

**Comment by cbornet** [comment]
Well, technically 9.99999999E8 is a valid number value but it seems it's not accepted by the python jsonschema validator.

**Comment by yucer** [comment]
Some observations:

1. In previous versions there was a clean generation, the value was kept as it was provided in the original spec. So why does it occurs now ?

2. The [json-schema](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.2) spec doesn't say that this value should be of the same domain that of the property value. The integer value could also be converted to float and compared with the maximum's float value.

**Comment by wing328** [comment]
@yucer I'm working on a fix for this. Will keep you posted.

**Comment by yucer** [comment]
Further information, in case it helps:

The same error raises when the field is of type: `decimal`. Which is rare, because decimal can have a floating point. For example, it does happen with a property defined like this:

```yaml
      transaction_amount:
        type: "number"
        format: "decimal"
        minimum: 10000.00
        maximum: 9999999999.99 
```

we get again:

`swagger_spec_validator.common.SwaggerValidationError: '9.9999999999E8' is not of type 'number'`

Also I did find this [statement](http://json-schema.org/latest/json-schema-validation.html#rfc.section.3.2) relevant.

**Comment by wing328** [comment]
@yucer FYI. I fixed the max and min mustache tag with https://github.com/swagger-api/swagger-codegen/pull/4335. I don't think the PR will fix this issue as well but worth giving a try anyway if you've time.

**Comment by wing328** [comment]
@yucer it should be fixed with the latest master. Please give it a try.
