### ISSUE TITLE
[JAVA] Support for Retrofit2 client generation with Play! Async WS http-client

### ISSUE THREAD

**Issue by lukoyanov** [swagger-api/swagger-codegen#4250]
##### Description

Seems no support for retrofit2 client that use Play's WS as a http-client. I could contribute a generator for play 2.4.

**Comment by wing328** [comment]
@lukoyanov thanks! Let us know if you need help or any starting point to begin the contribution.

**Comment by wing328** [comment]
FYI. Currently, Java API client already supports Retrofit2 (in additional to jersey1.x, jersey2.x, feign, etc). You may want to add the support by adding another option (e.g. usePlayWS) similar to [`parcelableModel`](https://github.com/swagger-api/swagger-codegen/pull/3928).

For a full list of Java API options, please run java -jar `modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java`

**Comment by lukoyanov** [comment]
I've opened a PR core implementation + api key auth. https://github.com/swagger-api/swagger-codegen/pull/4263

**Comment by lukoyanov** [comment]
Created new PR, with proper history https://github.com/swagger-api/swagger-codegen/pull/4270

**Comment by wing328** [comment]
@lukoyanov thanks. I've left you some comments. Please let me know if you need help adding the Petstore samples with the enhancement you provided.

**Comment by lukoyanov** [comment]
@wing328 PR updated.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/4270. Thanks for the PR from @lukoyanov

**Comment by wing328** [comment]
@lukoyanov when you've time, I wonder i you can look at the issue when upgraing retrofit2 to the latest version 2.2.0 as found in https://github.com/swagger-api/swagger-codegen/pull/5235

**Comment by lukoyanov** [comment]
@wing328 I'll take a look in a few days.
