### ISSUE TITLE
[Python]Do python client support the header in response?

### ISSUE THREAD

**Issue by WillaLuo** [swagger-api/swagger-codegen#4253]
##### Description
The header "set-cookie" in response defined "string", when it is send with the response about more than one thousand letter, can it be supported? When I use this definition to generate python client, the header "set-cookie" can't be found.

##### Swagger-codegen version
Swagger-codegen 2.2.1

##### Swagger declaration file content or url

 ```json
    "responses": {
                    "204": {
                        "headers": {
                            "set-cookie": {
                                "type": "string",
                                "description": "This is the Cookie, has more than one thousand letter"
                            }
                        },
                        "description": "No Content. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."
                    }
                    
                }
    ```

**Comment by WillaLuo** [comment]
I found a workaround with using "_with_http_info" to get the response header, can found "set-cookie" in it.
But I still have a question, does swagger-codegen support the definition here?:
'''
"responses": {
                   "204": {
                       "headers": {
                           "set-cookie": {
                               "type": "string",
                               "description": "This is the Cookie, has more than one thousand letter"
                           }
                       },
                       "description": "No Content. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."
                   }
                   
               }
'''
Thanks!

**Comment by wing328** [comment]
@WillaLuo yes, _with_http_info can return the response headers as well.

The spec you provided looks correct: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#headerObject but I don't think swagger codegen (python or other API clients) support `set-cookie` in particular at the moment.
