### ISSUE TITLE
[JavaScript] Support for cache bursting 

### ISSUE THREAD

**Issue by Danielku15** [swagger-api/swagger-codegen#4254]
##### Description

The Internet Explorer has the bad habbit to cache Ajax GET requests. There are many blog posts in the internet reporting about this problem. 
http://thisinterestsme.com/ajax-request-internet-explorer-cache/
http://www.sitecrafting.com/blog/ajax-ie-caching-issues/
http://stackoverflow.com/questions/4303829/how-to-prevent-a-jquery-ajax-request-from-caching-in-internet-explorer

jQuery has a special cache parameter that will ensure that an additional timestamp value is added to the GET parameters. This way the URL is always different and IE has no chance of caching anything. We need such a parameter in the generated JS client. 

##### Swagger-codegen version

2.2.0

##### Suggest a Fix

My recommendation would be to extend the [`buildUrl` Method](https://github.com/swagger-api/swagger-codegen/blob/5f372ef15e1bac0127b61562b6c2db699ae07743/modules/swagger-codegen/src/main/resources/Javascript/ApiClient.mustache#L94)  to generate the same timestamp parameter as jQuery.  A new property `cache` on the ApiClient could control the generation.

**Comment by wing328** [comment]
Closed via #4255
