### ISSUE TITLE
[PHP][Silex] Generated parameters don't use same naming conventions as path variables

### ISSUE THREAD

**Issue by PisaJan** [swagger-api/swagger-codegen#4257]
##### Description

PHP SILEX server generator doesn't use same naming conventions for path variables and function parameters.

 Eg. like this:

`$app->GET('/pet/{petId}', function(Application $app, Request $request, $pet_id)`

When trying to GET that URI, you get:

```
RuntimeException in ControllerResolver.php line 126:
Controller "Closure" requires that you provide a value for the "$pet_id" argument (because there is no default value or because there is a non optional argument after this one).
```

##### Swagger-codegen version

swagger: '2.0'
info:
  version: 1.0.0
  title: PetStore on Heroku

##### Swagger declaration file content or url

I am using defalt Pet store example.

**Comment by wing328** [comment]
@PisaJan thanks for reporting the issue. Are you saying that the variable `$per_id` should have named as `$petId` instead?

**Comment by PisaJan** [comment]
@wing328 Happy to help. Yes, exactly. Otherwise Silex is not able to pair path variables to parameters.

**Comment by arnested** [comment]
I can confirm that as well (although I never got around to debugging it or reporting it).

**Comment by wing328** [comment]
@PisaJan @arnested so a workaround is not to rename variable to snake case and just keep the original naming?

We can introduce the following options (currently used by Typescript):
````
    modelPropertyNaming
        Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name (Default: camelCase)
```

**Comment by PisaJan** [comment]
@wing328 I guess so, it's working fine for: 
`$app->GET('/pets/{petId}', function(Application $app, Request $request, $petId)`
So you just need to use same naming convention for path and for function.

**Comment by wing328** [comment]
@PisaJan may I know if you've time to add `modelPropertyNaming` to PHP Slim generator? 

For reference, here is the PR to add `modelPropertyNaming` for Scala:https://github.com/swagger-api/swagger-codegen/pull/3685

**Comment by PisaJan** [comment]
@wing328 I am sorry, but I am currently working for the company and my personal time schedule is also a little busy.

**Comment by paulmasri** [comment]
If you've been foolish/naive enough to have used PascalCase, you get the same issue.
e.g. `$app->GET('/pet/{PetId}', function(Application $app, Request $request, $pet_id)`

**Comment by wing328** [comment]
@PisaJan @paulmasri I should be able to fix it (with a workaround using the original name of the parameter). Would you have time to help test the fix?

**Comment by PisaJan** [comment]
@wing328 Sure :-)

**Comment by wing328** [comment]
I've filed https://github.com/swagger-api/swagger-codegen/pull/4817 to workaround the issue.

I think an ideal fix is to loop through all endpoints and caemlize the variables in the path e.g. rename {pet_id} with {petId} (camelized).

To test:
```
git checkout -b wing328-silex_fix_path_name master
git pull https://github.com/wing328/swagger-codegen.git silex_fix_path_name
```

**Comment by paulmasri** [comment]
@wing328 Sorry I can't offer to check right now. Does your fix handle the related situation of converting hyphens to underscores (which I've just discovered)?
e.g. `$app->GET('/pet/{pet-id}', function(Application $app, Request $request, $pet_id)`

**Comment by wing328** [comment]
@paulmasri unfortunately nope (that's why I said it's more of a workaround)

**Comment by wing328** [comment]
@PisaJan @paulmasri I've fixed the issue by going through all the path, extract the variable inside `{...}` and camelize it. Please give it a try:
```
git checkout -b wing328-silex_fix_path_name master
git pull https://github.com/wing328/swagger-codegen.git silex_fix_path_name
```

**Comment by PisaJan** [comment]
@wing328 Hi, I am sorry I was swamped with bunch of other stuff, but I will take a look at it this weeekend.

**Comment by wing328** [comment]
@PisaJan np. PR merged into master. Please pull the latest master to give it a try.

**Comment by PisaJan** [comment]
@wing328 It works for me now. Thanks!
