### ISSUE TITLE
develop-2.0: Failed to resolve dependencies

### ISSUE THREAD

**Issue by gtinjr** [swagger-api/swagger-codegen#428]
I am getting the following error when running
    
     mvn package

on the development 2.0 branch

[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ........................... SUCCESS [5.685s]
[INFO] swagger-codegen (core library) .................... FAILURE [16.533s]

Failed to execute goal on project swagger-codegen: Could not resolve dependencies for project com.wordnik:swagger-codegen:jar:2.1.0-SNAPSHOT: The following artifacts could not be resolved: io.swagger:swagger-parser:jar:1.0.0-SNAPSHOT, io.swagger:swagger-legacy-spec-parser:jar:1.0.0-SNAPSHOT, com.wordnik:swagger-core:jar:1.5.0-SNAPSHOT

**Comment by fehguy** [comment]
Hi, we need sonatype snapshots added back in the build.  I believe I took it out, which is a mistake.

**Comment by fehguy** [comment]
added back:

https://github.com/swagger-api/swagger-codegen/commit/95155f07d8c20b71f8c3d18a5df4c0f361416efc

Please pull the branch again
