### ISSUE TITLE
General Question: Get a list of languages

### ISSUE THREAD

**Issue by poing** [swagger-api/swagger-codegen#4288]
I am looking for a list of the supported output languages BEFORE installing.  I don't want to install, then find it's not useful for my needs.

After browsing swagger.io where is only says I can run a command to generate a list, I found myself on GitHub.  Again presented with, there's a command to get a list.  But no list can be found WITHOUT installing.

**Comment by fehguy** [comment]
Sure, well you can look at the project:

https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages

Or use the web service to output the list:

```
http://generator.swagger.io/api/gen/clients
[
  "akka-scala",
  "android",
  "async-scala",
  "clojure",
  "cpprest",
  "csharp",
  "CsharpDotNet2",
  "cwiki",
  "dart",
  "dynamic-html",
  "flash",
  "go",
  "groovy",
  "html",
  "html2",
  "java",
  "javascript",
  "javascript-closure-angular",
  "jaxrs-cxf-client",
  "jmeter",
  "objc",
  "perl",
  "php",
  "python",
  "qt5cpp",
  "ruby",
  "scala",
  "swagger",
  "swagger-yaml",
  "swift",
  "swift3",
  "tizen",
  "typescript-angular",
  "typescript-angular2",
  "typescript-fetch",
  "typescript-node"
]
```
and
```
http://generator.swagger.io/api/gen/servers
[
  "aspnet5",
  "aspnetcore",
  "erlang-server",
  "go-server",
  "haskell",
  "inflector",
  "jaxrs",
  "jaxrs-cxf",
  "jaxrs-cxf-cdi",
  "jaxrs-resteasy",
  "jaxrs-spec",
  "lumen",
  "msf4j",
  "nancyfx",
  "nodejs-server",
  "python-flask",
  "rails5",
  "scalatra",
  "silex-PHP",
  "sinatra",
  "slim",
  "spring",
  "undertow"
]
```

This is OSS so you can add your $.02 by submitting a pull request and/or specific documentation suggestion, the community would appreciate it.
