### ISSUE TITLE
Can I ask if Swagger Codegen support Bean Validation 1.0 JSR-303 for Model definition in Java implementation?

### ISSUE THREAD

**Issue by beingcoder** [swagger-api/swagger-codegen#4319]
##### Description

I tried , looks like it does not support Bean Validation,  can you please conform?  thanks

**Comment by wing328** [comment]
@beingcoder are you using the latest master? I believe some works have already been done related to support Java bean validation in the models.

**Comment by fehguy** [comment]
answered by @wing328
