### ISSUE TITLE
https://generator.swagger.io/#/ generates bad zip files

### ISSUE THREAD

**Issue by Richard210363** [swagger-api/swagger-codegen#4321]
##### Description

I was looking to add swagger-codegen to my C# project so I looked at the example page at https://generator.swagger.io/#/

I notice that when I generate code (I tried Java, CsharpDotNet2 and csharp) that the created zip files are invalid and won't open.  ( I tried 7-zip and Windows 7)  .  7-zip reports CRC errors and Windows 7 says the archives are corrupt.

##### Steps to reproduce

Open https://generator.swagger.io/#/
Use POST /gen/clients/{language}      for any Java, CsharpDotNet2 or csharp
Note the returned "code"
Use GET /gen/download/{fileId}         with the code from above 
Click the link under Response Body
A zip file downloads.
Try to open the zip file.                      it is corrupt.

**Comment by wing328** [comment]
@Richard210363 I did a test with Petstore (full) example and could unzip the C# SDK without issue.

(editor.swagger.io leverages https://generator.swagger.io to generate codes and generator.swagger.io is powered by this project - swagger codegen)

**Comment by Richard210363** [comment]
OK.  I've now tried on 3 PC and 2 different networks and I still get a corruption error with both Windows 7 and 7Zip.
I'm downloading the zip- at the end of the Response Body link.

**Comment by wing328** [comment]
What browser are you using? I did the test with Chrome.

As a workaround, you can use Swagger Codegen CLI (Java JAR) locally in your machine: https://github.com/swagger-api/swagger-codegen#prerequisites

**Comment by Richard210363** [comment]
I tried Chrome as well.
Re the link you gave, thanks but I don't really want to waste time installing it when the example on the web fails.

**Comment by wing328** [comment]
> I'm downloading the zip- at the end of the Response Body link.

I don't need to manually extract the link from the response body. Chrome does it for me. Is that your experience as well?

**Comment by Richard210363** [comment]
I use the link as displayed in the SwaggerUI response.
Chrome then downloads the file.

**Comment by wing328** [comment]
Can you try https://editor.swagger.io instead to generate the SDK?

**Comment by wing328** [comment]
Here is the test I did with `curl`, which works as expected:
```
/tmp|⇒ curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' https://generator.swagger.io/api/gen/clients/ruby
{"code":"ce210954-0745-4833-bff6-84425770e4d0","link":"https://generator.swagger.io/api/gen/download/ce210954-0745-4833-bff6-84425770e4d0"}%                                   /tmp|⇒ wget https://generator.swagger.io/api/gen/download/ce210954-0745-4833-bff6-84425770e4d0
--2016-12-05 23:31:02--  https://generator.swagger.io/api/gen/download/ce210954-0745-4833-bff6-84425770e4d0
Resolving generator.swagger.io... 23.22.16.221
Connecting to generator.swagger.io|23.22.16.221|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65164 (64K) [application/zip]
Saving to: ‘ce210954-0745-4833-bff6-84425770e4d0’

100%[=====================================================================================================================================>] 65,164       290KB/s   in 0.2s   

2016-12-05 23:31:03 (290 KB/s) - ‘ce210954-0745-4833-bff6-84425770e4d0’ saved [65164/65164]

/tmp|⇒ unzip ce210954-0745-4833-bff6-84425770e4d0                                              
Archive:  ce210954-0745-4833-bff6-84425770e4d0
  inflating: ruby-client/.rspec      
  inflating: ruby-client/git_push.sh  
  inflating: ruby-client/LICENSE     
  inflating: ruby-client/docs/PetApi.md  
  inflating: ruby-client/docs/Category.md  
  inflating: ruby-client/docs/Tag.md  
  inflating: ruby-client/docs/UserApi.md  
  inflating: ruby-client/docs/Order.md  
  inflating: ruby-client/docs/StoreApi.md  
  inflating: ruby-client/docs/ApiResponse.md  
  inflating: ruby-client/docs/User.md  
  inflating: ruby-client/docs/Pet.md  
  inflating: ruby-client/swagger_client.gemspec  
  inflating: ruby-client/README.md   
  inflating: ruby-client/.gitignore  
  inflating: ruby-client/spec/api/pet_api_spec.rb  
  inflating: ruby-client/spec/api/user_api_spec.rb  
  inflating: ruby-client/spec/api/store_api_spec.rb  
  inflating: ruby-client/spec/configuration_spec.rb  
  inflating: ruby-client/spec/spec_helper.rb  
  inflating: ruby-client/spec/models/category_spec.rb  
  inflating: ruby-client/spec/models/pet_spec.rb  
  inflating: ruby-client/spec/models/tag_spec.rb  
  inflating: ruby-client/spec/models/order_spec.rb  
  inflating: ruby-client/spec/models/api_response_spec.rb  
  inflating: ruby-client/spec/models/user_spec.rb  
  inflating: ruby-client/spec/api_client_spec.rb  
  inflating: ruby-client/.swagger-codegen-ignore  
  inflating: ruby-client/lib/swagger_client/api/store_api.rb  
  inflating: ruby-client/lib/swagger_client/api/user_api.rb  
  inflating: ruby-client/lib/swagger_client/api/pet_api.rb  
  inflating: ruby-client/lib/swagger_client/api_client.rb  
  inflating: ruby-client/lib/swagger_client/version.rb  
  inflating: ruby-client/lib/swagger_client/models/pet.rb  
  inflating: ruby-client/lib/swagger_client/models/user.rb  
  inflating: ruby-client/lib/swagger_client/models/order.rb  
  inflating: ruby-client/lib/swagger_client/models/tag.rb  
  inflating: ruby-client/lib/swagger_client/models/api_response.rb  
  inflating: ruby-client/lib/swagger_client/models/category.rb  
  inflating: ruby-client/lib/swagger_client/api_error.rb  
  inflating: ruby-client/lib/swagger_client/configuration.rb  
  inflating: ruby-client/lib/swagger_client.rb  
```

**Comment by Richard210363** [comment]
I don't have CURL (windows) and my users wouldn't want to get the code that way anyway.

I'm not sure what I am to do in the editor to resolve this problem?

**Comment by wing328** [comment]
> I'm not sure what I am to do in the editor to resolve this problem?

editor.swagger.io is another GUI for generator.swagger.io. Instead of using the swagger-ui that comes with generator.swagger.io, you can use editor.swagger.io instead to generate Java, C# SDK.

**Comment by fehguy** [comment]
Please reopen if you're still having troubles.  We have 10's of thousands of downloads per day onto windows machines without corruption issues.
