### ISSUE TITLE
header parameters are not included on http request (typescript/angular2)

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#4322]
##### Description

I've generated my client using typescript2/angular2 language.

I'm not able to figure out what's been generated and how to use the artifacts.

As far I've been able to figure out, headers are not included on request in `create` method (`user` and `passwd` parameters). Otherwise, I don't understand how requests are made. I've set a breakpoint inside `map` method callback and it's never reached.

##### Swagger-codegen version

latest.

**Comment by wing328** [comment]
@jeusdi I believe the latest master has better support for header parameters in TS Angular2 API client. Please pull the latest master to give it a try.

**Comment by jeusdi** [comment]
Is there some repository showing how to use these artifacts?

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen#getting-started is a good starting point to build the JAR locally.

**Comment by jeusdi** [comment]
I meant a repository sample using typescript/angular2 code generated...

**Comment by www2k** [comment]
@wing328 @sebastianhaas 

Let me explain why this happens.

[typescript-angular2/api.mustache (2.2.1, latest release)](https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache)
[typescript-angular2/api.mustache (master, 87cb779fd465a0ba50cfd55684ed56fe7bbcddd8)](https://github.com/swagger-api/swagger-codegen/blob/87cb779fd465a0ba50cfd55684ed56fe7bbcddd8/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache)

`v2.2.1` uses `headerParams` but `master` uses `headers` instead.
However `SwaggerOperation` does not have `headers` so any header params are not included in `master`.

This change was made by the PR of [Angular2 rc5](https://github.com/swagger-api/swagger-codegen/pull/3603/files#diff-174bce348e2584ed556f2d1ce0714665L60).

**Comment by jeusdi** [comment]
Thanks @wing328 . Currently, I'm using a stable releases on angular2 (2.2.4). I don't quite understand what would I do from now on.  Could you you suggest me any steps in order to clean it up?

**Comment by sebastianhaas** [comment]
Thanks for the clarification @www2k. Sorry seems like I messed up there. I provided fixes for both the current `master` and the `2.3.0` branch in #4328 and #4329.

@jeusdi you could try to checkout #4328 run `mvn package` and see if your issue is resolved.

**Comment by jeusdi** [comment]
Currently I'm in `master` branch. Do you suggest me I checkout `2.3.0` branch and rebuid the package? What do you mean with `checkout #4328`?

**Comment by sebastianhaas** [comment]
Use git to checkout https://github.com/sebastianhaas/swagger-codegen/tree/fix4322. You can rebuild the package then and see if my fix works for you.

**Comment by jeusdi** [comment]
It seems it's working file by now (headers are added on request). Nevertheless, I'm detecting the request method it's sending has an `OPTIONS` method instead of `PUT`... Any ideas?

**Comment by sebastianhaas** [comment]
So you can confirm my fix is working for you?

Do you have `OPTIONS` as HTTP method generated in your Typescript API or in your browser network tab? In the latter case, it's most likely a CORS preflight request. https://www.w3.org/TR/cors/

**Comment by wing328** [comment]
FYI. Fixes by @sebastianhaas  merged into master and 2.3.0 branch. Please pull the latest to give it a try.

Thanks @sebastianhaas for the quick fix.

**Comment by wing328** [comment]
@jeusdi may I know if you've a chance to test the latest master to confirm it's no longer an issue?

**Comment by jeusdi** [comment]
[Here](https://gist.github.com/jeusdi/062aa6932596fbbce355689e2e660bb6) you can find the code codegen generates for User endpoint and it's the only code I'm using. I'm not able to see any `OPTIONS` request. Are you suggesting me the problem is related with any server configuration or any browser configuration...?

**Comment by jeusdi** [comment]
I've just checkedout `2.3.0` branch either on `swagger-codegen` and on `sebastianhaas\swagger-codegen` repositories. It seems headers are not loaded on request:

```
/**
     * User exists
     * 
     * @param user username
     */
    public existsWithHttpInfo(user: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/users`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'user' is not null or undefined
        if (user === null || user === undefined) {
            throw new Error('Required parameter user was null or undefined when calling exists.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }
```

**Comment by jeusdi** [comment]
It seems to be well integrated.
Thanks.

**Comment by kedzoo** [comment]
swagger-typescript-api(13.0.3),npm/10.2.5 node/v20.10.0 win32 x64 workspaces/false,debug mode DISABLED

**Comment by kedzoo** [comment]
same problem for httpClientType: 'fetch'
swagger-typescript-api(13.0.3),npm/10.2.5 node/v20.10.0 win32 x64 workspaces/false,debug mode DISABLED
