### ISSUE TITLE
a new go-resty client is created per request.

### ISSUE THREAD

**Issue by antihax** [swagger-api/swagger-codegen#4323]
##### Description
Go Client is creating a new go-resty client (and thus http.Client) per request which is inefficient and preventing KeepAlive from functioning.

##### Swagger-codegen version
2.3.0 HEAD

##### Suggest a Fix
Move client and services to APIClient.

**Comment by wing328** [comment]
@antihax I agree with you that it's inefficient and ideally it should be refactored to share the same go-resty client across requests.

**Comment by antihax** [comment]
see #4440

**Comment by antihax** [comment]
#5037 also resolves this issue.

**Comment by antihax** [comment]
Resolved in 2.3.0

**Comment by wing328** [comment]
@antihax FYI. Add you as the template creator in https://github.com/swagger-api/swagger-codegen/blob/master/README.md#template-creator
