### ISSUE TITLE
JavaJaxRS spec : formParam uses Attachment which is CXF specific

### ISSUE THREAD

**Issue by RaphC** [swagger-api/swagger-codegen#4327]
##### Description

When using JavaJaxRS to generate API with an endpoint consuming a form to upload a file, the plugin  translate file param data type in Attachment (org.apache.cxf.jaxrs.ext.multipart.Attachment) which is a CXF class. If we use another JaxRS implementation the compilation of generated API failed. The choice should be depends on JAX-RS  implementation

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/formParams.mustache

##### Suggest a Fix

:(. My question is : Is it possible to detect Jax-rs implementation, choose it and generation a dynamic datatype ?

**Comment by wing328** [comment]
> :(. My question is : Is it possible to detect Jax-rs implementation, choose it and generation a dynamic datatype ?

Not that I'm aware of

**Comment by jfiala** [comment]
I also came across this with #4091, currently the generated sources cause compilation errors as org.apache.cxf.jaxrs.ext.multipart.Attachment is not on the build path.

**Comment by jfiala** [comment]
Please see #4509 for the fix of the Multipart, in fact this is not standardized yet (https://java.net/jira/browse/JAX_RS_SPEC-413), so I replaced it with InputStream to be at least not CXF-dependent for the JAXRS-spec.

**Comment by wing328** [comment]
Please continue the discussion in https://github.com/swagger-api/swagger-codegen/issues/4509

**Comment by moshelav** [comment]
on which version this fix included in?

**Comment by wing328** [comment]
@moshelav please pull the latest master and see if you still encounter the issue.
