### ISSUE TITLE
[JAXRS-CXF] Wrong return type when returning arrays

### ISSUE THREAD

**Issue by MatanRubin** [swagger-api/swagger-codegen#4330]
##### Description
I have a swagger definition file where the response for `listBooks` contains an array of `Book`s. 
When generating static HTML documentation everything looks fine - the return type of the method is `array[Book]`:
![swagger-html](https://cloud.githubusercontent.com/assets/4488227/20928143/1838401c-bbcd-11e6-83d6-c2052243cadb.PNG)

Similarly, when generating JAVA code the return type for that method is `List<Book>`:
```java
    /**
     * List Books
     * 
     * @return List&lt;Book&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<Book> listBooks() throws ApiException {
        ApiResponse<List<Book>> resp = listBooksWithHttpInfo();
        return resp.getData();
    }
```

However, when generating an interface using JAXRS-CXF, the return type for the same method is `Book` instead of `List<Book>`:
```java
@Path("/")
@Api(value = "/", description = "")
public interface DefaultApi  {

    @GET
    @Path("/books")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "List Books", tags={  })
    public Book  listBooks();
}
```

##### Swagger-codegen version
2.2.2-SNAPSHOT

##### Swagger declaration file
```yaml
---
swagger: "2.0"
info:
  version: "1.0.2"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
paths:
  /books:
    get:
      summary: "List Books"
      description: ""
      operationId: "listBooks"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
definitions:
  Book:
    type: "object"
    properties:
      Author:
        type: "string"
      Length:
        type: "integer"
```

##### Command line used for generation

Generate HTML:
```
 java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ./tmp/swagger.yaml -l html -o ./tmp/output/
```

Generate JAVA:
```
 java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ./tmp/swagger.yaml -l java -o ./tmp/output/
```

Generate JAXRS-CXF:
```
 java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ./tmp/swagger.yaml -l jaxrs-cxf -o ./tmp/output/
```

**Comment by wing328** [comment]
@MatanRubin thanks for reporting the issue. May I know if you've time to contribute the fix? If yes, I can show you some good starting points.

**Comment by MatanRubin** [comment]
Hey @wing328, thanks for confirming this is a bug. I spent some time debugging the issue and I think I have a fix. Will create a PR soon.

**Comment by MatanRubin** [comment]
PR for this issue can be found here: #4339

**Comment by wing328** [comment]
#4339 merged into master. Thanks for the fix from @MatanRubin
