### ISSUE TITLE
[Swift3]swift build fail.

### ISSUE THREAD

**Issue by GuangLinLau** [swagger-api/swagger-codegen#4336]
Hello,

 language: Swift3/library:RxSwift

`        return Observable.create { observer -> Disposable in
            HiddenDanger(id: id, action: action) { data, error in
                if let error = error {
                    observer.on(.error(error as Error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return NopDisposable.instance
        }`

NopDisposable.instance is error. i search for google maybe replace to "Disposables.create()".

Command line used for generation

Thinks.

**Comment by chomatdam** [comment]
```
/**
    Singleton instance of `NopDisposable`.
    */
    @available(*, deprecated, renamed: "Disposables.create()")
    public static let instance: Disposable = NopDisposable()
```

**Comment by wing328** [comment]
Looks like @chomatdam has explained the error.

@GuangLinLau let us know if you still encounter issue with the Swift3 client.
