### ISSUE TITLE
[JAVA] classes extending from Serializable classes have no servialVersionId [low prio]

### ISSUE THREAD

**Issue by joergi77** [swagger-api/swagger-codegen#4351]
##### Description

Some classes, which are generated by swagger code-gen, are extending some serializable classes:
`public class MyClass extends HashMap<String, String> `

and if I look at the extended `HashMap<String, String>`, I can see it should be serializeable.
`public class HashMap<K,V> extends AbstractMap<K,V> implements Map<K,V>, Cloneable, Serializable `

In all generated classes is the serialVersionUID, something like the following missing:
`private static final long serialVersionUID = -2410670077461289444L;`

##### Swagger-codegen version

Version 2.2.1

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.1.jar generate -i tmp/name.swagger.yaml -l java -o tmp/client/ --additional-properties modelPropertyNaming=original

**Comment by wing328** [comment]
Did you switch on the `	serializableModel` flag when generating the code?
```
	serializableModel
	    boolean - toggle "implements Serializable" for generated models (Default: false)
```
To show all options, please run `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java`

**Comment by joergi77** [comment]
okay, I have used it without the option `--additional-properties serializableModel=true`
But if I do it with the option, the `private static final long serialVersionUID = -2410670077461289444L;` is still missing and will be shown in my IDE as a warning.

**Comment by wing328** [comment]
Have you pull the latest master? The change was made recently.

**Comment by joergi77** [comment]
Allright, checked out the newest version (branch Master) - but still no auto generated serialVersionUID in my code.....

**Comment by wing328** [comment]
Here is the code: https://github.com/swagger-api/swagger-codegen/blob/7a97c3c37554a4a2cd7919e8ef0ff83d192f0bdf/modules/swagger-codegen/src/main/resources/Java/pojo.mustache#L8

Have you run `mvn clean package` to rebuild the JAR before generating the code again?

**Comment by joergi77** [comment]
@wing328 , yes, i have done it before...
other question:  i have generated my code with  it with `-additional-properties serializableModel=true` but it only added my `implements Serializable`.   
How do you generate it with this behaviour?

**Comment by wing328** [comment]
@joergi77 here is the command I used:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml \
  -l java -DserializableModel=true\
  -o /var/tmp/java/serializableModel2/
```

**Comment by joergi77** [comment]
ah... okay, i used it wrong...   
but if i use now the `-DserializableModel=true` the `-DhideGenerationTimestamp=true` is not working anymore..

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml \
  -l java -DserializableModel=true -DhideGenerationTimestamp=true \
  -o /var/tmp/java/serializableModel2/
```

do you see where the problem is?

**Comment by wing328** [comment]
What about just `-DserializableModel=true,hideGenerationTimestamp=true`?

**Comment by wing328** [comment]
(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Comment by joergi77** [comment]
thanks a lot, the adding with `,` worked

**Comment by wing328** [comment]
No problem
