### ISSUE TITLE
String with custom format to generate different controller param type

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-codegen#4353]
##### Description

Can't use custom format to change controller parameter to be different type.

For example:
```yaml
      parameters:
        - name: job
          type: string
          format: job
          in: query
          description: The job to run this operation inside of
```
If I try to run the CLI with these type mappings:
```xml
<type-mappings>job=Job</type-mappings>
```
The controller still generates as a `String`

##### Swagger-codegen version

`v2.2.1`

##### Swagger declaration file content or url

```yaml
paths:
    post:
      description: |
        Adds a port to this switch.
      parameters:
        - name: job
          type: string
          format: job
          in: query
          description: The job to run this operation inside of
          required: false
        - name: port
          in: body
          schema:
            $ref: '#/definitions/Port'
      responses:
        200:
          schema:
            $ref: '#/definitions/Port'
```

##### Command line used for generation

```xml
<language>io.swagger.codegen.languages.SpringCodegen</language>
<configOptions>
  <sourceFolder>src/gen/java</sourceFolder>
  <interfaceOnly>true</interfaceOnly>
  <java8>true</java8>
  <type-mappings>job=Job</type-mappings>
  <import-mappings>Job=com.company.core.domain.job.Job</import-mappings>
</configOptions>
```

##### Suggest a Fix

Should there be a way to declare in the CLI  that if a string with a specific format is seen then to have its type replaced in the generated controller?

I was hoping to leverage this in combination with:
```java
org.springframework.web.method.support.HandlerMethodArgumentResolver
```
to convert the query parameter into a concrete type.

**Comment by wing328** [comment]
@JLLeitschuh Is `Job` a model/object?

**Comment by JLLeitschuh** [comment]
No, internally, a `Job` is an interface.
Currently, in our non swagger controllers we just add a `Job` as a parameter to the controller and our existing `HandlerMethodArgumentResolver` maps the `job` query param (represented as a UUID across the wire) to the `Job` instance.

Basically, our users would be passing in the `UUID` for a job but in our controllers we want to use the `HandlerMethodArgumentResolver` to map the UUID to a `Job`.

I don't know if we are stretching the swagger spec beyond its originally intended purpose but this would allow us to generate much simpler controllers that would reduce the amount of boilerplate code required to look up a `Job` in a service before using it.

**Comment by JLLeitschuh** [comment]
This works absolutely fine for `UUID`
```yaml
paths:
    post:
      description: |
        Adds a port to this switch.
      parameters:
        - name: job
          type: string
          format: uuid
          in: query
          description: The job to run this operation inside of
          required: false
        - name: port
          in: body
          schema:
            $ref: '#/definitions/Port'
      responses:
        200:
          schema:
            $ref: '#/definitions/Port'
```
I can say `<type-mappings>UUID=ComapnyUuid</type-mappings>` and the controller is generated correctly with the parameter `uuid` having the type `CompanyUuid`

**Comment by JLLeitschuh** [comment]
I would be willing to look into making a PR that would make this work for everyone.
Otherwise I'd have to make a 1 off for our company's particular use case.

**Comment by fehguy** [comment]
If you have time to share more about this, please feel free to reopen.
