### ISSUE TITLE
[Golang Client] definition of a single type string has not the correct type

### ISSUE THREAD

**Issue by paulvollmer** [swagger-api/swagger-codegen#4355]
##### Description
the generated struct is not correct
if i create a definition like this:
```
definitions:
  StructString:
    type: string
    description: "only a string..."
```

the generated struct looks like this:

```
// only a string...
type StructString struct {
}
```

but i think it need code like this...
```
// only a string...
type StructString string
```

##### Swagger-codegen version
repo master and the version at the editor.swagger.io generator download

##### Steps to reproduce
copy the example code to the editor and generate the go client code.

```
swagger: '2.0'
info:
  version: 0.0.0
  title: golang client string struct issue

paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/StructString"

definitions:
  StructString:
    type: string
    description: "only a string..."
```

**Comment by wing328** [comment]
@paulvollmer I don't think $ref to primitive type is supported by the Swagger parser at the moment. Can you try defining `type: string` directly in the response schema instead?

($ref to model should still work as expected)

**Comment by paulvollmer** [comment]
> Can you try defining type: string directly in the response schema instead?

ok, this is a workaround... but the generated go code does not show the correct definition...

**Comment by fehguy** [comment]
@wing328 it should be working against parsing master

**Comment by wing328** [comment]
@paulvollmer please pull the latest master to give it another try. Let us know if you still experience the same issue.
