### ISSUE TITLE
[NODE-SERVER] Date stub value set with ISO8601 date-time format

### ISSUE THREAD

**Issue by crazyfrozenpenguin** [swagger-api/swagger-codegen#4359]
##### Description

Swagger stub generator for node stubs date fields with date-time format.

date           ISO8601 full-date	2016-04-01
date-time  ISO8601 date-time	2016-04-16T16:06:05Z

##### Swagger-codegen version

2.2.1

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i swagger.json -l nodejs-server -o stub

##### Steps to reproduce

Create a swagger endpoint with a format":"date" field. Generate stub using command above.

##### Related issues

None found

##### Suggest a Fix

The generated field should be a date (2000-01-23) not a date-time (2000-01-23T04:56:07.000+00:00).

**Comment by wing328** [comment]
@crazyfrozenpenguin thanks for reporting the issue. May I know if you've time to contribute the fix?

Can you also show what the actual (problematic) code looks like?

A good starting point maybe is to define `typeMapping` in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java similar to [this](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java#L123-L143)

**Comment by bmsantos** [comment]
@wing328, I've submitted a fix for this. It was simpler than initially thought.

**Comment by wing328** [comment]
Thanks for the fix from @bmsantos 

PR merged into master. Please pull the latest master to give it a try.
