### ISSUE TITLE
Proposal: make ApiException a RuntimeException

### ISSUE THREAD

**Issue by mmaryo** [swagger-api/swagger-codegen#4376]
##### Description

Hello,

I would like to propose ApiException be changed to a RuntimeException for the following reasons:

Checked Exceptions have mostly been abandoned as a failure by pretty much every post-java language in existence. https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=checked%20exceptions%20are%20evil

##### Swagger-codegen version

2.2.1

##### Command line used for generation

Java

**Comment by wing328** [comment]
@mariomatar thanks for the suggestion. Would extending `ApiException` to `RuntimeException` via  a CLI option meet your requirement?

**Comment by mariomatar** [comment]
Yes @wing328, give the choice is very userful !

**Comment by wing328** [comment]
@mariomatar for the time being, I would suggest you to customize the template (https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/apiException.mustache#L9) and use `-t` to provide the path to the folder containing the customized templates and let us know if the Java API client using RuntimeException works better for you.

**Comment by mmaryo** [comment]
It works and it's better !

I think RuntimeException should be default 


Maybe we can do that :

public class ApiException extends {{#runtimeException}}RuntimeException{{/runtimeException}}{{^runtimeException}}Exception{{/runtimeException}} {


But I can't find where to pass 'runtimeException' variable to template :/

**Comment by wing328** [comment]
Have you tried `--additional-properties=runtimeException=true`?

**Comment by mmaryo** [comment]
You just let me know this option !

I would like to add 'runtimeException' in java configuration for all Swagger users
That why I looking for it in java code ...

**Comment by wing328** [comment]
If you've time to contribute the option (e.g. useRuntimeApiException), let me know and I can show you some good starting points.

**Comment by mmaryo** [comment]
I can do it ! Tomorrow morning. Do I know something ?

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/commit/1aeceead99bb0e6e053befb27e1d0cb415599f22 is a good starting point. Please review and let us know if you've any question.

**Comment by wing328** [comment]
@mmaryo may I know if you need help adding the option (e.g. useRuntimeApiException)?

**Comment by mmaryo** [comment]
@wing328 sorry for late
I push the code here : https://github.com/mmaryo/swagger-codegen/commit/b7b8881099e02c4ae0db1f5b757bc069be858c79
But I can't try it because when I run the generated jar with : java -jar swagger-codegen-2.2.3-SNAPSHOT.jar generate -i project/target/swagger.json -l java -o /tmp/test/
There is an error : no main manifest attribute, in swagger-codegen-2.2.3-SNAPSHOT.jar 
Any idea ?

**Comment by wing328** [comment]
@mmaryo thanks for working on the enhancement. Please submit a PR so that we can review the fix and potentially come up with a fix to the issue you encountered.

**Comment by mmaryo** [comment]
done
I tried pet store with --additional-properties=useRuntimeException=true and it works !

https://github.com/swagger-api/swagger-codegen/pull/5405

**Comment by cbornet** [comment]
Should it really be yet another option ? There are already so many...

**Comment by wing328** [comment]
@cbornet I shared similar concern in some of my replies to PR/discussion that adds another option to codegen.

For this particular case, I think it's ok to add the option since other generators (e.g. C#) may need similar option as it's really developer's preference on which one to use: checked exceptions or unchecked exceptions. From what I understand, there's no conclusion on which one is preferred or better.

**Comment by wing328** [comment]
Closed via #5405

**Comment by in-fke** [comment]
Documentation states:

https://openapi-generator.tech/docs/generators/java/

> Use RuntimeException instead of Exception. Only jersey2, jersey3, okhttp-gson, vertx, microprofile support this option.

But apparently, this also works with `<library>native</library>` - probably someone should update the docs?
