### ISSUE TITLE
swagger-codegen is using snapshot version of swagger-parser

### ISSUE THREAD

**Issue by sreeshas** [swagger-api/swagger-codegen#4377]
##### Description
I would like to understand the reason why swagger-codegen is using snapshot version of swagger-parser instead of released version. 
<swagger-parser-version>1.0.24-SNAPSHOT</swagger-parser-version>

While using snapshot version can get latest fixes from swagger-parser, it looses build reproducibility for swagger-codegen. 
Any bugs introduced by swagger-parser can manifest into a different form in swagger-codegen momentarily and disappear when next set of updates is downloaded from swagger-parser. 

If there is a critical fix needed by swagger-codegen from swagger-parser, next version of swagger-parser should be released and then consumed in swagger-codegen. 

##### Swagger-codegen version
2.2.2

##### Suggest a Fix

1) Release a 1.0.24 version of swagger-parser if there are critical fixes needed by swagger-codegen after 1.0.23 release and use 1.0.24 version in swagger-codegen instead of 1.0.24-SNAPSHOT
2) If the fixes are not critical, go back to 1.0.23 version of parser. 

I currently have a workaround where i can change the version from 1.0.24-SNAPSHOT to 1.0.23. 
But, i would like to see this process followed at swagger-codegen.  

Thoughts?

**Comment by wing328** [comment]
@sreeshas I agree with you that there are certain drawbacks in current approach (using SNAPSHOT version of Swagger Parser). 

To me, Swagger Codegen is probably one of the major consumers of swagger parser and using the SNAPSHOT version can help ensure the latest fix or enhancement won't break Swagger Codegen.

From what I recall, stable releases of Swagger Codegen do not use SNAPSHOT version of Swagger Parser. (please correct me if I'm wrong)

**Comment by sreeshas** [comment]
>From what I recall, stable releases of Swagger Codegen do not use SNAPSHOT version of Swagger >Parser. (please correct me if I'm wrong)

Thats true.  @wing328  Do you have any information on when next stable version of swagger-codegen is releasing? Current swagger-codegen is about 700+ commits ahead from past release.

**Comment by wing328** [comment]
Usually it takes 3 to 4 months but this minor release takes a bit longer than that. Here is the progress: https://github.com/swagger-api/swagger-codegen/milestones (it does not mean we'll address those 300+ issue before releasing 2.2.2)

I want to merge those PRs related to inheritance and release 2.2.2 in Jan/Feb
