### ISSUE TITLE
 Add a useTags flag to allow tags to be used to generate interface / controller classnames

### ISSUE THREAD

**Issue by eamon316** [swagger-api/swagger-codegen#4387]
##### Description

Currently `SpringCodegen` uses the basePath to generate classname for interface / controller.

I would like to be able to use tags to control the generated classnames (this appears to be the pattern for most other generators).

Just wondering if there is any particular issue why the `SpringCodegen` uses basePath and if there are any known issues with using tags? 

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Suggest a Fix

I have added a pull request with proposed changes #4607

**Comment by cbornet** [comment]
Warning : if an operation has 2 tags then you get 2 mappings for the same path which will fail.
I think some generators (JAX-RS?) use only the first tag of the operation.

**Comment by eamon316** [comment]
If there are 2 tags they are combined by the Java generator.
e.g.
```
      tags:
        - A B
```
you get `ABApi.java` and `ABApiController.java`

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/issues/4396
