### ISSUE TITLE
Proposal: Selective Generation Exclusions

### ISSUE THREAD

**Issue by johnnyxhm** [swagger-api/swagger-codegen#4389]
##### Description

It would be nice to be able to specify excluded models/apis/supporting files in use cases where there are, for example, many model objects. The existing selective generation feature could make it tedious to  specify all the model objects in the system properties.  

##### Swagger-codegen version

2.2.2-SNAPSHOT (Latest from master as of a291d3113aa729efb20226262c6bc2fe3a864d5a)

##### Command line used for generation

Java (Spring)

##### Related issues

#3587
#1428

##### Suggest a Fix

This can be done by modifying the DefaultGenerator.java in the swagger-codegen module.

**Comment by wing328** [comment]
Are you aware of using .swagger-codegen-ignore to skip file generation?

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-to-skip-certain-files-during-code-generation

**Comment by johnnyxhm** [comment]
I was under the impression that was doing something else, but just giving it a try right now and it seems to do exactly what we need. We did also stumble upon https://github.com/swagger-api/swagger-codegen#bringing-your-own-models which also covers excluding models. Either way, seems like this is already possible and I was looking at the wrong sections in the readme

**Comment by wing328** [comment]
@johnnyxhm np. Let us know if you've further feedback/suggestion on Swagger Codegen.

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
