### ISSUE TITLE
Swagger codegen on swagger spec 1.2

### ISSUE THREAD

**Issue by rohitsakala** [swagger-api/swagger-codegen#4394]
##### Description

Syntax on how to run swagger codegen on swagger spec 1.2 ? 

##### Swagger declaration file content or url

Here are the specs on which I want to run without putting them on a server. 
https://github.com/strongloop/loopback-swagger/tree/master/example/specs/1.2

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i swagger.json -l html2 

This commands works for swagger 2.0. But in spec 1.2 above mentioned there are multiple files. How do I give input to it.

Thanks :)

**Comment by wing328** [comment]
@rohitsakala can you try the following?
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i https://restunited.com/petstore/api-docs \
  -l html2 \
  -o /var/tmp/html2/
```

https://github.com/strongloop/loopback-swagger/tree/master/example/specs/1.2 seems to be broken as it's missing store.json.

**Comment by rohitsakala** [comment]
@wing328 Hi
 
Thanks for the reply. But Can't I run it without hosting the files somewhere, like in a directory ? Sorry if it is too general question.

**Comment by wing328** [comment]
Yes, you can using the same `-i` command line switch. Here is another example:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i /var/tmp/swagger.json \
  -l html2 \
  -o /var/tmp/html2/
```

**Comment by rohitsakala** [comment]
@wing328 

Thanks for the reply. But when run 
java -jar ../swagger-codegen-cli.jar generate -i pet-store.json -l html2

It is creating documentation only for only one file not for the other file

There are two files that are connected according to swagger spec 1.2 
1) pet-store.json
2) pet.json

**Comment by wing328** [comment]
Did you put user.json in the same directory? (store.json seems to be missing and I've filed an issue here: https://github.com/strongloop/loopback-swagger/issues/75)

**Comment by wing328** [comment]
What about updating `"path": "/pet"` to `"path": "/pet.json"`?

Btw, did you get any error message?

**Comment by wing328** [comment]
You may also want to try https://github.com/lucybot/api-spec-converter to convert the spec from 1.2 to 2.0 as `api-spec-converter` may be smarter to understand the swagger spec in your case.

**Comment by rohitsakala** [comment]
When I changed the path to pet.json, I get this error message.

[main] INFO io.swagger.parser.Swagger20Parser - reading from pet-store.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from pet-store.json
java.io.FileNotFoundException: null/pet.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:708)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:438)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:127)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:72)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:391)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /home/rohitsakala/workingSpecs/./index.html

**Comment by fehguy** [comment]
Hi, since 1.2 supports multiple files, you _must_ create an api listing file with api declarations in the same folder.  Consider using the parser project to test your setup, and even migrate from 1.2 to 2.0 before 1.2 support is dropped in a few months.
