### ISSUE TITLE
API calls are only allowed to return a single type of a response even when you have several HTTP/2xx response types defined

### ISSUE THREAD

**Issue by frol** [swagger-api/swagger-codegen#4398]
##### Description

I believe, It is a general design issue since `returnType` is passed to all the client templates (at least, I could find the use of `returnType` in Python, C++, Java, JavaScript clients).

My endpoints are designed to return HTTP/202 Accepted if a requested resource is not found in a cache (meanwhile, scheduling the update behind the scenes), and HTTP/200 OK if the item is found in a cache. I would like to have HTTP/202 return JSON schema with some useful information (e.g. the current status, progress in %, the time when the backend started processing the task), and HTTP/200 return either another JSON schema or a file or plain text.

Currently, my HTTP/202 responses get deserialized using HTTP/200 model as it is what `returnType` (a.k.a. `response_type`) gets. Another side effect is that if I don't have HTTP/200 response defined for an endpoint in Swagger config, my client calls to that endpoint will return `null`/`None`/... no matter what HTTP status is returned.

##### Swagger-codegen version

The issue seems to be there since the very beginning and it is not addressed in master.

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
basePath: "/api/v1"
definitions:
  StatusSchema:
    properties:
      id:
        format: int32
        type: integer
      status:
        enum:
        - failed
        - processing
        - finished
        maxLength: 10
        type: string
    type: object
  DataSchema:
    type: string
paths:
  "/data/":
    get:
      responses:
        '200':
          description: Request fulfilled, document follows
          schema:
            "$ref": "#/definitions/DataSchema"
        '202':
          description: Request accepted, processing continues off-line
          schema:
            "$ref": "#/definitions/StatusSchema"
```

##### Command line used for generation

```
$ java -jar '/opt/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar' \
              generate \
                  --input-spec './swagger.json' \
                  --lang python \
                  --output './python'
```

##### Steps to reproduce

1. Build a client
2. Try to make a request with `data_get()` API method
3. If the server responses with HTTP/202, the method will still return a string (this is how the `DataSchema` is defined) instead of an object with `StatusSchema` structure.

Side effects: If no HTTP/200 defined, you will always receive `None` no matter what 2xx status is returned and what schema is defined for it.

**Comment by ssteinerx** [comment]
I just ran into this same thing and I concur: multiple return types are not supported by the current architecture.

My work-around is to return a unique key when the job is accepted so you can execute a separate 'status' call with that key later.   If the status is 'completed', the data is returned as a payload otherwise the payload is empty.

**Comment by fehguy** [comment]
Yes, this is not supported in the current framework.  You cannot overload response types.

In the next major version we must support multiple response types across all response codes, so this will be added then.

**Comment by yonaskolb** [comment]
For what it's worth I just added this to https://github.com/yonaskolb/SwagGen 0.5

The approach I used was a nested enum with associated values for the response types. Maybe something similar would work here, though some languages don't have nested types like in Swift so they would be seperate enums/classes then in the global scope. Also other languages don't have associated types for enums, so they would have to be properties on a class

**Comment by fehguy** [comment]
Multiple return types will be supported along with the 3.0 spec support
