### ISSUE TITLE
Async scala client generator

### ISSUE THREAD

**Issue by akkie** [swagger-api/swagger-codegen#440]
Is there a plan to create a new generator for an async scala client. In the previous version there was one on top of `swagger-async-httpclient`, but it seems that this was removed in the current version.

The new swagger client generator has an [asyncHttpClient](https://github.com/swagger-api/swagger-codegen/blob/12531943d048efd9da439967e0d7bdca92f35cd4/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/languages/ScalaClientCodegen.java#L17) flag, but it seems that this is only used for authentication. Please correct my if I'm wrong.

**Comment by fehguy** [comment]
Yes, it is easy to move the templates over. You can send a pull request or wait for the next minor release to support them

**Comment by fehguy** [comment]
added in develop_2.0
