### ISSUE TITLE
Swagger Codegen War: web services not running in LJS server.

### ISSUE THREAD

**Issue by manojpandey89** [swagger-api/swagger-codegen#4402]
Swagger Codegen War web services are not running in LJS server. 

It runs fine when we deploy Swagger codegen war on tomcat server but gives problem when deployed on LJS server.

It throws below error on trying to access link http://localhost:8080/swagger-generator/api/gen/servers. As per my investigation it looks like some problem with glassfish.jersey jar which is used for web services.
Please suggest the solution to this. 

org.glassfish.jersey.server.internal.scanning.ResourceFinderException: The URI scheme bundleentry of the URI bundleentry://6914.fwk686299093/WEB-INF/classes/io/swagger/generator/resource/ExceptionWriter.class is not supported. Package scanning deployment is not supported for such URIs.
Try using a different deployment mechanism such as explicitly declaring root resource and provider classes using an extension of javax.ws.rs.core.Application
	org.glassfish.jersey.server.internal.scanning.PackageNamesScanner.addResourceFinder(PackageNamesScanner.java:282)
	org.glassfish.jersey.server.internal.scanning.PackageNamesScanner.init(PackageNamesScanner.java:196)
	org.glassfish.jersey.server.internal.scanning.PackageNamesScanner.<init>(PackageNamesScanner.java:153)
	org.glassfish.jersey.server.internal.scanning.PackageNamesScanner.<init>(PackageNamesScanner.java:110)
	org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:867)
	org.glassfish.jersey.server.ResourceConfig._getClasses(ResourceConfig.java:840)
	org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:755)
	org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1171)
	org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1144)
	org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1140)
	org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:317)
	org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:284)
	org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:168)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:358)
	javax.servlet.GenericServlet.init(GenericServlet.java:244)
	org.eclipse.virgo.web.enterprise.security.valve.OpenEjbSecurityInitializationValve.invoke(OpenEjbSecurityInitializationValve.java:44)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	com.sap.core.jpaas.security.auth.service.lib.AbstractAuthenticator.invoke(AbstractAuthenticator.java:168)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	com.sap.core.tenant.valve.TenantValidationValve.invokeNextValve(TenantValidationValve.java:168)
	com.sap.core.tenant.valve.TenantValidationValve.invoke(TenantValidationValve.java:94)
	com.sap.js.statistics.tomcat.valve.RequestTracingValve.invoke(RequestTracingValve.java:38)
	com.sap.core.js.monitoring.tomcat.valve.RequestTracingValve.invoke(RequestTracingValve.java:27)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

**Comment by fehguy** [comment]
I don't think this issue has to do with codegen.
