### ISSUE TITLE
Set up Eclipse environment with swagger-codegen?

### ISSUE THREAD

**Issue by fultonm** [swagger-api/swagger-codegen#4404]
EDIT: The main question I have is How do I open the swagger project in an IDE? I'm only assuming we use Eclipse around here.

##### Description

When I open swagger-codegen project in Eclipse I am having problems using the features of the IDE such as Find Method Reference and other things having to do with code searching.

##### Swagger-codegen version

master branch

##### Swagger declaration file content or url

Not applicable

##### Steps to reproduce

1. Clone the swagger-codegen project with git.
2. Import the projects into Eclipse using File -> Import -> Maven -> Existing Maven Projects
3. Find any method in any project and find all references.

##### Related issues

I opened an SO question about this issue here, including screenshots and more description:
[Cannot Perform Operation: The resource is not on the build path of a Java project](http://stackoverflow.com/questions/41157561/cannot-perform-operation-the-resource-is-not-on-the-build-path-of-a-java-projec)

##### Suggest a Fix

I think this has to do with how the projects were imported or an Eclipse plugin I haven't installed or configured correctly.

**Comment by wing328** [comment]
@fultonm I'm using [NetBeans](https://netbeans.org/downloads/). Please give it a try.

For Eclipse, which version are you using? I'll give it a try later when I've time.

**Comment by fultonm** [comment]
Neon.1. Thank you for the NetBeans suggestion I will try that.

**Comment by fultonm** [comment]
NetBeans works well.

**Comment by fehguy** [comment]
Closing out as this is more of an IDE question than anything.

**Comment by anish274** [comment]
@wing328  hello sir, I do not get any option in netbeans. How can I use swagger in netbeans?
