### ISSUE TITLE
[Dynamic HTML][Swagger 1.2] 

### ISSUE THREAD

**Issue by michalgce** [swagger-api/swagger-codegen#442]
Hello, I have a problem with generation dynamic html

```java -cp modules/swagger-codegen/target/*:modules/swagger-codegen/target/lib/* com.wordnik.swagger.codegen.Codegen -i http://localhost:8080/core/api-docs -l dynamic-html -o tmp```

getting exception 

```java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at com.wordnik.swagger.codegen.DefaultCodegen.initialCaps(DefaultCodegen.java:310)
	at com.wordnik.swagger.codegen.DefaultCodegen.toApiFilename(DefaultCodegen.java:133)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:122)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)  ```

**Comment by webron** [comment]
Which version of the codegen do you use?

**Comment by fehguy** [comment]
That stack trace looks like you don't have a `tag`, or your Api is mounted to the root "/".  It should give a better message, or pick a default location.

**Comment by michalgce** [comment]
Where i should set ```tag``` (please more details)?

**Comment by fehguy** [comment]
to be clear, I think the codegen should allow this, but you can set a tag on an operation like such:

```json
  "paths": {
    "/pet": {
      "put": {
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "description": "Pet object that needs to be added to the store",
            "required": false,
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],...
```

**Comment by yetti4** [comment]
If I am correct, tags are [not present](https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide) in 1.2 version. I have the same issue as @michalgce.
Which annotation am I missing or is it a bug?

**Comment by yetti4** [comment]
This issue is solved in the latest release

**Comment by webron** [comment]
@michalgce - can you please confirm this issue is solved for you?

**Comment by michalgce** [comment]
Yep, works great.

**Comment by webron** [comment]
Oh, that was fast, thanks :)
