### ISSUE TITLE
Swagger CodeGen C# 2.0 client Header Authentication/Authrization issue 

### ISSUE THREAD

**Issue by HarprasadShukla** [swagger-api/swagger-codegen#4424]
Hi Team,

We are consuming web API in .net application so generated swagger C# 2.0 client code but missing to pass  Header details Authentication in c# generated code. Without Authentication API responding correctly but when applying UID/PWD in c# generated code it is returning authorization denied. Could you please provide some sample to authenticate/Authorize web API generated code by Swagger C# client code. Just we can pass UID/PWD in config file based on different environment hosted API?
Do let me know in case further clarification required.

Regards,
Harprasad

**Comment by HarprasadShukla** [comment]
It help me lot if redirect ticket to right team in case again routed differently. I am looking quick reply as we stuck in middle of the way.

**Comment by HarprasadShukla** [comment]
Just want to add point- I am successfully able to generate code with JSON/YAML file. Issue is  when within C# code applying UID/PWD in unit test case. API responding Authrisation denied. 

We are not passing any header/Authentication info in YAML/JSON while generating code. Do we need to pass it before generating code? or later just only add in the C# code based on environment configuration.

**Comment by HarprasadShukla** [comment]
Just want to add point- I am successfully able to generate code with JSON/YAML file. Issue is when within C# code applying UID/PWD in unit test case. API responding Authrisation denied.

We are not passing any header/Authentication info in YAML/JSON while generating code. Do we need to pass it before generating code? or later just only add in the C# code based on environment configuration.

Sorry mistakenly clicked closed button.... reopening again...

**Comment by wing328** [comment]
@HarprasadShukla if your REST API supports HTTP basic authentication, then you should document it according to the OpenAPI/Swagger spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#basic-authentication-sample.

(I'm not sure if C# 2.0 generator has proper support for HTTP basic auth)
