### ISSUE TITLE
Swagger C# client codeGen Authencation/Authrization issue while doing unit testing

### ISSUE THREAD

**Issue by HarprasadShukla** [swagger-api/swagger-codegen#4425]
Hi Team,

We are consuming web API in .net application so generated swagger C# 2.0 client code but missing to pass  Header details Authentication in c# generated code. Without Authentication API responding correctly but when applying UID/PWD in c# generated code it is returning authorization denied. Could you please provide some sample to authenticate/Authorize web API generated code by Swagger C# client code. Just we can pass UID/PWD in config file based on different environment hosted API?
Do let me know in case further clarification required.

Regards,
Harprasad

**Comment by jimschubert** [comment]
This sounds like a duplicate of #4431. I'm am little confused what unit testing has to do with authentication, though. Could you clarify this?

**Comment by wing328** [comment]
@HarprasadShukla closing this as there's no update from you.
