### ISSUE TITLE
[typescript/angular2] new classes

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#4428]
##### Description

I've came up with some new classes added on 2.2.3 (`ApiModule` and `Configuration` classes).

Is there some example over there showing how to use these new classes with old `Api-likeService` classes?

Concretly, I don't quite understand how to provide `base_path` information. Currently, my `UserService` is like:

```
@Injectable()
export class UsersService {
    protected basePath = 'http://localhost/commty/cmng';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
```

As you can see, there two injectable parameters I'm able to set a basepath:

1. Using a `BASE_PATH`.
2. Using a `Configuration`.

Which is the way to provide it?

By other hand, which's the role of new `ApiModule.forConfig` module/method?

##### Swagger-codegen version

2.2.3

**Comment by kernwig** [comment]
If anyone is still stuck on this, here's how I was able to use the new structure to override basePath.

```
import * as api from '../api';
import * as AppConfig from '../app.config'; // access build-time options

/** Configuration settings for the backend API */
const backendConfiguration = new api.Configuration({basePath: AppConfig.baseApiUrl()});

@NgModule({
    imports: [api.ApiModule.forConfig(backendConfiguration), CommonModule],
    exports: [],
    providers: [
        // CoreModule services, which use the API...
    ]
})
export class CoreModule {
}
```

**Comment by wing328** [comment]
@jeusdi @kernwig if you guys have time to contribute auto-generated documentation TS Angular2 API client, please let me know and I can show you guys some good starting point.

**Comment by jeusdi** [comment]
Thanks @kernwig 

Is there any example about how to configure OAuth2 settings in configuration?
