### ISSUE TITLE
Required parameters not handled as required

### ISSUE THREAD

**Issue by cchafer** [swagger-api/swagger-codegen#443]
Hi, 
At this time, DefaultCodegen doesn't handle rightly required parameters. All of them as marked as NOT required when trying to figure out their type.

This can lead to several problems when, like me, you want to define type type of not required items as Option[...] in Scala.

Here's a simple fix for this : 
```
diff --git a/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java b/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
index 9d908aa..965106e 100644
--- a/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
+++ b/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java
@@ -774,6 +774,8 @@ public class DefaultCodegen {
         LOGGER.warn("warning!  Property type \"" + qp.getType() + "\" not found for parameter \"" + param.getName() + "\", using String");
         property = new StringProperty().description("//TODO automatically added by swagger-codegen.  Type was " + qp.getType() + " but not supported");
       }
+
+      property.setRequired(param.getRequired());
       CodegenProperty model = fromProperty(qp.getName(), property);
       p.collectionFormat = collectionFormat;
       p.dataType = model.datatype;
```

**Comment by fehguy** [comment]
Can you put in a test or two to demonstrate this in a PR to develop_2.0 branch?

**Comment by webron** [comment]
@cchafer - a bit confused here. You prepared #446 but closed it, and can't find another submission. Am I missing something or did you perhaps forget? :)

**Comment by cchafer** [comment]
Hi,

To be honnest, this little modification has already been merged a few weeks ago, in another PR, about CodegenParameter missing some data (can't remember exactly which one).
So this PR could be closed (I thought it already was, in fact).
Do you want me to close it ?

**Comment by webron** [comment]
I'm just going over the issues and cleaning out to get a better picture of what's needed for the final release. I don't keep track over all changes in the project, but if you say this issue can be closed, that's great.

**Comment by SunriseJJJ** [comment]
facing this issue right now
part of my contract (definitions section):
```
"sampleRequest": {
    "type": "object",
    "required": [
        "a",
        "b"
    ],
    "properties": {
        "a": {
            "type": "string",
            "description": "A field"
        },
        "b": {
            "type": "string",
            "description": "B field"
        },
        "c": {
            "type": "string",
            "description": "C field"
        }
    }
}
```

generated code:
```
  /**
   * A
   **/
  @ApiModelProperty(required = true, value = "A")
  @JsonProperty("a")
  public String getA() {
    return a;
  }
  public void setA(String a) {
    this.a = a;
  }
```

i can add 
```@JsonProperty(value = "a", required=true)```
 manually but I will lose it during next model generation (we don't store generated classes in code (and in repo as well), it generated automatically as step of project build)

**Comment by wing328** [comment]
@cchafer @SunriseJJJ I wonder if you can test with the latest `develop_2.0` branch and let us know if the issue still exists. Thanks!

**Comment by SunriseJJJ** [comment]
@wing328 issue still exists. Maybe issue related to [model.mustache](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/JavaJaxRS/model.mustache) file?
Line
'''
@JsonProperty("{{name}}")
'''

should be changed to something like this
'''
@JsonProperty({{#required}}required = {{required}}, {{/required}}value = "{{name}}")
'''
?

**Comment by fehguy** [comment]
So to be clear, this issue is really about the generated code not _enforcing_ the required parameter, not declaring it incorrectly in the swagger.json.  It's of course possible to do, but I suggest that's taken into your own templates, as the server generation isn't necessarily doing all validations for you.  Please reopen if you disagree or need more advice on this.
