### ISSUE TITLE
[java] Date or DateTime  with --model-name-prefix=Xyz will make a new Entity XyzDate and XyzDateTime

### ISSUE THREAD

**Issue by joergi77** [swagger-api/swagger-codegen#4430]
##### Description
when I use the format Date and the format DateTime in my swagger file and I generate a Java Client with   
```
java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar \
        -i tmp/swagger.yaml -l java -o tmp/model_name/client \
	--api-package=$api_package \
	--model-package=de.ourcompany.packagename.client.model_name.api \
	--model-name-prefix=Xyz \
	-DhideGenerationTimestamp=true
```

 I will have the following in my generated model:

Date will become
```
import de.ourcompany.packagename.client.model_name.api.model.XyzLocalDate;
 public XyzLocalDate getCreatedAt() {
```
and DateTime will become
```
import de.ourcompany.packagename.client.model_name.api.model.XyzDateTime;
 public XyzDateTime getCreatedAt() {
```

##### Swagger-codegen version
latest master

##### Swagger declaration file content or url
Date:
```
 expires_at:
        type: string
        format: date
```
DateTime
```
 expires_at:
        type: string
        format: date-time
```

##### Command line used for generation
```
java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar \
        -i tmp/swagger.yaml -l java -o tmp/model_name/client \
	--api-package=$api_package \
	--model-package=de.ourcompany.packagename.client.model_name.api \
	--model-name-prefix=Xyz \
	-DhideGenerationTimestamp=true
```

**Comment by ePaul** [comment]
This is the same issue as #3285. #3288 has a pull request for this, I guess we should have a look at it again?

**Comment by wing328** [comment]
@joergi77 we've merged #3288 into master. Please pull the latest master to give it a try.

**Comment by wing328** [comment]
@joergi77 have you run `mvn clean package` to rebuild the JAR?

**Comment by wing328** [comment]
I did another test but couldn't repeat the issue. Here is what I got:
```
  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("dateTime")
  private DateTime dateTime = null;
```

**Comment by joergi77** [comment]
I will test again at the weekend, and let you know!

**Comment by wing328** [comment]
If it's still an issue, please reply to let us know and we'll reopen the issue.

**Comment by leoluz** [comment]
Hi, I have this issue in 2.2.1
Is there a plan to release the fix?
Tks!
