### ISSUE TITLE
Swagger Editor C#2.0 client codegen -Authrization denied issue. 

### ISSUE THREAD

**Issue by HarprasadShukla** [swagger-api/swagger-codegen#4431]
Hi Team,

We are consuming web API in .net application so generated swagger C# 2.0 client code but missing to pass  Header details Authentication in c# generated code. Without Authentication API responding correctly but when applying UID/PWD in c# generated code it is returning authorization denied. Could you please provide some sample to authenticate/Authorize web API generated code by Swagger C# client code. Just we can pass UID/PWD in config file based on different environment hosted API?
In Swagger Editor during code generation JSON/YAML file not providing API URL and credential. We need to pass in config file as dependents upon environment hosted API.
Note- I do not have issue in code generation. When using generated code in C# Visual Studio and passing credential getting error –Authorization denied.
Do let me know in case further clarification required.

Regards,
Harprasad

**Comment by jimschubert** [comment]
@HarprasadShukla I'm not sure I follow the problem fully.

To clarify, you're generating the `C# 2.0` client. You can hit unauthenticated endpoints without a problem, but authenticated endpoints fail?

How are you attempting to pass the auth when you use the client? Currently, the client supports Basic Auth, API Key, and partially supports OAuth 2.0. Basic Auth should bet set via `Configuration.Username` and `Configuration.Password`.

Some sample code would help me to understand the issue better.

**Comment by wing328** [comment]
@HarprasadShukla closing this as there's no update from you.
