### ISSUE TITLE
Nodejs generator throws an exception

### ISSUE THREAD

**Issue by lowmemory** [swagger-api/swagger-codegen#444]
I get this exception when I try to generate a nodejs server stub:

![image](https://cloud.githubusercontent.com/assets/2770681/6318061/d54d4666-ba7b-11e4-95e6-5a7e7c8cd284.png)

I'm surprised that no one else generates nodejs stubs.

My test enviroment:
   windows 8.1
   jdk8
   mvn 3.2.3

I think the problem is in NodeJSServerCodegen.java (line 92):
    return outputFolder + File.separator + apiPackage().replaceAll("\\.", File.separator);
It should be replaced with:
    return outputFolder + File.separator + apiPackage().replace('.', File.separatorChar);
This was done in others codegen (ex. JavaClientCodegen.java) but not for the nodejs one.

Searching the code I found other parts that need to be fixed:

C:\Users\Marco\Desktop\swagger\swagger-codegen\modules\swagger-codegen\src\main\java\com\wordnik\swagger\codegen\DefaultGenerator.java 15 KB File JAVA 22/02/2015 08:41:55 22/02/2015 08:41:55 22/02/2015 08:41:55 1
156       bundle.put("apiFolder", config.apiPackage().replaceAll("\\.", "/"));

C:\Users\Marco\Desktop\swagger\swagger-codegen\modules\swagger-codegen\src\main\java\com\wordnik\swagger\codegen\DefaultCodegen.java 31 KB File JAVA 22/02/2015 08:41:55 22/02/2015 08:41:55 22/02/2015 08:41:55 2
104     return outputFolder + "/" + apiPackage().replaceAll("\\.", "/");
108     return outputFolder + "/" + modelPackage().replaceAll("\\.", "/");

C:\Users\Marco\Desktop\swagger\swagger-codegen\modules\swagger-codegen\src\main\java\com\wordnik\swagger\codegen\languages\NodeJSServerCodegen.java 4 KB File JAVA 22/02/2015 10:02:53 22/02/2015 08:41:55 22/02/2015 08:41:55 2
92     return outputFolder + File.separator + apiPackage().replaceAll("\\.", File.separator);
96     return outputFolder + File.separator + modelPackage().replaceAll("\\.", File.separator);

C:\Users\Marco\Desktop\swagger\swagger-codegen\modules\swagger-codegen\src\main\java\com\wordnik\swagger\codegen\languages\PythonClientCodegen.java 4 KB File JAVA 22/02/2015 08:41:55 22/02/2015 08:41:55 22/02/2015 08:41:55 2
67     return outputFolder + "/" + apiPackage().replaceAll("\\.", "/");
71     return outputFolder + "/" + modelPackage().replaceAll("\\.", "/");

The fix is the same for all:
replace
        .replaceAll("\\.", .... );
with:
        .replace('.', File.separatorChar);

Bye.

Marco

**Comment by fehguy** [comment]
when you make that change, does it work for you?

**Comment by lowmemory** [comment]
yes, it worked.
