### ISSUE TITLE
Yaml using inheritance get different result from swagger codegen and swagger editor

### ISSUE THREAD

**Issue by johnluan** [swagger-api/swagger-codegen#4441]
##### Description
I am trying to use allOf to do inheritance , but the result is different between swagger codegen and swagger editor. There is no **extends** key word from swagger codegen

The code from http://editor.swagger.io/#/
**
 * Child
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.SpringCodegen", date = "2016-12-21T02:24:11.587Z")

public class Child **extends** Parent  {
  @JsonProperty("newField")
  private Boolean newField = null;

The code from swagger codegen is 
**
 * Child
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.SpringCodegen", date = "2016-12-21T13:36:03.176+11:00")

public class Child   {
  private Boolean newField = null;
##### Swagger-codegen version
I am using 2.2.1

##### Swagger declaration file content or url

This is the yml

swagger: '2.0'
info:
  title: ''
  description:  ''
  termsOfService: ''
  version: '1.20'
host: 'localhost'
schemes:
  - https
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    get:
      summary: ''
      description: ''  
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Child' 
        403:
          description: Authorisation failed
 
definitions:
  Parent:
    properties:
      value:
        type: string
      description:
        type: string

  Child:
    type: object
    allOf:
     - $ref: '#/definitions/Parent'
     - type: object
     - properties:
        newField:
         type: boolean
##### Command line used for generation
java -jar ./swagger-codegen-cli.jar generate ^
   -i ../yml/test.yaml ^
   -l spring ^
   -o ../generatedSource1 ^

**Comment by fehguy** [comment]
There is a different update cycle for them, please consider using a local version if you need to control the server generation templates more carefully
