### ISSUE TITLE
[csharp] Optional enum parameters in method declarations should not be = null

### ISSUE THREAD

**Issue by gdurand** [swagger-api/swagger-codegen#4446]
##### Description

In a Model class constructor, if a parameter of type enum is optional, it is defaulted to null, which is illegal for enums.

##### Swagger-codegen version

master

##### Suggest a Fix

Perhaps default it to 0, but it is a valid enum value so it's no better, unless enums are generated starting with value 1.

**Comment by jimschubert** [comment]
This should already be addressed and fixed by #4145. @gdurand would you want to test my PR against your expectations?

**Comment by gdurand** [comment]
Your PR fixes the compilation issue.

**Comment by wing328** [comment]
@gdurand thanks for testing the PR, which has been merged into master.

Thanks @jimschubert for the fix.
