### ISSUE TITLE
[Android] FormData is not sent

### ISSUE THREAD

**Issue by PhilippMundhenk** [swagger-api/swagger-codegen#4453]
##### Description

When generating an Android client, some issues exist with paths that use formData input. It seems that the encoding setting is not correctly generated.

##### Swagger-codegen version

Version on editor.swagger.io

##### Swagger declaration file content or url

Here is an example (shortened to path declaration):
    ```yaml
    /test:
    put:
      summary: Test
      description: Used to get user ID.
      parameters:
        - name: email
          in: formData
          description: Email address of the user
          required: true
          type: string
        - name: password
          format: password
          in: formData
          description: Password of the user
          required: true
          type: string
      tags:
        - User
      responses:
        200:
          description: The URL of the user (includes user ID)
          schema:
            type: string
    ```

##### Command line used for generation

Used editor.swagger.io

##### Suggest a Fix

It seems that for the above example, the generated code in android-client\src\main\java\io\swagger\client\api\UserApi.java contains an error:

```
String[] contentTypes = {
  
};
String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";
```

I think it should be sthg like:
```
String[] contentTypes = {
  "application/x-www-form-urlencoded"
};
String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";
```
or:
```
String contentType = "application/x-www-form-urlencoded";
```

With that, it works fine for me.

**Comment by wing328** [comment]
@PhilippMundhenk Android API client (volley) does have proper support for `consumes` defined in the swagger spec: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/android/libraries/volley/api.mustache#L83-L87

In your swagger spec, does the operation has a proper `consumes` defined? Here is an example:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L190-L191

**Comment by PhilippMundhenk** [comment]
Ah, interesting! I must have missed the consume/produce statements. I currently don't have time to try it, but trust that it works.
