### ISSUE TITLE
enum support for golang in swagger-codegen

### ISSUE THREAD

**Issue by jeetcontext** [swagger-api/swagger-codegen#4459]
##### Description

I am trying to generate sdk for golang with respect to a json file. It is not able to generate the enum type. 

##### Swagger-codegen version 
Version 2.2.2-snapshot

##### Swagger declaration file content or url
"catalog_type": {
            "description": "Type of the catalog",
            "enum": [
                "CATALOG_A",
                "CATALOG_B"
            ],
            "title": "Catalog type",
            "type": "string"
        }
This is part of json file.

##### Command line used for generation
After doing the mvn build, used
 
Java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.json -o ./gosdk

##### Related issues

There is another dev going on with go-swagger which supports enum. 

##### Suggest a Fix

May be the template file and the GoClientCodegen file needs to be updated for complex json.

**Comment by jeetcontext** [comment]
I checked with petstore as well, It is not generating the enum inside pet object.

**Comment by taxpon** [comment]
@jeetcontext @wing328 I am interested in working on this issue. go-swagger is providing [`Validate`](https://github.com/go-swagger/go-swagger/blob/eba70dd18f6e0d254159853c6d98e514d720fb84/examples/task-tracker/models/task_card.go#L96) method and [validating enum value](https://github.com/go-swagger/go-swagger/blob/eba70dd18f6e0d254159853c6d98e514d720fb84/examples/task-tracker/models/task_card.go#L252) inside it. I am now planning to implement similar methods in swagger-codegen, is it OK?

**Comment by wing328** [comment]
@taxpon do you mean adding `go-swagger` as a dependency to the auto-generated Go API client?

For enum support in Go, I suggest we do it in the 2.3.0 branch in which @antihax has made a lot of enhancements to the Go API client, e.g. proper support of optional parameters.

**Comment by antihax** [comment]
Go does not support enum, so i think it is as simple as validating input is one of the enum elements as @jeetcontext suggest. But, to throw a wrench in the gears a bit... 

> 5.20. enum
The value of this keyword MUST be an array. This array SHOULD have at least one element. Elements in the array SHOULD be unique.
**Elements in the array MAY be of any type, including null.**

We know Go also does not allow nil data types so this may be better using interface{} or pointers.

**Comment by taxpon** [comment]
@wing328 I intended not to add `go-swagger` as a dependency but to update mustache template in `swagger-codegen` so that it provides methods for validations (like `go-swagger`) for Go.

**Comment by vpolouchkine** [comment]
Just ran into this.  FWIW Go "enums" are typically done like this:
```go
type MyEnum string

const (
	Foo MyEnum = "foo"
	Bar MyEnum = "bar"
)
```

**Comment by wing328** [comment]
@vpolouchkine thanks for sharing.

Has anyone started working on this yet? If yes, please kindly share the progress. Thanks.

**Comment by marcusljx** [comment]
I wouldn't mind helping out with this. It seems trivial to generate enums in golang (basically a type alias). But as I'm new to swagger-codegen, could someone please let me know where I can read the logic of the swagger-spec parser?
