### ISSUE TITLE
[Perl]Avoid update timestamp in README

### ISSUE THREAD

**Issue by shiqicao** [swagger-api/swagger-codegen#4466]
[Perl]Avoid update timestamp in README

2.2.2

Remove OR add an option for not update timestamp in README.md

**Comment by wing328** [comment]
@shiqicao one way is to can leverage the option `hideGenerationTimestamp ` to hide the generation timestamp, e.g. https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/go/README.mustache#L12
and here is the command line option: https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/bin/windows/java-petstore-okhttp-gson.bat#L8

May I know if you've time to contribute the enhancement?

**Comment by wing328** [comment]
I've submitted #4614 (merged) for the enhancement.

Please pull the latest master to give it a try.
