### ISSUE TITLE
Cannot generate SDK for Swift 3.0

### ISSUE THREAD

**Issue by SyedTayyab99** [swagger-api/swagger-codegen#4469]
##### Description
I have pulled the latest master but when I try to generate Swift3 SDK it gives me the error: "Can't load config class with name Swift3" The list of available configs still only show "swift" and there is no entry for swift3.

##### Swagger-codegen version

2.2.1

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i https://api.stoplight.io/v1/versions/Xha2rkYYd4s4CBhmW/export/oas.json -l Swift3 -o Projects/"71st Street"/SDKs/Swift

**Comment by wing328** [comment]
Pls try `swift3` (lower case) instead of `Swift3`

**Comment by wing328** [comment]
You will also need to run `mvn clean package` to build the JAR locally based on the latest master.

**Comment by SyedTayyab99** [comment]
Hi @wing328 can you please help me with this?

**Comment by wing328** [comment]
@SyedTayyab99 I can bulid locally without issue.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  7.066 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [ 42.764 s]
[INFO] swagger-codegen (executable) ....................... SUCCESS [  7.030 s]
[INFO] swagger-codegen (maven-plugin) ..................... SUCCESS [  4.571 s]
[INFO] swagger-generator .................................. SUCCESS [  9.036 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 min
[INFO] Finished at: 2016-12-29T18:01:14+08:00
[INFO] Final Memory: 60M/428M
[INFO] ------------------------------------------------------------------------
```

Can you try `mvn clean package -DskipTests` as a workaround for the time being?

**Comment by SyedTayyab99** [comment]
I have tried building it by skipping tests and have been successful in doing so. However when I try to generate the SDK i get the following error. 

io.swagger.parser.Swagger20Parser - reading from https://api.stoplight.io/v1/versions/Qbszws9L923pwWoY2/export/oas.json
Exception in thread "main" java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V

**Comment by SyedTayyab99** [comment]
Btw the generation works perfect with last stable package of swagger-codegen

**Comment by wing328** [comment]
@SyedTayyab99 I've rolled back swagger parser to 1.0.24 for the time being. For details, please refer to https://github.com/swagger-api/swagger-codegen/issues/4449#issuecomment-269648999

Please pull the latest master to give it a try.

**Comment by wing328** [comment]
@SyedTayyab99 if it's still an issue, please reply to let us know.

Closing this issue for the time being.

**Comment by SyedTayyab99** [comment]
@wing328 Thanks a lot for the support. I am sorry I have been on vacations and couldn't check it then. I have checked it now and it works perfect. Thank you so much for the help.

**Comment by wing328** [comment]
@SyedTayyab99 no problem. Let us know if you've other feedback on Swagger Codegen.

(we've just added Swagger Codegen to ProductHunt: https://www.producthunt.com/posts/swagger-codegen, pleae upvote if you found Swagger Codegen useful)
