### ISSUE TITLE
[Node.js] uniqueItems keyword not reported in generated swagger.yaml for server

### ISSUE THREAD

**Issue by alfi86** [swagger-api/swagger-codegen#4474]
for swagger editor on-line, using yaml, uniqueItems keyword not reported in generated swagger.yaml for Node.js server. I tried to insert it manually in the generated file and validation works now correctly, verifying the uniqueness of elements in an array.

**Comment by wing328** [comment]
@alfi86 please share the spec so that we can try to reproduce the issue.

If you've a manual fix already, please file a PR with the fix by updating the mustache templates:

https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/nodejs
