### ISSUE TITLE
Upgrade to MacOS Sierra

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#4479]
##### Description

After upgrading to MacOS Sierra, swagger codegen takes a long time to build (`mvn clean package`). It's stuck at the following line during build:
```
t3968277263874257851/spec/spec_helper.rb
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/folders/11/tmg47v691834gdzzydfl0nch0000gn/T/junit3968277263874257851/spec/configuration_spec.rb
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/folders/11/tmg47v691834gdzzydfl0nch0000gn/T/junit3968277263874257851/spec/api_client_spec.rb
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/folders/11/tmg47v691834gdzzydfl0nch0000gn/T/junit3968277263874257851/.swagger-codegen-ignore
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/2_0/petstore.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/1_2/petstore-1.2/api-docs
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/1_2/petstore-1.2/api-docs
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/2_0/binaryDataTest.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/2_0/binaryDataTest.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml


```
Eventually it will get through. The issue happens for both Java 1.7 and 1.8.

##### Swagger-codegen version

Latest master 

##### Suggest a Fix

The issue seems related to OS upgrade so please do not upgrade to MacOS Sierra for the time being or use a virtual machine (Linux) as a workaround.

**Comment by wing328** [comment]
@taxpon thanks for sharing more. It could be due to something else with my machine then.

**Comment by scheert2** [comment]
@wing328 I had the same issue. This is obviously not ideal but after realizing this was a test it was hanging on, I looked for a skip tests flag and found this worked for me:
`mvn clean package -DskipTests`

**Comment by wing328** [comment]
@scheert2 I tried with that too but no luck in my case.

**Comment by scheert2** [comment]
@wing328 that's odd, it didn't hang in the same spot did it? If it's actually skipping tests it should breeze right over that bit.

**Comment by wing328** [comment]
@scheert2 I rebooted my Mac (haven't rebooted it for a while...) and now `mvn clean package -DskipTests` takes less than a minute to finish :)

**Comment by wing328** [comment]
No longer encountered the same issue after OS/JVM upgrade.
