### ISSUE TITLE
Swagger-codegen JSON parser fails silently

### ISSUE THREAD

**Issue by josephmisiti** [swagger-api/swagger-codegen#448]
I am using `swagger-docs` to generate my `json` and then use this project to create my clients. For some reason (which I have not figured out yet), `swagger-docs` generated invalid json for one of my APIs and when I point `swagger-codegen` at the api-docs.json file to generate the clients, it fails to produce code but doesnt say why. The only way to track this down is to point  `swagger-codegen` at each individual api.json file to see which one fails.

**Comment by webron** [comment]
Can you share the api-docs.json?

**Comment by fehguy** [comment]
I have seen this happen as well.  The [SwaggerCompatParser](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java) will fail completely if a single spec is not valid, and without any indication as to why

**Comment by jvieten** [comment]
also in this vain maybe this would help:

--- a/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/Codegen.java
+++ b/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/Codegen.java
@@ -89,6 +89,7 @@ public class Codegen extends DefaultGenerator {
         clientOpts.getProperties().put("templateDir", String.valueOf(cmd.getOptionValue("t")));
     }
     catch (Exception e) {
+               e.printStackTrace();
       usage(options);
       return;
     }
many greetings

**Comment by TuomasKiviaho** [comment]
I stumbled also to this as a first impression of the project. It took me a while to figure out that the problem wasn't in the options that I gave.

I suggest that the ``new SwaggerParser().read()`` would be simply moved out from ``try/catch(...){usage(options);return;}`` block. I guess that the latter try/catch could be removed (and let main() throw exceptions)

```
java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.convertParameter(SwaggerCompatConverter.java:183)
	at io.swagger.parser.SwaggerCompatConverter.convertOperation(SwaggerCompatConverter.java:314)
	at io.swagger.parser.SwaggerCompatConverter.convert(SwaggerCompatConverter.java:454)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:111)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:87)
        ...
```

**Comment by josephmisiti** [comment]
@webron i can email you the file the fails if that would help

**Comment by webron** [comment]
Please do. You can add Tony to the email as well.

**Comment by fehguy** [comment]
OK I've made this better in swagger-parser-1.0.2-SNAPSHOT.  https://github.com/swagger-api/swagger-parser/issues/17

Expect this to come out in a release shortly
