### ISSUE TITLE
Nancyfx prefix interfaces with I in generated code

### ISSUE THREAD

**Issue by Razzeee** [swagger-api/swagger-codegen#4486]
##### Description

Not exactly a problem, but its a convention to prefix interfaces with `I` in c#

##### Swagger-codegen version

Latest master

##### Suggest a Fix

https://github.com/Razzeee/swagger-codegen/tree/nancyfx-interface
Might be considered a breaking changes, as users might be derriving from the interfaces and now need to change the name. So I can understand if you don't want to do this.

**Comment by wing328** [comment]
@Razzeee it's definitely reasonable and making the change in `2.3.0` is definitely a good idea as it's a breaking change. If later more people want the interfaces named without the `I`, we can add an option as a fallback.

cc @mstefaniuk (the author of the C# Nancyfx generator)

**Comment by mstefaniuk** [comment]
I'm against that convention and against that change in particular. It exposes in naming differences that are should not be exposed. As a consequence of that convention interfaces are prefixed with `I` but concrete class (first one) has no implementation indicator. It should go opposite - interfaces should have clean names but implementation should have implementation specific suffix. In Java there was also such bad convention (as adding `A` to abstracts) but it was dropped many years ago.
This idea has been discussed deeply in _Clean code_ of Robert Martin and also pops out on SO sites http://softwareengineering.stackexchange.com/questions/117348/should-interface-names-begin-with-an-i-prefix and http://stackoverflow.com/questions/5816951/prefixing-interfaces-with-i.

**Comment by Razzeee** [comment]
As much as I want to go with you on this, the one comment on SO pretty much summed it up for me:

> All of this being said, I tend to prefix my C# interfaces with I anyway because that is the .NET convention used and advocated by Microsoft. And when I'm explaining coding conventions to a new developer, it's far less hassle to just use Microsoft's rules than to explain why we have our own "special" rules.

**Comment by wing328** [comment]
What about adding an option (default to false) to prefix the interface with `I` so as to accommodate difference developer style/preference?

cc @jimschubert

**Comment by jimschubert** [comment]
I'm all for this change, even if it means using an option that defaults to the I prefix.

Microsoft's [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/ms229040(v=vs.110).aspx) suggest: 
--- 
✓ DO prefix interface names with the letter I, to indicate that the type is an interface.

For example, IComponent (descriptive noun), ICustomAttributeProvider (noun phrase), and IPersistable (adjective) are appropriate interface names. As with other type names, avoid abbreviations.

---

✓ DO ensure that the names differ only by the "I" prefix on the interface name when you are defining a class–interface pair where the class is a standard implementation of the interface

---

**Comment by jimschubert** [comment]
@Razzeee @wing328 @mstefaniuk I've opened a PR for allowing to customize this behavior. I added support to the C# generator for true/false/custom interface prefix using the `interfacePrefix` additional property.  I didn't get a response about the preferred behavior according to Microsoft's guidelines, so I've set the default in the NancyFX generator to be empty according to the above discussion.  I agree enforcing the I- prefix now _could be_ a breaking change, but I don't know how likely it is to be a problem.

**Comment by wing328** [comment]
@Razzeee the enhancement (PR) by @jimschubert has been merged into master. Please pull the latest master to give it a try.

**Comment by craffael** [comment]
I just noticed that the option `interfacePrefix=I` leads to a compilation error: The swagger file

    swagger: "2.0"
    info:
      description: "API Documentation of Security Service that is used to create machine and user access tokens"
      version: "1.0.0"
      title: "Security Service"
      
    paths:
      /foo:
        get:
          responses:
            200:
              description: "successful"

Now  swagger-codegen with `interfacePrefix=I` yields the following module:

    public sealed class DefaultModule : NancyModule
    {
        public DefaultModule(DefaultService service) : base("") // Interface Prefix missing here!!!
        { 
            Get["/foo"] = parameters =>
            {
                
                service.FooGet(Context);
                return new Response { ContentType = ""};
            };
        }
    }
    public interface IDefaultService // Interface Prefix correct here
    {
        void FooGet(NancyContext context);
    }
    ...

As you can see the interface prefix went missing in the constructor of `DefaultModule`! Hence the generated code doesn't compile.
