### ISSUE TITLE
Issue running CI tests for Typescript-Fetch API client

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#4498]
##### Description

As part of https://github.com/swagger-api/swagger-codegen/pull/4497, I've sync'd master into 2.3.0 but couldn't properly resolve the merge conflicts with the [typescript-fetch test files](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-fetch/tests/default/test). Here is the error when running the integration test:

```
test/PetApi.ts(18,16): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(23,18): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(23,78): error TS7006: Parameter 'result' implicitly has an 'any' type.
test/PetApi.ts(29,16): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(29,77): error TS7006: Parameter 'result' implicitly has an 'any' type.
test/PetApi.ts(31,18): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(32,20): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(32,81): error TS7006: Parameter 'result' implicitly has an 'any' type.
test/PetApi.ts(40,16): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(44,18): error TS2346: Supplied parameters do not match any signature of call target.
test/PetApi.ts(44,78): error TS7006: Parameter 'result' implicitly has an 'any' type.
test/PetApi.ts(46,15): error TS7006: Parameter 'err' implicitly has an 'any' type.
test/StoreApi.ts(17,16): error TS2346: Supplied parameters do not match any signature of call target.
test/StoreApi.ts(17,55): error TS7006: Parameter 'result' implicitly has an 'any' type.
```

The typescript-fetch CI tests have been commented out in pom.xml for the time being.

##### Swagger-codegen version

Latest 2.3.0

##### Steps to reproduce

```
git checkout 2.3.0
git pull origin 2.3.0
cd samples/client/petstore/typescript-fetch/tests/default
npm install
npm test
```

**Comment by wing328** [comment]
@alechill if you've time, I wonder if you can take a look at this as you've previously helped improve the test cases.

My apologies for the additional work due to the failed merge.

**Comment by alechill** [comment]
@wing328 No probs, I'll take a look at the weekend

**Comment by alechill** [comment]
@wing328 Fixed, PR raised against 2.3.0 branch

**Comment by ePaul** [comment]
Is this related to the currently occasionally (but not consistently) failing Travis CI builds, e.g. https://travis-ci.org/swagger-api/swagger-codegen/builds/208320810 ?

**Comment by alechill** [comment]
@ePaul Nope this was simply due to a bad merge
