### ISSUE TITLE
Add Curl connect timeout configuration option for PHP Client

### ISSUE THREAD

**Issue by brianvoss** [swagger-api/swagger-codegen#4499]
##### Description

If a service is down, we want the client to fail quickly so the requesting app doesn't hang.  This means that the Curl timeout setting is not enough.  Would like to add this setting inline with the existing Curl timeout setting in the PHP mustache templates.

##### Swagger-codegen version

dev-master

##### Swagger declaration file content or url
N/A

##### Command line used for generation

```
./run-in-docker.sh "generate -i /gen/myservice-swagger/main -l php -o /gen/myservice-client/php/ -c php-config.json"
```
##### Steps to reproduce

N/A

##### Related issues

N/A

##### Suggest a Fix

I have the code for this ready and can file a PR asap

**Comment by arnested** [comment]
Your pull request looks good and useful and can be merged.

Thank you for your contribution to Swagger Codegen!

**Comment by wing328** [comment]
@brianvoss PR has been merged into master. Please pull the latest master to give it a try.

Thanks for your contribution.
