### ISSUE TITLE
iOS codegen creates methods with unused variable warnings

### ISSUE THREAD

**Issue by mad102190** [swagger-api/swagger-codegen#450]
I created a podspec for the codegen output so that we could easily add the code to our project every time we push new versions, but the podspec requires there to be no warnings or errors, and the unused variables in the `SWGDefaultApi.m` class cause the podspec generation to fail. 

The variable in question is `m_body`. It's created in many of the methods, but sometimes it's simply assigned a nil value, and is then unused in the remainder of the method. 
````id m_body = nil;````

Could we omit this line if its only going to be assigned a nil value, or at least use the variable in some useless line like:
````
if(m_body == nil)
    m_body = nil;
````

**Comment by fehguy** [comment]
what version of codegen are you using? 2.1.1-M1?

**Comment by mad102190** [comment]
I just realized that this might have been built with an outdated jar. I'm going to rebuild with 2.1.1-M1 and check if this still occurs and if not I'll close the ticket.

**Comment by mad102190** [comment]
Ok so the `m_body' issue seems to be gone, but now the warnings generated by AFNetworking 2.1 are preventing the podspec from building: 

````AFNetworking/AFNetworking/AFHTTPRequestOperation.h:38:60: warning: auto property synthesis will not synthesize property 'response'; it will be implemented by its superclass, use @dynamic to acknowledge intention [-Wobjc-property-synthesis]````

What would you recommend doing to avoid this warning?

**Comment by fehguy** [comment]
Can you take a look here?

https://github.com/AFNetworking/AFNetworking/issues/1774

Maybe need a bump of AF?

**Comment by mad102190** [comment]
Looks like it. Could also be that I'm using Xcode 6.3 Beta. I'll close this for now and re-add under a new (aptly-named) ticket if the issue still exists once Xcode 6.3 is officially released.
