### ISSUE TITLE
[PHP] headers are not returned from object serialzation

### ISSUE THREAD

**Issue by tristansokol** [swagger-api/swagger-codegen#4501]
##### Description

Generated php libraries don't seem to use HTTP header information in object serialization to return the specified headers in the response in any way. 
##### Swagger-codegen version

2.2.1 ( last commit: 27f1b6ee988767129ed2696e204f0c80f3d13adc)

##### Swagger declaration file content or url
    
```json
                "get": {
                "tags": [
                    "Employees"
                ],
                "operationId": "ListEmployeeRoles",
                "description": "Provides summary information for all of a business's employee roles.",
                "parameters": [{
                    "name": "cursor",
                    "description": "A pagination cursor to retrieve the next set of results for your\noriginal query to the endpoint.",
                    "type": "string",
                    "in": "query",
                    "required": false
                }],
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_READ"]
                }],
                "deprecated": false,
                "responses": {
                    "200": {
                        "description": "Success",
                        "headers": {
                            "Link": {
                                "description": "If returned, there are too many items to return in one request and you must paginate with the supplied link.",
                                "type": "string"
                            }
                        },
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/EmployeeRole"
                            }
                        }
                    }
                }
            }
        },
```

##### Command line used for generation

`Swagger-codegen generate -i ~/api.json -l php`

##### Steps to reproduce
Generate php library from swagger that has a response header defined, php object serializer only checks if header is `Content-Disposition`. Never gets added to response. 

##### Related issues

I was unable to find a similar issue via, although there are many and I appologize if this has been raised before. 

##### Suggest a Fix

Seems like adding a bit to the [ObjectSerializer](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache) Template to iterate through headers, look for matches and return them in the response some how would do the trick?

**Comment by wing328** [comment]
@tristansokol in your swagger/openapi spec, did you define a proper `produces`?

**Comment by tristansokol** [comment]
@wing328 
I have `application/json`, Is there an addition I should make to to get info from the headers? 
My full (draft) spec is here: https://github.com/square/connect-api-specification/blob/tristans-holiday-hack/api.json

**Comment by wing328** [comment]
@tristansokol then the PHP API client should be able to deserialize the JSON string back into a model.

Did you mean you want to extract certain information from the HTTP response headers? There's an `WithHttpInfo` method for each endpoint operation to obtain not only the response but also the status code and HTTP headers.

An example of the HTTP response (header + body) and what you actually expect from the function would be helpful.

**Comment by tristansokol** [comment]
Primarily it is unclear how the headers aspect of http://swagger.io/specification/#responseObject works in regard to SDK generation. We have an api that uses header based pagination, so a json array is returned, and if there are more, you'll also get a `Link` header in the response, like `Link:<https://connect.squareup.com/v1/LOCATION_ID/payments?batch_token=BATCH_TOKEN>;rel='next'`. Is the only way to access it by using the `WithHttpInfo` methods?

**Comment by wing328** [comment]
@tristansokol The headers of the HTTP response are used only when deserializing `file` response: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php#L257-L272

Currently, the `WithHttpInfo` is the only way to retrieve the HTTP response headers. If it's insufficient, please share more with us on why it's the case and how it can be improved to meet your requirement.

**Comment by tristansokol** [comment]
I see, I wasn't aware that the `WithHttpInfo` functions were really meant to be accessed directly. Thanks for your help!
