### ISSUE TITLE
[PHP] Add minimum PHP version required to composer.json

### ISSUE THREAD

**Issue by philip** [swagger-api/swagger-codegen#4516]
##### Description

Today, the generated README.md lists "PHP 5.4.0 and later" as a requirement, whereas the generated composer.json does not contain required PHP version information.

##### Swagger-codegen version

2.2.1

##### Suggest a Fix

Also update composer.json, so today that means:

`"require": {`
`    "php": ">=5.4",`
`    ...`

**Comment by wing328** [comment]
@philip your suggestion sounds good to me.

May I know if you've time to file a PR for the enhancement?

**Comment by philip** [comment]
@wing328 Yep, I'll submit a PR. But I wonder, how is this minimum PHP version determined? Also, is it a static value or is it defined in a single location then referred to elsewhere like a variable?

I'll dig into the code later this week to submit a PR, which might reveal the answer to these questions.

**Comment by philip** [comment]
Looks like my request is bogus, as I confused the generated composer.json with the composer entry within README.md. The 5.4+ requirement is already in composer.mustache. Sorry for the unnecessary noise :(
