### ISSUE TITLE
[JAVA] Incorrect api method signature is generated when using java 8 dates and modelNameSuffix configuration parameter.

### ISSUE THREAD

**Issue by liqidator** [swagger-api/swagger-codegen#4522]
##### Description

[JAVA] When I use maven codegen swagger plugin with java8 date types and modelNameSuffix parameter, it will generate incompilable code .... instead of date type OffsetDateTime there will be OffsetDateTime + modelNameSuffix

##### Swagger-codegen version

Maven plugin 2.2.1

##### Swagger declaration file content or url

/requests:
    get:
      summary: List all requests
      tags:
        - requests
      parameters:
        - name: applicationId
          in: header
          description: Identification of the calling application. (web, lombardi etc.)
          required: true
          type: string
        - name: createdDateFrom
          in: query
          description: Filters out requests created before provided date.
          type: string
          format: 'date-time'
        - name: createdDateTo
          in: query
          description: Filters out requests created after provided date.
          type: string
          format: 'date-time'
      responses:
        200:
          description: Array of requests
          schema:
            type: array
            items:
              $ref: '#/definitions/Request'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

##### Command line used for generation

<configuration>                            
                            <inputSpec>${basedir}/src/main/resources/api/kb-online-api.yaml</inputSpec>
                            <language>spring</language>
                            <verbose>${swagger.debug}</verbose>
                            <modelNameSuffix>Gen</modelNameSuffix>
                            <configOptions>
                                <title>${project.parent.name}</title>
                                <sourceFolder>/src/main/java</sourceFolder>
                                <apiPackage>api.rest.generated</apiPackage>
                                <modelPackage>model.rest.generated</modelPackage>
                                <invokerPackage>rest.generated</invokerPackage>
                                <library>spring-boot</library>
                                <dateLibrary>java8</dateLibrary>
                                <async>true</async>
                                <java8>true</java8>
                                <interfaceOnly>true</interfaceOnly>
                                <serializableModel>true</serializableModel>
                                <debugSupportingFiles>${swagger.debug}</debugSupportingFiles>
                                <debugSwagger>${swagger.debug}</debugSwagger>
                                <debugOperations>${swagger.debug}</debugOperations>
                            </configOptions>
                        </configuration>

##### Steps to reproduce

Create query parameter of 
type: string and format: 'date-time'.

Use maven codegen plugin with the configuration above (above all with modelNameSuffix set to 'Gen' and with dateLibrary java8).

The generated api method contains nonsense: instead of OffSetDateTime there will be OffsetDateTimeGen. And therefore it is incompilable.

##### Suggest a Fix
Sorry, I just noticed it is duplicate to #4522

**Comment by wing328** [comment]
@liqidator please pull the latest master to give it another as the issue should have been addressed.
