### ISSUE TITLE
Forward references in include files no longer handled properly

### ISSUE THREAD

**Issue by ssteinerx** [swagger-api/swagger-codegen#4523]
In swagger-codegen: stable 2.2.1, a forward reference to a definition within a `$ref:`'d file worked properly, in current versions (master and 2.2.3) it does not.

##### Description
In the following, `ping.yaml` is included in the main `swagger.yaml`.

It refers to the schema `PingStat`, which is in the `definitions:` of the main `swagger.yaml`.

The actual schema for `PingStat` is in an external `$ref:`'d file.

The 2.2.1 seems to have included all of the `$ref:` files prior to actually trying to parse the resultant `.yaml` file and the "forward reference" to `PingStat` resolves just fine.

In the current `master` and `2.2.3` branches, the same `swagger.yaml` file throws an error when including `./swagger-chunks/ping.yaml` complaining that 'PingStat' hasn't been defined.

The old behaviour was much better, in my opinion.

```yaml
swagger.yaml
--------------
paths:
  /ping:
    $ref: ./swagger-chunks/ping.yaml
...
definitions:
  PingStat:
    $ref: ./swagger-chunks/pingstat.yaml
```

##### Swagger-codegen version

2.2.1 processes the file just fine, master and the 2.2.3 branch complain as described above.

##### Command line used for generation

```
java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar     generate 		\
	-l python-flask 				\
	-i PingAPI/swagger.yaml 				\
	-o ./flask-server/PingAPI
```

##### Suggest a Fix

The issue appears to be a change in the order of operations on the YAML file.  The working version (2.2.1) seems to have built the full YAML file from  all the parts, then worried about parsing it.  The current version seems to try an incremental approach which breaks forward references.

**Comment by wing328** [comment]
@ssteinerx as you probably aware, the latest master of Swagger Codegen is using a newer version of Swagger Parser.

Please share the spec files via https://gist.github.com so that we can reproduce the issue more easily.

**Comment by wing328** [comment]
Closing this as there's no update.
