### ISSUE TITLE
swagger-codegen 2.2.2-SNAPSHOT uses deleted swagger-parser SNAPSHOT version 

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-codegen#4535]
Using io.swagger:swagger-codegen-maven-plugin:2.2.2-SNAPSHOT, the following artifacts could not be resolved: 
io.swagger:swagger-parser:jar:1.0.24-SNAPSHOT, 
io.swagger:swagger-compat-spec-parser:jar:1.0.24-SNAPSHOT:

According to https://oss.sonatype.org/content/repositories/snapshots, these versions of swagger-parse and swagger-compat-spec-parse do  ot exist, yet they are still refernced from swagger-codegen*2.2.2-SNAPSHOT.

Also, the latest deployment of swagger-codegen*2.2.2-SNAPSHOT was back in November. 

Can swagger-codegen be propagated ? Or is there another repository that I should use?

**Comment by wing328** [comment]
@jeff9finger I think we will need to publish another `io.swagger:swagger-codegen-maven-plugin:2.2.2-SNAPSHOT` based on the latest master with the new parser.

cc @fehguy

**Comment by jeff9finger** [comment]
FYI: I am unable to use the maven-plugin SNAPSHOT at the moment. I've tried excluding the swagger-parser and swagger-parser-compat dependencies (1.0.24-SNAPSHOT), and including 1.0.25 (also tried 1.0.26-SNAPSHOT) but somehow downloading the 1.0.24 dependency is always attempted.

Is anyone else having a similar issue? Any workarounds?
Or can we just get this published?

Thanks

**Comment by wing328** [comment]
@jeff9finger as a workaround, what about doing a `mvn clean install` to install swagger parser 1.0.24-SNAPSHOT in the local Maven store?

You will need to clone the swagger parser project and update the pom with "1.0.24-SNAPSHOT".

**Comment by jeff9finger** [comment]
Thanks for the suggestion. This won't work in our situation because this artifact is needed for others in the company.

I have a workaround in place now, though

**Comment by wing328** [comment]
Closing this as 2.2.2 will be released soon (Feb 2017)
