### ISSUE TITLE
Query Parameter missing in swift 3 export

### ISSUE THREAD

**Issue by Vario** [swagger-api/swagger-codegen#4536]
##### Description

We have a swagger definition with a PUT Request which contains a Body DTO with properties to update, header parameters and path parameters and one query parameter.

the parameter is in the method definition updateXXXUsingPUTWithRequestBuilder but it is not used in the code and not appended to the url..

##### Swagger-codegen version

2.2.2

##### Steps to reproduce

i assume, generating a PUT request with body, header, path and query parameters with swift 3 template

in the generated code there is this part missing
var path = "//path**?queryparametername={queryparametervalue}**"
**path = path.replacingOccurrences(of: "{queryparametervalue}", with: "\(queryparametervalue)", options: .literal, range: nil)**

**Comment by tomekc** [comment]
Can you share a fragment of spec? I think I can look into it.

**Comment by tomekc** [comment]
Did you try latest version from master? I addressed this issue (query parameters are ignored when making POST with request body) and it has been merged in #1564

**Comment by Vario** [comment]
Which fragment do you need from the spec? i dont know why but i cant load the master project on my machine. do you have a .jar file which i can test with my spec?

**Comment by wing328** [comment]
@Vario what error did you get when building the project locally?

**Comment by Vario** [comment]
actually i'm getting stuck loading the project, the entire project is empty.

**Comment by wing328** [comment]
@Vario you may want to try "git clone https://github.com/swagger-api/swagger-codegen.git" again in a new directory to see if that makes any difference.

**Comment by tomekc** [comment]
@Vario were you trying to load project in IDE? Why not trying command line. Checkout as @wing328 say, then enter the project directory in Terminal,

```
mvn package
```

and then 

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
```

should run your newly built swagger-codegen.

**Comment by Vario** [comment]
okay, i got the new jar file, but the query parameters are still missing. they are listed in the method description above as query but in the var path= "/url..../ nothing like ?parameter={value} can be seen or is used in the code below.

**Comment by tomekc** [comment]
Can you share swagger specification (YAML preferred) of the method you want code generated? Rename things if you need, just want to make sure we are on the same page.

**Comment by Vario** [comment]
problem solved, i updated the jar file, but not the templates, and 4 days ago a commit changed them to include query parameters. this issue is solved!

**Comment by wing328** [comment]
Glad to hear that it's now resolved.

**Comment by wing328** [comment]
Thanks @tomekc for addressing this issue.
