### ISSUE TITLE
io.github.swagger2markup.internal.document.OverviewDocument doesn't found with swagger2markup-1.1.1.jar when generate files

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-codegen#4542]
##### Swagger-codegen version

swagger2markup-1.1.1.jar

##### Command line used for generation

		CodegenConfigurator configurator = CodegenConfigurator.fromFile(configFile);
		new DefaultGenerator().opts(configurator.toClientOptInput()).generate();
	
		Path localSwaggerFile = Paths.get(yamlFile);
		Path outputFile = Paths.get(asciidocFile);		

		Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder() 
				.withPathsGroupedBy(GroupBy.TAGS)
				.withOperationOrdering(OrderBy.AS_IS)
		        .withOutputLanguage(Language.ZH) 
		        .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
		        .build(); 
		Swagger2MarkupConverter.from(localSwaggerFile) 
		        .withConfig(config)
		        .build() 
		        .toFolder(outputFile);

        MarkupDocBuilder builder = MarkupDocBuilders.documentBuilder(MarkupLanguage.ASCIIDOC);

      it is throws java.lang.NoClassDefFoundError: javaslang/Function2 ,when i followed the code with debug mode,it is can not find the class of io.github.swagger2markup.internal.document.OverviewDocument,but it is exist in jar, and it generate ok when using swagger2markup-1.0.1.jar
       when i add: 
Class.forName("io.github.swagger2markup.internal.document.OverviewDocument"); it also throw the exception

**Comment by zcb22000** [comment]
my pom.xml is :
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.huawei.m2m.ecosystem.platform</groupId>
		<artifactId>rest-api</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>codegenerator</artifactId>

	<properties>
		<swagger-codegen.version>2.2.1</swagger-codegen.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-codegen</artifactId>
			<version>${swagger-codegen.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-configuration2</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.9.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.0</version>
		</dependency>
		<dependency>
			<groupId>org.pegdown</groupId>
			<artifactId>pegdown</artifactId>
			<version>1.6.0</version>
		</dependency>

		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj</artifactId>
			<version>1.5.4</version>
		</dependency>
		

		<dependency>
			<groupId>io.github.swagger2markup</groupId>
			<artifactId>swagger2markup</artifactId>
			<version>1.0.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/swagger2markup-1.1.1.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>nl.jworks.markdown_to_asciidoc</groupId>
			<artifactId>markdown_to_asciidoc</artifactId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/markdown_to_asciidoc-1.0.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>io.github.swagger2markup</groupId>
			<artifactId>markup-document-builder</artifactId>
			<version>1.1.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/markup-document-builder-1.1.1.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.shared</groupId>
			<artifactId>maven-invoker</artifactId>
			<version>2.2</version> 
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.9</version>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by wing328** [comment]
For issues related to Swagger2Markup, please report to  https://github.com/Swagger2Markup/swagger2markup

**Comment by zcb22000** [comment]
ok,thanks
