### ISSUE TITLE
Requests dont add Content-type defined in swagger definition Swift 3

### ISSUE THREAD

**Issue by Vario** [swagger-api/swagger-codegen#4546]
##### Description

The generated API does not include the consumes property which is defined in the definition json.
,"consumes":["application/json"],"produces":["*/*"],

if i print the request in the processRequest method from the AlamofireImplementations, i get the following 

`curl -i \
	-X PUT \
	-b "JSESSIONID=....ID....." \
	-H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
	-H "Accept-Language: de-AT;q=1.0, en-US;q=0.9" \ .....`

Do i habe to specify the content-type anywhere else, or is it a bug in the template / generator for swift 3?
##### Swagger-codegen version

2.2.2

**Comment by wing328** [comment]
@Vario thanks for reporting the issue. You're correct in saying that `consumes`, `produces` are not being leverage in Swift (2.x, 3.x) templates at the moment.

May I know if you've time to contribute the enhancement? If yes, I can show you some good starting points.

**Comment by wing328** [comment]
The ObjC API template is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/objc/api-body.mustache#L134-L144

**Comment by Vario** [comment]
Okay i'll give it a try, i havent done anything with mustache files yet.
I assume i have to change the api.mustache and APIs.mustache file.

**Comment by wing328** [comment]
Thanks 👍 

For `swift3`, I believe you will need to add the logic in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift3/api.mustache#L140

For `swift`, https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/api.mustache#L123 should be the starting point.

Let us know if you need any help.

**Comment by Vario** [comment]
its more difficult than i thought and i'm not sure if i can solve it as fast as i would need it..
matching objective c with the swift code structure seems to be completely different.

**Comment by wing328** [comment]
@jaz-ah @jgavris @hexelon any pointer on how @Vario can add the headers based on `consumes`, `produces` provided in the spec to Swift3 API client?

**Comment by Vario** [comment]
5 days ago a new template for swift 3 was commited and i havent recognized that. now the Content-Type is added correctly!
thank you guys

**Comment by wing328** [comment]
@Vario thanks for the update.
