### ISSUE TITLE
Spaces in .yaml causes them to be interpreted as json

### ISSUE THREAD

**Issue by deibl** [swagger-api/swagger-codegen#4555]
##### Description
More than one space after ":", when setting an attribute in .yaml file, causes it to be interpreted as json which Results in parse Exception (Unexpected character). Removing the additional spaces fixes the problem.

##### Swagger-codegen version
2.2.0

##### Swagger declaration file content or url
Relevant part from xxx.yaml:
`definitions:`
`Entity:`
`...`
`properties:`
`propertyName:`
`        title:  Material ID <- 2 Spaces between ":" and "M"`

##### Command line used for generation
java -Dmodels -Dapis -DapiTests=false -jar swagger-codegen-cli-2.2.0.jar generate -i xxx.yaml -l jaxrs -c config.json

##### Config
{
"sourceFolder" : "src/main/java",
"implFolder" : "src/main/java",
"modelPackage" : "package.generated.data",
"apiPackage" : "package.generated.api",
"invokerPackage" : "package.invoker",
"library" : "jersey2"
}

**Comment by wing328** [comment]
@deibl seems to me an issue with your YAML file. Have you used some online YAML validator to validate the file? e.g. http://www.yamllint.com/

**Comment by deibl** [comment]
@wing328 The YAML File seems to be valid according to your yamllint.com and swagger Editor validation.
For reproduction i attached a minimal file which causes the problem (i did save it as .txt to enable upload on github). Saving it as xxx.yaml and use it as src for codegen results in json parse exception. Removing extra spaces in line 32 resolves the problem. 
Command used: java -jar swagger-codegen-cli-2.2.0.jar generate -i swagger.yaml -l jaxrs
[invalidyaml.txt](https://github.com/swagger-api/swagger-codegen/files/710495/invalidyaml.txt)

**Comment by fehguy** [comment]
@deibl the reason this fails is because you have tabs in your spec, and according to the official YAML guys... "Tabs have been outlawed"

http://www.yaml.org/faq.html
