### ISSUE TITLE
[typescript-angular2] Generated model attributes always start with lowercase char

### ISSUE THREAD

**Issue by bloody-orange** [swagger-api/swagger-codegen#4558]
##### Description

The models generated by the cli always have attributes whose first character is lowercase. My properties all start with an uppercase character though, and they are also written like that in the API and the swagger doc. 

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url

```yaml
{ ...
"definitions":{ ... 
    "Rating":{"type":"object","properties":{
        "RatingId":{"format":"int32","type":"integer"},
        "Player":{"$ref":"#/definitions/Player"},
        "Datetime":{"format":"date-time","type":"string"},
        "Value":{"format":"int32","type":"integer"}
    }}
}}
```

generates:

```javascript
export interface Rating {
    ratingId?: number;
    player?: models.Player;
    datetime?: Date;
    value?: number;
}
```

##### Command line used for generation

CMD:
```
java -jar swagger-codegen-cli-2.2.1.jar generate -o [...]\src\app \
-i http:\\localhost:4649/swagger/docs/v1 -l typescript-angular2
```

**Comment by wing328** [comment]
@bloody-orange there's an option change the variable naming:
```
	modelPropertyNaming
	    Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name (Default: camelCase)
```

Ref: `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l typescript-angular2`

**Comment by wing328** [comment]
@bloody-orange there's also another PR to use an ObjectSerializer to handle mapping of the JSON key name: https://github.com/swagger-api/swagger-codegen/pull/4264

Please kindly it test out by runnning:
```
git checkout -b TiFu-typescriptPropertyNamingFix 2.3.0
git pull https://github.com/TiFu/swagger-codegen.git typescriptPropertyNamingFix
```

**Comment by bloody-orange** [comment]
@wing328  thanks for the quick response
The config works perfectly, thanks again.

**Comment by wing328** [comment]
@bloody-orange no problem. Let us know if you've further feedback.

(we've just added Swagger Codegen to ProductHunt: https://www.producthunt.com/posts/swagger-codegen, pleae upvote found Swagger Codegen useful)
