### ISSUE TITLE
Malformed, but accepted, schema reference produces python-flask output that imports non-existent models.object

### ISSUE THREAD

**Issue by jasco** [swagger-api/swagger-codegen#4567]
I mistakenly described a schema `definitions` reference as follows.  Unless there is some valid scenario that precluded producing an error, it would be helpful if this construct produced an obvious error.

```
schema:
  type: object
  items:
    $ref: '#/definitions/User'
```

It should have been described as:

```
schema:
  $ref: '#/definitions/User'
```

The python-flask generator accepted the input and produced code that attempted to import non-existent models.object in both the controller and controller-tests.

    from swagger_server.models.object import object

This was observed using a build from commit 0fb154e.  As far as I know this is a long-standing issue.  I do not know whether this project shares the validator with the swagger-editor, but I will mention that the Swagger Editor accepted the bad input without complaint and produced mysteriously empty objects in the auto docs.

**Comment by wing328** [comment]
@jasco thanks for the suggestion to produce more obvious error message. Swagger Codegen relies on [Swagger Parser](github.com/swagger-api/swagger-parser) to parse the spec.

I would recommend you to submit your suggestion to the Swagger Parser project directly.

**Comment by jasco** [comment]
@wing328 Thank you.  It appears someone has already reported it.
https://github.com/swagger-api/swagger-parser/issues/237

**Comment by wing328** [comment]
@jasco ok. will use that one to track instead.
