### ISSUE TITLE
muti small yaml files does not work by ref in yaml file

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-codegen#4568]
I want to split yaml file to small files. But it doesn't work when generate. How to use muti yaml files for micro-service project? And How to specified apipackage and modulpackge for each yaml file?
I am followd with "http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html".

##### Swagger declaration file content or url

paths:
  $ref: './paths/index.yaml'         
            
definitions:
  $ref: ./definitions/definitions.yaml  

##### Command line used for generation

        CodegenConfigurator configurator = CodegenConfigurator.fromFile(configFile);
        new DefaultGenerator().opts(configurator.toClientOptInput()).generate();
    
        Path outputFile = Paths.get(asciidocFile);

        Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder() 
                .withPathsGroupedBy(GroupBy.TAGS)
                .withOperationOrdering(OrderBy.NATURAL)
                .withOutputLanguage(Language.ZH) 
                .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
                .build(); 
        Swagger2MarkupConverter.from(configurator.getInputSpec()) 
                .withConfig(config)
                .build() 
                .toFolder(outputFile);; 
##### Steps to reproduce
 The output json as bellow:
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.1.0",
    "title" : "IoT Platform NSCL Service REST API",
    "termsOfService" : "used for Application developing"
  },
  "host" : "184.2.9.57:8843",
  "basePath" : "/iocm/app/v1.1.0",
  "tags" : [ {
    "name" : "订阅管理",
    "description" : "订阅管理"
  }, {
    "name" : "事件管理",
    "description" : "事件管理"
  } ],
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "paths" : { },
  "securityDefinitions" : {
    "basic_auth" : {
      "type" : "basic"
    },
    "app_key" : {
      "type" : "apiKey",
      "name" : "app_key",
      "in" : "header"
    }
  },
  "definitions" : { },
  "securityRequirement" : [ {
    "app_key" : [ ]
  }, {
    "basic_auth" : [ ]
  } ]
}

**Comment by wing328** [comment]
@zcb22000 you're using 2.2.1. Please pull the latest master to give it a try as the latest Swagger Codegen uses a newer version of Swagger parser with better handling of external references.

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by valeriucraciun** [comment]
this is still not working on 2.2.2

**Comment by wing328** [comment]
@valeriucraciun please share the spec via https://gist.github.com so that we can more easily reproduce the issue.

**Comment by XtreZz** [comment]
It works on master (2.2.3-SNAPSHOT).Will this be released soon ? this is an important feature i guess.

**Comment by wing328** [comment]
2.2.3 will be released 3 or 4 months later.

Upcoming release is 2.3.0, which is scheduled to be released in Apr 2017. Please test `2.3.0` as well.
