### ISSUE TITLE
[JAXRS-CXF] basePath ignored since #4068

### ISSUE THREAD

**Issue by markus-wa** [swagger-api/swagger-codegen#4569]
##### Description

In the CXF generator the basePath gets ignored since #4068 and all paths changed from 'host/basePath/operationPath' to 'host/operationPath'.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: missing basePath example
host: example.com
basePath: /exa
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /mple:
    get:
      responses:
        200:
          description:  Example
```

generates

```java
...
@Path("/")
@Api(value = "/", description = "")
public interface DefaultApi  {

    @GET
    @Path("/mple")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "", tags={  })
    public void mpleGet();
}
```

instead of
```java
...
@Path("/exa")
...
```

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.2-SNAPSHOT.jar generate -i schema.json -l jaxrs-cxf

##### Steps to reproduce

Use a basePath in your swagger spec and generate the CXF server code.

##### Related issues

Pull #4068

##### Suggest a Fix

Change 
```java
@Path("/")
```
in https://github.com/swagger-api/swagger-codegen/blob/14bca6cd8922e6134c5848378e2c86151c439486/modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/api.mustache#L21
back to
```java
@Path("{{contextPath}}")
```

**Comment by wing328** [comment]
@markus-wa thanks for reporting the issue. Please submit a PR so that we can review the fix.

**Comment by sbarinov** [comment]
Am I the only one who still experiences this issue with 2.3.1?

**Comment by staraise** [comment]
still have this in 2.4.13, as I see the spring version got fixed, but all of the jax-rs ones are still bugged.
