### ISSUE TITLE
[Question] Digest authentication

### ISSUE THREAD

**Issue by bricev** [swagger-api/swagger-codegen#457]
Hi,

After some investigations, I couldn't find any support for HTTP Digest authentication.
It seems this prevent our project from using Swagger to generate clients for our RESTful webservices.

What would be the best way to add support for this in "Code Generator"? 

Thanks for your advices :)

**Comment by fehguy** [comment]
I would suggest that you simply enhance the templates to sign requests as needed.

**Comment by wing328** [comment]
@bricev to support HTTP digest authentication, you can try extending the class "ApiClient" and override the `callApi method` to add the header for HTTP Digest authentication. Would that meet your requirement ?

**Comment by fehguy** [comment]
Closing as not active.
