### ISSUE TITLE
[Typescript] Payload for Array of Enums Not Valid

### ISSUE THREAD

**Issue by nheinbaugh** [swagger-api/swagger-codegen#4577]
##### Description

When my API request accepts an array of enum values the generated typescript code is invalid.

JSON File (the smallest piece I could grab, let me know if you need more):

`{"type":"object","properties":{"id":{"format":"uuid","type":"string"},"Foo":{"enum":["Foo", "Bar"],"type":"string"}}}`

Generated Code:

```
export interface FooWrapper {
    data?: ApiNamespace.Array<DataEnum>;
    meta?: any;
    success?: boolean;
    errors?: Array<ErrorWrapper>;
}
export namespace ApiNamespace {

    export enum Array&lt;DataEnum&gt; { 
        Foo = <any> 'Foo',
        Bar = <any> 'Bar'
    }
```

#### Swagger-codegen version

2.0.17

##### Command line used for generation

java -jar c:\tools\swagger\swagger-codegen-cli.jar generate -i internalApi.json -l typescript-angular2 -o internalApi

##### Steps to reproduce

1. Create an API (ASP.NET Web API)
2. Create a request that has a payload expecting an array of Enum values
3. Create swagger using above CLI command
4. Validate Auto Generated Swagger

##### Related issues

Did not find any.

##### Suggest a Fix

Honestly I wouldn't even know where to start.

**Comment by matteonovelli** [comment]
I have same issue.

**Comment by matteonovelli** [comment]
I've compiled the latest version and this issue appears to be solved

**Comment by kirpit** [comment]
You guys sure it is resolved? Apparently `array` and `enum` do not play nice with each other for typescript. Here is a very basic spec:

```
swagger: "2.0"
info:
  version: "1.0"
  title: "Hello World API"
paths:
  /hello:
    get:
      parameters:
        - name: myData
          in: body
          schema:
            properties:
              myField:
                type: array
                enum:
                  - foo
                  - bar
                  - baz
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: string
```

Very straightforward, I want `myField` to accept one or more value within the defined enum. Here is what I got for typescript/angular2:

`model/MyData.ts`:
```
export interface MyData {
    myField?: Array<models.ERRORUNKNOWN>;

}
```

Almost the exact same output for typescript/fetch in `api.ts`:
```
export interface MyData {
    "myField"?: Array<ERRORUNKNOWN>;
}
```

My version was the latest stable (`2.2.2` I guess) but http://editor.swagger.io/ creates the same output.

**Comment by kirpit** [comment]
Well after a quick dig in, I found out the original problem was already resolved. However my example above, with the _array of enum choices_ is still broken.

I will create another issue with my use case and refer here but I believe this issue should be already closed.

**Comment by wing328** [comment]
@kirpit thanks for the update. Issue closed.
