### ISSUE TITLE
[JAVASCRIPT] Error generating Javascript code when only some templates are present

### ISSUE THREAD

**Issue by me717** [swagger-api/swagger-codegen#4584]
##### Description

Generating a javascript library does not find original template files if templateDir is set

##### Swagger-codegen version

2.2.1 (using the maven plugin)

##### Command line used for generation

swagger-codegen -l javascript -i swagger.json

Have primarily been using the maven plugin, but the above command produces similar output

##### Steps to reproduce

Run swagger-codegen with the language being 'javascript' and templateDir being set to a folder containing ApiClient.mustache, and no other template files

##### Suggest a Fix

In JavascriptClientCodegen.java, set the embeddedTemplateDir variable

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/4585

Thanks for the contribution from @me717
