### ISSUE TITLE
CodegenProperty.java does not have title field. 

### ISSUE THREAD

**Issue by sreeshas** [swagger-api/swagger-codegen#4588]
##### Description

io.swagger.models.Properties.Property has title field but CodegenProperty Class does not have title field. 

While converting from Property instance to CodegenProperty this information is lost. 

##### Swagger-codegen version

Top of the tree.

##### Suggest a Fix

CodegenProperty should have title field. While generating CodegenProperty from Property title should also be copied.

**Comment by wing328** [comment]
Closed via #4590
