### ISSUE TITLE
Swagger-Codegen-Maven-Plugin currently does not allow for a flag to set documentation generation type.

### ISSUE THREAD

**Issue by kenisteward** [swagger-api/swagger-codegen#4598]
##### Description

In the base swagger-codegen-cli a user is allowed to set for generation of HTML documentation by using the -l flag with the html option.  With the current maven plugin code there is no corresponding flag.  It would be nice to be able to have this for deploying fully documented SDK's.

##### Swagger-codegen version

2.2.1

##### Related issues

I looked for this by searching all issues with "maven plugin" and none seemed to correlate.

##### Suggest a Fix

I saw that the maven plugin has a simple set of flags that represent what would be used to generate the library.  I would suggest having something like <documetation>html|dynamic-html</documentation> to be able to be passed.  I'm not sure if that is the best option as I'm not sure currently if any other docs are generated.

**Comment by kenisteward** [comment]
I think I may have misunderstood what docs were generated.  I now see that it was just the language flag and the docs for the API are generated not docs for the generated SDK.  Is there anything that makes docs for the SDK?

**Comment by wing328** [comment]
@kenisteward depends on which generator you're referring to. Some generators like C#, Java, Ruby, PHP, etc come with auto-generated SDK documentation in markdown format. Other generators like Flash are pending community contribution for the auto-generated SDK doc.
