### ISSUE TITLE
Generate using maven plugin from command line?

### ISSUE THREAD

**Issue by yuniorb** [swagger-api/swagger-codegen#4599]
##### Description

I am trying to use `swagger-codegen-maven-plugin` to generate the client for a `java` project. 
Unfortunately, the generation fails with the following error: `Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.2.0:generate (default-cli) on project employee-cmd: The parameters 'inputSpec', 'language' for goal io.swagger:swagger-codegen-maven-plugin:2.2.0:generate are missing or invalid -> [Help 1]`.

The reason why this happens is because the the maven plugin only exposes the `output` property as an assignable parameter with system properties. Is there a reason why we don't expose all of the parameters this way?

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

```
mvn io.swagger:swagger-codegen-maven-plugin:2.2.1:generate \
-Dlanguage=java \
-DinputSpec=http://petstore.swagger.io/v2/swagger.json \
-Dverbose=true
```

**Comment by fehguy** [comment]
You need to use the `configuration` block like such:

```xml
<plugin>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>${codegen.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>src/main/swagger/swagger.yaml</inputSpec>
                <language>java</language>
                <configOptions>
                    <sourceFolder>src/main/java</sourceFolder>
                </configOptions>
                <output>.</output>
                <modelPackage>org.your.company</modelPackage>
            </configuration>
        </execution>
    </executions>
</plugin>
```
