### ISSUE TITLE
(Spring) SubClass annotations are missing from the base class 

### ISSUE THREAD

**Issue by eamon316** [swagger-api/swagger-codegen#4606]
##### Description

Applying fix for #2449 to **_JavaSpring_** 

> In order for jackson ObjectMapper to deserialize correctly a base class to its subclasses, we need to include annotations defining all expected subclasses in the parent class.
> The codegen currently does not generate those annotations.
> For this example YAML:
> 
> definitions:
>   Base:
>     type: object
>     discriminator: disc
>     properties:
>       disc:
>         type: string
>     required:
>       - disc
>   SubClass:
>     allOf:
>       - $ref: '#/definitions/Base'
>         required:
>           - field
>         properties:
>           field:
>             type: string
> 
> Jackson expects these annotations to be produced, but they are not:
> @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "disc")
> @JsonSubTypes({ @Type(value = SubClass.class, name = "SubClass") })
> public class Base {
> }
> 

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i modules/swagger-codegen/src/test/resources/2_0/allOfTest.yaml \
   -l spring \
   -o /tmp/java_spring

##### Steps to reproduce

Run the above command. 
The following annotations are not included
`@JsonTypeInfo`
`@JsonSubTypes`

##### Related issues

#2449

##### Suggest a Fix

I have submitted a pull request

**Comment by philipptrenz** [comment]
Short question: How's the state? Does it work now?

**Comment by wing328** [comment]
@philipptrenz the fix (https://github.com/swagger-api/swagger-codegen/issues/4607) by @eamon316 has been merged into master. Please pull the latest master to give it a try.

Thanks for the PR from @eamon316
