### ISSUE TITLE
[JavaScript] undefined 'pet' variable in tests

### ISSUE THREAD

**Issue by davidteixeira** [swagger-api/swagger-codegen#4608]
##### Description

When generating a JavaScript client from swagger.yml  file, all tests include the 'pet' variable, which is not defined anywhere in the project. This results in a Reference Error when testing:
`ReferenceError: pet is not defined`

##### Swagger-codegen version

I am using the latest swagger-codegen version.

##### Swagger declaration file content or url
    describe('UsersApi', function() {
    describe('usersGet', function() {
      it('should call usersGet successfully', function(done) {
        //uncomment below and update the code to test usersGet
        instance.usersGet(pet, function(error) {
          if (error) throw error;
        expect().to.be();
        });
        done();
      });
    });

##### Command line used for generation
`npm start -- (./node_modules/mocha/bin/mocha --recursive)`

**Comment by wing328** [comment]
@davidteixeira thanks for reporting the issue. I think you will need to update the following line:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/api_test.mustache#L44

May I know if you've time to contribute the fix?

**Comment by davidteixeira** [comment]
@wing328 thanks for the info. Sure, I'll open a pull request in the next few days.

**Comment by wing328** [comment]
@davidteixeira thanks. Let us (the community) know if you need any help on that.

**Comment by wing328** [comment]
PR merged into master. Thanks for the contribution from @davidteixeira
