### ISSUE TITLE
CLI-option to only generate the sources in src/gen (interface + models)

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4610]
##### Description

Add a cross-language CLI-option to generate only interfaces/models without impl/tests/config whatsoever
(for Jaxrs languages this will in fact mean that the interfaces should be identical finally)

The basic idea is that usually only interfaces/models always need to be generated, all others are usually only needed for the first run of the generator and when using the maven task to generate to the target-directory they should not be generated. 

With #4514 the swagger-codegen-ignore file can now be specified in the maven task, but still it is necessary to fine-tune the generator to exclude the unneeded files from the target directory.
Here it would be nice to have an option so only the sources in the src/gen/java directory get generated (= API + models).

Of course for some languages it is still necessary to fine-tune, but it would be easier to have a basic option to set rather than working with swagger-codegen-ignore.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Related issues

#4514

**Comment by wing328** [comment]
@jfiala currently we can generate `models`, `apis` or supporting files via the following options:
```
# generate only models
java -Dmodels {opts}

# generate only apis
java -Dapis {opts}

# generate only supporting files
java -DsupportingFiles

# generate models and supporting files
java -Dmodels -DsupportingFiles
```
Ref: https://github.com/swagger-api/swagger-codegen#selective-generation

Would that meet your requirement?

**Comment by jfiala** [comment]
@wing328 yes, I think that is sufficient, thanks for the hint!

**Comment by jfiala** [comment]
Closed as the CLI parameters are sufficient.
