### ISSUE TITLE
html output adds backslashes to double quotes

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-codegen#4611]
##### Description

An Open API contains a schema with a property
```
   templateCatalogName:
        type: string
        description: 'The name of the template catalog to use if set or "*CREATE*" if one is to be created.'
```

which Swagger UI renders correctly

templateCatalogName (string, optional): The name of the template catalog to use if set or "CREATE" if one is to be created. ,

but which swagger-codegen with output language `html` renders incorrectly as 

templateCatalogName (optional)
String The name of the template catalog to use if set or \"*CREATE*\" if one is to be created.

Note the extra \ before the embedded double quotes.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Command line used for generation

Done in Groovy via a gradle build:
```
      def name = file.getName()
      def html = name.replace(".json", ".html")
      def dirName = file.getParent()
      String[] args = [ "generate", "-i", file.getPath(), "-l", "html", "-o", dirName ]
      println "Generate HTML for ${name} into output directory ${dirName}/${html} : ${args}"
      try {
        io.swagger.codegen.SwaggerCodegen.main( args )
      } catch (Exception e) {
        String msg = e.getMessage()
        println ">>> Exception ${msg} IGNORED processing ${dirName}/${html}  <<<"
        throw e
      }
```

**Comment by wing328** [comment]
@DavidBiesack I think one way to address the issue is to use `unescapedDescription` instead: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java#L14

May I know if you've time to contribute a fix?

**Comment by DavidBiesack** [comment]
i'll try to find time to post a pull request. Thanks for the code pointer; I would not have known where to start.

**Comment by DavidBiesack** [comment]
I changed `{{description}}` to `{{unescapedDescription}}` in the `htmlDocs` and `htmlDocs2` `*.mustache` files. This is an improvement; the double quotes are not escaped. My sample uses
```
      "description" : "A description string with escaped \"double quotes\".\nThis is a multi-line description.\nTry some <strong> bold </strong> and <it> italic </it> text and an &amp; ampersand, too. and some markup such as **strong** and *italic* text.",
```
The `html` output does **not** show the description with the markdown or HTML markup working. I see

`A description string with escaped "double quotes". This is a multi-line description. Try some <strong> bold </strong> and <it> italic </it> text and an &amp; ampersand, too. and some markup such as **strong** and *italic* text.`

exactly. The HTML source is:

`A description string with escaped &quot;double quotes&quot;
This is a multi-line description.
Try some &lt;strong&gt; bold &lt;/strong&gt; and &lt;it&gt; it &lt;/it&gt; text and an &amp;amp; ampersand, too. and some markup such as **strong** and *italic* text.`

so HTML escaping is being applied, but not Markdown transformation. That is (I believe) issue #1203 and/or #3436 

However, when used in the description string of the API it is *not* HTML escaped.

````
<div class="app-desc">A description string with escaped "double quotes".
This is a multi-line description.
Try some <strong> bold </strong> and <it> italic </it> text and an &amp; ampersand, too. and some markup such as **strong** and *italic* text.</div>
```
The html2 output renders the description as I expected:

A description string with escaped "double quotes". This is a multi-line description. Try some **bold** and _italic_ text and an & ampersand, too. and some markup such as strong and italic text.

I'll submit a PR soon.

**Comment by fehguy** [comment]
Please keep in mind that we have to escape strings or we'll get another nasty XSS vulnerability report.

**Comment by DavidBiesack** [comment]
For XSS, I can understand escaping <script> or other HTML tags. However, escaping a nested quoted string 
```
   "description" : "A description string with escaped \"double quotes\"."
```

so that it renders as

A description string with escaped \"double quotes\".

does not seem related to XSS but rather source code escaping. This is inherited from DefaultCodegen.java
```
    // override with any special text escaping logic
    @SuppressWarnings("static-method")
    public String escapeText(String input) {
        if (input == null) {
            return input;
        }

        // remove \t, \n, \r
        // replace \ with \\
        // replace " with \"
        // outter unescape to retain the original multi-byte characters
        // finally escalate characters avoiding code injection
        return escapeUnsafeCharacters(
                StringEscapeUtils.unescapeJava(
                        StringEscapeUtils.escapeJava(input)
                                .replace("\\/", "/"))
                        .replaceAll("[\\t\\n\\r]"," ")
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\""));
    }
```
and [org.apache.commons.lang3.StringEscapeUtils](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/StringEscapeUtils.html)

**Comment by DavidBiesack** [comment]
It looks like {{unescapedDescription}} is not set for parameters (body, query, path, etc). Running `bin/html2-petstore.sh ` results in diffs such as the following:

```
     <div class="field-items">
       <div class="param">username (required)</div>
 
-      <div class="param-desc"><span class="param-type">Query Parameter</span> &mdash;  </div><div class="param">password (required)</div>
+      <div class="param-desc"><span class="param-type">Query Parameter</span> &mdash; The user name for login </div><div class="param">password (required)</div>
 
-      <div class="param-desc"><span class="param-type">Query Parameter</span> &mdash;  </div>
+      <div class="param-desc"><span class="param-type">Query Parameter</span> &mdash; The password for login in clear text </div>
     </div>  <!-- field-items -->
 
 ```

Note: I've updated `modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java` :+1: 
```
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java
@@ -73,7 +73,7 @@ public class CodegenParameter {
 	 * See http://json-schema.org/latest/json-schema-validation.html#anchor14
 	 */
     public Number multipleOf;
-    
+
     public CodegenParameter copy() {
         CodegenParameter output = new CodegenParameter();
         output.isFile = this.isFile;
@@ -90,6 +90,7 @@ public class CodegenParameter {
         output.collectionFormat = this.collectionFormat;
         output.isCollectionFormatMulti = this.isCollectionFormatMulti;
         output.description = this.description;
+        output.unescapedDescription = this.unescapedDescription;
         output.baseType = this.baseType;
         output.isFormParam = this.isFormParam;
         output.isQueryParam = this.isQueryParam;
```

but I don't see where these CodegenParameter objects are instantiated/populated; there is no CodegenParameter fromModel() method. I'm not sure if I'm looking in the right place.

**Comment by DavidBiesack** [comment]
PR #4641 submitted
