### ISSUE TITLE
[ANDROID/Volley] basePath is set to localhost when "host" missing from Swagger Specification

### ISSUE THREAD

**Issue by gconst02** [swagger-api/swagger-codegen#4612]
##### Description
```
java -jar swagger-codegen-cli-2.2.1.jar generate \
  -i http://example.com/swagger.json \
  -l android --library=volley \
  -o android/volley/ 
```
When executing the above and "host" field is missing from swagger.json the basePath in generated java api files is set to "http://localhost/..." instead of "http://example.com/..."

##### Swagger-codegen version

swagger-codegen-cli-2.2.1.jar

##### Command line used for generation
```
java -jar swagger-codegen-cli-2.2.1.jar generate \
  -i http://example.com/swagger.json \
  -l android --library=volley \
  -o android/volley/ 
```
##### Steps to reproduce

Remove "host" field from swagger.json, place it on a server and execute command above.

**Comment by wing328** [comment]
If you want to customize the base path, I believe you can do so in the Android (volley) API client.

There are other ways to generate Android clients as well: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk
