### ISSUE TITLE
ApiResponse and importModels don't mix

### ISSUE THREAD

**Issue by mbucc** [swagger-api/swagger-codegen#4617]
[JAVA]

##### Description

We have our own ApiResponse object.  In fact, we would like to use importModels config
for all models.

However, even though ApiResponse is listed in importModels config, the code gen for jaxrs-resteasy
insists on importing ModelApiResponse.  I cannot figure out how to tell it "no really, use ours".

I spent a few hours yesterday and could not track it down.  Grepping the source was surprisingly unhelpful, and I wonder if the ModelApiResponse import is some "magic" from swagger-core.

I assume this will be obvious to swagger code gen dev's, if not let me know and I can create a small yaml file to demonstrate.

##### Swagger-codegen version

HEAD

Thanks!

**Comment by mbucc** [comment]
Solution:

Remove reserved word from AbstractJavaCodegen.reservedWords set.

In last line of JavaResteasyServerCodegen constructor, call `removeReservedWord("ApiResponse");` where that routine is defined as

```java
    private void removeReservedWord(final String word) {

        for (Iterator<String> iterator = this.reservedWords.iterator(); iterator.hasNext();) {
            String s =  iterator.next();
            if (s.equals(word.toLowerCase())) {
                iterator.remove();
            }
        }
    }
```

**Comment by wing328** [comment]
@mbucc yes, that's one way to workaround the problem. Thanks for sharing the details of your fix.
