### ISSUE TITLE
Embedded mustache files are used even if TemplateFolder option is specified and contains a different version of the mustache file (in a library folder)

### ISSUE THREAD

**Issue by eblis** [swagger-api/swagger-codegen#4627]
##### Description

I'm trying to generate Spring-Boot server sources from a swagger.json file and I'm specifying my own TemplateFolder which was copied from the original `JavaSpring` template folder and subsequently modified. I've modified the `pom.mustache` file for all 3 Spring libraries (`spring-boot`, `spring-cloud` and `spring-mvc`) and none are taken into consideration while generating for `spring-boot` library.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Command line used for generation

./java -jar swagger-codegen-cli.jar generate -i swagger.json -c spring-config.json -l spring -o samples/server/test -t JavaSpring-Modified

**Comment by eblis** [comment]
This seems to affect all languages that have libraries, not limited to Spring.

**Comment by anselmos** [comment]
@eblis any suggestion how to fix this issue - I'm currently trying to debug and hotfix this but no success so far... 
Related issues : #9521 #9363

**Comment by eblis** [comment]
I haven't been following this for a while, but have you tried my changes that I made ? It worked for me at the time.

**Comment by HugoMario** [comment]
this is fixed for codegen 2.x version, so closing now, but please, let me know if issue it's still present and i work on it asap.
