### ISSUE TITLE
android client generation problem on list of enum

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#4631]
_From @dvalishvili1 on January 23, 2017 12:50_

- swagger-ui version '2.0'
- generated on http://editor.swagger.io/

enum is:
  `public enum CardType
    {
        Unknow = 0,
        Amex = 10,
        Visa = 11,
        MasterCard = 12,
        Maestro = 13
    }`
 property in model:
`public IEnumerable<CardType> PaymentMerchants { get; set; }`

generated android client model is:
`  public enum List&lt;PaymentMerchantsEnum&gt; {
     Unknow,  Amex,  Visa,  MasterCard,  Maestro, 
  };`

`  @SerializedName("PaymentMerchants")
  private List<PaymentMerchantsEnum> paymentMerchants = null;`

_Copied from original issue: swagger-api/swagger-ui#2627_

**Comment by wing328** [comment]
@djvaldez as a workaround, please generate the Java API client instead, which has better support for enum:

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

**Comment by wing328** [comment]
Closing this as there's no update.
