### ISSUE TITLE
std::to_string() is undefined for Android

### ISSUE THREAD

**Issue by martinkbrown** [swagger-api/swagger-codegen#4632]
##### Description

The cpprest resource uses std::to_string() in apiclient-source.mustache and modelbase-source.mustache. This causes builds to fail in Android, even using the latest versions of the NDK. I was able to reproduce the issue with NDK versions r12b, r13b, r14 beta 1. 

##### Swagger-codegen version

2.2

##### Command line used for generation

java -jar swagger-codegen/swagger-codegen-cli.jar generate -l cpprest -i "yaml/latest.yaml" -o src --model-package CPMobileCore.API --api-package CPMobileCore.API

##### Steps to reproduce

Try to build an Android project that includes the code generated by the cpprest component
Alternatively, simply try to use std::to_string() in Android Native code with the following build variables set in your Android Applicaiton.mk

APP_ABI := armeabi-v7a 
APP_STL := gnustl_shared
APP_CPPFLAGS := -fexceptions -frtti -std=c++11 -fpermissive -Wno-unused-variable -g

I know that I can set APP_STL := c++_shared instead, but that introduces a host of other build issues.

##### Suggest a Fix

I will make a pull request for this fix. The solution is to simply use std::stringstream instead of std::to_string() in the mustache templates. E.g.

**Comment by wing328** [comment]
@martinkbrown thanks for reporting the issue and proposing the fix.

We'll review your PR when it's ready.

(I'm sure you aware that Swagger Codegen can also generate Android API client)

**Comment by martinkbrown** [comment]
@wing328 Am I correct in saying that there are no tests to run for cpprest? I haven't used maven much, but if I run `mvn integration-test` from samples/client/petstore/cpprest it says

[ERROR] The goal you specified requires a project to execute but there is no POM
 in this directory (C:\Users\nz962\git\martinkbrown-swagger-codegen\samples\clie
nt\petstore\cpprest). Please verify you invoked Maven from the correct directory

How do we currently test the cpprest component?

**Comment by wing328** [comment]
@martinkbrown yup, there's no test for C++ REST API client at the moment and we would welcome contribution to add integration tests with the Petstore server.
