### ISSUE TITLE
Is it possible to generate model in multiple directories

### ISSUE THREAD

**Issue by mankr1981** [swagger-api/swagger-codegen#4634]
We our model json's in multiple directory structure and wanted to check is there a possibility using code generator I can have my model classes in multiple directory using the name of schema folder.

For e.g. - we provide model package to generator but I want with that package it also add the folder name as  well where the schema resides.
package input - com.schema.model
schema dirs - common, client, shared
when it generates, I want to have my packages like
com.schema.model.common
com.schema.model.client
com.schema.model.shared

before we were using jsonschema2pojo plugin which used to generate as above packages. but could not find if swagger generator supports it.

Any guidelines will be appreciated.
thanks

**Comment by wing328** [comment]
@mankr1981 that's a very special requirement, which may be possible by customizing `modelFileFolder` in the generator, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PhpClientCodegen.java#L323

You may also consider writing a script to move the model files around after the code generation based on your requirement.

**Comment by sreeshas** [comment]
@mankr1981 It is possible but it is not trivial. You have to extend existing Codegen class and introduce package layer. You should also consider how parent and child models are placed once you introduce packaging.
