### ISSUE TITLE
[Python] Proxy support in generated Python module

### ISSUE THREAD

**Issue by krmaxwell** [swagger-api/swagger-codegen#4639]
##### Description

Currently, the generated Python module does not support proxy usage. Is this something in the works? I've cobbled together some modifications to the code but am unsure of the best way to specify the configuration. My current setup uses an environment variable that is automatically detected and used at runtime. Using the requests library would also streamline this greatly.

##### Swagger-codegen version

2.1.0 but this appears to be the case in `master` based on https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/rest.mustache

##### Related issues

#4000 
#4102 

##### Suggest a Fix

Apart from using requests, I have a patch (locally, not yet submitted as a PR) to detect the environment variable `HTTPS_PROXY` at runtime. If it exists, I create an additional property for the `Configuration()` object and call `urllib3.ProxyManager()` instead of `urllib3.PoolManager()` in rest.py. I'd appreciate feedback and constructive criticism on this approach.

**Comment by wing328** [comment]
@krmaxwell thanks for reporting the issue and proposing a fix.

For PHP, we've added the proxy-related properties to the configuration class: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/Configuration.php#L144-L178

For Python, I think we can do something similar.

**Comment by wing328** [comment]
@krmaxwell may I know if you've time to contribute the enhancement? Let me know if you need help with the PR.

**Comment by krmaxwell** [comment]
@wing328 Yes, sorry, I have something cobbled together that I will submit today. I'll need feedback, though, to make sure I'm doing it properly. :smiley_cat:
