### ISSUE TITLE
async-scala codegen places Invoker in wrong directory

### ISSUE THREAD

**Issue by realzeus** [swagger-api/swagger-codegen#4640]
##### Description

async-scala codegen places Invoker in wrong directory.
It's always placed in `io.swagger.client` but contains `package` statement with value provided as `--invoker-package` to `swagger-codegen-cli`.

##### Swagger-codegen version

2.2.1

##### Command line used for generation

```
    "generate",
    "-i", apiDefUri,
    "-l", "async-scala",
    "--api-package", s"$pkg.api",
    "--invoker-package", s"$pkg",
    "--model-package", s"$pkg.model",
    "--group-id", organization.value,
    "--artifact-id", name.value,
    "--artifact-version", version.value,
    "-o", outputDir.getPath,
    "-DapiTests=false", "-DapiDocs=false", "-DmodelTests=false", "-DmodelDocs=false"
```

##### Steps to reproduce

invoke swagger-codegen-cli for language `async-scala` and provide `--invoker-package`.

##### Related issues

None known.

##### Suggest a Fix

Put generated file into correct directory.

**Comment by wing328** [comment]
@realzeus thanks for reporting the issue. May I know if you've time to contribute a fix?

In the future, we plan to combine both `async-scala` and `scala` clients into the same `scala` API client providing both sync and async HTTP calls.

**Comment by wing328** [comment]
@realzeus please try the `scala` generator in 2.3.0, which combines both `scala` and `async-scala` generator into one. Let ue know if you still experience issue.
