### ISSUE TITLE
Add a Retrofit client generator

### ISSUE THREAD

**Issue by futurely** [swagger-api/swagger-codegen#465]
[Retrofit](https://github.com/square/retrofit) is a very popular "type-safe REST client for Android and Java by Square, Inc".

Smartbear developed an example for GitHub API.

https://github.com/olensmar/github-retrofit-client/tree/master/src/main/java/com/olensmar/apis/github

They didn't use template. Instead, the generator is hard coded in Groovy. It should be possible to implement the same functionality with pure templates.

https://github.com/olensmar/soapui-retrofit-plugin/blob/e40722ebbb4c9c97017aa72c04d184e5cd65c4a6/src/main/groovy/com.smartbear.soapui.plugin.retrofit/RetrofitGenerator.groovy

**Comment by webron** [comment]
Sounds like a great idea! Maybe @olensmar would like to contribute it? ;)

**Comment by olensmar** [comment]
awesome - I'll definitely have a look!

just FYI - the plugin referred to above generates Retrofit interfaces for any REST API, i.e. the API doesn't have to be defined with a swagger spec

**Comment by Panthro** [comment]
Any news on that guys?

I use swagger for all my apis, but like retrofit better for the client side.

It would be awesome to be able to generate the client automagically!

**Comment by wing328** [comment]
The latest Java API client supports different HTTP client including Retrofit. To use Retrofit, please create a config.json file as follows:
```
{
  "library": "retrofit"
}
```
and pass config.json via -c in the command line

You can run `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java` for more information on customizing the Java API client.

Would that meet your requirement?

**Comment by fehguy** [comment]
Please reopen if you need help on this.  It's now supported as an option when generating java clients.

**Comment by Panthro** [comment]
I just generated a cli based using the following command:


java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar  generate -i http://localhost:8080/v2/api-docs -l java -o myapi/client/java --library retrofit


It all went well and seemed to work, I explored the code and liked what I saw, with Oauth authentication flow and everything  in place, but when I tried a `mvn package` this happened:


[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/api/BuildrequestresourceApi.java:[10,30] error: cannot find symbol
[ERROR]  package io.swagger.client.model
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/api/BuildrequestresourceApi.java:[52,10] error: cannot find symbol
[ERROR]  interface BuildrequestresourceApi
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/api/BuildrequestresourceApi.java:[65,10] error: cannot find symbol
[ERROR]  interface BuildrequestresourceApi
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/api/UserresourceApi.java:[10,30] error: cannot find symbol
[ERROR]  package io.swagger.client.model
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/api/UserresourceApi.java:[53,10] error: cannot find symbol
[ERROR]  interface UserresourceApi
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/api/UserresourceApi.java:[66,10] error: cannot find symbol
[ERROR]  interface UserresourceApi
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[3,0] error: package com.fasterxml.jackson.annotation does not exist
[ERROR] /Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[4,0] error: package com.fasterxml.jackson.databind does not exist
[ERROR] /Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[5,0] error: package com.fasterxml.jackson.datatype.joda does not exist
[ERROR] /Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[11,10] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[14,17] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[15,48] error: package JsonInclude does not exist
[ERROR] /Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[16,21] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[17,19] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[18,18] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[19,18] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[20,30] error: cannot find symbol
[ERROR]  class JSON
/Users/panthro/swagger/swagger-codegen/myclient/client/java/src/main/java/io/swagger/client/JSON.java:[45,4] error: cannot find symbol
[INFO] 18 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.287 s
[INFO] Finished at: 2015-10-26T10:25:00+01:00
[INFO] Final Memory: 16M/301M
[INFO] ------------------------------------------------------------------------


I don't know if it's anything related to the retrofit or just a common bug.

my git is pointing to the latest commit, which is 6b7ceab

**Comment by wing328** [comment]
@Panthro I could repeat the issue. Let me look into it and get back to you.

**Comment by wing328** [comment]
@Panthro the issue has been addressed by @xhh via #1444 

Please pull the latest master and give it another try.

**Comment by Panthro** [comment]
So, I tried.

[![asciicast](https://asciinema.org/a/7fg7pmo3lvjnyp7fn32y7jk8j.png)](https://asciinema.org/a/7fg7pmo3lvjnyp7fn32y7jk8j)

**Comment by wing328** [comment]
@Panthro do you mind sharing the spec with us (privately via my personal email address or publicly) so that we can use it to reproduce the issue?

**Comment by Panthro** [comment]
shared with you by email.

**Comment by hauthorn** [comment]
Is it possible to (easily) create a new generator for Retrofit 2.0? It would greatly decrease the number of lines in the interface file, as their new structure doesn't require 2 methods for a single call.

I would love to take a stab at it if someone could point me toward a starting point :smile:

**Comment by olegivo** [comment]
> The latest Java API client supports different HTTP client including Retrofit. To use Retrofit, please create a config.json file as follows:
> 
> ```
> {
>   "library": "retrofit"
> }
> ```
> 
> and pass config.json via -c in the command line
> 
> You can run `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java` for more information on customizing the Java API client.
> 
> Would that meet your requirement?

Is it possible to make option to use retrofit with kotlin?

**Comment by olegivo** [comment]
> Please reopen if you need help on this. It's now supported as an option when generating java clients.

Is it possible to make option to use retrofit with kotlin?
