### ISSUE TITLE
[JAVA] [okhttp-gson] Model class not imported in generated client code

### ISSUE THREAD

**Issue by brucegodden** [swagger-api/swagger-codegen#4651]
##### Description

The uploaded [example.zip](https://github.com/swagger-api/swagger-codegen/files/730033/example.zip) contains a simple swagger definition and configuration file that generates a client for the Java okhttp-gson library that fails to compile because an import of the model class used is missing.

The part of the definition that triggers this is the api response being of type List&lt;List&lt;Person&gt;&gt;.

The DefaultApi.java file in the uploaded [example.zip](https://github.com/swagger-api/swagger-codegen/files/730033/example.zip) is the file I generated and you can see that it has no model class imports in it at all. 

##### Swagger-codegen version

v2.2.1

##### Swagger declaration file content or url

Definition: swagger.json in the uploaded [example.zip](https://github.com/swagger-api/swagger-codegen/files/730033/example.zip).

Configuration: java.json in the uploaded [example.zip](https://github.com/swagger-api/swagger-codegen/files/730033/example.zip).

##### Command line used for generation

java -cp /tmp/lib/swagger-codegen-cli-2.2.1.jar io.swagger.codegen.SwaggerCodegen generate -l java -c /tmp/example/java.json -i /tmp/example/swagger.json -o /tmp/build

##### Steps to reproduce

1. Put the json files from the uploaded [example.zip](https://github.com/swagger-api/swagger-codegen/files/730033/example.zip) into `/tmp/example`.
2. Run the generator as above. (You may need a different path to  the cli jar.)
3. Cd into the `/tmp/example/build` directory.
4. Run `./gradlew compileJava`
5. Notice the compile errors due to the missing import for the `Person` class.

##### Related issues

I can't see any similar reports.

##### Suggest a Fix

**Simple**

The vanilla java `api.mustache` template file includes the line

```
import {{modelPackage}}.*;
```

This should be put into all the library specific copies of the `api.mustache` files. I have created [pull request 4652](https://github.com/swagger-api/swagger-codegen/pull/4652) to do just this.

**Complex**

Fix the code that generates the `imports` property to find classes inside more than one level of wrapping by list. (And also, I suspect, set and map.)

**Comment by wing328** [comment]
@brucegodden thanks for reporting the issue and filing a PR for the fix.

I'll review and let you know if I've any question.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5891
