### ISSUE TITLE
[JavaScript] Handling empty array

### ISSUE THREAD

**Issue by khorolets** [swagger-api/swagger-codegen#4653]
Hi! Thank for your great work once again! I wonder if you can help me.

##### Description

I'm using generated javascript client in my project and I've met a bug, I suppose.

If my API returns an empty array client is returning it to me as a string and fails with message:

> TypeError: data.map is not a function

It occurs in `src/ApiClient.js:exports.convertToType()` 

```javascript
} else if (Array.isArray(type)) {
          // for array type like: ['String']
          var itemType = type[0];

          return data.map(function(item) {
            return exports.convertToType(item, itemType);
          });
        } else if (typeof type === 'object') {
```

I suppose this data is handled somewhere in `exports.prototype.deserialize`

Because of 
```javascript
if (data == null || !Object.keys(data).length) {
      // SuperAgent does not always produce a body; use the unparsed response as a fallback
      data = response.text;
    }
```

Can you help me?

**Comment by wing328** [comment]
@khorolets is it correct to say that `Object.keys(data).length)` failed to return `0` somehow and that's why the following logic failed to work with empty array (which should have 0 size/length)?

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/ApiClient.js#L323-L326

**Comment by khorolets** [comment]
@wing328 yes. Do you need me to provide anything else to help you understand why this is happening?

**Comment by frol** [comment]
I am not sure what was the case for adding `Object.keys(data).length` check, but since

```javascript
Object.keys([]).length == 0
Object.keys({}).length == 0
Object.keys('').length == 0
Object.keys(0).length == 0
Object.keys(1).length == 0
```

It should be addressed with a more specific check or even get fixed in the `superuser` library.

**Comment by wing328** [comment]
@khorolets I read this: http://stackoverflow.com/a/6700/677735, which suggests the approach is correct.

Are you using an old browser somehow?

**Comment by frol** [comment]
@wing328 `Object.keys(data).length` is fine by itself, but it catches too many cases as you can see in my previous comment, while I think, it should only catch `{}` (empty object) or `''` (empty string).

**Comment by frol** [comment]
This behavior was introduced in #4219.

@jordanyaker Could you please comment on this issue as it was your PR adding this `!Object.keys(data).length` check. Should be there added `(typeof data === 'object' && typeof data.length === 'undefined' && !Object.keys(data).length)` to ensure that we catch only empty **objects**?

**Comment by wing328** [comment]
@frol just saw your detailed comments and agree with a more specific check to handle the issue.
