### ISSUE TITLE
If a type's field is an array or a map, format of  array or map's type is not copied into encapsulating type. 

### ISSUE THREAD

**Issue by sreeshas** [swagger-api/swagger-codegen#4660]
##### Description

Consider model A which has field  B, which is an array of type C.  if C has a data format ("format") it is not copied into B's format.  format information is lost. 

 

##### Swagger-codegen version
Latest.

##### Suggest a Fix
format information should be copied.

**Comment by sreeshas** [comment]
PR #4661 has the fix for this issue.

**Comment by sreeshas** [comment]
Here is an example. Consider json object User.  It has property called events which is an array of type string whose format is "date".   In DefaultCodegen.java  fromProperty method ignores dataFormat from a property if it is an array. 

    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "username": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "userStatus": {
          "type": "integer",
          "format": "int32",
          "description": "User Status"
        },
        "events":{
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          }
        }
      }

**Comment by wing328** [comment]
PR merged.
