### ISSUE TITLE
[JAVA/] jaxrs/jersey2 java8-date codegeneration gives jersey1 imports

### ISSUE THREAD

**Issue by veinSmart** [swagger-api/swagger-codegen#4662]
##### Description

We are trying to generate jaxrs/jersey resoursces that take in OffsetDateTime values as parameters. But the generated OffsetDateTimeProvider class holds imports from com.sun.jersey packages that are from jersey1.

This causes some version clashes for us since we use the jersey2 classes from org.glassfish packages.

Codegen version 2.2.1, we are using the maven-plugin, with this xml:

```
<plugin>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-codegen-maven-plugin</artifactId>
  <version>2.2.1</version>
     <executions>
       <execution>
         <goals>
           <goal>generate</goal>
          </goals>
          <configuration>
             <inputSpec>${basedir}/src/main/resources/swagger/swagger.yaml</inputSpec>
                  <language>jaxrs</language>
                  <library>jersey1</library>
                  <configOptions>
                      <sourceFolder>src/gen/main/java</sourceFolder>
                      <dateLibrary>java8</dateLibrary>
                   </configOptions>
                </configuration>
              </execution>
        </executions>
   </plugin>
```

A suggestion would be to make a special jersey2 version of the *DateProvider classes that use the org.glassfish packages instead.

**Comment by wing328** [comment]
@veinSmart I would suggest you to pull the latest master to give it a try as there's been a lot of enhancements to the latest master to 2.2.1 release.

(we hope to release 2.2.2 in Feb 2017)

**Comment by veinSmart** [comment]
@wing328 Yeah, I thought of that and (correct me if I have understood this wrongly, but) I actually cloned the repo to my machine to look at the code and saw that the:

src/main/resources/JavaJaxRS/OffsetDateTimeProvider.mustache

file seems the be used for both jersey1 and jersey2 generation and it has the imports to the com.sun.jersey files here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/OffsetDateTimeProvider.mustache#L3-L5

**Comment by mamghari** [comment]
Hi Everyone,
The package "com.sun.jersey" is only for JERSEY 1!

We should manage that for Jersey 2. They are not compatible.
Cheers.

**Comment by wing328** [comment]
@veinSmart @mamghari would you have time to contribute the fix? If yes, I can show you some good starting points.

**Comment by veinSmart** [comment]
@wing328 Yeah, I should be able to find time on friday if that is ok for you?

**Comment by mamghari** [comment]
@veinSmart @wing328 I fixed the issue in the pull request (a part of ) :
https://github.com/swagger-api/swagger-codegen/pull/5002

**Comment by veinSmart** [comment]
@mamghari As far as I understand only thing you have fixed is that Java8 Date time classes are generated only if the library version is jersey1. But then what I need is to make it work with jersey2. I am working on the fix to make it work with jersey2. Please let me know if I misunderstood and if you have already fixed it to make it work with jersey2. I will stop working on the fix if so.

**Comment by veinSmart** [comment]
@wing328 @mamghari I have managed to make it work for java8 Date time classes for jersey2. I'll create a pr tomorrow.
