### ISSUE TITLE
[csharp] generated enums attempting to assign strings

### ISSUE THREAD

**Issue by marekr** [swagger-api/swagger-codegen#4670]
##### Description

Using the EVE Online ESI Swagger definition, the generated csharp client code  is generated without error by the code gen however it cannot be compiled.  Observing the output, the generator correctly created an enum but then proceeded to try assigning strings to it which is invalid.

The problem can be seen here where Color is defined as ColorEnum

        /// <summary>
        /// Hexadecimal string representing label color, in RGB format 
        /// </summary>
        /// <value>Hexadecimal string representing label color, in RGB format </value>
        [DataMember(Name="color", EmitDefaultValue=false)]
        public ColorEnum? Color { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostCharactersCharacterIdMailLabelsLabel" /> class.
        /// </summary>
        /// <param name="Color">Hexadecimal string representing label color, in RGB format  (default to &quot;#ffffff&quot;).</param>
        /// <param name="Name">name string (required).</param>
        public PostCharactersCharacterIdMailLabelsLabel(ColorEnum? Color = null, string Name = null)
        {
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for PostCharactersCharacterIdMailLabelsLabel and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // use default value if no "Color" provided
            if (Color == null)
            {
                this.Color = "#ffffff";
            }
            else
            {
                this.Color = Color;
            }
        }

but at the end, it attempts to set the class level Color definition to a string "default"

The generated ColorEnum appears like this:

        /// <summary>
        /// Hexadecimal string representing label color, in RGB format 
        /// </summary>
        /// <value>Hexadecimal string representing label color, in RGB format </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ColorEnum
        {
            
            /// <summary>
            /// Enum Ffffff for "#ffffff"
            /// </summary>
            [EnumMember(Value = "#ffffff")]
            Ffffff,
            
            /// <summary>
            /// Enum Ffff01 for "#ffff01"
            /// </summary>
            [EnumMember(Value = "#ffff01")]
            Ffff01,
            
            /// <summary>
            /// Enum Ff6600 for "#ff6600"
            /// </summary>
            [EnumMember(Value = "#ff6600")]
            Ff6600,
        }

(Enum shortened for sanity)

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url
The link to the swagger file is here

https://esi.tech.ccp.is/latest/#

##### Command line used for generation
java -jar swagger-codegen-cli-2.2.1.jar generate ^
   -i esi.json ^
   -c esi-codegen.json ^
   -l csharp ^
   -o ./esi-lib

esi-codegen.json

{
	"packageName": "ESI",
	"packageGuid": "1b95dd80-dd8a-4e94-80db-2db990e00824"
}

##### Steps to reproduce

Generate code using above command line, attempt compile in visual studio

**Comment by marekr** [comment]
It appears the solution is to make the toDefaultValue section in AbstractCSharpCodegen.java match that of the javacodegen.

Namely

diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
index 10ccff3..cdeeba3 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java
@@ -484,7 +484,13 @@ public abstract class AbstractCSharpCodegen extends DefaultCodegen implements Co
         if (p instanceof StringProperty) {
             StringProperty dp = (StringProperty) p;
             if (dp.getDefault() != null) {
-                return "\"" + dp.getDefault() + "\"";
+                String _default = dp.getDefault();
+                if (dp.getEnum() == null) {
+					return "\"" + _default + "\"";
+                } else {
+                    // convert to enum var name later in postProcessModels
+                    return _default;
+                }
             }
         } else if (p instanceof BooleanProperty) {
             BooleanProperty dp = (BooleanProperty) p;

**Comment by jimschubert** [comment]
@marekr I opened a PR with your proposed change.

If you'd like to test it out locally (assuming you have maven and JDK locally):

```
git clone git@github.com:jimschubert/swagger-codegen.git
cd swagger-codegen
git checkout csharp/4670
mvn clean package -Dmaven.test.skip=true -DskipTests
java -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar …
```

where … is the rest of your options with relevant paths.

This will build 2.2.2-SNAPSHOT for you. There may be differences between the code generated here versus 2.2.1, probably most notable a nuspec is generated.

**Comment by wing328** [comment]
PR merged into master. Please pull the latest master to give it a try.

**Comment by jritmeijer-muhimbi** [comment]
We are running into this problem on the live http://editor.swagger.io site. When will that site be updated with the latest code generators?

**Comment by wing328** [comment]
@jritmeijer-muhimbi 2.2.2 will be released this month and then generator.swagger.io (used by editor.swagger.io) will be updated accordingly.
