### ISSUE TITLE
[JAVA] Okhttp leaks connections if response type is not defined or ill-defined

### ISSUE THREAD

**Issue by yaronlev171** [swagger-api/swagger-codegen#4671]
##### Swagger-codegen version

2.1.5, 2.2.1, master

##### Swagger declaration file content or url

```json
    "paths": {
        "/api/somecall": {
            "get": {
                "operationId": "getSomeAnswer",
                "responses": {
                    "200": {
                        "$ref": "#/responses/NonExistingResponseType"
                    }
                }
            }
        }
```
##### Command line used for generation

generate -i swagger.json -l java -o .

##### Steps to reproduce

Create the DefaultApi object.
Use the DefaultApi to call the /api/somecall
Do not read the response explicitly - assume the call succeeded (it did).
Wait 5 minutes.
Okhttp issues a warning about a connection being leaked.

Notice that the code goes through the path:
```code
      if (returnType == null || response.code() == 204) {
        // returning null if the returnType is not defined,
        // or the status code is 204 (No Content)
        return null;
```
The response body is never closed and the connection is leaked. 
According to Okhttp docs the response body needs to be closed ALWAYS either by calling string(), bytes() or close() - even on failures and exceptions. Otherwise the connection is leaked.

##### Suggest a Fix
Something on the line of this (so far no connections leak):

```code
  public <T> T handleResponse(Response response, Type returnType) throws ApiException {
        boolean returnnull = false;
        String respBody = null;
        boolean success = false;
        try {
          if (response.isSuccessful()) {
            if (returnType != null && response.code() != 204) {
              T t = deserialize(response, returnType);
              // deserialize closes the body correctly, so do not do it again
              success = true;
              return t;
            }
            else {
              returnnull = true;        // but close the body first!!!
            }
          }
        }
        finally {
          // ensures response body is closed, unless already closed by deserialize()
          if (response.body() != null && !success) {
                try {
                  respBody = response.body().string();
                } catch (IOException e) {
                  throw new ApiException(response.message(), e, response.code(), response.headers().toMultimap());
                }
          }
        }
        if (returnnull) {
          // response was successful, but no Type to use, or no content - nothing to return
          return null;
        }
        throw new ApiException(response.message(), response.code(), response.headers().toMultimap(), respBody);
  }
```

**Comment by wing328** [comment]
>                         "$ref": "#/responses/NonExistingResponseType"

Is it correct to say that the issue can also be fixed by defining a proper (correct) response?

**Comment by yaronlev171** [comment]
Not really. You can enforce *your* api to be more strict by erroring in codegen if you wish, or even throwing an ApiException on null type. But allowing null types and then leaking because of it is not ok.This is quite a serious bug in your integration with okhttp. And in any case, for correctly defined 204's it's still going to leak.
-------- Original message --------From: wing328 <notifications@github.com> Date: 1/28/17  20:58  (GMT-08:00) To: swagger-api/swagger-codegen <swagger-codegen@noreply.github.com> Cc: yaronlev171 <yaronlev171@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [swagger-api/swagger-codegen] [JAVA] Okhttp leaks connections if
  response type is not defined or ill-defined (#4671) 

                    "$ref": "#/responses/NonExistingResponseType"


Is it correct to say that the issue can also be fixed by defining a proper (correct) response?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/swagger-api/swagger-codegen","title":"swagger-api/swagger-codegen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/swagger-api/swagger-codegen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wing328 in #4671: \u003e                         \"$ref\": \"#/responses/NonExistingResponseType\"\r\n\r\nIs it correct to say that the issue can also be fixed by defining a proper (correct) response?"}],"action":{"name":"View Issue","url":"https://github.com/swagger-api/swagger-codegen/issues/4671#issuecomment-275894047"}}}

**Comment by wing328** [comment]
@yaronlev171 thanks for sharing more with me. I agree with you that the leaking should be fixed.

May I know if you've time to contribute the fix by filing a PR?

A good starting point is https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L1020

**Comment by candlejack297** [comment]
@yaronlev171 there's no reason to close only if not closed. Calling close multiple times is fine (and explicitly supported by OkHttp).

**Comment by yaronlev171** [comment]
If I remember correctly I actually tried this and it failed saying that the body was already closed.

Better be safe than rely on okhttp’s internal handling of such cases.

**Comment by wing328** [comment]
> Better be safe than rely on okhttp’s internal handling of such cases.

@yaronlev171 I totally agree with you on that.

**Comment by yaronlev171** [comment]
Opened PR: 
https://github.com/swagger-api/swagger-codegen/pull/4772

**Comment by wing328** [comment]
#4997 has been merged into master. Please pull the latest master to give it a try.
