### ISSUE TITLE
how to generate spring mvc server stub with swagger 2.2.1

### ISSUE THREAD

**Issue by aparnarus** [swagger-api/swagger-codegen#4679]
##### Description

we just upgraded swagger version to 2.2.1 from 2.1.6. We had generated server side code using spring MVC earlier. i cant seem to find an option to do that with 2.2.1, its picking up sprint boot. how can i still generate spring MVC code.

##### Swagger-codegen version

2.2.1

##### Command line used for generation

mvn io.swagger:swagger-codegen-maven-plugin:generate

##### Steps to reproduce

switch the version from 2.1.6  to 2.2.1 and then run maven goal specified above.

**Comment by wing328** [comment]
@aparnarus yes, you can specify the `library` option:
```
	library
	    library template (sub-template) to use (Default: spring-boot)
	        spring-boot - Spring-boot Server application using the SpringFox integration.
	        spring-mvc - Spring-MVC Server application using the SpringFox integration.
	        spring-cloud - Spring-Cloud-Feign client with Spring-Boot auto-configured settings.
```
Ref: `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l spring`

**Comment by wing328** [comment]
@aparnarus let us know if you've further question.

**Comment by aparnarus** [comment]
Thanks that worked.!

**Comment by wing328** [comment]
No problem. How's the upgrade so far? Did you encounter any other issues?

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
