### ISSUE TITLE
[Python] Wrong file/import naming for server

### ISSUE THREAD

**Issue by philipptrenz** [swagger-api/swagger-codegen#4684]
##### Description

Generated Python server code from Swagger Editor results at start in issue
 ```
 File "~/python-flask-server/swagger_server/controllers/default_controller.py", line 4, in <module>
    from swagger_server.models.inline_response200 import InlineResponse200
ImportError: No module named 'swagger_server.models.inline_response200'
```
The files inside `swagger_server/models/` are named e.g. `inline_response_200.py`

##### Swagger-codegen version

Version of http://editor.swagger.io : Version 2.10.3
(Couldn't find explicit swagger-codegen version)

##### Command line used for generation

By dropdown at editor.swagger.io, cmd to start server:

pip3 install -r requirements.txt
python3 -m swagger_server

**Comment by wing328** [comment]
@philipptrenz can you share the spec (e.g. via gist.github.com) so that we can try to repeat the issue?

**Comment by philipptrenz** [comment]
Sorry, was busy.

<script src="https://gist.github.com/philipptrenz/4b07ce3eddd4faf190f3d8436406332f.js"></script>

**Comment by wing328** [comment]
I could repeat the issue but got a different error message:
```
debug|⇒ python3 -m swagger_server                                                     

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/python-flask/debug/swagger_server/__main__.py", line 4, in <module>
    from .encoder import JSONEncoder
  File "/private/var/tmp/python-flask/debug/swagger_server/encoder.py", line 3, in <module>
    from swagger_server.models.base_model_ import Model
  File "/private/var/tmp/python-flask/debug/swagger_server/models/__init__.py", line 5, in <module>
    from .device import Device
  File "/private/var/tmp/python-flask/debug/swagger_server/models/device.py", line 4, in <module>
    from swagger_server.models.function import Function
  File "/private/var/tmp/python-flask/debug/swagger_server/models/function.py", line 4, in <module>
    from .base_model_ import Model
  File "/private/var/tmp/python-flask/debug/swagger_server/models/base_model_.py", line 2, in <module>
    from typing import TypeVar, Type
ImportError: No module named 'typing'
```
Another thing I would suggest you to try is to generate the Python API client and review the auto-generated models to see if those look good to you.

**Comment by philipptrenz** [comment]
I haven't tested the python client, but naming of the model class files are okay.

**Comment by wing328** [comment]
If the models in the Python API client are fine, we can reuse the model mustache template in Python Flask generator.

**Comment by cgiraldo** [comment]
I have this workaround to fix the server once it was started for the first time and generated an errroneous default_controller.py file.

Modify all the model import lines of the file python-flask-server/swagger_server/controllers/default_controller.py as the following example:

original line:
`from swagger_server.models.inline_response200 import InlineResponse200`
modified line:
`from swagger_server.models import InlineResponse200`

**Comment by wing328** [comment]
@cgiraldo @philipptrenz can you please try the latest master? I found that the same function is called in both import statement and model file naming:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FlaskConnexionCodegen.java#L650

**Comment by cgiraldo** [comment]
I hit the problem when using swagger-editor last docker image:
`docker pull swaggerapi/swagger-editor
docker run -d -p 80:8080 swaggerapi/swagger-editor`

**Comment by wing328** [comment]
editor.swagger.io leverages https://generator.swagger.io to generate code. From what I know generator.swagger.io is not using the latest master of Swagger Codegen.

**Comment by wing328** [comment]
I did a test with latest master, python2 and here is what I got in a test model:
```
from swagger_server.models.inline_response200 import InlineResponse200
```
which is consistent with the model file naming:
```
(venv)import3|⇒ ls swagger_server/models/inline_response200.py 
swagger_server/models/inline_response200.py
```

**Comment by wing328** [comment]
2.2.2 has been released. Please give that a try and let us know if you still experience issue.

**Comment by wing328** [comment]
The issue should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4958

Please pull the latest master to give it a try.
