### ISSUE TITLE
[JAVA] Builder methods causing Freemarker issues

### ISSUE THREAD

**Issue by smmcneill** [swagger-api/swagger-codegen#4687]
##### Description

Swagger generated model classes include builder methods which clash when executing Freemarker transformations.  An example:

```
// Swagger generated model
public class Instance{
    @ApiModelProperty(example = "hellworld", value = "Name for the instance.")
    public String getName() {
      return name;
    }

    public Instance name(String name) {
      this.name = name;
      return this;
    }
}
```

```
# Freemarker template
{
  "resource": {
    "displayName": "${name}",
    ...
  }
}
```

When I try processing the Swagger model instance using the Freemarker template, Freemarker is clearly trying to use the name(String): Instance method rather than the getName method.  For this reason, the Freemarker processing fails.  If the builder methods included a prefix (eg. with) then Freemarker wouldn't fail.  If I could disable the generation of builder methods, that would be great too.  I've validated that both 1) manually removing the builder methods, and 2) adding a prefix to builder method names result in happy path.

##### Swagger-codegen version

2.2.1
##### Command line used for generation

java -jar /opt/swagger-codegen-cli.jar generate -i "${API_FILE}" \
	--lang spring \
	--group-id xx \
	--artifact-id api \
	--api-package xxx \
	--model-package xxx \
	-c config/swagger_config.json

{
	"basePackage": "xx",
	"configPackage": "xx",
	"hideGenerationTimestamp": true,
	"dateLibrary": "java8"
}

**Comment by wing328** [comment]
@smmcneill please take a look at the answer in http://stackoverflow.com/a/39754680/677735 to see if it addresses the problem for you.
