### ISSUE TITLE
[ANDROID/Volley] build.gradle dependency error: No service of type Factory available in ProjectScopeServices 

### ISSUE THREAD

**Issue by gconst02** [swagger-api/swagger-codegen#4689]
##### Description

After generating client for volley:
```
java -jar swagger-codegen-cli-2.2.1.jar generate \
  -i http://example.com/swagger.json \
  -l android --library=volley \
  -o android/volley/ 
```

The project fails to sync (I am using Android Studio), with the following output:
```
Error:(22, 0) No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.
```

##### Swagger-codegen version

swagger-codegen-cli-2.2.1.jar

##### Command line used for generation
```
java -jar swagger-codegen-cli-2.2.1.jar generate \
  -i http://example.com/swagger.json \
  -l android --library=volley \
  -o android/volley/ 
```
##### Steps to reproduce

Use exported project as library and try to sync.

##### Suggest a Fix

I fixed the issue by changing the dependency version for **android-maven-gradle-plugin** to 1.5 (was 1.3) in generated **build.gradle**:
```
dependencies {
        classpath 'com.android.tools.build:gradle:1.5.+'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
}
```

**Comment by wing328** [comment]
@gconst02 thanks for reporting the issue. We'll upgrade the dependency to newer version after the 2.2.2 release (which will due soon in Feb 2017)

Btw, are you following the installation procedure in README.md? are you using the gradle wrapper for installation?

**Comment by gconst02** [comment]
I am using gradle wrapper within Android Studio. I have followed this: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#android and this https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/android/volley

**Comment by wing328** [comment]
@gconst02 thanks for sharing more with me.

A workaround is to customize the template: https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache#L13 and then use the `-t` option with the customized templates.
