### ISSUE TITLE
[aspnetcore] packageName or sourceFolder specified in the config do not change the project folder name

### ISSUE THREAD

**Issue by abkordata** [swagger-api/swagger-codegen#4690]
After generating aspnetcore server code the packageName provided in the configuration isn't reflected on the source project folder name, instead the folder name uses the default name: "IO.Swagger".
Same thing happens when defining the sourceFolder in the configuration json file.
The structure should be:
Api/src/Title.Case/ 
Instead it defaults to
Api/src/IO.Swagger/

with config.json being:
```json
{
"packageName": "Title.Case"
}
```

Note: All the templates seem to update correctly to the specified packageName.

##### Swagger-codegen version
using swagger-codegen 2.2.1 as well as the master branch and 2.3 branch 

##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -i swagger.json -l aspnetcore -c config.json -o Api`

**Comment by wing328** [comment]
@abkordata thanks for reporting the issue. 

Have you tried passing the `sourceFolder` option to setup a proper source folder based on package name?
```
	sourceFolder
	    source folder for generated code (Default: src/IO.Swagger)
```
Ref: `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l aspnetcore`

**Comment by abkordata** [comment]
Yes I have tried with the sourceFolder option like so:
```json
{
"sourceFolder": "src/Tilte.Case"
}
```
And I also tried having both packageName and sourceFolder like so:

```json
{
"packageName": "Title.Case"
"sourceFolder": "src/Tilte.Case"
}
```
None of these changed the folder name properly. The folder name still defaults to IO.Swagger

**Comment by wing328** [comment]
@abkordata the following lines show that the `sourceFolder` is used for API and model folders:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java#L118-L126

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AspNetCoreServerCodegen.java#L48-L50 obtains the setting and put it into `sourceFolder`

I can't really tell what's causing the issue at the moment.

cc @jimschubert

**Comment by jimschubert** [comment]
Yeah that's weird. I've generated with different source folder to evaluate an older PR. Maybe something has changed in DefaultCodegen.

This generator should probably error if sourceFolder doesn't start with src/ (ASP net core constraint), or fix the input with a warning message.

I'll try to look into this tonight.

**Comment by jimschubert** [comment]
@abkordata @wing328 I opened #4699 to resolve the issue with packageName. However, in testing I've found that changing `src` to anything else basically breaks the ASP.NET Core expected structure. I wasn't sure of the best approach here, so I'd like some feedback. See PR.

**Comment by wing328** [comment]
@jimschubert thanks for the quick fix 👍 

I think throwing a warning is a good start. If there are developers changing `src` to something else, we need to talk to them to find out the reason behind and then come up with a better approach if possible.

**Comment by wing328** [comment]
@abkordata PR merged into master. Please pull the latest master to give it a try.
