### ISSUE TITLE
spring json config file is not working for me...

### ISSUE THREAD

**Issue by donahchoo** [swagger-api/swagger-codegen#4697]
I'm trying to use a json config file to generate spring code.  I want to change my base package but I keep getting io.swagger.

 I have this command:
    java -Dapis -Dmodels -XX:MaxPermSize=256M -Xmx1024M -DloggerPath=conf/log4j.properties \
    -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
    -t modules/swagger-codegen/src/main/resources/JavaSpring \
    -i swagger.json \
    -l spring -o spring-boot -c config.json -DhideGenerationTimestamp=true

My config.json file has:
```
{ "configuration": 
  {
    "basePackage": "com.foo.bar"
  }
}
```

I've tried changing configuration to configOptions and without that parent object, but I can't get my classes generated in the correct package.

Suggestions?

**Comment by donahchoo** [comment]
Interestingly, this puts my models and api files in the right places

```
{ 
   "modelPackage": "com.foo.bar.model",
  "apiPackage": "com.foo.bar.api",
}
```

**Comment by wing328** [comment]
@donahchoo yes, I believe you will need to set the `apiPackage` and `modelPackage`

For your use case, did you mean you want to set `basePackage` to "com.foo.bar" and then both `apiPackage` and `modelPackage` will be set accordingly?

**Comment by adhamhf** [comment]
@wing328 yes, that's what I expected to happen.  not sure what basePackage is for...

**Comment by wing328** [comment]
Doing a search for `basePacakge` will show where it's used in the mustache template: https://github.com/swagger-api/swagger-codegen/search?utf8=%E2%9C%93&q=basePackage
