### ISSUE TITLE
[Typescript-Angular2] When #isKeyInQuery but no #hasFormParams, generated API breaks.

### ISSUE THREAD

**Issue by creat-or** [swagger-api/swagger-codegen#4703]
##### Description

When generating an endpoint without a `formParam`, but `isKeyInQuery` the template generates
```
if (this.configuration.apiKey) {
    formParams.set('{{keyParamName}}', this.configuration.apiKey);
}
```
But formParams never gets initialized before or used afterwards, because apparently `hasFormParams` is false.
```
{{#hasFormParams}}
        let formParams = new URLSearchParams();
{{/hasFormParams}}
```

```
{{#hasFormParams}}
            body: formParams.toString(),
{{/hasFormParams}}
```
##### Swagger-codegen version

2.2.1

##### Command line used for generation

used typescript-angular2 from http://editor.swagger.io/#/

##### File

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache

**Comment by wing328** [comment]
@creat-or Thanks for reporting the issue. The API key should not be put in the form parameter. It should be stored in the query parameter instead so https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L140 should be changed as follows:
```
            queryParameters.set('{{keyParamName}}', this.configuration.apiKey);
```

May I know if you've time to contribute the fix?

**Comment by creat-or** [comment]
Thanks! OK, I will look into it! :)
