### ISSUE TITLE
Configure Spring Boot Server Controllers generation

### ISSUE THREAD

**Issue by rmharris157** [swagger-api/swagger-codegen#4706]
Sorry to bother you; but I have three questions.

##### Description

- Is there a way to explicitly say which .java file in which to write a particular autogenerated controller? (for instance, if I want to put some of the /foo controllers in one class and some in a different class to group them for clarity.)

- Is there a way to configure the spring-boot codegen to not generate service controller stubs, but to still have it generate the API stubs?

- And/or is there a way to configure it to render the stub controllers into a different package namespace than the API's?

**Comment by wing328** [comment]
1. You may try putting the operations in different `tags` ([example](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L126)) to see if that meets your requirement.

2. You can leverage .swagger-codegen-ignore to skip files you don't want to generate. https://github.com/swagger-api/swagger-codegen#ignore-file-format.

3. Please run `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l spring` to explore different options available to customize the Spring generator.
