### ISSUE TITLE
Repackage as io.swagger

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#472]
It may be late in the process but it may make sense to repackage into the io.swagger group.

@webron what do you think?

**Comment by olensmar** [comment]
the longer you wait - the harder it will be - I suggest you do it now :-)

**Comment by webron** [comment]
We can do that now, but we have to release it as 2.2 - it can't carry the same version number.

**Comment by fehguy** [comment]
OK after conferring with a few folks, since we've pushed to maven central, we need to do a real version change.  So @olensmar pain comes another day...

**Comment by olensmar** [comment]
ok - well, thanks for looking into it for now!

**Comment by webron** [comment]
Done. Released.
