### ISSUE TITLE
[Jaxrs-spec] jaxrs-spec-petstore-server.sh is using the wrong templates of Jersey

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4720]
##### Description

jaxrs-spec-petstore-server.sh:

Current:
ags="$@ generate -t modules/swagger-codegen/src/main/resources/JavaJaxRS -i modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -l jaxrs-spec -o samples/server/petstore/jaxrs-spec

The templates of Jaxrs-Jersey are used due to the option "-t modules/swagger-codegen/src/main/resources/JavaJaxRS" (correct would be the directory modules/swagger-codegen/src/main/resources/JavaJaxRs/spec)

The template option should not be used, to use the defined templates of jaxrs-spec.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Suggest a Fix

Remove the -t option.

**Comment by wing328** [comment]
Fixed via #4722
