### ISSUE TITLE
Package names in the finch generator should not contain petstore

### ISSUE THREAD

**Issue by clasnake** [swagger-api/swagger-codegen#4727]
I found that in FinchServerCodegen, the packageName and invokerPackage are set to "io.swagger.petstore...".
petstore is just the sample and I guess the package names here should not contain "petstore".

**Comment by clasnake** [comment]
@wing328 @jimschubert Just had a quick look at the finch generator and found the above issue.

**Comment by clasnake** [comment]
@wing328 I guess even the default should not contain petstore. Can be "io.swagger"

**Comment by wing328** [comment]
@clasnake you're definitely right. What default would you suggest?

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FinchServerCodegen.java#L18

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FinchServerCodegen.java#L23

**Comment by clasnake** [comment]
@wing328 How about "io.swagger"?

**Comment by wing328** [comment]
@clasnake sounds better to me as it doesn't contain "petstore" 😄 

Please feel free to submit the PR with updated petstore sample for Finch.

**Comment by wing328** [comment]
Closed via #4755
