### ISSUE TITLE
Add support for BeanValidation @Valid annotation on nested attributes

### ISSUE THREAD

**Issue by jmiddleton** [swagger-api/swagger-codegen#4738]
##### Description

When useBeanValidation flag is true, it does not add @Valid annotation to attributes of type object. For instance, I have the class JoinDetails which has a field of type MemberProfile. When I validate joinDetails instance, the validator does not validate memberProfile because there is no @Valid annotation on it. It would be better if swagger-codegen can support this use cases either using extraAnnotation (i.e. x-extraAnnotation: "@Valid") in swagger config or automatically added during code generation.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

    ```yaml
    JoinDetails:
    type: object
    required:
      - memberProfile
    properties:
      memberProfile:
        $ref: '#/definitions/MemberProfile'
     MemberProfile:
    type: object
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
        maxLength: 50
      lastName:
        type: string
        maxLength: 50
    ```

##### Command line used for generation

I'm using maven:

<groupId>io.swagger</groupId>
<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>2.2.2-SNAPSHOT</version>

##### Suggest a Fix

Add support via x- extension or automatically detect complex object or entities from the model.

**Comment by wing328** [comment]
@jmiddleton thanks for the suggestion. For this particular case, I think `@Valid` should be added automatically.

cc @jfiala

**Comment by jfiala** [comment]
For spring we already have a PR: https://github.com/swagger-api/swagger-codegen/pull/4850/files

**Comment by jfiala** [comment]
Overview of all the languages to be updated:

- [ ] jaxrs-spec
- [ ] jaxrs (Jersey2 + library jersey1)
- [ ] jaxrs-resteasy
- [x] jaxrs-cxf - PR #4738
- [ ] jaxrs-cxf-cdi
- [ ] spring (default library spring-boot + library spring-mvc, spring-cloud)

**Comment by michaelpaesold** [comment]
This also applies to `jaxrs` (Jersey2). I could provide a patch.

**Comment by olivierpaquet** [comment]
Is someone already working on the same issue for jaxrs-cxf?

**Comment by jfiala** [comment]
@olivierpaquet  I did the PR in summer last year as you already seem to have discovered. But currently I'm not working on it, so feel free to catch up and get it pulled in...

**Comment by fabian-braun** [comment]
@jfiala , would you do the review or maybe point me to someone else I could ask? If I can further support with anything let me know

**Comment by jfiala** [comment]
@fabian-braun  Sorry I'm totally occupied with other things, maybe @cbornet  can take a look in the meanwhile?
