### ISSUE TITLE
Codegen v2.1.2-M1 does NOT generate Java client code when swagger specification contains Map model

### ISSUE THREAD

**Issue by kcao3** [swagger-api/swagger-codegen#474]
Hello,

I am using codegen v2.1.2-M1. Currently codegen for Java does NOT generate 
Java client code when my swagger specification JSON document contains model with
Map. Here is my swagger specification document: 
https://raw.githubusercontent.com/kcao3/test/master/MyResource.json

Here is the output I received when I ran the codegen command: 

$ java -jar modules/swagger-codegen-distribution/target/swagger-codegen-distrib
ution-2.1.2-M1.jar -DdebugSwagger -DdebugModels  -i https://raw.githubuserconte
nt.com/kcao3/test/master/MyResource.json -l java -o sample/java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
usage: Codegen
 -a,--auth                 addes authorization headers when fetching the
                           swagger definitions remotely. Pass in a
                           URL-encoded string of name:header with a comma
                           separating multiple values
 -d,--debug-info           prints additional info for debugging
 -h,--help                 shows this message
 -i,--input-spec <arg>     location of the swagger spec, as URL or file
 -l,--lang <arg>           client language to generate.
                           Available languages include:
                           [android, async-scala, java, jaxrs, nodejs,
                           objc, scalatra, scala, dynamic-html, html,
                           swagger, tizen, php, python]
 -o,--output <arg>         where to write the generated files
 -t,--template-dir <arg>   folder containing the template files

I used both the Swagger UI tool and the live validation tool 
from this website: http://online.swagger.io/validator/ and they indicated 
my swagger specification is valid. So I am not quite sure why the codegen was 
not able to generate Java client code against my swagger specification. I would
like to know is there a bug in the codegen or I have done something really terrible
wrong here.

**Comment by fehguy** [comment]
please try the develop_2.0 branch.  I just deployed a snapshot fix to the [swagger-parser](https://github.com/swagger-api/swagger-parser/commit/7b0d6e0ace8fb40ded5270608b402a4b5894edc6) which was causing swagger-codegen to fail reading your file.  It works now, although I haven't tested the generated data.
