### ISSUE TITLE
CodegenResponse.java should contain `is<DataType>` boolean fields

### ISSUE THREAD

**Issue by abaruni** [swagger-api/swagger-codegen#4742]
In order to more thoroughly support any type of response defined in an Open API spec, `CodegenResponse.java` should contain `isString`, `isDouble`, `isInteger`, etc, etc. This will allow handling responses from the server at a more granular level

**Comment by wing328** [comment]
@abaruni yes, we want to do the same to CodegenParameter and CodegenProperty as well.

May I know if you've time to contribute the enhancements?

**Comment by abaruni** [comment]
@wing328 yes, i've got time to contribute the enhancement

the properties already exist in CodegenParameter and CodegenProperty:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenParameter.java#L15

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java#L42

**Comment by wing328** [comment]
@abaruni yes, you're right. The funny thing is that I added those. I'm getting old...

**Comment by abaruni** [comment]
created pull request for this issue https://github.com/swagger-api/swagger-codegen/pull/4763

**Comment by wing328** [comment]
Closed via #4763. Thanks @abaruni for the PR.
