### ISSUE TITLE
CodegenParameter and CodegenResponse have Boolean fields.

### ISSUE THREAD

**Issue by sreeshas** [swagger-api/swagger-codegen#4746]
##### Description
CodegenParameter and CodegenResponse classes have Boolean fields where as 
CodegenOperation and CodegenProperty have boolean fields. 

Boolean fields are not necessary and requires users to check for null before using them which leads to ugly code.

##### Suggest a Fix

Change the fields to boolean.

**Comment by sreeshas** [comment]
PR #4747 has the fix for this issue.

**Comment by wing328** [comment]
#4747 merged into master.
