### ISSUE TITLE
CSharp template generates SDK requiring access to temp folder that raise exception when environment has restricted access.

### ISSUE THREAD

**Issue by bunnyc1986** [swagger-api/swagger-codegen#4748]
##### Description
The C# SDK generated from the template requires system permission to get the temp folder. However some hosting environment doesn't grant permission to access system folders. That makes the ApiClient initialization fails.

##### Swagger-codegen version
latest.

##### Related issues

https://github.com/square/connect-csharp-sdk/issues/5

##### Suggest a Fix
Two options here:
1) Let caller handle the `Steam` instead of saving it in temp folder. So the SDK doesn't need to obtain the temp folder path. **(Preferred)**
2) Still save the `Stream`, but only obtain the temp folder path inside the `Deserialize` when it's needed. This is actually just a small change: [set `_templateFolderPath` in `Configuration` to be `null` instead of `Path.GetTempPath()` on line 237](https://github.com/swagger-api/swagger-codegen/blob/90512e6326d5e7aff4dd21a649b8616012da9974/modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache#L237)

**Comment by bunnyc1986** [comment]
From:
```
#237 private string _tempFolderPath = Path.GetTempPath();
```
To:
```
#237 private string _tempFolderPath;
```

**Comment by wing328** [comment]
If I remember correctly, there's a way to customize the temp folder path: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/Configuration.cs#L46

Would that help?

**Comment by bunnyc1986** [comment]
No, it doesn't help. [Line 237](https://github.com/swagger-api/swagger-codegen/blob/90512e6326d5e7aff4dd21a649b8616012da9974/modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache#L237) is called before the constructor, and I believe it is not intentional because the constructor wants to set it to null by default.

**Comment by sreeshas** [comment]
+1 for this issue. We are facing similar problems.

**Comment by wing328** [comment]
@jimschubert has refactored the C# API client via https://github.com/swagger-api/swagger-codegen/pull/3530

Please give it a try by:
```
git checkout -b jimschubert-csharp/client_refactoring 2.3.0
git pull https://github.com/jimschubert/swagger-codegen.git csharp/client_refactoring
```

**Comment by bunnyc1986** [comment]
In #3530, the _tempFolderPath is still initialized by Path.GetTempPath(). https://github.com/jimschubert/swagger-codegen/blob/da8651a74ba7f9c62dedfb95197f79b93b41c036/modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache#L94
May I request a single quick fix as I mentioned above, so I can resolve the issue on our side?

Thanks

**Comment by wing328** [comment]
@bunnyc1986 your fix is definitely reasonable. If I remember correctly, I was the one who wrote line. My intention is to have a default temp folder but that does not work well in all situations.

I'll create a fix to:
- remove Path.GetTempPath();
- in the [get](https://github.com/swagger-api/swagger-codegen/blob/90512e6326d5e7aff4dd21a649b8616012da9974/modules/swagger-codegen/src/main/resources/csharp/Configuration.mustache#L245),  default to Path.GetTempPath() if _tempFolderPath is null.

**Comment by wing328** [comment]
@bunnyc1986 @sreeshas I've filed #4749 to fix the issue. Please take a look and give it a try if you've time:
```
git checkout -b wing328-fix_issue4748 master
git pull https://github.com/wing328/swagger-codegen.git fix_issue4748
```
