### ISSUE TITLE
[Java-retrofit/retrofit2] String comparison uses for authName == operator

### ISSUE THREAD

**Issue by CodeNinjai** [swagger-api/swagger-codegen#4750]
##### Description

String comparison for authName with == does a reference comparsion, which may work if the string is being optimized by the compiler and points to a single address...

##### Swagger-codegen version

2.2.1

##### Java/libraries/retrofit/ApiClient.mustache && Java/libraries/retrofit2/ApiClient.mustache

```java
    {{#authMethods}}if (authName == "{{name}}") { {{#isBasic}}
```
##### Potential fix

```java
    {{#authMethods}}if ("{{name}}".equals(authName)) { {{#isBasic}}
```

**Comment by wing328** [comment]
Closed via #4751
