### ISSUE TITLE
Java client maven build fail generating JavaDoc

### ISSUE THREAD

**Issue by gurubook** [swagger-api/swagger-codegen#4753]
##### Description
Java client pojo generation template will add empty lines in javadoc comment, breaking maven build where javadoc will be generated.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Suggest a Fix

attached the required template patch.

[javadoc-pojo-template-fix.txt](https://github.com/swagger-api/swagger-codegen/files/760764/javadoc-pojo-template-fix.txt)

**Comment by wing328** [comment]
@gurubook thanks for reporting the issue. Please file a PR so that we can review the fix.
