### ISSUE TITLE
online generator docs are missing parameter descriptions

### ISSUE THREAD

**Issue by olensmar** [swagger-api/swagger-codegen#476]
the online generator at http://generator.swagger.io/ seems to be missing a more detailed description of the input to the /gen/client call - is this supposed to be part of the documentation there or is it elsewhere?

thanks!

/Ole

**Comment by fehguy** [comment]
I believe the develop_2.0 branch has some improved documentation, which has been deployed to http://generator.swagger.io. Can you look there or online to see if that solved the ambiguity?  If not we can look into adding more info

**Comment by fehguy** [comment]
Closing as covered in master.
