### ISSUE TITLE
[Swift] RxSwift Option Not Respected

### ISSUE THREAD

**Issue by JackWink** [swagger-api/swagger-codegen#4765]
##### Description

Generating a client with 2.2.0 and 2.2.1 doesn't seem to respect the `responseAs=RxSwift` option, however the `responseAs=PromiseKit` works.

##### Swagger-codegen version

2.2.0 and 2.2.1

##### Swagger declaration file content or url

n/a

##### Command line used for generation

Excerpt from our bash script:

```
$CODE_GENERATOR generate -i http://localhost:5000/api/spec.json \
    -l swift \
    -o clients/swift-rx/ \
    -t client_templates/Swift \
     --language-specific-primitives Int \
    --type-mappings integer=Int \
    --additional-properties projectName=Client,podAuthors=Anon,podHomepage=https://example.com,podSummary="Client",responseAs=RxSwift
```

##### Steps to reproduce

Download the client generator from http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.0/swagger-codegen-cli-2.2.0.jar or http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.1/swagger-codegen-cli-2.2.1.jar and try to generate an RxSwift build.

##### Related issues

n/a

##### Suggest a Fix

Really scratching my head here.  We ran `java -jar swagger-codegen-cli.jar config-help -l swift` and it showed the following for the `responseAs` field:

```
CONFIG OPTIONS
       	sortParamsByRequiredFlag
       	    Sort method arguments to place required parameters before optional parameters. (Default: true)

       	ensureUniqueParams
       	    Whether to ensure parameter names are unique in an operation (rename parameters that are not). (Default: true)

       	projectName
       	    Project name in Xcode

       	responseAs
       	    Optionally use libraries to manage response.  Currently PromiseKit are available.
```

Looking at the code for the [swift generator](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SwiftCodegen.java#L145) it seems to suggest we should see `PromiseKit, RxSwift are`, instead we just see `PromiseKit are`.  Perhaps the wrong versions of the codegen have been uploaded to maven?

**Comment by wing328** [comment]
@JackWink thanks for reporting the issue. May I know if you've tried to repeat the issue using the latest master of Swagger Codegen?

**Comment by JackWink** [comment]
Master doesn't seem to have this issue

**Comment by wing328** [comment]
@JackWink thanks for testing with the latest master. We plan to release 2.2.2 this month.
