### ISSUE TITLE
Swagger Documentation in PDF

### ISSUE THREAD

**Issue by rohitsakala** [swagger-api/swagger-codegen#4769]
##### Description

Hi, I wanted to know is there a feature where the spec.json can be converted to a pdf file just like the static documentation. 

##### Commands 

Something like 
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l pdf

**Comment by wing328** [comment]
@rohitsakala currently, there's no direct export to pdf but we would welcome contributions to support that.

**Comment by jfiala** [comment]
@rohitsakala @wing328 pls take a look at the Swagger2Markup (https://github.com/Swagger2Markup/swagger2markup) project, they allow to convert to Asciidoctor files and then to HTML sites or PDF format.

**Comment by Fer-Picu** [comment]
y agree to this feature

**Comment by wing328** [comment]
As a workaround, you may consider using `html` or `html2` to generate HTML documentations and then use 3rd-party tools to convert the HTML into PDF.

**Comment by plutext** [comment]
See further https://stackoverflow.com/questions/30217910/generate-pdf-from-swagger-api-documentation
