### ISSUE TITLE
[PYTHON] requirements.txt different from setup.py for six

### ISSUE THREAD

**Issue by vsoch** [swagger-api/swagger-codegen#4770]
##### Description

Hey swagger! When I generate a `python-client`, I noticed that the version of six specified in the requirements.txt is different from what is in the setup.py:

setup.py

      REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

requirements.txt

      certifi >= 14.05.14
      six == 1.8.0
      python_dateutil >= 2.5.3
      setuptools >= 21.0.0
      urllib3 >= 1.15.1

I might have ignored had there not been the "it must be this version" `==` sign. Which would you like us to use?

##### Command line used for generation

I am just downloading with curl:

      download=$(curl -k -X POST -H "content-type:application/json" -d '{"swaggerUrl":"https://app.swaggerhub.com/apiproxy/schema/file/susanweber/UID/1.0.0/swagger.json"}' https://generator.swagger.io/api/gen/clients/python)

- python

##### Steps to reproduce

No bug, I'm just anticipating something :)

##### Suggest a Fix

Just put the same thing both places.

I'm new to swagger and totally loving it by the way! I spent a day to roll my own api client, found swagger, and now I can generate them for languages that I don't even know. *pouf* mind blown!

**Comment by wing328** [comment]
@vsoch thanks for reporting the issue. That should be fixed already in the latest master.

Please pull the latest master to give it a try and let us know if you still experience the same issue.
