### ISSUE TITLE
ApiImplicitParam and public static inner classes

### ISSUE THREAD

**Issue by james-async** [swagger-api/swagger-codegen#4777]
Once moving my parameter objects to be top level instead of public static inner classes the swagger.json generates as expected. For example, controllers.ApiController.TokenAccount was the inner class that was moved to controllers.model.TokenAccount.

##### Description

When first defining my service I had the parameter objects as simple public static classes. The ApiImpliciParam datatype was set to the full path - (package.class.innerclass).  However the generation of the swagger.json would fail with the following exception.

[error] application - Failed to resolve 'controllers.ApiController.TokenAccount' into class
java.lang.ClassNotFoundException: controllers.ApiController.TokenAccount
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.modules.swagger.PlayReader.typeFromString(PlayReader.java:411)
	at play.modules.swagger.PlayReader.readImplicitParam(PlayReader.java:387)
	at play.modules.swagger.PlayReader.readImplicitParameters(PlayReader.java:360)
	at play.modules.swagger.PlayReader.read(PlayReader.java:198)
	at play.modules.swagger.PlayReader.read(PlayReader.java:63)
	at play.modules.swagger.PlayReader.read(PlayReader.java:57)

##### Swagger-codegen version

"io.swagger" % "swagger-play2_2.11" % "1.5.3"

```java
@ApiImplicitParams(
      {@ApiImplicitParam(name = "tokenAccount", value = "TokenAccount", dataType = "controllers.ApiController.TokenAccount", paramType = "body", required = true)}
  )
```
 
compared with the following that worked as expected.

```java
@ApiImplicitParams(
      {@ApiImplicitParam(name = "tokenAccount", value = "TokenAccount", dataType = "controllers.model.TokenAccount", paramType = "body", required = true)}
  )
```
##### Suggest a Fix

I was surprised that a public static class failed generation.  You do not necessarily need to support them, but this might simply be a bug against your documentation.

**Comment by wing328** [comment]
@james-async is the issue related to the following project instead?

https://github.com/swagger-api/swagger-play

**Comment by james-async** [comment]
Based on the stack trace you could be right. I did not put it in this project on purpose -- just where I ended up.  I did not know how deep of a problem, if it was something on the "surface" of the class parsing or something lower in the dependency chain in io.swagger. I think while I was looking at that I just ended up thinking documenting the stumble I had and did not recheck which project I was posting against.

**Comment by wing328** [comment]
@james-async we added a Java Play server generator in v2.2.3. Please give it a try and let us know if you've any feedback.
