### ISSUE TITLE
Java example is broken

### ISSUE THREAD

**Issue by ToreJohansson** [swagger-api/swagger-codegen#4781]
##### Description

The yaml below will result in incorrect java example:

Arrays.asList(new List<String>())

##### Swagger-codegen version
2.2.2-SNAPSHOT

##### Swagger declaration file content or url

    ```yaml
  type: array
  items:
    type: string
    ```
##### Command line used for generation
java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l jaxrs-cxf  -i api.yaml

##### Suggest a Fix

        if(type != null)
        {
            if (type.contains("String"))
            {
                if (example == null)
                {
                    example = p.paramName + "_example";
                }
                example = "\"" + escapeText(example) + "\"";
            } else if (type.contains("Integer") || type.contains("Short"))
            {
                if (example == null)
                {
                    example = "56";
                }
            } else if (type.contains("Long"))
            {
                if (example == null)
                {
                    example = "56";
                }
                example = example + "L";
            } else if (type.contains("Float"))
            {
                if (example == null)
                {
                    example = "3.4";
                }
                example = example + "F";
            } else if (type.contains("Double"))
            {
                example = "3.4";
                example = example + "D";
            } else if (type.contains("Boolean"))
            {
                if (example == null)
                {
                    example = "true";
                }
            } else if (type.contains("File"))
            {
                if (example == null)
                {
                    example = "/path/to/file";
                }
                example = "new File(\"" + escapeText(example) + "\")";
            } else if (type.contains("Date"))
            {
                example = "new Date()";
            } else if (!languageSpecificPrimitives.contains(type))
            {
                // type is a model class, e.g. User
                example = "new " + type + "()";
            }
        }

**Comment by wing328** [comment]
@ToreJohansson thanks for reporting the issue. Please file a PR so that we can review the fix.

**Comment by wing328** [comment]
Closing this as there's no update.
