### ISSUE TITLE
\\DateTime non existent class appearing in import for PHP model

### ISSUE THREAD

**Issue by archana27m** [swagger-api/swagger-codegen#4791]
##### Description

I am trying to generate PHP code via swagger codegen, however if there is DateTime format for any of class attribute, then there is non-required classname appearing in "imports" as "DateTime" when I used -DdebugModels causing unnecessary import of "DateTime" non-existent class when I use the following code snippet in my model.mustache

{{#imports}}use {{import}};
{{/imports}} 
 
results in 

use MyPackage\model\\\DateTime;

which is not required.

##### Swagger-codegen version
swagger: 2.1.5

**Comment by wing328** [comment]
@archana27m I suspect you're using an old version of Swagger Codegen. Please give the latest master or stable release a try and share the spec if you still encounter issues.

**Comment by archana27m** [comment]
@wing328  I am using swagger codegen 2.1.5. will it be possible to suggest a fix or some workaround for this?

**Comment by wing328** [comment]
Please upgrade to the latest stable release: https://github.com/swagger-api/swagger-codegen/releases

**Comment by archana27m** [comment]
@wing328 Is that possible without upgrading?

**Comment by wing328** [comment]
I don't think so.

The upgrade process should be pretty smooth. Let us know if you need help.

**Comment by archana27m** [comment]
@wing328 Thank you. I will let you know if any help needed.
