### ISSUE TITLE
how to say swagger-codegen to implement serializable for model classes.

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [swagger-api/swagger-codegen#4792]
##### Description

I want the Swagger generated classes to implement Serializable.  Is there way i can say to swagger-codegen to implement this ??

##### Swagger-codegen version

swagger-codegen version : 2.2.1

##### Swagger declaration file content or url

    ```yaml
paths:
   /pet:
    get:
      description: pet
      tags:
        - pet
      responses:
        '200':
          description: got response ok
          schema:
            $ref: '#/definitions/PetTO'
definitions:
  PetTO:
    type: object
    properties:
      id:
        type: string
        description: pet id
      petName:
        type: string
        description: pet name
    ```
    (for YAML code) or
   -->

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i pet.yml   -l java --library=okhttp-gson 
										     -o generated_source_code 
										    -c package_config.json

=> With the above Yaml, Swagger-codegen will generate a PetTO class. I want the PetTO class to implement serializable. Is there a way i can say to swagger-codegen to implement serializable for this class.

**Comment by wing328** [comment]
Have you tried the following option?
```
	serializableModel
	    boolean - toggle "implements Serializable" for generated models (Default: false)
```

Ref: `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java`

**Comment by kpradeepkumarreddy** [comment]
thanks. it is working with "serializableModel" : true

**Comment by Pramodhraj** [comment]
Hi, where to add this serializableModel" : true
please help

**Comment by kpradeepkumarreddy** [comment]
> Hi, where to add this serializableModel" : true
> please help

add it in the config.json, which you provide as input to the swagger-codegen

**Comment by PetarMI** [comment]
Is it possible to implement Serializable just for a set of classes instead of all?

**Comment by lucvandijk** [comment]
When I run my codegen like the following:
swagger-codegen generate -i $SWAGGER_URL -l $CLIENT -o $OUT_DIR -D modelDocs=$MODEL_DOCS -D apiTests=$API_TESTS -D apiDocs=$API_DOCS --config config.json

With the following config inside my config.json:
{
  "modelPackage": "dms.models",
  "apiPackage": "dms.api",
  "serializableModel" : true
}

Objects still don't implement Serializable

**Comment by mukesh02** [comment]
can we serialize specific model in openapi?
