### ISSUE TITLE
[Lua] Add API client generation

### ISSUE THREAD

**Issue by daurnimator** [swagger-api/swagger-codegen#4794]
Add lua API client generation.

Probably using [lua-http](https://github.com/daurnimator/lua-http)

**Comment by wing328** [comment]
@daurnimator sounds good to me :)

May I know if you're working on the Lua generator? Do you need any help from us (the community)?

**Comment by daurnimator** [comment]
> May I know if you're working on the Lua generator?

Not yet. Though I'm considering it.

> Do you need any help from us (the community)?

Indeed: I'm not sure where to start. (I've just had a look around at some of the other generators: shouldn't be too hard to translate...)

**Comment by wing328** [comment]
We recently add the Bash generator via https://github.com/swagger-api/swagger-codegen/pull/4541, which may serve as a good starting point to add a new client generator.

**Comment by zjarkov** [comment]
Hi, didn't try it personally wth swagger but [lua-Spore](http://fperrad.github.io/lua-Spore/) is not sufficient?

**Comment by daurnimator** [comment]
> Hi, didn't try it personally wth swagger but lua-Spore is not sufficient?

I didn't realise lua-Spore had a swagger component. It might actually be suitable for me.

-----------------

I'm wondering if adding lua support to swagger-code is the most useful thing to do. I feel like a fully dynamic-runtime approach like [swagger-js](https://github.com/swagger-api/swagger-js) took might be more appropriate.

**Comment by wing328** [comment]
@daurnimator dynamic client approach (e.g. swagger-js, lua-spore) is definitely one way to do it but some developers prefer static clients generated by Swagger Codegen.

**Comment by kigsmtua** [comment]
@daurnimator  any progress on this

**Comment by wing328** [comment]
@daurnimator @zjarkov @kigsmtua similar to PowerShell and Rust, we can go through the same approach by creating a Lua API client for [PetStore](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml) by focusing on a few endpoints.
- [GET](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L156-L183)
- [POST (form)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L184-L218)
- [POST (JSON body)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L31-L56)

The Lua code can be put in the folder `samples/client/petstore/lua`.

Then we can reverse-engineer the Lua code to create the mustache templates and the generator in Java.

**Comment by daurnimator** [comment]
> @daurnimator any progress on this

No. I think I'm one of those developers that prefers a dynamic approach :)

**Comment by daurnimator** [comment]
> @daurnimator @zjarkov @kigsmtua similar to PowerShell and Rust, we can go through the same approach by creating a Lua API client for PetStore by focusing on a few endpoints.
> 
>     GET
>     POST (form)
>     POST (JSON body)
> 
> The Lua code can be put in the folder samples/client/petstore/lua.
> 
> Then we can reverse-engineer the Lua code to create the mustache templates and the generator in Java.

I'm not totally sure what you're requesting. If you can explain further (are you on irc? matrix?) I'm happy to give you samples. I created the PR https://github.com/swagger-api/swagger-codegen/pull/6244 to track.

**Comment by wing328** [comment]
@daurnimator thanks. Let me review the code.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/6252.

@kigsmtua @zjarkov please pull the latest master or use the latest SNAPSHOT version to give it a try.
