### ISSUE TITLE
Generate better example code

### ISSUE THREAD

**Issue by bartkummel** [swagger-api/swagger-codegen#4796]
##### Description

The code generated does not leverage all example and default values from the Swagger spec.

##### Swagger-codegen version

2.2.1

##### Suggest a Fix

Use examples, default values and enum values from Swagger spec to generate better example values.

**Comment by wing328** [comment]
@bartkummel I think some generators do have better support for default and example values.

May I know which generators you find inadequate support of example/default value?

**Comment by bartkummel** [comment]
I have tried the nodejs generator. I have also created a pull request on the DefaultGenerator, which is subclassed by the specific generators, as I understand it. I have tested my PR with the nodejs generator and it works as I expect. See https://github.com/swagger-api/swagger-codegen/pull/4797

**Comment by wing328** [comment]
Closed via #4797
