### ISSUE TITLE
Reference links not handled

### ISSUE THREAD

**Issue by suleymankoksal** [swagger-api/swagger-codegen#4802]
Hi Everyone;

##### Description
In my swagger YML' s response, in responses schema is reference other YML. Not same file. 
When I generate csharp code in my local host, i don't get other (reference) json information.
I look just reference url not reference content. But I want to see reference content.

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url

My First File, you look $ref
responses:
        200:
          description: OK
          schema: 
            $ref: 'https://api.swaggerhub.com/domains/endermalkoc/DecoCMS/1.0#/definitions/Zone'

When I generate csharp code via Mustache in local host
{{#responses}}
    {{#-first}}
        {{{jsonSchema}}}
    {{/-first}}
{{/responses}}

My Result code is 
{
     "description" : "OK",
     "schema" : {
        "$ref" : "#/definitions/Zone"
     }
}

**But I want to see json information (reference) in schema from reference other $ref. HOW CAN I? Thanks.**

##### Related issues
#1551 
I looked other issues but not fix :(

**Comment by wing328** [comment]
@suleymankoksal thanks for reporting the issue. Please share the spec via https://gist.github.com so that we can more easily reproduce the issue.

**Comment by wing328** [comment]
Please pull the latest master (which uses a newer version of Swagger Parser) to give it a try.
