### ISSUE TITLE
[C#] ApiClient fails to parse return type "string" to response

### ISSUE THREAD

**Issue by meisterlampe** [swagger-api/swagger-codegen#4816]
##### Description

Hi,

I generated a C#-Client for the swagger.yaml created by swagger-node and have an issue.
Steps for code generation:
- `swagger project create hello-world` and chose express as framework
- Used the generated swagger.yaml to generate the c# client:
`java -jar swagger-codegen-cli-2.2.1.jar generate -i hello-world/api/swagger/swagger.yaml -l csharp`
- In Visual Studio I added two simple lines of code: 
`var api = new DefaultApi("http://192.168.92.145:10010");`
`Console.WriteLine(api.Hello("Bob"));`

Now I'm getting a runtime exception, because the generated code tries to parse the returned string "Hello, Bob!" into HelloWorldResponse.
Exception is beeing thrown in ApiClient.cs::Deserialize in this line:
`return JsonConvert.DeserializeObject(response.Content, type, serializerSettings);`

I debugged it and response.Content is "Hello, Bob!". So the failing statement at runtime is:
`return JsonConvert.DeserializeObject("Hello, Bob!", typeof(HelloWorldResponse), serializerSettings);`

The Exception is:
`An unhandled exception of type 'IO.Swagger.Client.ApiException' occurred in IO.Swagger.dll
Additional information: Error converting value "Hello, Bob!" to type 'IO.Swagger.Model.HelloWorldResponse'. Path '', line 1, position 15.`

Is there a bug in the code-generation or in swagger-node?

Should the hello-world-project return `{ message: "Hello, Bob!" }`  or is just `"Hello, Bob!"` a valid response in case of just one message property?

Thanks in advance..

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url
generated swagger.yaml from swagger-node hello-world:
https://gist.githubusercontent.com/meisterlampe/49f2deb9d35cc4524c0d75f4e015cff8/raw/6fa4cbeaba79292cee9a97899a684f65d29780aa/swagger.yaml

##### Command line used for generation
 java -jar swagger-codegen-cli-2.2.1.jar generate -i hello-world/api/swagger/swagger.yaml -l csharp

**Comment by wing328** [comment]
In your spec, you've the following defined:
```
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
```
which is an object (JSON) and an example is `{ message: "Hello, Bob!" }`

Whether your endpoint should return an object or primitive type (e.g. string) is entirely based on your use case. Returning an object (JSON) will allow you to return additional data in the future by defining more fields/properties in the object.

**Comment by meisterlampe** [comment]
Ok thank you, that makes sense ;) 
So spec and server implementation of the code generated by swagger-node do not match at this point.
I'll head over to the swagger-node repo and file an issue there to get this very minor bug fixed.
