### ISSUE TITLE
Vendor Extensions of JSON type being parsed as string

### ISSUE THREAD

**Issue by ankeshanand** [swagger-api/swagger-codegen#4826]
##### Description

While using a vendor extension that is of JSON type, I get a string instead of a dict (in case of Python).
This extension is defined in the swagger spec as:
```json
"x-new-extension": {
    "name": "Foo",
    "amount": 1
}
``` 

When I try to use this in swagger-codegen using `val = {{vendorExtensions.x-new-extension}}`,
the generated code output is this:

`val = {&quot;x-new-extension&quot;:{&quot;name&quot;:&quot;Foo&quot;,&quot;amount&quot;:1}`

As you can see, the JSON object was not parsed properly and I get an badly formatted string instead. Is there anyway I could modify a file in swagger-codegen project to produce the right output?
##### Swagger-codegen version
2.2.1

**Comment by ankeshanand** [comment]
Okay, I figured out a solution. I can simply do {{{vendorExtensions.x-new-extension}}} to unescape the string.

**Comment by wing328** [comment]
@ankeshanand yup, or `{{&vendorExtensions.x-new-extension}}}`
