### ISSUE TITLE
swagger codegen generate api from produces json value "produces: [ "*/*" ]" to  localVarAccepts *_/_* ???

### ISSUE THREAD

**Issue by andyman09** [swagger-api/swagger-codegen#4830]
##### Swagger declaration file content or url

my swagger.json file look something like this:

`/user/{user-id}: {
put: {
tags: [
"filter-controller"
],
summary: "updateUser",
operationId: "updateUserUsingPUT",
consumes: [
"application/json"
],
produces: [
"*/*"
] ...`

##### Command line used for generation

swagger-codegen generate -i swagger.json -l java

The generated api looks something like this:

`List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*_/_*"
        };
`

instead of 

`List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
`
  Any idea why? Because of this can't make successfully call to my api.

NOTE: when I generate swagger jave client on swagger edit it's working fine. It generated the correct localVarAccepts/

**Comment by wing328** [comment]
@andyman09 the issue should have been addressed in the latest master. Please pull the latest to give it a try.

If it's not the case, we'll look into the issue again.
