### ISSUE TITLE
Creating qt5cpp library from swagger has missing include

### ISSUE THREAD

**Issue by fortiumant** [swagger-api/swagger-codegen#4833]
##### Description

While creating a static library from the generated files, compilation issues arose due to QDateTime only being forward declared. Adding the include resolves the issue.

The file affected is SWGHelpers.cpp. So editing the mustache file and tested locally worked correctly.

##### Sample CMake lists

I used generated code from existing examples. Using the cmake file below, just create a folder called client and place the generated code in there to reproduce.

[CMakeLists.txt](https://github.com/swagger-api/swagger-codegen/files/792968/CMakeLists.txt)

**Comment by wing328** [comment]
Closed via #4834
