### ISSUE TITLE
[Spring][maven-plugin] Too more spaces/tab in 2.2.1

### ISSUE THREAD

**Issue by M3lkior** [swagger-api/swagger-codegen#4837]
##### Description

Since codegen-maven-plugin 2.2.1, generated code contains extra space/tab and CR : 

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url
2.2.0 : 

![image](https://cloud.githubusercontent.com/assets/5501911/23215775/d54c66c8-f913-11e6-96a6-9fae59ca26d7.png)
    
In 2.2.1 with the same api.yaml : 

![image](https://cloud.githubusercontent.com/assets/5501911/23215744/ba363eae-f913-11e6-9aab-939c2407d67f.png)
 
##### Steps to reproduce

Generate code from maven plugin in v2.2.1 after generating in 2.2.0 (for comparison)

**Comment by wing328** [comment]
@M3lkior thanks for reporting the issue. Can you please try the latest master (2.2.2) to see if the issue still occurs?

We'll release 2.2.2 soon.

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by M3lkior** [comment]
Sorry @wing328 , seems to be solved in 2.2.2.

**Comment by wing328** [comment]
@M3lkior np. Thanks for performing a check to confirm.

Let us know if you've further feedback on Swagger Codegen.
