### ISSUE TITLE
Array of string values as query parameter is not generated correctly in Java client code

### ISSUE THREAD

**Issue by kcao3** [swagger-api/swagger-codegen#484]
Hello,

It seems to me the swagger-codegen version 2.1.2-M1 currently does NOT generate Java client code properly when dealing with a query parameter as an array of string values. For example, when I specified an optional query parameter as the following:
```js
{
     "name": "callerIds",
    "in": "query",
    "description": "A list contains the unique IDs the caller could pass in.",
    "required": false,
    "type": "array",
    "items": {
        "type": "string"
    },
    "collectionFormat": "multi"
}
```

I expected the tool to generate a query string in this specific this format: callerIds=abc&callerIds=xyz&callerIds=lmn to represent a list callerIds with string values("abc", "xyz", "lmn"). However, currently swagger-codegen generates the query string in this exact format:  callerIds=[abc,xyz,lmn].
I believe this is not the correct format to present an array of string value as a query parameter.

The following shows the a portion of the Java generated code from my swagger specification document: https://raw.githubusercontent.com/kcao3/test/master/MyResource.json using the swagger-codegen tool from the swagger-codegen-develop_2.0 branch.
```java
public class TopologyServiceApi {

public GetMetricsResponse getMetrics (List<String> callerIds, String sourceNodeId, String destinationNodeId) throws ApiException {
    Object postBody = null;
    ....
    
    // query params
    Map<String, String> queryParams = new HashMap<String, String>();
    
    .... 
    
    if(!"null".equals(String.valueOf(callerIds)))
      queryParams.put("callerIds", String.valueOf(callerIds));
    ...
    
    String response = apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType);
        ...
}
}    
```
```java
public class ApiInvoker {

    public String invokeAPI(String host, String path, String method, Map<String, String> queryParams, Object body, Map<String, String> headerParams, Map<String, String> formParams, String contentType) throws ApiException {
    ...
    
    StringBuilder b = new StringBuilder();

    for(String key : queryParams.keySet()) {
      String value = queryParams.get(key);
      if (value != null){
        if(b.toString().length() == 0)
          b.append("?");
        else
          b.append("&");
        b.append(escapeString(key)).append("=").append(escapeString(value));
      }
    }
    String querystring = b.toString();
    
    ...
    }   
}
```

**Comment by sudohippie** [comment]
@webron I have fixed Java and Android templates to address this issue. Will you accept a PR?

**Comment by webron** [comment]
@sudohippie - we always appreciate PRs. Just make sure to submit it against the develop_2.0 branch and link it to this issue.

**Comment by wing328** [comment]
Closing this as #893 has been merged into master.
