### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type application/zip

### ISSUE THREAD

**Issue by HansHammel** [swagger-api/swagger-codegen#4841]
swagger-editor release 2.10.5, win10, chrome

`Resource interpreted as Document but transferred with MIME type application/zip "http://generator.swagger.io/api/gen/download/1ce98a20-cb5c-4758-8a50-2485baf38106". codegen.js:43`

note: fixed some issues with subfolders and https: swagger-api/swagger-editor#1193 swagger-api/swagger-editor#1192

**Comment by wing328** [comment]
Looks like a Swagger Editor issue. Please report the issue in the Swagger Editor github repo instead.
