### ISSUE TITLE
Warn when passing form data without a matching "consumes" directive

### ISSUE THREAD

**Issue by dhasenan** [swagger-api/swagger-codegen#4853]
##### Description

If you pass a parameter as `formData`, you need a `Content-Type: multipart/form-data` or `application/x-www-form-urlencoded`. It would be really handy if swagger-codegen warned you when you fail to do so -- or if it just did something sensible by default.

By default, at least with the java client, it sends a content type of `application/json`. A JAX-RS server, for instance, will produce a 403 error because of the content type mismatch.

##### Swagger-codegen version

2.2.1

**Comment by jeff9finger** [comment]
Yea, I noticed this too. The generated client is unusable if trying to send a request to download a file with a specific media type, like "application/pdf" or "text/csv", etc. The client alway sets the Content-Type header to "application/json", with no way to change it.

**Comment by wing328** [comment]
In the spec, do you have a proper `consumes` set for the operation?

**Comment by dhasenan** [comment]
No, I didn't have a `consumes` set. I want the code generator to complain about that fact.

**Comment by wing328** [comment]
You may want to provide this feedback to the Swagger Parser project instead, which is used by Swagger Codegen to parse the Swagger/OpenAPI spec.

**Comment by dhasenan** [comment]
Filed https://github.com/swagger-api/swagger-parser/issues/403

Another possible solution is to make the generated client intuit the appropriate content type from the parameters. However, since there are tradeoffs between `multipart/form-data` and `application/x-www-form-urlencoded`, that might not be appropriate.
