### ISSUE TITLE
Swagger Codegen Java not using java.util.Date when not specifying date library

### ISSUE THREAD

**Issue by raghav0110** [swagger-api/swagger-codegen#4856]
##### Description

According to [1784](https://github.com/swagger-api/swagger-codegen/pull/1784), not specifying the date library should result in using java.util.Date. But, I notice that it ends up using joda DateTime.

##### Swagger-codegen version

version 2.2.1

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i http://localhost:8080/v1/swagger.json -l java --library feign -o samples/client/my-client`

##### Steps to reproduce

You'll notice the joda library is used in the petstore sample client.

**Comment by cbornet** [comment]
The default date has been changed to joda. If you want old dates, you need to use -DdateLibrary=legacy.
That said it's not recommended to use java.util.Date and you should always prefer threeten or joda.

**Comment by sacdpathade** [comment]
> The default date has been changed to joda. If you want old dates, you need to use -DdateLibrary=legacy.
> That said it's not recommended to use java.util.Date and you should always prefer threeten or joda.

Please let me know how can we pass reset dateLibrary while using "swagger-codegen-maven-plugin" in pom.xml file?

**Comment by DaBlick** [comment]
I believe that there's a bug where the threeten stuff is NOT included in the POM.xml as a dependency.
