### ISSUE TITLE
[OBJC] Problem in prefix generation in APIClient

### ISSUE THREAD

**Issue by patulacci** [swagger-api/swagger-codegen#4865]
##### Description

Some Classes in APIClient are not generated with config.json prefix (and keep SWG prefix) :

1) Line 68 in ApiClient.h, SWGConfiguration 

2) Line 78 in ApiClient.m, SWGJSONRequestSerializer

3) Line 79 in ApiClient.m, kSWGApplicationJSONType

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

path/to/CLIENT/Core APIClient.h line 68
path/to/CLIENT/Core APIClient.m lines 78, 79

##### Command line used for generation
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
-i http://127.0.0.1:9000/swagger.json \
-l objc \
-o samples/client/CLIENT  \
-c config.json
```

**Comment by wing328** [comment]
@patulacci thanks for reporting the issue. The templates can be found in [modules/swagger-codegen/src/main/resources/objc/](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/objc)
```
grep -R SWG modules/swagger-codegen/src/main/resources/objc/*
modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache:        SWGJSONRequestSerializer * swgjsonRequestSerializer = [SWGJSONRequestSerializer serializer];
modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache:        _requestSerializerForContentType = @{kSWGApplicationJSONType : swgjsonRequestSerializer,
modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache:    __weak id<SWGSanitizer> sanitizer = self.sanitizer;
modules/swagger-codegen/src/main/resources/objc/ApiClient-header.mustache:- (instancetype)initWithBaseURL:(NSURL *)url configuration:(id<SWGConfiguration>)configuration;
```
Would you have time to contribute the fix?

**Comment by patulacci** [comment]
I'll have a look yes. Thanks for your answer

**Comment by wing328** [comment]
@patulacci thank you. Let us know if you need any help.

**Comment by patulacci** [comment]
I've just sent the pull request
