### ISSUE TITLE
[Ruby] Can only use content-type application/json with ruby-client

### ISSUE THREAD

**Issue by viktorchukhantsev** [swagger-api/swagger-codegen#4867]
Can only use content-type application/json with ruby-client. Other content types are fail, but codegen should support such clients:

  application/json
  application/vnd.github+json

##### Swagger-codegen version

2.2.1

##### Suggest a Fix

Just update regexp at https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/ruby/api_client.mustache#L132 to something like this
```
/Application\/.*json(;.*)?/i
```

**Comment by wing328** [comment]
@viktorchukhantsev please submit a PR for the suggested fix so that we can review more easily.

**Comment by viktorchukhantsev** [comment]
@wing328 Created #4893

**Comment by wing328** [comment]
@viktorchukhantsev thanks for the PR, which has been merged into master.
