### ISSUE TITLE
Spring Boot Path Parameter in the Spec gets renamed into CamelCase in Code and the spec thats generated!

### ISSUE THREAD

**Issue by techlogix** [swagger-api/swagger-codegen#4870]
##### Description

Path parameter defined in the yaml spec for example "student-id" on the path and named as such in the parameter name - gets incorrectly renamed to "studentId" in the Spring Controller.

##### Swagger-codegen version

This is the latest version thats hooked to the editor at editor.swagger.io.
##### Steps to reproduce

Create any POST URI path with a path paramenter and have a name that's hypenated.

e.g. POST /students/student-id

Then generate Spring Boot - the API and Controller do not have that name for the parameter - instead it expects a Camel Case.

**Comment by digitaldivvy** [comment]
This issue is a BLOCKER - a fix should be to respect the exact name of the path parameter in the Spring Code that's generated.

**Comment by techlogix** [comment]
in the YAML snippet below - the path parameter is called 'transaction_id' - but when the Spring code is generated - the code 

***Java Code snippet ***
@PathVariable("transactionId") String transactionId)

this is incorrect

it SHOULD be

@PathVariable("transaction_Id") String transactionId)


*** the YAML Spec ***
```  /foo/{transaction_id}/bar:
    post:
      summary: |
        
       
      description: |

      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: transaction_id
          description:
          required: true
          type: string
        - in: body
          name: account
          description: Add an account to an existing transaction. If one already exists this will error out.
          required: true
          schema:
            $ref: "#/definitions/Account"
```

**Comment by wing328** [comment]
To fix it, can you try updating the following file?

[modules/swagger-codegen/src/main/resources/JavaSpring/pathParams.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/pathParams.mustache)

and replace `@PathVariable("{{paramName}}")` with `@PathVariable("{{baseName}}")`

then use `-t` to specify the mustache template path.

**Comment by techlogix** [comment]
I made the changes locally and tested it. Yes - the parameters are now showing up.

**Comment by wing328** [comment]
@techlogix thanks for testing the fix.

@ePaul has filed https://github.com/swagger-api/swagger-codegen/pull/4875 to fix the in the template.

**Comment by techlogix** [comment]
@wing328 You're welcome. 
BTW there are few other enhancements I am wanting to code into the codegen to bring up the template to Spring best-practices.

**Comment by wing328** [comment]
@techlogix 👍 looking forward to your PRs
