### ISSUE TITLE
Introduce parameter object for query parameters

### ISSUE THREAD

**Issue by bedag-moo** [swagger-api/swagger-codegen#4876]
##### Description

In RESTful APIs, search operations are often represented by a resource for the search result, where search parameters are passed as query parameters. Often, most of these are optional, and there can be a great many of them.

When generating code for such an operation, swagger-codegen currently generates a separate method parameter for each query parameter. For instance, the typescript-angular2 binding generates:

    /**
     * Searches issues.
     * 
     * @param from offset from which to start paging; defaults to 0
     * @param size maximum number of hits to return; defaults to 500
     * @param reporterId 
     * @param assigneeId 
     */
    public searchIssues (from?: number, size?: number, reporterId?: string, assigneeId?: string, extraHttpRequestParams?: any ) : Observable<Array<models.Issue>> {

forcing a caller to skip absent parameters by passing null:

    issuesApi.searchIssues(null, null, null, currentUser);

This code is hard to read (it is not apparent what the 4th parameter means) and brittle if the api changes (if a query parameter is added, you have to insert a null argument at all call sites). 

Instead, I'd prefer to write something like

    issuesApi.searchIssues({
        assigneeId: currentUser
    });

Therefore, would it be possible for swagger-codegen to generate a parameter object in such cases?

##### Swagger-codegen version

2.3.0-SNAPSHOT

##### Suggest a Fix

The API spec does not (and probably should not) describe when a parameter object is sensible for doing a method call. I'd therefore like swagger-codegen to apply reasonable heuristics based on the number of parameters (and possibly their optionality).

If desired, I could try implementing this.

**Comment by fehguy** [comment]
The spec doesn't support this, so we cannot add it into the tool.  There will be, however, an update in the 3.0 spec which is hitting RC0 tomorrow which allows for this.  So for now, we can't merge even with a pull request.  The new structure to support this feature will be different.

**Comment by bedag-moo** [comment]
Indeed, I didn't realize. Ok, we'll wait for official support.
