### ISSUE TITLE
release date 2.2.2

### ISSUE THREAD

**Issue by CFenner** [swagger-api/swagger-codegen#4878]
##### Description

The swagger-codegen-maven-plugin v2.2.1 is causing test classes to be build with compile scope, which is not possible and will fail the build. However, this is fixed in v2.2.2-SNAPSHOT, when can we expect a release of 2.2.2?

##### Swagger-codegen version

2.2.1

**Comment by wing328** [comment]
@CFenner we're working on the release. Will keep you posted.

cc @fehguy

**Comment by wing328** [comment]
Btw, if your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen)

**Comment by wing328** [comment]
Released: https://github.com/swagger-api/swagger-codegen/releases/tag/v2.2.2
