### ISSUE TITLE
[JAVA] Faults in generated code Values.java/JSON.java

### ISSUE THREAD

**Issue by M1ch13l** [swagger-api/swagger-codegen#4879]
##### Description

Generated swagger code didn't compile so I changed the following.

##### Swagger-codegen version

2.2.1

##### Fix
This is the commit that fixed it.
[fix.txt](https://github.com/swagger-api/swagger-codegen/files/810678/fix.txt)

**Comment by wing328** [comment]
Please give the latest master a try or wait for v2.2.2, which will be released soon.

**Comment by M1ch13l** [comment]
The problem is in the latest master 2.2.2-SNAPSHOT

**Comment by wing328** [comment]
I don't think the snapshot version is updated with the latest master (there's no nightly build to update the snapshot version)

**Comment by wing328** [comment]
Can you also share the spec so that we can repeat the issue?

**Comment by M1ch13l** [comment]
Yeah, Maven POM
[pom.zip](https://github.com/swagger-api/swagger-codegen/files/810796/pom.zip)

**Comment by wing328** [comment]
That's not the Swagger/OpenAPI spec.

**Comment by M1ch13l** [comment]
Yes sorry
[swagger.zip](https://github.com/swagger-api/swagger-codegen/files/810819/swagger.zip)

**Comment by wing328** [comment]
@M1ch13l sorry we didn't have a chance to look into it.

Is it still an issue?
