### ISSUE TITLE
Support oneOf

### ISSUE THREAD

**Issue by toaster33** [swagger-api/swagger-codegen#488]
Curious if there is / will be support for [oneOf](http://json-schema.org/example2.html) in the code generator?  Thanks.

```
"properties": {
        "storage": {
            "type": "object",
            "oneOf": [
                { "$ref": "#/definitions/diskDevice" },
                { "$ref": "#/definitions/diskUUID" },
                { "$ref": "#/definitions/nfs" },
                { "$ref": "#/definitions/tmpfs" }
            ]
        }
    }
````

**Comment by webron** [comment]
There's no support for `oneOf` in Swagger in general. It's just not part of the spec.

**Comment by toaster33** [comment]
Yah, I was not clear on that exactly since I know the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object) refers to being JSON schema draft 4 compliant.  But after re-reading this again it does mention subset.

**Comment by webron** [comment]
I guess we can close this one for now then. There are reasons why we don't support oneOf, but that discussion belongs to the swagger-spec repository. If you'd like to suggest future support for it, feel free to open an issue there.

**Comment by magnushiie** [comment]
Now that the spec v3 includes oneOf - should this issue be reopened?

**Comment by glebmachine** [comment]
@webron it's time to reopen, huh?)

**Comment by cbornet** [comment]
I think the codegen will have a hard time supporting oneOf. When you get JSON data, how do you choose the model into which you deserialize ? If you’re serious about your API, don’t use oneOf.

**Comment by glebmachine** [comment]
I'm not sure about, but, it's common.

for example, we have web page content, based on components, like:

- wysiwyg
- video
- photogallery
- wysywig (again)
- feedback form.

so, data structure will be like:
```js
{
  ....
  content: [
    {
      type: 'html',
      raw: '<h1>hello world',
    },
    {
      type: 'video'
      youtubeLink: 'youtube.com/XXX'
    },
    {
      type: 'photogallery',
      photos: [
        'link one',
        'link two',
        'link three',
      ]
    }
    {
      type: 'html',
      raw: 'looks reasonable, right?',
    },
    {
      type: 'form',
      fields: [...]
    }
  ]
}
```

And typings looks like: 
```ts 
interface Page {
  ...
  content: WysywigContent | VideoContent | PhotoGalleryContent | FormContent
}
```

**Comment by cbornet** [comment]
Oh, I hadn’t read OAS3 fully ! If you have oneOf + discriminator (here : discriminator=type) then OK, it’s useful. OneOf without discriminator remains a bad idea.

**Comment by glebmachine** [comment]
Yes, thanks. 
If you would like, i can help you with Angular/typescript template.

**Comment by cbornet** [comment]
Also note that to be able to generate in strongly typed languages such as JAVA, you also need each element of the oneOf to inherit from a common parent (with allOf). See the last example of discriminator in OAS3. So that’s a lot of things to consider when using oneOf.
