### ISSUE TITLE
How can I create sdk based on sources, not url

### ISSUE THREAD

**Issue by egormasalitin** [swagger-api/swagger-codegen#4884]
Can I generate SDK based on API sources, not url?

**Comment by wing328** [comment]
You mean from a local file? Yes and here is an example:
```
   java  -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i ~/Downloads/swagger_enum_test_yaml.txt \
  -l java \
  -o /var/tmp/swagger_enum_test_yaml/
```

**Comment by egormasalitin** [comment]
@wing328 No, I mean local sources, for example I have api-service with swagger, ok, but how can I generate sdk using just sources (without starting service).

**Comment by wing328** [comment]
@egormasalitin there are plug-ins to generate Swagger/OpenAPI spec from annotation in the code. Is that what you're looking for?

**Comment by egormasalitin** [comment]
@wing328 Am I'm wrong, but for swagger spec generation I have to start service? Or you mean that I can generate spec to file (for example via gradle task, without service start) and then using this file, generate sdk?

**Comment by wing328** [comment]
@egormasalitin I think you're right. Likely you need to start the service, e.g. https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#using-swaggers-servlet-in-the-webxml

**Comment by egormasalitin** [comment]
@wing328 Yes, we are using swagger for 2 years already, but it is really bad that we should start service, because it means that we cannot create simple jenkis job to build sdk based on latest sources, we have to start service in this job, and then generate sdk based on it.

Am I right? There is no way do do it without service start?

Second question, can I pass url to sdk as generator parameter? Or It will always use url, which spec provide?

Thank you.

**Comment by egormasalitin** [comment]
@wing328 for example I'll start service in docker but I want to use this specs with url to production, is it possible without changing host file?

**Comment by wing328** [comment]
Most API clients (SDKs) support changing the host (API backend) at runtime. Would that meet your requirement?

Or you can download swagger.json and update the file locally before using swagger codegen to generate code for you.

**Comment by egormasalitin** [comment]
@wing328 first one doesn't, but I can try second one too, thank you.
