### ISSUE TITLE
[GO] generated golang client leaks file descriptors 

### ISSUE THREAD

**Issue by iamsamwood** [swagger-api/swagger-codegen#4899]
##### Description

The go client that is generated creates a new resty client per connection which is never closed. This results in a file descriptor leak. 

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

This applies to all generated go client code. 

##### Steps to reproduce

Generate any go client. 

##### Related issues

None.

##### Suggest a Fix

Short term: Add the following line to prepareClient() in: resources/go/api_client.mustache

`rClient.SetCloseConnection(true)`

Long term: Change resty to reuse http clients.

**Comment by antihax** [comment]
#5037 resolves this.

**Comment by wing328** [comment]
@iamsamwood please pull the latest 2.3.0 and build the JAR locally to give the fix a try.
