### ISSUE TITLE
Python generator: wrong deserialize when model holds another model as attribute

### ISSUE THREAD

**Issue by kiss2110** [swagger-api/swagger-codegen#490]
When deserialization of a attr in model X is type of another model Y, swagger deserialize it as same model (Y deserialzed as model X)
The fix should be in deserialize(self, obj, objClass) function:
Instead of:                  setattr(instance, attr, self.deserialize(value, objClass))
should be:                  setattr(instance, attr, self.deserialize(value, attrType))

**Comment by webron** [comment]
@wing328 - I think you've done a lot of work on the Python generator. Any chance you can have a look at this?

**Comment by geekerzp** [comment]
@kiss2110 It has been fixed in develop 2.0.
https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/python/swagger.mustache#L248
Please try again in develop2.0 branch.

**Comment by wing328** [comment]
@webron As @geekerzp has pointed out that the fix is already in the develop_2.0. I would defer to @kiss2110 to confirm.

**Comment by webron** [comment]
@wing328 - thanks, that's why I added the `Awaiting feedback` label :)

**Comment by webron** [comment]
@kiss2110 - I assume it's fine now?

**Comment by kiss2110** [comment]
yap :)

**Comment by pambeard** [comment]
Is this fix in the cli version of the codegen tool?  It is not working for me.
Reservation:
      type: object
      properties:
        taskId:
          $ref: "#/definitions/TaskId"
        startTime:
          type: string
          format: date-time
 TaskId:
         type: string

When the object is returned, startTime is parsed correctly, TaskId is an empty object.  Both TaskId and startTime are in the tuple correctly but are not deserialed (__deserialize_model) correctly

**Comment by wing328** [comment]
@pambeard it should be fixed and we've a test case to cover it: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/tests/test_pet_api.py#L72

Please make sure you're using the latest stable version (or master) and also verify that your swagger model definition correctly describes the model (JSON).

**Comment by pambeard** [comment]
It seems to work when the included model has more than one property, but fails when the included model only has one property.  If you are using the same pet store definition that you can download from the site, I don’t see where that test case was covered.

Thanks,
Pam

**Comment by wing328** [comment]
@pambeard the example you provided has 3 properties:
```
taskId:
startTime:
TaskId:
```
and `taskId`, `TaskId` are essential the same when defining as Python property. I would suggest you to revise the definition of your model as most deserialisation issue I've seen has to do with incorrect definition.
