### ISSUE TITLE
Stray comma in model listing when using list markdown

### ISSUE THREAD

**Issue by pauldzy** [swagger-api/swagger-codegen#4905]
##### Description

When a swagger definition description includes a markdown list, a stray comma appears at the end of the description.  This can be seen here 
http://petstore.swagger.io/?url=https://api.swaggerhub.com/apis/pauldzy/StrayComma/1.0.0
under the inventory model name definition.   It is also visible on SwaggerHub interface in the same place.

Apologies if this is nitpicky.

##### Swagger-codegen version

version v2.2.10

##### Steps to reproduce

http://petstore.swagger.io/?url=https://api.swaggerhub.com/apis/pauldzy/StrayComma/1.0.0

##### Related issues

I could not find anything similar in the swagger-codegen issues. 

Thanks,
Paul

**Comment by wing328** [comment]
@pauldzy is this a swagger-ui issue? If yes, please open the issue via https://github.com/swagger-api/swagger-ui/issues/new instead.

**Comment by pauldzy** [comment]
Apologies, am moving now.

Thanks.
