### ISSUE TITLE
Use sdk send requests to url with two slashes

### ISSUE THREAD

**Issue by egormasalitin** [swagger-api/swagger-codegen#4906]
##### Description
SDK which codegen generates use use url like `http://some.url.com//create` but it should be `http://some.url.com/create` it happens because baseUrl is '/' and createUrl is '/create'. You should avoid double slashes in code. Problem is in `io.swagger.client.ApiClient#buildUrl` For example now our swagger version `io.springfox:springfox-swagger2:2.5.0` generates config with `basePath="/"`, and endpoint with `/create` as a result it becomes `{url}//create`

##### Swagger-codegen version

`io.swagger:swagger-codegen-cli:2.2.1`

##### Swagger declaration file content or url

Sorry, it is private

##### Command line used for generation

`-i {URL} -l java`

##### Steps to reproduce

1. Generate SDK

##### Suggest a Fix

Avoid double slashes in `io.swagger.client.ApiClient#buildUrl` 
```
url.append(this.basePath).append(path);
```

**Comment by wing328** [comment]
@egormasalitin thanks for reporting the issue. Can you try the latest version 2.2.2 (released last week) to see if the issue still occurs?

**Comment by egormasalitin** [comment]
@wing328 I just checked 2.2.2, same behavior.

**Comment by wing328** [comment]
In your spec, is there by any chance the `host` (e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L12) attribute contains an ending slash?

I'll try to reproduce the issue in my end as well.

**Comment by egormasalitin** [comment]
@wing328 I know I get the problem. If base path is empty, it ends on slash, and it creates a problem. How do you suggest to fix it?
![image](https://cloud.githubusercontent.com/assets/6221420/23611995/33d6db66-0282-11e7-91fe-f6d16541e252.png)

**Comment by wing328** [comment]
What about removing basePath (which is not required)?

I did a test and it seems to work for me.

**Comment by egormasalitin** [comment]
@wing328 it was set by default, how to set it as null?

**Comment by wing328** [comment]
I simply remove this line: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L13

**Comment by egormasalitin** [comment]
@wing328 I can't, It is generated by swagger using sources, it should be dynamic, that's the problem

**Comment by wing328** [comment]
IMO, the source should be updated to remove the basePath.

As a workaround, download the spec to your local drive and update it, then use the same -i argument for the local file (e.g. /var/tmp/swagger.yaml) to generate the Java API client.

**Comment by egormasalitin** [comment]
@wing328 Thanks, I'll update swagger version and check it, than I'll update you.
About your suggestion:
1. Yes, I know that we can do it, but I think it is bad to work with generator using such workaroud
2. I think that it should be fixed on generator side, because system should work even if `basePath='/'`
What do you think?

**Comment by wing328** [comment]
Yup, I agree the generator should be smart enough to remove ending "//" with "/" in the base URL.

Would you have time to contribute the enhancement? If yes, I can show you a good starting point.

**Comment by egormasalitin** [comment]
@wing328 I have time for it. Please tell me where I should change java behavior.

**Comment by wing328** [comment]
I think we can change the following line:

https://github.com/swagger-api/swagger-codegen/blob/7df1f8e2006a824a30ad2f665cc076b3c1c653d0/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L83

to make sure basePath does not equal to "/" before appending the base path.

**Comment by egormasalitin** [comment]
@wing328 It is 30m already since I cannot find publish to local maven task :) I did changes locally, but which task performs deploy to local maven (in order to test it locally)?

**Comment by wing328** [comment]
`mvn clean install` will install the package (version 2.2.3-SNAPSHOT) to the local maven store

**Comment by egormasalitin** [comment]
@wing328 I cannot push to feature branch, how can I create a pull request?

**Comment by wing328** [comment]
You will need to first folk this repo and then make the change in your folked repo in which you've permission to push the branch.

**Comment by egormasalitin** [comment]
@wing328, ok, one sec

**Comment by wing328** [comment]
Closed via #4906

**Comment by egormasalitin** [comment]
@wing328 Thanks a lot for your help 👍

**Comment by wing328** [comment]
@egormasalitin no problem. If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen)

**Comment by egormasalitin** [comment]
@wing328 I'll ask our managers
