### ISSUE TITLE
[Jaxrs-cxf] Update to swagger-core-version 1.5.12 causes compile errors

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4924]
##### Description

The update to swagger-core-version 1.5.12 in pom.mustache for CXF:
<swagger-core-version>1.5.12</swagger-core-version>

causes compile errors for newly generated samples.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url
petstore-with-fake-endpoints-models-for-testing.yaml

##### Command line used for generation
see jaxrs-cxf-petstore-server.sh

##### Steps to reproduce
remove pom.xml before generating to samples/server/petstore/jaxrs-cxf

##### Suggest a Fix

The dependencies of swagger-core 1.5.12 have joda and jackson dependencies removed, so they need to be added additionally.

Applies to:
- [x] cxf server see PR #4925 
- [x] cxf client see PR #5032

**Comment by jfiala** [comment]
@fehguy commit 894f272 broke this, pls make sure to delete pom.xml before updating the samples or upvote my suggestion #4087 to add unittests to make sure samples are not out of date.

**Comment by fehguy** [comment]
thanks @jfiala

**Comment by jfiala** [comment]
The pom.xml for language jaxrs-cxf is now updated to 1.5.15 and compliles OK.
