### ISSUE TITLE
static html generate includes incorrect license and description of api_key, references to Reverb

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-codegen#493]
See #492 for an example.
The default HTML if the input swagger.json does not describe a license inserts the Apache Software License 2.0 (which is not a correct assumption). 

*http://apache.org/licenses/LICENSE-2.0.html*

The html also contains

*Access to the API requires an api key to be provided by our Partner for all requests. The api key is passed as a header with the name `api_key` and the value provided by Reverb Technologies, Inc. Unless otherwise agreed upon, access to the Reverb API is intended solely for usage by our Partner and not third parties.*

which should not be the default either.

**Comment by Nathan-Smith** [comment]
:+1:

**Comment by fehguy** [comment]
Please send a pull request with updated, general language.  Remember, these templates are a starting point for your own.

**Comment by fehguy** [comment]
I've removed Reverb from the description, but the templates are really meant to be modified for your purposes.
