### ISSUE TITLE
README.md swagger-codegen-cli incorrect direct download link

### ISSUE THREAD

**Issue by josiahpeters** [swagger-api/swagger-codegen#4944]
##### Description

The download link for swagger-codegen-cli jar directly from Maven does not point to the latest version

##### Swagger-codegen version

2.2.2

##### Suggest a Fix

I will be opening a PR to update the README.md to point to the correct download link: http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.2/swagger-codegen-cli-2.2.2.jar

**Comment by wing328** [comment]
Thanks for the PR. Issue closed.
