### ISSUE TITLE
Missing codegen-cli docker image in registry

### ISSUE THREAD

**Issue by danbeaulieu** [swagger-api/swagger-codegen#4947]
##### Description

The README calls out an image swagger-api/swagger-codegen but that image does not exist. The image swaggerapi/swagger-codegen-cli does "exist" on docker hub, but there aren't any actual images pushed to it: https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/

##### Swagger-codegen version

latest Docker image.

##### Swagger declaration file content or url

NA

##### Command line used for generation

From README:
docker run --rm -v ${PWD}:/local swagger-api/swagger-codegen generate \
    -i http://petstore.swagger.io/v2/swagger.json \
    -l go \
    -o /local/out/go

Or according to docker hub: 
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
    -i http://petstore.swagger.io/v2/swagger.json \
    -l go \
    -o /local/out/go

##### Steps to reproduce

Run above docker commands

##### Suggest a Fix

Need to at least push an image to docker hub and possibly/probably update the README/Docs.

**Comment by arnested** [comment]
See #4912. I will add the changes to the readme over there.

Thank you for noticing and reporting this!

**Comment by arnested** [comment]
The README has been corrected now and an image has been pushed to Docker Hub now (`latest` -- future releases will be pushed with their release tag as well).
