### ISSUE TITLE
[Swift] Alamofire.Manager instances created without a ServerTrustPolicyManager

### ISSUE THREAD

**Issue by JakePayton** [swagger-api/swagger-codegen#4948]
##### Description

Generated swaggers don't seem to allow for ServerTrustPolicyManager to be defined for Alamofire.Manager instances.  This is a requirement to being able to implement SSL certificate pinning 

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

AlamofireImplementations.swift

```swift
override func execute(completion: (response: Response<T>?, error: ErrorType?) -> Void) {
        let managerId = NSUUID().UUIDString
        // Create a new manager for each request to customize its request header
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = buildHeaders()
        let manager = Alamofire.Manager(configuration: configuration)
        managerStore[managerId] = manager

        let encoding = isBody ? Alamofire.ParameterEncoding.JSON : Alamofire.ParameterEncoding.URL
```

##### Command line used for generation

swagger-codegen generate -i swagger.json -l swift -o ~/swagger-client/

##### Steps to reproduce

Use the API client created by swagger-codegen, note that there is not an ability to set a ServerTrustPolicyManager when AF Managers are being created for making requests.  

```swift
        let manager = Alamofire.Manager(configuration: configuration)
        managerStore[managerId] = manager
```

##### Suggest a Fix

Would like a way to define a ServerTrustPolicyManager to be used for requests

**Comment by wing328** [comment]
@JakePayton please use v2.2.2 (released a few days ago) to give it a try.

**Comment by wing328** [comment]
v2.2.3 has been released. Closing this as there's no update.

You may want to try the latest master (2.3.0), which contains a lot of enhancements and bug fixes for swift and swift3
