### ISSUE TITLE
[Java*] Joda can't seem to handle all iso8601 dates

### ISSUE THREAD

**Issue by ryanackley** [swagger-api/swagger-codegen#4950]
##### Description
Getting an exception on certain dates. Switching to legacy fixes the client. 

java.lang.IllegalArgumentException: Invalid format: "2017-03-01T07:00:00Z" is malformed at "Z"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
	

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url

N/A since it's data specific

##### Command line used for generation

using maven plugin

##### Steps to reproduce

Have your REST endpoint return "2017-03-01T07:00:00Z" for a date, watch Java client crash.

##### Related issues

not sure

##### Suggest a Fix

Use a different default Java date library or change the way it's serializing the JSON so it doesn't crash.

**Comment by wing328** [comment]
@ryanackley please try the latest version 2.2.2, which was released a few days ago.

**Comment by ePaul** [comment]
@ryanackley An example swagger.yaml (possibly the official petstore one, if it has a date-time field in a response), the settings you use to generate your client, and an example JSON result would still be helpful for others to reproduce this.

**Comment by wing328** [comment]
Closing this as there's no update.
