### ISSUE TITLE
Make Controller constructor public in spring mvc generator

### ISSUE THREAD

**Issue by pablo-ml** [swagger-api/swagger-codegen#4968]
##### Description

I am using swagger codegen with the delegatePattern option. I want to manually create the swagger generated controller in the spring configuration file and inject its delegate, instead of letting spring scan for controllers and autowire the delegate. The problem is that the generated constructor is package access.

##### Swagger-codegen version

This happened in 2.2.2.

##### Suggest a Fix

Simpy add public to the generated Controllers constructor.

**Comment by pablograna** [comment]
Created PR #4972
