### ISSUE TITLE
[typescript-angular2] client handling of date-time format results in TS2339 compiler errors

### ISSUE THREAD

**Issue by kernwig** [swagger-api/swagger-codegen#4969]
##### Description

Any API parameter defined as `"type":"string","format":"date-time"` results in typescript code full of TS2339 errors.
```javascript
            if(startDate instanceof Date) {
                queryParameters.set('startDate', <any>startDate.d.toISOString());
            else {
                queryParameters.set('startDate', <any>startDate);
            }
```
The if condition is an error, as `startDate` (in this example) is already a function parameter of type `Date`, so the check is redundant and, annoyingly, reported as an error.

Secondly, `<any>startDate.d.toISOString()` does not compile. There is no 'd' field in Date. Changing it to `(<any>startDate).d.toISOString()` will compile, but of course fail at runtime.

##### Swagger-codegen version

2.2.2

##### Command line used for generation

`swagger-codegen generate -i <uri> -l typescript-angular2 -o src/app/core/backend`

##### Related issues

Probably #3105 

##### Suggest a Fix

I worked around the problem by:

1. In TypeScriptAngular2ClientCodegen, set the typeMapping of Date to string.
2. In typescript-angular2/api.mustache, commenting out most of the above block of code, leaving only the else statement.

I then manage the ISO date strings myself.

**Comment by wing328** [comment]
Can you please try the `2.3.0` branch to see if the issue still occurs?

`2.3.0` branch contains enhancements, bug fixes that are not backward compatible.

**Comment by kernwig** [comment]
I switched to the 2.3.0 source branch. It's better, but still unusable.

date-time API parameters still translate to Javascript Date objects, which then is passed to the API simply by calling Date.toString(), which is not of a format any server would accept. Example of a resulting query string:

`?startDate=Wed%20Mar%2001%202017%2000:00:00%20GMT-0800%20(PST)&endDate=Fri%20Mar%2031%202017%2000:00:00%20GMT-0700%20(PDT)`

**Comment by kernwig** [comment]
Fixed by #4812.

**Comment by HDaghash** [comment]
Hey guys , how to generate lib from this branch 2.3.0 so i can use it before release time

**Comment by wing328** [comment]
@HDaghash please try the following:
```
git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
git checkout 2.3.0
mvn clean package
```

**Comment by HDaghash** [comment]
many thanks @wing328 
i already did that but where can i found the generated package to use it in angular2 / typescript .

i need the same folder like when i do npm install  swagger-codegen

Thank you !

**Comment by kernwig** [comment]
@HDaghash  Here's an example of how I use my locally compiled version, run from a parallel directory:

`java -jar ../swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.json -l typescript-angular2 -c config/swagger.json -o src/app/api`

**Comment by HDaghash** [comment]
Thank you @kernwig for the fast response 

what i meant here if i install the npm package for swagger i will use this command :

ex : swagger-codegen generate -i address.yaml -l typescript-angular2 -o .

how can i generate a package to replace it in my node_moduls instead of waiting the next release

your help is highly appreciated .

**Comment by HDaghash** [comment]
Thank you guys  
it's seems the one on npm not official , but it very nice to have one 👍 

Thanks for the support .
