### ISSUE TITLE
Compile fails with Java 8 due to Scala 2.10

### ISSUE THREAD

**Issue by burmanm** [swagger-api/swagger-codegen#497]
When trying to compile with Java 8, the compilation fails on swagger-generator:

[INFO] Compiling 1 source files to /home/miburman/projects/git/swagger-codegen/modules/swagger-generator/target/test-classes at 1426248936536
[ERROR] error: error while loading CharSequence, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
[ERROR] error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[INFO] (class java.lang.RuntimeException/bad constant pool tag 18 at byte 76)
[ERROR] two errors found

This can at least be fixed by changing swagger-generator/pom.xml scala-test_2.10 -> scala-test_2.11 and scala.version from 2.10.0 to 2.11.0, but that generates some warnings on the compile (multiple Scala versions). However, as a workaround it works.

**Comment by fehguy** [comment]
This is master or develop_2.0?  Going to 2.10.4 solves it as well

**Comment by burmanm** [comment]
master

**Comment by mlasak** [comment]
Thanks @burmanm your hint worked for me. Can successfully build master now. Ibtw, i've spotted multiple declarations of the scala-version in the project root pom.xml [there](https://github.com/swagger-api/swagger-codegen/blob/4bd227271aad52f014fc29f069ab5a207ae3b277/pom.xml#L351) and [there](https://github.com/swagger-api/swagger-codegen/blob/4bd227271aad52f014fc29f069ab5a207ae3b277/pom.xml#L362). Having a strong feeling that this cannot be intended...

**Comment by fehguy** [comment]
This should be fixed now, also removed the scala version.
