### ISSUE TITLE
Swagger Node Port -

### ISSUE THREAD

**Issue by jspears** [swagger-api/swagger-codegen#4981]
I recently ported Swagger Codegen v2.2.1 to javascript, and I would like to make sure I credit swagger appropriately.  Please let me know what other than a copyright and keeping Apache-2 license is necessary. 

[gen-swagger](https://github.com/jspears/gen-swagger)

I know this may not be the right forum, but given it a shot

Thanks for the project and all the work gone into it.

**Comment by ePaul** [comment]
> I recently ported Swagger Codegen v2.2.1 to javascript

Just out of curiosity, what was the reason to do so?

**Comment by fehguy** [comment]
@jspears might want to chime in here with your thoughts...

https://github.com/swagger-api/swagger-codegen/issues/3948

**Comment by jspears** [comment]
@ePaul well my project does not have a jdk or java dependency, so i didn't want to add one.  Add i need to add a non-http transport, so I figured might as well do it in JS.

**Comment by wing328** [comment]
@jspears if you do not want Java dependency installed, you can also use https://generator.swagger.io or Docker to generate code. More info can be found in README.md
