### ISSUE TITLE
Python API client refactoring

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#4986]
##### Description

Currently, Python API client is singleton and we want to move away from singleton in Python to configuration per instance of API client similar to what we've done to Ruby, PHP, C#, etc.

##### Swagger-codegen version

Latest matser

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/4240

##### Suggest a Fix

If anyone from the community wants to work on this enhancement, please reply to let us know.

**Comment by baartosz** [comment]
I can give it a shot but I will need someone to review it carefully as I am not doing much python besides simple cli scripts.

**Comment by wing328** [comment]
Closed via #5012. Thanks for the contribution by @baartosz

**Comment by taxpon** [comment]
@wing328 This issue can be closed.

**Comment by wing328** [comment]
@taxpon thx for the reminder.
