### ISSUE TITLE
Can i make by model classes extends from a base class

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [swagger-api/swagger-codegen#4988]
##### Description

I want the Swagger generated classes to extend from a base class.  Is there way i can say to swagger-codegen to implement this ??

##### Swagger-codegen version

swagger-codegen version : 2.2.1

##### Swagger declaration file content or url

    ```yaml
paths:
   /pet:
    get:
      description: pet
      tags:
        - pet
      responses:
        '200':
          description: got response ok
          schema:
            $ref: '#/definitions/PetTO'
definitions:
  PetTO:
    type: object
    properties:
      id:
        type: string
        description: pet id
  BaseTO:
      type: object
      properties:      
        petName:
           type: string
           description: pet name
    ```
    (for YAML code) or
   -->

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i pet.yml   -l java --library=okhttp-gson 
										     -o generated_source_code 
										    -c package_config.json

=> With the above Yaml, Swagger-codegen will generate a PetTO class and BaseTO class. what to specify in yaml so that my PetTO class will extends from BaseTO class.

**Comment by ePaul** [comment]
(Just a formatting hint: Please don't indent the

    ```
around your code, otherwise they are interpreted as part of the code.)

You could try to define your PetTO as this:

```yaml
definitions:
  PetTO:
  allOf:
    - $ref: '#/definitions/BaseTO'
    - type: object
      properties:
        id:
          type: string
          description: pet id
```

I don't know what the current state of the language's implementation of this is, though.
