### ISSUE TITLE
5k!

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#5000]

**Comment by ponelat** [comment]
![over-4999](https://cloud.githubusercontent.com/assets/8438485/23786625/cb621e2c-0576-11e7-8ba0-1c745bb055be.jpg)

**Comment by ePaul** [comment]
We could have got a meaningful issue or PR with this nice number, but no :-(

**Comment by wing328** [comment]
:tada: :confetti_ball: :tada: :confetti_ball: :tada: :confetti_ball:

**Comment by webron** [comment]
@ePaul - celebrations are meaningful too ;)
