### ISSUE TITLE
[Java][Play] Enhancements to the Play generators

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5003]
##### Description

Here is a list of enhancements:

- Change `bin/java-play-framework-petstore-server.sh` to "executable" (`chmod a+x bin/java-play-framework-petstore-server.sh`)
- Run `bin/java-play-framework-petstore-server.sh` to generate Petstore sample and add the files to this project.
- Test Petstore play server code in Travis CI
- Remove dependency on Swagger-Play
- Update README with more information ([example](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/README.mustache))

Please reply to this if anyone has other feedbacks/suggestions

##### Swagger-codegen version

Latest master

##### Command line used for generation

`bin/java-play-framework-petstore-server.sh`

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/pull/4943

**Comment by JFCote** [comment]
I will work on the following improvements in the next days/weeks

- [ ]  Make the ControllerImplementor implements an interface as a CLI options. This is helping code generation when in a IDE each time the code is generated. By default, it will be to true.
- [ ] Completely remove swagger-play as a dependency and use the provided json instead of "generating" the json from the annotations.

**Comment by JFCote** [comment]
@wing328 Can you assign me to this issue. I will soon submit PR about this.

**Comment by wing328** [comment]
I cannot assign it to you since Github only allows issue to be assigned to "members" of the project only.

**Comment by JFCote** [comment]
@wing328 : Ok no problem :)

**Comment by wing328** [comment]
Added CI test via https://github.com/swagger-api/swagger-codegen/pull/5130

**Comment by JFCote** [comment]
@wing328 I think this can be closed. I'm pretty sure everything has been done for a long time. Let me know if something is missing.
