### ISSUE TITLE
[QT5 C++] JSON Token authorization problem / setting header

### ISSUE THREAD

**Issue by Kajzer133** [swagger-api/swagger-codegen#5006]
* Version of Swagger: 2.2.2

**Issue**

Problem with json token authorization. I use CakePHP REST Api in project.  The are a lot of tables in our MSSQL database. I want to set header for each by return token from **SWGAuthenticateApi** and pass it in main class, before calling, by variable for example: to object, which method inserts new data to table. Currently I use **request.setRawHeader("Authorization", "here I wrote a token statically")** in SWGHttpRequest.cpp. I want token to be valid only for 2h so I can't write it manually in my application. I know that i can use:

`HttpRequestWorker *worker = new HttpRequestWorker();
HttpRequestInput input(fullPath, "POST");
input.headers.insert("Authorization","");
`

But the problem is that i can't or i don't know how to return token to my main class and add configuration. All functions are **void**, and there is no configuration method too. Is there an option to generate a code in Qt without void functions but with functions that return something? Or maybe there is a way to do it on voids?

In C# Client it looks like:

`IrisCodeResponse result = loginApiInstance.ApiLoginPost(login);
token = result.Data.Token;
token = String.Format("bearer {0}", token);           apiInstance.Configuration.AddDefaultHeader("authorization", token);`

I want to make it similar to this, in QT.

**Comment by wing328** [comment]
@Kajzer133 would the following test case (which executes HTTP GET request) help?

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/qt5cpp/PetStore/PetApiTests.cpp#L66

**Comment by Kajzer133** [comment]
@wing328 sorry for my late feedback, but i had more things to do.

I don't see authorization test in Your example. I think this is only test of post and get. I use **SWGAuthenticateApi** to get JSON Web-authorization token and I am able to Insert new data, but only when I modfiy original classess and I use token statically.

How can I pass the JSON-Web-Token Authorization header to every request? The only solution I find is to edit the generated files but this is not useful in future.

**Comment by fehguy** [comment]
It looks like we didn't expose a method to set headers in the API classes.  I'll see that it's added--the current generated code for setting headers is when they're declared in the operation, not the security definition.

**Comment by SonnyRajagopalan** [comment]
@fehguy Is this the issue I am seeing in https://github.com/swagger-api/swagger-codegen/issues/5188? Any pointers appreciated. I am gating on this, and would like a way forward. Thanks!

**Comment by fehguy** [comment]
@SonnyRajagopalan yes that's right.  I'll be working on this now, sorry for the delay.

**Comment by stmeyer** [comment]
@fehguy Any news to this bug?

**Comment by stmeyer** [comment]
@fehguy do you know if this will be fixed in 2.2.3 or 2.3.0?

**Comment by fehguy** [comment]
I'm really sorry about lagging.  Honestly my QT got really rusty, but now it's back :)

I have the fix (it's literally 3 lines) and will try to get it in the 2.2.3 which was delayed today for other reasons.  Maybe it's cosmic and I need to fix this first!
