### ISSUE TITLE
[Java] Large download stream progress

### ISSUE THREAD

**Issue by jdupouy** [swagger-api/swagger-codegen#5007]
##### Description

We would like to show the progress when downloading a file from a server. To do se we would need to access the input stream of the request body.

##### Swagger-codegen version

We are using the last version from the repository 2.2.3-SNAPSHOT (building from source).

##### Suggest a Fix

Make method [`private com.squareup.okhttp.Call {{operationId}}Call`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache#L67) public in [Java/libraries/okhttp-gson/api.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache).

**Comment by wing328** [comment]
Closed via #5010
