### ISSUE TITLE
If my response has a key with a hyphen character, swagger generates properties with invalid identifiers

### ISSUE THREAD

**Issue by jirkadanek** [swagger-api/swagger-codegen#503]
My schema:

        /users/show:
            get:
            parameters:
                - name: username
                in: query
                description: Username of the user.
                required: true
                type: string
            responses:
                200:
                schema:
                    $ref: '#/definitions/User'

        definitions:
          User:
            properties:
            "change-design":
                type: boolean

Then in the generated binding code I see definitions like

    ./main/java/io/swagger/client/model/User.java:  public void setChange-design(Boolean change-design) {

That is, there is a hyphen. Hyphen is not a valid character in identifiers in most programming languages. As far as I know, hyphen works only in lisps.

I tested this with Python, Java and Scala codegen. Happens in all those languages. I suggest that the specification should be amended with a new property that would allow me to specify a new name for the parameter using only A-Za.z_ characters.

**Comment by fehguy** [comment]
The pattern for fixing this is has been committed for java.  It needs to be applied to other languages, and in broader context.

**Comment by jirkadanek** [comment]
I guess replacing the hyphen with an underscore is good too. ;)
