### ISSUE TITLE
PHP get only class name for import model 

### ISSUE THREAD

**Issue by archana27m** [swagger-api/swagger-codegen#5059]
##### Description

I would like to get only class name or file name with {{#imports}}use {{import}};
{{/imports}} rather than getting fully qualified namespaced classname.
Is there any param/variable which can be used in this case?

##### Swagger-codegen version

V 2.1.5

##### Steps to reproduce

namespace {{modelPackage}};

{{#imports}}use {{import}};
{{/imports}} 

using above code I am getting models which should be imported as "use MyApp/Model/Hello"
is there anyway I can get only class name and I can use my custom namespace like "use MyWorld/Hello"?

**Comment by wing328** [comment]
> V 2.1.5

That's a very old version. Please try the latest version 2.2.2.

The latest PHP model does not use {{imports}}

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/model.mustache

**Comment by wing328** [comment]
Closing this as there's no update.
