### ISSUE TITLE
[TS][Angular2] support for collection formats

### ISSUE THREAD

**Issue by kernwig** [swagger-api/swagger-codegen#5062]
##### Description

The feature/bug fix in #4539 and #4531 was made to v2.2.2, but is not present in v2.3.0.

##### Swagger-codegen version

Regression in v2.3.0.

##### Related issues

Regression of #4539

**Comment by wing328** [comment]
@kernwig we're trying to sync master to 2.3.0 via #5072, #5079 

We might need your help to review later due to merge conflicts in the TS generators or templates.

**Comment by kernwig** [comment]
Post-merge, it _looks_ like the regression of #4539 is fixed, but the Date bugs reported under #4969 are back. I will once again modify my working copy, and then will be able to confirm this regression is fixed.

**Comment by kernwig** [comment]
Post-merge, api.ts has added an `export const APIS`, trying to export services that were not imported. I think this is an obsolete line from the v2.2 branch. Simply removing it allows for successful compilation.

**Comment by kernwig** [comment]
Confirmed that the #4539 regression is resolved.

Leaving this issue open to track api.ts regression.

**Comment by wing328** [comment]
Closing this. If it's still an issue, please reply to let us know.
