### ISSUE TITLE
[charp-client] import-mappings doesn't work with csharp

### ISSUE THREAD

**Issue by iamkarlson** [swagger-api/swagger-codegen#5086]
##### Description
this is script for calling codegen
java.exe -jar $swaggerJar generate -i $swaggerJsonUrl -l csharp -o $outputFolder -c $config -t $templates --import-mappings AccountStateViewModel=Contracts.Results.AccountTopup

I have my server model in the separated nuget package, and I'm trying to reuse them.
##### Swagger-codegen version

last commit from master

**Comment by wing328** [comment]
@iamkarlson we need a fix similar to https://github.com/swagger-api/swagger-codegen/pull/5373

Would you have time to contribute the fix?

**Comment by iamkarlson** [comment]
give me some time, maybe the upcoming week I will have time. i'm not sure

**Comment by wing328** [comment]
@iamkarlson let us know if you need any help with the PR.

(we just released v2.2.3 so please pull the latest master before working on the enhancement)

**Comment by iamkarlson** [comment]
Hi @wing328 . I don't need any help but need some time. busy at work and difficult to find an empty slot

**Comment by wing328** [comment]
@iamkarlson no problem :)

**Comment by wing328** [comment]
Closed via #6155. Thanks for your contribution.
