### ISSUE TITLE
[Haskell] Generated Petstore sample is broken, doesn't compile

### ISSUE THREAD

**Issue by mandrean** [swagger-api/swagger-codegen#5096]
##### Description

The petstore sample client/server generated using `./bin/haskell-servant-petstore.sh` is broken and doesn't even compile.

It has numerous issues:

* `\` and `"` specialCharReplacements need to be escaped twice, once for Java and once for Haskell, otherwise the [specialchars list](https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/haskell-servant/lib/SwaggerPetstore/Types.hs#L115) will not compile. This is a regression bug caused by the `specialCharReplacements` hashmap in `DefaultCodegen.java` being extended with more special chars in this commit: https://github.com/swagger-api/swagger-codegen/commit/7a245e31894c30a050e59cffefb97739005c0013
* The [lookupEither](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/haskell-servant/API.mustache#L58) return type (`Either Text b`) doesn't pattern-match with [fromFormUrlEncoded](https://hackage.haskell.org/package/servant-0.6/docs/Servant-API-ContentTypes.html#t:FromFormUrlEncoded) (`Either String b`)
* [Lots of dead legacy Petstore sample code left](https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/haskell-servant) from the old solution before it was refactored in #2322

##### Swagger-codegen version

`v2.2.2` or latest `master`, doesn't matter.

##### Steps to reproduce

0) `git clone https://github.com/swagger-api/swagger-codegen && cd swagger-codegen`
1) `git checkout origin master && git pull origin master --rebase`
2) `mvn clean package`
3) `sh ./bin/haskell-servant-petstore.sh`
2) `cd samples/server/petstore/haskell-servant`
3) `stack install`

**Comment by wing328** [comment]
Closed via #5097 

Thanks for the PR.
