### ISSUE TITLE
[TypeScript] Generators (node, fetch, angular, angular2, jquery) refactoring

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5104]
##### Description

We want to refactor/consolidate all Typescript generators (node, fetch, angular, angular2, jquery) into one single `typescript` generator and support node, fetch, angular, angular2, jquery via the `library` option. 

The goal is to reuse templates (e.g. model) if possible and for easier maintenance/support.

##### Swagger-codegen version

2.3.0 (since it's breaking change)

##### Suggest a Fix

- put the templates under `typescript/{name}`
- put shared templates under `typescript/common` and reuse if possible

If anyone has feedback or wants to work on this, please reply to let us know.

**Comment by bherila** [comment]
@wing328 I am worried the template for this will become too complex/unwieldy, I already feel like editing the mustache templates is mind bending :-o

Also, I'm having buyers remorse about my own investment in the jquery library. Since I end up consuming the Typescript from multiple places (React Native, Node, and Client side) I am considering writing *yet another one* that uses just regular XmlHttpRequest. 

How do folks feel about deprecating lots of these in favor of `XmlHttpRequest`? I don't have time right now but I wouldn't mind putting it up on Freelancer.com or something.

**Comment by mmkal** [comment]
@bherila isn't [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) a better candidate as a lowest common denominator? You should be able to use something like [this](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-fetch/builds/default/api.ts) it for React Native, Node and Client side.

As an aside, I agree that the current TypeScript offerings aren't quite sufficient. Two things I would like from TypeScript are:

* [`express`](https://expressjs.com/en/4x/api.html) types, for a node server. i.e. Interfaces for functions which produce an express middleware, that you can implement. This would make sure that node servers are abiding by their own contracts (and give accurate intellisense etc. while developing).
* React/React PropTypes.

If @wing328's suggestion would make it easier to add those, I would be all for it.

**Comment by wing328** [comment]
@bherila 

> How do folks feel about deprecating lots of these in favor of XMLHttpRequest? 

Based on my experience with other generators (e.g. Java, PHP, C#, etc), there's always a need for another HTTP library since it's unlikely there's one HTTP library that can meet all the requirements.

> I already feel like editing the mustache templates is mind bending :-o

If you don't mind, can you share more on the challenges you faced? Is that due to lack of documentation? no easy way to test the customized templates? or something else?

**Comment by wing328** [comment]
@mmkal thanks for the feedback.

> express types, for a node server. i.e. Interfaces for functions which produce an express middleware, that you can implement

Is your suggestion similar to this one? https://github.com/swagger-api/swagger-codegen/issues/2197

> React/React PropTypes.

Please feel free to open a new "issue" with a bit more details (any example?) and someone from the community might have already started working on it.

My goal about combining TS generators into one is to make it easier to add new features or apply bug fixes across all TS generators (fetch, node, etc) as currently most TS-related PRs only target one of the TS generators and usually the PR owner lacks time to implement the enhancement or bug fixes in the remaining TS generators.

**Comment by bherila** [comment]
I think the biggest challenge with the mustache templates is the lack of editor support, I'm constantly fighting with my editor in terms of indendation and also have trouble keeping track of what context I'm in (especially in loops), and which/when variables are available/not. I think it's a mental block on my part more than anything else. 

The environments that are important to me are Node and Browser. Secondly, it's important that the interfaces from Api proxy -> TS code are also compatible and I would *ideally* like to keep the "Api.ts" generated file in a shared folder and be able to reference it from TS files for Node *or* Browser interchangeably.

**Comment by bherila** [comment]
Also, I'm developing an app for Android and iOS using React Native, so compatibility with that is important.

**Comment by wing328** [comment]
> I think the biggest challenge with the mustache templates is the lack of editor support,

Please join the discussion in https://github.com/swagger-api/swagger-codegen/issues/3950.

The latest proposal is to support HandleBars

**Comment by wing328** [comment]
> Also, I'm developing an app for Android and iOS using React Native, so compatibility with that is important. That new environment is what's causing me to re-evaluate the whole thing.

My proposed consolidation won't be a breaking change so the auto-generated TS clients should work the same work as before.

**Comment by bherila** [comment]
Love that proposal! 👍

**Comment by bherila** [comment]
@mmkal  you have successfully influenced me and at this point I have now removed all of my dependency on everything except the fetch API. Thank you !!

**Comment by kenisteward** [comment]
@wing328 Let me know when you want to talk more about this.  I have a little under a sprint (til nov 1)  to possibly work on this.

**Comment by wing328** [comment]
@kenisteward Let me email you on this.

**Comment by bherila** [comment]
I will say that I still currently use the typescript-fetch generator and am very happy with it

**Comment by masaeedu** [comment]
@wing328 Might be a good idea to discuss this stuff in a dedicated issue or gitter or something for visibility.

**Comment by wing328** [comment]
@masaeedu you mean opening another issue to discuss the technical details in consolidation?

**Comment by kenisteward** [comment]
To be honest I made this a long time ago when the codegem was very
different. I think this one should probably be closed and then we can
discuss a new issue that woould combine them in their current state.
