### ISSUE TITLE
Update feign version of java client generator (feign library)

### ISSUE THREAD

**Issue by oteichmann** [swagger-api/swagger-codegen#5107]
##### Description

Update Feign to latest version of https://github.com/OpenFeign/feign

##### Swagger-codegen version

2.2.3-SNAPSHOT

##### Swagger declaration file content or url

[swagger-codegen/modules/swagger-codegen/src/main/resources/Java/libraries/feign/pom.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/feign/pom.mustache)

##### Command line used for generation

 ./bin/java-petstore-feign.sh

##### Suggest a Fix

Update dependencies

**Comment by wing328** [comment]
Closed via #5114. Thanks for the PR
