### ISSUE TITLE
Swagger Pet Shop example - TypeScript NodeJS client - issue when populating query string parameters from Array

### ISSUE THREAD

**Issue by prawana-perera** [swagger-api/swagger-codegen#5124]
##### Description

Hi,

I used the Swagger Pet Sop example to generate a TypeScript NodeJS client:
`swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l typescript-node -o ~/swagger-codegen-demo/petstore-typescript-node`.

I am testing against the Swagger PetShop API end points i.e.
`http://petstore.swagger.io/v2/pet/`

The PetShop Swagger doc defines a GET /pet/findByStatus which accepts a status query string parameter. This parameter can be multi valued e.g. status=sold&status=pending. The TypeScript generated has a function:

`findPetsByStatus (status: Array<string>) : Promise<{ response: http.ClientResponse; body: Array<Pet>;  }>`

So to use this API method, the client has to pass in an array of strings. When the call is issued the query string part of URL the call is issued to, seems to get URL encoded e.g.

`http://petstore.swagger.io/v2/pet/findByStatus?status%5B0%5D=sold&status%5B1%5D=pending`

And no results are returned. I checked the generated code, and within the function it has this line:

``` 
if (status !== undefined) {
            queryParameters['status'] = status;
}
```

And `queryParameters` are sent as part of the `request`.

If I hard code the value to say `queryParameters['status'] = 'sold'` it works, and the correct URL is used i.e.

`http://petstore.swagger.io/v2/pet/findByStatus?status=sold`

So it looks like an issue with setting `queryParameters` variable value to the array string passed in.

**Comment by wing328** [comment]
@prawana-perera thanks for reporting the issue (and sorry for late reply). May I know if you've time to contribute a fix? If yes, I can show you some good starting points.

**Comment by prawana-perera** [comment]
Hi @wing328 , yes I would be happy to try contribute a fix. Any guidance will be appreciated.

Thanks.

**Comment by wing328** [comment]
@prawana-perera we've added the ObjectSerializer: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L384

Please pull the latest or use v2.2.3 to give it a try.

If it's still an issue, we'll reopen this.
