### ISSUE TITLE
[Java] Generate ApiClient with SSL configuration

### ISSUE THREAD

**Issue by tainacaetano** [swagger-api/swagger-codegen#5129]
##### Description

I have a service where both the server-side and client-side were generated based on my swagger spec file. In my setup, services should have mutual authentication amongst themselves. As such, the client needs to know configuration related to certificates.

Although I've seen an example that contains a `setSslCaCert` method, I failed to make it work, and couldn't find good examples of its usage. It seems to me that the existing implementation is insufficient for my needs. 

##### Suggest a Fix

I do not have a suggestion on how this would work, but to illustrate what I want to do, this is what I have to configure if I use a jersey HttpClient directly:

```
public Client getClient() {
        SSLContext sslContext = SSLContextLoader.loadSSLContext();
        client = ClientBuilder.newBuilder().sslContext(sslContext).build();
}

private SSLContext loadSSLContext()
            throws IOException, NoSuchAlgorithmException, UnrecoverableKeyException, KeyStoreException,
            KeyManagementException, CertificateException {

        String truststorePath = new File(TRUSTSTORE_PATH).getPath();
        String truststorePassword = SECRET_PASSWORD;
        String keystorePath = new File(KEYSTORE_PATH).getPath();
        String keystorePassword = SECRET_PASSWORD;

        SSLContext sslContext = SSLContexts.custom()
                .loadKeyMaterial(
                        loadJks(keystorePath, keystorePassword, KEY_STORE_TYPE),
                        keystorePassword.toCharArray())
                .loadTrustMaterial(
                        loadJks(truststorePath, truststorePassword, KeyStore.getDefaultType()),
                        new TrustSelfSignedStrategy())
                .build();

        return sslContext;
}

private KeyStore loadJks(String path, String password, String keystoreType) throws IOException,
            NoSuchAlgorithmException, CertificateException, KeyStoreException {

        try (FileInputStream fileInputStream = new FileInputStream(new File(path))) {
            KeyStore keystore = KeyStore.getInstance(keystoreType);
            keystore.load(fileInputStream, password.toCharArray());
            return keystore;
        } catch (IOException | NoSuchAlgorithmException | CertificateException | KeyStoreException e) {
            throw e;
        }
}
```

Ideally, I would like to have the Trust Store and Key Store configuration happening under the hood on the generated ApiClient, based on some configuration on the swagger spec.

Is this, perhaps, already supported and I'm just not finding the right resources to get to it?

Thanks.

**Comment by wing328** [comment]
@tainacaetano so you mean you've included Trust Store and Key Store configuration in the spec somehow and you want the auto-generated Java API client to include these configuration as part of the code generation, right?

**Comment by wing328** [comment]
Closing this as there's no update.
