### ISSUE TITLE
[Java] Methods names uniq in scope of full documentation, not in scope of controller

### ISSUE THREAD

**Issue by egormasalitin** [swagger-api/swagger-codegen#5135]
##### Description

For example we have UserController and CompanyController

`UserController` with method create(`/user`, POST)
`CompanyController` with method create(`/company`, POST)

in this case swagger will generate 2 api classes (`UserControllerApi`, `CompanyControllerApi`), but methods inside will be different, methods will be `createUsingPOST` and `createUsingPOST1` I think that it is wrong, and names should be uniq in scope of Controller, not in scope of full project.

##### Swagger-codegen version

`io.swagger:swagger-codegen-cli:2.2.2`

##### Swagger declaration file content or url

Sorry, I cannot share this information.

##### Command line used for generation

```generate -i http://SOME_URL -l java -o bin/sdk --artifact-id sdk-name```

##### Steps to reproduce

Generate sdk when project has 2 methods with same name.

##### Suggest a Fix

Make it uniq in scope of Controller

What do you think?

**Comment by wing328** [comment]
In your spec, do the operations have a proper `operationId` set? The function/controller name is based on `operationId` defined in the spec.

**Comment by egormasalitin** [comment]
@wing328 Where I can change operationId in api?

**Comment by cbornet** [comment]
The swagger spec requires that the operationId is unique for the whole declaration.

**Comment by egormasalitin** [comment]
But how can I declare `operationId` via annotation? Or the only way is to change method name in java controller?

**Comment by cbornet** [comment]
You can use [@ApiOperation](https://github.com/swagger-api/swagger-core/wiki/Annotations#apioperation) for that

**Comment by egormasalitin** [comment]
But don't you think it could be a problem? For example we have 2 controllers:

A (with `create` `POST` method)
C (with `create` `POST` method)

In this case `operationId` will be `createUsingPOST` for `A` and `createUsingPOST_1` for `C`

Then, for example we will generate java sdk for it, and in this case we will get 2 api classes:
`AApi`, `CApi` for example, with methods `aApi.createUsingPost()` and `cApi.createUsingPost1()`.

Then we publish it to customers, and they starting to use it in their projects.

After one week we decided to add controller `B` with `create` `POST` method, so now `operationId` is `createUsingPOST` for `A`, `createUsingPOST_1` for `B`, `createUsingPOST_2` for `C`

It means that SDK method will be `aApi.createUsingPost()`,`bApi.createUsingPost1()` and `cApi.createUsingPost2()`.

And we cannot publish it for our clients, because it break backward compatibility for them. Because method for cApi now `createUsingPost2` when it was `createUsingPost1`. We didn't change anything in C controller, but it broke BC.

**Comment by egormasalitin** [comment]
@cbornet Which parameter from `@ApiOperation`?  Because now it seems like it take method name + httpMethod name. Thank you.

**Comment by cbornet** [comment]
I think it's `nickname`.
The codegen does it's best to resolve conflicts but of course it can't be perfect.
What could be done is to detect the `operationId` of your input swagger spec and configure the annotation accordingly.

**Comment by cbornet** [comment]
Actually it "must" be done since the swagger spec generated by springfox should be identical to the initial spec.

**Comment by egormasalitin** [comment]
@cbornet I don't think that it should be done via codegen, I just think that it is problem in swagger, and specs shouldn't have _1, _2, _N prefixes, because it could be a problem for SDK, thank you for your answer.

How do you recommend to solve it? Set uniq nickname for each method? Which pattern do you recommend? Should it be like `createFooUsingPost` `getFooUsingGet`? or how?

**Comment by cbornet** [comment]
I really think the codegen should support `operationId` if it's not already the case. This would allow you to set whatever operationId you want for your operations if you're not happy with the default ones.

**Comment by egormasalitin** [comment]
@cbornet @wing328 Thank you a lot
