### ISSUE TITLE
Java codegen - generates class name Collection<Model>.java

### ISSUE THREAD

**Issue by rajeshkamal** [swagger-api/swagger-codegen#514]
Using the swagger springmvc to generate the swagger spec from a Spring REST impementation. 
The Spring REST controller class returns a Collection<Model> Ex:

    @ApiOperation(value = "List all contacts")
    @RequestMapping(value = "/contacts", method = RequestMethod.GET)
    @ResponseStatus(value = HttpStatus.OK)
    public Collection<Contact> list() {
        return contactService.list();
    }

Running the swagger codegen onto the generated swagger spec 1.2(because of swagger springmvc currently only supports 1.2).

Then, changed the Collection<> to List<> and the problem was gone. Just wanted to see if this is a bug.

Lets say if the Spring REST implementation that we have remains the same and we currently use codegen with 1.2 spec. If in future when, swagger springmvc starts producing swagger 2.0 spec. Will the generated code for the model classes and the API/service classes be backward compatible.

**Comment by fehguy** [comment]
Are you using 2.1.x-M1?  That should support the 1.2 swagger specifications.  It is possible, however, that your API is not creating valid JSON.  Can you share the JSON output?

**Comment by rajeshkamal** [comment]
Yes, I am using 2.1.2-M1 - java -jar swagger-codegen-distribution-2.1.2-M1.jar -l java -i http://localhost:8080/api-docs/default/bundle-controller

1. The generated 1.2 Swagger Spec(using swagger springmvc) contains these models which are not correct.

"Collection«Bundle»": {
"description": "",
"id": "Collection«Bundle»",
"properties": {
"empty": {
"required": false,
"type": "boolean"
}
}
},
"Void": {
"description": "",
"id": "Void",
"properties": {}
}

2. The generated JSON OUTPUT is a valid one,

[
   {
      "name":"REST-Demo-Bundle",
      "id":"d26c4979-a7eb-48e0-be0d-a68918261c8b",
      "description":"REST-Demo-Bundle-Desc",
      "fileNames":[
         "file1",
         "file2"
      ],
      "version":"1.0.1",
   }
]

3. The code generation logs,

java -jar swagger-codegen-distribution-2.1.2-M1.jar -l java -i http://localhost:8080/api-docs/default/bundle-controller
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from http://localhost:8080/api-docs/default/bundle-controller
reading from http://localhost:8080/api-docs/default/bundle-controller
writing file generated-code/java/src/main/java/io\swagger\client\model\BundleElement.java
writing file generated-code/java/src/main/java/io\swagger\client\model\Bundle.java
writing file generated-code/java/src/main/java/io\swagger\client\model\Void.java
writing file generated-code/java/src/main/java/io\swagger\client\model\CollectionÂ«BundleÂ».java
writing file generated-code/java/src/main/java/io\swagger\client\api\BundleApi.java
writing file generated-code/java\pom.xml
writing file generated-code/java\src/main/java\io\swagger\client\ApiInvoker.java
writing file generated-code/java\src/main/java\io\swagger\client\JsonUtil.java
writing file generated-code/java\src/main/java\io\swagger\client\ApiException.java

**Comment by rajeshkamal** [comment]
@dilipkrish do you think this is an issue with the swagger-springmvc ?

**Comment by rajeshkamal** [comment]
Closing this since I had created a bug on @springdox - https://github.com/springdox/springdox/issues/620
