### ISSUE TITLE
Java codegen - generates class name Void.java

### ISSUE THREAD

**Issue by rajeshkamal** [swagger-api/swagger-codegen#515]
Spring REST controller returns void for DELETE operation.
    
    @ApiOperation(value = "Delete a contact")
    @RequestMapping(value = "/contact/{contactId}", method = RequestMethod.DELETE)
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
    public @ResponseBody void delete(@PathVariable String contactId) {
        contactService.delete(contactId);
    }

Using swagger springmvc for generating the swagger spec 1.2.

The spec contains a Void model for some reason and inturn generates a Void.java. How can we avoid this.
{
    "apiVersion": "1.0",
    "swaggerVersion": "1.2",
    "basePath": "/",
    "resourcePath": "/contact",
    "produces": [
        "*/*"
    ],
    "consumes": [
        "application/json"
    ],
    "apis": [
        {
            "path": "/contact/{contactId}",
            "description": "delete",
            "operations": [
                {
                    "method": "DELETE",
                    "summary": "Delete a contact",
                    "notes": "delete",
                    "nickname": "delete",
                    "produces": [
                        "*/*"
                    ],
                    "consumes": [
                        "application/json"
                    ],
                    "parameters": [
                        {
                            "allowMultiple": false,
                            "defaultValue": "",
                            "description": "contactId",
                            "name": "contactId",
                            "paramType": "path",
                            "type": "string",
                            "required": true
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 204,
                            "message": "No Content"
                        },
                        {
                            "code": 401,
                            "message": "Unauthorized"
                        },
                        {
                            "code": 403,
                            "message": "Forbidden"
                        }
                    ],
                    "deprecated": "false",
                    "type": "void"
                }
            ]
        }
    ],
    "models": {
        "Void": {
            "description": "",
            "id": "Void",
            "properties": {}
        }
    }
}

**Comment by wing328** [comment]
I would recommend you to report the issue to @springdox to skip "void" as a model in the swagger spec generated by springdox (void is reserved keyword in java so there should not be a class named "void" in a valid use case)

**Comment by rajeshkamal** [comment]
Done created a bug in the @springdox - https://github.com/springdox/springdox/issues/617
