### ISSUE TITLE
Unable to send parameters of type 'body' for 'GET' operations

### ISSUE THREAD

**Issue by aseychell** [swagger-api/swagger-codegen#5150]
##### Description

HTTP `GET` operations do not normally have a request body but it can be encoded as part of the query string as a JSON object.  This is handled correctly in [Swagger Editor](http://editor.swagger.io).  The request is URL encoded and set as a query string.  However, in most code generation tools (we tried Java and Javascript generators) this is not handled and the parameter is completely ignored.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

[Gist for swagger.yaml](https://gist.github.com/aseychell/51e7d91c69695f18b292129c0d663a2d)

##### Command line used for generation

`java -jar swagger-codegen-cli-2.2.2.jar generate -l javascript -i https://gist.githubusercontent.com/aseychell/51e7d91c69695f18b292129c0d663a2d/raw/d532e2b728b355953ffa64aeeeec1b0553946167/swagger.yaml -o swaggergetjs`

`java -jar swagger-codegen-cli-2.2.2.jar generate -l java -i https://gist.githubusercontent.com/aseychell/51e7d91c69695f18b292129c0d663a2d/raw/d532e2b728b355953ffa64aeeeec1b0553946167/swagger.yaml -o swaggergetjava`

##### Steps to reproduce

1. Generate client using codegen
2. Start server at (Swagger Server example)[https://github.com/aseychell/swagger-getwithbody-issue]
2. Send a request to `/filter' with some parameters and 

##### Suggest a Fix

For `GET` requests which do not have a query string and have a body, start encoding the body (typically a JSON object) as URL encoded and send it as the query string.

**Comment by wing328** [comment]
> For GET requests which do not have a query string and have a body, start encoding the body (typically a JSON object) as URL encoded and send it as the query string.

You may want to document the parameters as query string instead of HTTP body.

For Java, you may also want to try the `retrofit2` (which supports HTTP GET with request body)

Also it's worth sharing with you the following discussion:

http://stackoverflow.com/a/983458/677735
