### ISSUE TITLE
[Swift] Generated Code does not compile when UIKit or AppKit is not included

### ISSUE THREAD

**Issue by vincent-coetzee** [swagger-api/swagger-codegen#5156]
### Extensions.swift, AlamofireImplementations.swift, DefaultAPI.swift and Models.swift do not compile in Swift Package Manager projects

The Extensions.swift,AlmofireImplementations.swift, and DefaultAPI.swift do not compile in Swift Package Manager projects because they assume that Foundation is imported automatically, this is not true in certain SPM projects or projects that are being built on Linux.

##### Swagger-codegen version

I'm using the version built in to the swagger-editor

##### Swagger declaration file content or url

Any Swagger that is used to generate code for Swift 3 that gets included into an SPM project.

##### Command line used for generation

I use the online Swagger Editor to generate a client for Swift 3

##### Steps to reproduce

Define any path in the Swagger and generate a Swift 3 client, then include that client code into a non iOS or macOS project ( e.g. a Swift Package Manager project that targets Linux )

##### Related issues

None

##### Suggest a Fix

In the generated Extensions.swift file add "import Foundation" after "import Alamofire". In the generated AlamofireImplementations.swift file add "import Foundation" after "import Alamofire". In the generated DefaultAPI.swift file add "import Foundation" after "import Alamofire". In the generated Models.swift file, in the function 
~~~~
static func decode<T>(clazz: T.Type, source: AnyObject) -> T 

replace 

if T.self is Int32.Type && source is NSNumber {
            return source.int32Value as! T;
        }

with 

if T.self is Int32.Type && source is NSNumber {
            return (source as! NSNumber).int32Value as! T;
        }

~~~~

Making these changes allows all the code to build and function in non iOS and non macOS projects ( i.e. command line executables, standalone libraries or Linux projects ).

**Comment by wing328** [comment]
@vincent-coetzee thanks for the suggestion. I wonder if you can file a PR so that we can review the fix.

Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache

**Comment by vincent-coetzee** [comment]
Hi there,

Thanks for your email, sorry about the delay in replying.

I have pulled a copy of the swagger-codegen repo, created a branch and fixed the bugs in that branch. I’d like to push the branch to the repo but I am unable to do so, since I don’t have permissions to push to the repo. I’m unfamiliar with how to create a PR unless I can push the branch first, can you assist me here ?

Many thanks

Vince Coetzee

**Comment by wing328** [comment]
@vincent-coetzee did you "folk" https://github.com/swagger-api/swagger-codegen and work on the folked repo (e.g. https://github.com/vincent-coetzee/swagger-codegen)?

**Comment by vincent-coetzee** [comment]
Ah, thanks, I finally found the document detailing how to go about contributing. I have submitted the PR. I ran the shell/batch scripts, but on my machine they just hang.

**Comment by wing328** [comment]
@vincent-coetzee sorry I forgot to send you this: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5390
