### ISSUE TITLE
[PHP]Probably wrong generated setter.

### ISSUE THREAD

**Issue by JohnJonnyJohn** [swagger-api/swagger-codegen#5176]
##### Description

Hello together, I think I just found a problem with the generated code of swagger.
I have a DTO with an List<Enum> property. I think swagger realizes that it is a 
List of enums. The generated setter wants to check the given array, so that just 
valid enums can be setted, but the setter uses the given array as needle in ```in_array```. 

##### Swagger-codegen version

swagger: '2.0'

##### Swagger declaration file content or url

```json
MyDTO:
    type: object
    properties:
      firstProp:
        type: boolean
      thisIsTheProblemProb:
        type: array
        items:
          type: string
          enum:
            - A
            - B
            - C
            - D
```

##### Command line used for generation

java -jar modules/swagger-codegen-cli-2.2.1.jar generate \
  -i http://HOST:PORT/SOMETHING-1.0/rest-api/swagger.json \
  --invoker-package SOME\\THING \
  --api-package SOME\\THING\\Api \
  --model-package SOME\\THING\\Model \
  -l php \
  -o ./src/ \

##### Generated Code

```php
/**
* Sets thisIsTheProblem
* @param string[] $thisIsTheProblem
* @return $this
*/
public function setThisIsTheProblem($thisIsTheProblem)
{
  $allowed_values = array('A', 'B', 'C', 'D');
  if (!in_array($thisIsTheProblem, $allowed_values)) {
      throw new \InvalidArgumentException("Invalid value for 'thisIsTheProblem', must be one of 'A', 'B', 'C', 'D'");
  }
  $this->container['conditions'] = $conditions;

  return $this;
}
```

##### Steps to reproduce

Just generate the code

##### Related issues

Not found

##### Suggest a Fix

I think the array should be iterated in a foreach to use the
```in_array``` function or it should be compared with an ```array_intersect```.

**Comment by wing328** [comment]
I noticed that you're using 2.2.1. Please try to reproduce the issue with the latest stable version 2.2.3

**Comment by arnested** [comment]
Swagger Codegen c2.2.2 (v2.2.3 is not the stable releaes yet, @wing328 😄) will generate the setter below. So I believe this bug is fixed.
```php
    /**
     * Sets this_is_the_problem_prob
     * @param string[] $this_is_the_problem_prob
     * @return $this
     */
    public function setThisIsTheProblemProb($this_is_the_problem_prob)
    {
        $allowed_values = array('A', 'B', 'C', 'D');
        if (!is_null($this_is_the_problem_prob) && (array_diff($this_is_the_problem_prob, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'this_is_the_problem_prob', must be one of 'A', 'B', 'C', 'D'");
        }
        $this->container['this_is_the_problem_prob'] = $this_is_the_problem_prob;

        return $this;
    }
```

**Comment by wing328** [comment]
@arnested thanks for the correct :sweat_smile: 2.2.2 is the latest stable release.

@JohnJonnyJohn if you still experience issue with 2.2.2, let us know and we'll reopen the issue.

**Comment by JohnJonnyJohn** [comment]
Thank you all, now it works perfectly!
