### ISSUE TITLE
[inflector] Generated operation IDs are not correct

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#5182]
When generating an inflector server, the generated handlers (controllers) do not have the proper name when `operationId` is absent.

The generated classes look like this:

```java
public ResponseContext petsGet(RequestContext request ) {
    return new ResponseContext().status(Status.INTERNAL_SERVER_ERROR).entity( "Not implemented" );
}
```

The inflector expects `petsGET` as a name (all caps)

**Comment by wing328** [comment]
Closed via #5183
