### ISSUE TITLE
[C#] Missing XML comment for IValidatableObject.Validate generated method

### ISSUE THREAD

**Issue by StefanoRaggi** [swagger-api/swagger-codegen#5195]
##### Description

The C# generator is not generating XML comments for the `IValidatableObject.Validate` methods in the model classes, causing many build warnings:

```
public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
{ 
    yield break;
}
```

```
warning CS1591: Missing XML comment for publicly visible type or member 'ClassName.Validate(ValidationContext)'
```

##### Swagger-codegen version

v. 2.2.2

##### Swagger declaration file content or url

https://raw.githubusercontent.com/oanda/v20-openapi/master/json/v20.json

##### Command line used for generation

```
java -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i modules/swagger-codegen/src/test/resources/2_0/v20.json -l csharp -o samples/client/oandav20/csharp/Oanda.RestV20 -DpackageName=Oanda.RestV20
```

**Comment by wing328** [comment]
@StefanoRaggi the issue should be fixed via #5206 

Please pull the latest master to give it a try.

**Comment by StefanoRaggi** [comment]
@wing328 Thanks for the fix, but there is a typo in the template: 
validationContex instead of validationContext

```
warning CS1572: XML comment has a param tag for 'validationContex', but there is no parameter by that name
warning CS1573: Parameter 'validationContext' has no matching param tag in the XML comment for 'ClassName.Validate(ValidationContext)' (but other parameters do)
```

**Comment by wing328** [comment]
@StefanoRaggi sorry. https://github.com/swagger-api/swagger-codegen/pull/5223 should fix it.

Please pull the latest master to give it another try.
