### ISSUE TITLE
The samples with GUID should not change with every update

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#5196]
##### Description

When updating the samples for C#, ASP.NET or NancyFx, you always get changes, because those contain a random GUID as the project identifier. This makes it harder to note when actually something changes.

##### Swagger-codegen version

Current master, likely added a long time ago with #1941.

##### Command line used for generation

```bash
bin/aspnetcore-petstore-server.sh
bin/csharp-petstore.sh
bin/csharp-property-changed-petstore.sh
bin/nancyfx-petstore-server.sh
git status
```

##### Related issues

#3084 is trying to get rid of timestamps in the samples (which lead to the same problem).

##### Suggest a Fix

For the two C# samples, it seems to be enough to add an option with a fixed GUID to the generation script.
For ASP.NET Core, the corresponding property needs to be added to the code.
(Same for NancxFX.)

I'll open pull requests for that.

**Comment by wing328** [comment]
PR merged. Thanks for the enhancement.

cc @jimschubert

**Comment by jimschubert** [comment]
Thanks!
