### ISSUE TITLE
[Typescript-Angular2] Multiple API Keys in definition point to same property in config

### ISSUE THREAD

**Issue by usmanatron** [swagger-api/swagger-codegen#5224]
Firstly, I hope this is the right place to raise this - let me know if not and Ill move!

##### Description
I have an API with multiple API key definitions.  When I use this to generate a "Typescript - Angular 2" client (via the online Swagger Editor, http://editor.swagger.io/#!/ ) I get the following in my *Api.ts files:

`

        // authentication (api_key) required
        if (this.configuration.apiKey) {
            headers.set('x-api-key', this.configuration.apiKey);
        }

        // authentication (authorizer) required
        if (this.configuration.apiKey) {
            headers.set('authorizationToken', this.configuration.apiKey);
        }
`
The issue is that, for separate API Key objects, it's pointing at the same apiKey property in the configuration object.  

##### Swagger-codegen version
Not sure, whatever the version is on the online editor (as of 2017-03-27)

##### Swagger declaration file content or url
Here's the relevant snippet.  If you'd prefer to have a full file I can generate a stub API?
```yaml
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
  authorizer:
    type: apiKey
    name: authorizationToken
    in: header
```

##### Command line used for generation
Not applicable, since Im using the online editor.  

##### Steps to reproduce
Export Client -> Typescript - Angular2.  The *Api.ts files will exhibit the bug

##### Related issues
I couldn't find any

##### Suggest a Fix
The problem area is "modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache" (this is why I raised here - I looked for the relevant code :-) ).  Specifically line 138 - 151.  
In terms of fixing, I guess you'd want to have separate properties for each Api Key definition.  The issue I see is reflecting that in the configuration object... perhaps you could have an api_keys dictionary and find the right thing to put there by key?

Im going to do a bit more research and post here if I find anything worth knowing...

**Comment by usmanatron** [comment]
Update: After further research it's not as complicated as I suspected :-).  Ive created a pull request for what I believe to be a reasonable solution.  Do let me know what you think!

**Comment by wing328** [comment]
@usmanatron thanks for the contribution 👍
