### ISSUE TITLE
[C#][aspnetcore] [SwaggerResponse()]:s missing for non HTTP 200 OK responses

### ISSUE THREAD

**Issue by mandrean** [swagger-api/swagger-codegen#5252]
##### Description

* The `[SwaggerResponse()]` is set to `200 OK` by default (even if response-code is e.g. `204 No Content`)
* `[SwaggerResponse()]` for `400 Bad Request`, `404 Not Found` etc. aren't even added by the generator

##### Swagger-codegen version

`v2.3.0` or latest `master`, doesn't matter.

##### Swagger declaration file content or url

`sh ./bin/aspnetcore-petstore-server.sh` or your own `Swagger.json`, doesn't matter.

##### Steps to reproduce

0. `git clone https://github.com/swagger-api/swagger-codegen && cd swagger-codegen`
1. `git checkout origin 2.3.0 && git pull origin 2.3.0 --rebase`
2. `mvn clean package`
3. `sh ./bin/aspnetcore-petstore-server.sh`
4. `cd samples/server/petstore/aspnetcore/src/IO.Swagger`
5. `sh build.sh`
6. Check `swagger-codegen/samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs`

##### Suggest a Fix

Update `controller.mustache` to loop through all responses and generate a `[SwaggerResponse()]` for each of them.

**Comment by mandrean** [comment]
Fixed in #5257. All responses are now shown in the swashbuckle-generated `swagger.json` and `swagger-ui`.

*Before*:
![skarmavbild 2017-03-30 kl 09 09 06](https://cloud.githubusercontent.com/assets/4631744/24493091/d877a020-152d-11e7-9e6b-371e7203de7e.png)

*After*:
![skarmavbild 2017-03-30 kl 09 09 52](https://cloud.githubusercontent.com/assets/4631744/24493115/f032a548-152d-11e7-9b34-9dc514295fbb.png)

**Comment by wing328** [comment]
Closed via #5257
