### ISSUE TITLE
[C#][aspnetcore] Required fields in generated models are missing [Required] attribute

### ISSUE THREAD

**Issue by mandrean** [swagger-api/swagger-codegen#5253]
##### Description

Required fields in generated API models are missing the `[Required]` attribute used in model state validation.

##### Swagger-codegen version

`v2.3.0` or latest `master`, doesn't matter.

##### Swagger declaration file content or url

`sh ./bin/aspnetcore-petstore-server.sh` or your own `Swagger.json`, doesn't matter.

##### Steps to reproduce

0. `git clone https://github.com/swagger-api/swagger-codegen && cd swagger-codegen`
1. `git checkout origin 2.3.0 && git pull origin 2.3.0 --rebase`
2. `mvn clean package`
3. `sh ./bin/aspnetcore-petstore-server.sh`
4. `cd samples/server/petstore/aspnetcore/src/IO.Swagger`
5. `sh build.sh`
6. Check `swagger-codegen/samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Pet.cs`

##### Suggest a Fix

Update `model.mustache` to add `[Required]` when a field is required.

**Comment by mandrean** [comment]
Fixed in #5257. Now you actually get a `400 Bad Request` in the response if you e.g. forget to send in `photoUrls: []` for the PetStore sample:

![image](https://cloud.githubusercontent.com/assets/4631744/24491322/00eadda8-1527-11e7-92c3-73dede40ad1c.png)

**Comment by mandrean** [comment]
Also fixed in #5257; the swashbuckle-generated `swagger.json` and `swagger-ui` correctly shows the non-option/required fields now.

*Before*:
![skarmavbild 2017-03-30 kl 09 09 01](https://cloud.githubusercontent.com/assets/4631744/24493035/a46e4b1c-152d-11e7-888d-e1a8ee787c1d.png)

*After*:
![skarmavbild 2017-03-30 kl 09 09 41](https://cloud.githubusercontent.com/assets/4631744/24493048/ae3326cc-152d-11e7-969a-f5eceb6d40a8.png)

**Comment by wing328** [comment]
Closed via #5257
