### ISSUE TITLE
[C#][aspnetcore] Input model fields aren't properly validated

### ISSUE THREAD

**Issue by mandrean** [swagger-api/swagger-codegen#5254]
##### Description

The input model fields (model state) should be properly validated and return a `400 Bad Request` when a field is incorrect or missing.

Currently, if a required field is missing you might actually get a `500 Internal Server Error`...

##### Swagger-codegen version

`v2.3.0` or latest `master`, doesn't matter.

##### Swagger declaration file content or url

`sh ./bin/aspnetcore-petstore-server.sh` or your own `Swagger.json`, doesn't matter.

##### Steps to reproduce

0. `git clone https://github.com/swagger-api/swagger-codegen && cd swagger-codegen`
1. `git checkout origin 2.3.0 && git pull origin 2.3.0 --rebase`
2. `mvn clean package`
3. `sh ./bin/aspnetcore-petstore-server.sh`
4. `cd samples/server/petstore/aspnetcore/src/IO.Swagger`
5. `sh build.sh`
6. Check `swagger-codegen/samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs` and `swagger-codegen/samples/server/petstore/aspnetcore/src/IO.Swagger/Models/Pet.cs`

##### Suggest a Fix

Use a `ValidateModelStateAttribute` on the controller methods: https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/model-validation-in-aspnet-web-api

**Comment by mandrean** [comment]
Fixed in #5257. Now you actually get a `400 Bad Request` in the response:

![image](https://cloud.githubusercontent.com/assets/4631744/24491322/00eadda8-1527-11e7-92c3-73dede40ad1c.png)

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/issues/5257
