### ISSUE TITLE
[Javascript] Is it possible to use the client without browserify/npm/node.js?

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-codegen#5262]
This is a question/issue that I would have asked @jfiala directly but there is no contact information on his profile so I decided to create an issue so everyone will benefit.

We are trying to use the Javascript generated client in our project and so far, it has been very hard to use it "as is".
In the readme.md, there is an explanation about publishing the client to npm and then use browserify.

I was wondering if there is a way to use this client without all of this? There are many reasons for this:
- Forcing a user to have a npm account (only free for open source) is a very intense dependency for someone who just wants to use a simple javascript client. The only dependency that a javascript client should have is something like JQuery to be able to send requests over the network.
- Forcing a user to use browserify for his entire website when he may not want to do this.
- These are 2 additional steps to do after the generation itself which is not ideal.

We tried to use the client as is but we had many problems, probably all related to this:
- Missing libraries that we had to find manually by installing them via npm. (querystring, superagent, buffer, etc...)
- Problems with the path to the client itself. We had to move it in the same folder as requirejs in order to make it work.
- In the end, even after everything was put in place, the query generated by the client doesn't seem to be valid (empty body, for example). Probably linked to the libraries that we found that are not complete or valid at all...

So my final questions are:

- Is there way to use this client without using npm and browserify? If so, how?
- If there is no way, what are my alternatives using swagger-codegen to have a valid javascript client? The best would be a simple "copy and paste" client that may or may not require other easy to find libraries like "jquery".

**Comment by wing328** [comment]
> Forcing a user to have a npm account (only free for open source) is a very intense dependency for someone who just wants to use a simple javascript client. The only dependency that a javascript client should have is something like JQuery to be able to send requests over the network.

I think another way is to publish the NodeJS SDK to github (or other git repo) and install directly from github: 
- https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/README.md#git
- http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly

About browserify, would the following help?

https://github.com/swagger-api/swagger-codegen/issues/3336

**Comment by JFCote** [comment]
@wing328 : Will take a look at this documentation. Thanks!

**Comment by jfiala** [comment]
@JFCote thx for your feedback.
To make things clear, you only need two dependencies to run the generated JS client code in any browser (without using npm or anything else): 
- querystring.js (npm\node_modules\request\lib\querystring.js, there are other flavours of it available as well as querystringJs etc.)
- superagent.js

In fact, the first implementation I did in Dec. 2015 only used jquery as dependency.
@xhh wrapped this as a npm module later, maybe he can give a hint why superagent.js was then used instead of jquery.

I am with you that the generated client code should be runnable "out of the box", this was the case in the first implementation I did. Maybe it would be worth to also ship a default version of superagent.js + querystring.js to prevent confusion.
For those preferring to use jquery only, maybe a separate javascript library would make sense (which could be based on the original implementation).

**Comment by JFCote** [comment]
@jfiala : Thanks for your answer!

Would you be able to find a revision in the master that contains this version that rely only on JQuery? I would like to try it. If it work, I think that this should be the default generator and the "npm" packaging/module should only be an options. In the meantime, I could use the old version for my project.

What do you think @wing328 ?

**Comment by JFCote** [comment]
I've made my homework and I think I have found your latest commit in the javascript generator:
b0e3be8fb371a21a0f2adcc6c5021fe1756b1c05

The only thing is that a LOT of bug fixes and features has been add after that. I will try to use it for my project and we'll wait for the advice of @wing328 for what to do.

Thanks!

**Comment by JFCote** [comment]
@jfiala : I've tried the old version of your generator but could not use it for multiple reasons, probably bugs that have been fixed since that time. But it is exactly like it should be, lightweight and needing nothing more than jquery.
