### ISSUE TITLE
[JAVA] Support different collectionFormats with Feign

### ISSUE THREAD

**Issue by bbdouglas** [swagger-api/swagger-codegen#5265]
##### Description

I ran into a compatibility issue with the Feign client talking to a swagger-specified server. The server expected a multi-valued field (list) to be encoded with commas, like `foo=bar,baz`, but the Feign client instead repeated the key/value pair, like `foo=bar&foo=baz`.

It turns out that Feign only supports the "multi" collection format. I've brought up this issue with Feign (OpenFeign/feign#542), but it hasn't been solved yet. The issue may be eventually get resolved inside the Feign library, but in the meantime I have an external workaround.

I've also added some more fine-grained testing of this feature. The swagger.io public server is actually lenient with respect to list formatting, more so than the server I'm talking to. So I've added a test that looks at the actual URL sent by the client.

##### Swagger-codegen version

Current version (2.3.0)

##### Swagger declaration file content or url

This is reproducible with the petstore API, for example with the findPetByTags endpoint. If you provide more than one tag, the format does not use commas to delimit tags.

##### Command line used for generation

bin/java-petstore-feign.sh produces a client that displays the problem.

##### Steps to reproduce

Given a list of tag strings passed to the Pet Store api's findPetByTags, you can see in the resultant URL passed to the server that the tags are not comma delimited.

##### Related issues

I have seen other issues regarding commas with various clients, for example #3638. But this is related to whether a comma is represented as "," or "%2C".

There are also other libraries that haven't supported multiple collection types, for example #2789. But nothing has come up wrt Feign as far as I have found.

##### Suggest a Fix

I have a pull request ready for review. Coming shortly.

**Comment by wing328** [comment]
Closed via #5266
