### ISSUE TITLE
[Docker] Please update offical swagger-codegen-cli image

### ISSUE THREAD

**Issue by eritikass** [swagger-api/swagger-codegen#5297]
##### Description

Docker [swaggerapi/swagger-codegen-cli](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/) image has not updated with latest fixes from [Dockerfile](https://github.com/swagger-api/swagger-codegen/blob/master/Dockerfile).

Result of that is that in some cases, for example in gitlab-ci its unusable :(

##### Steps to reproduce

run in terminal
```docker run --rm swaggerapi/swagger-codegen-cli date```

date is just random unix command selected for testing here, [docker-entrypoint.sh ](https://github.com/swagger-api/swagger-codegen/blob/master/docker-entrypoint.sh) should make sure they will end up bash.

and result is error

```
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [date]
	at io.airlift.airline.Cli.validate(Cli.java:148)
	at io.airlift.airline.Cli.parse(Cli.java:116)
	at io.airlift.airline.Cli.parse(Cli.java:97)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

##### Related issues

Its been fixed in: https://github.com/swagger-api/swagger-codegen/commit/436731184d8cfb3b9e561a8cca2bc2fe5a151821
I also tested it over, it working fine with this change.

##### Suggest a Fix

Please update [swaggerapi/swagger-codegen-cli](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/) in dockerhub with latest changes.

**Comment by wing328** [comment]
@eritikass when I checked https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/, it said "Last pushed: 12 hours ago". As part of the CI (travis), we push the updated image to Docker.com: https://github.com/swagger-api/swagger-codegen/blob/master/.travis.yml#L74

Are you not pulling the latest image somehow?

**Comment by wing328** [comment]
cc @arnested

**Comment by eritikass** [comment]
@wing328 tnx for your fast response, i also notice this dockerhub Last pushed time, but never less its not there...

made this gist for testing  https://gist.github.com/eritikass/b23ac66e1d552af50843fd7e0a557e7d during docker build, [docker-entrypoint.sh](https://github.com/swagger-api/swagger-codegen/blob/master/docker-entrypoint.sh) should be copy'ed into docker image `/usr/local/bin/docker-entrypoint.sh`, this gist will output content of docer image in `/usr/local/bin/` and as you can see its not there :(

also when i check travis-ci build outputs (for example [this](https://travis-ci.org/swagger-api/swagger-codegen/builds/217782941) from yesterday) - its docker build part is strange as its not matching with the contents of latest [Dockerfile](https://github.com/swagger-api/swagger-codegen/blob/master/Dockerfile).
```
Step 1 : FROM java:8-jre-alpine
 ---> fdc893b19a14
Step 2 : ADD target/swagger-codegen-cli.jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar
 ---> 90b2a3862eab
Removing intermediate container 11cbdca5b6dc
Step 3 : ENTRYPOINT java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar
 ---> Running in 2928ddc1bb4c
 ---> fd3a92008ebe
Removing intermediate container 2928ddc1bb4c
Step 4 : CMD help
 ---> Running in f68ecac1a9b5
 ---> 2f2d5c86e672
Removing intermediate container f68ecac1a9b5
Successfully built 2f2d5c86e672
The push refers to a repository [docker.io/swaggerapi/swagger-codegen-cli]
```

**Comment by arnested** [comment]
The Swagger Codegen CLI at Docker Hub is built from [`modules/swagger-codegen-cli/Dockerfile`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-cli/Dockerfile) -- not from the Dockerfile in the root of the repository.

The version on Docker Hub is not supposed to be able to run arbitrary commands or used for building Swagger itself but only [act as a standalone executable](https://github.com/swagger-api/swagger-codegen#swagger-codegen-cli-docker-image).

**Comment by eritikass** [comment]
ok, my bad then - closing this issue

i still think that this root level image would be more useful, also if you check in dockerhub, and search [swagger-codegen-cli](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=swagger-codegen-cli&starCount=0), then you can see that most popular image is near 1:1 copy for this project root level image

**Comment by arnested** [comment]
We could probably improve the documentation in the README and add some documentation on Docker Hub to better explain the differences between the various Docker images.
