### ISSUE TITLE
[CI][Typescript] nondeterministic failure on Travis CI of typescript builds with NPM

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-codegen#5304]
##### Description

The CI runs on Travis CI fail sometimes (non-deterministically) when doing typescript builds.

Example log extract (from the log of [a build of #5147](https://travis-ci.org/swagger-api/swagger-codegen/jobs/217776446)):
```
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4

npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular/npm-debug.log
```

This time it was in the build of the TS Angular Petstore client, often it also happens with one of the other TypeScript builds. (You'll need to "view raw log" in order to see the actual error messages, but I'm linking to the pages of the builds because those link to the pull requests.)

* TS Fetch Petstore Test Client ([1](https://travis-ci.org/swagger-api/swagger-codegen/jobs/217575218), [2](https://travis-ci.org/swagger-api/swagger-codegen/jobs/217564077) [3](https://travis-ci.org/swagger-api/swagger-codegen/jobs/213653620))
* TS Angular Petstore Client ([1](https://travis-ci.org/swagger-api/swagger-codegen/jobs/215684567), [2](https://travis-ci.org/swagger-api/swagger-codegen/jobs/214915052))
* TS Fetch Default Petstore Client ([1](https://travis-ci.org/swagger-api/swagger-codegen/jobs/215676368), [2](https://travis-ci.org/swagger-api/swagger-codegen/jobs/215653286), [3](https://travis-ci.org/swagger-api/swagger-codegen/jobs/215299302), [4](https://travis-ci.org/swagger-api/swagger-codegen/jobs/215207107), [5](https://travis-ci.org/swagger-api/swagger-codegen/jobs/214958727), [6](https://travis-ci.org/swagger-api/swagger-codegen/jobs/214354344))
   * this one is the first of the TS builds, so I guess it is natural that it happens more often.

##### Swagger-codegen version

This happens from time to time already for at least some weeks, possibly longer.
The examples linked above cover the last ~ 11 days.
Usually triggering the build again (by doing a force push to the branch without changes, or by adding commits) helps.

##### Suggest a Fix

I guess this is somehow related to the NPM configuration of our Travis CI build. I don't know anything about this, though.

**Comment by wing328** [comment]
I noticed something similar - I usually saw network errors when `npm install` trying to download npm modules from npmjs.com.

I'm trying to move the tests (JS, TS) to Shippable and so far I've encountered minor issue related to JS Petstore test (1 test failure).

**Comment by wing328** [comment]
Moved tests to CircleCI and seems no longer seeing the issue.

Will reopen this if the issue reoccurs.
