### ISSUE TITLE
[PHP] Add support for async requests

### ISSUE THREAD

**Issue by baartosz** [swagger-api/swagger-codegen#5306]
##### Description
Generated clients are already using guzzle6 out of the box on 2.3.0 branch and guzzle supports async requests. It is easy task now to allow generated client to send async requests. I would suggest adding separate `$api->xxxAsync()` and `$api->xxxAsyncWithHttpInfo()` methods for this. 

##### Swagger-codegen version
2.3.0+ 
##### Command line used for generation
`--library=none` or something
##### Related issues
https://github.com/swagger-api/swagger-codegen/pull/5190
https://github.com/swagger-api/swagger-codegen/issues/1482
##### Suggest a Fix

**Comment by wing328** [comment]
Closed via #5771 by @ackintosh
