### ISSUE TITLE
[JAVA]To generate @JsonInclude(Include.NON_NULL) in java pojo classes

### ISSUE THREAD

**Issue by archsri333** [swagger-api/swagger-codegen#5309]
Description:
How to make Swagger codegen to generate @JsonInclude(Include.NON_NULL) in java pojo classes

Swagger-codegen version:
2.2.1

**Comment by wing328** [comment]
@archsri333 one way is to modify the templates and pass the customized templates via the `-t` option.

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/pojo.mustache

You can want to start with the latest stable release v2.2.2: github.com/swagger-api/swagger-codegen/releases/tag/v2.2.2

**Comment by archsri333** [comment]
Thank you for your response. 
Can you please let me know how to pass it via -t option. If there is any sample regarding that, can you please share it.
Since we are manually editing all generated  java pojo classes  to include those line.

**Comment by archsri333** [comment]
Please anyone of you help me in letting me know how to use -t option to customize template.

**Comment by wing328** [comment]
I've added the following FAQ. Please take a look to see if it helps.

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-customize-the-template-to-add-headerfooter-to-the-auto-generated-code

**Comment by LebedkoDmitry** [comment]
The option `NotNullJacksonAnnotation` was introduced in [Swagger Codegen 2.4.15](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.4.15). You can find details in #6488. Please feel free to use it to have your POJOs annotated with `@JsonInclude(Include.NON_NULL)`.
```
<build>
  <plugins>
    <plugin>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-codegen-maven-plugin</artifactId>
      <version>2.4.15</version>
      <executions>
        <execution>
          <id>generate-api</id>
          <goals>
            <goal>generate</goal>
          </goals>
          <configuration>
            <inputSpec>${project.basedir}/src/main/resources/swagger-api.yaml</inputSpec>
            <language>java</language>
            <modelPackage>org.test.model</modelPackage>
            <configOptions>
              <dateLibrary>java8</dateLibrary>
              <notNullJacksonAnnotation>true</notNullJacksonAnnotation>
            </configOptions>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```
