### ISSUE TITLE
[Maven] swagger-codegen-maven-plugin version 2.2.3-SNAPSHOT fails

### ISSUE THREAD

**Issue by Krabatz** [swagger-api/swagger-codegen#5316]
##### Description

Using swagger-codegen-maven-plugin version 2.2.3-SNAPSHOT fails because the dependency to io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT could not be resolved.

Error message:

**[ERROR] Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.2.3-SNAPSHOT:generate (swagger-generate-usermanagement) on project a4yCodegen: Execution swagger-generate-usermanagement of goal io.swagger:swagger-codegen-maven-plugin:2.2.3-SNAPSHOT:generate failed: Plugin io.swagger:swagger-codegen-maven-plugin:2.2.3-SNAPSHOT or one of its dependencies could not be resolved: The following artifacts could not be resolved: io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT, io.swagger:swagger-compat-spec-parser:jar:1.0.27-SNAPSHOT: Failure to find io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT in http://repo2.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of fallback has elapsed or updates are forced -> [Help 1]**

pom.xml:

...
\<dependencyManagement>
    \<dependencies>
    	\<dependency>
        \<groupId>io.springfox\</groupId>
        \<artifactId>springfox-swagger2\</artifactId>
        \<version>2.5.0\</version>
    	\</dependency>
    	\<dependency>
        \<groupId>io.springfox\</groupId>
        \<artifactId>springfox-swagger-ui\</artifactId>
        \<version>2.5.0\</version>
    	\</dependency>
    \</dependencies>
	\</dependencyManagement>
...
\<pluginManagement>
    	\<plugins>
        \<plugin>
        	\<groupId>io.swagger\</groupId>
        	\<artifactId>swagger-codegen-maven-plugin\</artifactId>
        	\<version>2.2.3-SNAPSHOT\</version>
        \</plugin>
    	\</plugins>
\</pluginManagement>
...
\<pluginRepositories>
    \<pluginRepository>
    	\<id>sonatype-snapshots\</id>
    	\<url>https://oss.sonatype.org/content/repositories/snapshots\</url>
    	\<snapshots>
        \<enabled>true\</enabled>
    	\</snapshots>
    \</pluginRepository>
\</pluginRepositories>

##### Swagger-codegen version

swagger-codegen-maven-plugin version 2.2.3-SNAPSHOT

##### Swagger declaration file content or url

N/A

##### Command line used for generation

mvn clean install

##### Steps to reproduce

See above

##### Related issues

N/A

##### Suggest a Fix

1.0.27-SNAPSHOT does not exist. Update swagger-parser dependency to 1.0.29-SNAPSHOT

**Comment by wing328** [comment]
Please pull the latest master, which no longer depends on 1.0.27-SNAPSHOT

**Comment by kirpit** [comment]
Unfortunately, it is still so easy to re-produce this error with the current master. The error is present only for `swagger-codegen-maven-plugin` module:

```
$ git clone git@github.com:swagger-api/swagger-codegen.git swagger-clone
Cloning into 'swagger-clone'...
remote: Counting objects: 158089, done.
remote: Total 158089 (delta 0), reused 0 (delta 0), pack-reused 158088
Receiving objects: 100% (158089/158089), 47.21 MiB | 2.52 MiB/s, done.
Resolving deltas: 100% (85214/85214), done.
Checking connectivity... done.
$ cd swagger-clone/modules/swagger-codegen-maven-plugin/
$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building swagger-codegen (maven-plugin) 2.2.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.swagger:swagger-compat-spec-parser:jar:1.0.27-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.775 s
[INFO] Finished at: 2017-05-05T11:15:47+10:00
[INFO] Final Memory: 9M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project swagger-codegen-maven-plugin: Could not resolve dependencies for project io.swagger:swagger-codegen-maven-plugin:maven-plugin:2.2.3-SNAPSHOT: The following artifacts could not be resolved: io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT, io.swagger:swagger-compat-spec-parser:jar:1.0.27-SNAPSHOT: Failure to find io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by TehBakker** [comment]
Having the same issue using Maven plugin with the 2.2.3-SNAPSHOT version

**Comment by guocongwudi** [comment]
+1

**Comment by wing328** [comment]
Will take another look later today...

**Comment by wing328** [comment]
Pulling the latest and the followings run fine:
```
cd modules/swagger-codegen-maven-plugin/
mvn clean package
```
Here is the result:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.818 s
[INFO] Finished at: 2017-06-26T15:09:42+08:00
[INFO] Final Memory: 40M/515M
[INFO] ------------------------------------------------------------------------
```

**Comment by wing328** [comment]
SNAPSHOT version now available. Please refer to https://github.com/swagger-api/swagger-codegen/blob/master/README.md#compatibility for more information.
