### ISSUE TITLE
customize date format in swift3

### ISSUE THREAD

**Issue by ahmettaha** [swagger-api/swagger-codegen#5318]
How can I customize the dateformat when serializing the dates. I know i can alter the generated code, but is it possible to change it via a configuration?

I want to serialize with a localdate format, rather than zulu time

**Comment by jgavris** [comment]
What do you mean local date? Could you give a specific example of what you're trying to do? In general you want to keep the zulu time and just format it according to the local time zone. Maybe what you're looking for is tracking a user's time zone as a separate field somewhere?

**Comment by ahmettaha** [comment]
Sure.

right now the following default code produces

`
let fmt2 = DateFormatter()
fmt2.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ"
fmt2.locale = Locale(identifier: "en_US_POSIX")

fmt2.string(from: date)
`

2017-04-04T14:37:19.936+01:00

however, our server doesnt care about the timezoneoffset. It just needs the local datetime, so it accepts a datetime like below.

"2017-04-04T14:40:06.374"

so I would like to change it to

"yyyy-MM-dd'T'HH:mm:ss.SSS"

different servers expect different datetime formats, although they all mean the same thing. and a certain format needs to be decided to be able to support multiple client from various platforms.

**Comment by jgavris** [comment]
Ah, your server *should* care about the time zone offset. What makes you think you don't need to?

**Comment by ahmettaha** [comment]
because we dont need to. We keep datetime fields of the records in localtime. We dont use the offset with the GMT time. Not every business operation need to care about timezone ;)

**Comment by jgavris** [comment]
Ok, I'll ask one more time. What operation is this that you don't care about the timezone?

**Comment by ahmettaha** [comment]
ok. Let's assume, I have an api operation called userClickedButton(string userid, datetime localtime)

It sends the userid and the datetime user clicked the button on the mobile app. On the api side, server inserts the record to a sql table. Then server generate a report to see which times of the day, the user has clicked the button. if more is clicked in the morning, or the evening. So I dont care about the offset. I just do operation on the localtime.

**Comment by jgavris** [comment]
The local time is encoded in the time with zone format...you just need to change your query on your server to render that time as a local time. Just add / subtract the offset from the time.

**Comment by wing328** [comment]
Just want to share a bit more on customizing datetime format in other client generators such as C#, Java, PHP. The idea is that the server is not expecting RFC3999 datetime but in order to ease the adoption of Swagger/OpenAPI, we allow the datetime format to be customized in the configuration class. 

For Swift (2.x, 3.x) clients, we can probably do something similar by adding a configuration object for customising datetime format and other values (e.g. base path)

e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/Configuration.cs#L284-L315
