### ISSUE TITLE
[Java] Retrofit2Rx2 code generation problem

### ISSUE THREAD

**Issue by steven0529** [swagger-api/swagger-codegen#5320]
##### Description

Hi,

I noticed the petstore sample from [petstore sample](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/java/retrofit2rx2) still uses **RxJava 1 (rx.Observable)**. 
I also tried generating an sdk using this swagger-codegen-cli-2.2.1.jar with this config.json 

`{
  "sourceFolder": "src",
  "modelPackage": "com.gatebuzz.oxford.model",
  "apiPackage": "com.gatebuzz.oxford.api",
  "library": "retrofit2",
  "useRxJava2": true
}`

but still generates the same **RxJava 1(rx.Observable).**

Is this a bug or is this the expected result? 

How can we generate the Retrofit code with **RxJava2(io.reactive.Observable)**? 

##### Swagger-codegen version
**swagger-codegen-cli-2.2.1.jar**

**Comment by wing328** [comment]
Can you try the latest stable version 2.2.2 instead?

**Comment by steven0529** [comment]
I also tried the 2.2.2 jar but still experience same problem. :(

**Comment by wing328** [comment]
@steven0529 ok. I'll take a look...

**Comment by wing328** [comment]
Fixed via https://github.com/swagger-api/swagger-codegen/pull/5321 with `useRxJava2`

Please pull the latest master to give it a try.

**Comment by steven0529** [comment]
Worked, thanks!
