### ISSUE TITLE
Parameters' name with "_" not properly mapped in Angular2 typescript client

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#5322]
_From @basygit on April 4, 2017 9:54_

This bug is both online on http://editor.swagger.io/#!/, than into the "http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.2/swagger-codegen-cli-2.2.2.jar"

![capture](https://cloud.githubusercontent.com/assets/26896343/24651229/5b545ed6-192d-11e7-943e-d4b6eb6003d5.PNG)

_Copied from original issue: swagger-api/swagger-editor#1249_

**Comment by cenkentimist** [comment]
@basygit I have run into this issue as well. Currently I'm using the work around of not naming path parameters that way. It's a less then impressive work around but it does work.

**Comment by wing328** [comment]
The issue has been [fixed](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L65) in the latest master via https://github.com/swagger-api/swagger-codegen/commit/dbe99c3af92ebc4862e7984a246b9af5e707013d. Please pull the latest master to give it another try.

**Comment by wing328** [comment]
FYI. Reviewed other TS generators (jquery, node, angular, fetch) and confirmed the bug has been also addressed.

**Comment by basygit** [comment]
Ok, tnx! Please update the online editor too.

**Comment by wing328** [comment]
Please refer to https://github.com/swagger-api/swagger-codegen/wiki/FAQ#what-does-httpseditorswaggerio-leverage-swagger-codegen-for-code-generation
