### ISSUE TITLE
How to deal with same name files with swagger jar

### ISSUE THREAD

**Issue by suresh777** [swagger-api/swagger-codegen#5323]
i am using swagger classes in swift3,our backend side we have multiple microservices apis,they are giving different jars but the api client inside that jar file is with same name,in android we have package structure but in ios if i copy multiple file with same name it won't allow

**Comment by wing328** [comment]
@suresh777 have you tried different options to customize `swift3` client? e.g. `swiftUseApiNamespace`, `projectName`

Ref: java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l swift3

**Comment by suresh777** [comment]
we are generating swagger classes by running this command                  
 java -jar swagger-codegen-cli.jar generate -i login.json -l swift3 -o SwaggerClient 
where should i add swiftUseApiNamespace

**Comment by wing328** [comment]
@suresh777 please use the -c option
```
        -c <configuration file>, --config <configuration file>
            Path to json configuration file. File content should be in a json
            format {"optionKey":"optionValue", "optionKey1":"optionValue1"...}
            Supported options can be different for each language. Run
            config-help -l {lang} command for language specific config options.
```
e.g. https://github.com/swagger-api/swagger-codegen#customizing-the-generator

**Comment by suresh777** [comment]
i used -c config.json but my swaggerclient folder contain one file with class name response, same class exist in alamofire so that it is conflicting in xcode

**Comment by wing328** [comment]
We can mark `response` as a reserved word in Swift3 generator: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Swift3Codegen.java#L102

Currently, we only whitelist `ErrorResponse`.

Would you have time to contribute the enhancement?

**Comment by suresh777** [comment]
We are getting classes which use Alamofire by default.  Problem arises because of same model class name and Alamofire class.Is it possible to get these classes with other library or just by urlsession?

**Comment by wing328** [comment]
> Is it possible to get these classes with other library or just by urlsession?

I don't think I understand your question. Whitelisting `response` should address the issue for you.

**Comment by suresh777** [comment]
If response is whitelisted then my server team can't use "response" as a class name ? if that is the case all alamofire class names must be whitelisted in order to prevent conflict

**Comment by wing328** [comment]
> If response is whitelisted then my server team can't use "response" as a class name ?

The server side can still use "response" as the class name.

>  if that is the case all alamofire class names must be whitelisted in order to prevent conflict

Right. Do you have a full list?

**Comment by suresh777** [comment]
you are asking alamofire class,protocols,enums,structs list,if i provide that list we should add it in whitelist,but if i whitelist response class name what happens after swagger client jar generation what will be the name of response class will it change to some other name?

**Comment by suresh777** [comment]
Thank you for giving replies,i will generate those class files by adding prefix that way i can prevent conflicts

**Comment by wing328** [comment]
> what happens after swagger client jar generation what will be the name of response class will it change to some other name?

`response` (model name) will become `ModelResponse`

**Comment by wing328** [comment]
I've updated the reserved keyword list to include "response". Please pull the latest master to give it a try.

**Comment by suresh777** [comment]
if i try to generate swagger client in swift it is giving classes folder it contains both apis,alamofire classes,if i import into xcode it is working fine but if i generate swagger client for one more microservice it gives both apis,alamofire classes,in ios there is no package structure so that if i try to import this same alamofire classes it shows already exist, one way is  i need to convert every swagger client library into framework another way is  i need to add prefix for all swagger classes but in swagger client generator you added prefix provision for only models.
