### ISSUE TITLE
How do I add authorization function for all my protected routes before they hit the routes in the controller?

### ISSUE THREAD

**Issue by SonnyRajagopalan** [swagger-api/swagger-codegen#5326]
##### Description

I had to add Authorization in my header in the format `Authorization: Bearer <token>`. I receive this in my `req.swagger.params.Authorization` but I would like to add a way to authorize all requests with this header without having to deal with this in my `/controllers/*Service.js` and `/controllers/*.js`. I added code in `index.js` but that doesn't seem to be called. I added this:

    swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
      // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
      app.use(middleware.swaggerMetadata());
       
        app.use(middleware.swaggerSecurity({
	    Authorization: function (req, def, scopes, callback) {
    	        console.log ('INDEX.JS RECEIVED SOMETHING', req);
	        callback();
	    }
        }));

Where do I add code to authorize all protected routes in my API?

##### Swagger-codegen version

2.2.3-SNAPSHOT

**Comment by SonnyRajagopalan** [comment]
Because of a quirk in swagger, I do not get to "catch" the header in `swagger-security.js` (i.e., the swaggerSecurity middleware). My workaround was to manually tamper with the `swagger-security.js` file. The condition

          if (securityReqs && securityReqs.length > 0) {

won't catch the Auth header. Instead, catch it in the `else` clause like so:

    req.swagger.params.Authorization.originalValue

And do what you have to for the authorization of this request. Then, you can set your user based on the authorization step like so (if you need to):

    req.swagger.params.user = 'sonny'

and even pass custom parameters:

    req.swagger.params.custom = 'This was a good exercise to figure out'

And viola! Each request is authorized before it hits the routers in `controllers/` and you can use your extra information (`custom` and `user`) in those methods because each `Tag.js` file is only passing `req.swagger.params` to `TagService.js`.

Hope this helps someone.  I really think swagger is awesome, but I think the security parts of swagger-codegen and swagger-tools could use a lot more documentation and examples.

**NOTE:**  My method detailed here is not needed if you do catch the Auth header--in that case, the swaggerSecurity middleware function defined in my OP will manage the Auth part. However, if you **DO** want to pass your security token as a header, then you will have to do what I detail in this answer and NOT do it in the `index.js` file for your app (i.e., not do what I write in the OP).

**Comment by wing328** [comment]
@SonnyRajagopalan thanks for sharing the details on how you fixed the issue.

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))
