### ISSUE TITLE
[JAVA] swagger-codegen-maven-plugin does not generate server code?

### ISSUE THREAD

**Issue by jojow** [swagger-api/swagger-codegen#5332]
##### Description

It seems like the swagger-codegen-maven-plugin module does not generate any server code, but only client code. I can only find client-related code that is generated.

##### Swagger-codegen version

swagger-codegen-maven-plugin 2.2.2

##### Swagger declaration file content or url

any Swagger definition

##### Command line used for generation

using maven module:
swagger-codegen-maven-plugin 2.2.2

##### Steps to reproduce

Run `mvn clean compile`

##### Related issues

--

##### Suggest a Fix

Extend swagger-codegen-maven-plugin to generate server code.

**Comment by wing328** [comment]
@jojow can you provide more information on what server code you want to generate? Java Spring, C# Nancy, PHP Slim, etc?

Here is a list of targets (client, server, API doc) supported:
```
aspnet5
aspnetcore
async-scala
bash
cwiki
csharp
cpprest
dart
elixir
flash
python-flask
go
groovy
java
jaxrs
jaxrs-cxf-client
jaxrs-cxf
jaxrs-resteasy
jaxrs-resteasy-eap
jaxrs-spec
jaxrs-cxf-cdi
inflector
javascript
javascript-closure-angular
jmeter
nancyfx
nodejs-server
objc
perl
php
python
qt5cpp
ruby
scala
scalatra
finch
silex-PHP
sinatra
rails5
slim
spring
java-play-framework
dynamic-html
html
html2
swagger
swagger-yaml
swift
swift3
tizen
typescript-angular2
typescript-angular
typescript-jquery
typescript-node
typescript-fetch
akka-scala
CsharpDotNet2
clojure
haskell
lumen
go-server
erlang-server
undertow
msf4j
ze-ph
```

**Comment by jojow** [comment]
@wing328 thanks for the reply! I'm currently interested in generating Java Spring Boot server code.

After I specified `<language>spring</language>` (instead of `<language>java</language>`) in my pom.xml file, server code was generated.
So, `<language>java</language>` does only generate client code. It would be awesome if this could be documented explicitly. I'll make a pull request. :-)

Thanks for your efforts!

**Comment by elizabetht** [comment]
Shouldn't this issue be closed? I see the code changes being merged.

**Comment by kenisteward** [comment]
+1 this should be closed

**Comment by fehguy** [comment]
I love closing tickets!
