### ISSUE TITLE
codegen for multiple .yaml files together.

### ISSUE THREAD

**Issue by dnome2** [swagger-api/swagger-codegen#5334]
##### Description

I'm trying to generate python client from a bunch of yamls that are autogenerated for our project. Is there way using the cli, that i can specify all the yaml file together, i.e with -i option. Does it take a list? I've tried to do that haven't succeeded so if there is way to get around it would really help. 

##### Swagger-codegen version

recently downloaded swagger codegen. Fairly new to this community

##### Command line used for generation

swagger-codegen generate -i device_registration.yaml -DapiTests=false,apiDocs=false,modelTests=false,modelDocs=false -c config.json -l python -o pyclient

##### Suggest a Fix

if possible the -i option should take a list of comma seperated files.

**Comment by wing328** [comment]
`-i` does not support list of spec and I don't think config.json should be the same for all the spec you want to generate the Python SDKs with.

**Comment by dnome2** [comment]
Thanks for the response. The thing is all these spec's are of same application but it would be helpful if all the api's are in the same folder so a sdk/client that is generated does have redundancy for eg files like api_client.py would be generated in every folders for every config.json. Is there a better way that you can help us suggest for generating multiple specs?

**Comment by wing328** [comment]
I think you will need a tool to combine the Swagger spec into one.

Another suggestion from mine is to actually generate 3 SDKs separately as some developers may prefer Python modules that are smaller in size with only a few endpoints. (we did have issues opened before about size of SDKs too large to fit into certain environments)

**Comment by Ark-kun** [comment]
> `-i` does not support list of spec

It does not refuse it either. You can specify -i 1.json -i 2.json ...
