### ISSUE TITLE
[typescript] missing type for a property results in it being ignored with little warning

### ISSUE THREAD

**Issue by cenkentimist** [swagger-api/swagger-codegen#5335]
##### Description
if you leave the type of a property in a defintion it will be silently dropped from the typescript definition with only the message `[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=I'm invisible!, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
` as warning.

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url

```nowork.yaml
swagger: '2.0'

info:
  title: example
  version: "0"

paths: {}

definitions:
  aDef:
    type: object
    properties:
      initialValue:
        description: "I'm invisible!"
```
##### Command line used for generation
any of the following
`swagger-codegen generate --lang typescript-angular2 --output box --input-spec nowork.yaml`
`swagger-codegen generate --lang typescript-angular --output box --input-spec nowork.yaml`
`swagger-codegen generate --lang typescript-node --output box --input-spec nowork.yaml`
`swagger-codegen generate --lang typescript-fetch --output box --input-spec nowork.yaml`

##### Steps to reproduce
create a file nowork.yaml with the given text
run one of the following
`swagger-codegen generate --lang typescript-angular2 --output box --input-spec nowork.yaml`
`swagger-codegen generate --lang typescript-angular --output box --input-spec nowork.yaml`
observe the interface in `box/model/ADef.ts` has no properties
note  (you can run -node or -fetch as well and check the box/api.ts file)

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/5164

##### Suggest a Fix

Either notify in a clear way to the user that the attribute has been dropped or assume the object type.

**Comment by wing328** [comment]
@cenkentimist thanks for the suggestion. I agree better error message can make the experience better using Swagger Codegen

Please submit your feedback to [Swagger Parser project](https://github.com/swagger-api/swagger-parser), which is used by Swagger Codegen to parse the OpenAPI/Swagger spec.

**Comment by kenisteward** [comment]
Should this be closed as it is not a swagger-codegen but swagger-parser issue?

**Comment by wing328** [comment]
@kenisteward yes as https://github.com/swagger-api/swagger-parser/issues/441 has been created for swagger-parser
