### ISSUE TITLE
[Perl] remove singleton for ApiClient

### ISSUE THREAD

**Issue by tbe** [swagger-api/swagger-codegen#5336]
##### Description
The ApiClient generated for Perl uses a singleton. This makes it impossible to use it in a web application with multiple users and therefore multiple authentication data.

##### Swagger-codegen version

v2.2.2

**Comment by wing328** [comment]
@tbe yes, we've been doing something similar (removal of singleton) in other languages. Most recently, we did that for Python in branch 2.3.0 (with breaking changes) via https://github.com/swagger-api/swagger-codegen/pull/5012

May I know if you've time to contribute the enhancement to make the Configuration per ApiClient? If yes, I can show you some starting points.

**Comment by tbe** [comment]
@wing328 sure. I already started last night reading the templates and experimenting.

**Comment by wing328** [comment]
@tbe thanks! Let us know if you need any help.

Please pull the latest 2.3.0 and file the PR against 2.3.0 as it's going to be a breaking change.
