### ISSUE TITLE
[Swift3] Unit tests do not compile

### ISSUE THREAD

**Issue by jgavris** [swagger-api/swagger-codegen#5343]
##### Description

The example Swift 3 project tests do not compile.

##### Swagger-codegen version

2.3.0 @ `6c745596d43baa99792165e8a3e50e9c37bcf47e`

##### Swagger declaration file content or url

Petstore.json example

##### Steps to reproduce

Ran `./bin/swift3-petstore-all.sh` and then tried to run 
 the unit tests in `./samples/client/petstore/swift3/default/SwaggerClientTests/SwaggerClient.xcworkspace`. 

##### Suggest a Fix

Where are we at in terms of getting CI going for the Apple platforms?

**Comment by wing328** [comment]
@jgavris thanks for spotting the issue. I tried running the test without updating Swift3 Petstore and it's fine but looks like a recent change breaks it.

There are many little issues with CIs these days and I'll open a master issue to track all of them (including this one)

**Comment by wing328** [comment]
Fixed in the latest master and 2.3.0

Thanks for your help 👍
