### ISSUE TITLE
[All Generators] List of `required` gets dropped in objects with `allOf`

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-codegen#5344]
##### Description
If you have a field that has been marked as `required` in a definition that extends from another type the `required` field is stripped off the spec.

##### Swagger-codegen version

Reproducible through the editor: http://editor.swagger.io/
Also, in 2.2.2.

##### Swagger declaration file content or url

Input spec:
```yaml
definitions:
  Product:
    type: object
    required:
      - a_description
    properties:
      a_description:
        type: string
        description: Description of product.
  ExtendedProduct:
    type: object
    required:
      - another_field
    allOf:
      - $ref: '#/definitions/Product'
      - properties:
          another_field:
            type: boolean
            description: This should be required
```

After being run through the swagger codegenerator (yaml -> yaml):
```yaml
definitions:
  Product:
    type: "object"
    required:
    - "a_description"
    properties:
      a_description:
        type: "string"
        description: "Description of product."
  ExtendedProduct:
    allOf:
    - $ref: "#/definitions/Product"
    - properties:
        another_field:
          type: "boolean"
          description: "This should be required"
```

You can see that `Product` keeps it's list of `required` but `ExtendedProduct` does not.
##### Command line used for generation

I used the editor here to produce the example:
 http://editor.swagger.io/

But this is reproducible with the java code generator if you target the `yaml` generator.

##### Steps to reproduce

Run the input above in the code generator and observe the output.

##### Suggest a Fix

This is probably a problem somewhere in the spec parser.

**Comment by JLLeitschuh** [comment]
I may have the spec defined wrong:
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-simple.yaml#L124-L136

**Comment by nbruno** [comment]
Yes, the original spec is incorrect. `allOf` simply takes an array of object definitions, so it should look like this:

```
definitions:
  Product:
    type: object
    required:
      - a_description
    properties:
      a_description:
        type: string
        description: Description of product.
  ExtendedProduct:
    type: object
    allOf:
      - $ref: '#/definitions/Product'
      - properties:
          required:
            - another_field
          another_field:
            type: boolean
            description: This should be required
```

Can you confirm that this resolves your issue?

**Comment by JLLeitschuh** [comment]
Yes, this does resolve my issue. Thanks!!!
