### ISSUE TITLE
[Spring] Add serialVersionUID to serializable model POJO's

### ISSUE THREAD

**Issue by anuthebananu** [swagger-api/swagger-codegen#5346]
##### Description

When trying to use auto-generated Spring models in my Spring Boot project, the Java compiler throws the following warning for each model:

` warning: [serial] serializable class <class name> has no definition of serialVersionUID` 

These warnings prevent me from using the auto-generated Spring models in my project, as I cannot submit any code that has compiler warnings.

##### Swagger-codegen version

2.2.3-SNAPSHOT

##### Command line used for generation

`java -jar -Dmodels swagger-codegen-cli.jar generate -i <myYamlFile> -l spring -c codegen-config.json`

##### Steps to reproduce

Generate the models using the command line and try to use them in a Spring Boot project. Make sure compiler has the -Werror flag enabled.

##### Suggest a Fix

Pretty simple, just add serialVersionUID to the mustache template for POJO's (modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache). I've already incorporated the fix and passed integration tests, just need to make the pull request.

**Comment by wing328** [comment]
Closed via #5347. Thanks for the PR from @anuthebananu

**Comment by anuthebananu** [comment]
I'm using Gradle to load swagger-codegen-cli as a dependency in my Spring Boot project. Unfortunately the latest available version on my company's repository is 2.2.2. 

I saw you added this PR to the 2.2.3 patch release milestone - when is that scheduled to be released?

**Comment by wing328** [comment]
@anuthebananu we target to release 2.3.0 (with breaking changes) in April/May. It will contain the enhancement you made to Spring models.

Given that we released 2.2.2 in March, I foresee it will take 3 to 4 months for another release (2.2.3)
