### ISSUE TITLE
could the generated code be supported beanValidation

### ISSUE THREAD

**Issue by fisherliu** [swagger-api/swagger-codegen#5354]
@ePaul, 
hi ePaul,
I am the swagger user. could you help me?
In current generated code, there is no beanValidation info .
@ApiModelProperty(example = "null", required = true, value = "Unique identifier")
  public String getId() {
    return id;
  }
could swagger support to generate beanValidation like below
**@NotNull**
@ApiModelProperty(example = "null", required = true, value = "Unique identifier")
  public String getId() {
    return id;
  }

/swagger-codegen/src/main/resources/Java/pojo.mustache
 /**
  {{#description}}
   * {{{description}}}
  {{/description}}
  {{^description}}
   * Get {{name}}
  {{/description}}
  {{#minimum}}
   * minimum: {{minimum}}
  {{/minimum}}
  {{#maximum}}
   * maximum: {{maximum}}
  {{/maximum}}
   * @return {{name}}
  **/
{{#useBeanValidation}}{{>**beanValidation**}}{{/useBeanValidation}}  @ApiModelProperty({{#example}}example = "{{example}}", {{/example}}{{#required}}required = {{required}}, {{/required}}value = "{{{description}}}")
{{#vendorExtensions.extraAnnotation}}
  {{{vendorExtensions.extraAnnotation}}}
{{/vendorExtensions.extraAnnotation}}
  public {{{datatypeWithEnum}}} {{getter}}() {
    return {{name}};
  }

/swagger-codegen/src/main/resources/Java/beanValidation.mustache
{{#required}}
  @NotNull
{{/required}}
{{>beanValidationCore}}

the mustache has the @NotNull, why  does the generate code not include @NotNull?

**Comment by fisherliu** [comment]
The latest version has fixed the issue. so closed!

**Comment by ePaul** [comment]
Not sure why you pinged me, but a hint for future issues:

If you wrap the code in

    ```yaml
    ...
    ```
or
    ```java
    ...
    ```

it becomes much more readable. (Similar for other programming languages.)
