### ISSUE TITLE
[csharp-client] Get rid of Configuration in the ApiClien

### ISSUE THREAD

**Issue by iamkarlson** [swagger-api/swagger-codegen#5361]
##### Description

Client code contains tons of unused code as if 

```
            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
```

We can drop it of simply by replace reference to Configuration with reference to ApiClient. And then, in the ApiClient, do all this stuff like default headers, or timeout,etc.

##### Swagger-codegen version

last from master

##### Suggest a Fix

Refactor client templates and remove api client reference from configuration

**Comment by wing328** [comment]
@iamkarlson thanks for the feedback. Would you please test the following PR?

https://github.com/swagger-api/swagger-codegen/pull/3530

Here are the steps
```
git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
git checkout jimschubert-csharp/client_refactoring
mvn clean package
```

**Comment by iamkarlson** [comment]
@wing328 I checked it out. Everything is ok. I have a couple of issues and modifications. I add raw server response to ApiResonse class and additionally check that ApiClient returns an error from the server, and that is not a network error. What do you think if I make a patch and send it to you?

**Comment by wing328** [comment]
@iamkarlson thanks for reviewing https://github.com/swagger-api/swagger-codegen/pull/3530. Is your patch on top of https://github.com/swagger-api/swagger-codegen/pull/3530 (for 2.3.0)?

**Comment by iamkarlson** [comment]
@wing328 yep, just 3 lines at all :) If you could suggest me a correct branch to fork and to make a PR, I would do so.

**Comment by wing328** [comment]
@iamkarlson please fork https://github.com/jimschubert/swagger-codegen.git, make the changes on top of `csharp/client_refactoring` and submit the PR against https://github.com/jimschubert/swagger-codegen.git

cc @jimschubert

**Comment by iamkarlson** [comment]
@wing328 I've tried to make a fork of a fork, but it's not possible... However, I found a workaround for my requirements and guess can close issue in favour of #3530

**Comment by jimschubert** [comment]
@iamkarlson if you encounter this again, you don't actually "fork" the fork, you'd add the fork as another remote.

```
git remote add jimschubert https://github.com/jimschubert/swagger-codegen.git
git fetch jimschubert
git checkout --track jimschubert/csharp/client_refactoring
```

Now, when you make changes and push to your fork of swagger-codegen, a PR can be created against another fork.
