### ISSUE TITLE
Cannot generate Examples Object for Server Code

### ISSUE THREAD

**Issue by hammadkhan119** [swagger-api/swagger-codegen#5366]
I have an examples object in my YAML file but when I generate Server stub for C# using NSWAG or Swagger hub Website then it is not generating code for examples object.

Is it currently supported or not?

Thanks

**Comment by wing328** [comment]
@hammadkhan119 for C# server generator, we support NancyFx and ASP.NET Core Web API.

I don't think we support the `examples` at the moment. If you want to contribute the enhancement, I can show you some good starting points.

It's as simple as just 3 steps: 
1) add {{#examples}} mustache tag
2) deserialize `examples` back into object
3) return the object

There's a similar ongoing work for Spring server: https://github.com/swagger-api/swagger-codegen/issues/5310#issuecomment-293139220

**Comment by wing328** [comment]
@hammadkhan119 we've just add the support of `examples` to Java Spring generator via https://github.com/swagger-api/swagger-codegen/pull/5411

May I know if you've time to make similar change to C# NancyFx or ASP.net core generator?

**Comment by wing328** [comment]
Meta-issue for tracking: https://github.com/swagger-api/swagger-codegen/issues/5423

**Comment by wing328** [comment]
Closing this as we're using #5423 for tracking.
