### ISSUE TITLE
withCredentials:true  for Typescript-Angular 2 Generated code

### ISSUE THREAD

**Issue by xmeng1** [swagger-api/swagger-codegen#5374]
##### Description

When I used the generated code of Typescript-Angular 2, and try to CORS request, the session information is always losing. After search the issue, I found that I need to add an option of `withCredentials:true ` when sending HTTP request. But the generated code does not include this option.

see: http://stackoverflow.com/questions/13734686/communication-between-angularjs-and-a-jersey-webservice-which-are-on-a-different/14111039#14111039

http://stackoverflow.com/questions/16882245/http-request-doesnt-send-cookies-cross-domain-in-angular-cors

So I hope the option `withCredentials:true` can be added to the HTTP request in 

```
        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters
        });
```
##### Swagger-codegen version

git clone at April 3rd.
##### Suggest a Fix

The option `withCredentials:true` can be added to the HTTP request in 

```
        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters
        });
```

**Comment by wing328** [comment]
@xmeng1 thanks for reporting the issue. Your suggestion sounds reasonable to me as we've done something similar to JS API client: https://github.com/swagger-api/swagger-codegen/search?q=withCredentials&type=Issues&utf8=%E2%9C%93

Do you mind submitting a PR so that we can review the fix?

Please also checkout the `typescript-angular2` client in `2.3.0`, which contains enhancements and breaking changes.

**Comment by xmeng1** [comment]
@wing328  OK, let me try the latest firstly.

**Comment by xmeng1** [comment]
I have modified the template and submit a PR. thanks
https://github.com/swagger-api/swagger-codegen/pull/5380

**Comment by kernwig** [comment]
I don't use cookies for authentication. Adding withCredentials:true broke everything for me. This should not be default behavior.

`XMLHttpRequest cannot load https://--server--/api/User/GetUser. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by wing328** [comment]
@kernwig what about adding `withCredentials` as a property to the configuration object and default  to false to keep the previous behaviour? 

Ref: https://github.com/xmeng1/swagger-codegen/blob/eac2533b55510d8eb8c9b8692850402291839d08/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L27

**Comment by xmeng1** [comment]
@kernwig  sorry for the effect. @wing328 I agree with you, add configuration and default value is `false`. If the user wants to get the api for authentication, just as configure such as `--withCredentials=ture` .

**Comment by wing328** [comment]
@xmeng1 no worry. Do you mind submitting a PR with the suggested fix when you've time?

**Comment by kernwig** [comment]
Yes @wing328, that would be perfect.

**Comment by xmeng1** [comment]
@wing328 @kernwig  That's OK. Let me review it tonight.

**Comment by mdkannan** [comment]
Hi All,
Thanks and i too try to find same but my question is that these following lines are working fine in  Angular1.x. i need to do same kind of configuration in angular4. Please help to write at common place or generic ways to config in angular4.
config(['$httpProvider',
                       function($httpProvider) {
    	
    	//To attach cookies in response during rest api call
    	$httpProvider.defaults.withCredentials = true;
    	$httpProvider.interceptors.push('httpInterceptor');
    }])

**Comment by xmeng1** [comment]
@mdkannan cannot understand what you mean. Currently, the configuration is the injectable for the API, so you can inject the value of withCredentials as true in the Angular 2+ project. such as:
```
{provide: Configuration, useValue: {withCredentials: true}},
```

**Comment by mdkannan** [comment]
@xmeng1  you are almost got it what i expect. 
shall i use this in app.module.ts as one time configuration ?? is it possible?. if it is possible. how can i inject?

**Comment by xmeng1** [comment]
you can inject it like that for global app in app module: 
```
{provide: Configuration, useValue: {withCredentials: true}},
```

**Comment by Polyterative** [comment]
Any news on this issue?
Can't I add a flag to the .json file and automatically add the configuration everywhere?

**Comment by xmeng1** [comment]
@Polyterative  
you can inject it like that for the global app in `app.module.ts`: 
```
{provide: Configuration, useValue: {withCredentials: true}},
```
then the configuration will be appled overall the application

**Comment by adamfellon** [comment]
@xmeng1 In your example is the ```Configuration``` a custom injectable or is that something that is in angular core?

**Comment by xmeng1** [comment]
not custom, it is defined in the generated code and can be imported to the app.module.ts

    import {Configuration} from './swagger/configuration';

**Comment by xmeng1** [comment]
@adamfellon , the is the content of the generated file: `swagger / configuration.ts`

```
export interface ConfigurationParameters {
    apiKeys?: {[ key: string ]: string};
    username?: string;
    password?: string;
    accessToken?: string | (() => string);
    basePath?: string;
    withCredentials?: boolean;
}

export class Configuration {
    apiKeys?: {[ key: string ]: string};
    username?: string;
    password?: string;
    accessToken?: string | (() => string);
    basePath?: string;
    withCredentials?: boolean;

    constructor(configurationParameters: ConfigurationParameters = {}) {
        this.apiKeys = configurationParameters.apiKeys;
        this.username = configurationParameters.username;
        this.password = configurationParameters.password;
        this.accessToken = configurationParameters.accessToken;
        this.basePath = configurationParameters.basePath;
        this.withCredentials = configurationParameters.withCredentials;
    }
}
```

**Comment by xmeng1** [comment]
according to 2.3.1, the Configuration class not only contains property but also has several methods. So don't use ~~`{provide: Configuration, useValue: {withCredentials: true}},`~~.  replace with :
