### ISSUE TITLE
Include Swagger Codegen version in the generated files

### ISSUE THREAD

**Issue by sonicjolt** [swagger-api/swagger-codegen#5376]
##### Description

When swagger codegen generates code, it would be very nice that it outpus which version of swagger codegen is used to generate the code. I have experienced several instances where developers have generated code with a specific version, and then forgotten which version they had used.

It seems it would be fairly easy to implement, and would save time for a lot of people.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues

N/A
##### Suggest a Fix

Include the version number of swagger codegen in the generated files.

**Comment by wing328** [comment]
@sonicjolt that's definitely a good suggestion. We do have "version" available through the command line. 
```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar version            
2.2.3-SNAPSHOT
```
It's just a matter of putting that into `additionalProperties` so that the mustache templates can reference it.

May I know if you've time to contribute the enhancement?

**Comment by elizabetht** [comment]
@wing328 I can contribute, if you can point me to the places where the version can be picked up to be added to the additionalProperties.

**Comment by wing328** [comment]
@elizabetht thanks for offering help on this. Which language generator do you want to work on? SpringMVC?

**Comment by elizabetht** [comment]
Yes, to start with, I would like Spring MVC

**Comment by elizabetht** [comment]
@wing328: where should the version be placed?

**Comment by sonicjolt** [comment]
@wing328 I'd like to have a look at the AbstractCSharp

**Comment by sonicjolt** [comment]
@wing328 Is the version-number of swagger-codegen available somehow ? I can see it's defined in swagger-codegen/modules/swagger-codegen/pom.xml 

And if that is the case, do I simply need to add a line of code to swagger-codegen/modules/swagger-codegen/src/main/resources/csharp/partial_header.mustache ?

If I'm wrong, could you please help me a long a bit, thanks :)

**Comment by wing328** [comment]
@elizabetht @sonicjolt Let me see if I can create a quick example. Stay tuned.

**Comment by wing328** [comment]
Seems like it's not that straghtforward. Here are some pointers:

1) Here is how Swagger Codegen CLI obtains the "version": https://github.com/swagger-api/swagger-codegen/blob/e633073082ecb575627c3ba0b7b757b19c86e326/modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/SwaggerCodegen.java#L25

2) After obtaining the version, we will need to store that in `additionalProperties`: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L129

e.g. `config.additionalProperties().put("generatorVersion", version);`

3) then we can use `{{{generatorVersion}}}` in the mustache template

For Spring, we will need to add a comment section (header) similar to the following in PHP templates:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L13-L17

Then we can update the header as follows:
```
/**
 * NOTE: This class is auto generated by the swagger code generator program ({{{generatorVersion}}}).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
```

**Comment by elizabetht** [comment]
@wing328 I followed your notes. But when the files get generated the generatorVersion is coming back as "unset". Is there anything I should specifically set?
See the PR: https://github.com/swagger-api/swagger-codegen/pull/5449

**Comment by sonicjolt** [comment]
@wing328 @elizabetht I have the same issue with not getting the version info from the pom.xml-file using the suggested method.

**Comment by wing328** [comment]
@elizabetht thanks for the PR, which is definitely a good start. I'll look into this more over thew weekend.

**Comment by nbruno** [comment]
You won't be able to use the `Version.readVersionFromResources();` method in the manner that is attempted in the PR. This method works because during the Maven build, the [original resource file](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-cli/src/main/resources/version.properties) gets [filtered](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-cli/pom.xml#L21) (i.e. has its placeholders interpolated) with the values from the POM, and the final result is what is stored in the CLI JAR. At runtime, the `Version` helper just reads this properties file off the classpath.

To bring this functionality to the core `swagger-codegen` module, you'll need to follow a similar path - Currently, resources are not filtered in that module.

**Comment by wing328** [comment]
@nbruno thanks for sharing more on how to bring similar functionality to swagger-codegen module.

**Comment by wing328** [comment]
Hi all, I've added a hard-coded version via https://github.com/swagger-api/swagger-codegen/pull/5459 for the time being. We'll need to file another PR later to obtain the version from the resource file.

**Comment by elizabetht** [comment]
@nbruno I have updated the PR filtering the version.properties that I moved to swagger-codegen module (from swagger-codegen-cli module). Even then, I get "unset" as the verison. Any idea where I am going wrong?

**Comment by elizabetht** [comment]
@nbruno @wing328 I have moved the version.properties to swagger codegen module (from swagger codegen cli module) and added filtering for the version.properties resource file. I am able to see version.properties under /modules/swagger-codegen/target/classes/version.properties with the following content
```
cat ./modules/swagger-codegen/target/classes/version.properties
version = 2.2.3-SNAPSHOT
```

@wing328 I also removed your hard-coded version from DefaultGenerator.java

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/issues/5556 has been merged into master.

Please pull the latest master to give it a try.

**Comment by elizabetht** [comment]
@wing328 Submitted #5691 for this issue. Please take a look and let me know your comments

**Comment by wing328** [comment]
I've created https://github.com/swagger-api/swagger-codegen/issues/5998 to track all languages.

Closing this one.
