### ISSUE TITLE
Definitions Of Non-Aggegate Types Generate Empty Classes

### ISSUE THREAD

**Issue by bbdouglas** [swagger-api/swagger-codegen#5382]
##### Description

When you have a definition that is a simple type (such as "string", "number", "boolean") the class generated for it is empty. This makes the class unusable for serializing/deserializing since it holds no data.

##### Swagger-codegen version

Current

##### Swagger declaration file content or url

    definitions:
      JustABoolean:
        type: boolean

Becomes

    public class JustABoolean {
      // Note, no member variables, getters, setters, etc
      @Override
      public boolean equals(java.lang.Object o) {...}
      @Override
      public int hashCode() {...}
      @Override
      public String toString() {...}
      private String toIndentedString(java.lang.Object o) {...}  
    }

##### Command line used for generation

    -l java

##### Steps to reproduce

Any definition that isn't declared as type "object" or "array" will exhibit this behavior.

##### Related issues

I couldn't find a related issue.

##### Suggest a Fix

I can imagine two possible fixes.

* Create wrappers around all the non aggregate types. This might get a little tedious for each language/library, but since the number of types is small it is doable. The only downside I see is extra boilerplate.

    request.setMyJustABoolean(new JustABoolean(true))

* Replace the definition name with the underlying class name. That is, instead of creating a new JustABoolean class, use Boolean everywhere you would have used JustABoolean. This makes the client code a little cleaner, at the expense of making swagger-codegen potentially more complicated. It also obscures a bit of what's going on.

    request.setMyJustABoolean(true);

I thought about extending the simple types (Boolean, String, BigDecimal, etc), but that has its own problems. String, for example, is declared `final` and so can't be extended and BigDecimal can't be constructed directly from another BigDecimal :/

**Comment by wing328** [comment]
Closed via #5408
