### ISSUE TITLE
Object type not identified in swift 3

### ISSUE THREAD

**Issue by bharathreddy-97** [swagger-api/swagger-codegen#5397]
[Swift 3]Bug

Swagger generated this method

open class func addEmails(lbid: Int64, lasid: Int64, luid: Int64, attachment: URL? = nil, lupid: Int64? = nil, ptype: String? = nil, emailAddRequest: AttObject? = nil, completion: @escaping ((_ data: AttSuccessResponse?,_ error: Error?) -> Void))

I am getting error as "Use of Undeclared type 'AttObject' ". 'Att' is the prefix we gave for models while generating.

Swagger json:

          {
            "name": "emailAddRequest",
            "in": "formData",
            "required": false,
            "type": "ref"
          }
Type is ref which is generic type I guess. For Swift 3 this should generate Any instead of Object right?

**Comment by wing328** [comment]
> Type is ref which is generic type I guess

`ref` is not a valid type

Given that it's a form parameter, my guess is that it should be a `string` instead.

**Comment by bharathreddy-97** [comment]
In android when we tried it is generating Object Type. Similarly should it not generate Any Type in swift 3?

**Comment by wing328** [comment]
@bharathreddy-97 again I don't think the spec is valid (even though may other generators can generate something out of it)
