### ISSUE TITLE
[Android] Bug generating parcelables constructors for custom classes ( missing getClassLoader() )

### ISSUE THREAD

**Issue by guidovezzoni** [swagger-api/swagger-codegen#5425]
##### Description

When creating a parcelable for a custom class containing an instance of another custom class, the code will try to use the default loader rather than adding `class.getClassLoader()`.

For example in the pet store sample Pet.java constructor reads:
```
  Pet(Parcel in) {
    
    id = (Long)in.readValue(null);
    category = (Category)in.readValue(null);
    name = (String)in.readValue(null);
    photoUrls = (List<String>)in.readValue(null);
    tags = (List<Tag>)in.readValue(Tag.class.getClassLoader());
    status = (StatusEnum)in.readValue(null);
  }
```
However the `category` line should be:
`category = (Category)in.readValue(Category.class.getClassLoader());`
as flagged also by Android Studio.

##### Swagger-codegen version

Tested with 2.2.2 and the latest master generating the JAR locally

##### Command line used for generation

Tested this on the provided pet sample with `./bin/java-petstore-okhttp-gson-parcelable.sh`

##### Steps to reproduce

I followed the [Getting Started](https://github.com/swagger-api/swagger-codegen#getting-started) and run `./bin/java-petstore-okhttp-gson-parcelable.sh`

##### Related issues

None found

##### Suggest a Fix / Workaround

I modified [pojo.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/pojo.mustache).

The current constructor is:
```
  {{classname}}(Parcel in) {
    {{#parent}} super(in); {{/parent}}
    {{#vars}}
    {{#isContainer}}
    {{#complexType}}
    {{name}} = ({{{datatypeWithEnum}}})in.readValue({{complexType}}.class.getClassLoader());
    {{/complexType}}
    {{^complexType}}
    {{name}} = ({{{datatypeWithEnum}}})in.readValue(null);
    {{/complexType}}
    {{/isContainer}}
    {{^isContainer}}
    {{name}} = ({{{datatypeWithEnum}}})in.readValue(null);
    {{/isContainer}}
    {{/vars}}
  }
```

My patched version is

```
  {{classname}}(Parcel in) {
    {{#parent}} super(in); {{/parent}}
    {{#vars}}
    {{#isPrimitiveType}}
    {{name}} = ({{{datatypeWithEnum}}})in.readValue(null);
    {{/isPrimitiveType}}
    {{^isPrimitiveType}}
    {{name}} = ({{{datatypeWithEnum}}})in.readValue({{complexType}}.class.getClassLoader());
    {{/isPrimitiveType}}
    {{/vars}}
  }
```

With the change it seems to work as expected, although I'm not completely sure about the correct use of the tokens: `{{#isContainer}}` `{{#complexType}}` `{{#isPrimitiveType}}`.

Any suggestions/recommendations are welcome.
Thanks

**Comment by wing328** [comment]
@guidovezzoni thanks for reporting the issue. I wonder if you can submit a PR with the suggested fix so that we can review the fix more easily.

**Comment by guidovezzoni** [comment]
Yes sure, will do that asap.

**Comment by wing328** [comment]
@guidovezzoni thanks. I've added some explanations of mustache tags in https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables#explanations

**Comment by guidovezzoni** [comment]
Thanks @wing328 
I had some doubts about the definition of primitive, but now I think I understand.

PR ready: https://github.com/swagger-api/swagger-codegen/pull/5483
