### ISSUE TITLE
[Objc] Class not identified due to Circular imports

### ISSUE THREAD

**Issue by bharathreddy-97** [swagger-api/swagger-codegen#5440]
I generated Objective C files using Swagger Codegen using following command:

java -jar swagger-codegen-cli.jar generate -i {url} -l objc -o {folderPath}

I was able to generate correctly but when i added to my project I was getting compile time errors. Some Classes were not identified. The main issue to due to circular imports. A.h imports B.h and B.h imports A.h. B is not identified in A. 

I fixed it by adding @class <className>,@protocol <name> at the top but is there any way to auto-generate using codegen and prevents these errors??

**Comment by wing328** [comment]
@bharathreddy-97 can you share a bit more on where you add `@class`, `@protocol`?

**Comment by bharathreddy-97** [comment]
When i first generated this is one class which got generated

#import "SWGUserProfile.h"


@protocol SWGUserRegistration
@end

@interface SWGUserRegistration : SWGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* login;

@property(nonatomic) NSString* password;

@property(nonatomic) NSString* token;

@property(nonatomic) NSString* registrationStatus;

@property(nonatomic) NSDate* expiryDate;

@property(nonatomic) NSString* registrationSource;

@property(nonatomic) NSString* registrationType;

@property(nonatomic) SWGUserProfile* userProfileId;

@property(nonatomic) NSDate* dob;

@end

Though UserProfile.h is imported variable SWGUserProfile is not identified. I added @class above @protocol SWGUserRegistration line for SWGUserProfile to be identified.

**Comment by wing328** [comment]
@bharathreddy-97 one way is to update the templates: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/objc

Would you have time to contribute a PR for the suggested fix using @class, @protocol ?

**Comment by alexandern** [comment]
@bharathreddy-97  Can you share the yams here, I'd like to see if I can fix this issue

**Comment by alexandern** [comment]
Here is an example that illustrates the issue

```
swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger ABC
  license:
    name: MIT
basePath: /fooapi
paths:
  /sample:
    get:
      parameters:
        - name: limit
          in: query
          type: integer
          format: int32
      responses:
        "200":
          description: Array of foos
          schema:
            $ref: '#/definitions/Foo'
definitions:
  Foo:
    type: object
    properties:
      rxBar:
        $ref: '#/definitions/Bar'
      person:
        $ref: '#/definitions/Person'
  Bar:
    type: object
    properties:
      rxFoo:
        items:
          $ref: '#/definitions/Foo'
        type: array
      statusMessage:
        type: string
      person:
        $ref: '#/definitions/Person'
  Person:
    type: object
    properties:
      names:
        items:
          type: string
```

The aforementioned solution would be to change the model-header.mustache as follows

```
#import <Foundation/Foundation.h>
#import "{{classPrefix}}Object.h"

{{>licenceInfo}}

{{#imports}}#import "{{import}}.h"
{{/imports}}
{{#imports}}
@protocol {{import}};
@class {{import}};
{{/imports}}

{{newline}}
{{#models}}
{{#model}}

@protocol {{classname}}
@end

@interface {{classname}} : {{#parent}}{{{parent}}}{{/parent}}{{^parent}}{{classPrefix}}Object{{/parent}}

{{#vars}}
{{#description}}/* {{{description}}} {{^required}}[optional]{{/required}}
 */{{/description}}
@property(nonatomic) {{{ datatype }}} {{name}};
{{/vars}}

@end
{{/model}}
{{/models}}

```

This in turn would generate code like

```
#import "SWGBar.h"
#import "SWGPerson.h"
@protocol SWGBar;
@class SWGBar;
@protocol SWGPerson;
@class SWGPerson;

@protocol SWGFoo
@end

@interface SWGFoo : SWGObject
@property(nonatomic) SWGBar* rxBar;
@property(nonatomic) SWGPerson* person;
@end

```

**Comment by alexandern** [comment]
I will ask others to peer review

**Comment by wing328** [comment]
@alexandern thanks. If you submit a PR with the suggested fix, we can use the CI (travis) to test the updated ObjC Petstore client.

**Comment by alexandern** [comment]
@wing328 I will run the UTs and submit the PR.

**Comment by wing328** [comment]
@bharathreddy-97 The fix by @alexandern has been merged into master. Please pull the latest master to give it a try.
