### ISSUE TITLE
Update from Oracle JDK to OpenJDK

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#5444]
For licensing reasons, makes sense to switch to openjdk

**Comment by ePaul** [comment]
Could we get some more details?

I guess you mean to switch from Oracle's JDK to OpenJDK, for the docker images?
Which licensing reasons are that?

**Comment by wing328** [comment]
@ePaul I think the move was to avoid "potential" licensing issue with Oracle JDK. Here is a news article related to that:

https://www.theregister.co.uk/2016/12/16/oracle_targets_java_users_non_compliance/

**Comment by ePaul** [comment]
Thanks. (But could you please change "jdk" in the title to "Oracle JDK"?)

**Comment by wing328** [comment]
Updated.
