### ISSUE TITLE
[typescript/angular2] Implement interfaces for api resources

### ISSUE THREAD

**Issue by kirpit** [swagger-api/swagger-codegen#5453]
##### Description

Currently, generated api files consist of bare classes for typescript / angular2. We are happy to have them as is but would like to make implemented alongside with their interfaces so we can create our own behaviours.

To extend a bit, depending on development scenario we sometimes want api resources to use local storage or json fixtures rather than querying our api endpoint. Therefore, would like to be able to implement its interface and overwrite the generated class.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

```yaml
paths:
  /user:
    get:
      operationId: getUsers
      summary: Returns all users.
```
Currently generated:
```typescript
export class UsersApi {
   // snipped..
}
```
Proposed:
```typescript
export interface IUsersApi {
  // snipped.
}

export class UsersApi implements IUsersApi {
  // snipped.
}
```

##### Related issues

Improve TypeScript Template #1334

##### Suggest a Fix

I am happy to spend my time, keeping in mind that I'm new to the java and typescript world.

**Comment by wing328** [comment]
@kirpit thanks for offering help on this. Do you need some good starting points on where to start?

The change should be made against 2.3.0 as it should be a breaking change if I understand correctly.

**Comment by kirpit** [comment]
@wing328 I was actually able to make this change only by modifying the `api.mustache` file without changing any single line in the java code and I can't really find any good reason that it is a breaking change.  Same classes are still present with the exact same methods and signatures..

One important heads up though that constructor method definition for interfaces in typescript has a bit different behaviour; check out [this](http://stackoverflow.com/questions/13407036/how-does-typescript-interfaces-with-construct-signatures-work) and [that](http://stackoverflow.com/questions/34074244/interface-with-constructor-inside-implement-questoin). I personally would leave the constructor method definition away from its interface since it brings too much complexity and some of its parameters are actually irrelevant to the classes with different behaviours. However it sounds more like a design decision and will probably affect the planned implementation about converting models from pure interfaces to classes as well (see #1334).

**Comment by wing328** [comment]
> I was actually able to make this change only by modifying the api.mustache file without changing any single line in the java code and I can't really find any good reason that it is a breaking change. Same classes are still present with the exact same methods and signatures..

If the change is transparent to the developers consuming the TS Angular2 SDK (before and after the change), then please file it against the current master.

We don't have Petstore integration tests for TS Angular2 at the moment. A good starting point is to reference those created for TS Fetch Petstore client: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-fetch/tests/default

**Comment by kirpit** [comment]
Well after quite the experiment, found out it's not a good idea to create the interfaces within same resource files because of angular/angular-cli#2034. Unfortunately, that issue is not treated as priority to my understanding either. As a result, I probably need to change some java code as well, to create them in a separate file.

I also would like to define some sort of generation parameter flag specific to typescript/angular2 so we can have something like `<createInterfaces>true</createInterfaces>`, which can be perhaps `false` by default. I heard from my colleague there is one for java..

I will also much appreciate if you could point me the starting point for regarding java tests. Perhaps the petstore again?

**Comment by wing328** [comment]
@kirpit what about using the "-t" option to use your own customized templates?

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-customize-the-template-to-add-headerfooter-to-the-auto-generated-code

**Comment by kirpit** [comment]
@wing328 yeah actually also tried that but it is not capable of creating the interfaces in a separate file..

**Comment by kirpit** [comment]
Hi @wing328, please have a look at the PR #5519.

**Comment by kirpit** [comment]
I believe the PR is good to go with the unit tests have been fixed.

**Comment by chiragmaheshwari** [comment]
Hi..I want to integrate swagger codegen with my angular 4 application, please let me know any starting point for this...
