### ISSUE TITLE
How to enable more language in swagger codegen?

### ISSUE THREAD

**Issue by ChandrakantRathod** [swagger-api/swagger-codegen#5464]
##### Description

I have downloaded swagger codegen from Github. Currently its allow to generate only 8 languages for client code generation by default like below...

Curl, Java, Android, Obj-C, JavaScript, C#, PHP, Perl, Python

We want additional languages support like below...
Raw, cURL, Node.js, Ruby, Go, Visual Basic, Groovy, Swift

We want a rest of languages support for client code. 

Do we need to change any configuration in the code to provide the rest of the languages?
or
Do we need to write client templates for rest the languages?

**Can you please guide us? Prompt reply is highly appreciated**

##### Swagger-codegen version
2.3.0  | Apr/May 2017   | 1.0, 1.1, 1.2, 2.0   | Minor release with breaking changes

**Comment by wing328** [comment]
@ChandrakantRathod swagger codegen supports the following generators (client, server documentation).
```
aspnet5
aspnetcore
async-scala
bash
cwiki
csharp
cpprest
dart
elixir
flash
python-flask
go
groovy
java
jaxrs
jaxrs-cxf-client
jaxrs-cxf
jaxrs-resteasy
jaxrs-resteasy-eap
jaxrs-spec
jaxrs-cxf-cdi
inflector
javascript
javascript-closure-angular
jmeter
nancyfx
nodejs-server
objc
perl
php
python
qt5cpp
ruby
scala
scalatra
finch
silex-PHP
sinatra
rails5
slim
spring
java-play-framework
dynamic-html
html
html2
swagger
swagger-yaml
swift
swift3
tizen
typescript-angular2
typescript-angular
typescript-jquery
typescript-node
typescript-fetch
akka-scala
CsharpDotNet2
clojure
haskell
lumen
go-server
erlang-server
undertow
msf4j
ze-ph
```
which covers what you need except Visual Basic, "cURL", Raw (?)

To add new client generator, https://github.com/swagger-api/swagger-codegen/wiki/How-to-add-a-generator-for-a-new-language-or-framework is a good starting point.

**Comment by ChandrakantRathod** [comment]
![image](https://cloud.githubusercontent.com/assets/26959397/25341830/cc17dd32-2927-11e7-970c-10f8f1e565b4.png)

I downloaded swagger codegen from github and setup local system and when i generated client for html2 then i have code for only eight languages which i have mentioned in my question and as shown in the above image. I know that swagger support all the languages which you mentioned then my problem is i can see client code for only eight languages?

**Comment by wing328** [comment]
Currently, `html2` does not support code samples for **all** languages. If you want to add code samples for other langauges, https://github.com/swagger-api/swagger-codegen/pull/4575 is a good reference.

Most API client also comes with auto-generated documentation (markdown) with code samples: https://github.com/swagger-api/swagger-codegen/issues/2359

**Comment by ChandrakantRathod** [comment]
Thanks a lot for prompt reply...:)

**Comment by wing328** [comment]
No problem. Let us know if you've further question or you want to work on the enhancement.
