### ISSUE TITLE
Add a "Validate" option to Swagger Codegen

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5466]
##### Description

Currently Swagger Codegen supports the following options:
```
swagger-codegen|master ⇒ swagger-codegen help
usage: swagger-codegen-cli <command> [<args>]

The most commonly used swagger-codegen-cli commands are:
    config-help   Config help for chosen lang
    generate      Generate code with chosen lang
    help          Display help information
    langs         Shows available langs
    meta          MetaGenerator. Generator for creating a new template set and configuration for Codegen.  The output will be based on the language you specify, and includes default templates to include.
    version       Show version information

See 'swagger-codegen-cli help <command>' for more information on a specific
command.
```

We want to add another option "validate" to validate the Swagger/OpenAPI spec and show human-readable result.

Ref: https://github.com/swagger-api/swagger-parser/issues/46#issuecomment-150605901

##### Swagger-codegen version

Latest master

##### Suggest a Fix
If anyone from the community wants to contribute this enhancement, please let us know. https://github.com/swagger-api/swagger-parser/issues/46#issuecomment-150605901 is a good starting point.

**Comment by taxpon** [comment]
@wing328 I am interested in working on this issue. Please wait for while before sending PR.

**Comment by wing328** [comment]
@taxpon thanks for the PR 👍 

@kenjones-cisco please pull the latest master to give it a try.

**Comment by kenjones-cisco** [comment]
@wing328 The validate option works as expected.
There are some other issues in master currently. But they are unrelated to this change.

Great job! @taxpon Thanks!

**Comment by wing328** [comment]
> There are some other issues in master currently.

Can you please elaborate on that?

**Comment by kenjones-cisco** [comment]
I am making note as I go through all the latest changes.

**Comment by kkms** [comment]
I'm see this issue in io.swagger.codegen.v3 version 3.0.20, Generated API class don't have @Validated
