### ISSUE TITLE
Swagger Codegen for Javascript throws NullPointerException for missing version in swagger json

### ISSUE THREAD

**Issue by erdarun** [swagger-api/swagger-codegen#5467]
##### 
version field not included in swagger json/yaml causing issue for javascript codegen but java/ruby works.

Exception in thread "main" java.lang.NullPointerException
	at io.swagger.codegen.languages.JavascriptClientCodegen.escapeQuotationMark(JavascriptClientCodegen.java:1045)
	at io.swagger.codegen.languages.JavascriptClientCodegen.preprocessSwagger(JavascriptClientCodegen.java:247)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:139)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)

##### Swagger-codegen version

swagger-codegen 2.2.2

##### Command line used for generation

swagger-codegen generate -i ./swagger.json -l javascript -o javascript/.
##### Steps to reproduce

Remove info version from swagger json/yaml

##### Suggest a Fix

Null check for info.version should be implemented

**Comment by wing328** [comment]
@erdarun can you try the latest master to see if you still encounter the same issue?

**Comment by erdarun** [comment]
Yes still the same issue in master branch too

**Comment by wing328** [comment]
For the master branch, can you help show us the stack trace?

**Comment by wing328** [comment]
Btw, version is a required field: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#info-object

**Comment by erdarun** [comment]
@wing328 
swagger-codegen/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java line no. 259

**Comment by erdarun** [comment]
Yes after adding version info it works. But null check should be added for escapeUnsafeCharacters, escapeQuotationMark methods.

As I tested Java/Ruby client codegen doesn't report any error if there is no info.version

**Comment by wing328** [comment]
@erdarun good point. Do you mind submitting a PR to avoid NPE in those methods?

**Comment by erdarun** [comment]
@wing328 Raised PR https://github.com/swagger-api/swagger-codegen/pull/5471

**Comment by wing328** [comment]
Thanks for the contribution from @erdarun 

Closing this issue.
