### ISSUE TITLE
Invalid Parameter Naming Case (TypeScript-Angular2) (Swagger-Codegen 2.2.2)

### ISSUE THREAD

**Issue by darius-iko** [swagger-api/swagger-codegen#5468]
##### Description

Parameter for API functions generated by Swagger-codegen is invalid.

![image](https://cloud.githubusercontent.com/assets/8023913/25372841/b7c17724-29c9-11e7-834f-1acae3a76e26.png)

##### Swagger-codegen version

2.2.2

##### Command line used for generation

-c config.json -l typescript-angular2

Config.json:
{
	"modelPropertyNaming" : "original"
}

##### Suggest a Fix

It should follow the parameter naming case (lowercase).

**Comment by darius-iko** [comment]
By the way, that string literal should be generated if I set supportsES6 to true. By default, it is false.

**Comment by wing328** [comment]
@darius-iko yup, that's a bug. We've fixed similar issues in other generators. I'll try to file a PR shortly to address it.

**Comment by darius-iko** [comment]
@wing328 Thank you

**Comment by wing328** [comment]
> By the way, that string literal should be generated if I set supportsES6 to true. By default, it is false.

@darius-iko can you elaborate on that by providing an example (actual output vs expected output)?

**Comment by darius-iko** [comment]
Expected output:
If the supportsES6 config is false (by default), it should use the old way by replacing the text like below:
![image](https://cloud.githubusercontent.com/assets/8023913/25374050/97404624-29ce-11e7-91c7-4b1815c201a3.png)

Actual output:
As seen at the issue posted on the top-most.

**Comment by wing328** [comment]
@darius-iko can you pull the latest master to give it a try?

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/api.mustache#L63-L65

Looks like we've fixed it already via https://github.com/swagger-api/swagger-codegen/commit/dbe99c3af92ebc4862e7984a246b9af5e707013d

**Comment by darius-iko** [comment]
@wing328 Yes, the latest master has fixed it.

**Comment by wing328** [comment]
Thanks for the confirmation. Closing the issue.

**Comment by darius-iko** [comment]
@wing328 So the version 2.2.2 cannot be used to generate TypeScript-Angular2 code and we have to wait the next version for it? When is the estimated release date for the next version?

**Comment by darius-iko** [comment]
Thanks. Version 2.2.3 is out.

**Comment by wing328** [comment]
@darius-iko yup, please give it a try and let us know if you've further feedback.
