### ISSUE TITLE
[JAVA] [Android] Android generation sending unused body parameters as null

### ISSUE THREAD

**Issue by TarekDeeb** [swagger-api/swagger-codegen#5469]
##### Description

Android client sending unused (or not set) body parameters as null. So lets say I have a function *setUser* that has *email* *age* and *phone* in the body, but I only want to set email and age. I keeo getting that *phone* is being sent as null. 

##### Swagger-codegen version

 2.2.2

##### Command line used for generation

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/path-to-yaml-file.yaml -l android --library=volley -o ~/here -v
```

**Comment by wing328** [comment]
@TarekDeeb thanks for reporting the issue. Can you please try the Java (okhttp-gson) or Retrofit2 API client to see if the same issue occurs?

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

**Comment by wing328** [comment]
@TarekDeeb do you need help generating Java API client (okhttp-gson, retrofit2)?

**Comment by TarekDeeb** [comment]
I'm sorry for not replying. I generated the Java API with okhttp-gson library, however, the codebase was built using volley which had a different structure (listeners). It was too much to edit and we simply didn't have the time. We'll make the switch very soon though, so I'll report back when we do. Thanks!
