### ISSUE TITLE
How to customize swagger client code for different languages?

### ISSUE THREAD

**Issue by ChandrakantRathod** [swagger-api/swagger-codegen#5473]
We want to customize swagger client code for different languages. The reason behind this is, instead of generating client and server code, we just wanted to create a raw client code which directly call the actual API without any dependancy of the server code (Which we generate from swagger-editor).

Do we need to manually write customize client code for each and every language? I believe there is any rare developer/company who has knowledge/competency of all these languages due to this it is very deficult to customize mustache templates for all languages.

Can you please suggest any way so that we can generate raw client code to call API directly in different languages even if we do not have competency of all required languages?

Please guide/suggest us.

Thanks in advance.

Swagger-codegen version

2.3.0 | Apr/May 2017 | 1.0, 1.1, 1.2, 2.0 | Minor release with breaking changes

**Comment by wing328** [comment]
You can simply generate API clients, server stubs or API doc using Swagger Codegen CLI. e..g https://github.com/swagger-api/swagger-codegen#getting-started without using editor.swagger.io (which relies on generator.swagger.io to generate the code and generator.swagger.io is part of the Swagger Codegen project)
