### ISSUE TITLE
[QT5CPP] Enhancement : allow to configure api and model namespace for generated code

### ISSUE THREAD

**Issue by sabras75** [swagger-api/swagger-codegen#5481]
##### Description

It is currently not possible to configure namespace in which model and API code are generated. 
The hardcoded namespace in which the code reside is 
```
namespace Swagger{
```

This is problematic when you have multiple generated code for different APIs

##### Swagger-codegen version

2.2.2

##### Command line used for generation

done through gradle swagger plugin instead of command line. Here is the section
```
...
project('swagger-qt5cpp') {
    apply plugin: 'org.hidetake.swagger.generator'
    dependencies {
        swaggerCodegen "io.swagger:swagger-codegen-cli:2.2.2"
    }
    generateSwaggerCode {
        language = 'qt5cpp'
        inputFile = file('../src/model/rest-api/swagger.yaml')
        configFile = file('../src/model/rest-api/config-qt5cpp.json')

        dependsOn clean
    }
}
...

the config-qt5cpp.json is empty

```
##### Suggest a Fix

Have similar approach than in the cppRest code generation with following 
```
CONFIG OPTIONS
	modelPackage
	    C++ namespace for models (convention: name.space.model). (Default: io.swagger.client.model)

	apiPackage
	    C++ namespace for apis (convention: name.space.api). (Default: io.swagger.client.api)
```

**Comment by sabras75** [comment]
I'll take care of this.
Any advice to how implement it is welcome

**Comment by wing328** [comment]
@sabras75 thanks. A good starting point to implement these options is as follows:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CppRestClientCodegen.java#L67-L76

**Comment by sabras75** [comment]
My first thought on using modelPackage and apiPackage appears more complicated than I expected.
Those 2 options also have an impact on subdirectories were the file will be generated and the includes to be done.
I am not confident on the way the includes are currently generated for the C++ in regards of thos e options , so I'd rather stay away of those two options and introduce an option that **only** impact the namespace (as in C++ namespace and directory are 2 distinct concepts).
So my suggested fix will be to have the following option
```
CONFIG OPTIONS
	cppNamespace
	    C++ namespace (convention: name::space::for::api). (Default: Swagger)
```
that will impact every generated file (api, model and supporting files)

@wing328 is it ok for you if I go that way ?

**Comment by wing328** [comment]
@sabras75 sounds good to me.
