### ISSUE TITLE
[C++][CppRest] Auto generate Makefile or CMake file for C++ API client

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5488]
##### Description

We want to auto-generate Makefile or CMake file for C++ (cpprest) API clients so that the developers can build the client more easily.

Here are some examples of Makefiles/CMakefile:

https://github.com/rahuliyer/dropbox-cpp/blob/master/Makefile
https://github.com/swatkat/twitcurl/blob/master/twitterClient/Makefile
https://github.com/aws/aws-sdk-cpp/blob/master/aws-cpp-sdk-s3/CMakeLists.txt
https://github.com/Affectiva/cpp-sdk-samples/blob/master/CMakeLists.txt

##### Swagger-codegen version

Latest master

##### Suggest a Fix

If anyone wants to work on this enhancement, please reply to let us know.

**Comment by ravinikam** [comment]
I will give it try.

**Comment by wing328** [comment]
@ravinikam thanks. Let us know if you need any help (e.g. testing)

**Comment by wing328** [comment]
Closed via #5561
