### ISSUE TITLE
If i use multiple yaml files in my swagger specification file then swagger code generator is not working.

### ISSUE THREAD

**Issue by ChandrakantRathod** [swagger-api/swagger-codegen#5492]
If I use multiple yaml files in my swagger specification file then swagger code generator is not working as shown below.

![image](https://cloud.githubusercontent.com/assets/26959397/25536269/ce8d3eb2-2c57-11e7-89fa-d02e8f6e39a3.png)

But swagger editor and swagger UI is working ok.

Can you please check the issue or guide us am i doing anything wrong here.

Thanks in advance.

##### Swagger-codegen version

2.3.0 | Apr/May 2017 | 1.0, 1.1, 1.2, 2.0 | Minor release with breaking changes

**Comment by loeti** [comment]
I had similar problems. Additionally I tried to use subfolders. In the 'paths' context I have to define the references as follows:
properties:
  owner:
     $ref: './shared/base.yaml#/definitions/Owner'

But in the definitions part it has to be:
categories:
          description: Available asset categories for filtering provided as selectable items
          type: array
          items:
            $ref: './../shared/base.yaml#/definitions/Selectable'

**Comment by fehguy** [comment]
Multiple yaml or JSON files are certainly supported.  Please share a specific specification in the [swagger-parser](https://github.com/swagger-api/swagger-parser) project, which is what deals with this sort of resolution.

**Comment by loeti** [comment]
@fehguy That's true but there are bug's and it is a difference if you can open and validate a OpenApi specification in multiple files in the web editor or afterwards generate code out of them. I'm working on  a large  specification and I experienced the problems.

**Comment by ChandrakantRathod** [comment]
Let me explain more in details,

I have downloaded swagger-editor source code and established the project in my local system.

My main/parent swagger specification I have directly write in the local swagger editor as shown below
![image](https://cloud.githubusercontent.com/assets/26959397/25475004/f6aa6c5e-2b52-11e7-8da8-4328fc14b00b.png)

I have created two reference .yaml files as shown below.
1) Posts_PostPutGet.yaml
![image](https://cloud.githubusercontent.com/assets/26959397/25475176/85ad9926-2b53-11e7-929c-34f582c174c3.png)

2) Posts_Delete.yaml
![image](https://cloud.githubusercontent.com/assets/26959397/25475077/38c288ec-2b53-11e7-922e-726f19f09a7c.png)

I have put both reference .yaml files in root folder of the swagger-editor project as shown below.
![image](https://cloud.githubusercontent.com/assets/26959397/25474903/80cb15a6-2b52-11e7-9f0a-3ca558ef1c8a.png)

Now, as shown in the below, swagger editor is show correct UI.
![image](https://cloud.githubusercontent.com/assets/26959397/25475472/8115ca90-2b54-11e7-8a35-8264eb57b7ca.png)

But problem is when I try to generate client -> "Html2" i got below error.
Step-1: ![image](https://cloud.githubusercontent.com/assets/26959397/25475620/f5f9dca2-2b54-11e7-8fc0-bea0e6cbf5c5.png)
Step-2: ![image](https://cloud.githubusercontent.com/assets/26959397/25475639/07b2f5d2-2b55-11e7-94fe-0f5c68d6cd09.png)

Can you please suggest what i did wrong here 'or' can you please guide me?

Thanks in advance.

**Comment by fehguy** [comment]
OK well this helps.  Think of it like this--you have the editor running on your local network and the codegen is running as a web service out on the internet.  When you generated code, as you can see in the network tab, we are posting the specification up to the online codegen running out on the cloud.  That specification is then used to generate code.

If you have relative files on your local network, it is impossible for the codegen to find them.  You're sending a specification to the codegen in a POST, and there is no "relative path".

So if you want codegen to work from the editor, you either need (a) everything to be in the document that you are posting up, or (b) use full URLs to any referenced resources.  Given the context I just gave as to how this is deployed, you'll see that relative references doesn't make sense, and should never work in this scenario.

**Comment by ChandrakantRathod** [comment]
Thanks for prompt reply.

Swagger editor of my local system is refering/pointing to my swagger codegen project which i have established in my local system only.

Instead of multiple .yaml files, if I keep only single swagger specification file then it generate properly according to my custom .mustache template. But its create problem when i use multiple .yaml files.

**Comment by fehguy** [comment]
It still doesn't matter because of how definitions are passed to codegen.  They are POSTed (look at the network request) and because of there, there is no notion of a relative path.  So even if you host it, that mechanism doesn't work.

In order to have a relative path, you'll need to _serve_ your definition somewhere, along with the multiple files.  Then when you codegen, you would point it to that definition via URL, then the codegen can find the files.

**Comment by ChandrakantRathod** [comment]
As you suggested i have serve/host my two reference .yaml files files on microsoft iis server like below.
1) Posts_PostPutGet.yaml
![image](https://cloud.githubusercontent.com/assets/26959397/25479225/c9bf7054-2b61-11e7-892c-73530aabcf9f.png)

2) Posts_Delete.yaml
![image](https://cloud.githubusercontent.com/assets/26959397/25479199/afcfa8f8-2b61-11e7-8c85-52a249cc7707.png)

Also, refered the same path in my main swagger specification file like below.
![image](https://cloud.githubusercontent.com/assets/26959397/25479337/191d3910-2b62-11e7-960f-b892463c8773.png)

"Then when you codegen, you would point it to that definition via URL":
Can you please tell me from where i can point this URL from swagger codegen?

Please correct me if i have done anything wrong

Thanks in advance.

**Comment by fehguy** [comment]
Ok, what you have done should work as-is.  When I was saying for codegen was if you don't have absolute references.  So try with your definition like this and report back?

**Comment by ChandrakantRathod** [comment]
I tried above what i mentioned and i got sme error like mentioned above.

**Comment by fehguy** [comment]
Are you sure you're calling your internal version of the codegen service?  Check your network tab to make sure it's not going to generator.swagger.io because there's no way that server can reach your internal network.

**Comment by ChandrakantRathod** [comment]
I checked my network request and found below. 
![image](https://cloud.githubusercontent.com/assets/26959397/25481194/b717f054-2b69-11e7-8e23-67d7a4bdb17a.png)

When I open/hit that link then i get below output.
![image](https://cloud.githubusercontent.com/assets/26959397/25481273/0bd7141c-2b6a-11e7-8724-044387db1d85.png)

Is there anything wrong here?

**Comment by wing328** [comment]
@ChandrakantRathod please let us know if it's still an issue

**Comment by maheshmahadevan** [comment]
Hi, I am facing similar problems with multi yaml projects having directories , also my definition yaml files refer definitions from other yaml files.  I am using swagger version 2.1.6

**Comment by wing328** [comment]
Can you please try the latest version 2.3.0 locally?

**Comment by maheshmahadevan** [comment]
Yes ,that could be an option and i believe that will solve it , but the issue is we do have customized the code gen for our specific needs on top of 2.1.6 version . I had tried previously to change the version to 2.3.0 but it caused some breaks since there were quite a few custom templates not specific to newer version of codegen. I am looking for a way to fix this within this same version . Any thoughts on how i can achieve this ??

**Comment by wing328** [comment]
2.1.6 is likely using a very old version of Swagger Parser. You may want to update it to the latest version but likely you need to make some manual modification.

You may also consider using 2.3.0 version but using 2.1.6 templates with the `-t` option.

**Comment by francescobianco** [comment]
@ChandrakantRathod I suggest you to avoid $ref tag it is not flexible use an external parser from command-line to build a composed file like this https://github.com/javanile/yamlinc @wing328

**Comment by mapad** [comment]
It is possible to resolve all ref to build a single swagger.json using this: https://github.com/mohsen1/multi-file-swagger-example . This solved the problems I had with swagger-codegen toolchain without changing the splitted swagger files.
