### ISSUE TITLE
[Typescript][Fetch] configurable BASE_PATH

### ISSUE THREAD

**Issue by mulles3008** [swagger-api/swagger-codegen#5494]
Hi,

I wonder if there is an easy way of having a configurable `BASE_PATH` as I need to switch between different hosts depending on the current environment (production and dev). This should be a common scenario in my opinion.

I realize that there are (at least) 2 solutions:
1. Adjusting the `host` and/or `basePath` fields in the definition file
2. Passing the desired base url to constructor function of each concrete API.

But I believe both options are far from ideal.
1. This means that one needs multiple definition files (i.e. one for production, one for dev) and these need be kept in sync... Also one needs to switch between the production- and the dev-version of the generated clients depending on the environment. 
2. Is OK but tedious nonetheless (especially for large APIs) as one has to repeat the base url whenever one instantiates a concrete API.

Configuring the base url only once in centralized fashion would be less error-prone and much more convenient.

Thanks for any suggestions!

**Comment by wing328** [comment]
I think the following PR is related to your suggestion:

https://github.com/swagger-api/swagger-codegen/pull/3403

**Comment by mulles3008** [comment]
Oh... thx! Will definitely have a look at it!

**Comment by zwenza** [comment]
@wing328 this is still a issue in the typescript-fetch templates.

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache#L9

I found no way to override the base-path for all APIs, instead you currently need to configure each API in each usage on their own.

Is there any plan to change this?

**Comment by wing328** [comment]
@zwenza the configuration object also contains the `basePath` parameter: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-fetch/configuration.mustache#L46

Is that what you're looking for?
