### ISSUE TITLE
Swagger UI - Can we add new button like "Try it out"?

### ISSUE THREAD

**Issue by ChandrakantRathod** [swagger-api/swagger-codegen#5508]
Swagger UI - Can we add new button like "Try it out"?

![image](https://cloud.githubusercontent.com/assets/26959397/25554750/ce725552-2cf2-11e7-96bc-fa6508466bc8.png)

I have to change name of button "or" wanted to add new button similar like "Try it out" button. 
Can we do?

At present I have downloaded source code from below link
GitHub: https://github.com/swagger-api/swagger-ui

But in that source code i have minfied code in below files in /dist folder
1) swagger-ui.js 
2) swagger-ui-bundle.js

![image](https://cloud.githubusercontent.com/assets/26959397/25528138/de649178-2c39-11e7-85fe-3b8cf84bf90e.png)

From where can I download original source code of swagger UI, so that instead of minified file i can change in actual file and check it?

Can anyone help me on this?

Thanks in advance.

##### Swagger-codegen version
swagger-ui, 3.x.

**Comment by ChandrakantRathod** [comment]
Hi

Can anyone please help me on my issue?

**Comment by wing328** [comment]
For feedback/question related to Swagger UI, please report to https://github.com/swagger-api/swagger-ui
