### ISSUE TITLE
Sample generating sh/bat scripts not in sync

### ISSUE THREAD

**Issue by bbdouglas** [swagger-api/swagger-codegen#5511]
##### Description

Hi,

I noticed a recent commit (0792933c) that converted all windows batch files for sample generation to use `petstore.yaml`. However, I noticed that there are still some shell scripts that use `petstore.json` instead. Since `petstore.json` and `petstore.yaml` are slightly different (for example, the contact email apiteam@wordnik.com vs apiteam@swagger.io), you get different code generated depending on which script you execute.

Is the intent to move all the shell scripts to use `petstore.yaml` as well? Or should `petstore.json` be synced with `petstore.yaml`? I'm happy to help with this if you let me know the intended state.

##### Swagger-codegen version

Current

##### Swagger declaration file content or url

N/A

##### Command line used for generation

bin/android-petstore-httpclient.sh
vs
bin/windows/android-petstore-httpclient.bat

(and others pairs)

##### Steps to reproduce

Generating the samples with the scripts in bin/

##### Related issues
N/A
##### Suggest a Fix

The bash and bat scripts for a single target should either reference the same source file or the json and yaml versions should be synced up to match each other.

**Comment by wing328** [comment]
Done via 427ca18
