### ISSUE TITLE
[C#] swagger-codegen, date datatype in swagger, and services that expect/validate date only

### ISSUE THREAD

**Issue by sumo300** [swagger-api/swagger-codegen#5513]
##### Description

We currently use a service bus platform called Tibco to develop RESTful servics for our enterprise.  Tibco supports both the `date` and the `datetime` data types and validates them as such in requests to the services.  `date` expects a strict date with no time element.  However, when these services are used from C#, which swagger-codegen generates properties as `DateTime?`, the service throws an exception because the value submitted always comes with a time element.

The issue in C# is discussed at length [here](http://stackoverflow.com/questions/5314309/a-type-for-date-only-in-c-sharp-why-is-there-no-date-type).

Is there a way to solve this problem without forcing our service developers to always use `datetime` and ignore the time element?  We've tried just making it a `string`, but that feels wrong as well.

##### Swagger-codegen version

`2.2.2`

##### Command line used for generation

`generate -i "swagger.json" -l csharp -c "config.json" -o ".\SomeProject" --model-name-prefix Ent`

Contents of `config.json`

```
{
  "packageName": "SomePackageName"
}
```

##### Steps to reproduce

1. Define swagger that uses a `date` data type for an input parameter
2. Generate C# API using swagger-codegen
3. Call service using generated API, passing a C# date value

**Comment by wing328** [comment]
@sumo300 thanks for reporting the issue. Seems like we need to provide a converter function as described in http://stackoverflow.com/questions/18635599/specifying-a-custom-datetime-format-when-serializing-with-json-net

May I know if you've time to contribute the enhancement? A good starting point is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/model.mustache and the {{#isDate}} mustache tag.

**Comment by jimschubert** [comment]
@wing328 this should be considered a breaking change. I can pick it up within the next week or so if @sumo300 doesn't call dibs.

**Comment by jimschubert** [comment]
Also, proper formats for `date` and `date-time` are documented [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types). This may affect more generators than just the C# ones.

**Comment by wing328** [comment]
> Also, proper formats for date and date-time are documented here. This may affect more generators than just the C# ones.

Yup, I've created https://github.com/swagger-api/swagger-codegen/issues/5531 for tracking.

**Comment by wing328** [comment]
>  this should be considered a breaking change.

To me, it's more like a bug fix so I'm ok to see the fix going to master instead of 2.3.0.

**Comment by jimschubert** [comment]
I totally agree. I doubt anyone is using master in CI pipelines.

**Comment by sumo300** [comment]
@wing328 @jimschubert Have at it!  By the time I learn what actually needs to be done here, you will likely have it completed!  Thanks for recognizing the issue so quickly and jumping on it.

**Comment by jimschubert** [comment]
@sumo300 Sorry it took me quite a while to get around to this. I opened a PR with a fix that adds a custom date serializer. Would you be able to test out the PR referencing this issue (#5734)?

**Comment by sumo300** [comment]
@jimschubert Thanks!  And somehow, I missed your comments from 5/30.  Apologies.  We're going to add this to our builds right away and see how things fall out.  I'm expecting with how mature testing and review of changes are for this project, that it will work as expected.

**Comment by wing328** [comment]
@sumo300 the fix is included in the latest stable release v2.2.3. Please give it a try and let us know if you need further help.
