### ISSUE TITLE
[Suggestion] Curl / Language specific examples from the spec

### ISSUE THREAD

**Issue by traxair** [swagger-api/swagger-codegen#553]
I saw the 2.0 spec and the threepane sample, and I wondered if there was a way to generate the examples automatically from the Swagger spec. @webron told me he was not aware of this existing, so I was wondering if there was a way to make it work?

**Comment by fehguy** [comment]
It is still pending in that branch, but will eventually be supported with flags when generating the sample.

**Comment by traxair** [comment]
So, you'll have a flag that says "generate samples from spec examples"?

**Comment by fehguy** [comment]
examples are now available in the generator examples field.  This is produced by this code:

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/examples/ExampleGenerator.java
