### ISSUE TITLE
Maven-plugin 2.2.2 from Maven repo missing selective generate 

### ISSUE THREAD

**Issue by darangho-duplicate** [swagger-api/swagger-codegen#5546]
##### Description
I recently downloaded the latest available swagger-codegen-maven-plugin from Maven repo and noticed that this is missing parameters like:
- generateModels
- generateModelTests
- generateModelDocumentation
- generateApis
- generateApiTests
- generateApiDocumentation
- generateSupportingFiles

However, in documentation these parameters do exist, which lead to confusion.

##### Suggest a Fix
Please upload the latest changes to Maven central repo.

**Comment by wing328** [comment]
@darangho-duplicate the parameters you mentioned are added after the 2.2.2 stable release.

Please build the maven plugin from the latest master for the time being.
