### ISSUE TITLE
Object deserialization in PHP SDK gives array

### ISSUE THREAD

**Issue by adhocore** [swagger-api/swagger-codegen#5553]
##### Description

The code section [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache#L235-L237) to deserialize `object` bypasses the primitive types deserialization [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache#L250-L252) causing the primitive `object` type data to be `array`.

##### Swagger-codegen version

2.2.2

##### Command line used for generation

```bash
java -jar swagger-codegen-cli.jar generate -i resources/schema/spec.json -l php -Dmodel -o sdk/php
```

##### Suggest a Fix

Maybe removing [these lines](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/ObjectSerializer.mustache#L235-L237) would fix it.

**Comment by wing328** [comment]
@adhocore if you describe the property as "type: object", that implies it's an arbitrary JSON, which will be deserialized into an associative array in PHP.

**Comment by adhocore** [comment]
isn't it that arbitrary types don't have type definition at all ? if it is object in json schema then should not it be corresponding `\stdClass` object in php too? :)

**Comment by wing328** [comment]
> if type is object in json schema then should not it be corresponding \stdClass object in php too? :)

It's not the case at the moment. Arbitrary JSON is mapped into associative array at the moment. Would that work for you?
