### ISSUE TITLE
skip generating tests not working (generateApiTests, generateModelTests)

### ISSUE THREAD

**Issue by silentFred** [swagger-api/swagger-codegen#5557]
##### Description

When running the maven plugin and specifying the options to skip generating api and model tests, the plugin still ends up generating the tests. I have tried moving these properties around but the test still get generated no matter what I try. Am i missing something silly here?

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

NA

##### Command line used for generation

NA

##### Steps to reproduce
`
plugin>
                        <groupId>io.swagger</groupId>
                        <artifactId>swagger-codegen-maven-plugin</artifactId>
                        <version>2.2.2</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <inputSpec>${project.basedir}/src/main/resources/services/swagger.json</inputSpec>
                                    <language>java</language>
                                    <configOptions>
                                        <sourceFolder>src/gen/java/main</sourceFolder>
                                        <library>feign</library>
                                        <dateLibrary>legacy</dateLibrary>
                                        <generateApiTests>false</generateApiTests>
                                        <generateModelTests>false</generateModelTests>
                                    </configOptions>
                                    <modelPackage>xxx.model</modelPackage>
                                    <apiPackage>xxx.client</apiPackage>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
`
##### Related issues

NA

##### Suggest a Fix

NA

**Comment by silentFred** [comment]
Thank you for the feedback Jim!

Unfortunately this still generates tests. (This is the first thing I tried
because the docs where not too clear on where the options should be).

I also noted in your file list that you also have some tests:

    └── IO.Swagger.Test
        ├── IO.Swagger.Petstore.Models
        │   ├── ApiResponseTests.cs
        │   ├── CategoryTests.cs
        │   ├── OrderTests.cs
        │   ├── PetTests.cs
        │   ├── TagTests.cs
        │   └── UserTests.cs
        ├── IO.Swagger.Test.csproj
        └── packages.config

**Comment by jimschubert** [comment]
@silentFred I left model tests in there to show selective generation was working. I tested this against master.

I checked against 2.2.2, and I do also get tests.

As a workaround, you can define an .ignore file which allows for gitignore-like selective file exclusions and inclusions. The syntax for our ignore file is identical, since I coded the support against the spec for gitignore. :dancer:

From my example above, you can change the maven plugin version to 2.2.2 and add the following to a file called `ignore` (this path is for C# since that's the generator I maintain, so it's the one I always use for testing):

```
target/generated-sources/swagger/src/IO.Swagger.Test/IO.Swagger.Petstore.Apis/
```

Then, add the configuration to your pom.xml:

```
<ignoreFileOverride>${project.basedir}/ignore</ignoreFileOverride>
```

So, this should be your updated configuration:

```
<plugin>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>2.2.2</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                 <ignoreFileOverride>${project.basedir}/ignore</ignoreFileOverride>
                <inputSpec>${project.basedir}/src/main/resources/services/swagger.json</inputSpec>
                <language>java</language>
                <generateApiTests>false</generateApiTests>
                <generateModelTests>false</generateModelTests>
                <configOptions>
                    <sourceFolder>src/gen/java/main</sourceFolder>
                    <library>feign</library>
                    <dateLibrary>legacy</dateLibrary>
                </configOptions>
                <modelPackage>xxx.model</modelPackage>
                <apiPackage>xxx.client</apiPackage>
            </configuration>
        </execution>
    </executions>
</plugin>
```

---

I think 2.2.2 is the first version in which the `ignoreFileOverride` option landed.

Just an FYI, I did notice that model and api documentation are also generated for my example when I switch to 2.2.2 yet they work as expected on my build from master.

@wing328 do you think I should dig deeper into 2.2.2 to understand why selective generation is broken, or should we consider this a known bug that has already been fixed? Can you double-check with my pom.xml example from my previous post to make sure things are definitely working in master and broken in 2.2.2?

**Comment by silentFred** [comment]
Good thing the ignore file works like a charm! Unfortunately I can't test
2.2.3-SNAPSHOT now as our nexus repo does not allow any snapshot releases.
I will have to wait and see when 2.2.3 is released. Thank you for the quick
response! Please let me know if I can help with this in any other way?

**Comment by jimschubert** [comment]
Yeah man, no problem. I'm glad I could get you a workaround.

**Comment by yohanakh** [comment]
I am facing this issue with 2.2.3 as well... **Sometimes** the tests are being generated.
Upgraded now to 2.3.1, hopefully it is fixed there.

**Comment by jimschubert** [comment]
@yohanakh can you provide which generator and options you're using?

**Comment by yohanakh** [comment]
This is the plugin section in pom.xml:
 <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.2.3</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>generate-swagger</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <language>java</language>
                            <inputSpec>${project.basedir}/spec.yaml</inputSpec>
                            <output>${project.basedir}</output>
                            <apiPackage>com.domain.rest.client.java.api</apiPackage>
                            <modelPackage>com.domain.rest.client.java.model</modelPackage>
                            <invokerPackage>com.domain.rest.client.java.invoker</invokerPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <configOptions/>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by Nyawawa** [comment]
Same thing for versions swagger-codegen-maven-plugin 3.0.2, swagger-annotations 2.0.5. If I set "generateModelTests" and "generateApiTests" to "false" the tests are still generated but in the generated pom.xml the dependency for junit is removed. (Same happens for generating documentation.) (Another problem with the generated test files is that the package is not adjusted.)

Thats my pom.xml for generation:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>someId</groupId>
    <artifactId>SomeProject</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <swagger-annotations-v3-version>2.0.5</swagger-annotations-v3-version>
        <jersey-version>2.27</jersey-version>
        <jackson-version>2.9.7</jackson-version>
        <maven-plugin-version>1.0.0</maven-plugin-version>
        <junit-version>4.12</junit-version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations-v3-version}</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>${jersey-version}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>${jersey-version}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <version>${jersey-version}</version>
        </dependency>
        
        
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-base</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <version>${jackson-version}</version>
        </dependency>
        
         
        <dependency>
            <groupId>com.brsanthu</groupId>
            <artifactId>migbase64</artifactId>
            <version>2.2</version>
        </dependency>
        
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit-version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/swagger/swagger.json</inputSpec>
                            <language>java</language>
                            <generateApis>true</generateApis>
                            <generateModels>true</generateModels>
                            <supportingFilesToGenerate>
                                Pair.java,ApiClient.java,ApiException.java,Configuration.java,JSON.java,StringUtil.java,RFC3339DateFormat.java,ApiKeyAuth.java,Authentication.java,HttpBasicAuth.java,OAuth.java
                            </supportingFilesToGenerate>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <output>${project.build.directory}/generated-sources/swagger</output>
                            <modelPackage>some.package</modelPackage>
                            <apiPackage>some.package</apiPackage>
                            <invokerPackage>some.package</invokerPackage>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <sourceFolder>.</sourceFolder>
                                <java8>true</java8>
                            </configOptions>
                            <library>jersey2</library>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

**Comment by fr599** [comment]
Was there a resolution on this issue? Running into the same problem 

> <plugin>
    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.1</version>
    <executions>
        <execution>
            <id>server</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <language>spring</language>
                <library>spring-boot</library>
                <output>${project.build.directory}/generated-sources</output>
                <ignoreFileOverride>${project.basedir}/src/main/resources/.openapi-codegen-ignore
                </ignoreFileOverride>
                <invokerPackage>com.xxxxx.yyyyy.zzz.apiserver.api.generated</invokerPackage>
                
                <apiPackage>com.xxxxx.yyyyy.zzz.apiserver.api.generated</apiPackage>
                <generateApiTests>false</generateApiTests>
                <generateApiDocumentation>false</generateApiDocumentation>
                
                <modelPackage>com.xxxxx.yyyyy.zzz.apiserver.api.generated</modelPackage>
                <generateModelTests>false</generateModelTests>
                <generateModelTests>false</generateModelTests>
                <configOptions>
                    <sourceFolder>swagger</sourceFolder>
                    <java8>true</java8>
                    <dateLibrary>java8</dateLibrary>
                    <serializableModel>true</serializableModel>
                    <delegatePattern>true</delegatePattern>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>

**Comment by vikrampancholi** [comment]
++ any updated on this issue ?

**Comment by andrewrowe-wk** [comment]
+1 I am also getting the same issue.

**Comment by KoTeuKou** [comment]
++, getting the same on v3.0.1

**Comment by FernandoGarcia1995** [comment]
+1 , getting the same issue in v3.0.34

**Comment by yevsh** [comment]
same issue, this project is not maintained anymore?
v3.0.3

**Comment by mnesarco** [comment]
Hello, I am having the same issue with 6.3.0. Is there any workaround?

**Comment by diabolusss** [comment]
> Hello, I am having the same issue with 6.3.0. Is there any workaround?

Hi,

I've struggled with the same error, and `--additional-properties=generateModelTests=false,generateApiTests=false` hasn't helped. 
The actual [solution](https://stackoverflow.com/a/73252545/5161226) is to use `--global-property models,modelTests=false,apiTests=false`.
However, please note that I'm using openapi-generator-cli, so I'm not sure if it will help for the Maven plugin.

**Comment by Lenormju** [comment]
Or put the directories in your `.swagger-codegen-ignore` file, which has the effect of them to not be written.

**Comment by gratinierer** [comment]
`<generateModelTests>false</generateModelTests>` seems to do the trick in maven

**Comment by isarang** [comment]
Moving out of <configOptions> to outer <configuration> works

  ```
 <configuration>
              <inputSpec>${basedir}/openapi.yaml</inputSpec>
              <language>java</language>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
                <configOptions>
                  <modelPackage>abc.model</modelPackage>
                  <apiPackage>abc.api</apiPackage>
                  <dateLibrary>java11</dateLibrary>
                  <jakarta>true</jakarta>
                  <useGzipFeature>true</useGzipFeature>
                </configOptions>
              <library>okhttp-gson</library>
            </configuration>
```

**Comment by MuhammedOzdogan** [comment]
> Moving out of `<configOptions>` to outer `<configuration>` works
> 
> ```
> <configuration>
>             <inputSpec>${basedir}/openapi.yaml</inputSpec>
>             <language>java</language>
>             <generateApiTests>false</generateApiTests>
>             <generateModelTests>false</generateModelTests>
>               <configOptions>
>                 <modelPackage>abc.model</modelPackage>
>                 <apiPackage>abc.api</apiPackage>
>                 <dateLibrary>java11</dateLibrary>
>                 <jakarta>true</jakarta>
>                 <useGzipFeature>true</useGzipFeature>
>               </configOptions>
>             <library>okhttp-gson</library>
>           </configuration>
> ```

This solves the issue completely, there is not even test package under `src`,  thank you for sharing!
