### ISSUE TITLE
swagger generates non-compiling code (java)

### ISSUE THREAD

**Issue by lpicquet** [swagger-api/swagger-codegen#5562]
##### Description
When using Swagger-codegen with the published bitbucket.org swagger api, the following exception occurs when compiling:
C:\workspace\f_bitbucket\build\codegen\java\src\main\java\io\swagger\client\model\PipelineSelector.java:91: error: getType() in PipelineSelector cannot override getType() in Object
  public TypeEnum getType() {
                  ^
  return type TypeEnum is not compatible with String

The issue is the swagger definition defines a "type" field, for which getType is generated. The code does not compile because this getter exists on Object. 

##### Swagger-codegen version
io.swagger:swagger-codegen-cli:2.2.2

##### Swagger declaration file content or url
https://bitbucket.org/api/swagger.json

##### Suggest a Fix

Is there a way we can map a field to something else, say in this case "typeEnum" and "getTypeEnum" and pass the mapping on the command line?

**Comment by wing328** [comment]
@lpicquet one way is to map "type" to something like "property_type" so that the getter becomes `getPropertyType`:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java#L453

Would that meet your requirement?

**Comment by rvowles** [comment]
This has not been resolved. One has to remove the Pipeline functionality from the swagger.json manually as it will not compile. Even with the suggestion from @wing328 - i can see in the maven compile that the escape method never even gets called.
