### ISSUE TITLE
[Angular 4+] [Typescript Client] OpaqueToken deprecated in Angular 4

### ISSUE THREAD

**Issue by iblocks-Xander** [swagger-api/swagger-codegen#5565]
##### Description

OpaqueToken is deprecated in Angular 4 and will be removed in 2 versions according to the Angular deprecation policy. InjectionToken 

##### Swagger-codegen version

2.2.2

##### Steps to reproduce

Use PetStore example to generate Angular2TypescriptClient

##### Related issues

https://github.com/angular/angular/issues/14763

##### Suggest a Fix

Simply changing the type from `OpaqueToken` to `InjectionToken<string>` will work, however, this is will break Angular 2 clients, so I am unsure of how to approach this. Should it be a command line flag on the Angular client build or should it be a separate client?

**Comment by taxpon** [comment]
@iblocks-Xander CC @wing328 
How about providing option like `useOpaqueToken`? If this option is provided as true, generator will use `OpaqueToken` as it does now. If this option is not provided, it will use `InjectionToken<string>`.

**Comment by wing328** [comment]
@iblocks-Xander please pull the latest master to give it a try.

Thanks for the PR from @taxpon

**Comment by iblocks-Xander** [comment]
@wing328 Works for me. Although I wonder whether the default should be OpaqueToken rather than InjectionToken, just so updating does break existing workflows. 

Thanks for the PR @taxpon

**Comment by wing328** [comment]
@iblocks-Xander what about setting the default to "OpaqueToken" in current master and "InJectionToken" in 2.3.0 (a branch with breaking changes)?
