### ISSUE TITLE
swagger authentication for spring mvc

### ISSUE THREAD

**Issue by pranotiB** [swagger-api/swagger-codegen#5566]
Im using swagger 2.4.0 version in my spring mvc project. All working fine. But now I want to add authentication to my REST web services. I want to show authorize button on swagger ui. Can anybody help me? I saw the posts related to swagger authentication but it was confusing and they are from almost 1-2 years ago. So can anybody help me? Is that issue has been solved in 2.4.0? Do I have to add that authorize button in html page manually?

**Comment by cbornet** [comment]
Authentication is currently not supported by the spring templates.
To add authentication, you can have a look at [spring security](http://docs.spring.io/spring-security/site/docs/current/guides/html5/). I don't think Springfox currently supports spring-security so you will have to configure it manually your Springfox SecurityContext (see [example](http://springfox.github.io/springfox/docs/current/#dependencies))

**Comment by pranotiB** [comment]
Yes I did add spring security but that was not supported to springfox. I'll check for springfox security context.. Thanks @cbornet ...
