### ISSUE TITLE
unknown library: retrofit2 in both 2.2.2 and 2.2.3

### ISSUE THREAD

**Issue by bdauer** [swagger-api/swagger-codegen#5568]
##### Description

When trying to generate retrofit2 I receive the following error:

```Exception in thread "main" java.lang.RuntimeException: unknown library: retrofit2
	at io.swagger.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:3195)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:410)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:232)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:43)```

##### Swagger-codegen version

I initially installed 2.2.2 with homebrew, and then I cloned the latest version and tried with that.

##### Swagger declaration file content or url


This is my config file:

```json
{
  "library": "retrofit2",
  "apiPackage": "org.affoa.bendauer.<app name>.client.api",
  "invokerPackage": "org.affoa.bendauer.<app name>.client",
  "modelPackage": "org.affoa.bendauer.<app name>.client.models",
  "groupId": "org.affoa.bendauer"
}
```

I don't think the declaration is important in this case but if it is I can create a gist containing the Json object.

##### Command line used for generation

With 2.2.3 I used
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -c ../config.json -l android -i ~/Downloads/looksapi.json -o ../example
```
##### Steps to reproduce

Run the command using a swagger api declaration.

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/1850

I posted to that issue yesterday, but I think this is new since it was reported working in v2.1.5.

##### Suggest a Fix

Wondering if something got cut out at some point after 2.1.5. I'm going to do a little investigating, but new to swagger-codegen and still possible this is user error on my part.

**Comment by wing328** [comment]
@bdauer using the latest master, you get any error running `./bin/java-petstore-retrofit2.sh` in the project?

**Comment by bdauer** [comment]
@wing328 I didn't test with java-petstore, but I just got it working for my swagger api declaration. I saw that retrofit2 wasn't available for android, but was available for java. I ran it through with java and it's working properly now. Going to go ahead and close this. Thanks for following up quickly!

**Comment by wing328** [comment]
@bdauer no problem :)
