### ISSUE TITLE
Issue when generating jaxrs server side code for basic-auth.yaml sample

### ISSUE THREAD

**Issue by test12121212** [swagger-api/swagger-codegen#557]
Issue when generating jaxrs server side code for basic-auth.yaml sample

Unable to build target: A target generation was attempted, but no files were created!

Details:
 Object
 code: 1
 type: "error"
 message: "Unable to build target: A target generation was attempted, but no files were created!"

Steps:
http://editor.swagger.io/
file menu->Open Example->basic-auth.yaml
open button
Generate Server->javax Alpha
Code Generation Error pasted  above

**Comment by fehguy** [comment]
This is fixed in develop_2.0
