### ISSUE TITLE
generated code is java.time.OffsetDateTime from a json format "date-time"

### ISSUE THREAD

**Issue by jnie** [swagger-api/swagger-codegen#5583]
##### Description

2017-05-08 15:32:44.089  WARN [user=] [clientIp=] [request=] [session=] [qtp514447876-22] o.eclipse.jetty.servlet.ServletHandler   : 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is feign.FeignException: Can not construct instance of java.time.OffsetDateTime: no String-argument constructor/factory method to deserialize from String value ('2017-05-08T16:32:44')

  @JsonProperty("entry_date")
  private OffsetDateTime entryDate = null;

##### Swagger-codegen version

codegen Version: 2.2.2
feign-version: 9.5.0

##### Swagger declaration file content or url

swagger.json
...
        "entry_date" : {
          "type" : "string",
          "format" : "date-time"
        },
...
##### Command line used for generation
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>${swagger-codegen-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <id>generate-swagger-javaclient</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.build.directory}/swagger/swagger.json</inputSpec>
                            <language>java</language>
                            
                            <modelPackage>model</modelPackage>
                            <apiPackage>api</apiPackage>
                            <invokerPackage>invoker</invokerPackage>
                            <output>${project.build.directory}/generated-sources</output>
                            <addCompileSourceRoot>true</addCompileSourceRoot>
                            <library>feign</library>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
##### Steps to reproduce

Use the plugin and a swagger.json file with the declaration of a "date-time"

##### Error

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is feign.FeignException: Can not construct instance of java.time.OffsetDateTime: no String-argument constructor/factory method to deserialize from String value ('2017-05-08T16:56:08')

**Comment by jnie** [comment]
Fix the issue with:
<dateLibrary>java8-localdatetime</dateLibrary>

**Comment by jnie** [comment]
dateLibrary element use java8-localdatetime

**Comment by monktastic** [comment]
For posterity: what the previous comment is saying is to set the config setting `dateLibrary` to `java8-localdatetime`.

https://openapi-generator.tech/docs/generators/java/
