### ISSUE TITLE
[Csharp] Code using Netstandard "RestSharp.Portable" serializes JSON twice

### ISSUE THREAD

**Issue by voydz** [swagger-api/swagger-codegen#5589]
##### Description

Using the netstandard version of csharp to generate code uses restsharp.portable in the background. As the implementation differs from RestSharp.Net, the body in "application/json" requests is serialized twice.

##### Swagger-codegen version

current master branch @ fa2e575762dc71939cfcf8ae8bc1d058bce5cdab

##### Swagger declaration file content or url

Not exactly caused by a specific declaration, just any normal JSON model as request body.

##### Command line used for generation

```bash
java -jar swagger-codegen-cli.jar generate \
  -i "api.json" \
  -c "config.json" \
  -l "csharp" \
  -o "generated"
```

```js
// ... config.json
{
    "packageName": "My.Api",
    "targetFramework": "v5.0",
    "packageGuid": "<insert random package guid here>"
}
```

##### Steps to reproduce

1. Generate project with above command and config
2. Attach HTTP proxy debugger like Charles or Fiddler
3. Make random POST/PUT request with JSON body
4. Inspect request in HTTP proxy debugger
5. See double serialized JSON

##### Related issues

Introduced in #1557 ?

##### Suggest a Fix

Disabling the restsharp.portable serialization by respecting the slightly different api. PR is incoming.

**EDIT:** see #5590 for details

**Comment by wing328** [comment]
Closed via #5590. Thanks for the fix from @voydz
