### ISSUE TITLE
Updating Typescript-Angular2 to forRoot instead of forConfig

### ISSUE THREAD

**Issue by kenisteward** [swagger-api/swagger-codegen#5608]
##### Description

Currently the best practices for including a module and all of it's provided services for Angular is to use a static forRoot function explained here.
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

The sample shows that the template does not use that function name and also includes the providers in the NGModule declaration instead of the forConfig

https://github.com/swagger-api/swagger-codegen/blob/2.3.0/samples/client/petstore/typescript-angular2/npm/api.module.ts

##### Steps to reproduce

run the generator under -l typescript-angular2

##### Related issues

None that are open

##### Suggest a Fix

I'd suggest that the template here
https://github.com/swagger-api/swagger-codegen/blob/2.3.0/modules/swagger-codegen/src/main/resources/typescript-angular2/api.module.mustache

to put the generation of providers in the function and to change the function name to forRoot so it meets current best practices

**Comment by kenisteward** [comment]
@Vrolijkx Any comment on this?  Technically if you want to lazy load the module you'll end up having 2 copies instead of 1 when the providers in the ngmodule declaration instead of in forRoot()

**Comment by Vrolijkx** [comment]
@kenisteward Looks like a good change but maybe keep it backward compatible. By making forConfig delegate to forRoot.

**Comment by kenisteward** [comment]
@Vrolijkx this was only added to 2.3.0 right?  No one is using that unless they are okay with breaking changes I thought.

**Comment by Vrolijkx** [comment]
@kenisteward good point.

**Comment by kenisteward** [comment]
@wing328 are we still taking pull request for 2.3.0? I'd like to contribute
this this weekend hopefully.

@vrolijkx just checking to make sure you agree with this still

**Comment by sebastianhaas** [comment]
I'm all for it. We also might want to protect against reimporting as described [here ](https://angular.io/guide/ngmodule#prevent-reimport-of-the-coremodule) then? 
@kenisteward @Vrolijkx @TiFu  what do you think?

**Comment by kenisteward** [comment]
That sounds great!

**Comment by TiFu** [comment]
I don't have much experience with angular, but following best practices sounds good.

**Comment by kenisteward** [comment]
@wing328 can i still make this against 2.3.0 or is it too late?
