### ISSUE TITLE
[Client: PHP] api_doc.mustache documentation is generating broken links for object parameters

### ISSUE THREAD

**Issue by frojasg** [swagger-api/swagger-codegen#5611]
##### Description

api_doc.mustache is generating broken links for "model" body parameters. Here you can see an example in master 

Step to reproduce:

1.- [go to Pet example API documentation](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/docs/Api/PetApi.md#addpet)
2.- Click [\Swagger\Client\Model\Pet](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/docs/Model/%5CSwagger%5CClient%5CModel%5CPet.md)
3.- You get a broken link

Expected result:

3.- [this is how the link should look like](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/docs/Model/Pet.md)

Additional Information:
This is working fine for Ruby, Java, Python, and C#

##### Suggest a Fix

I took a quick look at the code and I notice the that CodegenParameter.dataType and baseType are the same. and I'm not sure why this is not a problem with other languages

**Comment by wing328** [comment]
@frojasg thanks for reporting the issue. May I know if you've time to contribute a fix? If yes, I can show you some good starting points.

**Comment by frojasg** [comment]
@wing328 yes, I would like to help with a fix. If you can give me some starting points it would be awesome. Thanks

**Comment by wing328** [comment]
@frojasg Thanks for offering help.

I used `-DdebugOperations` and found the following:
```
      "path" : "/pet/{petId}",
      "operationId" : "getPetById",
      "returnType" : "\\Swagger\\Client\\Model\\Pet",
      "httpMethod" : "GET",
      "returnBaseType" : "Pet",
      "summary" : "Find pet by ID",
      "unescapedNotes" : "Returns a single pet",
      "notes" : "Returns a single pet",
      "baseName" : "Pet",
```

Can you try using `returnBaseType` instead in api_doc.mustache?

**Comment by frojasg** [comment]
Did you use that flag when you ran `java -jar target/swagger-codegen-cli.jar generate -DdebugOperations ...`? It didn't work for me. 

That's the return type of the operation. The problem is only present in the parameters of the operation. I tried inspecting the CodegenParameter object, and I saw that the dataType and baseType are the same

**Comment by wing328** [comment]
Sorry please try "-DdebugOperations=true"

**Comment by wing328** [comment]
I will take another look later today

**Comment by wing328** [comment]
UPDATE: I should have a fix by today (Friday)

**Comment by wing328** [comment]
@frojasg the issue should be fixed by #5715. Please pull the latest master to give it a try.

**Comment by frojasg** [comment]
@wing328 Thank you! You're awesome. I'll test it now.

**Comment by bunnyc1986** [comment]
@wing328 Thank you! This is awesome!

**Comment by yonpols** [comment]
@wing328 I believe this PR https://github.com/swagger-api/swagger-codegen/pull/5715 introduced another issue. The name of the type used in the docs and examples is changed so that if a model is named `V1TheModel` it will be documented as `v1TheModel`. 

I believe the change to fix this is:
```diff
diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
index 627139049..d3f983453 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
@@ -2580,8 +2580,8 @@ public class DefaultCodegen {
                         name = typeMapping.get(name);
                         p.baseType = name;
                     } else {
-                        p.baseType = name;
                         name = toModelName(name);
+                        p.baseType = name;
                         if (defaultIncludes.contains(name)) {
                             imports.add(name);
                         }
```

Please let me know if this makes sense to you and I'll submit a change. (PS this is true not only for PHP but also tested in Java, C#, Ruby and Python)

**Comment by wing328** [comment]
Please open a PR so that we can more easily review the change.
