### ISSUE TITLE
[Java] Codegen produces unnecessary classes

### ISSUE THREAD

**Issue by davidgri** [swagger-api/swagger-codegen#5612]
##### Description
I wrote an api with the swagger editor and during generation of a spring-boot server several unnecessary java classes were generated:
CapabilityBody.java
CapabilityBody1.java
CustomerOrderBody.java
CustomerOrderBody1.java
InlineResponse200.java
InlineResponse200JobDrawings.java
InlineResponse2001.java
InlineResponse2002.java
InlineResponse2003.java
InlineResponse2004.java
InlineResponse2004ResourceGroup.java
InlineResponse2005.java
InlineResponse2006.java
JobBody.java
JobBody1.java
JobBody2.java
JobBody3.java
JobStateBody.java
OperationBody.java
OperationBody1.java
OperationStateBody.java
ResourcesresourceIdjobsjobIdjobStatesState.java
ResourceStateBody.java

Although the  classes:
Capability.java
CustomerOrder.java
Job.java
JobDrawing.java
JobState.java
Operation.java
OperationState.java
ResourceGroup.java
ResourceState.java

exists the new classes were created for parameters and responses, making the generated code unusable.

##### Swagger-codegen version
I used the online Editor to write and generate the api. 

##### Swagger declaration file content or url

[swagger (7).yaml.zip](https://github.com/swagger-api/swagger-codegen/files/992129/swagger.7.yaml.zip)

##### Suggest a Fix

I cloned the project and figured out that if i remove the code in the method AbstractJavaCodegen.reconcileInlineEnums only the needed classes were generated. So the bug might be somewhere there.

**Comment by wing328** [comment]
@davidgri from what the auto-generated model file name, I think you're defining the model inline. You can control the naming of the model by defining the model properly, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L653 and reference the model in the spec, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L49

**Comment by davidgri** [comment]
@wing328 

I am using defined models:

```yaml
definitions:
  Capability:
    type: object
    properties:
      id:
        type: string
        description: id of the machineState
      name:
        type: string
        description: name of the Capability
    description: >-
      Every resource has Capabilities. Every operation of a job needs special
      capabilities
  CustomerOrder:
    type: object
    properties:
      comment:
        type: string
        description: Possibility to add a comment to the order
      description:
        type: string
        description: A breif description of the order
      id:
        type: string
        description: The id of the order
      jobs:
        type: array
        description: a list of jobs the order consists of
        items:
          $ref: '#/definitions/Job'
      orderState:
        type: string
        description: The current state of the order.
        enum:
          - CREATED
          - PLANNED
          - RELEASED
          - TRANSFERED
          - PROCESSING
          - STOPPED
          - FINISHED
      orderType:
        type: string
        description: >-
          This field describes the type of the order, as those types are
          diffrent in every enterprise it is no a enumeration.
      priority:
        type: integer
        format: int32
        description: The priority of the order
    description: >-
      A Customer Order is a order placed by a customer, consisting of several
      jobs.
...
```

and use $ref to reference them:

```yaml
...
   responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Capability'
...
```

The yaml i'm using is attached and i tried to generate a spring server through the online editor.

**Comment by rvbiljouw** [comment]
@davidgri did you ever figure out what caused this?

**Comment by davidgri** [comment]
I have integrated swagger-codegen 2.2.2 into my build pipeline and the models were generated as expected. However generating through the online-Editor still results in Inline models.  I don't know wether the online generator is using another version of swagger-codegen.

**Comment by se7vanj** [comment]
Same issue exists for .NET (Client 2.0 & Server .NET Core) generation - PFB

06/27/2017  12:40 PM             1,963 ApiResponseStatus.cs
06/27/2017  12:40 PM            10,224 Driver.cs
06/27/2017  12:40 PM            10,226 Driver1.cs
06/27/2017  12:40 PM               889 Drivers.cs
06/27/2017  12:40 PM             3,169 DriversAddress.cs
06/27/2017  12:40 PM            10,246 InlineResponse200.cs
06/27/2017  12:40 PM             3,595 InlineResponse2001.cs
06/27/2017  12:40 PM             5,187 InlineResponse2002.cs
06/27/2017  12:40 PM             1,963 InlineResponse400.cs
06/27/2017  12:40 PM             1,491 InlineResponse400ExceptionMessages.cs
06/27/2017  12:40 PM             5,187 MotorVehicleRecord.cs
06/27/2017  12:40 PM             5,189 MotorVehicleRecord1.cs
06/27/2017  12:40 PM               913 MotorVehicleRecords.cs
06/27/2017  12:40 PM               891 Policies.cs
06/27/2017  12:40 PM             3,571 Policy.cs
06/27/2017  12:40 PM             3,573 Policy1.cs
06/27/2017  12:40 PM             3,938 PolicyDriverAssociation.cs
06/27/2017  12:40 PM             1,467 StatusExceptionMessage.cs

**Comment by rvbiljouw** [comment]
Came to the same conclusion as @davidgri - looks like codegen 2.2.2 works fine...

**Comment by fehguy** [comment]
Would like more details--specifically the spec file you used.

**Comment by felimartina** [comment]
What is the best way to define Responses for the generator to work properly?

**Comment by se7vanj** [comment]
@fehguy Please find below the spec and corresponding output

## **Model Definition:**
  "definitions": {
    "Driver": {
      "type": "object",
      "description": "A representation of a Driver. \n- Specify policyID when exists",
      "required": [
        "lastName"
      ],
      "properties": {
        "driverId": {
          "type": "string",
          "readOnly": true,
          "format": "uuid",
          "description": "unique GUID - UUID v4"
        },
        "lastName": {
          "type": "string",
          "maximum": 60
        },
        "address": {
          "required": [
            "addrLine1"
          ],
          "type": "object",
          "properties": {
            "adderssId": {
              "type": "string",
              "readOnly": true,
              "description": "unique GUID - UUID v4"
            },
            "addrLine1": {
              "type": "string",
              "maximum": 50
            }
          }
        }
      }
    },
    "Drivers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Driver"
      }
    },


## **Resource:**
 "paths": {
    "/drivers/": {
      "get": {
        "tags": [
          "Drivers"
        ],
        "summary": "Get the list of Drivers",
        "description": "Loads a list of Driver",
        "parameters": [
          {
            "name": "$size",
            "in": "query",
            "required": false,
            "type": "integer",
            "description": "Size of the page to retrieve."
          },
          {
            "name": "$page",
            "in": "query",
            "required": false,
            "type": "integer",
            "description": "Number of the page to retrieve."
          },
          {
            "name": "$sort",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Order in which to retrieve the results. Multiple sort criteria can be passed."
          },
          {
            "name": "lastName",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Allows to filter the collections of result by the value of field lastName"
          }
        ],
        "responses": {
          "200": {
            "description": "Status 200",
            "schema": {
                "$ref": "#/definitions/Drivers"
            },
            "headers": {
              "X-Page-Count": {
                "type": "integer"
              },
              "X-Page-Number": {
                "type": "integer"
              },
              "X-Page-Size": {
                "type": "integer"
              },
              "X-Total-Count": {
                "type": "integer"
              }
            }
          },
          "400": {
            "description": "Invalid ID supplied",
            "schema": {
              "$ref": "#/definitions/ApiResponseStatus"
            }
          }
        }
      },



Pls see the ## **difference in output model class file generation** between Editor.Swagger.IO vs Swagger CodeGen:

![swagger_editor_ui_codegeneration_vs_swagger_codegen_utility](https://user-images.githubusercontent.com/16820267/27664210-497b9900-5c34-11e7-9ae2-d610ccdd9042.png)

**Comment by wing328** [comment]
> What is the best way to define Responses for the generator to work properly?

@felimartina I would suggest you defining the model in a separate section ([example](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L573)) and reference it in the response/parameter/property ([example](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L177)) so that you can reuse the same model definition in your spec.

**Comment by imgx64** [comment]
This seems to only affect http://editor.swagger.io/ . I built the code from source from three different branches (master, 2.3.0, 3.0.0), and tried pre-built JARs ([2.2.2](https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.2/swagger-codegen-cli-2.2.2.jar) and [2.2.3](https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.3/swagger-codegen-cli-2.2.3.jar)) and none of them generated these `InlineResponse*` classes. Only the online editor generates these extra classes.

A simpler spec that reproduces this:
```
swagger: '2.0'
info:
  version: '1.0'
  title: title
basePath: /
paths:
  /:
    get:
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LookupResponse'
definitions:
  LookupResponse:
    type: object
    properties:
      lookup:
        type: array
        description: lookup
        items:
          $ref: '#/definitions/Lookup'
  Lookup:
    type: object
    properties:
      key:
        type: string
      value:
        type: string
```

**Comment by imgx64** [comment]
I think this issue can be closed. The real issue is swagger-api/swagger-editor#1319 .

**Comment by wing328** [comment]
@imgx64 ok. Issue closed. Please open a new ticket (issue) if you need further help from us.
