### ISSUE TITLE
[Java] Property name "null" is not recognized as keyword

### ISSUE THREAD

**Issue by pfeuffer** [swagger-api/swagger-codegen#5615]
##### Description

Given a type definition with a property named "null", illegal java code will be created, because "null" is not recognized as a keyword (like "new", "for", etc.). Therefor it will not be 'escaped' like other keywords.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

```json
{
  "swagger": "2.0",
  "definitions": {
    "MyType": {
      "type": "object",
      "properties": { "null": { "type": "boolean" } }
    }
  }
}
```

This creates the java class MyType like this:
```java
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-11T11:47:22.422+02:00")
public class MyType {
  @SerializedName("null")
  private Boolean null = null;

  public MyType null(Boolean null) {
    this.null = null;
    return this;
  }
  // [...]
}
```

##### Command line used for generation

-l java

##### Steps to reproduce

java -jar swagger-codegen-cli-2.2.2.jar generate -i test.json -o ./tmp -l java

##### Related issues

./.

##### Suggest a Fix

The string "null" has to be appended to the list of language specific primitives in the AbstractJavaCodegen class.

**Comment by wing328** [comment]
Closed via #5617

**Comment by packleader** [comment]
Thanks for resolving this bug. My team is currently facing this issue while using v2.2.2.  @wing328  Do you guys have a roadmap for when v2.2.3 will be released?

**Comment by wing328** [comment]
I don't have a release date for v2.2.3 at the moment but we just setup a workflow (as part of Travis CI) to publish a SNAPSHOT version of v2.2.3 and v2.3.0 (with breaking changes). Would that help?

Ref: https://github.com/swagger-api/swagger-codegen#compatibility
