### ISSUE TITLE
[Java] Can't access enum value directly (feature request)

### ISSUE THREAD

**Issue by sdoeringNew** [swagger-api/swagger-codegen#5619]
##### Description

Enum models are generated and marshalled correctly. But there is no way to access its value directly. For String you might use the `toString()` method. But how to access the value of a number (Integer, Float, etc.)?

There is an indirect way to do this.

1. You call `toString()` – which generates a String out of the value: `String.valueOf(value)`
2. You parse the String into the number type, e.g. `Integer.parseInt(valueAsString)`

That is not just slower or uglier. It might be incorrect for floats, too.

##### Swagger-codegen version

Tested with Version: 2.2.2

##### Swagger declaration file content or url

e.g. any petstore file.

##### Command line used for generation

(n/a)

##### Steps to reproduce

(n/a)

##### Related issues

(n/a)

##### Suggest a Fix

(n/a)

**Comment by wing328** [comment]
Closed via #5620 

Thanks for the PR by @sdoeringNew
