### ISSUE TITLE
[typescript-jquery] Bug generating ajax request when there is no returnType

### ISSUE THREAD

**Issue by paulfelix** [swagger-api/swagger-codegen#5624]
##### Description

When there is no returnType, the mustache template does not provide a type for the 'data' param in the ajax done callback signature.

##### Swagger-codegen version

2.2.2

##### Suggest a Fix

Something like this, I think:

$.ajax(requestOptions).then(
            (data: {{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}any{{/returnType}}, textStatus: string, jqXHR: JQueryXHR) =>
                dfd.resolve({ response: jqXHR, body: data }),
            (xhr: JQueryXHR, textStatus: string, errorThrown: string) =>
                dfd.reject({ response: xhr, body: errorThrown })
        );

**Comment by wing328** [comment]
@paulfelix thanks for reporting the issue. May I know if you've time to file a PR with the suggested fix so that we can review?

cc @bherila

**Comment by taxpon** [comment]
@wing328 This can be closed.
