### ISSUE TITLE
Build a customized static HTML

### ISSUE THREAD

**Issue by lal-s** [swagger-api/swagger-codegen#5625]
##### Description

Is there any way to create our own customized static HTML using swagger codegen?

##### Language

Ruby

##### Swagger-codegen version

Swagger 2.0

**Comment by wing328** [comment]
@lal-s have you tried the `html2` generator? Here are the samples: https://github.com/swagger-api/swagger-codegen/tree/master/samples/html2

API clients (e.g. ruby, php, etc) also usually comes with auto-generated documentation (markdown)

**Comment by wing328** [comment]
Closing this as there's no update.
