### ISSUE TITLE
[Python] Allow 'safe' chars to be specified in config when quoting path params

### ISSUE THREAD

**Issue by boosh** [swagger-api/swagger-codegen#5627]
##### Description
The current python API client [quotes all path params](https://github.com/swagger-api/swagger-codegen/blob/c366f139e28b4b67f11a51807580f897afccc305/modules/swagger-codegen/src/main/resources/python/api_client.mustache#L110) without any 'safe' characters:

    for k, v in path_params:
        resource_path = resource_path.replace(
            '{%s}' % k, quote(str(v), safe=''))  # no safe chars, encode everything

This is awkward for me. I'm using [gRPC](http://grpc.io) and am following the [Google API design guidelines](https://cloud.google.com/apis/design/resource_names) especially regarding resource names which can contain '/' characters. So I need to be able to specify '/' as a safe character.

It'd be great if safe characters could be specified in config for the python library.

##### Swagger-codegen version
Latest version at: http://editor.swagger.io/

##### Swagger declaration file content or url
N/A

##### Command line used for generation
Swagger editor

##### Steps to reproduce
Generate a python library from a swagger spec using http://editor.swagger.io/ 

##### Suggest a Fix
Store safe characters in  the `Configuration` object, and use that as a parameter to the `quote` function.

**Comment by wing328** [comment]
@boosh can you take a look at the [PR](https://github.com/swagger-api/swagger-codegen/issues/5628) filed by @taxpon when you've time?

The enhancement by @taxpon looks good to me.

**Comment by wing328** [comment]
@boosh PR merged into master. Please pull the latest master to give it a try.

Thanks for the PR from @taxpon

**Comment by boosh** [comment]
Wow, that was fast. Thanks a lot @taxpon. LGTM 👍
