### ISSUE TITLE
update android, scala templates, add tests

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#563]
https://github.com/swagger-api/swagger-codegen/commit/3d12c8847f405fbfc612081c0fbe311ef1d6e008 added integration tests for java.  There were issues in the templates that were resolved and are now tested--need to do the same for scala and android templates as they probably have the same bugs.

**Comment by wing328** [comment]
UPDATE: There are Petstore integration tests for both scala and android.
