### ISSUE TITLE
typescript-angular2: Missing optional headers are sent as string 'undefined'

### ISSUE THREAD

**Issue by imgx64** [swagger-api/swagger-codegen#5638]
##### Description
When a header parameter is optional, and is not supplied when calling the API, the header is sent with the string `undefined` as its value.

##### Swagger-codegen version
swagger-codegen-cli 2.2.3-SNAPSHOT (downloaded from https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.2.3-SNAPSHOT/ )

##### Swagger declaration file content or url
```yaml
swagger: '2.0'
info: 
  title: title
  version: "1"
paths:
  /:
    get:
      parameters:
        - name: "Accept-Language"
          in: "header"
          type: "string"
          required: false
      responses:
        200:
          description: ""
          

```

##### Command line used for generation
```
> java -jar ./swagger-codegen-cli-2.2.3-20170310.174729-1.jar generate -i swagger.yaml -l typ
escript-angular2 -o test
```

##### Steps to reproduce
1. Generate the typescript-angular2 client as above.
2. Import it into an Angular project.
3. Call `DefaultApi.rootGet()`.
4. Notice the "Accept-Language: undefined" header in the sent request.

##### Related issues
Couldn't find any.

##### Suggest a Fix
This line is generated:
```
headers.set('Accept-Language', String(acceptLanguage));
```
It should check that the parameter exists before setting it. For example:
```
if (typeof acceptLanguage !== 'undefined') { // Or some other check, I'm not sure what is best
        headers.set('Accept-Language', String(acceptLanguage));
}
```

**Comment by wing328** [comment]
@imgx64 Thanks for reporting the issue. What about using the following to check?
```
if (x == null) {
```
Ref: http://stackoverflow.com/a/28984306/677735

**Comment by imgx64** [comment]
Since tslint can be configured to complain about `==`, I prefer this:
```
if (x !== undefined && x !== null) {
```

Turns out using `typeof x === 'undefined'` is unnecessary in TypeScript because you can't redefine `undefined` (unlike JavaScript).

**Comment by wing328** [comment]
May I know if you have time to file a PR so that we can review the more
easily?

**Comment by wing328** [comment]
@imgx64 please pull the latest master to try the fix.

Thanks for the PR from @taxpon
