### ISSUE TITLE
document integration tests

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#564]
You can now run objective-c integration tests against a local server and java tests against a remote server.  Probably should standardize on one or the other (local or remote).

In addition, it's not reasonable to expect every contributor has all the different client frameworks installed so the -Psamples profile should probably be expanded so you can run integration tests for specific languages locally.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/wiki/Integration-Tests
