### ISSUE TITLE
php client

### ISSUE THREAD

**Issue by DavidJona** [swagger-api/swagger-codegen#5644]
hello everyone,
noob question,

i've just generated the php client from my swagger spec but i have no idea how to use it, the readme is very vague and i'm not making any progress with it.

can someone point me to a documentation on how to use it or help me with some info?
thank you very much

**Comment by wing328** [comment]
@DavidJona For readme, are you referring to the auto-generated README file, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/README.md#installation--usage ?

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/test.php is an example using the PHP Petstore client. Would it help?

**Comment by wing328** [comment]
@DavidJona closing this as there's no update.
