### ISSUE TITLE
[Java] Handling file response fails with file exists exception

### ISSUE THREAD

**Issue by HaraldWalker** [swagger-api/swagger-codegen#5649]
##### Description

When the generated java client receives a file form an endpoint it fails with java.nio.file.FileAlreadyExistsException.

##### Swagger-codegen version

2.2.2

##### Generated client code

Generated API client uses in class **ApiClient** downloadFileFromResponse method:  
```java
 File file = prepareDownloadFile(response);
 Files.copy(response.readEntity(InputStream.class), file.toPath();
```
The method prepareDownloadFile already creates the temp file.  
File.copy doc: 

> By default, the copy fails if the target file already exists or is a symbolic link. 

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.2.jar generate -i my.json -l java -c swagger-java.conf  
in swagger-java.conf:  "library":"jersey2"

##### Steps to reproduce

Generate a java client where a response of an endpoint is defined as type file and then execute the API call to retrieve the file.
```json
"responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
```
##### Related issues

not found

##### Suggest a Fix
Pass as copy option that it should replace existing, so that the created file is being used.
```java
 File file = prepareDownloadFile(response);
      Files.copy(response.readEntity(InputStream.class), 
     file.toPath(), StandardCopyOption.REPLACE_EXISTING);
```

**Comment by wing328** [comment]
@HaraldWalker I think that's the expected behaviour as we want to avoid your previous downloaded files being overwritten. You should move the files to another folder as the default folder is a temp folder.

**Comment by HaraldWalker** [comment]
The step prepareDownloadFile creates a new unique temp file. That is the existing file that then throws the exception.

**Comment by wing328** [comment]
@HaraldWalker I just took another look and seems like we already have what you suggested: 

https://github.com/swagger-api/swagger-codegen/blob/22eb72791c4184d3697170dfa654389c322a3f95/modules/swagger-codegen/src/test/resources/2_0/templates/Java/libraries/jersey2/ApiClient.mustache#L585

Can you pull the latest master to give it a try?

**Comment by HaraldWalker** [comment]
@wing328 yes, looks like pull request #5268 addresses it. It was only a pull request without an issue, so I didn't find it.
I'll check.

**Comment by wing328** [comment]
@HaraldWalker pls give it a try. If it's still an issue, I'll reopen this issue.

**Comment by wing328** [comment]
PR merged into master. Thanks for the fix by @HaraldWalker
