### ISSUE TITLE
TypeScript Fetch

### ISSUE THREAD

**Issue by cyberhck** [swagger-api/swagger-codegen#5656]
##### Description

Using the current TypeScript Fetch generator, there's no way of using authentication data, once the user is logged in, ie we have auth tokens, we're not able to use those.

In addition to that, it uses isomorphic fetch which doesn't have middlewares, so I can't modify the behavior that much.

##### Swagger-codegen version
Swagger 2.0 docker command line

##### Swagger declaration file content or url
not required. any JSON will do.

##### Steps to reproduce
- create a server with protected routes (only users with access_token can access)
- create api.json for that spec.
- use typescript-fetch to generate the api
- see generated file, it doesn't use the auth data.

##### Suggest a Fix

I actually think it'd be better for everyone if we use a http client, in this way, user can create middlewares and attach to client and he can extend this very easy. I suggest `github.com/crazyfactory/ts-http-client` which I've been using because of powerful middleware support, mocking api support out of the box AND cache requests based on configuration (if required of course).

I can create a PR a little later using this package.

**Comment by wing328** [comment]
@cyberhck you may also want to generate TS Fetch API client from 2.3.0 branch (which contains breaking changes) to see if the same issue persists.

**Comment by wing328** [comment]
v2.2.3 has been released and current master is 2.3.0. Please give it a try and let us know if it's still an issue.

**Comment by cyberhck** [comment]
we ended up writing our own sdk generator in TypeScript which uses our own http client because our http client supports a lot of things like middleware, mocking an endpoint, caching, etc out of box.

So No, I don't think I'll be doing that, someone else if provided a sample generated api.ts file, I could look into it.
