### ISSUE TITLE
Generate Autorest compatible methods from operationId

### ISSUE THREAD

**Issue by TsengSR** [swagger-api/swagger-codegen#5657]
##### Description

When generating an swagger client from a swagger.json which uses Autorest compatible operation ids, the prefix isn't removed. 

In order to make Autorest split API per controller, the `operationId` must have an underscore, i.e. `Configs_GetConfigById`, this will result in a `Configs` class and a method `getConfigById` method. 

Swagger-gen however creates a `ConfigsApi` method and `configsGetConfigById` method. 

Can we have an additional parameter to use the Autorest style and use the first part (before underscore) for the `XxxApi` class and `getConfigById` method?

##### Swagger-codegen version

swagger-codegen-cli.jar 2.2.2

##### Swagger declaration file content or url

The swagger.json produced by Swashbuckle.AspNetCore (.NET Core swagger definition generator), with a custom filter to generate this `operationId` to make it Autorest compatible for per-controller api generation.

(for YAML code) or
```json
  "paths": {
    "/api/Configs": {
      "get": {
        "tags": [
          "Configs"
        ],
        "summary": "Returns a list of all configurations.",
        "description": "",
        "operationId": "Configs_GetAll",
        "consumes": [],
        "produces": [
          "text/plain",
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ]
      }
    }
  }
```

##### Command line used for generation

Windows Batch File,

`java -jar .\swagger-codegen-cli.jar generate -i swagger.json -l typescript-angular2 -o output\rest-client`

##### Steps to reproduce

1. Generate swagger.json with operationId in format of `Controller_ActionName`, i.e. `Configs_GetAllConfigs`
2. generate client with above parameters

##### Suggest a Fix

Add an additional parameter to use [Autorest convention](https://github.com/Azure/autorest/blob/master/docs/developer/guide/defining-clients-swagger.md#generating-operation-classes) for grouping the Api. 

Alternatively (or additionally) it would be nice if the the method could be replicated on multiple classes, depending on which tags are set up for the action, i.e. if an path is configured with `"tags": [ "Foo" ]` the method should be on both, `ConfigsApi` (from `operationId` if autorest parameter is set) and `FooApi`. Additional parameter for completely ignoring everything before `_` would be good too, if the user wants to solely depend on the `tags` for grouping the Api

**Comment by wing328** [comment]
> When generating an swagger client from a swagger.json which uses Autorest compatible operation ids, the prefix isn't removed.

That's the expected behaviour for all generators (including typescript-angular2 client)

> In order to make Autorest split API per controller, the operationId must have an underscore, i.e. Configs_GetConfigById, this will result in a Configs class and a method getConfigById method.

Swagger Codegen uses `tags` to name the class instead of using a prefix in the operationId.

> Can we have an additional parameter to use the Autorest style and use the first part (before underscore) for the XxxApi class and getConfigById method?

Technically it's possible but I do have some concerns about the approach (see more below)

> The swagger.json produced by Swashbuckle.AspNetCore (.NET Core swagger definition generator), with a custom filter to generate this operationId to make it Autorest compatible for per-controller api generation.

What about **not** using the custom filter? Would it still generate the operationId with prefix?

I would recommend not naming your operation ID in the form of "prefix_methodName" as this convention seems only recognizable by AutoRest only. Many other tools like ReadyAPI, Postman do not respect such convention but instead use `tags` to group endpoints.

> Additional parameter for completely ignoring everything before _ would be good too, if the user wants to solely depend on the tags for grouping the Api

Technically it's also possible (and not difficult)

**Comment by TsengSR** [comment]
> What about not using the custom filter? Would it still generate the operationId with prefix?
>
>I would recommend not naming your operation ID in the form of "prefix_methodName" as this convention seems only recognizable by AutoRest only. Many other tools like ReadyAPI, Postman do not respect such convention but instead use tags to group endpoints.

Then Autorest users won't be able to generate a client with an Api class per controller and everything will land in one single huge class. With with 70 to 150 actions this ends quite in a mess, also making autocomplete of TypeScript and other languages quite useless (having 100 methods when you type `.get` is less then optimal).

Also using only method name may not be unique enough, at least in the way I am about to use it. For example to generate a nice Api, the the methods should be nice and readable so `GetAll` or `GetAllById` may appear on multiple controllers. Prefixing it with the controller name makes it unique though. 

Putting the class or controller name into the action seems redundant, i.e. `GetAllConfigs`, `GetAllUsers` and will result in client API like `configs.getAllConfigs()`, since the controller/Api name type already implies what's returned.

**Comment by wing328** [comment]
> Then Autorest users won't be able to generate a client with an Api class per controller and everything will land in one single huge class.

Not sure if you agree, Autorest should have used `tags` instead of prefix in operation ID to classify the API endpoints/operations.

If we add an option "removeOperationIdPrefix", would that make your life easier in using Swagger Codegen with your current spec?

**Comment by TsengSR** [comment]
> If we add an option "removeOperationIdPrefix", would that make your life easier in using Swagger Codegen with your current spec?

Yes, that would do it. Then both generators would be able to generate an rest client with the correct (and friendly) method names and splitting/grouping across classes

**Comment by wing328** [comment]
OK. I should have some cycle this weekend to work on it. Will keep you posted.

**Comment by wing328** [comment]
@TsengSR #5674 merged into master. Please pull the latest master to give it a try.

**Comment by TsengSR** [comment]
Yep, works great
