### ISSUE TITLE
[Typescript-angular2] Inheritance in generated model not working

### ISSUE THREAD

**Issue by sidebaet** [swagger-api/swagger-codegen#5658]
##### Description

I use swagger to generate my angular4 client and I have an issue when I have inheritance in my model. The generated typescrpit is not correct. The generated  code is : 

parent.ts:

export interface Parent{}

child.ts:

import {Parent} from './Parent';

export interface Child extends **models**.Parent{}

##### Swagger-codegen version

2.3.0-SNAPSHOT
##### Swagger declaration file content or url

BaseHospitalVisit:
  type: object
AmbulatoryVisit:
  allOf:
    - $ref: '#/BaseHospitalVisit'
    - type: object

##### Command line used for generation

<execution>
                        <id>API V1</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-resources</phase>
                        <configuration>
                            <apiPackage>api</apiPackage>
                            <modelPackage>model</modelPackage>
                            <inputSpec>/v1/api.yaml</inputSpec>
                            <language>typescript-angular2</language>
                        </configuration>
                    </execution>

##### Suggest a Fix

Generate:
export interface Child extends Parent{}

**Comment by wing328** [comment]
@sidebaet can you share the spec via https://gist.github.com so that the community can use it to reproduce the issue?

**Comment by austin94** [comment]
@wing328 I am able to reproduce with: https://gist.github.com/austin94/11642f6482dc2eed7a227979f0b44dfe

The fix for me was to just remove the `models.` string in `modelGeneric.mustache`. It appears that this was being used when the models namespace was still around?

**Comment by wing328** [comment]
@austin94 thanks for sharing more. I wonder if you can file a PR with the suggested fix when you've time.

**Comment by austin94** [comment]
@wing328 Sure, I can submit a PR in the next few days.

**Comment by austin94** [comment]
@wing328 turns out I was wrong.  I must have been on an old version of `2.3.0`.  Currently on master and 2.3.0 branches the `models` usage is working correctly in `modelGeneric.mustache`.

While exploring I found the solution for #5709 so I may submit a PR for that issue if no one has started yet.
