### ISSUE TITLE
How can I change text header and text links of left side of html2 version

### ISSUE THREAD

**Issue by NabiKAZ** [swagger-api/swagger-codegen#5680]
Hi,

How can I change text header and text links in position 1 and 2 specified in this picture:

![image](https://cloud.githubusercontent.com/assets/246721/26275748/645d5568-3d7d-11e7-980e-dbd9c4575584.png)

Thanks

**Comment by taxpon** [comment]
@NabiKAZ You can change API group name (`CONVERSATION` in 1) by using `tags` in operation section and also can change operations' names in 2 by using `operationId` in each operation.

**Comment by NabiKAZ** [comment]
@taxpon Thanks.
1) I use tags, but I see `API METHOD -` prefix for all sections!
2) I set `Get Comments` for `operationId` but appears `get Comments` !

**Comment by wing328** [comment]
You can also customize the templates using the `-t` option: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-customize-the-template-to-add-headerfooter-to-the-auto-generated-code
