### ISSUE TITLE
[Java][Spring] Allow controller methods to throw Exceptions

### ISSUE THREAD

**Issue by stevecookform3** [swagger-api/swagger-codegen#5686]
##### Description

Currently all API interfaces are defined to not throw exceptions. This means that implementations that follow the throw / global exception handler pattern don't work without manually editing the API interface.

Would like to change this to add `throws Exception` to all @RequestMapping methods in the API interface.

e.g. 

```
@Api(value = "users", description = "the users API")
public interface UsersApi {
...
    @RequestMapping(value = "/users", method = RequestMethod.POST)
    ResponseEntity usersPost(@RequestBody UserCreation userCreationRequest); 
```

becomes

```
    @RequestMapping(value = "/users", method = RequestMethod.POST)
    ResponseEntity usersPost(@RequestBody UserCreation userCreationRequest) throws Exception;

```
##### Swagger-codegen version

latest head

##### Suggest a Fix

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache

change

`{{/allParams}}){{^jdk8}};`

to 

`{{/allParams}}){{^jdk8}} throws Exception;`

**Comment by wing328** [comment]
@stevecookform3 looks to me it's breaking change so the change should be filed against 2.3.0 branch.

cc @cbornet @jfiala

**Comment by stevecookform3** [comment]
@wing328 @cbornet @jfiala I've attached the PR.

**Comment by bmtKIA6** [comment]
I am not seeing this as part of 3.0.0. Was it removed? https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache

**Comment by HugoMario** [comment]
Hi @bmtKIA6, can you please file a new ticket to port this for spring on codegen 3.0.0?

**Comment by bmtKIA6** [comment]
Created the issue and a PR.
