### ISSUE TITLE
[Java][Spring] missing @Valid / @Validated for model & param validation

### ISSUE THREAD

**Issue by stevecookform3** [swagger-api/swagger-codegen#5688]
##### Description

In order to use the Spring validation code, the`@Valid` annotation needs to be added to various places (such as private variables on the model, and controller method parameters). In addition, model and controller classes need to be annotated with `@Validated`.

1. To validate nested models, Spring requires you to annotate each private variable that contains a validated class with `@Valid`, and the class with `@Validated`. This is not currently done, meaning that things like Regex patterns are ignored on nested classes.

2. To validate parameters, the controller also needs to be `@Validated` and the parameters marked with `@Valid`.

3. Spring also requires that you include the validation API as well as an implementation of the validator into your gradle build file, such as:	
'javax.validation:validation-api:1.1.0.Final' and 'org.hibernate:hibernate-validator:5.1.3.Final'

4. IIUC you'll also need to include a config bean:

```java
@Configuration
public class ValidationConfig {
    @Bean
    public MethodValidationPostProcessor methodValidationPostProcessor() {
        final MethodValidationPostProcessor methodValidationPostProcessor;
        methodValidationPostProcessor = new MethodValidationPostProcessor();
        methodValidationPostProcessor.setProxyTargetClass(true);
        return methodValidationPostProcessor;
    }
}
```

It looks like various issues/fixes have been raised in the past, but all the required fixes dont seem to have been merged into the main branch.

##### Swagger-codegen version

latest head

##### Command line used for generation

generate -i swagger.yaml -l spring

##### Suggest a Fix

I've fixed the issue on our local fork here (although this is against a slightly older version, it would be easy enough to update):

https://github.com/form3tech/swagger-codegen/commit/a5e1fc1a38dea9882bd7328a1e57a2d265af0f4d

**Comment by stevecookform3** [comment]
#5517 
#5360 
#5393

**Comment by wing328** [comment]
Both #5517 and #5393 have been merged into master. Please file a PR so that we can review the fix.

**Comment by stevecookform3** [comment]
@wing328 sorry finally got round to this. I've filed the referenced PR.

**Comment by tasneem93** [comment]
@wing328 please let us know when this PR is LIVE as we are having the same issues. This PR will solve our problem. Thanks @stevecookform3 for the PR.

**Comment by wing328** [comment]
@tasneem93 please use the SNAPSHOT version before the stable release of 2.3.0:https://github.com/swagger-api/swagger-codegen#compatibility
