### ISSUE TITLE
python from __future__ import print_statement vs print_function at http://editor.swagger.io/

### ISSUE THREAD

**Issue by rompic** [swagger-api/swagger-codegen#5692]
##### Description

When I generate a python client the readme tells me to import print_statement:
`from __future__ import print_statement`

shouldn't this rather be 
`from __future__ import print_function`

##### Swagger-codegen version
used http://editor.swagger.io/

**Comment by rompic** [comment]
see https://github.com/swagger-api/swagger-codegen/blob/8ccf9828e425da79b90b3a985fc37bc672050be4/modules/swagger-codegen/src/main/resources/python/api_doc.mustache#L22

**Comment by wing328** [comment]
@rompic you're right. It should be print_function instead just like we've documented in the README.md: https://github.com/swagger-api/swagger-codegen/blob/f63cae8aae4f780613deafd5a5bbe7633436e2ce/modules/swagger-codegen/src/main/resources/python/README.mustache#L56

May I know if you've time to file a PR to replace print_statement with print_function?
