### ISSUE TITLE
swagger-codegen not generating classes for schemas defined in referenced json files

### ISSUE THREAD

**Issue by bluewolf8** [swagger-api/swagger-codegen#5693]
##### Description

I am unable to get swagger-codegen to generate classes for json schemas defined in files separate from the main API definition file

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

This is what api.json looks like:

https://gist.github.com/bluewolf8/94bcb589f44c49ea2e610e428a73c523

The person.json file referenced here lives alongside api.json (i.e. at the same level) and contains the following:

https://gist.github.com/bluewolf8/35857e7e5b2b700a8e0e9f17df298970

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.2.jar generate -i api.json -l java -o gen -v

##### Steps to reproduce

Use the gists listed above and run the command line specified.
I would expect the code generation to generate a class called Person.java - but it does not - in fact it does not generate any model classes.Also the verbose logging logs the following right at the start which makes me think it is interpreting the reference incorrectly and for some reason prepending a #definitions to the $ref.

https://gist.github.com/bluewolf8/da33d07398af3c2e05b3f70213f2b43c

**Comment by wing328** [comment]
@bluewolf8 please try the latest master to generate the code and use `./person.json#/definitions/person` instead.

**Comment by bluewolf8** [comment]
Hi - this works as expected even with version 2.2.2. Adding the ./ to the $ref did it.
