### ISSUE TITLE
Preserving Entity Bean static variables

### ISSUE THREAD

**Issue by edasaur** [swagger-api/swagger-codegen#5696]
I have been trying to use Swagger Codegen to generate Java client libraries, and I've noticed that none of the DTO's that were generated preserved the static constants that were originally in the entity beans that swagger scanned. I looked through the output from `debugModels` and didn't seem to see anything there...

Is it possible to generate DTO's while preserving the static constants from the original entity beans?

**Comment by edasaur** [comment]
Just to go into a little more detail, say I have a bean:

`
public class EntityBean {
    public static final String CONSTANT = "constant"
    
    private final String variable;
    public EntityBean() {}

    public void setVariable(String var) {
        this.variable = var;
    }
    
    public String getVariable() {
        return this.variable
    }
}`

the DTO generated would contain the `variable` field, but not have the `CONSTANT` String...

**Comment by cbornet** [comment]
It's not clear : is that our own code ? The codegen doesn't know anything about it ...

**Comment by edasaur** [comment]
Ah, so the `EntityBean` class is just an example of some model code I might have

**Comment by edasaur** [comment]
However, it seems that I found a workaround for this issue, so I no longer need this open!
