### ISSUE TITLE
Rxjava2 code generation won't work

### ISSUE THREAD

**Issue by wafer-li** [swagger-api/swagger-codegen#5697]
##### Description

When using the following config:

```json
{
  "library": "retrofit2",
  "useRxJava2": true
}
```

The generated code doesn't use the rxjava2 call adapter, instead it use the default retrofit `Call` implementation.

With `"useRxJava" = true` will use the rxjava1.x implementation, which I don't want.

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url
http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

```
swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l java -c config.json  -o ~/Desktop
```

##### Steps to reproduce

Use the above command line to generate code

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/5320

**Comment by wing328** [comment]
If I don't think 2.2.2. supports RxJava2, please build the JAR from the latest master and give it another try.

**Comment by wafer-li** [comment]
Ok, I will try to build it

2017年5月24日 12:08，"wing328" <notifications@github.com>写道：

**Comment by wing328** [comment]
Let us know if it's still an issue.

You may also want to generate the client based on 2.3.0 branch instead, which contains breaking changes (enhancements, bug fixes)

**Comment by wafer-li** [comment]
2.3.0 have no problem

**Comment by wing328** [comment]
Good. Closing this issue.
