### ISSUE TITLE
'exec' keyword isn't obfuscated in Python

### ISSUE THREAD

**Issue by brendandburns** [swagger-api/swagger-codegen#570]
This is with ```develop_2.0``` branch

For example:
```json
"v1beta3.Handler": {
      "id": "v1beta3_Handler",
      "properties": {
        "exec": {
          "$ref": "#/definitions/v1beta3_ExecAction",
          "description": "exec-based handler"
        },
...
```

This generates:

```python
...
   self.exec = ...
...
```

Which cause the python interpreter to die.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-codegen/commit/492ab20c00cd50ec1b6d3436e07f9a97dce042c8

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-codegen/commit/492ab20c00cd50ec1b6d3436e07f9a97dce042c8 now keywords (from https://docs.python.org/release/2.5.4/ref/keywords.html) are escaped with `_`
