### ISSUE TITLE
need a way to print http response for an api call.

### ISSUE THREAD

**Issue by dnome2** [swagger-api/swagger-codegen#5703]
##### Description

Currently for every api, the template sets "kwargs['_return_http_data_only'] = True" and hence response data like headers, status code don't get printed...if i set it to false i do get to see the headers, status code etc but modifying every api is probably not an efficient way of doing it.

So is there a way to print all of http response data+headers etc. ?

##### Swagger-codegen version

2.2.2

##### Command line used for generation

swagger-codegen generate -i master-restapi.yaml -DapiDocs=false,modelDocs=false -l python -o py-client

##### Steps to reproduce
invoke any rest api from the generated code.

##### Suggest a Fix

Can you allow user to set the option for return type or provide any other way to get the status code and headers get printed ?

**Comment by wing328** [comment]
@dnome2 Have you tried the `_with_http_info` method for an endpoint? e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/apis/pet_api.py#L69

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by jinxingf** [comment]
@wing328 

I also have the same problem. the arg `_return_http_data_only` in the generated code is hardcode  like this, eventhough pass the `_return_http_data_only` in the kwargs.

```
"""
    def add_pet(self, body, **kwargs):  # noqa: E501
        """Add a new pet to the store  # noqa: E501
          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_pet(body, async_req=True)
        >>> result = thread.get()
        :param async_req bool
        :param Pet body: Pet object that needs to be added to the store (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True           # the  _return_http_data_only is hardcode in here
        if kwargs.get('async_req'):
            return self.add_pet_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.add_pet_with_http_info(body, **kwargs)  # noqa: E501
            return data
```

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/api/pet_api.py#L36

**Comment by wing328** [comment]
@jinxingf thanks for tagging me but I'm no longer involved in this particular project. I hope others will be able to help you out.
