### ISSUE TITLE
[PYTHON] mismatch between html2 python method names examples (CamelCase) and generated python method names (underscore)

### ISSUE THREAD

**Issue by rompic** [swagger-api/swagger-codegen#5706]
##### Description

The generated html2 doc method name examples (camelCase) do not match the actual method names (with underscore) when a python client is generated.

E.g. see addPet 
![add_pet](https://cloud.githubusercontent.com/assets/6322123/26454720/2f68ea54-4168-11e7-8cb4-08d8f6e6c309.png)

![add_pet_code](https://cloud.githubusercontent.com/assets/6322123/26454802/6bf85888-4168-11e7-966f-cbd2c0631802.png)

underscore should be the way to go according to https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables

##### Swagger-codegen version

used http://editor.swagger.io/#/

##### Swagger declaration file content or url
petstore example

##### Command line used for generation

used http://editor.swagger.io/#/

##### Steps to reproduce

- go to http://editor.swagger.io/#/
- generate html2 doc for petstore example
- generate python client for petstore example

##### Related issues

similar to https://github.com/swagger-api/swagger-codegen/issues/5169 (curl)

**Comment by wing328** [comment]
Thanks for the fix by @taxpon 

@rompic please pull the latest master to give it a try.

**Comment by rompic** [comment]
pulled master, ran ./bin/html2-petstore.sh
LGTM!

thx for the quick fix (this one really drove me crazy).

**Comment by wing328** [comment]
@rompic thanks for the confirmation.
