### ISSUE TITLE
[Java] Numbers with enum are wrongly serialized as String

### ISSUE THREAD

**Issue by sdoeringNew** [swagger-api/swagger-codegen#5712]
##### Description

Number enum models are generated and marshalled correctly. But unmarshalling fails because the value will be written as String into the resulting JSON. This is wrong because it should be a number.

##### Swagger-codegen version

Tested with Version: 2.2.2

##### Swagger declaration file content or url

_samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/model/EnumTest.java_

##### Command line used for generation

(n/a)

##### Steps to reproduce

(n/a)

##### Related issues

(n/a)

##### Suggest a Fix

Add the ```@JsonValue``` annotation to the getValue() method newly introduced with #5619.

**Comment by wing328** [comment]
Closing via #5713
