### ISSUE TITLE
[Android] references

### ISSUE THREAD

**Issue by PhilippMundhenk** [swagger-api/swagger-codegen#5720]
##### Description
In the curent code generator used on editor.swagger.io, the referenced classes are generated as "InlineResponseX" instead of their classname. The appropriate class is still being generated but does not seem to be used by the services referencing it.

This worked before editor.swagger.io was updated.

##### Swagger-codegen version
current version from editor.swagger.io

##### Swagger declaration file content or url
```yaml
[...]
/stuff/{abc}:
    get:
      [...]
      responses:
        200:
          description: Stuff.
          schema:
            $ref: '#/definitions/Stuff'
[...]
definitions:
  Stuff:
    type: object
    properties:
      name:
        $ref: '#/definitions/Name'
      other:
        type: string
        description: other stuff.
[...]
```

**Comment by wing328** [comment]
Usually InlineResponseX means you've object/schema defined inline. A better way is to defined the model in the definition section like what you've shown in your question.

You may also want to build the JAR based on the latest master as Swagger Editor is using the latest stable version (not latest master).

There're other ways to generate Android API client. Please refer to https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk for more information.
