### ISSUE TITLE
[Java] snake_case swagger contents are converted to camelCase java code

### ISSUE THREAD

**Issue by felixvolz** [swagger-api/swagger-codegen#5721]
##### Description

I am using swagger-codegen 2.2.2 to generate java code from a swagger file. the contents of the swagger contract are snake_case but the java generated is camelCase. Is there a setting that corrects this bug. 

##### Swagger-codegen version

swagger-codegen 2.2.2 
 

##### Command line used for generation

Building from Maven via the following maven goal

<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>2.2.2</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							
							<inputSpec>src/main/resources/swagger.yaml</inputSpec>

							
							<language>jaxrs-cxf</language>
							<addCompileSourceRoot>true</addCompileSourceRoot>
							<output>${project.build.directory}/generated</output>

							
							<configOptions>
								<sourceFolder>src/main/java</sourceFolder>
								<dateLibrary>joda</dateLibrary>
								<modelPackage>io.swagger.model</modelPackage>
								<apiPackage>io.swagger.api</apiPackage>
								
								<debugModels>true</debugModels>
								<modelPropertyNaming>snake_case</modelPropertyNaming>
							</configOptions>

							<generateApiTests>false</generateApiTests>

						</configuration>
					</execution>
				</executions>
			</plugin>

##### Steps to reproduce

maven clean install (wiht above maven goal)

##### Related issues
As far as I can see - its been resolved here, but I cant see HOW/WHERE to apply modelPropertyNaming to force snake_case
https://github.com/swagger-api/swagger-codegen/pull/4508

**Comment by wing328** [comment]
Java uses "camelCase" for naming variables and the Java API client comes with a mapping between java variable name and original name defined in the spec.

What issues are you seeing when using the Java API client?

**Comment by wing328** [comment]
> My issue is - 3rd party consumers will be passing requests that are snake_case. The request will be rejected as the swagger-codegen generated code is camelCase.

I don't think that's true. The serialization process in the API client should take care of that with the mapping between Java variable name and original name defined in the spec.

Have you performed a test and inspect the JSON payment sent out by the Java API client generated by Swagger Codegen?

**Comment by felixvolz** [comment]
Okay I guess I missed including an important bit. I am exposing my service via cxf:rsServer (Camel) for 3rd parties to consume. 

`<cxf:rsServer address="/rest" id="rest" serviceClass="io.swagger.api.DefaultApi">
        <cxf:providers>
            <ref bean="jsonProvider"/>
        </cxf:providers>
    </cxf:rsServer>`

Are you saying its the responsibliity of rsServer to map from the received json snake_case to java camelCase?

**Comment by ePaul** [comment]
The generated classes for each Java-based "language" or "library" usually contain annotations to make sure that the on-the-wire version of names are as they are in the Swagger/OpenAPI definition.

It might be that `jaxrs-cxf` does something wrong here, or it doesn't actually work with the `<cxf:rsServer>`.

**Comment by felixvolz** [comment]
I re

**Comment by ginere** [comment]
While creating a java client for the themoviedb.org, (https://www.themoviedb.org/talk/58691a749251414e7500c442) I have one problem with attribute names like _id, example:
                                    
 ```
                                     "properties": {
                                            "_id": {
                                                "type": "string"
                                            },
                                            "id": {
                                                "type": "integer"
                                            },

                                     }
```
I need a way to differentiate attribute id and _id.

Kind regads
