### ISSUE TITLE
Bad class name for JsonSubTypes

### ISSUE THREAD

**Issue by manuc66** [swagger-api/swagger-codegen#5735]
##### Description

``@JsonSubTypes.Type(value =`` does not use the generated class name.

##### Swagger-codegen version

``2.2.2``

##### Swagger declaration file content or url

https://gist.github.com/manuc66/6949ccf855a54e65db40f32eb4b37af2

produce this:
```java
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-30T14:56:11.096+02:00")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "key", visible = true )
@JsonSubTypes({
  @JsonSubTypes.Type(value = invalid-foo-error.class, name = "invalid-foo-error"),
})

public class Error {
  @JsonProperty("key")
  private String key = "generic-error";

  @JsonProperty("message")
  private String message = null;

  public Error key(String key) {
    this.key = key;
    return this;
  }
```

``invalid-foo-error.class`` should instead be ``InvalidFooError.class``

##### Suggest a Fix

I'm preparing a fix that would fix some ``.mustache`` files

**Comment by wing328** [comment]
Fixed via #5736
