### ISSUE TITLE
com.sun.org.apache.bcel.internal.classfile not found at swagger-codegen core libary

### ISSUE THREAD

**Issue by claudefalbriard** [swagger-api/swagger-codegen#5739]
##### Description
Trying to build the latest swagger-codgen package using the "mvn clean package" command. The build stops at the compile step for swagger-codegen (core library), unable to find the package named: "com.sun.org.apache.bcel.internal.classfile". I'm using IBM Java 7 SDK.  

I also tried to add the package using a new Maven dependency that contains the package, as described below, but still getting the same error.  
```
<!-- https://mvnrepository.com/artifact/com.sun.xml.parsers/jaxp-ri -->
<dependency>
    <groupId>com.sun.xml.parsers</groupId>
    <artifactId>jaxp-ri</artifactId>
    <version>1.4.2</version>
</dependency>
```
**Error Message:** 
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/claudef/tmp/swagger-codegen/swagger-codegen-master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java:[5,50] package com.sun.org.apache.bcel.internal.classfile does not exist
[ERROR] /home/claudef/tmp/swagger-codegen/swagger-codegen-master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java:[5,50] package com.sun.org.apache.bcel.internal.classfile does not exist
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  2.802 s]
[INFO] swagger-codegen (core library) ..................... FAILURE [ 15.117 s]
[INFO] swagger-codegen (executable) ....................... SKIPPED
[INFO] swagger-codegen (maven-plugin) ..................... SKIPPED
[INFO] swagger-generator .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

Any hints how to correct the build, or bypass this error? 

##### Swagger-codegen 2.3.0

Master 

##### Command line used for generation

mvn clean package

**Comment by wing328** [comment]
@claudefalbriard can you try using Open JDK instead of IBM Java 7 SDK.?

**Comment by wing328** [comment]
Let us know if you still need help.

We've also setup a workflow to publish a SNAPSHOT version to sonatype.
