### ISSUE TITLE
[C++] Restbed Server Stub Code Generator

### ISSUE THREAD

**Issue by stkrwork** [swagger-api/swagger-codegen#5741]
##### Description

I created a new code generator template for the Restbed framework. The framework can be found here: https://github.com/Corvusoft/restbed

##### Swagger-codegen version

Latest on master

I haven't created the pull request yet, but the changes are ready on a fork.

**Comment by wing328** [comment]
@stkrwork wow... that's the first C++ server stub generator for Swagger Codegen 👏 👏 👏 

Please submit a PR so that we can review the new generator.

**Comment by stkrwork** [comment]
#5742 is the pull request
