### ISSUE TITLE
[QUESTION] 2.3.0 Release Date

### ISSUE THREAD

**Issue by nirvik66** [swagger-api/swagger-codegen#5745]
Hi!

According to the README file the release for 2.3.0 was expected for Apr/May 2017. Could you please give me an estimate when the build 2.3.0 will become the stable one?

Thanks!

**Comment by wing328** [comment]
@nirvik66 thanks for the question but I'm sorry to inform you that the release has been postponed. 

I'll go through all the remaining issues in the next couple of days and come up with a list of outstanding items pending for 2.3.0.

**Comment by nirvik66** [comment]
Thanks for letting me know!

**Comment by natami** [comment]
Are we closer to a 2.3.0 release?

**Comment by rompic** [comment]
same question here :)

**Comment by wing328** [comment]
We hope to release by the end of July, 2017

**Comment by wing328** [comment]
UPDATE: We now have a workflow to publish a SNAPSHOT of 2.2.3 and 2.3.0 as part of the CI (travis). Please refer to https://github.com/swagger-api/swagger-codegen#compatibility for more information.

**Comment by wing328** [comment]
2.2.3 (not 2.3.0) has been released. We hope to release 2.3.0 by the end of Aug as there're some ongoing work to refactor some of the API clients.

**Comment by rompic** [comment]
Thanks for the update! Looking forward to the release.

**Comment by dougbacelar** [comment]
Hi there, just wondering if we have an update on this :)

Thanks!

**Comment by johnnyxh** [comment]
Hey, also wondering what the status is on the 2.3.0 release

**Comment by cjkumaresh** [comment]
@wing328 Any update on 2.3.0 release

**Comment by sherbondy** [comment]
Would love to see the 2.3 release make it out into the world!

Lack of easily-configurable connection pool maxsize in the current python client code gen is putting a damper on my day.

Wish you all a swift and bug-free stable release cutting! And sorry for the issue-spam, really appreciate the open source work you all do.

**Comment by zetlan** [comment]
+1 on this. The 2.3.0 release will include the OpaqueToken -> InjectionToken update, needed for Angular 5; right now I'm having to hack that into place.

**Comment by wing328** [comment]
Hi guys, I'm aiming a release before the end of this year.

Will keep you guys posted.

**Comment by wing328** [comment]
2.3.0 released!! Huge thanks to the awesome Swagger Codegen community.

Tweet to promote the new release: https://twitter.com/wing328/status/944259218386718720
