### ISSUE TITLE
Any tips for the cleanup of generated files?

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-codegen#5747]
##### Description

I'm the main contributor to the JavaPlayFramework template and since the generator is pretty stable right now, I was wondering if there is some ways to clean the generated files.

Here are the problem I see in my generated codes:

1. Route files are in serious needs of some alignment. It looks like this:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/java-play-framework/conf/routes
But should ideally look like this:
https://github.com/playframework/play-java-starter-example/blob/2.5.x/conf/routes

2. A lot of files are using unnecessary import statement. I have done my best using the generator to import the minimum but in a lot of cases, "you don't know" what the file will contains... Is there a way to launch some kind of static analysis at the end of the generation to detect and remove the unnecessary import like Lint in IntelliJ propose? This is more a problem for the controllers.

Any ideas how to add a mechanism that do that in my code or in every other template in general?

Thanks

##### Swagger-codegen version

All versions

**Comment by ePaul** [comment]
I think some other languages are having just the minimum imports (which are used in the hardcoded parts of the template) hardcoded, and add other stuff dynamically during e.g. the operation or model postprocessing to some `import` map/list. That one is later used to expand to the list of imports. (I didn't have a look at the Play stuff yet and don't have the code in front of me, so I can't give more details. If I remember, I'll have a more detailed look later.)
