### ISSUE TITLE
[JAVA] date-time is not handled correctly if the type is defined after it's referenced

### ISSUE THREAD

**Issue by jstockall** [swagger-api/swagger-codegen#5752]
Two types are defined. UserOfTime and Time. UserOfTime has a single property that references Time. Time is defined as `"type": "string", "format": "date-time"`.

If Time is defined after UserOfTime the Time class is never generated. If Time is defined before UserOfTime the property is converted to a string.

In 2.2.2 this worked as expected using a generated Time class no matter which order the two types are defined.
in 2.3.0-SNAPSHOT and 2.2.3-SNAPSHOT (git master) there is an undefined reference to the Time class when Time is defined before UserOfTime. When Time is defined after UserOfTime a String is used instead of an instance of the Time class.

Swagger definition with two definitions of UserOfTime, one before Time and one after.

https://gist.github.com/jstockall/3c2150029924c0c20b16ee11a26c202b

Generated with `java -jar ../swagger-codegen-cli.jar generate -i swagger.json -o . -l java`

**Comment by wing328** [comment]
@jstockall you may want to pull the latest master (2.3.0) to give it another try with a newer version of Swagger Parser to see if the issue persists.

**Comment by jstockall** [comment]
Tested with 2.3.0 and both classes are now identical and defined using a String for the timestamp
