### ISSUE TITLE
Apache Authentication and Authorization Conf Gen

### ISSUE THREAD

**Issue by stkrwork** [swagger-api/swagger-codegen#5760]
##### Description

With the information in the Swagger AuthMethods component, a Apache configuration could be generated.

It might also be useful to extend the AuthMethods Class to include a groups Array, to create the group handling in Apache for HTTP Basic/Digest Authentication/LDAP.

Through this one can generate the server  stub and reroute the calls to the server stub via apache. Apache then takes care of the authentication and authorization.

**Comment by wing328** [comment]
Yes, I think that will be useful. There are discussions about generating a DB schema from OpenAPI/Swagger 2.0 spec so there are unlimited possibilities with Swagger Codegen to generate "things" other than API client, server stub, documentation.

**Comment by stkrwork** [comment]
I did make an implementation for it, but it misuses the scope parameters for groups for apache authorization instead as swagger codegen does not support groups for authorization for http basic requests.

**Comment by wing328** [comment]
> as swagger codegen does not support groups for authorization for http basic requests.

What about using vendor extensions to document that in the spec?

**Comment by stkrwork** [comment]
So the user would already include a vendor extension section in the input spec containing the groups?

Something like this:
`"/pet": {
      "post": {
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "description": "",
        "operationId": "addPet",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "pet"
        ],
        "summary": "Update an existing pet",
        "description": "",
        "operationId": "updatePet",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Pet not found"
          },
          "405": {
            "description": "Validation exception"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ],
        "vendorExtensions": [
          {
            "x-apache-groups": [
              "test",
              "test2"
            ]
          }
        ]
      }
    },`

**Comment by wing328** [comment]
Yup, that's one way to do it if we want to classify the endpoint into 1 or more groups.

Is the Apache group similar to the security definition (e.g. petstore_auth)?

**Comment by stkrwork** [comment]
If the logged in user is not part of the group on the apache server, the apache server returns unauthorized.

Through this you could define a group write, and on all POST PUT and DELETE methods add a `require group write` in `<limit>` tags.  If you want every logged in user to use a resource, you would define `require valid-user`. If everybody can access is, just leave away the require statement.

**Comment by wing328** [comment]
I would suggest you to submit a PR for the generator so that we can look at the output and see how we can improve it together.

**Comment by stkrwork** [comment]
#5800 is the pr but it is still not ready yet. but it shows the basic idea.

**Comment by wing328** [comment]
@stkrwork I think it's a very good starting point for a configuration generator 👍 

I would suggest you to list out a list of tasks left to be done to make the generator ready for an alpha/beta release so that the community can help out.

**Comment by stkrwork** [comment]
Well in terms of using it, the generated config can be copied into an apache webserver config right now.

If one would want to extend it, it would be possible to add more cli options for generating in cgi handling, enable logging, change the path of the log files, or change the authentication from basic to having a form to handle login.

Other things that can be done to extend it is setting the server name at the top and encapsulate the currently generated code in VirtualHost tags, to change generated config into a more complete config stub.

**Comment by wing328** [comment]
@stkrwork I would suggest we merge it into master so as to gather feedback from the community. Then we can create a list of tasks for enhancements (similar to what you've done for c++ RestBed recently)

**Comment by stkrwork** [comment]
Yes, I agree. I'll put up the todo list as soon as its merged in.

**Comment by stkrwork** [comment]
#5936 for the todo list

**Comment by wing328** [comment]
Closed via #5800 

We'll continue the discussion for enhancements in #5936
