### ISSUE TITLE
Cannot use Javascript generated code 

### ISSUE THREAD

**Issue by sebastienFrance** [swagger-api/swagger-codegen#5772]
##### Description

I have a small REST API defined using Swagger. I have generated the Java code (JAX-RS) and implemented the service, it works.
Now I have generated the Javascript client code and I would like to integrate it in my React App. I'm not able to integrate due to issue when importing the Swagger generated code.

##### Swagger-codegen version

Latest online version

##### Swagger declaration file content or url

No issue with the declaration file

##### Command line used for generation

Javascript

Here some error when trying to build a bundle with web pack

Module not found: Error: Can't resolve 'fs' in '/Users/sebastien/Documents/Javascript/Stackoverflow/superagenttest/src'
 @ ./src/ApiClient.js 156:74-87 156:108-121
 @ ./src/main.js

ERROR in ./src/index.js
Module not found: Error: Can't resolve 'ApiClient' in '/Users/sebastien/Documents/Javascript/Stackoverflow/superagenttest/src'
 @ ./src/index.js 17:4-84
 @ ./src/main.js

ERROR in ./src/index.js
Module not found: Error: Can't resolve 'model/Error' in '/Users/sebastien/Documents/Javascript/Stackoverflow/superagenttest/src'
 @ ./src/index.js 17:4-84
 @ ./src/main.js

ERROR in ./src/index.js
Module not found: Error: Can't resolve 'model/MyField' in '/Users/sebastien/Documents/Javascript/Stackoverflow/superagenttest/src'
 @ ./src/index.js 17:4-84
 @ ./src/main.js

ERROR in ./src/index.js
Module not found: Error: Can't resolve 'api/DefaultApi' in '/Users/sebastien/Documents/Javascript/Stackoverflow/superagenttest/src'
 @ ./src/index.js 17:4-84
 @ ./src/main.js

##### Steps to reproduce

Just generate the Javascript code and try to use it in a React App or even a simple Javascript App

##### Related issues

I don't know

##### Suggest a Fix

Would be nice to have a full example with code generation and how to integrate it in a client Javascript webApp.

**Comment by wing328** [comment]
@sebastienFrance thanks for reporting the issue. It may be related to https://github.com/swagger-api/swagger-codegen/pull/5768

**Comment by sebastienFrance** [comment]
I found a solution thanks to [#3336](https://github.com/swagger-api/swagger-codegen/issues/3336)
I have updated my webpack.config.js as indicated and it works.
