### ISSUE TITLE
[JAVA] java/jersey2 ApiClient.invokeAPI doesn´t close the Response object

### ISSUE THREAD

**Issue by Moscagus** [swagger-api/swagger-codegen#5777]
##### Description

The code does not guarantee the correct closing of the Response object, since it does not always reach a response.readEntity or call a response.readEntity(InputStream.class) that does not close the connection either.
See:
https://jersey.github.io/documentation/latest/client.html#d0e5222

##### Swagger-codegen version

swagger-codegen-cli-2.2.2.jar

##### Command line used for generation

-l java --library jersey2
##### Suggest a Fix

  ...    
  Response response **= null**;
    
  **try {**
      if ("GET".equals(method)) {
        response = invocationBuilder.get();
  ... 
  **} finally {
      try {
        response.close();      
      } catch (Exception e) {}
  }**
}

**Comment by wing328** [comment]
@Moscagus thanks for reporting the issue. Please file a PR so that we can more easily review the fix.
