### ISSUE TITLE
CSharp Newtonsoft.json.dll not copied as binary file

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#578]
The original size of Newtonsoft.Json.dll is 417k. After csharp codegen, its size changes to 513k
```
ls -alh /var/apps/wing328/swagger-codegen/samples/client/petstore/csharp/bin/Newtonsoft.Json.dll
-rw-rw-r-- 1 dev01 dev01 513K Apr  1 01:32 /var/apps/wing328/swagger-codegen/samples/client/petstore/csharp/bin/Newtonsoft.Json.dll
```
I think it's due to the file not copied as a binary file when generating the CSharp code.

I tried to look for a solution (e.g. copying png file in threepane) but couldn't find the solution to copy the file as binary.

**Comment by fehguy** [comment]
fixed by copying as binary
