### ISSUE TITLE
[HTML2]Html2 api documentation generated by codegen does not render correctly in IE

### ISSUE THREAD

**Issue by leonluocheng** [swagger-api/swagger-codegen#5780]
##### Description

Html2 client generated by codegen does not render correctly in IE 11. as shows in screenshot, exactly same html2 client but when opened by IE 11, part of the parameter schema are missing. This issue does not happen in chrome, edge and Firefox.   Also this issue does not happen when I using swagger online editor to generate the html2 documentation. 

![image](https://cloud.githubusercontent.com/assets/8879694/26797718/749fd7a2-49f3-11e7-853a-a9c07a1c7a3c.png)

##### Swagger-codegen version

master branch 2.3

##### Swagger declaration file content or url
Example perstore.json 

I am looking for a possible solution here. and also this issue does not occur when using swagger online editor tool.

**Comment by wing328** [comment]
@leonluocheng thanks for reporting the issue. Swagger Editor is using the latest stable version (v2.2.2).

Seems like the issue was introduced to master after the stable release.

I wonder if you can help perform a "git bisect" with the latest master and [2.2.2](https://github.com/swagger-api/swagger-codegen/commit/ff209ada223dcc7f6c6afc59bb02ec96b85c7e39) commit to identy which changes broke it.

**Comment by leonluocheng** [comment]
@wing328 hmm, interesting. sure, I can help on this.

**Comment by leonluocheng** [comment]
@wing328 After "git bisect". found out this commitment cause this issue. 

![image](https://user-images.githubusercontent.com/8879694/27295107-66588466-54e1-11e7-845f-4f5a09f01f7b.png)

**Comment by leonluocheng** [comment]
@wing328 I am a js newbie. but thought my debug on [5313 ](https://github.com/swagger-api/swagger-codegen/commit/abffdca441c3a524ac336d66c24e4fa474cd2493). found out that "object.assign" is not support at IE11. looks like we need to find a way to polyfill this issue.

**Comment by wing328** [comment]
@leonluocheng thanks for identifying the issue.

@wy-z would you please take a look when you've time and see if the suggested fix by @leonluocheng works for you?

**Comment by wing328** [comment]
> A quick fix is to change "schemaWrapper.definitions = Object.assign({}, defs);" to "schemaWrapper.definitions = defs;"

@leonluocheng Please file a PR with the fix when you've time

**Comment by leonluocheng** [comment]
@wing328 sure np.
