### ISSUE TITLE
CPPRest generated models are not using inheritance

### ISSUE THREAD

**Issue by harishchoragudi** [swagger-api/swagger-codegen#5788]
##### Description

CPPRest's generated models are extending from ModelBase instead of the actual Class specified in REST contract provided as input to swagger-codegen-cli. This classs ModelBase is directly hardcoded in model-header.mustache template. This needs to be fixed. Also there is a method call to ModelBase::fromJson() which takes a map's value but instead a map's entry is being passed. This needs to be corrected in api-source.mustache template.

##### Steps to reproduce
1. Create a contract where the models using inheritance. 
   For example if Class A inherits from class B - but the generated models both class A and B extend from ModelBase.
2. Also in api-source.mustache, this line of code (itemObj->fromJson(item)) does not work if a map is being processed as there is no fromJson() method in ModelBase class that takes a map entry. This is causing a compilation error. So it needs to be fixed to itemObj->fromJson(item.second);

**Comment by wing328** [comment]
Closed via #5791
