### ISSUE TITLE
CodeGen not generating correct field names

### ISSUE THREAD

**Issue by egodolja** [swagger-api/swagger-codegen#5790]
Using the swagger codegen for a C# project. 

The issue is that in the swagger specifications I have a few fields in my models that have an underscore in the name. For example, I have fields names "**_links**" or "**_embedded**". When the code is generated these fields appear without the underscore, so I just see "**links**" or "**embedded**" when I receive responses. Is this a known issue,; is there a fix to it? I need the field name to appear with the underscore.

**Comment by wing328** [comment]
@egodolja there's a mapping between the property name and the actual name in JSON. Here is an example

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Model/Pet.cs#L127

"category" vs "Category"

The mapping is done as part of the serialization and deserialization so developers using the SDK do not need to worry about the mapping at all.

**Comment by wing328** [comment]
@egodolja are you still encountering issues with the variable naming or mapping with JSON payload in the C# API client?

**Comment by wing328** [comment]
@egodolja Btw, you may want to try generating the C# API client from 2.3.0 branch, which has the C# API client refactored based on various feedback we got from our users.

Closing this for the time being.

**Comment by egodolja** [comment]
I have tried adding the attribute 
[DataMember(Name="*myFieldName*", EmitDefaultValue=false)]
as shown in the example, using the latest jar file for generating the code, and am seeing the same result. Any other suggestions?

Thank you for your help!

**Comment by wing328** [comment]
Can you share the spec? You should not need to add the DataMember manually.
