### ISSUE TITLE
[Python] Tags behaves incorrectly when using template.

### ISSUE THREAD

**Issue by baibinghere** [swagger-api/swagger-codegen#5798]
I'm generating controller code from the template I defined myself.

The issue I met is that even though I defined lower case tag names like
- tags
  - test

The file generated is test_controller.py --> that is correct.
But when I define the controller.mustache to apply variables like {{tags}} or {{baseName}}, it shows like Test.
I feel this is an inconsistency issue.
At least for python, I don't think we have to capitalize the first character.

**Comment by wing328** [comment]
@baibinghere which version are you using? If I remember correctly, we might have fixed it in the latest master.

**Comment by baibinghere** [comment]
Hi Wing328,

I'm using the latest stable version.
$ java -jar swagger-codegen-cli-2.2.2.jar version
2.2.2

**Comment by wing328** [comment]
Can you try the latest master instead?

**Comment by baibinghere** [comment]
I've tried the latest master branch:

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        npm-debug.log

nothing added to commit but untracked files present (use "git add" to track)

$ git remote -v
origin  https://github.com/swagger-api/swagger-codegen.git (fetch)
origin  https://github.com/swagger-api/swagger-codegen.git (push)


I used mvn command to build the package and the version is below:
$ java -jar swagger-codegen-cli.jar version
2.2.3-SNAPSHOT

I don't think this issue has been resolved.

**Comment by wing328** [comment]
@baibinghere thanks for testing the latest master to confirm the issue. Please share a spec to reproduce the issue more easily so that the community can help on this.

**Comment by baibinghere** [comment]
Below is the YAML file definition

```yaml
---
swagger: "2.0"
info:
  description: "Issue 5798 API"
  version: "1.0.0"
  title: "Issue"
  contact:
    name: "test"
    url: "http://test.com"
    email: "test@test.com"
  license:
    name: "Proprietary"
basePath: "/v1"
schemes:
- "http"
- "https"
produces:
- "application/json"
paths:
  /test/:
    get:
      tags:
      - "user"
      operationId: "test"
      responses:
        200:
          description: "success"
```

Below is how I rewrite the controller.mustache:
```
{{#imports}}{{import}}
{{/imports}}

{{#operations}}
{{#operation}}


def {{operationId}}({{#allParams}}{{paramName}}{{^required}}=None{{/required}}{{#hasMore}}, {{/hasMore}}{{/allParams}}):
    # The baseName tag: {{baseName}}
	# The tags tag: {{tags}}
{{/operation}}
{{/operations}}
```
Below are my files:

``` bash
baib2@CNENBAIB2L3C MINGW64 ~/Desktop/test
$ find .
.
./flaskConnexion
./flaskConnexion/controller.mustache
./swagger-codegen-cli-2.2.2.jar
./test.yaml
```

Below is how I executed the command:
```bash
$ java -jar swagger-codegen-cli-2.2.2.jar generate -t flaskConnexion/ -i ./test.yaml -l python-flask -o ./server/ -D supportPython2=true
```

**Comment by baibinghere** [comment]
This is what have been generated as controller file:

```python
def test():
    # The baseName tag: User
    # The tags tag: [User]
```

**Comment by wing328** [comment]
OK. For the issue with baseName, please open a new issue for tracking instead.
