### ISSUE TITLE
[Java] Parcelable dependency is missing

### ISSUE THREAD

**Issue by BjoernPetersen** [swagger-api/swagger-codegen#5801]
##### Description

If the `parcelableModel` option is used, the required dependency for the `Parcelable` interface is not added to the generated pom.xml.

##### Swagger-codegen version

`2.2.2`, `2.2.3-SNAPSHOT` (built from master 73f52665963c291796b4ab9c344dbea5de5b4ec4)

##### Swagger declaration file content or url

Any declaration with a model (petstore can be used as an example).

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i swagger.yaml -o output -l java --library=okhttp-gson -DparcelableModel=true`

##### Suggest a Fix

This issue can be easily fixed by adding the following dependency to the pom.xml if the `parcelableModel` option has been set:

```xml
<dependency>
    <groupId>com.google.android</groupId>
    <artifactId>android</artifactId>
    <version>4.1.1.4</version>
    <scope>provided</scope>
</dependency>
```

I plan on fixing the issue myself, I'll open a PR soon.

**Comment by wing328** [comment]
Closed via #5802
