### ISSUE TITLE
C# code generation not using fully qualified type names

### ISSUE THREAD

**Issue by stevevanderhoeven-optimizely** [swagger-api/swagger-codegen#5803]
##### Description

The code generator for C# generate classes that do not use the fully qualified name. So a swagger field att of type "Attribute" would be generated as 

....
 Attribute att;
....

This would conflict with the name spaces include by default like in this case System.Attribute. The client generator only checks for conflicts with keywords so it does not detect that it generates uncompilable code.

If the type labeling instead of the bare class name would be replaced by packageName.apiPackage.swaggerType There would be no conflict. And it also removes a lot of conflicts between keywords and swagger type names.

##### Swagger-codegen version

v2.2.2-532-g5ebae2911

##### Swagger declaration file content or url

n/a

##### Command line used for generation

n/a

##### Steps to reproduce

n/a

##### Related issues

n/a

##### Suggest a Fix

I have an implementation for the fix I would like to submit.

**Comment by wing328** [comment]
@stevevanderhoeven-optimizely thanks for the PR. We'll review and let you know if we've any question.

A workaround is to add "Attribute" to the list of reserved words: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java#L65
