### ISSUE TITLE
[Java] Bug: generating incorrect queries to the server

### ISSUE THREAD

**Issue by Tmin10** [swagger-api/swagger-codegen#5816]
##### Description

Generated java client make incorrect queries to the server. API method (/alliances/names/) has parameter:
```json
{
  "description": "A comma separated list of alliance IDs",
  "in": "query",
  "items": {
    "format": "int64",
    "type": "integer"
  },
  "maxItems": 100,
  "minItems": 1,
  "name": "alliance_ids",
  "required": true,
  "type": "array"
}
```
Client made url for this method like https://esi.tech.ccp.is/latest/alliances/names/?alliance_ids=1354830081&alliance_ids=99005338&alliance_ids=498125261&alliance_ids=99003500&alliance_ids=1695357456&alliance_ids=99003006&alliance_ids=99003214&alliance_ids=99004126&alliance_ids=1900696668&alliance_ids=99002938&datasource=tranquility&user_agent=userAgent_example 
but alliance_ids override each other and server return answer for only one alliance_id. 

I think that correct url is https://esi.tech.ccp.is/latest/alliances/names/?alliance_ids=1354830081%2C99005338%2C498125261%2C99003500%2C1695357456&datasource=tranquility (comma separated ids).

##### Swagger-codegen version

v. 2.2.3-SNAPSHOT

##### Swagger declaration file content or url

I generate client from https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility

##### Command line used for generation

```java -jar .\swagger-codegen-cli.jar generate -i https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility -l java -o \out```

##### Steps to reproduce

* Generate client with CLI.
* Make request with method /alliances/names/ and ids 1354830081, 99005338, 498125261, 99003500, 1695357456.

**ER**: server return 5 names
**AR**: server return only one name

##### Suggest a Fix
Replace 
```java
if (collectionFormat.equals("multi")) {
    for (Object item : valueCollection) {
        params.add(new Pair(name, parameterToString(item)));
    }

    return params;
}
```
to
```java
if (collectionFormat.equals("multi")) {
    StringJoiner sj = new StringJoiner(",");
    for (Object item : valueCollection) {
        sj.add(parameterToString(item));
    }
    params.add(new Pair(name, sj.toString()));
    return params;
}
```
in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/ApiClient.mustache file. 

If this fix is correct I can make a pull request.

**Comment by ePaul** [comment]
The default for `collectionFormat` should be `csv` (which is what you want), the behavior you observe is the specified one for `multi`. Changing the behavior for `multi` is certainly not the right thing to do.

From afar (I didn't try it yet) it looks like the default is chosen wrong in your case.

**Comment by Tmin10** [comment]
Ok. But why swagger online editor generate correct comma-separated string to alliance_ids?





![screenshot at 21-08-33](https://user-images.githubusercontent.com/1534088/27005152-2d4f452c-4e21-11e7-97a7-328791d09901.png)

**Comment by ePaul** [comment]
I agree that the behavior is wrong (it should be comma-separated), just the bug is not at the place where you want to fix it. Sorry if I didn't say that clearly enough.

I didn't find a release 2.2.3 (last one was 2.2.2) – do you mean you tried it with current master?

**Comment by Tmin10** [comment]
Yes, it's 2.2.3-SNAPSHOT version.

**Comment by ePaul** [comment]
I just tried it with current master (21bf3a5a5e1218bd15a44df898427ff559ff8f0c), modified the generated test (AlliancesApiTest) to this:

```
    @Test
    public void getAlliancesNamesTest() throws ApiException {
        List<Long> allianceIds = Arrays.asList(1354830081L,99005338L,498125261L,99003500L,1695357456L);
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetAlliancesNames200Ok> response = api.getAlliancesNames(allianceIds, datasource, userAgent, xUserAgent);
        System.out.println(response);
    }
```
That was printed:
```java
[class GetAlliancesNames200Ok {
    allianceId: 1354830081
    allianceName: Goonswarm Federation
}, class GetAlliancesNames200Ok {
    allianceId: 99005338
    allianceName: Pandemic Horde
}, class GetAlliancesNames200Ok {
    allianceId: 498125261
    allianceName: Test Alliance Please Ignore
}, class GetAlliancesNames200Ok {
    allianceId: 99003500
    allianceName: Shadow of xXDEATHXx
}, class GetAlliancesNames200Ok {
    allianceId: 1695357456
    allianceName: Circle-Of-Two
}]
```
So it seems to work correctly?
Could you try building the current master – the -SNAPSHOT version number unfortunately doesn't really identify the build, as we don't have releases that often.

**Comment by Tmin10** [comment]
Yes, it's correct.
It's strange: I get latest version, regenerate client and all working right too...

Thank you for you help.
