### ISSUE TITLE
swagger-codegen confuses git on case-insensitive filesystems

### ISSUE THREAD

**Issue by bedag-moo** [swagger-api/swagger-codegen#5830]
#### Reproduction

Under windows (or any other OS with a case-insensitive file system):

$ git clone https://github.com/swagger-api/swagger-codegen.git
$ git checkout 2.3.0
$ git status

Expected: no changed files
Actual:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        samples/client/petstore-security-test/typescript-angular/API/FakeApi.ts
        samples/client/petstore-security-test/typescript-angular/API/api.ts
```

#### Cause

swagger-codegen has two different directories that only differ in the case of their filename:

/samples/client/petstore-security-test/typescript-angular/API/
/samples/client/petstore-security-test/typescript-angular/api/

In a case insensitive file system, these paths refer to the same directory, which places the checkout of api into the API directory, which in turn confuses git because the files are under a new path.

#### Remedy

Please rename one of the directories so they differ in more than case, or consolidate their files in a single directory.

**Comment by wing328** [comment]
@bedag-moo thanks for reporting the issue. I've re-added the folder. Can you pull the latest master/2.3.0 to give it a try?

**Comment by bedag-moo** [comment]
Thanks, that fixed it :-)

PS: windows users can fix their working copy with

$ rm -r samples/client/petstore-security-test/typescript-angular
$ git reset --hard

Obviously, you should commit / stash your changes before you reset.

**Comment by wing328** [comment]
@bedag-moo thanks for sharing the fix for windows users
