### ISSUE TITLE
is there a way to get elapsed time for rest operation.

### ISSUE THREAD

**Issue by dnome2** [swagger-api/swagger-codegen#5833]
##### Description
Wanted a way to find the elapsed time for every restapi operation. Request module supports elapsed.total_seconds() method, is there a way to execute this or add this as future enhancement?

##### Swagger-codegen version

2.2.2

**Comment by cbornet** [comment]
Which language/framework ?

**Comment by dnome2** [comment]
python

**Comment by wing328** [comment]
@dnome2 I think a good starting point is to use the `-t` option with the customized templates. You may want to start with [api_client.mustache:L139](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_client.mustache#L139)
