### ISSUE TITLE
[Spring] @JsonProperty annotations missing when using CLI jar

### ISSUE THREAD

**Issue by TekiYoung** [swagger-api/swagger-codegen#5842]
##### Description
If I use the online editor on swagger.io, and generate server codes for Spring, I get all fields correctly annotated with @JsonProperty and @JsonCreator.
But for the same Swagger specification file, if I use the command line tool as following:

java -jar swagger-codegen-cli-2.2.1.jar generate -i my-model.json -l spring --model-package my.package

Then all @JsonProperty annotations are missing, while the two imports are kept but never used.
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;

Can anyone please verify is this an issue or am I not using the CLI jar correctly?
Thanks.
##### Swagger-codegen version

2.2.1

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.1.jar generate -i my-model.json -l spring --model-package my.package

**Comment by wing328** [comment]
@TekiYoung please try the latest master by building the JAR locally instead as the issue may have been already addressed.

**Comment by wing328** [comment]
v2.2.3 stable version has been released. Please give it a try and let us know if you still face the same issue.
