### ISSUE TITLE
Javascript client codegen useES6 and templates

### ISSUE THREAD

**Issue by kevin-lot** [swagger-api/swagger-codegen#5845]
##### Description
Javascript client codegen doesn't use my own templates when useES6 additionnal properties is setted.

##### Swagger-codegen version
2.3.0
pull at june 14, 2017

##### Command line used for generation
java \\
-DdebugModels \\
-DdebugOperations \\
-jar ./generator/swagger-codegen-cli.jar \\
generate \\
-i ../swagger.json \\
-l javascript \\
-o ./ \\
--additional-properties useInheritance=true,useES6=true \\
-t ./generator/templates/javascript-es6 \\
\> ./.mustache.log

##### Steps to reproduce
Use templates with useES6 additional properties.

**Comment by wing328** [comment]
Your usage of `-t` with customized templates should work. Not sure why it's not working for you.

Can you share a bit more on what you want to customize?

You may want to also try without the `useES6` option.

**Comment by kevin-lot** [comment]
-t ./generator/templates/javascript-es6 is the path of my own template.

When I **put** "us6=true" in command, generics template from codegen are used.
When I **don't put** "us6=true" in command , my own templates are used.

My templates work with isomorphicFetch and are completely rewrote.

**Comment by wing328** [comment]
@kevin-lot I did fix some minor issues with the Javascript generator and would suggest you to pull the latest master to see if you're still experiencing the same issue.

**Comment by kevin-lot** [comment]
@wing328 
OK, you did something.

With the latest branch 2.30, pulled at june 28, 2017

Now, with or without the additionnal parameter "useES6", generic template from codegen are used. The "-t" parameter are completely ignored.

**Comment by wing328** [comment]
I'll look into the issue with the `-t` parameter support for JS generator tomorrow.

If you run `bin\windows\javascript-petstore.bat` on Windows or `./bin/javascript-petstore.sh` (Mac/Linux), do you see any code changes in the JS ES5 Petstore samples?

**Comment by lkettenb** [comment]
Any news here? 

We had to update from v2.2.2 to v2.2.3 because of #4932. But now or CI is broken because the code generator for JavaScript seems to ignore all templates. Thus, the default package.json is used and new packages cannot be published anymore.

**Comment by wing328** [comment]
@kevin-lot @lkettenb I've filed #6253 to fix it. Will merge it into master after the CI tests pass.

**Comment by wing328** [comment]
The fix has been merged into master. Please pull the latest master to give it a try.

**Comment by lkettenb** [comment]
@wing328 Thank you very much! It seems to work again!

**Comment by wing328** [comment]
@lkettenb np. Sorry for taking this long as I lost track of this issue.

If you've further feedback on the JS API client, please let us know.
