### ISSUE TITLE
[CSharp .NETStandard] How to intercept/change response content?

### ISSUE THREAD

**Issue by ModernRonin** [swagger-api/swagger-codegen#5857]
##### Description
ApiClient is generated as a partial class providing the extension point
``
partial void InterceptResponse(IRestRequest request, IRestResponse response) {}
``
However, it turns out response.Content is readonly. 
In my particular instance, I would need to remove some wrapping in the content which has been added by a server-side filter (and thus the swagger spec doesn't know anything about it). I don't see how I can do that. 
More generally, I don't see what's the point of this partial method if you can't change the response's content.

Any suggestions?

Thanks,
Max

##### Swagger-codegen version
Current master (HEAD: f27143fc081bc37c0a4bf5d65c84e4ec5c09c398)

##### Command line used for generation
swagger-codegen-cli

**Comment by wing328** [comment]
@ModernRonin I would suggest you to try generating the C# API client from 2.3.0 branch, which has the C# client generator refactored.

**Comment by ModernRonin** [comment]
@wing328 thanks, will check that out!

**Comment by wing328** [comment]
@ModernRonin closing this as there's no further update. Let us know if you still need help from us.

**Comment by protegesolutions** [comment]
I agree that `ByVal` parameter passing makes complete sense. Otherwise there's no way to, say, manage a **429 Too Many Requests** situation where what you would do is retry the call after a delay (and possibly loop a couple of retries):

        partial void InterceptResponse(**ref** IRestRequest request, **ref** IRestResponse response)
        {
            if (response != null && (int)response.StatusCode == 429)
            {
                System.Threading.Thread.Sleep(1000);
                response = RestClient.Execute(request);
            }
        }

`Ref` parameters here make sense, especially for the response.

Does anyone have a solution to this conundrum? (The code above is in a custom Helper Class.)
