### ISSUE TITLE
[JavaScript] master branch now generates ES6 JS code instead of ES5

### ISSUE THREAD

**Issue by frol** [swagger-api/swagger-codegen#5888]
##### Description

@dinukadesilva Adding `useES6` configuration option with a default value `true` in #5593 introduced a *breaking change* because the behavior for `generate -l javascript` with no options now generates ES6 JavaScript code instead of ES5.

By the way, the `./bin/javascript-es6*` generators set `useEs6=true` while the option name is `useES6` (`S` is capital).

##### Swagger-codegen version

Master branch

##### Related issues

#5593 

##### Suggest a Fix

Change the default value to `false`.

**Comment by dinukadesilva** [comment]
Thanks for this @frol 
I'll look into this

**Comment by wing328** [comment]
I'll work on this tomorrow if no one has time to pick this up.

**Comment by wing328** [comment]
Filed #5907 to fix it.
