### ISSUE TITLE
The deployed version of swagger-codegen-project still uses swagger-parser-version 1.0.27-SNAPSHOT

### ISSUE THREAD

**Issue by TehBakker** [swagger-api/swagger-codegen#5892]
Greetings,

Trying to retrieve and use Maven Plugin io.swagger:swagger-codegen-maven-plugin:2.2.3-SNAPSHOT, I get the following error

> The following artifacts could not be resolved: io.swagger:swagger-parser:jar:1.0.27-SNAPSHOT, io.swagger:swagger-compat-spec-parser:jar:1.0.27-SNAPSHOT

I see the source code has been updated to uses 1.0.29 : https://github.com/swagger-api/swagger-codegen/blob/master/pom.xml
However it has not been deployed and the actual available jar on https://oss.sonatype.org/content/repositories/snapshot still uses 1.0.27-SNAPSHOT
[Link to the pom from the repo](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-project/2.2.3-SNAPSHOT/swagger-codegen-project-2.2.3-20170310.174636-1.pom)

Could you deploy it please :)

There has been issues opened but they have been closed without fixing the issue.
#5134 
#5316

**Comment by wing328** [comment]
@TehBakker thanks for reporting the issue. What about building the JAR from the latest master instead? (we do not regularly publish a SNAPSHOT version of current master to maven repo)

**Comment by TehBakker** [comment]
Oh I could check out the project and install the jar on my local repo sure, but since there has been a few ticket and the currently deployed Snapshot doesn't work (since 1.0.27-SNAPSHOT of swagger-parser:jar is not available) I thought this warranted a new deploy. (And others have also reported the issue)

I'm probably not alone awaiting the next release (especially the new validation for java) ;)

**Comment by wing328** [comment]
> I thought this might warrant a new deploy

Sounds reasonable to me but I don't have right to publish the package to Maven repo. I'll ask Tony Tam to do so.

> While I've you here, any indication on the next release? Really eager to have the validation fully working with the java code.

We planned to release 2.3.0 (a branch with breaking changes and bug fixes) by the end of May but we'd to postpone as the team is busy. We hope to release 2.3.0 by the end of July.

**Comment by TehBakker** [comment]
Alright thanks, care to warn me here when it's done? 
Cheers

**Comment by TehBakker** [comment]
Hey there,

No luck on getting the repo updated ?

**Comment by fehguy** [comment]
I'll deploy the latest snapshot which is using release versions where possible.  You should try to do the same...

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/5934 has been merged into master.

@TehBakker can you give it another try?

**Comment by TehBakker** [comment]
Thank you, the repository has been updated and the build now works fine.
