### ISSUE TITLE
[Java][Spring][Server] When java8 and interfaceOnly are true, generated interface default methods should return HTTP 501 Not Implemented

### ISSUE THREAD

**Issue by gabrielbauman** [swagger-api/swagger-codegen#5895]
##### Description

Currently when java8 and interfaceOnly are true and we're generating a java/spring server, swagger-codegen produces java8 default implementations for each API method. These implementations return 200 OK.

    default ResponseEntity<Void> doSomething() {
        // do some magic!
        return new ResponseEntity<Void>(HttpStatus.OK);
    }

It would be useful if the default implementation returned 501 Not Implemented instead. 

    default ResponseEntity<Void> doSomething() {
        // do some magic!
        return new ResponseEntity<Void>(HttpStatus.NOT_IMPLEMENTED);
    }

This would be a nice default behaviour that would make sense to clients. If I forget to implement an interface method on a concrete controller class and it returns OK, it can cause some head scratching.

##### Swagger-codegen version

2.2.2 (maven plugin)

**Comment by wing328** [comment]
Closed via #5897 (merged into master)
