### ISSUE TITLE
[C++] Generating Restbed server stubs

### ISSUE THREAD

**Issue by jason-watkins** [swagger-api/swagger-codegen#5896]
##### Description

The Overview section of the repo's readme states that the project supports generating server stubs for C++ using Restbed, but the [Server stub generator HOW-TO](https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO) page, as well as the list printed by the application when an unknown language is specified, make no mention at all of Restbed.

Where can I find documentation about how to generate a Restbed server stub?

##### Swagger-codegen version

I am using version 2.2.2, retrieved using the wget command given under the Prerequisites section of the Readme.

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

1. Read documentation
2. Be confused by lack of information

##### Related issues

None found

##### Suggest a Fix

Document the specific `-l` arguments for each supported language/framework.

**Comment by wing328** [comment]
> I am using version 2.2.2, retrieved using the wget command given under the Prerequisites section of the Readme.

The C++ RestBed server stub generator was only added recently but it's not included in the previous stable release.

Please build the project locally (mvn clean install) or use the docker image to generate the C++ RestBed server stub.

**Comment by wing328** [comment]
You can also download the SNAPSHOT version from https://oss.sonatype.org/content/repositories/snapshots/io/swagger/

Let us know if you still need help on this.
