### ISSUE TITLE
Java generator - Date attribute without import java.util.Date

### ISSUE THREAD

**Issue by frodrigo** [swagger-api/swagger-codegen#590]
The java generator produce Date attributes but forget import java.util.Date

**Comment by fehguy** [comment]
Are you talking about a model or operation?

**Comment by frodrigo** [comment]
Yes in model

**Comment by fehguy** [comment]
Hmm it looks to be working in the petstore samples so something must be off.  Can you please share the model that's giving you trouble?

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/DefaultCodegen.java#L228

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/java/src/main/java/io/swagger/client/model/Order.java#L3

**Comment by frodrigo** [comment]
I check and it's not about Date but DateTime.
importMapping.put("DateTime", "org.joda.time.*"); 
is in place for DateTime but generator produce Date in code.

My simplificated swagger code:

```json
{
  "apiVersion": "0.1",
  "swaggerVersion": "1.2",
  "resourcePath": "/stores",
  "produces": [
    "application/json"
  ],
  "apis": [
    {
      "path": "/0.1/stores.{format}",
      "operations": [
        {
          "notes": "",
          "summary": "Fetch customer's stores.",
          "nickname": "getStores",
          "method": "GET",
          "parameters": [],
          "type": "array",
          "items": {
            "$ref": "Store"
          }
        }
      ]
    }
  ],
  "basePath": "http://127.0.0.1:3000/api",
  "models": {
    "Store": {
      "id": "Store",
      "properties": {
        "open": {
          "type": "dateTime"
        }
      }
    }
  }
}
```

```java
import org.joda.time.*;

public class Store  {
  private Date open = null;
}
```

**Comment by fehguy** [comment]
Great. So you are expecting the joda date import, correct?

**Comment by frodrigo** [comment]
Yes org.joda.time.* but the attribute must be of class DateTime not Date.

**Comment by fehguy** [comment]
OK this is a 1.2 swagger specification.  I'll report back shortly.

**Comment by frodrigo** [comment]
Any news ?

**Comment by wing328** [comment]
@frodrigo the feature is added via https://github.com/swagger-api/swagger-codegen/pull/1784

Please pull the latest and let us know if you're still seeing the same issue.

Closing this issue for now.
