### ISSUE TITLE
[New Generator] Rust API client generator

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5905]
##### Description

We want to generate Rust API client so that Rust programmers can consume REST APIs more easily with Rust.

cc @frol 

##### Swagger-codegen version

Latest master

##### Suggest a Fix

If anyone wants to contribute the generator or help out, please reply to let us know. 

(You don't need to know Java in order to contribute the generator)

**Comment by farcaller** [comment]
> You don't need to know Java in order to contribute the generator

Why am I deep into java code now, then? 😄 

On a serious note: I'm working on rust client generator based on hyper.rs.

**Comment by wing328** [comment]
The PowerShell API client generator was created with the help of an experienced PowerShell developer who does not know Java.

We can start the same process if you're interested creating a Rust client generator in Swagger Codegen.

**Comment by farcaller** [comment]
I'd be up for any help in re. java code (I can reasonably read java). Can do the rust part.

**Comment by wing328** [comment]
@farcaller thanks for offering help on this.

We can reuse the same [methodology](https://github.com/swagger-api/swagger-codegen/issues/4320#issuecomment-296198548) we used for PowerShell API client by first creating a Rust wrapper/SDK for [PetStore](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml) by focusing on a few endpoints.
- [GET](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L156-L183)
- [POST (form)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L184-L218)
- [POST (JSON body)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L31-L56)

The Rust code can be put in the folder `samples/client/petstore/rust`.

Then we can reverse-engineer the Rust code to create the mustache templates and the generator in Java.

**Comment by farcaller** [comment]
SGTM. I'll work on the example and will submit a PR

**Comment by farcaller** [comment]
There you go: https://github.com/swagger-api/swagger-codegen/pull/6092

It almost works with the sample node server (it actually crashes the server, but I'm very sure it's the server's fault).

**Comment by BenjaminGill-Metaswitch** [comment]
As trailed in https://github.com/swagger-api/swagger-codegen/pull/6105#issuecomment-320300513, we've now released an alternative implementation of Rust codegen - https://github.com/Metaswitch/swagger-codegen (the `rust` branch).

It's sufficiently feature-complete that we will be immanently using it in production, though there are still some rough edges.

How should we proceed? In https://github.com/swagger-api/swagger-codegen/pull/6105#issuecomment-320300513, it was suggested that the two implementations could co-exist. Ours is currently named `rust2` to make that easier.

**Comment by wing328** [comment]
@BenjaminGill-Metaswitch thanks! Please file a PR against master.

About the naming, `rust2` is ok but I would prefer something like "rust-{http_lib_name}". For example, we've "typescript-jquery" for Typescript generators in which `jquery` is the "http_lib_name".

**Comment by wing328** [comment]
@BenjaminGill-Metaswitch do you need help filing the PR? Anything else the community can help out with?

**Comment by BenjaminGill-Metaswitch** [comment]
There are still some outstanding issues (not least a merge conflict), but I've just opened https://github.com/swagger-api/swagger-codegen/pull/6613 so we can start the conversation.
