### ISSUE TITLE
[Java] Empty Schema definition results in 'Cannot find Symbol' javac error

### ISSUE THREAD

**Issue by Rajmohan** [swagger-api/swagger-codegen#5916]
##### Description
An empty schema definition  is associated with a body parameter type for a PUT operation (which also has other query params).  The intent of this empty type is as a placeholder for future use.
This usage of  empty schema definition results in an javac 'Cannot find symbol ... ' error in the generated code.

Also please note that, this swagger is provided to us by an external user and we don't have any control over it's definition.  

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url

```json
{
"swagger": "2.0",
"paths": {
     "/myservice/api/v1/foo": {
	"put": {
	  "parameters": [
	    {
	      "name": "payload",
	      "in": "body",
	      "schema": {
		 "$ref": "#/definitions/precheck-request"
	      }
	   }
	 ]
	}}}
  "definitions":{
    "precheck-request":{
    	"description":"For future use, no parameters are supported in the payload at this time.</p>"
     },		
  }
}
```

##### Command line used for generation
java -jar swagger-codegen-cli.jar generate 
   -i test-swagger.json \
   -l java \
   --library retrofit2
   -o ....

##### Steps to reproduce

Able to consistently reproduce by having a empty schema definition referenced as a body parameter type (as given in the above swagger)
##### Related issues
AFAIK, searched and did not find a related issue.

##### Suggest a Fix

I am planning on submitting a fix, but need advise on the approach to take.

From the reading of the code (with my limited understanding), looks like the issue is caused by :

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java
line#834
            if("{ }".equals(Json.pretty(impl)))
                return null;
Swagger parser discards empty schema definitions.

However Swagger-Codegen generates import mappings and Body param type definition in the generated code. But since Swagger-parser has discarded the empty schema definition, there is no associated Model type and hence no Type are generated for this empty schema. Thus leading to 'cannot find symbol' error in the generated code.

So, some approaches I can think of to address the issue,

option 1)  Let swagger-parser not discard empty schema definitions. This will lead to generation of a bare-bone type in swagger-codegen and thus no 'cannot find symbol' error.  However, I am unsure of what other side-effects this would cause.

option 2) Modify swagger-codegen not to emit import statement and Typed bodyParameter (instead used some generic Object type) when there are no associated Model type associated with the parameter.

Please let me know if there are alternative ways/approaches to address this issue.  I am interested in submitting a fix , but want to validate the approach before submitting a PR.
Thanks!

**Comment by wing328** [comment]
@Rajmohan What does the empty object definition representation? Is that an arbitrary JSON?

**Comment by Rajmohan** [comment]
@wing328 yes, it's an empty object definition representation i.e.,

```json
"precheck-request":{
    	"description":"For future use, no parameters are supported in the payload at this time.</p>"
     },	
```
Some swaggers have these definition objects with empty schemas(with only description fields), used as place-holders for future use.

**Comment by wing328** [comment]
So the PUT operation does not have any parameter (query, body, header, form) at the moment and you just put a body parameter there (with empty definition) as a placeholder for future use, right?

I wouldn't suggest you to document your API this way as currently the PUT operation does not have any parameter. You can use vendor extensions (e.g. x-parameter-placeholder) to document it instead.
