### ISSUE TITLE
[Java][RESTEasy] Gradle build failed while maven build succeeded

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5925]
##### Description

Gradle build failed for Java RESTEasy Petstore sample while `mvn test` works fine. Here are the steps to repeat it:
```
swagger-codegen|master⚡ ⇒ cd samples/client/petstore/java/resteasy
resteasy|master⚡ ⇒ gradle test
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:36: error: package org.jboss.logging does not exist
import org.jboss.logging.Logger;
                        ^
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:37: error: package org.jboss.resteasy.client.jaxrs.internal does not exist
import org.jboss.resteasy.client.jaxrs.internal.ClientConfiguration;
                                               ^
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:38: error: package org.jboss.resteasy.plugins.providers.multipart does not exist
import org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataOutput;
                                                     ^
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:39: error: package org.jboss.resteasy.spi does not exist
import org.jboss.resteasy.spi.ResteasyProviderFactory;
                             ^
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:445: error: cannot find symbol
      MultipartFormDataOutput multipart = new MultipartFormDataOutput();  
      ^
  symbol:   class MultipartFormDataOutput
  location: class ApiClient
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:445: error: cannot find symbol
      MultipartFormDataOutput multipart = new MultipartFormDataOutput();  
                                              ^
  symbol:   class MultipartFormDataOutput
  location: class ApiClient
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:649: error: cannot find symbol
    final ClientConfiguration clientConfig = new ClientConfiguration(ResteasyProviderFactory.getInstance());
          ^
  symbol:   class ClientConfiguration
  location: class ApiClient
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:649: error: cannot find symbol
    final ClientConfiguration clientConfig = new ClientConfiguration(ResteasyProviderFactory.getInstance());
                                                 ^
  symbol:   class ClientConfiguration
  location: class ApiClient
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:649: error: cannot find symbol
    final ClientConfiguration clientConfig = new ClientConfiguration(ResteasyProviderFactory.getInstance());
                                                                     ^
  symbol:   variable ResteasyProviderFactory
  location: class ApiClient
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java:652: error: cannot find symbol
      clientConfig.register(Logger.class);
                            ^
  symbol:   class Logger
  location: class ApiClient
Note: /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/resteasy/src/main/java/io/swagger/client/ApiClient.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
10 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.804 secs
```

`sbt test` also failed.

##### Swagger-codegen version

Latest master.

##### Suggest a Fix

If anyone wants to work on this issue, please reply to let us know and I can show you some good starting points.

**Comment by dejan2609** [comment]
@wing328 I'll try to deal with this.

**Comment by dejan2609** [comment]
@wing328 it seems that now maven test are failing also; scenario:

* execute mvn test against current HEAD and receive error:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project swagger-petstore-resteasy: Compilation failure: Compilation failure:
> [ERROR] C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\api\FakeApi.java:[227,51] error: unmappable character for encoding Cp1252
> [ERROR] C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\api\FakeApi.java:[227,61] error: unmappable character for encoding Cp1252

* test are failing due to characters incompatibility with **_HEAD_** encoding (see *class io.swagger.client.api.FakeApi*):
```
  /**
   * Fake endpoint for testing various parameters 假端點 偽のエンドポイント 가짜 엔드 포인트 
   * Fake endpoint for testing various parameters 假端點 偽のエンドポイント 가짜 엔드 포인트 
   * @param number None (required)
   * @param _double None (required)
```
* _**(optional/suggested)**_: delete your **\<userHome>.m2/repository** folder content
*  checkout  my pull request branch (simple chage: maven compiler plugin encoding is configured to _UTF-8_ value)
*  execute mvn test and you will receive error:

> [INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ swagger-petstore-resteasy ---
> [INFO] Compiling 50 source files to C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\target\classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\model\FormatTest.java:[24,22] error: package org.threeten.bp does not exist
> [ERROR] C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\model\FormatTest.java:[25,22] error: package org.threeten.bp does not exist
> [ERROR] C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\model\FormatTest.java:[60,10] error: cannot find symbol
> [ERROR]   symbol:   class LocalDate
>   location: class FormatTest
> C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\model\FormatTest.java:[63,10] error: cannot find symbol
> [ERROR]   symbol:   class OffsetDateTime
>   location: class FormatTest
> C:\Work\IDEA-2017.2\projects\swagger-codegen\samples\client\petstore\java\resteasy\src\main\java\io\swagger\client\model\FormatTest.java:[243,25] error: cannot find symbol
> [ERROR]   symbol:   class LocalDate
>   location: class FormatTest
 
It seems that (at least) this dependency needs to be added: 
 * https://github.com/ThreeTen/threeten
 * http://www.threeten.org/

I'll try to revisit this soon.

**Comment by wing328** [comment]
I've filed #6555 to fix the maven build error. 

I wonder if you can file a PR to fix the same for build.gradle and build.sbt files for Java RESTEasy client.

**Comment by dejan2609** [comment]
@wing328 I'll try to change build.gradle and buil.sbt.

**Comment by developersteve** [comment]
Getting this error as well during Travis checks 

```
ApiClient.java:22: error: package org.threeten.bp does not exist
import org.threeten.bp.LocalDate;
```

**Comment by wing328** [comment]
@dejan2609 @developersteve the issue with build.gradle has been addressed with https://github.com/swagger-api/swagger-codegen/pull/7448

Please pull the latest 2.4.0 branch and give it a try.
