### ISSUE TITLE
 [JAVA] Bug generating enum values

### ISSUE THREAD

**Issue by acostros** [swagger-api/swagger-codegen#5932]
##### Description
Generating a java client that has enums where the values have a common prefix will lead to generated enums having the common prefix striped off.

We make extensive use of enums to show various configuration values. This bug removes he meaning from the enum names and makes the generated clients inconsistent with the API. 

i.e. 
ON_STARTUP gets replaced with STARTUP , 
ON_SHUTDOWN gets replaced with SHUTDOWN,

FIXED_INTEREST_RATE gets replaced with INTEREST_RATE
FIXED_INDEX_RATE gets replaced with INDEX_RATE

DELETE_USERS turns into USERS 
DELETE_PRODUCTS turns into PRODUCTS
DELETE_CLIENTS turns into CLIENTS

I think it's clear that the intended meaning of the enum is no longer the same and that this can have a significant impact on any api that makes extensive use of enums.

##### Swagger-codegen version
 group: 'io.swagger', name: 'swagger-codegen-cli', version:2.2.2

##### Command line used for generation

generate, -i, /Users/user/Desktop/json/swagger.json, -l, java, -o, /Users/user/Desktop/build/JavaSdk/, --library, okhttp-gson, --artifact-id, branches, --group-id, com.client, --artifact-version, 2, --api-package, com.client.api, --model-package, com.client.model, -DapiTests=false, -DmodelTests=false, -DdateLibrary=java8

##### Steps to reproduce

Any enum that has all values with a common prefix.

##### Related issues

This was introduced here:

https://github.com/swagger-api/swagger-codegen/pull/1264/commits/6dcaa890cff06badcff86596f0aac3efb0193c8f

##### Suggest a Fix

Expose this behaviour into a command line parameter to allow us to have the full enum names that we want. (enum-prefix-stripping, pick a better name if you please).

This will allow users that rely on this to continue using it and offer users that don't need this behaviour to skip it.

**Comment by wing328** [comment]
@acostros I'll try to look into it this week.

**Comment by asthomas** [comment]
This is show-stopping for us.  I have found no work-around, even by modifying the mustache files.  I'm creating an interface between a NancyFx server and a C# client and I cannot make the enum definitions match due to this bug.

**Comment by mast4461** [comment]
@asthomas, one work-around would be to add unique prefixes to each enum case. It's not pretty, but easy, simple and should work.

**Comment by asthomas** [comment]
@mast4461, Thanks, but I am creating an interface using an existing enum that cannot be altered.  I found a hack for the mustache code that gets the nancyfx generator and the csharp generator to match each other and the actual enum.

The combination of nancyfx and csharp is in fact broken.  The two generators create code that can serialize/deserialize from nancyfx to csharp, but cannot serialize/deserialize from csharp to nancyfx.

**Comment by elion** [comment]
I have the same issue with enum that has single element. The prefix is stripped.

**Comment by elion** [comment]
@wing328 Could the milestone be changed to v2.4.0?

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/7726

Please pull the latest master or use the SNAPSHOT version to give it a try.

**Comment by Dingesken** [comment]
Please reopen as #7726 only solves issues with a single enum value and not with mulitple enum values as mentioned in #5932.

**Comment by drsatan1** [comment]
Agree with @Dingesken. This functionality of stripping prefixes seems rather arbitrary. Does this follow some part of the specification? At my organisation it has lead to fragmentation between variable names and honestly it sucks a lot.

**Comment by Dingesken** [comment]
Looks like a partial solution was provided in #4331 , I can't test it though.

**Comment by vgadamsetty** [comment]
Do we have any solution for this?

**Comment by jkoorts** [comment]
Using, 

<groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.10</version>

Still shows this bug:
properties:
        bitrate:
          enum: ["BAUD_125KBPS", "BAUD_250KBPS", "BAUD_500KBPS", "BAUD_1000KBPS"]

public enum BitrateEnum {
    _125KBPS("BAUD_125KBPS"),
    
    _250KBPS("BAUD_250KBPS"),
    
    _500KBPS("BAUD_500KBPS"),
    
    _1000KBPS("BAUD_1000KBPS");

**Comment by Simoncdesmet** [comment]
The bug is still there, but I have found the easiest work around for me is to just add another element to the enum that doesn't have the common prefix
```
PUBLIC_CUSTOMER
PUBLIC_VENDOR
PUBLIC_VISITOR
DUMMY_TYPE
```

will generate the enum with the PUBLIC_ included, because the generator can not extract a common part to all the enum elements.
