### ISSUE TITLE
The return value is defined as "void" make Python client code to fail

### ISSUE THREAD

**Issue by madhuri-rai07** [swagger-api/swagger-codegen#594]
The return type of some the APIs are defined as "void" which make no sense in python. The python client code fail with error "not defined".

**Comment by madhuri-rai07** [comment]
I think this error is due to the swagger-spec used to generate code but not swagger-codegen issue.

**Comment by brendandburns** [comment]
I actually think this is an error in swagger-codegen.  The swagger spec:

https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#521-object-example

includes:

```"type": "void"``` in the example

So I think that swagger-codegen should do the right thing for python and not emit a return type here.

**Comment by wing328** [comment]
The issue, due to conversion from 1.2 to 2.0, should be fixed by https://github.com/swagger-api/swagger-parser/pull/34/files. please pull the latest develop_2.0 and give it another try.

**Comment by madhuri-rai07** [comment]
I have tested and it works fine now.
Thanks!
