### ISSUE TITLE
[JAVA] Maven plugin, is it possible to generate only certain path and the associated object ?

### ISSUE THREAD

**Issue by TehBakker** [swagger-api/swagger-codegen#5953]
##### Description

Hey, 

I was wondering if there is anyway in the pom.xml to configurate so that when generating the Client, it wil only generates some path and models and not the unused path ?

This is more a question as I failed to find info on the matter, I saw that you can choose to generate API or MODEL but not sure if possible to cherry pick in those.

##### Swagger-codegen version

2.2.3-SNAPSHOT

**Comment by wing328** [comment]
@TehBakker what about using .swagger-codegen-ignore to skip files that you don't need?

**Comment by wing328** [comment]
Closing this as there's no update. Please open a new ticket with an example if you still have question on this.

**Comment by TehBakker** [comment]
Yep sorry @wing328 I will try and create a more detailed example when I've time.
But the way I use codegen, wagger-codegen-ignore  can't help me.

**Comment by wing328** [comment]
@TehBakker np. Just share more with us when you've time and we'll see what we can do to meet your requirement.
