### ISSUE TITLE
[cpprestsdk]Missing example

### ISSUE THREAD

**Issue by ZdenoPavlik** [swagger-api/swagger-codegen#5976]
Missing example how to generate swagger file for c++ - cpprestsdk

**Comment by wing328** [comment]
I think your question is how to generate the C++ (cpprest) API client.

Here are the steps:

1. Download [Swagger Codegen CLI JAR (SNAPSHOT version)](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.2.3-SNAPSHOT/swagger-codegen-cli-2.2.3-20170704.034918-42.jar) to a local directory
2. Run the following command:

    java -jar swagger-codegen-cli-2.2.3-20170704.034918-42.jar generate -i swagger.json -l cpprest -o c:\temp\cpprest_client\
