### ISSUE TITLE
[objc] [Bug] Bool default values posted as integer

### ISSUE THREAD

**Issue by marcotta** [swagger-api/swagger-codegen#5982]
##### Description
Default values for Bool convert into numbers.
Bool are stored as NSNumber, setting a default value to 'false' or 'true' on specification file generates the following lines:

```
property = @0 //false
property = @1 //true
```

this converts into a __NSCFNumber instead of __NSCFBoolean

When posting to the backend this will post an integer instead of a boolean and the REST API will complain.

I guess if instead it generated the following code:
```
property = @(NO) //false
property = @(YES) //true
```

it would create an __NSCFBoolean and would not fail when posting the object to the server wrapped into a JSONDictionary

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url

```json
{
            "name": "isEnabled",
            "description": "Enables the flag",
            "in": "query",
            "type": "boolean",
            "default": false
}
```

##### Command line used for generation
```
swagger-codegen generate -i api-spec.json -l objc -c config.json -o APIClient
```

**Comment by wing328** [comment]
@marcotta I think the issue you reported is similar to https://github.com/swagger-api/swagger-codegen/issues/4491

I suggested a fix in https://github.com/swagger-api/swagger-codegen/issues/4491. Can it give it a try to see if it works for you?

**Comment by wing328** [comment]
@marcotta yes. Please create a pull request.

To skip that line when the property is a boolean, please try the following:
```
{{^isBoolean}}
...
{{/isBoolean}}
```

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5999
