### ISSUE TITLE
i want know that if support i18n?

### ISSUE THREAD

**Issue by lmx1989219** [swagger-api/swagger-codegen#5984]
this is a great project.
but i want the static file generated is chinese.

**Comment by wing328** [comment]
It should work with double byte characters. What issue did you get?

**Comment by lmx1989219** [comment]
@wing328 
the meaning of mine is that whether it can generate chinese words with api static file.
thanks.

**Comment by bidiu** [comment]
Maybe you want this:
https://angular.io/guide/i18n

**Comment by wing328** [comment]
@lmx1989219 just give it a try and let us know if you encounter issues.

**Comment by shijinkui** [comment]
In the swagger json support i18n, such as keys: `summary`, `description`. The generate doc and function comment can have different languages.

For example:

```
"200": {
            "description": {
               "cn":"Successful",
               "zh": "成功"
             },
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
 }
```

**Comment by wing328** [comment]
@shijinkui looks like it's still not yet support in the latest version (3.0) of OpenAPI:

https://github.com/OAI/OpenAPI-Specification/issues/274
https://github.com/OAI/OpenAPI-Specification/pull/639

**Comment by shijinkui** [comment]
@wing328 wing  OK. Thanks
