### ISSUE TITLE
Generated javascript README doesn't make much sense

### ISSUE THREAD

**Issue by boosh** [swagger-api/swagger-codegen#5986]
##### Description

I've generated a javascript library, but the [README](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/README.mustache) doesn't make much sense. It starts by talking about publishing a library to npm (which I'm not going to do because it's a private library), doesn't explain what `main.js` is meant to include, and doesn't explain how to use the generated client locally unless it's already been published to npm.

##### Swagger-codegen version
The one at editor.swagger.io/#/.

##### Swagger declaration file content or url
N/A

##### Command line used for generation
N/A - Used the online swagger editor.

##### Steps to reproduce
Generate a javascript client library using the online swagger editor. Give the zip file to someone who's never followed the README before and observe low productivity and confusion.

##### Suggest a Fix
Improve the README not to assume knowledge of publishing npm modules, etc. Target instructions at people who have to use javascript to because they make web sites, not because they enjoy it.

**Comment by boosh** [comment]
Apparently you need to use `npm link path/to/javascript-client`.

**Comment by wing328** [comment]
@boosh thanks for the feedback. I agree with you the auto-generated README has rooms for improvement. Would you have time to contribute a PR to make it better?

Here is a good starting point: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/README.mustache

**Comment by boosh** [comment]
Done, rather hamfistedly.
