### ISSUE TITLE
[TypeScript][Aurelia] To add TypeScript Aurelia client generator

### ISSUE THREAD

**Issue by ksm2** [swagger-api/swagger-codegen#5987]
##### Description

I would like to add an (Aurelia)[http://aurelia.io/] client using TypeScript to support the framework directly out of Swagger.
Right now, I use the implementation of a custom "api.mustache" template for the `typescript-fetch` generator, but I needed to fix HTTP methods to be "Camelcase" as Aurelia's HTTP client uses methods like `asGet`, `asPost`, etc. to change the method being used for the request.
Should I propose a PR?

**Comment by wing328** [comment]
@ksm2 thanks for the PR. I've provided some feedbacks. Please take a look when you've time.

**Comment by wing328** [comment]
Closed via #5991 

Future enhancements to TypeScript Aurelia tracked via https://github.com/swagger-api/swagger-codegen/issues/6149
