### ISSUE TITLE
Change generated html file name (from index)

### ISSUE THREAD

**Issue by sh123sh** [swagger-api/swagger-codegen#5989]
Hi,
I`m generating an Html file from Yaml and the defualt file name is index.html. How can i change that?

**Comment by wing328** [comment]
The only way is to customize the generator here: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtmlGenerator.java#L66

Or rename the file after the code generation.

**Comment by fehguy** [comment]
You can also create an option for the output filename and send a PR.  The default should be `index.html` though.

**Comment by sh123sh** [comment]
Thanks!!
