### ISSUE TITLE
Python 3 generator dropped?

### ISSUE THREAD

**Issue by dpeschman** [swagger-api/swagger-codegen#599]
Python3ClientCodegen was removed (c5ccc0a908a4f1217e36d5ca91b7264f6bb987d2), but the other python generator does not work for generating python 3 clients (long datatype removed in python 3, etc).  Will python 3 support be restored?

**Comment by wing328** [comment]
I'm no expert in Python but would it make sense to have the same Python client that works with both Python 2 and Python 3 ?

I look at Twilio Python SDK, which seems to work with both Python 2 and Python 3.

**Comment by dpeschman** [comment]
It's possible, yes.  But in the meantime, can we restore support for Python 3 users by bringing back Python3ClientCodegen?

**Comment by wing328** [comment]
I submitted a PR #618 to add back the python3 codegen but need your help to test since I'm no expert in python.

**Comment by wing328** [comment]
#618 merged into develop_2.0 and therefore this can be closed.

**Comment by dpeschman** [comment]
Thanks.  I'll let you know when I get a chance to try out the new old
generator :)

**Comment by wing328** [comment]
@dpeschman #768 (Upgrade python client with urllib3) has been merged into develop_2.0 so the python client (not python3) should support both python2 and python3. please give it a try.

**Comment by dpeschman** [comment]
Ok will do



On May 21, 2015, at 12:07 AM, wing328 <notifications@github.com> wrote:

@dpeschman #768 (Upgrade python client with urllib3) has been merged into develop_2.0 so the python client (not python3) should support both python2 and python3. please give it a try.
