### ISSUE TITLE
Generated code from swagger gives controller with default return type always as HttpStatus.OK

### ISSUE THREAD

**Issue by ayushoo7** [swagger-api/swagger-codegen#5990]
When we generate the controller using swagger-codegen-cli-2.2.1.jar  all the api class controller class have return type as HttpStatus.OK

jar used swagger-codegen-cli-2.2.1.jar

.yml file content

post:
      
      security:
        - basicAuth: []
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Language
          in: header
          description: 
          required: true
          type: string                       
      responses:
        201:
          description: Created
        400:
          description: Bad Request         
        401:
          description: Unauthorized
        403:
          description: Forbidden 
        405:
          description: Method Not Allowed 
        500:
          description: Internal Server Error 

java -jar swagger-codegen-cli-2.2.1.jar generate -i %apiyml% -c %conf% -l spring -o %tmp% 

Just generate the controller using above command putting .yml file as desired place.

need to update apiController.mustache as well as jar code to take the code as dynamic but not 
return new ResponseEntity<{{>returnTypes}}>(HttpStatus.OK);{{/async}}{{#async}}

**Comment by ayushoo7** [comment]
Please can some one help me with this.

**Comment by fehguy** [comment]
The client generator can't currently return different response codes and payloads as the spec describes.  Watch for this in the 3.0 spec support which is about to get underway.
