### ISSUE TITLE
[cpprestsdk]Generate swagger description from C++ solution/project

### ISSUE THREAD

**Issue by ZdenoPavlik** [swagger-api/swagger-codegen#5997]
Hi guys,

I would like to generate swagger json file from existing solution (using cpprestsdk - Casablanca).
But the command 

java -jar swagger-codegen-cln.jar generate -i D:\_temp\MySolution\mySolution.sln  -l cpprest -o swagger.json

seems not to be supported.

Is it even possible? 

Thanks.

**Comment by wing328** [comment]
I'm not aware of any solution to parse the source code (C++) and generate an OpenAPI/Swagger spec at the moment.

You can choose to manually write the spec using https://editor.swagger.io instead.

**Comment by RamakrishnaChilaka** [comment]
Is there any update on this ??

**Comment by RamakrishnaChilaka** [comment]
Is there any update on this ??
