### ISSUE TITLE
[TypeScript Fetch] Optional URL query parameters are sent empty if not present

### ISSUE THREAD

**Issue by roberterdin** [swagger-api/swagger-codegen#6003]
##### Description
When an URL parameter is optional and **not** specified it results in requests that can break back-end systems.

Generated stub, correctly specifying that `v` and `open` are optional
```
getRouteUsingGET(params: {  "src": string; "dst": string; "open"?: string; "v"?: string; }, options?: any): FetchArgs {
```

Hoewver, using it like this
```
SomeApi.RouteApiFactory().getRouteUsingGET({
            src: "foo",
            dst: "bar",
            open: "PAN"
            // no v
        })
```
results in a requested URL that looks like `http://localhost:8080/someapi/route/foo/bar?open=PAN?v=`.
While this might strictly be standard compliant it can break back-end frameworks. Spring for example will think the `open` parameter is `PAN?v=` instead of it being `PAN`.

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url

```
/distance/route/{srcPort}/{dstPort}: {
get: {
consumes: [
"application/json"
],
produces: [
"*/*"
],
parameters: [
{
name: "open",
in: "query",
required: false,
type: "string"
},
{
name: "v",
in: "query",
required: false,
type: "string"
}
],
responses: {...}
...
}
```
##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i http://localhost:8090/v2/api-docs -l typescript-fetch -o output/`

##### Suggest a Fix

Don't send empty query parameters.

**Comment by wing328** [comment]
@roberterdin thanks for reporting the issue. Have you tried other TS API clients to see if they've similar issue?

In 2.3.0 branch, `typescript-angualr2` supports both TS Angular 2.x and 4.x so worth giving it a try.

cc @Vrolijkx @taxpon @sebastianhaas @kenisteward @TiFu

**Comment by ElfenLiedGH** [comment]
@wing328 i've got it too, and i've tried other API clients, they havn't this error
they all have check like
` for (var key in params) {
      if (params.hasOwnProperty(key) && params[key] != undefined && params[key] != null) {`

or 

`        if (search !== undefined) {
            queryParameters['search'] = search;
        }`

**Comment by wing328** [comment]
@roberterdin thanks for doing a check. Would you have time to contribute a fix by reusing the code snippets in other TS client templates?

Here are the TS Fetch templates: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/TypeScript-Fetch

**Comment by ElfenLiedGH** [comment]
@wing328 

i don't know mustache, but it looks like 

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache#L93

`if(params["{{paramName}}"] !== undefined){

urlObj.query = {{#supportsES6}}Object.{{/supportsES6}}assign({}, urlObj.query, {

 {{#queryParams}}
   "{{baseName}}": params["{{paramName}}"],
   {{/queryParams}}
   });


}`

ts =>
`   if (params["search"] !== undefined) {

            urlObj.query = assign({}, urlObj.query, {

                "search": params["search"],

            });
        }`

**Comment by TiFu** [comment]
I think your fix is almost correct. `{{queryParams}} /* code */ {{/queryParams}}` is basically a loop over all query parameters (see [mustache demo](https://mustache.github.io/#demo) for more examples). So your solution would not work for more than one query parameter.

Could you test if this works?

```
{{#hasQueryParams}}
        urlObj.query =  {{#supportsES6}}Object.{{/supportsES6}}assign({}, urlObj.query)
{{#queryParams}}
        if (params["{{paramName}}"] !== undefined) {
            urlObj.query["{{baseName}}"] = params["{{paramName}}"];
        }
{{/queryParams}}
{{/hasQueryParams}}
```

**Comment by roberterdin** [comment]
@wing328 I'll try to submit a fix.
@TiFu that almost works... I'll have a look.
