### ISSUE TITLE
[JAVA] Generated models do not contain JAXB annotations

### ISSUE THREAD

**Issue by packleader** [swagger-api/swagger-codegen#6005]
##### Description

When generating a Java client, the resulting models do not contain JAXB annotations.  As a result, the client cannot be used with a service that produces or consumes XML.  (This applies to all libraries.)

##### Swagger-codegen version

master (a64c7d7986b5aa87e4b476267496722d10eb3095)

##### Swagger declaration file content or url

Here's an [excerpt of the swagger.json](https://gist.github.com/packleader/668d6115f795c2e1a64b03f3b3924ddc) that shows the definition of my model with XML attributes.

##### Command line used for generation

I'm using the maven plugin with `<language>java</language>` and `<library>jersey2</library>`, but the problem seems to affect all of the Java libraries.

##### Steps to reproduce

1. Create a swagger definition in which the object type has XML properties.
2. Generate a Java client using the maven plugin or the CLI
3. Observe that the Java classes generated for the models do not have JAXB annotations

##### Related issues

None that I know of.

##### Suggest a Fix

The [`Java/pojo.mustache`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/pojo.mustache) template needs to be updated with JAXB annotations.  We may also need to update [`CodegenModel`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenModel.java) and [`CodegenProperty`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenProperty.java) with additional members to store the XML properties.  I can work on adding this feature if the team thinks it's valuable.

**Comment by wing328** [comment]
@packleader I remember there's a Java client that supports the JAXB annotations. I'll check on this and get back to you.

**Comment by packleader** [comment]
According to the README for the maven-plugin, there is a config option `useJaxbAnnotations`.  However, it appears that it's only ever used for JavaJaxRS/cxf (in [pojo.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache)).

**Comment by wing328** [comment]
I found the `jaxrs-cxf-client` generator but the auto-generated code is broken due to incorrect response type defined in the annotation.

**Comment by wing328** [comment]
FYI. https://github.com/swagger-api/swagger-codegen/pull/5962 adds XML support to `resttempalte` Java client.

**Comment by packleader** [comment]
@wing328 Thanks for finding that PR.  I think it will solve this issue for all the Java clients.
