### ISSUE TITLE
[lumen] Generated code for verification of path params contains syntax errors

### ISSUE THREAD

**Issue by ffleige** [swagger-api/swagger-codegen#6012]
##### Description
The generated code for verification of path parameters contains syntax errors, due to superfluous closing bracket.

##### Swagger-codegen version
2.2.2

##### Swagger declaration file content or url

https://gist.github.com/ffleige/7981448e6e5f801174fc2079839acca4

##### Command line used for generation
swagger-codegen generate -i swagger.yml -l lumen -o lumen

##### Steps to reproduce
Generate a Lumen server using the linked swagger definition file above.
The function showPetById of generated class App\Http\Controllers\PetsApi will contain buggy code:

```php
 public function showPetById($pet_id)
    {
        $input = Request::all();
        //path params validation
        if (!preg_match("/^[0-9]+$/", $pet_id])) {  // <=== bug!!!
            throw new \InvalidArgumentException('invalid value for $pet_id when calling PetsApi.showPetById, must conform to the pattern /^[0-9]+$/.');
        }
        //not path params validation
        return response('How about implementing showPetById as a GET method ?');
    }
```

**Comment by wing328** [comment]
Closes via #6013
