### ISSUE TITLE
Typescript-angular2 generator does not support polymorphism

### ISSUE THREAD

**Issue by NBakaev** [swagger-api/swagger-codegen#6018]
##### Description
Typescript-angular2 generator does not support polymorphism. If i have base object Founder and have 2 classes that extend that base class (eg FounderComp and FounderPers)

##### Swagger-codegen version

latest. reproducable via generation in http://editor.swagger.io

##### Swagger declaration file content or url
```yaml
---
swagger: "2.0"
info:
  description: "REST API"
  version: "1.0-SNAPSHOT"
  title: "REST API"
  contact:
    url: "http://example.com"
    email: "support@example.com"
  license:
    name: "Company Licence"
host: "localhost:8081"
basePath: "/rest"
tags:
- name: "API"
- name: "founder"
- name: "user"
schemes:
- "http"
- "https"
paths:
  /founder-get:
    get:
      summary: "Returns partner verification"
      description: ""
      operationId: "getFounder"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Founder"
        404:
          description: "founder not found"
definitions:
  Founder:
    type: "object"
    discriminator: "type"
  FounderComp:
    allOf:
    - $ref: "#/definitions/Founder"
  FounderPers:
    allOf:
    - $ref: "#/definitions/Founder"
  
```
##### Steps to reproduce

generate in http://editor.swagger.io and get object 
export interface FounderComp {
}

without "type" property, which should be setup when use discriminator and allOf in swagger

##### Related issues
https://github.com/swagger-api/swagger-codegen/issues/3904

##### Suggest a Fix
add new field "type" to every object that extend base class to determine type class

**Comment by wing328** [comment]
@NBakaev Can you try the `2.3.0` branch instead (which contains a lot of enhancements for TS Angular2)?

I could find the following in the template:
```
swagger-codegen|2.3.0⚡ ⇒ grep -i parent modules/swagger-codegen/src/main/resources/typescript-angular2/*
modules/swagger-codegen/src/main/resources/typescript-angular2/modelGeneric.mustache:export interface {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}{
```

**Comment by wing328** [comment]
We'll reopen this if this is still an issue with 2.3.0 (master)
