### ISSUE TITLE
Swift3 - New generated code differs from old one

### ISSUE THREAD

**Issue by wolfAle** [swagger-api/swagger-codegen#6023]
##### Description

I've used the Swagger `Uber API` example online to generate the Swift3 client code, no changes whatsoever to the yaml.
The issue is that the generated Swift3 code changes from the "old" version of Swagger Editor and the new one.

The difference is that with the old CodeGen `UserAPI.swift` contains (among the rest) a method `historyGet` that would return in the completionBlock an `Activities` object.
`open class func historyGet(offset: Int32? = nil, limit: Int32? = nil, completion: @escaping ((_ data: Activities?,_ error: Error?) -> Void)) {`

However, the new one returns a list of `InlineResponse2003`.
`open class func historyGet(offset: Int32? = nil, limit: Int32? = nil, completion: @escaping ((_ data: InlineResponse2003?,_ error: Error?) -> Void)) {`

The generated `Models` are different as well:

**New Models**
![schermata 2017-07-11 alle 16 14 34](https://user-images.githubusercontent.com/15248820/28073074-03d58b06-6655-11e7-87cb-b43b4ec15f1c.png)

**Old Models**
![schermata 2017-07-11 alle 16 23 13](https://user-images.githubusercontent.com/15248820/28073166-43410004-6655-11e7-8e49-c557782bb4e3.png)

Obviously the old output was much better.
Is there anything I'm missing here? 
Am I doing anything wrong? 
Is this still a WIP in the new version?

##### Steps to reproduce

1. Open the online [Swagger Editor](http://editor.swagger.io/#/)
2. Generate Client --> Swift3
3. Click on `Switch back to previous editor` to go to the [old editor](http://editor2.swagger.io/)
4. Generate Client --> Swift3
5. compare the two outputs

Thanks for your help

**Comment by wing328** [comment]
@wolfAle for Swift3, I would suggest you to try the latest 2.3.0 branch, which contains breaking changes.

I just did a test and found both new and old version of Swagger Editor uses the same https://generator.swagger.io to generate codes.

cc @fehguy

**Comment by wolfAle** [comment]
Hi @wing328,

thanks for the feedback, I'll give it a go.

I actually figured they were using the same version, I think I read it somewhere, but there must be something else that changes because the output is clearly different. 

I'll let you know how the testing with 2.3.0 goes.

**Comment by wolfAle** [comment]
Hi @wing328 and @fehguy 

I've just tested the swagger-codegen branch 2.3.0 and looks ok, the output is exactly as expected.

Not sure why the online swagger-editor outputs a different result. Actually the same happens when installing locally swagger-editor from the last version available on the [github](https://github.com/swagger-api/swagger-editor) page.

Anyway, all good with 2.3.0, I'll use it.

On a side note: I've noticed a few improvements that the generated code could use, would you be open to a PR with those changes applied?

Thanks,
Alessandro

**Comment by wing328** [comment]
@wolfAle please open a PR so that we can review the enhancements.

**Comment by wolfAle** [comment]
Cool, I will.

I'm gonna close this issue, it's not an issue after all.
