### ISSUE TITLE
[Python]Bug in api_client.py __call_api

### ISSUE THREAD

**Issue by zorrofox** [swagger-api/swagger-codegen#6029]
##### Description

In api_client __call_api function [this line](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_client.mustache#L93) use a new init Configuration:
```python
config = Configuration()
```
and I think we should use the parameter configuration which has be assigned to the attribute  like this:
```python
config = self.configuration
```

**Comment by wing328** [comment]
Closed via #6033
