### ISSUE TITLE
android-java client pom.xml should use maven-shade-plugin to generate a fat jar

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#603]
I've been kicking the tires with swagger-codegen and found that the android-java client doesn't work when its resulting jar is included as a module in Android Studio.

After adding maven-shade-plugin support to the pom.xml which was spit out by swagger-codegen, I was able to use the resulting jar successfully in Android Studio.

Is there a reason for not generating poms that yield fat jars by default?

**Comment by fehguy** [comment]
The fat jar can cause more problems than I think necessary, since they can bring in conflicting classes to your project.  To avoid that, it seems best to bring in the dependencies into the gradle build file.
