### ISSUE TITLE
[Maven] dependencies not declared properly in 2.2.2?

### ISSUE THREAD

**Issue by Johanneke** [swagger-api/swagger-codegen#6045]
##### Description

In my company we can't use Maven central and need to use our own hosted Nexus repository. This repository downloads dependencies from maven central when needed. When declaring swagger-cocdegen version 2.2.2 as a dependency, Nexus refuses to download the jar. Other dependencies and even other versions of this same dependency work correctly.
When using swagger-codegen-maven-plugin version 2.2.2, mvn package results in an error about org/apache/commons/lang3/StringUtils missing. It seems that maven does not recognize it as a dependency for the plugin. Using version 2.2.1 everything works fine.

The error when using swagger-codegen-maven-plugin:
```Execution generate-jaxrs-from-swagger of goal io.swagger:swagger-codegen-maven-plugin:2.2.2:generate failed: A required class was missing while executing io.swagger:swagger-codegen-maven-plugin:2.2.2:generate: org/apache/commons/lang3/StringUtils```

##### Steps to reproduce
- Empty maven repository
- Create a project with swagger-codegen-maven-plugin version 2.2.2 plugin
- ```mvn package```

**Comment by wing328** [comment]
@Johanneke as a workaround, what about using the SNAPSHOT version? https://github.com/swagger-api/swagger-codegen#compatibility

> Nexus refuses to download the jar.

Does it show any error in the log?

**Comment by wing328** [comment]
Please try v2.2.3 instead, which has just been released.

We'll reopen this if it's still an issue.

**Comment by Johanneke** [comment]
The problem in Nexus persists for swagger-codegen-2.2.3. I'll have to ask the administrator for any logging.
The maven plugin does work on version 2.2.3, as long as I tell it to use swagger-codegen-2.2.1 instead of 2.2.3.

**Comment by wing328** [comment]
Yup, please check the log. Otherwise, there's no much we can help here. You may want to check the SNAPSHOT version as well to see if it makes any different.

**Comment by Johanneke** [comment]
We get a `SocketTimeoutException: Read timed out`. We're looking into our firewall settings to check if that is causing any issues with downloading dependencies into Nexus.
