### ISSUE TITLE
[Clojure] How to set headers using with-api-context

### ISSUE THREAD

**Issue by devth** [swagger-api/swagger-codegen#6051]
##### Description

I need to set headers in a request (e.g. `If-None-Match`). I tried with:

```clojure
(with-api-context
  {:headers {"If-None-Match" "..."}
   :debug true}
   (foo-get-with-http-info))
```

but in the debug info it doesn't look like my headers were included. I also tried `:header-params` instead of `:headers`, which I see being used in the generated client, but don't see how to set.

Not sure if I'm missing something or if there is no way to set headers currently.

##### Swagger-codegen version

2.2.2

##### Command line used for generation

```
swagger-codegen generate -i swagger.json -l clojure -o .
```

**Comment by wing328** [comment]
@devth What about `header-params`? https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/clojure/api.mustache#L13

Disclaimer: no expert in Clojure.
