### ISSUE TITLE
[Java] Question about how to use Patch with varying content-type

### ISSUE THREAD

**Issue by lwander** [swagger-api/swagger-codegen#6053]
##### Description

The PATCH verb depends heavily on what patch strategy is being applied. For example, "application/json-patch+json", "application/merge-patch+json", and "application/strategic-merge-patch+json" all change the meaning of the request body. As far as I can tell, there is no neat way to tell the generated client which strategy to use. I'll show an example in the below sections that clarifies this:

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

Take the following swagger.json snippet:

```json
"patch": {
  "description": "partially update the specified Deployment",
  "consumes": [
    "application/json-patch+json", 
    "application/merge-patch+json", 
    "application/strategic-merge-patch+json"
  ],
...
```

My understanding of that swagger is that any of the `content-type`s in the `consumes` block should work.

Will generate code like this: https://github.com/kubernetes-client/java/blob/ca0f25614bdb5a9438a04635e07a6390d2a13f1c/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L2066-L2108

The line in question is https://github.com/kubernetes-client/java/blob/ca0f25614bdb5a9438a04635e07a6390d2a13f1c/kubernetes/src/main/java/io/kubernetes/client/apis/AppsV1beta1Api.java#L2091, which by default picks the first content type.

##### Command line used for generation

https://github.com/kubernetes-client/gen/blob/master/openapi/client-generator.sh#L61 invoked by https://github.com/kubernetes-client/gen/blob/master/openapi/java.sh

##### Steps to reproduce

N/A

##### Related issues

Haven't found any

##### Suggest a Fix

I see three ways to fix this:

1. Have your local ApiClient override `selectHeaderContentType` defined [here](https://github.com/swagger-api/swagger-codegen/blob/53bd931f5c57eeb805ef38e47a880d73e3dbdc5d/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L780). It would probably read a flag that's set before issuing a patch command where you've specified what JSON patch strategy you want to employ. This is quick, and easy to do in our client, but feels a little hacky and like it's missing the point of having multiple content-types to choose from.

2. Update the mustache templates for any patch call to take the desired strategy as a parameter. This seems like a fair bit of work, and I feel like someone has run into this already.

3. Update the mustache template for `selectHeaderContentType` to try and infer the patch type when applicable. I don't think this can be done reliably, however.

Any thoughts?

**Comment by fehguy** [comment]
I don't think this will be possible given the current architecture.  When we add the 3.0 spec support you'll have the ability to have more control over how different content-type values will be used.  I suggest that you consider using the codegen to get you started with your case, and then adding custom logic for this.

**Comment by lwander** [comment]
Thanks @fehguy - could you share how the 3.0 spec will help solve this?

**Comment by fehguy** [comment]
Yes, the 3.0 spec (which lives [here](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md)) has moved the `content-type` of an operation like `Patch` into a `requestBody` object (see [here](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#requestBodyObject)).  What that means is that you'll be able to specify exactly how different content types will be handled, and with different schemas.

You can also start using `oneOf` as a JSON Schema construct, which means you can describe what acceptable payloads exist.  So a `Patch` may be an object but no fields are required.

**Comment by lwander** [comment]
Very neat, thanks for the help @fehguy
