### ISSUE TITLE
[Maven-Plugin] Comma-separated string parameters should be lists, rather than strings, in the maven plugin

### ISSUE THREAD

**Issue by zmoore-usgs** [swagger-api/swagger-codegen#6062]
##### Description

In similar vein as https://github.com/swagger-api/swagger-codegen/issues/5383 and following in the theme of https://github.com/swagger-api/swagger-codegen/issues/5860 this in regards to  `instantiation-types`, `type-mappings`, `language-specific-primitives`, `additional-properties`, and `reserved-words-mappings`.  Currently these are all single-string, comma-separated parameters and when the number of entries grows the lists become unmanageable and hard to read.

##### Swagger-codegen version

2.2.1, 2.2.2, 2.2.3-SNAPSHOT

##### Swagger declaration file content or url
This example is taken from https://github.com/swagger-api/swagger-codegen/issues/5383 and tweaked to show type-mappings.

```
<configOptions>
    <type-mappings>json_model=com.mypackage.Model,json_anothermodel=com.mypackage.AnotherModel</type-mappings>
</configOptions>
```

##### Command line used for generation

mvn generate-sources

##### Related issues/PRs

Issues:
https://github.com/swagger-api/swagger-codegen/issues/5383
https://github.com/swagger-api/swagger-codegen/issues/5860

PRs:

https://github.com/swagger-api/swagger-codegen/pull/5384

##### Suggest a fix/enhancement

The same as was proposed in https://github.com/swagger-api/swagger-codegen/issues/5383

(Example modified to show type-mappings)

```
<configOptions>
    <type-mappings>
        <param>json_model=com.mypackage.Model</param>
        <param>json_anothermodel=com.mypackage.AnotherModel</param>
    </type-mappings>
</configOptions>
```

**Comment by fehguy** [comment]
Unfortunately this will be a breaking change for all users of the plugin.  Perhaps you can handle the old format as well as the new?  I don't know if it's possible, but that's why this hasn't been merged.

You may also want to chime in on #6041 as we will be redoing the interface to access the codegen completely with that PR.
