### ISSUE TITLE
Error generation server stub for python-flask

### ISSUE THREAD

**Issue by github-madhu** [swagger-api/swagger-codegen#6074]
##### Description

Unable to generate the server code for python-flask

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url
http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

c:\>java -jar swagger\swagger-codegen-cli-2.2.1.jar generate -i http://petstore.swagger.io/v2/swagger.json -l python-flask
--

##### Steps to reproduce

Run the command

##### The error info

[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\swagger\swagger.yaml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\app.py
Exception in thread "main" java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
        templateFile: app.mustache
        folder:
        destinationFilename: app.py
'
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:603)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.io.FileNotFoundException: c:\.\app.py (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at io.swagger.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:31)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:573)
        ... 2 more

c:\>java -jar swagger\swagger-codegen-cli-2.2.1.jar generate -i http://petstore.swagger.io/v2/swagger.json -l csharp
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
[main] INFO io.swagger.codegen.languages.CSharpClientCodegen - Generating code for .NET Framework v4.5
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Model\ApiResponse.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Model\ApiResponseTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\\ApiResponse.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Model\Category.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Model\CategoryTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\\Category.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Model\Order.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Model\OrderTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\\Order.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Model\Pet.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Model\PetTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\\Pet.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Model\Tag.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Model\TagTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\\Tag.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Model\User.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Model\UserTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\\User.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Api/PetApi.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Api/PetApiTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\/PetApi.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Api/StoreApi.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Api/StoreApiTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\/StoreApi.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Api/UserApi.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger.Test\Api/UserApiTests.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\docs\/UserApi.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Client\IApiAccessor.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Client\Configuration.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Client\ApiClient.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Client\ApiException.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Client\ApiResponse.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\src\IO.Swagger\Client\ExceptionFactory.cs
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\.\build.bat
Exception in thread "main" java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
        templateFile: compile.mustache
        folder:
        destinationFilename: build.bat
'
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:603)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.io.FileNotFoundException: c:\.\build.bat (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at io.swagger.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:31)
        at io.swagger

**Comment by wing328** [comment]
We just release stable version v2.2.3. Please give that a try.

**Comment by github-madhu** [comment]
I have tried v2.2.3 same error

**Comment by wing328** [comment]
```
Caused by: java.io.FileNotFoundException: c:.\app.py (Access is denied)
```
looks like permission issue.

Can you try another folder like c:\temp?
