### ISSUE TITLE
Replace `useJaxbAnnotations` with `withXml`

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#6084]
##### Description

Replace `useJaxbAnnotations` with `withXml` to make it consistent with other generators when it comes to XML support.

https://github.com/swagger-api/swagger-codegen/search?utf8=%E2%9C%93&q=useJaxbAnnotations&type=

##### Swagger-codegen version

Latest master

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/pull/5962

##### Suggest a fix/enhancement

If anyone wants to work on this enhancement, please reply to let us know.

**Comment by mobreza** [comment]
@wing328 I'll give it a go.

**Comment by wing328** [comment]
@mobreza thank you 👍
