### ISSUE TITLE
[Java-PlayFramework] Using wrapCalls=false generates invalid code

### ISSUE THREAD

**Issue by edrevo** [swagger-api/swagger-codegen#6094]
##### Description

`wrapCalls=false` will not emit the `ApiCall.java` file, but it will still use the `@ApiAction` annotation, which in turn depends on `ApiCall`.

The net result is that the code does not compile.

##### Swagger-codegen version
2.2.3

##### Command line used for generation

`java -jar "C:\Users\ximo.HI\Downloads\swagger-codegen-cli-2.2.3.jar" generate -i .\swagger.json -l java-play-framework -o codegen -DwrapCalls=false`

**Comment by wing328** [comment]
@edrevo sorry to hear that. May I know if you've time to contribute the fix?

We'll then need to setup CI (circle CI) to cover this issue moving forward.

**Comment by edrevo** [comment]
hi @wing328,

@tzimisce012 might have time to contribute a fix

**Comment by tzimisce012** [comment]
When JavaPlayFrameworkCodegen is first time initialized it has a value of warpCalls = true, and this is the value that ClientOptInput is going to store and send to the DefaultCodegen.

Later, when then method processOpts is called, JavaPlayFrameworkCodegen changes the value of wrapCalls to false (the value of it is given in the object additionalProperties that gets all its information from CodegenConfigurator)

Still working on the issue

**Comment by JFCote** [comment]
I will look into this as well.

**Comment by JFCote** [comment]
@tzimisce012 : I have found the problem. Will create a PR thing afternoon with the fix

**Comment by JFCote** [comment]
After some consideration, it might take until tomorrow. I will provide a complete fix + all of the required test for the CI.

**Comment by tzimisce012** [comment]
Great

**Comment by wing328** [comment]
Thanks for the fix (#6121) by @JFCote 

@edrevo the fix has been merged into master. Please pull the latest master to give it a try.

**Comment by tzimisce012** [comment]
In the class CodegenConfigurator, in line 390, when the JavaPlayFrameworkCodegen is initialized the wrapCalls value is overwritten and it is changed again from false to true, so the ApiActions annotations are still generated.

**Comment by tzimisce012** [comment]
@JFCote already fixed the problem doing 

```
if (additionalProperties.containsKey(WRAP_CALLS)) {
            this.setWrapCalls(convertPropertyToBoolean(WRAP_CALLS));
        }
writePropertyBack(WRAP_CALLS, wrapCalls);
```
The issue can be closed,

**Comment by JFCote** [comment]
Thank for the testing @tzimisce012 ! @wing328 , you can close the issue :)
