### ISSUE TITLE
[Java-PlayFramework] Fix dependency injection in the Controllers

### ISSUE THREAD

**Issue by tzimisce012** [swagger-api/swagger-codegen#6100]
##### Description

When a controller is generated we have that the constructor has as input the implementation of the interface so no dependency injection can be done.

##### Swagger-codegen version

2.3.0-SNAPSHOT

##### Suggest a fix/enhancement

Instead, the constructor should have the interface of the api.

**Comment by JFCote** [comment]
Hi @tzimisce012 

Thanks for the bug report. Unfortunately, I'm not sure to understand it completely.
Can you please provide an example to illustrate the problem that you have?

Thanks!

**Comment by tzimisce012** [comment]
The generated code is the following:

`public class UsersApiController extends Controller {

    private final UsersApiControllerImp imp;
    private final ObjectMapper mapper;

    @Inject
    private UsersApiController(UsersApiControllerImp imp) {
        this.api = api;
        mapper = new ObjectMapper();
    }`

Instead of using the implementation, the interface should be used, and then the implementation will be used thru dependency injection

**Comment by JFCote** [comment]
@tzimisce012 I will look into it this morning. I'm pretty sure I will need to add a module but it should be easy. Let me check for this. Thanks

**Comment by wing328** [comment]
Closed via #6100
