### ISSUE TITLE
[Core] DefaultGenerator is reading system properties

### ISSUE THREAD

**Issue by edrevo** [swagger-api/swagger-codegen#6101]
##### Description

`DefaultGenerator` has several calls to `System.getProperty` that change the behavior of the class. This makes sense in the context of the CLI, but since this class isn't part of the cli project, it seems more reasonable that these parameters be passed in `ClientOpts` or some other Opt class.

This would make `DefaultGenerator` easier to use as a library

##### Swagger-codegen version

2.2.3

**Comment by wing328** [comment]
@edrevo Here is a related discussion: https://github.com/swagger-api/swagger-codegen/issues/6041

**Comment by edrevo** [comment]
Great, thanks for the pointer. I'll close this issue since it seems like a dupe of the one you mentioned.
