### ISSUE TITLE
Tagged Docker images for releases

### ISSUE THREAD

**Issue by manuc66** [swagger-api/swagger-codegen#6104]
Hi,

Currently only the `latest` tag is available on [DockerHub](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/tags/) which target the master / SNAPSHOT version.

Could it be possible to have tagged docker images per release ?

**Comment by wing328** [comment]
@manuc66 thanks for the suggestion

cc @fehguy as I do not have admin permission on [DockerHub](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/tags/)

**Comment by monsdar** [comment]
In general it would be good to have some kind of indicator about the version that the docker-image is based on.

**Comment by PabloCastellano** [comment]
Looks like this issue was partially fixed at least, as https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/tags shows images for v2.4.14, 2.4.13, 2.4.12... and older.

However the images for v3 are not being uploaded! (3.0.20 has been released already) Can you review it?

**Comment by frantuma** [comment]
Adding here v2 and v3 images links to clarify; please reopen ticket if you have further issues/questions:

#### v2
https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/tags
https://hub.docker.com/r/swaggerapi/swagger-generator/tags

#### v3
https://hub.docker.com/r/swaggerapi/swagger-codegen-cli-v3/tags
https://hub.docker.com/r/swaggerapi/swagger-generator-v3/tags

Full list: https://hub.docker.com/u/swaggerapi
