### ISSUE TITLE
[Java] Jersey, Jersey2 and Resteasy clients do not support HTTP-HEAD

### ISSUE THREAD

**Issue by lopesmcc** [swagger-api/swagger-codegen#6118]
##### Description

Found out that Jersey2 clients do not support requests using the HEAD method. This seems to apply as well to Jersey and resteasy.
Is there any reason for that or was this simple oversight?

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  version: v1
paths:
  /operation-x:
    head:
      operationId: operationX
      responses:
        200:
          description: exists
        404:
          description: does not exist
```

##### Suggest a fix/enhancement

All of those clients have code similar to the following (which is for Jersey 2):
```java
      if ("GET".equals(method)) {
        response = invocationBuilder.get();
      } else if ("POST".equals(method)) {
        response = invocationBuilder.post(entity);
      } else if ("PUT".equals(method)) {
        response = invocationBuilder.put(entity);
      } else if ("DELETE".equals(method)) {
        response = invocationBuilder.delete();
      } else if ("PATCH".equals(method)) {
        response = invocationBuilder.header("X-HTTP-Method-Override", "PATCH").post(entity);
      } else {
        throw new ApiException(500, "unknown method type " + method);
      }
```
Adding something like the following should be enough:
```java
...
    } else if ("HEAD".equals(method)) {
      response = invocationBuilder.head();
    }
...
```

**Comment by wing328** [comment]
@lopesmcc I think that's because we've not encountered a use case with `HEAD` yet. May I know if you've time to contribute the enhancements?

**Comment by lopesmcc** [comment]
@wing328 👍 Will try to find some time for this.

**Comment by YashchenkoN** [comment]
@wing328 @lopesmcc created PR, please review it
#6210

**Comment by lopesmcc** [comment]
@YashchenkoN nice one, thanks!

**Comment by wing328** [comment]
Thanks @YashchenkoN for the PR, which has been merged into master.
