### ISSUE TITLE
{"code":1,"type":"error","message":"Unable to build target: Could not generate api file for 'PartsOrder'"}

### ISSUE THREAD

**Issue by jemprince** [swagger-api/swagger-codegen#6119]
##### Description

codgen fails to produce c#

##### Swagger-codegen version

latest

##### Swagger declaration file content or url

see attached file
[codegen.txt](https://github.com/swagger-api/swagger-codegen/files/1159854/codegen.txt)

**Comment by wing328** [comment]
@jemprince have you used https://editor.swagger.io or other tools to validate the spec?

**Comment by ccp-zoetrope** [comment]
I'm having the same problem except with python and it only happens when using https://editor.swagger.io, however it works if you run the code gen locally with version 2.3.0.

**Comment by wing328** [comment]
@ccp-zoetrope from what I know, https://editor.swagger.io is running Swagger Generator 2.2.3 so please use the local JAR (2.3.0) for the time being. (you can also use the SNAPSHOT version of the latest master, which is v2.3.0)

**Comment by ccp-zoetrope** [comment]
@wing328 do you know if https://editor.swagger.io will be moving to 2.3.0? If so, any ideas on when?

**Comment by jemprince** [comment]
>>> @jemprince have you used https://editor.swagger.io or other tools to validate the spec?
No. The spec we use hasn't changed in months.
This swagger site (and a couple of others) has been working for 6 months and nothing has changed this started to break some time after 14 july.

**Comment by wing328** [comment]
> @wing328 do you know if https://editor.swagger.io will be moving to 2.3.0? If so, any ideas on when?

@ccp-zoetrope We hope to release 2.3.0 by the end of Aug.

**Comment by wing328** [comment]
@jemprince please roll back to the stable release v2.2.2 for the time being: https://github.com/swagger-api/swagger-codegen/releases

Swagger Codegen v2.2.3 is using a newer version of Swagger Parser, which might explain the issue you're seeing.
