### ISSUE TITLE
Jersey2 ApiClient not very extensible

### ISSUE THREAD

**Issue by drd** [swagger-api/swagger-codegen#6123]
##### Description

In working with the generated Jersey2 client libraries, I have found several cases where I need to change or augment some of the default behavior, but I am hindered by all of the `private` fields and methods. In particular, I needed to add a `Feature` to my `HttpClient` but this would not have been possible without essentially copy & pasting the entire `ApiClient.java` source.

##### Swagger-codegen version

This is present in 2.2.2 and 2.3.0.

##### Swagger declaration file content or url

(not specific to swagger declaration)

##### Command line used for generation

Config:
```
{
  "library": "jersey2",
  "artifactId": "${CLIENT_LIB_ARTIFACT_ID}",
  "groupId": "${SERVICE_GROUP_ID}",
  "artifactVersion": "${VERSION}"
}
```

Command:
```
java -jar swagger-codegen-cli.jar \
  generate -i swagger.json \
  -l java \
  -o client_lib \
  -c config.json \
  --api-package "${CLIENT_LIB_PACKAGE}.api" \
  --model-package "${CLIENT_LIB_PACKAGE}.model" \
  --invoker-package ${CLIENT_LIB_PACKAGE}
```

##### Steps to reproduce

Attempt to modify the features present on the http client.

##### Suggest a fix/enhancement

I have a simple diff here: https://github.com/drd/swagger-codegen/tree/drd/more-extensible-jersey-client

**Comment by wing328** [comment]
@drd please file a PR so that we can review the change. Generally I agree with changes to make the API client more extensible.

**Comment by drd** [comment]
@wing328 thanks, here is the PR: https://github.com/swagger-api/swagger-codegen/pull/6159

**Comment by wing328** [comment]
@drd the PR has been merged into master. Thanks for your contribution.
