### ISSUE TITLE
[Kotlin] "sourceFolder" additional property not taken into account in codegen

### ISSUE THREAD

**Issue by CappCorp** [swagger-api/swagger-codegen#6133]
##### Description

sourceFolder is properly ignored for kotlink code generation

##### Swagger-codegen version

2.2.3

##### Command line used for generation

`java -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -t modules/swagger-codegen/src/main/resources/kotlin-client -i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml -l kotlin --artifact-id kotlin-petstore-client -o samples/client/petstore/kotlin -DsourceFolder=generated`

##### Steps to reproduce

Simply run the command line, source folder is ignored, generated code is placed under `/samples/client/petstore/kotlin/src/main` whatever the value of sourceFolder parameter

**Comment by wing328** [comment]
Closed via #6134
