### ISSUE TITLE
[objc] Allow the user to customize the date format

### ISSUE THREAD

**Issue by SirBif** [swagger-api/swagger-codegen#6136]
##### Description

Allow the user to customize the date format. This, for example, would allow specifying a timezone (e.g. UTC) or to add milliseconds.

##### Related issues/PRs

This issue has come up already in other languages:
- https://github.com/swagger-api/swagger-codegen/issues/3439
- https://github.com/swagger-api/swagger-codegen/issues/5318

##### Suggest a fix/enhancement

Adding a configuration option to specify the date format and use a NSDateFormatter instead of depending on the ISO8061 framework

**Comment by wing328** [comment]
@SirBif Thanks for the suggestion.

For other API clients (e.g. C#), we store the datetime format in the configuration, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/Configuration.cs#L39

What about doing something similar in ObjC by storing the datetime format in the DefaultConfiguration class?

**Comment by SirBif** [comment]
Yeah, I was thinking the same. Actually I'd go as far as directly exposing the date formatter itself in the configuration, so users can just set the format and the timezone to use in it.

**Comment by wing328** [comment]
@SirBif may I know if you've time to contribute the enhancement?

**Comment by SirBif** [comment]
Hi. Yep, sorry, I was polishing it. I'll push it very soon
