### ISSUE TITLE
[objc] [Bug] Bool query params sent as either 1 or 0

### ISSUE THREAD

**Issue by marcotta** [swagger-api/swagger-codegen#6139]
Description

Boolean properties when sent as query string parameters are being sent as either 0 or 1.

```
?isEnabled=1
?isEnabled=0
```

To match Swagger-UI behaviour it should send true or false instead
```
?isEnabled=true
?isEnabled=false
```

Swagger-codegen version

2.2.2

Swagger declaration file content or url

```
{
    "name": "isEnabled",
    "description": "Enables the flag",
    "in": "query",
    "type": "boolean"
}
```
Command line used for generation

`swagger-codegen generate -i api-spec.json -l objc -c config.json -o APIClient`

**Comment by wing328** [comment]
Closed via #6142
