### ISSUE TITLE
swagger-codegen 2.3.0 fails to generate models with inheritance

### ISSUE THREAD

**Issue by mricken** [swagger-api/swagger-codegen#6148]
##### Description

swagger-codegen 2.3.0 does not correctly generate Java classes (and internally does not fill out the "parent" field) for models that extend other models.

This works in 2.2.x.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

YAML:
https://gist.github.com/mricken/c7604e0a542d7e6a945bec6b1c8b1478

##### Command line used for generation

Used from
http://editor.swagger.io/#

##### Steps to reproduce

1. Paste YAML
2. Observe model representation (does not show inheritance, everything is flat and composed).
3. Generate Java client, look at Cat.java. No "extends Pet".

For comparison, the "old" editor and generator displays and generates correctly:
http://editor2.swagger.io/#!/

**Comment by wing328** [comment]
@mricken I did a test with the latest master and both Dog.java and Cat.java extend "Pet".

**Comment by mricken** [comment]
Verified that with the latest master it DOES work.

The code deployed at https://editor.swagger.io/ is still broken.

**Comment by wing328** [comment]
https://editor.swagger.io should be using the latest stable version v2.2.3 of "Swagger Generator" (part of the Swagger Codegen project) in which I just did a test and the result is still good.

cc @fehguy to see if there's any chance Swagger Generator is running a different version but not the latest stable v2.2.3

**Comment by jdevera** [comment]
I am also seeing this when trying with 3.0.0

**Comment by jayeshsidhwani** [comment]
I also encountered the same issue as the OP. While the `java` generator seems to be extending the parent class, the `kotlin` seems to be defaulting to composition

**Comment by HugoMario** [comment]
This has been fixed on latest releases, so going to close it.
