### ISSUE TITLE
Anyway to specify Maven artifactId and groupId of generated Java SDK?

### ISSUE THREAD

**Issue by arnm** [swagger-api/swagger-codegen#615]
I'm using Swagger 1.2.

When I generate a Java SDK from my swagger spec the pom.xml generated has default values. Is there any way I can generate the SDK with values I specify?

I know I can edit the pom after I generate the SDK but I would like for it to be generated automatically.

**Comment by fehguy** [comment]
Please track here:  https://github.com/swagger-api/swagger-codegen/issues/616

We will make a generalized mechanism for configs.
