### ISSUE TITLE
Jersey2 REST Client with supportJava6 not working

### ISSUE THREAD

**Issue by jdidac** [swagger-api/swagger-codegen#6154]
When you try to create a REST Client using jersey2 library with supportJava6, it's not working because generated client has maven dependencies with Jersey 2.25 then Java7 is needed then it's not compatible with Java6. How can I create a jersey2 client with maven dependencies with Jersey 2.4 or 2.6 to use Java6?

**Comment by wing328** [comment]
@jdidac thanks for reporting the issue. To fix, we'll need to update https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/pom.mustache#L286-L290 using `{{^ supportJava6}} ... {/supportJava6}}` for Jersey 2.25.1

May I know if you've time to contribute the fix?

**Comment by wing328** [comment]
@jdidac I've fixed the issue via #6198 

Please pull the latest master to give it a try.
