### ISSUE TITLE
[Typescript][Node] Use typescript 2 typings system?

### ISSUE THREAD

**Issue by duanshiqiang** [swagger-api/swagger-codegen#6163]
##### Description

Currently the `typescript-node` still uses typings system of typescript1 and generates library that depends on project `typings`. `typescript-angular2` has been updated to use typescript2 typing system [refer to: #5965](https://github.com/swagger-api/swagger-codegen/pulls) and it makes sense to update `typescript-node` also.

##### Swagger-codegen version
 2.2.3

**Comment by wing328** [comment]
@duanshiqiang thanks for the suggestion. May I know if you've time to contribute a PR with the suggested enhancement?

**Comment by duanshiqiang** [comment]
@wing328 sure, but I'm a starter of typescript. I'll try do do it asap I got time after work.

**Comment by wing328** [comment]
@duanshiqiang thanks 👍  A good starting point is to look at the change for removing typings from typescript-angular2 package.mustache: https://github.com/swagger-api/swagger-codegen/pull/5966/files#diff-205a59017a660768be5412f97ea62565

Then you can apply similar change to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/package.mustache (TS Node package.mustache)

Let me know if you've any question or need any help.
