### ISSUE TITLE
[PHP] Missing template on file param name in php api mustache

### ISSUE THREAD

**Issue by Alex-D** [swagger-api/swagger-codegen#6170]
##### Description

If you have a file field which is not named "file", generated code is wrong since only a part of the method is templated.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

modules/swagger-codegen/src/main/resources/php/api.mustache:361

##### Command line used for generation

PHP

##### Suggest a fix/enhancement

PR #6171

**Comment by wing328** [comment]
Closed via #6171 

Thanks for the PR from @Alex-D
