### ISSUE TITLE
[Java-PlayFramework] Using the method request() in the wrong class

### ISSUE THREAD

**Issue by tzimisce012** [swagger-api/swagger-codegen#6181]
##### Description

In the ApiControllerImplementation of the api interfaces is being used the method request() even though the class is not an extension of the class Controller.

##### Swagger-codegen version

2.3.0

##### Steps to reproduce

You can find the bug in the file newApi.mustache

##### Related issues/PRs

Other issues related with this mustache file can be found here:
https://github.com/swagger-api/swagger-codegen/issues/6180

##### Suggest a fix/enhancement

I would suggest remove all kind of business logic in the generation of this class.

**Comment by JFCote** [comment]
@wing328 
This will be fix by #6128 when it gets merged.

It was cause by the examples

**Comment by wing328** [comment]
Closed via #6128
