### ISSUE TITLE
[Android] Add requestPackage and authPackage variables to the configuration

### ISSUE THREAD

**Issue by encos** [swagger-api/swagger-codegen#6183]
I cannot pass custom values for variables `requestPackage `and `authPackage `in android generator. I'm trying against version 2.2.3 

In the [AndroidClientCodegen](https://github.com/swagger-api/swagger-codegen/blob/63facc0b0b6d8c7436af94ab332b33e444825979/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java) 

```java
 // requestPackage and authPackage are used by the "volley" template/library
    protected String requestPackage = "io.swagger.client.request";
    protected String authPackage = "io.swagger.client.auth";
    protected String gradleWrapperPackage = "gradle.wrapper";
    protected String apiDocPath = "docs/";
    protected String modelDocPath = "docs/";
```

the 2 variables I mentioned are never overwritten

Is there a reason for it? Is it possible to add them to the configuration or as environment variables?

**Comment by wing328** [comment]
I think these 2 variables should be set when [`invokerPackage`](https://github.com/swagger-api/swagger-codegen/blob/63facc0b0b6d8c7436af94ab332b33e444825979/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java#L25) is set: 

https://github.com/swagger-api/swagger-codegen/blob/63facc0b0b6d8c7436af94ab332b33e444825979/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java#L347-L352

Do you agree?

**Comment by encos** [comment]
From what I see it seems that the invokerPackage is used properly in the package declaration on top of java files but not when it comes to the directory structure for those files. 

From here:
https://github.com/swagger-api/swagger-codegen/blob/63facc0b0b6d8c7436af94ab332b33e444825979/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AndroidClientCodegen.java#L469-L484

It seems that the path is generated without using the invokerPackage
```java
(sourceFolder + File.separator + requestPackage).replace(".", File.separator)
(sourceFolder + File.separator + auth).replace(".", File.separator)
```

**Comment by wing328** [comment]
I've filed #6200 to fix the issue. Please review the fix when you've time.

**Comment by wing328** [comment]
@encos I did some more tests and the fix works for me.

Please pull the latest to give it a try.

**Comment by encos** [comment]
Hi I just tried, works fine now. Thanks!
