### ISSUE TITLE
Typescript-Angular2 produces invalid import for self-referencing model 

### ISSUE THREAD

**Issue by psamwel** [swagger-api/swagger-codegen#6201]
##### Description

typescript-angular2 client codegen for a model that references itself (e.g.):

```json
		"APISearchTerm": {
			"description": "Adds generic filter capability to API",
			"type": "object",
			"properties": {
				"field": {
					"description": "Field to compare",
					"type": "string"
				},
				"fieldValue": {
					"description": "Primary value",
					"type": "string"
				},
				"searchOperation": {
					"description": "Operator type",
					"enum": ["Equal",
					"NotEqual",
					"Contains",
					"GreaterThan",
					"GreaterThanOrEqual",
					"LessThan",
					"LessThanOrEqual"],
					"type": "string"
				},
				"and": {
					"description": "For building nested And expressions",
					"type": "array",
					"items": {
						"$ref": "#/definitions/APISearchTerm"
					}
				},
				"or": {
					"description": "For building nested Or expressions",
					"type": "array",
					"items": {
						"$ref": "#/definitions/APISearchTerm"
					}
				}
			}
		}
```

resulting in:

```typescript
import { APISearchTerm } from './aPISearchTerm';

export interface APISearchTerm {
    field?: string;
    fieldValue?: string;
    searchOperation?: APISearchTerm.SearchOperationEnum;
    and?: Array<APISearchTerm>;
    or?: Array<APISearchTerm>;
}
...
```
which produces the following tsc error(s):

[12:04:12]Error at aPISearchTerm.ts:13:10: Individual declarations in merged declaration 'APISearchTerm' must be all exported or all local.
[12:04:12]Error at aPISearchTerm.ts:13:10: Import declaration conflicts with local declaration of 'APISearchTerm'
[12:04:12]Error at aPISearchTerm.ts:46:18: Individual declarations in merged declaration 'APISearchTerm' must be all exported or all local.

##### Swagger-codegen version
Verified in latest master & 2.3.0 locally.

2.3.0 branch

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i application.json -l typescript-angular2 -o $outputpath/sdk_angular2 -c $clientConfig

where $clientConfig:
`{
    "modelPropertyNaming": "original"
}`

##### Suggest a fix/enhancement

Exclude a classname from its own list of imports.

**Comment by wing328** [comment]
```typescript
import { APISearchTerm } from './aPISearchTerm';

export interface APISearchTerm {
    field?: string;
    fieldValue?: string;
    searchOperation?: APISearchTerm.SearchOperationEnum;
    and?: Array<APISearchTerm>;
    or?: Array<APISearchTerm>;
}
...
```

@psamwel thanks for reporting the issue. What should be the correct output look like?

cc @Vrolijkx @taxpon @sebastianhaas @kenisteward @TiFu

**Comment by kenisteward** [comment]
@wing328 it should not have an import at the top because the interface is
in the same file

**Comment by wing328** [comment]
@kenisteward looks like the issue we can loop through models via [`postProcessModels`](https://github.com/swagger-api/swagger-codegen/blob/78051257136d79f17c1dab7c814557f40e163c48/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java#L262) and add vendor extensions (e.g. x-ts-angular2-self-ref) to avoid the import.

If anyone has better suggestions, please reply to let us know.

**Comment by kenisteward** [comment]
That seems fine. I'm on vacation right now and don't have access to my
computer atm. But this should definitely be done for all clients.

I really wish I had time to recombine all the clients into 1 typescript 1

**Comment by wing328** [comment]
@kenisteward Enjoy your vacation 👍

**Comment by sebastianhaas** [comment]
Isn't this something that could happen in any language that uses imports? It feels weird to add Angular-specific logic for something that might happen in C# etc. as well :/

**Comment by kenisteward** [comment]
I don't think we have a generic handler for imports do we?
