### ISSUE TITLE
[SWIFT3] POD Generated podfile doesn't include all generated swift files

### ISSUE THREAD

**Issue by hce** [swagger-api/swagger-codegen#6212]
##### Description

When using swagger-codegen to generate swift3 code, a pod file is generated. When using this podfile to import the generated code into an xcode project, not all files are imported.

The generated podfile has this line:
    s.source_files = 'Client/Classes/Swaggers/**/*.swift'

This excludes the directory "Swaggersgen" which contains the DefaultAPI file. I've changed the line to
    s.source_files = 'Client/Classes/**/**/*.swift'

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

n/a

##### Command line used for generation

swagger-codegen generate -l swift3 -i https://some.url/some.service/private/swagger.json --api-package some.package.name -c swagger-codegen.config.json -o code

##### Steps to reproduce

Just generate the files using the above command.

##### Related issues/PRs

unknown

##### Suggest a fix/enhancement

Change the following line in the generated podfile to this:
    s.source_files = 'Client/Classes/**/**/*.swift'

**Comment by hce** [comment]
Due to formatting issues, the double stars in my changed line do not appear. What I meant to write was:

s.source_files = 'Client/Classes/ ** / ** /*.swift' (without the spaces)

**Comment by wing328** [comment]
@hce thanks for reporting the issue. Please kindly file a PR with the suggested fix so that we can review more easily.

**Comment by hce** [comment]
@wing328 I haven't modified your codebase, just modified the podfile of the *generated* code... If you want a PR, it'd take me some time as I'm not familiar with your code at this time.

**Comment by wing328** [comment]
@hce let me point you to the right file to make the update. Give me a sec.

**Comment by wing328** [comment]
Swift: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/Podspec.mustache#L28

Swift3: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift3/Podspec.mustache#L17

Swfit4: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift4/Podspec.mustache#L17

**Comment by hce** [comment]
Thank you, I'll have a look at it.

**Comment by wing328** [comment]
After the change, please run the following scripts to update Petstore samples so that the CI (travis) can verify the change:
```
./bin/swift-petstore-all.sh
./bin/swift3-petstore-all.sh
./bin/swift4-petstore-all.sh
```

**Comment by hce** [comment]
There you go: https://github.com/swagger-api/swagger-codegen/pull/6220

**Comment by wing328** [comment]
@hce thanks for the PR, which has been merged into master.
