### ISSUE TITLE
[Swift3] Client API credentials ignored?

### ISSUE THREAD

**Issue by hce** [swagger-api/swagger-codegen#6213]
##### Description

It seems the credentials supplied to the generated client API via
    ClientAPI.credential = URLCredential.init(...)

seems to be ignored by the generated code.

open class ClientAPI {
    [...]
    // this variable seems to be ignored
    open static var credential: URLCredential?
    [...]    
}

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

n/a

##### Command line used for generation

swagger-codegen generate -l swift3 -i https://path.to.some.server/some_api/private/swagger.json --api-package some.package -c swagger-codegen.config.json -o code

##### Steps to reproduce

Use an API that requires HTTP BASIC authentication, instantiate the API, set the credentials and make a request. The request should fail due to the credentials not being sent.

##### Related issues/PRs

n/a

##### Suggest a fix/enhancement

Pay heed to the supplied credentials

**Comment by wing328** [comment]
Please give 2.3.0 (current master) a try as it has a lof breaking changes (enhancements, bug fixes)

**Comment by hce** [comment]
Yup. Seems to be working. Thank you! (-:
