### ISSUE TITLE
[Async-Scala] Package name should be stripped from the class name

### ISSUE THREAD

**Issue by ramzimaalej** [swagger-api/swagger-codegen#6234]
##### Description

When generating a client using Async-scala module, the class name of the generated models contains the package like this "models.WebsiteBodyModel" which causes compilation errors. I tried many config parameters to override this behavior but ended up submitting a PR to fix.

##### Swagger-codegen version

Latest

##### Swagger declaration file content or url

[link to json file to reproduce the error](https://gist.github.com/ramzimaalej/88a079d293ca7f3a099beec97e74db66)

##### Command line used for generation

swagger-codegen generate -i pet.json -l async-scala

##### Steps to reproduce

cd into the folder created by the generator and do: sbt compile

##### Suggest a fix/enhancement

This [PR](https://github.com/swagger-api/swagger-codegen/pull/6235) fixes the problem

**Comment by wing328** [comment]
Please try the latest master to generate scala client, which combines both `scala` and `async-scala` clients into one.
