### ISSUE TITLE
develop-2.0: java.util.Calendar can't get instantiated

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#624]
Swagger-Codegen: develop-2.0
Swagger-SpringMvc: 2.0.0-SNAPSHOT

Swagger-SpringMvc currently renders a java.util.Calendar as follows in the api-docs:
```
"ShowcaseDatatypeDate":{"properties":{"calendar":{"$ref":"#/definitions/Calendar"},"date":{"type":"string","format":"date-time"}}}
...
"Calendar":{"properties":{"firstDayOfWeek":{"type":"integer","format":"int32"},"lenient":{"type":"boolean"},"minimalDaysInFirstWeek":{"type":"integer","format":"int32"},"time":{"type":"string","format":"date-time"},"timeInMillis":{"type":"integer","format":"int64"},"timeZone":{"$ref":"#/definitions/TimeZone"},"weekDateSupported":{"type":"boolean"},"weekYear":{"type":"integer","format":"int32"},"weeksInWeekYear":{"type":"integer","format":"int32"}}}}
```

After generating client code, Swagger-Codegen will create a separate Class for Calendar, which holds all properties above.

However, when the api gets called, the Response object cannot be created:
```java
io.swagger.client.ApiException: Can not instantiate value of type [simple type, class io.swagger.client.model.Calendar] from Long integral number (1428851792519); no single-long-arg constructor/factory method
 at [Source: {"id":1,"name":"Test","state":"ACTIVE","photo":[48,49],"categories":[{"id":1,"name":"Category 1"},{"id":2,"name":"Category 2"}],"locations":[{"street":"1 Howard St","zip":"94103","city":"San Francisco","country":"United States","latitude":37.78199,"longitude":-122.40406}],"locationMap":{},"primitives":{"singleByte":127,"tinyNumber":32767,"counter":2147483647,"id":9223372036854775807,"budgetFloat":3.4028235E38,"budget":1.7976931348623157E308,"deleted":false,"singleCharacter":"?"},"math":{"bigInteger":9223372036854775807,"bigDecimal":1.7976931348623157E+308},"date":{"date":1428850032123,"calendar":1428851792519}}; line: 1, column: 592] (through reference chain: io.swagger.client.model.User["date"]->io.swagger.client.model.ShowcaseDatatypeDate["calendar"])
```

I'm not sure whether the api-docs should be rendered differently (Swagger-SpringMvc issue) or whether this is a matter of Swagger-Codegen?

**Comment by webron** [comment]
Putting aside the internal structure of your application - if I understand correctly, ShowcaseDatatypeDate is used as a response for one of your API operations. What does the response actually look like? (that is, what is the JSON/XML/whatever produced by calling that API?)

If I had to guess, I believe the Calendar is translated to long and that's what the documentation should expose.

**Comment by fehguy** [comment]
Can you please share what your Calendar model looks like?  It should work...

However, I do suggest that the `Calendar` type is represented as `date-time` in the description.

**Comment by jfiala** [comment]
In fact, I simply expose a java.util.Calendar structure:
https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html

The trouble is, that a Calendar currently is exposed as a model structure, but the real object will be sent over the wire as 
```
"calendar": 1428909372307
```

So it will be sent as a simple long value, not as a structure.
So the API provider should expose java.util.Calendar as a long value I suppose to make it possible for Swagger-Codegen to pick it up.
(And there is nothing wrong with the Java code generated by Swagger-Codegen)

I'll post it to the springfox-project.

**Comment by webron** [comment]
Looks like the response in springfox resolved this issue. Closing for now, please reopen as needed.
