### ISSUE TITLE
[Haskell]  Generated API code has overlong names

### ISSUE THREAD

**Issue by strake** [swagger-api/swagger-codegen#6242]
##### Description

From petstore example:
`type SwaggerPetstoreAPI = _`
`data SwaggerPetstoreBackend m = _`
`newtype SwaggerPetstoreClient a = _`

The "SwaggerPetstore" prefix is needlessly verbose as these are already in the module `SwaggerPetstore.API`, which one can import qualified.

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

`http://petstore.swagger.io/v2/swagger.json`

##### Command line used for generation

`swagger-codegen generate -lhaskell -iswagger.json`

##### Steps to reproduce

```sh
curl -LO http://petstore.swagger.io/v2/swagger.json
swagger-codegen generate -lhaskell -iswagger.json
```

##### Suggest a fix/enhancement

Emit simple type names with no titular prefix, e.g. `API`, `Backend`, `Client`.

**Comment by wing328** [comment]
@strake Have you tried to customize the output using the following?
```
--additional-properties title=Dummy
```

**Comment by wing328** [comment]
Closing it as there's no update.
