### ISSUE TITLE
Swift3;  array seems broken

### ISSUE THREAD

**Issue by dgaedcke** [swagger-api/swagger-codegen#6243]
##### Description

Model object definition is missing from my generated swift source...
TradeEntityMtMsgCollection
is referenced many places throughout my generated swift code, but it's definition is not declared anywhere.  I'm not sure if this is a Swagger-codegen problem or if the issue lies elsewhere...

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url
My Swagger file contains:
```yaml
  TradeEntityMtMsgCollection:
    description: TradeEntityMtMsgCollection is the media type for an array of TradeEntityMtMsg
      (default view)
    example:
    - appId: Velit aut aspernatur quos.
      cost: 0.78245723
      shares: 0.13033341
      status: Et ducimus consectetur.
      transId: Sit sit omnis voluptas.
    items:
      $ref: '#/definitions/TradeEntityMtMsg'
    title: 'Mediatype identifier: application/nmg.tradeentity; type=collection; view=default'
    type: array
```
##### Command line used for generation

swagger-codegen generate \
   -i swagger/swagger.json \
   -l swift3 \
   -o /Users/dgaedcke/Downloads \
   -c apigen_config.json

##### Steps to reproduce

I can provide my swagger file if requested..

##### Suggest a fix/enhancement

that's over my head...

**Comment by wing328** [comment]
Please try the latest master (2.3.0), which has a lot of enhancements (breaking changes) to Swift3 generator.

**Comment by wing328** [comment]
Closing this as there's no update.
