### ISSUE TITLE
Swift 3 Warnings

### ISSUE THREAD

**Issue by ahmettahasakar** [swagger-api/swagger-codegen#6258]
Hello,

When I build with the master branch, I get two warnings for Swift 3.

- Result of call to 'addHeader(name:value:)' is unused
- 'where' clause next to generic parameters is deprecated and will be removed in the future version of Swift

Should these be fixed? I can create a pull request if you want.

Thank you.

**Comment by jaz-ah** [comment]
what version of Xcode are you using?  yes please submit a PR thanks!

**Comment by ahmettaha** [comment]
It's Xcode 8.3.3
