### ISSUE TITLE
[Rails5] Reserved word causing codegen to fail

### ISSUE THREAD

**Issue by willyko** [swagger-api/swagger-codegen#6264]
##### Description

Reserved word causes Rails5 codegen to fail.  However, Ruby codegen has a workaround that renames the words that's causing an issue.  Hoping this can be ported to Rails5

##### Swagger-codegen version

2.2.3

##### Command line used for generation

`swagger-codegen generate -i swagger.yaml -o ./server/generated-server -l rails5`

##### Suggest a fix/enhancement

Not sure if it's as simple as taking 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java#L478-L483
and putting it in 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Rails5ServerCodegen.java#L259
and
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Rails5ServerCodegen.java#L259

**Comment by wing328** [comment]
@willyko yup, I think it should be as simple as that. Do you have time to file a PR for the suggest?
