### ISSUE TITLE
swagger-codegen does not let me pick package name

### ISSUE THREAD

**Issue by josephmisiti** [swagger-api/swagger-codegen#627]
If I execute the following command in bash

```bash
	java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate  \
		 -i http://developers.vestorly.com/v2/api-docs  \
		 -l python   -o /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python
```

I see the following output:

```
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/rss_feed.py
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/post.py
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/article.py
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/event.py
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/advisor.py
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/source.py
writing file /Users/josephmisiti/mathandpencil/projects/vestorly/clients/v2/python/SwaggerPetstore-python/SwaggerPetstore/models/session.py
```

I do not want the folder `SwaggerPetstore` created on my machine

**Comment by fehguy** [comment]
What's wrong with pets?

The generator needs this:

https://github.com/swagger-api/swagger-codegen/issues/616

Then you will be able to configure it.  Essentially it means either passing in a JSON configuration object or a bunch of args.  Still deciding which way to take that.

**Comment by josephmisiti** [comment]
I just mean I am using `swagger-codegen` for a public facing API and SwaggerPetstore has nothing to do with. If I understand correctly, does this mean that the functionality doesnt currently exist per #616

**Comment by fehguy** [comment]
There are two options.

1) Everything in the codegen is intended to be modified.  Typically people will do so by extending the functionality in the language classes.

2) We can choose different defaults in the codegen project to get the pets out.  I agree it should be SwaggerClient instead of Petstore.

**Comment by josephmisiti** [comment]
cool thank you!

**Comment by webron** [comment]
Closing this issue as it is indeed covered by #616 (though not yet resolved). Please add any relevant comments there.
