### ISSUE TITLE
NullPointer error from CLI

### ISSUE THREAD

**Issue by dancrumb** [swagger-api/swagger-codegen#6272]
##### Description

When trying to parse a Swagger 3 JSON file, I'm getting a NPE

##### Swagger-codegen version

3.0.0-20170727.135949-1

##### Swagger declaration file content or url

https://gist.github.com/dancrumb/df25eec9d2b74f42faab8753ee66d257

##### Command line used for generation

 java -jar swagger-codegen-cli.jar validate -i ../alex-platform/services/v8-php-calculator/swagger.json

##### Steps to reproduce

That's all it takes ^^

##### Related issues/PRs

None that I can find

##### Suggest a fix/enhancement

```
Validating spec file (../alex-platform/services/v8-php-calculator/swagger.json)
Exception in thread "main" java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at io.swagger.codegen.cmd.Validate.run(Validate.java:27)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by FarooqKhan** [comment]
I am getting the same error
