### ISSUE TITLE
Error Making my own codegen module

### ISSUE THREAD

**Issue by erickcsh** [swagger-api/swagger-codegen#6282]
Steps I'm following:

1) Clone swagger-codegen
2) run `mvn clean package`
3) ```java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar meta -o output/mypackage -n myCustomCodegen -p my.package```
4) `cd output/mypackage`
5) `mvn package`

Error I am getting:
```
ERROR] Failed to execute goal on project myCustomCodegen-swagger-codegen: Could not resolve dependencies for project io.swagger:myCustomCodegen-swagger-codegen:jar:1.0.0: Could not find artifact io.swagger:swagger-codegen:jar:2.3.0-SNAPSHOT -> [Help 1]
```

**Comment by bruno-bert** [comment]
Hello erick im havinh same issue. Did you resolved it?

**Comment by erickcsh** [comment]
Hello Bruno, sorry for the late response. Actually I started using an older version instead of 2.3.0-SNAPSHOT
