### ISSUE TITLE
[typescript-angular] URLSearchParams does not allow to pass '+' character 

### ISSUE THREAD

**Issue by taxpon** [swagger-api/swagger-codegen#6306]
##### Description

As reported in angular/angular#11058, [URLSearchParams](https://angular.io/api/http/URLSearchParams) does not allow to pass '+' character. Currently I am developing a search interface with email and email can contain '+' character obviously like `foo+bar@example.com`. So this behavior is problem for me.

##### Swagger-codegen version

Latest master

##### Suggest a fix/enhancement

`URLSearchParams` can receive customized encoder as in the [document](https://angular.io/api/http/URLSearchParamsa). My suggestion is implement custom encoder as follows:

```TypeScript
/*
 * CustomQueryEncoderHelper
 * Fix plus sign (+) not encoding, so sent as blank space
 * See: https://github.com/angular/angular/issues/11058#issuecomment-247367318
 */
import { QueryEncoder } from "@angular/http";

export class CustomQueryEncoderHelper extends QueryEncoder {
    encodeKey(k: string): string {
        k = super.encodeKey(k);
        return k.replace(/\+/gi, '%2B');
    }
    encodeValue(v: string): string {
        v = super.encodeValue(v);
        return v.replace(/\+/gi, '%2B');
    }
}
```
And update URLSearchParams in `api.service.mustache` as follows.
```TypeScript
let queryParameters = new URLSearchParams('', new CustomQueryEncoderHelper());
```
This code is cited from [this comment](https://github.com/angular/angular/issues/11058#issuecomment-292457108) in angular/angular#11058.

I will file a PR soon if there is no problem.

**Comment by macjohnny** [comment]
@taxpon @wing328 this issue should be reopened, as the changes went missing in #6295.
PR #6574 should re-apply them.

**Comment by macjohnny** [comment]
This issue was resolved with https://github.com/swagger-api/swagger-codegen/pull/6574 and can be closed
