### ISSUE TITLE
In the generated Markdown documentation, anchors must be lowercase to work on GitHub

### ISSUE THREAD

**Issue by manuelkiessling** [swagger-api/swagger-codegen#6308]
##### Description

When generating API client code (in my case, for PHP), swagger-codegen also generates a Markdown documentation for the resulting client. It consists of several Markdown documents which are hyperlinked using anchors. The anchors in generated URLs are written WithUpperAndLowerCase, but when browsing the documentation on GitHub, lowercase-only anchors are expected.

Example:
https://github.com/gamingsolved/paperspace-api-php-client/blob/c59bf79d0fb7bbbb0dce6a5b6cee87e23ac505b9/src-generated/0.1.3/docs/Api/MachinesApi.md links to https://github.com/gamingsolved/paperspace-api-php-client/blob/c59bf79d0fb7bbbb0dce6a5b6cee87e23ac505b9/src-generated/0.1.3/docs/Api/MachinesApi.md#createMachine, but only https://github.com/gamingsolved/paperspace-api-php-client/blob/c59bf79d0fb7bbbb0dce6a5b6cee87e23ac505b9/src-generated/0.1.3/docs/Api/MachinesApi.md#createmachine works (`#createmachine` instead of `#createMachine`).

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

Not relevant in this case.

##### Command line used for generation

Running from the root folder of https://github.com/gamingsolved/paperspace-api-php-client at c59bf79d0fb7bbbb0dce6a5b6cee87e23ac505b9:

```
java -jar swagger-codegen-cli.jar generate \
       -i ./api-definitions/0.1.3/paperspace-api-swagger-definition.json \
       -l php \
       -c ./api-definitions/0.1.3/swagger-config.json \
       -o ./src-generated/0.1.3
```

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

We probably just need to make all anchor parts in generated links lowercase, however the risk is that this makes it work on GitHub, but breaks stuff on other Markdown browsers.

**Comment by wing328** [comment]
@manuelkiessling looks like the issue has already been fixed.

e.g. https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/README.md#documentation-for-api-endpoints
