### ISSUE TITLE
allOf only works when defined directly under definitions

### ISSUE THREAD

**Issue by dentych** [swagger-api/swagger-codegen#6318]
Swagger codegen version: 2.3

I am working on a project, where the people specifying the OAS document have begun extensively using the allOf keyword. This does work in only ONE out of all the use cases we've tried. That is when defined in an object, directly under the definitions sections.

Example (working):

```
...
definitions:
  SomeObject:
    allOf:
      - $ref: '#!/definitions/SomeOtherObject'
      - type: object
        properties:
          thisWorks:
            type: string
```

However, we've tried a multitude of other things, that does NOT work.

Take a look at this example:

```yaml
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
host: "localhost"
basePath: "/api"
schemes:
- "http"
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        200:
          description: response
          schema:
            $ref: '#/definitions/ObjB'
definitions:
  ObjA:
    type: object
    properties:
      prop1:
        type: string
  ObjB:
    type: object
    properties:
      propB:
        allOf:
          - $ref: '#/definitions/ObjA'
          - type: object
            properties:
              propB2:
                type: string
```
Doesn't work. ObjB doesn't contain "propB".
Now, take a look at this example:

```yaml
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
host: "localhost"
basePath: "/api"
schemes:
- "http"
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        200:
          description: response
          schema:
            $ref: '#/definitions/ObjB'
definitions:
  ObjA:
    type: object
    properties:
      prop1:
        type: string
  ObjB:
    type: array
    items:
      allOf:
        - $ref: '#/definitions/ObjA'
        - type: object
          properties:
            propB2:
              type: string
```
This doesn't work either. In Java, it will generate the following class:

`public class ObjB extends ArrayList<ERRORUNKNOWN>`

**Comment by wing328** [comment]
@dentych thanks for reporting the issue. Can you please share the spec to more easily reproduce the issue?

**Comment by dentych** [comment]
@wing328 Hey. I have modified my original text, so it now includes full specs, ready to be copy pasted into an editor/codegen/whatever 😃

**Comment by djanku** [comment]
Is anybody working on it?

**Comment by olivierpaquet** [comment]
Same question from my side, because we encountered a lot of issues currently using the swagger-codegen-maven-plugin to generate our stubs. Is there any progress?

We have issues with for example this swagger def: https://github.com/OpenBankingUK/account-info-api-spec/blob/master/dist/v2.0-rc3/account-info-swagger.yaml , its a valid Swagger file but the generated code is still broken.

**Comment by dentych** [comment]
Does anyone know if this has been fixed or if it's still an issue ??...

**Comment by irissoftworks** [comment]
I am facing this issue now, working on a project in which the swagger spec is autogenerated by the framework based on decorators, and the underlying library uses this construct to describe types. 

I can confirm generated clients (at least the node-typescript one) can't see the correct typing, even though the swagger UI can see them perfectly. 

Also, the type was defined as ERRORUNKNOWN with codegen 2.4.0 which I was using before - funny enough when I upgraded to codegen 2.4.8 it just shows the typing as any, but not the weird ERRORUNKNOWN.

Any idea if there are any plans to fix this ?

**Comment by dentych** [comment]
Doesn't seem like this receives any attention. Closing the issue.
