### ISSUE TITLE
[PHP Client] Nested models do not deserialize correctly

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#635]
If you have nested models in your swagger spec, the nested object does not deserialize correctly.

Given this Swagger 2.0 spec snippet:

```
...
  "definitions": {
    "BookAuthor": {
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "Book": {
      "properties": {
        "name": {
          "type": "string"
        },
        "bookAuthor": {
          "$ref": "#/definitions/BookAuthor"
        }
      }
    }
  }
...
```

The PHP client will yield this JSON when returning **Book** responses.

```
{"name":"My Book Name","book_author":null}
```

The fix for this appears to be in the `deserialize()` method of [APIClient.Mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/APIClient.mustache)

Here's the apparent fix: 

Change this:
```
...
      foreach ($instance::$swaggerTypes as $property => $type) {
        if (isset($data->$property)) {
          $original_property_name = $instance::$attributeMap[$property];
          $instance->$property = self::deserialize($data->$original_property_name, $type);
        }
      }
...
```

To this:
```
...
      foreach ($instance::$swaggerTypes as $property => $type) {
        $original_property_name = $instance::$attributeMap[$property];
        if (isset($original_property_name)) {
          $instance->$property = self::deserialize($data->$original_property_name, $type);
        }
      }
...
```

**Comment by fehguy** [comment]
Thanks.  Yes, @who, there is currently no support for nested schemas right now.  It will be added, but for now please consider using `$ref` syntax to flatten them out.

**Comment by who** [comment]
@fehguy 

Using the code that I provided, I am able to deserialize nested models (at least 2 levels deep) correctly.

Would you be willing to take this as a PR ?

**Comment by fehguy** [comment]
@who i stand corrected, the snipped you put _is_ valid.  I read it as there was a schema in a property which _is not_ currently supported in the codegen project.

So yes, please do send a PR.  Apologies for the misidentification of the issue.

**Comment by who** [comment]
@fehguy 

I've added it to my existing PHP PR where I've fixed another issue as well.

https://github.com/swagger-api/swagger-codegen/pull/630

**Comment by fehguy** [comment]
great, thank you.

**Comment by who** [comment]
Closing this, as it's fixed now.
