### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-codegen#6363]
##### Description

When trying to fix some bugs in the Java PlayFramework generator, I've come across something I think is a bug.

Let's say you have a model called `Software` which have a property `Platform`.

```yaml
  properties:
    platform:
      $ref: "#/Platform"
   ...
```

Platform is simply a string (enum) that the spec re-use at multiple places. We could call this a wrapper. It could be done with an integer and a float too.

```
Platform:
  type: string
  enum:
    - Linux
    - Android
    - Windows
    - Web
  description: "The type of platform the software runs on"
  example: Android
```

If I debug my generation using `debugModels`, I can see this:

```json
{
      "baseName" : "platform",
      "complexType" : "Platform",
      "getter" : "getPlatform",
      "setter" : "setPlatform",
      "datatype" : "Platform",
      "datatypeWithEnum" : "Platform",
      "name" : "platform",
      "defaultValue" : "null",
      "defaultValueWithParam" : " = data.platform;",
      "baseType" : "Platform",
      "jsonSchema" : "{\r\n  \"$ref\" : \"#/definitions/Platform\"\r\n}",
      "exclusiveMinimum" : false,
      "exclusiveMaximum" : false,
      "hasMore" : true,
      "required" : true,
      "secondaryParam" : false,
      "hasMoreNonReadOnly" : true,
      "isPrimitiveType" : false,
      "isContainer" : false,
      "isNotContainer" : true,
      "isString" : false,
      "isInteger" : false,
      "isLong" : false,
      "isFloat" : false,
      "isDouble" : false,
      "isByteArray" : false,
      "isBinary" : false,
      "isFile" : false,
      "isBoolean" : false,
      "isDate" : false,
      "isDateTime" : false,
      "isListContainer" : false,
      "isMapContainer" : false,
      "isEnum" : false,
      "isReadOnly" : false,
      "vendorExtensions" : { },
      "hasValidation" : false,
      "isInherited" : false,
      "nameInCamelCase" : "Platform",
      "isXmlAttribute" : false,
      "isXmlWrapped" : false
    }
```

As you can see `isPrimitiveType` is considered `false`, which I think is a bug. I also think that some other fields are wrong like `baseType`, `isString`, etc... Is this something wanted and if so, what is the reason?

In my bugs I'm trying to fix, I need to detect when a property is "wrapping" a primitiveType or if you want to see it the other way, when the property is not a real `object`. That way, I would be able to prevent Bean Validation of these "fake" models.

##### Swagger-codegen version

2.3.0

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l java-play-framework -o generatedServer -DhideGenerationTimestamp=true`

**Comment by jimschubert** [comment]
In many languages, enums are compiled as integers. In Java, these are immutable objects. The primitive field you're looking at really only refers to built-in tires for many languages (int, float, string, etc).

Because you've defined a type of `Platform` as an enum, you're generating an enum object. Was the expectation that you would generate a string parameter with validation of the acceptable values?

**Comment by JFCote** [comment]
Hi @jimschubert, thanks for the clarification.

I'm not sure to understand completely your last question (my main language is french, that might explain).

To clarify: What I'm expecting is a way to know that an "object" is only a wrapper over a primitive type (int, string, float). When I did the debugModels=true, I was kind of expecting that in the structure itself, the system was knowing this in its properties (isPrimitive, baseType, etc...). Unfortunately, it seems the system is simply considering them as object which are then converted to class in the java code.

That makes sense but that don't solve my problem. In the Play Framework Generator, you can activate the u`seBeanValidation` flag which validate automatically using a bean validator every input and output of the api. In the ["fake endpoint petstore" sample, the spec returns a wrapped an integer. Something like Platform but without the enum.](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L821)

I don't generate a "validate" function in enums since there is nothing to validate so when I call "validate" in the generated controller, [it doesn't compile](https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/java-play-framework-fake-endpoints/app/controllers/FakeApiController.java#L84).

This is because, in the end, the object type of Platform is not an "object", it is String, float or int. That's why I was wondering if it's a bug. Even if it's a "model", it could be replaced by a simple inline string, float or int directly in the spec. It is only a model for the sake of reuse.

Is it more clear? :)

**Comment by JFCote** [comment]
This problem is no longer relevant and has been fixed using other techniques in the JavaPlayFramework. Closing this.
