### ISSUE TITLE
Generating client with Kotlin and Retrofit2 fails

### ISSUE THREAD

**Issue by andre-artus** [swagger-api/swagger-codegen#6368]
##### Description

I tried to generate a Retrofit2 client in Kotlin, which results in:
Exception in thread "main" java.lang.RuntimeException: unknown library: retrofit2
        at io.swagger.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:3329)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:421)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

##### Swagger-codegen version

2.3.0-SNAPSHOT

##### Swagger declaration file content or url

I don't think it's specific to input as I also tried it on [included] petstore.yaml.

##### Command line used for generation

generate  --library retrofit2  --artifact-id "[aid]" -i [path to swagger.json] -l kotlin -o [path to output directory]

##### Steps to reproduce

run it with swagger-codegen-cli.

I ran the same swagger.json without `--library retrofit2`, that worked (but obviously not correct library). Then I ran it changing `-l kotlin` to `-l java`, that produced Retrofit2 compatible code, but obviously for Java. 
So it is the combination that fails.

**Comment by jimschubert** [comment]
There is no retrofit library support for Kotlin. I believe retrofit is only supported by Java.

I think a fix here would be:

* give a better error for missing templates, possibly including all libraries available to the target generator
* open a feature request to implement retrofit library support for the Kotlin generator

**Comment by jimschubert** [comment]
@andre-artus @wing328 I've opened #6856 to provide a better message for missing libraries.  I think the retrofit library is a good addition. Should this issue be repurposed as a feature request for retrofit support?

**Comment by wing328** [comment]
@jimschubert I'll open another issue for tracking and closing this one since your PR has been merged into master.

**Comment by wing328** [comment]
I've updated the list in https://github.com/swagger-api/swagger-codegen/issues/5730 with a new item to add support for Retrofit.

**Comment by veonua** [comment]
so now I need to subscribe to general list to track the progress for retrofit? 
what was the point to add the reference to this issue and close it immediately?

**Comment by wing328** [comment]
Yes, please use https://github.com/swagger-api/swagger-codegen/issues/5730 to track the Retrofit support.

**Comment by 8secz-johndpope** [comment]
I posted an update with successful code generation on above ticket.

**Comment by wing328** [comment]
@8secz-johndpope thanks for the update but I'm no longer involved in this project. I hope others will be able to review your update.
