### ISSUE TITLE
[angular2Typescript] package.json not generated

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#6369]
##### Description

`package.json`, `typings.ts` and `tsconfig.json` files are not generated.

According to this code, those files have to be generated, hasn't it?

    //Files for building our lib
    supportingFiles.add(new SupportingFile("README.mustache", getIndexDirectory(), "README.md"));
    supportingFiles.add(new SupportingFile("package.mustache", getIndexDirectory(), "package.json"));
    supportingFiles.add(new SupportingFile("typings.mustache", getIndexDirectory(), "typings.json"));
    supportingFiles.add(new SupportingFile("tsconfig.mustache", getIndexDirectory(), "tsconfig.json"));

[This is the source code into git repository](https://github.com/swagger-api/swagger-codegen/blob/8a423d2aa55a15187ead24148bd03d14f4201db9/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java#L138).

##### Swagger-codegen version

2.3.0

##### Command line used for generation

    java -jar "D:\projects\living\references\swagger_codegen\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar" generate -i http://guest1:8080/commty/cmng/swagger.json -l typescript-angular2

**Comment by jeusdi** [comment]
Solved, you have to specify `npmName` option on config file.

**Comment by arimus** [comment]
For anyone who finds this and wants an example, this seemed to do the trick for me and generated all the relevant files needed to package / compile:

`generate -i http://localhost:5000/swagger.json -l typescript-angular -o ./codegen/ --additional-properties ngVersion=4.3,npmName=test,npmVersion=1.0.0`

**Comment by felimartina** [comment]
Is this documented anywhere?

Thanks for sharing btw

**Comment by Hamcker** [comment]
For me, the config file name was wrong, it couldn't find such file.
