### ISSUE TITLE
[python] Request: Generate an "unsafe" constructor to models that allows missing required elements

### ISSUE THREAD

**Issue by jdevera** [swagger-api/swagger-codegen#6371]
I'm testing with the master branch and the generated models are very nicely checking for all required parameters.

However, I am using the client to write tests against an API and I need to be able to create invalid requests.

If would be great if there was a way to construct the model objects without the `required` and without the range validation.

Such option could even be configurable in the generator options.

How would you go about creating such thing? Currently I see the validation happens in the property setters, which are all called in the constructor. This makes it a bit complex to have both the validated paths and the unsafe ones. However, while I want to create invalid objects in my tests, I still want to rely on the model validation for the API **responses**.

Let's discuss this, I have some capacity to work on this.

**Comment by jdevera** [comment]
How about having a `_validate=True` keyword argument to every constructor? We can store the flag in the model and then check it in all property setters to perhaps bypass the validation.

**Comment by frol** [comment]
Just for the reference, a solution was proposed here: https://github.com/swagger-api/swagger-codegen/pull/6390#issuecomment-325954400, so there is no need for changes in Swagger-Codegen.
