### ISSUE TITLE
Swagger Api Client vs Azure Server

### ISSUE THREAD

**Issue by ecolgia** [swagger-api/swagger-codegen#6378]
I've to implement a Java client for a service and the one who developed the server just tell me it is an Azure Server and gave me:
    1) The swagger
    2) a pfx file
    3) and a key to pass in the header.

    I tried to use SOAP UI and everything is working fine. I can get back the answer predicted.
    Then I started to implement my Java Client.
    I used your swagger-codegen cli client to create the client side from the swagger.
    The I wrote a main method like this without tacking in account the pfx file but just keys:

    public static void main(String[] args) {
            GetTokenInput body = new GetTokenInput();
            ApiClient apiClient = new ApiClient();
            try {
    apiClient.setApiKeyPrefix("myKeyName");
    apiClient.setApiKey("myKeyVakue");

                //apiClient.setSslCaCert(sslCaCert)
                apiClient.setDebugging(true);
                body.setFunctionID("VA");
                api.setApiClient(apiClient);

                GetTokenOutput response = api.getToken(body);
                System.out.println("------------ TOKEN STARTS ---------");
                System.out.println(response.toString());
                System.out.println("------------ TOKEN ENDS ---------");
            } catch (ApiException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }

    and I had this answer:

    { "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }

    Here they are my questions:

    1) But the key is the same use with SOAP UI then there will be maybe something missing. Do you have any idea?

    Another questions is. For what concerning the pfx file, I understood reading in internet that I can't use directly the pfx but maybe a jsk or a cert file that I suppose I have to pass to .setSslCaCert method.

    2) May you explain me which kind of file should I use? And how I can pass from pfx to the one to use?

    3) Is it true that on Azure service have to be uploaded the file I use in my application? If yes, why soap 
 UI doesn't need it?

Thanks

Gianluca

**Comment by wing328** [comment]
@ecolgia did you have a chance to check the auto-generated README.md, which contains sample code on how to access an endpoint with API key?
