### ISSUE TITLE
Objc - headers are not being preserved

### ISSUE THREAD

**Issue by hyeghiazaryan** [swagger-api/swagger-codegen#638]
Headers added to API-s by the following methods are not being passed along with the request 

```
+(SWGSampleApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
```

Cause:

Both methods call this method of SWGApiClient class

```
-(void)setHeaderValue:(NSString*) value forKey:(NSString*) forKey;
```

Which sets the header value calling this method on it's self.requestSerializer
```
- (void)setValue:(NSString *)value forHTTPHeaderField:(NSString *)field;
```

But requestSerializer is being regenerated before request and set headers are being lost (see lines 277-286 and 436-444 in SWGApiClient.m file)

**Comment by who** [comment]
:+1:  

This means that, in some cases, all headers (including conent-type, auth, etc) are being lost on every request.  This is a good bug.

**Comment by fehguy** [comment]
thanks for the report.  will get this addressed.

**Comment by webron** [comment]
This is resolved in develop_2.0. Thanks for the PR.
