### ISSUE TITLE
c# client : POST method may return a body

### ISSUE THREAD

**Issue by omatrot** [swagger-api/swagger-codegen#6388]
The POST methods generated from the Fitbit API do not retrieve the response body.

For instance:

> https://dev.fitbit.com/docs/explore/#/Activity/get_1_user___activities_date__date__json

is generated as:

`public ApiResponse<Object> v1UserActivitiesDateDateJsonGetWithHttpInfo (string date)
        {
...
           return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                                           null);
        }
`

I simply replaced **null** with  **localVarResponse.Content** to solve the problem for now:

`public ApiResponse<Object> v1UserActivitiesDateDateJsonGetWithHttpInfo (string date)
        {
...
           return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                                           localVarResponse.Content);
        }
`

I'm running swagger-codegen 2.2.3 on MacOSX installed with Homebrew.
To reproduce the problem, generate a csharp client api with the following command:

> swagger-codegen generate -i https://dev.fitbit.com/docs/explore/fitbit-web-api.swagger.json -l csharp

Related issues : #6387

**Comment by wing328** [comment]
@omatrot I'd a look at the spec and seems like that endpoint does not define a proper response so I would argue swagger codegen is doing the right thing in this case. Do you agree?

**Comment by omatrot** [comment]
I'll have to double check.
Thanks for that.

**Comment by omatrot** [comment]
I have the same problem with the PHP generated client.
The endpoint is defined as the following:
"/oauth2/token": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Get OAuth 2 access token",
                "description": "Retrieves an OAuth 2 access token.",
                **"produces": [
                    "application/json"
                ]**,

Is it not what is required to have the generator parse the response ?

**Comment by wing328** [comment]
They need to define something like https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L175-L178 (in other words, `produces` is not enough)

**Comment by omatrot** [comment]
You mean that part:
>schema:
>            $ref: '#/definitions/Pet'

??

This seems to define a custom type.
What if I want to return arbitrary JSON ?

Furthermore, the GET Apis are generated correctly with the same definition ? Am I wrong ?

**Comment by wing328** [comment]
> What if I want to return arbitrary JSON ?

https://stackoverflow.com/a/37982152/677735

**Comment by omatrot** [comment]
I'll ask the API developer. Stay tuned.

**Comment by sordina** [comment]
I think being able to get access to the response body in generated code is important regardless of what the API response definition lists. This provides an escape hatch during periods where the schema is broken, which is especially critical if your schema is being generated for you by third party libraries (such as apipie). I'd be happy if the body were available as a string.

**Comment by wing328** [comment]
@sordina currently, for every method/operation, there's a `WithHttpInfo` method generated to obtain not only the defined response (e.g. Model, string, void, etc) but also HTTP status code and header.

We can consider including the body as string in the response of the `WithHttpInfo` method. Would that meet your requirement?

**Comment by sordina** [comment]
@wing328  absolutely!
