### ISSUE TITLE
[python] Thread pool not closed or handled on client.

### ISSUE THREAD

**Issue by tuxbotix** [swagger-api/swagger-codegen#6392]
##### Description
This is a potential issue I found on python client after testing a very badly implemented app which create an API client once in a few seconds!! :stuck_out_tongue: 

The client (api_client.py) creates a ThreadPool on initialization, but it is not closed or cleared. From what I found on little-available documentation on threadPool, it has to be closed.

Suggestions:
Add close() and join() for the "destructor". Once the destructor start to close and join the threads, the system showed no problem after many hours of operations throughout few days.

ref: [https://www.codementor.io/lance/simple-parallelism-in-python-du107klle](url)

I can do a PR if this is acceptable.

```python
def __del__(self):
  self.pool.close()
  self.pool.join()
```

##### Swagger-codegen version

Spec: 2.0, Codegen: 2.3

##### Command line used for generation
python client. Nothing special!

swagger-codegen -l python

##### Steps to reproduce

Try to create client once a second or such small interval (speed up to see results quicker xD), the system will run out of threads. (bad implementations can easily show this.!)

**Comment by wing328** [comment]
@tuxbotix please submit a PR so that we can review the fix more easily.

(Note: the latest master (2.3.0) has the Python API client refactored)

**Comment by rousku** [comment]
This fix introduced another bug:
https://github.com/kubernetes-client/python/issues/411

**Comment by tuxbotix** [comment]
@rousku Interesting situation, I introduced this fix to avoid running out of threads itself when running many clients.
Anyway as I said in my pull request, do we have a better way to do this? perhaps using something other than threadpools which is barely documented !?

**Comment by wing328** [comment]
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11)

**Comment by cbornet** [comment]
Using a concurrent.futures.ThreadPoolExecutor would probably be better

**Comment by cbornet** [comment]
Creating the pool outside of the class so that the same pool is used for all Apiclient instances would also do it I guess.
