### ISSUE TITLE
[JAVA] Bug wrong group id for Feign/OpenFeign artifact in build.gradle.mustache

### ISSUE THREAD

**Issue by dgroomes** [swagger-api/swagger-codegen#6397]
##### Description

The group id of the Feign/OpenFeign artifacts is outdated at https://github.com/swagger-api/swagger-codegen/blob/b77337102a883a074ee646a57bb4673ac0933846/modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.gradle.mustache#L116. The group id should be 'io.github.openfeign'. 

##### Swagger-codegen version

I am using Swagger-codegen version 2.2.3. This issue is a regression.

##### Related issues/PRs

I traced the origination of this error to this PR https://github.com/swagger-api/swagger-codegen/pull/5114/files. Where the group id was updated correctly for the pom.mustache file but was not updated for the build.gradle.mustache file.

##### Suggest a fix/enhancement

See 'Description'.

**Comment by wing328** [comment]
@dgroomes thanks for reporting the issue. Do you mind submitting a PR to fix the issue?

**Comment by dgroomes** [comment]
@wing328 yeah I'll plan to do it

**Comment by jihlee** [comment]
@wing328 @dgroomes Added PR to #6652 to fix the issue
