### ISSUE TITLE
csharp client build.bat errors "IReadableConfiguration could not be found"

### ISSUE THREAD

**Issue by jasonl99** [swagger-api/swagger-codegen#6408]
I cannot get the csharp client to build, using either the `build.bat` file or through Visual Studio 2017 and swagger-codegen-cli 2.2.3.

Trying to isolate this as much as I can, I've put the codgen jar file, the petshop spec file,  and copied the default csharp from `modules/swagger-codegen/src/main/resources/csharp` to `./csharp` in a directory.

I then run this command

```
java -jar swagger-codegen-cli-2.2.3.jar generate -i ./petshop_spec.yml -l csharp -t ./csharp -o ./csharp_client/
```

I then `cd` into the csharp_client directory, and run the build.bat file where I get the following output (errors are at the bottom):

```
All packages listed in C:\Users\...\packages.config are already installed.
        1 file(s) copied.
        1 file(s) copied.
Microsoft (R) Visual C# Compiler version 4.7.2046.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

src\IO.Swagger\Client\Configuration.cs(24,34): error CS0246: The type or namespace name 'IReadableConfiguration' could
        not be found (are you missing a using directive or an assembly reference?)
src\IO.Swagger\Client\ApiClient.cs(101,16): error CS0246: The type or namespace name 'IReadableConfiguration' could not
        be found (are you missing a using directive or an assembly reference?)
```

The contents of the files referenced in the errors are as follows:

ApiClient.cs line

```csharp
public IReadableConfiguration Configuration { get; set; }
```

Configuration.cs

```csharp
public class Configuration : IReadableConfiguration
```

The identical errors occur with my own swagger spec file.

Ideas?

**Comment by jasonl99** [comment]
Additional note: `IReadableConfiguration.mustache` in the template directory does not appear to end up anywhere in the generated client code.  

If I look at the mustache file, there's a comment on line 8:
```csharp
    /// Represents a readable-only configuration contract.
```
That comment does not end up in any client code at all.  Conversely, comments in `Configuration.mustache`, `IApiAccessor.mustache` and `api.mustache` all end up in `IO.Swagger/Client/Configuration.cs`, `IO.Swagger/Client/IApiAccessor.cs` and `IO.Swagger/Api/DefaultApi.cs` respectively.  It seems that `IReadableConfiguration.mustache` is not generating code.

**Comment by wing328** [comment]
@jasonl99 can you please try the latest master, which has the C# client refactored?

The snapshot version can be found in https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by jasonl99** [comment]
@wing328, that worked!  Thanks a ton.
