### ISSUE TITLE
Question: is there a way to let swagger-codegen add "implements BaseModel" to a set of models?

### ISSUE THREAD

**Issue by tanis2000** [swagger-api/swagger-codegen#6414]
Hi, I've been trying to find a way to let swagger-codegen know that some of my models should implement an interface (in this specific case the language I'm using is Java). Is there such an option?
Alternatively, is there any way to pass some options all the way down to the Java generator so that I can retrieve them from within the mustache template and add the `implements BaseModel` where specified?

Thanks!

**Comment by wing328** [comment]
@tanis2000 one way is to customize the template and pass the customized template with the `-t` option. The following might help:

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-customize-the-template-to-add-headerfooter-to-the-auto-generated-code

**Comment by tanis2000** [comment]
@wing328 thanks, I've already adopted the template to add more properties to all the models. What I' unable to do is to make only some of the generated models derive from a common interface (only some of them though)

**Comment by wing328** [comment]
@tanis2000 What about using vendor extensions?

e.g. `x-implements-base-model` in the spec will result in `{{#vendorExtensions.x-implements-base-model}} ... {{/vendorExtensions.x-implements-base-model}}`

**Comment by tanis2000** [comment]
@wing328 that's brilliant! Problem partially solved. Now I'm left with a little issue.

I added the following code to my `pojo.mustache`

```
  @SerializedName("lastSync")
  private String lastSync = null;

  public {{classname}} lastSync(String lastSync) {
    this.lastSync = lastSync;
    return this;
  }

  public String getLastSync() {
    return lastSync;
  }

  public void setLastSync(String lastSync) {
    this.lastSync = lastSync;
  }

  @SerializedName("isDeleted")
  private boolean isDeleted = false;

  public {{classname}} isDeleted(boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  public boolean getIsDeleted() {
    return isDeleted;
  }

  public void setIsDeleted(boolean isDeleted) {
    this.isDeleted = isDeleted;
  }
```

That's because I need some properties that are common to all the models but they only make sense in my client's code and they shouldn't be in the services definition. 
It works fine except for those models that correspond to arrays because they do not import `SerializedName`.
I've been hunting down that import which should be `import com.google.gson.annotations.SerializedName;` but I cannot find where it's hiding. Otherwise I have those models that I always need to change by hand at each spec update.

Cheers!

**Comment by wing328** [comment]
You mean https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java#L367 ?

**Comment by tanis2000** [comment]
So that's where it's defined, but where is it used in the mustache templates? Obviously I've been searching for the full `com.google.gson.annotations.SerializedName` so I couldn't find it :-P
