### ISSUE TITLE
Jersey2 set ApiKey for all the apis

### ISSUE THREAD

**Issue by xmeng1** [swagger-api/swagger-codegen#6415]
##### Description

I try to generate the Jersey2 api and use the ApiKey to authorization the access for api. I try to set the api key in configuration like that

```java
public static ApiClient getDefaultApiClient() {
        defaultApiClient.setApiKey("my-key");
        return defaultApiClient;
}
```
but after deep in the source code, I found that every api has local string array
`String[] localVarAuthNames = new String[] {  };` and when `invokeAPI`, this local variable should be pass to the method. And in the `invokeAPI`, I found that `updateParamsForAuth` is used for update the HTTP parameter for authentication. In this method, it first to traverse all the string in the `localVarAuthNames`, So even thought I set the ApiKey, the ApiKey cannot be set to the HTTP requrest.

Does `localVarAuthNames` should be set by some annotation?  
Currrently, I just write a function to traverse all the ` private Map<String, Authentication> authentications;` in the `ApiClient`. And if the value is not nul and it type of `ApiKeyAuth`, I will set the apikey by default. The detail of code is shown as below. 

```
 private void updateParamsForAuth(List<Pair> queryParams, Map<String, String> headerParams) {
    for (Authentication authentication : authentications.values()) {
      if (authentication != null && authentication.getClass().equals(ApiKeyAuth.class)) {
        authentication.applyToParams(queryParams, headerParams);
      }
    }
  }
// add this method to the invokeAPI
```

##### Swagger-codegen version

git revision number: 025bf3aa8018aa0be2e6e7d519bdb98a9e83245e

##### Command line used for generation

```
java -jar ~/Develop/Swagger/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
    -i ${Url_remote} \
    -l java --library=jersey2 \
    -o /my-project \
    -c ./config.json
```

```
{
  "hideGenerationTimestamp":true,
  "groupId":"com.xxxxx",
  "artifactId":"xxxx",
  "artifactDescription":"xxxxx",
  "invokerPackage":"xxxxxx",
  "apiPackage":"xxxxxx",
  "modelPackage":"xxxxxxx"
}
```

##### Suggest a fix/enhancement

Currrently, I just write a function to traverse all the ` private Map<String, Authentication> authentications;` in the `ApiClient`. And if the value is not nul and it type of `ApiKeyAuth`, I will set the apikey by default. The detail of code is shown as below. 

```
 private void updateParamsForAuth(List<Pair> queryParams, Map<String, String> headerParams) {
    for (Authentication authentication : authentications.values()) {
      if (authentication != null && authentication.getClass().equals(ApiKeyAuth.class)) {
        authentication.applyToParams(queryParams, headerParams);
      }
    }
  }
// add this method to the invokeAPI
```

**Comment by wing328** [comment]
@xmeng1 even though you set the API key in the default API client, the authentication setting (api key in your case) will only be applied if the endpoint has proper authentication setting applied.

In your spec, are the endpoints correctly defined with proper authentication setting?

**Comment by mvh77** [comment]
I'm having the same issue, not using Jersey though, default okhttp. My setting is as follows:

```
{
  "apiVersion": "2.0.0",
  "swaggerVersion": "1.2",
  "basePath": "http://localhost:8088/ari",
  "authorizations": {
    "apiKey": {
      "type": "apiKey",
      "passAs": "query",
      "keyname": "api_key"
    }
  },
  "apis": [
    {
```

Still the generated code is:
```
String[] localVarAuthNames = new String[] {  };
```
How should I setup the individual endpoints so the apiKey setting is applied to requests? The [examples for v1.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#5210-authorizations-object) only talk about oauth2 for individual endpoints. Thanks!

**Comment by wing328** [comment]
Here is an example to use apiKey for endpoint authorization: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L570

**Comment by mvh77** [comment]
Well that seems to be a v2.0 example so I don't know. I'm working with a v1.2 api (actually a very old and buggy v1.1 api that I made a converter to 1.2 for). Anyway, I've managed to make it work by overriding the ApiClient#buildCall method and adding my key and value to the queryParams list before calling super.

**Comment by wing328** [comment]
@mvh77 OK. I would suggest you to upgrade the spec to 2.0.
