### ISSUE TITLE
In the html client generator, newline (\n) added in the JSON under Example data 

### ISSUE THREAD

**Issue by kvelakur** [swagger-api/swagger-codegen#642]
For example go to http://editor.swagger.io/ and export the default Uber API that is loaded as a static html page by selecting Generate Client -> html. 

In the generated html, all the JSONs under Example data look like this: 
`[ {\n  "image" : "aeiou",\n  "product_id" : "aeiou",\n  "description" : "aeiou",\n  "display_name" : "aeiou",\n  "capacity" : "aeiou"\n} ]`

The \n shouldn't appear here, and should probably a <\br> instead.

**Comment by webron** [comment]
@kvelakur - it looks like you have a potential PR here?

**Comment by kvelakur** [comment]
Yes I did:
https://github.com/swagger-api/swagger-codegen/pull/654

Removing the line fixes the Static HTML page, but I'm not sure if it affects anything else. In any case this line needs to be fixed, the second argument in the function call is not even a valid regular expression.

**Comment by wing328** [comment]
@kvelakur I believe it's fixed and I could no longer repeat the issue. Please reopen the issue if it's not the case.
