### ISSUE TITLE
[PHP] Bug generating nulls after deserialization

### ISSUE THREAD

**Issue by piotrjozwiak** [swagger-api/swagger-codegen#6420]
##### Description

Helo guys!
I am using your api to generate libraries for my clients (posting on http://generator.swagger.io/api/gen/clients/php) and I have generated this libraries in PHP.
This libs works fine - request is made, my server answers correctly, but after all I get an array with valid keys and nulled values.

For example:

`$result = $api_instance->apiGwApiKeyTransactionGetPost($api_key, $basic_data);
            var_dump($result);`
produces:

> array (size=16)
>   0 => 
>     object(Swagger\Client\Model\GetResponse)[9]
>       protected 'container' => 
>         array (size=18)
>           'result' => null
>           'status' => null
>           'error_code' => null
>           'start_time' => null
>           'payment_time' => null
>           'chargeback_time' => null
>           'channel' => null
>           'test_mode' => null
>           'amount' => null
>           'amount_paid' => null
>           'name' => null
>           'email' => null
>           'address' => null
>           'code' => null
>           'city' => null
>           'phone' => null
>           'country' => null
>           'err' => null 
>  :
>  
> and 15 duplicated keys in array

After some diging in code I have find the Serializer class which makes my output nulled
`return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\GetResponse[]', $httpHeader), $statusCode, $httpHeader];
`
(The $response here contains std object with response from api)

Can you fix this serializer to work?

##### Swagger declaration file content or url

[JSON](https://docs.tpay.com/api.json?33) code

PHP [Libs](https://generator.swagger.io/api/gen/download/fcc0c415-974a-4aa0-9b47-05b5076a84df)

You can use this code to reproduce bug:

> require_once '../autoload.php';
> 
> class test1
> {
>     public function __construct()
>     {
>         $api_instance = new Swagger\Client\Api\TransactionAPIApi();
>         $api_key = "158ae0714578f5ab76bf6c0374cb1508b98ece5d"; // string | The api key.
>         $data['title'] = 'TR-C4Y-JPHD7X';
>         $data['api_password'] = 'testtpay123';
>         $basic_data = new \Swagger\Client\Model\GetFields($data); // \Swagger\Client\Model\CheckFields | check method data
> 
>         try {
>             $result = $api_instance->apiGwApiKeyTransactionGetPost($api_key, $basic_data);
>             var_dump($result);
>         } catch (Exception $e) {
>             echo 'Exception when calling CardsAPIApi->apiCardsApiKeyCheckPost: ', $e->getMessage(), PHP_EOL;
>         }
>     }
> 
> }
> new test1();
>

**Comment by wing328** [comment]
@piotrjozwiak which version of Swagger Codegen are you using?

The latest master has the PHP API client refactored so please check it out if you've not done so.

**Comment by ackintosh** [comment]
👀

**Comment by piotrjozwiak** [comment]
I am using 2.2.3 version published here [generator.swagger.io](http://generator.swagger.io) - I do not host my own instance of codegen.
I have downloaded libs and tested again, there is still the same problem.
Will this be fixed on 2.3.0 release?

**Comment by ackintosh** [comment]
@piotrjozwiak  Please refer to the below and try generate your client code with the lastest master. 💡 

https://github.com/swagger-api/swagger-codegen#getting-started

**Comment by piotrjozwiak** [comment]
I do not want to host my own instance of generator. I am waiting for update of http://generator.swagger.io/ to 2.3.0 version.

**Comment by wing328** [comment]
@piotrjozwiak What about using the SNAPSHOT version of the latest master? https://github.com/swagger-api/swagger-codegen#compatibility
