### ISSUE TITLE
[Spring][maven-plugin] Change default generated status to NOT_IMPLEMENTED in controller

### ISSUE THREAD

**Issue by M3lkior** [swagger-api/swagger-codegen#6445]
##### Description
Code implementation after swagger generation is not immediat in certain team workflow. In my case, i generate controllers sources based on my swagger specs and my developers implements the business code later in the week / or month.

I think it could be fine generating the default implementation with HttpStatus.NOT_IMPLEMENTED:

```java
        return new ResponseEntity<...>(HttpStatus.NOT_IMPLEMENTED);
```

##### Swagger-codegen version

2.2.2

##### Suggest a fix/enhancement

I think it could be fine generating the default implementation with HttpStatus.NOT_IMPLEMENTED:

```java
        return new ResponseEntity<...>(HttpStatus.NOT_IMPLEMENTED);
```

**Comment by wing328** [comment]
Yup, I think so. We've already done something similar for Spring Cloud client: https://github.com/swagger-api/swagger-codegen/blob/adfe4b6e6c297231cbad20512809ee78a82715c8/modules/swagger-codegen/src/main/resources/JavaSpring/api.mustache#L69

cc @cbornet @ePaul

**Comment by cbornet** [comment]
I think we now have example responses generated. Should we generate with NOT IMPLEMENTED statuts code and the example body ?
