### ISSUE TITLE
[Go] Add response body when reporting error

### ISSUE THREAD

**Issue by nazieb** [swagger-api/swagger-codegen#6449]
##### Description

When the HTTP response status code is > 300, the API client treated it as an error. But the only thing that's reported in the returned error is the HTTP Response Status, eg. `500 Internal Server Error`. Example: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/go-petstore/pet_api.go#L572

I think it's better to also return the response body which usually contain the message which may explain why the error happened, so the caller can log and debug better.

Currently, we can't get the body from the `HTTP.Response` object returned from the function call, since the body is already closed there. While in previous version (2.2.x) where we still have `APIResponse` object it's possible to get the body from the `Payload` attribute.

##### Swagger-codegen version

2.3.0

##### Suggest a fix/enhancement

In [API template](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/api.mustache#L215), add something like this:

```go
if localVarHttpResponse.StatusCode >= 300 {
	body, _ := ioutil.ReadAll(localVarHttpResponse.Body)
	return {{#returnType}}successPayload, {{/returnType}}localVarHttpResponse, reportError("Status: %v, Body: %v", localVarHttpResponse.Status, body)
}
```

**Comment by wing328** [comment]
@nazieb thanks for the suggestion. Can you please file a PR with the suggested enhancement so that we can review more easily?

**Comment by antihax** [comment]
See #7192

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/7192 by @antihax has been merged into master.

@nazieb please pull the latest master to give it a try.
