### ISSUE TITLE
[Typescript-Angular2] Setting multipart/form-data will always send [object FormData] as body

### ISSUE THREAD

**Issue by SargoDarya** [swagger-api/swagger-codegen#6457]
##### Description

At the moment it is not possible to actually send multipart/form-data requests using generated code with the typescript-angular2 generator as it will always call formParams.toString() for the body contents which will always result in [object FormData] in the actual request.

##### Swagger-codegen version

v2.3.0

##### Swagger declaration file content or url

Problematic file: [swagger-codegen/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache#L185)

Problematic lines:
```mustache
let formParams = new (useForm ? FormData : URLSearchParams as any)() as {
   set(param: string, value: any): void;
};
...
{{#hasFormParams}}
    body: formParams.toString(),
{{/hasFormParams}}
```

##### Steps to reproduce

1. Create an API service which can upload files
2. Generate the API client as usual using typescript-angular2 template
3. Try to use the Service with a file
=> Request will show up with [object FormData] in the body

##### Suggest a fix/enhancement

Angulars HTTP handling of forms is actually pretty smart. I think simply changing the line to the following works.

```mustache
{{#hasFormParams}}
    body: useForm ? formParams : formParams.toString(),
{{/hasFormParams}}
```

**Comment by wing328** [comment]
@SargoDarya thanks for reporting the issue. Would you please submit a PR with the suggested fix so that we can review the fix more easily?

**Comment by macjohnny** [comment]
@SargoDarya could you have a look at https://github.com/swagger-api/swagger-codegen/pull/6574 ?

**Comment by SargoDarya** [comment]
I will give this a try.
