### ISSUE TITLE
No return statement in some of the python APIs

### ISSUE THREAD

**Issue by madhuri-rai07** [swagger-api/swagger-codegen#647]
I have generated python client code for Kubernetes and seems some of the APIs doesn't return response.
For example createPod API doesn't return any response even if the responses are defined in swagger definition.
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1beta3.json#L3879

**Comment by webron** [comment]
Which version of the codegen did you try?

**Comment by madhuri-rai07** [comment]
I used the master branch code.

**Comment by wing328** [comment]
@madhuri-rai07 please kindly do a test with the `develope_2.0` branch. If the issue persists, please try to generate Ruby/PHP code to see if it's a Python-only issue.

**Comment by webron** [comment]
@madhuri-rai07 - can you please test with develop_2.0?

**Comment by wing328** [comment]
@madhuri-rai07 we'll close this issue given that we've not heard from you.

**Comment by webron** [comment]
Closed for lack of activity.

**Comment by madhuri-rai07** [comment]
I am unable to generate code due to this issue https://github.com/swagger-api/swagger-codegen/issues/877

**Comment by webron** [comment]
Fine. ;)

**Comment by fehguy** [comment]
Is this still an issue?  Please reopen if so.
