### ISSUE TITLE
[Spring] Server stub generation with Java 8, delegatePattern and interfaceOnly 

### ISSUE THREAD

**Issue by david-noel** [swagger-api/swagger-codegen#6471]
##### Description

I have a new feature I would like to see added to the server stub generation.  When the following configOptions are set

- java8
- delegatePattern
- interfaceOnly

I would like the generated code to create an interface that has a default method that delegates to a non-default method on the same interface.  Sample default and non-default methods from the PetApi would look as follows..

```java
@ApiOperation(value = "Add a new pet to the store", notes = "", response = Void.class, authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:pets", description = "modify pets in your account"),
            @AuthorizationScope(scope = "read:pets", description = "read your pets")
            })
    }, tags={ "pet", })
    @ApiResponses(value = {
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/pet",
        produces = { "application/xml", "application/json" },
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> addPet(@ApiParam(value = "Pet object that needs to be added to the store" ,required=true )  @Valid @RequestBody Pet body, @RequestHeader(value = "Accept", required = false) String accept) throws Exception {

        return addPetPOST(body);
    }

    ResponseEntity<Void> addPetPOST(Pet body);
```

##### Swagger-codegen version

2.3.0-SNAPSHOT
##### Swagger declaration file content or url

N/A
##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Suggest a fix/enhancement

feature is added to master branch here
https://github.com/david-noel/swagger-codegen

**Comment by wing328** [comment]
@david-noel thanks for the suggestion. Please file a PR so that we can review the change more easily.
