### ISSUE TITLE
[All Java Generators] Diamond operators for java 8 back to < Java 1.7

### ISSUE THREAD

**Issue by JFCote** [swagger-api/swagger-codegen#6472]
##### Description

I found that a change I had made some time ago has disappeared. It was a simple change to remove warnings since in Java 8 we don't need to provide the type in the diamond.

For example:

In java 1.7
`List<SomeObject> myVar = new ArrayList<SomeObject>();`

In java 1.8
`List<SomeObject> myVar = new ArrayList<>();`

The changes has been erased in commit `506c58e` by user @daveish 

I can submit a new PR to fix this but I would like to know what was the reason for the regression. Was this creating bugs in other generator? 

It is related to https://github.com/swagger-api/swagger-codegen/issues/2588 and https://github.com/swagger-api/swagger-codegen/pull/6373

My changes were removed in the `AbstractJavaCodegen.java` file: https://github.com/swagger-api/swagger-codegen/pull/6373/files#diff-563d4b5a0d57e0184af3b98607bbb4a5L642

So, @wing328 and @daveish , can you please check and confirm that I can submit my change back?

Thanks!

##### Swagger-codegen version

Master

**Comment by daveish** [comment]
See this build: https://circleci.com/gh/swagger-api/swagger-codegen/1402

If you change it back now, it would not succeed, I guess?

Regards
David

**Comment by JFCote** [comment]
Hi @daveish ,

My improvement was merged on August 11 and everything build ok except for the travis-ci which have problem sometimes: https://github.com/swagger-api/swagger-codegen/pull/6275

My guest is that your generated code (sample) rely on a old java version (< 1.8) so you should specify `java8=false` in you `.sh` file. By default, I think that most generators are using java 8 so it's set to true.

I don't even know what is jax-rs or what it does, but I'm pretty sure my code was only affecting generators that set "java8=true" or where java8 was set to true by default.

Can you please validate this in your code? I will do a new PR with my old code so we can validate this.

Thanks

**Comment by JFCote** [comment]
Here is my PR: https://github.com/swagger-api/swagger-codegen/pull/6480
Please check if your generator works fine with the change. If it doesn't, we will work from there.
Thanks!

**Comment by JFCote** [comment]
Closing this since it has been fixed in https://github.com/swagger-api/swagger-codegen/pull/6480
