### ISSUE TITLE
[PHP] Bug with 'format: date' when using --model-name-prefix

### ISSUE THREAD

**Issue by SunMar** [swagger-api/swagger-codegen#6474]
##### Description

When an object property in the Swagger definition is defined as a **date** and swagger-codegen is called with ```--model-name-prefix``` it **incorrectly maps** the object to ```<Prefix>Date``` instead of a ```\DateTime``` object.

##### Swagger-codegen version

I am using swagger-codegen-cli-2.2.3.

##### Swagger declaration file content

```yaml
---
swagger: '2.0'

info:
  title: 'Test Codegen Date'
  version: '1.0'
  
paths:
  '/foo':
    get:
      responses:
        200:
          description: 'Success'
          schema:
            type: object
            properties:
              some_date:
                type: string
                format: 'date'
              some_datetime:
                type: string
                format: 'date-time'
```

##### Command line used for generation

```java -jar swagger-codegen-cli-2.2.3.jar generate -i test.yaml -l php --model-name-prefix Foo```

##### Steps to reproduce

1. Save the above example YAML as ```test.yaml```.
2. Run swagger-codegen without a prefix: ```swagger-codegen generate -i test.yaml -l php```.
3. Open the generated file ```SwaggerClient-php/lib/Model/InlineResponse200.php```.
4. See on line 57 that ```some_date``` from ```test.yaml``` is correctly mapped to ```\DateTime```.
5. See on line 58 that ```some_datetime``` from ```test.yaml``` is correctly mapped to ```\DateTime```.
6. Run swagger-codegen with a prefix: ```swagger-codegen generate -i test.yaml -l php --model-name-prefix Foo```.
7. Open the (prefixed) generated file ```SwaggerClient-php/lib/Model/FooInlineResponse200.php```.
8. See on line 57 that ```some_date``` is **incorrectly** mapped to ```FooDate``` where it should be ```\DateTime```.
9. See on line 58 that ```some_datetime``` is **correctly** mapped to ```\DateTime``` even when using a prefix.

##### Related issues/PRs

Issue #4430 looks similar but it is regarding Java generated code, I haven't been able to find a similar issue for PHP.

##### Suggest a fix/enhancement

Unfortunately I was not able to find where in the code this is managed, but since it works correctly for ```format: 'date-time'``` it could be that it's an easy fix once the difference in handling prefixes between ```format: 'date-time'``` and ```format: 'date'``` is identified.

**Comment by ackintosh** [comment]
I can repeat the issue also in master branch. Let me check it out. 👀

**Comment by SunMar** [comment]
Thank you! :)

**Comment by wing328** [comment]
@SunMar the fix by @ackintosh has been merged into master. Please pull the latest master to give it a try.

**Comment by SunMar** [comment]
I can confirm that for my test case this works now with the latest snapshot. Thank you! :)

**Comment by SunMar** [comment]
Hmm, a different thing I just noticed now is that the way this currently works you can't use a response value directly as a parameter in your next request. This is because a `\DateTime` will always get formatted to `\DateTime::ATOM` in `ObjectSerializer->toString()` which is used by other functions like `toPathValue()` and `toQueryValue()`. If the parameter is a `format: date-time` that is fine, but if it is a `format: date` it will result in bad data being sent.

Perhaps (though maybe I should open a different issue for that) `format: date` should not be a `\DateTime` at all and be just a `string` (regardless of whether `--model-name-prefix` is used), or either `DefaultApi` or `ObjectSerializer` should differentiate between a `date` and a `date-time` and apply the proper formatting in `toString`.
