### ISSUE TITLE
[Python] models implement __eq__ without __hash__

### ISSUE THREAD

**Issue by calbach** [swagger-api/swagger-codegen#6475]
##### Description

The base model does not implement a hash function, but it does implement __eq__. This is illegal according to: https://docs.python.org/3/reference/datamodel.html#object.__hash__

The concrete side effect of this is that I cannot use swagger generated Python models in Set comparisons; models that are equal do not necessarily have the same hash.

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

1. Generate any swagger model for Python.
2. 
```
> Model() == Model()
True

> set([Model()]) == set([Model()])
False
```

**Comment by calbach** [comment]
Fix: implement a hash function on base model.

**Comment by cbornet** [comment]
Would you do a PR ? Does the python client also have the issue ?

**Comment by wing328** [comment]
We can probably reuse the model-related mustache templates from Python API client.

**Comment by calbach** [comment]
I tried generating `-l python` as well (I assume that's the python client) and the models have the same issue. I don't have time right now to make a PR, possibly next week.

**Comment by wing328** [comment]
@calbach I've submitted #6555 to add `__hash__`. Please review when you've time.

**Comment by mbohlool** [comment]
> The base model does not implement a hash function, but it does implement eq. This is illegal according to: https://docs.python.org/3/reference/datamodel.html#object.__hash__

I don't think anywhere in the doc it said they are illegal. Can you point to the exact phrase? As far as I can tell, this implies that the model is not hashable.

The generated model here is mutable so it cannot be hashable according to the same document:

> If a class defines mutable objects and implements an __eq__() method, it should not implement __hash__(), since the implementation of hashable collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket).

If you want to use these models as a key in a set or map, the easiest way is to convert them to string (serialize them) and use the string version as key.

**Comment by mbohlool** [comment]
Also about your example:

> ```
> > Model() == Model()
> True
> 
> > set([Model()]) == set([Model()])
> False
> ```

Which model did you try this on? I've tried one simple generated model and I get TypeError for the second command (as I expected to get because Model is not hashable)

**Comment by mbohlool** [comment]
I would suggest we explicitly set `__hash__` to None in models as, at least in python 2.7, the model is considered hashable while it is not (I guess, based on documentation, that is not an issue in python 3 but won't hurt explicitly set that).

**Comment by calbach** [comment]
@mbohlool I was referring to the fact that `__eq__` may return `true` for two objects, while `__hash__` returns different values. Though you're right that the docs claim you can have an `__eq__` without a `__hash__` (and supposedly `__hash__` will magically be set to `None`), sounds like a python3 thing but I'm not sure.

Good point about immutable - I missed that in the docs. Sorry to mislead on the solution.

Setting to `None` sounds like it would work here. Not as useful as having a hashable model but would have made my invalid usage in a hashable collection immediately obvious.
