### ISSUE TITLE
Pojo to ignore null value fields

### ISSUE THREAD

**Issue by dougbacelar** [swagger-api/swagger-codegen#6488]
#### Description
I have an issue where I need the pojo to **ignore null value fields**.

The same issue is described by this guy [here](https://stackoverflow.com/questions/45031264/swagger-codegen-ignore-null-fields-for-pojo-classes)

I was wondering if it is possible to make this work(some kind of setting or parameter), without having to edit the swagger-codegen code, like the guy above did.

If it is not possible, shouldn't this be the default behaviour? Shouldn't the pojo ignore null value fields by default?

Guess I would expect `@JsonInclude(JsonInclude.Include.NON_NULL)` to be populated on the pojo by default, do I have the wrong idea?

Not sure if it is the right file, but I checked [pojo.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache) and it doesn't seem to have anything doing that.

#### Swagger-codegen version

2.3.0

#### Related issues/PRs
I found this issue but I am not sure if it is related:
https://github.com/swagger-api/swagger-codegen/issues/1413

#### Ps
I am new to swagger-codegen so I apologize if this does not make sense.

I solved my problem for the time being by adding `spring.jackson.serialization-inclusion=non_null`, but I would rather have a class-level solution, instead of project-level.

**Comment by mbracero** [comment]
+1

**Comment by apurvjain17** [comment]
+1

**Comment by ManuDevelopia** [comment]
+1

**Comment by pleali** [comment]
+1

**Comment by gserracalahorra** [comment]
+1

**Comment by Petronious** [comment]
+1

**Comment by anshchauhan** [comment]
+1

**Comment by sendhilcoep** [comment]
+1

**Comment by LuGaXu** [comment]
+1

**Comment by gracekarina** [comment]
PR’s de NotNull option:
Master Branch:
swagger-api/swagger-codegen#10269
v3 codegen-generators:
swagger-api/swagger-codegen-generators#690
v3 codegen:
swagger-api/swagger-codegen#10268
