### ISSUE TITLE
No content to map due to end of input

### ISSUE THREAD

**Issue by michael-shaw** [swagger-api/swagger-codegen#650]
Hi,

I am trying to use the latest version with a REST API that uses swagger V1.0

When I attempt to create python code I get "com.fasterxml,jackson.databind.JsonMappingException: No content to map due to end of input

If I run with verbose on I see:

{
    "swagger": "2.0",
    "info": {
        "version": "1.0
    }
    ...
}

Is the generator using swagger version 2.0 or am I missing something?

Thanks,

Michael

**Comment by webron** [comment]
The generator converts anything given to it to 2.0 and uses that. Is the Swagger definition you use public?

**Comment by michael-shaw** [comment]
Hi Webron, 

No its private unfortunately. Is there something you need to see?

Thanks,

Mike

**Comment by webron** [comment]
It would be impossible to debug that without the actual definition. Can you share it in private?

**Comment by michael-shaw** [comment]
I have obscured my data this is roughly what my REST API shows with the endpoints and url placeholders:

So if I go to the endpoint http://localhost:1234/api-docs in my browser I get the following

{
	"apiVersion": "1.0",
	"swaggerVersion": "1.0",
	"basePath": "http://localhost:1234/",
	"apis": [{
		"path": "/api-docs/endpoint-1"
	},
	{
		"path": "/api-docs/endpoint-2"
	},
	{
		"path": "/api-docs/endpoint-3"
	},
	{
		"path": "/api-docs/endpoint-4"
	},
	{
		"path": "/api-docs/endpoint-5"
	},
	{
		"path": "/api-docs/endpoint-6"
	},
	{
		"path": "/api-docs/endpoint-7"
	},
	{
		"path": "/api-docs/endpoint-8"
	},
	{
		"path": "/api-docs/endpoint-9"
	},
	{
		"path": "/api-docs/endpoint-10"
	},
	{
		"path": "/api-docs/api-docs"
	}]
}

Going to http://localhost:1234/api-docs/endpoint-1 gives me (and so on for all the other endpoints):

{
	"apiVersion": "1.0",
	"swaggerVersion": "1.0",
	"resourcePath": "/endpoint-1",
	"models": {
		
	},
	"apis": [{
		"path": "/a",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/b",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/c",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/d",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/e",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/f",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/g",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	},
	{
		"path": "/h",
		"description": "",
		"operations": [{
			"httpMethod": "GET",
			"summary": "invoke",
			"notes": "",
			"deprecated": false,
			"responseClass": "any",
			"nickname": "invoke"
		}]
	}]
}

Is this correct? (I am using a rest api another person wrote and need to generate a python client from it, I have been told the api-docs was generated using swagger-mvc)

Thanks,

Michael

**Comment by webron** [comment]
This is going to be difficult. The Swagger version you're using is very old (I mean, very very very old), and although it is supported to an extent, these kind of issues are to be expected. With the conversion to 2.0, something definitely goes wrong, but it's impossible to tell without the exact input.

Are you able to upgrade the version of swagger-springmc? That would make your life easier (at least in this aspect).

**Comment by webron** [comment]
@michael-shaw - any updates?

**Comment by wing328** [comment]
@michael-shaw we're closing this as we don't see further update from you.
