### ISSUE TITLE
HTML output exception: preprocessSwagger(StaticHtmlGenerator.java:186)

### ISSUE THREAD

**Issue by eric-jahn** [swagger-api/swagger-codegen#6506]
##### Description
When trying to generate html from either valid swagger 2 yaml or json, I get the following exception pasted below.  I looked up the code line 186 (it's the "for" loop): 

public void preprocessSwagger(Swagger swagger) {
        Info info = swagger.getInfo();
        info.setDescription(toHtml(info.getDescription()));
        info.setTitle(toHtml(info.getTitle()));
        Map<String, Model> models = swagger.getDefinitions();
        for (Model model : models.values()) {
            model.setDescription(toHtml(model.getDescription()));
            model.setTitle(toHtml(model.getTitle()));
        }
    }

But, my swagger has a title and a description.  

[main] INFO io.swagger.parser.Swagger20Parser - reading from ./api.oas.2.0.yaml
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.codegen.languages.StaticHtmlGenerator.preprocessSwagger(StaticHtmlGenerator.java:186)
	at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:134)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:687)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

##### Swagger-codegen version
2.2.3 installed using linux homebrew today

##### Swagger declaration file content or url

The yaml and json are online here:[https://github.com/hmis-api/user-service-api/blob/master/api-markup/api.oas.2.0.json](https://github.com/hmis-api/user-service-api/blob/master/api-markup/api.oas.2.0.json) and here: [https://github.com/hmis-api/user-service-api/blob/master/api-markup/api.oas.2.0.yaml](https://github.com/hmis-api/user-service-api/blob/master/api-markup/api.oas.2.0.yaml) .

##### Command line used for generation

/home/eric/.linuxbrew/bin/swagger-codegen generate -i ./api.oas.2.0.yaml -l html -o /home/eric/git/user-service-api/api-markup/

##### Steps to reproduce

run command

##### Related issues/PRs

no

##### Suggest a fix/enhancement
parsing the title and description should even allow a null

**Comment by wing328** [comment]
@eric-jahn thanks for reporting the issue. May I know if you've time to contribute a PR with better null check?

**Comment by eric-jahn** [comment]
Yes, what would you like me to run and send exactly?

**Comment by eric-jahn** [comment]
Yes, but it may take a little time.  I've added it to my to-do list.

**Comment by francisbrito** [comment]
To anyone looking for a quick workaround: create a `definitions` section. Should work after that.

**Comment by kumardevendra26** [comment]
Hi @wing328 ,

I am facing the same issue while doing HTML output. Are u able to find any workaround?
Even after adding definitions section also still it shows the same error logs:

> Exception in thread "main" java.lang.NullPointerException
        at io.swagger.codegen.languages.StaticHtmlGenerator.preprocessSwagger(StaticHtmlGenerator.java:186)
        at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:171)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:737)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

Please try to help me out from this.

Thanks in advance

**Comment by wing328** [comment]
@kumardevendra26 Thanks for tagging me but I'm no longer involved in this project. I hope others will be able to help you out. Good luck.

**Comment by frantuma** [comment]
fixed in #9615
