### ISSUE TITLE
[Question] Body (model) parameter should be required?

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#653]
In the Petstore example, the operation `addPet` has a `body` parameter, which refers to the `Pet` model: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L43

The body field is marked as optional (required=false).

My questions is that should the body field for this particular example set to required? 

Currently the ruby code looks like this: `add_pet(:body => pet)`

Ideally it should look like `add_pet(pet)`

**Comment by webron** [comment]
It should probably be required in this specific use case. Please open an issue on swagger-core for that and we'll fix it.

**Comment by wing328** [comment]
Opened swagger-api/swagger-core#990
