### ISSUE TITLE
[Ts-angular (4)]The request with consume x-www-form-urlencoded and formParam not work

### ISSUE THREAD

**Issue by xmeng1** [swagger-api/swagger-codegen#6536]
##### Description

According to my research, the when changing the name of typescript-angular from `api.mustache` to `api.service.mustache`. there is one statement missing: 
```
headers.set('Content-Type', 'application/x-www-form-urlencoded');
```
It means when there is formParams in the request, we need to add this parameter in the header. But the new version change to:

```
{{#headerParams}}
        {{#isListContainer}}
        if ({{paramName}}) {
            headers.set('{{baseName}}', {{paramName}}.join(COLLECTION_FORMATS['{{collectionFormat}}']));
        }
        {{/isListContainer}}
        {{^isListContainer}}
        if ({{paramName}} !== undefined && {{paramName}} !== null) {
            headers.set('{{baseName}}', String({{paramName}}));
        }
        {{/isListContainer}}

{{/headerParams}}
```
I can understand, and according to my test, the statement of `headers.set('Content-Type', 'application/x-www-form-urlencoded');` will not generated to lead the error for request (**415 Unsupported Media Type)**.  By the way, I paste the code of jersey2 code:

```
@POST
@Path("/config")
@Consumes({"application/x-www-form-urlencoded"})
@Produces({MediaType.APPLICATION_JSON})
@ApiOperation(value = "Configure server", notes = "Config server")
    public Result configLdapServer(
            @ApiParam(value = "key1", required = true) @FormParam("key1") final String key1,
            @ApiParam(value = "key2", required = true) @FormParam("key2") final String key2,) final String configure) {}
```
@Vrolijkx @wing328 

##### Swagger-codegen version
the latest master branch 
ae6d34d480627f9d39c5048080a138cedc1898f1

##### Suggest a fix/enhancement
add the code in the `api.service.mustache` in function `public {{nickname}}WithHttpInfo`
```
{{#hasFormParams}}
        headers.set('Content-Type', 'application/x-www-form-urlencoded');
{{/hasFormParams}}
```
https://github.com/swagger-api/swagger-codegen/compare/master...xmeng1:feature/angular-form-fix

**Comment by wing328** [comment]
@xmeng1 that's one way to do it. I think a better solution is what we discussed in https://github.com/swagger-api/swagger-codegen/issues/6006#issuecomment-314462155

**Comment by wing328** [comment]
@xmeng1 the fix has been merged into master. Please pull the latest to give it a try.
