### ISSUE TITLE
[JAVA] Retrofit2 Observable<Void> should be Observable<Response<Void>>

### ISSUE THREAD

**Issue by zkdzegede** [swagger-api/swagger-codegen#6553]
##### Description

API calls that have no response content causes a null pointer in retrofit.

```
Null is not a valid element
```

This is currently what is produced:
```
  @POST("logout")
  Observable<Void> logout();
```

This causes the: Observable onNext to never be called

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```yaml
  /logout:
    post:
      operationId: logout
      responses:
        200:
          description: success
        401:
          description: 401
```

##### Command line used for generation

```
{
  "library": "retrofit2",
  "groupId": "com.test",
  "artifactVersion":"0.0.2",
  "invokerPackage": "com.test",
  "modelPackage": "com.test.model",
  "apiPackage": "com.test.api",
  "useRxJava2": true,
  "hideGenerationTimestamp": true
}
```

swagger-codegen generate -i doc/api/definitions/test.yaml -c doc/api/config/test.json -l java -o libs/api/test

Using:
Kotlin, Java, Retrofit2

##### Steps to reproduce

1. generate the api 
2. subscribe to api.logout()

##### Related issues/PRs

---

##### Suggest a fix/enhancement

Swagger-codgen produces ```Observable<Void>``` when it should produce ```Observable<Response<Void>>```

I found the solution here: https://stackoverflow.com/questions/41914037/rxjava2-retrofit2-handling-null-for-204-put-and-delete-requests

**Comment by zkdzegede** [comment]
I tested by manually overwriting with Observable<Response<Void>> and everything works as expected.

**Comment by jschoedt** [comment]
I think it would be more clean to use [Completable](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Completable.html) as the return type although Response also works.

**Comment by zkdzegede** [comment]
@wing328   Any information on what swagger.yml response would lead to a Completable being generated?

Or is this not supported?

in RxJava2 Observable<Void> is an error but the swagger-codegen generates this...

**Comment by wing328** [comment]
@zkdzegede sorry for late reply on this. Please kindly try the latest stable release v2.3.0. If it's still an issue, we will look into it.

**Comment by zkdzegede** [comment]
It seems like this version is not in brew...

**Comment by zkdzegede** [comment]
I just confirmed that this still happens in v2.3.0
@wing328

**Comment by wing328** [comment]
cc @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet

**Comment by wingsofovnia** [comment]
I confirm this still happens in v2.3.0 too. It's a really big problem because typical DELETE or any other endpoints that return noting don't work. 

We can realy on the following check in `io.swagger.codegen.languages.JavaClientCodegen`:
```
if (operation.returnType == null) {
   operation.returnType = "Void";
}
``` 
to set `Completable` instead of `Observable<Void>` as @jschoedt proposed.

**Comment by cbornet** [comment]
The problem is that with Completable you lose response headers (typically the location header in a 201 created op)

**Comment by zkdzegede** [comment]
Even if temporary it seems better than the current situation which is an Error since RxJava Observables cannot contain Void.

I think Flowables can so would it be reasonable to change it to Flowable<Void> ?  
I may be mistaken of course.

**Comment by wingsofovnia** [comment]
> The problem is that with Completable you lose response headers (typically the location header in a 201 created op) @cbornet
It's the problem of all current RxJava2 endpoints, isn't it? For example, having `Observable<Order>` you can't fetch any HTTP related metadata. I think here we should fix ASAP and that think about it.

**Comment by wingsofovnia** [comment]
@zkdzegede meanwhile the #7397 is under review, you can use fixed version with jitpack: https://jitpack.io/#wingsofovnia/swagger-codegen/642c0566de

**Comment by cbornet** [comment]
> It's the problem of all current RxJava2 endpoints, isn't it? For example, having Observable<Order> you can't fetch any HTTP related metadata. I think here we should fix it ASAP and that think about it.

Indeed, the correct return type should be `Single<Response<Void>>`

**Comment by cbornet** [comment]
> I would say Completable even is better than Single, there is no fun having "Void" returned, we just need a confirmation that such action is ok or failed.

With `Single<Response<Void>>` you have response headers, so that's better

**Comment by zkdzegede** [comment]
@wing328  What version can I find this on?

**Comment by zkdzegede** [comment]
@wingsofovnia  Thank you for your help 💯

**Comment by wing328** [comment]
@wing328 the latest master has the fix. You can pull the build the JAR locally or use the SNAPSHOT version as mentioned in the README.
