### ISSUE TITLE
petstore server does not update pet data for updatePetWithForm

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-codegen#656]
It seems the petstore server does not make any changes for pet at all.

Steps to reproduce the issue:
1. create a pet and use `getPetById` to get the current pet data (e.g. via [Swagger UI](http://petstore.swagger.io/) with pet id: 1429180158721)
2. use `updatePetWithForm` or `updatePet` to update the pet's name and status to new values
3. use `getPetById` to get the data again, which is not updated

It's better to make it work so that add test cases for them in codegen (the current test cases in petstore java then can be changed to reflect the actual changes).

**Comment by fehguy** [comment]
Are you sure?  The java & objective c tests mutate the pets for testing purposes.

**Comment by xhh** [comment]
@fehguy yes, I'm sure. As you can see in the java test:
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/src/test/java/io/swagger/petstore/test/PetApiTest.java#L97
it does not compare names between "frank" and "furt", which actually proves that the name is not changed at all.
The [updatePet test](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/src/test/java/io/swagger/petstore/test/PetApiTest.java#L34) does not compare name changes either.

**Comment by wing328** [comment]
I did some quick tests with swagger ui. The following works for me

addPet (post)
getPet (get)
updatePet (post model)

However, updatePetWithForm does not work for me even though it returns 200

**Comment by xhh** [comment]
I confirmed that `updatePet` works well. Only `updatePetWithForm` has issue.

**Comment by webron** [comment]
@xhh - to clarify, does the *online pet store server* not update? The generated server (which would make sense)? Or does the client not execute the operation properly?

**Comment by xhh** [comment]
@webron it's the server that has issue, the client sends the correct data but the server does not update the data in the database

**Comment by webron** [comment]
@xhh - can you open the issue on [swagger-core](https://github.com/swagger-api/swagger-core/) instead then? That's the project containing the online pet store. If you want to go over the logic of it, the specific sample is this one - https://github.com/swagger-api/swagger-core/tree/master/samples/java-jaxrs.

**Comment by xhh** [comment]
done
