### ISSUE TITLE
[Typescript-Angular]CodegenOperation not getting correct isRestfulXXX properties

### ISSUE THREAD

**Issue by Coke25** [swagger-api/swagger-codegen#6560]
##### Description
    I'm trying to generate files by creating custom templates and updating TypeScriptAngularClientCodegen.java
    On my custom template mustache file, I have code like:
    {{#operations}}{{#operation}}
    {{#isRestfulCreate}}Create{{/isRestfulCreate}}
    {{#isRestfulUpdate}}Update{{/isRestfulUpdate}}
    {{#isRestfulDestroy}}Delete{{/isRestfulDestroy}}
    {{#isRestfulShow}}Show{{/isRestfulShow}}
    {{#isRestfulIndex}}Index{{/isRestfulIndex}}
    {{/operation}}
    {{/operations}}
    And this is used as apiTemplateFile:
            apiTemplateFiles.put("myCustomTemplate.mustache",".component.ts");
    I'm using http://petstore.swagger.io/v2/swagger.json PetApi as my spec.
    I only got "Create" generated.
    And by debugging operations, some of the operations don't have correct properties
    i.e. getPetById or deletePet have below properties
      "isRestfulIndex" : false,
              "isRestfulShow" : false,
              "isRestfulCreate" : false,
              "isRestfulUpdate" : false,
              "isRestfulDestroy" : false,
              "isRestful" : false

            
 ##### Swagger-codegen version
    2.2.3

 ##### Swagger declaration file content or url
    http://petstore.swagger.io/v2/swagger.json

**Comment by wing328** [comment]
@Coke25  Have you tried using `debugOperations` and `debugModels` to troubleshoot?

https://github.com/swagger-api/swagger-codegen/wiki/Mustache-Template-Variables

**Comment by fiveanddone** [comment]
I noticed that [isRestfulIndex](https://github.com/swagger-api/swagger-codegen/blob/3c7505670ba35e2bc42411d8870d3b100de3d95e/modules/swagger-codegen/src/main/java/io/swagger/codegen/CodegenOperation.java#L114) is using `"GET".equals(httpMethod)`.  Shouldn't it be `"GET". equalsIgnoreCase(httpMethod)` like the rest of them?

I'm able to render all of them except that one.

**Comment by wing328** [comment]
@fiveanddone ok. May I know if you have time to file a PR so that we can review the fix more easily?

**Comment by fiveanddone** [comment]
@wing328 Just created the request...

https://github.com/swagger-api/swagger-codegen/pull/7352

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/7352 has been merged into 2.4.0

Thanks for the fix 👍
