### ISSUE TITLE
[typescript-angular] Invalid regular expression error

### ISSUE THREAD

**Issue by kimamula** [swagger-api/swagger-codegen#6566]
##### Description

The code generated from the following template results in a runtime error, `Invalid regular expression: /(?i)^(application/json|[^;/ 	]+/[^;/ 	]+[+]json)[ 	]*(;.*)?$/: Invalid group`

https://github.com/swagger-api/swagger-codegen/blob/d2b91073e1fc499fea67141ff4c17740d25f8e83/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache#L82

##### Swagger-codegen version

Master branch (2.3.0)

##### Steps to reproduce

Paste the regular expression in Chrome Developer console, and Chrome raises the syntax error.

**Comment by taxpon** [comment]
@wing328 I think we need to add some basic tests for angular and run them on CI in order to avoid this kind of bugs. What do you say?

**Comment by wing328** [comment]
@wing328 definitely. It's better to rely on CI to catch similar issue moving forward.

**Comment by wing328** [comment]
Btw, `npm run build` didn't catch this issue so we need to write some integration tests similar to what we've done for TS Fetch: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-fetch

**Comment by wing328** [comment]
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by mattrc** [comment]
+1

**Comment by gimre** [comment]
+1 - also worth mentioning that ```typescript-angular``` is still using the old and about-to-be-deprecated ```HttpModule``` instead of ```HttpClientModule```

**Comment by kenisteward** [comment]
There is a PR to use the new one by default and optionally use the old one

**Comment by wing328** [comment]
@kimamula the issue has been fixed by #6584. Please pull the latest master to give it a try.
