### ISSUE TITLE
[typescript-angular2] use new HttpClient from '@angular/common/http' instead of old Http

### ISSUE THREAD

**Issue by krizic** [swagger-api/swagger-codegen#6568]
##### Description

The template generates services which use old Http class. Please use latest (available since angular@4.3.0) HttpClient from `'@angular/common/http'` which is necessary for new interceptors suppot

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url
modules/swagger-codegen/src/main/resources/typescript-angular2/api.service.mustache

##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -i swagger.json -l typescript-angular -o out/`

##### Suggest a fix/enhancement

`import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';`
...and refactor the rest accordingly

**Comment by taxpon** [comment]
The feature will be merged soon. See #6295

**Comment by macjohnny** [comment]
#6295 was merged, so this issue could be closed
