### ISSUE TITLE
[Swift4] generate client error (CodableHelper.swift)

### ISSUE THREAD

**Issue by riceman2** [swagger-api/swagger-codegen#6576]
##### Description
When outputting a model that was created in Swagger Editor ,
CodableHelper.swift build error
"Type 'JSONDecoder.DataDecodingStrategy' has no member 'base64Decode'"
I think there is a difference from the information of github
https://github.com/swagger-api/swagger-codegen/blob/8067612e06172942c5d661f0988bb866492d1cab/samples/client/petstore/swift4/default/PetstoreClient/Classes/Swaggers/CodableHelper.swift

It happens in both the old version and the latest version Swagger Editor

##### Steps to reproduce
Use SwaggerEditor  -> Generate Client -> swift4

**Comment by riceman2** [comment]
I download SNAPSHOT version.
It is bug fixed.

**Comment by trein** [comment]
Thanks for fixing the bug. For historical reasons, can you provide more information on the version this fix will be release?

**Comment by riceman2** [comment]
Im sorry, I don't fixed a bug.
I download new SNAPSHOT codegen-cli.
Link it below
https://github.com/swagger-api/swagger-codegen/issues/6589
I use codegen-cli 2.3.0 or 3.0.0 latest version.

Are you okay with this?

**Comment by trein** [comment]
@riceman2 Oh, I see! My mistake. It seems `CodableHelper.siwft` has been fixed in master. However, the Homebrew cli that I have does not have it. I will just wait for the next release. I'm overriding the template right now. Thanks for the info though.
