### ISSUE TITLE
[nodejs] too complex description field in swagger specification fires an error with npm

### ISSUE THREAD

**Issue by Cooker-Monster** [swagger-api/swagger-codegen#658]
Hi, 
__description__ field in an API Swagger spec could be very useful during browsing but if the content is __too complex__ (I.E GFM syntax), an error occurs during "__npm install__" or elsewhere after.
this is already the case with petstore sample ;-)
Maybe for code generation the simple way to fix this is to replace description field content with title content, after all, the content of description is not so useful inside generated code.

**Comment by wing328** [comment]
@Cooker-Monster can you provide a spec for reproducing the issue?

**Comment by Cooker-Monster** [comment]
@wing328 sorry for the delay. Does this query still relevant ?

**Comment by wing328** [comment]
@Cooker-Monster please pull the latest master and let us know if you're still seeing the same issue.

Closing it for now and will reopen if needed.
