### ISSUE TITLE
[Javascript] Using the --template-dir option doesn't seem to do anything

### ISSUE THREAD

**Issue by mpoiriert** [swagger-api/swagger-codegen#6586]
##### Description

I am trying to use the Javascript language with the option --template-dir and it's not working.
If I am setting a invalid template directory it does throw a error so I know the path is good. I am changing
a file in the directory (I copy pasted the content of the Javascript language from the master branch) and it's not doing anything.

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

Not related to that

##### Command line used for generation

java -jar ../../swagger-codegen-cli.jar generate --template-dir ../swagger-code-generator/templates/javascript -i http://localhost:3000/explorer/swagger.json -l javascript -o . -DusePromises=true

##### Steps to reproduce

Set a **--template-dir** parameter option.
Edit the content of one of the template (example: README.mustache)
Execute the generation.
Check that the output has your change.

**Comment by wing328** [comment]
@mpoiriert if I remember correctly, we've fixed the issue in the latest master. Please give it a try and let us know if you still encounter the issue.

Latest master defaults to ES6, which still needs some work (https://github.com/swagger-api/swagger-codegen/pull/6431). Please set the switch `useES6` to false for the time being.

**Comment by mpoiriert** [comment]
I used the latest build and it does work like expected.


Just to let you know, you mention setting useES6 to false, I didn't do any of this and it seems to still be false as the default value.

Closing the issue.

**Comment by wing328** [comment]
@mpoiriert ok. I'll take another look at the default value for "useES6"

**Comment by Loktor** [comment]
Since i just ran in the same issue and investigated it a bit.
I think the issues stems from this part

        if (additionalProperties.containsKey(USE_ES6)) {
            setUseES6(convertPropertyToBooleanAndWriteBack(USE_ES6));
        } else {
            setUseES6(false);
        }

inside processOpts, which calls

         public void setUseES6(boolean useES6) {
                this.useES6 = useES6;
                if (useES6) {
                    embeddedTemplateDir = templateDir = "Javascript/es6";
                    LOGGER.info("Using JS ES6 templates");
                } else {
                    embeddedTemplateDir = templateDir = "Javascript";
                    LOGGER.info("Using JS ES5 templates");
                }
            }

and there the templateDir var is always overridden. 

Sadly that is also the case for useES6 = false, because for The JavascriptCodegen the templateDir variable is always overriden:

           config.setTemplateDir(swaggerTemplateDirectory);

I hope that might help, since i am using it currently myself and was stuck on that problem too :D
