### ISSUE TITLE
[Swift4] JSONDecoder mapping Error

### ISSUE THREAD

**Issue by riceman2** [swagger-api/swagger-codegen#6589]
##### Description

I am gaining Json data with hyphens attached.
e.g. "key-color" / "file-type"

After mapping to Swift 4, mapping of such data is not working properly.
I cope temporarily by adding the following code.

enum CodingKeys:String,CodingKey{
        case baseColor = "base-color"
        case keyColor  = "key-color"
    }

I am happy to attach such code automatically when generating code automatically.

**Comment by wing328** [comment]
@riceman2 which version of Swagger Codegen are you using? The latest master has a couple of enhancements, bug fixes to Swift4 generator. Please give that a try and let us know if you still experience the same issue.

**Comment by riceman2** [comment]
@wing328 thank you for reply.
I use Swagger editor.
https://editor.swagger.io/

1.upload yaml
2.click "Generate Client"
3.Select "Swift4"

Now, I retry this situation.Still the same situation.

Would it be better to use this report as a Swagger Editor?

I did not know which to report to.
https://github.com/swagger-api/swagger-codegen/issues/2430

**Comment by wing328** [comment]
@riceman2 Swagger Editor is using the latest stable version if I'm not mistaken.

I would suggest you to use the SNAPSHOT version of the latest master to give it a try: https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by riceman2** [comment]
I download SNAPSHOT version at
swagger-codegen-cli-2.3.0-20170926.043109-160.jar

I try cli command to
"java -jar swagger-codegen-cli-2.3.0-20170926.043109-160.jar generate -i swagger.yaml -l swift4 -o temp/"
It is success! Thank you very much!

**Comment by wing328** [comment]
No problem :)
