### ISSUE TITLE
Is it possible to use swagger codegen to generate a client for .Net4.0?

### ISSUE THREAD

**Issue by Faerylnahr** [swagger-api/swagger-codegen#6596]
Hi everybody,

I already asked this question on stackoverflow (https://stackoverflow.com/questions/46454292/is-it-possible-to-use-swagger-codegen-to-generate-a-client-for-net4-0) but was asked by @wing328  to open a ticket if I'm looking for a particular .net version that is not yet supported at the moment.
For my project I need a .NET 4.0 client :-) is it possible to add support for this?

Regards, Stefi

**Comment by wing328** [comment]
@Faerylnahr We can work together to add support for .NET 4.0.

What error did you get when using the .NET3.5 or 4.5 client in your environment (assuming you've tested both .NET3.5 and 4.5 client)?

**Comment by Faerylnahr** [comment]
Sounds good 👍 Even though I'm new to C# and Swagger I'll try my best.
My project needs to be based on .NET-4.0. When adding the generated client for .NET-4.5 I'll get the error message that both frameworks do not match as RestSharp and Newtonsoft are intented to be used under 4.5. In combination with .NET-3.5 the build fails with `[...]\Pet.cs(89,29): error CS0241: Default parameter specifiers are not permitted`. In addition I've read somewhere that it isn't a good idea to combine a .NET-4.0 project with a .NET-3.5 library. Both should use the same .NET-Version as otherwise both need to be installed on the executing os (currently I have different systems to support starting with XP and ending with Windows7). But that's the point where I don't know what's the best way to go as I'm new to the whole C#/.NET world.

**Comment by wing328** [comment]
Just want to ask the obvious question. It's not an option in your side to upgrade the .NET framework to a newer version, e.g. .NET 4.5, right?

**Comment by Faerylnahr** [comment]
No, unfortunately not :-( As I already stated, I have different systems to support starting with XP (thus the NET-4.0 requirement) and ending with Windows7. Maybe I can switch to .NET-4.5 in future but currently that's not an option.

**Comment by wing328** [comment]
Understood. I would suggest you to do the following:
1) start with the C# API client for .NET 3.5
2) Manually fix the output code to confirm it works with .NET 4.0
3) apply the fix to the mustache templates with new mustache tag for .NET 4.0 such as `{{^net40}} ... {{/net40}}` or `{{#net40}} ... {{/net40}}` in the C# templates: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/csharp

**Comment by Faerylnahr** [comment]
Hi, after almost 2 hours I finally got it working under .NET-4.0 I think. I had to remove the default parameters (e.g. ` = null`) for some methods (see here: [https://docs.microsoft.com/de-de/dotnet/csharp/misc/cs0241](https://docs.microsoft.com/de-de/dotnet/csharp/misc/cs0241)), added Newtonsoft 4.5.11 (RestSharp stays with 105.2.3) and changed the targetFramework to net40 (in packages.config). 
Step 3 will become a little bit tricky for me as I'm not familiar with mustache :-(

**Comment by wing328** [comment]
@Faerylnahr good to see that you can customize the output to make it work with .NET 4.0

> Step 3 will become a little bit tricky for me as I'm not familiar with mustache :-(

I think this is something we can help. We can work together as follows:

1) you use https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml to generate
2) publish it in your github repo
3) we compare that C# petstore client generator by the default setting and reverse engineering change back into the template.

Does it sound good to you?

**Comment by Faerylnahr** [comment]
Sounds good to me! I'll to my best to provide you the stuff you need :-)
Just to get you right: Do I publish the generated (and already modified) C# client? Because you are speaking of a generator and I'm a little bit confused what exactly you are expecting to get.

**Comment by wing328** [comment]
Please push the C# petstore code with the fix for .NET 4.0

2017年10月8日 下午6:47，"Faerylnahr" <notifications@github.com>寫道：

**Comment by Faerylnahr** [comment]
I just recognized that I generated the c# client the wrong way. I didn't change the build.bat correctly. I did change the lib versions but not the framwork version. Thus I got `CS0241: Default parameter specifiers are not permitted` errors.
All that has to change are the following three files:
**\build.bat** (change the versions for Newtonsoft & Restsharp)

```
copy packages\Newtonsoft.Json.4.5.11\lib\net40\Newtonsoft.Json.dll bin\Newtonsoft.Json.dll
copy packages\RestSharp.105.2.3\lib\net4\RestSharp.dll bin\RestSharp.dll
```

**\src\IO.Swagger\packages.config**

```
<package id="Newtonsoft.Json" version="4.5.11" targetFramework="net40" />
<package id="RestSharp" version="105.2.3" targetFramework="net40" />
```

**\src\IO.Swagger.Test\packages.config**

```
<package id="Newtonsoft.Json" version="4.5.11" targetFramework="net40" />
<package id="NUnit" version="3.8.1" targetFramework="net40" />
<package id="RestSharp" version="105.2.3" targetFramework="net40" />
```

I newly generated the c# client, changed those files and add the dll as reference in a small sample project. Everything is (currently) working as intended.
Maybe someone else can verify it :-)

**Comment by Faerylnahr** [comment]
Any update on this? :-)

**Comment by wing328** [comment]
@Faerylnahr I'll try to look into this in the coming week

**Comment by wing328** [comment]
@Faerylnahr I've submitted #6792. Please give it a try:
```
git fetch origin
git checkout -b csharp_40 origin/csharp_40
git merge master
```

**Comment by wing328** [comment]
@Faerylnahr the PR has been merged into master. Please pull the latest master to give it a try or use the SNAPSHOT version of 2.3.0 as mentioned in the README.

**Comment by Faerylnahr** [comment]
Sry for the very late response. With the current version 2.3.1 i can generate .Net 4.0 code. Unfortunately the async operations are missing :-(
I set "supportAsync" in the config.json to true but it's not working
