### ISSUE TITLE
[Java-Playframework] UUID parameter is not found

### ISSUE THREAD

**Issue by sparta15** [swagger-api/swagger-codegen#6609]
##### Description

If you have one a parameter as `UUID` inside you `url`, It's not found as parameter of the controller method and don't compile.

##### Swagger-codegen version

2.3.0 - SNAPSHOT

##### Swagger declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
(here your code)
```
(for YAML code) or
```json
```-->
You can consult the example [here](https://gist.github.com/sparta15/cc45018f7657201b893288ea77643c51)
<!--
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->
And this is the routes file generated:

```
# Routes
# This file defines all application routes (Higher priority routes first)
# ~~~~

#Functions for Awesome API
GET     /awesomeapi/v1/pets/:petId/stores/:id                     controllers.StoresApiController.getStore(petId: String, id: UUID)
GET     /awesomeapi/v1/pets/:petId/stores                     controllers.StoresApiController.listStores(petId: String)

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)
```

Whit this error:
```
[error] /localDirectory/petExample/store/target/scala-2.11/resource_managed/main/routes:8: not found: type UUID
[error] GET     /awesomeapi/v1/pets/:petId/stores/:id                   controllers.StoresApiController.getStore(petId: String, id: UUID)

```
##### Command line used for generation

<!-- including the language, libraries and various options -->

##### Steps to reproduce

language JavaPlayFramework

<!-- unambiguous set of steps to reproduce the bug.-->
##### Pull Request to resolve it

[Resolve problem with UUID class not found if there is almost one parameter with format as uuid](https://github.com/swagger-api/swagger-codegen/pull/6617)
##### Suggest a fix/enhancement

Change `route.mustache` adding `java.util.UUID` when the parameter will be `UUID`
Example:
```
GET     /awesomeapi/v1/pets/:petId/stores/id                     controllers.EventsApiController.getEvent(userId: String, id: java.util.UUID)
```

**Comment by sparta15** [comment]
I'm seeing the last PRs in the `swagger-codegen` project and @tzimisce012 add support for isUuid [here](https://github.com/swagger-api/swagger-codegen/pull/6382) , but in order to maintain consistence UUID object has both property `isUuid` and `isString` true. I don't know why but the property `isUuid` is ignored but not `isString`

**Comment by sparta15** [comment]
I know what is the problem and why the property `isUuid` had been ignored, I'm working in order to have a PR with the fix soon. I hope you guys accept it :)

**Comment by tzimisce012** [comment]
Thanks @sparta15 , I did not realize about this problem until now.
