### ISSUE TITLE
Minor issue: method description is incorrectly HTML-escaped 

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#661]
The original method description in Swagger spec does not contain HTML-escaped characters (e.g. &lt;). However, the auto-generated code escapes all HTML special characters in the description as shown below (Java Petstore example).

```
  /**
   * Delete purchase order by ID
   * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or nonintegers will generate API errors
   * @param orderId ID of the order that needs to be deleted
   * @return void
   */
  public void deleteOrder (String orderId) throws ApiException {
    Object postBody = null;
```

**Comment by fehguy** [comment]
we can use the triple {{{mustache}}} syntax if we want to write unescaped.

**Comment by wing328** [comment]
thanks @fehguy let me try that and file a PR to fix the issue accordingly

**Comment by xhh** [comment]
JavaDoc treats comments as HTML source, using `&lt;` there is correct actually (and accidentally).
See a relevant discussion here: http://stackoverflow.com/a/28073980/243797

**Comment by wing328** [comment]
I see. Will leave Java, Android, CSharp and Scala unchanged using the HTML-escaped output

**Comment by wing328** [comment]
Did a little bit more research and seems like only Python method documentation does not encode HTML special characters (http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format).

I'll file a PR to update Python documentation and fix other languages that are missing method documentation at the moment

**Comment by wing328** [comment]
Submitted #663
