### ISSUE TITLE
[Go] Update to use oauth2

### ISSUE THREAD

**Issue by grokify** [swagger-api/swagger-codegen#6618]
##### Description

I would like to use `oauth2` with the codegen SDK. This is supported in `resty` v1.

* https://github.com/go-resty/resty/issues/89
* https://github.com/go-resty/resty/pull/91
* https://godoc.org/github.com/go-resty/resty#Client.SetTransport

Issues with codegen SDK reported here:

* https://github.com/grokify/ringcentral-sdk-go-scg/issues/1
* https://github.com/grokify/ringcentral-sdk-go-scg/issues/2

It seems like 2 changes are needed:

* Change `Configuration.Transport` type to `http.RoundTripper` from `*http.Transport`
* Change `api_client.go` to use `"gopkg.in/go-resty/resty.v1"` from `"gopkg.in/go-resty/resty.v0"`

##### Swagger-codegen version

https://github.com/grokify/ringcentral-sdk-go-scg/blob/master/swagger_ringcentral_codegen_version.txt

```
$ unzip -p swagger-codegen-cli.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
implementation-version: 2.2.3
Built-By: tony
Build-Jdk: 1.7.0_79
package: io.swagger
Created-By: Apache Maven 3.3.9
Main-Class: io.swagger.codegen.SwaggerCodegen
url: https://github.com/swagger-api/swagger-codegen/modules/swagger-co
 degen-cli
mode: development
```

##### Swagger declaration file content or url

https://github.com/grokify/ringcentral-sdk-go-scg/blob/master/swagger_ringcentral_spec.json

##### Command line used for generation

https://github.com/grokify/ringcentral-sdk-go-scg/blob/master/swagger_ringcentral_command.sh

##### Steps to reproduce

Run this code with an unmodified client SDK:

https://github.com/grokify/ringcentral-sdk-go-scg/blob/master/examples/get_extension/get_extension.go

##### Related issues/PRs

not found

##### Suggest a fix/enhancement

| Item | old | new |
|------|-----|-------|
| `Configuration.Transport` type | `*http.Transport` | `http.RoundTripper` |
| resty dependency | `gopkg.in/go-resty/resty.v0` | `gopkg.in/go-resty/resty.v1` |

More testing is necessary to ensure `resty.v1` is backward compatible with `resty.v0` everywhere used.

**Comment by wing328** [comment]
@grokify can you check the latest master (2.3.0), which has Go client refactored and OAuth2 support?
