### ISSUE TITLE
[Python] Map java.io.InputStream type to str

### ISSUE THREAD

**Issue by jkankiewicz** [swagger-api/swagger-codegen#6626]
##### Description

The Python code generator is outputting a useless `models.input_stream.InputStream` model class for `java.io.InputStream` argument and return values when it should instead be mapping them to Python's built-in `str` type like it already does for `byte[]` values.
The generated model class is useless because it's incapable of conveying a sequence of bytes and an instance of it can never serve as more than a permanently empty `dict` object e.g.
```python
class InputStream(object):
    ...
    def __init__(self):
        ...
        self.swagger_types = {
            
        }

        self.attribute_map = {
            
        }

    def to_dict(self):
        ...
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            ...

        return result

    def to_str(self):
        ...
        return pformat(self.to_dict())
    ...
```

##### Swagger-codegen version

 v2.3.0

##### Related issues/PRs

I haven't been able to find any.

##### Suggest a fix/enhancement

Insert the following statements as lines 831 and 854, respectively, into the modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java file:
```java
        typeMapping.put("InputStream", "InputStream");
```
```java
        importMapping.put("InputStream", "java.io.InputStream");
```
Insert the following statement as line 96 into the modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java file:
```java
 typeMapping.put("InputStream", "str");
```

**Comment by wing328** [comment]
The Python client in 2.3.0 (latest master) has been refactored and I would suggest you to give it a try.

If it's still an issue with the latest master, please file a PR so that we can review your change more easily.

**Comment by jkankiewicz** [comment]
> The Python client in 2.3.0 (latest master) has been refactored and I would suggest you to give it a try.

It won't make any difference because the `java.io.InputStream` type still hasn't been accounted for in the current master branch.

> If it's still an issue with the latest master, please file a PR so that we can review your change more easily.

The changes that I've proposed are in terms of the master branch already. I'm afraid that I can't file a PR because I'm unable to clone your repository due to my version of OpenSSL which I'm not at liberty to update.
The addition of the type mapping should fix the problem because the failing methods in the generated client API began to function after I replaced all occurrences of `'InputStream'` with `'str'` within them.

**Comment by wing328** [comment]
cc @taxpon @frol @mbohlool @cbornet

**Comment by mbohlool** [comment]
We had the same problem with some types in kubernetes and in the preprocessing step of our client generator we replaced empty definitions (here I assume InputStream is one of them) with a proper type like object or string (empty definitions means no properties). Though io.java.InputStream seems to be a standard class, this is a side effect of your spec generator and I am not sure if it is a good idea to add it as a custom mapping to python client.

**Comment by jkankiewicz** [comment]
> Though io.java.InputStream seems to be a standard class, this is a side effect of your spec generator and I am not sure if it is a good idea to add it as a custom mapping to python client.

@mbohlool, Can you provide link(s) to the documentation for specifying type mappings via configuration?

**Comment by jkankiewicz** [comment]
It appears that the alternative to specifying the mapping of the `java.io.InputStream` type to `str` in the Python generator itself is to enable the `configuration.configOptions.import-mappings` tag in the POM file (corresponding to the `--import-mappings` command line option) for the Python generator so that it can be specified on an as-needed basis instead.

@mbohlool, Do you agree with that assessment or did you have a different mechanism in mind?

**Comment by mbohlool** [comment]
That sounds good to me.
