### ISSUE TITLE
CsharpDotNet2 generates UUID instead of Guid

### ISSUE THREAD

**Issue by sheltonc** [swagger-api/swagger-codegen#6631]
**swagger-codegen-cli-2.2.1.jar** (incorrectly) generates the type **UUID** instead of **System.Guid** when targetting CsharpDotNet2. 

However, when using the online swagger editor, the generated code creates the correct type from the same swagger.json.

I've attached a repro using docker. 
Steps:
1. Execute run.ps1
2. The output file ./CsharpDotNet2/src/main/CsharpDotNet2/IO/Swagger/Api/RegisterApi.cs has the type UUID (line:21)

If the same swagger.json is used to generate a CsharpDotNet2 client on the online editor, the correct type is generated (Guid?)

[cshelton-csharpdotnet2.zip](https://github.com/swagger-api/swagger-codegen/files/1363891/cshelton-csharpdotnet2.zip)

**Comment by wing328** [comment]
@sheltonc please try with the latest master as 2.2.1 was released a while ago.

SNAPSHOT version can be found in https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by wing328** [comment]
Closing this as there's no update.

Please let us know if it's still an issue with the latest master.
