### ISSUE TITLE
Swift4: Need additional initializer which uses properties

### ISSUE THREAD

**Issue by ehyche** [swagger-api/swagger-codegen#6641]
##### Description

I am filing this issue to track the discussion which took place in this PR for swift3: https://github.com/swagger-api/swagger-codegen/pull/6492

The request was to add an additional initializer for swift4-generated models. This initializer would take all of the properties, and thus would allow you to initialize a model object without having to decode it from JSON.

##### Swagger-codegen version

All

##### Swagger declaration file content or url

This is a feature request. See the discussion at the end of the PR listed above for context.

**Comment by Kimnyhuus** [comment]
Hi' @ehyche!
Do you by any chance know, when this will be merged and available in Swagger?
 - I'm guessing that it will be available in Swagger Codegen 2.3.0, when merged?

**Comment by wing328** [comment]
@Kimnyhuus https://github.com/swagger-api/swagger-codegen/pull/6642 has been merged into master.

Can you pull the latest master or use the SNAPSHOT version to give it a try?

**Comment by Kimnyhuus** [comment]
@wing328 Sure! Thanks for the quick response :-)

**Comment by wing328** [comment]
@Kimnyhuus no problem. Let me know if you still need help on this.

Closing this for the time being as the PR has already been merged.

**Comment by Kimnyhuus** [comment]
@wing328: 
We've now generated code from master on v2.3.0, and the initialisers are present now.
There's one thing missing though. On Swift3 the initialisers had the ability to make all optional model variables '=nil' in the parameter, making it possible to initialise an object with only some or none of the parameters. 

Example:

```
Model:

Open class SwaggerModel: Codable

public var foo: String
public var bar: Int?

public init(foo: String, bar: String?=nil) {
        self.score = score
        self.user = user
}


In class usage:

var swaggerModel = SwaggerModel(foo: "Leet")
swaggerModel.bar = 1337
```
This is not the case with the current version of v2.3.0, which does not generate the '=nil'.
Can you add this again? :-)

**Comment by ehyche** [comment]
@Kimnyhuus : yeah we can add this. I should have added it previously. 

Of course, the "= nil" will only get added if:

- the property is optional (and thus is a Swift Optional); AND
- no default is provided in the schema. If a default is already provided in the schema, then that will be used for the default.

**Comment by ehyche** [comment]
@Kimnyhuus : would mind filing a separate issue for this? That way, I can tie the PR to a new Issue and not one that has already been closed. Thanks!

**Comment by Kimnyhuus** [comment]
@ehyche : Sure, I'll open an issue right away.
Thank you! It's really appreciated :-)
