### ISSUE TITLE
[Swift3] Crash when building an array of strings (from enum)

### ISSUE THREAD

**Issue by ornithocoder** [swagger-api/swagger-codegen#6643]
##### Description

My project is using the DayOfWeek definition from Google (see below) but swagger-codegen is having problems to JSON-encode it as an array of strings.

Google's protobuf is defined as:

```proto
enum DayOfWeek {
  // The unspecified day-of-week.
  DAY_OF_WEEK_UNSPECIFIED = 0;

  // The day-of-week of Monday.
  MONDAY = 1;

  // The day-of-week of Tuesday.
  TUESDAY = 2;

  // The day-of-week of Wednesday.
  WEDNESDAY = 3;

  // The day-of-week of Thursday.
  THURSDAY = 4;

  // The day-of-week of Friday.
  FRIDAY = 5;

  // The day-of-week of Saturday.
  SATURDAY = 6;

  // The day-of-week of Sunday.
  SUNDAY = 7;
}
```

Swagger-codegen creates the following code:

```swift
public enum DayOfWeek: String {
    case dayOfWeekUnspecified = "DAY_OF_WEEK_UNSPECIFIED"
    case monday = "MONDAY"
    case tuesday = "TUESDAY"
    case wednesday = "WEDNESDAY"
    case thursday = "THURSDAY"
    case friday = "FRIDAY"
    case saturday = "SATURDAY"
    case sunday = "SUNDAY"

    func encodeToJSON() -> Any { return self.rawValue }
}
```

When encoding to an array of strings, instead of using the raw values from the enums, it's referencing the type. in other words, `[.monday, .tuesday]` become `[ClientAPI.DayOfWeek.monday, ClientAPI.DayOfWeek.tuesday]` instead of  `["MONDAY", "TUESDAY"]`. When performing the request, the client crashes because it doesn't know how to process and build the body JSON.

The problem happens when the array is encoded, see below.

```swift
open class Recurrence: JSONEncodable {

    public var weekdays: [DayOfWeek]?
    // ...

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["weekdays"] = self.weekdays?.encodeToJSON()
        // ...

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
```

When I replace `self.weekdays?.encodeToJSON()` with `weekdays?.map { $0.rawValue }.encodeToJSON()` it works properly.

##### Swagger-codegen version

2.2.3

##### Command line used for generation

```
        swagger-codegen generate \
            --input-spec "./swagger/combined_swagger.json" \
            --lang "${lang}" \
            --config "./config/${lang}.config" \
            --output "./out/${lang}"
```

where `lang` = `swift3`.

**Comment by jaz-ah** [comment]
@ornithocoder can you try out 2.3.0 since many changes were added to fix issues there...

**Comment by ornithocoder** [comment]
Sure @jaz-ah. I'll give it a try tomorrow morning. Thanks :-)

**Comment by ornithocoder** [comment]
Issue persists on 2.3.0.

**Comment by ornithocoder** [comment]
HI there! Any update on this?

**Comment by jaz-ah** [comment]
@ornithocoder sorry I haven't taken a look at this in a while - I would suggest either trying 2.3.1 or potentially submitting a fix here which we can review (if this is specific to all arrays of string enums)

**Comment by ornithocoder** [comment]
@jaz-ah same happens with 2.3.1. I'll migrate my project to Swift 4 to workaround this problem (the Swift 4 templates use Codable and don't have this issue).
