### ISSUE TITLE
[csharp] Return types don't match generated model names

### ISSUE THREAD

**Issue by Snelbinder** [swagger-api/swagger-codegen#665]
I'm using swagger-codegen to generate a C# client. In my swagger spec my types include their full namespace because I have classes with the same name spread across different namespaces.

For example I could have a definition for Example.Store.Product in my swagger spec:
```
"definitions": {
    "Example.Store.Product": {
        "type": "object",
        "properties": {
            "Title": {
                "type": "string"
            },
            "LanguageCode": {
                "type": "string"
            }
        }
    }
}
```
This will generate a ExampleStoreProduct model as follows:
```
namespace io.swagger.Model {
    public class ExampleStoreProduct {
        // Properties
    }
}
```
However, in the generated Api file the return type will be Example.Store.Product, which obviously not does compile.
```
public Example.Store.Product Product_GetProducts () {
    // code
}
```
I'm using version 2.1.0-M2 and a Swagger 2.0 spec.

**Comment by wing328** [comment]
@Snelbinder I've filed a PR #668 to fix the issue. I did some tests and the generated code looks good (e.g the return type is PetTest instead of Pet.Test).

**Comment by Snelbinder** [comment]
@wing328 Tested it and it all seems to work now, thanks for the quick fix!

**Comment by fehguy** [comment]
great, thank you
