### ISSUE TITLE
[Python Server] Enums don't work in Python Server

### ISSUE THREAD

**Issue by p-buse** [swagger-api/swagger-codegen#6654]
##### Description
Enums don't get translated properly when using language `python-flask`.

##### Swagger-codegen version
I'm using version `2.3.0-SNAPSHOT`, in Docker.

##### Swagger declaration file content or url
https://gist.github.com/p-buse/bf29f7b13ce1b7f412266165e1423ca3

##### Command line used for generation
`./run-in-docker.sh generate -l python-flask -o python-server -i openapi.yaml`

##### Steps to reproduce
Generate the `python-server` directory as seen above. Browse to `python-server/swagger_server/models/author_gender.py`. This model file contains no information.

##### Related issues/PRs
None AFAIK.

##### Suggest a fix/enhancement
The Python Client generation works fine with Enums. I'd recommend borrowing the code from there.

**Comment by wing328** [comment]
> The Python Client generation works fine with Enums. I'd recommend borrowing the code from there.

Yes please. We wanted to sync the Python model template to Python Flask but no one can find the time. I wonder if you can help on this.

Let me know if you need some good starting points (e.g. template folder)
