### ISSUE TITLE
[JAVA] Bug: Code with compile errors is generated for 'path' query param

### ISSUE THREAD

**Issue by katilius** [swagger-api/swagger-codegen#6655]
##### Description

If you have path as your query parameter, code gen generates non compilable Java client.

##### Swagger-codegen version

2.2.3

##### Swagger declaration

```json
  "parameters": [
          {
            "name": "path",
            "in": "query",
            "description": "path",
            "required": false,
            "type": "string"
          },
```

##### Variable name clashes with this

```java
        String path = UriComponentsBuilder.fromPath("/fieldchanges").buildAndExpand(uriVariables).toUriString();

```

**Comment by wing328** [comment]
@katilius Have you tried the `localVariablePrefix` option?

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/api.mustache#L74

**Comment by katilius** [comment]
Oh, I've missed this one. With localVariablePrefix it does compile.
Although, probably it needs better documentation for that kind of cases.

**Comment by wing328** [comment]
Please feel free to submit a PR to improve the documentation :)
