### ISSUE TITLE
Static HTML Page Requesting site.css

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-codegen#666]
I just built using the [`-l html` flag](https://github.com/swagger-api/swagger-codegen#generating-static-html-api-documentation) but it looks like outputted page is requesting site.css:
https://github.com/swagger-api/swagger-codegen/blob/e8ae9178af5a62276f09deac9805ca3ff8b2d6e8/modules/swagger-codegen/src/main/resources/htmlDocs/index.mustache#L5

**Comment by fehguy** [comment]
you are correct, that can go away.

**Comment by wing328** [comment]
This can be closed as #715 has been merged

**Comment by wing328** [comment]
site.css still found in index.html. Submit #1335 to remove it.
