### ISSUE TITLE
C# Enums defined as optional are not nullable [MyEnum (?) myenum]

### ISSUE THREAD

**Issue by moreyeel** [swagger-api/swagger-codegen#6690]
##### Description

I am generating C# files from a YAML file. I have an optional enum parameter which I decorate in the template NullValueHandling = NullValueHandling.Ignore meaning if null do not serialize. Like so:

[JsonProperty("days", NullValueHandling = NullValueHandling.Ignore)]
public WeekDays Days { get; set; }

The trouble is that unlike other C# nullable types (int?, bool?) the enum is not generated as nullable. 
This means that the default value (sun) is always sent in my requests which is not the desired behavior. I cannot discern when the user chose not to configure a value at all and when the user configured sun in the aforementioned enum.

##### Swagger-codegen version

swagger-codegen version 2.2.3

##### Swagger declaration file content or url

```yaml

swagger: '2.0'
info:
  version: '1'
  title: My title
host: 'localhost:10010'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  WeekDays:
    type: string
    enum:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
  My_Class_With_Optional_Enum:
    properties:
      quarantine:
        type: boolean
      grayware:
        type: boolean
      days:
        $ref: '#/definitions/WeekDays'
      
```

##### Command line used for generation

java -jar -Dproject -Dmodels -DmodelTests=false -DmodelDocs=false -DdebugModels=true -DdebugOperations=true swagger-codegen-cli-2.2.3.jar generate -i my.yaml -l csharp -o outputDir -t templateDir --type-mappings Guid?=string

##### Steps to reproduce

Generate the C# files using swagger-codegen-cli-2.2.3.jar
Open the file MyClassWithOptionalEnum.cs
See public WeekDays Days { get; set; }
Expected" public WeekDays ? Days { get; set; }

##### Suggest a fix/enhancement

C# treat enums as a nullable type

**Comment by moreyeel** [comment]
Any ideas about this one?

**Comment by jimschubert** [comment]
@moreyeel I've opened #6851. I was wondering if you could build this branch and evaluate?

**Comment by moreyeel** [comment]
Hi Jim, 

Thank you very much for this, while the solution is not what I expected, it certainly does the job. 
What I found is that the enum is still not generated as a null-able type (?) by default however following your effort I am now able to discern in the mustache templates (modelGeneric.Mustache) {{#vars}} between {#isEnum}} and {^isEnum}}. 

This allows me to add the null-able (?) between the data type and the name, I assume this is because of the other programming languages where enum is an object.
To solve the problem I am having, I added the question mark (null-able) as followes:

{{#isEnum}}
[JsonProperty("{{baseName}}"{{^required}}, NullValueHandling = NullValueHandling.Ignore{{/required}})]
public {{{datatype}}} **_?_** {{name}} { get; {{#isReadOnly}}private {{/isReadOnly}}set; }
{{/isEnum}}

Do you have a target release planned for this issue? 

Thanks again!

**Comment by jimschubert** [comment]
@moreyeel If you check the integration tests in the linked PR, you'll see the properties should now look like you've suggested (with the Nullable). I used the spec you provided for one test, and slightly modified it for another.

 I still have some testing to do, around required=false/true, but I wanted to see if you could evaluate this branch.

Would it be easier if I built a sticker image of the branch?

If this is a blocker currently, you can always pull the csharp template directory from the swagger-codegen module's resources, make the template modification locally and use the `-t` option to point to your customized templates.

**Comment by moreyeel** [comment]
I built the branch and am using the JAR to generate according to my templates. I tested this on about 400 different models and they all generate correctly. Should I close this?

**Comment by jimschubert** [comment]
@moreyeel Thanks for verifying against so much code! I would say to leave the issue open until the PR is merged, just for visibility to avoid duplicate bug reports.

**Comment by jimschubert** [comment]
I was just going through open issues. Looks like the PR is now in master. If this still works, I think the issue can be resolved.

**Comment by moreyeel** [comment]
I have been using this code for a month now. I found no issues, I generated over 1000 classes in this period and in the use cases that I am using there are no issues. 

@jimschubert informed me that the fix is in the master therefore I am closing this.
