### ISSUE TITLE
[Java][CXF] Include more of the API documentation in the CXF Server stub generation

### ISSUE THREAD

**Issue by gustavoapaz** [swagger-api/swagger-codegen#6696]
##### Description

This is a feature request. I want to include more of the API documentation in the CXF Server stub generation so that the Java code is more complete.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url
..

##### Command line used for generation

..

##### Steps to reproduce

..

##### Related issues/PRs

..

##### Suggest a fix/enhancement

Here is the change that I propose: https://github.com/gustavoapaz/swagger-codegen/commit/05eefe2adbde8a9b8cb44c7bdccd5a81ab9daba3

**Comment by wing328** [comment]
@gustavoapaz the proposed change looks good to me. Please submit a PR so that we can review the enhancement more easily.
