### ISSUE TITLE
[TypeScript-Fetch] Local variables can conflict with parameters

### ISSUE THREAD

**Issue by masaeedu** [swagger-api/swagger-codegen#6698]
##### Description

The `typescript-fetch` client template inserts local variables with names like `path`, which is a fairly common name for API parameters. If an API has a parameter named `path`, the generated client will have a compile error and the transpiled code can have subtle bugs.

##### Swagger-codegen version

Issue is present in 96137e5. Specifically, the lines starting [here](https://github.com/swagger-api/swagger-codegen/blob/96137e5/modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache#L101).

##### Swagger declaration file content or url

[Latest Docker API spec](https://github.com/moby/moby/blob/01f9227/api/swagger.yaml)

##### Command line used for generation

```
generate -i /moby/api/swagger.yaml -l typescript-fetch -o /package
```

##### Suggest a fix/enhancement

Use mangled names for the local variables (e.g. `const ____path` or such).

**Comment by wing328** [comment]
@masaeedu For other generators, we usually add a prefix to the local variable (e.g. localVarPath or local_var_path).

May I know if you've time to help us add something similar to the TS Fetch generator? A good starting point is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-fetch/api.mustache
