### ISSUE TITLE
Static HTML Page Not Rendering Example Correctly

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-codegen#670]
The newlines (`\n`) are not rendering correctly in the example block when creating a static HTML page. The same block looks fine in swagger-ui.
```
Example data
Content-Type: application/json
{\n  "number" : "aeiou",\n  "date" : "",\n ....
```

**Comment by kvelakur** [comment]
I've reported this issue as well #642

**Comment by webron** [comment]
Closing as duplicate then.
