### ISSUE TITLE
Return Type Href Not Actually Set

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-codegen#671]
The link to the return type in the static pages is just left as `#`:
https://github.com/swagger-api/swagger-codegen/blob/618b4698c246a39824262e781ecd2b7f7a954261/modules/swagger-codegen/src/main/resources/swagger-static/operation.mustache#L16

**Comment by wing328** [comment]
@cancan101 should be fixed by #716. Please reopen this issue if it's not the case.
