### ISSUE TITLE
[Java] -DdebugModels option causes JsonMappingException during generation preventing debug output

### ISSUE THREAD

**Issue by jonschoning** [swagger-api/swagger-codegen#6711]
##### Description

`-DdebugModels` option causes `JsonMappingException: Infinite recursion (StackOverflowError)` on `petstore-with-fake-endpoints-models-for-testing.yaml`.  This prevents debugModels output from displaying properly.

Have also reproduced with `csharp`.  
Haven't tested all generators, but doesn't occur with all generators.

cli output : https://gist.github.com/jonschoning/f743916372f25a09b05611363a334d61

Ubuntu 17.04
java version "1.8.0_144"

##### Swagger-codegen version

5c14f907d (master @ 2017-10-16 22:33:12 +0800)

##### Swagger declaration file content or url

`modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml`

##### Command line used for generation

```bash
java  -XX:MaxPermSize=256M -Xmx1024M -DloggerPath=conf/log4j.properties -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar  generate -t modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson -i modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -l java -c bin/java-petstore-okhttp-gson.json -o samples/client/petstore/java/okhttp-gson -DhideGenerationTimestamp=true -DdebugModels=true
```

(command copied from `bin/java-petstore-okhttp-gson.sh` /w `-DdebugModels=true` added)

##### Steps to reproduce

see above

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

N/A

**Comment by wing328** [comment]
If my memory serves me well, there may be models defined with circular reference in petstore-with-fake-endpoints-models-for-testing.yaml, which might explain the exception you encountered.

**Comment by diamondq** [comment]
I also ran into this. Turned out to be a recursion problem with the CodegenModel 'children' having a 'parent' that points back to the same object. Jackson get's confused with a larger Swagger.

Very simple fix, as Jackson has an annotation specifically for this problem. Change the code to have the following 3 annotations: 

```java
    @JsonBackReference
    public CodegenModel parentModel;
    @JsonManagedReference
    public List<CodegenModel> interfaceModels;
    @JsonManagedReference
    public List<CodegenModel> children;
```

**Comment by plcousins** [comment]
> I also ran into this. Turned out to be a recursion problem with the CodegenModel 'children' having a 'parent' that points back to the same object. Jackson gets confused with a larger Swagger.
> 
> Very simple fix, as Jackson has an annotation specifically for this problem. Change the code to have the following 3 annotations:
> 
> ```java
>     @JsonBackReference
>     public CodegenModel parentModel;
>     @JsonManagedReference
>     public List<CodegenModel> interfaceModels;
>     @JsonManagedReference
>     public List<CodegenModel> children;
> ```

I would suggest reversing the use of JsonBackReference and JsonManagedReference.  The parentModel is probably what you want to keep if you are debugging a template.
