### ISSUE TITLE
[typescript-angular] Generate fat arrow functions at services

### ISSUE THREAD

**Issue by wurmrobert** [swagger-api/swagger-codegen#6714]
##### Description

I have base classes which I transfer swagger generated service methods as function parameters. However, the transpiled service code loses the `this` scope. In order to keep the correct `this` scope, the swagger methods should be implemented as fat-arrow functions.

Is there any possibility to generate fat arrow functions?

##### Swagger-codegen version

Version 2.3.0

##### Steps to reproduce

```json

// correct
public getFindAllCustomerPaged = (page?: string, size?: string, sort?: string, extraHttpRequestParams?: any): Observable<PagedCustomerResources> => {
        return this.getFindAllCustomerPagedWithHttpInfo(page, size, sort, extraHttpRequestParams)
            .map((response: Response) => {
               ...
            });
}

// loses the this scope if method is hand over function parameter to other objects
public getFindAllCustomerPaged (page?: string, size?: string, sort?: string, extraHttpRequestParams?: any): Observable<PagedCustomerResources> {
        return this.getFindAllCustomerPagedWithHttpInfo(page, size, sort, extraHttpRequestParams)
            .map((response: Response) => {
               ...
            });
}

```

**Comment by wing328** [comment]
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by TiFu** [comment]
To make sure I understand the problem correctly: 

You have some method `a` which accepts `swagger.getFindAllCustomerPaged` as a parameter. If you pass it with `a(swagger.getFindAllCustomerPaged)`, `getFindAllCustomerPaged` looses the `this` scope. This could be solved either like you proposed or by using `a(swagger.getFindAllCustomerPaged.bind(swagger))`. 
Is my understanding of the issue correct?

**Comment by kenisteward** [comment]
@tifu I was just about to respond with that solution haha

**Comment by kenisteward** [comment]
@wurmrobert we probably won't generate fat arrow functions in the future as
@tifu's proposed solution does everything I think you need. Also generating
fat arrow breaks aot I'm some cases and we wouldn't want that!

**Comment by wurmrobert** [comment]
@TiFu 
The `bind` function is the perfect solution to my problem. Many thanks for your help!

**Comment by wurmrobert** [comment]
The bind function is the perfect solution to my problem. Many thanks for your help!
Thanks to @TiFu
