### ISSUE TITLE
Java JaxRs Resteasy: @DefaulValue missing in queryParams template.

### ISSUE THREAD

**Issue by andreaformica** [swagger-api/swagger-codegen#6716]
##### Description

Trying to generate RESTEASY server side API using swagger codegen: API methods are missing the DefaultValue in the query parameters.

##### Swagger-codegen version

I am using the master in git.

##### Suggest a fix/enhancement

I think it is enough to add 
{{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}){{#defaultValue}} @DefaultValue("{{{defaultValue}}}"){{/defaultValue}}
in the queryParams.mustache  file which is in 
swagger-codegen/src/main/resources/JavaJaxRs/resteasy

But I must admit I do not understand the mustache templates a lot...

**Comment by wing328** [comment]
@andreaformica your suggested fix looks good. Please file a PR when you've time.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/6726
