### ISSUE TITLE
[Javascript] Referencing old Babel presets causes warnings during npm install.

### ISSUE THREAD

**Issue by TheFirstLairron** [swagger-api/swagger-codegen#6719]
##### Description
When running npm install on a javascript client generated by swagger-codegen you will notice the following error:

> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

This is not a serious issue but is fixed fairly easily(I recently did it to a project), and will cut down on warnings.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url
Use any swagger file content.

##### Command line used for generation

Language: ES6 Javascript

##### Steps to reproduce

Produce an ES6 javascript client

##### Related issues/PRs
None

##### Suggest a fix/enhancement
As the error suggested, update the javascript templates to use the newer, and non-deprecated babel preset "babel-preset-env" instead of "babel-preset-2015" and "babel-preset-stage-0".

**Comment by wing328** [comment]
@TheFirstLairron I agree we should update it to use the newer version. Do you mind submitting a PR with the suggested fix?

**Comment by TheFirstLairron** [comment]
Hey, sorry for going dark on you guys. I've been fairly busy so I don't think I will have any time to put together a PR for you guys. At least not soon. If this is still active when I have more time than i would be more than happy to help.

**Comment by wing328** [comment]
@TheFirstLairron it has been fixed by https://github.com/swagger-api/swagger-codegen/pull/6799 (by @hisener )

Please pull the latest master to give it a try or use the SNAPSHOT version (2.3.0) mentioned in the README
