### ISSUE TITLE
[Suggestion] Use RestSharp to replace ApiInvoker in CSharp

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#673]
I would suggest using [RestSharp](https://github.com/restsharp/RestSharp) to replace ApiInvoker in the CSharp client.

I've tested GetPetById (GET), AddPet (POST JSON) and UpdatePetWithForm(POST FORM) using RestSharp and it works perfectly fine. To me, the code looks cleaner and easier to understand.

Here is a list of projects/SDKs using RestSharp:
https://github.com/restsharp/RestSharp/wiki/Projects-Using-RestSharp

May I know if anyone has concern using RestSharp to replace ApiInvoker in CSharp?

**Comment by fehguy** [comment]
no concerns from my side.  Looks like a solid library.

**Comment by wing328** [comment]
PR merged
