### ISSUE TITLE
[Swift4] Bug - Swift4 `CodableHelper.swift` file is not compiling

### ISSUE THREAD

**Issue by Tesan3010** [swagger-api/swagger-codegen#6744]
##### Description

Enum has been changed in JSONDecoder & JSONEncoder (`DataDecodingStrategy`, `DataEncodingStrategy` and `Outputformatting`) due to which unable to compile the `Swift4 project`.

##### Swagger-codegen version

2.2.3

##### Command line used for generation
```
swagger-codgen -i <input_yaml_file or input_json_file> -l swift4 -o <output_directory>
```

##### Steps to reproduce

- Open CodableHelper.swift from `Classes > Swaggers > CodableHelper.swift`

- Find the below entries in the file
  - decoder.dataDecodingStrategy = .base64Decode
  - encoder.outputFormatting = (prettyPrint ? .prettyPrinted : .compact)
  - encoder.dataEncodingStrategy = .base64Encode

##### Suggest a fix/enhancement
  - decoder.dataDecodingStrategy = .base64
  - encoder.outputFormatting = (prettyPrint ? .prettyPrinted : .sortedKeys)
  - encoder.dataEncodingStrategy = .base64

**Comment by wing328** [comment]
Please try the latest master (2.3.0) to see if the issue persists.

SNAPSHOT version of 2.3.0 can be found in the README

**Comment by Tesan3010** [comment]
Thanks for the reply. When I was trying to install from the source code using maven, tests were failing at `org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test` goal.

I'm using `Apache Maven - 3.5.0` and `Java -v9`

**Comment by wing328** [comment]
What about using the 2.3.0 SNAPSHOT JAR in mentioned in https://github.com/swagger-api/swagger-codegen#compatibility?

**Comment by wing328** [comment]
Btw, I ran `mvn clean package` locally without issues:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  7.128 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [12:16 min]
[INFO] swagger-codegen (executable) ....................... SUCCESS [ 26.553 s]
[INFO] swagger-codegen (maven-plugin) ..................... SUCCESS [  3.828 s]
[INFO] swagger-generator .................................. SUCCESS [ 30.841 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:26 min
[INFO] Finished at: 2017-10-20T13:07:37+08:00
[INFO] Final Memory: 79M/1132M
[INFO] ------------------------------------------------------------------------
```

**Comment by Tesan3010** [comment]
I guess I'm missing something while installing from snapshot. Can you please tell me how do I install 2.3.0 from the snapshot.

**Comment by wing328** [comment]
@Tesan3010 please download https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.3.0-SNAPSHOT/swagger-codegen-cli-2.3.0-20171022.172748-209.jar

**Comment by Tesan3010** [comment]
Thanks @wing328 , 2.3.0-cli doesn't have this issue.

**Comment by wing328** [comment]
@Tesan3010 thanks for the confirmation. Issue closed.
