### ISSUE TITLE
[typescript-angular] template variable `defaultValue` not set correctly

### ISSUE THREAD

**Issue by trenneman** [swagger-api/swagger-codegen#6765]
##### Description

When overriding the mustache files for `typescript-angular`, I found out it does not set the template variable `defaultValue` for strings. I wanted to file a PR for this, but I noticed the `toDefaultValue` in `DefaultCodegen.java` is also ignoring `StringProperty`s.

##### Swagger-codegen version

2.2.3, 2.3.0-latest

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

* create a swagger file with a schema with an property of type 'string' and a 'default'
* update `modules/swagger-codegen/src/main/resources/typescript-angular/modelGeneric.mustache` to contain `defaultValue`
* run the codegen
* the generated .ts file has parses `defaultValue` of `'null'`

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

Either patching `modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java` or `modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java` by adding

```
if (p instanceof StringProperty) {
    StringProperty sp = (StringProperty) p;
    if (sp.getDefault() != null) {
        return sp.getDefault();
    }
    return "null";
}
```

to `public String toDefaultValue(Property p)`.

I am willing to do so, but I am not sure it can be added to `DefaultCodegen.java` safely.

**Comment by wing328** [comment]
@trenneman Please patch modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractTypeScriptClientCodegen.java and we'll review the change.
