### ISSUE TITLE
confict with android jar

### ISSUE THREAD

**Issue by zzsoszz** [swagger-api/swagger-codegen#6767]
java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/message/BasicHeaderValueFormatter; in class Lorg/apache/http/message/BasicHeaderValueFormatter; or its superclasses (declaration of 'org.apache.http.message.BasicHeaderValueFormatter' appears in /system/framework/org.apache.http.legacy.boot.jar)

**Comment by wing328** [comment]
Please fill out the issue form so that the community can help you out with the information you provided in the form
