### ISSUE TITLE
[Go] Arbitrary "object" type generated as pointer of interface

### ISSUE THREAD

**Issue by nazieb** [swagger-api/swagger-codegen#6768]
##### Description

In on of our API we need to define a field as "object" where in Go it's actually map string of interface. Right now Swagger Codegen generate that field as `*interface{}` where there is no such thing as pointer of interface.

##### Swagger-codegen version

I'm using snapshot of 2.3.0 branch:
swagger-codegen-cli-2.3.0-20170927.021746-163.jar

##### Swagger declaration file content or url

```json
"definitions": {
        "User": {
            "title": "User",
            "type": "object",
            "required": [],
            "properties": {
                "id": {
                    "description": "ID of the user",
                    "type": "number"
                },
                "attributes": {
                    "description": "The attributes of the user",
                    "type": "object"
                }
            }
        }
```

##### Command line used for generation

```
$ java -jar swagger-codegen-cli-2.3.0-20170927.021746-163.jar generate -i api.swagger.json -l go -o output
```

##### Steps to reproduce

Just run command line above on that swagger example

##### Related issues/PRs

I've found nothing regarding this

##### Suggest a fix/enhancement

I think this is not just patching the mustache template, maybe treat "object" as Container in Go generator class?

**Comment by wing328** [comment]
>  actually map string of interface. 

What about defining it as https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties?
