### ISSUE TITLE
[PHP] Debug flag is not passed

### ISSUE THREAD

**Issue by tarioch** [swagger-api/swagger-codegen#6770]
##### Description

With current master version (2.3.0) the debug flag from Configuration is not passed when the request is sent.

##### Swagger-codegen version

2.3.0

##### Suggest a fix/enhancement
When doing the clientInterface->send it should pass the debug flag in through the options array.

**Comment by ackintosh** [comment]
@tarioch Thanks for reporting the issue!  Let me check.

**Comment by ackintosh** [comment]
Can you attach a PR for this?

**Comment by wing328** [comment]
@tarioch PR by @ackintosh has been merged into master.

Please pull the latest master or use the SNAPSHOT version (2.3.0) to give it a try.
