### ISSUE TITLE
[Suggestion] Use urllib3 replace urllib2 in python client

### ISSUE THREAD

**Issue by geekerzp** [swagger-api/swagger-codegen#678]
I would suggest using [urllib3](https://github.com/shazow/urllib3) to replace urllib2 in the python client.

Compared with urllib2, urllib3 has many advantages:

* File posting (encode_multipart_formdata). We need not encode the multipart body manually.
* Re-use the same socket connection for multiple requests (HTTPConnectionPool and HTTPSConnectionPool) .

* urllib3 powers many great Python libraries, including pip, Dropbox and requests.
* The code looks cleaner and easier to understand.

May I know if anyone has concern using urllib3 to replace urllib2 in python client?

**Comment by fehguy** [comment]
hi @geekerzp any back compatibility concerns with this?

**Comment by geekerzp** [comment]
`urllib3` covers the majority of python version: `python2.6`, `python2.7`, `python3.2`, `python3.3` and `python3.4` so it's unlikely the user would encounter issues unless they're using an old version of python (python 2.5 was released almost 10 years ago).

**Comment by fehguy** [comment]
That sounds like a good upgrade to me!

**Comment by wing328** [comment]
Merged (#768)
