### ISSUE TITLE
how to put parameter default value into generated code in swagger

### ISSUE THREAD

**Issue by wangyiran125** [swagger-api/swagger-codegen#6782]
swagger parameter default is not in generated code. for example:

   paths:
  /user/refresh.json:
    post:
      operationId: refresh
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      produces:
      - application/json
      consumes: 
      - application/x-www-form-urlencoded
      parameters:
      - name: "RC-App-Key"
        in: "header"
        description: appkey..
        required: true
        default: "abc"
        type: "string"

the generated code like

public class DevelopersApiTest {

private final DevelopersApi api = new DevelopersApi();

@Test
public void refreshTest() throws ApiException {
    String rcAppKey = null;
    Common response = api.refresh(rcAppKey);

    // TODO: test validations
}
the rcAppKey is null,but i want it be the default value "abc",like:

String rcAppKey = "abc";
Common response = api.refresh(rcAppKey);
the default value is not in generated code,but in .md file,how to put the default value into the code?

**Comment by wangyiran125** [comment]
i use swagger2.0

**Comment by wing328** [comment]
Please try the latest master (2.3.0), which has better support for default values.

SNAPSHOT version can be found in the README

**Comment by wangyiran125** [comment]
@wing328 hi, i use 2.3.0 to generate java code, the default value is generated in DevelopersApi.md file, but not in java code.

**Comment by jonschoning** [comment]
I don't know about how the Java generator is supposed to work, but according to https://swagger.io/unlocking-the-spec-the-default-keyword/ the client does not need to set the default; it is the server that should assume the default value when it is not received by the client.  So it shouldn't be necessary to set the default on the client when communicating to a server that is following the spec appropriately.

**Comment by wangyiran125** [comment]
@jonschoning thanks,i use swagger3.0,and the  swagger-codegen-cli-3.0.0-20171009.075709-6.jar,my command is `java -jar swagger-codegen-cli-3.0.0-20171009.075709-6.jar  generate -i ~/Downloads/swagger.json --library=okhttp-gson  -l java -o /var/tmp/java_api_client`,but exception  [main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swager-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:687)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

**Comment by wing328** [comment]
@jonschoning is right in saying that the API client does not take the default value (`{{{defaultValue}}}`) into account as the server should be setting the default value. (now I recall a similar discussion 2 years ago!)

**Comment by wing328** [comment]
> Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!

You may want to double check the spec.

**Comment by wangyiran125** [comment]
@wing328 thanks,missing swagger input or config! may be a bug
like:https://github.com/swagger-api/swagger-codegen/issues/6517#issuecomment-337279894

**Comment by wing328** [comment]
@wangyiran125 can you try the 2.3.0 SNAPSHOT instead?

**Comment by wangyiran125** [comment]
@wing328 tried 2.3.0,but the same exception when i use swagger 3.0  Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!

**Comment by wing328** [comment]
@wangyiran125 can you please share the spec (e.g. via gist.github.com)?

**Comment by dfrommi** [comment]
Is there an update on the issue?
I'm using swagger-codegen 3.0.8 and have the same issue. The default value is not showing up in the model. 

It's not an template-issue. I've used a debugger to verify the `CodegenModel` and while `minimum` and `maximum` are properly set, `default` is `null` in the `CodegenParameter`.

Here's an enhanced operation of the pet store having the issue:

```yaml
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - petstore
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
```

**Comment by HugoMario** [comment]
hi @dfrommi 
can you please try with recent with [latest version](https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.19/swagger-codegen-cli-3.0.19.jar) ?

**Comment by dfrommi** [comment]
Hi @HugoMario

Took a bit now to test it, because I'm using a custom generator and had to fix some things for the update. 

**Yes, it is working with version 3.0.19**

Thanks a lot and sorry for the confusion.
