### ISSUE TITLE
[Typescript][Angular] File uploads not working

### ISSUE THREAD

**Issue by itsTeknas** [swagger-api/swagger-codegen#6789]
##### Description

Methods generated with the client generated by angular2-typescript do not handle file uploads properly.

##### Swagger-codegen version

Live editor.swagger.io version. I don't know which one they use.

##### Swagger declaration file content or url

Any method declared with a file is affected.
```
/upload_doc:
    post:
      consumes: 
        - multipart/form-data
      parameters: 
        - name: file
          type: file
          in: formData
          required: true
      responses:
        200:
          description: OK
```

Generates something like : 

```
headers.set('Content-Type', 'application/x-www-form-urlencoded');

        if (file !== undefined) {
            formParams.set('file', <any>file);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: formParams.toString(),   <-----  is this correct ?
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
```

##### Suggest a fix/enhancement

The Following typescript code seems to works fine to post a file to a server.
```
const formData: FormData = new FormData();
formData.append('file', file, file.name);
this.http.post(target, formData, options);
```

P.S. I'm new with angular, i might be making some mistakes calling the method which i am not aware of.

**Comment by wing328** [comment]
> Live editor.swagger.io version. I don't know which one they use.

Please try the latest master (2.3.0), which has a lot of enhancements. SNAPSHOT version of 2.3.0 JAR can be found in the project's README.

**Comment by macjohnny** [comment]
@itsTeknas @wing328 this was fixed with https://github.com/swagger-api/swagger-codegen/issues/6457 (https://github.com/swagger-api/swagger-codegen/pull/6574)
