### ISSUE TITLE
Jaxrs-cxf server generation compilation error, because of cannot find symbol error

### ISSUE THREAD

**Issue by devdream02** [swagger-api/swagger-codegen#6791]
##### Description

I am trying to generate the jaxrs-cxf server stub using swagger codegen maven plugin v2.2.3, while i try to build the project its throwing me below compilation error.

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/devyansh.mittal/Downloads/e1-protocol-library/e1-protocol-library-service-api/target/generated-sources/swagger/src/main/java/io/swagger/api/impl/ProtocolLibraryApiServiceImpl.java:[4,24] cannot find symbol
  symbol:   class PlApiResponse
  location: package io.swagger.model
[ERROR] /C:/Users/devyansh.mittal/Downloads/e1-protocol-library/e1-protocol-library-service-api/target/generated-sources/swagger/src/main/java/io/swagger/api/impl/ProtocolLibraryApiServiceImpl.java:[5,24] cannot find symbol
  symbol:   class Protocol
  location: package io.swagger.model
[ERROR] /C:/Users/devyansh.mittal/Downloads/e1-protocol-library/e1-protocol-library-service-api/target/generated-sources/swagger/src/main/java/io/swagger/api/impl/ProtocolLibraryApiServiceImpl.java:[20,55] cannot find symbol
  symbol: class ProtocolLibraryApi
[ERROR] /C:/Users/devyansh.mittal/Downloads/e1-protocol-library/e1-protocol-library-service-api/target/generated-sources/swagger/src/main/java/io/swagger/api/impl/ProtocolLibraryApiServiceImpl.java:[21,39] cannot find symbol
  symbol:   class Protocol
  location: class io.swagger.api.impl.ProtocolLibraryApiServiceImpl
[ERROR] /C:/Users/devyansh.mittal/Downloads/e1-protocol-library/e1-protocol-library-service-api/target/generated-sources/swagger/src/main/java/io/swagger/api/impl/ProtocolLibraryApiServiceImpl.java:[21,12] cannot find symbol
  symbol:   class PlApiResponse
  location: class io.swagger.api.impl.ProtocolLibraryApiServiceImpl

##### Swagger declaration file content or url

```yaml
swagger: "2.0"
info:
  description: "PL API"
  version: "1.3"
  title: "Protocol-Library-Api"
  license:
    name: "Devyansh Mittal"

schemes:
  - http
  
host: "localhost"
basePath: "/api/v1"

consumes:
  - "application/json"
produces:
  - "application/json"

tags:
- name: "protocolLibrary"
  description: "Protocol library API endpoints"


paths:
  /copyProtocol:
    post:
      tags:
      - "protocolLibrary"
      summary: "Copy a protocol to User's Data Manager"
      description: "Copy a protocol to User's Data Manager"
      operationId: "copyProtocol"
      parameters:
      - in: "body"
        name: "body"
        description: "Asset ID of protocol to be saved, Target's Parent ID, New name of protocol (Optional)"
        required: true
        schema:
          $ref: "#/definitions/Protocol"
      
      responses:
        200:
          description: "Copied successfully"
          schema:
            $ref: "#/definitions/ApiResponse"
          examples: 
            application/json:
             {
                "assetId": "b77437f5-d7b3-449-a026-c8d06aaa2d2"
             }
        403:
          description: Forbidden


definitions:
  Protocol:
    type: object
    required:
          - "parentId"
          - "assetId"
    properties:
          parentId:
            type: "string"
            description: "Parent ID of the target folder."
            example: "home:533c54ac-9afc-454e-bd86-b87f86224646"
          assetId:
            type: "string"
            description: "Asset ID of the protocol to be saved."
            example: "b77437f5-d7b3-449-a026-c8d06aaa2d2"
          protocolName:
            type: "string"
            description: "New name of the Protocol after saving."
            example: "new cfDNA2mlDuo"
  
  ApiResponse:
    type: "object"
    properties:
      assetId:
        type: "string"
        description: "Asset ID of the protocol saved in User's Data Manager."
        example: "b77437f5-d7b3-449-a026-c8d06aaa2d2"

**Comment by wing328** [comment]
Can you please try the latest master (2.3.0)? SNAPSHOT version can be found in the README

**Comment by wing328** [comment]
Closing this as there's no update.
