### ISSUE TITLE
[RUBY] additionalProperties generates Array type-check instead of Hash

### ISSUE THREAD

**Issue by kaelumania** [swagger-api/swagger-codegen#6793]
##### Description

When a model of type `object` is used with `additionalProperties` declaring a sub-schema, the generated ruby model code does a type-check on `Array` instead of `Hash`.

See the following code mentions:
- [partial_model_generic](https://github.com/swagger-api/swagger-codegen/blob/7bbe3dcb53e849f6be809a99ef93b82851dd9a9e/modules/swagger-codegen/src/main/resources/ruby/partial_model_generic.mustache#L60)
- [Petstore](https://github.com/swagger-api/swagger-codegen/blob/e3a1e308c445aee433f8eacdcf8550e5258f8bf9/samples/client/petstore/ruby/lib/petstore/models/additional_properties_class.rb#L48)

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```yaml
MyModel:
    type: object
    properties:
      id:
        description: id of the model
        type: string
      map_of_things:
        type: object
        additionalProperties:
          $ref: '#/definitions/Thing'

Thing:
    description: A thing
    type: object
    properties:
      value:
        description: The value
        type: object
      timestamp:
        description: A timestamp
        type: string
        format: date-time
```

##### Command line used for generation

`swagger-codegen generate -i ./swagger.json -l ruby`

##### Steps to reproduce

1. Setup swagger file
2. Run generation command
3. Try to `initialize` model with a Hash of things, e.g. `{"thing1": {value: 123, timestamp: ...}}`
4. Observe that `model.map_of_things` is not set

**Comment by wing328** [comment]
@kaelumania thanks for reporting the issue. Can you try the latest master (2.3.0) to see if the issue persists? SNAPSHOT version of 2.3.0 can be found in the README.

**Comment by kaelumania** [comment]
@wing328 thanks for the quick response. Yes, in version `2.3.0` the issue still exists. Or do I need to convert my map of maps into some kind of Array structure before putting it into the model?

**Comment by kaelumania** [comment]
@wing328 I changed the template part to
```
        {{#isContainer}}
        {{#isListContainer}}
        if (value = attributes[:'{{{baseName}}}']).is_a?(Array)
          self.{{{name}}} = value
        end
        {{/isListContainer}}
        {{^isListContainer}}
        if (value = attributes[:'{{{baseName}}}']).is_a?(Hash)
          self.{{{name}}} = value
        end
        {{/isListContainer}}
        {{/isContainer}}
``` and it works for me. But I can not estimate if this is the best/correct solution.

**Comment by wing328** [comment]
@kaelumania the fix looks good to me 👍  
I would suggest replacing the following
```
        {{^isListContainer}}
        if (value = attributes[:'{{{baseName}}}']).is_a?(Hash)
          self.{{{name}}} = value
        end
        {{/isListContainer}}
```
with 
```
        {{^isMapContainer}}
        if (value = attributes[:'{{{baseName}}}']).is_a?(Hash)
          self.{{{name}}} = value
        end
        {{/isMapContainer}}
```
which should also work

**Comment by kaelumania** [comment]
@wing328 I think the `^` before `^isMapContainer` in your example is wrong?

**Comment by wing328** [comment]
@kaelumania sorry for the typo. Just updated it.

**Comment by wing328** [comment]
@kaelumania I wonder if you can submit a PR for the fix when you've time.

**Comment by kaelumania** [comment]
@wing328 I did a PR, hopefully that matches your expectations.
