### ISSUE TITLE
[ELIXIR] Bug dialyzer typespecs not correct for Tesla API calls

### ISSUE THREAD

**Issue by edescourtis** [swagger-api/swagger-codegen#6798]
##### Description

`%Tesla.Client{}` uses typical middlewares such as `Tesla.Middleware.Timeout` or `Tesla.Middleware.Fuse`. When a server is unreachable for example the return value is usually something like `{:error, :unavailable}`. And in some cases, an exception can be thrown. However, the typespec generated by swagger codegen doesn't take this into account resulting in tons of error when doing type checking with dialyzer.

##### Swagger-codegen version

3.0.0 and latest master

##### Command line used for generation

defaults

##### Steps to reproduce

Generate code for any spec

##### Related issues/PRs

None

##### Suggest a fix/enhancement

See [here](https://github.com/swagger-api/swagger-codegen/blob/66cbab1947b3a4025cd9fa6a8d1bc3a0ed4457d6/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ElixirClientCodegen.java#L631) for how the typespec is generated. This should probably include `no_return` and `{:error, term}` to be accurate given it's nearly impossible to predict all errors that all middlewares can generate.

**Comment by wing328** [comment]
@edescourtis thanks for reporting the issue. May I know if you've time to submit a PR with the suggested fix?

cc @niku @chingor13

**Comment by edescourtis** [comment]
Perhaps! I will see what I can do.

**Comment by niku** [comment]
@earldouglas 
Hi, I just publish [a PR](https://github.com/swagger-api/swagger-codegen/pull/6821) that fixes typings in `RequestBuilder`.
The changes have fixed a lot of error more than I expected 😅 

I guess It removes errors that is described in this issue.
So, I recommend  checking that PR before you tackle this issue.

**Comment by earldouglas** [comment]
@niku I think you meant to mention @edescourtis

**Comment by niku** [comment]
I'm very sorry for making a wrong mention 🙇

**Comment by niku** [comment]
Now, I send a mention to @edescourtis 
Please read a comment https://github.com/swagger-api/swagger-codegen/issues/6798#issuecomment-339714863

**Comment by wing328** [comment]
@edescourtis https://github.com/swagger-api/swagger-codegen/pull/6821 by @niku has been merged into master. Please pull the latest master or use the SNAPSHOT version mentioned in the README to give it a try.
