### ISSUE TITLE
[Java] @Deprecated annotation fix

### ISSUE THREAD

**Issue by brian-byungsookim** [swagger-api/swagger-codegen#6800]
##### Description
OAS 2.0 supports deprecated methods, and the Java libraries should reflect that. There was a previous PR related to this, but that didn't include the actual Java `@Deprecated` method annotations.

##### Swagger-codegen version
2.3.0

##### Related issues/PRs
https://github.com/swagger-api/swagger-codegen/pull/6166

##### Suggest a fix/enhancement
Will submit a PR fixing this.

**Comment by wing328** [comment]
Fixed via https://github.com/swagger-api/swagger-codegen/pull/6801
