### ISSUE TITLE
PHP Authorization Not Working

### ISSUE THREAD

**Issue by efecarranza** [swagger-api/swagger-codegen#6807]
##### Description

Hi, I am currently using swagger-codegen to generate an SDK. We've added basic authorization to our API and I want the SDK to have the username/password already so I can make requests.
If I'm reading the documentation correctly, this should be possible, and I don't have to manually set the username and password every time I'm going to use the SDK from my App.

The client that's generated from my swagger.json file with the options listed below, knows that it needs security, but I have to manually add the username and password as follows:

```
Billing\Sdk\Configuration::getDefaultConfiguration()->setUsername('YOUR_USERNAME');
Billing\Sdk\Configuration::getDefaultConfiguration()->setPassword('YOUR_PASSWORD');
```

Is this how it's supposed to be and my issue is a non-issue?

##### Swagger-codegen version

Using 2.2.3

##### Command line used for generation

I'm trying the following, which I got from here: https://stackoverflow.com/questions/42119616/using-swagger-codegen-with-username-and-password-basic-auth

`swagger-codegen generate -i ~/path/to/file/swagger.json -o ~/path/to/output/ -l php -a "Authorization: Basic Base64encodedstring"`

and also:

`swagger-codegen generate -i ~/path/to/file/swagger.json -o ~/path/to/output/ -l php -a "username:password"`

##### Steps to reproduce

Pass -a or --auth option when generating from swagger.json file.

**Comment by wing328** [comment]
@efecarranza do you mean you want to hardcode the username and password in the PHP API client?

**Comment by efecarranza** [comment]
hey @wing328 thanks for the prompt reply. What i understood was that passing --auth and my username:password would set it in the config, so I wouldn't have to add it elsewhere in my app. if that's not the case I can close the issue.

if that's not the case, what does passing --auth do exactly then?

thanks

**Comment by wing328** [comment]
If the URL to the specification (e.g. https://api.security.org/swagger.json) is protected with HTTP basic authentication, one can use the `--auth` parameter provide the username and password to access the protected spec.

We do not recommend hard-coding username/password in the mustache templates or auto-generated code.

**Comment by wing328** [comment]
Btw, 2.3.0 (master) has the PHP client refactored. Please give it a try and let us know if you've any feedback. SNAPSHOT version of 2.3.0 (master) can be found in the project's README

**Comment by efecarranza** [comment]
@wing328 thanks for explaining that to me. i was reading it wrong.
