### ISSUE TITLE
[Swift4] required=true parameters should not be optionals

### ISSUE THREAD

**Issue by inforeqd512** [swagger-api/swagger-codegen#6827]
##### Description

For parameters that are marked as required in Swagger, the generated model objects currently show them as optional. 

Can you pls have it so they are not optionals and are definitely initialized and, assertion failed/given a type safe default, when deserializing it from JSON

##### Swagger-codegen version

Currently 2.2.3

##### Swagger declaration file content or url

NA

##### Command line used for generation

NA

##### Steps to reproduce

NA

##### Related issues/PRs

NA

##### Suggest a fix/enhancement

in description above

**Comment by wing328** [comment]
@inforeqd512 given that you're using 2.2.3, please try the latest master (SNAPSHOT version available in the README)

**Comment by wing328** [comment]
Closing this as there's no update.
