### ISSUE TITLE
[QT5CPP] Code generator does not handle the additionalproperties section of the yaml for qt5cpp

### ISSUE THREAD

**Issue by etherealjoy** [swagger-api/swagger-codegen#6841]
Code generator does not handle the **additionalproperties** section of the yaml for qt5cpp

##### Description

Whenever the yaml have **additionalProperties** the generated code is missing handling for the QMap caused by the arbitrary name of the property.

when the **additionalProperties** is referencing an array the generated code is also missing handling the QList from the additional property which may then host a normal property.

##### Swagger-codegen version

The problem is reproducible in v2.2.3 and v3.0.0
It is not a regression.

##### Swagger declaration file content or url

https://docs.docker.com/engine/api/v1.31/swagger.yaml

##### Command line used for generation

java -jar /home/dev/swagger-codegen/swagger-codegen-cli-3.0.0-20171009.075709-6.jar generate -i /mnt/YoctoDisk/genivi/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/docker-v132-subset.yaml -o /mnt/YoctoDisk/genivi/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/gen-qt1 -l qt5cpp

java -jar /home/dev/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /mnt/YoctoDisk/genivi/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/docker-v132-subset.yaml -o /mnt/YoctoDisk/genivi/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/gen-qt1 -l qt5cpp

##### Steps to reproduce

Have the yaml code referencing additional properties pointing to an array type, and then the code generation is missing some steps to deserialize the json data.

##### Related issues/PRs

I have not seen this issue yet in the known issues

##### Suggest a fix/enhancement

- fix handling of QMap for the additionalproperties arbitrary section.
- provide means to access the QMap for both key and json value
- when the QMap has an array as JSon value there has to be a way to access that

**Comment by wing328** [comment]
@etherealjoy thanks for reporting the issue. Can you please try the below?
- 2.3.0 (latest master)
- "cpprest" generator in the latest master, which should have better support of "map" via https://github.com/swagger-api/swagger-codegen/pull/5884

**Comment by etherealjoy** [comment]
@wing328 
I tried the v2.3.0, apparently the fix was for cpprest. This issue is present in qt5cpp.
So the issue still exists. I fixed manually by hand some models. but since there are many models I cannot fix each and everyone. :(

**Comment by etherealjoy** [comment]
@wing328 OK, I fixed the mustache template for generating the additional properties.

Now I discovered another bug. I will create another issue for it.

**Comment by wing328** [comment]
> I fixed the mustache template for generating the additional properties.

Please file a PR with the fix when you've time.

> Now I discovered another bug. I will create another issue for it.

Yes, please and have a nice weekend.

**Comment by wing328** [comment]
@etherealjoy when you've time, I wonder if you can contact me via my email address on my Github profile. Thanks.

**Comment by wing328** [comment]
@etherealjoy sorry, please send me another email again when you've time as I've lost your previous email.
