### ISSUE TITLE
Unable to find error in yaml file based on output

### ISSUE THREAD

**Issue by GioviQ** [swagger-api/swagger-codegen#6848]
##### Description

Based on the output
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('#' (code 35)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at APIREST+Corrispettivi+gestionali.yaml; line: 1, column: 2]

I don't know how to fix yaml file

I tried to add # before $ref with no success.

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url
http://www.agenziaentrate.gov.it/wps/wcm/connect/9ce8ea74-ebc4-4723-8494-a8d0227004d2/APIREST+Corrispettivi+gestionali.yaml?MOD=AJPERES&CACHEID=9ce8ea74-ebc4-4723-8494-a8d0227004d2

##### Command line used for generation

-l android -o "D:\temp" --api-package  "it.gov.agenziaentrate.api"

**Comment by jimschubert** [comment]
@GioviQ I've opened swagger-api/swagger-parser#564 with this report, as this appears to be either a bug with swagger-parser or Jackson.

**Comment by ryandavis84** [comment]
Both android and java worked fine for me when building from the master branch.

**Comment by gracekarina** [comment]
Hi, @jimschubert, @GioviQ it seems like there is a TAB (t) in line 124 of the file, I have removed it and it generates ok, and also parses ok.
Please let me know if this solves your issue

**Comment by gracekarina** [comment]
Hi, this issue is being close due to inactivity.
