### ISSUE TITLE
[TypeScript-Angular2] need help using the generated code / how to post the payload

### ISSUE THREAD

**Issue by Bulledesavon** [swagger-api/swagger-codegen#6855]
##### Description
Hi,

I'm working on an Angular 2 app calling Rest services built using swagger-maven-plugin 3.1.5.
Here is Java my web-service:
```
    @Path(value = "myUrl")
    @POST
    @ApiOperation(value = "...", response = String.class)
    @Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
    @Consumes(MediaType.APPLICATION_JSON)
    public String callMyUrl(final Someone someone, @Context final HttpServletRequest request,
            @Context final HttpServletResponse response) {
```

where "Someone" is this POJO:
```
public class Someone implements Serializable {
    private String name;
    private String phone;
    [...getters ans setters...]
}
```

Before using swagger-codegen, I used to call this service from Angular2 this way, and it works:
```
    callMyUrl(someone: { name: string; phone: string }): Observable<void> {
        return this.http.post(this.baseUrl + '/foo/myUrl', someone)
            .map(value => {
                // something
            })
    }
```

Now, I want to use the Api classes generated by swagger-codegen-maven-plugin 2.2.3 plugin. Here is my maven config for this:
```
			<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>2.2.3</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${pathToTheJsonFile}</inputSpec>
							<language>typescript-angular2</language>
							<output>${project.basedir}/dist</output>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

The TypeScript generated code looks like this:
```
    public callMyUrl(extraHttpRequestParams?: any): Observable<string> {
        return this.callMyUrlWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    public callMyUrlWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/foo/myUrl';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json',
            'application/xml'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }
```

My problem is that I can't figure out how to post my payload (name and phone).
If I call `callMyUrl({name:this.name, phone:this.phone})`, the server gets someone=NULL.

What am I missing?

Thanks

##### Swagger-codegen version
swagger-codegen-maven-plugin 2.2.3

**Comment by HermenOtter** [comment]
@Bulledesavon Can you post the yaml/json file you generate from?

**Comment by macjohnny** [comment]
@Bulledesavon your `callMyUrl()` does not seem to have any parameters defined, which is why nothing is transferred as payload. you need to define the request body in your yaml file. If you want to transfer arbitrary parameters, you can do so by simply calling `this.http.request()` in your service (not the generated one).

**Comment by Bulledesavon** [comment]
@macjohnny thank you, you helped me to find out what I did wrong.
Indeed, the json file produced by swagger-maven-plugin and used by swagger-codegen-maven-plugin did not contain any information about the payload.
I added an annotation to my service definition and now my service is working:
`    @Path(value = "myUrl")
    @POST
    @ApiOperation(value = "...", response = String.class)
    @Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
    @Consumes(MediaType.APPLICATION_JSON)
    public String callMyUrl(**@ApiParam(value = "documentation...")** final Someone someone, @Context final HttpServletRequest request,
            @Context final HttpServletResponse response) {`

What bugged me was that calling `this.http.post(this.baseUrl + '/foo/myUrl', someone)` worked without any @ApiParam annotation, so I didn't think it was necessary.

Thanks again
