### ISSUE TITLE
Use one client for Android and Java

### ISSUE THREAD

**Issue by karussell** [swagger-api/swagger-codegen#686]
As noted in #684: please merge the client for Android and Java, e.g. via using [okhttp](https://github.com/square/okhttp/)

**Comment by xhh** [comment]
:+1: okhttp seems to support PATCH, which would fix #682

**Comment by xhh** [comment]
[Retrofit](https://square.github.io/retrofit/) looks nice too, it uses okhttp by default.
The ability of turning REST API into Java interfaces without the needs of implementation details would make the generated client pretty slim.

**Comment by wing328** [comment]
Closing this as this is supported by the "okhttp-gson" template.
