### ISSUE TITLE
[kotlin] Model names need to be sanitized

### ISSUE THREAD

**Issue by jimschubert** [swagger-api/swagger-codegen#6864]
##### Description

An model definition named "TestNs.TestClass" should be converted to `TestNsTestClass`.

##### Swagger-codegen version

2.2.3+

##### Swagger declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Test API"
  },
  "host": "localhost:8080",
  "schemes": [ "https" ],
  "paths": {
    "/": {
      "get": {
        "summary": "test api",
        "operationId": "getRoot",
        "consumes": [ ],
        "produces": [ "application/json" ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": { "$ref": "#/definitions/TestNs.TestClass" }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "TestNs.TestClass": {
      "properties": {
        "which": {
          "enum": [ "Value1", "Value2" ],
          "type": "string"
        }
      }
    }
  }
}
```

##### Command line used for generation

```
generate -l kotlin -i swagger.json -o out
```

##### Steps to reproduce

Try generating with model definition names containing non-alphanumeric characters.

Examples:

* `TestNs.TestClass`
* `This is a test`
* `One<Two`

etc.

##### Related issues/PRs

* #6858

##### Suggest a fix/enhancement

Update the model name method to sanitize model names in a way similar to how I've sanitized enum property names in #6858.

**Comment by wing328** [comment]
Closed via #6874
