### ISSUE TITLE
[Android] [JAVA] Automated request parameter generation using swagger in DefaultTest.class file.

### ISSUE THREAD

**Issue by SanjuChauhan** [swagger-api/swagger-codegen#6871]
I want to generated Model Request parameter automatically in test cases
for example , in my model there are two variable with setter and getter methods as shown below.

I am using Swagger-codegen version 2.2.3.
```
public class LoginModel{
	public String username;
	public String password;
	
	public void setUserName(String username){
		this.username = username;
	}
	public String getUserName(){
		return this.username;
	}
       ...
}
```
and i want this to be generated by swagger in DefaultTest.class file.
```
LoginModel loginModel = new LoginModel();
        loginModel.setUserName("Abc");
        loginModel.setPassword("abc123");
```
is there any other way to generate it using custom template?
please suggest.
thanks...!!!

**Comment by wing328** [comment]
You can definitely customize the templates and use the `-t` parameters when generating the client (Java, Android)
