### ISSUE TITLE
body parameters are not requiredParams

### ISSUE THREAD

**Issue by jonschoning** [swagger-api/swagger-codegen#6878]
```
------------------------------|~~~~~~~~~~~~~~~~|
                if (p.required || p.isBodyParam) {
                    requiredParams.add(p.copy());
```
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2238-L2239

c.f. c2eb53ab1d86a8eb4d993dc913ee8948b4cf0055

**Comment by wing328** [comment]
You're right. Body parameters can be optional as well.

Let me fix it shortly.

**Comment by wing328** [comment]
Filed https://github.com/swagger-api/swagger-codegen/pull/6885

**Comment by wing328** [comment]
@jonschoning the fix has been merged into master. Please pull the latest master to give it a try.
