### ISSUE TITLE
[Kotlin] select date library

### ISSUE THREAD

**Issue by magiepooh** [swagger-api/swagger-codegen#6892]
##### Description

select date library like Java Generator.

##### Swagger-codegen version

2.2.3+

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/5730

##### Suggest a fix/enhancement

`generate -i swagger.yaml -l kotlin  -o out -DdateLibrary=threetenbp`

**Comment by wing328** [comment]
@magiepooh thanks for the feedback. May I know if you've time to contribute the enhancement?

**Comment by magiepooh** [comment]
I'll work on this!

**Comment by magiepooh** [comment]
Related PR: https://github.com/swagger-api/swagger-codegen/pull/7516

**Comment by wing328** [comment]
Thanks again for the PR. Closing this.
