### ISSUE TITLE
Generated Lumen code can contain dots in routes

### ISSUE THREAD

**Issue by philip** [swagger-api/swagger-codegen#6897]
Lumen does not allow `.` in routes. The generator allows them without warning. Dots in URLs are common though, for example `/api/v1.1/`, but Lumen insists on not allowing them.

Confirmation about dots being disallowed in routes: https://github.com/laravel/framework/issues/6180

**Comment by wing328** [comment]
@philip yes, we should be able to fix it easily in the postProcessOperations.

Is that something you can contribute? If yes, I can show you a good starting point.

**Comment by philip** [comment]
@wing328 I'm interested, all pointers are welcome. Also, thoughts on what to do here e.g., replace them with something, fail, or allow this to be configured somehow.

**Comment by wing328** [comment]
My take is to throw an exception as it's something not supported by Lumen.

As you mentioned we can replace it with something else but still the clients (PHP, Python, etc) generated from the spec expect the `.` in the path.

Please refer to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/FinchServerCodegen.java#L210 on how we loop through all the path in `postProcessOperations`

**Comment by philip** [comment]
@win328 I remember testing paths with dots and they failed, and removing the dots caused it all to work. However now I can't replicate this so am baffled and confused. Tested Lumen 5.2, 5.4, and 5.5. I switched to codegen on docker but don't understand how that'd change things.

On the bright side the lumen generator is working for my use case so I hope to expand its general usage and functionality. Although I fear this bug will make a comeback but we'll see.

Related, using Lumen 5.5 required other code updates but considering 5.5 is LTS I think it might be worth it.

**Comment by wing328** [comment]
@philip thats ok. We'll open this if any reports similar issue.

I've created https://github.com/swagger-api/swagger-codegen/issues/6963 to track the Lumen veresion upgrade.

**Comment by wing328** [comment]
FYI. I've filed https://github.com/swagger-api/swagger-codegen/pull/6986 to throw an exception if dot is found in the path.

**Comment by chrillep** [comment]
same goes for laravel.
