### ISSUE TITLE
[LagomScala] Add Scala API  generator for lagomframework

### ISSUE THREAD

**Issue by gmkumar2005** [swagger-api/swagger-codegen#6900]
##### Description
Lagomframework is the opinionated microservices framework for moving away from the monolith
https://www.lagomframework.com/

It supports Java and Scala as primary language. 
A typical project in lagom has an API, Server Impl [or a server consuming the API] and UI. API project is used for both as a client as well as server. 

Is there any one working on Lagon Scala API code generator ?

There is a alpha project https://github.com/lagom/sbt-lagom-descriptor-generator
But it does not have the support for templates.  

##### Swagger-codegen version
2.3.0 and 3.0.0

Is there any one working on Lagon Scala API code generator ?

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/6901
