### ISSUE TITLE
Test endpoint returns invalid data

### ISSUE THREAD

**Issue by tomplus** [swagger-api/swagger-codegen#6907]
##### Description

http://petstore.swagger.io which is used by integration tests, returns invalid data, for example pets without name (name is required). There are a lot of such records.

##### Command line used for generation

```
curl -X GET "http://petstore.swagger.io/v2/pet/-4227537848496351315" -H  "accept: application/xml"

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <Pet>
    <id>-4227537848496351315</id>
    <photoUrls/>
    <status>sold</status>
    <tags/>
  </Pet>
```

##### Suggest a fix/enhancement

Can I delete invalid records ? Is it possible to add such records by API ? Can we reset data periodically ? 

Thanks.

**Comment by wing328** [comment]
@tomplus yes, the public petstore server contains invalid data as anyone can insert invalid records since there's no validation.

The CIs run a local copy of the Petstore server to avoid issues due to bad data.

**Comment by tomplus** [comment]
@wing328 Thanks, it's good to know. I see that some Python tests use public API, I'll fix it.

**Comment by tomplus** [comment]
Ok, I got it, CIs have /etc/hosts overwritten https://github.com/swagger-api/swagger-codegen/blob/master/.travis.yml#L31 and tests can have public server configured.
