### ISSUE TITLE
two api's with same operationid - sdk failed for both

### ISSUE THREAD

**Issue by naveenkumar-007** [swagger-api/swagger-codegen#6908]
##### Description

-->
if two api's are having same operationid, the sdk code generation is generating for only one api. How to handle this.
-->

##### Swagger-codegen version
2.2.0

**Comment by HermenOtter** [comment]
The swagger specification requires unique operationId's. Is it a problem to change the operationid?

**Comment by wing328** [comment]
@HermenOtter is correct. `operationId` needs to be unique. Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-5

You may find the following option useful:
```
        --remove-operation-id-prefix
            Remove prefix of operationId, e.g. config_getId => getId
```

**Comment by naveenkumar-007** [comment]
Leave a comment

**Comment by wing328** [comment]
Btw, 2.2.0 is an old version. The latest stable is 2.2.3 that you can find in the release page.

**Comment by naveenkumar-007** [comment]
Thanks a lot For providing info. But the requirement is like two json files needs have one operationId like
add, I am writing the java code how to handle this. can i append a request to it or else is there anyway to do it.

**Comment by naveenkumar-007** [comment]
Json file 1:
-----------
"methodName": "List",
          "request": "GetArrayRequest",
Json file 2:
----------------
"methodName": "List",
          "request": "GetSNMPRequest",

**Comment by wing328** [comment]
You can add a prefix, e.g. GetArrayRequest_List, GetSNMPRequest_List and then use `--remove-operation-id-prefix`  when generating the client.

Please email me if you need further help on this. (you can find my email in my 
Github profile page)

**Comment by naveenkumar-007** [comment]
Hi,

I tried the option as you suggested like

java -jar swagger-codegen-cli.jar generate -i sample.json -l java -o sdk
--remove-operation-id-prefix


and I got the exception like

Exception in thread "main"
io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected
parameters: [--remove-operation-id-prefix]

Please help,

Thanks,
Naveen

**Comment by wing328** [comment]
Likely you're not using the latest stable version. Please try v2.2.3

**Comment by naveenkumar-007** [comment]
Thanks a log. the latest version v2.2.3 has resolved the issue.

**Comment by naveenkumar-007** [comment]
after the sdk is created the localVarPath is comming like  
localVarPath = "/GetArrayRequest_ListSamplessample
instead  of /port
