### ISSUE TITLE
issues with uri's in swagger json file

### ISSUE THREAD

**Issue by naveenkumar-007** [swagger-api/swagger-codegen#6909]

**Comment by HermenOtter** [comment]
Can you post your yaml or json file, with an example of the uri's that cause issues? If you provide information, we might be able to help ^^.

**Comment by naveenkumar-007** [comment]
Hi HermenOtter,
Thanks a lot for quick reply.

here i am pasting sample code:

one one json:
"methodName": "List",
 "request": "GetArrayPortsRequest",
in another json:
"methodName": "List",
          "request": "ListSNMPRequest",

I have written the parser code to convert the json files into swagger spec json file.

**Comment by naveenkumar-007** [comment]
Hi,
Could you please let me know how to handle this.

**Comment by HermenOtter** [comment]
@naveenkumar-007 Your issue is resolved? You can use the '@' to notify someone of your reply. You can use codetags for yaml, json or typescript formatting. Have a nice day.

**Comment by naveenkumar-007** [comment]
Hi HermenOtter,

I have already raised another issue 6930. could you please check.

Thanks,
Naveen

**Comment by naveenkumar-007** [comment]
while constructing the uri, i am removing the part after ?. because swagger won't allow right. 

But in the uri, after quesetion mark, two parameters 

"uri": "/test/{0}/diff?block_size={1}&length={2}"
 1 and 2 are there. I don't know how to resolve the issue. It is urgent. Could you please let me know
