### ISSUE TITLE
Java ApiInvoker - Microsoft Server gives Content Length required error on null body POST

### ISSUE THREAD

**Issue by panshul007** [swagger-api/swagger-codegen#691]
I have a Microsoft Server hosted with the serving application, for which I have a generated swagger ui.
All the request work fine from the Swagger UI.
I use Swagger-codegen to generate the client for Java.
In the POST requests I get an error from the server -> Content-Length required.
So I add the Content-Length parameter to the header in the generated API invoker for the POST methods. It seems to work, but this should be handled.
I case of a null body of a POST request, adding a Content-Length parameter with 0 value does not work. I still get the Content-Length required error. So as a workaround I add a blank body with Content-Length as 1, which works.
Please suggest a better way of handling this error? or should this be handled at the server level?

I used the apiInvoker from here: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java

**Comment by xhh** [comment]
this relates to #592

**Comment by webron** [comment]
@xhh - it looks more than related. It looks identical, no?

**Comment by xhh** [comment]
@webron right, these two issues are identical. I said "relates to" because this issue's description contains info of manually setting the Content-Length header does not work either when the body is null.

**Comment by webron** [comment]
Right, so closing this one in favor of #592.
