### ISSUE TITLE
generated code of javascript client can not be used in es6 module

### ISSUE THREAD

**Issue by zzsoszz** [swagger-api/swagger-codegen#6912]
code:
const {UserApi,User} = require("../consultant/index");
import {UserApi,User} from "../consultant/index";

errors:
Failed to compile
./src/consultant/index.js
  Line 26:  'define' is not defined  no-undef
  Line 28:  'define' is not defined  no-undef

can i generate code for es6 module  enviroment?

**Comment by wing328** [comment]
Please fill out a new issue form to provide us the necessary info so that the community can help you out.
