### ISSUE TITLE
Java codegen artifact does not build if items array contains {} in object definition

### ISSUE THREAD

**Issue by kylos101** [swagger-api/swagger-codegen#6918]
The Java codegen artifact does not build if the definition of the items array is {}, [but it does pass validation in Swagger Editor, see this for a related Editor issue](https://github.com/swagger-api/swagger-editor/issues/1556).

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |   bug
| Which Swagger/OpenAPI version?      |   2.0
| Which Swagger-Editor version?       |  editor.swagger.io
| How did you install Swagger-Editor? |  n/a
| Which broswer & version?            | Chrome 62
| Which operating system?             | Windows 7 

### Demonstration API definition
In swagger editor, using your petstore demo, change line 670 to {} (an empty object), click on Generate Client > Java, then try "mvn install", it should fail building.

### Expected Behavior
A warning or an error in Swagger Editor.
No ability to generate a client until the spec is "valid".
Perhaps the "type" related to the empty object should be "object"?

### Current Behavior
No warning or error is displayed in S.
I am able to Generate the Java client.
The Java client cannot build, this is because class members lack type info.

```Java  
  @SerializedName("photoUrls")
  private  photoUrls = ; // see here how photoUrls lacks a type definition?
```

### Possible Solution
If this is not a valid condition ever, display an error in Editor, and prevent Codegen from producing a client.

### Context
I shared my YAML with a coworker (it didn't have any errors).
They tried generating a Java client, and were unable to build it.

**Comment by wing328** [comment]
Please try the latest stable version 2.3.1 and let us know if you still experience the issue.
