### ISSUE TITLE
Java AsyncHttpClient

### ISSUE THREAD

**Issue by panshul007** [swagger-api/swagger-codegen#692]
I have a Java client generated using codegen from a swagger specification. 
Currently in the ApiInvoker, it is using a blocking Jersey Client for http requests.
 
 * How can I make it a non-blocking async client?
 * Is there a way other than replacing the apiInvoker implementation manually with something like Apache HttpAsyncClient ?

**Comment by fehguy** [comment]
hi, yes, you can easily change the templates.  Look at [api.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/api.mustache).  Modify the template and pass -t {template-path} when invoking the cli.
