### ISSUE TITLE
Python Generated PetStore doesn't read sucessfully

### ISSUE THREAD

**Issue by kvlahromei** [swagger-api/swagger-codegen#695]
Hi,

I used the official petstore file (http://petstore.swagger.io/v2/swagger.yaml) in teamwork with the editors alpha client generator to get an python client [like you ship it](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/python) with the codegen itself.

Unfortunatly after installing the package in my virtualenv and after fixing some minor changes (e.g. it's no more petId like in your sample) I get always an 500 error if I try to read a status:
```python
...
petApi.findPetsByStatus(status="pending")
```
>/usr/lib/python2.7/urllib2.pyc in http_error_default(self, req, fp, code, msg, hdrs)
    529 class HTTPDefaultErrorHandler(BaseHandler):
    530     def http_error_default(self, req, fp, code, msg, hdrs):
--> 531         raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    532 
    533 class HTTPRedirectHandler(BaseHandler):
HTTPError: HTTP Error 500: Server Error

To my suprise the 'add-a-pet-and-read-it-back' part works ok, but the same problem appears if I try to read another pet id (that exits but wasn't touched before).

**Comment by wing328** [comment]
Please test with the `develop_2.0` branch instead of the alpha client generator. 

If I remember correctly, the `develop_2.0` has a few bug fixes for the Python client.

**Comment by webron** [comment]
@kvlahromei - can you retest please with develop_2.0?

**Comment by wing328** [comment]
@kvlahromei we'll close this task as we've not heard from you. Please test with the latest and let us know if you encounter any issue.

**Comment by webron** [comment]
Closed for lack of activity.
