### ISSUE TITLE
[Java][google-api-client] Minor bugs with google-api-client templates

### ISSUE THREAD

**Issue by charlescapps** [swagger-api/swagger-codegen#6950]
##### Description

There are some minor bugs in the new `google-api-client` Java library.
* @wing328 made a reasonable change so that the `requiredParams` property on a `CodegenOperation` is actually just the required params (not required params OR body param). That broke the codegen for `google-api-client`. I think the change is good since the property should be what its name implies, so I'm fixing the `google-api-client` templates to work with this and leaving @wing328's change as-is. 
* Spacing in some generated code
* Passing in an immutable map for the overloaded methods with query params as a map was causing an explosion, but it's a common practice to want to work with immutable maps.

##### Swagger-codegen version

Latest (2.3.0-SNAPSHOT)

##### Swagger declaration file content or url

Use samples, see reproduction steps below.

##### Command line used for generation

You can simply generate samples to reproduce this with `./bin/java-petstore-google-api-client.sh`. Then you can verify that the generated modules aren't compiling, and the code has some funny spacing in `ApiClient.java`'s imports, as well as funny spacing in some of the generated APIs.

##### Steps to reproduce

Ditto. Just generate samples and verify they don't compile. Also some funny spacing.

##### Related issues/PRs

n/a

##### Suggest a fix/enhancement

I'm going to fix this soon with a pull request.

**Comment by wing328** [comment]
Fixed via #6951

**Comment by charlescapps** [comment]
Thanks! I'm glad to get this in with the next release.
