### ISSUE TITLE
Specify Media format type

### ISSUE THREAD

**Issue by swavans** [swagger-api/swagger-codegen#6958]
Okay so this is more of a question I guess cause this should be possible I think.

I have an API endpoint using swashbuckle and swagger specs 2.0 and it returns a string formatted in the mediaformattype "text/plain". 

But when I use this it will create a (C#) SDK that will use mediaformattype "aplication/json"
If I try to override for example the "Accept" header with the add defaultheader method  I get an exception on invocation saying it's already set.

**Comment by wing328** [comment]
Can you please share the spec so that we can more easily reproduce the issue?

**Comment by swavans** [comment]
Hi Sorry for the late response, I'm not sure what you mean by spec?
So it looks like this:
`{
  "swagger": "2.0",
  "info": {
    "version": "v",
    "title": "v"
  },
  "host": "localhost:3000",
  "schemes": [
    "https"
  ],
  "paths": {
    "/Rest/Action": {
      "post": {
        "tags": [
          "Rest/Action"
        ],
        "operationId": "Authentication_Action",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SomeModel"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
  },
  "definitions": {
    "SomeModel": {
      "required": [
        "username",
        "ipAddress",
      ],
      "type": "object",
      "properties": {
        "username": {
          "maxLength": 50,
          "minLength": 0,
          "type": "string"
        },
        "ipAddress": {
          "maxLength": 50,
          "minLength": 0,
          "type": "string"
        }
      }
    }
  }
}`

**Comment by swavans** [comment]
@wing328 Is this all you needed?

**Comment by wing328** [comment]
Can you give it another try by updating your spec to set `consumes` to `text/plain`?
