### ISSUE TITLE
Java Async ApiInvoker Sample

### ISSUE THREAD

**Issue by panshul007** [swagger-api/swagger-codegen#696]
Currently If I use the sample api.moustache and apiInvoker.moustache for any of the Java examples I get a synchronous implementation generated.

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/src/main/java/io/swagger/client/ApiInvoker.java

It will be really helpful if you can please provide with an example or a sample code with an asynchronous implementation in Java for an api and api Invoker.

**Comment by xhh** [comment]
@panshul007 async request has not been supported in the default Java client codegen, but is supported in the `okhttp-gson` template of Java client codegen (via the `library` option).
Please take a look at the `executeAsync` method in [ApiClient.java](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/ApiClient.java#L657) and give it a try.
An example of calling the [`getPetByIdAsync`](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/java/okhttp-gson/src/main/java/io/swagger/client/api/PetApi.java#L323) method is:

```java
petApi.getPetByIdAsync(new Long(1), new ApiCallback<Pet>() {
    @Override
    public void onFailure(ApiException e, int statusCode, Map<String, List<String>> responseHeaders) {
        System.err.println("Failed with status code: " + statusCode);
        e.printStackTrace();
    }

    @Override
    public void onSuccess(Pet pet, int statusCode, Map<String, List<String>> responseHeaders) {
        System.out.println(pet);
    }
});
```
