### ISSUE TITLE
Swift4 codegen with PromiseKit is omitting most properties for POST

### ISSUE THREAD

**Issue by dgaedcke** [swagger-api/swagger-codegen#6962]
##### Description
Swift4 codegen with PromiseKit is omitting most properties for POST

##### Swagger-codegen version
Swagger-codegen version
2.2.3

##### Swagger declaration file content or url
partial section below
```json
https://gist.github.com/dgaedcke/8b8c2ad728e974d5d702ce5fb24eebe1
```

##### Command line used for generation

I have tried both Swift3 & 4
swagger-codegen generate \
   -i gen/http/openapi.json \
   -l swift3 \
   -o /Users/dgaedcke/Downloads \
   -c apigen_config.json

##### Steps to reproduce
Generated code:
note that ONLY "shares" (parameters) is being sent to the server 
```
    open class func ordersSubmitWithRequestBuilder(clientID: String, execMode: String, assetKey: String, quotedPrice: Float, shares: Int64, constraintMode: String? = nil, allOrNone: Bool? = nil, limitDollars: Float? = nil) -> RequestBuilder<SubmitResponseBody> {
        let path = "/orders/submit"
        let URLString = NmgGenClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: shares)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SubmitResponseBody>.Type = NmgGenClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
```

##### Suggest a fix/enhancement

Over my pay grade....I'm not even sure if this is user error or a problem with the Codegen..

**Comment by wing328** [comment]
@pixelshaded please try the latest master (2.3.0), which comes with a lot of enhancements, bug fixes in the Swift4 generator.

SNAPSHOT version of the latest master can be found in the project's README.

**Comment by dgaedcke** [comment]
thanks!!!  Will do.   Also, I had installed via HomeBrew & I'm not seeing any instructions for upgrading that.  Homebrew just keeps telling me it's already installed & search show's no other Taps.

brew search swagger-codegen
==> Searching local taps...
swagger-codegen ✔
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...

**Comment by wing328** [comment]
HomeBrew only installs the stable version.

You can download the JAR of the master snapshot in https://github.com/swagger-api/swagger-codegen#compatibility and run something like:
```
 java -jar swagger-codegen-cli-2.3.0-20170703.140356-40.jar generate \
  -i http://generator.swagger.io/api/swagger.json  \
  -l swift4 \
  -o /tmp/swift4/
```

**Comment by dgaedcke** [comment]
No....that didn't do it......generated function looks almost identical.
All the function args (except "shares") are still omitted from the final payload as shown below
I'm attaching our full spec to help debug the problem...
```
    open class func ordersSubmitWithRequestBuilder(clientID: String, execMode: String, assetKey: String, quotedPrice: Float, shares: Int64, constraintMode: String? = nil, allOrNone: Bool? = nil, limitDollars: Float? = nil) -> RequestBuilder<SubmitResponseBody> {
        let path = "/orders/submit"
        let URLString = NmgApiAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: shares)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SubmitResponseBody>.Type = NmgApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
```

**Comment by dgaedcke** [comment]
I'm kind of blocked here....can someone please advise me?
Should I rollback to using Swift3 or is there something else I can try??

**Comment by wing328** [comment]
cc @jgavris @ehyche @Edubits @jaz-ah

**Comment by dgaedcke** [comment]
Any feedback or suggestions please??

**Comment by wing328** [comment]
> openapi.json.zip

I used https://editor.swagger.io to load the spec and got some errors. I would suggest you review the spec to first those errors.

**Comment by dgaedcke** [comment]
Ok good news!!   The problem did lie with my swagger generator.
And that developer has fixed his bug so my API is generating quite well now.

There is one problem with your promises implementation....for the latest PromiseKit
for a Promise<Void>, you are generating:
deferred.fulfill( )
when you should generate
deferred.fulfill( () )

**Comment by wing328** [comment]
Please open another issue to track the promises implementation.

**Comment by jgavris** [comment]
Do recommend using the latest release if you're on Swift 4. The latest release is not something you can get from homebrew.

**Comment by dgaedcke** [comment]
Yes...I'm on Swift 4 and using the latest version of the JAR
Opening a new issue now for the issue with the void promise return value.
