### ISSUE TITLE
Where I supposed to set the api_key value in Java generated code ?

### ISSUE THREAD

**Issue by frodrigo** [swagger-api/swagger-codegen#697]
Where I supposed to set the api_key value in Java generated code, when api_key set send as query parameter ?

**Comment by fehguy** [comment]
Currently not supported, but will be added.

**Comment by karussell** [comment]
See my hack: https://github.com/swagger-api/swagger-codegen/pull/684

**Comment by xhh** [comment]
This has been implemented by #826, see [here](https://github.com/swagger-api/swagger-codegen/pull/826/files#diff-020fa73a5bfe0a474c7664df2e509fb9R22) and [here](https://github.com/swagger-api/swagger-codegen/pull/826/files#diff-1e4023556cca7d29c4aba501832d8788R66) for examples of how to set API key.

**Comment by karussell** [comment]
Thanks. 

Still the static things are really ugly. For example Configuration: what we live in a perfect world and all APIs are implemented with swagger :) ? Then two APIs cannot use different keys or other config stuff with this approach!

**Comment by xhh** [comment]
@karussell as you can see in [the constructor of ApiClient](https://github.com/swagger-api/swagger-codegen/blob/fffc5d7c351a2a270534d70f2eea602013ed72a7/samples/client/petstore/java/src/main/java/io/swagger/client/ApiClient.java#L63), authentications are stored within an ApiClient instance, so configurations of different ApiClient instances do not interfere with each other.

what's more, ApiClient/Configuration from different SDKs shall have different packages, for example, `com.hello.ApiClient` vs `com.world.ApiClient`, so why can't use different keys or other config stuff?

**Comment by karussell** [comment]
Ah, okay. Maybe the docs are outdated. As in #826 I saw `Configuration.setApiKey("special-key");` and assumed it that way.
