### ISSUE TITLE
Windows Installation Instructions are Unclear

### ISSUE THREAD

**Issue by Grauenwolf** [swagger-api/swagger-codegen#6970]
`wget` isn't a built-in Windows command and there are no alternative installation instructions. This could really use an installer, or if not that instructions that non-Java Windows users can understand.

**Comment by wing328** [comment]
@Grauenwolf thanks for the feedback. I've revised it: https://github.com/swagger-api/swagger-codegen/blob/master/README.md#prerequisites

Please take a look to see if it's now clearer.

**Comment by Grauenwolf** [comment]
Looks good.
