### ISSUE TITLE
[Java] Add a method to edit default headers

### ISSUE THREAD

**Issue by JacC510** [swagger-api/swagger-codegen#6976]
##### Description
Similar to the configuration class from c#, it sould be possible to set the default headers for each HTTP request. 
At the moment adding deafult header will cause duplicates, beacause there is no way to remove the previous header. 

##### Swagger-codegen version

CodeGen version: 2.2.3

##### Swagger-codegen Java library 

resttemplate

##### Suggest a fix/enhancement
fix duplicate problem: 
```
public ApiClient addDefaultHeader(String name, String value) {
        if(defaultHeaders.containsKey(name))
            defaultHeaders.remove(name);
        defaultHeaders.add(name, value);
        return this;
    }
```
or add something like
```
public void setDefaultHeader(HttpHeaders headers){
       defaultHeaders = headers;
}
```

**Comment by wing328** [comment]
@JacC510 thanks for the suggestion. Please submit a PR so that we can more easily review the change.

**Comment by JacC510** [comment]
@wing328 I would do this, but I have no rights do publish a new branch.

**Comment by wing328** [comment]
Please have a look at https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements to see if it helps.

**Comment by JacC510** [comment]
@wing328 Thanks. 
Here the PR #6981
