### ISSUE TITLE
NullPointerException Thrown When Parsing Spec from marvel.com

### ISSUE THREAD

**Issue by brintoul** [swagger-api/swagger-codegen#698]
Running: 
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -v -i http://gateway.marvel.com/docs -l java -o samples/java/marvel

results in an NPE at line 230 of SwaggerCompatConverter.java

**Comment by wing328** [comment]
The Marvel Swagger spec version is 1.0, which should still be supported according to https://github.com/swagger-api/swagger-codegen#compatability

I would recommend you to try the branch `develop_2.0` to see if the issue persists.

**Comment by brintoul** [comment]
I tried the develop_2.0 branch, and the NPE is now happening at line 225 of SwappgerCompatConverer.java.

**Comment by wing328** [comment]
Seems like it's related to another project: https://github.com/swagger-api/swagger-parser/blob/09747b5ee07befb4d4c5e182b20b09025d5739a1/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java

I would recommend you to open an issue in https://github.com/swagger-api/swagger-parser

**Comment by brintoul** [comment]
Ok, will do.  Thanks!
