### ISSUE TITLE
[Angular][Typescript] Question: How do you generate multiple api's for an application in a robust way?

### ISSUE THREAD

**Issue by HermenOtter** [swagger-api/swagger-codegen#6982]
##### Description
How would one go about generating multiple API's for an application in a robust way? Currently I have 2 API's published on SwaggerHub along with an shared domain causing external references, I do not mind having to generate them separate. However the problem is that both API's generate an ApiModule import with the same name. I have looked at combining swagger definitions with swagger-parser, but I would appreciate some advise at this matter. Everything I tried till now didn't come across as robust to me. I wonder if anyone has this problem as well and if so, what is your approach to solve this problem?

##### Swagger-codegen version 
master branch 3.0

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i https://api.swaggerhub.com/apis/cars/2.2.0 https://api.swaggerhub.com/apis/bikes/2.2.0 -l typescript-angular --o "AngularWebApplication\src\app\api"`

##### Related issues/PRs

I have read related issues, but couldn't extract a good practice for my situation.

**Comment by HermenOtter** [comment]
@kenisteward @bedag-moo

**Comment by macjohnny** [comment]
where exactly does the api module naming lead to a problem?
you can simply alias the module names when importing, i.e. 
```
import { ApiModule } from 'my-api-path';
import { ApiModule as OtherApiModule } from 'my-other-api-path';

@NgModule({
  imports: [
    ApiModule, 
    OtherApiModule
  ]
})
export class CoreModule {

}
```
would this work for you?

**Comment by kenisteward** [comment]
@hermenotter what @macjohnny said

**Comment by HermenOtter** [comment]
@macjohnny Thank you for the quick reply. That is a quite simple solution that works, I didn't think of it. I will give it a try.
