### ISSUE TITLE
 [qt5cpp][cpprest] allOf in request body schema produces blank type

### ISSUE THREAD

**Issue by etherealjoy** [swagger-api/swagger-codegen#6983]
When Using allOf in the description of a body parameter then the combination of multiple ref types is not assembled to create a new type.
##### Description

using **allOf** in the parameter schema causes no type to be generated.

Generated code
_void containerUpdate(QString* id,  update);_
instead of
_void containerUpdate(QString* id, SWGResources update);_

##### Swagger-codegen version

2.2.3
2.3.0
2.4.0
3.0.0

##### Swagger declaration file content or url

```yaml
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "ID or name of the container"
          type: "string"
        - name: "update"
          in: "body"
          required: true
          schema:
            allOf:
              - $ref: "#/definitions/Resources"
              - type: "object"
                properties:
                  RestartPolicy:
                    $ref: "#/definitions/RestartPolicy"
```
##### Command line used for generation

java -jar /home/dev/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /mnt/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/yaml/docker-v132-subset.yaml -o /mnt/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/gen-qt1/ -l qt5cpp --model-name-prefix SWG
##### Steps to reproduce

Run the command with the allOf in the parameter schema

**Comment by etherealjoy** [comment]
I need help to fix this. Can someone please give me some hints?

**Comment by etherealjoy** [comment]
There is a workaround for this problem, create an intermediate type and use allOf. Then refer this intermediate type in the body schema.

**Comment by etherealjoy** [comment]
@fvarose 
Do you have an idea what to do here, if you don't mind me bothering you?

Many thanks.

**Comment by fvarose** [comment]
Sorry, I have no idea what causes this, I can maybe have a look when I find the time.

**Comment by etherealjoy** [comment]
Ok, this seems to be a problem with the swagger-codegen core when I check the referenced issue. But thanks all the same.
