### ISSUE TITLE
[qt5cpp] serializing arrays of ints causes segfault

### ISSUE THREAD

**Issue by etherealjoy** [swagger-api/swagger-codegen#6984]
When the parameter or property is an array of int, serializing it causes a seg fault.
##### Description

when an array of int is serialized, it causes a seg fault.
##### Swagger-codegen version

2.2.3
2.3.0
3.0.0
##### Command line used for generation

java -jar /home/dev/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /mnt/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/yaml/docker-v132-subset.yaml -o /mnt/genivi-dev-platform/meta-userapp/recipes-dockerctrl/dockerctrl/sources/dockerctrl-qtapp/gen-qt1/ -l qt5cpp --model-name-prefix SWG
##### Steps to reproduce

Code will build, however when an array of int is serialized, it causes a seg fault.

**Comment by wing328** [comment]
cc @ravinikam @stkrwork
