### ISSUE TITLE
NSURLSession/NSURLConnection HTTP load failed

### ISSUE THREAD

**Issue by Jenishmistry** [swagger-api/swagger-codegen#7000]
##### Description
 Hello, i am using swagger codegen for one of my project. Right now i am stuck in some situation.
In swift 3.0 when i load api with https with alamofire its working fine, but when i load api with swagger codegen api, its not working. and give me error like this, 

nw_coretls_callback_handshake_message_block_invoke_3 tls_handshake_continue: [-9812]

NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813) 

so, how can i fix this issue. ?
Thanks in advance.

##### Swagger-codegen version
swagger 2.2.3

**Comment by wing328** [comment]
Please try the latest stable version 2.3.1. I would recommend also trying the `swift4` generator as well to see if you still experience the issue.
