### ISSUE TITLE
operationId is ignored if contains periods

### ISSUE THREAD

**Issue by tomer** [swagger-api/swagger-codegen#7015]
##### Description

I'm generating a python-flask server from a yaml file which contain periods in operationIds. At the moment swagger-codegen ignore the operationId definition and replace it with names such as get_0, get_1 and so on. If I replace the period manually with an underscore everything works as expected, but since the yaml file is 3rd party, I can't change it directly in the upstream.

##### Swagger-codegen version

swagger-codegen.jar v2.2.3

##### Swagger declaration file content or url

```yaml
[snip]
 paths:
     get:
       operationId: ApplicationsDnsRules.GET
```
https://forge.etsi.org/rep/gitweb.cgi/MEC.GS_011.git/blob/HEAD:/Mp1.yaml#l127
##### Command line used for generation
```bash
java -jar swagger-codegen-cli.jar generate --additional-properties supportPython2 -l python-flask -i Mp1.yaml -o out/python-flask
```
##### Additional information
If removing the operationId from the yaml file, swagger does generate functions with better naming by default, so I suggest to *ignore* the operationId keyword if it can't be used at all.

**Comment by wing328** [comment]
@tomer Please try the latest master to see if it's still an issue. The SNAPSHOT version of the latest master (2.3.0) can be found in the README.

**Comment by tomer** [comment]
@wing328 I don't see any difference with 2.3.0-SNAPSHOT.

```bash
$ java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar version
2.3.0-SNAPSHOT
```
```bash
$ java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i Mp1.yaml --additional-properties supportPython2 -l python-flask -o out/python-flask-codegen23snapshot
[main] INFO io.swagger.parser.Swagger20Parser - reading from Mp1.yaml
[...snip...]
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_0`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_1`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_2`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_3`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_4`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `put_0`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_5`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `post_0`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_6`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `put_1`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_7`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_8`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `get_9`
```

**Comment by wing328** [comment]
@tomer from the warning message, it looks like some `operationId` are duplicated and therefore Swagger Codegen automatically generates a unique `operationId` (method name) so that the auto-generated code works right out of the box.

**Comment by tomer** [comment]
@wing328 There are no duplications, and if I replace `.GET` (or POST, DELETE, etc.) with `_GET`, it doesn't generate these method names. 

replaced 
```
       operationId: ApplicationsDnsRules.GET
```
with - 
```
       operationId: ApplicationsDnsRules_GET
```

**Comment by wing328** [comment]
@tomer let me take another look ...

**Comment by wing328** [comment]
The following lines have the same `operationId` (ApplicationsDnsRules.GET):
- https://forge.etsi.org/rep/gitweb.cgi/MEC.GS_011.git/blob/HEAD:/Mp1.yaml#l127
- https://forge.etsi.org/rep/gitweb.cgi/MEC.GS_011.git/blob/HEAD:/Mp1.yaml#l146

As a workaround, can you download the YAML file and fix the duplicated operationId locally?

**Comment by tomer** [comment]
> The following lines have the same `operationId` (ApplicationsDnsRules.GET):

Please note there is ApplicationsDnsRule.GET and ApplicationsDnsRule**s**.GET (the first two lines in the output below), so there are no duplications in file…

```bash
$ grep operationId MEC.GS_011/Mp1.yaml 
      operationId: ApplicationsDnsRules.GET
      operationId: ApplicationsDnsRule.GET
      operationId: ApplicationsDnsRule.PUT
      operationId: ApplicationsSubscriptions.GET
      operationId: ApplicationsSubscriptions.POST
      operationId: ApplicationsSubscription.GET
      operationId: ApplicationsSubscription.DELETE
      operationId: ApplicationsTrafficRules.GET
      operationId: ApplicationsTrafficRule.GET
      operationId: ApplicationsTrafficRules.PUT
      operationId: Services.GET
      operationId: Services.POST
      operationId: ServicesServiceId.GET
      operationId: ServicesServiceId.PUT
      operationId: TimingCurrentTime.GET
      operationId: TimingCaps.GET
      operationId: Transports.GET
```

> As a workaround, can you download the YAML file and fix the duplicated operationId locally?

Is it against any standard to supply dots in the `operationID` field? If so, I'd forward a request to change the value to the upstream.

**Comment by wing328** [comment]
You're right. I'll include additional log to see which operationId is duplicated (maybe caused by a bug).

**Comment by wing328** [comment]
@tomer I filed #7035 to file it and the PR has been merged into master.

Please pull the latest master to give it a try or use the SNAPSHOT version mentioned in the README (after the CI jobs in master complete)

**Comment by tomer** [comment]
> Please pull the latest master to give it a try
I can confirm it does work as expected. 

```diff
> def applications_app_instance_id_dns_rules_get(appInstanceId):  # noqa: E501
< def get_1(appInstanceId):  # noqa: E501
```
