### ISSUE TITLE
[Go] Handle 204 response without json conversion 

### ISSUE THREAD

**Issue by carpani-mailup** [swagger-api/swagger-codegen#7016]
##### Description

The generated api client handles a 204 response with no data as a normal 200 response, where data is expected.

When a request retuns a status 204 with no data in the body, the library will treat this as a success and return an empty object.
The api client will call deserialize with the empty object, which will result in unexpected data.

##### Swagger-codegen version

swagger-codegen 2.3.0 - 242

##### Swagger declaration file content or url

delete:
      tags:
        - sources
      summary: Deletes a source
      description: ''
      operationId: deleteSource
      produces:
        - application/json
        - application/xml
      parameters:
        - name: IdSource
          in: path
          description: Source ID to delete
          required: true
          type: integer
          format: int32
      responses:
        '204':
          description: Deleted

##### Command line used for generation

java -jar /path/to/swagger-codegen.jar generate -i test.json -l go -o ./clients/

##### Steps to reproduce

Generate a Go client with the example code and let the server return 204 without any body.
Then calling the api should reproduce the problem.

##### Related issues/PRs

The 204 was an issue with lots of languages.

##### Suggest a fix/enhancement

avoiding call  json.NewDecoder(localVarHttpResponse.Body).Decode() if http 204

**Comment by wing328** [comment]
@carpani-mailup do you mind submitting a PR with the suggested fix?

**Comment by antihax** [comment]
Confused here. I am generating a large client which uses DELETE many times and has no return type in the output parameters. No data is decoded in the operation.

How are you getting return data?

Compare these two operations
```
func (a *ContactsApiService) DeleteCharactersCharacterIdContacts(...) (*http.Response, error) {
func (a *ContactsApiService) GetAlliancesAllianceIdContacts(...) ([]GetAlliancesAllianceIdContacts200Ok, *http.Response, error) {
```

**Comment by carpani-mailup** [comment]
Close the issue, please. I've rechecked with latest version in 2.3.0 and there's no more evidence of the issue as mentioned by antihax. Or better i've got another error, exactly it happened with DELETE/POST if in YML has been declared a VOID object to be returned. Go code create an 'empty' interface as object to be returned and client blowup, but i'll open anoterh issue more detailed.
