### ISSUE TITLE
[Swift4] Codable models can rely on default implementation of decode/encode functions

### ISSUE THREAD

**Issue by inforeqd512** [swagger-api/swagger-codegen#7020]
##### Description

The encode and decode method implementations are not required as Swift has default implementation for all Codable objects and we can rely on that

##### Swagger-codegen version

snapshots:
3.0.0 = tried with swagger-codegen-cli-3.0.0-20171114.064241-7.jar
2.3.0 = and with swagger-codegen-cli-2.3.0-20171121.153419-270.jar

##### Swagger declaration file content or url

the generated Swift 4 file

```swift
open class FieldError: Codable {

    /** The field that failed validation */
    public var field: String?
    /** A message about the validation failure */
    public var message: String?


    public init(field: String?, message: String?) {
        self.field = field
        self.message = message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(field, forKey: "field")
        try container.encodeIfPresent(message, forKey: "message")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        field = try container.decodeIfPresent(String.self, forKey: "field")
        message = try container.decodeIfPresent(String.self, forKey: "message")
    }
}
```

##### Command line used for generation

java -jar /Documents/Development/Tools/swagger-codegen-cli-2.3.0-20171121.153419-270.jar generate -i /Documents/Development/Payments.yaml -l swift4 -o /tmp/swg1

##### Steps to reproduce

just generate command as above

##### Related issues/PRs

NA

##### Suggest a fix/enhancement

Create models like the stable version 2.2.3 but just with init methods too.

**Comment by d-date** [comment]
+1.
We should avoid to custom encode/decode methods and use `CodingKeys` insted.

**Comment by d-date** [comment]
But We need to think additionally that when the class inherited super `Codable` class, by mapped with `allOf:` in schema. 

```swift
    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(field, forKey: "field")
        try container.encodeIfPresent(message, forKey: "message")

        try super.encode(to: encoder) // When inherited super `Codable` class
    }
```

So I think, in currently system, it's better to use customized encoder/decoder methods.

What's your problem?

**Comment by cloudjubei** [comment]
We have to have the custom `encode` / `decode` as Swift normally uses `camelCase` for variables, whereas on the web you normally use `snake_case`. So if you have a variable `veryImportantMessage` somewhere in your code, it would almost certainly be `very_important_message` on the server side. I personally don't want to see anything close to `very_important_message` as my variable in my code.
Therefore I would be very strongly against getting rid off them.

**Comment by d-date** [comment]
@cloudjubei
Swagger-codegen generate camelCase variable with jsonkeys as written in yaml, by mapping with CodingKey.

So you don’t have to worry about your concern.

**Comment by d-date** [comment]
Sorry, it’s my confused. We need to have custom encode/decode method as @cloudjubei said

**Comment by inforeqd512** [comment]
@cloudjubei 

This is an example of the encoding in a Swift 4 class used as model in iOS application and not on the server side. 

The expectation is whatever be the variable naming convention used by the server, when the server sends that value over the wire as JSON, it will come to the front end application with the JSON keys as defined in the YAML

Also even when using `allOf` tag the model object generated in Swift 4 implements Codeable and has all properties copied from the referenced schema and appends any additional properties to it.

Since all model classes are generated as Codeable, even when any model class is composed in another, the default Codeable implementation from Swift 4 should work

So, all in all, we can do without the custom implementations. Am I still missing sth here

**Comment by cloudjubei** [comment]
@inforeqd512 
Of course - I understood everything you wrote.
The problem is precisely here:
> The expectation is whatever be the variable naming convention used by the server

I don't want my Swift code to follow my server naming convention as those are written in two different languages. They have different conventions. Let's keep it this way.
