### ISSUE TITLE
[Android] Android Client SDK build fail when no "definitions" in OpenAPI specification

### ISSUE THREAD

**Issue by vlgunarathne** [swagger-api/swagger-codegen#7033]
##### Description

The "DefaultApi.java" class and the "JsonUtil.java" class of an Android Client SDK generated from a swagger definition without a "definitions" section, has an import statement 
"import org.wso2.client.model.<title>.*".
When generating an Android Client SDK from a swagger definition without a "definitions" section, the package "io.swagger.client.model" does not get generated. Hence a compilation error occurs when building the project. 
If the swagger definition does have a "definitions" section, then this issue doesn't arise!
##### Swagger-codegen version
2.2.2 , 2.2.3

Below is a screenshot of the Android Client SDK
![screenshot from 2017-11-23 12-27-06](https://user-images.githubusercontent.com/16064696/33161488-d418bd16-d049-11e7-9963-fbd24fa45c05.png)

**Comment by wing328** [comment]
@vlgunarathne as a workaround, I wonder if you can try generating the Java API client, which is also compatible with Android: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

**Comment by vlgunarathne** [comment]
@wing328, Got it working with the Java API client. Thanks for the workaround!

**Comment by wing328** [comment]
@vlgunarathne glad to hear that. Closing this one as I remember there's another issue to track something similar.
