### ISSUE TITLE
Codegen at editor.swagger.io failing to generate code

### ISSUE THREAD

**Issue by RitwikChatterjee** [swagger-api/swagger-codegen#7040]
##### Description

editor.swagger.io is failing to generate any code (server or client) based on the order in which I am defining my oas file. (OASv2.0)
www.swaggerhub.com is able to generate the code for the same specification file. 

##### Swagger-codegen version

The version used by editor.swagger.io (2.2.3)
Note: Swaggerhub.com uses an older version of codegen and is able to generate the code.

##### Swagger declaration file content or url

Specification for which codegen at editor.swagger.io is not able to generate code:
https://app.swaggerhub.com/apis/RitwikChatterjee/transactions/1.0.0

Updated specification for which codegen at editor.swagger.io is _able_ to generate code:
https://app.swaggerhub.com/apis/RitwikChatterjee/transactions/1.0.1

The difference:

**v1.0.0 (lines 160-167)**
```yaml
    allOf:
      - type: object
        properties:
          Txn_Id:
            type: integer
        required:
          - Txn_Id
      - $ref: '#/definitions/transaction-input'
```
**v1.0.1 (lines 160-167)**
```yaml
    allOf:
      - $ref: '#/definitions/transaction-input'
      - type: object
        properties:
          Txn_Id:
            type: integer
        required:
          - Txn_Id
```

**Note**

1. Similar issue faced when using the JSON version instead of yaml.

2. Codegen being used at Swaggerhub.com is able to generate the code for both the versions

##### Command line used for generation

See above.

##### Steps to reproduce

1. Paste the specification version 1.0.0 in editor.swagger.io.
2. Click on "Generate Server" or "Generate Client" and select any language.

##### Related issues/PRs
None found

##### Suggest a fix/enhancement

Looks like this problem has been introduced in a later version of the code

**Comment by wing328** [comment]
Please try the latest 2.3.1 stable version and let us know if you still encounter the issue.
