### ISSUE TITLE
retrofit2 codegen depends on a corrupted version of oauth2 client

### ISSUE THREAD

**Issue by justwy** [swagger-api/swagger-codegen#7044]
https://github.com/swagger-api/swagger-codegen/blob/12ccdcddcd60dbeaddccadef2723b6daaa6e6cba/modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/pom.mustache#L173

[org.apache.oltu.oauth2.client v1.0.1](https://bintray.com/bintray/jcenter/org.apache.oltu.oauth2%3Aorg.apache.oltu.oauth2.client/1.0.1) artifacts seem to have an issue where `org/apache/oltu/oauth2/common/` package are  accidentally included. This caused the following error: 
> Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> \> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
 
Changing back to v1.0.0 worked for me.

**Comment by wing328** [comment]
@justwy thanks for reporting the issue. I wonder if you can file a PR with the suggested fix so that we can review more easily.

**Comment by joeboyscout04** [comment]
I added a PR with updates for this since I also was facing the same issue.  Hope it will be reviewed soon.  Thanks!

**Comment by wing328** [comment]
Closed via #7343 

Thanks for the PR by @joeboyscout04
