### ISSUE TITLE
[Typescript][Angular] Generating unused file 'rxjs-operators.ts'

### ISSUE THREAD

**Issue by bvwells** [swagger-api/swagger-codegen#7048]
##### Description
This is a follow on from PR #6989 . After recent updates the file 'rxjs-operators.ts' is generated, but not used anywhere. This file should be removed from the auto-generation.

##### Swagger-codegen version

I am using version 2.3.0-SNAPSHOT after the mentioned recent changes.

##### Related issues/PRs

#6989

**Comment by wing328** [comment]
@bvwells the PR by @topce has been merged into master. Please pull the latest master to give it a try.

**Comment by bvwells** [comment]
Thanks @wing328 and @topce for the fix. I'll give it a go!

**Comment by bvwells** [comment]
All working well. Thanks again @wing328 and @topce  for the help!

**Comment by topce** [comment]
@bvwells thank you for reporting problem
No file is better then empty file ;-)
