### ISSUE TITLE
[Java] Is there a way to generate hidden=true for a query parameter ?

### ISSUE THREAD

**Issue by TehBakker** [swagger-api/swagger-codegen#7062]
##### Description

Looking to add the Hidden=true parameter to the generated @ApiParam annotation of a query parameter

##### Swagger-codegen version

2.2.3

##### Suggest a fix/enhancement

add a parameter hidden=true for parameter declarion

**Comment by wing328** [comment]
You can do so by using the `-t` option with customized templates.
