### ISSUE TITLE
[Java] Models not created when they share name of built-in JRE classes

### ISSUE THREAD

**Issue by igeryu** [swagger-api/swagger-codegen#7064]
##### Description
Whenever I create a swagger specification that includes a model that shares the name of a built-in JRE class (e.g. ``File``), swagger-codegen imports and uses that built-in version and the custom properties that I included in my definition are not included.

##### Swagger-codegen version
2.2.2

##### Steps to reproduce
Create a specification with a model that has the same name as a JRE built-in class, such as ``File``, ``String``, ``Number``, etc.

##### Related issues/PRs
This started as a question on StackOverflow [here](https://stackoverflow.com/questions/47358472/swagger-codegen-for-java-models-that-share-names-with-built-in-classes).  I am creating this issue ticket per @wing328 's suggestion

##### Suggest a fix/enhancement
@wing328 said that they could think of more than one way to solve the problem

**Comment by wing328** [comment]
@igeryu Can you try the latest master (2.3.0)? The SNAPSHOT version can be found in the README. 

We might have fixed it: https://github.com/swagger-api/swagger-codegen/issues/1561

**Comment by wing328** [comment]
You may also find the following option useful:
```
	fullJavaUtil
	    whether to use fully qualified name for classes under java.util. This option only works for Java API client (Default: false)
```
