### ISSUE TITLE
Add Maven Wrapper

### ISSUE THREAD

**Issue by SimonKlausLudwig** [swagger-api/swagger-codegen#7093]
I Have a suggestion.. You could put the maven wrapper into the git repo.. So a user without maven can run it without installing maven .. and there are no version problems..

https://github.com/takari/maven-wrapper

**Comment by cbornet** [comment]
:+1: would you do a PR ?

**Comment by wing328** [comment]
@SimonKlausLudwig the PR by @devcsrj has been merged into master.

Please pull the latest to give it a try.
