### ISSUE TITLE
[ASPNETCORE Server] OperationID casing is modified

### ISSUE THREAD

**Issue by knom** [swagger-api/swagger-codegen#7116]
I have a swagger contract with an operation with...
`"operationId":"submitParcel"`

However when I look at the C# code generated for the controller it says..
`[SwaggerOperation("SubmitParcel")]`

The different casing breaks the Swagger Contract with Swashbuckle.SwaggerGen - vs. the originally imported one.

**Comment by knom** [comment]
Hey @wing328,
if you have any advice for me how to approach it I can try doing the change (maybe still getting it into 2.3.0).

Thanks.

**Comment by wing328** [comment]
@knom I've filed https://github.com/swagger-api/swagger-codegen/pull/7522 to add "operationIdOriginal". Please review to see if it looks good to you.

**Comment by wing328** [comment]
Closed via #7522 

Please pull the latest master to give it a try.
