### ISSUE TITLE
[Scala] How disable ssl with wordnik.swagger.client and async-http-client

### ISSUE THREAD

**Issue by shijinkui** [swagger-api/swagger-codegen#7130]
when local test, I want to disable SSL. 

##### Description

`AsyncHttpClientConfig` have ssl option. But `RestClient`  didn't set ssl.

```
  protected val clientConfig: AsyncHttpClientConfig = (underlying.builder
    setUserAgent config.userAgent
    setRequestTimeoutInMs config.idleTimeout.toMillis.toInt
    setConnectionTimeoutInMs config.connectTimeout.toMillis.toInt
    setCompressionEnabled config.enableCompression               // enable content-compression
    setAllowPoolingConnection true                               // enable http keep-alive
    setFollowRedirects config.followRedirects).build()

```

I have to say that `wordnik.swagger.client` is rubbish.

**Comment by shijinkui** [comment]
swagger-codegen generated sdk can't be use in product, there are too many  bad design and rubbish code.

**Comment by wing328** [comment]
Understood that wordnik.swagger.client may not meet your requirement in terms of changing the SSL setting.

I see  2 options: 
1) submit a PR to enhance https://github.com/swagger-api/swagger-async-httpclient
2) Try the `akka-scala` generator to see if it has better support for changing SSL setting.

**Comment by shijinkui** [comment]
> Try the akka-scala generator to see if it has better support for changing SSL setting.
Thanks, that's what i want.
