### ISSUE TITLE
[TypeScript - nodejs] Compilation failure for extendObj

### ISSUE THREAD

**Issue by krysalead** [swagger-api/swagger-codegen#7139]
##### Description

When generating typscript-nodejs code using swagger-codegen there is a method

```
private extendObj<T1,T2>(objA: T1, objB: T2) {
        for(let key in objB){
            if(objB.hasOwnProperty(key)){
                objA[key] = objB[key];
            }
        }
        return <T1&T2>objA;
    }
```
That doesn't compile

##### Swagger-codegen version

Swagger-codegen-cli-2.2.1

##### Swagger declaration file content or url

Not related to the swagger file

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.1.jar generate -i swagger.json -l typescript-node -o apis

##### Steps to reproduce

Generate and open the generated file into a IDE that has tslint activated

##### Suggest a fix/enhancement

Change the generator to use this code

```
 private extendObj<T1,T2>(objA: T1&T2, objB: T2):T1&T2 {
        for(let key in objB){
            if(objB.hasOwnProperty(key)){
                objA[key] = (<any>objB[key]);
            }
        }
        return objA;
    }
```

**Comment by wing328** [comment]
Please try the latest master (2.3.0) as 2.2.1 was released a while ago.

The SNAPSHOT version of the latest master can be found in the project's README

**Comment by krysalead** [comment]
Thanks it fixes

**Comment by wing328** [comment]
@krysalead thanks for the confirmation.

Closing the issue.
