### ISSUE TITLE
[csharp] supportsAsync has no influence

### ISSUE THREAD

**Issue by Schwenkner** [swagger-api/swagger-codegen#7147]
May be I'm doing something wrong, pls correct me. if the mistake is with my code.

I'm trying to remove the async methods from code generation. In the mustache files I've found the section {{#supportsAsync}} which shall handle this as I thaught. Unfortunaltely when defining de following config

{
  "packageName": "MyPackageName",
  "additionalProperties": {
    "optionalSolutionFile": false,
    "excludeTests": true,
    "supportsAsync": false
  }
}

The async api methods are still generated.

Am I missing something? When I wrap this section with my own defined in the mustache templates, it is gone.

**Comment by wing328** [comment]
@Schwenkner I think the correct CLI option should be `asyncServer`:
```
	asyncServer
	    Set to true to enable the generation of async routes/endpoints. (Default: false)
```
Ref: java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l nancyfx

**Comment by Schwenkner** [comment]
Sorry, but this answer is not related to my question. The answer is for server code but I mentioned client generated code. 

I didn't answer here, because I had modified template files and solved it by my own, but now I have to generate another client and have the problem again.

**Comment by wing328** [comment]
@Schwenkner the API client supports both Async and Sync API calls in the same C# client.

**Comment by wing328** [comment]
@Schwenkner please contact me via the email address in my Github profile so that I can learn more about your use case.

**Comment by Schwenkner** [comment]
I found this [issue:]
(https://github.com/swagger-api/swagger-codegen/issues/2896)

There is stated, that targetFramework=v3.5 internal sets supportsAsync to false which prevents generating async calls. It seems it cannot been set from config.

Can this be added?
