### ISSUE TITLE
[Java] Redundant declaration of validation-api version 

### ISSUE THREAD

**Issue by elion** [swagger-api/swagger-codegen#7151]
##### Description

Remove version declaration from javax.validation.validation-api in pom.xml. The version declaration is redundant, it is declared in spring-boot-starter-parent.

![javax version](https://user-images.githubusercontent.com/22718104/33877255-84f77628-df30-11e7-88d5-3ddc692fea17.png)

##### Swagger-codegen version

2.3.0-SNAPSHOT

##### Steps to reproduce

Generate a Spring server

**Comment by cbornet** [comment]
Would you do a PR ?
