### ISSUE TITLE
[Java] Redundant validation annotation. Add to field only.

### ISSUE THREAD

**Issue by elion** [swagger-api/swagger-codegen#7153]
##### Description

Currently javax.validation.Valid annotation is added to collection field and getter both. This is redundant. Other validation annotations are added only to getter methods. 

Could all javax.validation.** annotations be added to fields only and not to getter methods?

##### Swagger-codegen version

2.3.0-SNAPSHOT

##### Steps to reproduce

Generate a Spring server

**Comment by wing328** [comment]
> Could all javax.validation.** annotations be added to fields only and not to getter methods?

That's possible by using the `-t` option with the customized templates.
