### ISSUE TITLE
[PYTHON] Parameters name getting converted from camelCase to snake_case while generating python wrapper

### ISSUE THREAD

**Issue by aakanksha-sib** [swagger-api/swagger-codegen#7157]
[PYTHON]

##### Description

This issues is concerned with the variable naming convention for python. For other languages, options are provided for choosing the same eg. camelCase or snake_case, but there is no such option for python.
For eg. we have an option of `variableNamingConvention` for php.

My variables in swagger_definition.yml are in camelCase (eg: `startDate`) but it converts to snake_case (eg. `start_date`) on wrapper generation, which is not desirable. Please suggest a way to solve this out. 
Using master branch / version: 2.2.3

**Comment by pavelzagalsky-paloalto** [comment]
Bumping up, is there a way to tell codegen to keep the camelCase convention instead of using underscore?

**Comment by gdebeaupuis-plenty** [comment]
@HugoMario Is this available on version 3 or only version 2? Thanks!
