### ISSUE TITLE
[AspnetCore Server] Include original swagger.json as a file in the package

### ISSUE THREAD

**Issue by knom** [swagger-api/swagger-codegen#7159]
@wing328 @jimschubert 
Can we include the original JSON passed into Swagger-Codegen as a file in the generated ZIP package?

Would be great to compare with the Swashbuckle generated JSON..

**Comment by jimschubert** [comment]
In think this may cause some licensing issues.

I wonder if we could default the option to false and opt-in to copying the swagger definition to the .swagger folder in the output directory.

**Comment by wing328** [comment]
Some other server generators are generating/including the original OpenAPI/Swagger spec in JSON/YAML format.

e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/ErlangServerCodegen.java#L125

Template: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/erlang-server/swagger.mustache
