### ISSUE TITLE
[SpringCodeGen] dateLibrary "java8-localdatetime" option is broken

### ISSUE THREAD

**Issue by nemecec** [swagger-api/swagger-codegen#7177]
##### Description

Using `dateLibrary` option set to `java8-localdatetime` is not working as expected in case of `spring-mvc` library. I would expect the generated object model to use `java.time.LocalDateTime` but instead, it is using `java.time.OffsetDateTime`.

`AbstractJavaCodeGen` contains logic to choose the right dateTime implementation ([code](https://github.com/swagger-api/swagger-codegen/blob/5306372b981b9fc7290dc38a2be17fa11fa34605/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java#L402)) but that is rudely overridden by `SpringCodegen` ([code](https://github.com/swagger-api/swagger-codegen/blob/81c0e81c7787dd450280b44dc5d3f70519b9bbad/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/SpringCodegen.java#L292)).

Removing those 4 lines of overriding code from `SpringCodegen` seems to fix the issue and should not have any adverse side-effect (as Java8 is the default date library anyway in case of `SpringCodegen`).

I'll prepare a pull request so you can review it.

BTW, I'm aware that using `LocalDateTime` is not according to Swagger spec, but I'm maintaining an existing API and it will take time to migrate users to start using `OffsetDateTime`. And the logic to use `LocalDateTime` is already there, so I think users should have that option available and working as advertised by Swagger Codegen documentation.

##### Swagger-codegen version

All versions of `SpringCodegen` that I could see on GitHub.

**Comment by macjohnny** [comment]
@nemecec awesome, thanks for the fix!
