### ISSUE TITLE
Please help in resolving issue "Property 'body' does not exist on type '{}'".

### ISSUE THREAD

**Issue by wajidreply** [swagger-api/swagger-codegen#7231]
##### Description

Generated the models using ng-swagger-gen and while building the application getting error "Property 'body' does not exist on type '{}'." . Please help in how to resolve this issue. 

##### Swagger-codegen version: 

 Swagger-codegen version: 0.9.3

##### Swagger declaration file content or url
http://petstore.swagger.io/v2/swagger.json

 http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation
ng-swagger-gen --gen-config -i http://petstore.swagger.io/v2/swagger.json  -o src/app/api

##### Steps to reproduce
1. Generated the autogenerated code files using below command in Angular 
ng-swagger-gen --gen-config -i http://petstore.swagger.io/v2/swagger.json -o src/app/api
2. After generating the files when trying to build the application getting error as "Property 'body' does not exist on type '{}'.".

Using below version.
angular/cli: 1.4.9
node: 6.9.5
os: win32 x64
angular/animations: 4.4.6
angular/common: 4.4.6
angular/compiler: 4.4.6
angular/core: 4.4.6
angular/forms: 4.4.6
angular/http: 4.4.6
angular/platform-browser: 4.4.6
angular/platform-browser-dynamic: 4.4.6
angular/router: 4.4.6
angular/cli: 1.4.9
angular/compiler-cli: 4.4.6
angular/language-service: 4.4.6
typescript: 2.3.4

##### Suggest a fix/enhancement

Below code might help in identifying the issue. 
/**
   * Returns a single pet
   * @param petId - ID of pet to return
   */
  getPetByIdResponse(petId: number): Observable<HttpResponse<Pet>> {
    let __params = this.newParams();
    let __headers = new HttpHeaders();
    let __body: any = null;
    
    let req = new HttpRequest<any>(
      "GET",
      this.rootUrl + `/pet/${petId}`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });

    return this.http.request<any>(req).pipe(
      filter(_r => _r instanceof HttpResponse),
      map(_r => {
        let _resp = _r as HttpResponse<any>;
        let _body: Pet = null;
        _body = _resp.body as Pet
        return _resp.clone({body: _body}) as HttpResponse<Pet>;
      })
    );
  }

  /**
   * Returns a single pet
   * @param petId - ID of pet to return
   */
  getPetById(petId: number): Observable<Pet> {
    return this.getPetByIdResponse(petId).pipe(
      map(_r => _r.body) **// Getting error on this line.**
    );
  }

**Comment by luisfpg** [comment]
@wajidreply I see you are reporting this in the official swagger-codegen project, but you state to be using [ng-swagger-gen](https://github.com/cyclosproject/ng-swagger-gen) to generate the code.
It is a separated, of which I'm the maintainer, by the way.
So, please, report ng-swagger-gen issues in its own gihub project.

**Comment by luisfpg** [comment]
By the way, I think the problem is, as it is stated on [ng-swagger-gen requirements](https://github.com/cyclosproject/ng-swagger-gen#requirements), rxjs 5.5 or newer is needed.

**Comment by wajidreply** [comment]
@luisfpg - Thank you for taking time and looking into this issue. I have updated to rxjs 5.5 version and issue got resolved. :)

**Comment by gildniy** [comment]
And update your typescript to ^2.4.0
