### ISSUE TITLE
[Node/Express -> TypeScript-Angular] Consolidate generated files into one `api.ts` file

### ISSUE THREAD

**Issue by nartc** [swagger-api/swagger-codegen#7253]
##### Description

I’ve just got started with Swagger and NodeJS. I was able to implement Swagger to my NodeExpress application and was also able to generate typescript-client-code with Swagger-Codegen (Typescript-Angular) to be exact.

One problem that I have is the generated code is so spread out many different files. I was hoping that it only output one file `api.ts` and it contains everything from API calls and interfaces/models.

I’ve been looking for a way to solve this problem because it is hard to read and maintain the generated-client-code as the backend grows.

##### Swagger-codegen version

swagger-codegen-cli 2.3.0

##### Swagger declaration file content or url
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->https://gist.github.com/nartc/4cb5fb53493badbf36b5ffb86597d945

##### Command line used for generation

`java -jar ../../../swagger-codegen-cli.jar generate -l typescript-angular -c ./api/swagger/swagger-config.json -i http://localhost:3000/api/docs/swagger.json -o ../helpdesk-tm-ngsrc/src/app`

config:
```json
{
  "supportsES6": true,
  "ngVersion": "5.0.0"
}
```

##### Suggest a fix/enhancement

Any pointers or suggestions would be much appreciated. Thank you.

**Comment by macjohnny** [comment]
@nartc I would say this works as intended. Generating separate files allows a clear separation of models from APIs and everthing else. 
You could, however, create a script that merges all files into one big file in your project. The only thing you would need to do is to remove the import statements for imports that are whithin your api path.
Possibly, naming collisions could occur.

I suggest to close this issue, as this is a very special requirement for a specific project.

**Comment by nartc** [comment]
Hi @macjohnny ,

After working with it for a while, I totally get the intentions now. I also opt for closing the issue. 

Thanks for commenting
