### ISSUE TITLE
[Python] Example of providing API key does not work

### ISSUE THREAD

**Issue by cledoux** [swagger-api/swagger-codegen#7269]
##### Description

The example of configuring an API in the generated README is broken for python.

The example code generated is:
```python
# Configure API key authorization: api_key
swagger_client.configuration.api_key['api_key'] = 'YOUR_API_KEY'
```

However, the `configuration.py` file does not have an `api_key` attribute. All attributes are now inside the `Configuration` class and cannot be set at the module level. 

##### Swagger-codegen version
2.3.0

##### Swagger declaration file content or url
(This is just the petstore spec stripped down to only the necessary bits. It will not work if you use the full petstore spec because the example uses the OAuth instead of ApiKey.)

```yaml
---
swagger: "2.0"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "http"
paths:
  /pet:
    get:
      operationId: "get_pet"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
security:
  - api_key: []
```

##### Command line used for generation

`docker run --rm -v $(pwd):/local swaggerapi/swagger-codegen-cli generate -i swagger.yaml -l python -o /local/clients/python`

##### Steps to reproduce

1. Generate the python client using the provided swagger yaml.
1. pip install the generated client.
1. Attempt to follow the example in the generated README.

**Comment by wing328** [comment]
> swagger_client.configuration.api_key['api_key'] = 'YOUR_API_KEY'

@cledoux Do you mind filing a PR to fix the sample code when you've time?

**Comment by jacksonlauder** [comment]
I am having a similar issue.  Is this issue solved?

**Comment by Prime03** [comment]
What is the expected behavior? A preconfigured `Configuration` used to initialize an `ApiClient`?

**Comment by jacobweber** [comment]
Any workaround for this?

**Comment by ensonic** [comment]
I still can't get it to work. What is the semantics of 'my-key-name' in
``` python
config.api_key['my-key-name'] = 'my-key-value'
```
Also does anyone know how to get to see the actual http request that is sent?

**Comment by Prime03** [comment]
@ensonic `my-key-name` should match the security definition name.
```
securityDefinitions: {
    api_key: {
       type: "apiKey",
       name: "authorization",
       in: "header"
      }
}
```

In my configuration object, that looks like,
```
api_client.configuration.api_key['authorization'] = 'token_value'
api_client.configuration.api_key_prefix['authorization'] = 'Token'
```

This produces a header `authorization: Token xyz123..`

**Comment by ensonic** [comment]
Thanks. That definitely helps. So I have this in my open-api-spec.json:
```json
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    }
  },
  "security": {
    "api_key": []
  }
```
and in the code I'll do this:
``` python
config = registry.Configuration()
config.api_key['x-api-key'] = api_key
api_client = registry.ApiClient(config)
registry_client = registry.RegistryApi(api_client)
```
expected would be a header "x-api-key: 12345", but the header is not set :/ I'll think I have to put logging stuff into the generated code :/. Can it be that it does not handle the case where the security settings are applied globally?
