### ISSUE TITLE
CSharp code generator -  property names changed to fit language convention

### ISSUE THREAD

**Issue by boazsapir** [swagger-api/swagger-codegen#727]
I have a property name in my schema which is lower-case, e.g.:

 *@SWG\Definition(definition="TimeIntput", type="object",
     *   required={ "time" },
     *   @SWG\Property(property="time", type="integer", description="timestamp"),
     * )

This property should be included as part of a request body:

    *   @SWG\Parameter(name="Input", in="body", @SWG\Schema(ref="#/definitions/TimeInput")),

The CSharp code generator creates a class where the property name is capitalized according to the language conventions:
namespace io.swagger.Model {
  public class TimeInput {
    
    /* timestamp */
    
    public int? Time { get; set; }

    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class TimeInput {\n");
      
      sb.Append("  Time: ").Append(Time).Append("\n");
      
      sb.Append("}\n");
      return sb.ToString();
    }
  }

When sending the request by APIInvoker, the CSharp object which is an instance of the above class is serialized so the parameter in the request body has the capitalized name.
This means that the server does not get the parameter with the expected name as defined in the schema.

**Comment by wing328** [comment]
The issue should be addressed by #700 

I wonder if you can do a test to help confirm.

**Comment by boazsapir** [comment]
I want to do the test but I am not able to merge the change request, it says:
Only those with write access to this repository can merge pull requests.

**Comment by wing328** [comment]
please pull the fix from https://github.com/wing328/swagger-codegen/tree/csharp_restcsharp instead as the PR #700 has not been merged into develop_2.0 branch.

**Comment by boazsapir** [comment]
Thank you, the problem is solved in the csharp_rescsharp codeline.
When do you expect that it will be merged into the branch?

**Comment by wing328** [comment]
No problem. Thanks for your time in testing the change.

I believe @fehguy is quite busy these days. How urgent do you need the change ? (the change will be merged into develop_2.0 branch but not master)

**Comment by boazsapir** [comment]
Within one week would be great.

**Comment by webron** [comment]
Can't guarantee that. The earliest we can make it is probably next weekend, but again, no guarantee.

**Comment by boazsapir** [comment]
ok, thank you anyway.
I am going to open some more issues as I am building a sample C# program to test our API and I encountered some problems.

**Comment by webron** [comment]
Keep in mind #700 may be merged sooner and you could use the develop_2.0 branch easily.

**Comment by wing328** [comment]
@boazsapir FYI. csharp_restsharp has been merged into develop_2.0. Please kindly close this issue if the property names for CSharp are all good.

**Comment by boazsapir** [comment]
@wing328 I cannot test now because of the build error in develop_2.0. Will try later today

**Comment by fehguy** [comment]
merged.
