### ISSUE TITLE
CSharp code generator - Class for array property is generated without any data member

### ISSUE THREAD

**Issue by boazsapir** [swagger-api/swagger-codegen#729]
I have a property defined as an array:
     * @SWG\Definition(definition="Tokens", type="array", @SWG\Items(type="string", maxLength=64, maxItems=32), description="a list of tokens")
     *   @SWG\Property(property="tokens", ref="#/definitions/Tokens")

In the generated CSharp code, the corresponding class  is created empty without any data members and it does not inherit from any other class (in the Java generated code, for instance, it extends ArrayList<String>).

namespace io.swagger.Model {
  [DataContract]
  public class Tokens {
    
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class Tokens {\n");
      
      sb.Append("}\n");
      return sb.ToString();
    }
  }
  
  
}

**Comment by wing328** [comment]
Is it correct to say that the issue also occurs in the "csharp_restcsharp" PR #700 ?

**Comment by boazsapir** [comment]
Yes, I am testing now on the #700 code (note the [DataContract] annotation in the generqted code)

**Comment by wing328** [comment]
OK. I'll spend some time to look into the issue tomorrow.

**Comment by wing328** [comment]
Are you trying to define a property, which is an array of model ? If that's the case, I think you need to set the type to "array". Using the Pet object in http://petstore.swagger.io/v2/swagger.json as an example, it has a property named tags, which is an array of Tag.
```
tags: {
  type: "array",
  items: {
    $ref: "#/definitions/Tag"
  }
},
```
If my guess is not correct, please kindly share with us the Swagger spec for repeating the issue.

**Comment by boazsapir** [comment]
I do use the "array" type but still the generated class does not inherit any base class.

Here is my swagger spec:

       "Tokens": {
            "description": "a list of  tokens",
            "type": "array",
            "items": {
                "type": "string",
                "maxLength": 64,
                "maxItems": 32
            }
        },

**Comment by webron** [comment]
@boazsapir - that's an array of strings, not an array of a model.

**Comment by boazsapir** [comment]
@webron do I have to change it to an array of model or is it a bug that it does not work for array of strings?

**Comment by wing328** [comment]
@boazsapir Array of strings should also work. For Pet object in the [petstore](http://petstore.swagger.io/v2/swagger.json) example,  the property "photoUrls" is an array of strings:
```
photoUrls: {
  type: "array",
  xml: {
  name: "photoUrl",
    wrapped: true
  },
  items: {
    type: "string"
  }
},
```
which works fine with the CSharp codegen.

Do you have the full Swagger spec that you can share with us to look into the issue (assuming the spec can share publicly)?

**Comment by boazsapir** [comment]
Sorry I cannot publicly share the full spec. I will try to isolate the reason why the behavior in my case is different than in the petstore example

**Comment by wing328** [comment]
@boazsapir understood. Did you encounter the same issue using Ruby, PHP client codegen?

**Comment by boazsapir** [comment]
I did not try those clients, only Java and CSharp. Had no problem with Java

**Comment by fehguy** [comment]
Please reopen if you're still having an issue with this.
