### ISSUE TITLE
[typescript-angular] undefined queryParameters when apiKeyQuery exists but no method parameters

### ISSUE THREAD

**Issue by jwoehrle** [swagger-api/swagger-codegen#7303]
##### Description

I stumpled upon this issue when trying to generate a client for the Microsoft LUIS API. The complete swagger file can be found at https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/export?DocumentFormat=Swagger&ApiName=LUIS%20Programmatic%20APIs%20v2.0 however see below for a smaller file which illustrates the issue as well.

When generating a typescript-angular client a queryParameters parameter is generated which is not defined if endpoint has no parameters but `apiKeyQuery` is set within `securityDefinitions`.

It seems that the `{{#hasQueryParams}}` in the `api.service.mustache` file does not respect the `apiKeyQuery`

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "title": "LUIS Programmatic APIs v2.0",
    "version": "1.0"
  },
  "host": "westus.api.cognitive.microsoft.com",
  "basePath": "/luis/api/v2.0",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "apiKeyHeader": {
      "type": "apiKey",
      "name": "Ocp-Apim-Subscription-Key",
      "in": "header"
    },
    "apiKeyQuery": {
      "type": "apiKey",
      "name": "subscription-key",
      "in": "query"
    }
  },
  "security": [
    {
      "apiKeyHeader": []
    },
    {
      "apiKeyQuery": []
    }
  ],
  "paths" : {
    "/apps/": {
      "get": {}
    }
  }
}

```
##### Config file
```json
{
"modelPropertyNaming": "original",
"ngVersion": "5.0.0",
"classPrefix": ""
}
```

##### Command line used for generation

`java -jar swagger-codegen-cli-2.3.0.jar generate -i "C:\tmp\swagger_example.json" -l typescript-angular -o ./angular_client -DnpmName=LUIS_CLIENT -c config.json`

##### Steps to reproduce

generate the client with above command. See `default.service.ts:78` where a variable `queryParameters` is used which is not defined.

##### Suggest a fix/enhancement

respect `apiKeyQuery` for the `{{#hasQueryParams}}` in `api.service.mustache`

**Comment by vkeenan** [comment]
This happened to me when generating my own Swagger/OpenAPI 2 code to TypeScript-Angular. 

Wondering if replacing the missing variable with
```javascript
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
```
fixes it.
