### ISSUE TITLE
[Go] 2.3.0 `undefined: localVarFile` problem in multipart/form-data file

### ISSUE THREAD

**Issue by grokify** [swagger-api/swagger-codegen#7311]
##### Description

The auto-generated function parameter name for a file is set to the file's `parameter` `name` property while the code within the function expects `localVarFile`. This occurs in a `multipart/form-data` request with the type `file` parameter.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

The following file property:

https://github.com/grokify/ringcentral-sdk-go-scg/blob/master/codegen/swagger_ringcentral_v1.0.32.json#L4291

```json
          {
            "name": "body",
            "in": "formData",
            "type": "file",
            "required": true,
            "description": "The file to upload"
          }
```

Results in:

```
func (a *GlipApiService) CreateGlipFile(ctx context.Context, body *os.File, localVarOptionals map[string]interface{}) (PostGlipFile, *http.Response, error) {
```

Renaming `body` to `localVarFile` fixes the issue in multiple instances.

```
func (a *GlipApiService) CreateGlipFile(ctx context.Context, localVarFile *os.File, localVarOptionals map[string]interface{}) (PostGlipFile, *http.Response, error) {
```

##### Command line used for generation

`$ java -jar swagger-codegen-cli.jar generate -c swagger_ringcentral_config.json -i swagger_ringcentral_v1.0.32.json -l go -o .`

##### Steps to reproduce

Build the SDK, run this example code:

https://github.com/grokify/go-ringcentral/blob/master/examples/get_me/get_me.go

##### Related issues/PRs

https://github.com/grokify/go-ringcentral/issues/4

##### Suggest a fix/enhancement

In the RingCentral SDK, this is manifested using the `body`, `attachment`, and `image` parameter names. Renaming all of these to `localVarFile` solves the issues when the property type is `file`.

**Comment by imissyouso** [comment]
it is still actual for me too
