### ISSUE TITLE
CSharp code generator - generated function's response type is string instead of byte[]

### ISSUE THREAD

**Issue by boazsapir** [swagger-api/swagger-codegen#733]
I defined the response data type of a POST api request as binary, according to the Swagger spec (type="string", format="byte"):

    *   @SWG\Response(response=200, description="Encrypted data", @SWG\Schema(type="string", format="byte"))

The generated CSharp API call function has "string" as return type, and therefore apiInvoker.invokeAPI() will be called instead of apiInvoker.invokeBinaryAPI().

The generated code:

       if (typeof(string) == typeof(byte[])) {
          
          var response = apiInvoker.invokeBinaryAPI(basePath, path, "GET", queryParams, null, headerParams, formParams);
          return ((object)response) as string;
          
          
        } else {
          
          var response = apiInvoker.invokeAPI(basePath, path, "POST", queryParams, BinaryData, headerParams, formParams);
          if (response != null){
             return (string) ApiInvoker.deserialize(response, typeof(string));
          }
          else {
            return null;
          }
          
          
        }

**Comment by wing328** [comment]
In your example, is the HTTP response body/content encoded in base64 and you would expect the method to automatically convert the base64-encoded string to byte array using [Convert.FromBase64String](https://msdn.microsoft.com/en-us/library/system.convert.frombase64string(v=vs.110).aspx) ?

Related discussion: https://github.com/swagger-api/swagger-spec/issues/50

**Comment by boazsapir** [comment]
@wing328 in fact my response content is binary, not base64 encoded

**Comment by wing328** [comment]
@boazsapir OK. RESTSharp supports sending binary data so I'll try to address the issue in the csharp_restsharp branch.

**Comment by webron** [comment]
@boazsapir - what's the `produces` of your operation?

**Comment by boazsapir** [comment]
"consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/octet-stream"
                ],

**Comment by webron** [comment]
@boazsapir - hope you saw my comment regarding `application/octet-stream` and the `byte` format in the other thread.

**Comment by wing328** [comment]
@boazsapir currently the format `byte` in Swagger Spec (2.0) is a base64-encoded string so there's not much I can do at the moment to change the return type to `byte[]`

**Comment by wing328** [comment]
Fixed by #1864

**Comment by wing328** [comment]
@boazsapir when you've time, please kindly help perform a test. 

Closing this issue for the time being.
