### ISSUE TITLE
Petstore 1.2 spec has validation issues?

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-codegen#735]
Running the [Swagger JSON](http://petstore.swagger.io/api/api-docs) for the example petstore server through the swagger-tools validator turned up two issues:
1. `/pet` has an uploadFile operation with a 'File' type, which [should use paramType of 'form'](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v1.2/parameterObject.json#L21).
2. `/user` has several operations whose scopes are `test:anything`. It may be failing validation because that hasn't been declared in the api-docs resource listing's authorizations definition.

**Comment by fehguy** [comment]
I'm not clear what the issue is--the sample app or the codegen?  I think the latter, and this belongs in swagger-core, which is where the samples live.

**Comment by earth2marsh** [comment]
Apologies if I picked the wrong one! This issue is about however the petstore.swagger.io/v2/swagger.json is populated. IIRC, it comes from the Java annotations, and when I searched for `test:anything` in this and the swagger-core repos, the only hit I found was in the swagger-codegen project. If that was a faulty assumption, I'll happily close and re-open there.

**Comment by webron** [comment]
@earth2marsh - it's definitely an issue with the sample...

**Comment by earth2marsh** [comment]
OK, please close this one then, and I'll reopen there.
