### ISSUE TITLE
 [Python] ModuleNotFoundError: No module named 'swagger_client.models.inline_response2006_billing'

### ISSUE THREAD

**Issue by yevhen-kalyna** [swagger-api/swagger-codegen#7357]
##### Description

I want to use unity-cloud-build_api for my scripts on Python, for this I generate the api client by Swagger CodeGen on laptop with macOS, using homebrew with [this](https://build-api.cloud.unity3d.com/docs/1.0.0/index.html) json. Than I send the swagger-client to my PC on Windows10, unpuck it and after $  python -m swagger_client , get the error"ModuleNotFoundError"

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

https://gist.github.com/MrDeman/617108cac6e8b0beac027910c7d9a3e5

##### Command line used for generation

$ brew install swagger-codegen
$ swagger-codegen generate -i https://build-api.cloud.unity3d.com/docs/1.0.0/index.html -l python -o /tmp/test/

##### Preconditions

PC one - macOS
PC two - Windows 10

##### Steps to reproduce

On PC one:
1. Open terminal and write `$ brew install swagger-codegen`
2. After downloading write `$ swagger-codegen generate -i https://build-api.cloud.unity3d.com/docs/1.0.0/index.html -l python -o /tmp/test/`
3. Archive the got files and send it to PC two

On PC two:
1. Unzip archive to any folder
2. In the folder with unzipped archive, open PowerShell and use commands $ pip install -r requirements.txt $ python -m swagger_client

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/4684
https://github.com/Bungie-net/api/issues/357
https://github.com/marcgibbons/django-rest-swagger/issues/33
https://github.com/swagger-api/swagger-codegen/issues/2517

##### Suggest a fix/enhancement

May be problem on the names of files
Log
```
Traceback (most recent call last):
  File "C:/Users/e.kalina/Downloads/Kalina/Kalina/APIstart.py", line 3, in <module>
    import swagger_client
  File "C:\Users\e.kalina\Downloads\Kalina\Kalina\swagger_client\__init__.py", line 19, in <module>
    from swagger_client.api.builds_api import BuildsApi
  File "C:\Users\e.kalina\Downloads\Kalina\Kalina\swagger_client\api\__init__.py", line 6, in <module>
    from swagger_client.api.builds_api import BuildsApi
  File "C:\Users\e.kalina\Downloads\Kalina\Kalina\swagger_client\api\builds_api.py", line 21, in <module>
    from swagger_client.api_client import ApiClient
  File "C:\Users\e.kalina\Downloads\Kalina\Kalina\swagger_client\api_client.py", line 27, in <module>
    import swagger_client.models
  File "C:\Users\e.kalina\Downloads\Kalina\Kalina\swagger_client\models\__init__.py", line 31, in <module>
    from swagger_client.models.inline_response_200_6 import InlineResponse2006
  File "C:\Users\e.kalina\Downloads\Kalina\Kalina\swagger_client\models\inline_response_200_6.py", line 19, in <module>
    from swagger_client.models.inline_response2006_billing import InlineResponse2006Billing  # noqa: F401,E501
ModuleNotFoundError: No module named 'swagger_client.models.inline_response2006_billing'
```

**Comment by MrDeman** [comment]
Repair it by hands. Need to find files with long names and check " _ " chars. Actual on the builded project files, Expected on the documents on the builded project.
