### ISSUE TITLE
Petstore YAML is not valid YAML

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-codegen#736]
It looks like line breaks in longer descriptions aren't being handled properly. In order to use multiple lines in YAML, you must use a `|` and then indent the subsequently consistently. The petstore example uses JS-style `\` to continue across lines.

See: petstore.swagger.io/v2/swagger.json

**Comment by fehguy** [comment]
You mean http://petstore.swagger.io/v2/swagger.yaml

**Comment by earth2marsh** [comment]
Oops, yes! Does this also belong in swagger-core instead?

**Comment by fehguy** [comment]
yes please!
