### ISSUE TITLE
Typescript: local lowercase variable appears in uppercase in the return statement 

### ISSUE THREAD

**Issue by NatalieBorovykh** [swagger-api/swagger-codegen#7384]
##### Swagger-codegen version
2.3.0

##### Swagger declaration file content or url
```yaml
swagger: '2.0'
info:
  version: '1.0.0'
  title: Test

schemes:
  - http

paths:
  '/Item/{Id}':
    get:
      parameters:
        - name: Id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
```

##### Steps to reproduce
1. Generate typescript-angular code for the definition above.
Sample command line:
java -jar swagger-codegen-cli.jar generate -l typescript-angular -i C:\swagger.yaml -o C:\typescript
2. Example the default.service.ts file - in the return statement the "Id" is written instead of "id" 
![image](https://user-images.githubusercontent.com/5817317/34869825-43938970-f799-11e7-873f-8d7c16d7f1b7.png)

**Comment by webron** [comment]
@wing328 do you have any input on this one?

**Comment by wing328** [comment]
@NatalieBorovykh by default, `camelCase` is used according to TypeScript style guide.
```
camelCase for property names and local variables
```
Ref: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names

To keep the original name, please set `modelPropertyNaming` to `original`:

```
	modelPropertyNaming
	    Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name (Default: camelCase)
```

Ref: java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l typescript-angular
