### ISSUE TITLE
[Scalatra] Inappropriate header message

### ISSUE THREAD

**Issue by magnolia-k** [swagger-api/swagger-codegen#7398]
##### Description

Although it says "Do not edit the class manually." in the header of the api class, 
this class obviously needs to be modified and this description is inappropriate.

For example, the following file

https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/scalatra/src/main/scala/com/wordnik/client/api/PetApi.scala

##### Swagger-codegen version

2.4.0

##### Suggest a fix/enhancement

Except for model, think that this header should be deleted.

**Comment by wing328** [comment]
Agreed with you. That line is probably copied from another mustache file (e.g.  Scala client) and should be removed.

**Comment by magnolia-k** [comment]
fixed and merged

https://github.com/swagger-api/swagger-codegen/pull/7454
