### ISSUE TITLE
Support for Produces or operation that serves a file download

### ISSUE THREAD

**Issue by adamcoimbra** [swagger-api/swagger-codegen#74]
Hello,

Thanks for your excellent work on swagger-codegen. I am attempting to use it to produce client libraries for an API in which one operation may return a response with a Content-Type of either "application/pdf", "application/csv", or "application/html" depending on a parameter. The response body will contain the bytes of a PDF, CSV, or HTML file. 

If it helps, my swagger spec for this operation is more or less the following:
```json
{
    "path":"/jobs/{job_id}/result",
    "description":"Job results",
    "operations":[{
      "httpMethod":"GET",
      "nickname":"getJobResult",
      "produces":["application/pdf","application/csv","application/html"],
      "responseClass":"byte",
      "parameters":[{
        "paramType":"path",
        "name":"job_id",
        "description":"job_id",
        "dataType":"string",
        "required":false,
        "allowMultiple":false,
        "defaultValue":null
      },{
        "paramType":"header",
        "name":"Accept",
        "description":"Accept",
        "dataType":"string",
        "required":false,
        "allowMultiple":false,
        "defaultValue":null
      }],
      "summary":"",
      "notes":"",
      "errorResponses":[]
}]
}
```
Any advice is greatly appreciated.

**Comment by wing328** [comment]
@adamcoimbra most API clients (e.g. C#, Java, Ruby, etc) should support file download. Please kindly give the latest stable version (2.1.4) a try and let us know if you still experience issue,

**Comment by vivex** [comment]
@wing328
  i am using swagger-ui 2.1.4, there is a API which returns pdf,  I am  using schema type as "file" in json  but the downloaded pdf from swagger link is currupt (coming blank) but if i download it directly from browser then it works fine (mean there is some issue with blob conversion or something) , Can you please help ?

**Comment by wing328** [comment]
For issue with swagger-ui, please report [here](https://github.com/swagger-api/swagger-ui/issues/new)
