### ISSUE TITLE
[PHP][Symfony] Passthru of any HTTPException

### ISSUE THREAD

**Issue by frickelbruder** [swagger-api/swagger-codegen#7422]
Hi there,

I want to return some specific HTTP status codes.

For example in case of a failed remote API request by my application, I want to return a custom HTTP status code (e.g. 410 or whatever). Currently there seem to be only a limited number of mapped Exceptions, which map to the named Symfony exception. 

It would be great, if you could return exceptions of type HttpException directly without wrapping them into a 500 response. So it should somehow look similar like this:

    } catch (HttpException $httpException) {
        return $this->createErrorResponse($httpException);
    } catch (Exception $fallthrough) {
        return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
    }

Thank you in advance.

**Comment by frickelbruder** [comment]
Follow-Up:
It would be even better, passthru any HttpExceptionInterface - Exceptions :-)

**Comment by wing328** [comment]
@frickelbruder thanks for the feedback. Can you please file a PR so that we can review the improvement more easily?

**Comment by frickelbruder** [comment]
Hi there,

I close this feature request. 
As I checked the code, there is already a way to provide a custom HTTP code. 
This just does not yet work with https://generator.swagger.io/api/gen. There seems to be an older release online.

Thanks anyway.
