### ISSUE TITLE
Unable to install `swagger-codegen` using brew command

### ISSUE THREAD

**Issue by Tesan3010** [swagger-api/swagger-codegen#7427]
[Mac OS X] Unable to install `swagger-codegen` using `brew install command`

##### Description

Even though I've the latest Java version, when running `brew install swagger-codegen` via command line, encountering JavaRequirement unsatisfied! error. PFB the details.

* brew install command:

`brew install swagger-codegen`

> Updating Homebrew...
swagger-codegen: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
brew cask install caskroom/versions/java8
You can download from:
https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.

* Java version:
`java -version`
> java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

* JAVA_HOME:
`echo $JAVA_HOME`
> /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home

##### Swagger-codegen version

2.3.0 

##### Command line used for generation

`
brew install swagger-codegen
`

**Comment by wing328** [comment]
Please use the JAR as a workaround for the time being: https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by Tesan3010** [comment]
@wing328 : Okay.

**Comment by wing328** [comment]
Filed https://github.com/Homebrew/homebrew-core/pull/23015 to upgrade to the latest v2.3.1.
