### ISSUE TITLE
Improve the code and comments to be valid with tslint.

### ISSUE THREAD

**Issue by Domvel** [swagger-api/swagger-codegen#7428]
##### Description
Currently tslint shows errors about swagger generated files.
In most of cases it's the header comment which contains `trailing spaces`. 
Also generate the code with 2-spaces instead of tabs or 4 spaces. etc.
Ok, maybe there are settings to do this. But the trailing spaces etc. are bugs.

Example file:
```javascript
/**
 * Swagger Maven Plugin
 * Example swagger code generation
 *
 * OpenAPI spec version: 1.0.0-BETA
 * <- Here is the trailing space. This line was " * " (one trailing space) The next line is ok. (" *")
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Example {
    id?: number;
    /**
     * name of the device
     */
    name: string;
}
```
Error by tslint: trailing whitespace (no-trailing-whitespace) (6, 3)

##### Generation

1. Generate the swagger json.
2. Generate the models / code (ts files) from this json.

Language: typescript-angular
Generate APIs: true

##### Suggest a fix/enhancement

Just remove all trailing spaces for the first step.

**Comment by macjohnny** [comment]
@Domvel you could simply exclude the generated API from linting with `linterOptions.exclude`, since it can be impossible to comply to all different linting settings chosen by different users.

**Comment by Domvel** [comment]
@macjohnny That's right: It's impossible to comply to all different linter settings. That's not what I want. Just remove unwanted characters from file. **The trailing spaces** That a fault and has nothing to do with a linter.

**Comment by macjohnny** [comment]
@Domvel could you file a PR for this code cleanup?

**Comment by Domvel** [comment]
Here's a screenshot about the issue. It's really a trivial thing.
![issue](https://user-images.githubusercontent.com/35452565/35438707-e681c788-0297-11e8-96e5-90e795938c67.png)

**Comment by macjohnny** [comment]
@Domvel this is due to the following line: 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/licenseInfo.mustache#L6
```
 * {{#version}}OpenAPI spec version: {{{version}}}{{/version}}
 * {{#infoEmail}}Contact: {{{infoEmail}}}{{/infoEmail}}
```
If no `infoEmail` is set, there is an excessive whitespace.
This could be changed to
```
 * {{#version}}OpenAPI spec version: {{{version}}}{{/version}}
 *{{#infoEmail}} Contact: {{{infoEmail}}}{{/infoEmail}}
```
But I am pretty sure this would be changed back at some point to make the template look nicer if one is not aware of the trailing spaces problem.

I suggest you use `linterOptions.exclude` and exclude the generated code from code format checks in your IDE.

**Comment by Domvel** [comment]
Ok thanks for your suggestion. I'll looking to add a config file to the projects which overwrites the vs code settings, because this is a project issue. It should not added to the global settings of vs code which affects to all project. 

My suggestion is to pipe the file after generation through a prettier formatter. Or change the generator to trim the right side of every line. Easy, isn't it? In this case, no one has to check this on changes.
Whatever... it's not a k.o. 😄 But it must be all perfect.
