### ISSUE TITLE
Java Jersey 2 generated client thread safety

### ISSUE THREAD

**Issue by tsiq-karold** [swagger-api/swagger-codegen#7453]
##### Description
This is related to an old issue which was closed with documentation improvements: https://github.com/swagger-api/swagger-codegen/issues/1435.

I would like to revisit this and actually fix the problem.

##### Swagger-codegen version

Master HEAD.

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/1435

I debated commenting on that issue instead but it's been closed for over 2 years so figured opening a new one makes more sense.

##### Suggest a fix/enhancement

  The interface of ApiClient as generated for Jersey2 is quite different from say the okhttp one.  In the okhttp case, the status and response headers are local in the invoke method and are made accessible to the caller of the generated Api via a secondary withHttpInfo method.  This secondary method does not exist in the Jersey 2 generated code and the status and response headers are both fields in ApiClient.

The first consequence of this is that if I need to access the response headers for example then I need to do:
```java
MyResponse response = myApi.myMethod();
Map<String, List<String>> respHeaders = myApi.getApiClient().getResponseHeaders();
```

Ideally if I'm using myApi generated class, I'm not sure I should have to reach in and look at the underlying ApiClient.  This also leads to the second problem in that the generated client is not thread safe if one needs to access headers or status.

As it happens the invoke method uses a local status for controlling the response from the method (i.e. return vs. void vs. throw) so if you're not using headers or status it is thread safe.

My proposal is to do something similar to the okhttp implementation so if you don't care about headers or status the invocation of the generated client will remain as it is now.  If you do want to inspect headers for example, the code would become:
```java
ApiResponse<MyResponse> apiResponse = myApi.myMethodWithHttpInfo();
MyResponse response = apiResponse.getData();
Map<String, List<String>> respHeaders = apiResponse.getHeaders();
```

I have made the above changes locally and it's actually a fairly simple change which I'd be happy to submit a PR for.  There is however one issue which I would like to get the Swagger owners' opinion on.

The existing impl does allow one to do `myApi.getApiClient().getResponseHeaders()`.  If we were to follow the exact pattern used in okhttp, this would no longer be the case as there would not be status and response headers fields.  Obviously this is backwards compatibility breaking.  The alternative is to introduce the new methods I describe above and preserve the status and headers fields with the same thread safety caveats as before.  It would however be a bit odd to have two ways to access that data which would potentially return different results but it does allow us to introduce thread safety without breaking backwards compatibility.

A third, more complex option, is to introduce a config option which would dictate whether to generate code as it is today or as I'm suggesting.  Which is the default behaviour is somewhat debatable.

Please let me know your thoughts.

**Comment by tsiq-karold** [comment]
Does anyone have any thoughts on this? Or should I submit a PR before discussing this further?

**Comment by wing328** [comment]
@tsiq-karold sorry for late reply and thanks for bringing this up.

>My proposal is to do something similar to the okhttp implementation so if you don't care about headers or status the invocation of the generated client will remain as it is now. If you do want to inspect headers for example, the code would become:

Yes, please as I think that's the correct way to go and other clients (Python, PHP, Ruby, etc) offer similar methods and developers are happy with such method to retrieve the status and HTTP header so far.

**Comment by tsiq-karold** [comment]
Thanks @wing328.  Any thoughts on the backwards compatibility aspect?  Happy to leave those fields in for compatibility if needed but it will look a little odd.

**Comment by wing328** [comment]
@tsiq-karold Most of the time we aim for backward compatibility but for this one, I would suggest we go ahead with the breaking change by removing those fields so as to prevent developers from experiencing the issue in the multi-threading environment.

We'll mark the change as "Breaking Changes without fallback"
