### ISSUE TITLE
[Ada] wrong JSON in POST operations

### ISSUE THREAD

**Issue by micheleISEP** [swagger-api/swagger-codegen#7459]
##### Description

Generated code does not provide correct POST operations. In fact, the Ada code ends up sending JSON:

{"registerReqBody":{"providedService":{"serviceGroup":"Temperatures","serviceDefinition":"tempera1","interfaces":[],"serviceMetadata":{"entry":[]}},"serviceURI":"127.0.0.1:7223","version": 1,"isUDP":true}}

while the correct JSON would be:

{"providedService":{"serviceGroup":"Temperatures","serviceDefinition":"tempera1","interfaces":[],"serviceMetadata":{"entry":[]}},"serviceURI":"127.0.0.1:7223","version": 1,"isUDP":true}

The latter JSON is confirmed by editor.swagger.io, and by Java code generated with the same YML.

##### Swagger-codegen version

2.3.1, downloaded from git on January 20, 2018

##### Swagger declaration file content or url

```yaml

swagger: '2.0'
# edited with http://editor.swagger.io/
info:
  version: 1.0.0
  title: AH Registry
  description: Service Interface for Arrowhead Registry
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: Michele Albano
    email: mialb@isep.ipp.pt
    url: http://www.cister.isep.ipp.pt/people/michele_albano/
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
#host: arrowhead.tmit.bme.hu
host: 127.0.0.1:8442
basePath: "/serviceregistry"
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json


paths: 
  /register:
    post:
      description: Registers a service
      operationId: register
      parameters:
        - name: registerReqBody
          in: body
          description: Operation to register a service instance. All details must be specified for both the service, and its provider
          required: true
          schema:
            $ref: '#/definitions/serviceRegistryEntryType'
      responses:
        200:
          description: Data of the service that was registered
          schema:
            $ref: '#/definitions/serviceRegistryEntryType'
        default:
          description: Unexpected error

definitions: 
  metadata:
    type: "object"
    properties:
      entry:
        type: array
        items:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
  serviceRegistryEntryType:
    type: object
    required:
# unique id
      - providedService
      - provider
# rest of stuff
      - UDP
      - serviceURI
      - version
    properties:
      providedService:
        $ref: '#/definitions/arrowheadServiceType'
      serviceURI:
        type: string
      version:
        type: integer
        format: int32
      isUDP:
        type: boolean
  arrowheadServiceType:
    type: object
    required:
# unique id
      - serviceGroup
      - serviceDefinition
# rest of stuff
      - interfaces
      - serviceMetadata
    properties:
      serviceGroup:
        type: string
      serviceDefinition:
        type: string
      interfaces:
        type: array
        items:
          type: string
      serviceMetadata:
        $ref: '#/definitions/metadata'


```

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ../openapiAHregistrerShorter.yml -l ada -o ../ada-code/ --api-package Arrowhead.Registry --model-package Arrowhead.Registry

##### Steps to reproduce

- generate the code (see previous file)
- compile with gnat
- either dump the serialized model, or use tcpdump

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

In the generated *-models.adb, it is necessary to change the "Serialize" functions for some of the data models:
      Into.Start_Entity (Name);
      Into.End_Entity (Name);
to:
      Into.Start_Entity ("");
      Into.End_Entity ("");

In particular, they have to be changed for the models generated for the "in: body" parts of the YML files. No need for that for the "definitions" section.

**Comment by stcarrez** [comment]
Thanks for the bug report.

The problem is not in the generated *-models.adb file but instead in the generated
client which calls the Serialize with the "registerReqBody" name.  The generated Register
procedure is doing the following call:

      X.Models.Serialize (Req.Stream, "registerReqBody", Register_Req_Body);

and this should really be:

      X.Models.Serialize (Req.Stream, "", Register_Req_Body);
