### ISSUE TITLE
[Golang] Support for "application/xml" content-type in response payload.

### ISSUE THREAD

**Issue by mr1sunshine** [swagger-api/swagger-codegen#7463]
##### Description

As I can see now there is no support of "application/xml" content-type for Golang API client generation. I can see at least that for java lang there is option called "withXml" which does required thing.

##### Swagger-codegen version

I've tested it with swagger-codegen-cli version 2.3.1

##### Swagger declaration file content or url

[http://petstore.swagger.io/v2/swagger.json](url)

##### Command line used for generation

`java -jar swagger-codegen-cli-2.3.1.jar generate -l go -i http://petstore.swagger.io/v2/swagger.json -o output`

##### Steps to reproduce

Just run provided CLI command and check that generated code accepts only json as response format:
`	err = json.Unmarshal(localVarHttpResponse.Body(), &successPayload)`

##### Suggest a fix/enhancement

Add similar implementation(as it is done for Java client) for Golang.

**Comment by wing328** [comment]
Yup, Java client generator has the `withXml` option to support XML payload. May I know if you've time to implement something similar for Go client generator?

**Comment by mr1sunshine** [comment]
@wing328 Yes. Actually, I'm already working on it. Will be ready soon.

**Comment by mr1sunshine** [comment]
Basic implementation is done. Properties support is under #7631
