### ISSUE TITLE
[TypeScript][Aurelia] Bug: imports in ...Api.ts files are broken

### ISSUE THREAD

**Issue by macjohnny** [swagger-api/swagger-codegen#7465]
##### Description

The imports in the `...Api.ts` files are broken, see e.g.
https://github.com/swagger-api/swagger-codegen/blob/v2.3.1/samples/client/petstore/typescript-aurelia/default/PetApi.ts#L18

##### Swagger-codegen version

2.3.1, was already there in 2.3.0, and probably before, too.

##### Swagger declaration file content or url
see example petstore yaml

**Comment by macjohnny** [comment]
@ksm2 would you like to try to fix this?

**Comment by ksm2** [comment]
Hi @macjohnny, I think I can do this at Sunday!

**Comment by macjohnny** [comment]
@ksm2 awesome!
