### ISSUE TITLE
[haskell-http-client] add the ability to customize module prefix

### ISSUE THREAD

**Issue by guoshimin** [swagger-api/swagger-codegen#7482]
##### Description

Currently the haskell-http-client module seems to derive the Haskell module names from the OpenAPI spec. It would be nice if we can customize the module prefix. So, for example,  instead of `Kubernetes.*`, generate `Network.Kubernetes.Client.*`.

I looked at the code and it doesn't seem it's customizable at the moment. If I missed something please let me know. Thanks!

cc @jonschoning 

##### Swagger-codegen version

HEAD. Not a regression.

**Comment by wing328** [comment]
@guoshimin the PR by @jonschoning has been merged into master. Please pull the latest master to give it a try.
