### ISSUE TITLE
[typescript-angular] method names that are reserved words begin with underscore

### ISSUE THREAD

**Issue by crhistianr** [swagger-api/swagger-codegen#7493]
##### Description

Reserved words are unnecessarily sanitized for method names. 

Having a method called service.delete for example is perfectly valid and we shouldn't be transforming names unless there is a good reason to do so.

##### Swagger-codegen version

3.0.0

##### Swagger declaration file content or url

```json
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Reserved Words Issue",
        "description": "Reserved words changing method names",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Crhistian Ramirez"
        },
        "license": {
            "name": "MIT"
        }
    },
    "host": "example.com",
    "basePath": "/api",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/example": {
            "delete": {
                "responses": {
                    "204": {
                        "description": ""
                    }
                },
                "operationId": "Delete",
                "tags": [
                    "ApprovalRule"
                ],
                "parameters": []
            }
        }
    }
}
```

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate  generate -l typescript-angular -i example.json -o outputexample

##### Steps to reproduce

1. Save above spec as example.json
2. Run above command to generate angular-typescript client
3. inspect the method `_delete` in outputexample/api/approvalRule.service.ts

##### Suggest a fix/enhancement

It looks like we're using nickname in the template:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache#L115-L118

Which maps directly to operationId, which incidentally probably shouldn't be used anymore, looks like its just there as legacy support.
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2291-L2292

I suggest we either replace nickname where its being used as a method with `operationIdCamelCase` so `_delete` would appear as `Delete`

OR

we hijack nickname and transform it to remove underscores. 

I'd be willing to make these changes if accepted.

**Comment by macjohnny** [comment]
Sounds reasonable to me

**Comment by crhistianr** [comment]
Ok, got it.

**Comment by macjohnny** [comment]
@kenisteward @sebastianhaas what is your opinion on that?

**Comment by macjohnny** [comment]
this issue is related to https://github.com/swagger-api/swagger-codegen/issues/7484
