### ISSUE TITLE
Void and Object ambiguous

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#751]
when I build using android as language, all the class in client folder use the custom Object and Void class and the compiler say that are ambiguous with System classes.

Any idea?

**Comment by wing328** [comment]
Are you using the develop_2.0 branch ? Do you mind sharing the spec with us ?

Giuseppe <notifications@github.com> 於 2015年5月17日 下午6:47 寫道：

**Comment by uniprof** [comment]
I did try with the master and the develop_2.0 branch, same problem.

I am trying to generate csharp and java from this doc: http://easydocs.azurewebsites.net/swagger/docs/v1

**Comment by wing328** [comment]
I noticed the following is defined as response
```
responses: {
  200: {
    description: "OK",
    schema: {
      $ref: "#/definitions/Void"
    }
  }
},
```
and "Void" is defined as an object without properties as follows:
```
Void: {
  type: "object",
  properties: { }
},
```
From what I understand that's not a correct way to define a "void" response.

To define "void" response, please refer to [petstore.json#L49](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L49) as an example (which simply omits the HTTP 200 response)

**Comment by fehguy** [comment]
Sounds like something we either need to special case in swagger-codegen or fix in swashbuckle

**Comment by wing328** [comment]
I would suggest fixing in swashbuckle as other tools built on top of Swagger spec may not expect "void" response defined as a model with no property.

**Comment by wing328** [comment]
If not defining HTTP response 200 is the preferred/correct way to define void response of an endpoint, I'll check with the owner of swashbuckle to see if he/she has cycle to update that.

**Comment by webron** [comment]
@domaindrivendev - any chance you can take a look at this please?

**Comment by domaindrivendev** [comment]
This looks like a SB bug for sure. Thought I had tests around correct generation of void response (i.e. 204, no Schema) so have a feeling this may be a special case.

@uniprof - can you give a bit more detail ... which version of SB, C# action signature etc.?

**Comment by uniprof** [comment]
This happens when the response is a IHttpResult and the response is ok() that mean http 200
That is the standard response created by the Identity layer in ASP.NET Web API 2.2

I think this something to be solved at swashbuckle.

**Comment by fehguy** [comment]
OK I'm going to close this out as it's an issue with Swashbuckle.  If you can't get it sorted out there, we can reopen and change the c# generator for special handling (wouldn't be the first time we've had to do this).

**Comment by uniprof** [comment]
No way, sounds like need to be fixed from generator side, can you please reopen and handling it?

**Comment by fehguy** [comment]
OK, send me your entire JSON spec (email is fine)

**Comment by domaindrivendev** [comment]
This is being addressed in SB (see https://github.com/domaindrivendev/Swashbuckle/issues/344) and will go out with the next release.

**Comment by wing328** [comment]
Thanks @domaindrivendev !
