### ISSUE TITLE
Where are the templates in 3.0.0?

### ISSUE THREAD

**Issue by nateroling** [swagger-api/swagger-codegen#7521]
I would like to submit a PR to fix an issue in 3.0.0 (#7505), but I'm unable to find the templates.

I see some references in the commits to them being moved to another repo.

Am I able to contribute to the 3.0.0 branch, or is it not ready for that yet?

**Comment by marcoreni** [comment]
https://github.com/swagger-api/swagger-codegen-generators

**Comment by nateroling** [comment]
@marcoreni It looks like only the Java generator templates are there...

**Comment by marcoreni** [comment]
As specified inside the release notes for 3.0.0rc0, for now those are the
only ones that have been posted to OAS..

Il 29 gen 2018 17:51, "nateroling" <notifications@github.com> ha scritto:

**Comment by nateroling** [comment]
Found the release notes, thank you!
https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0-rc0
