### ISSUE TITLE
RubyClientCodegen.java seems doesn't support different naming conventions

### ISSUE THREAD

**Issue by YaroslawEkimov** [swagger-api/swagger-codegen#7536]
Hi guys, sorry if such issue already existed, I hadn't found it.
So the issue is I'm working on ruby sdk and bumped into problem with naming convention.
My config file is
{
	"moduleName": "RubySdk",
	"gemVersion": "1.0",
	"gemName": "ruby_sdk",
	"variableNamingConvention":"camelCase"
}

After my sdk is generated I see that naming convention still the same - snake_case. Hovewer in PhpClientCodegen I found this code
`if (additionalProperties.containsKey(VARIABLE_NAMING_CONVENTION)) {
            this.setParameterNamingConvention((String) additionalProperties.get(VARIABLE_NAMING_CONVENTION));
        }`
but in RubyClient I didn't find such kind of code.
Can you give me any advises how can I achieve this behavior?

Thank you in advance.

**Comment by wing328** [comment]
You're correct in saying that the Ruby client does not support `variableNamingConvention` as it contains the logic to serialize/deserialize JSON payload properly.

What issue did you run into with the Ruby client?

**Comment by YaroslawEkimov** [comment]
Hi, thank you for fast answer.
The issue is I have, for instance, this path for method: `/base/{name}/objectProperties/{propertyName}`
so as you can see path contains variables in camelCase. Then I want to replace all variables in path to correspond values like this:
`path.sub('{' + '{{paramName}}' + '}')` or `path.sub('{' + '{{baseName}}' + '}')` in my template. The first one gives me something like `property_name` and second just `PropertyName`.
So my question is how to manage this scenario?

**Comment by wing328** [comment]
Are you using the latest stable version (2.3.1)? The naming convention of the path parameters should be transparent to the users of the Ruby SDK.

**Comment by wing328** [comment]
I'll also double check tomorrow when I've time.

**Comment by YaroslawEkimov** [comment]
I use 2.3.0

**Comment by wing328** [comment]
I did some tests and it works for me even though I changed the property naming in the spec.

If the path is `/base/{name}/objectProperties/{propertyName}`, how is the path parmeter (especially `propertyName`) documented in the spec?

**Comment by wing328** [comment]
> "name": "PropertyName",

That's the problem as it's not the same as the one defined in the path `propertyName`
