### ISSUE TITLE
[3.0.0][Golang] Support Golang in OAS3

### ISSUE THREAD

**Issue by mr1sunshine** [swagger-api/swagger-codegen#7570]
##### Description

Are there any already created issues about Golang support in OAS3? or should this issue be addressed to [https://github.com/swagger-api/swagger-codegen-generators](url)? As I can see now there is only java version available?

**Comment by HugoMario** [comment]
@mr1sunshine 

yes, right now it should be addressed to https://github.com/swagger-api/swagger-codegen-generators
