### ISSUE TITLE
[PHP] Async Client

### ISSUE THREAD

**Issue by behrad** [swagger-api/swagger-codegen#7603]
##### Suggest a fix/enhancement

Can codegen generate an async client for PHP?

**Comment by wing328** [comment]
Have you tried the latest stable version or master?

The latest PHP client uses Guzzle, which supports async requests: http://docs.guzzlephp.org/en/stable/faq.html

**Comment by wing328** [comment]
No problem.Let us know if you need help on that.

Closing the issue for the time being.
