### ISSUE TITLE
Wrong feeder filenames in gatling tests 

### ISSUE THREAD

**Issue by atomfrede** [swagger-api/swagger-codegen#7616]
##### Description

Gatling language generates wrongly named `bodyParams` feeder file.
The generator generates e.g. `xyz-BodyParams.csv` while the generated gatling test expects `xyz-bodyParams.csv` which is also in line with other feeder files e.g. `-headerParams.csv`.

##### Swagger-codegen version

Latest master

##### Swagger declaration file content or url

Not relevant

##### Command line used for generation

`...l scala-gatling...`

##### Steps to reproduce

Use a yaml spec with body parameters and generate the gatling project. 

##### Related issues/PRs

None found.

##### Suggest a fix/enhancement

Change

```java
 FileUtils.writeStringToFile(new File(outputFolder + File.separator + dataFolder + File.separator + operation.getOperationId() + "-" + "BodyParams.csv"), StringUtils.join(bodyFeederParams, ","));
```

to

```java
 FileUtils.writeStringToFile(new File(outputFolder + File.separator + dataFolder + File.separator + operation.getOperationId() + "-" + "bodyParams.csv"), StringUtils.join(bodyFeederParams, ","));
```

I can do a PR for that.

**Comment by wing328** [comment]
@atomfrede thanks for reporting the issue. Please file a PR so that we can review the fix more easily. Thanks!

**Comment by atomfrede** [comment]
@wing328 I will make a PR during the weekend.
