### ISSUE TITLE
[JAVA] Bug generating nodejs-server with googleCloudFunctions=true

### ISSUE THREAD

**Issue by mfurlend** [swagger-api/swagger-codegen#7632]
##### Description
When the hostname is blank in swagger.yaml there is a `java.lang.NullPointerException` at line 347 of `https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java`

##### Swagger-codegen version
tip of the master branch

##### Swagger declaration file content or url
anything without a host field

##### Command line used for generation
`java -jar ~/programming/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i ~/Downloads/swagger.json \
  -l nodejs-server --additional-properties=googleCloudFunctions=true`

##### Steps to reproduce

1. create a swagger.yaml that lacks a host field
2. try to generate nodejs-server with `--additional-properties=googleCloudFunctions=true`
3. fail

##### Suggest a fix/enhancement
check that `host` is defined before checking if it ends with `cloudfunctions.net`

**Comment by wing328** [comment]
@mfurlend thanks for reporting the issue. I've filed https://github.com/swagger-api/swagger-codegen/pull/7633 to fix the issue. I tested locally with undefined `host` and could no longer repeat the NPE.

**Comment by wing328** [comment]
@mfurlend the fix has been merged into master. Please pull the latest or use the SNAPSHOT version to give it a try.
