### ISSUE TITLE
Errors in code generated for typescript-angular. (Angular 5.1.1) (using the maven plugin)

### ISSUE THREAD

**Issue by marcoaltieri** [swagger-api/swagger-codegen#7647]
##### Description
I have used the swagger-codegen maven plugin to generate the client code for typescript-angular.
The pom file is:
https://gist.github.com/marcoaltieri/e89758aac2d95a33b8cece599331ab2f

##### Swagger-codegen version
As mentioned in the pom file, I am using 2.2.2

##### Swagger declaration file content or url

https://gist.github.com/marcoaltieri/df660aa8ab3a428df74e597e645aed8a

##### Command line used for generation
See pom.xml
##### Steps to reproduce
mvn clean compile
tsc /core/contracts/exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts

tsc returns the following errors:

../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(23,34): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(36,127): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(60,32): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(80,117): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(99,32): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(119,113): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(133,32): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(152,113): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(166,32): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(184,103): error TS2503: Cannot find namespace 'ng'.
../../exaricm-ui/src/app/contracts-api/api/DocumentQueueApi.ts(193,32): error TS2503: Cannot find namespace 'ng'.

**Comment by macjohnny** [comment]
@marcoaltieri since you are using angular, you need to define the `ng` namespace. To do so, you will need to add the types in your `tsconfig.json` as follows:
```
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types"
    ],
    ...
  }
```
If you are unsure how to compile an angular project, I recommend you to [create a new project with Angular CLI](https://angular.io/guide/quickstart)

**Comment by marcoaltieri** [comment]
It worked when I started to use the latest version of the maven plugin (currently 2.3.1)
