### ISSUE TITLE
[JavaJaxRS] add @Valid annotation for generated beans

### ISSUE THREAD

**Issue by bsirenko** [swagger-api/swagger-codegen#7651]
##### Description

It seems that bean validation for JavaJaxRs module is not in sync with pure Java module. @Valid annotation is missing on object references, which means that even if they contain any of bean validation annotations they won't have any impact since the validation is not activated. I can see that there was a commit to add this functionality into Java module. Here is a link: https://github.com/swagger-api/swagger-codegen/commit/d08d55d4190c916e2ce8c55be27a9da4eaa4b0e8#diff-cdacab44bbe95919b17233ba1735d732. Would it be possible to add the same logic into beanValidation.mustache for JavaJaxRs module?

##### Swagger-codegen version

2.2.3
##### Suggest a fix/enhancement

fix is available for Java module: https://github.com/swagger-api/swagger-codegen/commit/d08d55d4190c916e2ce8c55be27a9da4eaa4b0e8#diff-cdacab44bbe95919b17233ba1735d732

**Comment by jmini** [comment]
The same two files are under the `JavaJaxRS/` folder (for the `jaxrs` language):

* [model.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/model.mustache)
* [beanValidation.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/beanValidation.mustache)

You should try to do the same modification than in commit d08d55d4190c916e2ce8c55be27a9da4eaa4b0e8 on those other files locally, test it and if it works, propose a pull request.

---
There is a lot of copy-paste code in the `mustache` template. This means that a modification should be made everywhere (`Java/` and `JavaJaxRS/`).
=> This could be discussed here: #4937

**Comment by deveshpujari** [comment]
@jmini @wing328 
This issue still exists in the Swagger-codegen version 2.3.1 for javaJaxRS/ .  Is it possible for some one to quickly add in 2.4.0 Snapshot ? thanks .

**Comment by HugoMario** [comment]
closing this on favor of #8641
