### ISSUE TITLE
[Java - feign library] serialize only non null properties

### ISSUE THREAD

**Issue by TemaniH** [swagger-api/swagger-codegen#7654]
**Description**
I would like to config the ObjectMapper to serialize only non null properties.
This is due to 2 small issues:
1. To avoid sending unnecessary data.
what's the benefit of sending null data over the net?
1. To avoid sending Unmapped data.
e.g. if Microservice A is sending Microservice B an Object with 2 fields 'a' and 'b' but is only mapping 'a',
A might expect that only 'a' is being sent.
If  B breaks his API by removing field 'b' its transparent to A (not that its valid, but A should not be the blocker)

**Suggest a Fix**
Configure objectMapper:
objectMapper.setSerializationInclusion([Include.NON_NULL](https://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonInclude.Include.html#NON_NULL));

p.s.
if there is any objection/ disagreement / BWC issue.
can we atleast make it optional/configurable (like joda / java8 / threetenbp) ?

**Comment by cbornet** [comment]
You can access the object mapper with the ApiClient’s getObjectMapper method to configure it as you wish.
Now I wouldn’t be against making Include.NON_NULL the default.

**Comment by TemaniH** [comment]
Thanks for the fast and simple solution.

regarding 'making Include.NON_NULL the default'.
With the above  i don't think there is any motivation and we can close the issue.
If you think there is need, i don't mind making it default with a config argument.
