### ISSUE TITLE
[csharp] Referencing standalone enum generates uncompilable enum

### ISSUE THREAD

**Issue by donqstepper** [swagger-api/swagger-codegen#7657]
##### Duplicate, please close
* Sorry, I started writing this last night and in the meantime #7656 has been raised for the same issue. Please accept my apologies and close this as a duplicate.

##### Description

Using the csharp generator, when generating for a swagger definition which uses a referenced type which itself references a standalone enum type, the generated enum code is malformed/does not compile.

##### Swagger-codegen version

2.3.1 (does not happen in 2.3.0)
Also checked it still occurs on master as of aa6b217

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  title: Enum failure reproduction
  description: "Minimal-ish reproduction of enum generation failure in swagger-codegen 2.3.1"
  version: 1
paths:
  /discussions:
    post:
      operationId: createDiscussion
      summary: Create discussion
      parameters:
        - name: discussion
          in: body
          description: Discussion to create.
          required: true
          schema:
            $ref: "#/definitions/NewDiscussion"
definitions:
  NewDiscussion:
    type: object
    properties:
      status:
        $ref: '#/definitions/DiscussionStatus'
    required:
      - status
  DiscussionStatus:
    type: string
    description: Status of the discussion.
    enum: 
      - "open"
      - "closed"
      - "review"
```

##### Command line used for generation

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.yaml -l csharp -o /tmp/broken -DpackageName=CommentingServiceClient`

##### Steps to reproduce

1. Run above command line
2. Attempt to build resulting solution, or open DiscussionStatus.cs and observe:

```csharp
namespace CommentingServiceClient.Model
{
    /// <summary>
    /// Status of the discussion.
    /// </summary>
    /// <value>Status of the discussion.</value>
    
    public enum DiscussionStatus
    {
        
        /// <summary>
        /// Enum Open for value: open
        /// </summary>
        
        Open = open,
        
        /// <summary>
        /// Enum Closed for value: closed
        /// </summary>
        
        Closed = closed,
        
        /// <summary>
        /// Enum Review for value: review
        /// </summary>
        
        Review = review
    }

}
```

As you can see, this will not compile.

##### Related issues/PRs

Duplicate of #7656 - please close

##### Suggest a fix/enhancement

This issue goes away if you inline the definition of NewDiscussion (or DiscussionStatus, but that also removes the standalone enum class). Unfortunately this is not a viable workaround if you wish to reuse the type.

**Comment by frantuma** [comment]
should be fixed in #9936
