### ISSUE TITLE
multipart/form-data body sent with application/x-www-form-urlencoded content-type header

### ISSUE THREAD

**Issue by shupp** [swagger-api/swagger-codegen#7668]
##### Description
My swagger document indicates it consumes "application/x-www-form-urlencoded".  The generated GO sdk sets that header, but then builds the parameter into an multipart body.  I used netcat to see what query is being sent by the client:

```
$ nc -l localhost 5000
POST /1.0/token HTTP/1.1
Host: localhost:5000
User-Agent: Swagger-Codegen/1.0.0/go
Content-Length: 203
Accept: application/json
Authorization: Basic bWU6c2VjcmV0
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

--ceb5c60a585899c0667172c5af5a5ed29b747fa332c5f179ed996a69d7db
Content-Disposition: form-data; name="grant_type"

client_credentials
--ceb5c60a585899c0667172c5af5a5ed29b747fa332c5f179ed996a69d7db--
```

##### Swagger-codegen version

Today's master, which displays as "2.4.0-SNAPSHOT".  This is the case with 2.3.1 as well.

##### Swagger declaration file content or url

https://github.com/shupp/VegaDNS-API/blob/master/swagger/vegadns.swagger.json

##### Command line used for generation

java -jar ./swagger-codegen-cli.jar generate -i vegadns.swagger.json -l go -o vegadns -c config

##### Steps to reproduce

You can run netcat as I did above, then run this go code:

```go
package main

import (
    "context"
    "fmt"
)

func main() {
    config := vegadns.NewConfiguration()
    client := vegadns.NewAPIClient(config)

    auth := context.WithValue(context.Background(), vegadns.ContextBasicAuth, vegadns.BasicAuth{
        UserName: "me",
        Password: "secret",
    })

    response, err := client.UtilityApi.TokenPost(auth, "client_credentials")
}
```

##### Related issues/PRs

None that I could find.

##### Suggest a fix/enhancement

When building the request body, the SDK needs to differentiate between application/x-www-form-urlencoded and multipart/form-data.

**Comment by rubens21** [comment]
@shupp Have you found the solution?
Apparentely, there is also another but when we set the content-type to `x-www-form-urlencoded`. The parameters are not sent correctly. I believe I've found the cause of this error, I'll try to make a PR for it.

**Comment by shupp** [comment]
@rubens21 I have not found a solution.  Please do a PR if you have one!  Thanks...

**Comment by Splash34** [comment]
+1

**Comment by HugoMario** [comment]
covered by #8767
