### ISSUE TITLE
[angular] Bug withInterfaces does not support usehttpclient

### ISSUE THREAD

**Issue by liuy97** [swagger-api/swagger-codegen#7711]
##### Description

@angular/http is still used in interface. The interface codes cannot find required model types. The related classes cannot resolve interface files.

##### Swagger-codegen version

swagger-codegen-cli-2.4.0-20180222.131322-150.jar

##### Swagger declaration file content or url

modules/swagger-codegen/src/test/resources/2_0/petstore.yaml

##### Command line used for generation

java -jar swagger-codegen-cli-2.4.0-20180222.131322-150.jar generate -i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml -l typescript-angular -c bin/typescript-petstore-npm.json -o samples/client/petstore/typescript-angular-v4.3/npm --additional-properties ngVersion=4.3 -D withInterfaces=true 

##### Steps to reproduce

[generated interface and class](https://gist.github.com/liuy97/e2e94077c6ea50d16b4a507df3463424)
##### Suggest a fix/enhancement

add usehttpclient support in apiInterface.mustache

**Comment by jagrodal** [comment]
I am experiencing the same issue

**Comment by liuy97** [comment]
I fix it for now [issue7711](https://github.com/liuy97/swagger-codegen). If this bug is approved, I will send a pull request.

**Comment by jagrodal** [comment]
I do the same thing. The stubs that is used in unit tests implement the interface generated by swagger codegen. This way is is easy to make sure that the stub is in sync with the actual API service. It also makes speeds up making these stubs since the declaration of functions can be auto-generated by the IDE.

**Comment by kenisteward** [comment]
@liuy97 @jagrodal 

I see your points,  this seems to be a very helpful feature so I'll try to keep that in mind in the future. 

Our perspectives were slightly different.  I didn't rely on the library itself to generate them.  My team created the mocks based off the models before these were here.

**Comment by kenisteward** [comment]
@liuy97 @jagrodal 

I'll look into instead of just generating the interfaces, actually generating the spied classes based on the yaml.  That way you never have to update the mocks at all.

**Comment by mrpaaske** [comment]
@kenisteward did you manage to look into generating the spied classes?
