### ISSUE TITLE
[JAVA] schemas with array types are not generated in 3.0.0

### ISSUE THREAD

**Issue by mike03081972** [swagger-api/swagger-codegen#7713]
##### Description

Schemas with array types are not generated

##### Swagger-codegen version

swagger-codegen-cli-3.0.0-20180216.030259-21
swagger-codegen-cli-3.0.0-20180221.003354-22

##### Swagger declaration file content or url

This is the YAML file that I used to show the problem.
```yaml
openapi: 3.0.0
components:
  schemas:
    Test1:
      type: object
      properties:
        name:
          type: string
    Test2:
      type: array
      items:
        type: string
```
##### Configuration file used

```json
{
  "modelPackage" : "com.mma.web.payloads.v0",
  "sourceFolder" : "",
  "dateLibrary"  : "java8",
  "library"      :  "feign"
}
```

##### Command line used for generation

```
java -jar -Dmodels .\swagger-codegen-cli-3.0.0-20180216.030259-21.jar generate -l java -i .\simple_3_0.yaml -c .\java-config.json -o c:\temp\
```

##### Steps to reproduce

Run the codegen:
```
java -jar -Dmodels .\swagger-codegen-cli-3.0.0-20180216.030259-21.jar generate -l java -i .\simple_3_0.yaml -c .\java-config.json -o c:\temp\
```

##### Output of the generator

```
[Thread-1] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
[Thread-1] INFO io.swagger.codegen.languages.java.AbstractJavaCodegen - Invoker Package Name, originally not set, is now dervied from model package name: com.mma.web.payloads
[Thread-1] INFO io.swagger.codegen.AbstractGenerator - writing file c:\temp\com\mma\web\payloads\v0\Test1.java
```

##### What's missing

The Test2 schema is not generated !

##### Work's with generator 2.3.1 with swagger 2.0

```yaml
swagger: '2.0'
definitions:
  Test1:
    type: object
    properties:
      name:
        type: string
  Test2:
    type: array
    items:
      type: string
```

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./simple_2_0.yaml
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
[main] INFO io.swagger.codegen.languages.AbstractJavaCodegen - Invoker Package Name, originally not set, is now dervied from model package name: com.mma.web.payloads
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\temp\com\mma\web\payloads\v0\Test1.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\temp\com\mma\web\payloads\v0\Test2.java
```

**Comment by mike03081972** [comment]
Not working any more with version:

- swagger-codegen-cli-3.0.0-20180223.212535-23
- swagger-codegen-cli-3.0.0-20180226.055311-24
- swagger-codegen-cli-3.0.0-20180226.055655-25

**Comment by jmini** [comment]
For your problem, I tried with:

```
openapi: 3.0.1
info:
  title: array test
  version: '1.0'
servers:
  - url: 'http://localhost:8000/'
paths:
  /myendpoint:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test2'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Test1:
      type: object
      properties:
        name:
          type: string
    Test2:
      type: array
      items:
        type: string
```

I can confirm that no class `io.swagger.client.model.Test2` is generated. But is this necessary? There is a method `myendpointPost(List<String> body)` in `DefaultApi` and this is correct. `Test2` defines a list of String. I do not think that a Model object is requested for that.

---

As for your error, this might comes from my commit: 7732083a1bee0604d2c030b41e3d8c98c07548ee
But if a `swagger-codegen-generators-<version>.jar` is on the classpath, the java generator is registered (see commit https://github.com/swagger-api/swagger-codegen-generators/commit/992db7300d546f6cbb2844df9a6e1ae3468fcb76)

During a small period of time, the `swagger-codegen-generators-1.0.0-SNAPSHOT.jar` was not published online. See: https://github.com/swagger-api/swagger-codegen-generators/issues/23

I guess that the `cli` jar was containing an old version of the `generators` jar.
I have built a `cli` jar locally with maven and it was fixed without any additional modifications.
I think that the latest `cli` jar available online should also work.

Can you retry with a newer version? `swagger-codegen-cli-3.0.0-20180226.055655-25.jar` is old.

**Comment by mike03081972** [comment]
Hi,

The latest avalaible generator 'swagger-codegen-cli-3.0.0-20180228.021013-28.jar' is working.

For me it's OK when Test2 is not generated but I thing it's strange because all 2.x generator will generate it.

**Comment by pellyadolfo** [comment]
[ERROR] Failed to execute goal io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.8:generate (default) on project client.swagger.android: Execution default of goal io.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.8:generate failed: Can't load config class with name android Available: aspnetcore

**Comment by houtianze** [comment]
`Exception in thread "main" java.lang.RuntimeException: Can't load config class with name android Available: aspnetcore`

**Comment by houtianze** [comment]
version `3.0.8`
