### ISSUE TITLE
Request: Liberate DefaultGenerator!

### ISSUE THREAD

**Issue by dankling** [swagger-api/swagger-codegen#7722]
##### Description

Hey all,

I'm looking to get creative with my generated APIs/Controllers and it looks like there's a few `private` methods in `DefaultGenerator` that would really benefit me if they were to be made `protected`. For instance, the `private void generateApis(List<File> files, List<Object> allOperations, List<Object> allModels)` is a great target to be able to override in order to customize logic around the operations on a path/endpoint.

Let me know what you think and I can open up a PR.

**Comment by macjohnny** [comment]
@dankling I think this sounds reasonable

**Comment by frantuma** [comment]
Thanks! implemented in #9136 (includes #8097)

**Comment by dankling** [comment]
Could we get these changes on the 3 release?
