### ISSUE TITLE
[JAVA] Question how to get uri req res body from a yaml

### ISSUE THREAD

**Issue by lihaoHuawei** [swagger-api/swagger-codegen#7765]
##### Description
here is my question:
I want to get uri,request,response body,response code from a swagger yaml file.
Then I can put them into my own database.
Like this
![image](https://user-images.githubusercontent.com/24602093/37012766-3e235abc-2131-11e8-9600-b40fc0381e73.png)

##### Swagger-codegen version

none

**Comment by jmini** [comment]
This is the wrong project to ask this question. This project is about generating applications (client or server) derived from a swagger specification.

I recommend you to use a parser (if you write java code you can use `io.swagger:swagger-parser:1.0.34`) then read the specification and do what ever you want while reading the specification.

I am ready to help you if you need more details, but I would prefer a question on StackOverflow (you can link you question here).

Please close this issue.

**Comment by lihaoHuawei** [comment]
Thanks!here is my stackoverflow link:
https://stackoverflow.com/questions/49142700/how-to-get-uri-req-res-body-from-a-yaml-by-swagger-parser
