### ISSUE TITLE
[Python] [SSL: CERTIFICATE_VERIFY_FAILED] Even with verify_ssl = False

### ISSUE THREAD

**Issue by Markoscl** [swagger-api/swagger-codegen#7778]
##### Description

Attempting to connect to a unverified host throws:

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1.2.3.4', port=443): Max retries exceeded with url: /myAPI/rest/user/list (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
```
If i enable the following flags:

```python
        client.configuration.verify_ssl = False
        client.configuration.ssl_ca_cert = None
        client.configuration.assert_hostname = False
        client.configuration.cert_file = None
```

I expect the problem to go away, urllib should trust the certificate and everyone should be happy, but this is sadly not happening.

The expected behaviour is that if i explicitely specify that i want to disable ssl verification, i should be able to do so.

##### Swagger-codegen version
Version being used:
2.3.1

Provided at:

http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar

##### Swagger declaration file content or url

```json
{
        "packageName": "mapiclient",
        "projectName": "mapiclient",
        "packageVersion": "1.0.0",
        "library": "urllib3"
    }
```

##### Command line used for generation

```bash
    java -Dio.swagger.parser.util.RemoteUrl.trustAll=true -jar swagger-codegen-cli.jar generate -i ${SOURCE_SWAGGER} -l python -o ${OUTPUT_FOLDER} -c ${CONFIGURATION}
```
##### Steps to reproduce

- From a swagger.json file, generate a python client with the previous command.
- Attempt to launch a test with the following code:

```python
        # Removed imports etc....
        client = mapiclient.ApiClient()
        client.configuration.host = "1.2.3.4/MyAPI/rest"
        client.configuration.verify_ssl = False
        client.configuration.ssl_ca_cert = None
        client.configuration.assert_hostname = False
        client.configuration.cert_file = None
        self.api_instance = mapiclient.V1Api(api_client=client)

        # Now any method produces the exception
```
##### Related issues/PRs

This PR should be the one that fixes/implements this:

https://github.com/swagger-api/swagger-codegen/pull/1132

**Comment by aburgett87** [comment]
Hey @Markoscl 

I just ran into this issue and to get around it you need to rewrite the client instantiation.

Change your snippet to the following
```python
configuration = mapiclient.Configuration()
configuration.host = "1.2.3.4/MyAPI/rest"
configuration.verify_ssl = False
configuration.ssl_ca_cert = None
configuration.assert_hostname = False
configuration.cert_file = None

client = mapiclient.ApiClient(configuration=configuration)

self.api_instance = mapiclient.V1Api(api_client=client)
````

**Comment by Markoscl** [comment]
Thanks @aburgett87, i will try your solution and will get back with results!

**Comment by Markoscl** [comment]
Sorry for being late, it worked!
