### ISSUE TITLE
[qt5cpp] Generate project include file (*.pri)

### ISSUE THREAD

**Issue by MartinDelille** [swagger-api/swagger-codegen#7784]
##### Description

This would be really nice to have the project include file generated! Example for the Pet store example:

    QT += network
    
    HEADERS += \
    	$${PWD}/SWGApiResponse.h \
    	$${PWD}/SWGCategory.h \
    	$${PWD}/SWGHelpers.h \
    	$${PWD}/SWGHttpRequest.h \
    	$${PWD}/SWGModelFactory.h \
    	$${PWD}/SWGObject.h \
    	$${PWD}/SWGOrder.h \
    	$${PWD}/SWGPet.h \
    	$${PWD}/SWGPetApi.h \
    	$${PWD}/SWGStoreApi.h \
    	$${PWD}/SWGTag.h \
    	$${PWD}/SWGUser.h \
    	$${PWD}/SWGUserApi.h
    
    SOURCES += \
    	$${PWD}/SWGApiResponse.cpp \
    	$${PWD}/SWGCategory.cpp \
    	$${PWD}/SWGHelpers.cpp \
    	$${PWD}/SWGHttpRequest.cpp \
    	$${PWD}/SWGOrder.cpp \
    	$${PWD}/SWGPet.cpp \
    	$${PWD}/SWGPetApi.cpp \
    	$${PWD}/SWGStoreApi.cpp \
    	$${PWD}/SWGTag.cpp \
    	$${PWD}/SWGUser.cpp \
    	$${PWD}/SWGUserApi.cpp

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

https://gist.github.com/MartinDelille/c358209832ed023c1cd7ddb308db0099

##### Command line used for generation

    $ swagger-codegen generate -i api.yml -l qt5cpp

##### Steps to reproduce

None it is a feature request

##### Related issues/PRs

Not that I know.

##### Suggest a fix/enhancement

I'll be happy to make a PR if you provide me some little support!

**Comment by etherealjoy** [comment]
@MartinDelille 
Maybe you could check the example from C# generator? it creates a solution file.

**Comment by MartinDelille** [comment]
Can you point me quickly where does it happens? I'm currently setting up my machine for building `swagger-codegen`.

**Comment by MartinDelille** [comment]
Ok I start to understand how it works.
