### ISSUE TITLE
[typescript/fetch] Implement interfaces for api resources

### ISSUE THREAD

**Issue by tsiq-jeremy** [swagger-api/swagger-codegen#7789]
##### Description

Would like api resources to implement interfaces. Will be helpful for mocking resources or switching them out with internal resources. 

##### Swagger-codegen version

2.3.1
##### Swagger declaration file content or url

```yaml
paths:
  /user:
    get:
      operationId: getUsers
      summary: Returns all users.
```

Currently generated:

```javascript
export class UsersApi extends BaseAPI {
   // snipped..
}
```
Proposed:
```javascript
export interface IUsersApi {
  // snipped.
}

export class UserApi extends BaseAPI implements IUsersApi {
  // snipped.
}
```
##### Related issues/PRs

[typescript/angular2] Implement interfaces for api resources #5453 

##### Suggest a fix/enhancement

Would be happy to implement interfaces in the same way as #5453 but wasn't sure if there was a reason it was just implemented for the angular version and not the other typescript versions?

**Comment by macjohnny** [comment]
@tsiq-jeremy I would say the feature you propose is useful. It should be no problem to include it if you can turn in on and it is disabled by default. 
Would you like to give it a try and implement this?

**Comment by tsiq-jeremy** [comment]
@macjohnny Sure I will give it a try and see how it goes.

**Comment by tsiq-jeremy** [comment]
Hey this is kind of outside the scope of the update I was doing, but it is a bit confusing that all the typescript codegen's have different file conventions. For instance the Angular one places every Api in it's own file, while with the Fetch version everything is done within one file. In the end it does not particularly matter to me since I am going to use the built version, but it does make it a bit confusing while developing to figure out what the best way to do things are. Is there any plan to standardize this?

Another thing I was thinking about is that `withInterfaces` is now being used for both Angular and Fetch, should variables like this be moved to `AbstractTypeScriptClientCodegen` or just duplicate the code in multiple places?
