### ISSUE TITLE
[Typescript-Node] Optional fields in swagger file are generated as required in Typescript

### ISSUE THREAD

**Issue by JakeSummers** [swagger-api/swagger-codegen#7791]
##### Description

When using the `typescript-node` code generator, fields that should be optional are being generated as required.  For example, I have tthe following in my swagger file:

```yaml
definitions:
  User: 
    properties:
      userName:
        type: string
      firstName:
        type: string
    required:
      - userName
```

When I generate TS, I get this:

```
export class User {
    'userName': string;
    'firstName': string;
}
```

I am expecting to get this:

```
export class User {
    'userName': string;
    'firstName'?: string;
}
```

##### Swagger-codegen version

I am generating from: https://editor.swagger.io/ .  Not sure what version this is.

![image](https://user-images.githubusercontent.com/5657503/37117287-d54bc8fa-221e-11e8-9573-b49a8d47f917.png)

##### Swagger declaration file content or url

Full swagger file:

```yaml
swagger: "2.0"
info:
  title: Sample API
  version: 1.0.0


basePath: /v1
schemes:
  - https

paths:
  /user:
    get:
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'

definitions:
  User: 
    properties:
      userName:
        type: string
      firstName:
        type: string
    required:
      - userName
    
    ```

**Comment by macjohnny** [comment]
@JakeSummers sounds reasonable. would you like to give it a try and file a PR? you could have a look at the typescript-angular templates, since the code generated for `angular` handles required / optional fields correctly.

**Comment by JakeSummers** [comment]
@macjohnny - thanks for the reply.  Decided to use typescript-fetch, it supports this.

**Comment by bvwells** [comment]
Thought I'd fix this issue while I was in this area (see PR #7849). Hope it helps!

**Comment by macjohnny** [comment]
@bvwells thank you!

**Comment by wing328** [comment]
@JakeSummers please pull the latest master to give it another try

Thanks for the fix by @bvwells
