### ISSUE TITLE
[Swift 4] unacceptable collection parameter in query

### ISSUE THREAD

**Issue by d-date** [swagger-api/swagger-codegen#7796]
##### Description

When calling api with query parameter which is contain collection (array, dictionary), some letters (`[`, `]` and so on) will be converted to percent-encorded letters. 

in `APIHelper.swift`, the parameter will be converted to String using string interpolation

```swift
    static func mapValuesToQueryItems(values: [String: Any?]) -> [URLQueryItem]? {
        let returnValues = values
            .filter { $0.1 != nil }
            .map { (item: (_key: String, _value: Any?)) -> URLQueryItem in
                URLQueryItem(name: item._key, value: "\(item._value!)")
            }
        if returnValues.count == 0 {
            return nil
        }
        return returnValues
    }
``` 

for example, as passing the array like `[1, 2, 3, 4,]` as a [Int], it'll be converted to `array-parameter=%5B1,%202,%203,%204,%5D` that not acceptable for server.

##### Swagger-codegen version

master, but still exist from 2.3.x

##### Swagger declaration file content or url
```yaml
  /xxx/{id}:
      parameters:
        - in: path
          name: xxx
          type: integer
          required: true
        - $ref: "#/parameters/Array-Parameter"

parameters:
  Array-Parameter:
    in: query
    name: arrayParameter
    type: array
    items:
      type: integer
```

##### Suggest a fix/enhancement

Now that we can understand whether the parameter is array or not, if we find array parameter passing to query, we just convert to string before passing to parameter.

```swift
url?.queryItems = APIHelper.mapValuesToQueryItems(values: [
  "array-parameter": arrayParameters?.reduce(into: "") { $0 += ",\($1)" }
])
```

Before:
```
?array-parameter=%5B1,%202,%203,%204,%5D // [1, 2, 3, 4]
```

After:
```
?array-parameter=1,2,3,4
```

**Comment by alokc83** [comment]
@wing328: as per release: this was fixed in 2.4.0. 
`[Swift 4] Fix APIHelper to accept array parameter (#7821)`
I am still seeing this issue 2.4.4. thoughts?
