### ISSUE TITLE
[Java] $ref type references mangled

### ISSUE THREAD

**Issue by fwielstra** [swagger-api/swagger-codegen#7797]
##### Description

We've built an openapi 3.0.1 spec and are trying to generate models from that via swagger-codegen. The problem occurs with references; in one of our schemas we have a property which is an array to a $ref:

    "deliveryConditions": {
            "type": "array",
            "description": "Delivery conditions array",
            "items": {
              "$ref": "#components/schemas/DeliveryCondition"
            }
          },

Both the schema and the DeliveryCondition schema this refers to generate a model, but the base object's list of DeliveryConditions is mangled:

    @SerializedName("deliveryConditions")
    private List<ComponentsschemasDeliveryCondition> deliveryConditions = new ArrayList<ComponentsschemasDeliveryCondition>();

Expected:

    @SerializedName("deliveryConditions")
    private List<DeliveryCondition> deliveryConditions = new ArrayList<DeliveryCondition>();

As far as I'm aware this is a properly formatted document, the swagger editor does not give any errors. I also tried to make the DeliveryCondition schema a Swagger 2.x type, moving it to a definitions block, but that has the same effect.

If this has been fixed, when is an rc1 being released? rc0 with this apparent bug (and an NPE in API generation but we're not interested in that atm) is already over a month old.

##### Swagger-codegen version

swagger-codegen-cli 3.0.0-rc0

##### Command line used for generation

        task generateSources(type: JavaExec) {
            classpath = sourceSets.main.runtimeClasspath
    
            main = 'io.swagger.codegen.SwaggerCodegen'
    
            args 'generate', '-i', 'src/main/resources/public/swagger/swagger.json', '-l', 'java', '--model-package', 'ps.furby.allocationstrategy.generated', '-Dmodels'
        }

##### Suggest a fix/enhancement

Couldn't find the relevant code, but, probably a bug in the reference to class name logic.

**Comment by webron** [comment]
@fwielstra - your API definition is actually wrong.

It should be:
```json
"deliveryConditions": {
        "type": "array",
        "description": "Delivery conditions array",
        "items": {
          "$ref": "#/components/schemas/DeliveryCondition"
        }
      },
```

Notice the extra `/` after the `#` in the reference. We're aware the editor currently doesn't warn you about that, but that should hopefully change in this week's release.

**Comment by fwielstra** [comment]
@webron That was it, I must've missed that while trying to parse the standard :/. Thanks for pointing out something I've overlooked for forever!
