### ISSUE TITLE
How to create static javascript api

### ISSUE THREAD

**Issue by razakpm** [swagger-api/swagger-codegen#78]
Hi, 
 We like to create static javascript api using swagger. We tried with node.js implementation but we didn't succeeded in the browser.
I need something like ./bin/runscala.sh com.wordnik.swagger.codegen.Basic<B>JS</B>Generator http://petstore.swagger.wordnik.com/api/resources.json

I know a runtime support for javascript is there , but I prefer a static api geneartion.
Any advice is very helpful.

**Comment by jdhiro** [comment]
It looks like this probably fell out of scope at some point. My team would really love to see this working (as well as an Angular $resource based generator).

**Comment by mozey** [comment]
@jdhiro I wrote something to do this a while back. But it's a bit intertwined in other code and I never bothered to extract it. Also, I just used the $http service directly, not $resource. Recently been wondering if swagger-codgen supports static javascript yet and come across this link, have you tried it? https://github.com/wcandillon/swagger-js-codegen

**Comment by who** [comment]
I've written an npm package that can accomplish the original intent of this ticket: 

https://www.npmjs.com/package/swagger-client-standalone

This package builds all of the NPM dependencies, the swagger spec, and swagger client all into one JS file.  I use it in places where I can only use UMD-style includes.  Because modular javascript doesn't work well in UMD environments, I opted to bundle it together.

**Comment by jdhiro** [comment]
@mozey I haven't tried that project yet, but I was going to. They don't support $resource yet either.

@who Yeah, I'm making a library/SDK, so I'm basically just doing a require('swagger.json') and bundling it all up. This really just makes the runtime library superfluous though.

**Comment by jdhiro** [comment]
Good lord, I just realized that this approach is adding over 300kb to my library. That is not an option.

**Comment by wing328** [comment]
@jfiala has created a JS API client generator, which has been merged into master. Please pull the latest master and give it a try.
