### ISSUE TITLE
JS ApiClient Date Parsing 

### ISSUE THREAD

**Issue by dan3721** [swagger-api/swagger-codegen#7822]
##### Description

[ApiClient.mustache.parseDate](http://apiclient.mustache.parsedate/) is yanking the 'T' :

```
{{#emitJSDoc}}/**
    * Parses an ISO-8601 string representation of a date value.
    * @param {String} str The date value as a string.
    * @returns {Date} The parsed date object.
    */{{/emitJSDoc}}
    static parseDate(str) {
        return new Date(str.replace(/T/i, ' '));
    }
```

Not sure exactly why that is being done as I believe the T is actually part of ISO-8601 and works in both Chrome and IE but, this replacement breaks the Date constructor under IE11 and Edge.

console.log(new Date('2017-12-12T10:48:01.000Z')) <- with 'T" works in IE and Chrome
console.log(new Date('2017-12-12 10:48:01.000Z')) <- with 'T' replaced with ' ' works in Chrome but, fails silently in IE and Date returns the string 'Invalid Date'

##### Swagger-codegen version

3.0.0

##### Suggest a fix/enhancement

Ideally the DateTime format should be configurable similar to what we've done for C# client: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/Configuration.cs#L339 - @wing328

**Comment by dan3721** [comment]
#3069 Invalid date parsing for all browsers.

**Comment by webron** [comment]
The 3.0.0 parser doesn't yet support the JS client.

**Comment by dan3721** [comment]
`java -jar ../../swagger-codegen-cli-3.0.0-20170727.135949-1.jar generate -l javascript -DuseES6=true -DapiTests=false -DmodelTests=false -i my.json -o $SERVICE_NAME -DusePromises=true

produces a JS ApiClient.js with:

```
/**
* Parses an ISO-8601 string representation of a date value.
* @param {String} str The date value as a string.
* @returns {Date} The parsed date object.
*/
static parseDate(str) {
    return new Date(str.replace(/T/i, ' '));
}
```

Again the replace is the issue as replacing the 'T' with ' ' breaks the Date constructor in IE causing it to return 'Invalid Date'. Suggest removing the replace; not sure why it is there in the first place.

Thanks,
Dan

**Comment by webron** [comment]
This hasn't changed in the last 18 hours, there's still no support for the JS client with OAS3.
