### ISSUE TITLE
3.0.0 "swagger-codegen-cli.jar meta" "can't load template codegen/pom.mustache"

### ISSUE THREAD

**Issue by jimcullenaus** [swagger-api/swagger-codegen#7845]
##### Description

Following the instructions in the README under "making your own codegen modules", running the initial step as follows produces the following result:

```bash
me@work:path-to/swagger-codegen$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar meta \
>   -o output/myGeneratorDir -n myGeneratorName -p my.company.mygeneratorname
[Thread-1] INFO io.swagger.codegen.cmd.Meta - writing to folder [/mnt/c/path-to/swagger-codegen/output/myGeneratorDir]
[Thread-1] ERROR io.swagger.codegen.AbstractGenerator - codegen/pom.mustache (No such file or directory)
[Thread-1] ERROR io.swagger.codegen.AbstractGenerator - can't load template codegen/pom.mustache
Exception in thread "Thread-1" java.lang.RuntimeException: can't load template codegen/pom.mustache
        at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:51)
        at io.swagger.codegen.cmd.Meta$1.convert(Meta.java:103)
        at io.swagger.codegen.cmd.Meta$1.convert(Meta.java:92)
        at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
        at ch.lambdaj.Lambda.convert(Lambda.java:986)
        at ch.lambdaj.collection.LambdaIterable.doConvert(LambdaIterable.java:142)
        at ch.lambdaj.collection.LambdaList.convert(LambdaList.java:57)
        at io.swagger.codegen.cmd.Meta.run(Meta.java:79)
        at java.lang.Thread.run(Thread.java:748)
```

This is after cloning the repo, switching to the 3.0.0 branch, and running `mvn clean package`, which executed successfully.

This also occurs if I change to the default values like `output/myLibrary`, so it's not an issue of some parts of the codebase hardcoding those values.

##### Swagger-codegen version

3.0.0

Also, Apache Maven version 3.3.9, and JDK version 8.

The same error occurs whether I run in Windows Subsystem for Linux's bash shell, or Windows PowerShell.

**Comment by jmini** [comment]
I don't think that the bootstrap project generated by the engine is up to date with all the changes made with version `3.0.0-SNAPSHOT` of `swagger-codegen`. I will try to have a look at it.

---

This does not mean that you can not write a custom generator already. You can have a look at the generators implemented in the [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators/) repository.

**Comment by jmini** [comment]
I have proposed a Pull Request to make the 'meta' generator work with v3: #7881

**Comment by jimcullenaus** [comment]
Awesome, thanks a bunch.

Out of interest, do you have an idea of roughly how many changes would need to be made to a 2.0 codegen module and associated templates to get up and running on 3.0?

**Comment by jmini** [comment]
I would say that this not complicated at all. The main benefit is that you will be able to use version `openapi: "3.0.1"` (you can also continue to use the `swagger: "2.0"` format, there is a parser to ensure backward compatibility).

---

I try to keep every necessary step in the wiki: 
[Swagger Codegen migration (swagger codegen generators repository)](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-(swagger-codegen-generators-repository))


But this is mostly for the official generators. Some points are about naming convention, code cleanup and refactoring. You do not need to follow each steps.

The most important point is the move from the Mustache templating engine to the Handlebars one. You should change some constructs inside your templates. 
See this wiki page: [Swagger Codegen migration from Mustache and Handlebars templates.](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-from-Mustache-and-Handlebars-templates.)

If you are interested, I have created this class to help with the template migration: [ConvertMustache.java](https://github.com/jmini/openapi-experiments/blob/master/misc/src/misc/ConvertMustache.java)

Feedback is welcomed.

**Comment by HugoMario** [comment]
Hey @jimcullenaus, this has been fixed, please let me know if you still get it.
