### ISSUE TITLE
[Python] Swagger spec 2.0 with global security setting fails

### ISSUE THREAD

**Issue by ensonic** [swagger-api/swagger-codegen#7847]
##### Swagger-codegen version
2.3.1

##### Swagger declaration file content or url

I have this in my open-api-spec.json:
```json
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    }
  },
  "security": {
    "api_key": []
  }
```
and in the code I'll do this:
``` python
config = my_api.Configuration()
config.api_key['x-api-key'] = api_key
api_client = my_api.ApiClient(config)
registry_client = my_api.MyApi(api_client)
```
expected would be a header "x-api-key: 12345", but the header is not set :/ I added some logging into the generated `api_client.py` and `auth_settings` passed to `__call_api()` are `None`. In the generated `my_api.py` I see `auth_settings = []` and I think this is the cultprit.

If you look at the top-level swagger object:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object
One can attach a global security setting there.

**Comment by wing328** [comment]
@ensonic thanks for reporting the issue.

Looks we fixed the problem before: https://github.com/swagger-api/swagger-codegen/issues/1365

Have you validated your OpenAPI spec using https://editor.swagger.io or other tools?

**Comment by jasonl99** [comment]
I am having a nearly-identical problem with the ruby client.

**Comment by wing328** [comment]
We do have a test case for this: https://github.com/swagger-api/swagger-codegen/blob/c66a0aaa07695276fc3fa6a24bb42d2176d0f5cc/modules/swagger-codegen/src/test/java/io/swagger/codegen/DefaultGeneratorTest.java#L96

The global security definition in the test spec can be found in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/globalSecurity.json#L818-L847

**Comment by wing328** [comment]
Can you please share the full spec via https://gist.github.com so that we can more easily repeat the issue?

**Comment by ensonic** [comment]
Mistake on my side:
```
"security": {
    "api_key": []
  }
```
needs to be:
```
"security": [
  {
    "api_key": []
  }
]
```
and 
```
> swagger-codegen validate -i registry.json 
Validating spec file (registry.json)
attribute security is not of type `array`
...
```

**Comment by wing328** [comment]
@ensonic no problem. Glad to hear that the issue is resolved.

**Comment by wing328** [comment]
@jasonl99 if you still need help with the issue, please share the spec with us.

**Comment by jasonl99** [comment]
@wing328 My apologies for not reporting back sooner.  I went to create a minimally viable example that failed, and found that it worked just fine.  That led me to discover my original code had a careless mistake, using an underscore instead of a dash.  My header's key was `api-key` but I I had written the code as `config.api_key['api_key']` rather than `config.api_key['api-key']`.  Once I fixed it, it worked fine.   I must have looked at that line a dozen times and still didn't catch it.  Sorry for the alarm!

**Comment by wing328** [comment]
@jasonl99 no problem at all. Just let us know if you've further question or feedback.

**Comment by manuelaceron** [comment]
I'm new with codegen, I'd like some help with this:
I have a single OAuth security scheme with just one scope in my YAML, using codegen it applies the same scope tag to each operation, and I need just one global security tag to be able to generate the annotation @Scopes at class level in my Maven project

Thankss
