### ISSUE TITLE
[Suggestion] Standardise naming, exception and more

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#786]
Hi all,

I would like to propose standardising the following across all API client libraries:

- name the HTTP client as ApiClient instead of ApiInvoker, SwaggerClient, etc (For ObjC, we'll use SWGApiClient instead)
- name exception as ApiException instead of APIClientException, ErrorResponse, etc
- use a Configuration class for configuration (authentication, logging, etc)
- throw ApiException instead of returning null data for 404

This will make the API client more consistent across different languages and easier to maintain.

If you've any feedback or concern for the above, please share with us.

Thanks.

**Comment by fehguy** [comment]
This is a good idea as long as the conventions are consistent with each language vernacular.

**Comment by fehguy** [comment]
@wing328  can we close this?  I believe we've covered this need.

**Comment by wing328** [comment]
Yes, most clients are using the standardised naming, exception, etc
