### ISSUE TITLE
DateTime Nullable in C#

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#788]
Server side a DateTime2 is set Nullable, the generated code is NOT NULLABLE

public DateTime LodgementDate { get; set; }

**Comment by wing328** [comment]
For server side, are you using any tool to generate the code ?

I'll update the mapping to support nullable datetime for C#.

**Comment by uniprof** [comment]
Server side is a normal .NET web API, what do you mean for tool to generate the code?

**Comment by wing328** [comment]
Updated in #785 

I thought you've a code generator to generate the server-side code

**Comment by fehguy** [comment]
#785 has been merged.
