### ISSUE TITLE
ReadOnly in C#

### ISSUE THREAD

**Issue by lakeba** [swagger-api/swagger-codegen#789]
Even the doc appoint a property as readonly, the code generation is not considering it

DOC:
{
type: "object",
properties: {
SumDocumenti: {
format: "int32",
type: "integer",
readOnly: true
}

GENERATED CODE:

public int? SumDocumenti { get; set; }

**Comment by wing328** [comment]
Not only C#, other languages such as Java, Ruby and PHP do not take into consideration the `readOnly` attribute.

How critical is this feature to your use case ?

**Comment by uniprof** [comment]
It's enough critical as I am exposing all the datamodel to the client and would be good to have fields in readonly instead that a model for the GET and a model for the POST/PUT.

**Comment by wing328** [comment]
To understand the requirement a bit more, you want to make the attribute/property readonly to prevent the user from changing it since the model (with the readonly attribute) will be sent to the API backend (potentially using POST/PUT) ?

**Comment by webron** [comment]
@wing328 - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaReadOnly

This is basically used to more easily separate read and write models for simple use cases. If it is read only, it should not be available for the client to send to the server at all, but the client should expect to accept it when receiving from the server. Similar (but reverse) logic applies to server generation.

**Comment by wing328** [comment]
@webron yes, I've read that. 

I think this is similar to default value, which should be implemented in the server side as one cannot always expect the client to correctly omit the read-only property when sending the request to the server. (what if the request is sent by a curl command or API client in other languages instead of a C# API client?)

**Comment by webron** [comment]
This is different. Default values are informative to tell the user what value would be used in case one is not provided (which also makes it relevant only if the property is optional).

On the other hand, readOnly can lead to a logical problem at the server side and can explicitly induce an error from it. Some server implementations would ignore the additional fields (whether readOnly or something random), but some would prefer to provide an error message to the client to assert the user they may be doing something wrong.

**Comment by wing328** [comment]
Just to be clear I'm not saying this must not be done in the client side. Ideally it should be implemented in the client side but personally I don't see it as "critical"

C# supports the keyword "readonly" for properties/attributes but looking at the bigger picture I don't see other programming languages such as PHP, Ruby, Java can do something similar with just one keyword.

**Comment by webron** [comment]
Not sure how it is not critical if it will produce clients that would generate errors when trying to operate the APIs.

**Comment by uniprof** [comment]
It's critical when the datamodel is the same for the verbs PUT/POST/GET.
if you want to provide the creation date of the record into the GET, dosen't men that you want to make it editable into the PUT.

**Comment by fehguy** [comment]
i would suggest that we expose read-only in the comments rather than enforce them in accessors.  Would that suffice, @uniprof?

**Comment by uniprof** [comment]
No suffice as the client developer will be able to PUT data that is not expected to be change.

**Comment by wing328** [comment]
@uniprof at the moment would the API server throw an exception (400) or it will just update the read-only data? in other words, I would like to know more about the validation done in the server side for the read-only data.

**Comment by uniprof** [comment]
The server will throw an exception if the readOnly property is changed.

**Comment by fehguy** [comment]
OK this is something that *could* be enforced at the client side.  Most any server implementation would reject changes in read-only properties.  I'd be happy to merge a PR, so please reopen if you have any questions.

**Comment by wing328** [comment]
@lakeba FYI. We've added support for read-only property in C# model.

**Comment by lakeba** [comment]
Really appreciated !!!
