### ISSUE TITLE
[typescript-angular] Swagger-codegen optional parameters with null value are given value "null" : string

### ISSUE THREAD

**Issue by ZeroUltimax** [swagger-api/swagger-codegen#7893]
##### Description
For optional parameters on a ASP.NET Web API 2 rest controller,  the generated code is
```
public employeSearchGetByName(name?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Employe>>{
  let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
  if (name!== undefined) {
    queryParameters = queryParameters.set('name', <any>name);
  }
```

When calling ```employeSearchGetByName(null).subscribe();```

the service will generate a request to ```example.com/api/employe-search?name=null```, which will be (correctly) interpreted as the parameter [name] having the string value "name"

##### Expected behavior

The code should be generated in a way that when calling ```employeSearchGetByName(null).subscribe();```
the service generates a request to ```example.com/api/employe-search```, which will be (correctly) interpreted as the parameter [name] having the no value (null)

##### Swagger-codegen version

using Swagger codegen 2.3.1,

##### Swagger declaration file content or url

```json
{  
   "/api/employe":{  
      "get":{  
         "tags":[  
            "EmployeSearch"
         ],
         "summary":"Get employes who's name match.",
         "operationId":"EmployeSearch_GetByName",
         "consumes":[ ],
         "produces":[  
            "application/json",
            "text/json",
            "application/xml",
            "text/xml"
         ],
         "parameters":[  
            {  
               "name":"name",
               "in":"query",
               "required":false,
               "type":"string"
            }
         ],
         "responses":{  
            "200":{  
               "description":"OK",
               "schema":{  
                  "type":"array",
                  "items":{  
                     "$ref":"#/definitions/Employe"
                  }
               }
            }
         },
         "deprecated":false,
         "security":[ ]
      }
   }
}
```

##### Suggest a fix/enhancement

Instead of checking ```  if (name!== undefined) ```, 
check for  ```  if (name!== undefined&&name!== null) ```

**Comment by macjohnny** [comment]
@ZeroUltimax sounds good

**Comment by macjohnny** [comment]
@ZeroUltimax sounds good, would you like to try and implement this improvement?

**Comment by macjohnny** [comment]
@ZeroUltimax I filed PR #8033 to fix this issue
