### ISSUE TITLE
[cpprest] number type with unspecified format build fails

### ISSUE THREAD

**Issue by murzic4** [swagger-api/swagger-codegen#7906]
##### Description
Hi
Few days ago I faced issue that swagger-codegen doesn't correctly  generate cpprest code for type "number" with no format specified and type "string" format "uuid".
today I have checked with the last release (swagger-codegen-cli-2.3.1.jar) and it looks like that issue with uuid is solved, but the problem with "number" is still exist

##### Swagger-codegen version
2.3.1

##### Swagger declaration file content or url
yaml file attached to the ticket (echo.yaml.log) , the issue with the code generated for the following description:
```
 - name: some_number
          in: query
          type: number
          required: true
```
##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -l cpprest -o ./out -i ./echo.yaml`

##### Steps to reproduce
to execute command above for the yaml file [echo.yaml.log](https://github.com/swagger-api/swagger-codegen/files/1845999/echo.yaml.log)

##### Related issues/PRs
[0001-cpprest-add-parameterToString-for-number-type-with-u.patch.log](https://github.com/swagger-api/swagger-codegen/files/1845998/0001-cpprest-add-parameterToString-for-number-type-with-u.patch.log)
[echo.yaml.log](https://github.com/swagger-api/swagger-codegen/files/1845999/echo.yaml.log)

##### Suggest a fix/enhancement
please find possible patch here [0001-cpprest-add-parameterToString-for-number-type-with-u.patch.log](https://github.com/swagger-api/swagger-codegen/files/1845998/0001-cpprest-add-parameterToString-for-number-type-with-u.patch.log)

**Comment by etherealjoy** [comment]
@murzic4 
Do you wish to submit a PR for your patch?

**Comment by murzic4** [comment]
@etherealjoy
Sorry I have not enough experience in it. Could you please send me instruction how to do it?

**Comment by etherealjoy** [comment]
Ok, you need to fork this project first then make your changes 
Follow the guide here
https://gist.github.com/MarcDiethelm/7303312

**Comment by murzic4** [comment]
@etherealjoy
well.. i definitely have made something but not sure all steps were correct
