### ISSUE TITLE
Readme says java-petstore.sh targets http://petstore.swagger.io/v2/swagger.json but it actually targets a local file

### ISSUE THREAD

**Issue by RPrimrose** [swagger-api/swagger-codegen#792]
Minor thing but https://github.com/swagger-api/swagger-codegen/blob/master/README.md says under "To generate a sample client library" that https://github.com/swagger-api/swagger-codegen/blob/master/bin/java-petstore.sh runs a command targeting http://petstore.swagger.io/v2/swagger.json but the script actually targets modules/swagger-codegen/src/test/resources/2_0/petstore.json

Not sure if it's the README or the actual script that isn't as intended?

**Comment by wing328** [comment]
Agree with you that the description does not correctly describe the actual command. If you've time, I would suggest you to submit a PR to revise the wording to show what the script actually does (reading the spec from a local file)

**Comment by RPrimrose** [comment]
Sure, I'll submit a PR at the weekend
