### ISSUE TITLE
Support for 'paths'-less Swagger files?

### ISSUE THREAD

**Issue by marcelstoer** [swagger-api/swagger-codegen#7922]
Currently the `DefaultGenerator` [fails with an NPE](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L810) for Swagger files without a `paths` element. Shouldn't the generator be a bit more lenient?

True, Swagger files without a `paths` element are invalid as [it's required](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathsObject). However, if you have model definitions that are shared across several Swagger files you end up with one file that has no paths.

The `DefaultGenerator` could easily be fixed to allow that but would a PR to that effect get accepted?

**Comment by webron** [comment]
Unfortunately, no. The tool is intended to be used with valid definitions (as are the other tools in the Swagger family). Not saying the use case is not reasonable though - and we have solved that in some variance. The potential workaround for this would be to add an empty `paths` to those definitions.

**Comment by marcelstoer** [comment]
>  The potential workaround for this would be to add an empty paths to those definitions.

Yep, in CI we inject a dummy `paths` into those definitions before we feed it to the validator.
