### ISSUE TITLE
[Rust] Proposed change in use of contexts

### ISSUE THREAD

**Issue by tca-ms** [swagger-api/swagger-codegen#7925]
Currently the `Api` trait generated by `rust-server` includes in its methods a parameter of type [`swagger::context::Context`](https://docs.rs/swagger/0.10.0/swagger/context/struct.Context.html), which stores various contextual data relating to a request.

This is a proposal to make the type of the context parameter generic, with the functionality required by swagger-codegen being enforced by trait bounds on the context type parameter.

This will allow implementations of the `Api` trait to make additional requirements on the context that it is passed, without these requirements being visible to the autogenerated code. These requirements can then be fulfilled by other hyper [services](https://hyper.rs/hyper/master/hyper/server/trait.Service.html) wrapping the autogenerated server.

### Changes in the external [`swagger-rs`](https://crates.io/crates/swagger) crate

The traits used to constrain the context types of incoming requests will be defined here.

The trait `Has<T>` defines a setter and getters (mutable and immutable) for a field of type `T`. This trait will be used to specify the requirements on the context of an incoming request.

The `Context<C, T>` struct implements `Has<T>`. In addition, a `Context<C, T>` can use the getters and setters from `Has<S>` implementations on the wrapped `C`, thanks to extensions of these implementations to `Context<C, T>`. This struct can be used to build up a concrete type to be used as the context type parameter to the `Api` trait.

### Changes in `rust-server`

The autogenerated Api trait and the `Client` and `Service` structs will be modified to have a type parameter representing a context type - This will be used as the type of the context parameter to the APIs methods, and as part of the `Request` associated type of the `Service`'s `hyper::service::Service` implementation.

**Comment by bjgill** [comment]
OK - I think #8114 pulled in the implementation. Can this issue not be closed?
