### ISSUE TITLE
[aspnetcore] .csproj doesn't load in Visual Studio 2017

### ISSUE THREAD

**Issue by TomSelleck101** [swagger-api/swagger-codegen#7945]
##### Description

The generated aspnetcore project won't open in Visual Studio 2017 (tested with version 15.4.1).

##### Swagger-codegen version

Version 2.3.1 - hosted on editor.swagger.io

##### Swagger declaration file content or url

gist [here](https://gist.github.com/TomSelleck101/17c3143caef2cc9a796d82f3b59c0f31)

##### Command line used for generation

editor.swagger.io

##### Steps to reproduce

1. Paste contents of gist into http://editor.swagger.io (Not https as the content can't be downloaded over https :/ )
2. Click `Generate Server`
3. Click `aspnetcore`
4. Extract the folder from the downloaded `.zip` 
5. Open the `.sln` file to open with Visual Studio 2017
6. The project says `IO.Swagger (load failed)` in the solution explorer
7. Attempting to right click and reloading the project brings an error which says: The operation could not be completed. Unspecified error.

**Comment by jonathh21** [comment]
I too am experiencing this issue, vanilla code generated by Swagger UI won't load VS 2017 (15.6.4)

**Comment by cal5fishbowl** [comment]
Just happened to me as well. VS 2017 (15.6.5)

**Comment by cal5fishbowl** [comment]
@djmitchella That solved it for me. Thanks!

**Comment by tkieronski** [comment]
Interesting thought that you can still open the solution without any issues on Mac Visual Studio but not on Windows.

**Comment by Monte-Christo** [comment]
The project  also loads without a problem in Visual Studio Code. 
Upon removing and re-adding, two changes are made to the .sln file:

1. The project GUID is changed.
2. This added to the end of the file:
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {some GUID}
	EndGlobalSection

**Comment by eeskildsen** [comment]
The generated project path is missing backslashes. Looks like this is the case for `csharp` too.

https://i.imgur.com/xD8ln2V.png

I'm guessing this has to do with how Mustache handles backslashes?

**Comment by GreatJobBob** [comment]
Here what worked for me
I created a new blank solution in Visual Studio
I added a new .Net Core API project
Then added an existing project and selected my generated swagger project
Then made that project start up project.
Rebuild solution then ran fine

**Comment by TheBeardedLlama** [comment]
I'm having the same issue, but I can't even open the csproj on its own.

When I first try to open the project I get
![image](https://user-images.githubusercontent.com/1180470/61066548-ae6dde00-a3fd-11e9-94e7-3fdc9afe07aa.png)

If I try to reload then I get:
![image](https://user-images.githubusercontent.com/1180470/61066608-c2b1db00-a3fd-11e9-8bf0-8afac9a812db.png)

**Comment by roryvidalburgoa** [comment]
I've just removed the project from the solution and re-added it. It worked.

**Comment by HugoMario** [comment]
Hi @TheBeardedLlama @GreatJobBob @roryvidalburgoa 
i'm not familiar with net but if you let me know which changes are required to fix this i could help

**Comment by HugoMario** [comment]
fixed by [swagger-codegen#10478](https://github.com/swagger-api/swagger-codegen/pull/10478)
