### ISSUE TITLE
swagger-codegen-cli generates original jar that is **not** the original

### ISSUE THREAD

**Issue by vandmo** [swagger-api/swagger-codegen#798]
The original-swagger-codegen-cli.jar is the same as the shaded jar.
original-swagger-codegen-cli.jar should only include the classes added by project.
The original jar is useful when creating a new shaded jar based on swagger-codegen-cli.

**Comment by lugaru1234** [comment]
I compared two jars and they are different in META-INF/services/*. And as I understand it what this configuration https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen-cli/pom.xml#L65 should do.  @fehguy can you clarify this issue?

**Comment by vandmo** [comment]
What I meant was that they SHOULD be different. Much more different. When creating a shaded fatjar all dependencies are merged into that jar and it becomes very large. It is true that ServicesResourceTransformer is needed in many cases to make services from dependent jars available as java services.

The problem is when you want to build your own fatjar that uses the project that creates a fatjar. If you want another version of some dependency there will be a conflict.

Therefore it is customary to produce an original jar that can be used when you don't want or need the fatjar. This original jar is much smaller since it does not contain the classes from all dependencies.

What I noted with this issue is that the original jar is the same as the fatjar. They are both about 14 megs.
