### ISSUE TITLE
HTTP Request method type not being set correctly in Python 3 generation

### ISSUE THREAD

**Issue by gsastry** [swagger-api/swagger-codegen#80]
In swagger.mustache, the "MethodRequest"'s method get_method wasn't properly being called. I removed this method and it uses urllib's default get_method's and chooses a POST request when the 'data' parameter is set. It works after doing this, but there may be a better solution. Probably the Pyton 2 -> 3 refactor of urllib/urllib2 caused this.

**Comment by fehguy** [comment]
this is quite old, but should be addressed in https://github.com/swagger-api/swagger-codegen/commit/db5259b9130450e01cf365a1899ab9f8adbccbd7

Please reopen if you still have issues.
