### ISSUE TITLE
ObjectiveC generation

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#800]
generation ObjectiveC code return this error

can't open objc\SWGObject.h for input
can't open objc\SWGObject.m for input
can't open objc\SWGQueryParamCollection.h for input
can't open objc\SWGQueryParamCollection.m for input
can't open objc\SWGApiClient.h for input
can't open objc\SWGApiClient.m for input
can't open objc\SWGFile.h for input
can't open objc\SWGFile.m for input
can't open objc\JSONValueTransformer+ISO8601.m for input
can't open objc\JSONValueTransformer+ISO8601.h for input

**Comment by wing328** [comment]
Are you using `developer_2.0`? I did a test with `mvn clean && ./bin/objc-petstore.sh` and it works for me.

**Comment by uniprof** [comment]
Have you tested it on Windows? on Mac it work fine, on Windows not.

**Comment by wing328** [comment]
I've not

**Comment by wing328** [comment]
I submitted a PR to fix the issue #803 

Please kindly perform a test (in Windows) to see if it fixes the issue.

**Comment by fehguy** [comment]
This should be fixed now.
