### ISSUE TITLE
Custom generators can't read vendor specifics from swagger spec.

### ISSUE THREAD

**Issue by vandmo** [swagger-api/swagger-codegen#802]
Swagger supports x-* properties in various places. To write a generator that makes use of that they need to access the swagger spec **before** the files are generated.

I suggest adding: config.postProcessSwagger(swagger); in the generate() method in DefaultGenerator.

**Comment by fehguy** [comment]
I believe the intended design for supporting extensions inside codegen is to use the model factory in [CodegenModelFactory.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/CodegenModelFactory.java) so you can read extensions and do what you wish with them.  That's more powerful (imho) than reading a java object, which is usually unusable in the mustache templates.  Can you please look there to see if that fulfills your usecase?

**Comment by vandmo** [comment]
Thanks for the reply!
Unfortunately it won't help me.

My use case is that I want to write a bunch of custom generators that I want to invoke using swagger-codegen-cli. My entry point is that I can provide a class name using the -l command line parameter.
The class I provide must implement the com.wordnik.swagger.codegen.CodegenConfig interface.

The interface already has a method ''void processSwagger(Swagger swagger)'' which gets called **after** everything else has run and then it is too late to use the information from the swagger object.

I could solve it by writing my own CLI artifact and my own implementation of DefaultGenerator but I would prefer to avoid that. Especially since it would only require adding about 3 lines of code in the swagger-codegen project. It would also be consistent with how DefaultGenerator works. There are already a bunch of postProcess**(...) methods that gets called att various places.

Thanks again :)

**Comment by wing328** [comment]
@vandmo do you mind sharing with us a bit more about those custom generators? Are those API clients or servers generated based on Swagger Spec ?

**Comment by vandmo** [comment]
I am writing one generator for markdown, one for generating client and one generating a server using Spring's RestController etc. It is the server part where I can't use information from the swagger yaml file.

**Comment by wing328** [comment]
@vandmo Thanks for sharing your requirement with us.

**Comment by vandmo** [comment]
Thanks for asking for it! :)

**Comment by fehguy** [comment]
You can now read vendor extensions from the POJOs, and create your own Codegen* models for storing any values in them, which are available at template execution.  Please give that a shot, and reopen if still having an issue.

**Comment by vandmo** [comment]
I'm still not able to extract the information.
There is a method, io.swagger.models.Info#getVendorExtensions() which I can't find any references to.

io.swagger.models.Response does not contain any method that allows you to access vendor extenstions at all.

**Comment by vandmo** [comment]
I can't reopen this issue unfortunately.
