### ISSUE TITLE
[Java] [Android] Auto-Value and Nullability Annotations

### ISSUE THREAD

**Issue by benwicks** [swagger-api/swagger-codegen#8038]
##### Suggestion / Question

@emilianobonassi @xhh @jaz-ah @jimschubert

I think you're the relevant contributors to ask. My team is considering using swagger-codegen for an Android project. We are trying to decide whether to generate Kotlin or Java. Our Android app will be written in Kotlin and we need the generated models to include nullability features. If we generate Kotlin, it looks like we'd get proper `?`-marked fields for required fields out of the box. However, we're interested in also generating Retrofit-2 networking code with RxKotlin which appears to not yet be supported by swagger-codegen.

For that reason (and because we really don't *need* the generated code to be Kotlin), we're also considering generating Java. If we go that route, is there documentation around generating AutoValue Java classes *and* generating `@Nullable`/`@NotNull` annotations on required fields? Do you know of any work currently being done on those issues? If not, my team should be able to experiment and possibly contribute - can you explain how we should proceed? Thank you!

**Comment by kassim** [comment]
I've found there isn't any `@Nullable` annotations, however there is `@ApiModelProperty` annotation with (or without) a `required` field.

I think we could use the existing logic in the codegen that sets this to set `@Nullable` or `@NonNull` to the field.

**Comment by benwicks** [comment]
Thanks for the feedback. Kotlin codegen is working for my team's needs now.
