### ISSUE TITLE
[Go][Client] Wrong body format for POST form-urlencoded requests

### ISSUE THREAD

**Issue by rubens21** [swagger-api/swagger-codegen#8062]
##### Description
The body's format of POST requests using content-type `application/x-www-form-urlencoded` is coming in "multipart/form-data" format.

##### Swagger-codegen version
2.3.0 (swagger-codegen-cli-2.3.0.jar)

Same behavour happens in the API client tests in master branch.

##### Swagger declaration file content or url
Swagger Petstore (http://petstore.swagger.io)

##### Command line used for generation
Irrelevant. 
Same behaviour happens in the API client tests in master branch.

##### Steps to reproduce
0. Edit a server method that response for a POST/form-urlencoded request (e.g. method UpdatePetWithForm, https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/go-api-server/go/api_pet.go#L47) 
0. Print out the headers content-type and the request body gotten by that method
![image](https://user-images.githubusercontent.com/447656/39136665-c2d3f13a-46e9-11e8-97c9-a8793b72aa69.png)
0. Call a api client method that post a request to that route (send some parameter to make easier to see the error) (e.g. run the the samples/client/petstore/go/pet_api_test.go, but if you do that, remember of changing the base URL to you host at https://github.com/rubens21/swagger-codegen/blob/master/samples/client/petstore/go/go-petstore/configuration.go#L64)
0. Read the server output.

A url-encoded body is expected, but we get something like this:
![image](https://user-images.githubusercontent.com/447656/39137018-9a302b62-46ea-11e8-9a9f-643cdd9d066e.png)

##### Related issues/PRs
#7668 mentions something like that, but I was not able to reproduce as it is described there.

However, I also found a but on "multipart/form-data" POST format. The boundary is not been included in the headers IF there is no file being uploaded.

Although it seems to be a very critical bug, I surpreslly didn't find more users complaining about that, neither more issues in the repo. So, I've checked many times to ensure I am not missing something. If I am, sorry for the long description.

##### Suggest a fix/enhancement
0. The tests are only checking the http status code, which one will always be 200 since the server also does not too much than only returning it. That's why this bug is not caught by tests.
0. The default server generated could echo all request exactly as it has gotten the request. Then the client could test the request properlly.

**Comment by HugoMario** [comment]
covered by #8767
