### ISSUE TITLE
support for inheritance in code generation

### ISSUE THREAD

**Issue by ialmetwally** [swagger-api/swagger-codegen#810]
Is there any way to support inheritance in code generation? like specifying the parent/base model in the JSON schema? 

The only resource I found about this issue was this discussions https://gist.github.com/leedm777/5730877 and it doesn't seem to be implemented yet!

I need to generate the following Java models from the below JSON schema

```
public class Bar {
  String a;
  String b;
}

public calls Foo extends Bar {
  String c;
  String d;
  String e;
}
```

```
{
  "Bar": {
    "properties": {
      "a": {
        "type": "string"
      },
      "b": {
        "type": "string"
      }
    }
  },
  "Foo": {
    "properties": {
      "c": {
        "type": "string"
      },
      "d": {
        "type": "string"
      },
      "e": {
        "type": "string"
      }
    },
    "parent": "Bar"
  }
}

```

**Comment by webron** [comment]
If you look at the examples under the [Schema Object](http://swagger.io/specification/#schemaObject) you'll see how inheritance and composition is defined. 

The support for it is not yet included, but please follow #358 for integration.
