### ISSUE TITLE
AddFile to the Rest Call

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#811]
Can we have the upload/download function to a rest call or at least upload/download of a stream?

**Comment by wing328** [comment]
It's not supported at the moment. Please have a look at https://github.com/swagger-api/swagger-codegen/issues/733

**Comment by uniprof** [comment]
I think that just exposing the HttpClient (RestClient in case of C#) will be enough as this class support the add file and the Download.

**Comment by wing328** [comment]
You may want to refer to the PR #808 about making API Client pluggable as the change will allow the RestClient (in ApiClient class) to be configurable

**Comment by uniprof** [comment]
you are brilliant !! I hope only that your changes will be merged soon in the main project!

**Comment by wing328** [comment]
FYI. Some other clients (e.g. PHP) have gone through similar change already, e.g. #778

**Comment by uniprof** [comment]
why you don't do the changes in your fork ? android, ios and csharp would cover the most important!

**Comment by wing328** [comment]
@uniprof #808 has been merged. Did you have a chance to test ? Can this be closed ?

**Comment by uniprof** [comment]
Work perfectly!
