### ISSUE TITLE
[C#] ApiException to be more generic (response.content to be embedded as property)

### ISSUE THREAD

**Issue by Hadou1** [swagger-api/swagger-codegen#813]
In order to support a more generic implemention for the sdk developers the response.content should be embedded in the API-Exception as dynamic object. 

Hence API developers aims to return proper HTTP Status Codes, by normal the more generic and typyfised application error is often embedded in the body as JSON-Object. In order to be able to react on these Exceptions, one would need the ability to query this object and its properties.

**Comment by wing328** [comment]
I agree with you that the application error is usually embedded in the body (JSON). Currently, PHP API client would serialise the JSON body as a string and include it in the exception message.

Your suggestion to store the JSON body in a property of the Exception object (e.g. `ResponseContent`) is definitely a good one.

I would also suggest adding another property `ResponseHeader` as the response header may be useful in explaining the error (e.g. rate limiting)

**Comment by webron** [comment]
Fixed in develop_2.0.
