### ISSUE TITLE
[PYTHON] Generated Client doesn't send basic access authentication informations

### ISSUE THREAD

**Issue by PowerOfCreation** [swagger-api/swagger-codegen#8147]
##### Description

I have generated a Flask Server and a Python Client using Swagger. I copied the example python code from the README.md as found in the generated Client and inserted a random username and password just to test whether the clients actually sends the data to the server. Then I opened wireshark and ran the python script. In wireshark I can see that only an ":" has been sent as authentication and the username and password are missing.

##### Swagger-codegen version

Swagger Editor 3.3.1 and the Swagger Online Editor(not sure which Version that is)

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  description: >-
    This is a server to solve complex mathematical problems. Like calculating
    a+b=x.
  version: 1.0.0
  title: Complex Algorithm Solver
  termsOfService: 'http://example.com'
  contact:
    email: 404@example.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /math
tags:
  - name: addition
    description: Add 2 numbers and get the result.
schemes:
  - http
security:
  - basicAuth: []
paths:
  /operations:
    get:
      tags:
        - addition
      summary: Addition
      description: Adds 2 numbers.
      operationId: add_two_numbers
      consumes:
        - text/plain
      produces:
        - text/plain
      parameters:
        - name: a
          in: query
          description: First Value
          required: true
          type: number
        - name: b
          in: query
          description: Second Value
          required: true
          type: number
      responses:
        '200':
          description: Ok
          schema:
            type: number
        '400':
          description: Only numbers can be added
      x-swagger-router-controller: swagger_server.controllers.addition_controller
securityDefinitions:
  basicAuth:
    type: basic
definitions: {}
```
##### Command line used for generation

I have used the Swagger Editor to generate the client. Swagger Editor -> Generate Client -> python

##### Steps to reproduce

Open the .yaml in Swagger Editor and generate a python client. Then create a server and run it. Copy the example code from the python client as found in the README.md and try to execute it. Now check with Wireshark if the username and password have been sent as well.

##### Suggest a fix/enhancement

I'm not sure if I'm doing something wrong or if Swagger has an issue with basicAuth or if the example python script in the README.me is wrong.

The python script that is generated in the README.md and I'm talking about is this one: 
```python
from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# Configure HTTP basic authorization: basicAuth
swagger_client.configuration.username = 'YOUR_USERNAME'
swagger_client.configuration.password = 'YOUR_PASSWORD'
# create an instance of the API class
api_instance = swagger_client.AdditionApi()
a = 8.14 # float | First Value
b = 8.14 # float | Second Value

try:
    # Addition
    api_response = api_instance.add_two_numbers(a, b)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AdditionApi->add_two_numbers: %s\n" % e)

```

**Comment by Cloudmersive** [comment]
We have seen this as well

**Comment by PowerOfCreation** [comment]
I have figured out the problem. The README.md is simply wrong. After searching which file is generating the wrong README.md I did found out that the bug already got fixed 11 days ago. #7269

Here is some working example code in order to use basicAuth:
`from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# create an instance of the API class
api_instance = swagger_client.AdditionApi()
api_instance.api_client.configuration.username = "YOUR_USERNAME"
api_instance.api_client.configuration.password = "YOUR_PASSWORD"

a = 8.14 # float | First Value
b = 8.14 # float | Second Value

try:
    # Addition
    api_response = api_instance.add_two_numbers(a, b)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AdditionApi->add_two_numbers: %s\n" % e)`
