### ISSUE TITLE
Create codegen template from Maven command

### ISSUE THREAD

**Issue by alblue** [swagger-api/swagger-codegen#818]
All of the examples in the wiki page require the code to be built first, then executed. Why not publish them as a canonical build into Maven central and then use that instead?

Someone already has published these into Maven central, but under different groupids:

http://search.maven.org/#search%7Cga%7C1%7Cswagger-codegen

What I'd like to be able to do is run something like:

`mvn io.swagger:swagger-codegen:2.1.0:generate-java -Dpackage=com.example -Droot=/blah ...`

**Comment by webron** [comment]
Umm, those *are* our builds in central... and that *is* the groupid we currently use :) We haven't moved toe projects to io.swagger yet, though that would happen soon.

**Comment by fehguy** [comment]
We actually do publish an executable jar:

https://oss.sonatype.org/content/repositories/snapshots/com/wordnik/swagger-codegen-cli/
