### ISSUE TITLE
[JAVA] Port  #6852 to 3.0.0 : need to expose getters / setters for readTimeout and writeTimeout values on the generated java clients

### ISSUE THREAD

**Issue by jmzc** [swagger-api/swagger-codegen#8193]
##### Description

The issue #6852 ( fixed on 2.3.0 branch)  should be ported to 3.0.0 branch .
Last nightly build ( currently swagger-codegen-cli-3.0.0-20180515.103456-67.jar ) doesn't include this feature

##### Swagger-codegen version

3.0.0

**Comment by HugoMario** [comment]
thanks @jmzc 
we'll address this.

**Comment by HugoMario** [comment]
@jmzc i merged PR's to solve this issue, i'm going to close it but please let me know if you still get it.
