### ISSUE TITLE
[RUBY] Swagger Codegen version: unset

### ISSUE THREAD

**Issue by brianeroth** [swagger-api/swagger-codegen#8230]
##### Description

I'm generating a Swagger client for a Ruby app, but the `Swagger Codegen version` is `unset` in the resulting `.rb` files from the command. Previous versions of swagger-codegen included the version correctly. 

This is a problem for me because it seems that the client is not being generated correctly, and causing exceptions in my Ruby app when I attempt to use methods from this client.

##### Swagger-codegen version

2.3.1

##### Command line used for generation
```
LOCATION="api-docs.json"
LANG="ruby"
CONFIG="client_config.json"
WORKING_DIR="temp_client"

swagger-codegen generate --input-spec $(LOCATION) --lang $(LANG) --config $(CONFIG) --output $(WORKING_DIR)
```

##### Suggest a fix/enhancement

Find out why the version is `unset`, and fix the problem.

**Comment by medvedzver** [comment]
@brianeroth got the same problem. The issue was my java version. Make sure you have java 1.7 or 1.8. This is what I have now.
```
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

**Comment by brianeroth** [comment]
@medvedzver That was it! Installed java 1.8 and it works now. Thanks!
