### ISSUE TITLE
Create codegen template from Maven command

### ISSUE THREAD

**Issue by alblue** [swagger-api/swagger-codegen#824]
I want to be able to run a command from a maven plugin (i.e. not as a standalone executable jar)

$ mvn io.swagger:swagger-codegen:2.1.0:generate-java -Dpackage=com.example -Droot=/blah

Issue #818 was closed incorrectly since the maven command does not exist.

**Comment by fehguy** [comment]
The maven plugin has been added to the project, please see https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin
