### ISSUE TITLE
Key "packageName" not work for Kotlin language

### ISSUE THREAD

**Issue by freakdragon** [swagger-api/swagger-codegen#8243]
Key "packageName" not work for Kotlin language
I used 2.3.1 codegen
Command is:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l kotlin --packageName="ru.test" -o Simple/modules/api`
Error is:

> Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [--packageName=ru.test]
> 	at io.airlift.airline.Cli.validate(Cli.java:148)
> 	at io.airlift.airline.Cli.parse(Cli.java:116)
> 	at io.airlift.airline.Cli.parse(Cli.java:97)
> 	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

Tried:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l kotlin -packageName="ru.test" -o Simple/modules/api`
Tried:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l kotlin --package-name="ru.test" -o Simple/modules/api`
Tried:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l kotlin -package-name="ru.test" -o Simple/modules/api`
When I remove the packageName key, all work.

Config options for kotlin:

java -jar swagger-codegen-cli-2.3.1.jar config-help -l kotlin

> CONFIG OPTIONS
> 	sourceFolder
> 	    source folder for generated code (Default: src/main/kotlin)
> 
> 	packageName
> 	    Client package name (e.g. io.swagger). (Default: io.swagger.client)
> 
> 	groupId
> 	    Client package's organization (i.e. maven groupId). (Default: io.swagger)
> 
> 	artifactId
> 	    Client artifact id (name of generated jar). (Default: kotlin-client)
> 
> 	artifactVersion
> 	    Client package version. (Default: 1.0.0)
> 
> 	enumPropertyNaming
> 	    Naming convention for enum properties: 'camelCase', 'PascalCase', 'snake_case', 'UPPERCASE', and 'original' (Default: camelCase)
>

**Comment by skrysmanski** [comment]
Just in case you're still looking for an answer: you need to write `-DpackageName=ru.test` (at least in Swagger v2)
