### ISSUE TITLE
Code generation for kotlin language with library "retrofit2" not works

### ISSUE THREAD

**Issue by freakdragon** [swagger-api/swagger-codegen#8244]
Code generation for kotlin language with library "retrofit2" not works
Codegen version is 2.3.1
Code generation for kotlin language with library "retrofit2" not works:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l kotlin --library=retrofit2 --api-package="test.swagger.api" --model-package="test.swagger.model" -o project
`
Error is:

> Exception in thread "main" java.lang.RuntimeException: Unknown library: retrofit2
> Available libraries:
>   NONE
> 	at io.swagger.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:3375)
> 	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:421)
> 	at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
> 	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

Code generation for java language with library "retrofit2" works:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l java --library=retrofit2 --api-package="test.swagger.api" --model-package="test.swagger.model" -o project`

Code generation for kotlin language without library "retrofit2" works:
`java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.yml -l kotlin --api-package="test.swagger.api" --model-package="test.swagger.model" -o project`

Does kotlin supports retrofit or retrofit2 library?

**Comment by tsuharesu** [comment]
No, kotlin doesn't have any library. You can check config using:

```
$ swagger-codegen config-help -l kotlin

CONFIG OPTIONS
	sourceFolder
	    source folder for generated code (Default: src/main/kotlin)

	packageName
	    Client package name (e.g. io.swagger). (Default: io.swagger.client)

	groupId
	    Client package's organization (i.e. maven groupId). (Default: io.swagger)

	artifactId
	    Client artifact id (name of generated jar). (Default: kotlin-client)

	artifactVersion
	    Client package version. (Default: 1.0.0)

	enumPropertyNaming
	    Naming convention for enum properties: 'camelCase', 'PascalCase', 'snake_case', 'UPPERCASE', and 'original' (Default: camelCase)
```
