### ISSUE TITLE
DefaultGenerator does not pass top level Consumes and Produces to configurations

### ISSUE THREAD

**Issue by Xanadros** [swagger-api/swagger-codegen#827]
The swagger spec seems to support having consumes and produces fields at the top level of an api file (global to all APIs defined), but the DefaultGenerator never passes these fields to the configuration being used.

**Comment by wing328** [comment]
@Xanadros I've implemented the support for top level `consumes` and `produces` in my repo (wing328: branch `global_consume`). If you've time, please help perform a test.

**Comment by wing328** [comment]
@Xanadros PR merged. Please pull the latest master and let us know if you still see issue with top-level consumes or produces.

**Comment by Xanadros** [comment]
Sorry about not being able to test the PR. Our project has moved to higher priorities, but I'll be sure to try it out now that it was merged. Thanks!

**Comment by wing328** [comment]
@Xanadros the change has been reverted as we're pending an enhancement PR for swagger-parser: https://github.com/swagger-api/swagger-parser/pull/115. I'll let you know once the PR has been merged into master again.

**Comment by wing328** [comment]
@Xanadros the swagger-parser PR has been merged and we've made the change to support top-level consumes and produces in swagger-codegen.

**Comment by Xanadros** [comment]
@wing328 awesome, glad to hear it!
