### ISSUE TITLE
New Community Fork: openapi-generator

### ISSUE THREAD

**Issue by macjohnny** [swagger-api/swagger-codegen#8278]
##### Description

There is a new community fork of swagger codegen available at [https://github.com/OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator)

The openapi-generator was forked from swagger codegen between version 2.3.1 and 2.4.0-SNAPSHOT and supports OpenAPI 2.0 and 3.0 with all generators currently available in swagger codegen 2.x
It might be useful to add a note in the Readme.

**Comment by webron** [comment]
Without going into the politics behind it, I don't think it's appropriate for us to promote a competing project, especially one that simply copied this project's code. I'm afraid I cannot accept the related PR as well.

**Comment by macjohnny** [comment]
@webron I still think both projects could benefit from each other. Having a common codebase is a great part of the open source philosophy and allows to adapt products for different needs. Even more it allows to let people follow different directions. And it also allows to figure out a common path again. How about allowing this here?
Since these projects are non-profit, it is safe to say that it is all about seeking for the best technical solution, not the most profitable one. 
I would kindly ask you to reconsider co-existence instead of competition.

**Comment by webron** [comment]
I completely agree with you, however when such an act is done completely one-sided, it doesn't exactly spell out collaboration (and there are a few added things that I won't get into here). 

I'm happy to have a real discussion, but unfortunately so far my attempts in doing that have failed.

**Comment by MartinDelille** [comment]
The reason of the fork is that many people think that there was a problem in the way the transition toward the new 3.0.0 specification which would have lead to many side effect and bad experience for the users.

`openapi-generator` address the specification compliance without breaking change in the usage.
