### ISSUE TITLE
jaxrs templates are failing

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#830]
https://github.com/swagger-api/swagger-codegen/commit/1f360961e0bff365b3c0ad3f19a8e9f9c8829c5e broke the jaxrs templates because of the `processOpts` directive.

**Comment by olensmar** [comment]
@fehguy I'll have a look

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-codegen/commit/ddbef8b25daaf5db6d43a6b3ba95372fd22ba415

**Comment by fehguy** [comment]
@olensmar just got it fixed.

**Comment by olensmar** [comment]
wow - nice one :-)
