### ISSUE TITLE
update jaxrs generator to jersey2

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#832]
@olensmar any reason not to update the jaxrs to jersery2?

**Comment by olensmar** [comment]
not unless we want to make sure that the generated code works under jersey 1 as well ?

**Comment by jeff9finger** [comment]
I really need the jersey 2/jaxrs 2.0 as well.

**Comment by vnalla** [comment]
I need JAX-RS 2.0 support for both server and client and it will better if the library is configurable option for server side.
