### ISSUE TITLE
 [GO and Scala] Dockerfiles are not generated

### ISSUE THREAD

**Issue by SyCode7** [swagger-api/swagger-codegen#8320]
[GO and Scala] Dockerfiles are not generated.

##### Swagger-codegen version

`latest`
##### Swagger declaration file content or url
url - `http://localhost:46712/v2/api-docs.json`

##### Command line used for generation

`java -jar /home/test/git/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate    -i http://localhost:46712/v2/api-docs.json    -l go-server -o /home/test/git/risk-assess/spring_petclinic_customers_go`

**Comment by beardeddragon5** [comment]
Is this a requirement of swagger-codegen?

**Comment by SyCode7** [comment]
requirement ?
