### ISSUE TITLE
[Python] "async" is now a reserved keyword in Python 3.7

### ISSUE THREAD

**Issue by xlz-jgoutin** [swagger-api/swagger-codegen#8328]
##### Description
"async" is now a reserved keyword in Python 3.7.

"async" is used as variable and argument name multiple time in swagger-codegen Python client.

This make the client non working on Python 3.7 (Raises SyntaxError).

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

https://github.com/Accelize/apyfal/blob/master/rest_api/input_spec.json

##### Command line used for generation

java -jar swagger-codegen-cli-2.3.1.jar generate -i input_spec.json -o output -l python"

##### Steps to reproduce

Import generated client in Python 3.7.

##### Related issues/PRs

None found.

##### Suggest a fix/enhancement

Replace "async" variable/argument name use by anything else.

**Comment by austindrenski** [comment]
@ehlertjd Was this closed via #1345?

**Comment by ehlertjd** [comment]
@austindrenski Nope! I'm using a copy of the swagger templates and updated them in my copy. I just referenced this issue for posterity.

**Comment by yapily-gkatzioura** [comment]
A workaround for those with this issue using sed
`
find pathwithgeneratedcode/ -type f -exec sed -i 's/async=params.get/asyncRequest=params.get/g' {} +
find pathwithgeneratedcode/ -type f -exec sed -i 's/async=None/asyncRequest=None/g' {} +
find pathwithgeneratedcode/ -type f -exec sed -i 's/if not async/if not asyncRequest/g' {} +
`

**Comment by gkatzioura** [comment]
A workaround for those with this issue using sed find path/ -type f -exec sed -i 's/async=params.get/asyncRequest=params.get/g' {} + find path/ -type f -exec sed -i 's/async=None/asyncRequest=None/g' {} + find path/ -type f -exec sed -i 's/if not async/if not asyncRequest/g' {} +

**Comment by xavierhardy** [comment]
You should use snake_case (PEP8: https://www.python.org/dev/peps/pep-0008/#function-and-variable-names). I'd rather use `async_` or `is_async`, but that does not really matter.

There already is a pull request on that topic: #8401
