### ISSUE TITLE
Wrong package in the project

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#833]
Why Generator.java is under the package com.wordnik.swagger.generator.online but in the file is declared:

package com.wordnik.swagger.online;

I can't understand it

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-generator/src/main/java/com/wordnik/swagger/generator/online/Generator.java#L1

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/Generator.java#L1

So...

**Comment by uniprof** [comment]
If you try to compile now using MVN clean package, then won't work.

**Comment by webron** [comment]
Just ran it on both master and develop_2.0, no problem.

**Comment by uniprof** [comment]
So you have no issue opening the project from Eclipse ?

![screen shot 2015-06-06 at 10 45 26 am](https://cloud.githubusercontent.com/assets/1730650/8017448/4a1353dc-0c39-11e5-90d2-ec0c78bbc60c.png)
![screen shot 2015-06-06 at 10 45 47 am](https://cloud.githubusercontent.com/assets/1730650/8017449/4a1a15dc-0c39-11e5-8f0d-2dd60c592f21.png)

**Comment by webron** [comment]
I don't use eclipse. Maven from command line works just fine.

**Comment by uniprof** [comment]
How do you edit the code then ? textEditor?

**Comment by webron** [comment]
Sublime and IDEA, but that's not relevant. If the code compiles fine from command line, it is fine.

**Comment by xhh** [comment]
I think it's a typo, will submit a PR for it.

**Comment by webron** [comment]
My deepest apologies, it's been a really long day. Thank you for noticing and reporting, thanks @xhh for providing a quick fix.

**Comment by webron** [comment]
Fixed in develop_2.0, and again, sorry for the confusion.
