### ISSUE TITLE
[JAVA] [SPRING] Spring-MVC CamelCase or underscore - not both.  3.0 codegen

### ISSUE THREAD

**Issue by n24005** [swagger-api/swagger-codegen#8330]
##### Description

It seems that the object name is correctly camelCased for JAVA/Spring, but that the usage in $ref leaves it with the underscores.  I read many other notes that suggested that I could force it to always use underscore, but I would hope that they would be consistent out of the box.

##### Swagger-codegen version

swagger-codegen-cli-3.0.0-20180616.031247-80.jar

##### Swagger declaration file content or url

openapi: '3.0.0'
info:
  title: Foo API
  version: 'v1'
components:
  schemas:
    error_general:
      type: object
      description: A general error has been encountered.
      required:
      - error_code
      - error_message
      properties:
        error_code:
          type: integer
          description: The code that describes the error.
        error_message:
          type: string
    error_validation:
      allOf:
      - $ref: '#/components/schemas/error_general'
      description: An input validation error has been encountered.
      required:
        - errors
      properties:
        errors:
          type: integer
paths:
  /foo:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/error_general'
        required: true
      responses:
        400:
          description: Invalid ID supplied
          content: {}

##### Command line used for generation

java -jar swagger-codegen-cli-3.0.0-20180616.031247-80.jar generate -l java -i test.yaml -Dmodels -l java 

or 

$ java -jar swagger-codegen-cli-3.0.0-20180616.031247-80.jar generate -l java -i test.yaml -Dmodels -l spring --library spring-mvc 

##### Steps to reproduce

Examine generated classes....

The classes ErrorGeneral.java and ErrorValidation.java are created, but ErrorValidation extends Error_general instead of ErrorGeneral.

`package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Error_general;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;
/**
 * ErrorValidation
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.SpringCodegen", date = "2018-06-18T15:32:23.350-06:00[America/Denver]")

public class ErrorValidation extends Error_general  {

  @JsonProperty("errors")
   private Integer errors = null;
  

  
  
  public ErrorValidation errors(Integer errors) {
    this.errors = errors;
    return this;
  }
  
  

  /**
  
  
   * Get errors
  
  
  
   * @return errors
  **/
 
  @ApiModelProperty(required = true, value = "")

  @NotNull

  public Integer getErrors() {
    return errors;
  }

  public void setErrors(Integer errors) {
    this.errors = errors;
  }

  

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorValidation errorValidation = (ErrorValidation) o;
    return Objects.equals(this.errors, errorValidation.errors) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorValidation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

`

**Comment by n24005** [comment]
Anyone have any thoughts?

**Comment by n24005** [comment]
I'm new to this project..  I think I have a fix for this issue, but I can't get it to build correctly in my local environment.  If someone would like to make this change, it would be great, or if you want to help me get my system working, that would be appreciated too..

What I think is the bug is in DefaultCodegen line 1190.  It should convert the parent name using the toModelName(parentName) rather than simply StringUtils.capitalize(modelNamePrefix + parentName + modelNameSuffix);

**Comment by n24005** [comment]
OK - so the change really should go into swagger-codegen-generators DefaultCodeGenConfig.java line 1296.

**Comment by HugoMario** [comment]
This has been fixed by [swagger-codegen-generators PR 108](https://github.com/swagger-api/swagger-codegen-generators/pull/108). So going to close it.
