### ISSUE TITLE
[csharp-dotnet2] generate .csproj for csharp-dotnet2 client code generation

### ISSUE THREAD

**Issue by jbarbeira** [swagger-api/swagger-codegen#8334]
##### Description

The generated client code for csharp-dotnet2 should include a .csproj file.
This would allow to use dotnet commands to build and push the client to a nuget server.
With the current setup I'm able to compile the code using mono, but then it is not possible to generate a nuget package without interaction with the nuspec file.

##### Swagger-codegen version

2.3.1

##### Command line used for generation

Using the maven plugin

        <profile>
            <id>dotnetclient</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.swagger</groupId>
                        <artifactId>swagger-codegen-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <inputSpec>${project.basedir}/generated/swagger.json</inputSpec>
                                    <language>csharp-dotnet2</language>
                                    <output>${project.build.directory}/generated-sources/swagger/dotnetclient</output>

                                    <configOptions>
                                        <packageName>${project.groupId}</packageName>
                                        <packageVersion>${project.version}</packageVersion>
                                        <clientPackage>${project.groupId}.dotnetclient</clientPackage>
                                    </configOptions>

                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>

        </profile>

**Comment by HugoMario** [comment]
i added an option to use this feature, can be checked at #10361
