### ISSUE TITLE
[typescript-angular] QueryParameter with a Default Value/single value enum is not handled in the generated Typescript method

### ISSUE THREAD

**Issue by kunal-pmj** [swagger-api/swagger-codegen#8339]
##### Description

Constant Values for the QueryParameter are not taken into account while generating the TypeScript Code

##### Swagger-codegen version

Swagger Code Gen Cli 2.3.1

##### Swagger declaration file content or url

https://gist.github.com/kunal-pmj/2ac190b160382093893c036dfc313c30

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i test.json -l typescript-angular -o test-api 

##### Steps to reproduce
Pretty Strainght Forward
Use the Swagger JSON file to generate typescript-angular SDK. The productdetails.service.ts 
file does not handle the Query parameters's Constant Value 

##### Suggest a fix/enhancement
Handle the Constant QueryParameter Value in the generate ts library. The only value that can be set to this parameter is the one defined in the enum

**Comment by kunal-pmj** [comment]
Since, there are no updates on this Issue.
I have made a fix by modifying

1. CodegenParameter.java and
2. api.service.mustache

Thanks

**Comment by HugoMario** [comment]
Hey again @kunal-pmj, this  LGTM, i would just recommend to edit the [petstore sample](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml) adding this case, only if it's not present. and based on this update the `typescript-angular` samples. wdyt? i could give you a hand if you need help.

**Comment by kunal-pmj** [comment]
Let me add the tests. I will contact you if I need any help.

thanks
Kunal

**Comment by kunal-pmj** [comment]
Closing the Issue
