### ISSUE TITLE
How to install swagger-codegen from sources on mac

### ISSUE THREAD

**Issue by atrbx5** [swagger-api/swagger-codegen#8344]
##### Description

I have tried to download swagger-codegen-3.0.0-rc1 and follow instruction to install it

```
mvn clean package

[INFO] swagger-codegen-project 3.0.0-rc1 .................. SUCCESS [  1.466 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [ 16.677 s]
[INFO] swagger-codegen (executable) ....................... SUCCESS [  6.005 s]
[INFO] swagger-codegen (maven-plugin) ..................... SUCCESS [  4.172 s]
[INFO] swagger-generator 3.0.0-rc1 ........................ SUCCESS [  4.176 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

but when I try

`swagger-codegen`

I get 

command not found

Is there is other commands required to make it available in the system?

##### Swagger-codegen version

swagger-codegen-3.0.0-rc1

**Comment by macjohnny** [comment]
try running 
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
```

**Comment by atrbx5** [comment]
ok, it helps, is there is a way I can make it available under short name "swagger-codegen"?

**Comment by macjohnny** [comment]
you could create a `swagger-codegen.sh` file with the following content:
```bash
#!/bin/bash
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
```
and link it in your `/usr/local/bin` folder:
```
chmod u+x /path/to/swagger-codegen.sh
ln -s /path/to/swagger-codegen.sh /usr/local/bin/swagger-codegen
```
please close this issue, as it is rather a question that could be posted e.g. on stackoverflow
