### ISSUE TITLE
Steps to compile for iOS

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#836]
Once generated the objC files, what are the steps to compile it?

**Comment by wing328** [comment]
@uniprof You can use https://cocoapods.org/ to install the ObjC SDK. Is that what you're looking for ?

**Comment by uniprof** [comment]
All working fine here. thank you.

**Comment by wing328** [comment]
@uniprof glad to hear. Do you mind closing the task ?
