### ISSUE TITLE
[docker] build fails on 3.0.0-rc1

### ISSUE THREAD

**Issue by fenollp** [swagger-api/swagger-codegen#8368]
##### Description

`docker build` fails while processing the POMs.

I want to try generating SDKs for an OpenAPIv3 spec yet the 2 months old (latest) image `swaggerapi/swagger-codegen-cli` does not like v3. So I'm trying to build my own image.

##### Swagger-codegen version

Tag 3.0.0-rc1 (commit 29bca10f03b7386e08d90003dfad708fe3e4ab99)

##### Swagger declaration file content or url

None

##### Command line used for generation

None.

##### Steps to reproduce

```shell
$ docker build --compress --force-rm --pull --tag v3.0.0-rc1-29bca10f03b7386e08d90003dfad708fe3e4ab99 .
...snip...
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-1/wagon-provider-api-1.0-beta-1.jar (41 KB at 1124.9 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /opt/swagger-codegen/modules/swagger-generator of /opt/swagger-codegen/pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.swagger:swagger-codegen-project:3.0.0-rc1 (/opt/swagger-codegen/pom.xml) has 1 error
[ERROR]     Child module /opt/swagger-codegen/modules/swagger-generator of /opt/swagger-codegen/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Removing intermediate container 843ca3457c89
The command '/bin/sh -c mvn -am -pl "modules/swagger-codegen-cli" package' returned a non-zero code: 1
```

##### Related issues/PRs

None I could find.

##### Suggest a fix/enhancement

No idea sorry!

**Comment by HugoMario** [comment]
Hey @fenollp 

I just merged a PR fixing this for `3.0.0-SNAPSHOT`, can you please check when you have a chance?

**Comment by fenollp** [comment]
Your patch fixed it! Thanks.
Now, what's the plan on growing the list of generatable languages back to what v2 supports? Right now it says
```

**Comment by HugoMario** [comment]
Hey  @fenollp, right now we're expecting help from community from that, but eventually we'll be adding languages to 3.0.0. Right now there is a [guide](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-(swagger-codegen-generators-repository)) that describes how to migrate languages.

**Comment by HugoMario** [comment]
So, i think we can close this now.
