### ISSUE TITLE
Swagger-Codegen 3.0.0-SNAPSHOT doesn't support python by default, but I could not find the place to add python 

### ISSUE THREAD

**Issue by markshao** [swagger-api/swagger-codegen#8384]
code branch : 3.0.0
build the latest version with the command : ./run-in-docker.sh mvn package

try the command : `java -jar swagger-codegen-cli.jar langs` , and see the result 

`Available languages: [dynamic-html, html, html2, java, jaxrs-cxf-client, jaxrs-cxf, inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs-jersey, jaxrs-di, jaxrs-resteasy-eap, jaxrs-resteasy, spring, kotlin-client, kotlin-server, php, swift3, swift4, typescript-angular]
`

Looks like the source code using the "ServiceLoader" to load the CodegenConfig , but I could not see any 'META-INF/services/' in the src , I don't know how to add python support

**Comment by HugoMario** [comment]
Hello @markshao,

All the files you need to add `python` support are located at [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators) repo.

If you are willing to add this language you can follow this [guide](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-(swagger-codegen-generators-repository)). And i can help you with any doubt/support you required, specially for templates changes, which are  explained [here](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-from-Mustache-and-Handlebars-templates.)

**Comment by markshao** [comment]
@HugoMario 
First, thanks for your comment.

Looks like I need to do some code migration from swagger-codegen to swagger-codegen-generator project for the Python support ?

**Comment by HugoMario** [comment]
@markshao 
That's right, but that migration is basically a copy/paste. Python language is already updated with OAS 3 classes in `swagger-codegen 3.0.0 branch`

**Comment by HugoMario** [comment]
actually i can make the migration and ping you to check the changes, since i´m not a python developer  (yet) it would be good to have some help.

**Comment by markshao** [comment]
it's my pleasure if you can help migrate the python generator , I can help check the python generator when you finished. We have a client project base on the OAS 3 python

**Comment by cognifloyd** [comment]
I see these python-related files (that should be deprecated once the move is complete):
- https://github.com/swagger-api/swagger-codegen/blob/3.0.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java
- https://github.com/swagger-api/swagger-codegen/blob/3.0.0/modules/swagger-codegen/src/test/java/io/swagger/codegen/python/PythonClientOptionsTest.java

Which should end up here:
- https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/java/io/swagger/codegen/languages (in python subdir)

=====================================================================

And these templates
- https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/python

Which should be converted and put here:
- https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/v2/ (v2 I'm guessing is not referring to the openapi version)

=====================================================================

Register the Python Generator here
- https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig

right?

**Comment by markshao** [comment]
@cognifloyd is it possbile share us a code branch that we can try to compile it in local?

**Comment by cognifloyd** [comment]
I started trying to figure out what code needed to go where, and then I found that OpenAPITools already has OpenAPI 3.0 support, so that's what I'm using now.

**Comment by HugoMario** [comment]
we're planning to do that this month, maybe next week, i'll let you guys know here.

**Comment by MichaelSEA** [comment]
Hey there - Any update on python/flask support for swagger-codegen-cli 3.x?

**Comment by catspirit** [comment]
> Hey there - Any update on python/flask support for swagger-codegen-cli 3.x?

same question here

**Comment by spacether** [comment]
Hey there - Any update on python/flask support for swagger-codegen-cli 3.x?

**Comment by Miiike89** [comment]
Hi- Any update on python support for swagger-codegen-cli 3.x?

**Comment by dialtr** [comment]
Is there any update on the state of Python support in swagger-codegen-cli?

**Comment by ms32035** [comment]
Guys, if it's an option openapi-generator supports Python

**Comment by dialtr** [comment]
Thanks for the tip, we just found this and are investigating!

**Comment by andrew-matteson** [comment]
I've got experimental Python support almost working [here](https://github.com/swagger-api/swagger-codegen-generators/pull/274); however, I need some support to get it working. Any advice would be appreciated.

The openapi-generator gives wrong code for my schema, and has similar issues to what's going wrong with my PR (oneOf issues).

**Comment by HugoMario** [comment]
hey @andrew-matteson, a python generator has been added. Can you please check it and let me know if works as expected? if it doesn't, please let me know and i'll work on a fix asap

**Comment by HugoMario** [comment]
hey guys, python generator has been added by https://github.com/swagger-api/swagger-codegen-generators/pull/292 . so going to close it but let me know if you find something wrong and i'll work on it asap.

**Comment by dialtr** [comment]
Excellent! Thanks for the note. I'll take a look ASAP.

**Comment by HugoMario** [comment]
@markshao i know it's been a while. but if you are still willing to check this it will be appreciated.
