### ISSUE TITLE
[Java] discriminator ignored, properties flattened.

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-codegen#8441]
_From @AlexeyNezhdanovGardena on July 17, 2018 15:56_

### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome, also tried command line.
 - Version: 67
 - Method of installation: use online; download and run jar
 - Swagger-Editor version: no idea
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration
I am trying to generate a java source code that would automatically distinguish between object types that are defined as anyOf with discriminator. 

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Example
paths:
  /a-path:
    get:
      responses:
        '200':
          description: example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      type: array
      items:
        $ref: '#/components/schemas/AnyPet'
    AnyPet:
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Lizard'
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
        mapping:
          cachorro: Dog
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string
    Lizard:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Lizard`
        properties:
          lovesRocks:
            type: boolean
```

### Describe the bug you're encountering
The discriminator field gets totally ignored, it is not even present in the source code. The "AnyPet" object that I defined comes back as a fuse between the three which is not the intention.

### To reproduce...

Please generate the "Java Client" from the yaml file above and examine the AnyPet class.

### Expected behavior
A source that would return a list of AnyPet objects from which Cat or Dog or Lizard could be retrieved.
A list of Pet objects would be even better.

### Additional context or thoughts

I have an impression now that this part is just not implemented. Am I right?

_Copied from original issue: swagger-api/swagger-editor#1838_

**Comment by shockey** [comment]
_From @hkosova on July 17, 2018 16:57_

Code generation is done by [Swagger Codegen](https://github.com/swagger-api/swagger-codegen). Please open an issue in the Swagger Codegen repository https://github.com/swagger-api/swagger-codegen/issues.

**Comment by shockey** [comment]
Closing, as this is a Codegen issue 😄

**Comment by AlexeyNezhdanovGardena** [comment]
I believe, this is a combination of two issues:
1) missing property: https://github.com/swagger-api/swagger-codegen/issues/8442
2) discriminator is ignored.

I think this particular issue could be closed now. If you want, I can file a separate ticket for discriminator handling in Java, but I am sure that the problem is well known - the bug tracker is full of references to that fact.

**Comment by shockey** [comment]
@AlexeyNezhdanovGardena sure - closing this in favor of #8442. thanks!

**Comment by spacebel** [comment]
When using allOf/oneOf it tries to extend one of the children element in the Java class. Which means the issue also occurs when using nested allOf sequence, as mentionned here : https://github.com/swagger-api/swagger-codegen/issues/8442
