### ISSUE TITLE
Generate POJOs without any library annotations

### ISSUE THREAD

**Issue by madhead** [swagger-api/swagger-codegen#8443]
##### Description

We're using standalone Git-versioned Swagger JSON file to describe our AWS API Gateway API. We want to generate a Java model from it using Gradle for future use in Lambdas. We don't use any plugins, just a `DefaultGenerator`. The model don't need any annotations to work - API Gateway does all the deserializations.

The default configuration produces a model with Gson annotation on model fields. There are options for Jackson as well, but how can I create just a POJO without any JSON annotations?

One more question: is it possible to override Java package for a particular response definition (model class)?

##### Swagger-codegen version

`DefaultGenerator` @ 2.3.1

##### Command line used for generation

*`build.gradle.kts`*:

```kotlin
import io.swagger.codegen.config.CodegenConfigurator
import io.swagger.codegen.DefaultGenerator

buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath("io.swagger:swagger-codegen:2.3.1")
	}
}

tasks {
	val generateApi by creating {
		inputs.file("src/main/swagger/aws-api-gw.json")
		outputs.dir("build/generated")

		doLast {
			val config = CodegenConfigurator().apply {
				inputSpec = "src/main/swagger/api.json"
				outputDir = "build/generated"
				lang = "java"
				modelPackage = "by.dev.madhead.app.model"
			}

			System.setProperty("models", "")
			System.setProperty("modelDocs", "false")

			DefaultGenerator().opts(config.toClientOptInput()).generate()
		}
	}
}
```

**Comment by bledari** [comment]
+1
