### ISSUE TITLE
Indentation removed in master and develop_2.0

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#845]
Indentation in the mustache templates have been removed by this commit:

https://github.com/swagger-api/swagger-codegen/commit/1c2d0656b07829ad6786df40851262fc4c1c429e

This affects particularly python, which relies on indentation to compile the code properly.

@webron @fehguy would you please take a look and roll back the change if possible?

**Comment by webron** [comment]
Too late, it was released. Feel free to submit a PR to fix it though for the next one.

**Comment by fehguy** [comment]
I think we will have to fix this asap

**Comment by webron** [comment]
Sure thing.

**Comment by wing328** [comment]
I would suggest recovering the template files from the commit https://github.com/swagger-api/swagger-codegen/commit/22d7db2cb4579e40eabe73f9f9482fe4bd4fa264 (which is the commit right before https://github.com/swagger-api/swagger-codegen/commit/1c2d0656b07829ad6786df40851262fc4c1c429e)

**Comment by wing328** [comment]
@webron let me work on the fix as I believe it's already mid-night for you.

**Comment by webron** [comment]
@wing328 - thanks. If @fehguy won't manage to release the fix later, I'll do it tomorrow. If you have time, please check if there are any other *critical* issues to be fixed. Would be better to not have a stream of fixes :) Thanks for all the help!

**Comment by wing328** [comment]
@webron no problem. Please get some rest.

**Comment by wing328** [comment]
PR merged
