### ISSUE TITLE
[Spring Boot] Compilation error for javax.validation.constraints.Max(9999999999) annotation if value is int64 in Swagger specification

### ISSUE THREAD

**Issue by ppotemki** [swagger-api/swagger-codegen#8479]
##### Description

Compilation errors after generating Spring Boot project.

Example of a parameter definition:
```json
"parameters": [{
    "name": "customerId",
    "in": "path",
    "description": "ID of a customer",
    "required": true,
    "type": "integer",
    "format": "int64",
    "minimum": 1000000000,
    "maximum": 9999999999
},
```

Generated code:
```java

default ResponseEntity<Account> getAccountById(@Min(1000000000) @Max(9999999999) @ApiParam(value = "ID of account",required=true) @PathVariable("customerId") Long customerId

```

Obviously, `@Max(9999999999)` is not an int. Int upper limit in Java is `2,147,483,647`.

##### Swagger-codegen version

2.3.1.

##### Swagger declaration file content or url

```json
"paths": {
    "/accounts/{customerId}": {
      "get": {
        "tags": ["accounts"],
        "summary": "Find account by ID",
        "description": "Returns an account",
        "operationId": "getAccountById",
        "parameters": [{
          "name": "customerId",
          "in": "path",
          "description": "ID of account",
          "required": true,
          "type": "integer",
          "format": "int64",
          "minimum": 1000000000,
          "maximum": 9999999999
        }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Account"
            }
          }
        }
      }
    }
  },
```

##### Command line used for generation

Maven plugin. Language is set to `spring`.

##### Steps to reproduce

Generate spring-boot app based on specification that includes parameter with type integer and maximum value more than allowed for int in Java (i.e. 9999999999).

##### Suggest a fix/enhancement

Make `javax.validation.constraints.Max(9999999999)` value `long` if parameter is `int64` in Swagger specification.

**Comment by silkentrance** [comment]
Maybe appending a 'L' for 'long' will do the trick?

**Comment by silkentrance** [comment]
@ppotemki I think I have found the reason for this:

Given a spec such as 

```
swagger: "2.0"
info:
  version: 0.0.0
  title: Example
paths:
  /foo:
    get:
      responses:
        '200':
          description: Random pet
          schema:
            $ref: '#/definitions/Foo'
definitions:
  Foo:
    type: object
    properties:
      lint:
        type: integer
        format: int64
```

will work, and the `lint` property will be generated as a field of type `Long`

```
public class Foo {
  @SerializedName("lint")
  private Long lint = null;
```

However, when indirecting this by defining a second definition, e.g.

```
swagger: "2.0"
info:
  version: 0.0.0
  title: Example
paths:
  /foo:
    get:
      responses:
        '200':
          description: Random pet
          schema:
            $ref: '#/definitions/Foo'
definitions:
  Foo:
    type: object
    properties:
      lint:
        $ref: "#/definitions/Lint"
  Lint:
    type: integer
    format: int64
```

then the generated code will look like this

```
public class Foo {
  @SerializedName("lint")
  private Integer lint = null;
```

So the initial assumption, that it loses knowledge of the `format` was correct.

**Comment by ppotemki** [comment]
> what is your target language?

Language is set to: `spring`

Also, we did not face an issue with the wrong parameter type. So in this generated code:
```java
default ResponseEntity<Account> getAccountById(@Min(1000000000) @Max(9999999999) @ApiParam(value = "ID of account",required=true) @PathVariable("customerId") Long customerId
```
Parameter type is `Long`, which is correct, given the specification:
```json
    "type": "integer",
    "format": "int64",
    "minimum": 1000000000,
    "maximum": 9999999999
```
Only in `@Max(9999999999)` it is using an `int` (i.e. not appending `L`).

> However, when using spring as the language, the beanValidationCore template will not be used, at least on current master, and the @Min etc. annotations will never be generated.

Actually, I didn't test it with `master`. Only with `2.3.1` from maven central.

> However, when indirecting this by defining a second definition, e.g.

Yes, but in our case there is no indirection for parameter. Please, see an updated version of the Swagger JSON in the original question.

**Comment by silkentrance** [comment]
Will you give the latter a try, the one that actually fixes your problem? I don't believe that the swagger team needs any test cases for this 😀 as they are currently working on OpenAPI v3.0.0.

See https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/JavaSpring for starters.

**Comment by ppotemki** [comment]
An error with `L` postfix is fixed in master (v. 2.4.0). So I am closing this issue.
