### ISSUE TITLE
Java client codegen BigDecimal initialised to 0 rather than BigDecimal.ZERO

### ISSUE THREAD

**Issue by rhysphelps1970** [swagger-api/swagger-codegen#8515]
##### Description
Java language client code generation from json v3 spec.
BigDecimal is being initialised using the numeral 0, rather than BigDecimal.ZERO.
This is causing compilation errors that need to be corrected.

Some examples of the default output:
  @SerializedName("PastDue")
  private BigDecimal pastDue = 0;
  
  @SerializedName("Total")
  private BigDecimal total = 0;
  
  @SerializedName("TotalDepositAmount")
  private BigDecimal totalDepositAmount = 0;

When the code is updated to init using the static it compiles just fine.
private BigDecimal totalDepositAmount = BigDecimal.ZERO

This code seems to be in v3. Schema code set, and not part of the codegen set. 

##### Swagger-codegen version

https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180717.153005-90.jar

##### Swagger declaration file content or url
"SubscriberManagement-PostpaidDetail":{"type":"object","properties":{"Balance":{"type":"number","format":"decimal","description":"Balance","default":0,"nullable":true},"CurrencyCode":{"type":"string","description":"Currency Code","minLength":0,"nullable":true},"DelinquencyAmount":{"type":"number","format":"decimal","description":"The current amount delinquent","default":0,"nullable":true},"DelinquencyDays":{"type":"integer","format":"int32","description":"Days Delinquent","default":0,"nullable":true},"DueDate":{"type":"string","format":"date-time","description":"Due Date","nullable":true},"LastInvoiceId":{"type":"integer","format":"int64","description":"Last Invoice Id","nullable":true},"LastPaymentAmount":{"type":"number","format":"decimal","description":"Last Payment Amount","nullable":true},"LastPaymentDate":{"type":"string","format":"date-time","description":"Last Payment Date","nullable":true},"PastDue":{"type":"number","format":"decimal","description":"Past Due Amount","default":0,"nullable":true},"Total":{"type":"number","format":"decimal","description":"Total Amount","default":0,"nullable":true},"TotalDepositAmount":{"type":"number","format":"decimal","description":"Total Amount of all Deposits on Postpaid Account","default":0,"nullable":true}}},"SubscriberManagement-PrepaidDetail":{"type":"object"}

##### Command line used for generation

set jarfile=swagger-codegen-cli-3.0.0-20180710.190537-87.jar
set language=java
set inputfile=.v3.spec.json
set output=C:/Ascendon/swagger/
set apipackage=csgi.dbss.api.
set modelpackage=csgi.dbss.model.

FOR %%A IN (Subscriber) DO (	
	java -jar %jarfile% generate -i %%A%inputfile% -l %language% -o %output%%%A --api-package %apipackage%%%A --model-package %modelpackage%%%A -v
	pause
)
pause
##### Steps to reproduce

Client codegen for java.  The errors occur in code generated under the model. From the json spec pasted above, SubscriberManagementPostpaidDetail.java contains 3 examples.

##### Suggest a fix/enhancement

toDefaultValue takes a schema, which seems to be part of v3.media.models.Schema.NumberSchema. It might be that part of the code, but I am not sure.

**Comment by HugoMario** [comment]
thanks @rhysphelps1970, going to check this after refactoring we're working on.

**Comment by francoisprunier** [comment]
I can confirm that's still the case. It's not only zero. Actually, try it with a property that has a 'number' schema and any sort of default value. It should wrap it in the constructor like this `new BigDecimal(<defaultValue>)`

**Comment by azakordonets** [comment]
Any chance you guys can take a look at it now ? It's been more then a year since this was posted. Or maybe you could point me to where to look and i could try make a PR for you ?

**Comment by aczire** [comment]
Even after 2+ years, the case is same, any chance to get this fixed?
