### ISSUE TITLE
[jaxrs-jersey] Runtime errors running sample.

### ISSUE THREAD

**Issue by HugoMario** [swagger-api/swagger-codegen#8530]
##### Description
Multiples error trying to run sample:

```
org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] A HTTP GET method, public javax.ws.rs.core.Response io.swagger.api.FakeApi.testJsonFormData(java.lang.String,java.lang.String,javax.ws.rs.core.SecurityContext) throws io.swagger.api.NotFoundException,

javax.servlet.ServletException: jersey@baa68670==org.glassfish.jersey.servlet.ServletContainer,1,false

```

##### Swagger-codegen version

2.4.0-SNAPSHOT

##### Swagger declaration file content or url
[petstore-with-fake-endpoints-models-for-testing-yaml](https://gist.github.com/HugoMario/5292d9936367ac145ba80e895793e003#file-petstore-with-fake-endpoints-models-for-testing-yaml)

##### Steps to reproduce

just `cd` to `swagger-codegen/samples/server/petstore/jaxrs/jersey2`
then run: `mvn jetty:run`

**Comment by frantuma** [comment]
fixed in #8538
