### ISSUE TITLE
Problem with Windows

### ISSUE THREAD

**Issue by lakeba** [swagger-api/swagger-codegen#858]
My project work very well on MAC but not on windows:

1) a csharp project
can't open csharp\Newtonsoft.Json.dll for input
can't open csharp\RestSharp.dll for input

2) a objc project
can't open objc\SWGObject.h for input
can't open objc\SWGObject.m for input
can't open objc\SWGQueryParamCollection.h for input
can't open objc\SWGQueryParamCollection.m for input
can't open objc\SWGApiClient.h for input
can't open objc\SWGApiClient.m for input
can't open objc\SWGFile.h for input
can't open objc\SWGFile.m for input
can't open objc\JSONValueTransformer+ISO8601.m for input
can't open objc\JSONValueTransformer+ISO8601.h for input

**Comment by wing328** [comment]
I believe you confirmed the issues were fixed before: #803 , #785 

Are you using the latest develop_2.0 ?

**Comment by moczkowski** [comment]
I have the same problem on Windows 8.1 for csharp output using latest develop_2.0.

**Comment by uniprof** [comment]
I am using the last developer 2.0 and the problem was fixed before only for MAC, check my comment in #803.

**Comment by wing328** [comment]
I've filed #867 to fix the issue. I tested the fix in Windows and Mac, and both worked for me. Please kindly give it a try:

Repo: `https://github.com/wing328/swagger-codegen`
Branch with the fix: `fix_jar_path`

**Comment by wing328** [comment]
The fix has been merged into develop_2.0.

@uniprof please kindly close this task if you no longer encounter the issue.

**Comment by uniprof** [comment]
On MAC is still working well, on windows this is the new problem now:

C:\Users\giuseppe.porcelli\Documents\git\swagger-codegen-uniprof>java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://localhost:4529/swagger/docs/v1 -l csharp -o easyDocs/client/csharp

reading from http://localhost:4529/swagger/docs/v1
writing file C:\Users\giuseppe\porcelli\Documents\git\swagger-codegen-uniprof\easyDocs\client\csharp/src/main/csharp/IO/Swagger/Model\RegisterBindingModel.cs
java.io.FileNotFoundException: C:\Users\giuseppe\porcelli\Documents\git\swagger-codegen-uniprof\easyDocs\client\csharp\src\main\csharp\IO\Swagger\Model\RegisterBindingModel.cs (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at io.swagger.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:25)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:142)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

seems that the method is replacing giuseppe.porcelli with giuseppe\porcelli

**Comment by wing328** [comment]
to confirm, did you pull the upstream to use the latest develop_2.0 ?

**Comment by uniprof** [comment]
yes I did pull the upstream.

with this changes below, MAC and WINDOWS work fine now

    @Override
    public String apiFileFolder() {
        return (outputFolder + "/" + sourceFolder + "/" + apiPackage().replace('.', '/'));
    }

    public String modelFileFolder() {
        return (outputFolder + "/" + sourceFolder + "/" + modelPackage().replace('.', '/'));
    }

**Comment by wing328** [comment]
should you be using File.separartor instead ?

**Comment by uniprof** [comment]
yes File.separator work as well on both platform

**Comment by uniprof** [comment]
@Override
    public String apiFileFolder() {
        return (outputFolder + "/" + sourceFolder + "/" + apiPackage().replace('.', File.separatorChar));
    }

    public String modelFileFolder() {
        return (outputFolder + "/" + sourceFolder + "/" + modelPackage().replace('.', File.separatorChar));
    }

**Comment by wing328** [comment]
Feel free to submit a PR for develop_2.0 branch

**Comment by uniprof** [comment]
please can you do it? I am not a good PR !!!

**Comment by wing328** [comment]
Do you mind testing other languages so that we've better picture of the issue in the Windows platform ?

**Comment by uniprof** [comment]
I will do

**Comment by lakeba** [comment]
Test finished, all compile well on Windows now. I will close this issue.
