### ISSUE TITLE
Python client is generated in 'SwaggerPetstore-python' directory

### ISSUE THREAD

**Issue by yzats** [swagger-api/swagger-codegen#860]
With swagger-codegen 2.1.2, python client is generated in  *clients/python/SwaggerPetstore-python/SwaggerPetstore/* directory. It should be just *clients/python*.

See Google Groups [thread](https://groups.google.com/forum/#!topic/swagger-swaggersocket/bXT1_OYLrSk) about this issue.

**Comment by geekerzp** [comment]
Sorry, I didn't have enough time to implement the CLI option for Python client before the latest major release.

Here is a PR (#864) to fix that.

**Comment by wing328** [comment]
PR merged. Closing this issue.
