### ISSUE TITLE
[ALL?] Bug: Request body's schema can not contain allOf ("String to be sanitized is null. Default to Object")

### ISSUE THREAD

**Issue by djslin99** [swagger-api/swagger-codegen#8601]
##### Description
When I have an `allOf` keyword in my request body's schema, I get the following warning three times:
`String to be sanitized is null. Default to Object`

##### Swagger-codegen version
Self build with 3.0.0 Branch commit  d78362d

##### Swagger declaration file content

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test
paths:
  /test:
    post:
      operationId: test
      requestBody:
        required: true
        content:
          application/json:
            schema:
               allOf:
                - $ref: '#/components/schemas/Test'
      responses:
        default:
          description: response...
components:
  schemas:
    Test:
      type: object
```

##### Command line used for generation
I tried it with java, jaxrs-cxf-client, jaxrs-cxf, spring and typescript-angular. I can test more languages if needed.

For example: `java -jar swagger-codegen-cli.jar generate -l spring -i test.yaml -o test`

##### Steps to reproduce
Use the `allOf` keyword in request body's schema and generate spring code

**Comment by rasentry** [comment]
The same issue with 3.0.8

**Comment by skyzenr** [comment]
Same for me. v 3.0.12.

**Comment by HugoMario** [comment]
this has been addressed by https://github.com/swagger-api/swagger-codegen-generators/pull/513
