### ISSUE TITLE
Question: Use PSR standards for PHP Client

### ISSUE THREAD

**Issue by ammmze** [swagger-api/swagger-codegen#861]
Anybody wildly opposed to updating the PHP client follow the [PSR-2 code standards](http://www.php-fig.org/psr/psr-2/)?

**Comment by wing328** [comment]
@ammmze thanks for proposing the change to follow the code standard.
My understanding is that this will not change the method naming and method argument naming. Please correct me if I'm wrong.

@fehguy FYI. The proposed change will change the indentation from 2 spaces to 4 spaces

**Comment by ammmze** [comment]
@wing328 You are correct, the method names and method arguments would remain the same. 

PSR "intentionally avoids any recommendation regarding the use of `$StudlyCaps`, `$camelCase`, or `$under_score` property names". However, it does also say "Whatever naming convention is used SHOULD be applied consistently within a reasonable scope. That scope may be vendor-level, package-level, class-level, or method-level" and I do see that in method arguments, we use `$camelCase` (which I prefer), but in property names, we are using `$under_score`. 

I did see (relatively) recently that even the model properties now have an attribute map and that is converting the properties from `$camelCase` to `$under_score`. Are we set on doing that? Perhaps its better to leave them as-is? Or maybe provide an option for the property convention.

**Comment by wing328** [comment]
@ammmze the attribute map is for handling JSON key name that will cause issue in PHP. e.g. the JSON key "12month_avg" will cause compile error in PHP when using it as a variable name.

**Comment by wing328** [comment]
@ammmze FYI. I'm working on a PR to enable CLI option (similar to #864) so that users can change the method and property naming convention

**Comment by ammmze** [comment]
Awesome 😀 Great to hear
