### ISSUE TITLE
[JavaJaxRS] enhance beanvalidation by adding @Valid

### ISSUE THREAD

**Issue by nisargshah95** [swagger-api/swagger-codegen#8641]
##### Description

Using bean validation does not add `@Valid` annotation to codegen generated files. Similar ticket was filed for Java (#5498). The changes need to be ported to JavaJaxRS as well.

##### Swagger-codegen version

master (2.4.0)

##### Related issues/PRs

#5498 - [JAVA] enhance beanvalidation with adding @Valid
##### Suggest a fix/enhancement

Set of changes from PR #5517 can be applied

**Comment by deveshpujari** [comment]
Can someone fix this for JavaJaxRs in 2.4.0 ? Whole feature of bean validation in JavaJaxRS has become unusable because of this bug. 
Thanks,

**Comment by HugoMario** [comment]
@deveshpujari, got it, let's fix this!

**Comment by nisargshah95** [comment]
This seems like a duplicate of #7651. @HugoMario you can close of these at your will.

**Comment by deveshpujari** [comment]
@HugoMario 
I looked at this little bit. Apart from the changes done in commit [d08d55d](https://github.com/swagger-api/swagger-codegen/commit/d08d55d4190c916e2ce8c55be27a9da4eaa4b0e8)  it needs fix in api.mustache file also to add the {{>beanValidation}} . Also I am not sure if for nested objects @Valid is working or not.

**Comment by deveshpujari** [comment]
@HugoMario 
Is there a way to add the message template in the swagger yaml file. Currently all annotations are generated like 
@NotNull

but if i want with message.
@NotNull(message = "{contact.wrong.name}")

This way i can provide more specific message in the ValidationMessages.properties file.

**Comment by HugoMario** [comment]
i think we can use vendor extensions for that.

**Comment by HugoMario** [comment]
@deveshpujari ^^

**Comment by MariaPushkin** [comment]
I've fixed that by changing some mustache files, but my PR checks failed with exec-maven-plugin:1.2.1 on project PythonPetstoreClientTests. But I change nothing related to python. Maybe someone know what's wrong?

**Comment by deveshpujari** [comment]
@HugoMario 
Is there any way we can add custom validation annotation in the yaml file. Like for for ipv4 format , i want to add my custom validators.

**Comment by deveshpujari** [comment]
> i think we can use vendor extensions for that.

@HugoMario 
Could you please provide an example on how  to use the vendor extension ? Thanks.

**Comment by HugoMario** [comment]
hello @deveshpujari sorry for delay, here is a description about vendor extension https://github.com/swagger-api/swagger-codegen/wiki/Vendor-Extensions . let me know if you have any doubt or more question about it.

**Comment by miralexan** [comment]
@HugoMario @deveshpujari have either of you looked at @MariaPushkin's PR? I dont think it addresses the validator customization asks, but it looks like it fixes the base `@Valid` issue.

**Comment by malikb1** [comment]
Hello .. any update on this yet

**Comment by Roopa-Riya** [comment]
> > i think we can use vendor extensions for that.
> 
> @HugoMario
> Could you please provide an example on how to use the vendor extension ? Thanks.



> > i think we can use vendor extensions for that.
> 
> @HugoMario
> Could you please provide an example on how to use the vendor extension ? Thanks.

can upate on the example?
can you please share an example how to use this?
