### ISSUE TITLE
Add support for asp.net core 2.1

### ISSUE THREAD

**Issue by SeanFarrow** [swagger-api/swagger-codegen#8678]
It would be nice if the generator supported Asp.Net Core 2.1.

I'm happy to do the work for this, but have a few questions:

Firstly, is there a way to completely exclude files from the output if they are not needed. The case where SwashBuckle is not included is the example I'm thinking of.
Secondly, how does the generator indicate that authorization is needed on an endpoint to the code that generates files from the templates.
Thanks for any help.
Sean.

**Comment by HugoMario** [comment]
hi @SeanFarrow aspnet core 2.1 is partially implemented on:
https://github.com/swagger-api/swagger-codegen/pull/9529 for codegen v2
and
https://github.com/swagger-api/swagger-codegen-generators/pull/397
for codegen v3

about exclude files, please give me an example of what files should be exclude, and i'll try to help with that.

security was not previously supported, so please check these now and let me know.
