### ISSUE TITLE
only last media type considered in request body when multiple types are defined

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-codegen#8679]
##### Description

only last media type considered in request body when multiple types are defined in a request body, only the last one get considered (at least e.g. in java client)

##### Swagger-codegen version

3.0.1-SNAPSHOT

##### Swagger declaration file content or url

https://gist.github.com/frantuma/40d3b1610b70693717393969562ad3f5

##### Command line used for generation

via online generator, request:
```
{
  "specURL" : "https://gist.github.com/frantuma/40d3b1610b70693717393969562ad3f5",
  "spec" : {},
  "lang" : "java",
  "options" : {
    "additionalProperties" : {
    	"useRuntimeException": true,
    	"useRxJava" : true
    }
  },
  "type" : "CLIENT",
  "codegenVersion" : "V3"
}
```

##### Steps to reproduce

run the generator for java client, and see there will be no updatePet(Pet pet) operation in generated client

**Comment by HugoMario** [comment]
this issue has been fixed with [codegen-generators 299 PR](https://github.com/swagger-api/swagger-codegen-generators/pull/299)
