### ISSUE TITLE
Upload/Download files

### ISSUE THREAD

**Issue by lakeba** [swagger-api/swagger-codegen#869]
looks like the file upload/download is something to implement in swagger-codegen as well

https://github.com/domaindrivendev/Swashbuckle/issues/120

**Comment by wing328** [comment]
File upload should work. What client did you test and what error did you get ?

For file download, it's a limitation with the spec. Please refer to https://github.com/swagger-api/swagger-spec/issues/50 for more information.

**Comment by uniprof** [comment]
When you say that File Upload should work, what do you mean? where is it and how to use it?

**Comment by wing328** [comment]
Petstore has an example to upload image: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L351

**Comment by uniprof** [comment]
Thanks for your feedback.

Can you please clarify how the client will translate it ?

 {
            "name": "file",
            "in": "formData",
            "description": "file to upload",
            "required": false,
            "type": "file"
          }

**Comment by wing328** [comment]
@uniprof please refer to https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameter-object

You can also use http://petstore.swagger.io/#!/pet/uploadFile and Chrome Devtools to inspect the HTTP header and body

**Comment by lakeba** [comment]
Any news about the download ? 
What format from Web Api we must return to download a file/Image ?

**Comment by umbreak** [comment]
Is the download capability ready? I've understood that the decision to use [Hypermedia](http://json-schema.org/latest/json-schema-hypermedia.html#anchor3) has been taken. However, is there something new?
