### ISSUE TITLE
[JAVA] Bug generating model with inline definitions

### ISSUE THREAD

**Issue by florintene** [swagger-api/swagger-codegen#8704]
##### Description

It seems that the 3.0.0 version doesn't correctly generate the models when the model has a nested inline definition. 
In the example below there are 2 definitions under "Pet":
- the first one "_categoryInline_" is defined inline
- the second one "_category_" is a reference pointing to a top level object definition

e.g. take the following definition (using the pet store sample):
```yaml
Pet:
    type: "object"
    properties:      
      categoryInline:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          name:
            type: "string"
        xml:
          name: "Category"
      category:
        $ref: "#/definitions/Category"
```

Now, the code generated for the "Pet" model is not correct (unless this is a desired behaviour, not sure) as the "categoryInline" is defined as Object:

```
public class Pet   {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("categoryInline")
  private Object categoryInline = null;

  @JsonProperty("category")
  private Category category = null;
```

Using the above swagger definition in codegen 2.3.1 or 2.4.0 is producing the correct results.

##### Swagger-codegen version

Swagger-codegen 3.0.0  Thu Sep 06 15:07:36 UTC 2018 (Size: 18684752)

Source: 
```https://oss.sonatype.org/content/repositories/releases/io/swagger/codegen/v3/swagger-codegen-cli/3.0.0/swagger-codegen-cli-3.0.0.jar```

As a note, i've also tried with the source code from the 3.0.0 branch

##### Swagger declaration file content or url

```yaml
Pet:
    type: "object"
    properties:      
      categoryInline:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          name:
            type: "string"
        xml:
          name: "Category"
      category:
        $ref: "#/definitions/Category"
```

##### Command line used for generation

The call to swagger-codegen to generate the code for spring was done like this:
```java -jar swagger-codegen-cli-3.0.0.jar generate -i petSample.swagger -l spring -o petSwaggerSample```

##### Steps to reproduce

1. Add the following definition in the standard "Swagger PetStore" sample under the "Pet" object:
```yaml
      categoryInline:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          name:
            type: "string"
        xml:
          name: "Category"
```
2. Generate the "spring" code
3. Check the "Pet.java" class generated

##### Related issues/PRs

Seems to be similar to the:  [Issue-4883](https://github.com/swagger-api/swagger-codegen/issues/4883)

##### Question

Looking at the 4883 issue, the workaround was to define everything as a top level definition but this is not always feasible. 
I think i'm more interested to know if this will be treated as a bug or this is the behavior that should be expected in 3.0.0 ?

**Comment by HugoMario** [comment]
looks like a bug, let's fix this!

**Comment by HugoMario** [comment]
This is happening when a OAS 2 definition is used. working with a OAS 3 definition gets the expected output. 

It's still a bug, but the solution could be in `swagger-parser` project. I'll keep on figuring this out, and let you know here.

**Comment by florintene** [comment]
Great, many thanks. I will look into OAS 3 option, although at the moment all our definitions are based on OAS 2. Thanks again for looking into this one.

**Comment by 0DArk-aveNGER** [comment]
Hi we're having the same issue with version 3.0.17. Is there any planned item in your backlog for this issue? Is there any workaround we can apply temporarily?

**Comment by apae89** [comment]
I'm facing the same issue with version 3.0.18 and OpenAPI 3.0 spec file. Any news related to this issue?

**Comment by HugoMario** [comment]
hey guys. PR [swagger-parser#1360](https://github.com/swagger-api/swagger-parser/pull/1360) will fix this issue. Just waiting for reviewing and merging.

**Comment by HugoMario** [comment]
[swagger-parser#1360](https://github.com/swagger-api/swagger-parser/pull/1360) has been merged, so this is fixed, changes can be used on snapshots or next releases, thanks everyone and sorry for delay.

Closing now, if error still persist, please let me know.
