### ISSUE TITLE
[JAVA] Client generated with deprecated code.

### ISSUE THREAD

**Issue by emile-jumo** [swagger-api/swagger-codegen#8705]
##### Description
I use wagger to define my API and generate clients form the swagger spec. When I generated the Java client using swagger-codegen a class called `RFC3339DateFormat.java` was generated and it extends `ISO8601DateFormat` which is deprecated.

Do suggest that I replace it manually with the preferred class `StdDateFormat`? Or is there configuration that I should set to use `StdDateFormat` rather.

##### Swagger-codegen version
2.3.1

**Comment by emile-jumo** [comment]
Moving this issue to OpenAPI generator: https://github.com/OpenAPITools/openapi-generator/issues/1053

**Comment by chenjianjx** [comment]
Don't have to close this issue.  Swagger-codegen and openapi-generator are different projects. The problem should also be fixed here.
