### ISSUE TITLE
[C#] Models to be generated as partial

### ISSUE THREAD

**Issue by Hadou1** [swagger-api/swagger-codegen#872]
During our development we noticed the need of small manipulations on the generated models. Hence to this need the model object should be generated as partial classes, which then easaly can be extended for certain custom developer needs.

**Comment by wing328** [comment]
@Hadou1 do you mind sharing a bit more about the "small manipulations" and your use case ? I'm definitely open to the idea of partial classes.

**Comment by Hadou1** [comment]
Partial classes can be used in order to extend the retrieved models by calculated properties.

**Comment by wing328** [comment]
No concern from me

**Comment by wing328** [comment]
@Hadou1 do you still want to make the C# model partial? If yes, please submit a PR against the master branch.

**Comment by wing328** [comment]
@Hadou1 closing this as we've not heard any update from you.
