### ISSUE TITLE
[PHP] Swagger codegen 3.0 multiple request types comma missing (Syntax error)

### ISSUE THREAD

**Issue by blasto333** [swagger-api/swagger-codegen#8722]
##### Description

When generating swagger codegen 3.0 spec in php the following is generated for request headers

(comma forgotten)

```
 $headers = $this->headerSelector->selectHeaders(
                ['application/json''application/xml'],
                ['application/json''multipart/form-data']


```

##### Swagger-codegen version

3

##### Swagger declaration file content or url

https://demo.phppointofsale.com/application/controllers/api/

##### Command line used for generation

php 7.1
##### Steps to reproduce
`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://demo.phppointofsale.com/application/controllers/api/ -l php -o /Users/cmuench/Desktop/api`

**Comment by hampsterx** [comment]
dup of #8345

**Comment by HugoMario** [comment]
issue has been fixed, so going to close it but please let me know if you guys find something wrong and we can reopen it.
