### ISSUE TITLE
[C#] Introduction of abstract apiBase class and ApiInjector Interface

### ISSUE THREAD

**Issue by Hadou1** [swagger-api/swagger-codegen#873]
In order to centralize certain logic it would be nice to introduce a abstract base class, in which for example central api call logic could be placed.
Further, when the call logic is centralized a ApiInjector could be introduced in order to provide the end developer the possibility to react before, after and on exception inside the context of one certain call. 
This would be needed for the use case of dynamically reacting on expired tokens inside a certain call which could be refreshed during the call.

**Comment by wing328** [comment]
@Hadou1 so your goal is to make the auto refresh of expired token transparent to the developers using the C# SDK?

**Comment by Hadou1** [comment]
yes thats correct - espacially in case of the technical client tokens.

**Comment by wing328** [comment]
@Hadou1 are you still planning to submit a PR (against the master branch) for the change above?

**Comment by wing328** [comment]
@Hadou1 closing this as we've not heard any update from you.
