### ISSUE TITLE
[TYPESCRIPT-ANGULAR] Cannot build because SubscriptionLike is not found

### ISSUE THREAD

**Issue by cornem** [swagger-api/swagger-codegen#8732]
##### Description

If I try to build the project that was generated with `ngVersion=6` (without any changes made to the generated files), I get the following error:

    node_modules/@angular/common/src/location/location.d.ts:8:10 - error TS2305: Module '"{path}/node_modules/rxjs/Rx"' has no exported member 'SubscriptionLike'.

##### Swagger-codegen version

2.3.1

**Comment by macjohnny** [comment]
@cornem generating for `ngVersion=6` only works for https://github.com/swagger-api/swagger-codegen/tree/v3.0.0 or the community fork https://github.com/OpenAPITools/openapi-generator/tree/v3.2.3 (which contains more enhancements, too)
So I think this issue should be closed.

**Comment by cornem** [comment]
@macjohnny Thanks, I'll try that instead.
