### ISSUE TITLE
Maven Central Missing 3.0.0

### ISSUE THREAD

**Issue by KyleJamesWalker** [swagger-api/swagger-codegen#8739]
##### Description

There is a [GitHub release of 3.0.0](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0), but Maven Central only has RC versions of 3.

```
wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/3.0.0/swagger-codegen-cli-3.0.0.jar -O swagger-codegen-cli.jar
```

Is the v3 released 19 days ago, being held back for any reason?

**Comment by hkosova** [comment]
It's here:
http://central.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.0/

[3.0.0 release notes](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0) mention that the package has been moved:
> NOTE: artifact groupId and root package of modules have been updated since 3.0.0-RC1 (#8431); the new groupId is `io.swagger.codegen.v3` and the new root package is `io.swagger.codegen.v3`.
