### ISSUE TITLE
Golang stub code generation issue v.3.0.0

### ISSUE THREAD

**Issue by kko0** [swagger-api/swagger-codegen#8743]
##### Version 
Golang stub code generation issue v3.0.0
OpenAPI v3

##### Description 
Hello, I was trying to generate a Golang server stub following the steps here https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#go-server but 
 either it doesn't build(1st screenshot) or can not generate Golang code because it doesn't exist for it (2nd screenshot). 

##### Steps to reproduce
1. Following the steps here 
https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#go-server

it can't even build the project, it is also pointing to v2.4.0.  

Maven output : 

![ps-codegen](https://user-images.githubusercontent.com/43600139/46065160-aba54380-c171-11e8-81f3-22720b343b09.PNG)
 
2. If you download the zip from https://github.com/swagger-api/swagger-codegen/releases and then extract and build it using the steps here https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#go-server  - it builds.  But when you try to generate a Golang server stub it gives this error 

![cmd-codegen3 0 0](https://user-images.githubusercontent.com/43600139/46065100-8284b300-c171-11e8-99ff-4627d6e87f6d.PNG) 

Hopefully this will be fixed soon :)

**Comment by HugoMario** [comment]
hello @adamdecaf for codegen v3, we place the generator class in this repo: https://github.com/swagger-api/swagger-codegen-generators

We have been working on generator classes migration and `Golang` is in plan.

**Comment by adamdecaf** [comment]
Cool! Have you started on the Go generator? I could try and poke around to get that going.

**Comment by HugoMario** [comment]
@adamdecaf i'll try to get it done for earlier next week. if you can help me with some feedback it would be pretty helpful

**Comment by coffeepac** [comment]
Hello friends!  Any update on this issue?  I'd be happy to be a beta tester for this go generation.

**Comment by krishnareddyakkala** [comment]
it seems the V3.0.8 is not supporting GoLang codegen. can anyone please update by when the codegen support for OpenAPIV3 support will be provided for GoLang?

**Comment by adamdecaf** [comment]
I use v4.0.2 to generate Go clients. You should try the 4.x series of [openapi-generator](https://github.com/OpenAPITools/openapi-generator/releases).

**Comment by HugoMario** [comment]
solved by [swagger-codegen-generators#641](https://github.com/swagger-api/swagger-codegen-generators/pull/641)
