### ISSUE TITLE
[TYPESCRIPT-ANGULAR] nothing get generated at all after commit 64553ba

### ISSUE THREAD

**Issue by lea-raya** [swagger-api/swagger-codegen#8744]
##### Description

Nothing get generated at all after  64553ba2fae530913b7b55be25ed6998701f48bb / #8713 / #8712 
for `typescript-angular-v6`

##### Swagger-codegen version

2.0.4-SNAPSHOT

##### Swagger declaration file content or url

_see below_

##### Command line used for generation

_see below_

##### Steps to reproduce

Checkout mater (now on 1f93f09b0215ac6dd84c28e8a66608f401c9ceac)
```bash
mvn package -DskipTests=true
rm -rf target
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar \
	generate -l typescript-angular \
	-i samples/yaml/echo.yaml \
	-c <(echo '{"ngVersion": "6.0.0","npmName": "echo","version":"0.0.1"}') \
	-o target
file target/package.json
```
→ `cannot open 'target/package.json' (No such file or directory)`

```bash
git revert 64553ba2f
mvn package -DskipTests=true
rm -rf target
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar \
	generate -l typescript-angular \
	-i samples/yaml/echo.yaml \
	-c <(echo '{"ngVersion": "6.0.0","npmName": "echo","version":"0.0.1"}') \
	-o target
file target/package.json
```
→ `target/package.json: ASCII text`

##### Related issues/PRs

64553ba2fae530913b7b55be25ed6998701f48bb / #8713 / #8712

**Comment by HugoMario** [comment]
thanks @lea-raya , going to try to fix this quickly.

**Comment by HugoMario** [comment]
@lea-raya ,

#8748 was merge to solve this. can you please check it when you have a chance and let me know if it was fixed?

**Comment by HugoMario** [comment]
fixe by #8748
