### ISSUE TITLE
[Kotlin] Unable to Download Files

### ISSUE THREAD

**Issue by Frozenstep** [swagger-api/swagger-codegen#8753]
##### Description

After generating our Swagger client, we were not able to download files. We found similar issue
that was fixed in the past but it doesn't seems to works for us.

##### Swagger-codegen version

2.3.1

##### Command line used for generation

swagger-codegen generate -i swagger.json -l kotlin -o SwaggerClient/

##### Steps to reproduce

Generate swagger client from a Json specification that has a GET file endpoint

##### Related issues/PRs

This is a similar change to the swift version of this issue.
https://github.com/swagger-api/swagger-codegen/issues/8699

##### Suggest a fix/enhancement

We identified a fix and will be putting in a PR shortly

**Comment by HugoMario** [comment]
thanks @Frozenstep , ping me once you made the PR and i'll help you with merging.

**Comment by Frozenstep** [comment]
@HugoMario The pull request has been added, https://github.com/swagger-api/swagger-codegen/pull/8769

**Comment by Frozenstep** [comment]
Pull request merged, seems to be fixed.
