### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by nikhiljindal** [swagger-api/swagger-codegen#876]
I want to use [Sourcegraph](https://sourcegraph.com) for swagger-codegen code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/swagger-api/swagger-codegen. (It should only take 30 seconds.)

Thank you!

**Comment by webron** [comment]
We'll look into it.

**Comment by fehguy** [comment]
no idea what it does, but i enabled it!
