### ISSUE TITLE
Add cookieParams to CodegenOperation

### ISSUE THREAD

**Issue by rbiersbach** [swagger-api/swagger-codegen#8794]
##### Description

On writing a new code generator for scala akka http server I noticed that for open api 3.0 cookies can be defined as parameters. As all other parameters, cookies should also be provided as List<CodegenParameter> in the CodegenOperation class, as they are allready added to the "allParams" variable.

##### Swagger-codegen version

3.x.x

##### Suggest a fix/enhancement
**Before:**
`  
public List<CodegenParameter> allParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> bodyParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> pathParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> queryParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> headerParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> formParams = new ArrayList<CodegenParameter>();
`
**After:**
`   
public List<CodegenParameter> allParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> bodyParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> pathParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> queryParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> headerParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> formParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> cookieParams = new ArrayList<CodegenParameter>();
`

**Comment by nataliaoliveira** [comment]
any updates on this issue?

**Comment by frantuma** [comment]
this should be duplicate of #9820 which has been fixed
