### ISSUE TITLE
json array/list of objects in html2 generated report response schema

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-codegen#8796]
_From @LorenzoTesta on September 28, 2018 14:38_

### To reproduce...

1. Go to 'https://editor.swagger.io/'
2. Click on 'Generate Client'
2. Click on 'html2'
4. Open the index.html file
5. Go to 'findPetsByStatus'
6. Go in the 200 Response schema
7. See the error

### Expected behavior
See an array of objects

_Copied from original issue: swagger-api/swagger-editor#1891_

**Comment by frantuma** [comment]
fixed in #8889
