### ISSUE TITLE
[SWIFT3, SWIFT4] Unable to generate client SDK's due to missing config template.dir

### ISSUE THREAD

**Issue by michaelmelodysmartbear** [swagger-api/swagger-codegen#8805]
##### Description

Error thrown when attempting to generate Client SDK's for Swift3 and Swift4 when using an OAS3 spec.

##### Swagger-codegen version
3.0.1

Previously working in 3.0.0

##### Steps to reproduce

Attempt to generate client sdk

##### Suggest a fix/enhancement

Issue appears to be due to a missing template dir. The following line returns null for config.templateDir(). https://github.com/swagger-api/swagger-codegen/blob/2807c714e0f7933696101821bb649a431ab43628/modules/swagger-codegen/src/main/java/io/swagger/codegen/v3/AbstractGenerator.java#L96

**Comment by frantuma** [comment]
should be fixed in swagger-api/swagger-codegen-generators#214. Closing ticket, please reopen if still experiencing issues.
