### ISSUE TITLE
Error when building 3.0.2-SNAPSHOT version

### ISSUE THREAD

**Issue by nbeucler** [swagger-api/swagger-codegen#8811]
When building  io.swagger.codegen.v3:swagger-codegen-cli:jar:3.0.2-SNAPSHOT whith maven i got the following error :

Could not resolve dependencies for project io.swagger.codegen.v3:swagger-codegen-cli:jar:3.0.2-SNAPSHOT: Could not find artifact io.swagger.codegen.v3:swagger-codegen-generators:jar:1.0.2-SNAPSHOT

I 've looked up for said artifact in maven central repository but could not find version upper 1.0.1.

Any help on this error will be appreciated.

**Comment by frantuma** [comment]
The dependency is available on [sontaype snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-generators/1.0.2-SNAPSHOT/), which is declared in [root pom](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-generators/1.0.2-SNAPSHOT/), and should be therefore picked up with no issues; do you have any custom repo declared in `settings.xml` maybe, and does this happen with a fresh clone and build from root?

**Comment by nbeucler** [comment]
I had a mirror in my settings.xml preventing call to sonatype repos... It solved my issue
