### ISSUE TITLE
[Kotlin] Kotlin swagger codegen throws exception on void responses from server

### ISSUE THREAD

**Issue by Frozenstep** [swagger-api/swagger-codegen#8823]
##### Description

When our server responded with a 204 message, but the body had no json content, an EOF exception would be thrown because it tried to deserialize json that did not exist.

##### Swagger-codegen version

master

##### Command line used for generation

swagger-codegen generate -i swagger.json -l kotlin -o SwaggerClient/

##### Steps to reproduce

Generate swagger client from a Json specification that has a void response type

##### Suggest a fix/enhancement

https://github.com/swagger-api/swagger-codegen/pull/8822

**Comment by Frozenstep** [comment]
@HugoMario

**Comment by frantuma** [comment]
fixed in #8822
