### ISSUE TITLE
[PowerShell] Automatically Build CSharp Client or Document Usage

### ISSUE THREAD

**Issue by nstr10** [swagger-api/swagger-codegen#8826]
##### Description

Attempting to generate a Powershell client but the path `$ScriptDir\csharp\SwaggerClient` does not exist - because it was not generated when I ran the java command. After some searching, I found mention of generating a C# library separately but there were no instructions about how to go about this. I generated and built the C# stuff but it doesn't have a `SwaggerClient` directory so...

Eventually I figured out that you have to generate the C# library, build it, rename its directory to `SwaggerClient`, generate the PowerShell library, create a directory named `csharp` within that one, move the C# library into that, and finally run `.\Build.ps1`

The README.md generated in the Powershell client library says all you have to do is run `.\Build.ps1` - I wonder how many folks have just given up on using this project because of that.

##### Swagger-codegen version

Latest build (2.9.1)

##### Related issues/PRs

Documentation was updated here, but it's more a clue than instructions:
https://github.com/swagger-api/swagger-codegen/commit/30a176126aa3600b6252f80b84040a1ab351c125

##### Suggest a fix/enhancement

Microsoft's PSSwagger project dynamically generates C# assemblies when needed, which seems like the easy approach for users - maybe that would be feasible here?

Otherwise, it would be nice to at least have the documentation reflect the steps required to generate the client library DLL for Powershell. Figuring out the process on my own was not something I'd wish on anyone else. If documentation is the solution, I might be able to submit a PR at some point.

**Comment by nstr10** [comment]
I ultimately gave up on using this with PowerShell after many headaches trying to get the C# client to compile. Switched to Python and generating a client for that was a whole new world of easy by comparison.

**Comment by JustinGrote** [comment]
I gave up and went to the @azure/autorest project due to this problem.

**Comment by jonas-westphal-at-banovo** [comment]
I have to push this issue, I can not find any solution.
Autorest is not working for my .yaml

**Comment by HugoMario** [comment]
Hello guys,

Sorry for this long delay, so yeam there is a lack of documentation about Powershell, unfortunately i'm not familiar with this generator nor dotnet technologies.

However i just tested this on windows 10 running the following commands:

```cmd
java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -l powershell -i https://petstore.swagger.io/v2/swagger.json -o D:\swagger-codegen\output
```
and
```cmd
 java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -l csharp -i https://petstore.swagger.io/v2/swagger.json -o D:\swagger-codegen\output\csharp\SwaggerClient
```

Then i moved to output folder  and run:
```cmd
.\Build.ps1
```

After doing this, the script runs with not problem and made the builds. So, i'm going to close this, but if there is another issue related please let me know and i work on it asap.
