### ISSUE TITLE
Generated typescript files on windows contain backslashes and caused build errors

### ISSUE THREAD

**Issue by jeremymeng** [swagger-api/swagger-codegen#8867]
##### Description

When running swagger-codegen on Windows to generate typescript client code, backslashes were used in import statements and causing build failures.

![image](https://user-images.githubusercontent.com/7583839/47585547-7461b800-d912-11e8-91c7-3117c87d5aea.png)

##### Swagger-codegen version

swagger-codegen-cli-3.0.0-20180717.153005-90.jar

##### Command line used for generation

```
e:\temp\generated>java -jar swagger-codegen-cli-3.0.0-20180717.153005-90.jar generate -i https://<endpoint>/swagger/v1/swagger.json -l typescript-angular -o .

```

**Comment by xarling** [comment]
Same as #8930

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen-generators/pull/372
