### ISSUE TITLE
Java putXxxItem() initializes null additionalProperties map incorrectly

### ISSUE THREAD

**Issue by clintfoster** [swagger-api/swagger-codegen#8869]
#### Description
When using `additionalProperties` in a Swagger 2.0 schema, the generated Java `putXxxItem()` method correctly initializes the map if it is null. But with an equivalent OpenAPI 3.0.0 schema the generated `putXxxItem()` method makes no sense: It checks if the map is null, then sets it to null (instead of constructing a HashMap).

###### Schema
```yaml
swagger: "2.0"
definitions:

  MyModel:
    properties:
      mapOfStr2Str:
        type: object
        additionalProperties:
          type: string
```
###### Good generated code
`putXxxItem()` is correct:
```java
  public MyModel putMapOfStr2StrItem(String key, String mapOfStr2StrItem) {
    if (this.mapOfStr2Str == null) {
      this.mapOfStr2Str = new HashMap<>();  // works as expected
    }
    this.mapOfStr2Str.put(key, mapOfStr2StrItem);
    return this;
  }
```

###### Schema
Same as 2.0 (above), except model is under `components/schemas` instead of `definitions`:
```yaml
openapi: "3.0.0"
components:
  schemas:

    MyModel:
      properties:
        mapOfStr2Str:
          type: object
          additionalProperties:
            type: string
```

###### Bad generated code
Same as for 2.0 except map is initialized to null if null (makes no sense):
```java
  public MyModel putMapOfStr2StrItem(String key, String mapOfStr2StrItem) {
    if (this.mapOfStr2Str == null) {
      this.mapOfStr2Str = null;  // not expected
    }
    this.mapOfStr2Str.put(key, mapOfStr2StrItem);
    return this;
  }
```
### Swagger-codegen version

`io.swagger.codegen.v3:swagger-codegen-cli:3.0.2`

### Command line used for generation

Language: Java
Config file:
```json
{
  "modelPackage"     : "org.foo",
  "serializableModel": "true",
  "dateLibrary"      : "java8",
  "java8"            : "true"
}
```

**Comment by clintfoster** [comment]
I haven't tried more recent versions of swagger-codegen, but I have verified this problem does not exist in version `4.0.0-beta2` of the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) fork.

**Comment by HugoMario** [comment]
this is already fixed in recent versions
