### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by javier-alvarez** [swagger-api/swagger-codegen#887]
This bit of json inside the swagger spec at definitions level makes the code generator crash.

,
		"Object": {
			"type": "object",
			"properties": {}
		}

Removing this from the swagger spec generates the client without any problems. It breaks for every language that I tested.

java.lang.NullPointerException
        at io.swagger.codegen.examples.XmlExampleGenerator.modelImplToXml(XmlExampleGenerator.java:87)
        at io.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:58)
        at io.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:156)
        at io.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:47)
        at io.swagger.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:58)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:781)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:351)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:325)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:153)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

**Comment by wing328** [comment]
@javier-alvarez Are you trying to create a model/object/class named "Object" ?

**Comment by javier-alvarez** [comment]
I am using https://github.com/domaindrivendev/Swashbuckle to generate the swagger spec

**Comment by webron** [comment]
@javier-alvarez - I think what @wing328 is asking is, what are you trying to represent by that model definition? It's fine that it is generated, and while it shouldn't cause an error, it may not mean what you want it to mean. This is also a potential issue with Swashbuckle, so let's try to figure this one out.

**Comment by wing328** [comment]
@javier-alvarez are you using the latest version of Swashbuckle (released 13 days ago) ? According to the author, it should have addressed the issue (https://github.com/domaindrivendev/Swashbuckle/issues/344)

ref: https://github.com/swagger-api/swagger-codegen/issues/751

**Comment by javier-alvarez** [comment]
<package id="Swashbuckle.Core" version="5.2.1" targetFramework="net451" />

I updated to this version that seems to be the latest one and I still see the empty object.

I think that this is coming from controllers with this kind of response  
public async Task<HttpResponseMessage> 

"Object":{"type":"object","properties":{}}}}

**Comment by wing328** [comment]
Do you have the swagger spec that you can share with us ?

If you remove `"properties": {}`, does the null pointer exception still occur ?

**Comment by javier-alvarez** [comment]
Yes even if you remove "properties": {}, the null still happens

You can reproduce the issue easily, adding a definition like the one above

**Comment by webron** [comment]
@javier-alvarez - regardless that the codegen shouldn't choke on such an input, it does seem Swashbuckle doesn't produce the right output for this use case (though I'm not entirely sure what `Task<HttpResponseMessage.` should be translated to). Perhaps there's room to open an issue on Swashbuckle as well. @wing328 may have a better idea regarding the correctness of the representation.

**Comment by wing328** [comment]
@javier-alvarez I'm working on a fix which seems to be able to fix the null pointer issue and generated the model files successfully.

However the code won't compile since the generated code contains a class named "Object", which is a reserved class name in C#.

I wonder if you can share more with me on how you define the response using Swashbuckle and assuming the "Object" is used as a response for an endpoint, do you really expect the endpoint to just return an "Object" (which is essentially any class in C#) ? and what does that endpoint actually return in the HTTP body? JSON? Empty body ?

**Comment by javier-alvarez** [comment]
Yes I think that Swashbuckle generates this empty Object class when the response body is empty and I just return a status code using HttpResponseMessage. Can you not call it @Object in the generated code?

**Comment by wing328** [comment]
@javier-alvarez is it more correct say that the method has a `void` return type ?

https://github.com/domaindrivendev/Swashbuckle/issues/344 contains sytnax to define a void response/return type

**Comment by javier-alvarez** [comment]
Yes I should probably use this tags in SB. Thanks

**Comment by wing328** [comment]
No problem. If the void syntax works, please close the issue.

If you still encounter the issue, we'll take another look.

**Comment by javier-alvarez** [comment]
I verified that I don't get the crash now! Thanks
