### ISSUE TITLE
Python issue : problem with api_key identification

### ISSUE THREAD

**Issue by bletail** [swagger-api/swagger-codegen#888]
Hello,

I'm trying to request swagger with an api_key by the URL way in a python generated code

When I'm requesting swagger, I use (in my web browser for example) :
***http://host:80/api/0.1/tags.json?api_key="api_key"***
But in the generated code, when I precise the api key with the method
***client = swagger.ApiClient('host/api', 'api_key', 'value-of-my-key')***
just only the request's header is changed

Here's the header generated by my python code : 
***GET /api/0.1/tags.json HTTP/1.1***
***Accept-Encoding: identity***
***Host: host***
***Accept:***
***User-Agent: Python-Swagger***
***Connection: close***
***Api_Key: value-of-my-key***
***Content-Type:***

In the swagger UI when I test a request I don't need any header's parameter which precise the api_key. Just only the URL's parameter "api_key" is used

Is there a way that my python code can use a URL's parameter "api_key" instead using a header identification ?

**Comment by wing328** [comment]
Please have a look at the configuration.py: https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/python/SwaggerPetstore-python/SwaggerPetstore/configuration.py (assuming you're using develop_2.0 branch)

It should be as simple as just storing the API key in `api_key` (assuming you're the correct security definition defined in your swagger spec)

**Comment by wing328** [comment]
@bletail does the above help? if yes, are you happy to close the issue ?

**Comment by bletail** [comment]
Yes it's working ! thank you ! I'm happy
there is maybe not enough comments or documentation or examples in the `configuration.py` file but it's fine

**Comment by jorourke** [comment]
The link in wing328's comment is broken.

**Comment by wing328** [comment]
Develop_2.0 branch (for development) has been deleted as all enhancements and bug fixes go to `master` directly. Here is the updated URL to configuration.py for Petstore sample: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/swagger_client/configuration.py
