### ISSUE TITLE
[JAVA] openapi 3.0.0 json file is not considered valid I

### ISSUE THREAD

**Issue by andsel** [swagger-api/swagger-codegen#8888]
##### Description

[JAVA] openapi 3.0.0 json file is not considered valid I got this execption:
```
[main] INFO io.swagger.parser.Swagger20Parser - reading from openapi.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from openapi.json
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:739)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

```

##### Swagger-codegen version

2.4.0-SNAPSHOT

##### Swagger declaration file content or url

I can't post it, it's private API but the start is 
```json
{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Acme Internal API",
    "description" : "Acme Internal API",
    "version" : "1.0.0"
  },
```

##### Command line used for generation

java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i email_api_def.json -l java -o /tmp/test/

##### Steps to reproduce

Create an openapi v 3.0.0 file with the root node named 'openapi'

##### Suggest a fix/enhancement

The problem is that the swagger-parser used is 1.0.36 and on method call to io.swagger.parser.Swagger20Parser.convertToSwagger() L 132

```java
            // must have swagger node set
            JsonNode swaggerNode = rootNode.get("swagger");
            if (swaggerNode == null) {
                return null;
            } else {
                ....
            }
```
The problem is that on json file it search for a node named "swagger" while in API v 3.0.0 the root node I've is "openapi". For my use case I've solved replacing the root node "openapi" -> "swagger" and the generator generated the Java files. But I think it should be adamptive.

**Comment by hkosova** [comment]
To generate code for OpenAPI 3.0 definitions you need to use Codegen v. 3 (e.g. [3.0.3-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/3.0.3-SNAPSHOT/)). Codegen 2.x supports OpenAPI 2.0 only.

**Comment by andsel** [comment]
Thank's @hkosova probably the cause is that, but the codegen I ran was from a fresh checkout that now I've dropped, so I can't grant you which version I used. Probably instead of stacktrace a more pleasant warning message like '"you are using a bad version of code gen" could be more helpful for the user.
