### ISSUE TITLE
[Python client] cannot deserialize polymorphic models

### ISSUE THREAD

**Issue by AlexInGitHub** [swagger-api/swagger-codegen#8901]
##### Description

Originally, all of the generated model's super-model are Object. No matter the model is sub-model or super-model. 
![image](https://user-images.githubusercontent.com/6847022/48249670-c9371f80-e436-11e8-9fd8-85bb21c737c2.png)

However, looks this issue is fixed recently. Currently, the sub-model's super model is not object.
![image](https://user-images.githubusercontent.com/6847022/48249696-db18c280-e436-11e8-9043-022a74ce66b2.png)

But I think it also needs to update the deserialize process in line 684 of api_client.mustache. The code looks like below
![image](https://user-images.githubusercontent.com/6847022/48249704-e2d86700-e436-11e8-9640-d5c8df177f02.png)

Since the sub-model inherints super-model's attribute, so the code believe the sub-model also has child, until get error. 

I think we can change the code like 
![image](https://user-images.githubusercontent.com/6847022/48249916-7873f680-e437-11e8-9a40-80e30ff290a8.png)

And I create a PR https://github.com/swagger-api/swagger-codegen/pull/8900

##### Swagger-codegen version

Master branch

**Comment by woz5999** [comment]
@webron @HugoMario Can someone please help figure out who is able to review and merge this mix?

**Comment by frantuma** [comment]
#8901 merged
