### ISSUE TITLE
[TYPESCRIPT][v3.0.2] Incorrect imports generated with backslash (windows 10)

### ISSUE THREAD

**Issue by vtecnica** [swagger-api/swagger-codegen#8930]
##### Description
When generating typescript-angular, the import for api and modules are generated with backslash:
E.g. 
``` typescript
import { ApiResponse } from '../model\apiResponse';
```
##### Swagger-codegen version

v.3.0.2

##### Swagger declaration file content or url
http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

java -jar swagger-codegen-cli-3.0.2.jar generate -i http://petstore.swagger.io/v2/swagger.json -l typescript-angular

##### Steps to reproduce
Download or generate swagger-codegen-cli-3.0.2.jar

java -jar swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l typescript-angular

**Comment by Maxim-Mazurok** [comment]
I confirm, getting `import { SomeDto } from '../model\someDto';` on Windows 10 with [swagger-codegen-cli-3.0.0-20180717.153005-90.jar](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180717.153005-90.jar)

**Comment by dbusacca** [comment]
Still open in 3.0.4 ...

**Comment by xarling** [comment]
In https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java the following lines: 

`supportingFiles.add(new SupportingFile("models.mustache", modelPackage().replace('.', File.separatorChar), "models.ts"));`
`supportingFiles.add(new SupportingFile("apis.mustache", apiPackage().replace('.', File.separatorChar), "api.ts"));`

replace the '.' character by the File.seperatorChar. The seperatorChar is the system-dependent default name-separator character, which is / for Unix and \ for Windows. 

Shouldn't it just be / independent of the system?

**Comment by RaduFurnea** [comment]
Any news on this?

**Comment by paulbors** [comment]
In case you don't want to change the generator and can't wait till this bug is fixed, here's a quick dirty patch for maven you could invoke post code generation and before you start building the generated code:

```XML
<plugin>
    <!-- Hook into Maven's build life cycles and execute custom build that's outside of Maven convention
            See https://maven.apache.org/plugins/maven-antrun-plugin/
    -->
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-antrun-plugin</artifactId>
    <version>${maven-antrun-plugin.version}</version>
    <dependencies>
        <dependency>
            <groupId>ant-contrib</groupId>
            <artifactId>ant-contrib</artifactId>
            <version>${ant-contrib.version}</version>
        </dependency>
    </dependencies>
    <executions>
        <!-- Default lifecycle -->
        <execution>
            <id>npm-install</id>
            <phase>process-resources</phase>
            <goals><goal>run</goal></goals>
            <configuration>
                <tasks>
                    <taskdef resource="net/sf/antcontrib/antcontrib.properties"/>
                    <condition property="isWindows"><os family="windows" /></condition>
                    <if>
                        <equals arg1="${isWindows}" arg2="true" />
                        <then>
                            <property name="npm.bin" value="npm.cmd" />
                            <!-- FIXME: Remove once issue 8930 is fixed -->
                            <echo message="Patching Swagger's default service on Windows only!" level="info" />
                            <echo message=" Remove once below bug has been fixed:" level="info" />
                            <echo message=" https://github.com/swagger-api/swagger-codegen/issues/8930" level="info" />
                            <replace file="${project.basedir}/.../generated/swagger-api/api/default.service.ts" token="\" value="/"/>
                        </then>
                        <else><property name="npm.bin" value="npm" /></else>
                    </if>
                    <available file="${ng-app.node_modules}" type="dir" property="skipNpmInstall"/>
                    <if>
                        <equals arg1="${skipNpmInstall}" arg2="true" />
                        <then>
                            <echo message="WARNING: ${ng-app.node_modules} exists, skipping npm install!" level="warning" />
                        </then>
                        <else>
                            <exec executable="${npm.bin}" dir="${ng-app.root}" failonerror="true">mvn
                                <arg value="install"/>
                            </exec>
                        </else>
                    </if>
                </tasks>
            </configuration>
        </execution>
...
```

**Comment by HugoMario** [comment]
hey @vtecnica @Maxim-Mazurok @dbusacca @xarling , i added a PR solving this issue. can you please check this when you have a chance?
