### ISSUE TITLE
[.NET] Question: Does app.swaggerhub.com use the Swagger Codegen 3.0.2 for code generation

### ISSUE THREAD

**Issue by stephenpatten** [swagger-api/swagger-codegen#8933]
Hello,

I need to use the CLI in order to customize the namespaces in our projects, and in order to do that I wanted to know which version of swagger-codegen I need to use, since I can't readily tell what the website uses.,

1) Multiple swagger libraries, 3 currently.

2) C# 4.5 Full .NET Framework, not core at the moment.

Thank you,
Stephen

**Comment by hkosova** [comment]
SwaggerHub currently uses Swagger Codegen v. 3.0.2 for OAS3 specs and v. 2.3.1 for OAS2 specs. The version numbers are listed on this page:
https://app.swaggerhub.com/help/apis/generating-code/index

By the way, for questions related to SwaggerHub specifically (such as this one) it's best to use the in-app support chat.

**Comment by stephenpatten** [comment]
Thank you.

I was able to infer usage for the c# client by poking around a bit and with a lucky guess. Here is the simplest way of doing it .

`#download the version of the cli which corresponds to your spec with powershell
Invoke-WebRequest -OutFile swagger-codegen-cli.jar http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar`

`#help with csharp
java -jar swagger-codegen-cli.jar config-help -l csharp`

 `#create config.json file to modify the default naming conventions
{
    "packageName" : "com.company.whatever",
    "modelPackage" : "com.xyz.model",
    "apiPackage" : "com.xyz.api"
}`

`#generate the code
java -jar swagger-codegen-cli.jar generate -i swagger.json -l csharp -o c:\temp\csharp -c config.json`
