### ISSUE TITLE
Incorrect objective-c

### ISSUE THREAD

**Issue by javier-alvarez** [swagger-api/swagger-codegen#896]
There is some issue with value types in the objective-c generation.

This code generated doesn't compile:

This is the parameter fromX: (BOOL) fromX

In the method is adding:

if(fromX != nil) {
        queryParams[@"fromX"] = fromX;
    }

Implicit conversion of 'BOOL' (aka 'signed char') to 'id' is disallowed with ARC

**Comment by javier-alvarez** [comment]
Also:

 NSAssert(fromX != nil, @"Missing the required parameter `fromX` when calling X");

is a warning and crashes the app

**Comment by wing328** [comment]
@javier-alvarez do you have the swagger spec that I can help repeat the issue ?

**Comment by javier-alvarez** [comment]
```json
"/v1/mycall": {
			"post": {
				"tags": [
					"mything"
				],
				"operationId": "mycall_PostImage",
				"consumes": [
					"application/json",
					"text/json",
					"application/xml",
					"text/xml",
					"application/x-www-form-urlencoded"
				],
				"produces": [
					"application/json",
					"text/json",
					"application/xml",
					"text/xml"
				],
				"parameters": [
					{
						"name": "deviceId",
						"in": "query",
						"required": true,
						"type": "string"
					},
					{
						"name": "fromX",
						"in": "query",
						"required": true,
						"type": "boolean"
					},
					{
						"name": "imageBase64",
						"in": "body",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "saveResults",
						"in": "query",
						"required": false,
						"type": "boolean"
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/myresult"
						}
					}
				},
				"deprecated": false
			}
		},
```

**Comment by javier-alvarez** [comment]
I also found another issue. The imageBase64 string is not passed in the body correctly. For some reason when it tries to serialize the string to json it returns null in objective-c

**Comment by wing328** [comment]
Thanks, will troubleshoot using it

**Comment by javier-alvarez** [comment]
Another problem with objective-c. If a property of a definition is called "description" this conflicts with the NSObject description and it doesnt fail at compile time but at run time the description is something different. Do you know how long it could take to fix this things? I really need this fixed. Many thanks

**Comment by wing328** [comment]
I'm not a ObjC expert so I can't provide you any ETA.

Looking at the definition, my understanding is that the method will send (upload) the image to the server. Have you considered using the `file` type for uploading the image ?

Under `consumes`, it supports 5 different MIME type. Can the endpoint really accept so many different types for image upload ?

**Comment by wing328** [comment]
@javier-alvarez do you mind testing the latest develop_2.0 to see if you still encounter the issues ?

**Comment by wing328** [comment]
@javier-alvarez we're closing this issue since we've not heard from you. Please open a new issue if needed.
