### ISSUE TITLE
Swagger code-gen: typescript-node vs. nodejs-server

### ISSUE THREAD

**Issue by bravobobo** [swagger-api/swagger-codegen#8973]
##### Description

Hi Guys, 

I'm pretty new in Swagger code-gen, I'm trying to generate restful sdk for NodeJS

Question: What's the difference between TypeScript-node and nodejs-server?

Both are found in help script.

Thanks!

**Comment by bravobobo** [comment]
@wing328

**Comment by wing328** [comment]
@bravobobo Thanks for tagging me but I'm no longer involved in this project. I hope others will be able to help you out. Good luck.

**Comment by bravobobo** [comment]
thanks @wing328, still appreciate your comment :)
