### ISSUE TITLE
[JavaScript] New generator options and template improvements

### ISSUE THREAD

**Issue by demonfiddler** [swagger-api/swagger-codegen#8988]
##### Description

I've recently developed some new generator options and associated template improvements for the **OpenAPITools/openapi-generator** JAX-RS/CXF server generator, including the ability to generate random test data and serve it up from the generated CXF services, with the additional option of saving/loading the data from a file - see https://github.com/OpenAPITools/openapi-generator/issues/1158. Hitherto the service implementation methods were essentially empty stubs - with this option they can be fully functional services that actually return syntactically valid (if static) data. The PR#https://github.com/OpenAPITools/openapi-generator/pull/1879 is pending review.

SO... in the JavaScript world I've also added a related option to the **swagger-api/swagger-codegen** JavaScript client generator to enable the generated Mocha tests to read the same test data file format and use the data when invoking the service and to compare what the service returns with the expected response. As an alternative approach to loading the test data from a file, I've also made some test template enhancements to support deep programmatic validation of service response values - previously, the Mocha spec files were essentially empty stubs with no assertions and it was a lot of work to populate them. I've also fixed a couple of bugs (including https://github.com/swagger-api/swagger-codegen/issues/8849) along the way.

This Enhancement Issue is to enable me to make this contribution (I already have the necessary legal approval, having done so before).

##### Swagger-codegen version

2.4.0-SNAPSHOT. This is (mostly) an enhancement.

##### Swagger declaration file content or url

n/a

##### Command line used for generation

This enhancement will add the following JavaScript generator options:
- loadTestDataFromFile: Load test data from a JSON file (default false)
- testDataFile: JSON file to contain test data (ignored unless loadTestDataFromFile=true, default ${output}/test/test-data.json)
- preserveLeadingParamChar: Preserves leading $ and _ characters in parameter names. (default false) [Currently they get stripped out, not sure why, and this will remain the default behaviour. This was originally necessitated by the fact that the Java generators do not strip leading $ and _ characters from parameter names, but it should be a useful option to some users especially where **ODATA compliance** is important.]

##### Steps to reproduce

Run bin/javascript-override-default-config-petstore.sh to generate an example that uses the new options.

##### Related issues/PRs

This contribution builds on my previous contributions to the JavaScript Swagger-Codegen generator, see #2258 and related.

##### Suggest a fix/enhancement

I have raised PR#https://github.com/swagger-api/swagger-codegen/pull/9054 with the enhancement and some associated fixes.

**Comment by demonfiddler** [comment]
I raised PR https://github.com/swagger-api/swagger-codegen/pull/9054 that fixes this issue. Please may I have a code review?

**Comment by HugoMario** [comment]
hey @demonfiddler , i'll take a time next week for reviewing, thanks!

**Comment by demonfiddler** [comment]
Thank you @HugoMario!

**Comment by demonfiddler** [comment]
@HugoMario any joy with that code review?

**Comment by demonfiddler** [comment]
@HugoMario many thanks for the PR merge - much appreciated!

**Comment by HugoMario** [comment]
thanks to you @demonfiddler for PR !
