### ISSUE TITLE
parameter named `_` causes invalid variable names in java client

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#900]

**Comment by wing328** [comment]
@fehguy is that because the parameter name is written as "_" in the spec ? in other words, the generator should throw an exception if the parameter name is invalid (e.g. _, __ , etc) ?

**Comment by fehguy** [comment]
yes, it is valid to have `_` in the spec.  but the generator should not fail.  We can keep `baseName` as `_`

**Comment by fehguy** [comment]
@wing328 the fix in here is definitely not comprehensive for all invalid names.

**Comment by wing328** [comment]
@fehguy gotcha. In my opinion, the REST API owner should provide a better name instead of `_`

**Comment by fehguy** [comment]
I totally agree, I only found this because one didn't and per the spec, it is technically valid.

**Comment by wing328** [comment]
OK. I'll submit a PR later to update other codegens to handle this special case.
