### ISSUE TITLE
High CVE vulnerability

### ISSUE THREAD

**Issue by mlushpenko** [swagger-api/swagger-codegen#9011]
##### Description

![image](https://user-images.githubusercontent.com/2006610/50399516-4c5ecb80-0780-11e9-9d3e-19017596c645.png)

##### Swagger-codegen version

Your latest release 3.0.3 is affected and all previous as well I guess

##### Related issues/PRs

https://github.com/FasterXML/jackson-databind/issues/2058

##### Suggest a fix/enhancement

Upgrade jackson version https://github.com/swagger-api/swagger-codegen/blob/master/pom.xml#L943

**Comment by mlushpenko** [comment]
Looks like 2.9.8 is better update as there are a few more security issues followed up https://github.com/FasterXML/jackson-databind/issues/2097

**Comment by 0ktavandi** [comment]
nice0ne

**Comment by frantuma** [comment]
this has been fixed in #9584
