### ISSUE TITLE
[JAVA] Spring RestTemplate Client should Use "org.springframework.core.io.Resource" for Swagger "file" type

### ISSUE THREAD

**Issue by lwoerdeman** [swagger-api/swagger-codegen#9025]
##### Description

The Swagger Rest-Template should use the Resource class for the Swagger "file" type. This has already been resolved on the server side with this pull request https://github.com/swagger-api/swagger-codegen/pull/5181. However, it needs updated on the client side. This will allow the ResourceHttpMessageConverter to be used when retrieving files. Currently, there is no built in rest template support for the "java.io.File" class being used now.

This is the error you will get when returning an applicaiton/octet-stream MultipartFile from the server.
org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class java.io.File] and content type [application/octet-stream]

##### Swagger-codegen version

2.4.0

##### Swagger declaration file content or url

`org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class java.io.File] and content type [application/octet-stream]`

##### Command line used for generation

`def config = new CodegenConfigurator()
        config.setInputSpec(swaggerInputFile)
        config.setOutputDir("${swaggerOutputDir.path}/java")
        config.setLang('java')
        config.setArtifactId('datalake-client')
        config.setArtifactVersion(version.toString())
        config.setGroupId(project.property("group").toString())
        config.setAdditionalProperties([
                'dateLibrary'   : 'java8',
                'library'       : 'resttemplate',
                'localVariablePrefix' : 'local'
        ])
        new DefaultGenerator().opts(config.toClientOptInput(), ).generate()`

##### Steps to reproduce

Use Swagger code gen to generate a client that receives data as a File type with an application/octet-stream content type. It will throw an error finding no suitable HttpMessageConverter

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/pull/5181

##### Suggest a fix/enhancement

Add a typeMapping/importMapping in JavaClientCodegen.java for resttemplate
`else if("resttemplate".equals(getLibrary())) {
            typeMapping.put("file", "Resource");
            importMapping.put("Resource", "org.springframework.core.io.Resource");
            additionalProperties.put("jackson", "true");
            supportingFiles.add(new SupportingFile("auth/Authentication.mustache", authFolder, "Authentication.java"));
}`

**Comment by CHITOU** [comment]
Hello, a simple solution is to add in your configuration : 
<typeMappings>		                
       <typeMapping>File=org.springframework.core.io.Resource</typeMapping>
</typeMappings>

**Comment by Hollerweger** [comment]
Adding the typeMapping results in a compilation error:
`java: no suitable constructor found for FileSystemResource(org.springframework.core.io.Resource)`

**Comment by CHITOU** [comment]
Hope this can help you. My full configuration using openapi-generator-maven-plugin version 3.3.4 with a java 11 project is below : 

`<execution>
	<id>generate-sources-client</id>
	<phase>generate-sources</phase>
	<goals>
		<goal>generate</goal>
	</goals>
	<configuration>
		<inputSpec>${project.basedir}/../../api/v1/api.yml</inputSpec>
		<modelPackage>api.v1.client.model</modelPackage>
		<apiPackage>api.v1.client</apiPackage>
		<language>java</language>
		<library>resttemplate</library>
		<generateApiDocumentation>true</generateApiDocumentation>
		<generateModelDocumentation>true</generateModelDocumentation>
		<generateApiTests>false</generateApiTests>
		<typeMappings>
            <typeMapping>File=org.springframework.core.io.Resource</typeMapping>
        </typeMappings>
		<configOptions>
			<sourceFolder>src/gen/java/main</sourceFolder>
			<interfaceOnly>true</interfaceOnly>
			<dateLibrary>java8-localdatetime</dateLibrary>
			<java8>true</java8>
			<serializableModel>true</serializableModel>
			<generateSupportingFiles>true</generateSupportingFiles>
		</configOptions>
	</configuration>
</execution>`

**Comment by ips219** [comment]
> Hope this can help you. My full configuration using openapi-generator-maven-plugin version 3.3.4 with a java 11 project is below :
> 
> `<execution> <id>generate-sources-client</id> <phase>generate-sources</phase> <goals> <goal>generate</goal> </goals> <configuration> <inputSpec>${project.basedir}/../../api/v1/api.yml</inputSpec> <modelPackage>api.v1.client.model</modelPackage> <apiPackage>api.v1.client</apiPackage> <language>java</language> <library>resttemplate</library> <generateApiDocumentation>true</generateApiDocumentation> <generateModelDocumentation>true</generateModelDocumentation> <generateApiTests>false</generateApiTests> <typeMappings> <typeMapping>File=org.springframework.core.io.Resource</typeMapping> </typeMappings> <configOptions> <sourceFolder>src/gen/java/main</sourceFolder> <interfaceOnly>true</interfaceOnly> <dateLibrary>java8-localdatetime</dateLibrary> <java8>true</java8> <serializableModel>true</serializableModel> <generateSupportingFiles>true</generateSupportingFiles> </configOptions> </configuration> </execution>`

I also have same problem as @Hollerweger  (openapi-generator-maven-plugin 5.0.0 & Java 11) so to fix FileSystemResource problem templates must be also modified... As WO I added a [MessageConverter](https://github.com/benetech/daisy-pipeline2-client/blob/master/src/main/java/org/benetech/pipeline/client/FileHttpMessageConverter.java) to the RestTemplate used for the generated ApiClient

**Comment by lwoerdeman** [comment]
Given all of the current workarounds posted on this issue, I think I'll close this issue. Thank you all for your input.
