### ISSUE TITLE
Marven doesn't have latest binary build

### ISSUE THREAD

**Issue by JesseKPhillips** [swagger-api/swagger-codegen#9027]
##### Description

The marven repo does not contain the latest 3.0 builds.

http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/

##### Swagger-codegen version

Not because there is no way to build this on Windows.

##### Steps to reproduce

Visit the URL and see the builds don't exist.

##### Suggest a fix/enhancement

Provide the binary builds like you use to because this ecosystem sucks.

**Comment by frantuma** [comment]
codegen v3 builds since release 3.0.0 have changed group id and are available at http://central.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/
