### ISSUE TITLE
Help Wanted Swagger code generation c# restsharp

### ISSUE THREAD

**Issue by pratik8490** [swagger-api/swagger-codegen#9041]
##### Description

In swagger generated code for c#,  urlencode method is declared using restsharp.contrib namespace but that namespace is not available in new restsharp nuget package and also there is one change needed for request.addfile method to add content length when  action<stream> is added in code. 

##### Swagger-codegen version
Not sure about version, I am generating code online using this editor.

https://editor.swagger.io/

##### Swagger declaration file content or url
http://petstore.swagger.io/v2

##### Suggest a fix/enhancement

Both issue can be fixed by replacing lines mentioned below in client folder and apiclient file.

First Change
Line no 92 
`                request.AddFile(param.Value.Name, param.Value.Writer, param.Value.FileName, param.Value.ContentType);`

please change it to
`                request.AddFile(param.Value.Name, param.Value.Writer, param.Value.FileName, param.Value.ContentLength, param.Value.ContentType);`

Second Change
Line no 119 
`return RestSharp.Contrib.HttpUtility.UrlEncode(str);`
please change it to 
`return HttpUtility.UrlEncode(str);`

as we can use httputility from system.web as well.

**Comment by flyrev** [comment]
Any update on this? I'm using 2.2.3 and it's still not generating what @pratik8490 is suggesting.

**Comment by VladCananau** [comment]
That's because the generated code is asking for the RestSharp.Net2 package (which seems a fork of RestSharp).

**Comment by iquirino** [comment]
Why use a fork using newtonsoft.json version 4?..

**Comment by alexeyzimarev** [comment]
RestSharp maintainer is here. Let's talk, happy to help.

**Comment by mswilson4040** [comment]
I'm hitting this same issue:

**ApiClient.cs**
```
// add file parameter, if any
foreach(var param in fileParams)
{
    request.AddFile(param.Value.Name, param.Value.Writer, param.Value.FileName, param.Value.ContentType);
}
```

It looks like it's missing a ContentLength property. Changing it to this resolves it:

```
// add file parameter, if any
foreach(var param in fileParams)
{
    request.AddFile(param.Value.Name, param.Value.Writer, param.Value.FileName, param.Value.ContentLength, param.Value.ContentType);
}
```

**Comment by HugoMario** [comment]
this has been covered by #10372

**Comment by smargoli2** [comment]
This is still an issue for me. I'm using version 2.4.28 of the swagger-codegen-cli.jar.

**Comment by iustin94** [comment]
I also get this issue, using the swagger codegenerator v3
