### ISSUE TITLE
[HTML] OAS3.0 Error generating docs - Missing body param - "Uncaught SyntaxError: Unexpected token ;"

### ISSUE THREAD

**Issue by tagliala** [swagger-api/swagger-codegen#9056]
##### Description

With OpenAPI 3.0, I was expecting to see the body param as it happened before in version 2.0

##### Swagger-codegen version

Version 3.0.3.

Would like to test  3.0.4-SNAPSHOT, but it didn't compile.

This is a regression from version 2

##### Swagger declaration file content or url

```yaml
openapi: 3.0.0
info:
  description: |
    This is a sample Petstore server.  You can find 
    out more about Swagger at 
    [http://swagger.io](http://swagger.io) or on 
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0-oas3"
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      operationId: addPet
      responses:
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      requestBody:
        $ref: '#/components/requestBodies/Pet'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'http://localhost/Petstore/1.0.0'
components:
  requestBodies:
    Pet:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
      description: Pet object that needs to be added to the store
      required: true
  schemas:
    Pet:
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: Pet
```

##### Command line used for generation

swagger-codegen generate -i test.yaml  -l html2

##### Steps to reproduce

1. Run `swagger-codegen generate -i test.yaml  -l html2`
3. Open the generated file
4. See missing Body params and javascript errors in the console

##### Related issues/PRs

n/a

##### Suggest a fix/enhancement

Maybe the following screenshots will help you understanding the issue

![image](https://user-images.githubusercontent.com/556268/50843066-4cf28700-1368-11e9-86df-3f3451162eda.png)

![image](https://user-images.githubusercontent.com/556268/50843215-8c20d800-1368-11e9-86f6-5b45008fdf27.png)

**Comment by tagliala** [comment]
Also found this in the repository: https://github.com/swagger-api/swagger-codegen/blob/3.0.0/samples/html2/index.html#L1200

**Comment by tagliala** [comment]
Ok, I've managed to understand how the code is organized. 😅 

swagger-api/swagger-codegen-generators#247

**Comment by frantuma** [comment]
Yes you're right, also about contributing guidelines which will be updated (as usual, any contribution welcome).  Would close this ticket as duplicate of https://github.com/swagger-api/swagger-codegen-generators/issues/247

**Comment by tagliala** [comment]
Sure, thanks!

I'm closing here as a duplicate of swagger-api/swagger-codegen-generators#247

If the empty body param does not depend on that issue, I will reopen a new issue in the other repository

> also about contributing guidelines which will be updated (as usual, any contribution welcome)

will try to submit a PR
