### ISSUE TITLE
Run asp.net core server in Visual Studio 2017

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-codegen#9068]
_From @sergio-alifano on January 3, 2019 15:32_

### Screenshots

![image](https://user-images.githubusercontent.com/37305363/50645773-f20cfa00-0f39-11e9-9614-3abde6b6eecc.png)

### How can we help?

I'm using the editor.swagger.io **Live demo** to generate an asp.net core server from the **Petstore** sample yaml file. 
When I try to load the sln file using **Visual Studio 2017** it says that the file cannot be loaded. (0 project).
Running the `.build.bat` file it works ok though.

I was wondering if there is a way to open the solution file using Visual Studio. 
Thanks.

_Copied from original issue: swagger-api/swagger-editor#1924_

**Comment by hkosova** [comment]
Looks like the same issue as #7945.
