### ISSUE TITLE
Cannot mvn package anymore after the last Fetch of developer 2.0

### ISSUE THREAD

**Issue by lakeba** [swagger-api/swagger-codegen#907]
This happens on Windows platform.

Tests in error:
(..)ould convert a simple php model(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert a model with list property(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert a model with a map property(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert a model with complex property(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert a model with complex list property(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert a model with complex map property(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert an array model(php.PhpModelTest): Unexpected internal error near index 2
(..)ould convert an map model(php.PhpModelTest): Unexpected internal error near index 2

**Comment by wing328** [comment]
so the error only occurred on Windows but not Mac ? Did you get the error in master or develop_2.0 branch ?

**Comment by lakeba** [comment]
Yes occurred only in windows.

Happens in developer 2.0 branch

Giuseppe

On Tuesday, 23 June 2015, wing328 <notifications@github.com> wrote:

> so the error only occurred on Windows but not Mac ? Did you get the error
> in master or develop_2.0 branch ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-codegen/issues/907#issuecomment-114411546>
> .
>


-- 
Giuseppe procelli

**Comment by wing328** [comment]
My guess is that it's due to https://github.com/swagger-api/swagger-codegen/pull/865. I'll look into it and submit a PR if it's confirmed the case.

**Comment by wing328** [comment]
Submitted #908 to fix it. Please help perform a test.
