### ISSUE TITLE
Parameter items is null

### ISSUE THREAD

**Issue by galagar** [swagger-api/swagger-codegen#909]
When parameter has type value as "array" and items has the value of invalid format then item object itself return as null. It would be better to skip the format not the  items object as a whole.

Example :
```js
 {
in: "query",
name: "item",
type: "array",
collectionFormat: "multi",
description: "test",
items: {
type: "string",
format: "character"
}
}
```

**Comment by webron** [comment]
In 2.0, any string value to the format field is a valid value, whether the codegen knows what to do with it or not. In general, we should add an extension mechanism to allow handling of custom formats.

**Comment by fehguy** [comment]
Parser now has fallbacks for unexpected formats, which will address this.  Please retry with master of codegen.
