### ISSUE TITLE
[JAVA] generation fails with java.lang.StackOverflowError

### ISSUE THREAD

**Issue by radzionkow** [swagger-api/swagger-codegen#9107]
##### Description

When I'm trying to generate code with swagger-codegen-cli for java language it fails with:

`Exception in thread "Thread-1" java.lang.StackOverflowError
        at io.swagger.codegen.v3.CodegenModel.hashCode(CodegenModel.java:161)
        at java.util.AbstractList.hashCode(AbstractList.java:541)
        at io.swagger.codegen.v3.CodegenModel.hashCode(CodegenModel.java:165)
        at io.swagger.codegen.v3.CodegenModel.hashCode(CodegenModel.java:164)`

I belive it's related only to java generator since for example php generation works just fine.

##### Swagger-codegen version

v3.0.4, build from source on Ubuntu 18.10, openjdk version "1.8.0_191"

##### Swagger declaration file content or url

https://developer.allegro.pl/swagger.yaml

https://editor.swagger.io/ showed error for that file, but whenever I corrected it or not, error persists - seems it's not related to that error.

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l java -o java_client`

Doesn't seem to be library related, tried with default and with resteasy, same results.

##### Steps to reproduce

Just try do generate it with above command.

**Comment by gravelld** [comment]
I think this has already been fixed: https://stackoverflow.com/a/57578579/28190

**Comment by frantuma** [comment]
Thanks! closing as fixed
