### ISSUE TITLE
[Python] KeyError in api_client

### ISSUE THREAD

**Issue by nitrocode** [swagger-api/swagger-codegen#9123]
##### Description

Original ticket: https://github.com/rapid7/vm-console-client-python/issues/17

I generate python code from insightvm's api.json 

##### Swagger-codegen version

3.0.4

##### Swagger declaration file content or url

Full json piped to jq. Curl request requires referer and user agent headers.

```
curl 'https://help.rapid7.com/insightvm/en-us/api/api.json' -H 'Referer: https://help.rapid7.com/insightvm/en-us/api/index.html' -H 'User-Agent: Mozilla/5.0' --compressed | jq . | less
```

Example. There is an empty discriminator and I believe this causes the key error.

```
  "definitions": {
    "Account": {
      "type": "object",
      "discriminator": "",
      "properties": {
        "service": {
          "type": "string"
        }
      },
      "description": ""
    },
```

##### Command line used for generation

Download json. Curl request requires referer and user agent headers.
```
curl -s 'https://help.rapid7.com/insightvm/en-us/api/api.json' -H 'Referer: https://help.rapid7.com/insightvm/en-us/api/index.html' -H 'User-Agent: Mozilla/5.0' --compressed -o api.json
```
Generate
```
swagger-codegen generate -i api.json -l python -o /tmp/insightvm
```

##### Steps to reproduce

Get the json, generate the code, and run the python from the original issue https://github.com/rapid7/vm-console-client-python/issues/17

##### Related issues/PRs

https://github.com/rapid7/vm-console-client-python/issues/17

##### Suggest a fix/enhancement

A try/except solved it for me here:

https://github.com/rapid7/vm-console-client-python/blob/master/rapid7vmconsole/api_client.py#L622-L624

            klass_name = instance.get_real_child_model(data)
            if klass_name:
                instance = self.__deserialize(data, klass_name)

turns into

            try:
                klass_name = instance.get_real_child_model(data)
                if klass_name:
                    instance = self.__deserialize(data, klass_name)
            except KeyError:
                pass

**Comment by HugoMario** [comment]
No sure if this is actually a codegen error. However from the time this issue was file, the python generator has been modified multiple times. Going to close this if the key error is still present, please let me kow.
