### ISSUE TITLE
[Python] Markdown broken in README and entire README on a single line in every file

### ISSUE THREAD

**Issue by nitrocode** [swagger-api/swagger-codegen#9124]
##### Description

Issues
* markdown is broken in README.md
* README.md is outputted on a single line in the comments at the top of every file e.g. `swagger_client/__init__.py`

##### Swagger-codegen version

3.0.4 and both of the above issues seem like regressions when compared to 2.4.0

##### Swagger declaration file content or url

Please see https://github.com/swagger-api/swagger-codegen/issues/9123

##### Command line used for generation

Please see https://github.com/swagger-api/swagger-codegen/issues/9123

##### Steps to reproduce

Please see https://github.com/swagger-api/swagger-codegen/issues/9123

##### Related issues/PRs

Please see https://github.com/swagger-api/swagger-codegen/issues/9123

**Comment by HugoMario** [comment]
hello @nitrocode, is it possible you share the input file you're using to get this issue?

**Comment by nitrocode** [comment]
From #9123, the input file is https://help.rapid7.com/insightvm/en-us/api/api.json

**Comment by HugoMario** [comment]
I try to reproduce this again but seems ok. In case it is still present, please let me know.
