### ISSUE TITLE
ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN

### ISSUE THREAD

**Issue by edson-19** [swagger-api/swagger-codegen#9132]
##### Description
Not able to generate java client:
ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN

module java clasess are not generated.

##### Swagger-codegen version

2.4.1
3.0.4

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate  -i C:/swagger/alip-agent-swagger.json -l java -o samples/client/alip-agent/java

[main] INFO io.swagger.parser.Swagger20Parser - reading from C:/swagger/alip-agent-swagger.json
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting pom.xml as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\\pom.xml
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting README.md as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\\README.md
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting build.gradle as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\\build.gradle
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting build.sbt as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\\build.sbt
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting settings.gradle as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\\settings.gradle
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting gradle.properties as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\\gradle.properties
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting AndroidManifest.xml as the file already exists in c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\AndroidManifest.xml
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: get /agents/{id}/summary. Renamed to auto-generated operationId: agentsIdSummaryGet
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] ERROR io.swagger.codegen.languages.AbstractJavaCodegen - No Type defined for Property io.swagger.models.properties.UntypedProperty@0
[main] ERROR io.swagger.codegen.DefaultCodegen - String to be sanitized is null. Default to ERROR_UNKNOWN
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java\io\swagger\client\api\DefaultApi.java
[main] INFO io.swagger.codegen.DefaultGenerator - File exists. Skipped overwriting c:\swagger-codegen-2.4.1\samples\client\alip-agent\java/src\test\java/io/swagger/client/api\DefaultApiTest.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\docs\\DefaultApi.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\.travis.yml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\ApiClient.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\StringUtil.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client/auth\HttpBasicAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client/auth\ApiKeyAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client/auth\OAuth.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client/auth\OAuthFlow.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\gradlew
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\gradlew.bat
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\gradle\wrapper\gradle-wrapper.properties
[main] INFO io.swagger.codegen.DefaultGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\gradle\wrapper\gradle-wrapper.jar
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\git_push.sh
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\.gitignore
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\ApiException.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\Configuration.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\Pair.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client/auth\Authentication.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\ApiCallback.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\ApiResponse.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\JSON.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\ProgressRequestBody.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\ProgressResponseBody.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\src\main\java/io/swagger/client\GzipRequestInterceptor.java
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\swagger-codegen-2.4.1\samples\client\alip-agent\java\.swagger-codegen\VERSION

**Comment by edson-19** [comment]
input file: alip-agent-swagger.json

{
  "swagger": "2.0",
  "info": {
    "title": "alip-agent",
    "description": "ALIP Agent Summary",
    "version": "1.0"
  },
  "host": "alipmule.eastus.cloudapp.azure.com",
  "basePath": "/alip-agents",
  "schemes": [
    "http"
  ],
  "paths": {
    "/agents/{id}/summary": {
      "get": {
        "description": "Get Agent Summary from ALIP",
        "parameters": [
          {
            "name": "client_id",
            "required": true,
            "in": "query",
            "type": "string"
          },
          {
            "name": "client_secret",
            "required": true,
            "in": "query",
            "type": "string"
          },
          {
            "name": "id",
            "description": "Agent Number",
            "required": true,
            "in": "path",
            "default": "131",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "x-amf-mediaType": "application/json",
            "schema": {
              "example": {
                "TXLife": {
                  "TXLifeResponse": {
                    "TransRefGUID": "acbd73e3-e17f-5f66-e320-226f8e4b7c7d",
                    "TransExeDate": "2017-09-14",
                    "TransExeTime": "01:34:20",
                    "OLifE": {
                      "Party": {
                        "@id": "Party_1",
                        "EMailAddress": {
                          "EMailType": {
                            "@tc": "2",
                            "$": "Personal"
                          },
                          "AddrLine": "lisa.spencer@lifeins.com"
                        },
                        "PartySysKey": 35,
                        "FullName": "Lisa Spencer",
                        "Address": [
                          {
                            "LastUpdate": "2017-09-11",
                            "Zip": 10111,
                            "Line3": null,
                            "EndDate": "2999-12-31",
                            "StartDate": "2014-01-07",
                            "LastUpdateTime": "02:21:16-04:00",
                            "Line2": "14th Floor",
                            "AddressCountryTC": {
                              "@tc": "1",
                              "$": "USA"
                            },
                            "City": "NEW YORK",
                            "AddressSysKey": 2,
                            "AddressState": "New York",
                            "Line1": "449 Fifth Avenue",
                            "@id": "Address_1",
                            "AddressTypeCode": {
                              "@tc": "2",
                              "$": "Business"
                            },
                            "AddressStateTC": {
                              "@tc": "37",
                              "$": "NY"
                            },
                            "AddressCountry": "United States of America"
                          },
                          {
                            "Zip": "08837",
                            "AddressCountry": "United States of America",
                            "LastUpdateTime": "02:43:54-04:00",
                            "Line2": null,
                            "@id": "Address_2",
                            "StartDate": "2014-01-09",
                            "City": "Edison",
                            "AddressTypeCode": {
                              "@tc": "1",
                              "$": "Home"
                            },
                            "EndDate": "2999-12-31",
                            "Line3": null,
                            "AddressSysKey": 52466,
                            "LastUpdate": "2017-09-12",
                            "AddressCountryTC": {
                              "@tc": "1",
                              "$": "USA"
                            },
                            "AddressStateTC": {
                              "@tc": "35",
                              "$": "NJ"
                            },
                            "AddressState": "New Jersey",
                            "Line1": "500 Main Street Y"
                          }
                        ],
                        "OLifEExtension": {
                          "VendorCode": 33,
                          "Holding": {
                            "id": "Holding_1",
                            "HoldingTypeCode": {
                              "tc": 2,
                              "content": "Policy"
                            },
                            "HoldingName": "#839438asdfghjk",
                            "Policy": {
                              "id": "Policy_1",
                              "PolNumber": 839438,
                              "ProductType": {
                                "tc": 1,
                                "content": "Standard Flexible VUL"
                              },
                              "isTrad": false
                            }
                          }
                        },
                        "GovtIDTC": {
                          "@tc": "1",
                          "$": "Social Security Number US"
                        },
                        "GovtID": 126319308,
                        "Person": {
                          "MiddleName": "",
                          "FirstName": "Lisa",
                          "Gender": {
                            "@tc": "2",
                            "$": "Female"
                          },
                          "LastName": "Spencer",
                          "BirthDate": "1900-01-01"
                        },
                        "Phone": [
                          {
                            "PhoneTypeCode": {
                              "@tc": "1",
                              "$": "Home"
                            },
                            "DialNumber": null
                          },
                          {
                            "PhoneTypeCode": {
                              "@tc": "12",
                              "$": "Mobile"
                            },
                            "AreaCode": 111,
                            "DialNumber": 1111111
                          },
                          {
                            "PhoneTypeCode": {
                              "@tc": "2",
                              "$": "Other"
                            },
                            "AreaCode": 456,
                            "DialNumber": 7897656
                          }
                        ]
                      }
                    },
                    "TransResult": {
                      "ResultCode": {
                        "@tc": "1",
                        "$": "Success"
                      }
                    },
                    "TransType": {
                      "@tc": "204",
                      "$": "Agent Party Inquiry"
                    }
                  }
                }
              },
              "type": "object",
              "additionalProperties": true,
              "properties": {
                "TXLife": {
                  "type": "object",
                  "additionalProperties": true,
                  "properties": {
                    "TXLifeResponse": {
                      "type": "object",
                      "additionalProperties": true,
                      "properties": {
                        "OLifE": {
                          "type": "object",
                          "additionalProperties": true,
                          "properties": {
                            "Party": {
                              "type": "object",
                              "additionalProperties": true,
                              "properties": {
                                "Address": {
                                  "type": "array",
								  "additionalProperties": true,
								  "items": {
									"type": "object",
									"properties": {
									"AddressCountry": {
									  "type": "string"
									},
									"AddressCountryTC": {
									  "properties": {
										"content": {
										  "type": "string"
										},
										"tc": {
										  "type": "integer"
										}
									  },
									  "type": "object",
									  "additionalProperties": true
									},
									"AddressKey": {
									  "type": "integer"
									},
									"AddressState": {
									  "type": "string"
									},
									"AddressStateTC": {
									  "type": "object",
									  "additionalProperties": true,
									  "properties": {
										"content": {
										  "type": "string"
										},
										"tc": {
										  "type": "integer"
										}
									  }
									},
									"AddressTypeCode": {
									  "type": "object",
									  "additionalProperties": true,
									  "properties": {
										"content": {
										  "type": "string"
										},
										"tc": {
										  "type": "integer"
										}
									  }
									},
									"City": {
									  "type": "string"
									},
									"EndDate": {
									  "type": "string"
									},
									"LastUpdate": {
									  "type": "string"
									},
									"LastUpdateTime": {
									  "type": "string"
									},
									"Line1": {
									  "type": "string"
									},
									"Line2": {
									  "type": "string"
									},
									"Line3": {
									  "type": "string"
									},
									"StartDate": {
									  "type": "string"
									},
									"Zip": {
									  "type": "integer"
									},
									"id": {
									  "type": "string"
									}
									}
								  }
								},
                                "EMailAddress": {
                                  "type": "object",
                                  "additionalProperties": true,
                                  "properties": {
                                    "AddrLine": {
                                      "type": "string"
                                    },
                                    "EMailType": {
                                      "type": "object",
                                      "additionalProperties": true,
                                      "properties": {
                                        "content": {
                                          "type": "string"
                                        },
                                        "tc": {
                                          "type": "integer"
                                        }
                                      }
                                    }
                                  }
                                },
                                "FullName": {
                                  "type": "string"
                                },
                                "GovtID": {
                                  "type": "integer"
                                },
                                "GovtIDTC": {
                                  "type": "object",
                                  "additionalProperties": true,
                                  "properties": {
                                    "content": {
                                      "type": "string"
                                    },
                                    "tc": {
                                      "type": "integer"
                                    }
                                  }
                                },
                                "PartyKey": {
                                  "type": "integer"
                                },
                                "Person": {
                                  "type": "object",
                                  "additionalProperties": true,
                                  "properties": {
                                    "BirthDate": {
                                      "type": "string"
                                    },
                                    "FirstName": {
                                      "type": "string"
                                    },
                                    "Gender": {
                                      "type": "object",
                                      "additionalProperties": true,
                                      "properties": {
                                        "content": {
                                          "type": "string"
                                        },
                                        "tc": {
                                          "type": "integer"
                                        }
                                      }
                                    },
                                    "LastName": {
                                      "type": "string"
                                    },
                                    "MiddleName": {
                                      "type": "string"
                                    }
                                  }
                                },
                                "Phone": {
                                  "type": "array",
								  "additionalProperties": true,
								  "items": {
									"type": "object",
									"properties": {
									"DialNumber": {
									  "type": "string"
									},
									"PhoneTypeCode": {
									  "type": "object",
									  "additionalProperties": true,
									  "properties": {
										"content": {
										  "type": "string"
										},
										"tc": {
										  "type": "integer"
										}
									  }
									}
									}
								 }
                                },
                                "id": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        },
                        "TransExeDate": {
                          "type": "string"
                        },
                        "TransExeTime": {
                          "type": "string"
                        },
                        "TransRefGUID": {
                          "type": "string"
                        },
                        "TransResult": {
                          "type": "object",
                          "additionalProperties": true,
                          "properties": {
                            "ResultCode": {
                              "type": "object",
                              "additionalProperties": true,
                              "properties": {
                                "content": {
                                  "type": "string"
                                },
                                "tc": {
                                  "type": "integer"
                                }
                              }
                            }
                          }
                        },
                        "TransSubType": {
                          "type": "object",
                          "additionalProperties": true,
                          "properties": {
                            "content": {
                              "type": "string"
                            },
                            "tc": {
                              "type": "integer"
                            }
                          }
                        },
                        "TransType": {
                          "type": "object",
                          "additionalProperties": true,
                          "properties": {
                            "content": {
                              "type": "string"
                            },
                            "tc": {
                              "type": "integer"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
   
}

**Comment by edson-19** [comment]
attached input as txt 
[alip-agent-swagger.txt](https://github.com/swagger-api/swagger-codegen/files/2805145/alip-agent-swagger.txt)
file

**Comment by frantuma** [comment]
fixed in #9336
