### ISSUE TITLE
codegen with typescript-node creates code using http.ClientResponse which is factored out of core release

### ISSUE THREAD

**Issue by webwizrd** [swagger-api/swagger-codegen#9168]
##### Description

running codegen for language typescript-node results in code that contains http.ClientResponse, which is factored out in core. 
Should use http.IncomingMessage instead. see [request issue](https://github.com/request/request/issues/678)

##### Swagger-codegen version

2.4.1

##### Swagger declaration file content or url
n/a

##### Command line used for generation

`swagger-codegen generate -i swagger.json -l typescript-node -DmodelPropertyNaming=original -o tmp`

##### Steps to reproduce

create client with typescript-node

##### Related issues/PRs

n/a

##### Suggest a fix/enhancement

Replace http.ClientResponse with http.IncomingMessage in generation.

**Comment by hankolsen** [comment]
@webwizrd, I had the same issue, and just realized that if you add the flag `-DsupportsES6=true` it will generate code with `http.IncomingMessage` instead!

**Comment by iyarych** [comment]
Well that workaround doesn't work for swaggerhub - it doesn't have any config available.
