### ISSUE TITLE
Compiling and Unit Testing with Java 1.8

### ISSUE THREAD

**Issue by mikebz** [swagger-api/swagger-codegen#917]
I have Java 1.8 installed on my Mac and I was hoping not to install both 1.7 and 1.8.

When I run 
```
pom package
```
I get errors:

```
Tests in error: 
  CodegenTest: io/swagger/parser/SwaggerParser : Unsupported major.minor version 51.0
  Objc.ObjcModelTest: io/swagger/parser/SwaggerParser : Unsupported major.minor version 51.0
  python.PythonTest: io/swagger/parser/SwaggerParser : Unsupported major.minor version 51.0
  SwaggerMigratorTest: io/swagger/parser/SwaggerParser : Unsupported major.minor version 51.0
```

Has anyone tried running the compiler with javac -target 1.4  or has done any other upgrades to make Swagger compatible with 1.8?

My environment:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.3 (14D136)
      Kernel Version: Darwin 14.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: DSA002574
      User Name: Mike Borozdin (mike.borozdin)
      Secure Virtual Memory: Enabled
      Time since boot: 2 days 38 minutes

**Comment by webron** [comment]
Not an issue with the code but with maven - http://stackoverflow.com/questions/18813828/why-maven-use-jdk-1-6-but-my-java-version-is-1-7/19324816#19324816.

**Comment by mikebz** [comment]
It looks like using this solution from StackOverflow:

"add the following to your ~/.mavenrc:
export JAVA_HOME=/Library/Java/JavaVirtualMachines/{jdk-version}/Contents/Home"

Has got me past the build and unit test issue:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  2.933 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [ 20.073 s]
[INFO] swagger-codegen (executable) ....................... SUCCESS [ 15.459 s]
[INFO] swagger-generator .................................. SUCCESS [ 42.551 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2015-06-25T10:55:48-07:00
[INFO] Final Memory: 40M/548M
[INFO] ------------------------------------------------------------------------
```
