### ISSUE TITLE
Ruby _deserialize error for type number

### ISSUE THREAD

**Issue by neoecos** [swagger-api/swagger-codegen#920]
The type  number is not correctly deserialized in the base_object, the `Swagger.cons_get(number).new` fails.

Solved adding the case 

```
when :number
        value.to_i
```

**Comment by xhh** [comment]
Hi @neoecos! Thanks for reporting this. However, I could not repeat the issue with a `number` model property, which works well for me.
Have you tested it in the latest **develop_2.0** branch?

**Comment by wing328** [comment]
@neoecos is that still an issue? can you provide an example of the data to be deserialized so that we can try to repeat the issue ?

**Comment by wing328** [comment]
@neoecos closing the issue as we've not heard further update from you. Please open a new one if needed.
