### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ]

### ISSUE THREAD

**Issue by Janos-Sur** [swagger-api/swagger-codegen#9202]
##### Description

In the html2 document generated with swagger-codegen-cli-3.0.5 all the responses schema are empty. 
I have found after a quick check on my browser's console this error:

>  Uncaught SyntaxError: Unexpected token ]

##### Swagger-codegen version

3.0.5

##### Swagger declaration file content or url

I have used this yaml : 
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Related issues/PRs

Seems like this closed issue had the same kind of problem, even though the console error is different:
https://github.com/swagger-api/swagger-codegen/issues/8951

##### Suggest a fix/enhancement

While playing with the html2 document I have replaced all the occurences of this code line : 

`var schema = schemaWrapper.content[].schema;`

with the following line:

`var schema = schemaWrapper["content"]["application/json"]["schema"];`

With these changes I have found that the html document works as expected, showing correctly the schemas.

**Comment by HugoMario** [comment]
hey @Janos-Sur 

this issue has been fixed [with this PR](https://github.com/swagger-api/swagger-codegen-generators/pull/316), can you please check when you have a chance?

i'm going to close it for now, but if you find any issue i'll work on it immediately

**Comment by Janos-Sur** [comment]
Hi @HugoMario 

Sorry for my late reply.  I have just checked the html file generated using Swagger Codegen 3.0.7, now the schemas are showing correctly.

Thanks!
