### ISSUE TITLE
[Java] Bug generating Boolean type property

### ISSUE THREAD

**Issue by bwangfdu** [swagger-api/swagger-codegen#9203]
##### Description

When generate model object with Boolean type property, the get method is generated with duplicated `is` as `isisPropertyName`

##### Swagger-codegen version

3.0.1, 3.0.4, 3.0.5, others 3.0.x versions doesn't test.

##### Swagger declaration file content or url

```
"OrderLineAudit": {
      "type": "object",
      "properties": {
        "id": {
          "format": "uuid",
          "type": "string"
        },
        "completeTS": {
          "type": "string"
        },
        "eventId": {
          "type": "string"
        },
        "processed": {
          "type": "boolean"
        }
      }
    },
```
The processed property get method generated as `isisProcessed`
##### Command line used for generation

swagger-codegen-maven-plugin

##### Steps to reproduce

run generate goal

**Comment by frantuma** [comment]
fixed in swagger-api/swagger-codegen-generators#458
