### ISSUE TITLE
Can't build with `mvn package` on swagger-codegen

### ISSUE THREAD

**Issue by aeonyin** [swagger-api/swagger-codegen#921]
Apache Maven 3.0.5
Java version: 1.7.0_79, vendor: Oracle Corporation

After cloning, and following the Building step:  mvn package -X

It show errors:

Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
[DEBUG] Writing resolution tracking file /home/aeon/.m2/repository/org/sonatype/oss/oss-parent/5/oss-parent-5.pom.lastUpdated
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for http://repo.maven.apache.org/maven2
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
[DEBUG] Writing resolution tracking file /home/aeon/.m2/repository/org/sonatype/oss/oss-parent/5/oss-parent-5.pom.lastUpdated
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:5 from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): oss.sonatype.org: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 3, column 13

[ERROR]   The project io.swagger:swagger-codegen-project:2.1.2 (/home/aeon/python_api_k8s/swagger-codegen/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:5 from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): oss.sonatype.org: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 3, column 13: Unknown host oss.sonatype.org: Name or service not known -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact org.sonatype.oss:oss-parent:pom:5 from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): oss.sonatype.org: Name or service not known

Does it mean my host can not get the pom.xml?

I also try to retrieve the URL:https://oss.sonatype.org/content/repositories/snapshots/org/, and I am sure there is NO sonatype sub-directory. 

Please double check this issue.

**Comment by wing328** [comment]
Pull the latest master and it's working fine for me

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  1.176 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [  8.761 s]
[INFO] swagger-codegen (executable) ....................... SUCCESS [  4.587 s]
[INFO] swagger-generator .................................. SUCCESS [  7.781 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.694 s
[INFO] Finished at: 2015-06-26T16:19:44+08:00
[INFO] Final Memory: 46M/1033M
[INFO] ------------------------------------------------------------------------

**Comment by aeonyin** [comment]
Could help me to check it?

aeon@k8s-master:~/python_api_k8s/swagger-codegen$ mvn package
[INFO] Scanning for projects...
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.swagger:swagger-codegen-project:2.1.2 (/home/aeon/python_api_k8s/swagger-codegen/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:5 from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots): oss.sonatype.org: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 3, column 13: Unknown host oss.sonatype.org: Name or service not known -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom

Do u see Downloading messages? No Errors shown?
Thank you !

**Comment by wing328** [comment]
To troubleshoot the issue, I would suggest you to use mvn to build other packages (e.g. https://github.com/swagger-api/swagger-core or packages not related to Swagger) to see if mvn is correctly setup in your machine.

**Comment by aeonyin** [comment]
OK, I will try it, and let u know, thanks your suggestion.

**Comment by webron** [comment]
@aeonyin - any update?

**Comment by wing328** [comment]
Closing the issue as there's no further update.

**Comment by jason-kane** [comment]
for future searchers -- I saw exactly the same error message with both the docker build and "mvn package", it was a permissions problem.  I didn't track it down, just ran it as root (sudo mvn package) and it all worked.

ubuntu wily (15.10), maven 3.3.3-3 installed from ubuntu, oracle java 7 installed via webupd8team/java ppa

**Comment by yemyat89** [comment]
Same applies to RedHat and it appears to be a permission problem. Running as root solves the problem.
