### ISSUE TITLE
Missing custom abort message via generated API client

### ISSUE THREAD

**Issue by paullo0106** [swagger-api/swagger-codegen#922]
My application is based on [flask-restful-swagger](https://github.com/rantav/flask-restful-swagger), [swagger-codegen](https://github.com/swagger-api/swagger-codegen/), and python.

I universally use `abort()` in server side logic for unexpected situations, and it works fine on swagger UI (the abort reason is displayed fine).

```
from flask.ext.restful import abort

class PlatformInfo(Resource, Parameter):
    def __init__(self):
        pass

    @swagger.operation(
        notes='Get platform info',
        type=SomeType,
        responseClass=SomeType.__name__,
        nickname='get_platform_info',
        parameters=[
        ],
        responseMessages=[
            {
                "code": 200,
                "message": "Successfully get platform info."
            },
            {
                "code": 400,
                "message": "Error occurs while retrieving platform info."
            },
        ])
    def get(self):
        response_dict = dict()
        try:
            response_dict = get_platform_data()
	except:
	    abort(400, message='custom error messages here....')  # abort with custom error message

        return response_dict, 200
```
![swagger-issue](https://cloud.githubusercontent.com/assets/4966393/8374192/08034f04-1c26-11e5-9365-e3850bb0d440.png)

However, if I use the client generated by swagger-codegen, the abort message would be missing. I can only get something like *HTTP Error 400: BAD REQUEST*

Investigated further, I see that *ApiClient* issues a `urllib2.urlopen(request)`  

```
class ApiClient:
    """Generic API client for Swagger client library builds"""

    def __init__(self, apiKey=None, apiServer=None):
        if apiKey == None:
            raise Exception('You must pass an apiKey when instantiating the '
                            'APIClient')
        self.apiKey = apiKey
        self.apiServer = apiServer
        self.cookie = None

    def callAPI(self, resourcePath, method, queryParams, postData,
                headerParams=None):

        url = self.apiServer + resourcePath
        headers = {}
        if headerParams:
            for param, value in headerParams.iteritems():
                headers[param] = value

        headers['Content-type'] = 'application/json'
        headers['api_key'] = self.apiKey

        if self.cookie:
            headers['Cookie'] = self.cookie

        data = None

        if method == 'GET':
            ...(omitted)

        else:
            raise Exception('Method ' + method + ' is not recognized.')

        request = MethodRequest(method=method, url=url, headers=headers,
                                data=data)

        # Make the request
        response = urllib2.urlopen(request)
        if 'Set-Cookie' in response.headers:
            self.cookie = response.headers['Set-Cookie']
        string = response.read()

        try:
            data = json.loads(string)
        except ValueError:  # PUT requests don't return anything
            data = None

        return data
```

and `abort()` would be caught in **HTTPDefaultErrorHandler** of *urllib2.py*, and the message we put could not be found there anymore.

```
class HTTPDefaultErrorHandler(BaseHandler):
    def http_error_default(self, req, fp, code, msg, hdrs):
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

Result (our message *'custom error messages here....'* is lost):

```
    import platform_api  # client generated by swagger-codegen
    response = None
    try:
        response = platform_api.get_platform_info()
        print response
    except Exception as e:
        print e  # 'HTTP Error 400: BAD REQUEST'
        print e.msg  #  'BAD REQUEST'
```

I was wondering that if this is a limitation on API Client use case of swagger-codegen, and how could we get around of this issue. Thanks.

**Comment by wing328** [comment]
I noticed that in rest.py, there is a class named "ApiException" defined.

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/python/swagger_client/rest.py#L166

When the HTTP 400 occurred, were you able to catch the ApiException ?

**Comment by paullo0106** [comment]
Thank you, @wing328 , I might need some further investigation on those code to see if it's helpful for my scenario. I don't think I include an `ApiException` class in my current code base. Do you know any more information or use cases for `ApiException`?

**Comment by wing328** [comment]
If you look at the code:
```
    def __init__(self, http_resp):
        self.status = http_resp.status
        self.reason = http_resp.reason
        self.body = http_resp.data
        self.headers = http_resp.getheaders()
```
it stores the HTTP body in `self.body`, which means it should meet your requirement to obtain the error message in the body of the HTTP 400 response.

(other languages such as Ruby, PHP have similar ApiExcpetion object to store the HTTP header and body in the error response should developers need those information for error handling, troubleshooting, etc)

**Comment by paullo0106** [comment]
Thanks @wing328, I think I probably need to check how to update my `ApiClient` code with some latest changes like in https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/python/swagger_client/rest.py#L166
I will report what I find out later.

**Comment by wing328** [comment]
@paullo0106 do you need further assistance from us? Are you happy to close the issue ?

**Comment by paullo0106** [comment]
My issue was resolved after applying https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/python/swagger_client/rest.py which catch the abnormal status code and wrap the error nicely in `class ApiException`
```
if r.status not in range(200, 206):
    raise ApiException(r)
```
as well as updating some code in `request()` and `call_api()` functions in `class ApiClient` from https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/samples/client/petstore/python/swagger_client/api_client.py

Below is the result
```
    import platform_api
    response = None
    try:
        response = platform_api.get_platform_info()
        print response
    except Exception as e:
        print e.body['message']  # 'custom error messages here....' is printed successfully!
```
Thank you a lot @wing328  :)
