### ISSUE TITLE
[Java] - RestTemplate library - generated client thread safety

### ISSUE THREAD

**Issue by korlat** [swagger-api/swagger-codegen#9222]
##### Description

This is related to an old issue which was closed with documentation improvements: #1435.
A fix was applied to the Jersey library, for some parts of the thread safety issues - response headers, and response status codes: #7453, #7605

I would like to fix this issue for the RestTemplate library

##### Swagger-codegen version

Using 2.4.2 but applies to the current Master (HEAD) as well

##### Swagger declaration file content or url

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L95

##### Command line used for generation

Any - N/A

##### Related issues/PRs

#1435
#7453
#7605

##### Suggest a fix/enhancement

I am happy to provide a PR for the issue that perform the same changes as PR: #7605 but applied to the RestTemplate library.

Another option I was considering was to create a PR as above but also to go a step further and address some of the other thread safety issues raised in #1435.

This would include making the following fields immutable:

- debugging
- defaultHeaders
- basePath
- restTemplate
- authentications
- dateFormat

That would involve creating a builder class as suggested in #1435

Weather this would move the RestTemplate library to far from the other Java libraries may be an issue, thoughts?

Note: Either of the above approaches would be non backward compatible as #7605 was.

**Comment by kmurthy0** [comment]
Subscribed - I'm interested in this change as well.

**Comment by mjeffrey** [comment]
See https://github.com/OpenAPITools/openapi-generator/issues/2280 for a workaround.

**Comment by thomasJoei** [comment]
Hi @korlat I created a PR regarding the response headers/status thread safety.
https://github.com/swagger-api/swagger-codegen/pull/9737

I might open another PR to create the builder class and enable users to provide thread safe `Authentication`, which something I had to work around in my current project, but it depends on my availabilities. 
Anyway you will at least be able to safely retrieve headers and status with `RestTemplate` once https://github.com/swagger-api/swagger-codegen/pull/9737 is merged :)

**Comment by HugoMario** [comment]
hello @thomasJoei , please, ping me once you want your PR gets merged.

**Comment by thomasJoei** [comment]
@HugoMario All checks have passed, PR is up to date with `master`. 
I don't know if you want to ping some other contributors to review it, but on my side it is ready to be merged :)

**Comment by HugoMario** [comment]
great, i can review :)

**Comment by sbilello** [comment]
Any update on this?

**Comment by HugoMario** [comment]
fixed by #9737 and [swagger-codegen-generators#942](https://github.com/swagger-api/swagger-codegen-generators/pull/942)
