### ISSUE TITLE
[HTML] doesn't document Arrays or Enums

### ISSUE THREAD

**Issue by jonwakingup** [swagger-api/swagger-codegen#9231]
##### Description

HTML generated documentation has empty sections for Enum and Array models.

##### Swagger-codegen version

Generated from SwaggerHub 04/03/2019.  I don't know what version they are using.

##### Swagger declaration file content or url

https://gist.github.com/jonwakingup/e4567d68317f92417f8df43fd0f183b8

The yaml document above, defines an array "DomainArray" on line 55, a "CustomCodes" enum on line 69 and an "HttpStatuses" enum on line 75. These are referred to in the steps to reproduce below.

##### Command line used for generation

Paste the file above into the Swagger editor at SwaggerHub.  
Open the documentation generated from menu option: / Export / Documentation / html

##### Steps to reproduce

Open the html documentation:
- In the Models section, click "1. CustomCodes".  The enum values are not included in the documentation.
- In the Models section, click "3. DomainArray".  Array members are not included in the documentation.

**Comment by jonwakingup** [comment]
Have also noticed that the same problem occurs if recursion is used within an object, in other words when one of the properties of an object is the object itself, for example when trying to build a tree structure.

**Comment by HugoMario** [comment]
I added a new option to generate models for now objects, this is a sample about how to use it:

```console
java -jar ./swagger-codegen-cli.jar generate -l html -i ./input.yaml -o ./output --additional-properties docNoObjects=true
```
