### ISSUE TITLE
Generate client/server using OpenAPI 3 from code

### ISSUE THREAD

**Issue by Lasering** [swagger-api/swagger-codegen#9275]
The readme states version 3.0.5 is capable of generating clients/servers for OpenAPI 3.0. However doing a git clone, git checkout 3.0.0 or git checkout v3.0.5, mvn clean package, and finally running the code like described in [here](https://github.com/swagger-api/swagger-codegen/tree/3.0.0#getting-started) does not work.

It seems one must fetch a snapshot directly from Maven, however the corresponding source code is nowwhere to be found. Is there a way to generate clients/servers for OpenAPI 3.0 from source?

I wanna build a custom generator for a combination of language/framework which is not supported, and currenlty it seems impossible.

**Comment by frantuma** [comment]
I am not sure I understand the issue, what is the issue you are getting trying to clone, build and run the cli?

**Comment by Lasering** [comment]
Yes, but for specifications using OpenAPI 3.0. And for a language/framework not currently supported, aka, I'm developing the code.

Converting OpenAPI 3.0 to 2.0 or to Swagger is not acceptable.

**Comment by Lasering** [comment]
```
git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
git checkout -b v3.0.7 # since version 3.0.7 supports OpenAPI 3
mvn clean package
# Now I would like to change the Finch generator to tweak it to my use case
# However it seems it no longer exists. In fact the entire package `languages` disappeared from the swagger-codegen module. I cannot find any of the mustache templates.
```

**Comment by lbordowitz** [comment]
If you want to add a generator to version 3, the generators are now in a [separate repository](https://github.com/swagger-api/swagger-codegen-generators). I'm also interested in a Finch generator.
