### ISSUE TITLE
C# client using IO.Swagger.Model even if no model is defined

### ISSUE THREAD

**Issue by ThomasBarnekow** [swagger-api/swagger-codegen#929]
The C# client classes in the `IO.Swagger.Api` namespace include a
```
using IO.Swagger.Model;
```
statement even if no model class (in the `IO.Swagger.Model` namespace) has been generated. The code won't compile in this case.

**Comment by wing328** [comment]
@ThomasBarnekow thanks for reporting the issue. I'll spend some time tomorrow to explore a solution as other languages (e.g. Java) may face the same issue.

**Comment by wing328** [comment]
Fixed in #927. Please help perform a test.

**Comment by ThomasBarnekow** [comment]
@wing328 It doesn't work with the swagger.json shared in #928. That doesn't have a model but
```
using IO.Swagger.Model;
```
is generated. An actual model is not generated.

**Comment by wing328** [comment]
Fixed and tested with the spec you provided.
```
using System;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
using RestSharp;
using IO.Swagger.Client;

namespace IO.Swagger.Api {

    public interface ITransformationApi {

```

**Comment by ThomasBarnekow** [comment]
@wing328 Tested myself and confirm it is now fixed.

**Comment by wing328** [comment]
@ThomasBarnekow Thanks again for reporting the issue and help test the fix.

**Comment by wing328** [comment]
PR merged into develop_2.0
