### ISSUE TITLE
codegen cli.jar for latest version (3.0.7) is not available

### ISSUE THREAD

**Issue by amitsendinblue** [swagger-api/swagger-codegen#9317]
Hi,
I am not able to find cli.jar file for the latest version (3.0.7) of swagger codegen. It would be great if you can provide me the link for the same.

I visited below links but it is not available there too:
1. https://mvnrepository.com/artifact/io.swagger/swagger-codegen-maven-plugin
2. https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/

It shows that the latest version of jar file is 2.4.4 (2019-03-26 13:11 ).

Thanks,

**Comment by hkosova** [comment]
Here it is:
https://mvnrepository.com/artifact/io.swagger.codegen.v3/swagger-codegen-cli/3.0.7
https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen/

The groupId for v. 3.x was [changed](https://github.com/swagger-api/swagger-codegen/issues/8431) from `io.swagger` to `io.swagger.codegen.v3`.

**Comment by amitsendinblue** [comment]
Thanks @hkosova
