### ISSUE TITLE
The Spring MVC Server swagger-ui webapp is not working

### ISSUE THREAD

**Issue by cosbor11** [swagger-api/swagger-codegen#934]
Steps to reproduce: 
1. Generate a SpringMVC server skeleton
2. Execute this command to start the project:  `mvn jetty:run`
3.  The readme says:
> "You can view the server in swagger-ui by pointing to http://localhost:8002/v1/sdoc.jsp"

ISSUE: No you can't; 404

**Comment by wing328** [comment]
@cosbor11  The README has been updated in `develop_2.0` branch:

http://localhost:8002/v2/swagger-ui.html

**Comment by wing328** [comment]
closing this issue as we've not heard from you
