### ISSUE TITLE
Question:  Can methods in DefaultGenerator be overriden, specifically, generateAPIs?

### ISSUE THREAD

**Issue by jjohnst-us** [swagger-api/swagger-codegen#9352]
##### Description

Looking to add a new Server Type for a unique platform REST implementation.  As part of creating stubs, we need to generate a source file for each operationID, not just each unique API path.  With my limited understanding looks like I would need to update (*hack*) generateApis in DefaultGenerator.  Is there a better way to do this?  Can I override it from *Codegen segments, didn't appear so because they don't extend DefaultGenerator.

Thanks.
##### Swagger-codegen version

N/A, new porting effort.

##### Swagger declaration file content or url
N/A, not a bug.

##### Command line used for generation
N/A
##### Related issues/PRs
N/A

**Comment by HugoMario** [comment]
hi @jjohnst-us, this https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L435 can certainly be override.

**Comment by jjohnst-us** [comment]
Thanks.  Looking at this a little more closely, how would I call a different generateAPIs?
SwaggerCodegen creates a builder based on io.swagger.codegen.cmd.Generate which makes a direct call to io.swagger.codegen.DefaultGenerator which calls generate().  I would like to be able to contribute back the code, but how would I override DefaultGenerator, or if I could do it at the generateAPIs level, where would my version of the method live?  tia..

**Comment by jjohnst-us** [comment]
Okay worked my way around it.  I guess this would get hashed out if and when a PR occurs.

**Comment by torshid** [comment]
Any detail on how you managed to change the behavior of DefaultGenerator? I tried with the maven plugin and the cli but wasn't able to achieve something.
