### ISSUE TITLE
[JAVA] Bug: Path parameter with dot(.) character results in assigning null as parameter value

### ISSUE THREAD

**Issue by idil-k** [swagger-api/swagger-codegen#9359]
##### Description

When the path parameter {id} in this URL {{base}}/business/users/{id} includes one of the characters dot(.) or semicolon(;), the parameter value is null. The parameter type is Integer. In case there is an invalid entry, Swagger returns BAD_REQUEST, however not in this case. Is there a way to make sure such characters result in a BAD_REQUEST too?

- Proper usage:  {{base}}/business/users/12
- The current problem:  {{base}}/business/users/.12

 
##### Swagger-codegen version
We are using swagger-codegen-maven-plugin with version 2.2.3.
##### Swagger declaration file content or url

```yaml
swagger: '2.0'
paths:
  /business/users/{id}:
    delete:
      summary: summary
      description: |
         description
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: The user id
          required: true
          type: integer
      responses:
        404:
          description: The user with the given id does not exist or is not under control of your company.
```
The url is of the format:
{{base}}/business/users/.12

##### Command line used for generation
The maven plugin used for code generation:
```xml
<plugin>
	<groupId>io.swagger</groupId>
	<artifactId>swagger-codegen-maven-plugin</artifactId>
	<version>2.2.3</version>
	<executions>
		<execution>
			<id>external</id>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<inputSpec>${project.basedir}/../../api-spec/src/main/resources/api.yaml</inputSpec>
				<language>spring</language>
				<modelPackage>io.swagger.api.external.model</modelPackage>
			</configuration>
		</execution>
	</executions>
</plugin>
```

##### Suggest a fix/enhancement
I have seen that in OpenAPI 3.0.0 there is a style key for parameter [serialisation](https://swagger.io/docs/specification/serialization/). Could updating the version and setting the style to its default value manually ```style: simple ``` help?

**Comment by HugoMario** [comment]
hey @idil-k , why did you close this issue? it was opened by mistake?

**Comment by idil-k** [comment]
Hi, @HugoMario. Yes, I identified the problem wrong. It was a spring boot related issue. I found the answer [here](https://www.baeldung.com/spring-mvc-pathvariable-dot).

**Comment by HugoMario** [comment]
oh ok, if you need help in a future, please don't hesitate to let me know.
