### ISSUE TITLE
Issue with bearer token authentication

### ISSUE THREAD

**Issue by yusetc** [swagger-api/swagger-codegen#9365]
##### Description

I generated an SDK in PHP for my API. It contains bearer token authentication but the generated code, after receive the token, it doesn't pass the token to endpoints and I need to do it manually in the requests methods:
````php
if ($this->config->getAccessToken()) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
````
With this, the authentication is working well. 

##### Swagger-codegen version

version: 3.0.7

**Comment by powerpbx** [comment]
We also see this.  We have multiple headers and none of them are being generated.

**Comment by HugoMario** [comment]
hello @yusetc, can you check again when you have a chance? i tested this and worked fine for me, however going to add a capability to use a test access code.

**Comment by HugoMario** [comment]
btw, using the petstore sample to generate client, i use this snippet to test:
```php
require_once(dirname(dirname(dirname(__FILE__))) . '/vendor/autoload.php');
        require_once(dirname(dirname(dirname(__FILE__))) . '/vendor/guzzlehttp/guzzle/src/Client.php');
        $apiInstance = new Api\PetApi(new \GuzzleHttp\Client(), null);
        try {
            $result = $apiInstance->findPetsByStatus("available");
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling DefaultApi->testMethod: ' . $e->getMessage();
        }
```
settinng bearer in operation of course.

**Comment by HugoMario** [comment]
going to close this for now, but please let me know if issue is still present
