### ISSUE TITLE
JAX-RS generator produces invalid Java code when there are dashes in the resource URL 

### ISSUE THREAD

**Issue by giraone** [swagger-api/swagger-codegen#939]
If a "path" contains a dash, e.g.

```
"paths": {
      "/online-community": {
          "get": {
          ...
   }
}
```
and __jaxrs__ is used as the "language", the generated Java classes still contain the dashes:

```
public class Online-communityApiServiceImpl extends Online-communityApiService {
}
```
and the generation is unusable. Is there a way to remove dashes or even better force the replacement of "*snake-case*" style in URLs by "*CamelCase*" style in Java/JAX-RS?

**Comment by xhh** [comment]
@giraone I just submitted a PR (#940) to fix this and it works when testing manually on my local. Could you please give it a try and see if it fix your problem as well?

**Comment by giraone** [comment]
Thanks for the fast fix - the class names are now correct. This issue can be closed.
