### ISSUE TITLE
[Python] Client does not support oneOf?

### ISSUE THREAD

**Issue by neubig** [swagger-api/swagger-codegen#9395]
##### Description

I was trying to create a simple API that uses oneOf, but it seems that when I run this through the codegen to create a Python client, the resulting code throws an error (see below).

##### Swagger-codegen version

I am using the latest version of the 3.0.0 branch as of now, git tag: 305924cab9410f2fc9bb2b77aaf5e8271952c932

##### Swagger declaration file content or url

Here is a simple version of petstore that uses the oneOf syntax (described here: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/):

https://gist.github.com/neubig/557620a78a40be0a17dfc239076cc111

##### Command line used for generation

    java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i petstore.yaml -l python -o petstore/

##### Steps to reproduce

After generating the code above:

    cd petstore
    python setup.py
    python
    >>> import swagger_client
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/neubig/sand/petstore/swagger_client/__init__.py", line 18, in <module>
        from swagger_client.api.pets_api import PetsApi
      File "/Users/neubig/sand/petstore/swagger_client/api/__init__.py", line 6, in <module>
        from swagger_client.api.pets_api import PetsApi
      File "/Users/neubig/sand/petstore/swagger_client/api/pets_api.py", line 20, in <module>
        from swagger_client.api_client import ApiClient
      File "/Users/neubig/sand/petstore/swagger_client/api_client.py", line 26, in <module>
        import swagger_client.models
      File "/Users/neubig/sand/petstore/swagger_client/models/__init__.py", line 20, in <module>
        from swagger_client.models.pets import Pets
      File "/Users/neubig/sand/petstore/swagger_client/models/pets.py", line 17, in <module>
        from swagger_client.models.object import Object  # noqa: F401,E501
    ModuleNotFoundError: No module named 'swagger_client.models.object'

##### Related issues/PRs

Not that I can find.

##### Suggest a fix/enhancement

It seems that perhaps oneOf syntax is not fully supported? I'm not familiar enough with the codebase to give a concrete suggestion.

**Comment by jackthias** [comment]
I have the same issue on 3.0.8 version of the CLI tool.

**Comment by HugoMario** [comment]
hello @neubig @jackthias 
i checked this issue, and current snapshot works fine. 

keep in mind that schema:
```yaml
Pets:
      type: array
      items:
        oneOf:
          $ref: "#/components/schemas/Dog"
          $ref: "#/components/schemas/Cat"
```
is wrong, it should be 
```yaml
    Pets:
      type: array
      items:
        oneOf:
        - $ref: "#/components/schemas/Dog"
        - $ref: "#/components/schemas/Cat"
```

with command:
```
python3 setup.py install
```
on root folder.

Please, when you have a chance, check this and let me know how it goes

**Comment by neubig** [comment]
Thanks! It's likely that it was a bug in my YAML file. But we're no longer using swagger so I won't have time to check this. I can close the issue.
