### ISSUE TITLE
Java Wordnik Documentation

### ISSUE THREAD

**Issue by Spedwards** [swagger-api/swagger-codegen#942]
I'm not familiar with Swagger though I wish to port my Python script using Wordnik to Java and the documentation link on their website doesn't work.

This leads me to believe that the documentation for the Wordnik's Java library was removed. Was it moved somewhere else and/or is it going to be re-added?

**Comment by wing328** [comment]
@Spedwards  If you want to generate Java API client based on Swagger spec, you can pull the latest `master` or `develop_2.0` branch (which contains the latest bug fixes and enhancements) and then run `mvn clean && ./bin/java-petstore.sh` to generate Java API client for Petstore as an example.

or you can do it online and here is an example:
```
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' http://generator.swagger.io/api/gen/clients/java
```
Is that what you're looking for ?

**Comment by Spedwards** [comment]
No it's not. I'm looking for the documentation for the Wordnik API which is stored in this repository.

**Comment by wing328** [comment]
For Wordnik API, have you checked this: http://developer.wordnik.com/ ?

**Comment by Spedwards** [comment]
Yes I have... And if you noticed, the Java Documentation link leads to a dead link here...

**Comment by wing328** [comment]
I would recommend you contact the WordNik team via email: apiteam@wordnik.com

**Comment by wing328** [comment]
@Spedwards do you still need anything from us ? are you happy to close this issue ?

**Comment by webron** [comment]
FWIW, the clients can be found here - https://github.com/swagger-api/swagger-codegen/tree/v2.0.18/samples/client.
