### ISSUE TITLE
[Java] Gradle wrapper is unusable: Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by sasoiliev** [swagger-api/swagger-codegen#9421]
##### Description

I am trying to generate client bindings from an OpenAPI YAML spec and then use that with the generated Gradle Wrapper.

The issue is that the `gradle/wrapper/gradle-wrapper.jar` file has zero size rendering the `gradlew` script unusable.

##### Swagger-codegen version

3.0.8

##### Swagger declaration file content or url

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml

##### Command line used for generation

java -jar /tmp/swagger-codegen-cli-3.0.8.jar generate -i /tmp/pet.yaml -l java -o /tmp/java

##### Steps to reproduce

1. Download the pet store sample YAML definition (https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml) as `/tmp/pet.yaml`
2. Run the generator: `java -jar /tmp/swagger-codegen-cli-3.0.8.jar generate -i /tmp/pet.yaml -l java -o /tmp/java`
3. Make `gradlew` executable: `chmod +x /tmp/java/gradlew`
4. Try to run a Gradle command using the generated wrapper: `cd /tmp/java && ./gradlew --version`

Expected result: the Gradle version is printed out.

Actual result:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

Also doing a `ls -la gradle/wrapper`:

```
...
-rw-rw-r-- 1 ailiev ailiev    0 Mai  3 13:22 gradle-wrapper.jar
...
```

##### Suggest a fix/enhancement

The cause seems to be that the generator tries to copy the file from `handlebars/Java/gradle-wrapper.jar`, while the actual file is in `Java/gradle-wrapper.jar`. There is a warning in the generator output indicating this:

```
13:15:43.889 [Thread-1] WARN io.swagger.codegen.v3.DefaultGenerator - can't open handlebars/Java/gradle-wrapper.jar for input
```

Not sure what the correct solution would be though.

**Comment by jhandguy** [comment]
I am also experiencing this issue ☝️

**Comment by kaplin** [comment]
I'm also experiencing this

**Comment by madorb** [comment]
Yep, running into this as well. Strangly if i pass -Dmodels it works, if i pass -Dapis it fails. this seems a major problem.

**Comment by aarighi** [comment]
Seeing this too, with codegen version 3.0.13

**Comment by frantuma** [comment]
Thanks for reporting this, fixed in swagger-api/swagger-codegen-generators#555
