### ISSUE TITLE
[Go] Bug: Error "undefined: localVarFile" when specifying POST on file

### ISSUE THREAD

**Issue by psaffrey-origami** [swagger-api/swagger-codegen#9431]
##### Description

As in the title.

##### Swagger-codegen version

2.4.0-SNAPSHOT

##### Swagger declaration file content or url

https://gist.github.com/psaffrey-origami/f69ff09b2fcad530233488681868fd38

##### Command line used for generation

    docker run --rm -v /tmp:/local swaggerapi/swagger-codegen-cli generate -l go -i /local/file_post_bug.json -o /local/swagger_out

##### Steps to reproduce

Copy the file from:

    https://gist.github.com/psaffrey-origami/f69ff09b2fcad530233488681868fd38

into `/tmp` and then do this:

    docker run --rm -v /tmp:/local swaggerapi/swagger-codegen-cli generate -l go -i /local/file_post_bug.json -o /local/swagger_out
    cd /tmp/swagger_out
    go build

I get:

    ./api_default.go:64:5: undefined: localVarFile
    ./api_default.go:65:28: undefined: localVarFile
    ./api_default.go:67:22: undefined: localVarFile
    ./api_default.go:68:3: undefined: localVarFile

##### Related issues/PRs

This bug has been seen before and is described here:

https://github.com/swagger-api/swagger-codegen/issues/7311

There are two fix branches on that issue, one of which has been merged but I'm still experiencing the bug.

##### Suggest a fix/enhancement

I (manually) applied the fix from the the second PR on issue 7311:

https://github.com/swagger-api/swagger-codegen/pull/8051

and it fixed the problem for me. That PR has conflicts, but if I can resolve those to recreate the PR, would it be possible to merge this small change?

**Comment by karismann** [comment]
hello @psaffrey-origami  , I suggest you to take a loot at the forked project  https://github.com/OpenAPITools/openapi-generator where the problem has been fixed with PR https://github.com/OpenAPITools/openapi-generator/pull/382  with 3.1.0 version

**Comment by psaffrey-origami** [comment]
Yes, I also tried that:

    docker run --rm -v /Users/psaffrey/swagger-test:/local openapitools/openapi-generator-cli generate -g go -i /local/specs/partner-api-swagger.json -o /local/partner-api-go-client -c /local/configs/partner-api.json

followed by:

    cd ~/swagger-test/partner-api-go-client
    go build

and I get:

    ./model_file.go:13:6: invalid recursive type File
    ./model_throwable.go:13:6: invalid recursive type Throwable

This error has been fixed on the Swagger side: https://github.com/go-swagger/go-swagger/issues/1277 but not on the OpenAPI side :( I actually chose to merge their fix back to you (rather than the other way around) because the fix described in this thread is smaller. :(

**Comment by karismann** [comment]
What is the content of your /local/configs/partner-api.json  ?
Could you please try with latest openapi-generator-cli  version ?  (4.0.0)

**Comment by HugoMario** [comment]
Hello @psaffrey-origami , sorry for this delay answer, but if you're still willing to solve PR fixing let me know and i can help you to merge it.

**Comment by psaffrey-origami** [comment]
Thanks @HugoMario - I can make a PR with just that one-line change, but do you also require me to add a test for the fix before applying the merge?

**Comment by psaffrey-origami** [comment]
Hi @HugoMario - just coming back to this and I made the PR as suggested: https://github.com/swagger-api/swagger-codegen/pull/9527

What else can I do to help this get merged?

**Comment by HugoMario** [comment]
@psaffrey-origami , let me take a look before merging

**Comment by HugoMario** [comment]
@psaffrey-origami , just realize that there is gonna be a release soon, so let's hold merging after release, since i need to figure out why some CI are failing.

**Comment by psaffrey-origami** [comment]
Thanks @HugoMario . In case you missed it, I had a missing curly bracket from my first commit (sigh) but I put it back in and CI is happy now.
