### ISSUE TITLE
 error: type List does not take parameters

### ISSUE THREAD

**Issue by mikebz** [swagger-api/swagger-codegen#945]
After generating java libraries from swagger JSON I tried to compile a java client and I am getting a bunch of issues like these:

[ERROR] /Users/mike.borozdin/src/GitHub/Swagger-CodeGen-SDKs/java/src/main/java/io/swagger/client/model/Tabs.java:[251,29] error: type List does not take parameters

and:
[ERROR] /Users/mike.borozdin/src/GitHub/Swagger-CodeGen-SDKs/java/src/main/java/io/swagger/client/api/CloudStorageApi.java:[133,9] error: reference to Object is ambiguous

It looks like the generated objects do not disambiguate themselves from the standard java objects.  Can I force it to use the full local name or the full java.util name?

Thank you!

Environment: 
DSA002574:java mike.borozdin$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46

DSA002574:java mike.borozdin$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"

**Comment by wing328** [comment]
@mikebz do you mind sharing with us the Swagger spec (assuming it can be shared publicly) ? Is the Swagger Spec automatically generated using some plugins ?

We've previously received similar issue report from other users about the use of "Object" as model name. They managed to resolve the issue by avoid using reserved keywords to name models or parameters.

**Comment by mikebz** [comment]
Absolutely.  Here is the file:

**Comment by wing328** [comment]
FYI. I don't see the file in your reply.

**Comment by webron** [comment]
@mikebz - you can't attach files in email replies with Github :)

**Comment by mikebz** [comment]
Strange, I thought I copied and pasted the body of it into the message.  Here is a link: https://drive.google.com/open?id=0B32XZbrBkDXxb1FiYmx1Q1dTVjg

**Comment by mikebz** [comment]
I also created a Gist so you don't have do download it: https://gist.github.com/mikebz/bc801337c2d1f6faa8b5

Thank you!

**Comment by wing328** [comment]
@mikebz thanks for sharing the spec. I noticed that "Object" is defined as follows:
```
  "definitions": {
    "Object": {
      "type": "object",
      "properties": {}
    },
```
and it's used as a response (200) for many endpoints. Is that intentional to define the response as a model without any properties ?

For response, I noticed the following is defined:
```
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Object"
            }
          },
          "200-201": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/provisioningInformation"
            }
          },
          "400-500 Range": {
            "description": "Error encountered during execution.",
            "schema": {
              "$ref": "#/definitions/errorDetails"
            }
          }
        },
```
It seems to me there are duplicated 200 response defined.

For authentication, I noticed the following parameter is defined in the endpoint.
```
          {
            "name": "X-DocuSign-Authentication",
            "in": "header",
            "description": "Authentication",
            "required": false,
            "type": "string"
          }
```
You might considering using securityDefinitions instead. Here is an example [petstore.json#L811] (https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L811)

**Comment by wing328** [comment]
@mikebz closing this issue as we've not heard further update from you. Please open a new issue if you need help with Swagger-Codegen
