### ISSUE TITLE
Swagger codegen oAuth Spring Boot issue

### ISSUE THREAD

**Issue by tenaz3** [swagger-api/swagger-codegen#9455]
[KOTLIN] Bug generating code with Feign 10.1.0

##### Description

I tried to generate code from a swagger.json, problem is I'm using  Spring Boot 2.1.5.RELEASE
together with spring-cloud-starter-openfeign which gives me feign-core 10.1.0
The new feign version for `RetryableException` has change the contract.
My question is if someone had the same issue, or there is a way to workaround it.
I still want to use, but is not compatible =/
swagger-generate-config.json
```json
{
  "library": "feign"
}
```
##### Swagger-codegen version

 swagger-codegen 3.0.8

##### Swagger declaration file content or url
maven-compiler-plugin, swagger-codegen-maven-plugin
##### Command line used for generation

mvn clean compile

**Comment by dominic-jones** [comment]
Confirm, the codegen plugin, as I see it, is not compatible with OpenFeign 10. Also, not a Kotlin specific issue.
