### ISSUE TITLE
the swagger.json produced by generate server for node.js is missing path summary

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#947]
_From @tsmith-sdm on July 3, 2015 0:9_

The summary field on paths does not show up in the swagger.json which is produced by the generate server for node.js option.

_Copied from original issue: swagger-api/swagger-editor#524_

**Comment by wing328** [comment]
@tsmith-sdm I'm no expert in node.js but wonder if you can share with me where you expect to see the summary in the generated-code? Here is the code snippet for 2 methods in Petstore
```
'use strict';

var url = require('url');


var Pet = require('./PetService');


module.exports.updatePet = function updatePet (req, res, next) {
  var body = req.swagger.params['body'].value;


  var result = Pet.updatePet(body);

  if(typeof result !== 'undefined') {
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(result || {}, null, 2));
  }
  else
    res.end();
};

module.exports.addPet = function addPet (req, res, next) {
  var body = req.swagger.params['body'].value;


  var result = Pet.addPet(body);

  if(typeof result !== 'undefined') {
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(result || {}, null, 2));
  }
  else
    res.end();
};
```

**Comment by tsmith-sdm** [comment]
When you use the Generate Server -> Node.js option in http://editor.swagger.io/ it generates a zip archive. Inside that zip archive is a swagger.json spec file. That swagger.json file does not include the summary fields defined in the YAML.

For instance in the petstore_full.yaml the post pets path contains

> summary: Add a new pet to the store

Yet that doesn't show up in the generated swagger.json spec file.

```javascript
  "/pets": {
    "post": {
      "x-swagger-router-controller": "Pet",
      "tags": ["Pet"],
      "operationId": "addPet",
      "parameters": [
        
        {
  "in" : "body",
  "name" : "body",
  "description" : "Pet object that needs to be added to the store",
  "summary": "Add a new pet to the store" <==== this is missing
  "required" : false,
  "schema" : {
    "$ref" : "#/definitions/Pet"
  }
```

**Comment by wing328** [comment]
@tsmith-sdm thanks for the detailed explanation and sorry that I was not clear. Where in the generated code to you expected to see the `summary` (and `description`)? just one line above the function declaration like the following:
```
'use strict';

var url = require('url');


var Pet = require('./PetService');

/*
Update an existing pet
*/
module.exports.updatePet = function updatePet (req, res, next) {
  var body = req.swagger.params['body'].value;


  var result = Pet.updatePet(body);

  if(typeof result !== 'undefined') {
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(result || {}, null, 2));
  }
  else
    res.end();
};
```

**Comment by wing328** [comment]
@tsmith-sdm after reading your reply once again, I think I got what you meant. I submitted #966 to add back summary and description to the endpoint definition.

The updated swagger.json can be found at https://github.com/wing328/swagger-codegen/blob/nodejs_fix_summary/samples/server/petstore/nodejs/api/swagger.json

**Comment by wing328** [comment]
@tsmith-sdm do you mind confirming if the change is what you want ?

**Comment by wing328** [comment]
PR merged into develop_2.0

**Comment by alastair-todd** [comment]
@wing328   it is api/swagger.yaml if you chose that option..but the code looks for the json version

**Comment by wing328** [comment]
@alastair-todd thanks for tagging me but I'm no longer involved in this particular project so can't help with this issue.
