### ISSUE TITLE
3.0.x versions missing in maven

### ISSUE THREAD

**Issue by kyle-dorman** [swagger-api/swagger-codegen#9475]
Hi, I don't see the newer project releases in Maven. I only see up to 3.0.0-rc1. Am I looking in the wrong place?
https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/

**Comment by hkosova** [comment]
v3 releases are here:
https://repo1.maven.org/maven2/io/swagger/codegen/v3/

The groupId for v3 is `io.swagger.codegen.v3`.

**Comment by kyle-dorman** [comment]
thank you
