### ISSUE TITLE
Generated C# model does not work with inheritance ("allOf") / doesn't extend

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#948]
_From @StefH on July 3, 2015 6:7_

This swagger definition file:

``` yml
swagger: '2.0'

info:
  version: "1.0.0"
  title: test

definitions:
  ErrorModel:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
      code:
        type: integer

  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel'
    - type: object
      required:
      - rootCause
      properties:
        rootCause:
          type: string


paths:
  /api/ExtendedError:
    post:
      summary: Creates new ExtendedErrorModel.
      tags:
        - ExtendedErrorModel
      consumes:
        - N/A
      produces:
        - application/json+v1
      parameters:
        - name: body
          description: The ExtendedErrorModel to add.
          in: body
          required: true
          schema:
              $ref: '#/definitions/ExtendedErrorModel'
      responses:
        200:
          description: Acknowledged. No content.
```

Generates the following correct java-class:

``` java
public class ExtendedErrorModel extends ErrorModel {

  private String rootCause = null;


  /**
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty("rootCause")
  public String getRootCause() {
    return rootCause;
  }
  public void setRootCause(String rootCause) {
    this.rootCause = rootCause;
  }



  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtendedErrorModel {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  rootCause: ").append(rootCause).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
```

But the generated C# model class for ExtendedErrorModel does not extend the ErrorModel:

``` c#
public class ExtendedErrorModel {


    [DataMember(Name="rootCause", EmitDefaultValue=false)]
    public string RootCause { get; set; }



    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class ExtendedErrorModel {\n");

      sb.Append("  RootCause: ").Append(RootCause).Append("\n");

      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}
```

I would expect a c# code like:

``` c#
  [DataContract]
  public class ExtendedErrorModel : ErrorModel {
  // . . .
  }
```

_Copied from original issue: swagger-api/swagger-editor#525_

**Comment by wing328** [comment]
@Stefh would you please pull the latest develop_2.0 and see if that meets your requirement ?

**Comment by fehguy** [comment]
please reopen if you're still having troubles.

**Comment by StefH** [comment]
The generated C# class is still wrong because the 'Message' and 'Code' properties are also defined in the ExtendedErrorModel which is wrong.

(How to re-open this issue?)

```c#
using System;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Model {

  /// <summary>
  /// 
  /// </summary>
  [DataContract]
  public class ExtendedErrorModel : ErrorModel {
    
    /// <summary>
    /// Gets or Sets Message
    /// </summary>
    [DataMember(Name="message", EmitDefaultValue=false)]
    public string Message { get; set; }

    
    /// <summary>
    /// Gets or Sets RootCause
    /// </summary>
    [DataMember(Name="rootCause", EmitDefaultValue=false)]
    public string RootCause { get; set; }

    
    /// <summary>
    /// Gets or Sets Code
    /// </summary>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public int? Code { get; set; }

    

    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class ExtendedErrorModel {\n");
      
      sb.Append("  Message: ").Append(Message).Append("\n");
      
      sb.Append("  RootCause: ").Append(RootCause).Append("\n");
      
      sb.Append("  Code: ").Append(Code).Append("\n");
      
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public  new string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}
}

**Comment by hacki11** [comment]
any updates on this? having the same issue.

**Comment by illukarl23** [comment]
Same here :(

**Comment by cbornet** [comment]
Maybe set  supportsInheritance to true for C# codegens ?

**Comment by oleksabor** [comment]
I've tried to debug this case for c# model generation but found that  models are generated without inheritance for java client too. 

I've run `generate -i classInherti.yml -l java -o d:\temp\x-attr` where `classInherti.yml` is definition from the first message in this thread
and ExtendedErrorModel.java was generated without inheritance.
````
public class ExtendedErrorModel {
  @SerializedName("message")
  private String message = null;

  @SerializedName("code")
  private Integer code = null;

  @SerializedName("rootCause")
  private String rootCause = null;
...
}
````
Seems that inheritance is not handled in some special way for `AbstractJavaCodegen` and `JavaClientCodegen`.  Is there any chance that inheritance has been removed from the `DefaultCodegen` ? 

How should I generate java to get `ExtendedErrorModel` derived from the `ErrorModel`? I'm using `swagger 2.0` format

PS I've modified `JavaInheritanceTest.javaInheritanceTest` to use `CSharpClientCodegen` and it works as expected, no error is thrown.
However I've found that `model.getDiscriminator()` returns null when DefaultCodegen executes `fromModel`. This may cause inheritance to be ignored since no parent value is set.

**Comment by oleksabor** [comment]
I've modified `DefaultCodegen.fromModel` source code and it has started to inherit ExtendedErrorModel from ErrorModel (for both Java  and CSharp targets). However I suppose that code I've removed has been written for some purpose :-\

````
    [DataContract]
    public partial class ExtendedErrorModel : ErrorModel, IEquatable<ExtendedErrorModel>
    { 
        /// <summary>
        /// Gets or Sets RootCause
        /// </summary>
        [Required]
        [DataMember(Name="rootCause")]
        public string RootCause { get; set; }
````


[DefaultCodegen.java.zip](https://github.com/swagger-api/swagger-codegen/files/3378171/DefaultCodegen.java.zip)

**Comment by oleksabor** [comment]
tests fail with modified DefaultCodegen.java :(

> Failed tests:
>   CodegenTest.inheritanceOfComposedModelTest:353 expected [ComposedParent] but found [null]
>   CodegenTest.multiCompositionTest:270 expected [5] but found [1]
>   CodegenTest.multiInheritanceOfComposedModelTest:366 expected [ChildOfComposedParent] but found [null]
>   CodegenTest.multiInheritanceTest:303 expected [ChildOfSimpleParent] but found [null]
>   CodegenTest.noSupportsInheritanceTest:313 expected [5] but found [1]
>   CodegenTest.simpleCompositionTest:255 expected [3] but found [1]
>   CodegenTest.simpleInheritanceTest:287 expected [2] but found [1]
>   CodegenTest.supportsMixinsTest:333 expected [5] but found [1]
>   JavaScriptInheritanceTest.javascriptInheritanceTest:48 expected [Base] but found [Interface2]
>   JavaScriptInheritanceTest.javascriptNoInheritanceTest:89 expected [Base] but found [Interface2]

the source code I've commented out has to be investigated. May be it can be refactored to the new virtual method. This will allow to override base class search logic in the language generators.

**Comment by HugoMario** [comment]
Inheritance was implemented a while ago.
