### ISSUE TITLE
[PHP] Bug: Token Authentication headers missing in PHP generated Client

### ISSUE THREAD

**Issue by calcypher** [swagger-api/swagger-codegen#9495]
##### Description

Authorization Headers are not generated in PHP Client.
For example, if you have in your OpenAPI script Bearer Authentication:
```
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```
in the generated PHP Client, requests have no Authentication header.
I've verified that this problem is not present on Java Client.

##### Swagger-codegen version

Swagger Codegen version: 3.0.8

##### Swagger declaration file content or url

```
openapi: 3.0.0
info:
  title: IT API V2
  description: API Set per IT Framework.
  version: 2.0.0
servers:
  - url: 'https://xxx/api/v2'
  - url: 'http://xxx/api/v2'
paths:
  /queue-manager/items:
    get:
      tags:
        - queue-service
      summary: Queue Item List for a Status
      description: Queue Item List for a Status.
      operationId: queue-manager-items
      parameters:
        - name: queueStatus
          in: query
          description: Queue Status.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientTicket'
      security:
        - bearerAuth: []
components:
  schemas:
    PatientTicket:
      properties:
        id:
          description: ID
          type: string
          example: '123'
        ticketLevel:
          description: '1: First Level; 2: Second Level'
          type: integer
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
tags:
  - name: queue-service
    description: Queue Manager
```

##### Steps to reproduce
try to generate PHP client for this YAML. You can notice that API requests doesn't have Authorization headers.

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/9493

##### Suggest a fix/enhancement

on Configurator Class, it's possibile to set API key for Authentication, but then these values are not inserted in the request headers.

**Comment by FireLizard** [comment]
It should be possible to inherit the generated `HeaderSelector` to override  `selectHeaders()` and return your own headers.

**Comment by verbruggenalex** [comment]
Apparently this is only added for oauth:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L475-L480

I'm not sure this is correct.
