### ISSUE TITLE
Custom operations order

### ISSUE THREAD

**Issue by Shapoval1van** [swagger-api/swagger-codegen#9505]
Please remove default operation sort from the method `io.swagger.codegen.v3.DefaultGenerator#generateApis` or give the opportunity to override this behaviour. In this case, I have no way to change your predefined order, except to rewrite some classes what will be not so good decision.

**Comment by surighanta** [comment]
I have the  same ask as well. Is this customization available in version 3.0.14 ? , if yes, please suggest how. Current order is alphabetical, we need it like GET, POST, PUT, DELETE for example.

**Comment by Shapoval1van** [comment]
I close this issue because I found solution eventually. I wrote custom codegen that extend the basic one and override `postProcessSupportingFileData`  method and changed order

**Comment by surighanta** [comment]
Hi, would you mind committing the code / sharing with me.
