### ISSUE TITLE
[JavaSpring] Bug generating @Pattern regex

### ISSUE THREAD

**Issue by elier** [swagger-api/swagger-codegen#9509]
##### Description

When generating from this yaml file:
https://raw.githubusercontent.com/OpenBankingUK/account-info-api-spec/master/dist/v2.0.0/account-info-swagger.yaml

Regex pattern like this '^\d{1,13}\.\d{1,5}$' are not escape property and the generated java code does not compile.

To discuss: Should the code generation be responsible for escaping the regex properly for every language? or Should I modify the YAML to provide the appropriated escape?
 
##### Swagger-codegen version
3.0.8

##### Swagger declaration file content or url
```yaml
definitions:
  Amount:
    type: string
    pattern: '^\d{1,13}\.\d{1,5}$'
```

##### Command line used for generation
swagger-codegen generate -i https://raw.githubusercontent.com/OpenBankingUK/account-info-api-spec/master/dist/v2.0.0/account-info-swagger.yaml -l spring -o api-server

##### Steps to reproduce
swagger-codegen generate -i https://raw.githubusercontent.com/OpenBankingUK/account-info-api-spec/master/dist/v2.0.0/account-info-swagger.yaml -l spring -o api-account
mvn install

##### Suggest a fix/enhancement
Wrong java code generated: 
```java
@Pattern(regexp="^\d{1,13}\.\d{1,5}$")   
```
Right code generated should be: \
```java
@Pattern(regexp="^\\d{1,13}\\.\\d{1,5}$")   
```

**Comment by erreobi** [comment]
I'm having the same problem now ... we have just updated to the version from 2.3.1 to 2.4.5

**Comment by shameerkc** [comment]
Facing the same issue, while working with [https://github.com/jdegre/5GC_APIs/raw/master/TS29571_CommonData.yaml](https://github.com/jdegre/5GC_APIs/raw/master/TS29571_CommonData.yaml)

```yaml
    Mnc:
      type: string
      pattern: '^\d{2,3}$'
`

Generated output includese below error: java: illegal escape character

```java
@Pattern(regexp="^\d{2,3}$")   public String getMnc() {
    return mnc;
  }

`

**Comment by markwoon** [comment]
Still a problem with 3.0.21

**Comment by volkerrichert** [comment]
and also in 3.0.23. This is open since nearly 2 years. Does anyone have a workaround?

**Comment by HugoMario** [comment]
Hi @volkerrichert ,

Yes, we're working on this, and any PR is always welcome

**Comment by msm416** [comment]
Hello @HugoMario,

I've run into the same problem (single forward slash instead of double, for my regex) while invoking the 3.0.24 jar on my own spec, but for **jaxrs-jersey**

What is the progress on this issue for both spring and jaxrs-jersey?

Thank you!

**Comment by CDPrete** [comment]
I can confirm the same issue for version 2.4.19

**Comment by CDPrete** [comment]
Weird enough, if you provide an example in the definition then the pattern is correctly generated, unless you reference a scalar type with `$ref`. In such a case, the pattern is copied over without the example and it's then broken again...

**Comment by ambition-consulting** [comment]
still applies in 4.3.1 when converting @Digits(integer = Integer.MAX_VALUE, fraction = 3) to @Pattern(regexp="^\d{1,2147483647}([.]\d{1,3})?$")

**Comment by dlhermit** [comment]
Is there any progress on this issue?
We are currently using the last version, and the bug is still there
<groupId>io.swagger.codegen.v3</groupId>
<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>3.0.36</version>

As a workaround we are using
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>6.2.1</version>
This one gegerates the correct code
