### ISSUE TITLE
C# generator does not escape conflicting member names

### ISSUE THREAD

**Issue by danze** [swagger-api/swagger-codegen#955]
The C# code generator does not escape member names that are the same as their enclosing type. For example:

```csharp
namespace IO.Swagger.Model
{
  [DataContract]
  public class Capacities
  {
    [DataMember(Name="capacities", EmitDefaultValue=false)]
    public List<Capacity> Capacities { get; set; }
  }
}
```

In the above code, the "Capacities" property conflicts with the class name which is also "Capacities". The C# language does not allow this and the Swagger codegen should escape this to may be "_Capacities".

**Comment by wing328** [comment]
@danze thanks for reporting the issue. I agree ideally the conflicting member names should be escaped automatically by swagger-codegen.

In your case, may I know whether you manually create the Swagger Spec or you're using some plug-ins to generate the Swagger Spec?

**Comment by rajeshkamal** [comment]
Hi @wing328 ,

Replying for @danze . We are using https://github.com/springfox/springfox to generate the spec dynamically.

**Comment by wing328** [comment]
@rajeshkamal thanks. Is it correct to say that you've a corresponding model named "Capacities" defined in your Java source code? If yes, is that something you can share with us?

As a workaround, can the class use the name "Capacity" instead ?

**Comment by rajeshkamal** [comment]
Yes we have a model named Capacities

```
public class Capacities {

    public static final String MEDIA_TYPE = "application/vnd.acme.capacities+json";
    private List<Capacity> capacities;
    private String type;

    public Capacities() {
        this.type = MEDIA_TYPE;
    }

    public List<Capacity> getCapacities() {
        if (capacities == null) {
            capacities = new ArrayList<Capacity>();
        }
        return this.capacities;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
```

We can workaround for the time being to generate compilable code and generate dll's. It will be great if you can fix it and we can take the fix immediately.

**Comment by wing328** [comment]
I had a look at the generator source code and don't think it would be easy to escape conflicting member names. It also seems like this particular issue impacts C# client only as only C# client name the variable in PascalCase (which means other clients do not need the member name to be escaped to avoid the issue)

**Comment by smwurster** [comment]
:+1:   This affects me as well, although thankfully it only affects 2 classes and for now I can easily work around it by hand-modifying those as needed.

A quick look at the code shows that it doesn't seem to be that easy of a fix.  Looks like the model name isn't provided to the variable name function.  Some refactoring seems to be in order.

**Comment by wing328** [comment]
@danze @rajeshkamal @smwurster I've filed #1574 to escape the property name (which happens to be the same as the model name) by prepending an underscore (e.g. Name becomes _Name). Let me know if you've any feedback on the change.

**Comment by wing328** [comment]
PR merged. Please reply if you still encounter issues.

**Comment by mohansenthil** [comment]
@wing328  Hi I am seeing this issue in swagger-codegen-cli-3.0.33. do i have to open a new defect ? 

compilation error : "member names cannot be same as enclosing types. "

I have class named "File" and there is property named "File"

**Comment by AndreyDodonov-EH** [comment]
Same with 3.0.34
