### ISSUE TITLE
C# generator should use fully qualified names for builtin types

### ISSUE THREAD

**Issue by danze** [swagger-api/swagger-codegen#956]
The C# code generator should use fully qualified type name for types that are part of the .NET Framework or the standard library. This is in addition to the reserved keywords. For example, the

```csharp
System.Threading.Tasks.Task
```

type is defined in the .NET Framework and is used in generated code to represent a handle to an asynchronous operation. It's usually returned by asynchronous methods.

The issue is the C# codegen does not fully qualify such types and if the generated code also has a Swagger model named the same such as "Task", then the generated code won't compile. The reason is the C# compiler can not differentiate between the two types and it is ambiguous.

**Comment by wing328** [comment]
@danze thanks for the feedback. I'll incorporate the change into the PR https://github.com/swagger-api/swagger-codegen/pull/927 and I would also appreciate if you can help review the PR as it contains some improvements.

**Comment by wing328** [comment]
@danze updated #927 to use fully-qualified type name for `System.Threading.Tasks.Task`

Please take a look at the updated sample here:
https://github.com/wing328/swagger-codegen/tree/csharp_file_response/samples/client/petstore/csharp/SwaggerClientTest/Lib/SwaggerClient

**Comment by danze** [comment]
@wing328 the change looks good. Thank you for the quick response!

When can I expect this fix to make it to the 2.0 or master branch?

**Comment by wing328** [comment]
There's no official ETA to merge the PR to develop_2.0 or master branch. Based on my experience it would usually take 1 or 2 week for the PR to get merged.

**Comment by wing328** [comment]
@danze the PR has been merged into develop_2.0.

**Comment by wing328** [comment]
Closing the issue as no further question raised.
