### ISSUE TITLE
Spring-mvc-server cannot deploy

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#957]
_From @ericsodt on July 7, 2015 12:28_

I created a spring-mvc-server project from the 'minimal' project and tried to run it using mvn jetty:run however it does not seem to be deploying correctly.  I am getting the following errors: 

    No context on this server matched or handled this request.
    Contexts known to this server are:

     /api ---> o.e.j.m.p.JettyWebAppContext@6a916402{/api,[file:/C:/eclipse/workspace/spring-mvc-    swagger/target/webapp-tmp/, jar:file:/C:/Users/Jess/.m2/repository/io/springfox/springfox-swagger-    ui/2.0.0-SNAPSHOT/springfox-swagger-ui-2.0.0-SNAPSHOT.jar!/META-INF/resources],AVAILABLE}    {file:/C:/eclipse/workspace/spring-mvc-swagger/target/webapp-tmp/}

When I click on the api context I get another 404 stating:

    HTTP ERROR 404

    Problem accessing /api/. Reason:

        Not Found

_Copied from original issue: swagger-api/swagger-editor#530_

**Comment by mohsen1** [comment]
_From @webron on July 7, 2015 13:1_

@ericsodt - questions regarding the generated code belong to [swagger-codegen](https://github.com/swagger-api/swagger-codegen). I hope @mohsen1 won't mind though, and I'll say that I tried following the same process, ran it with `mvn jetty:run` and loaded up fine. The URL points to the root though at `http://localhost:8002` which unsurprisingly returns 200 with an empty response.

**Comment by dilipkrish** [comment]
I'll take a stab at fixing this since I'm familiar with this

**Comment by wing328** [comment]
@ericsodt the issue should be addressed in `develop_2.0` by #959. Please take a look.
