### ISSUE TITLE
Enums are not available in the static html generated

### ISSUE THREAD

**Issue by krishna-kashyap** [swagger-api/swagger-codegen#960]
When enums are used in models, they are not displayed/included in the static html that is generated using -l html. HTML generated using the sample (html-petstore.sh) from the bin file also fails to have any of the enums despite them being available in the swagger spec

**Comment by wing328** [comment]
@krishna-kashyap yes, currently the HTML doc does not include enum-related information in the documentation.

Please feel free to submit a PR against `develop_2.0` branch to enhance it.
