### ISSUE TITLE
Oauth support in retrofit template

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-codegen#962]
Once #347 is solved, I would like to implement client oauth2 in the retrofit template.
So far I have identified the following libs:
- google oauth client: https://github.com/google/google-oauth-java-client : all types of grants
- scribe : https://github.com/fernandezpablo85/scribe-java : only authorization_code
- oltu : http://oltu.apache.org/ : only authorization_code , password and client_credential

Password and client_credential flows are very simple and do not really need to pull a lib but to support implicit grant, only google oauth seems available. So should it be the winner ?
Has anyone worked with any of those libs and has an opinion ?

**Comment by cbornet** [comment]
Edit : apparently oltu does support implicit flow

**Comment by wing328** [comment]
@cbornet scribe looks promising as it includes a lot of examples covering different OAuth providers. https://github.com/fernandezpablo85/scribe-java/tree/master/src/test/java/org/scribe/examples

Thanks in advance for you contribution to support OAuth2 in the templates.

**Comment by cbornet** [comment]
But scribe seems to only support authorization code flow whereas a swagger client should be able to use password flow. I have started using oltu and so far it is working quite well.

**Comment by wing328** [comment]
Thanks for sharing the progress. I've not looked into `oltu` so I can't comment on it further (their API documentation URL is broken: http://oltu.apache.org/apidocs/index.html)

**Comment by cbornet** [comment]
Indeed the project doesn't seem very lively...

**Comment by cbornet** [comment]
I have a WIP for this issue.
* The code makes use of okhttp interceptors to add the auth headers and deal with the http responses. This adds a dependency to okhttp but it seems to be the direction taken by the retrofit team (https://github.com/square/retrofit/pull/728)
* It uses the oltu library for oauth2
* It will also adds support for Basic and API key auths
