### ISSUE TITLE
Incomplete model class rename in s-c-maven-plugin java language

### ISSUE THREAD

**Issue by heuermh** [swagger-api/swagger-codegen#9636]
##### Description

```bash
$ mvn clean install
...
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ hca-matrix-service-client ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 38 source files to hca-matrix-service-client/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] hca-matrix-service-client/target/generated-sources/swagger/src/main/java/io/swagger/client/model/V1LogicalFilter.java:[31,42] cannot find symbol
  symbol: class OneOfv1_MatrixFilter
[ERROR] hca-matrix-service-client/target/generated-sources/swagger/src/main/java/io/swagger/client/model/V1MatrixFilter.java:[23,41] cannot find symbol
  symbol: class OneOfv1_MatrixFilter
[ERROR] hca-matrix-service-client/target/generated-sources/swagger/src/main/java/io/swagger/client/model/V1ComparisonFilter.java:[31,45] cannot find symbol
  symbol: class OneOfv1_MatrixFilter
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Two of three OneOf model interfaces are named correctly
```java
/**
* OneOfV1ComparisonFilterValue
*/
public interface OneOfV1ComparisonFilterValue {

}

/**
* OneOfV1LogicalFilterValue
*/
public interface OneOfV1LogicalFilterValue {

}
```
while the third is not
```java
/**
* OneOfv1MatrixFilter
*/
public interface OneOfv1MatrixFilter {

}
```

The generated source contains `OneOfv1MatrixFilter` and `OneOfv1_MatrixFilter` instead of `OneOfV1MatrixFilter`.

##### Swagger-codegen version

swagger-codegen-maven-plugin 3.0.10

##### Swagger declaration file content or url

https://github.com/HumanCellAtlas/matrix-service/blob/6f86cacebf6d20a746256929669cb54d795d3b7f/config/matrix-api.yml

##### Command line used for generation

```bash
$ mvn clean install
```

##### Steps to reproduce

Entire repo at
https://github.com/heuermh/hca-matrix-service-client

Be sure to clone with submodules.

**Comment by heuermh** [comment]
Is there anything I need to do to help get feedback on this issue?  Thank you in advance.

**Comment by HugoMario** [comment]
ello @heuermh sorry for this delay, i can assign this issue to myself, but cant guarantee i'll work immediately, since i'm lack of time. However if you are willing to propose a PR i can help with reviewing and merging

**Comment by HugoMario** [comment]
hey @heuermh, actually it was a problem in templates and no so complex, so i took a time to address it, issue was solved with PR: https://github.com/swagger-api/swagger-codegen-generators/pull/486.

Closing now, but if you still get the error, please let me know.

**Comment by heuermh** [comment]
Thank you, @HugoMario!  Will that PR be available in a snapshot build?

**Comment by HugoMario** [comment]
yes @heuermh , indeed
