### ISSUE TITLE
Swagger CodeGen APIClient.java not returning the headers from the rest response by calling resttemplate

### ISSUE THREAD

**Issue by ayushaccenture** [swagger-api/swagger-codegen#9685]
##### Description

Swagger CodeGen APIClient.java not returning the headers from the rest response by calling resttemplate
It is returning only the response body. Please have a look into this.
##### Swagger-codegen version

2.4.5

##### Swagger declaration file content or url

 addHeadersToRequest(headerParams, requestBuilder);
        addHeadersToRequest(defaultHeaders, requestBuilder);
        
        RequestEntity<Object> requestEntity = requestBuilder.body(selectBody(body, formParams, contentType));

        ResponseEntity<T> responseEntity = restTemplate.exchange(requestEntity, returnType);
        
        statusCode = responseEntity.getStatusCode();
        responseHeaders = responseEntity.getHeaders();

        if (responseEntity.getStatusCode() == HttpStatus.NO_CONTENT) {
            return null;
        } else if (responseEntity.getStatusCode().is2xxSuccessful()) {
            if (returnType == null) {
                return null;
            }
            return responseEntity.getBody();

**Comment by thomasJoei** [comment]
Created a PR for this fix.
#39737
