### ISSUE TITLE
Spring Swagger Code Gen Templates

### ISSUE THREAD

**Issue by rajeswarikolluri** [swagger-api/swagger-codegen#9688]
Description
 Could you let me know the templates for Spring Library,  for SwaggerCode Generator version 3.0.10.
Could find the templates for Swagger Code Gen versions of 2.x but not for 3.x

**Comment by HugoMario** [comment]
hello @rajeswarikolluri ,
those templates are placed at:
https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/handlebars/JavaSpring

**Comment by rajeswarikolluri** [comment]
Thanks Hugo . This saved my time.

I need some help in updated templates  for this scenario
I have included configuration "modelNameSuffix" : "Type" .  Some of the APIs have return type as  'Object' . For this Swagger Generator suffixes Type for "Object" class as  'ObjectType'. Is there way to stop suffixing for 'Object'
