### ISSUE TITLE
Method parameters are called "body" instead of their actual names 

### ISSUE THREAD

**Issue by wasifshikder** [swagger-api/swagger-codegen#969]
When I generate the swagger documentation for my interface method parameters are called
"body" instead of their actual names.

for instance if I have a method  public int add(int first,int second)

the parameters first and second will both be called "body".

The method is in an interface.

**Comment by wing328** [comment]
Do you mind sharing the Swagger Spec with us so that we can repeat the issue ?

I'm assuming you're using `-l html` for generating the documentation.

**Comment by wing328** [comment]
Closing this issue as there's no further update.
