### ISSUE TITLE
Where do i get the libaries?!?!

### ISSUE THREAD

**Issue by Flori00** [swagger-api/swagger-codegen#9691]
##### Description

I only need the libraries for java.

##### Swagger declaration file content or url

import com.squareup.okhttp.*;
import com.squareup.okhttp.internal.http.HttpMethod;
import com.squareup.okhttp.logging.HttpLoggingInterceptor;
import com.squareup.okhttp.logging.HttpLoggingInterceptor.Level;
import okio.BufferedSink;
import okio.Okio;
i can't find a matching logging libary.

##### Command line used for generation

Why can't i press download and it works?

##### Steps to reproduce

Click on java in swagger-hub and then open it, here you have the problem.

**Comment by TeaTiMe08** [comment]
Add the corresponding dependanciues to your pom.xml file / in your IDE:
https://mvnrepository.com/artifact/com.squareup.okhttp
