### ISSUE TITLE
Public docker image is outdated

### ISSUE THREAD

**Issue by tomasfejfar** [swagger-api/swagger-codegen#9743]
##### Description

When using `swaggerapi/swagger-codegen-cli` docker image to generate PHP client, there are outdated dependencies in generated composer.json. 

```
    "require": {
        "php": ">=5.5",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8",
        "squizlabs/php_codesniffer": "~2.6",
        "friendsofphp/php-cs-fixer": "~1.12" <--------------------------------------
    },
```

Even though the [master version](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/composer.mustache#L31) already has updated dependencies. 

```
    "require": {
        "php": ">=5.5",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8",
        "squizlabs/php_codesniffer": "~2.6",
        "friendsofphp/php-cs-fixer": "~2.12" <--------------------------------------
    },
```

I did pull the newest image from dockerhub:

```
λ docker pull swaggerapi/swagger-codegen-cli
Using default tag: latest
latest: Pulling from swaggerapi/swagger-codegen-cli
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption.
709515475419: Already exists
38a1c0aaa6fd: Already exists
cd134db5e982: Already exists
1c84c2346990: Already exists
a3ed95caeb02: Already exists
Digest: sha256:510220aecb77fb9c196bf4ee7a65543544927f0fb58be0540e66351bf8b0f99e
Status: Image is up to date for swaggerapi/swagger-codegen-cli:latest
docker.io/swaggerapi/swagger-codegen-cli:latest
```
##### Swagger-codegen version

```
λ docker run --rm -v %CD%:/local swaggerapi/swagger-codegen-cli version
2.4.0-SNAPSHOT
``` 

##### Command line used for generation

`docker run --rm -v %CD%:/local swaggerapi/swagger-codegen-cli generate -i /local/swagger.json -l php -o /local/output --git-user-id xxx--git-repo-id xxx`

**Comment by tomasfejfar** [comment]
Version 2.4.8 works as expected, but the problem is that the ["latest" is used in README](https://github.com/swagger-api/swagger-codegen#swagger-codegen-cli-docker-image)

**Comment by frantuma** [comment]
Thanks for reporting this! from upcoming release docker image `latest` tag will be also updated
