### ISSUE TITLE
Login to Codeigniter via Command Line Interface (CLI)

### ISSUE THREAD

**Issue by ubriela** [swagger-api/swagger-codegen#976]
I used swagger-codegen to generated python client to login to CodeIgniter server.
To query the other services, the client needs a valid session.
However, CodeIgniter does not keep CLI sessions. Is there a way to go around this?
Thanks,

**Comment by wing328** [comment]
@ubriela for CLI sessions, are you referring to API token/key ? Do you have the Swagger Spec that you can share with us so that we can learn more about your backend?

**Comment by ubriela** [comment]
No, I mean, with CodeIgniter, "Under CLI, the Session library will automatically halt itself, as this is a concept based entirely on the HTTP protocol."
http://www.codeigniter.com/user_guide/libraries/sessions.html

I have two Swagger Path Objects, metadata_fov and login. In order to run metadata_fov, user needs to be login and have a valid session. The problem is that CodeIgniter do not maintain session for CLI client. 

        "/geoq/metadata_fov": {
            "get": {
                "tags": [
                    "geoq"
                ],
                "summary": "Returns a set of video frames",
                "description": "Returns metadata of individual video frames, from which it is possible to construct geospatial features of a video such as it's trajectory and coverage.",
                "operationId": "metadataFov",
                "produces": [
                    "application/json",
                    "application/xml",
                    "text/html",
                    "text/xml"
                ],
                "parameters": [
                    {
                        "name": "videoid",
                        "in": "query",
                        "description": "VideoId",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Metadata successfully returned",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Metadata not found"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },

        "/users/login": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Login user to the system",
                "description": "Authenticates user",
                "operationId": "loginUser",
                "parameters": [
                    {
                        "name": "username_email",
                        "in": "formData",
                        "description": "the username or email",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "password",
                        "in": "formData",
                        "description": "the user's password. Must be sent encrypted with sha512",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User logged in successfully"
                    },
                    "400": {
                        "description": "Invalid data supplied"
                    },
                    "409": {
                        "description": "Failed to login"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }

**Comment by wing328** [comment]
@ubriela the Codeigniter documentation mentions about using cookie for session but cookie parameter is not supported by swagger-codegen at the moment.

For REST API, it's more common to use HTTP basic authentication or API key/token for authentication.

**Comment by wing328** [comment]
@ubriela if there's no more follow-up question from you, we'll close this issue.
