### ISSUE TITLE
Swagger CodeGen 3.0.11 - JavaSpring - fullController

### ISSUE THREAD

**Issue by rajeswarikolluri** [swagger-api/swagger-codegen#9770]
##### Description

ApiController java stubs missing Method implementation of Api interface if  templates directory is used.

##### Swagger-codegen version
 swaggerCodegen 'io.swagger.codegen.v3:swagger-codegen-cli:3.0.11' 

##### Below is the configuration used to generate stubs
{
	"serializableModel": true,
	"dateLibrary":"legacy",
	"java8":false,
	"useBeanValidation":true,
	"interfaceOnly":false,
	"modelPackage": "oracle.communications.inventory.rest.model",
	"apiPackage": "oracle.communications.inventory.rest.api",
	"invokerPackage": "oracle.communications.inventory.rest.invoker",
	"modelNameSuffix" : "Type",
	"delegatePattern" : true,
	"delegatePackage" : "oracle.communications.inventory.rest.delegate",
	"allowUnicodeIdentifiers" : true,
	"generateModelDocumentation" : false,
	"generateApiDocumentation" : false,
	"generateSupportingFiles " : false,
	"hideGenerationTimestamp": true,
	"templateDir" : "src/templates/JavaSpring"
}

##### Suggest a fix/enhancement
Template dir includes latest handlebars present in https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/handlebars/JavaSpring .

Noticed that there are changes in apiController.mustache as per the bug https://github.com/swagger-api/swagger-codegen-generators/commit/303bb3fd88b0692c976ffef78f0ff7f43f02f251    which includes variable check "fullController".

If we remove "templateDir"  from swagger gen configuration , then all is fine , "fullController" is set to true.  But if "templateDir" is included in configuration, then ApiController stubs does not contain required methods.

For now we are using older version of ApiController.mustache file.

**Comment by rajeswarikolluri** [comment]
[yaml.zip](https://github.com/swagger-api/swagger-codegen/files/3716037/yaml.zip)

**Comment by frantuma** [comment]
I could not reproduce this with latest version, can you try 3.0.12 or latest snapshot version, and share some more details about the difference in outcome?

**Comment by rajeswarikolluri** [comment]
Thanks Francesco. It is working with 3.0.12
