### ISSUE TITLE
ASP.Net Core generate - .NET Core 3 / Swashbuckle 5 Support

### ISSUE THREAD

**Issue by knom** [swagger-api/swagger-codegen#9781]
Description
Update ASPNET Core generator to support .NET Core 3.0

Swagger-codegen version
2.0 branch

Suggest a fix/enhancement
Update ASPNET Core generator to support .NET Core 3.0

**Comment by gfrung4** [comment]
.NET Core 2.2 end of support is December 23, 2019.  It would be nice to have support for .NET Core 3.0 soon.  Is there any update on this?

It would also be nice to have support for .NET Core 3 added to the 3.0.0 branch for OpenAPI version 3.

**Comment by christiandersen** [comment]
I agree.

**Comment by knom** [comment]
@frantuma please approve and merge!

**Comment by knom** [comment]
Hmm.. I really liked the project - and did a few contributions every now and then..
(especially in combination w. https://editor.swagger.io)

But the community has changed, @wing328 is gone it seems..
Not sure how active / alive the codegen still is.. looking at alternatives right now!

Trying https://github.com/OpenAPITools/openapi-generator..

**Comment by HugoMario** [comment]
PR was merged and it's also been covered on v2 and v3, so closing this.

**Comment by bradygaster** [comment]
@HugoMario - do you have a link to a v3 issue or pull request related to @knom's request? I work on the .NET team at Microsoft and would very much like to see an ASP.NET Core 3.1 server stub generator created. I'd be willing to submit a pull request to make it happen - is there any other ongoing work in this space, or is there a pre-existing 3.1 generator in the works? 

Thanks in advance. Trust me - there is still very much interest in the OAS/Swagger opportunities for ASP.NET Core developers, and I'd be willing to work with the group to make this happen if we could get a little support in authoring the generators.

**Comment by HugoMario** [comment]
Hi @bradygaster, this PR https://github.com/swagger-api/swagger-codegen-generators/pull/642 is related to knom request for v3, it currently generates a aspnetcore version 3.0. Version 3.1 is in our path but with no ETA yet. So yea, it's pretty awesome receive any help to accomplish that.

Please, ping me if you need help with something.

**Comment by bradygaster** [comment]
@HugoMario - I submitted a PR last night to make a slight improvement - #10216 - which repairs one small bug I saw in the 3.0 template. I'm going to start working on the 3.1 update ASAP, so if anyone has tips on how to best submit a PR, feedback/guidance is welcome.

**Comment by HugoMario** [comment]
@bradygaster, here is a guide that you can use https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md.

if you have any doubt or need help to merge PR, please dont hesitate to ping me
