### ISSUE TITLE
Inherited model without additional properties results in a NullPointerException

### ISSUE THREAD

**Issue by maxime-morand** [swagger-api/swagger-codegen#980]
If a model inherit from an other without defining its own properties (allOf has just $ref to parent), a NullPointerException is thrown :

java.lang.NullPointerException
[INFO] Running BuildHelper...
    at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:529)
    at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:451)
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:125)

**Comment by webron** [comment]
@maxime-morand - thanks for reporting and submitting the PR. It was merged and 1.5.1-SNAPSHOT of swagger-core has been redeployed with it. Feel free to test it out.

**Comment by alex-estela** [comment]
I am still experiencing this issue with current master branch of swagger-codegen ; adding an additional property to the child does solve the issue. Could the issue still be opened ?

**Comment by wing328** [comment]
@alex-estela please pull the latest master to give it a try.

The latest version of Swagger Parser should have resolved it.
