### ISSUE TITLE
[Javascript] Recursive models break client generation

### ISSUE THREAD

**Issue by cmillsop** [swagger-api/swagger-codegen#9800]
##### Description

Generating models with properties that are arrays of the parent model breaks code generation for javascript client targets.  I tested this on the editor.swagger.io and using the codegen-cli libraries.  This appears to have started with the most recent version (2.4.9) as previous versions work fine.  I didn't test extensively on the 3.x branch but reproduced the issue on the most recent version (3.0.13).

Other client languages generate fine on the most recent versions (tested with editor.swagger.io).

##### Swagger-codegen version

Broken:
2.4.9
3.0.13

Working:
<=2.4.8

##### Swagger declaration file content or url

The following does not work.  Removing the array property or changing the type to a non-ref works.

```yaml
swagger: '2.0'
info:
  title: My API
  version: v1
paths:
  /api/test:
    get:
      tags:
        - TestClass
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/TestClass'
definitions:
  TestClass:
    type: object
    properties:
      name:
        type: string
      children:
        type: array
        items:
           $ref: '#/definitions/TestClass'
```

##### Command line used for generation

java -jar .\swagger-codegen-cli-2.4.9.jar generate -l javascript -i specification.json -v -o openapi

##### Steps to reproduce

Use the 2.4.9 or 3.0.13 codegen-cli library with the supplied yaml.

**Comment by pacome2017** [comment]
any fix yet ? I'm pretty sure it used to work a few months ago
