### ISSUE TITLE
Mustache files and CONTRIBUTING page for version 3 not found

### ISSUE THREAD

**Issue by stepobiz** [swagger-api/swagger-codegen#9805]
##### Description
Hello,
but where is the .mustache files in version 3.

Directory in tag 2.X: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources

now: https://github.com/swagger-api/swagger-codegen/tree/3.0.0/modules/swagger-codegen/src/main/resources

All the reference of this page: https://github.com/swagger-api/swagger-codegen/blob/3.0.0/CONTRIBUTING.md for version 3 go in 404

##### Swagger-codegen version
3.X

**Comment by frantuma** [comment]
https://github.com/swagger-api/swagger-codegen/blob/3.0.0/CONTRIBUTING.md has been [updated](#9931) to fix the links
