### ISSUE TITLE
[Java-Spring] Cookie parameters are not generated

### ISSUE THREAD

**Issue by nataliaoliveira** [swagger-api/swagger-codegen#9820]
##### Description

Cookie parameters are not being generated for Java language.

##### Swagger-codegen version

3.0.13

##### Swagger declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: fun!
  version: 1.0.1
servers:
- url: "/v1"
paths:
  "/one":
    get:
      operationId: duplicate
      parameters:
        - in: cookie
          description: cookie
          name: jsession
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
```

##### Command line used for generation

Language: spring
Library: spring-boot
InterfaceOnly: true

##### Steps to reproduce

Use the yaml above to generate sources with the options above.

##### Related issues/PRs

I found no PRs related, but there was one [issue](https://github.com/swagger-api/swagger-codegen-generators/issues/259) already reported on another swagger repo.

##### Suggest a fix/enhancement

The fix is going on this repo and [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators).

PRs: 
swagger-codegen-generators [https://github.com/swagger-api/swagger-codegen-generators/pull/524](https://github.com/swagger-api/swagger-codegen-generators/pull/524)
swagger-codegen https://github.com/swagger-api/swagger-codegen/pull/9825

**Comment by frantuma** [comment]
fixed in #9825 and  swagger-api/swagger-codegen-generators#524
