### ISSUE TITLE
missing imports in Python-Flask generated code

### ISSUE THREAD

**Issue by matteogrolla** [swagger-api/swagger-codegen#9829]
##### Description

version v3.0.12 correctly generates those imports
from swagger_server.models.base_model_ import Model
from swagger_server.models.id_name_pair import IdNamePair  # noqa: F401,E501

while master branch doesn't, and python complains about that

##### Swagger declaration file content or url
https://app.swaggerhub.com/apis/matteogrolla/test/1.0

##### Steps to reproduce
download the yaml from https://app.swaggerhub.com/apis/matteogrolla/test/1.0 as swagger_test.yaml 

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ../news-ingestion/resources/swagger_test.yaml -l python-flask -o news-ingestion-model_test

**Comment by tonyno** [comment]
+1
blocks using Swagger Online Editor with python server generator for us ;-(

**Comment by HugoMario** [comment]
This is fixed from version `3.0.17`. Check comment at https://github.com/swagger-api/swagger-codegen/issues/9864#issuecomment-690959367
