### ISSUE TITLE
[Java] Upgrade to support Jackson 2.10.0

### ISSUE THREAD

**Issue by rsclarke-vgw** [swagger-api/swagger-codegen#9833]
### Description

Codegen does not generate code that compiles against Jackson 2.10.0.

```
error: incompatible types: Object cannot be converted to T
[ERROR]   where T is a type-variable:
[ERROR]     T extends Object declared in method <T>readValue(HttpResponse,TypeReference)
```

##### Swagger-codegen version

2.4.9

##### Related issues/PRs

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10#2100pr1-typereference-assignment-compatibility-for-readvalue

**Comment by frantuma** [comment]
this should be fixed in #9866 and #9867, closing ticket please reopen if you're still experiencing issues
