### ISSUE TITLE
Multiple values not passed to arguments

### ISSUE THREAD

**Issue by motybz** [swagger-api/swagger-codegen#9837]
##### Description

I used the following command:
java -jar swagger-codegen-cli.jar generate -l python -i http://me-de/swagger/v1/swagger.json -o test2 -Dmodels=DataStream,DataSensor,DataLocation,DataEpisode -Dapis=DataStream,DataSensor,DataLocation,DataEpisode -DsupportingFiles

But only the first model/api (DataStream) was created
If I move the flags
java -jar swagger-codegen-cli.jar generate -l python -i http://me-de/swagger/v1/swagger.json -o test2
All of them (and more) will be created

##### Swagger-codegen version

java -jar swagger-codegen-cli.jar version
2.4.9
OS Linux Debian

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -l python -i http://me-de/swagger/v1/swagger.json -o test2 -Dmodels=DataStream,DataSensor,DataLocation,DataEpisode -Dapis=DataStream,DataSensor,DataLocation,DataEpisode -DsupportingFiles

**Comment by smillas** [comment]
Are you using the Windows PowerShell or the Command Console. I had the same problem generating net core projects with the Windows PowerShell but with the Command Console its work.

**Comment by motybz** [comment]
Updated, I'm using Linux Debian OS
