### ISSUE TITLE
[JavaSpring] Wrong generation of @JacksonXmlElementWrapper annotation

### ISSUE THREAD

**Issue by MariaPushkin** [swagger-api/swagger-codegen#9845]
##### Description

I generated spring boot server stub for the swaggerfile below with using `<withXml>` config option. Swagger editor generates the following example of respone: 

```xml
<segments>
	<segment>
		<branches>
			<branch>string</branch>
		</branches>
		<symbols>
			<symbol>string</symbol>
		</symbols>
	</segment>
</segments>
```

and thats what I really want. But my stub return something like that:

```xml
<segments>
   <segments>
      <segments>
        <branches>
            <branch>b1</branch>
            <branch>b2</branch>
        </branches>
        <symbols>
            <symbol>s1</symbol>
           <symbol>s2</symbol>
        </symbols>
      </segments>
   </segments>
</segments>
```

Adding `@JacksonXmlElementWrapper(useWrapping = false) `on `List<Segment> segments;` field in corresponding model helps to remove first `<segments>` tag, but adding `wrapped: false` to the swagger file change nothing (think because _isXmlWrapped_ property checked only for true values - [pojo.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache).

One other problem here is that codegen cant get xml name attribute for subobjects, definded separately. Thats why I have double `<segments><segments>` instead of `<segments><segment>`.  Adding xml property after $ref helps, but it is incorrect swagger, so I don`t whant to do that: 
```yaml
items:
   $ref: '#/definitions/segment'
   xml:
      name: segment
```
It seems that problem also can be seen in  [pojo.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache), because _#items.xmlName_ search only inside items swagger-property and not in subobjects.

##### Swagger-codegen version

version 2.4.9

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  title: API segments
  version: 1.0.0
  description: Test segments
schemes:
  - https
basePath: /base/v1
produces:
  - application/xml
consumes:
  - application/xml
paths:
  /segments:
    get:
      summary: Segments
      produces:
        - application/xml
      parameters:
        - name: symbols
          in: query
          required: false
          type: array
          items:
            type: string
        - name: branches
          in: query
          required: false
          type: array
          items:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/segments'
definitions:
  segment:
    type: object
    description: Segment
    xml:
      name: segment
    properties:
      branches:
        type: array
        xml:
          wrapped: true
        items:
          type: string
          xml:
            name: branch
      symbols:
        type: array
        xml:
          wrapped: true
        items:
          type: string
          xml:
            name: symbol
    required:
      - branches
      - symbols
  segments:
    type: object
    description: Segments
    xml:
      name: segments
    properties:
      segments:
        type: array
        xml:
          name: segments
          wrapped: false
        items:
          $ref: '#/definitions/segment'
```
##### Command line used for generation

```xml
<plugin>
               <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.4.9</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/swagger.yaml</inputSpec>
                            <language>spring</language>
                            <output>../spring-server</output>
                            <configOptions>
                                <withXml>true</withXml>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

##### Steps to reproduce

1. Generate spring server stub from the swagger with using swagger-codegen-maven-plugin cofiguration.
2.  Write returning of something like this in controller:
```java
List<Segment> segments = new ArrayList<>();
            segments.add(new Segment().symbols(Arrays.asList(new String("s1"), new String("s2")))
                    .branches(Arrays.asList(new String("b1"), new String("b2"))));
            return new ResponseEntity<>(new Segments().segments(segments), HttpStatus.OK);
```
3. Compile and run stub.
4. Make api call.

**Comment by thiko** [comment]
Same here - @JacksonXmlElementWrapper annotation is missing using maven code gen plugin version 3.0.14.
@MariaPushkin did you find a workaround? We still has this problem and it makes our generation process more or less useless.

Thanks!

**Comment by volvicoasis** [comment]
Same here - @JacksonXmlElementWrapper annotation is missing using maven code gen plugin version 3.0.19.

**Comment by thiko** [comment]
Workaround: We created custom mustache templates in order to override this strange behavior.
Swagger use this template files for its code gen. You can override them all or just partially.

**Comment by volvicoasis** [comment]
Hello, @thiko, can you provide in order to test your mustache template ?

**Comment by sanjeevgiri** [comment]
Is there any open PR for this. I have an updated version of pojo.moustache to fix this.

**Comment by sanjeevgiri** [comment]
@thiko @volvicoasis @MariaPushkin I have a PR for this now. Would you guys be able to help me push this to master? Would be nice if we could get this in place for folks in need (myself included :) )

**Comment by sanjeevgiri** [comment]
Suggestions, and discussions are welcome. I am willing to run and post the patched generator against a swagger spec to verify the fix. I used our internal api spec that is probably not suitable for illustrating the intent of the code since that is quiet big in size.
