### ISSUE TITLE
dart missing from 3.0.14 swagger-codegen-cli

### ISSUE THREAD

**Issue by stuz5000** [swagger-api/swagger-codegen#9878]
Following the instructions here:

 - https://github.com/swagger-api/swagger-codegen#to-generate-a-sample-client-library

and using the latest 3.0.14 release:

```
$ wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.14/swagger-codegen-cli-3.0.14.jar

$ java -jar swagger-codegen-cli-3.0.14.jar generate  \
       -i http://petstore.swagger.io/v2/swagger.json  \
       -l dart  \
       -o ./_swagger 
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name dart Available: aspnetcore
csharp
csharp-dotnet2
go-server
dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
micronaut
spring
nodejs-server
openapi
openapi-yaml
kotlin-client
kotlin-server
php
python
python-flask
scala
scala-akka-http-server
swift3
swift4
typescript-angular
javascript

	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
	at io.swagger.codegen.v3.cli.SwaggerCodegen.main(SwaggerCodegen.java:96)
Caused by: java.lang.ClassNotFoundException: dart
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
	... 1 more
```
Docs say that dart is supported:

 - https://github.com/swagger-api/swagger-codegen#overview

Java version:
```
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by frantuma** [comment]
You're probably wanting to use 2.x versions of swagger-codegen instead of 3.x version, as you're providing a Swagger / OpenAPI 2.0 spec.

Also `dart` is not yet available as generator language for OpenAPI 3.0 specification (supported by the 3.x version you're using in your example.

therefore something like this:
```
wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.10/swagger-codegen-cli-2.4.10.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l dart -o ./_swagger
```

please close ticket is this answers your question

**Comment by stuz5000** [comment]
Which part is not 3.0 compliant? When I paste the full spec to: https://editor.swagger.io/

it reports:
```
This documentation conforms to the OpenAPI 3.0 specification.
        You may use it to generate API classes for any programming language.
        This will work as simple function calls in your programming language 
        and hide the need to build HTTP requests.
```

**Comment by stuz5000** [comment]
Good point. Will test with 3.0 and report back.

**Comment by stuz5000** [comment]
Same results with:
``` 
java -jar swagger-codegen-cli-3.0.14.jar generate \
  -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml  \
  -l dart  \
  -o ./_swagger
````

**Comment by frantuma** [comment]
yes, maybe I wasn't clear in my comment, OpenAPI 3.0 does not provide yet a `dart` generator; this is available instead for Swagger / OpenAPI 2.0 specs, invoked via cli (codege version 2.4.10) as mentioned above

**Comment by stuz5000** [comment]
Should dart work when given a 2.0 spec?

https://github.com/swagger-api/swagger-codegen#overview

... fails for both 2 and 3 spec examples (see above). Is swagger-codegen-cli-3.0.14 not compatible with 2.0 specs?

Also, what the difference between this project and https://github.com/OpenAPITools/openapi-generator ?

**Comment by ThinkDigitalSoftware** [comment]
So the only solution is to do it manually for now? It seems like some advanced regex work would get this done, although I'm not familiar with building generators at all. What needs to be done to get this updated?

**Comment by stuz5000** [comment]
No, but you can do the same with the openapitools/openapi-generator-cli project.

I had a few issues with the generated code, but overall, was close enough.

```
wget http://central.maven.org/maven2/org/openapitools/openapi-generator-cli/4.2.2/openapi-generator-cli-4.2.2.jar -O openapi-generator-cli.jar

export SWAGGER_DEFINITION=swagger.json
export DART_POST_PROCESS_FILE="dartfmt -w"

# Swagger
#java -jar swagger-codegen-cli-3.0.14.jar generate \
# -i $SWAGGER_DEFINITION \
# -l dart \
# -o ./_swagger \
# ... fails

# OpenAPI
java -jar ./openapi-generator-cli.jar generate \
   -i $SWAGGER_DEFINITION \
   -g dart \
   -o ./_swagger \
    -DbrowserClient=false \
# ... success!
```

**Comment by purplesoft-io** [comment]
please add dart support for OAS 3... flutter devs need it!
thanks!

**Comment by LeLunZ** [comment]
Would be nice to get support :D

**Comment by SheenBR** [comment]
I dont understand how this is not available yet.

**Comment by stuz5000** [comment]
I think this project is abandoned. See the OpenAPi generate project. It has
Dart support.

**Comment by HugoMario** [comment]
@stuz5000 
nope, it's no abandoned. Dart and Flutter generators are in progress.

**Comment by csongorkeller** [comment]
when can we expect the dart generator for open API 3?

**Comment by SheenBR** [comment]
i'm using now openapi-generator-cli-4.3.1. Works just fine.
