### ISSUE TITLE
enum type properties can't be generated into models in Java

### ISSUE THREAD

**Issue by comm604** [swagger-api/swagger-codegen#99]
If a property is an enum, the Java generator doesn't create an Enum java file for it.

For example,
<pre>
<code>
"Employee":
       {
           "id": "Employee",
           "description": "An employee",
           "required":
           [
               "name",
               "id"
           ],
           "properties":
           {
               "name":
               {
                   "type": "string",
                   "description": "Name of the employee"
               },
               "id":
               {
                   "type": "string",
                   "description": "Id of the employee"
               },
               "department":
               {
                   "$ref": "Department",
                   "description": "The department that the employee belongs to",
                   "enum":
                   [
                       "SALES",
                       "FINANCE",
                       "ENGINEERING",
                       "MARKETING"
                   ]
               }
           }
       }
</code>
</pre>
With this example model, in addition to Employee.java, shouldn't it also generate a Department.java like the following?
<pre>
<code>
public enum Department {
    SALES, FINANCE, ENGINEERING, MARKETING
}
</code>
</pre>

**Comment by fehguy** [comment]
This feature has been added to the java templates in 2.1.x.  See the `develop_2.0` branch

**Comment by adrobotics** [comment]
I'm having trouble finding the version where this is supposed to be working. The develop_2.0 branch doesn't generate any enum classes for me.

**Comment by nihuyaka** [comment]
Why is this closed? As of 2.1.4 Enums are still generated inside the model which is wrong.

**Comment by fehguy** [comment]
Why?  Because this ticket isn't about having *external* enums, it's about having enums.  Making them inline is not _wrong_ it's a style preference.  I DO want to support external classes, and we're in the process of adding that support.  But that's why it's closed.  There's another one around external enums.

**Comment by nihuyaka** [comment]
Ah, sorry thanks.
