### ISSUE TITLE
isNumeric is not set for int32 integers

### ISSUE THREAD

**Issue by mitchnull** [swagger-api/swagger-codegen#9918]
##### Description

The isNumeric property is false for variables of type 'integer' where format is 'int32'.  It is properly set to true for unspecified format and 'int64' format (Long).

##### Swagger-codegen version

2.4.9, 2.4.10, 2.4.11-SNAPSHOT

##### Swagger declaration file content or url

```yaml
swagger: "2.0"
info:
  version: "1.0.0"
  title: "test"

paths: {}

definitions:
  IntTest:
    type: object
    properties:
      intProp:
        type: integer
      int32Prop:
        type: integer
        format: int32

```

##### Command line used for generation

java -jar ~/src/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.yaml -l java -o /tmp/test -DdebugModels=true > log.txt

##### Steps to reproduce

declare a property with type: integer, format: int32.  check the isNumeric property of the generated model.

##### Suggest a fix/enhancement

add the missing isNumeric property for the IntegerProperty case:
```diff
diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
index f25f429f9..4072b5ca4 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
@@ -1705,6 +1705,7 @@ public class DefaultCodegen {
         if (p instanceof IntegerProperty) {
             IntegerProperty sp = (IntegerProperty) p;
             property.isInteger = true;
+            property.isNumeric = true;
             if (sp.getEnum() != null) {
                 List<Integer> _enum = sp.getEnum();
                 property._enum = new ArrayList<String>();
```
[log.txt](https://github.com/swagger-api/swagger-codegen/files/3932599/log.txt)

**Comment by frantuma** [comment]
fixed in #9920
