### ISSUE TITLE
How to catch errors when using swagger-codegen as a library

### ISSUE THREAD

**Issue by hgwood** [swagger-api/swagger-codegen#993]
I've managed to generate code using `DefaultGenerator`. But `DefaultGenerator#generate` catches all exceptions and prints the stacktrace without rethrowing. This makes it impractical for the caller code to know if the generation was successful or not. `DefaultGenerator` was clearly not intended to be used outside of a CLI case.

How am I supposed to use swagger-codegen as Java library if not through `DefaultGenerator`? Or is it that error management was not tackled yet?

Is that latter case, I'm willing to make a patch. The patch would have to change the `Generator` interface to include a `throws` clause, except if you'd rather have (documented) unchecked exceptions.

**Comment by xhh** [comment]
Agreed that the behavior of hiding exceptions would be confusing.
As in [`DefaultGenerator#generate`](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L50):

```java
public List<File> generate() {
    if (swagger == null || config == null) {
        throw new RuntimeException("missing swagger input or config!");
    }
    /* ... */
    List<File> files = new ArrayList<File>();
    try {
        /* generating code ... */
    } catch (Exception e) {
        e.printStackTrace();
    }
    return files;
}
```

In cases of null swagger/config, RuntimeException would be thrown, while exceptions happening in the process of code generation are hidden (print stack trace and then get ignored).
I think it would be better to throw the exception again after `e.printStackTrace()`, as long as there's no particular reasons not to do it.

**Comment by fehguy** [comment]
This should be handled now, please reopen if not.
