### ISSUE TITLE
Error creating csharp client

### ISSUE THREAD

**Issue by valeriopittavino** [swagger-api/swagger-codegen#9965]
##### Description

I try to create the csharp client by https://editor.swagger.io/ and every time it fails.
I changed something in the code but nothing important.
You can see the swagger page to
https://services.dnsistemi.com/swagger/ui/index
The APIs work fine, the problem is to create the client.
Can somebody help me?

##### Swagger declaration file content or url

https://services.dnsistemi.com/swagger/docs/V1

##### Steps to reproduce

- go to https://editor.swagger.io/
- copy and paste documentation or import the documentation URL
- try to create csharp client
- open the chrome's console and you can see the error (i have to wait about 30 seconds)

Thanks a lot for your help
![Cattura](https://user-images.githubusercontent.com/58744233/71926005-a5827d00-3192-11ea-9646-2c19027f068c.PNG)

**Comment by copperorange** [comment]
Question - did you try to create the client from the swagger-codegen command line client? 

I tried it and it worked

`java -jar swagger-codegen-cli.jar generate -l csharp -i https://services.dnsistemi.com/swagger/docs/V1 --api-package Api.Resources --model-package Models.Resources -DmodelTests=false -DapiTests=false -DpackageName='My.Sdk'`

or replace java -jar swagger-codegen-cli.jar with swagger-codegen if you have it installed locally

It created this

`My.Sdk.sln         README.md          build.bat          build.sh           docs               git_push.sh        mono_nunit_test.sh src`

**Comment by valeriopittavino** [comment]
No I haven't tried.
I solved using NSwaggerStudio and changing the files in my project
