### ISSUE TITLE
Swagger Codegen CLI 2.4.11 do not support OpenApi 3.0.1

### ISSUE THREAD

**Issue by steevegldev** [swagger-api/swagger-codegen#9966]
##### Description

I'm using the docker image swaggerapi/swagger-codegen-cli:2.4.11 to generate a Python package from a swagger.json file. That file is generate by swashbuckle.aspnetcore.cli v5.0.0-rc4 but it's should not matter, it tested valid by swagger validator.

The command is:
`docker run swaggerapi/swagger-codegen-cli:2.4.11 generate -i /app/swagger.json -l python -o /app/packages/swagger`

The error:
`Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:762)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)`

The workaround I found is to change `"openapi": "3.0.1"` to `"swagger": "3.0.1"`

##### Swagger-codegen version

2.4.11

##### Command line used for generation

`docker run --rm -v "app:/app" swaggerapi/swagger-codegen-cli:2.4.11 generate -i /app/swagger.json -l python -o /app/packages/swagger`

`java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar generate -i /app/swagger.json -l pyth
on -c /app/config.json`

##### Steps to reproduce

Generate package from a swagger file with `"openapi": "3.0.1"`

**Comment by scara** [comment]
HI @steevegldev,
AFAIK actual _OpenAPI 3_ support is available only via CLI 3.0.x: your workaround looks like a bug in 2.4.x.

HTH,
Matteo

**Comment by steevegldev** [comment]
I didn't find a docker image for the version 3.

**Comment by scara** [comment]
Hi @steevegldev,
here it is: https://hub.docker.com/r/swaggerapi/swagger-codegen-cli-v3 😉.

BTW you could even use http://central.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.15/swagger-codegen-cli-3.0.15.jar via a Java 8 base image.

HTH,
Matteo

**Comment by steevegldev** [comment]
Perfect thanks!
