### ISSUE TITLE
Java codegen fails to create an Any class for swagger specs with an "any" type

### ISSUE THREAD

**Issue by elibixby** [swagger-api/swagger-codegen#997]
As an example you can run codegen on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json

**Comment by wing328** [comment]
According to [swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types), there's no such as type named "any".

**Comment by elibixby** [comment]
1. It's a 1.2 spec

2. It is an entry in the "type" field of which "any" is a valid value as a String, however, "any" is not created elsewhere in the spec. Additionally, the spec validates against the 1.2 swagger spec

**Comment by wing328** [comment]
@elibixby According to [swagger spec 1.2](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#431-primitives), there's no type named "any" either.

Do you expect "any" to be a class named "Any" without any properties in the generated code?

**Comment by wing328** [comment]
@elibixby I think it's a known issue as documented by the owner of `kubernetes`:

https://github.com/GoogleCloudPlatform/kubernetes/issues/4700

**Comment by elibixby** [comment]
@wing328 Thanks! I missed that issue I guess!

**Comment by wing328** [comment]
@elibixby As a workaround, you can do a find & replace for "any" with "object". I can generate code without exception using this approach.

**Comment by elibixby** [comment]
@wing328 Thanks, yeah I ended up replacing it with Map<String,String> and it seems to work fine.
