### ISSUE TITLE
[ANGULAR] Bug generating typescript-angular client 

### ISSUE THREAD

**Issue by BaptisteCyrill** [swagger-api/swagger-codegen#9971]
##### Description
I created a swagger documentation online (http://editor.swagger.io) and generate a typescript-angular client. In this client I found the following issues:
- Missing quotation marks on http methods
- Missing comma behind body: body

##### Swagger-codegen version
3.0.15 online (http://editor.swagger.io)

##### Swagger declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: Customer Management Service
  version: '1.0'
servers:
  - url: 'http://localhost:8086'
paths:
  '/v1/admin/countries/{key}':
    put:
      tags:
        - customer-mgmt-country-admin-v1
      summary: Updates a country.
      description: ''
      operationId: updateCountry
      parameters:
        - $ref: '#/components/parameters/key'
      requestBody:
        $ref: '#/components/requestBodies/CountryBody'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
components:
  schemas:
    Country:
      type: object
      properties:
        key:
          type: string
          minLength: 2
          maxLength: 2
          pattern: '^[A-Z]{2}$'
          example: DE
          description: A unique object key in ISO 3166-ALPHA-2 format.
      required:
        - key
  parameters:
    key:
      name: key
      in: path
      description: The functional key of the type.
      required: true
      schema:
        type: string
  requestBodies:
    CountryBody:
      description: A JSON object containing the translated country.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Country'
```
##### Steps to reproduce

- Paste the yaml above in editor on http://editor.swagger.io/
- Use menu item 'Generate client | typescript-angular'
- Open the file /api/customerMgmtCountryAdminV1.service.ts in the generated zip-file
- See the errors in line 99 and line 101

**Comment by mold** [comment]
It's been fixed in a PR waiting to get merged https://github.com/swagger-api/swagger-codegen-generators/pull/576

**Comment by cmalard** [comment]
@HugoMario can you help on the merging ? :beers: :vulcan_salute:

**Comment by HugoMario** [comment]
@cmalard , of course!!

**Comment by tsproesser** [comment]
Any news when this will get released / deployed?

**Comment by HugoMario** [comment]
@tsproesser , it will be released this week, probably today

**Comment by HugoMario** [comment]
PR merged, closing now, will release soon. thanks everyone!!
