### ISSUE TITLE
codegen fails on empty 'operationId'

### ISSUE THREAD

**Issue by Amrullha** [swagger-api/swagger-codegen#999]
If we've an empty 'operationId' like e.g.
...
   "get" : {
        "operationId" : "",
        "tags" : ...
the swagger-codegen fails with Ifollowing Exception

java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.substring(Unknown Source)
        at io.swagger.codegen.DefaultCodegen.camelize(DefaultCodegen.java:1285)
        at io.swagger.codegen.languages.JavaClientCodegen.toOperationId(JavaClientCodegen.java:225)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:706)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:351)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:323)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:153)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

because the operationId is just checked against null and DefaultCodeGen further processing will try to camalize the empty string by a 'word.substring(0, 1).toLowerCase() + word.substring(1);'
I'd like to assess it as a bug!?

**Comment by wing328** [comment]
@Amrullha Thanks for reporting the issue. I agree with you that a better exception handling is needed.

The `operationId` is the method name (e.g. getPetById). If it's an empty string, the generated code wont' compile. Of course, we can assign a default value (e.g. unknown_method_name) but other issues may come up, e.g. duplicated method names if there're more than 1 `operationId` with empty string.

If your case, do you mind sharing more with us why the `operationdId` is an empty string and what do you expect the method name to look like in the generated code ?

**Comment by Amrullha** [comment]
@win328: Thanks for picking up this that fast.
I agree not using a default value here for the mentioned reason. 
Empty operationId might be handled as null....
But not only for the reason that another issue will be an operationId with a length of 1
I'd like to recommend to throw an Exception if
1. the operationId is empty (probably never set as empty with intention)
2. the operationId does not have the required min-length

**Comment by wing328** [comment]
@Amrullha thanks for the suggestion. I'll file a PR based on your suggestion this weekend.

**Comment by Amrullha** [comment]
@wing328 Great. Thx. By the way - I forgot to answer your question:
Our operationId was created empty accidentally (by a generator and should not exist at all - so we also created a ticket against it.

**Comment by wing328** [comment]
@Amrullha for generator, are you referring to some 3rd-party Swagger-plugins, e.g. [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle), [swagger-php](https://github.com/zircote/swagger-php) ?

**Comment by Amrullha** [comment]
@wing328 Yes, it's our own product exposing REST services (also providing the swaqgger json)

**Comment by wing328** [comment]
Submitted #1018

**Comment by wing328** [comment]
Submitted PR #1018

**Comment by wing328** [comment]
Merged
